# Den Lätta Metoden
Målet med den här boken är att styra in dig i en ny sinnestämning. Den vanligaste metoden att sluta på börjar med känslan av att bestiga Mount Everest och ägnar sedan följande veckor med svåra begär och känslor av avsaknad. Den här metoden gör raka motsatsen. Du startar direkt med en upplyftande känsla, ungefär som om du blir botad från en hemsk sjukdom.  När du sedan tittar tillbaka på den här tiden, ju längre genom livet du går, så kommer du undra varför du någonsin tittade på porr från första början. Du kommer se på andra användare med medlidande snarare än avund.
Det är viktigt att du fortsätter konsumera porr tills du har läst färdigt hela boken, undantaget om du inte själv är en missbrukare (att du läser för din partners skull), eller redan har slutat (eller har en fastedag under en ”porrdiet”). Det ter sig möjligtvis motsägelsefullt och just den här instruktionen att fortsätta onanera till porr är grunden till mer protester än någon annan, men om du bara fortsätter läsa så kommer din längtan att fortsätta använda porr att kraftigt reduceras. Ta den här instruktionen på största allvar. 
Att försöka sluta för tidigt kommer inte att gagna dig.
Många läser inte färdigt boken då de får känslan att de tvingas ge upp något, medan andra bara läser en rad per dag i ett desperat försök att skjuta upp den annalkande skräckupplevelsen. Se på det så här: Vad har du att förlora? 
Skulle du inte ha slutat med porr när du har läst ut boken så har din situation inte blivit värre än vad den är nu. Det är per definition en Pascals Vadslagning, alltså ett accepterat vad där du inte har någonting att förlora men besitter stora chanser att bli rikligt belönad.
Om du händelsevis inte har tittat på porr på några dagar eller rentav veckor, men samtidigt inte är riktigt säker på om du är en användare, ex-användare eller icke-användare, fortsätt i så fall din avhållsamhet under läsningen. Då är du redan är en icke-användare, men vi måste låta hjärnan hinna ikapp med kroppen. I slutet av boken så kommer du att vara en lycklig icke-användare. 
EasyPeasy är motsatsen till den vanliga metoden där någon listar alla nackdelar som följer porren och säger:
”Om du bara gåt tillräckligt länge utan porr så kommer begären att försvinna och du kan återigen njuta av livet, befriad av slaveriet.”
Det är det logiska tillvägagångssättet som tusentals personer använder varje dag för att sluta. Det är dock väldigt svårt att lyckas på det här sättet på grund av följande anledningar:

** Att sluta med PMO (porr, masturbation, orgasm) är inte det egentliga problemet.**
Varje gång du avslutar en sittning så slutar du med porr. Du har säkerligen viktiga skäl till att säga på första dagen av din porr-diet: ”Jag vill inte använda porr, eller ens onanera, längre.” Det gör alla användare och deras skäl är mer kraftfulla än vad du kan föreställa dig. Det stora problemet är när du på dag två, tio eller tiotusen i ett svagt ögonblick bara måste ”ta en snabbtitt”. Sedan vill ta ännu en titt och plötsligt är du en missbrukare igen.

** Att känna till hälsoriskerna föder mer rädsla vilket gör det ännu svårare att sluta.**
Om du berättar för en användare att porr sabbar potensen så sträcker de sig efter något dopaminflödande hjälpmedel; en cigg, någon alkoholhaltig dryck, eller så kickar de igång webbläsaren och börjar söka efter porr.
** Alla skäl som finns att sluta gör det svårare att faktiskt sluta.**
Det finns två anledningar till det. Först så tvingas vi hela tiden ge upp vår ”lilla kompis”, pryl, anordning eller njutning (vad användaren än väljer att kalla det). För det andra så skapar man skygglappar. Vi onanerar inte på grund av anledningarna vi har att sluta. Frågan är: varför vill vi onanera, eller varför måste vi göra det?
Med EasyPeasy så glömmer vi (till en början) andledningarna till att vi vill sluta, bemöter problemen med porren och frågar oss själva följande frågor:

1.  Vad gör porren för mig?

2.  Uppskattar jag det verkligen?
3.  Behöver jag verkligen gå genom livet och sabotera hjärnan och kroppen?
Den vackra sanningen är porren absolut inte gör någonting för dig överhuvudtaget. Jag ska vara väldigt tydlig. Det är inte så att porrens nackdelar väger upp för fördelarna. Det är så att det finns NOLL fördelar med att titta på pornografi.
De flesta finner det nödvändigt att rationalisera sitt porranvändande, men alla anledningar de använder är vanföreställningar och villfarelser.
Vi ska börja med att avlägsna dessa vanföreställningar och villfarelser. Då kommer du inse att det inte finns någonting att ge upp. Sedan ska vi utforska alla fantastiska och positiva vinster som man får när man är en icke-PMO:are. Välmående och lycka är endast två av dessa vinster. Vi ska döda villfarelsen att livet aldrig mer kommer vara lika härligt utan porr (och du inser att livet är oändligt mycket härligare) och radera känslan av att gå miste om något när man slutar med porr.  Sedan går vi tillbaka och återupplever ökat välbefinnande och lycka och alla dussintals ytterligare goda anledningar till att sluta med porr. Dessa insikter kommer bli positiva hjälpmedel i din strävan att uppnå det du egentligen önskar – att njuta av livet befriad från porrberoendets slaveri.

