# Varför Är Det Svårt Att Sluta?

Alla vi porranvändare känner sig besatta av någonting ondskefullt. I början av användandet sa man bara: *"”jag ska sluta, bara inte idag”"*. Sedan utvecklas vi till att tro att vi saknar viljestyrka att sluta eller att det finns någonting inneboende i porren som vi måste ha för att kunna njuta av livet.

Att vara porrmissbrukare är som att kravla sig ut ur en hal grop: Allt eftersom vi närmar oss toppen och ser solen skina, så halkar vi snart tillbaka ner i gropen när vi dippar i humöret. När vi sedan öppnar webbläsaren och onanerar så mår vi skit under tiden.

Fråga en användare: *" Om du kunde gå tillbaka till tiden innan du blev fast, med vetskapen du har idag, skulle du då ha börjat titta på porr?"*

*"ALDRIG I LIVET!"* skulle svaret bli.

Fråga en användare som försvarar internetporr och inte tror att det skadar hjärnan eller nedreglerar dopaminreceptorerna: *" Uppmuntrar du dina barn att använda porr?"*

*" ALDRIG I LIVET!"* blir svaret återigen.

Porr är en utomordentlig gåta. Som tidigare sagts, problemet är inte att förklara varför det är enkelt att sluta, utan att förklara varför det är svårt. Det riktiga problemet är att logiskt förklara varför någon överhuvudtaget tittar efter alla insikter om de neurologiska skador som porren orsakar. 
En del av anledningen till att vi börjar är på grund av de tiotals miljoner som redan tittar på porr, samtidigt som de önskar att de aldrig börjat från början och vittnar om hur det känns som att de lever livet på tvåans växel. Vi har svårt att tro på att de inte uppskattar porr eftersom vi associerar det till frihet. Vi upptäcker sex och jobbar sedan hårt på att själva bli fast. Efter det ägnar vi en stor del av livet åt att vädja till andra att undvika porr, eller sluta med ovanan, medan vi tror att vi är unika på det sättet.
Vi tillbringar också en betydande del av vår tid åt att känna oss hopplösa och förtvivlade. När vi ”utbildar” oss med det supernormala gör det så att vi föredrar och längtar efter de här kalla bilderna, även när den varma, äkta varan finns tillgänglig. Genom de konstanta topparna och dalarna som PMO orsakar så dömer vi oss själva till en livstid av isolation, lättretlighet, ilska, stress, utmatting och sexuella problem. Genom att använda porr, som utelämnar de bästa bitarna av sex och anknytning, så mår vi piss och känner stor skuld.
Att läsa om internetporrens beroendeframkallande och destruktiva natur här och på andra sajter gör oss än mer nervösa och hopplösa. Vad är det för typ av hobby som när du utför den så önskar du att du inte gjorde det och när du inte utför den så har du starka begär för den? Användare föraktar sig själva varje gång de läser om hypofrontalitet och desensibilisering, varje gång de tittar bakom ryggen på sin tillitsfulla partner, och varje gång de inte orkar träna efter en dagtidssittning. En annars intelligent och rationellt tänkande person tillbringar sina dagar i självförakt. Men värst av allt, vad får användare ut av att de uthärdar livet med dessa svarta skuggor konstant i bakhuvudet? 

** Absolut ingenting!**

Du tänker kanske: *" Det är ju bra och jag vet det här, men när du väl är fast i de här sakerna så är det väldigt svårt att sluta."* Men varför är det så svårt? En del vill hävda att det är på grund av de svåra abstinensbesvären, men som du snart kommer att få veta så är de faktiska abstinensbesvären ytterst milda. Vilket blir tydligt när man betänker att många PMO:are har levt och dött utan att inse att de var missbrukare.
En del säger att internetporr är gratis och att mänskligheten borde omfamna den här biologiska guldgruvan, men det är dock inte sant. Internetporr är beroendeframkallande och fungerar precis som alla andra droger. Fråga en användare som svär sig till att endast gilla ”erotik” som Playboy-tidningar om de någonsin har korsat gränsen till ”farlig porr”. Är de då ärliga mot dig så erkänner de alla gånger som de korsat gränsen hellre än att inte använda någonting alls.
Uppskattning har heller ingenting med saken att göra. Jag uppskattar kräftor, men det har aldrig gått så långt att jag måsta äta kräftor varje dag. Precis som andra saker vi uppskattar under tiden vi gör eller utför dem, men aldrig känner oss berövade från när vi inte gör det.

Vissa säger:  
*" Det är utbildande!"* Hur har det då fått dig att växa som person?
*" Det är sexuellt tillfredställande!"* Varför isolerar det dig då och ger dig omättliga begär?
*" Det känns frisläppande!"* Frisläppt från det riktiga livets all stress? I en timme, kanske, innan allt kraschar över dig igen? Och vilken stress har den löst?
*"Det hjälper mig sova"* Varför kan då andra sova bra utan det? Det finns [många](https://www.sleepfoundation.org/insomnia/treatment/meditation) vetenskapliga [metoder](https://www.sleepfoundation.org/insomnia/treatment/cognitive-behavioral-therapy-insomnia) för att [fixa](https://www.amazon.com/Uvex-Blocking-Computer-SCT-Orange-S1933X/dp/B000USRG90) till sömnen, och [mer därtill](https://www.menshealth.com.au/what-is-the-military-method-the-technique-that-promises-to-help-you-sleep-in-2-minutes).

Många tror att porr avhjälper tristess, men tristess är en sinnesstämning. Porr vänjer dig blixtsnabbt vid nyhetssökande vilket gör dig allt mer uttråkad tills du hemfaller till att delta i den vilda jakten på rätt videoklipp. Det gör dig i sin tur mer programmerad att söka allt som framkallar nyhetens behag, starka känslor och till slut överdrivet chockvärde. 
En del säger att de bara tittar för att deras vänner och alla de känner också gör det. Om så är fallet för dig så kan du bara hoppas att dina vänner inte börjar hugga av sina huvuden för att lindra sin huvudvärk! De flesta användare som funderar lite kommer till slutsatsen att det bara är en ful ovana. Det är ingen riktig förklaring, men efter att man förkastat alla vanliga, rimliga förklaringar så verkar det vara den enda kvarvarande ursäkten. Tyvärr så är den precis lika ologisk. Vi byter vanor varje dag, av vilka en del är väldigt njutningsfulla. Vi har blivit hjärntvättade till att tro att PMO är en vana och att vanor är svåra att bryta.
Men är vanor svåra att bryta? Bilförare i USA är vana att köra på höger sida av vägen, men när de reser utomlands så bryter de den vanan nästan helt smärtfritt. Och när du byter jobb så underkastar du dig nya rutiner och ändrar därför dina vanor. Det kanske tar ett tag att vänja sig, men inte i närheten som av den livslånga kampen mot porrmissbruk. Vi skapar och bryter vanor varje dag. Så varför är det då så svårt att bryta en vana som gör att vi känner oss berövade när vi inte har tillgång till det och skuld när vi gör det, när det enda vi behöver göra är att *sluta göra det?*

Svaret är därför att porr inte är en vana, *det är ett missbruk!* Därför verkar det så svårt att släppa taget om det. De flesta användare förstår sig inte på missbruk och tror att de får genuin njutning av porr, eller att den fungerar som en krycka. De är övertygade om att det vore en genuin uppoffring att sluta med porr.
Den vackra sanningen är att när du väl förstår porrmissbrukets sanna natur och de bakomliggande anledningarna till att du använder porr så kommer du att sluta, bara så där. Inom tre veckor så kommer det enda mysteriet ligga i vad du fann för skäl till att använda porr så länge som du har gjort och varför du har så svårt att övertyga andra användare * hur ljuvligt det är att inte vara en PMO:are!*

## Den Lömska Fällan

Internetporr är en subtil och lömsk fälla som människan och naturen har jobbat tillsammans för att konstruera. En del av oss blir varnade för farorna samtidigt som vi inte förstår hur vi inte kan riktigt uppskatta det. Men vad är det som drar in oss i det? Vanligast är det gratisklipp som amatörer och proffs delar med sig av. Det är så fällan smäller igen. Om den istället hade varnat oss för vilken sorts faror vi är på väg in i innan man ens tar första titten, så skulle varningsklockor ha börjat tjuta.
Men inga klockor tjuter. Kanske är det chocken från videoklippen som försärkrar våra unga sinnen att vi aldrig kommer fastna, att eftersom vi inte uppskattar det så kommer vi kunna sluta när helst vi vill. Eller så triggas inte varningsklockorna av den skenbara oskuldsfullheten, precis som en lurendrejares skickliga väv av lögner kan styra våra tankar. Som intelligenta människor borde vi förstå hur hälften av den vuxna befolkningen är systematiskt beroende av något som reducerar vår förmåga att utföra precis det vi tittar på. Nyfikenheten tar oss allt närmare missbrukets tröskel, men vi vågar inte klicka på de thumbnails som vi sneglar på, vettskrämda att de ska skada oss eller skicka iväg oss på en högst riskfylld och sedeslös stig. Och råkar vi klicka på en så önskar man oftast ta sig från sajten snabbast möjligt samtidigt som man blir desperat nyfiken på mer.
När väl processen har börjat så är vi fångade i fällan. Från och med nu så ägnar vi resten av våra liv till att förstå varför vi gör det, vi säger åt våra barn att inte börja med det och ibland försöker vi själva slita oss loss. Fällan är designad på så sätt att vi försöker sluta enbart på grund av en incident, om det så är sexuell prestation, en förlorad karriär eller förhållande, brist på motivation eller bara genom att känna sig som en spetälsk. Så fort vi slutar känner vi än mer stress på grund av abstinensbesvär samtidigt som metoden vi brukade använda för att ta bort den stressen nu är otillgänglig.
Vårt beslut att sluta verkar nu vara en dålig idé. Efter några dagars tortyr övertygar vi oss själva att vi har valt att sluta vid fel tidpunkt och beslutar oss därför för att vänta in en period med mindre stress. Bara det att när dylik period dyker upp så försvinner också vår initiala anledning till att sluta. En sådan period kommer såklart heller aldrig att komma fullt ut och då börjar vi tro att våra liv blir allt mer stressiga. Vi lämnar tryggheten från våra föräldrar och stressen från jobbet, att ta hand om hemmet, huslån, barnuppfostran börjar ta upp all plats i våra liv. Men det är bara en illusion. Den mest stressiga perioden i alla varelsers liv är i barndomen och under ungdomsåren.
Vi tenderar ofta att blanda ihop ansvarstagande med stress. En användares liv – precis som en drogmissbrukares – blir per automatik mer stressigt eftersom vi inte blir avslappnade eller mindre stressade av att titta på porr, oavsett vad vissa vill få oss att tro. Sanningen är det rakt motsatta då stressen istället ökar när vi fortsätter använda porr och där efterdyningarna av alla skuldtyngda nätter staplar strå efter strå på kamelens rygg. Användare som gör sig av med vanan – som de flesta gör minst en gång i livet – kan leva lyckliga liv, men fastnar ändå snart i fällan igen. När man irrar in i porrlabyrinten blir våra sinnen helt dunkla och vi ägnar resten av våra liv till att försöka fly. Många lyckas bara för att ramla i den ondskefulla fällan senare igen.

Att lösa problemet med sitt porrmissbruk är en gåta. Det är komplicerat och krångligt, men när du väl har sett svaret och inser hur enkelt och roligt det är så undrar du varför du aldrig tänkt på det tidigare. EasyPeasy innehåller lösningen på problemet och leder dig ut ur labyrinten utan att du irrar tillbaka in i den. ** Det enda du behöver göra är att följa varje instruktion till punkt och pricka.**. Hamnar du däremot **snett och börjar hoppa över kapitel** eller **börjar läsa boken med blixtens hastighet** utan att göra ett ärligt försök vid första läsningen, då är resten av instruktionerna helt meningslösa.

Det kan vara enkelt för alla att sluta, men vi måste först etablera fakta. Nej, inte typen av fakta som skrämmer dig, det finns det redan nog av därute. Om det var allt som krävdes så hade du slutat för längesen. Men varför är det så svårt för oss att sluta? För att kunna svara på det behöver vi veta den verkliga anledningen till varför vi fortfarande använder porr, vilket kokar ner till två aspekter. De är:

-   Naturen och internetporr.

-   Samhällets hjärntvätt.

Porranvändare är intelligenta, rationella människor. De vet med sig att de tar enorma risker vilket gör att de ägnar mycket tid åt rationalisera sin ”vana”. Men porranvändare vet i sina hjärtan att de är dårar för att de vet att de aldrig behövde använda porr innan de blev fast. De flesta minns sina första ”snabbtittar” som en blandning av nyfikenhet av det okända och avsmak. Efter de specialiserar de sig i att hitta, filtrera och bokmärka sajter och jobbar stenhårt på att fastna i det.
Det mest störande är att det finns en känsla av att icke-missbrukare – mest kvinnor, äldre män och folk som bor i länder utan höghastighetsinternet – inte går miste om särskilt mycket och finner situationen skrattretande. Genom att plocka isär dessa faktorer i de kommande kapitlen så kommer du också att förstå hur den ondskefulla fällan fungerar!

