# Vad Ger Jag Upp?
**Absolut ingenting!** Det är svårt att ge upp porr på grund av rädslan att vi blir berövade vår källa till njutning eller vårt stöd. Rädslan att vissa njutbara situationer aldrig riktigt kommer att bli desamma igen. Rädsla att du kommer att vara oförmögen att hantera uppstressande situationer. Med andra ord så är det hjärntvättens effekter som lurar os att sex – och i förlängningen orgasm – är ett absolut måste för alla människor. Vidare så är det tron att det finns någonting inneboende i porr som vi behöver och att vi när vi slutar kommer att förvägra oss själva och skapa ett hålrum.
Gör detta tydligt i ditt huvud: **Porren fyller inte ett tomrum,** ***den skapar ett!***
Våra kroppar är de mest sofistikerade objekten på planeten. Oavsett om du tror på intelligent design, naturligt urval, eller en kombination av båda, så är våra kroppar tusen gånger mer effektiva än människan! Vi kan inte skapa den minsta levande cellen, synens eller fortplantningens mirakel eller olika sammankopplade system som finns i kroppen och hjärnan. Om skaparen eller processen hade för avsikt att vi skulle kunna hantera supernormal stimulering så hade vi varit utrustade med andra belöningssystem. Våra kroppar är försedd med kassaskåpssäkra varningssystem vilka vi ignorerar på egen risk.

## Det Finns Ingenting Att Ge Upp
När du väl har sparkat det lilla monstret ut ur kroppen och hjärntvätten (det stora monstret) från huvudet så kommer du varken vilja onanaera regelbundet eller använda internetporr för att göra det. Det finns mycket outforskad mark vad gäller porrmissbruk och de flesta inom sjukvården saknar helt metoder för att fastställa, eller ens undersöka, någon som porrberoende. Många av symptomen flaggas felaktigt som orsakade av andra anledningar. Användare är generellt sett inga korkade människor, de är bara väldigt olyckliga utan porr. De sitter fast mellan djävulen och det djupa havet, bedrövade i avhållsamheten eftersom de inte kan titta på porr. Eller plågade av skuldkänslor som de börjar förakta dem själva för. När de får symptom som smärta i ländryggen eller sexuell dysfunktion så slits de mellan att acceptera ansvaret och titta åt ett annat håll.
En till rökarliknelse. Vi har alla sett rökare som hittar på ursäkter för att smyga iväg och dra några bloss, det är tvättäkta missbruk i arbete. Missbrukare gör det inte för njutningen, utan för att de mår uselt utan det.
För många slutade deras första sexuella upplevelse med en orgasm och tillskansade sig således uppfattningen att det inte går att njuta av sex utan en. Porr marknadsförs mot men som ett hjälpmedel för sex, ibland till och med som utbildning i hur man är självsäker under själva akten. Det här är rent nonsens. Det enda som supernormal stimulans kan åstadkomma är att göra sex sämre för dig.
Inte bara finns det ingenting att ge upp, du får en massa positiva vinster. När användare överväger att sluta så brukar de fokusera på sin hälsa och sin virilitet. Båda är helt rimliga och viktiga anledningar, men personligen tycker jag att de största vinsterna är mentala:

-   Du får tillbaka ditt självförtroende och ditt mod
-   Frihet från slaveri
-   Inga fler mörka skuggor längst bak i huvudet och inget mer självförakt

## 7.2 Hålrum, Hålrum O Du Vackra Hålrum!
Tänk dig att du har fått ett munsår och går till en farmaceut som ger dig en salva som du ska prova. Du stryker på salvan och munsåret försvinner med en gång. En vecka senare kommer det dock tillbaka, så du går till farmaceuten och frågar efter mer salva. Farmaceuten säger: *”Absolut. Behåll tuben, du kanske behöver den igen.”*
Du stryker på salvan och simsalabim, såret försvinner igen. Men varje gång som såret kommer tillbaka blir det större och mer smärtsamt och det blir allt kortare mellan gångerna. Snart täcker munsåret hela ansiktet och smärtan är outhärdlig och kommer tillbaka varje halvtimme. Salvan tar bort såret tillfälligt, men du är väldigt orolig. Kommer såret spridas så att det täcker hela kroppen? Kommer mellanperioderna försvinna helt? Du går till läkaren och de kan inte bota det, så du testar andra behandlingar, men ingenting utom salvan hjälper.
Vid det här laget är du helt beroende av salvan och går aldrig ut utan att ha en tub med dig. Reser du utomlands tar du med dig flera tuber. I tillägg till oron kring din hälsa så tar farmaceuten hundra dollar per tub och du har inget annat val än att pynta.
Du snubblar över en artikel som handlar om det här och det här händer inte bara dig, utan det är många som lider av samma problem. Sjukvården har upptäckt att salvan inte botar såret, utan drar bara ner det under ytan. Det är salvan som gör så att såret växer. Så allt du behöver göra för att bli av med såret är att sluta använda salvan så kommer det så småningom att försvinna.
Skulle du fortsätta använda salvan? Skulle det krävas viljestyrka för att sluta använda den? Även om du inte skulle tro på artikeln så hade du säkert tvekat i några dagar, men när du sedan insett att såret började bli bättre skulle behovet av salvan försvinna. Skulle du bli olycklig? Självklart inte. Du hade ett förfärligt problem som du trodde var obotlig men nu hittat lösningen. Även om det tog ett år för såret att försvinna helt så skulle du må underbart för varje dag som det blev bättre. 
Det här är magin av att sluta med porr.
Såret är inte smärtan i kroppen, bristen på sexlust, den avtagande upphetsningen, de mjukare erektionerna, tidsslösandet på tvådimensionella bilder, känslan av att inte förtjäna saker, föraktandet av personerna som kommit på dig, eller värst av allt, föraktandet av dig själv. Allt det här händer tillsammans med såret.
Såret stänger av hjärnan mot de här sakerna och paniken som uppstår är känslan av att behöva en sil. Icke-användare känner inte den känslan. Det som vi lider av värst är rädslan och den största vinsten är att man blir av med den. Rädslan uppstår redan vid första sessionen och förstärks sedan vid varje efterföljande tillfälle.
En del användare är ”lyckliga”, helt förblindade av det manipulerande lilla monstret och går genom samma mardröm medan de hittar på löjliga argument för att försöka rättfärdiga sin dumhet.
*Det är så härligt att vara fri!*
