# Spara tid
När användare försöker sluta är anledningarna vanligtvis hälsan, religion eller stigmatisering av ens partner. En del av denna hemska drogs hjärntvättning är hur förslavande den är. Människan har kämpat för att utrota slaveriet i många delar av världen, ändå lever användaren under detta självvalda slaveri. Helt förblindade mot det faktum att de när de använder porr önskar att de var en icke-användare. Den enda gången som porr blir dyrbart för oss är när vi försöker skära ner eller avstå, eller om när vi tvingas till avhållsamhet.
Det kan inte upprepas ofta nog att det är hjärntvätten som gör det svårt att sluta med porr. Ju mer du tvekar kring porren innan du försöker sluta, desto lättare är det för dig att nå målet. Bekräftade användare som inte tror att porr är skadligt för hälsan (porrinducerad erektionsproblem, hypofrontalitet, etc.) och som inte har den mentala dragkampen är oftast yngre personer eller singlar med tillfälliga partners. Därför går den interna återkopplingen förlorad på grund av deras ungdomliga natur eller för att det sker för sällan för att synas och tas in.
Ett bättre argument för en yngre användare kan vara tiden och istället säga: ”*Jag förstår inte hur du inte kan vara mer oroad för tiden du slösar.*” De känner sig attackerade om man nämner hälsoskäl eller sociala stigman, men pratar man om tid så skiner de ofta upp. 
”*Äh, det har jag råd med. Det är bara x timmar i veckan och det tycker jag att det är värt. Det är min enda källa till njutning.*”
”*Jag kan fortfarande inte förstå att du inte oroar dig mer. Anta att du ägnar i snitt en halvtimme om dagen, som inkluderar det fysiska dräneringen av dopaminabstinens, då tillbringar du en full arbetsdag var fjortonde dag. Du håller säkert med om att en halvtimme om dagen är en väldigt försiktig uppskattning. Har du tänkt på hur mycket tid du slösar under en livstid? Vad gör du med den tiden? Utvecklar riktiga relationer? Nej, din favoritporrstjärna bryr sig inte om dig bara för att du har slösat tid på att se hennes videor. Du slösar en massa tid! Inte nog med det, du använder tiden till att ödelägga din hälsa, förstöra dina nerver och ditt självförtroende bara för att lida en livstid av förslavning, smärta, melankoli och irritation. Det måste väl ändå oroa dig?*”
Det är uppenbart, speciellt med yngre användare, att de aldrig har sett det som ett beroende för livet. Ibland räknar de ut hur mycket tid de slösar på en vecka och det är alarmerande nog. Mer sällan, och enbart när de funderar på att sluta, funderar de på hur mycket de slösar på ett år vilket är skrämmande. Men om man räknar på en livstid så är det helt ogreppbart. Hursomhelst, eftersom vi är inne i en diskussion säger användaren impulsivt, ”Jag har råd, det är bara så mycket under en vecka”, och drar sedan en försäljarharang mot sig själva.
Skulle du tacka nej till ett jobb med samma årslön som du har nu och som också ger dig en månads ledighet om året? Alla användare skulle tacka ja utan att blinka och börja googla exotiska semesterresmål. Att komma på hur man ska spendera en månad utan jobb hade varit det största problemet. I samma diskussion med en användare (alltså någon som inte har planer att sluta) fast med porr, så är det ingen som har tagit erbjudandet. Hur kommer det sig?
Vid det här laget brukar en användare säga: ”*Jag är inte riktigt orolig över pengarna.*” Om du tänker i de här banorna fråga dig själv varför du inte är orolig. Hur kommer det sig att du anstränger dig hårt för att spara några kronor här och där, men sedan slösar tusentals på att döda din lycka och strunta i kostnaden?
Alla andra beslut du tar i livet är resultatet av ett noga övervägande av för- och nackdelar tills man kommer till en rationell slutsats. Det visar sig kanske vara ett felbeslut, men det är ett resultat av rationell slutledningsförmåga. När en använder väger för- mot nackdelarna av internetporr blir svaret övervägande ofta: **”SLUTA ANVÄNDA PORR! DU ÄR EN IDIOT!”** Användare använder av den anledningen inte porr för att de vill eller bestämmer sig för det, utan för att de inte kan sluta. De ***måste*** använda porr och hjärntvättar därmed sig själva och fortsätter stå med huvudet i sanden.
Bekräftade användare bör tänka på att situationen bara kommer att bli exponentiellt värre med fler studier och folk som pratar om internetporrens skadliga effekter. Idag är det icke-medicinskt folk som pratar om effekterna, imorgon kommer de finnas på din läkares lista över diagnostiska tester. Då kan du inte längre skylla på tillfälliga problem i sexlivet på jobbrelaterad stress och din partner kommer att fråga varför du använder din laptop så sent på nätterna. Den stackars användaren som redan känner sig hopplös, vill nu att marken ska öppna sig och svälja honom hel.
Det konstiga är att många gärna betalar duktigt för gymmedlemskap och personligatränare för att bygga muskler och se tonad ut, flera som i deras upplevda (och verkliga) desperation vänder sig till behandlingar som ska boosta testosteronet med farliga biverkningar. Samtidigt skulle många i den här gruppen dra fördel av att sluta med en aktivitet som systematiskt trasar sönder hjärnans naturliga avkopplingssystem.
Det är för att de fortfarande har användarens hjärntvättade tankesätt. Gnugga bort sanden ur ögonen en stund. Internetporr är en kedjereaktion och en livskedja och om du inte knäcker den kedjan så kommer du fortsätta vara en användare för resten av livet. Gör en uppskattning hur mycket tid du kommer att lägga på porr för resten av din existens, det varierar från person till person såklart, men vi säger att det är ett och ett halvt år i rena arbetstimmar. Föreställ dig att en check med ett och ett halvt år av din nuvarande lön som låg på golvet imorgon. Du skulle brista ut i en lyckodans, så det är bara att börja dansa! För du ska snart få uppleva sådana fördelar.
Om det är svårt för dig att tänka såhär, så ljuger du för dig själv. Räkna ut hur mycket tid du hade sparat om du aldrig hade tagit den där titten från början.
Snart kommer du besluta dig för att ha din sista session (inte än, kom ihåg instruktionerna!) och sedan förbli icke-användare genom att inte fastna i fällan igen. Det enda du behöver göra för att vara en icke-användare är att sluta titta på porr och undvika ”bara en titt”-tänket. Kom ihåg att om du gör det, så kommer det kosta dig din uppskattade löneökning.
Om du agerar mentor åt någon med porrberoende, berätta för dem att de känner någon som tackade nej till ett jobberbjudande som betalar samma lön och som också ger dem en månads ledighet. När de frågar vem idioten är så svarar du: ***”Du!”*** Det är lite elakt, men ibland måste man driva genom sin poäng på mindre trevligt sätt.
