# Hälsan
Inom det här området är hjärntvätten som alla starkast hos användarna, speciellt hos de unga singlarna. De som tror att de känner till hälsoriskerna, men inte gör det. Många lurar sig själva genom att hävda att de är beredda att acceptera konsekvenserna. Om din router hade haft en funktion som utlöste en larmsignal när du gick in på en porrsida och varnade: ”Hittills har du kommit undan, men om du är kvar bara för en minut så kommer ditt huvud att explodera.” Hade du stannat kvar på sidan? Om du tvekar över svaret, så prova att gå upp till en klippkant med stängda ögon och tänk att du har valet att antingen tvingas sluta med porr eller att tvingas gå mot klippkanten med förbundna ögon. 
Det är ingen tvekan om vad du hade valt, men genom att gömma huvudet i sanden och hoppas på att vakna en morgon och inte vilja titta på porr längre så kommer du inte att åstadkomma någonting. Användare kan inte tillåta sig själva att tänka på hälsoriskerna, för om de gör det så försvinner missbrukets skenbara njutning. Detta förklarar varför elchocksbehandlingar är så ineffektiva i de första stadierna av att sluta. Det är bara icke-användare som dristar sig till att läsa på om de destruktiva förändringarna i hjärnan.
Det här är ett vanligt samtal med i regel yngre användare:
> **Jag:** "Varför vill du sluta?"
>
> **Användare:** "*Jag läste en raggningsexperts blogg som sa att det är bra att sluta i fyra dagar för att förstärka sig själv.*"
>
> **Jag:** "Oroar du dig inte för hälsoriskerna?"
>
> **Användare:** "*Nej, jag skulle kunna bli överkörd av en buss i morgon.*"
>
> **Jag:** "Skulle du avsiktligen bli överkörd?"
>
> **Användare:** "*Självfallet inte.*"  
>
> **Jag:** "Ser du dig inte för innan du korsar gatan?"
>
> **Användare:** "*Det klart att jag gör.*"

Precis. De gör mycket besvär för att inte bli överkörda och oddsen är flera tusen mot en att det ska inträffa. Men ändå riskerar användaren att bli närmast förlamad av missbruket, utan att ha en aning. Hjärntvättens makt är så stark. Internetporr är en ulv i fårakläder. Är det inte bra märkligt att om det finns minsta fel i ett flygplan skulle vi aldrig gå upp i det - även om riskerna är miljontals gånger större än en - men med porr tar vi en risk på en av fyra och är till synes omedvetna om det? Vad får användaren ut av det? **Absolut ingenting!**
En annan vanlig myt är depression, eller lättretlighet. Många yngre människor oroar sig inte för hälsan eftersom de inte lider av depression eller håglöshet. Depression eller stress är ingen sjukdom utan ett symptom. Yngre människor i allmänhet känner inte till den irritation eller depression som skapas på grund av kroppens naturliga förmåga att producera mer dopamin. Under livets gång, eller när man drabbas av allvarliga motgångar överbelastas deras redan uttömda resurser och de får fullskaliga symptom. När äldre användare känner sig stressade, deprimerade eller irriterade beror det på att kroppens naturliga mekanismer skyddar nervsystemet från överflödande dopamin genom att skära ner antalet receptorer. Användaren genomgår också andra neurologiska förändringar som håller kvar dem i rutinen.
Se det så här: Det vore ganska korkat om du hade en fin bil och lät den rosta utan du gjorde något åt det. Snart stod du med en värdelös rosthög som inte kunde transportera dig någonstans, men det vore kanske inte hela världen eftersom det trots allt bara är en fråga om pengar. Din kropp däremot är det fordon som tar dig genom livet. Det sägs att hälsan är vår största tillgång, fråga vilken sjuk miljonär som helst. De flesta av oss kan se tillbaka på en sjukdom eller olycka i våra liv där vi bönade och bad om att få bli friska. Som porranvändare låter du inte bara rosten obehindrat komma in, du förstör också systematiskt det enda fordon som du använder genom hela livet.
Var smartare. Du behöver inte använda porr, det ger dig ingenting om du kommer ihåg. Ta bara för ett ögonblick upp huvudet ur sanden och fråga dig själv: Om du visste att nästa porrsittning garanterat satte igång en process som gjorde dig helt avtrubbad inför någon som du älskar djupt, skulle du då fortsätta ändå? De människor som drabbas förväntar sig säkerligen inte att det ska hända dem, och det värsta är inte sjukdomen i sig, utan vetskapen om att det är självförvållat. Föreställd dig hur de som har "tryckt på knappen" känner, för dem är hjärntvätten avslutad. De kommer att tänka under resten av sina liv: "Hur kunde jag lura mig själv så länge att jag var tvungen att onanera till internetporr? Om jag bara hade fått chansen att gå tillbaka!"
Sluta lura dig själv! Du har chansen att gå tillbaka. Det hela är en kedjereaktion. Om du har en porrsession så kommer den att leda dig till nästa och sedan till nästa och nästa. Du är redan mitt uppe i den. EasyPeasy lovar ingen chockbehandling, så om du redan har bestämt dig för att sluta så kommer följande inte att vara chockerande för dig. Om du inte har bestämt dig så hoppa över resten av kapitlet och återkom sedan till det när du har läst resten av boken.
Det har redan skrivits mängder av forskning om hur internetporr skadar vårt sexliv och mentala välbefinnande. Problemet är att man inte vill veta det innan man bestämmer sig för att sluta. Olika forum och mentorgrupper är slöseri med tid eftersom porren sätter skygglapparna på. Om användare råkar läsa så öppnar de sin favoritporrsida det första de gör. Porranvändare tenderar att se på lycka, stress och ett hälsosamt sexliv som något som råkar hända en, lite som att trampa på en landmina.
Få in det i huvudet nu, det håller redan på. ***Varenda gång*** du öppnar din porrsida triggar du dopaminflöden och opioiderna börjar jobba. De neurala vattenrutschkanorna är färdigsmorda och åkturen tar dig smidigt genom nästa steg, eftersom din hjärna redan har gett efter för det förskrivna manuset. Nervsystemet översvämmas nu av dopamin och eftersom det är den femtielfte gången stängs dopaminreceptorer av vilket gör att du njuter mindre än föra gången. Det lilla monstret använder denna lilla dipp i njutning för att driva dig ytterligare över den röda linjen till mer chockerande porr eller beteende för att frigöra mer dopamin. Mer nyhetens behag, mer dopamin och det lilla monstret säger åt dig att fortsätta. Så många bilder och videoklipp under en enda session utlöser en supernormal stimulans som injicerar fler kemikalier i hjärnan och driver dig till att fortsätta.
Receptorerna får hela tiden information om att de ska stänga av som svar på översvämningen. Orgasm förstärker bara denna effekt och leder till abstinens. Du är i förnekelse då det lilla monstret kräver sin fix utan någon egentlig smärta eller obehag. Hotet om erektionsproblem skrämmer många, vilket på samma gång är anledningen till att de förtränger det och överskuggar det med rädslan för att sluta med porr. Det är inte så att rädslan i själva verket är större, men att sluta idag är så abrupt. Varför se så negativt på det? Det kanske aldrig kommer att hända, åtminstone inte innan man hunnit sluta ändå 
Vi tänker ofta på porr som en dragkamp där rädslan drar på ena sidan: "*Det är ohälsosamt, smutsigt och förslavande*". På andra sidan drar de positiva aspekterna: "*Det är min njutning, min vän, mitt stöd.*" Det slår oss aldrig att denna sida också är rädsla. Det är inte det att vi gillar porr, vi blir bara så olyckliga utan den. Heroinmissbrukare som berövas heroin genomlever helvetet, men när de äntligen får trycka in en nål i venen och få stopp på det fruktansvärda suget är glädjen total. Tänk dig hur någon faktiskt kan tro att de får glädje av att sticka in en injektionsspruta i en ven. Icke-heroinmissbrukare lider inte av den där panikkänslan vilket gör det ganska tydligt. Heroinet lindrar inte känslan, det orsakar den.
Icke-användare känner sig inte olyckliga om de inte får använda porr - det är det bara användare som gör. Internetporren lindrar inte känslan, den orsakar den. Rädslan för de negativa konsekvenserna hjälper inte användarna att sluta, vilket man kan likna vid att gå genom ett minfält. Lyckas du komma till andra sidan helskinnad är det okej, men du kunde lika gärna ha trampat på en mina och drabbats av konsekvenserna. Om du kände till riskerna och var beredd att ta dem, varför ska någon annan bry sig om det? Missbrukare med detta synsätt utvecklar vanligtvis följande undvikande taktik.
"***Man blir gammal och förlorar ändå sin sexuella förmåga... ***"
Visst, men den sexuella förmågan är inte poängen, vi snackar om förslavning här. Och även om så var fallet, är det ett logiskt skäl till att medvetet försämra sitt liv i förväg?
"***Livskvalitet är viktigare än att bara leva. ***"
Exakt! Skulle det betyda att livskvaliteten hos en missbrukare är högre än hos någon som inte är missbrukare? Är det verkligen rimligt att livskvaliteten hos en missbrukare är bättre än hos en icke-missbrukare. Ett liv där främsta målet är att stoppa huvudet i sanden och vara konstant olycklig låter inte som särskilt mycket livskvalitet.
"***Jag är singel och planerar inte att slå mig till ro inom snar framtid, så varför inte? ***"
Även om det var sant, skulle det verkligen vara ett logiskt skäl att leka med sina neurologiska impulskontrollmekanismer? Kan du tänka dig någon som är dum nog att klä av sig naken vid ensamhet, oavsett säkerheten på att man väntar besök eller inte? Det är precis vad porranvändare gör!
När vi successivt överstimulerar våra belöningskretsar och på så sätt gör dem oförmögna att hantera normal livsstress bidrar det till att du inte kan njuta av livet med full entusiasm och kraft. Porr och onani ersätter den naturliga sexlusten på samma sätt som en chokladkaka ersätter riktig mat. Det helt naturligt att många läkare och psykologer nu kopplar samman diverse psykiska problem med fysiologiska orsaker. Det allmänna medicinska samfundet hävdar att porr aldrig vetenskapligt har bevisats vara den direkta orsaken till de problem som rapporteras av personer som bekänner sig själva, men att offentligt erkänna sin sexuella oförmåga är en väldigt skamutlösande händelse. Varför skulle någon, efter att ha funnit orsaken och eliminerat den, göra det om de inte verkligen var oroliga?
EasyPeasy hjälper dig att avlägsna porren och göra dig till en lycklig före detta användare. Ingen mer porr, porrstödd onani och inga fler onödiga orgasmer. Den enda hjälpen kommer hädanefter att vara din partners beröring, lukt och doft. Precis som fullkornsbröd i en välbalanserad kosthållning kommer du inte längre att vilja ha den hälsovådliga glukos-fruktossirap som internetporren är. Bevisen är så överväldigande att de inte behöver ens behöver fastslås. När jag smäller en hammare rakt på tummen så vet jag att det gör det ont, det behövs inga ytterligare bevis. Stressen som internetporren framkallar påverkar andra aspekter av användarens liv och många hemfaller då till att använda droger som cigaretter och alkohol för att kunna hantera det. Vissa användare kontemplerar till och med självmord.
Användare inbillar sig vidare att porrens negativa effekter är överdrivna. Det motsatta är dock sanningen. Det råder nämligen ingen tvekan om att internetporren är den främsta orsaken till inte bara sexuell dysfunktion utan också många andra problem. Hur många skilsmässor har porren till exempel varit orsak till? Där finns det visserligen ingen helt tillförlitlig forskning, men sökningar i olika nätgemenskaper tyder på att antalet är många och exponentiellt ökande.
I ett avsnitt av tv-serien Vänner får killarna tillgång gratis porr på tv:n och började sedan undra varför inte pizzabudet frågade om hon kunde få se deras ”stora sovrum". Porrberoende förvränger verkligheten och man projicerar ofrånkomligen sina porrfantasier på riktiga kvinnor. Tänk effekten som oförsiktig eller oavsiktlig exponering av porr på internets mörkare sidor kan ha på någon som redan befinner sig vid en brytpunkt i sitt liv. Kampen mot dessa porrframkallade tankar belastar deras psykiska hälsa hårt.
Ett annat tankeexperiment: någon säger till dig att de gärna vill ha sex med dig, men att de inte nödvändigtvis vill ha en orgasm. De vill göra det så länge som möjligt utan orgasm, men om det händer så är det okej. Jag lovar dig att du får en fenomenal ny sexuell upplevelse som är långt bättre än någon annan du tidigare har haft. Prova det.
Hjärntvätten får oss att tänka precis som mannen som ramlar från 100:e våningen och som säger när han susar förbi 50:e våningen: ”Än så länge är det lugnt!” Eftersom vi har kommit undan hittills, tänker vi, så kommer inte en liten porrsittning till att göra någon skillnad. Se det istället som att porranvändandet är en konstant obruten kedja där varje länk skapar och förstärker behovet av nästa. När du börjar med ”vanan” tänder du en stubin, problemet är bara att du *inte vet hur lång den är.* Varje gång du ger efter för frestelsen och tar en porrsittning blir stubinen kortare och explosionen blir alltmer förestående. 
**HUR VET DU ATT DEN INTE EXPLODERAR NÄSTA GÅNG?**
## Olycksbådande, Mörka Skuggor
Användare har svårt att tro på att det är internetporren som faktiskt orsakar de nervösa känslor som kommer när du är ute sent efter en jobbig dag hemma eller på jobbet. Icke-användare lider inte av den känslan - det är porren som orsakar den.
En annan glädje med att sluta med porr är friheten från de olycksbådande mörka skuggorna som sitter i bakhuvudet. De flesta användarna inser idiotin i att låta porrens dåliga effekter stänga av sina sinnen. Det sker automatiskt, men de mörka skuggorna ligger konstant och lurar i vårt undermedvetna, strax under ytan. De fantastiska fördelarna med att sluta med porr är medvetna, till exempel slöseriet av tid och det fullständigt korkade i att älska med en tvådimensionell bild.
De senaste kapitlen har behandlat de avsevärda fördelarna som det innebär att vara en icke-användare, men i rättvisans namn är det nödvändigt att ge en balanserad bild. På nästa sida listas därför alla fördelarna med att använda porr.

# Fördelar Med Att Vara Porranvändare

