# Viljestyrkemetoden

Det är ett samhälleligt accepterat faktum att det är väldigt svårt att sluta med porr. Böcker och forum som ger råd om hur man slutar inleder alltid med att förklara hur obeskrivligt svårt det är. I själva verket är sanningen att det är löjligt enkelt. Det är förståeligt om du vill ifrågasätta det påståendet, men begrunda det först. Att springa en engelsk mil på fyra minuter, det är svårt! Även om du genomgår flera års hårdträning så skulle du kanske ändå alltid vara fysiskt oförmögen till det.

Det enda du dock behöver göra för att sluta med porr är att sluta titta på det och till det sluta onanera. Ingen håller en pistol mot ditt huvud och tvingar dig att onanera (förutom du själv) och till skillnad från mat och vatten är det heller inte nödvändigt för att överleva. Så om du vill sluta med porr varför skulle det då vara så svårt? Faktum är att det är det inte. Det är användare som gör det svårt för sig själva genom att använda metoder som får dem att känna att de gör någon form av uppoffring. Låt oss se på dessa metoder.

Det är inte så att vi en dag bestämmer oss för att bli användare. Det enda vi gör är att experimentera med porrtidningar eller porrsajter och på grund av deras förskräckliga natur (det stämmer, förskräckliga)övertygas vi om att vi kan sluta experimentera när närsomhelst. Till en början tittar vi på videorna sporadiskt när vi själva vill eller vid speciella tillfällen. Men innan vi vet ordet av sker det inte längre sporadiskt, utan plötsligt onanaerar vi till dessa sajter dagligen. Porren blir en normal del av våra liv och vi behöver därför vara uppkopplade var vi än går. Vi anser oss ha rätt till kärlek, sex, orgasmer och de stressreducerande egenskaper porren ger oss. Vi verkar ha svårt att greppa att samma klipp och skådespelare inte ger oss samma grad av upphetsning som innan och vi börjar streta emot den annalkande röda gränslinjen för att undvika "den dåliga porren". 

Onani och internetporr varken förbättrar vårt sexliv eller minskar vår stress. Det är bara användare som övertygar sig själva att de inte kan njuta av livet eller hantera stress utan konstanta orgasmer.

Det tar oftast lång tid för användare att inse att de är beroende av porr på grund av inbillningen att de enbart använder porr för njutnings skull, inte för att de ”behöver” det. När vi inte "njuter" av porr, vilket vi aldrig kan göra utan nyhetens behag, chockerande genrer eller upptrappning, befinner vi oss under villfarelsen att vi kan sluta när som helst. Detta är en självförtroendefälla. Vi tänker: Jag njuter inte av porr, så jag kan sluta när jag vill. Enda kruxet är bara det att du aldrig verkar vilja sluta.

Vanligtvis inser vi inte problemet förrän vi faktiskt försöker sluta. De första försöken är ofta ganska tidiga och inträffar då vi träffar en partner och märker efter de första dejterna att de inte kan mäta sig med dina ideal. En orsak kan vara är att man märker hälsoeffekter i det dagliga livet.

Användaren inväntar alltid en stressig situation, oavsett om det gäller hälsa eller sex. Så fort de slutar blir det lilla monstret hungrigt. Användaren behöver då något som pumpar igång dopaminet, t.ex. cigaretter, alkohol eller sitt favoritharem som finns bara ett klick bort. Porren finns inte längre i källaren, det är virtuellt och tillgängligt var helst man går. Är partnern i närheten, eller om de är med vänner, så finns inte det virtuella haremet fritt tillgängligt, vilket gör dem ännu mer förtvivlade.

När användare stöter på forskning i ämnet eller olika nätgemenskap så kommer hen tvingas till en mental dragkamp, kämpa emot frestelser och känna sig deprimerad. Deras vanliga sätt att lindra stress på rycks ifrån dem vilket blir ett tredubbelt slag i magen. Det mest sannolika resultatet efter en sådan tortyrperiod blir en kompromiss. "Jag ska skära ner” eller "Det är inte rätt tidpunkt nu” eller möjligen "Jag väntar tills stressen har försvunnit ur mitt liv". När stressen väl har försvunnit så finns det dock ingen anledning att sluta och användaren bestämmer sig således för att inte sluta igen förrän nästa gång stressen slår an.
 
Det finns såklart aldrig någon rätt tidpunkt eftersom livet för de flesta människor är väldigt stressigt. Vi lämnar tryggheten hos våra föräldrar för värld där vi bygger hem, tar lån, får barn och har mer ansvarsfulla jobb. Men det spelar egentligen ingen roll då användarnas liv inte kan bli mindre stressigt genom att hans porrbruk orsakar ännu mer stress. Ju snabbare användaren går över till eskaleringsstadiet, desto mer stressad blir hen och desto större blir illusionen om dess betydelse.

I själva verket är det en villfarelse att livet blir mer stressigt och det är porr - eller en liknande krycka – som skapar den villfarelsen. Det här kommer att diskuteras mer ingående senare. Efter de inledande misslyckandena börjar användaren att förlita sig på möjligheten att en dag vakna upp utan att vilja onanera eller använda porr. Detta hopp tänds vanligen av före detta användares berättelser: 

"Jag var inte seriös förrän jag drabbades av svaga erektioner. Då ville jag inte använda porr längre och slutade onanera".

Låt dig inte luras. Om du undersöker dessa rykten närmare så förstår du att det aldrig är lika enkelt som det verkar vara på ytan. Oftast så har användaren redan bestämt sig för att sluta och använder bara den senaste händelsen som en språngbräda. Personer som slutar "bara så där" har ofta chockats till det. Kanske har hen blivit upptäckt av sin partner, eller kommit på sig själv med att konsumera porr som är utanför ens egen sexuella läggning, eller haft en avvikande sexuell preferens som skrämt dem. 

"Det är bara sån jag är!" 

Sluta ljug för dig själv. Det kommer aldrig att hända om du inte får det att hända.

Låt oss titta närmare på viljestyrkemetoden och varför den är så svår att lyckas med. Många går genom livet med en passiv "jag slutar i morgon"-strategi. Vid enstaka tillfällen kommer något att utlösa ett försök till att sluta. Det kan vara oro för hälsan, viriliteten eller att vi inser att vi faktiskt inte tycker om porr. Oavsett orsak börjar vi väga porren för- och nackdelar mot varandra. Sex delas upp i två delar. Dels tantrisk (beröring, lukt, röst) och dels fortplantning (orgasm). Den här kunskapen är en av de viktigaste nycklarna för att öppna våra sinnen och utan denna viktiga distinktion skapas förvirring som leder till samma gamla misslyckande. När vi tittar på situationen rationellt kommer vi fram till samma slutsats som vi har vetat hela tiden: 

”SLUTA ATT TITTA PÅ SKITEN!” 

Om du satte dig ner för att poängsätta fördelarna med att sluta och jämföra dem med fördelarna att fortsätta med porr så skulle det totala antalet poäng för att sluta vida överstiga alla "nackdelar". Om man gör ett Pascals vadslagning så förlorar man ingenting genom att sluta samtidigt som de potentiella vinsterna är enorma. Man har rent krasst ingenting att förlora. Vetskapen om att användaren kommer att få det bättre som icke-användare, så är hen övertygad om att hen tvingas göra en uppoffring. Det är en kraftfull villfarelse, men ändå en villfarelse. Utan att veta varför tror användare att sessionerna hjälper under både goda som dåliga tider. Redan innan det initiala försöket att sluta kombineras den samhälleliga hjärntvätten med den av ditt eget missbruk och den ännu kraftigare indoktrineringen om hur svårt det är att "sluta".

Jag har hört historier om de som har slutat i flera månader och fortfarande känner ett desperat sug och de som tillbringar resten av sina liv med att gnälla över att de så gärna vill ha en session. Berättelser om användare som har hållit upp i månader, till och med år, och lever lyckliga liv, men som bara tar sig en "titt" på porr och plötsligt blir beroende igen. De känner förmodligen flera personer som befinner sig i ett avancerat stadium av sjukdomen, som synbart fördärvar sig själva och uppenbarligen inte njuter av livet - men som fortsätter att använda porr ändå. Förmodligen har de själva genomlidit en eller flera liknande erfarenheter.

Istället för att gå in med känslan: "Perfekt! Har du hört? Jag behöver inte titta på porr längre!", inleder de sin resa med en känsla av undergång och svårmod, som om de ska påbörja bestigningen av Mount Everest. De fastställer felaktigt föresatsen att när det lilla monstret väl har satt sina klor i dig, då är du fast för resten av livet. Många användare börjar med att be om ursäkt till sina flickvänner eller fruar: "Du, jag ska försöka ge upp porren. Jag kommer förmodligen att vara irriterad de närmaste veckorna, försök att ha överseende med mig." Som du förstår är de flesta försök att sluta är dödsdömda innan de ens har börjat.

Anta att användaren överlever några dagar utan en session, att han får tillbaka sin upphetsning och börjar återhämta sig. Han har inte öppnat sina favoritsajter och blir därför upphetsad av normala stimulanser som han tidigare hade zonat ut av. Skälen till varför han slutade från första början försvinner snabbt ur tankarna, ungefär som att se en trafikolycka när man är ute och kör bil. Det saktar ner dig ett tag, men du stampar plattan i mattan nästa gång du är sen till ett möte.

På andra sidan dragkampen finns det lilla monstret som fortfarande inte har fått sin medicin. Du känner ingen fysisk smärta, med samma känsla under en förkylning hade du inte stannat hemma från jobbet eller blivit deprimerad. Du skulle bara skratta bort det. Allt användaren känner är att han vill besöka sitt harem. Det lilla monstret vet det och sätter igång det stora hjärntvättsmonstret, vilket gör att samma person som några timmar eller dagar tidigare räknade upp alla skäl att sluta, nu desperat letar efter varje ursäkt till att börja igen. De börjar säga saker som:

• "Livet är för kort. En bomb skulle kunna explodera, jag kan bli överkörd av en buss i morgon. Jag har slutat för sent. Allting gör dig tydligen beroende nuförtiden."

• "Jag har valt fel tidpunkt."

• "Jag borde ha väntat till efter jul/efter min semester/efter mina tentor/efter denna stressiga händelse i mitt liv."

• "Jag kan inte koncentrera mig, jag blir irriterad och har dåligt humör, kan inte ens göra mitt jobb ordentligt."

• "Min familj och mina vänner kommer inte att älska mig. Låt oss inse det, för allas skull måste jag börja om på nytt. Jag är en bekräftad sexmissbrukare och det finns inget sätt för mig att någonsin bli lycklig igen utan orgasm."

• "Ingen kan överleva utan sex." (Hjärntvättad av välmenande människor som inte tar hänsyn till skillnaden mellan den tantriska och den fortplantande delen av sex)

• "Jag visste att detta skulle hända, min hjärna är 'sensibiliserad' av DeltaFosB på grund av förändringar som påverkas av dopaminpåslag på grund av mitt tidigare överdrivna porrbruk. Sensibilisering kan "aldrig" avlägsnas från hjärnan."

Det är nu användaren vanligtvis ger upp. Han startar webbläsaren och schizofrenin ökar. Å ena sidan den enorma lättnaden i att få stopp på suget när det lilla monstret äntligen får sin sil, å andra sidan den fruktansvärda orgasmen och användarens totala oförståelse över varför han gör det. Det är anledningen till varför användaren tror att han saknar viljestyrka. Det handlar i själva verket inte om brist på viljestyrka. Det enda han precis har gjort är att ändra sig och att fatta ett fullkomligt rationellt beslut i ljuset av den senaste informationen.

"Vad är meningen med att vara frisk eller rik om man är olycklig?”

Absolut ingen alls! Att leva ett kortare, mer uppfyllande liv är mycket bättre än ett långt och olyckligt liv. Lyckligtvis är detta inte sant för icke-användaren eftersom livet utan porr är så oändligt mycket roligare. Det elände som användaren genomlider beror inte på abstinensbesvären, även om det initialt utlöses av dem. Nej, det verkliga lidandet är den mentala dragkamp som orsakas av tvivel och osäkerhet. Eftersom användaren börjar med att känna att han gör en uppoffring börjar han sedan känna sig berövad av någonting, vilket är en form av stress.

Ett av dessa stressmoment är när användarens hjärna säger åt honom att "ta en liten titt". Den lilla titten gör att han vill gå tillbaka så fort som han slutar titta. Men eftersom de har slutat så kan de inte göra det, vilket gör dem ännu mer deprimerade och sätter igång utlösaren igen. 

En faktor som gör det så svårt att sluta är att man väntar på att något ska hända. Om du ska göra ett körprov så får du veta om du klarat målet så snart provet är klart. Du får veta direkt. Men om du ska sluta med hjälp av viljestyrkemetoden så är ditt inre narrativ: "Om jag klarar mig tillräckligt länge utan internetporr så kommer lusten att titta på den att försvinna till slut". Det kan man se på olika nätforum där missbrukare talar om sina streaks eller antal dagar av avhållsamhet.

Som nämndes ovan är den vånda som användaren genomlider mental och orsakas av osäkerhet. Även om det inte finns någon fysisk smärta så har det ändå starka effekter. Användaren blir olycklig och osäker och är långt ifrån att glömma, samtidigt nu också full av tvivel och rädsla.

- "Hur länge kommer suget att pågå?"

- "Kommer jag någonsin att bli lycklig igen?"

- ”Kommer jag någonsin att vilja gå upp på morgonen?"

- "Hur ska jag någonsin kunna klara av stress i framtiden?"

Användaren väntar på att saker och ting ska förbättras, men medan de fortfarande sörjer blir hans "harem" alltmer värdefullt. I själva verket är det något som ”händer”, men det sker omedvetet. Om användaren kan överleva flera veckor utan att öppna webbläsaren så försvinner suget efter det lilla monstret. Som tidigare nämnts är dock abstinensbesvären från dopamin och opioider så milda att användaren inte ens märker av dem. Här känner många användare att de har ”sparkat ut” beroendet och tar således en liten titt för att bevisa det - vilket skickar dem ut i vattenrutschbanan igen. Efter att ha försett kroppen med dopamin säger en röst i bakhuvudet: "Du vill titta igen.". Det hade gjort sig av med beroendet, men nu har de fastnat igen.


Som barn tittade du på tecknad film och bildade då enligt neurovetenskapen du nervbanor (DeltaFosB) för dem. Om man vill avskräcka ett barn från att titta på tecknade serier skulle man kunna undersöka om dessa banor fortfarande finns kvar hos en som vuxen och sedan undersöka varför de inte längre gillar att titta på samma tecknade serier som vuxna. För det första finns det bättre underhållning att tillgå och för det andra har tecknade filmer helt enkelt inte samma magi för en vuxen. Med viljestyrka-metoden förnekar man bara barnet tecknat, men med EasyPeasy ser man också till att barnet inte ser något värde i det. Vilket är bäst?

När användaren börjar en ny session tänker han inte: jag vill inte bli beroende igen! utan låter en period på timmar, dagar eller till och med veckor passera. Ex-användaren kan sedan säga: "Jag blev inte beroende, så jag kan säkert ta en ny session.” De faller sakta tillbaka ner i samma fälla som när de började och är redan på hal is.

Användare som lyckas med viljestyrkemetoden tycker generellt att det tar lång tid och är svårt eftersom det främsta problemet är att de är hjärntvättade. Långt efter att det fysiska beroendet har dött är användaren fortfarande olycklig. Så småningom, efter att ha överlevt denna långvariga tortyr, börjar det gå upp för dem att de inte kommer att ge efter. De slutar tjura och accepterar att livet går vidare och det är ganska trevligt utan porr. Det är betydligt fler som misslyckas än de som lyckas med viljestyrka. En del som lyckas går igenom sina liv i ett konstant sårbart tillstånd, fortfarande till viss del hjärntvättade att tro att lite porr faktiskt skulle ge dem en boost. Detta är förklaringen till varför många användare som har slutat under långa perioder börjar titta på porr igen.

Många ex-användare tar enstaka sessioner för att ”unna sig” lite eller för att övertyga sig själva om hur stark deras självkontroll är. Det är vad det är, men så fort sessionen slutar börjar dopaminet att avta och en liten röst väcks till liv i deras bakhuvud som börjar driva dem mot en ny session. Även om de bestämmer sig för att tillgodose rösten, så verkar det fortfarande vara under kontroll. Inget chockerande, ingen upptrappning eller nyhetens behag, så de säger till sig själva: "Märkligt! Även om jag inte riktigt njuter av det kommer jag inte att fastna. Efter julen/helgen/traumat slutar jag." Lyckligt ovetande hur hjärnans vattenrutschbanor precis har smörjts in ännu mer.

För sent! De är redan fast igen. Fällan som de lyckades kravla sig ur har skördat sitt byte igen.

Som sagt, njutning har ingenting med saken att göra, och har aldrig haft. Om vi tittade för njutnings skull så skulle vi aldrig stanna på sajterna längre än nödvändigt för pliktens skull. Ett bättre sätt att självbefläcka sig på är genom minnen. Vi antar att vi gillar internetporr eftersom vi inte kan se oss själva vara så korkade att vi blev beroende om vi inte hade gillat det. De flesta användare har ingen aning om supernormal stimulans, nyhetens behag eller jakten på chockerande innehåll. Inte ens efter att de läst på om det kan de acceptera att deras användning motiveras av ett evolutionärt hårdkodat belöningssystem. Det är därför som porr är så undermedvetet. Om du var medveten om de neurologiska förändringarna och var tvungen att motivera de framtida finansiella förlusterna, så skulle även njutningen försvinna.

När vi försöker blockera sinnet mot den mörka sidan känner vi oss korkade. Det skulle vara outhärdligt att tvingas möta det. Om du såg en användare in action skulle du se att de endast är lyckliga när de är omedvetna om att de använder. När de väl har vaknat upp brukar de bli obekväma och ursäktande. Porren matar det lilla monstret, så när du sparkar ut det ur kroppen tillsammans med hjärntvättningen (stora monstret), så känner du varken behov eller lust att titta mer.

