# Passa Dig För Att Skära Ner

Många användare hemfaller till att skära ner på sitt porrtittande som en språngbräda för att till sist sluta, eller som ett försök att kontrollera det lilla monstret. Många rekommenderar nedtrappning, eller någon form ”porrdiet” för att få igång motivationen. Att skära ner som ett steg att sluta helt är ***förödande.*** Det är dessa försök att skära ner som håller oss fångade för resten av våra liv. Nedskärning åtföljs generellt sett alltid av misslyckade försök att sluta. Efter några timmar eller dagar av avhållsamhet säger användaren något i still med:

”*Jag kan inte tänka mig att gå till sängs utan att besöka mitt virtuella harem, så från och med nu kommer jag bara titta på porr var fjärde dag eller slänga ut min samling av ”dålig porr”. Om jag följer den här porrdieten så kan jag antingen hålla det på den nivån eller skära ner ännu mer senare.*”

Dessa hemska saker händer sedan:

1. De fastnar i den värsta av alla världar –- fortfarande beroende av internetporr samtidigt som de håller det lilla monstret vid liv, inte bara i kroppen utan även i huvudet.

2. Önskar att tiden ska gå så de kan påbörja nästa session.

3. Innan nedskärningen så var det bara att starta webbläsaren om de ville åtminstone delvis ville lätta på abstinensbesvären. Nu däremot orsakar de sig själva att plågas av abstinensbesvären i tillägg till den normala stressen livet anbringar en. Det här gör dem ännu mer olyckliga och lättretliga.

4. Under frosseriperioder så njuter de inte av sessionerna eller ens inser att de använder supernormal stimulans. Det sker automatiskt, det enda harembesöket de faktiskt uppskattade var den som följde direkt efter en avhållsam period. Nu när de tar extra tid emellan sessionerna så uppskattar de dem alla. Ju längre väntan emellan, desto mer njutbar ter sig varje session. Det är för att njutningen inte ligger i själva sessionen, utan i att man blir av med oron som föranleds av begäret, oavsett om det är ett fysiskt begär eller mental tjurighet. Ju längre lidandet emellan är, desto mer njutbar blir varje session.

Den största svårigheten med att sluta är inte det neurologiska beroendet vilket i själva verket är lätt att komma över. Användare slutar utan problem vid flera tillfällen, t.ex. vid en närståendes död, familje- eller jobbrelaterade situationer, osv. Då skulle de utan tillgång till porr kunna gå i tio dagar utan att det stör dem. Om de däremot hade kunnat ha tillgång till porr under samma tio dagar så hade de slitit sitt hår i frustration.

Många användare har chansen att använda porr under sin arbetsdag, men avstår. De kan passera Victoria’s Secret och badbassänger osv utan värst mycket problem. Många avstår om de tillfälligt tvingas sova på soffan för att de har gäster, eller om de själva är på besök någonstans. Inte ens på lättklädda barer eller nudiststränder blir det mycket ståhej. Användare tycker det är närmast skönt när någon eller något gör att de inte kan titta på porr. Användare som vill sluta njuter faktiskt i hemlighet när de går längre perioder utan porr, vilket skänker hopp om att de en dag inte vill ha det mer. 

Det riktiga problemet när man vill sluta är hjärntvätten, den illusion som gör internetporr en slags rekvisita eller en belöning och att livet aldrig skulle vara detsamma utan det. Att skära ner kommer aldrig att få dig sluta med internetporr, det kommer bara att göra dig osäker och olycklig. Det kommer att övertyga dig om att det viktigaste i världen är den senaste videon som du har missat och att du inte kan bli lycklig igen utan att få se den.


Det mest patetiskt man kan stöta på är en användare som har försökt minska sin porrkonsumtion. Plågade av vanföreställningen att ju mindre porr de ser, desto mindre vill de besöka sitt virtuella harem. Tyvärr är sanningen det rakt motsatta. Ju mindre de tittar på porr, desto längre lider de av abstinensbesvär och desto mer "njuter" de av att lindra dem. Vad de dock kommer att märka är att de inte njuter av sin favoritgenre lika mycket längre. Men det stoppar dem inte av den anledningen att om tubsidorna var tillägnade endast en stjärna eller genre så skulle ingen användare någonsin gå dit mer än en gång.

Är det svårt att tro? Vilket är det värsta ögonblick av självkontroll man kan känna? Att vänta i fyra dagar innan man får nå klimax. Vad är då det mest värdefulla ögonblicket för de flesta användare som haft en fyra dagars porrbantning? Just det, samma klimax efter att ha väntat i fyra dagar! Är du under uppfattningen att du onanerar för att njuta av orgasmen, eller den mer rationella förklaringen att du måste lindra abstinensbesvären för att du har rätt till det?

Att avlägsna hjärntvätten är det viktigaste för att kunna krossa illusionen du har om porr innan din sista session. Om du inte har krossat illusionen innan du stänger sista fönstret till porren så finns det inget sätt att bevisa det på utan att fastna igen. När du svävar över bokmärken och sparade bilder så fråga dig själv var det fina i denna handling ligger. Du kanske tror att endast vissa videor är av god smak, till exempel dina favoritteman. Om så är fallet, varför ens orka bry sig om att titta på andra teman? För att du har fått en vana? Varför skulle någon vanemässigt sabba sin hjärna och låta sig själv gå till spillo? Ingenting är annorlunda efter en månad, varför skulle ett porrklipp vara det?

Du kan testa själv, hitta den heta filmen från förra månaden och bevisa att det är annorlunda. Ställ sedan in en påminnelse och titta på samma film efter en månad utan porr. Det kommer att träffa (nästan) samma punkter som förra månaden. Samma klipp kommer att vara annorlunda efter en social aktivitet där du blir testad eller avvisad av en potentiell partner. Anledningen är att missbrukaren aldrig blir helt lycklig om det lilla monstret förblir otillfredsställt.

Var kommer tillfredsställelse in i bilden? Grejen är att användarna är olyckliga såvida de inte får lätta på sina abstinensbesvär. Skillnaden mellan att titta på porr och att inte göra det är för dem skillnaden mellan att vara lycklig och olycklig. Därför verkar internetporr vara bättre. Medan användare som tittar på porr det första de gör på morgonen är olyckliga oavsett om de tittar på den eller inte.

Att skära ner på porr är inte bara ineffektivt, det är också den värsta formen av tortyr. Det är ineffektivt eftersom användaren hoppas att genom att minska vanan så kommer även lusten att titta på porr att minska. Det är dock inte en vana utan ett beroende. Ett beroende karaktäriseras av att man vill ha mer och mer, inte mindre och mindre. Därav måste användaren med viljestyrka och disciplin gå en livslång kamp mot beroendet. Att skära ner innebär alltså viljestyrka och disciplin för alltid. Att sluta helt är både enklare och mindre smärtsamt. Det finns tiotusentals fall där nedskärning har misslyckats.

Det svåra med att sluta helt är inte dopaminberoendet. Nej, det är lätt att hantera. Det är den felaktiga tron att porr ger dig njutning som gör det svårt. Den tron uppstår ursprungligen genom hjärntvättning som vi utsätts för redan innan vi började använda, och som ytterligare förstärks av det faktiska beroendet. Det enda nedskärning åstadkommer är att förstärka villfarelsen ytterligare, så till den grad att porren dominerar livet helt och hållet och övertygar användaren om att deras beroende är det mest värdefulla på jorden.

Den handfull fall som lyckats har uppnåtts genom en relativt kort nedskärningsperiod, följt av sedan sluta tvärt. Dessa användare lyckades slutade trots nedskärningen, inte tack vare den. Allt nedskärningen gjorde var att förlänga plågan. De misslyckade försöken gjorde användarna till nervösa vrak och ännu mer övertygade om att de kommer förbli beroende livet ut. Detta är vanligtvis tillräckligt för att de ska återvända till sitt internetharem, antingen för att söka nöje eller stöd, eller som en uppladdningsperiod innan nästa försök att sluta.
 
Att skära ner bidrar till att illustrera porrens meningslöshet, och visar tydligt att ett besök i haremet inte är njutbart efter avhållsamhet. Man tvingas slå huvudet mot en tegelvägg (drabbas av abstinensbesvär) för att det ska bli trevligt när man slutar. Valmöjligheterna är därför följande:

1. Att skära ner för livet och lida självvald tortyr, vilket du ändå inte kommer att kunna göra.

2. Att alltmer tortera dig själv i livet, vilket är meningslöst.

3. Att vara snäll mot dig själv och skippa porr helt och hållet.

Den andra aspekten som nedskärningen visar är att ett enstaka eller tillfälligt haremsbesök inte egentligen inte finns. Internetporr är en kedjereaktion som kommer att pågå resten av ditt liv om du inte gör en aktiv ansträngning för att bryta den.

**Kom ihåg: Genom att skära ner kommer du att dras längre ner.**
