# Bara En Titt

"Bara en titt" är en myt som du måste slå ur hågen:

- Det är *bara en titt* som en gång får oss att börja.

- Det är *bara en titt* som hjälper oss under en svår period eller vid ett speciellt tillfälle och som får våra försök att sluta att gå om intet.

- Det är *bara en titt* som, efter att ha lyckats bryta missbruket, skickar oss tillbaka i fällan. Ibland är det för att bekräfta att man inte behöver porr längre och ett besök i haremet är förödande.

Porrens efterverkningar är hemska och övertygar användaren om att de aldrig kommer att bli beroende igen – men det är de redan. Användaren känner att något som gör dem så olyckliga och fylld av skamkänslor inte borde få dem beroende. Det blir de ändå.
 
Det är tanken på en ”speciell sittning" som ofta hindrar användarna från att sluta. Den speciella sittningen efter din långa konferensresa, din hårda dag på jobbet, ditt senaste bråk med barnen eller när din partner förvägrar dig sex. Gravera ***fast*** i ditt sinne att det inte finns något sådant som "bara en titt". Det är en kedjereaktion som kommer att pågå resten av livet om den inte bryts. Myten om det enstaka, speciella tillfället gör att användarna fortsätter att tjura efter att ha slutat. Ta för vana att aldrig genomföra den "oviktiga" sittningen, den är ett fantasifoster. När du tänker på porr från och med nu, föreställ dig då ett bortslösat, oanständigt liv bakom en skärm bara för privilegiet att ödelägga dig själv mentalt och fysiskt. En livstid av slaveri och hopplöshet. Det är inget brott mot dig själv om dina erektioner skulle bli opålitliga. Att däremot prioritera kortsiktig ”njutning” framför långsiktig lycka är det definitivt. 

Det är helt okej att inte alltid kunna hitta på "något att göra" för att fylla tomrummet; det är inte realistiskt att kunna göra det varje gång. Vi kan planera för de flesta av dem, men ibland uppstår de bara. Goda och dåliga tider inträffar oberoende av porr. Men förstå att det inte är porren som orsakar det. Ditt liv kommer att antingen bestå av elände, eller inget alls. Du skulle aldrig drömma om att käka cyanid bara för att du gillar smaken av mandlar. Du måste sluta straffa dig själv med en tillfällig "no big deal"-sittning. Fråga en porrmissbrukare: "*Om du hade möjlighet att gå tillbaka till tiden innan du blev beroende, skulle du då ha blivit användare?*". Svaret blir oundvikligen "*Du måste skämta!*". Ändå har varje användare detta val varje dag i livet. Varför väljer de att inte sluta? Svaret är: rädsla. Antingen rädsla för att inte kunna sluta eller för att livet inte kommer att vara detsamma utan porr.

Sluta lura dig själv! Du kan sluta, vem som helst kan göra det. Det är faktiskt löjligt enkelt, men för att det ska bli så finns det vissa grundprinciper som du måste få klart för dig.

1.  Det finns inget att ge upp, bara fantastiska positiva vinster att uppnå.

2.  Övertala aldrig dig själv om att en sittning inte är ”stor grej" eller det du bara ska ta ”en titt". Det där existerar inte. Det enda som finns är en livstid av smuts och slaveri.

3.  Du är inte annorlunda, alla användare kan enkelt sluta.

Många användare tror att de är bekräftade missbrukare, eller att de har en beroende-personlighet. Detta beror oftast på att de läser överdrivet mycket chockerande neurovetenskap. Det finns inget sådant, ingen föds med behovet av att onanera till videoklipp innan de blev beroende. Det är drogen som gör dig fast, inte din karaktär eller personlighet. Karaktären av beroendeframkallande supernormala stimulanser får dig att tro att så är fallet. Det är dock viktigt radera den övertygelsen, för om du tror att du är beroende så kommer du att vara det, även efter att det lilla monstret i kroppen sedan länge är utrotat. Det är viktigt att avlägsna all denna hjärntvätt.
