# Tillfälliga Användare

De tunga användarna tenderar att avundas den tillfälliga porranvändaren. Vi har alla stött på typen: "*Äh, jag kan gå hela veckan utan porr, det spelar ingen roll för mig.*" Vi önskar att vi var sådana. Det kan vara är svårt att tro, men ingen användare njuter av att vara det. Glöm aldrig: 


| Ingen användare har någonsin bestämt sig för att bli det, vare sig tillfälligt eller på annat sätt, och därför:

| Känner sig alla användare dumma, och därför:

| Måste alla användare ljuga för sig själva och andra i ett fåfängt försök att rättfärdiga sin dumhet.


Golffanatiker skryter om hur ofta de spelar, så varför skryter porranvändare om hur lite de onanerar? Om det är det sanna kriteriet är det väl så att hyllningen är att inte onanera alls?

Om någon sa till dig: "*Jag kan gå hela veckan utan morötter och det stör mig inte det minsta*" skulle du tro att du pratade med en galning. Om jag gillade morötter, varför skulle jag vilja vara utan dem hela veckan? Om jag inte gillade dem, varför skulle jag säga så? Så när en bedyrar om att överleva en vecka utan en sittning försöker hen övertyga sig själv - och dig - om att hen inte har ett problem. Men fanns där inget problem skulle en dylik sägning inte behövas. Mer pricksäkert betyder kommentaren: "*Jag lyckades överleva en hel vecka utan porr*". Alla användare hoppas de att de efter detta kan överleva resten av sina liv. Kan du föreställa dig hur värdefull sittningen måste ha varit efter att ha känt sig berövad i en hel vecka?

Det är anledningen till varför tillfälliga användare i praktiken är mer beroende än tunga användare. Inte bara är illusionen av njutning större, de har också mindre incitament att sluta eftersom de slösar mindre tid och därför är mindre sårbara för hälsorisker. Ibland upplever de sexuell dysfunktion, men eftersom de är osäkra på orsaken så skyller de på andra faktorer. Den enda njutning användarna får är inuti den sökande dopamincykeln och i att lindra abstinensbesvären, vilket redan har förklarats. Nöjet är en illusion. Föreställ dig det lilla porrmonstret som en nästan omärkbar klåda som du till största delen förblir omedveten om.

Har man en permanent klåda så är den naturliga tendensen att klia den. Vad gäller porr och när belöningskretsarna blir alltmer immuna mot dopamin och opioider är den naturliga tendensen att edga (onanera och sluta innan klimax nås), eskalera, binga, söka nyheter, söka chockerande klipp osv. Det finns fyra huvudfaktorer som hindrar användarna från att kedjetitta.

**Tid.**
De flesta har inte råd att slösa för mycket tid på porr.

**Hälsa.**
För att lindra klådan måste vi konsumera allt gratis material som finns tillgängligt och lite till. Förmågan att klara av den typen av sträcktittande varierar hos varje individ, vid olika tidpunkter och situationer i deras liv. Detta fungerar som en automatisk begränsning.

**Disciplin.**
Påtvingad av samhället eller användarens arbete, vänner och släktingar; kanske till och med av användaren själv som ett resultat av den naturliga dragkamp som pågår i sinnet.

**Imagination.**
Bristande fantasi minskar subjektivt sett chocken, nyheten och andra värden i klippet.

Det är lätt att betrakta "icke-tillfälliga" användare som svaga, oförmögna att förstå varför andra kan begränsa sin "konsumtion". Men tunga användare bör komma ihåg att de flesta tillfälliga användare helt enkelt är oförmögna till kedjetittande, vilket kräver stark fantasi och uthållighet. En del av dessa en gång i veckan-användare som tunga användare tenderar att avundas är fysiskt oförmögna att göra mer, eller för att deras jobb, samhället eller deras eget hat mot att bli beroende inte tillåter dem.

Det kan vara fördelaktigt att ge några definitioner.

**Ickeanvändaren**

Någon som aldrig har fallit i fällan, men som inte bör vara självgod. De är en icke-användare endast genom lyckans eller godhetens nåd. Alla användare var övertygade om att de aldrig skulle bli beroende och vissa icke-användare fortsätter att försöka enstaka sessioner.

**Den tillfälliga användaren**

Det finns två grundläggande klassificeringar av dem:

1. Användaren som har gått i fällan men inte inser det - avundas inte sådana användare! De provsmakar bara nektarn vid mynningen av krukplantan och kommer med all sannolikhet snart att bli tunga användare. Kom ihåg att precis som alla alkoholister började som tillfälliga drickare, så börjar också alla användare tillfälligt.

2. Användaren som tidigare var en tung användare och som därför tror att han eller hon inte kan sluta. Dessa användare är de sorgligaste av alla och de faller in i olika kategorier, som alla kräver separata kommentarer.

**En Gång Om Dagen-användaren**

Om de njuter av sin rätt till orgasm, varför använder de internetporr endast en gång dagligen? Om de kan ha det eller låta bli, varför ens bry sig överhuvudtaget? Kom ihåg att "vanan" i själva verket är att slå huvudet mot en vägg för att få det att slappna av när man slutar. Den som använder porr en gång om dagen lindrar sina abstinensbesvär under mindre än en timme varje dag. Även om de inte är medvetna om det, spenderar de resten av dagen med att slå huvudet mot väggen och gör detta under större delen av sitt liv. De använder en gång om dagen eftersom de inte kan riskera att åka fast eller att stöka till sin neurologiska hälsa. Det är lätt att övertyga den tunga användaren om att de inte tycker om det, men betydligt svårare att övertyga en tillfällig användare. Alla som har gått igenom ett försök att minska sitt bruk vet att det är den värsta tortyren av alla, och nästan garanterat att du kommer att hålla dig beroende resten av ditt liv.

**Den Avvisade Användare**

De kräver rätten till dagligdags orgasm, men deras sexpartner uppfyller inte alltid det kravet. Till en början använder de internetporr för att fylla tomrummet, men när de åker nedför den upphetsande "vattenrutschkanan" är de fångade i en cykel av nyhetens behag, chock, supernormala bilder osv. I själva verket gillar de sin partners avvisande då det ger dem en ursäkt. Om internetporren nu ger dig så mycket, varför då ha en partner överhuvudtaget? Släpp henne fri i stället. Användarna njuter inte ens av sittningar när de måste "bära" sin partner i tankarna. Vid någon tidpunkt letar de efter sin partner i det verkliga livet för att ge dem en ursäkt för att ge sig ut i internets mörka dalar.

**Porrdiet-användaren**

Även känd som "*Jag kan sluta när jag vill, jag har gjort det tusentals gånger!*"

Om bantning skulle hjälpa dessa användare att komma i rätt stämning för att ragga upp partners, varför håller de då en diet som består av en sittning var fjärde dag? Ingen kan spå framtiden, så tänk om själva mötessituationen inträffar en timme efter den planerade sittningen? Om det är bra att emellanåt "rensa rören" för att lätta på spänningen, varför inte rensa rören varje dag? Det har bevisats att onani inte behövs för att hålla könsorganen friska och internetporr behövs inte alls. Även om så är fallet kommer ingen raggningsguru som har läst om de neurologiska skadorna någonsin att rekommendera att titta på superstimulerande porr. Sanningen är att de fortfarande är beroende. Även om de har blivit av med det fysiska beroendet, så finns det primära problemet med hjärntvätt fortfarande kvar. De hoppas varje gång att de ska sluta för gott, men faller snart i samma fälla igen.

De flesta användare avundas faktiskt dessa ”start-och-stoppare” och tänker på hur "lyckligt lottad" den bantare är som kan kontrollera sitt bruk. De förbiser dock att bantaren inte alls kontrollerar sitt bruk - när de använder önskar de att de inte gjorde det. De går igenom besväret att sluta, börjar sedan känna sig depriverade och faller i fällan igen och önskar att de inte hade gjort det. De får det värsta av två världar. Om man tänker efter är detta sant i användarnas liv när de tillåts ha en session - de tar det som en rättighet eller önskar att de inte hade gjort det. Det är bara när de berövas som porren blir värdefull. Syndromet med den "förbjudna frukten" är ett fruktansvärt dilemma för användarna. De kan aldrig vinna eftersom de mår dåligt av en myt, en illusion. Det finns bara ett enda sätt för dem att vinna, nämligen att sluta tjura genom att sluta med porr!

**"Jag tittar bara på statisk/tam/hemmagjord porr"-Användaren **.

Ja, alla gör detta till en början, men är det inte fantastiskt hur det genomsnittliga chockvärdet av dessa klipp verkar öka snabbt, och innan vi vet ordet av känner vi oss berövade (tolerans)? Nyheten saknas med statisk porr, så vi betalar för en kopp fett och åker nerför vattenrutschbanan mot förbittring och skuld. Det värsta du kan göra är att använda din partners bilder (med godkännande förstås) för onani. Varför? Därför att du i processen omkopplar din hjärna för de sökande, letande och variationsinducerade dopaminrusningarna. Kemiskt sett byggs porrvattenrutschkanorna i hjärnan upp av DeltaFosB, så du kommer att få svårigheter när du är med dem i realtid.

En annan fälla i denna kategori är "amatörporr" och "hemgjord" porr. De flesta är förfalskningar och det vet du, och du kommer inte heller att sluta vid den första som du ser utan fortsätter att söka och leta. Kom ihåg att det inte bara är orgasmen som hjärnan söker, utan även nyheten i jakten som ger vattenrutschkanan sin spänning. Det är inte porrinnehållet som är problemet - oavsett om det är amatör eller professionellt - utan det är dopaminströmmarna i hjärnan som leder till att tolerans och mättnad byggs upp. Porr förstör den normala hjärnverksamheten, onani förvirrar muskel-hjärnans reaktion, orgasm översvämmar hjärnan med opioider och gör det lättare att följa vägen nästa gång.

**"Jag har slutat, men tittar ibland"-Användaren **.

På sätt och vis är de som tittar en gång de mest patetiska av alla. Antingen går de genom sina liv och tror att de är berövade, eller oftare blir en tillfällig titt två. De glider nerför den slippriga backen och faller förr eller senare tillbaka till att bli tunga användare. De har återigen fallit i samma fälla som de föll i från början.

Det finns två ytterligare kategorier av tillfälliga användare. Den första är den typ som onanerar till bilder eller klipp av de senaste sexfilmerna från kändisar som kommit på nyheterna, eller något som de "tagit med sig hem" från en "oavsiktlig" visning i skolan eller på jobbet. Dessa personer är egentligen bara icke-användare, men de känner att de går miste om något. De vill vara en del av kakan, och de flesta av oss börjar på detta sätt. Nästa gång, lägg märke till att kändisen i din fantasi efter ett tag inte längre gör det för dig. Ju mer "ouppnåelig" målet för din fantasi är, desto mer frustrerande blir orgasmens tillbakadragande.

Den andra kategorin har fått uppmärksamhet på senare tid och beskrivs bäst genom att beskriva ett fall som delas på nätet.

En professionell kvinna hade läst porrhistorier på internet i många år och läste en varje kväll, varken mer eller mindre. I övrigt var hon en mycket viljestark kvinna. De flesta användare skulle undra varför hon överhuvudtaget ville sluta - gärna genom att påpeka att det inte fanns någon risk för PIED, eller PE i hennes fall (osant). Hon använde inte ens statiska bilder, historierna var mycket tamare än allt material som de själva använder dagligen.

De gör misstaget att anta att tillfälliga användare är lyckligare och mer kontrollerade. De kanske har mer kontroll, men de är definitivt inte lyckliga. I kvinnans fall var hon varken nöjd med sin partner eller riktigt sex, och mycket irriterad när hon reagerade på sin dagliga stress och påfrestningar. Hennes närmaste kunde inte förstå vad det var som störde henne. Även om hon övertygade sig själv om att inte vara rädd för sin användning genom rationalisering, fann hon sig fortfarande oförmögen att njuta av riktiga relationer som undantagslöst innebär upp- och nedgångar. Hennes belöningscentrum i hjärnan kunde inte använda sig av de normala avstressningsmedel som finns i livet till följd av den dagliga dopaminöverströmningen. Den efterföljande nedregleringen av hjärnans receptorer hade gjort henne melankolisk under de flesta omständigheter. Som de flesta hade hon en stor rädsla för porrens mörka sidor och behandlingen av kvinnor - före sin första gång. Så småningom föll hon offer för samhällets hjärntvätt och provade sin första webbplats. Till skillnad från de flesta som kapitulerar och blir kedjeanvändare - när hon såg de vidriga våldsfilmerna - stod hon emot glidningen.

Det enda man någonsin njuter av i porr är att avsluta det begär som startade innan, oavsett om det är det nästan omärkbara fysiska begäret eller den mentala tortyren av att inte få klia på klådan. Internetporren i sig själv är ett gift, vilket är anledningen till att man bara lider av illusionen att njuta av den efter perioder av avhållsamhet. På samma sätt som med hunger eller törst gäller att ju längre man lider av det, desto större är nöjet när det äntligen är lindrat. De gör misstaget att tro att porr bara är en vana och tänker: "*Om jag kan hålla det nere på en viss nivå eller bara vid speciella tillfällen kommer min hjärna och min kropp att acceptera det. Då kan jag fortsätta att använda på den nivån eller minska den ytterligare om jag vill.*".

Få det klart för dig att "vanan" inte existerar. Porr är drogberoende, där den naturliga tendensen är att lindra abstinensbesvären, inte att uthärda dem. För att hålla det på den nivå du befinner dig på för närvarande skulle det krävas att du utövar enorma mängder disciplin och viljestyrka resten av ditt liv; när hjärnans belöningscentrum blir immunt mot dopamin och opioider vill det ha mer och mer, inte mindre och mindre.

Allteftersom porren förstör ditt nervsystem, ditt mod, ditt självförtroende och din impulskontroll blir du alltmer oförmögen att motstå minskandet av intervallet mellan varje sittning. Det är därför man i början kan ha det eller vara uta det. Om vi får tecken på att något är fel mentalt eller fysiskt slutar vi bara. Avundas inte denna kvinna, när man bara tittar en gång var tjugofjärde timme verkar det vara det mest värdefulla på jorden, vilket gör porr till en "förbjuden frukt". I många år har denna stackars kvinna varit i centrum för en dragkamp.

Hon kunde inte sluta använda, men var rädd för att eskalera till att streama porr. Under tjugotre timmar och tio minuter av var och en av dessa dagar var hon tvungen att kämpa mot frestelsen och bristen på känslor för sin pojkvän. Det krävdes en enorm viljestyrka för att göra det hon gjorde, vilket till slut fick henne att gråta. Sådana fall är sällsynta, men se det logiskt: Antingen finns det en genuin krycka eller njutning i porr eller så finns det inte. Om det finns, vem vill då vänta en timme, en dag eller till och med en vecka? Varför skulle man under tiden vara berövad på denna krycka eller njutning? Om det inte finns någon genuin krycka eller njutning, varför bry sig om att besöka ditt harem på nätet?

Här är ett annat fall av en 1-gång-på-fyra-dagar-man som beskriver sitt liv på följande sätt:

> "*Jag är fyrtio år, jag har lidit av PIED (porrinducerad erektil dysfunktion) med riktiga kvinnor och även när jag använder porr, vilket är det mesta av tiden. Det var ett tag sedan jag fick full erektion. Innan jag började med porrdiet en gång i fyra brukade jag sova gott hela natten efter min session. Nu vaknar jag varje timme på natten och det är allt jag kan tänka på. Till och med när jag sover drömmer jag om mina favoritklipp. Dagarna efter min planerade session känner jag mig ganska nere, eftersom dieten tar all min energi. Min bättre hälft lämnar mig ifred eftersom jag är har så hetsigt humör och om hon inte kan åka iväg så vill hon inte ha mig i huset. Jag ger mig ut och joggar men mitt sinne är besatt av porren.*
>
> **På den planerade dagen börjar jag planera tidigare på kvällen och blir väldigt irriterad om något förhindrar mina planer. Jag låter bli samtal och ger efter (för att senare ångra mig) på jobbet och hemma. Jag är inte någon som argumenterar, men jag vill inte att ämnet eller samtalet ska hålla mig nere. Jag minns tillfällen då jag initierade dumma bråk med min bättre hälft. Jag längtar efter klockan tio och när timmen är slagen skakar mina händer okontrollerat. Jag börjar inte gärningen direkt. Eftersom det har lagts till nya videor så "shoppar jag runt". Min hjärna förklarar för mig att eftersom jag har svultit mig själv i fyra dagar så förtjänar jag ett "speciellt" klipp som är värt den tid som jag lägger ner på att leta. Så småningom nöjer jag mig med en eller två, men jag vill att det ska vara nog för att "överleva" i nästkommande fyra dagar. Så jag tar mer tid på mig för att slutföra gärningen.*"  

Förutom sina andra problem har den här stackaren ingen aning om att han behandlar sig själv med gift. Först drabbas han av "syndromet med förbjuden frukt" och sedan tvingas hans hjärna att spola dopamin. Jämförelsevis är hans dopaminreceptorer inte lika nedskurna, men han smörjer porrens vattenrutschkanor, söker, nyhet, variation, chock och ångest för att överleva de kommande fyra dagarna. Du föreställer dig förmodligen den här mannen som en patetisk imbecill, men så är det inte. Som en före detta idrottsman som blev en före detta sergeant i marinkåren ville han aldrig bli beroende av någonting. När han återvände från kriget utbildade han sig till IT-tekniker i ett rehabiliteringsprogram för veteraner. 

Väl i det civila arbetslivet blev han en välbetald IT-tekniker på en bank och fick en laptop som han kunde ta med sig hem. Det var samma år kända societetsmedlemmar "läckte" sina porrvideor på nätet och som det snackades mycket om. Han blev sedan beroende och tillbringade resten av sitt liv med att betala för det och förstöra sig själv fysiskt och psykiskt. Om han hade varit ett djur skulle samhället för länge sedan ha gjort slut på hans lidande, men vi tillåter fortfarande att mentalt och fysiskt friska unga tonåringar blir beroende. Du tycker kanske att den här historien är överdriven, men detta fall - även om det är extremt - är långt ifrån unikt. Det finns tiotusentals liknande historier. Tror du att hans vänner och bekanta avundades honom för att han bara kollade porr en gång på fyra dagar? Tror du att detta aldrig skulle kunna hända dig? **sluta lura dig själv.**

**DET HÄNDER REDAN.**

Liksom andra missbrukare är porranvändare notoriska lögnare, även för sig själva. Det måste de vara. De flesta tillfälliga användare tittar betydligt mer och vid fler tillfällen än de vill erkänna. I många samtal med så kallade "två gånger i veckan"-användare erkänner mer än tre eller fyra tillfällen den veckan. Berättelser från tillfälliga användare på Reddit, NoFap och forum för reboot visar att de antingen räknar dagar eller förväntar sig själva att misslyckas. Du behöver inte avundas tillfälliga användare. Du behöver inte heller använda porr, livet är oändligt mycket härligare utan det. Ta följande inlägg:

"*Det började med en enkel utmaning att inte röra mig själv där nere på en dag. Jag tänker inte längre på onani, det finns inte för mig. Det är möjligt, det lovar jag dig. De rikedomar som väntar de som slutar är otroliga.*"

Tonåringar är generellt sett svårare att bota. Det är inte för att de tycker att det är svårare att sluta, utan för att de inte tror att de är beroende, eller befinner sig i början av ett missbruk. De lider av vanföreställningen att de har slutat före det andra stadiet.

Föräldrar till barn som avskyr internetporr bör inte ha en falsk känsla av trygghet. Alla barn avskyr porrens mörka sidor innan de blir beroende. 

Föräldrar till barn som avskyr internetporr ska inte känna sig trygga. Alla barn ogillar porrens mörka sidor innan de blir beroende. En gång i tiden gjorde du det också. Låt dig inte heller luras av skrämselkampanjer, fällan är densamma som den alltid varit. Barn vet att internetporr är en supernormal stimulans, men de vet också att ett "besök" eller en "titt" inte räcker. I något skede kan de påverkas av en partner, klasskamrat eller arbetskamrat.

Bli inte självbelåten i denna fråga. Samhällets misslyckande att förhindra ungdomar från att bli beroende av internetporr och andra droger är kanske den mest oroande aspekten av detta beroende. Ungdomars hjärnor är betydligt mer plastiska, och det är nödvändigt att utbilda och skydda dem. 

Om du är osäker på var du ska börja kan du bland annat använda boken Your Brain On Porn för att lära dig om neurovetenskapen. Även om du misstänker att din tonåring kanske redan är beroende ger boken grundläggande förståelse för att hjälpa någon att fly. Jag rekommenderar den här boken!
