# YouTube-, Twitch- och Instagram-användaren

Den här användaren bör delas in i samma grupp som de tillfälliga användarna, men de lömska effekterna förtjänar ett eget kapitel. De leder till kollaps av själkontrollen, vilket gjorde att en NoFap-forumanvändare höll på att splittras:

> *"Jag befann mig tre veckor in i ännu ett av mina misslyckade försök att sluta, vilket utlöstes av min frus oro över mina opålitliga stånd och bristande sexlust. Jag sa att det inte berodde på henne, utan bara på stressen på jobbet. Hon sa: " Jag vet att du har klarat av stressen på jobbet förut, men vad skulle du känna om du var jag och var tvungen att se någon du älskar systematiskt krossar sig själv?". Det var ett oemotståndligt argument, och därför ville jag sluta. Hon vet att jag inte är otrogen, men detta är på sätt och vis ännu värre. Försöket avslutades efter tre veckor och kulminerade i ett hätskt gräl med en gammal vän. Jag insåg inte förrän flera år senare att mitt försåtliga sinnelag medvetet hade utlöst bråket. Vid den tidpunkten kände jag mig rättmätigt upprörd, men det var nog ingen slump då jag aldrig tidigare, och inte heller sedan dess, har bråkat med den här vännen. Det var uppenbart att det lilla monstret var i farten.*
>
> * Oavsett vad så hade jag min ursäkt. Jag var i desperat behov av utlösning och det kvittade hur. Eftersom min fru inte var sugen och jag kände mig "berättigad", så övertygade jag mig själv om att det vore i sin ordning om jag "begränsade" mig genom att undvika porrsidor och bara titta på YouTube-videor. Min fru ändrade sig dock under kvällen och ville ha sex, men jag var trött och saknade mina "hästkrafter", så jag låtsades ha huvudvärk. Jag kunde inte stå ut med den besvikelse som jag skulle åsamka min fru. Jag återgick sedan gradvis till mina gamla vanor och YouTube blev min nya haremsdestination. Jag var vid tillfället ganska så nöjd och trodde att det åtminstone minskade min konsumtion. Hon anklagade mig så småningom för att ha fortsatt ignorera henne i sängen. Jag insåg det inte, men hon berättade om de gånger jag skapat gräl och stormat ut ur huset. Vid andra tillfällen där jag tog två timmar på mig för att köpa en mindre pryl eller fejkade stukningar. Jag använde usla ursäkter för att slippa uppvakta henne, så när jag har ett pålitligt harem på nätet är det ännu svårare." *

Det sämsta med YouTube-användaren är att den stöder villfarelsen att de blir berövade. Det orsakar samtidigt en stor försämring av sin självrespekt; en vanligtvis ärlig person tvingar sig själv att lura sin älskade. Det har förmodligen hänt dig, eller händer dig fortfarande, på något sätt.

Problemen med webbplatser som Twitch, Instagram, TikTok, Twitter (de flesta sociala medier) drivs i huvudsak av komplettering. Pådrivna av nyhetssökande dopaminbegär så lurar de sig själva till att tro de befinner sig på en säker sajt. Kom ihåg att spänningen ligger i att söka, inte i att döda, och det lilla monstret skiter i varifrån det får sin "fix". För användaren ger det "mjuka" innehåll de får i sina olika flöden tillfällig lindring av abstinensbesvären, och håller dem fast i väntan på nästa session.

Modellen på bilden/videon är förvisso vacker, och hon skulle säkert ge dig njutning om du hade henne vid din sida, men bilden kan inte det... Den är helt enkelt inte verklig. Din hjärna har blivit lurad likt en tjur som rusar in i en röd kappa, som efteråt inte förstår varför den gjorde det. Man skulle kunna tro att du bara kan titta på de här bilderna utan att onanera. Men kom ihåg att hjärnan är beroende av de obegränsade nyheterna, och att det lilla monstret struntar i varifrån fixen kommer. Det är samma fälla.

Du har kanske sett tv-serien Columbo där temat i varje avsnitt är snarlikt. Skurken, vanligen en rik och respekterad affärsman, är övertygad om att han har begått det perfekta mordet och hans självförtroende att hans brott inte kommer att avslöjas förstärks när han får veta att den ganska ruffiga och föga tilltalande detektiven Columbo ansvarar för fallet.

Columbo har en frustrerande vana att stänga dörren när han har avslutat sitt förhör och försäkrat den misstänkte om att denne är oskyldig. Men precis innan mördarens nöjda blick har försvunnit så kommer Columbo tillbaka och säger: "*En liten sak bara, sir, som ni säkert kan förklara...*". Den misstänkte stammar och vet att Columbo nu successivt kommer att trötta ut honom. Hur avskyvärt brottet än var, så var sympatierna från och med den stunden hos mördaren.

Dessa attacker liknar varandra. Spänningen i att inte tillåtas överskrida den röda linjen för att få den porrfix de "rättmätigt förtjänar" och sedan undra var njutningen låg när gärningen är fullbordad. Rädslan för att gå över gränsen, förlora kontrollen och återvända till sängen, bara för att bli förföljd av rädslan att ens partner vill ha sex. De "säkra" YouTube-videorna kommer inte att tillfredsställa dig längre på grund av desensibilisering, brist på nyheter och den bestämda vetskapen om att du förr eller senare kommer att besöka ditt favoritharem på nätet. Den ultimata förnedringen och skammen kommer när denna visshet blir verklighet, följt av en omedelbar tillbakagång till kedjetittande.

**OH, VAD HÄRLIGT ATT VARA PMO:are!**
