# A social habit?

Health of the mind and body are the primary reasons for we *should* want to stop -- but then, they always have been. We don't actually need scientific research and knowledge in neuroscience to tell us porn is addictive and can potentially shatter our lives. These bodies of ours are the most sophisticated objects on the planet, and any user knows from the first session that the stimulus can go to excess and turn poisonous.

The only reason why we ever get involved with porn is the cycle's overlap with our evolutionary programming. Internet porn is highly available, free and streaming twenty-four hours a day. Porn was once considered harmless, but that was when the images were static, and videos involved a trip to the local store for a VHS tape.

Today, it's generally considered -- even by users themselves -- that porn is a supernormal stimulus and addiction forming. In the old days, the strong man didn't admit that he masturbated, with jerk being a derogatory term. In every pub, club or bar, the majority of men would be proudly wanting to take a woman home and have real sex. Today, the position is completely reversed for the internet porn addict, today's man realises that he's beginning to feel he doesn't need a woman. Banding together online, he discusses experiences, devises strategies and explores options. Today's strong man doesn't want to depend on drugs. Through social revolution, all users are giving serious thought to stopping internet porn and masturbation. Today's users consider porn a useless and harmful activity.

The most significant trend noticed on forums is the increasing emphasis on the anti-social aspects of porn, the days when a man boasted of having sex and orgasms every day is slowly being replaced with realisation of slavery to the porn monster.

The only reason why people continue after being educated is because they've failed to stop or are too frightened to try. There's a wide spectrum of interest in the subject, some abstaining from porn, masturbation and orgasm -- with or without partners. Practices that separate the tantric and propagative parts of sex such as semen retention and Karezza are discussed and adopted in droves. # En social vana?

Hälsa för kropp och själ är den främsta anledningen till varför vi *borde* vilja sluta - men så har det alltid varit. Det behövs i själva verket ingen forskning eller neurovetenskaplig kunskap för att förklara porrens beroendeframkallande natur och att den har potentialen att ödelägga våra liv. Människokroppen är planetens mest sofistikerade föremål, och alla användare vet redan från första sittningen hur kraftigt stimulansen kan gå till överdrift och bli giftig.

Enda anledningen till att vi överhuvudtaget blir engagerade av porr är att cykeln överlappar med vår evolutionära programmering. Internetporren är högst lättillgänglig, kostnadsfri och finns tillgänglig tjugofyra timmar om dygnet. En gång i tiden ansågs porren vara ofarlig, men då var bilderna statistiska och ville man se en video krävdes det en tur till den lokala videobutiken.

Numera anses det allmänt -- till och med av användarna själva -- att porr är en supernormal stimulans och beroendeframkallande. Förr i tiden erkände inte en stark man att han onanerade, och "jerk" var en nedsättande term. På alla pubar, klubbar och barer skulle största delen av männen stolt vilja ha med sig en kvinna hem och ha riktigt sex. I dag är läget det omvända för missbrukaren av nätporr. Idag börjar männen känna allt mer att de inte behöver några kvinnor. På nätet slår de sig samman och diskuterar erfarenheter, utarbetar strategier och utforskar alternativ. Dagens starka man vill nämligen inte bli beroende av droger. Genom en social revolution överväger alla användare på allvar att sluta med internetporr och onani. Användarna av idag betraktar porren som en onödig och skadlig aktivitet.

På olika forum har man noterat att den främsta trenden är den ökande uppmärksamheten på porrens antisociala effekter. Tiden då en man skröt om att ha sex och orgasmer varje dag ersätts långsamt med en medvetenhet om slaveriet under porrmonstret.

Enda anledningen till att folk fortsätter efter att ha upplysts är att de har inte lyckats sluta eller att de är alltför rädda för att ens försöka. Intresset för ämnet är brett, vissa avstår från porr, onani och orgasm -- såväl med som utan partner. Praktiker som separerar sexets tantriska och fortplantningsmässiga delar, såsom spermaretention och Karezza, diskuteras och accepteras i mängder. Många av de ovannämnda misslyckandena är i själva verket fall framåt, vilket i viss mån gynnar de som försöker. När du väl börjar vandra no-PMO-vägen finner du snart det som passar bäst för ditt liv. Du uppmuntras att utforma din egen plan för orgasm när väl du har förstått och börjat praktisera sexuell separation. Vilken väg du än väljer så kommer du se värdet av att begränsa antalet gånger du dränker din hjärna i orgasmframkallade kemikalier, och att aldrig mer betrakta porr, sex och orgasm som njutning eller som en krycka för ditt emotionella jag.

Diverse populära, av icke-användare grundade, gemenskaper på nätet är dedikerade till att inte bara sluta med porr utan även med onani. Dessa sidor är trots allt gynnsamma för de som försöker bryta sig loss, men de flesta råder dig att sluta genom viljestyrka. Konsekvensen av besattheten av att räkna dagar och andra mått är självömkan och utebliven glädje. Till största delen lever hjärntvätten kvar och frodas. Till slut knäcks någon och en dominoeffekt uppstår där andra användare upptäcker att de inte är ensamma. Deras insatser är dock inte förgäves. De går framåt, även om det sker med stora mängder självplågeri när de lyckas släcka sina webbläsare, men inte lusten eller behovet. EasyPeasy fungerar omvänt, det släcker behovet och önskan först, sedan webbläsaren. Fler och fler användare överger det sjunkande skeppet varje dag och de som blir kvar är skräckslagna för att de ska bli lämnade kvar.

** LÅT INTE DET BLI DU!**
