# Tajming

Bortsett från det självklara att porr inte är dig till gagn och att det är hög tid att sluta, så är tajmingen viktig. Samhället betraktar lättsinnigt internetporren som en lätt osmaklig ovana som ändå är oskadlig för hälsan. Det är inte sant. Det är ett drogmissbruk, en sjukdom som ödelägger relationer. Det värsta som inträffar i merparten av användarnas liv är att de fastnar i detta hemska beroende. Och om de förblir beroende så händer hemska saker. Därför är tajmingen viktig för att ge dig själv möjligheten till ett ordentligt botemedel.

Identifiera först och främst de tillfällen då porr tycks vara av betydelse för dig. Om du som affärsman använder porren för illusionen av stresslindring - välj då en relativt lugn period eller en semester. Om du huvudsakligen använder porr under tråkiga eller avslappnande perioder gäller motsatsen. Oavsett vilket, ta ditt försök på allvar och gör det till det allra viktigaste i ditt liv.

Blicka framåt under en treveckorsperiod och försök förutse alla händelser som skulle kunna innebära att du misslyckas. Tillfällen som konferensresor, att din partner är bortrest osv. ska inte behöva avskräcka dig under förutsättning att du förutser dem i förväg och att du inte tror att du kommer att känna dig berövad porren. Försök under tiden att inte att skära ner då det enbart skapar illusionen att det är angenämt att bli nekad. I själva verket gör det dig tvungen att titta på och ha så många porrsittningar som möjligt. Under din sista sittning så var uppmärksam på besvikelsen till följd av mättnad, ouppfyllda förväntningar, kroppslig smärta, eventuella abstinensbesvär, peppighet och melankoli. Betänk istället hur underbart det blir när du tillåter dig själv att sluta med det.

**VAD DU ÄN GÖR, FASTNA INTE I FÄLLAN GENOM ATT SÄGA: "INTE NU, SENARE" OCH SEDAN GLÖMMA BORT DET. UTFORMA DIN TIDSPLAN NU OCH EMOTSE DEN MED TILLFÖRSIKT.**

Kom ihåg: *Du ger inte upp någonting*. Du kommer tvärtom att uppleva fantastiska positiva vinster.

Läkarkåren har under flera år betraktat porren som ofarlig utan att kunna särskilja den tama statiska porren från förr och den senaste streamingupplevelsen i virtuell verklighet. Problemet är att även om alla användare konsumerade internetporr enbart för att lindra dopaminbegäret som den orsakar, så är det inte beroendet av dopamin som får användaren att fastna. Det är snarare den självhjärntvätt som uppstår till följd av beroendet som får användaren att bli fast. En intelligent person kan luras av ett förtroendeknep, men bara en dåre skulle fortsätta låta sig luras när han inser att det är ett trick. Lyckligtvis är de flesta användare inte dårar; de bara tror att de är det. Varje enskild användare hjärntvättar sig själv på sitt eget sätt. Av den anledningen tycks det finnas så många olika typer av missbrukare, vilket bidrar till att ytterligare öka mystiken kring det.

Även om den ursprungliga bokens fördel var att sluta med nikotin (en av de snabbaste och mest beroendeframkallande drogerna som vi känner till), så var det en behaglig överraskning att inse att den filosofi som framförs i den fortfarande är vettig när den anpassas till porr. Den samlade kunskap och utmaning som Carr och jag själv har tagit oss an är hur man bäst förmedlar denna kunskap till varje enskild användare. Att jag vet att alla användare kan tycka att det är enkelt att sluta, och faktiskt kan njuta av processen är inte bara meningslöst utan också ytterst frustrerande om man inte lyckas få användaren att inse det. I sin ursprungliga bok förklarar Allen Carr sitt omstridda råd:

>"Många människor har sagt till mig: *'Du säger: 'Fortsätt röka tills du har läst ut boken'.' Det brukar få rökaren att ta lång tid på sig att läsa boken eller att helt enkelt inte läsa ut den. Punkt slut. Du borde därför ändra instruktionen.'* Det låter logiskt, men jag vet att om instruktionen hade varit: *'Sluta genast'* skulle vissa rökare inte ens börja läsa boken. Jag hade en rökare som konsulterade mig i början. Han sa: *'Jag är verkligen ledsen över att behöva söka din hjälp, jag vet att jag är viljestark. På alla andra områden i mitt liv har jag kontroll. Hur kommer det sig att alla dessa andra rökare slutar med hjälp av sin egen viljestyrka, men att jag ändå måste komma till dig? "* Han fortsatte: *'Jag tror att jag skulle kunna göra det själv, om jag kunde röka medan jag gjorde det.'\"*

Samhällets synsätt föreskriver det otroligt svåra i att sluta röka, och vad behöver en rökare när något känns svårt? Hen behöver sin lille vän, sin krycka. Att sluta röka verkar vara ett dubbelt dråpslag. Inte nog med att det finns en komplicerad uppgift att utföra -- vilket är svårt nog -- men den krycka man normalt förlitar sig på vid sådana tillfällen finns inte tillgänglig. Kanske är det verkligt fina med denna metod att du inte behöver "ge upp" någonting medan du genomgår processen; istället gör du dig av med alla rädslor och tvivel i början, så när du avslutar den sista sittningen njuter du redan av friheten.

Därför kommer den här boken att hålla samma råd intakt. Oavsett hur ofta man säger att det kommer att bli enkelt och roligt kommer det att finnas en stor majoritet som inte kommer att kunna acceptera det på grund av personlig hjärntvätt om hur svårt det är att sluta.

Timing is the only chapter that causes me to question Allen's original advice seriously. Above all, if triggers include office stress, then picking a holiday to make an attempt and vice versa. This isn't the easiest way, instead picking what you consider to the most *difficult* time. Whether that's stress, social obligations, concentration or boredom, once you've proven you cope with and enjoy life in the worst situations, every other one is enjoyable. But if that was the advice, would you even make the attempt?

Here's an analogy, my sister and I intend to swim together. We arrive at the pool at the same time, but rarely end up swimming together. The reason being that she immerses one toe and half an hour later is actually swimming. That's slow torture, I know in advance that at some stage, no matter how cold the water is, I'll have to brave it at some point. So I've learned to do it the easy way: Diving straight in. Now, imagine if I was in a position to insist that if she didn't dive straight in, she couldn't swim. If that was the case, she wouldn't swim at all. Do you see the problem?

Tajming är det enda kapitlet som får mig att ifrågasätta Allens ursprungliga råd på allvar. Framför allt rået att om den utlösande faktorn är stress på jobbet, så välj en helgdag för att göra ett försök och vice versa. Det här är inte det enklaste tillvägagångssättet. Välj i stället det du anser vara den *svåraste* tiden. Vare sig det är stress, sociala förpliktelser, koncentration eller tristess -- när du väl har bevisat att du hanterar och njuter av livet i de värsta situationerna är alla andra situationer njutbara. Men om det var rådet, skulle du då ens anstränga dig?

Jag har en analogi: Min syster och jag har för avsikt att simma tillsammans. Vi kommer till bassängen samtidigt, men kommer sällan att simma tillsammans. Anledningen till det är att hon doppar en tå och först en halvtimme senare är hon i vattnet och i färd med att simma. Det är långsam tortyr. Jag vet i förväg att jag oavsett hur kallt vattnet måste trotsa det vid förr eller senare. Så jag har lärt mig den enkla metoden: Att dyka rakt ner i vattnet. Föreställ dig nu om jag kunde insistera på att om hon inte dyker rakt ner så kan hon inte simma. Om så vore fallet så skulle hon inte simma överhuvudtaget. Kan du se problemet?

Enligt feedback har många användare tillämpat det ursprungliga rådet om tajming att fördröja det man tror blir den "onda dagen". Jag tänkte använda en liknande teknik som i kapitlet om "porrens fördelar", något i stil med - *"Tajmingen är mycket viktigt och i nästa kapitel kommer du att informeras om den bästa tidpunkten att sluta."* och på nästa sida bara skriva ett stort *"NU!"* Det är egentligen det bästa rådet, men skulle du följa det? Fällans kanske mest subtila aspekt är att när vi upplever verklig stress i våra liv så verkar det inte vara rätt tillfälle att sluta, men i de perioder vi inte upplever stress så önskar vi inte att avsluta tortyren. Fråga dig själv följande frågor:

1.  När du för första gången började med porr, bestämde du dig verkligen för att du skulle fortsätta att vara beroende av det resten av livet utan att någonsin kunna sluta? ***Självklart gjorde du inte det!***

2.  Kommer du att fortsätta resten av ditt liv utan att någonsin kunna sluta? ***Självklart inte!***

Så när ska du sluta då? I morgon? Nästa år? Året därpå? Är det inte vad du har frågat dig själv sedan du först insåg att du faktiskt är beroende? Hoppas du att du en morgon ska vakna upp och bara inte vilja titta längre? Sluta lura dig själv! Precis som med alla typer av missbruk blir du successivt mer beroende, inte mindre. Tänker du vänta tills du känner att det är lättare att stanna kvar i sängen och runka istället för att bara gå upp? Det vore en smula meningslöst.

Den verkliga fällan är övertygelsen om att det inte är rätt tidpunkt just nu -- det kommer alltid att vara lättare i morgon. Vi upplever att vi lever stressiga liv, men det gör vi i själva verket inte. Den mesta verkliga stressen har avlägsnats från våra liv. När man lämnar huset går man inte i rädsla för att bli attackerad av vilda djur, de flesta undrar inte när eller varifrån deras nästa måltid ska komma, eller om de kommer att hitta tak över huvudet ikväll. Sätt dig in i ett vilt djurs liv. Varje gång en kanin lämnar sin håla sätter den hela sitt liv på spel. Men kaninen kan hantera det, eftersom den har adrenalin och andra hormoner. Det har vi också. De stressigaste perioderna i alla djurs liv är den tidiga barndomen och ungdomsåren. Men tre miljarder års naturligt urval har rustat oss för att kunna hantera stress, och många som växer upp med en svår barndom lever normala liv.

Det är en klyscha att säga: *"Om du inte har din hälsa, har du ingenting "* men det är helt sant. När du känner dig fysiskt och mentalt stark kan du njuta av höjdpunkterna och hantera nedgångarna. Många förväxlar ansvar med stress, men ansvar blir bara stressigt när vi inte känner oss starka nog att hantera det. Det som förstör mest är inte stress, jobb eller ålderdom, utan de illusoriska förljugna kryckor vi vänder oss till.

Se det som att du redan har bestämt dig för att inte stanna i fällan resten av livet. Därför måste du någon gång -- vare sig det är lätt eller svårt för dig -- gå igenom processen att frigöra dig. Porr är varken en vana eller ett nöje. Det är ett drogberoende och en sjukdom. Vi har konstaterat att det inte blir lättare i morgon, utan snarare ännu värre. Tidpunkten för att göra sig kvitt porren är **nu** -- eller så nära nu som du kan hantera. Det är bara att tänka på hur snabbt varje vecka av våra liv går. Tänk på hur skönt det ska bli att kunna njuta av livet i övrigt utan att dessa ständigt växande skuggor hänger över dig. Om du följer alla instruktioner så behöver du inte ens vänta fem dagar eller tre veckor. Du kommer inte bara att tycka att det är lätt att sluta, **du kommer att njuta av det!**
