# Kommer jag missa det roliga?

**Nej!** När det lilla porrmonstret har dödats, din kropp har slutat sukta efter dopamin och när porrvattenrutschkanorna börjar torka ut på grund av brist på ”smörjmedel” så kommer det sista av hjärntvätten att försvinna. Du kommer känna dig bättre utrustad såväl mentalt som fysiskt att hantera stressen och livets kval, och inte nog med det så kommer du njuta av livets goda fullt ut.

Det finns endast en fara och det är infytande hos de som fortfarande använder porr som en krycka eller för njutnings skull. *’Gräset är alltid grönare på andra sidan’* är en vanligt förekommande och förståelig inställning. Hur kommer det sig att ex-användare avundas de som fortfarande behöver sex och pornografi som en krycka?

Det är ganska rimligt att vi genom all hjärntvättning vi har utsatts för sedan barndomen har fastnat i porrfällan. Hur kommer det sig då – efter att ha insett vidden av bajsmacka som porren är och lyckats sluta med den – att vi går rakt i samma fälla igen? Det är tack vare den allmänna hjärntvätten som förväxlar porren med sex och som presenteras som fullt normalt. Ex-användaren får abstinens! Den tomma, osäkra känslan av att vara singel (vilket inte är ett brott) uppbådar ångestkänslor som driver dem att åka nedför vattenrutschkanan. Det är en lustig avvikelse, speciellt om man begrundar observationen: Inte bara är alla icke-användare helnöjda med att vara just det, utan också önskar världens alla användare dessutom, sitt sjuka, beroende, hjärntvättade sinne till trots att aldrig hade fastnat från första början. Så varför avundas en del icke-användare?

1.  Bara en titt. Kom ihåg, det existerar inte! Sluta titta på den isolerade händelsen och rikta i stället blicken porranvändaren. Se det ur dennes synvinkel. Du må avundas honom, men han accepterar inte sig själv, utan avundas istället dig. Om du bara kunde studera en annan användare så skulle det vara det mest kraftfulla sättet att bli kvitt avundsjukan. Ser hur kvickt han öppnar mängder av flikar och webbläsarfönster? Hur han snabbspolar fram till de viktiga bitarna, hur snabbt han tröttnar på videorna och tar sig genom alla genrer som erbjuder nyheter, chock och ångest, osv. Notera också hur agerandet verkar ske per automatik. Kom ihåg att det inte njuter av det, det är bara det att de inte kan njuta av sig själva utan det. nästa morgon vaknar det med en svagare vilja, mindre energi och suddig blick och måste fortsätta självbefläcka sig vid minsta stress och motgång. De går ett liv av snusk, mental ohälsa och dåligt självförtroende till mötes. Ett liv av självutplåning med svarta skuggor konstant i huvudet. För vad? En illusion att du får det du ”förtjänar” och lite jävla njutning?

2.  Andra anledningen några ex-användare får abstinensbesvär är för att porranvändare ägnar sig åt något – som egennjutning – och icke-användare inte gör det och tenderar därför att känna sig berövad. Få det klart för dig, det är inte icke-användaren som blir berövad, utan missbrukaren som blir berövad av:

	–	Hälsa

	-	Energi

	–	Självförtroende
	
	–	Sinnesro

	–	Kurage

	-	Lugn

	-	Frihet

	-	Självrespekt

Sluta avundas porranvändare och börja se dem som de olyckliga, patetiska varelser de verkligen är. Jag vet, jag var en gång i tiden en av de värsta. Just därför läser du den här boken och inte de som inte kan möta verkligheten och som fortsätter lura sig själva.

Du skulle aldrig avundas en heroinmissbrukare och precis som alla sorters drogberoenden så kommer ditt inte att bli bättre. Det kommer år för år bli exponentiellt sämre och om du inte gillar att vara en användare i dag så kommer du ogilla det ännu mer i morgon. Avundas aldrig andra användare, tyck synd om dem. Tro mig: ***De behöver ditt medlidande!***

