# Kan jag dela upp det i avdelningar?

Denna myt sprids främst av användare som försöker sluta med hjälp av viljestyrka och som utför mentala kullerbiyttor och påbörjar en Dr Jekyll och Mr Hyde-rutin: "* Porr är till för mitt alter ego och riktig romantik är till för mina relationer*." Inget är längre från sanningen -- porrvattenrutschkanorna, DeltaFosB och de neurologiska förändringarna kommer nämligen att överrösta romantiken i det verkliga livet och göra den mindre eftertraktad. Mr Hyde kommer definitivt att köra över Dr Jekylls direktiv.

Genom att använda internetporr tränar du dig själv för rollen som en fluktare, eller så måste du ha alternativet att klicka vidare till något mer upphetsande så fort dopaminnivån sjunker. Eller så söker du ständigt efter *just* rätt scen för att få maximal effekt. Därtill onanerar du kanske i en krökt hållning eller kollar på din smartphone i sängen varje kväll, och till slut kräver du dessa signaler mer än stimuli från det verkliga livet. Sex är raka motsatsen till nästan alla aspekter av ett nätharem och har därför ingen chans när man jämför dem med varandra. Minnena som skapas i unga år är kraftfulla och långvariga, och det tar därför längre tid att bryta ner dessa porrvattenrutschbanor och programera om dem, eller skapa nya. Det innebär dock inte att det är svårare.

Varje tur du tar nedför "porrvattenrutschkanan" smörjer in den. Du låter nerverna hålla sig fräscha och redo att avfyras. När du parkerar vid en snabbmatsrestaurang stiger lukten av fritösen in i näsan på dig och i samma stund är försäljningen är redan klar. På samma sätt är porrvattenrutschkanorna i hjärnan redo för att suga in dig och håller öppet tjugofyra timmar om dygnet. Varje signal eller trigger aktiverar din belöningskrets med ett löfte om sex -- fast det är inte sex. Ändå befäster nervcellerna de här associationerna med sexuell upphetsning genom att sprätta ut nya förgreningar som förstärker kopplingarna. Ju mer du använder porr, desto starkare blir nervkopplingarna. Resultatet blir att du i slutändan kanske *måste* vara en fluktare som behöver klicka på nytt och ständigt eskalerande material, behöver porr för att kunna sova eller är tvungen att hitta det perfekta slutet för att få jobbet gjort.

Precis som med alla substanser eller beteendedroger så bygger kroppen upp en immunitet som gör att drogen slutar att lindra abstinensbesvären helt och hållet. Så fort porranvändare avslutar en sittning vill de ha en ny, och den ständiga hungern förblir omättad. Den naturliga tendensen blir då en upptrappning för att få dopaminruset. De flesta användare förhindras dock till detta på grund av en eller båda av följande anledningar.

**Pengar:** De har inte råd att prenumerera på betalporrsajter.

**Hälsa:** Kroppen klarar bara en viss mängd, antingen dopaminrusningen eller orgasmerna. Dessutom utlöser orgasmer faktiskt kemikalier för att minska dopaminflödet. Den måste göra det, det är så kroppen fungerar.

När det lilla monstret lämnar kroppen försvinner den förfärliga osäkerhetskänslan. Du återfår självförtroendet, liksom en fantastisk känsla av självrespekt, och du blir trygg i att åter ta kontrollen över ditt liv och kan använda det som en språngbräda för att ta itu med andra problem. Det är en av alla stora fördelar med att bryta sig loss från ett missbruk.

Myten om uppdelning är ett av det lilla monstrets många trick som det spelar med ditt sinne. De här tricken gör det svårare att sluta -- på grund av det svåra i att mätta den ständiga hungern -- vilket gör att många användare tar till cigaretter, börjar dricka mycket eller till och med tar hårdare droger för att tillfredsställa tomheten.

Människor är bedömningsdjur, både mot oss själva och mot andra. Att se porr tillsammans med sin partner är otillfredsställande eftersom ni båda bedömer varandras prestationer i förhållande till narrativet. Vill du ha Brad Pitt i ditt sovrum, även om det är på en affisch? Ingen enskild person kan matcha ett harem där varje "upplevelse" är gestaltad, skriven, professionellt regisserad och finns direkt atillgängligt 24 timmar om dygnet.

