# Undvik falska incitament

Många som använder sig av viljestyrka för att sluta försöker öka motivationen genom att skapa falska incitament. Det finns många exempel på det här. Ett vanligt sådant är att belöna sig med gåvor när man helt har undvikit att titta på porr under en månads tid. Det här förefaller vara ett logiskt och förnuftigt tillvägagångssätt, men det stämmer faktiskt inte. Alla användare med självrespekt skulle nämligen hellre fortsätta titta på porr varje dag, än att belöna sig själva med en egenhändigt given gåva. Användaren tvivlar då han inte bara måste avstå i *trettio dagar*, utan också är osäker på huruvida han kommer att kunna *njuta* av de porrfria dagarna. Hans enda nöje eller krycka har ju ryckts ifrån honom! Följden blir bara att uppoffringen som användaren känner att han hon gör blir ännu större, eftersom den nu är ännu mer värdefull i hans medvetande.

Andra exempel inbegriper:

- Jag ska sluta så att jag tvingas skaffa mig ett socialt liv och mer sex på riktigt.

- Jag ska sluta så att jag genom någon magisk kraft ska springa förbi konkurrenterna och få den partner jag vill ha.

- Jag ska sluta för att kunna förbinda mig till att inte slösa energi och entusiasm på porr för att odla hunger i mig själv.

Alla dessa är verkliga, kan vara effektiva och kanske får du till slut det du vill ha -- men fundera på det en stund. Får du det du ville ha så kommer du att känna dig berövad när nyheten har försvunnit; om inte så kommer du att må uselt. Du kommer förr eller senare att falla i samma fälla igen.

Att sluta med hjälp av ett falskt incitament ökar bara tvivlet, för om du inte uppnår incitamentet (och även om du gör det) så börjar du snart tänka tvivelaktiga tankar som "*Kommer det verkligen att göra mitt liv bättre om jag slutar? Om jag slutar och inte får det jag vill ha, använde jag då metoden på rätt sätt?*". Tankar som dessa ökar känslan av att du måste offra något och skapar därför abstinensbesvär.

Ett annat typexempel är pakter på nätforum vilket har fördelen att de eliminerar frestelser under vissa perioder. Dock misslyckas de i allmänhet av följande skäl:

1. Incitamentet är falskt. Varför skulle du vilja sluta bara för att andra gör det? Det enda som uppnås är att skapa ytterligare press och att känslan av uppoffring ökar. Det går bra om alla användare genuint vill sluta vid en viss tidpunkt -- men man kan inte tvinga dem att sluta, även om alla i hemlighet vill det. Tills de är beredda att göra det skapar en pakt ytterligare press som i sin tur bara ökar deras begär att titta. Det gör dem till smygtittare, vilket ytterligare förstärker känslan av beroende.

2. Att vara beroende av varandra med hjälp av viljestyrka-metoden skapar en känsla av att man genomgår en period av botgöring, under vilken de inväntar att lusten ska försvinna. Ger de efter uppstår en känsla av misslyckande. När man använder viljestyrka-metoden kommer åtminstone en av deltagarna garanterat att ge upp, vilket ger de andra deltagarna den ursäkt som de har väntat på. Det är inte deras fel, de skulle ha hållit ut men "Fred" svek dem. Sanningen är att de flesta av dem redan har fuskat.

3. Att dela med sig av äran är den omvända varianten av beroende. Det finns en fantastisk känsla av prestation när man slutar med porr och när man gör det ensam kan den hyllning man får från sina vänner och nätkompisar vara en enorm boost under de första dagarna. Men när alla gör det samtidigt måste man dela på äran, vilket gör att uppmuntran minskar.

4. Ett annat klassiskt exempel är gurulöftet. Att sluta kommer att ge dig lycka eftersom du inte längre är involverad i dragkampen, din hjärna börjar programmera om och återfår impulskontroll. Vad du dock måste komma ihåg är att du varken kommer att bli en sexgud eller vinna på lotto. Ingen annan än du själv bryr sig det minsta om att du slutar med porr. Du är inte en svag person även om du använder porr tre gånger om dagen och har PIED, och inte heller en stark person om du är missbrukare och inte gör det.

Sluta lura dig själv. Om jobberbjudandet om tio månaders arbete för tolv månadslöner per år, eller riskerna med att minska hjärnans förmåga att klara av vardaglig stress och påfrestningar, eller att sätta sig själv i konflikt med att ha en pålitlig erektion, eller livslång psykisk och fysisk tortyr och slaveri inte stoppade dem, kommer de ovan nämnda få falska incitamenten inte att göra den minsta skillnad, utan bara lyckas få uppoffringen att verka värre. Koncentrera er i stället på den andra sidan:

\"Vad får jag ut av det? Varför måste jag titta på porr?\"

Fortsätt att titta på den motsatta sidan av dragkampen och fråga dig själv vad porren gör för dig. *ABSOLUT INGENTING!* Varför måste jag göra det? *DET MÅSTE DU INTE! DU STRAFFER BARA DIG SJÄLV.* Det är Pascals vadslagning: du har nästan ingenting att förlora (avtagande upphetsning), chanser till stora vinster (full och pålitlig upphetsning, psykiskt välbefinnande och lycka) och utan risk att förlora stort.

Varför då inte berätta för nära och kära att du slutar? Jo, därför att det skulle göra dig till en stolt före detta missbrukare eller ex-användare och inte till en exalterad och lycklig icke-användare. Det kan också skrämma din partner en aning eftersom hon kanske ser det som en new age-artad plan för att få mer sex. Hon kan också frukta att du ska förvandlas till en sexmaskin, vilket är svårt att förklara om de inte är öppensinnade.

Alla försök att sluta som innebär inblandning från andra ger ännu mer makt till det lilla monstret. Genom att trycka bort det ur huvudet och ignorera det blir effekten att man anstränger sig för att *inte* tänka på det. Var i stället uppmärksam på tankarna och signalerna. Säg till dig själv *\"Bra, jag är inte längre en porrens slav. Jag är fri och lycklig över att kunna känna skillnaderna inom sex!\"* Detta kommer att stoppa syret till tanken och hindra den från att börja brinna till att bli behov och sug. I detta avseende kan det vara bra att utöva mindfulness-meditation för att hjälpa till att depersonalisera tankarna.
