# Det enkla sättet att sluta på

Det här kapitlet innehåller instruktioner om det enkla sättet att sluta med porr. Förutsatt att du följer instruktionerna så kommer du att märka att det är allt från relativt enkelt till njutbart att sluta! Om du följer instruktionerna så är det löjligt enkelt att sluta med porr. Det enda som krävs är två saker.

1. Ta beslutet att du aldrig ska titta på porr igen.

2. Misströsta inte över det, utan gläd dig.

Du undrar säkert: *Varför behövs resten av boken? Kunde du inte ha sagt det från början?*". 

"*Varför sa du inte det från första början?*" Jo, svaret är att du så småningom skulle grubbla över det och följaktligen så småningom ändrat ditt beslut. Det har du förmodligen gjort många gånger tidigare.

Som sagt, porr är en subtil och ondskefull fälla. Huvudproblemet med att sluta är inte dopaminberoendet -- vilket förvisso är ett problem, men inte det primära -- det är hjärntvätten. Därför är det nödvändigt att först förgöra alla myter och vanföreställningar. Förstå din fiende, lär känna deras taktik så kommer du lätt att besegra dem. Efter att ha lidit av en mörk depression under stora delar av mitt liv gick jag, när jag äntligen lyckades fly, direkt till noll utan ett enda dåligt ögonblick. Det var trevligt även under abstinensperioden och jag har inte haft minsta lilla abstinens sedan dess. Det var tvärtom en av de mest underbara saker som har hänt i mitt liv.

Mitt sista försök var annorlunda. Liksom alla användare nuförtiden hade jag noga begrundat problemet i mitt huvud. Fram till dess var det rutin att efter ännu ett misslyckande trösta mig att det kommer att bli lättare nästa gång. Det slog mig aldrig att jag skulle tvingas fortsätta så här för resten av mitt liv. Den tanken fyllde mig med fasa och gjorde att jag började reflektera ordentligt över saken.

Istället för att undermedvetet sätta igång webbläsaren analyserade jag istället mina känslor och bekräftade det jag redan visste. Jag njöt inte av porr och tyckte att det var smutsigt och äckligt. Jag började titta på icke-användare som bodde i andra delar av världen, eller äldre personer som inte lärde känna tubsajterna. Fram till dess hade jag alltid betraktat icke-användare som önsketänkande, osociala och kräsna människor. Men när jag undersökte dem när de dök upp, verkade de vara - om något - starkare och mer avslappnade. De tycktes kunna hantera livets påfrestningar och njuta mer av sociala funktioner än porranvändare. De hade definitivt mer glöd och energi.

Jag började prata med ex-användare. Fram till dess hade jag alltid ansett att de hade tvingats sluta av hälsoskäl eller religiösa skäl och att de alltid i hemlighet längtade efter ett haremsbesök. Några få sa: *"Man får enstaka smärtor, men de är så sällsynta att de inte är värda att bry sig om. "* De flesta sa istället: *"Saknar du det? Du måste skämta! Livet har aldrig känts bättre!"* Till och med misslyckanden utgjorde ett fall framåt för dem, men de fördömde inte sig själva utan accepterade dem villkorslöst i stället. Precis som en tränare som accepterar misstag av en genuint gyllene spelare. Att prata med före detta missbrukare förstörde en annan myt som jag alltid hade haft i mitt huvud, den att det fanns en inneboende svaghet inom mig, tills det gick upp för mig att alla går igenom denna privata mardröm.

Vad jag i grund och botten sa till mig själv: *"Massor av människor slutar och lever lyckliga liv. Jag behövde inte göra det innan jag började, och jag minns att jag fick jobba hårt för att vänja mig vid den här smutsen. Så varför behöver jag göra det nu? "* I vilket fall som helst njöt jag inte av porr, jag hatade hela den smutsiga ritualen och ville inte tillbringa resten av mitt liv i slaveri av detta äckliga beroende. Jag sa då detta till mig själv:

*"Vare sig du gillar det eller inte har du avslutat din sista sittning."*

Jag visste redan från den stunden att jag aldrig skulle titta på porr igen. Jag förväntade mig inte att det skulle bli lätt, snarare tvärtom. Jag trodde till fullo att jag hade anmält mig frivilligt till månader av mörk depression och att jag skulle tillbringa resten av mitt liv med att ha en tillfällig abstinens. Istället har det ända från början varit en absolut lycka.

Det tog mig lång tid att lista ut varför det var så lätt och varför jag inte hade drabbats av de där skrämmande abstinensbesvären. Orsaken är för att de inte existerar, utan det är tvivlet och osäkerheten som skapar abstinensen. Den vackra sanningen är att ***det är lätt att sluta med porr.*** Det är bara obeslutsamhet och gråt som gör det svårt. Till och med när man är beroende kan man som användare gå relativt långa perioder vid vissa tillfällen utan porr. Det är bara när man vill ha det, men inte kan få det, som man lider.

Nyckeln för att göra det lätt är därför att göra beslutet att sluta bestämt och slutgiltigt. Inte hoppas, utan *veta* att du har slutat, att du har fattat beslutet. Tveka eller ifrågasätt aldrig, tvärtom -- finn alltid glädjen! Om du är säker från början blir det lätt, men hur kan du vara det redan från början? Därför är resten av boken nödvändig. Det finns vissa viktiga punkter som är nödvändiga att klargöra för dig innan du börjar:

1. Förstå att du kan klara av det. Du är inte annorlunda och den enda person som kan få dig att titta på porr är du själv. Inte den där stjärnan som aldrig någonsin skulle betrakta sig själva som ett redskap som minskar virilitet.

2. Det finns absolut ingenting att försaka. Tvärtom finns det enorma positiva vinster att göra. Inte bara blir du friskare och rikare, utan du kommer också att njuta mer av de goda tiderna och vara mindre olycklig under de dåliga.

3. Det finns inget sådant som en snabbtitt eller ett besök. Porr är drogberoende och en kedjereaktion, genom att gnälla över ett och annat besök kommer du bara att straffa dig själv i onödan.

4. Se inte på porr som en "pojkar kommer att förbli pojkar"-vana som kan skada dig, utan som ett drogberoende. Ta itu med det faktum att **du har fått sjukdomen**, vare sig du vill det eller inte. **Den kommer inte att försvinna för att du gräver ner huvudet i sanden. Ha i åtanke att precis som alla förlamande sjukdomar så består den inte bara livet ut utan blir också exponentiellt värre. Det enklaste är att bota den nu.

5. Separera sjukdomen -- det neurologiska beroendet -- från tankesättet att vara eller inte vara en användare. Alla användare skulle ta chansen att gå tillbaka till tiden innan de blev beroende om de gavs möjligheten. Du har den möjligheten i dag! Tänk inte ens på det som att "ge upp".

När du har fattat det definitiva beslutet att du har haft ditt sista harembesök är du redan en icke-användare. En användare är en av alla stackare som passerar genom livet och fördärvar sig själva med porr. En icke-användare är någon som inte gör det. När du väl har fattat beslutet så har du redan uppnått ditt mål. Gläd dig åt det faktumet, sitt inte och sura och samtidigt vänta på att det kemiska beroendet ska försvinna. Ge dig omedelbart ut och njut av livet. Livet är underbart även som missbrukare, men varje dag kommer att bli så mycket bättre när du inte är det.

Nyckeln till ett enkelt porravslut är din egen starka övertygelse om att du helt och hållet ska lyckas avstå under abstinensperioden (högst tre veckor). Om du har rätt inställning kommer det här bli löjligt lätt för dig.

Om du har öppnat ditt sinne på det sätt som begärdes i början har du redan bestämt dig för att bryta dig loss. Du bör nu känna spänning, som en hund som drar i kopplet och som inte kan bärga sig tills du får bryta ner DeltaFosB-smörjda porrvattenrutschkanor. Om du får en känsla i form av undergång och dysterhet så beror det på någon av följande anledningar:

1. Det är något som inte riktigt har satt sig ordentligt i ditt huvud. Läs de fem punkterna ovan igen och fråga dig själv om du tror att de stämmer. Är det någon punkt du tvivlar på så läs om de lämpliga avsnitten i boken.

2. Du fruktar själva misslyckandet. Ingen fara, fortsätt bara att läsa så kommer du att lyckas. Hela grejen med internetporr är ett bedrägeri av gigantiska proportioner. Intelligenta människor faller för bedrägerier, men bara en dåre fortsätter att lura sig själv när han väl har avslöjat dem.

3. Du instämmer med allting men är ändå olycklig. Var inte det! Öppna ögonen. Något underbart håller på att hända. Du ska snart fly från fängelset och det är viktigt att starta i rätt sinnesstämning: *"Det är underbart att jag är en icke-användare!"*

Det enda som behöver göras nu är att hålla kvar dig i den sinnesstämningen under abstinensperioden och i de kommande kapitlen diskuteras specifika punkter som gör det möjligt för dig att göra det. Efter avvänjningsperioden behöver du inte längre tänka på det sättet eftersom du kommer att tänka det automatiskt. Det enda mysteriet i ditt liv kommer att vara varför du inte såg det tidigare. Två viktiga varningar dock.

- Vänta med att planera ditt sista harembesök tills du har läst färdigt boken.

- En abstinensperiod på upp till tre veckor har nämnts många gånger vilket kan orsaka missförstånd. För det första kan du omedvetet få känslan av att du tvingas lida i tre veckor. Det behöver du inte. För det andra, undvik tankefällan *"På ett eller annat sätt måste jag bara avstå i tre veckor och därefter kommer jag må bra.”* Inget magiskt kommer att hända efter dessa tre veckor. Du kommer inte plötsligt att bara känna dig som en icke-användare eftersom de inte känner sig annorlunda gentemot användare. Om du mår dåligt av att sluta under de tre veckorna så kommer du sannolikt också må dåligt när veckorna har passerat. Sammantaget kan man säga att om du lyckas säga *"Jag kommer aldrig att ta droger igen, är det inte underbart?"*, så kommer alla frestelser att försvinna efter tre veckor. Om du däremot säger *"Om jag bara kan överleva dessa tre veckor utan porr."*, så kommer du att dö för ett haremsbesök efter de tre veckorna.

Se det som så att din hjärna vill behålla status quo. Så om du tror att du mister någonting bra när du slutar så kommer du givetvis känna dig hemsk. Det är omöjligt att tvinga sig själv att känna på ett visst sätt om inte hjärnan tror på det. Därför är det viktigt att ta sig igenom besväret att avlägsna illusionen att porr ger dig något överhuvudtaget. Det är så du vet att du inte offrar någonting.

Sexuell dysfunktion orsakas till stor del av din egen hjärna och sinnesstämning. Internetporren programmerar om hjärnans belöningskretsar och förser ditt sinne med "tvivlande" tankesätt. Detta självtvivel kommer absolut att orsaka sexuell dysfunktion. Att ha begären i din övre del, men ingen upphetsning i din nedre är det värsta som kan hända med din inställning. Libido som går hand i hand med romantik är ungdomens elixir som du kan ha tills du dör. Din libidos fortsatta kraft bibehålls med hög sannolikhet om du slutar, men det är inte din enda eller ens största vinst. Det är friheten från slaveri!

Translated with DeepL
