# Abstinensperiod

Du kan drabbas av abstinensbesvär i upp till tre veckor efter din sista sittning. Dessa består av två vitt skilda faktorer:

1. Dopaminabstinens. En tom, osäker känsla som påminner om hunger och som identifieras som ett begär eller en "något jag måste göra"-känsla.

2. Psykologiska triggers av vissa externa stimulanser, t.ex. reklamfilmer, surfande på nätet, telefonsamtal osv.

Om man inte kan förstå och skilja mellan dessa två distinkta faktorer är det svårt att nå framgång med hjälp av viljestyrkemetoden. Det är också anledningen till att många som gör det hamnar i fällan igen. Även om dopaminets abstinensbesvär inte orsakar fysisk smärta ska du inte underskatta dess kraft. Vi talar om "hungersnöd" om vi går utan mat under en dag; det kan kurra i magen, men du känner ingen fysisk smärta. Trots det är hunger en mäktig kraft och vi kan bli rejält irriterade om vi blir berövade på mat. Det kan liknas vid när vår kropp är sugen på ett dopaminrus, med skillnaden att kroppen behöver mat och inte gift. Med rätt sinnesstämning är abstinensbesvären lätta att övervinna och de försvinner mycket snabbt.

Om du avhåller dig från porr under några dagar med hjälp av viljestyrkemetoden försvinner snart suget efter dopaminkickar. Det är snarare den andra faktorn -- hjärntvätt -- som orsakar störst problem. Användaren har tagit för vana att lätta sina abstinensbesvär vid bestämda tidpunkter och tillfällen, vilket leder till idéassociationer (*"Jag har fått stånd, så jag måste titta på porr"* eller "*Jag ligger i sängen med min bärbara dator och måste ha en session för att känna mig lycklig*"). Effekten illustreras bäst med ett exempel: Du har en bil där spaken till blinkersen sitter till vänster, men du köper en ny bil och på den sitter samma spak till höger. Du vet att den är till höger, men i ett par veckors tid råkar du sätta på vindrutetorkarna när du egentligen vill blinka.

Att sluta med porr är ungefär samma sak. Under de första dagarna kommer den utlösande mekanismen att aktiveras vid särskilda tidpunkter. Du kommer ha i åtanke att du vill ha en sittning och därför är det nödvändigt att motverka hjärntvätten redan från början. Om du gör det kommer dessa signaler och triggers att snabbt försvinna. Med viljestyrkemetoden tror användaren tror att han gör en uppoffring. Det får honom att tjura över den uteblivna porren och vänta på att lusten ska försvinna. Denna metod är inte i närheten av att avlägsna dessa utlösningstriggers, den ökar dem. På samma sätt börjar användaren under gurutänkandet att fundera på när de kommer bli en gud och kräver att dessa tankar ska upphöra. Det banar väg för självförakt och misslyckande.

En vanlig trigger är ensamtid, särskilt vid sociala sammanhang tillsammans med vänner. Ex-missbrukaren som använder andra metoder för att sluta är redan olycklig på grund av berövandet av sin vanliga krycka eller källa till njutning. Ens vänner umgås intimt med sina partners. Användaren är antingen singel eller "får" inget från sin partner och kan inte njuta av vad som borde vara ett trevligt socialt tillfälle. De existerande vattenrutschkanorna som står redo i hjärnan leder dem till porr, vilket är lättare tillgängligt än att försöka uppvakta sin partner.

Eftersom han associerar sin rätt till sex med sitt välbefinnande drabbas han av ett trippelslag och hjärntvätten ökar. Är han tillräckligt beslutsam och lyckas hålla ut tillräckligt länge accepterar han till slut sin situation och går vidare med livet. En del av hjärntvätten kommer dock att bestå. Den näst mest patetiska aspekten är att användaren som har slutat efter flera år fortfarande längtar efter "ett sista besök hos haremet" vid vissa tillfällen. Han längtar efter en illusion som endast existerar i hjärnan, och han plågar sig själv i onödan.

Även med EasyPeasy så är den vanligaste anledningen till att man misslyckas att man reagerar på triggers. Ex-användaren brukar betrakta internetporr som ett slags placebo, ett sockerpiller. Han tänker: "*Porr gör ingenting för mig, det vet jag, men om jag bara tror att den gör det så kommer den vid vissa tillfällen att vara till hjälp.*". Ett placebo kan, även om det är fysiskt ineffektivt, vara ett kraftfullt psykologiskt hjälpmedel för att lindra verkliga symtom och är därför fördelaktigt. Internetporr och vanemässig onani är dock inget sockerpiller. Varför? Jo, för att porren skapar just de symtom som den lindrar och upphör sedan att lindra dem helt och hållet.

Du kanske förstår effekten enklare om du sätter den i relation till en icke-användare eller en sedan flera år framgångsrik ex-användare. Om en icke-användare exempelvis förlorar sin partner, då är det ganska vanligt att man med de bästa av intentioner säger: "*Ta du ett haremsbesök, det får dig att lugna ner dig.*" Det kommer dock inte att ha någon lugnande effekt eftersom det inte finns något dopaminberoende och därmed inga abstinensbesvär. I bästa fall ger det dem en tillfällig psykologisk boost.

Den ursprungliga tragedin finns kvar även efter att du har avslutat sessionen. Faktum är att den ökar eftersom personen nu lider av abstinensbesvär och står inför valet att antingen uthärda dem eller lindra dem genom att åka nedför vattenrutschkanan igen och påbörja misärens kedja på nytt. Det enda som porren gav var en flyktig psykologisk boost, samma som kunde ha uppnåtts genom en bok eller en feelgoodfilm, till och med en dålig sådan. Många icke- och ex-användare blir beroende på nytt på grund av sådana tillfällen. Se till att få det helt klart för dig: Du behöver inte dopaminpåslaget och du plågar bara dig själv ytterligare genom att fortsätta betrakta det som ett slags rekvisita eller en boost. Det finns ingen anledning att vara olycklig.

Orgasmer skapar inte bra relationer. Allt som oftast förstör de dem. Tänk också på att det inte alltid stämmer att de som visar offentlig ömhet njuter varje gång. Intimitet avnjuts bäst i avskildhet där parterna kan reagera utan förlägenhet. Man måste inte vara en orgasmberoende dopaminmissbrukare. Om du får en orgasm som sker naturligt till följd av en rad händelser i livet är det bra. Se bara till att njuta av tillfället, men också av livet utan den.

Efter att ha övergett begreppet porr som njutbart i sig självt tänker många användare: "*Om det bara fanns ren internetporr.*" Det finns ren mjukporr, men alla som provar det upptäcker snart vidden av tidslöseri det är. Den enda anledningen till att du överhuvudtaget använder porr är att få ett dopaminkick. Du måste förstå det. När väl dopaminbegäret efter porren har avlägsnats kommer du inte längre behöva besöka ditt nätharem. 

Oavsett om begäret beror på faktisk dopaminabstinens eller triggermekanismer, acceptera det bara. Det finns ingen fysisk smärta och med rätt inställning blir det inget problem. Du behöver inte bekymra dig för abstinensen, den känslan är i sig själv inte dålig. Snarare är det kopplingen mellan att vilja och att känna sig förnekad som är det riktiga problemet. Istället för att gråta över spilld mjölk, istället för att försöka förneka abstinensen, erkänn den: "*Jag vet vad det är. Det är porrframkallade abstinensbesvär. Porranvändare lider av dem hela livet och det är därför de förblir missbrukare. Icke-användare lider inte av dylika krämpor, vilket är ytterligare ett av detta förljugna missbruks många onda sidor. Visst är det underbart att jag spolar min hjärna ren från denna ondska!"*

Det kommer alltså att pågå ett mindre inre trauma under de närmaste tre veckorna, men det kommer under dessa veckor, och för resten av ditt liv, att hända något fantastiskt. Du kommer nämligen göra dig kvitt en fruktansvärd sjukdom, där fördelarna vida överstiger det lilla traumat. Du kommer faktiskt att njuta av abstinensbesvären. De kommer förvandlas till glädjestunder, en spännande lek som går ut på att svälta den pornografiska bandmasken som lever i din mage. Den måste svältas under de tre veckor den kämpar för sitt liv -- en desperat kamp för att lura dig att gå till sängs med porren igen.

Ibland ska den försöka göra dig olycklig. Vid vissa tillfällen kommer du att bli överrumplad. Du får kanske som av en händelse en porrlänk, eller snubblar över något på nätet som gör att du helt glömmer av att du har slutat. En lätt känsla av berövande när du minns. Förbered dig på dessa knep i förväg, kväv dem i sin linda. Och vad än frestelsen är, få in i huvudet att den bara finns där på grund av monstret i din kropp. Varje gång du står emot frestelsen så delar du ut ytterligare en moralisk smocka i kampen.

Vad du än gör, försök inte att förtränga porren. Det är en av anledningarna till att PMO:are som använder viljestyrka drabbas av depression. De strävar efter att ta sig igenom dagen i hopp om att glömma det till slut. Det är som att inte kunna sova -- ju mer du oroar dig för det, desto svårare blir det. Hur som helst kommer du inte att kunna glömma det. Under de första dagarna kommer det "lilla monstret" att fortsätta att påminna dig, det går inte att undvika det. Så länge laptops, smarttelefoner och tidningar fortfarande existerar kommer du att bli ständigt påmind.

Det viktiga är att du inte behöver glömma, det är ingenting dåligt som händer. Tvärtom, det är någonting fantastiskt och underbart som håller på att hända. Även om porren skulle dyka upp tusen gånger om dagen, **så njut av varje ögonblick och påminn dig själv om hur underbart det är att vara fri igen. Påminn dig själv om den rena glädjen i att slippa plåga dig själv längre.** Du kommer som sagt att märka hur plågorna blir till stunder av välbehag, och förvånas över hur snabbt du sedan glömmer porren.

Vad du än gör *tvivla aldrig på ditt beslut*. Börjar du tvivla så kommer du börja grubbla och det blir bara värre. Använd i stället den lilla stunden av grubbleri och omvandla den till en boost. Om det är depression som är orsaken, påminn dig själv om att det var porren som *orsakade* den. Om du får en webbadress vidarebefordrad av en vän, var stolt över att kunna säga: "*Jag är glad att jag inte längre behöver det där.*" Det kommer att göra ont i dem, men så fort de ser att det inte stör dig är de snart halvvägs till att ansluta sig till dig på den porrfria sidan.

** Kom ihåg att du har mycket starka skäl till att sluta redan från början.** Påminn dig själv om priset du måste betala. Fråga dig själv om du verkligen är beredd att riskera din kropps och sinnes fortsatta funktionalitet? Är du beredd att leva under en förbannelse för resten av livet? Uppmärksamma det lilla monstrets ansträngningar att minimera riskerna och kom framför allt ihåg att känslan bara är temporär och att varje stund är en stund närmare målet.

En del användare fruktar att de tvingas ägna resten av livet åt att upphäva "automatiska triggers". De tror alltså att de ska tvingas lura sig själva att de inte behöver porr med hjälp av psykologi. Så är inte fallet. Tänk på att optimisten ser flaskan som halvfull och att pessimisten ser den som halvtom. När det gäller porr är flaskan tom och användaren ser den som full. Internetporr ger inga fördelar överhuvudtaget. Det är användaren som har blivit hjärntvättad till att tro det. Så snart du börjar säga till dig själv att du varken behöver eller vill ha porr så behöver du på kort sikt inte ens säga det -- du ser då själv den vackra sanningen. Det är det sista du måste göra -- se till att det inte är det sista du gör!
