# Substitut

Några exempel på substitut är att begränsa sig till porrtidningar, porrbilder på internet, porrdieter osv. **Använd inte någon av dem!** De gör det bara svårare, inte lättare. Om du får ett begär och använder ett substitut så kommer begäret bara att förlängas, vilket gör det värre. Det du då egentligen säger är att du måste ha porr för att fylla tomrummet. Det blir som att ge efter för en kapare eller ett barns vredesutbrott. Begären hålls kvar och tortyren förlängs. I vilket fall som helst kommer substituten inte att lindra begäret. Vad du egentligen längtar efter är aminosyror som finns i hjärnan, och det kommeratt hålla dig kvar i tankarna på porr. Kom ihåg dessa punkter:

1.  Det finns inget substitut för porr.

2.  Du behöver inte porr! Det är inte mat, utan gift. När abstinensbesvären kommer, påminn dig själv om att det bara är användare som drabbas av abstinens, inte icke-användare. Se dem för vad de är, ännu ett av drogens onda sidor. Som ett monster som dör.

3.  Internetporren fyller inte tomheten; den skapar den. Ju förr du lär din hjärna att inte behöva titta, desto snabbare befrias du. Undvik allt som kan liknas vid porr, till exempel tidskrifter för män, sexiga filmer, kärleksromaner och reklamfilmer. Det här gör dig inte trångsynt, du får gärna prata romantik och sex, men inte om porr. Det går alltid att hitta tillfällen och platser att diskriminera på. Visst finns det ett litet antal användare lyckas sluta med mjukporr eller porrdieter (ur deras eget perspektiv) och att de tillskriver sin framgång åt sådan användning. De lyckas dock att sluta trots sitt bruk och inte tack vare det. Att många fortfarande rekommenderar dessa åtgärder är djupt beklagligt.

Om man inte förstår porrfällan fullt ut så låter en diet eller mjukporr som substitut väldigt rimligt, men det är inte överraskande. Den bygger på övertygelsen att när man ska sluta med porr måste man besegra två mäktiga fiender:

- Att bryta vanan.

- Att överleva fruktansvärda fysiska abstinensbesvär.

När man ställs inför två mäktiga fiender är det klokt att inte slåss mot dem samtidigt utan mot en i taget. Teorin går alltså ut på att när du ska till att sluta med porr så skär du ner till en gång i veckan eller använder "säker" porr. När vanan väl är bruten minskar man sedan successivt utbudet och bekämpar på så sätt varje fiende separat.

Det här låter visserligen logiskt, men det bygger på felaktig information. Porr är inte vana utan ett dopaminberoende medan den faktiska fysiska smärtan från abstinensen nästan inte märks. Vad du vill uppnå när du slutar är att döda båda monstren som härjar i kroppen och hjärnan på snabbast möjliga sätt. Det enda substitutionstekniker åstadkommer är att förlänga det lilla monstrets liv, vilket i sin tur förlänger hjärntvätten. EasyPeasy gör det enkelt att sluta omedelbart och dödar hjärntvätten före din sista sittning. Det lilla monstret kommer snart att dö, och även medan det dör kommer det inte att vara ett större problem än det var när du var användare.

Fundera på hur man någonsin skulle kunna bota beroendet av en drog genom att rekommendera samma drog? Det finns många historier på nätet om användare som har slutat hårdporr, men som istället har blivit beroende av "säkra" alternativ, efter att ha fallit offer för sitt lilla monsters rättfärdigande. Låt dig inte luras av att den "säkra" porren inte är hemsk -- det var det första höghastighetsklippet också. Alla substitut har exakt samma effekter som vilken porr som helst. En del börjar till och med äta, men även om den tomma känslan av att vilja ha en sittning är omöjlig att skilja från hunger efter mat, kommer den ena inte att tillfredsställa den andra. Faktum är att om det är något som är konstruerat för att få dig att vilja använda porr så är det att proppa i dig mat. Som tidigare beskrivits kommer porrdieter och "säker porr" bara att placera dig i mitten av dragkampen där motståndet mot frestelsen är så störande att du känner dig lättad när du besöker ditt favoritharem online.

Det mest ondskefulla med substitut är att de förlänger det verkliga problemet -- hjärntvätt. Behöver du ett substitut för influensan när du blir frisk? Givetvis inte. Genom att hävda att du behöver ett porrsubstitut säger du att du egentligen gör en uppoffring. Den depression som förknippas med viljestyrkemetoden orsakas av att du tror dig göra en uppoffring. Det enda du gör är att ersätta ett problem med ett annat. Det finns inget nöje i att proppa sig full med mat, kedjeröka cigaretter eller hälla i sig alkohol. Du kommer bara att bli fet, olycklig och på nolltid vara tillbaka på drogen.

Sporadiska användare har svårt att förkasta tanken att de berövas sin lilla belöning. Det gäller de som under en period inte kan vara online t.ex. under en resa, eller en familjehändelse osv. En del säger: "*Jag vet inte hur jag skulle kunna varva ner utan porr*" Just det bevisar poängen, att pausen ofta inte tas för att användaren behöver eller ens vill ha den, utan för att missbrukaren -- vilket är vad de är -- desperat behöver klia på klådan.

Kom ihåg: Porrsessionerna var aldrig några riktiga belöningar. De kan likställas med att bära trånga skor bara för att få nöjet att ta av sig dem. Om du känner att du måste ha en liten belöning, låt detta bli ditt substitut. Bär skor eller underkläder som är en storlek för små medan du arbetar och tillåt dig inte att ta av dem förrän du har rast. Upplev sedan det härliga ögonblicket av avslappning och tillfredsställelse när du tar av dig dem. Ni kanske tycker att det vore ganska dumt. Du har helt rätt. Man kan ha svårt att föreställa sig det när man fortfarande sitter i fast i skiten, men det är vad användarna gör. Det är också svårt att visualisera att du snart inte behöver din lilla "belöning", att du snart kommer att betrakta vänner som fortfarande sitter fast i skiten med äkta medlidande och undra varför de inte kan fatta poängen.

Men om du fortsätter lura dig själv att ett besök i nätharemet är en äkta belöning, eller att du behöver ett substitut, kommer du att känna dig berövad och olycklig. Risken att du faller i den vidriga fällan igen är då stor. Om du behöver en riktig rast, en sådan som hemmafruar, lärare, läkare och andra yrkesverksamma gör, kommer du snart att njuta ännu mer av den rasten eftersom du inte behöver göra dig själv beroende. Kom ihåg att du inte behöver någon ersättare. Sviterna är ett sug efter dopamin och kommer snart att vara borta. Låt det vara din rekvisita för de kommande dagarna och njut av att befria din kropp och ditt sinne från slaveri och beroende.
