# Bör jag undvika frestelser?

Hittills har råden varit direkta och uppmanat dig att betrakta dem som instruktioner snarare än förslag. Det finns sunda, praktiska skäl till dessa råd som har stöds av tusentals fallstudier. På frågan huruvida man ska försöka undvika frestelser eller inte så finns inte detta stöd. Varje användare måste själv avgöra detta. Du kan dock få två användbara tips som kan hjälpa dig genom processen. Rädslan för framtida abstinensbesvär är det som gör att vi fortsätter med porr under resten av våra liv, och denna rädsla utgörs av två olika faser.

** Första fasen - "*Hur kan jag överleva utan porr?*"**

Den här rädslan är samma panikartade känsla som användaren får som singel eller med en sexuellt ointresserad eller otillgänglig partner. Rädslan beror inte på abstinensbesvär utan är den psykologiska rädslan för beroende, att man inte ska kunna överleva utan sex och orgasm. Den rädslan kulminerar när man är på väg att sluta, när abstinensbesvären är som lägst. Det är rädslan för det okända, den typ av rädsla man känner när man lär sig dyka.

Hoppbrädan är en halvmeter hög men tycks snarare vara minst tre meter hög. Vattnet är tre meter djupt, men verkar vara en halvmeter. Man måste vara modig för att kasta sig ut i tron om att man kommer krossa skallen. Den svåraste delen är själva hoppet, men om man bara hittar modet att göra det så är resten lätt! Det förklarar varför många viljestarka användare aldrig har försökt sluta, eller bara klarar av några få dagar när de väl försöker. Faktum är att det finns en del användare på porrdieter som, när de bestämmer sig för att sluta, faktiskt börjar frossa och eskalerar till hårdare klipp snabbare än om de inte hade bestämt sig för att sluta. Detta beslut orsakar panik, vilket är stressande och utlöser en signal att ta en tur till haremet. Men nu kan man inte ha någon, vilket leder till tankar om berövande och förvärrar stressen.

Triggern utlöses snabbt när säkringen går och du startar webbläsaren. Oroa dig inte, paniken är bara av rent psykologisk. Du är rädd för att du är beroende. Den vackra sanningen är att du inte är det, även om du fortfarande missbrukar. Få inte panik utan starta dig själv.

** Andra fasen - Långsiktig rädsla**

Den andra fasen är långsiktig och innebär rädsla för att vissa situationer i framtiden inte kommer att vara roliga eller att du inte kommer att kunna hantera trauman utan porr. Oroa dig inte, om du kan starta dig själv kommer du att upptäcka att det motsatta är sant. Själva undvikandet av frestelser kan delas in i två kategorier.

1.  "*Jag använder en porrdiet på en gång på fyra dagar. Jag kommer att känna mig tryggare när jag vet att jag kan gå ut på nätet om det blir jobbigt. Om jag misslyckas är det okej, jag lägger bara till ytterligare dagar till min nästa cykel.*"

Andelen misslyckanden bland dem som tillämpar den här metoden är **väldigt mycket högre** än bland dem som slutar helt och hållet. Det beror främst på att om du har en dålig period under abstinensperioden är det lätt att hoppa in på webbläsaren och besöka haremet med ovanstående ursäkter. Om du har förnedringen att tydligt bryta mot dina egna regler som en krossad glasruta är det mer sannolikt att du övervinner frestelsen. I vilket fall som helst hade begäret antagligen redan gått över om du hade skjutit upp det. Den främsta orsaken till den höga misslyckandefrekvensen i dessa fall är dock att användaren inte kände sig helt och hållet engagerad i att sluta från början. Kom ihåg att de två viktigaste förutsättningarna för att lyckas är:

    - Övertygelse.

    - "*Är det inte fantastiskt att jag inte behöver porr längre?*"

    I båda fallen, varför i hela världen behöver du en session? Om du fortfarande behöver besöka ditt harem, läs om boken först. Det är något som inte riktigt har fungerat. Ta dig tid att döda det stora hjärntvättsmonstret i ditt sinne stenhårt.

2.  "*Ska jag undvika stressiga eller sociala tillfällen under abstinensperioden?*"

    När det gäller stressiga situationer, ja. Det är ingen idé att sätta onödig press på dig själv. När det gäller sociala tillställningar, som barer eller klubbar, är rådet det omvända. Gå ut och roa dig direkt, du behöver inte sex eller den fortplantande delen av sex även när du är porrberoende. Så gå ut och gläd dig åt att du inte behöver skiten längre. Den vackra sanningen att livet är så mycket bättre utan dessa påfrestningar kommer snabbt att bevisa sig för dig. Tänk bara hur mycket bättre det kommer att bli när det lilla monstret tillsammans med de krävande tankarna har lämnat dig.
