# Uppenbarelsens ögonblick

Vanligtvis upplever ex-användare uppenbarelsens ögonblick inom tre veckor efter att de har brutit sig fria. Himlen ter sig ljusare och hjärntvätten upphör helt och hållet. När du i stället för att säga till dig själv att du inte behöver titta på porr plötsligt inser att den sista tråden är bruten, att du kan njuta av resten av ditt liv utan att någonsin behöva det igen. Från och med den här punkten börjar man också vanligen betrakta fortsatta användare som föremål för medlidande.

De som slutar med hjälp av viljestyrka upplever normalt inte detta ögonblick, för även om de är glada över att vara före detta användare fortsätter de att leva i tron att de gör en uppoffring. Ju mer beroende man var, desto mer fantastiskt är detta ögonblick och dessutom varar det hela livet. Även om det finns många glädjeämnen i livet är det omöjligt att återskapa den faktiska känslan av att uppleva dem. Glädjen över att inte behöva titta på porr längre är annorlunda, om man känner sig låg och behöver en boost, kan man påminna sig själv om hur härligt det är att inte vara beroende av det hemska beroendet. Många anger det som en av de största händelserna i sina liv. I de flesta fall sker uppenbarelsens ögonblick inte efter tre veckor utan efter några dagar.

I mitt eget fall inträffade det innan jag avslutade mitt sista haremsbesök. Jag är säker på att många av läsarna här, innan de ens kommit till slutet av kapitlen skulle säga något i stil med "*Du behöver inte säga ett ord till. Jag kan se allt så tydligt att jag vet att jag aldrig behöver porr igen.*" Enligt den feedback som vi har fått händer detta ofta. I idealfallet, om du följer alla instruktioner och förstår psykologin helt och hållet, ska det hända dig omedelbart.

Fastän det anges att den märkbara fysiska abstinensen försvinner efter cirka fem dagar och cirka tre veckor för en ex-användare att bli helt fri, så kan sådana riktlinjer leda till två problem. Det första är att förslaget om att de måste lida i mellan fem dagar och tre veckor planteras in i folks sinnen. Det andra är att ex-missbrukaren brukar tänka "*Om jag bara lyckas överleva i fem dagar eller tre veckor kan jag förvänta mig en riktig uppryckning i slutet av den perioden*".

Dock kan de uppleva fem trevliga dagar eller tre härliga veckor följt av katastrofala dagar. Sådana dagar drabbar alla och har egentligen ingenting med missbruket att göra, utan de beror på andra faktorer i våra liv. Den ex-missbrukare som inväntar uppenbarelsens ögonblick upplever då i stället depression. Det kan rasera dennes självförtroende. På samma sätt skulle ex-användaren utan riktlinjer kunna leva resten av livet med att vänta på något som inte kommer att ske. Det är vad som händer med majoriteten av de som slutar genom att använda viljestyrkemetoden.

Folk frågar ofta vad de fem dagarna och de tre veckorna egentligen innebär. Är de bara perioder som fastställs ur en handvändning? Nej, även om de inte är definitiva datum så återspeglar de en sammanställning av feedback genom åren. Ungefär fem dagar efter att ha slutat är när den före detta missbrukaren slutar att ha missbruket som huvudsysselsättning i sitt sinne. De flesta f.d. missbrukare upplever uppenbarelsen runt denna period, vanligtvis under stressiga eller sociala situationer som förr hade varit omöjliga att klara av eller roa sig med utan ett haremsbesök. Du inser plötsligt att du inte bara njuter av det och att du klarar av det, utan också att tanken på porr inte ens har väckts hos dig. Från och med den stunden är det i regel en enkel resa. Då vet du att du är fri.

Både jag och många andra som försökt sluta med viljestyrka upplever att de flesta sådana försök misslyckas under denna treveckorsperiod. Vanligtvis känner man efter cirka tre veckor att man inte längre känner suget efter porr. Du måste då bevisa det för dig själv, så du sätter igång webbläsaren för ett besök i haremet. Att behöva bevisa att du har slutat med porr känns konstigt. Men i processen smörjer du DeltaFosB-vattenrutschkanan tack vare den färska dopaminsköljningen, det som din kropp har suktat efter de tre senaste veckorna. Så snart du är klar så börjar dopaminet lämna din kropp. Då dyker en liten röst upp igen: "*Du har inte gjort dig av med den, du vill ha ytterligare en.*"

Du rusar inte tillbaka eftersom du inte vill fastna i det igen, utan låter en trygg period förflyta. När du blir frestad nästa gång kan du säga till dig själv: "*Ja, jag blev inte beroende igen, så det är inget fel med att titta en gång till."* Du är redan på väg nerför den halkiga backen. Lösningen på problemet ligger i att inte vänta på uppenbarelsens ögonblick, utan att inse att när du stänger webbläsaren så är det slut. Du har strypt syretillförseln till ditt lilla monster. Ingen kraft på jorden kan hindra dig från att vara fri, *om du inte tjurar över det eller väntar på en uppenbarelse.* Gå ut och njut av livet; klara av det redan från början. Uppenbarelsens ögonblick kommer snart att komma.
