# Det Sista Besöket

När du väl har bestämt dig för när du ska sluta, är du nu redo att göra ett sista haremsbesök. Se dock till att kontrollera de två viktigaste frågorna innan du gör det.

1.  Känner du dig säker på att lyckas?

2.  Känner du en känsla av undergång och dysterhet, eller en spänning över att du är på väg att åstadkomma något fantastiskt?

Skulle du vara tveksam kan du läsa om boken igen innan du slutar. Kom ihåg: du bestämde dig aldrig för att falla i porrfällan, men fällan är utformad för att förslava dig livet ut. För att kunna fly måste du fatta det positiva beslutet att du ska sluta och att du ska göra ett sista besök.

Enda skälet till att du har läst så här långt är din starka längtan att fly, kom ihåg det. Så ta det positiva beslutet just nu och avlägga ett högtidligt löfte om att nästa gång du stänger webbläsarfönstret, vare sig lätt eller svårt, så ska du aldrig besöka ditt harem igen. Du kanske oroar dig för att du tidigare har avlagt detta löfte och misslyckats flera gånger, eller att du måste gå igenom ett fruktansvärt trauma. Frukta inte, det värsta som kan hända är att du misslyckas.Därför har du ***absolut ingenting*** att förlora och så oerhört mycket att vinna.

Sluta dock att ens fundera på att misslyckas! Den vackra sanningen är att det inte bara är löjligt lätt att sluta, utan att du faktiskt också kan njuta av processen. Den här gången ska du använda EasyPeasy! Allt du behöver göra är att följa de enkla instruktionerna som du kommer att få.

1.  Avge det högtidliga löftet nu och mena allvar med det.

2.  Bläddra medvetet bland bilderna och filmerna på din favoritporrsajt, betrakta webbplatsadministratörernas, skådespelarnas och även amatörernas desperata försök att förstärka chocken, nyheten och den supernormala naturen i sina varor och fråga dig själv vart nöjet finns.

3.  När du till slut stänger webbläsaren, gör det inte med en känsla av "*Jag ska aldrig besöka ett nätharem igen*" eller "*Jag tillåts aldrig besöka ett annat*". Gör det i stället med en känsla av frihet, som "*Är det inte fantastiskt? Jag är fri! Jag är inte längre slav under porren! Jag behöver aldrig i mitt liv besöka dessa smutsiga sajter igen*".

4.  Var medveten om att det kommer att finnas en liten porrsabotör i din mage under några dagar. Kanske är du bara uppmärksam på känslan av att vilja ha en sittning. Det lilla porrmonstret har refererats till som det lilla fysiska begäret efter dopamin. Strängt taget är detta felaktigt, och det är viktigt att förstå varför. Eftersom det tar upp till tre veckor för det lilla monstret att dö, tror ex-användare att det lilla monstret kommer att fortsätta att sukta efter det sista haremsbesöket och därför måste använda viljestyrka för att motstå frestelsen under denna period. Så är det inte, kroppen längtar inte efter det porrutlösta dopaminet, det är bara hjärnan som längtar.

Får du känslan av att du vill ta en titt under de närmaste dagarna har din hjärna ett enkelt val. Antingen tolkar den känslan för vad den faktiskt är -- en tom osäkerhetskänsla som uppstod vid ditt första porrsajtsbesök och ytterligare förstärks av varje nytt besök, och säger  istället till dig själv **" HURRA! JAG ÄR EN ICKE-ANVÄNDARE!"**

Eller så kan du börja sukta efter porr och lida resten av ditt liv. Tänk efter ett ögonblick, vore inte det en otroligt dum sak att göra? Att säga "*Jag vill aldrig mer titta på porr*" och sedan tillbringa resten av livet med att säga "*Jag vill gärna göra ett besök*"? Det är vad de som använder sig av viljestyrkemetoden gör och inte undra på att de känner sig så eländiga. De ägnar resten av sina liv åt att desperat tjura över något som de desperat hoppas att de aldrig kommer att få. Inte konstigt att så få lyckas och att de få som gör det aldrig känner sig helt fria.

> *'Få den här mentala bilden klart för dig, den kan nämligen vara till stor hjälp när det gäller att övervinna kraften hos yttre stimuli som stör dig. Föreställ dig att du sitter lugnt och stilla och låter telefonen ringa, att du ignorerar dess signal och är oberörd av dess uppmaning. Även om du är medveten om den så tänker du inte längre på den och lyder den inte längre. Inse också att denna yttre signal i sig själv inte har någon makt över dig, inte heller någon makt att påverka dig. Du har tidigare lytt den, reagerat på den, men enbart på grund av vana. Du kan, om du vill, skapa en ny vana att inte svara.*
>
> *Märk också att din underlåtenhet att svara inte består av att göra något, att anstränga dig, att göra motstånd eller att kämpa, utan av att göra ingenting -- att avslappnat inte göra något alls. Du slappnar helt enkelt av, ignorerar signalen och låter dess kallelse gå obeaktat. Telefonsignalen är en symbolisk analogi till alla andra yttre stimuli som du vanemässigt överlåter kontrollen över, och nu väljer du att mycket medvetet förändra den vanan.*''
>
--- Maxwell Maltz, "The New Psycho Cybernetics", kapitel 12. 

Det är endast tvivel och väntan som gör det svårt att sluta, ***så tvivla aldrig på ditt beslut*** eftersom du vet att det är det rätta. Om du börjar tvivla på det försätter du dig själv i en situation där du inte kan vinna. Eländig medan du längtar efter ett besök men inte kan få det. Oavsett vilket system du använder, vad är det du försöker uppnå när du slutar med porr? Att aldrig mer titta på porr igen? Nej! Många ex-användare gör det, men går igenom resten av sina liv och känner sig berövade.

Vad är skillnaden mellan användare och icke-användare? Icke-användare har varken behov eller lust att titta på porr. De har inget begär och behöver inte utöva viljestyrka för att inte titta på porr. Det är vad du ska försöka uppnå och det ligger helt och hållet i din makt att göra det. Du måste inte vänta på att sluta ha porrbegär eller bli en icke-användare, det är klart i samma ögonblick du stänger det sista webbläsarfönstret och skär av dopamintillförseln. **DU ÄR REDAN EN LYCKLIG ICKE-ANVÄNDARE!**

Du kommer att förbli en lycklig icke-användare förutsatt att:

1.  Du aldrig tvivlar på ditt beslut.

2.  Du väntar inte på att bli icke-användare. Om du gör det väntar du bara på att ingenting ska hända och skapar en fobi.

3.  Du anstränger dig inte för att *inte* tänka på porr eller väntar på att "uppenbarelsens ögonblick" ska komma och skapar en fobi.

4.  Du använder dig inte av substitut.

5.  Du ser alla andra användare som de verkligen är och tycker synd om dem i stället för att avundas dem.

Oberoende av om det är bra eller dåliga dagar så förändra inte ditt liv bara för att du har slutat. Om du gör det gör du en verklig uppoffring när det inte finns någon anledning till det. Kom ihåg att du inte har slutat leva. Du har inte gett upp någonting. Tvärtom har du botat dig själv från en fruktansvärd sjukdom och rymt från ett lömskt fängelse. Allteftersom dagarna går och din hälsa -- både fysiskt och psykiskt -- förbättras kommer topparna att verka högre och dalarna inte lika låga som när du var missbrukare. Närhelst du tänker på porr under de kommande dagarna eller resten av ditt liv, tänk:

***"HURRA! JAG ÄR EN ICKE-ANVÄNDARE!"***

## En Sista Varning

Med den kunskap de har nu skulle ingen användare välja att börja om han eller hon kunde gå tillbaka till tiden innan de blev beroende. Tiotusentals personer som lyckas sluta missbruka sedan många år lever idag helt lyckliga liv, bara för att återigen fastna i fällan. Jag är övertygad om att den här boken kommer att hjälpa dig att inse att det är relativt lätt att sluta. Jag varnar dig dock för att användare som finner det lätt att sluta finner det lika lätt att börja igen: **Fall inte i denna fälla.**

Oavsett hur länge sedan du slutade eller hur säker du är på att du aldrig kommer att bli beroende igen, gör det till en regel för livet att aldrig titta på porr av någon anledning. Motstå mediernas anspelningar och antydningar. Kom ihåg hur de driver på sin bild av "öppenhet" genom att föra in porr i den allmänna opinionen; omedvetna om att porr, internetporr och tvångsmässig onani dödar relationer och den personliga känslan av välbefinnande för ett enormt antal män och vissa kvinnor.

Den första titten eller det första besöket inte kommer att göra något för dig. Det kommer inte ge dig några abstinensbesvär att lindra och får dig att må förfärligt. Vad det kommer att åstadkomma är att placera dopaminrusets njutning i din hjärna och ditt sinne, och en liten röst i bakhuvudet talar om för dig att du vill ha en till. Du har då valet att vara olycklig ett tag eller att börja hela den smutsiga kedjan igen.
