# Feedback

Det är inte ett krig mot användarna, utan mot porrindustrins fälla. Kriget förs av den enkla anledningen att jag gillar det. Varje gång jag hör om en användare som lyckas rymma från fängelset så känner jag en oerhörd njutning. Men denna njutning har inte skett utan betydande frustration, främst orsakad av två kategorier av porranvändare. Trots varningen i föregående kapitel blir jag ständigt förvånad över antalet personer som tycker att det är lätt att sluta, men som senare fastnar och upptäcker att de inte kan lyckas nästa gång.

Det är som att hitta någon upp till halsen i ett träsk som är på väg att gå under. Du hjälper till att dra upp dem och de är tacksamma, men sex månader senare dyker de direkt ner i träsket igen. Användare som tycker att det är lätt att sluta och börja igen utgör ett särskilt problem, men när du blir fri ***VÄNLIGEN, VÄNLIGEN, GÖR INTE SAMMA MISSTAG.*** Man tror att sådana personer börjar igen för att de fortfarande är beroende och saknar dopaminet. I själva verket tycker användarna att det är så lätt att sluta att de förlorar sin rädslan för porr. De tänker: "*Jag kan ha en enstaka sittning, och skulle jag bli beroende igen kommer jag att ha lätt för att sluta*".

Tyvärr fungerar det inte på det sättet, att det är lätt att sluta med porr men omöjligt att kontrollera beroendet. Det viktigaste för att sluta med porr är att inte använda den.

Folk brukar komma tillbaka till porr eftersom de missförstår det "lätta" i easypeasy.

Tänk dig att någon sitter på det kalla betonggolvet i ett iskallt rum. På väggen mittemot dem finns ett fönster som visar en perfekt vårdag utanför -- träd som svajar mjukt, fåglar som kvittrar -- precis bredvid en olåst dörr. 

Behöver man någon form av viljestyrka för att ta sig ut ur det iskalla rummet? Nej! Är det svårare att fly än att stanna kvar? Självklart inte! (Faktum är att det är lite lättare eftersom kroppen rör sig). Varför skulle någon vid sina sinnens fulla bruk sätta sig själv i en sådan situation och orsaka sig själv månader eller år av frustration om de inte blev lurade?

Easypeasy drar isär gardinerna så att användaren klart och tydligt kan titta ut och för att undanröja **illusioner** om hur fruktansvärt det kan vara ute och hur bekvämt användaren har det i rummet.

Den andra kategorin av frustrerande användare är de som är för rädda för att försöka sluta, eller som när de gör det tycker att det är en hård kamp. De största svårigheterna verkar vara följande.

**Rädslan för att misslyckas.**

:   Det finns ingen vanära i att misslyckas, men att inte försöka är bara korkat. Se det så här, du gömmer dig för ingenting. Det värsta som kan hända är att du misslyckas, och i så fall är du inte i sämre skick än vad du är nu. Tänk bara på hur underbart det skulle vara att lyckas. Om du inte gör försöket har du redan garanterat misslyckandet.

**Rädslan för smärta och att vara olycklig.**

:   Oroa dig inte för det, tänk bara: Vilken hemskhet skulle kunna hända om du aldrig mer tittade på porr? Absolut ingenting. Fruktansvärda saker *kommer* däremot att hända om du fortsätter. Läs anteckningarna om Pascals vadslagning igen. I vilket fall som helst orsakas paniken av dopamin och den kommer snart att försvinna. Den största vinsten är att bli av med rädslan. Är verkligen användarna redo för sviktande penetrationsförmåga, opålitliga sexuella prestationer eller den skenbara njutning de får från porr? Skulle du märka att du får panik hjälper det att djupandas. Om du är med andra människor som gör dig nedstämd, undvik då dem och gå till garaget, ett tomt kontor eller någon annanstans där du kan vara ifred.

Skäms inte om du känner för att gråta. Gråt är naturens sätt att lätta på spänningar. Ingen har någonsin gråtit ordentligt utan att känna sig bättre efteråt. En av de fruktansvärda saker vi gör mot unga män är att konditionera dem att inte gråta. Du kan se dem kämpa emot tårarna, samtidigt som käken jobbar hårt. Vi lär oss att inte visa känslor, men det är inte meningen att vi ska konservera dem inom oss. Skrik, vråla eller ha ett vredesutbrott. Sparka på något. Se din kamp som en boxningsmatch som du inte kan förlora. Ingen kan stoppa tiden, varje stund som passerar dödar det lilla monstret inom dig. Njut av din oundvikliga seger.

**Inte följa instruktionerna.**

:   Det är otroligt att vissa användare uppger att metoden inte fungerade för dem. De beskriver då hur de inte bara ignorerade en instruktion utan praktiskt taget alla. För tydlighetens skull sammanfattas dessa som en checklista i slutet av detta kapitel.

**Missförstånd av instruktioner.**

:   De största problemen förefaller vara följande:

    "*Jag kan inte sluta tänka på porr.*"

    :   Det är klart att du inte kan, och om du försöker kommer du att skapa en fobi och bli olycklig. Det är som att försöka somna på natten; ju mer man försöker, desto svårare blir det. Det kvittar om du tänker på porr i nittio procent av ditt liv, det är vad du tänker som är viktigt. Om du tänker "*Oh, jag älskar att titta på porr*" eller "*När blir jag fri?*" kommer du att vara olycklig. Om du i stället tänker "*HURRA! Jag är fri!*" blir du lycklig.

    "*När kommer det lilla porrmonstret att dö?*"

    :   Dopaminsköljningen lämnar kroppen mycket snabbt, men det är omöjligt att avgöra när den slutar lida av den svaga fysiska känslan av dopaminabstinens. Denna tomma, osäkerhetskänsla är identisk med vanlig hunger, depression eller stress. Allt porren gör är att öka nivån av den. Det är därför som användare som slutar med viljestyrkemetoden aldrig kan vara helt säkra på om de har sparkat ut beroendet, även efter det att kroppen slutat att drabbas av dopaminabstinens. Om de lider av normal hunger eller stress talar hjärnan fortfarande om för dem att det är en giltig anledning till att kräva sin berättigade sittning. Poängen är att du inte behöver vänta på att suget ska försvinna, det är nämligen så svagt att vi inte ens märker det. Det är bara en känsla av att vilja ha. När du lämnar tandläkaren, väntar du då på att din käke ska sluta värka? Självklart inte, du låter livet fortsätta. Även om din käke fortfarande värker så är du glad.

Vänta inte på att abstinensen ska försvinna eftersom det skapar tvivel genom att ständigt fråga dig själv: "*Hur lång tid kommer det här att ta? Är jag ens fri om jag inte känner mig annorlunda?*" Rädslan är själva abstinensen, därför skapas tvivel om du bara går och väntar på förbättring efter att du har slutat. Avvänjningen är omärkbar såvida du inte är rädd för den, och de exponentiella förbättringarna av neurologin är långsamma. Om du därför väntar på att känna dig annorlunda kommer det att kännas som att ingenting händer, vilket skapar tvivel.

*"Uppenbarelsens ögonblick har inte kommit ännu."*

    :   Om du väntar på uppenbarelsens ögonblick skapar du bara en ny fobi. En gång höll jag upp i tre veckor med hjälp av viljestyrkemetoden. En gammal kompis frågade hur det gick för mig.
        "*Jag har överlevt tre veckor*", svarade jag.
        Han frågade: "Vad menar du med att du har överlevt tre veckor?".
        Jag förtydligade: "*Jag har klarat mig tre veckor utan porr*".
        Han sa: "*Vad ska du göra nu? Överleva resten av ditt liv? Du har gjort det, vad väntar du på? Du är en icke-användare nu.*"

Jag tänkte: "*Han har rätt, vad väntar jag på?*" Min bristande förståelse för fällan gjorde tyvärr att jag snart fastnade i den igen, men jag fattade poängen. Du blir en icke-användare så fort du stänger din webbläsare. Det viktigaste är att vara en lycklig icke-användare redan från början.

    "*Jag är fortfarande sugen på porr.*"

    :   Om du tänker så här så är du väldigt korkad. Hur kan du hävda att du vill vara icke-användare och sedan säga att du vill ha porr? Det är en motsägelse. Om du säger att du vill ha porr säger du att du vill vara en användare. Icke-användare vill inte besöka de äckliga tubsajterna. Du vet redan vad du vill bli, så sluta straffa dig själv.

"*Jag har sagt upp mig från livet.*"

    :   Varför då? Det enda du behöver göra är att sluta krossa dig själv och istället fylla upp med energi. Du behöver inte sluta leva överhuvudtaget. Det är så enkelt som så här: Under de närmaste dagarna kommer du att ha ett litet trauma i ditt liv. Din kropp kommer att drabbas nästan omärkbart av retirerandet av kraven och begären av en dopaminvåg. Ha detta i åtanke: du mår inte sämre än vad du gjorde tidigare. Du har lidit av det här i hela ditt liv -- varje gång du har sovit, varit i kyrkan, i snabbköpet eller på biblioteket. Det tycktes inte besvära dig som användare, men om du inte slutar kommer du att fortsätta lida denna plåga resten av ditt liv.

Porr och orgasmer berikar inte tillfällen, de berövar dig dem. Även när din kropp fortfarande suktar efter dopamin är måltider och sociala tillfällen underbara. Livet är underbart, gå på sociala tillställningar, även om det finns nakna dansare där. Kom ihåg att det inte är du som blir berövad, det är de som blir berövade. Varenda en av dem skulle älska att vara i din situation, om de bara visste. Njut av att vara primadonna och centrum för uppmärksamheten. Att sluta med porr är ett fantastiskt samtalsämne, att vidta en hemlig njutning som de inte kan. Dina vänner och kamrater kommer att bli förvånade över att se att du, som tidigare var blyg och såg trött ut, nu är glad och uppsluppen. Du kommer att njuta av livet redan från början, det finns ingen anledning att avundas de som raggar brudar på fest. De kommer att avundas dig - om de bara visste det.

    "*Jag är olycklig och irriterad.*"

    :   Det här är ett misslyckande med att följa instruktioner. Ta reda på vilken instruktion du har missat. En del har förstått och tror på allt som står i boken, men startar ändå med en känsla av undergång och dysterhet, som om något fruktansvärt håller på att hända. Du gör inte bara det du själv vill göra, utan också det som alla användare på planeten vill göra. Med alla metoder för att sluta försöker den före detta användaren uppnå en viss sinnesstämning, så varje porrrelaterad tanke är avbruten av "*HURRA! JAG ÄR FRI!*" Om det är ditt mål, varför då vänta? Börja med den sinnesstämningen och tappa aldrig bort den, det finns inget alternativ.

    "*Jag hade en bra vecka/månad/halvår men jag är tillbaka i fällan.*"

    :   Kom ihåg att rädslan är själva abstinensen. Att ge efter för ett begär genererar mer rädsla, vilket ger näring åt det försvagade lilla monstret och lyckas skrämma icke-användaren till att tro att han eller hon är fast för livet. I verkligheten har deras uppfattning av hjärntvätten inte förändrats, men de har gett dopamin till tankeprocessen. Detta är per definition att falla framåt, men fortfarande en underlåtenhet att följa instruktioner. Förstå vilken av dem nedan och gläd dig.

## Checklistan

Om du följer dessa instruktioner kan du inte misslyckas:

1.  Avge ett högtidligt löfte om att du aldrig, aldrig någonsin, kommer att gå ut på nätet för att besöka ditt harem *ELLER* nöja dig med statiska bilder * ELLER* förlika dig med erotisk grafik *ELLER* något som innehåller supernormala stimuli, och håll dig sedan till ditt löfte.

2.  Få detta klart för dig: Det finns överhuvudtaget ingenting att ge upp. Det betyder inte att du kommer att få det bättre som icke-PMO:are (det har du vetat hela tiden); inte heller att du inte, trots att den rationella anledningen till att du PMO:ar är obefintlig, får någon form av njutning eller stöttning av det. Hade det inte varit så, skulle du inte ha gjort det. Vad som avses är att det inte finns ***något genuint nöje eller någon stöttning med PMO.*** Det är bara en illusion, som att slå huvudet mot en vägg för att känna njutning när man slutar.

3.  Det finns inget sådant som en bekräftad PMO:are. Du är bara en av de hundratals miljoner som har fallit i den subtila fällan. Precis som de miljontals andra ex-användare som en gång trodde att de inte kunde fly, så har du flytt.

4.  Om du någon gång i ditt liv skulle väga för- och nackdelarna med PMO mot varandra skulle den överväldigande slutsatsen alltid vara "*Sluta göra det. Du är en idiot!*" Ingenting kommer någonsin att ändra på det. Det har alltid varit så och kommer alltid att vara så. När du har fattat vad du vet är det rätta beslutet, plåga dig aldrig genom att tvivla. Pascals satsning passar perfekt på PMO -- inget att förlora, stora chanser att vinna.

5.  Försök inte att undvika tänka på porr och oroa dig för att du tänker på det hela tiden. Varje gång du tänker på det, oavsett om det är idag, imorgon eller resten av ditt liv, tänk **"HURRA! JAG ÄR EN ICKE-PMO:ARE!"**

6.  **Använd inte** någon form av substitut. **Du får inte** utmana dig själv genom att ha din bärbara dator bredvid dig när du sover. **Undvik inte** pjäser, filmer eller tidningar. **Förändra inte** din livsstil på något sätt endast på grund av att du har slutat. Om du följer ovanstående instruktioner kommer du snart att uppleva "uppenbarelsens ögonblick", men:

7.  Vänta inte på att "uppenbarelsens ögonblick" ska komma. Fortsätt bara att leva ditt liv, njut av höjdpunkterna och hantera nedgångarna. Ögonblicket kommer att komma på nolltid.
