# Hjälp Dem På Det Sjunkande Skeppet

Porranvändare drabbas numera av panik eftersom de känner av förändringar i hur internetporren uppfattas idag. Internetporrens beroendeframkallande natur undersöks allt oftare och anses nu med rätta skilja sig från traditionell pornografi. Enkelheten och lättillgängligheten väcker oro även i porrförespråkarnas hjärtan. De känner också att deras korståg för yttrande- och tankefrihet håller på att kapas av olika aktörer. Den vilda västern med det okontrollerade internet gör det nästan omöjligt att införa åldersgränser för supernormala stimuli. Att det här inte kommer att upphöra i närtid är beklagligt, men hundratusentals användare slutar. De flesta missbrukare är väl medvetna om studier som visar på likheter mellan porr och substansberoende. Varje gång en användare lämnar det sjunkande skeppet känner sig de som är kvar på det ännu olyckligare.

Alla användare vet instinktivt hur löjligt det är med självsabotage och att ägna tid framför tvådimensionella pixlar, där hjärnan överspolas och man i processen utvecklar nervbanor som garanterar dåliga sexuella prestationer. Om det fortfarande inte känns löjligt kan stå mitt i stan och prata med en porrtidning och fråga dig själv vad skillnaden är. Bara en. Du uppnår inte njutningen av värme och intimitet på det sättet. Om du kan sluta köpa alkohol och cigaretter varje gång du handlar mat så kan du definitivt sluta besöka ditt nätharem. Användarna kan inte hitta förnuftiga skäl för att titta på porr, men de känner sig inte lika dumma om andra människor också gör det.

Användarna ljuger öppet om sina vanor, inte bara för forskare och personer i deras omgivning, utan även för sig själva. De måste göra det, hjärntvätten är nödvändig om de ska kunna behålla någon form av självrespekt. De anser sig behöva rättfärdiga sin "vana" inte bara för *själv* utan även för icke-användare. De gör ständigt reklam för porrens illusoriska fördelar på ett subtilare sätt.

Om en användare slutar med hjälp av viljestyrka känner han eller hon sig fortfarande berövad och tenderar att bli en gnällspik. Allt det här bekräftar för andra användare hur rätt de har att fortsätta använda. Om ex-användaren lyckas sluta med vanan är han tacksam över att slippa ett liv med självsabotage eller energislöseri och behöver därmed inte rättfärdiga sig själv. Kom ihåg att det är rädslan som får användaren att hålla huvudet i sanden och bara ifrågasätta sitt beteende när han väl slutar. Hjälp användaren genom att ta bort denna rädsla. Berätta för dem hur fantastiskt det är att inte behöva leva livet som i ett fängelse, hur härligt det är att vakna på morgonen och känna sig frisk och hälsosam i stället för orkeslös och fylld av självförakt. Bekriv det underbara i att vara fri från slaveri, att kunna njuta av hela sitt liv och att bli kvitt de svarta skuggorna. Eller ännu hellre, få dem att läsa den här boken.

Det är väsentligt att inte nedvärdera en gift användare genom att antyda att hen medvetet ruinerar sitt förhållande eller att det på något sätt är otrohet eller smutsigt. En vanlig missuppfattning är att ex-användaren är värst i det avseendet. Den här uppfattningen har en viss substans, men beror i allmänhet på de som använder viljestyrka som metod för att sluta. Eftersom ex-användaren -- även om hen har slutat med vanan -- fortfarande har kvar en del av hjärntvätten och fortfarande tror sig ha gjort en uppoffring. De känner sig sårbara och den naturliga försvarsmekanismen är att attackera porranvändaren.

Detta kan stärka ex-användarens ego, men det hjälper inte användaren alls. Det enda som händer är att de ställs med mot väggen och känner sig ännu eländigare och följaktligen blir behovet av porr ännu starkare. Även om läkarkårens inställning till internetporr har förändrats är den främsta anledningen till att många användare slutar, så innebär inte det att det blir lättare att sluta. I själva verket blir det mycket svårare. De flesta användare tror idag att de i första hand slutar av hälsoskäl. Detta är inte helt sant.

Trots att den enorma hälsorisken givetvis är det främsta skälet till att sluta, har användare i åratal saboterat sin potens utan att det har gjort den minsta skillnad. Den främsta anledningen till att användarna slutar är att samhället börjar se porren för vad den är: Drogmissbruk. Attityderna i samhället håller långsamt på att förändras -- många partners ställer numera frågor om du sitter med din laptop mitt i natten.

Vissa länders totalförbud mot porr eller otillgängligt internet är klassiska exempel på den resande användarens dilemma. De antar generellt sett attityden att det kommer att hjälpa dem att minska sitt intag. Resultatet blir att de i stället för en eller två njutningslösa sittningar om dagen avstår i en hel vecka. Under denna påtvingade avhållsamhet kommer de dock inte bara att vara mentalt berövade i väntan på belöningen, utan deras kropp suktar likaså. Åh, så värdefullt det haremsbesöket är när de till slut får lov att göra det.

Påtvingad avhållsamhet minskar faktiskt inte konsumtionen eftersom användaren bara unnar sig ännu mer när han äntligen får vara ensam. Allt det leder till är att användaren får inpräntat hur värdefull internetporren är och hur beroende han är av den. Den mest försåtliga aspekten av denna påtvingade avhållsamhet är dess effekt på ungdomar. Vi tillåter "yttrandefrihetens" kapare, porrproducenterna, att rikta in sig på stackars tonåringar för att få dem beroende från första början. Sedan, under vad som förmodligen är den mest stressiga perioden i deras liv, när de i sina vilseledda huvuden behöver porren mest av allt, utövar vi utpressning mot dem för att de ska sluta på grund av den skada de åsamkar sig själva.

Många är inte kapabla att sluta och tvingas, utan egen förskyllan, lida av ett skuldkomplex resten av livet. Många lyckas och är nöjda med det och tänker: "Bra. Jag gör det här nu och när det hela är över är jag i alla fall botad.\"* Sedan kommer smärtan, ångesten inför att alla vuxenproblem, följt av den största "höjdpunkten" i deras liv -- att hitta ett jobb. Smärtan försvinner och rädslan är över, nu känner de sig trygga och den gamla triggermekanismen börjar åter fungera. En del av hjärntvätten finns fortfarande kvar och innan lukten av den nya bärbara arbetsdatorn hunnit försvinna står användaren på tröskeln till sitt favoritharem på nätet. Glädjen över händelsen stänger ute de dåliga känslorna, de har inte för avsikt att bli beroende igen, men en liten titt kan inte skada... 

För sent! De sitter redan fast igen.

Det gamla suget från det lilla monstret kommer att ta fart igen och även om de inte blir beroende direkt, så kommer förmodligen depressionen efter ruset att fånga upp dem. Ett märkligt faktum är att även om heroinister är lagligt sett kriminella, så är samhällets reaktion att hjälpa dessa individer. Låt oss anta samma inställning till den stackars porranvändaren. Han använder inte porr för att han vill, utan för att han tror att han måste. Till skillnad från heroinmissbrukaren måste porrmissbrukaren vanligtvis utstå flera år av psykisk och fysisk tortyr. Vi säger alltid att en snabb död är bättre än en långsam, så avundas inte de stackars porranvändarna. ***De förtjänar ditt medlidande.***
