# Råd för icke-användare

## Hjälp dina porranvändande vänner att läsa den här boken.

Studera först innehållet i denna bok och försök att sätta dig in i användarens situation. Försök inte få dem att läsa boken genom att påtala att de förstör sin hälsa eller leker med elden. Det vet de bättre än du själv. Användare fortsätter inte med porr för att de gillar det eller för att de vill, de intalar bara sig själva och andra människor det för att behålla sin självrespekt. De är beroende av porren och tror att den hjälper dem att slappna av, gör dem modiga och självsäkra (njutning eller stöd) och att livet aldrig kommer att vara roligt utan "sex" -- åtminstone deras version av det. En användare som känner sig tvingad att sluta kommer att känna sig som ett instängt djur och vilja besöka sitt nätharem ännu mer. På så vis kan han bli en hemlig användare och porren blir då än mer värdefull i deras medvetande.

Fokusera hellre på den andra sidan av myntet, få dem att förkovra sig med ex-användare (bloggar, forum, YBOP, NoFap osv.). Få dem att berätta för användaren hur de också trodde att de var fast för livet och hur mycket bättre livet som icke-användare är. När du väl har fått dem att inse att de kan sluta så kommer deras sinne att börja öppna sig. Därefter kan du förklara illusionen som skapas av abstinensbesvären. Inte bara ger "dopaminrusningarna" dem ingen boost, de raserar också självförtroendet och gör dem irriterade och trötta.

De bör nu vara redo att själva läsa boken och förväntar sig att läsa sida efter sida med berättelser om opålitlig upphetsning, sviktande penetrering, PIED, PE osv. Förklara att den här metoden är helt annorlunda och att hänvisningar till olika sjukdomstillstånd bara utgör små brottstycken av materialet.

Kort sagt, låt inte detta dö i mörkret. Berätta för dina vänner, men gör det utan att vara konstig. Om du försöker "vinna" samtalet eller föra en debatt kommer du bara att alienera dem och spä på deras rädsla ytterligare.

## Ska jag berätta för min partner?

Ska jag berätta för min fru, flickvän eller partner om min vana? Avsikten är att hjälpa dig att sluta och det finns flera faktorer som spelar in här.

Har du redan gjort misslyckande försök att sluta med viljestyrka och redan har berättat det för din partner, berätta då om din nya metod och låt dem utbilda sig genom att läsa boken. De kan hjälpa och motivera dig under abstinensperioden och vara ett stöd när det lilla monstret försöker lura dig.

Om du först nu har blivit medveten om porrfällans existens och inte har försökt sluta tidigare, använd först EasyPeasy själv. Som förklarats tidigare ska detta vara en trevlig upplevelse. Men om du tycker att det är svårt kan du be om deras hjälp. Var öppen och sårbar med din partner, det kommer att stärka er relation.

Så länge du njuter av att rymma och obeslutsamheten inte gör det svårt så finns det ingen större anledning att berätta det för din partner. Var det tidigare inte ett problem så låt det dö. Förbered dig dock på att din partner kan komma att undra varför du, mår bättre, presterar bättre och ser bättre ut!

## Min partner slutar med porr

Porr är en pervers relationsförstörare och även om det går att sluta omedelbart så tar det tid att läka. På grund av irrationella föreställningar som fötts av deras missbruk tar många användare ut ilskan på sin partner och sina nära och kära. Dessa beteenden yttrar sig i gaslighting, lögner och manipulativa beteenden. Det gäller inte alla användare, men det är allt vanligare i senare stadier av sjukdomen. Även om dessa beteenden har utvecklats av det underliggande porrberoendet är det viktigt att utbilda sig om dessa beteenden. Överväg att gå till en terapeut som specialiserat sig på sexuella beroenden om de känns igen.

Om din partner befinner sig inom abstinensperioden ska du anta att han lider oavsett om så är fallet eller inte. Försök inte att förringa det genom att berätta för dem hur lätt det är att sluta, det klarar de själva. Berätta i stället för dem hur stolt du är, hur mycket mer välmående de ser ut, hur mycket härligare det är att umgås med dem och hur mycket lättsammare de är rent generellt. Det är särskilt viktigt att fortsätta med det här, när en användare försöker sluta kan euforin av försöket och det beröm de får från kamrater hjälpa dem på traven. De har dock en tendens att glömma snabbt, så fortsätt att berömma dem.

I och med att de inte pratar öppet om porren kan det vara lätt att tro att de har glömt och inte vill att du ska påminna dem. Vanligtvis är det helt motsatta fallet med viljestyrkemetoden, eftersom ex-användaren oftast inte kan tänka på något annat. Så räds inte att ta upp ämnet och fortsätt att berömma dem, de talar om för dig om de inte vill bli påminda.

Gör allt i din makt för att avlasta dem från påfrestningar under abstinensperioden och fundera över sätt som gör deras liv intressant och roligt. Detta kan också vara en prövande period för icke-användare som aldrig har varit beroende. Om en medlem i en grupp är irriterad så kan det leda till allmänt elände för alla i gruppen. Förutse därför ex-missbrukarens irritation. Det kan mycket väl hända att de tar ut det på dig, men ge inte igen. Vid den här tiden behöver de ditt beröm och din sympati allra mest. Känner du dig själv irriterad, vilket också är förståeligt, försök att inte visa det.

Ett av de knep som missbrukare använder sig av när man försöker sluta med hjälp av viljestyrkemetoden är att få vredesutbrott. I hopp om att partnern eller vännerna ska säga "*Jag står inte ut med att se dig lida på det här viset. För Guds skull, ta bara ditt gift.*" Användaren behöver alltså inte tappa ansiktet, de "ger inte upp", de har fått instruktioner. Om din porrslutande partner använder det här knepet ska du under inga omständigheter uppmuntra honom att återfalla i missbruk. Säg i stället: "*Om det här är vad porr gör med dig, tack och lov kommer du snart att vara fri. Så fantastiskt att du hade modet att ge upp.*"

Kom ihåg att det finns två helande parter inom återhämtningsresan. När din partner slutar med porr är det viktigt att du har ditt eget stödnätverk, rutiner för egenvård och gränser. Den här processen sker inte över en natt och kräver förtroende, kommunikation och ansvarstagande. Journalföring, utveckling av egna passioner och framför allt terapi hjälper denna process.

## Snedsteg (återfall)

Det här avsnittets existens bör tjäna som en varning för de som lämnar fällan. Jag har personligen aldrig återfallit, men kommer att använda erfarenheter från intervjuer med samhällsmedlemmar och verktyg från kognitiv beteendeterapi för att illustrera detta.

För det första är det kontraproduktivt att kalla det ett återfall. Allt som har hänt är att du har halkat och gett mat åt det lilla monstret, som i sin tur startar igång det stora hjärntvättsmonstret. Användare som snubblar (vilket per definition är att falla framåt) ger vanligtvis upphov till en hel rad irrationella föreställningar:

- "*Jag kommer aldrig att bli fri*" - **Katastrofisering**
- "*Jag borde/måste träna, studera och vara fruktbar varje dag i mitt liv*" (alias **måsterbation**).
- "*Jag har PMO:at idag, vad är det för mening med att läsa alla böcker och forum... Mitt mål var att inte ens att O, men här är jag - ett misslyckande - ett återfall.*" - **Låg frustrationstolerans**
  - "*Mina vänner/forumläsare/andra PMO:ar inte under (x) dagar, men jag kan inte avstå så jag är ett hopplöst fall. Igår pluggade jag bra och var produktiv och mådde bra, men idag var jag inte det... Det går utför för mig.*" - **Jämför sig med andra**
- "Jag borde inte ha sexuella tankar" - De själva, föräldrarna eller samhället som helhet har installerat **strama föreställningar** i förhållande till sex. Fråga dig själv om självutplåning hjälper dig att nå dina mål, och om så är fallet, njuter du av resan?

Faktorer som kulminerar till varje användares hjärntvätt är till synes oändliga. Du känner dig själv bättre än någon annan, det är uppenbarligen ett misslyckande att följa instruktioner. Du såg ett värde i porren, men hur?

Något som ofta förbises är att det tar tid att upphäva hjärntvätten. Det gör det inte svårare, men nästan alla branscher använder sig av sex. Att aktivt motverka hjärntvätt är en medveten process (åtminstone inledningsvis), så det kan ta tid att fullt ut befästa de lärdomar som finns i den. Därför rekommenderas flera läsningar (du kan hoppa över kapitel som du har svårt för) och det bör inte ta lång tid.

Något som är förvånansvärt vanligt för religiösa användare som lämnar fällan är att de vill att det ska smärta lite som en form av försoning. De tycker att det är så lätt att sluta och känner sig sedan skyldiga för att de känner så. Men varför sabotera sig själv och försvåra situationen? Det lilla monstret är väldigt lömsk i detta avseende.

Ta avstånd från det lilla monstret som tillsattes av porrindustrin för länge sedan. Tänk dig en mobbare som får ett utbrott på skolgården. Vad säger du till en mobbare? Om du ger efter kommer du bara att förstärka dem. En del slutar ge mobbaren mat och ökar därmed deras hjärntvätt, men uppfattningen om fällan har inte förändrats. Res dig upp, ta reda på var du gjorde för fel och njut av friheten!

Du är inte ditt begär. Mindfulness-meditation är en övning i att uppmärksamma tankarna och där finns grundläggande lärdomar om sinnets natur att finna. Att meditera i allmänhet rekommenderas starkt, och det är också helt förenligt med religiös praktik. Du kan inte bekämpa dig själv eller det lilla monstret. Du måste villkorslöst älska dig själv och processen.

Men avlägsna misslyckandet från ditt sinne. Här är ett avsnitt från "*Meditations of a Porn Addict*" av Gulliaco (länkad i resursavsnittet i slutet av boken).

> Eftersom det ger dig noll fördelar att titta på porr, eftersom det är något som bara skadar dig, och är extremt löjligt att vilja göra något sådant jämför jag det med att dricka blekmedel. Varsågod:
>
> **Den jobbiga resan mot att inte dricka blekmedel.**
>
> Hej! Vi är NoBleach och vi anordnar rebootingutmaningar där deltagarna ("Bleachstronauter") under en viss period avstår från att dricka blekmedel. Ditt mål kan vara att tillfälligt delta i en månatlig utmaning som ett test av självkontroll. Kanske har ett överdrivet blekmedelsdrickande blivit ett problem i ditt liv och du vill sluta för en längre tid. Oavsett vad kommer du här att hitta en stödjande gemenskap och massor av resurser.
>
> > - "*Ibland tillåter jag mig själv att dricka ett eller flera glas blekmedel. Jag vet om att "en droppe" är lögn, men jag tror inte att ett enda glas skadar. Man kan inte förstöra alla de timmar som jag har tillbringat utan att göra det.*"
> - "*Jag har inga problem med att sluta dricka blekmedel, men ibland går jag ner på gatan och ser någon som dricker vatten, du vet, i ett glas, och jag föreställer mig att glaset har blekmedel i sig. Då får jag ett sug och efter att ha diskuterat med mig själv om jag ska göra det eller inte, ger jag till slut efter på kvällen och dricker ett glas.*"
> - "*Så, mitt problem är att ibland, när jag är ensam i köket, börjar jag se glasen. Ibland frestar jag mig själv genom att öppna blekmedelsflaskan, ibland luktar jag på det och... Ja, då hamnar jag åter där jag började. Jag vill så desperat sluta med det här, men jag är inte säker på om jag någonsin kommer kunna sluta.*"
> - "*Att sluta dricka blekmedel är omöjligt, jag menar, jag kommer ju alltid att ha en mun, du vet? Hur ska jag kunna sluta om jag alltid har en hals som påminner mig om att jag kan svälja blekmedel?*"
> - "*Oh fan, det gick så bra, 19 hela dagar utan att dricka. Det viktiga är att lära sig av misslyckanden! Nu vet jag vad jag ska undvika att göra: att titta på rengöringsmedel i snabbköpet. Jag ska försöka klara en månad! Jag ska ställa om min räknare. Önska mig lycka till!*"

> Om du får ett begär så lugna ner dig, kompis! Kom ihåg vad hackboken säger:
>
> "*Blekmedel är svårt att ge upp på grund av rädslan att vi blir berövade vår njutning eller vårt stöd. Rädslan för att vissa lustfyllda situationer aldrig riktigt kommer att bli desamma igen. Rädslan för att inte kunna hantera stressiga situationer. Med andra ord är det effekterna av hjärntvätt som lurar oss att tro att det är ett måste för alla människor att köpa, och i förlängningen dricka, blekmedel. Vidare är det övertygelsen att det finns något inneboende i prisvärda blekmedel som vi behöver, och att när vi slutar använda dem kommer vi att förneka oss själva och skapa ett tomrum. Gör detta klart för dig: Blekmedel fyller inte ett tomrum, det skapar ett!*"
> 
> Och jag säger:
> "*Anta att du tvingas titta på ett glas med blekmedel i fem minuter. Försök att komma ihåg ett av de märken eller dofter som du tyckte så mycket om. Kanske åtföljs det av något ljud, eller så minns du bara utvalda detaljer. Blekmedlet finns där och du kan inte blunda eller vrida på huvudet, för detta blekmedel existerar i din hjärna, det är ett minne som registrerats inuti dig*.
>
> ** Känner du något sug? Känner du något i tungan eller någon förändring i din andning? Vilka känslor har du inför det du minns? Identifiera dem, blekmedlet vill fördunkla dem, förvirra dem och få dig att bara uppmärksamma det som vill fånga dig.*"
>
> Med ovanstående försöker jag inte avfärda dina känslor, än mindre säga något i stil med "haha, jag smart, du dum". Jag vill sätta saker i perspektiv så att du inser hur löjligt enkelt det är (och alltid kommer att vara) att övervinna det här beroendet.
> Att titta på porr är inte som en på/av-knapp där du säger "*åh ja, jag är i situation X, då tittar jag på porr*". Fantasier! Lögner! Hur ofta tillåter du dig själv att dricka ett glas blekmedel? Aldrig? Varför? Därför att det är en hemsk sak att göra! Hur ska du kunna fly undan ditt missbruk om du inte inser att PMO är en hemsk sak att göra mot dig själv?

## Hur är det med MO ("masturbation, orgasm")?

Människor har runkat i evigheter utan problem. För att vara helt tydlig så är det porren som är problemet.

Med det sagt kan du fortfarande bli beroende av MO av samma skäl som porr, till exempel "måste få orgasm"-mentaliteten, mental eskalering, att tvinga kroppen att ha sex, och helt enkelt hendonistiskt njutningssökande.

Det är ytterst troligt att porr och onani har blivit djupt sammanflätade i ditt sinne. Många användare upptäcker att de hamnar i återfall till följd av att de onanerar till porrinducerade fantasier. I takt med att din hjärna kopplas om kommer du att upptäcka att denna hjärntvätt så småningom försvinner, men det är bäst att ta en paus från MO ett tag. Du bör också söka dig till riktigt sex för att påskynda denna process.

Detta är visserligen ingen instruktion, men utvärdera den. De rapporterade fördelarna med att behålla sperma är många -- ökat fokus och energi, avlägsnande av "hjärndimma" och ökat självförtroende tillsammans med en mängd andra fördelar. Enligt personlig erfarenhet finns det en tydlig skillnad, och allt beror på hur du transmuterar denna ökade energi.

Om man spekulerar, och utan strikt vetenskaplig kunskap, kan fördelarna bero på ett par olika faktorer.

- Efter orgasmen frisätter hjärnan prolaktin, vilket hämmar dopaminfrisättningen.

- Om du berövar hjärnan dopaminsköljningar kan du få mer upptag från att helt enkelt leva livet.

- Sperma återabsorberas av blodomloppet efter ~78 dagar och är en av de bästa näringsämnena som din kropp kan få.

- Att omvandla sexuell energi till produktiva vanor ger ett extra lager av produktivitet.

Du kanske vill ha sex utan orgasm också, vilket som tidigare nämnts är en underbar sexuell upplevelse. Du kan stärka din förmåga att göra detta genom att utöva Kegelövningar. Av personlig erfarenhet är det enklaste och mest effektiva sättet att rikta in sig på denna muskel att stoppa urinen mitt i strömmen. Att separera den tantriska och den fortplantande delen av sexet är en av de många bonusarna med att komma ur PMO-fällan (och mina partners har också älskat det!).

## Avvikelser från de standardiserade råden

Det här är ett nytt avsnitt, skrivet på ett lite bekymmersamt sätt, men det måste ändå nämnas.

Vissa personer som använder EasyPeasy upptäcker att deras lust att titta på porr blir så kraftigt reducerad att de inte kan förmå sig att ha en sista sittning. **Det är bra**, men underskatta inte kraften i att ha en sådan. Att medvetet surfa runt och befästa hur mycket du ogillar PMO kan vara riktigt kraftfullt. Personligen fann jag det verkligen användbart och var glad att tvätta mina händer rena från det; uppriktigt lättad över att aldrig behöva göra det någonsin igen. Men din erfarenhet kan variera.

Har du redan frigjort dig från fällan sedan ett tag tillbaka och precis avlägsnat hjärntvätten så finns det ingen anledning att mata det lilla monstret eftersom det bara skulle plåga dig. Njut istället av friheten!

## Hjälp till att få slut på denna skandal

Internetporr är en av det fria samhällets stora faror eftersom den åker snålskjuts på den personliga frihetens välvilliga ansträngningar. Själva grunden för en civilisation -- anledningen till att den mänskliga arten har kommit så långt -- är att vi kan kommunicera vår kunskap och våra erfarenheter, inte bara till varandra utan även till kommande generationer. Till och med djur finner det nödvändigt att varna sin avkomma för livets fallgropar.

Porrproducenterna gör det inte i god tro utan tror att de verkligen att de hjälper mänskligheten, särskilt nu när beroendet av internetporr är föremål för omfattande studier. I början trodde man antagligen att porr lärde människor om intimitet, men myndigheterna vet att det är en villfarelse. Inte en enda tubsajt gör några verkliga anspråk genom att hävda att den är utbildande. De enda påståenden som görs handlar om chock, nyheter och eskalerande kvalitet på deras produkter.

Hyckleriet i frågan är helt ofattbart. Vi som samhälle upprörs av skolmobbning och objektifiering av människokroppen, men ställt mot internetporr är dessa problem att likna vid problem med finnar. Antalet missbrukare ökar årligen till nya nivåer och ödslar kvalitetstid med imaginära pixelmänniskor på bekostnad av sin hälsa, virilitet, energi och tid. Det är den överlägset största relationsdödaren och hundratusentals liv fördärvas varje år på grund av att de fastnar i beroende. Producenterna av internetporr annonserar inte i vanliga publikationer -- det behövs inte. Våra biologiska drifter leder oss över trösklarna till deras välfyllda harem där de bjuder på gratisprover likt den lokala langaren. Dagens porrsidor har inte så mycket varor på lager så mycket som att de uppmuntrar besökarna att lägga upp egen content.

Visst är det smart av porrföretagen att visa 18+-varningar för att avskräcka minderåriga användare, men vissa bemödar sig inte ens med att göra det. Nätporr påverkar alla i alla åldrar. "*Vi varnade dig för faran, nu är det ditt val.*" Det är deras inställning. Vidtar de några åtgärder för att kontrollera åldern? Nej, det skulle ju avskräcka deras kunder. Om åldersverifiering införs i lag kommer de bara att hitta ett annat land att bedriva sin verksamhet ifrån. Eller ska de betala någon "elit" som skriver om hur förbudet resulterade i smuggelförsäljning och skapandet av maffian? Bekvämt nog försummas frågan om varför förbudets upphävande inte resulterade i en minskning av antalet alkoholrelaterade dödsfall och att de polisiära myndigheterna misslyckades med att kontrollera maffians framväxt.

Vi kan ta itu med det här genom att utbilda den yngre generationen. Om de kan undvika cigaretter och alkohol när de handlar kan de göra detsamma med internetporr. Vi ser redan nu samhällsförändringar i form av att memes som "No Nut November" och "Coomer" börjar få en spridning i samhället. Användaren har inget val, lika lite som heroinisten har det. Användarna bestämmer sig inte för att bli beroende, de lockas in i en subtil fälla. Hade de fått välja skulle de enda användarna i morgon bitti vara ungdomar som precis börjat och som tror att de kan sluta när som helst om de vill.

Varför de falska kraven? Hur kan heroinister betraktas som brottslingar, medan de ändå kan registrera sig som missbrukare, få metadon och korrekt medicinsk behandling för att hjälpa dem att sluta med det? Prova du bara att registrera dig som porrmissbrukare. Om du vänder dig till en läkare för att få hjälp så kommer de förmodligen antingen att säga: "Sluta göra det så ofta, försök med måttlighet". Du vet redan att det inte fungerar. Eller så skriver de ut mediciner för att behandla din "depression". Än värre är rådet att gå ut och söka riktiga partners. Allvarligt talat? Är de medvetna om att det finns användare som föredrar porr och använder den bakom ryggen på sin partner? Somliga förstår bara inte.

Skrämselkampanjer bidrar inte till att hjälpa användarna att sluta, det försvårar det. Allt de gör är att skrämma användarna, vilket gör att de vill titta ännu mer. De hindrar inte heller tonåringar från att bli beroende. Tonåringar vet att porr dödar deras libido, men de vet också att en enda titt inte räcker för att fastna. Eftersom porrmissbruket är så utbrett kommer tonåringen förr eller senare -- på grund av antingen sociala påtryckningar eller ren nyfikenhet -- att ge sig på ett enda besök. Eftersom gratis porr har förskräckliga filmer är det sannolikt att de också kommer att bli beroende.

Hur kan vi tillåta denna skandal att fortgå? Varför kommer inte regeringarna med ordentliga kampanjer? Varför informeras vi inte om att internetporr är en drog och ett dödligt gift? Att den varken får dig att slappna av eller att få bättre självförtroende, utan att den förstör dina nerver? Att det räcker med en enda titt för att du ska fastna i ett beroende? Varför kan de inte införa åldersverifiering genom att begära registrerade kreditkort, kanske med en tredje part? Mindgeek, som äger många av de stora porrsidorna, försöker lura regeringar att använda sin egen patentskyddade lösning för ålderskontroll. Låt dem inte göra det! I H. G. Wells *The Time Machine* beskrivs en händelse i en avlägsen framtid där en man faller i en flod. Hans följeslagare sitter bara runt stranden som boskap och är omedvetna om hans desperata rop. Omänskligt och upprörande, precis som samhällets apatiska inställning till porrkrisen.

Men, det blåser en förändringens vind i samhället. Snöbollen har börjat rulla nerför backen och förhoppningen är att den här boken ska hjälpa till att göra den till en lavin. Du kan också hjälpa till genom att sprida budskapet.

Om du ser någon som brottas med viljestyrka eller som försöker sluta med porr, vänligen visa dem den här metoden. Den stora uppgiften är dock att förändra narrativet kring porr i allmänhet. Överväg att ta för vana att om du ser något på nätet, eller till och med upplever porrens normalisering på nära håll, så strävar du efter att *respektabelt* utbilda och befria dem.

Det kan hända att du ibland får en negativ reaktion, men i vissa fall räcker det med en kommentar. Som många andra har gjort före dig kan du förvänta dig meddelanden från tacksamma människor som tackar dig för deras frihet.

## En sista varning

Du kan nu njuta resten av ditt liv som en lycklig icke-användare. För att försäkra dig om att du gör det måste du följa dessa enkla instruktioner:

1.  Behåll följande sida i dina bokmärken och hänvisa till den så ofta du behöver.

2.  Skulle du någonsin börja avundas en annan användare, inse att det är han som är avundsjuk på dig. Du blir inte berövad. Det är de som blir det.

3.  Kom ihåg att du inte njöt av att vara användare. Det var därför du slutade. Du njuter av att vara icke-användare.

4.  Kom ihåg att det inte finns något som heter "bara en titt".

5.  Tvivla aldrig på ditt beslut att sluta titta på porr. Du vet att det är det rätta beslutet.

6.  Om du upplever problem, hitta och kontakta en terapeut som är kunnig inom internetporr. Det finns listor över dessa på nätet.
