# Instruktionerna

1.  Följ alla instruktioner.

2.  Var öppetsinnad.

3.  Börja med känslan av upprymdhet.

4.  Ignorera alla råd och influenser som strider mot EasyPeasy.

5.  Motstå alla löften om en tillfällig lösning.

6.  Få det klart för dig: Porr ger varken någon genuin njutning eller ett riktigt stöd och du gör ingen uppoffring. Det finns ingenting att ge upp och ingen anledning att känna sig berövad.

7.  Dröj inte med att sluta, gör det nu!

8.  Ta ett beslut att aldrig titta igen och ifrågasätt det aldrig.

9.  Kom ihåg att det inte finns något sådant som bara en titt.

10. Titta aldrig mer på porr igen.

## Affirmationer

- Jag är fri från porrens slaveri.

- Det är lätt att ignorera mina tankar om porr.

- Hej då tankar, hej då drifter. Åh, där försvinner mina begär.

- Jag fokuserar mitt undermedvetna sinne för att övervinna porrberoendet.

- Porren rånar mig på min tid, energi och vitalitet.

- Att besegra porren blir exponentiellt lättare dag för dag och i varje aspekt.

- Jag njuter av och värdesätter min porrfria, starka, lyckliga, enkla och lättsamma livsstil.

- Om jag ser tillbaka och tänker på mina framsteg skänker det mig stor glädje och stolthet över mig själv.

- Varje gång jag ser andra porranvändare blir jag mer motiverad av att se mig själv bryta den kedjan.

- Det är all den uppdämda energin som läker min kropp och mitt sinne. Därefter kan jag vara mer produktiv och utmanande när jag arbetar mot mina värderingar och mål.

- Min hjärna återfår sin rätta form och tränas genom att jag *inte* gör det jag tidigare gjorde.

- Jag utnyttjar nu all denna uppdämda viljestyrka för att hantera livets lätta påfrestningar.

- Toppen, jag är fri och inte längre en slav!
