# Łatwa metoda

Celem tej książki jest nakierowanie cię na inny sposób myślenia. W kontraście do zwykłej metody rzucania – gdzie zaczynasz myśląc o wspinaczce na Mount Everest, a potem przez kilka tygodni czujesz się wygłodniały i wybrakowany – tutaj zaczynasz od poczucia ulgi, jakbyś był wyleczony z jakiejś okropnej choroby. Od chwili, w której skończysz, im dalej idziesz w życiu, tym częściej będziesz spoglądał na ten okres twojego życia zastanawiając się po co kiedykolwiek w ogóle używałeś pornografii. Będziesz się patrzył na innych użytkowników z żalem, a nie z zazdrością.

Jeśli nie jesteś kimś uzależnionym (na przykład czytasz to dla swojej sympatii), bądź skończyłeś używać i potrzebujesz wsparcia, ważnym jest żebyś nadal oglądał pornografię, aż skończysz czytać książkę. Może to się wydawać sprzecznością, a to zalecenie dalszej masturbacji wywołuje najwięcej sprzeciwu - wierz mi, że im dalej w las – tym twoja ochota na oglądanie porno będzie mniejsza. Mówię poważnie – **próby wcześniejszego rzucenia nie będą miały żadnego pozytywnego skutku**.

Wiele osób nie kończy czytać, bo mają wrażenie, że pozbędą się czegoś ważnego, albo celowo czytają jedno zdanie dziennie, żeby odłożyć ten straszny moment. Spójrz na to w ten sposób – co masz do stracenia? Jeśli nie rzucisz po skończonej lekturze, to w twoim życiu nic nie będzie gorsze. To jest definicja zakładu Pascala – gra w której nie masz nic do stracenia, a możesz bardzo dużo zyskać.

Tak samo, jeśli nie oglądałeś pornografii i nie masturbowałeś się przez kilka dni bądź tygodni, ale nie jesteś pewien czy jesteś uzależniony, czy nie, nie oglądaj więcej. Właściwie to już nie jesteś użytkownikiem, ale twój mózg musi dogonić twoje ciało. Gdy skończysz czytać będziesz szczęśliwym, wolnym od pornografii człowiekiem. Koniec z Porno jest całkowitym przeciwieństwem normalnej metody, gdzie wypisuje się minusy pornografii:
„*Jeśli tylko nie będę oglądał przez dłuższy czas, moje pragnienie przejdzie i będę mógł się cieszyć życiem, jako wolny człowiek.*”

Jest to logiczny sposób, którego używa tysiące ludzi każdego dnia, ale mimo tego droga jest trudna z trzech powodów:

**Zaprzestanie PMO nie jest problemem.**
Za każdym razem, gdy kończysz sesję, to przestajesz używać. Możesz mieć silne powody i przekonania pierwszego dnia, żeby trzymać się swojej diety 'raz na cztery dni'. Możesz nawet mówić, że nie chcesz oglądać porno i nawet się masturbować. Każdy użytkownik tak mówi, a ich powody są dużo silniejsze niż sobie to wyobrażasz. Problemem jest dzień drugi, dziesiąty albo tysięczny gdzie w momencie słabości zdecydujesz się na 'podglądnięcie' jeden raz, który prowadzi do następnego, co prowadzi do nawrotu uzależnienia.

**Świadomość zagrożenia zdrowia powoduje więcej strachu, co utrudnia zaprzestanie.**
Powiedz użytkownikowi, że odbiera sobie męskość, a pierwsze co zrobi to poszuka czegoś co dostarcza dopaminy. Papieros, alkohol albo – pornografia.

**Wszystkie powody by przestać, tak naprawdę to utrudniają.**
Tak dzieje się z dwóch powodów. Po pierwsze – ciągle zmuszamy się do 'poddania' naszego sekretu, słabości czy przyjemności (zależnie od tego jak ty odbierasz swoje uzależnienie). Po drugie, kreuje się 'zasłonę'. Nie masturbujesz się z tego samego powodu, dla którego powinieneś przestać. Prawdziwe pytanie brzmi – dlaczego chcemy albo musimy to robić?

Z Koniec z Porno, na początku zapominamy o przyczynach naszych chęci do rzucenia, stajemy w szranki z problemem pornografii i odpowiadamy na następujące pytania:
1.  Co daje mi pornografia?
2.  Czy naprawdę daje mi to przyjemność?
3.  Czy naprawdę muszę iść przez życie sabotując swój umysł i ciało?

Piękną prawdą jest to, że *każda forma pornografii* jest dla ciebie absolutnie zbyteczna.
Może jaśniej – nie jest tak, że minusów pornografii jest więcej niż plusów, tu chodzi o to, że *nie ma**żadnych** plusów* oglądania porno.

Po pierwsze trzeba się ich pozbyć. Niedługo zrozumiesz, że tak naprawdę z niczego nie rezygnujesz. I to nie wszystko, bo gdy nie wchodzisz w cykl PMO, zyskujesz gigantyczne korzyści, a szczęście i dobre samopoczucie to tylko dwa z nich. W momencie, kiedy usuniesz przekonanie, że życie bez pornografii będzie gorsze i zrozumiesz, że jest dokładnie na odwrót, oraz gdy twoje poczucie wybrakowania się straci, powrócimy do tego dobrego samopoczucia i szczęścia, oraz wielu innych powodów do odstawienia porno. To zrozumienie będzie dla ciebie dodatkową, pozytywną pomocą w osiągnięciu tego czego naprawdę pragniesz – cieszenia się życiem bez bycia niewolnikiem pornografii!
