# Dlaczego tak trudno przestać?

Każdy uzależniony czuje jakby jakaś zła siła objęła nad nim kontrolę. Na początku sprawa jest prosta – *skończę, ale jeszcze nie dziś*, ale im dalej w las, tym bardziej wierzymy, że nie mamy siły przestać albo że w pornografii jest coś czego będzie nam brakować przy cieszeniu się życiem. Uzależnienie od porno można porównać do wychodzenia ze śliskiej dziury: już wychodzisz, czujesz ciepłe promienie słońca na twarzy, ale zaraz zjeżdżasz z powrotem na dół, gdy tylko masz gorszy dzień. W końcu otwierasz przeglądarkę i masturbując się czujesz się okropnie i zastanawiasz się, dlaczego w ogóle to robisz.

Zapytaj uzależnionego – „*czy gdybyś mógł wrócić do momentu kiedy nie byłeś uzależniony, z wiedzą którą posiadasz dziś – oglądałbyś?*”

„*W ŻYCIU!*” - taką usłyszysz odpowiedź.

Zapytaj kogoś kto używa i broni internetowego porno, kogoś kto nie wierzy, że pornografia powoduje problemy z mózgiem czy receptorami dopaminy: „*czy zachęcałbyś dzieci do oglądania porno?*”

Znowu usłyszysz - „*W ŻYCIU!*”

Pornografia to niesamowita enigma. Problemem nie jest wytłumaczenie dlaczego łatwo przestać, problemem jest wytłumaczyć, dlaczego trudno przestać. Dlaczego ktokolwiek nadal ogląda nawet jeśli jest świadomy neurologicznych skutków? Częściowo zaczynamy, bo setki milionów ludzi już to robi, a jednak oni wszyscy woleliby nigdy nie zacząć i mówią nam, że to jak życie na drugim biegu. Nie umiemy uwierzyć, że im się to nie podoba. Łączymy to z wolnością albo 'edukacją seksualną' i ciężko pracujemy aby samemu się uzależnić. A potem spędzamy resztę życia mówiąc innym, żeby tego nie robili i sami próbujemy pozbyć się uzależnienia.

Spędzamy też bardzo dużo naszego czasu z poczuciem nieszczęścia i beznadziei. „Edukacja” tymi nadnaturalnymi bodźcami sprawia, że wolimy te zimne obrazy, nawet jeśli mamy dostępne prawdziwe i ciepłe alternatywy! Poprzez nieograniczoną pompę dopaminy, wywoływaną przez PMO, skazujemy się na życie pełne nerwów, gniewu, stresu, zmęczenia i dysfunkcji seksualnej. Używając porno, które pozbawione jest najlepszych elementów prawdziwego seksu, kończymy z poczuciem winy i nieszczęścia.

Najgorsze jest to, że czytanie o uzależniających i destruktywnych elementach pornografii czy tutaj, czy gdzieś w Internecie sprawia, że czujemy się jeszcze gorzej! Co to za hobby, którym nie chcesz się zajmować, kiedy je robisz, a pragniesz go, kiedy go nie ma? Użytkownicy nienawidzą się za każdym razem, kiedy czytają o hipofrontalności czy znieczulicy, oglądają porno za plecami swojego partnera, albo gdy nie potrafią się zmusić do aktywności fizycznej po sesji z filmami pornograficznymi. Osoba, która normalnie jest racjonalna i inteligentna, spędza całe swoje dnie w poczuciu pogardy. A najgorsze w tym wszystkim? Co daje nam życie z tymi okropnymi cieniami z tyłu głowy? **Absolutnie nic!**

Pomyślisz sobie teraz – „*no okej, wszystko rozumiem, ale jak już raz się uzależnisz, to bardzo ciężko przestać*”. Ale dlaczego jest tak trudno? Niektórzy powiedzą, że to przez te ostre symptomy odstawienia, ale jak niedługo się dowiesz – właściwe odstawienie ma tak słabe skutki uboczne, że powinieneś zdać sobie sprawę, że są ludzie uzależnieni od cyklu PMO, którzy żyli i umarli nie wiedząc, że tak naprawdę są w sidłach narkotyku.

Niektórzy powiedzą, że pornografia jest darmowa, więc ludzkość powinna zaakceptować to biologiczne szaleństwo, ale to nie prawda – jest uzależniająca tak samo jak każdy inny narkotyk. Zapytaj użytkownika, który twierdzi, że ogląda tylko 'erotykę', taką jak Playboy, czy kiedykolwiek poszedł dalej do 'niebezpiecznego' porno. Jeśli będą szczerzy, to przyznają się, że owszem i że musieli to później sobie racjonalizować.

Przyjemność też nie ma z tym nic wspólnego – lubię sobie zjeść raki, ale nigdy nie byłem w punkcie, gdzie musiałem jeść raki codziennie. Tak jak z innymi rzeczami w życiu – cieszymy się kiedy je robimy, ale nie czujemy się wybrakowani, kiedy ich nie ma.

Inni mówią:
- „*To ma wartość edukacyjną!*” - kiedy matura?
- „*To satysfakcja seksualna!*” - więc po co to robić samemu, a nie z partnerem, z którym możesz się podzielić szczęściem?
- „*To uczucie wyzwolenia!*” - Wyzwolenia od stresów życia codziennego? Pornografia nie
  usuwa źródła twojego stresu, a tylko do niego dodaje.
- „*To pomaga mi zasnąć*” Więc dlaczego inni mogą spać bez problemu bez tego? Istnieje [wiele](https://www.sleepfoundation.org/insomnia/treatment/meditation) naukowo udowodnionych [metod](https://www.sleepfoundation.org/insomnia/treatment/cognitive-behavioral-therapy-insomnia) [poprawy](https://www.amazon.com/Uvex-Blocking-Computer-SCT-Orange-S1933X/dp/B000USRG90) snu i [jeszcze więcej](https://www.menshealth.com.au/what-is-the-military-method-the-technique-that-promises-to-help-you-sleep-in-2-minutes).

Wiele osób wierzy, że pornografia to sposób na nudę, co również jest błędnym myśleniem. Nuda to sposób myślenia. Pornografia przystosuje cię do szukania nowinek, do momentu, kiedy będzie ci się nudziło tak bardzo, że trafisz do pościgu za tym jednym idealnym filmem, co powoduje, że twój mózg zacznie czerpać przyjemność tylko z nowości, potem mocnych emocji a na końcu – z oburzających i szokujących obrazów.

Niektórzy mówią, że robią to, bo wszyscy których znają też to robią. Jeśli tak rzeczywiście jest, to módl się, aby twoi znajomi nie zaczęli sobie odcinać głów jako remedium na migrenę. Większość użytkowników dochodzi do wniosku, że porno to tylko przyzwyczajenie. To nie do końca dobre wytłumaczenie, ale pozbywając się wszystkich normalnych i racjonalnych powodów, to jedyna wymówka, która pozostaje. Niestety, jest tak samo nielogiczna. Każdego dnia zmieniamy swoje przyzwyczajenia, niektóre nawet bardzo przyjemne. Mamy wyprane mózgi, bo wydaje nam się, że PMO to przyzwyczajenie które trudno przerwać.

Czy przyzwyczajenia trudno zmienić? Kierowcy w Wielkiej Brytanii jeżdżą po lewej stronie drogi, jednak, kiedy wjeżdżają do Francji – nie mają żadnego problemu dostosować się do innych zwyczajów. Błędnym jest przekonanie, że przyzwyczajenia są trudne do zmiany. Tworzymy i zmieniamy nowe każdego dnia naszego życia. Więc dlaczego jest tak trudno zmienić ten jeden, którego tak nam brakuje, gdy go nie ma, sprawia że czujemy się winni gdy go wykonujemy i ten który bardzo chcemy zmienić – a jedyne co musimy zrobić to po prostu *przestać*?

Odpowiedź jest prosta – pornografia to nie przyzwyczajenie, **to uzależnienie!** Dlatego tak trudno ją 'oddać'. Większość użytkowników nie rozumie uzależnienia i wierzą, że pornografia dostarcza im szczerej przyjemności. Wierzą, że będą musieli dużo poświęcić, jeśli przestaną.

Piękne jest to, że jak już zrozumiesz prawdziwą naturę uzależnienia od porno i przyczyny, dla której używasz, to po prostu przestaniesz ot tak. Za trzy tygodnie jedyne o czym będziesz myślał to dlaczego korzystałeś z porno tak długo i jak przekonać innych, *że nie bycie PMOsem jest takie przyjemne*!

## Złowieszcza pułapka

Pornografia internetowa to jedna z najbardziej subtelnych i złowieszczych pułapek człowieka i natury. Jedyna pułapka w naturze, której zastawienie nie wymaga ciężkiej pracy. Niektórzy z nas byli ostrzeżeni, ale zastanawialiśmy się po co? Przecież to takie przyjemne. Więc jak wchodzimy w sidła pornografii? Zwykle poprzez darmowe próbki udostępniane przez amatorów i profesjonalistów. Tak pułapka się uruchamia - twój pierwszy wgląd w ten świat poprzez miniatury na stronach z porno, często amatorskie, robione w domu klipy z nieznanymi modelkami. Kto wie, jeśli świeżak zobaczyłby anielskie piękności i modelki, to może jakiś alarm odezwałby się już wtedy.

Wymieszanie klipów sprawia, że nasze młode umysły myślą - uzależnienie jest niemożliwe! Przecież większość się nam nie podoba, więc możemy przestać, kiedy chcemy. Jako inteligentni ludzie, wtedy zrozumiemy, dlaczego połowa dorosłej populacji jest uzależniona od czegoś, co obniża ich możliwości robienia tego co oglądają. Ciekawość zbliża cię powoli do progu drzwi, ale boisz się jeszcze kliknąć na niektóre z miniatur, bo masz wrażenie, że będzie ci się chciało wymiotować. A jeśli przypadkiem kliknąłeś, to czujesz potrzebę ucieczki jak najszybciej.

I od tego momentu, spędzamy całe życie zastanawiając się czemu to robimy, mówimy dzieciom, żeby nie zaczynały, a czasem nawet sami próbujemy się od tego odciąć. Pułapka działa tak, że próbujemy przestać tylko, kiedy przytrafi się nam 'incydent' – czy to problem ze sprawnością seksualną, czy przy problemach z karierą czy w związku, może gdy utracimy chęci życia, albo gdy poczujemy się jak chory na trąd. Gdy tylko przestaniemy – zwiększa się nasz stres, ze względu na symptomy odstawienia rzeczy, której używaliśmy regularnie do pozbycia się stresu.

Po kilku dniach tortur dochodzimy do wniosku, że wybraliśmy zły moment na odstawienie, że poczekamy na chwilę, gdzie stresu nie ma, która gdy nadejdzie – usuwa nasz powód dla którego postanowiliśmy przestać na początku. Oczywiście ten moment nigdy nie nadchodzi, bo w środku wierzymy, że nasze życie jest co raz bardziej stresujące. Najpierw wychodzimy spod parasola bezpieczeństwa naszych rodziców, a potem pojawia się praca, opieka nad domem, kredyty, dzieci, większy dom i więcej dzieci. To jest iluzja. Najbardziej stresującymi momentami w życiu człowieka jest dorastanie i wczesna dorosłość.

Często mieszamy odpowiedzialność ze stresem. Życie użytkownika – tak jak i uzależnionego od narkotyków – automatycznie staje się bardziej stresujące, bo pornografia nie ułatwia radzenia sobie ze stresem, ani nie relaksuje, tak jak twierdzą niektórzy. Jest dokładnie odwrotnie - powoduje większe obładowanie stresem, w miarę jak twoje używanie rośnie, ładując coraz większy ciężar na konia. Nawet użytkownicy, którzy pozbyli się swojego uzależnienia (często wielokrotnie w trakcie swojego życia), mogą mieć perfekcyjnie lekkie życie, by potem znowu wpaść w uzależnienie. Kiedy wchodzimy w labirynt pornografii, nasze umysły stają się zamglone, a my próbujemy całe życie z nich wyjść. Wielu się udaje, tylko by potem znowu wpadli w tę samą
pułapkę.

Uzależnienie od pornografii to skomplikowana i fascynująca układanka tak jak kostka Rubika, prawie niemożliwa do rozwiązania. Ale jeśli znasz sposób – to okazuje się łatwa i przyjemna! Koniec z Porno zawiera rozwiązanie, które wyprowadzi cię z labiryntu i zapewni, że nigdy więcej do niego nie wejdziesz. **Teraz pozostało ci tylko podążać za wytycznymi**. Jeśli natomiast **skręcisz w złą stronę poprzez pomijanie rozdziałów** – kolejne drogowskazy nie będą skuteczne.

Przestanie konsumpcji porno może być proste dla każdego, ale najpierw ustalmy sobie pewne fakty. Nie, nie fakty które mają cię przerazić, tych informacji jest już wystarczająco dużo. Jakby to ci miało pomóc, to już byś z porno nie korzystał. Więc dlaczego jest ci tak trudno przestać? Odpowiedź jest prosta i wymaga żebyś poznał dwa powody, dla których ciągle używamy
pornografii:
-   Natura i jej połączenie z pornografią internetową
-   pranie mózgów.

Uzależnieni od porno to ludzi inteligentni i racjonalni. Wiedzą, że podejmują ogromne ryzyko dla swojej przyszłości, dlatego spędzają dużo czasu na racjonalizowaniu swojego'przyzwyczajenia'. Natomiast w głębi serca wiedzą, że są głupcami, wiedzą że nie mieli żadnego użytku dla pornografii zanim się od niej nie uzależnili. Większość z nich pamięta, że ich pierwszy raz był mieszanką odrzucenia i zainteresowania. Niedługo później stają się specjalistami w wyszukiwaniu, przeszukiwaniu i zapisywaniu stron, pracując ciężko by jeszcze bardziej się uzależnić.

A najbardziej denerwujące jest to przeczucie, że ci wolni od uzależnienia – większość kobiet, starsi mężczyźni i ludzie, którzy żyją bez dostępu do Internetu – tak naprawdę niczego nie tracą i śmieją się z takich problemów. Gdy rozpracujemy te czynniki w kolejnych rozdziałach, ty też zrozumiesz na czym polega ta nikczemna pułapka!