# Z czego rezygnuję?

**Z absolutnie niczego!** Pornografia jest trudna do rzucenia, ze względu na strach przed wybrakowaniem i mniejszą przyjemnością z życia. Strachem, że pewne sytuacje nigdy nie będą już takie same. Strachem, że nie poradzisz sobie ze stresującą sytuacją. Mówiąc inaczej – to efekty prania mózgu, które wmawia nam, że seks – i orgazm – są konieczne dla każdego człowieka. Co więcej, to wiara, że w pornografii jest coś czego potrzebujemy, a kiedy przestaniemy używać, to odbierzemy sobie coś specjalnego i wykreujemy pustkę.

Zapamiętaj jedno: **Pornografia nie wypełnia pustki, ona ją tworzy!**

Nasze ciała to najbardziej skomplikowane mechanizmy na ziemi. Niezależnie czy wierzysz w stwórcę, selekcję naturalną czy kombinację obu, nasze ciała są tysiąc razy bardziej wydajne niż technologia! Nie jesteśmy w stanie stworzyć najmniejszych komórek albo cudu widzących oczu, reprodukcji i innych systemów, które są obecne w naszym ciele. Jeśli ten stwórca albo proces chciał, żebyśmy radzili sobie z ekstremalnymi bodźcami, to nasz mechanizm nagrody działałby inaczej. Nasze ciała są wyposażone w alarmy i inne narzędzia, które my ignorujemy ku własnej zagładzie.


## Nie ma z czego rezygnować

Kiedy wyzbędziesz się małego potworka z twojego ciała, a pranie mózgu (duży potwór) zniknie z twojej głowy, nie będziesz miał ochoty się masturbować, ani korzystać z pornografii. Jest wiele wiadomych i niewiadomych, jeśli chodzi o uzależnienie od porno, a wielu profesjonalistów medycyny nie potrafi rozpoznać kogoś jako uzależnionego od pornografii. Wiele symptomów jest źle oznaczanych, a przyczyn szuka się gdzieś indziej. To nie jest tak, że uzależnieni są głupimi ludźmi, po prostu są nieszczęśliwi bez pornografii. Znajdują się między młotem a kowadłem – odmawiają sobie i czują się niezaspokojeni bez oglądania swoich filmów albo nieszczęśliwi, bo czują się winni i nienawidzą się za to, kim się stali. Kiedy nadchodzi ból pleców albo dysfunkcje seksualne, ich umysły są rozdarte między akceptacją odpowiedzialności, albo przymknięciem oka na problem.

Znowu porównamy to do palaczy. Każdy z nas widział palacza, który tworzy sobie wymówki, żeby wyskoczyć na szybkiego papieroska, a wtedy rozpoznajemy uzależnienie.

Uzależnieni nie robią tego dla przyjemności, robią to, bo są bez tego nieszczęśliwi.

Dla wielu pierwsze doświadczenia seksualne kończyły się orgazmem, więc nauczyli się, że seks nie może być bez niego przyjemny. Dla mężczyzn pornografia reklamowana jest jako pomoc w seksie, a czasem nawet jako pożyteczna lekcja w zadowalaniu partnerki. To jest całkowity nonsens, warunkowanie nadnaturalnych bodźców tylko go wzmacnia.

Nie tylko z niczym się nie rozstajesz, ale będziesz miał z tego również ogromne korzyści.
Kiedy ktoś myśli o rzuceniu, koncentrują się na zdrowiu i jurności. To są odpowiednie i ważne powody, ale wierzę, że najwięcej zyskujesz mentalnie:
- powrót pewności siebie i odwagi
- wolność od niewoli
- brak cieni w twojej głowie, które sprawiają, że się nienawidzisz.


## Pustka, pustka, piękna pustka

Wyobraź sobie, że na twarzy pojawia ci się pryszcz. Idziesz do apteki i prosisz farmaceutę o pomoc. On daje ci darmową próbkę. Smarujesz twarz i rzeczywiście, pryszcz znika od razu.
Tydzień później budzisz się, a pryszcz jest tam, gdzie był. Wracasz do apteki i mówisz „*daj mi jeszcze trochę kremu*”, na co farmaceuta odpowiada - „*pewnie, weź całą butelkę przyda ci się*”

Znowu się smarujesz i proszę bardzo, pryszcza nie ma. Ale za każdym razem, bez wyjątku wraca i za każdym razem jest większy, bardziej bolesny no i pojawia się coraz szybciej. W końcu twoją twarz pokrywa jeden wielki pryszcz, który powraca co godzinę. Wiesz, że krem usunie go na chwilę, ale zaczynasz się martwić. Idziesz do lekarza, który nie jest w stanie ci pomóc, więc próbujesz innych metod, ale żadna poza kremem nie działa.

W tej chwili twoje życie jest zależne od kremu, nie możesz wyjść z domu bez butelki w kieszeni. Wyjeżdżasz za granicę? Lepiej spakuj kilka opakowań. No i nie dość, że martwisz się o swoje zdrowie, to farmaceuta każe ci teraz płacić po sto złotych za jedną butelkę. Nie masz wyboru – musisz płacić.

W końcu trafiasz na artykuł online, gdzie ludzie dyskutują na ten temat i okazuje się, że nie tylko ty cierpisz na taką przypadłość. Właściwie to okazuje się, że naukowcy odkryli, że krem wcale nie działa – po prostu ukrywa pryszcza pod skórą. To krem sprawia, że pryszcz rośnie i rośnie! Jedyne co musisz zrobić to przestać się smarować, a pryszcz sam niedługo zniknie.

Czy będziesz nadal smarował się kremem? Czy potrzebujesz siły woli, żeby nie smarować się kremem? Może nie wierzysz artykułowi i kilka dni się zastanawiasz, ale w końcu zdajesz sobie sprawę, że rzeczywiście, pryszcz się goi sam, więc nie musisz już używać kremu. Byłbyś nieszczęśliwy? Oczywiście, że nie! Miałeś okropny problem i myślałeś, że nie da się go wyleczyć, a teraz znalazłeś rozwiązanie. Nawet jeśli miałbyś czekać rok, aż pryszcz zniknie, to każdego dnia jest lepiej, a ty czujesz coś coraz szczęśliwszy. Tak działa magia rzucenia pornografii.

Pryszcz to nie obolałe ciało, brak popędu, znikające podniecenie, nieprzyjemna penetracja, stracony czas na oglądaniu dwuwymiarowych obrazków, nie uczucie naruszenia czy braku czegoś ani nie nienawiść do ludzi, którzy cię przyłapali, a w najgorszym wypadku – nienawiść do samego siebie. To wszystko to tylko dodatek do pryszcza.

Pryszcz sprawia, że zamykamy swoje umysły na wszystkie problemy, przez to paniczne uczucie potrzeby zaspokojenia. Ludzie nieoglądający pornografii nie mają tego problemu.
Najgorszą rzeczą jest strach, a największą korzyścią jest brak strachu. Strachu spowodowanego twoją pierwszą sesją, który był umacniany każdą następną.

Niektórzy użytkownicy są 'szczęśliwi', zaślepieni swoimi małymi potworkami, przechodząc przez ten sam koszmar i próbując usprawiedliwić swoją głupotę.

**Jak miło być wolnym!**