# Oszczędność czasu

Zwykle, kiedy ktoś próbuje przestać, jako główne powody podaje zdrowie, religię i wstyd przed partnerem. Częścią prania mózgu tego okropnego narkotyku jest jego niewola, z którą człowiek walczy od lat w wielu miejscach na świecie – bo użytkownicy spędzają całe swoje życie w auto-niewoli. Są nieświadomi faktu, że kiedy mogą używać pornografii – chcą przestać. Jedyny czas, kiedy pornografia jest dla nas cenna, to wtedy kiedy próbujemy ją 'ograniczyć' albo kiedy ktoś nas zmusza do abstynencji.

Będę to powtarzał w kółko – pranie mózgu sprawia, że rzucenie pornografii jest trudne, więc im więcej odczarujemy zanim zaczniemy, tym łatwiej będzie ci osiągnąć twój cel.

Użytkownicy, którzy nie wierzą w negatywne skutki oglądania pornografii (zaburzenia erekcji, hipofrontalność itd.) i nie mają wewnętrznego konfliktu, to najczęściej młodzi single, którzy raz na jakiś czas znajdują partnerkę. Więc ich wewnętrzne sprzężenie zwrotne traci się, ze względu na ich młodość albo jest zbyt rzadkie żeby je obserwować i rejestrować.

Lepszym argumentem dla młodego jest tracenie czasu, mówienie „*nie chce mi się wierzyć, że nie martwisz się o czas, który marnujesz!*”. Wtedy ich oczy się rozświetlają, bo zwykle atakuje się ich ze względu na zdrowie bądź problemy społeczne, ale czas?
„*A nie mam z tym problemu, to tylko kilka godzin w tygodniu i dobrze, że to robię, to moja jedyna przyjemność*”

„*Nadal nie wierzę, że się nie martwisz. Załóżmy pół godziny dziennie, w które wliczamy fizyczny brak dopaminy, spędzasz na tym prawie jeden dzień pracy tygodniowo. Jestem pewien, że się zgodzisz, że pół godziny dziennie to dość konserwatywne założenie. Myślałeś, ile ci to zajmuje w całym życiu? Co robisz w tym czasie? Budujesz zdrowe relacje? Nie, twoja ulubiona gwiazda porno nie ma żadnych uczuć wobec ciebie, tylko dlatego że często ją oglądasz – po prostu marnujesz czas!
I nie dość, że marnujesz, to jeszcze wykorzystujesz go do rujnowania swojego zdrowia fizycznego, niszczenia nerwów i pewności siebie, żeby potem żyć życiem niewolnika, życiem pełnym bólu i cierpienia, melancholii i podrażnienia. Na pewno o tym myślałeś?*”

W tym momencie staje się to jasne – szczególnie dla młodszych – że nigdy nie myśleli o tym jako o uzależnieniu na całe życie. Czasem zdają sobie sprawę, ile czasu marnują tygodniowo i to już jest alarmujące. Niektórzy, myśląc o skończeniu, liczą, ile tracą rocznie, co jest przerażające – a przez całe życie? Aż ciężko o tym myśleć! No ale i tak, z racji tego, że prowadzimy dyskusję, to młody rzuci „*a to tylko kawałek tygodnia, mogę sobie na to pozwolić*” ćwicząc podręcznikową sprzedaż na samym sobie.

Odmówiłbyś pracy, w której zarabiasz dokładnie tyle samo co teraz, ale do tego masz miesiąc wakacji w roku? Każdy by poszedł na coś takiego, szukając dobrej miejscówki na egzotyczne wakacje. Znalezienie sposobu na spędzenie miesiąca bez niczego do roboty byłoby największym wyzwaniem. W każdej dyskusji z uzależnionym (pamiętaj, to nie jest ktoś, kto chce przestać, tak jak ty), nikt nigdy nie chciał tej oferty. Dlaczego nie?

Bardzo często w tej chwili uzależniony mówi „*słuchaj, nie obchodzą mnie pieniądze*”.
Jeśli myślisz w podobny sposób, to zadaj sobie pytanie - dlaczego cię nie obchodzą? Dlaczego w innych dziedzinach życia będziesz szukał możliwości zarobku i oszczędności, a tutaj wydajesz tysiące złotych zabijając swoje szczęście i nie patrząc na koszt?

Każda inna decyzja, którą podejmujesz w życiu jest rezultatem procesu analizy plusów i minusów, która prowadzi do racjonalnej konkluzji. Może to będzie zła decyzja, ale będzie ona rezultatem racjonalnej dedukcji. Za każdym razem, kiedy użytkownik myśli o wadach i zaletach używania pornografii, odpowiedź zawsze jest jedna – **NATYCHMIAST PRZESTAŃ DEBILU!**
Więc wszyscy użytkownicy korzystają nie dlatego że chcą, ale dlatego, że nie potrafią przestać.
Muszą używać porno, więc piorą sobie mózg i trzymają głowę w piasku.

Użytkownicy powinni też pamiętać, że sytuacja będzie gwałtownie się pogarszała, szczególnie że co raz więcej badań i ludzi potwierdza okropne działanie pornografii. Dziś dyskutują o tym ludzie spoza medycyny, jutro zapyta o to twój lekarz rodzinny. Czasy, kiedy użytkownik mógł się schować za stresem w pracy, kiedy partner pyta co robisz na laptopie całą noc, już nie wrócą. W tej sytuacji użytkownik czuje się okropnie i ma ochotę zapaść się pod ziemię.

Co ciekawe, wielu ludzi płaci duże pieniądze za dostęp do siłowni i osobistych trenerów do budowania mięśni i rzeźbienia sylwetki, wielu z nich w swojej desperacji (wyobrażonej i prawdziwej) sięga po takie substancje jak testosteron, które mogą powodować różne nieciekawe skutki uboczne. W tej samej grupie jest mnóstwo ludzi, którzy zyskaliby dużo na zaprzestaniu praktyki, która systematycznie niszczy ich naturalne zdolności do relaksu.

Jest tak dlatego, że nadal myślą w kategoriach prania mózgu. Odsuń piasek sprzed oczu, chociaż na moment. Pornografia to reakcja łańcuchowa na całe życie i jeśli jej nie złamiesz – będziesz używał pornografii do końca. Oceń, ile czasu spędzisz na pornografii, od teraz aż do momentu twoja egzystencja się skończy, oczywiście ilość zmieni się w zależności od człowieka, ale załóżmy, że jest to rok i pół w roboczogodzinach. Wyobraź sobie, że leży przed tobą los na loterię, gdzie wygrałeś rok i pół swojej wypłaty. Zatańczyłbyś szczęśliwy, więc zacznij tańczyć. Już za chwilę zaczniesz czerpać te korzyści!

A jeśli ci się wydaje, że to jakaś sztuczka – sam się oszukujesz. Zastanów się, ile czasu oszczędziłbyś, gdybyś nigdy nie otworzył tej pierwszej strony z pornografią.

Za niedługo podejmiesz decyzję o swojej ostatniej sesji PMO (jeszcze nie trzeba, pamiętaj nasze zasady), żeby zostać nieużywającym i nie wpaść nigdy znowu w pułapkę. Jedyne co musisz zrobić, żeby pozostać nieużywającym, to uniknąć tego jednego podglądnięcia. Jeśli to zrobisz, będzie cię to kosztowało tyle pieniędzy, ile właśnie wyliczyłeś.

Natomiast jeśli zajmujesz się kimś z uzależnieniem od pornografii, powiedz mu, że znasz kogoś, kto odmówił oferty pracy, która gwarantuje mu tę samą wypłatę + miesiąc płatnego urlopu. A jak zapyta, kim jest ten idiota, to powiedz „**TY**”. Może i to niemiłe, ale czasem warto postawić na swoim.