# Zdrowie

Trafiamy do miejsca, gdzie pranie mózgu jest najskuteczniejsze – szczególnie wśród młodych singli – którym wydaje się, że są świadomi zagrożenia dla swojego zdrowia, ale tak naprawdę nie są. Wielu oszukuje samych siebie, mówiąc, że są gotowi na konsekwencje. Gdyby twój router miał funkcję alarmu, która wyje za każdym razem, kiedy wchodzisz na stronę z pornografią „*Aż dotąd nie było problemu, ale jeśli zostaniesz choć minutę, twoja głowa wybuchnie*”. Zostaniesz? Jeśli wątpisz co do odpowiedzi, podejdź do wysokiej przepaści, stań na brzegu z zamkniętymi oczami i wyobraź sobie wybór między rzuceniem pornografii a ślepotą.

Nie mam wątpliwości co wybierzesz, ale przez zakopanie głowy w piachu z nadzieją, że pewnego dnia się obudzisz bez ochoty na porno, nic nie osiągniesz. Użytkownik nie może myśleć o ryzyku związanym ze zdrowiem, bo jeśli to robi, to iluzja przyjemności się traci. Dlatego terapia szokowa nie działa, szczególnie w pierwszych dniach po rzuceniu. Tylko nieużywający czytają o destrukcyjnych zmianach w mózgu wywołanych pornografią.

Tutaj na przykład rozmowa z użytkownikiem:

> **Ja:** „*Dlaczego chcesz przestać?*”
>
> **Użytkownik:** „*Przeczytałem na kursie podrywania, że dobrze przestać na cztery dni przed randką, żeby się nakręcić*”
>
> **Ja:** „*Nie boisz się problemów zdrowotnych?*”
>
> **Użytkownik:** „*Nie, mógłbym równie dobrze jutro wpaść pod autobus*”
>
> **Ja:** „*Ale wszedłbyś mu pod koła celowo?*”
>
> **Użytkownik:** „*Oczywiście, że nie*”
>
> **Ja:** „*Więc patrzysz na lewo i na prawo przed przejściem przez ulicę?*”
>
> **Użytkownik:** „*No pewnie*”

Dokładnie popatrz, jak bardzo unika spotkania z autobusem, nawet jeśli prawdopodobieństwo wypadku wynosi tysiące do jednego. Jednak użytkownik ryzykuje praktyczną pewność upośledzenia wywołanego przez swoje uzależnienie i wydaje się na nią całkowicie obojętny. Tak wygląda siła prania mózgu pornografii, wilka w owczej skórze. Nie jest dziwne, że nie wszedłbyś do samolotu, z którym coś jest nie tak, nawet jeśli ryzyko katastrofy jest malutkie – a jednak podejmujemy ryzyko 1 do 4 z pornografią i jesteśmy na nie obojętni? A co z tego mamy?
**Absolutnie nic!**

Innym często powtarzającym się mitem jest depresja i podenerwowanie. Większość młodych ludzi nie martwi się swoim zdrowiem, bo nie dokuczają im żadne depresje czy melancholia. Smutek i stres to nie choroba, to symptom. Młodzi ludzie nie czują tych problemów, bo ich ciała mają naturalną zdolność do produkcji dopaminy. W ramach dojrzewania i kiedy pojawiają się prawdziwe problemy w życiu, ich zużyte już zasoby pracują na wyższych obrotach i wtedy zaczynają doświadczać pełni symptomów. Kiedy starszy użytkownik czuje stres, depresję bądź podenerwowanie, to dlatego, że naturalne mechanizmy ochraniają system nerwowy przed zalaniem dopaminą poprzez ograniczanie receptorów. Użytkownik jednocześnie rozwija inne zmiany neurologiczne, które trzymają go w dołku.

Myśl o tym w ten sposób – jeśli masz dobry samochód i pozwolisz mu zardzewieć, byłoby to dość głupie. Szybko będziesz właścicielem nieruchomej kupy rdzy, która nigdzie cię nie dowiezie. Na szczęście to nie koniec świata, bo wystarczą pieniądze. Twoje ciało to taki samochód, który prowadzisz przez życie. Każdy mówi, że zdrowie jest najważniejsze – możesz zapytać chorego milionera. Każdy z nas miał sytuację w chorobie bądź po wypadku, gdzie modlił się o wyzdrowienie. Kiedy używasz porno, nie tylko pozwalasz swojemu ciału rdzewieć, ty niszczysz swój jedyny statek, który prowadzi cię przez świat.

Ogarnij się, pamiętaj, nie musisz tego robić. Nie masz z tego **absolutnie nic**. Wyciągnij swoją głowę z piasku na moment i zadaj sobie pytanie, czy jeśli miałbyś pewność, że twoja następna sesja całkowicie pozbawi cię kontaktu z kimś kogo kochasz, to zacząłbyś cykl PMO?

Kiedy rozmawiam z ludźmi, którym się to przydarzyło, to żaden z nich się tego nie spodziewał, a najgorsze uczucie to nie sama choroba – tylko fakt, że sami siebie nią zarazili. Wyobraź sobie kogoś, kto wcisnął magiczny przycisk, dla kogo pranie mózgu się skończyło. Całe życie wali sobie w pierś pytając - „*dlaczego tak długo się oszukiwałem, że muszę się masturbować do pornografii? Gdybym tylko mógł przestać wcześniej*”

Przestań się oszukiwać, to twoja szansa. Reakcja łańcuchowa – jeśli zaczniesz znowu oglądać porno, będziesz oglądał kolejne, a potem kolejne. To już się dzieje. Koniec z Porno obiecało brak terapii szokowej, więc jeśli już postanowiłeś przestać, to to, co zaraz przeczytasz, nie będzie szokujące. Jeśli nadal nie jesteś pewien, omiń resztę tego rozdziału i wróć do niego po przeczytaniu całej książki.

Tony, powtarzam, tony opublikowanych materiałów naukowych mówi o szkodliwości pornografii dla naszego samopoczucia i życia seksualnego. Problem jest tylko taki, że dopóki nie chcesz przestać, to nie chcesz wiedzieć. Fora i grupy wsparcia są bez sensu, ponieważ pornografia zakłada zasłony na oczy. Jeśli przeczytasz je przypadkiem, pierwsze co zrobisz, to otworzysz swoją ulubioną stronę i klip. Użytkownicy myślą o szczęściu, stresie i zagrożeniu seksualności jako o przypadku, jakby chodzeniu po polu minowym.

Niech ci to wejdzie do łba – to już się dzieje. **Za każdym razem**, gdy otwierasz swoją stronę z pornosami, uruchamiasz wodospad dopaminy, a opioidy zabierają się do roboty. Twoje ścieżki w mózgu, naoliwione zabierają cię do kolejnego kroku, bo twój mózg ma już przećwiczony scenariusz. Twój system nerwowy jest zalewany dopaminą i z racji tego, że jest to już enty raz, receptory dopaminy przymykają się, a mały potwór używa tego minimalnego obniżenia podniety, by przerzucić cię za czerwoną linię, do bardziej szokujących i obrzydliwych materiałów, by zwiększyć ilość dopaminy. Więcej nowości, więcej dopaminy, a mały potwór chce jeszcze więcej.
Tyle obrazów w jednej sesji tworzy nadnaturalne bodźce, które wstrzykują do twojego mózgu więcej związków chemicznych, które potem każą ci kontynuować.

Przez cały ten czas twoje receptory dostają polecenie, żeby się przymykać, jako odpowiedź na zalanie. Orgazm zwiększa ten efekt i prowadzi do głodu. A tobie wydaje się, że tak nie jest, bo mały potwór jest głodny, nie powodując dyskomfortu czy bólu. Zagrożenie problemów z erekcją straszy wielu, dlatego blokują je ze swojego umysłu i zakrywają strachem przed rzuceniem. To nie jest tak, że strach jest większy, ale skończenie dziś jest natychmiastowe. Po co szukać negatywów? Może się nie uda, ale przynajmniej spróbowałeś.

Myślimy o pornografii jako o przepychance, po jednej stronie strach: „to jest niezdrowe, obrzydliwe i zniewalające”, z drugiej strony pozytywy: „To moja przyjemność, mój przyjaciel, moja podpora”. Nigdy nie myślimy, że ta strona to też strach. To nie tak, że porno nam się podoba.

Raczej bez niego jesteśmy nieszczęśliwi. Uzależnieni od heroiny przechodzą przez nieszczęście bez swojego narkotyku i łatwo sobie wyobrazić ten niesamowity moment, kiedy mogą zatopić igłę w ramieniu i zakończyć ten wielki głód. Spróbuj sobie wyobrazić, że ktokolwiek ma jakąkolwiek przyjemność z wkładania sobie strzykawki w żyłę. Ludzie nieuzależnieni nie cierpią na taką panikę, a heroina nie leczy paniki, tylko ją powoduje.

Nie używający nie czują się okropnie, kiedy nie mogą oglądać porno – tylko użytkownik się tak czuje. Pornografia nie daje ulgi – ona tworzy panikę. Strach przed konsekwencjami nie pomaga w rzuceniu, więc znowu jakbyśmy szli po polu minowym i czekali na konsekwencje. Jeśli ci się uda, to spoko, ale jeśli masz niefart i nadepniesz na minę – czekają cię konsekwencje. Gdybyś znał ryzyko i był na nie przygotowany, co to ma wspólnego z innymi ludźmi? Uzależnieni często używają następujących taktyk:

„***Kiedyś się zestarzejesz, wtedy i tak stracisz swoją sprawność seksualną***”

Oczywiście, to prawda, ale sprawność seksualna nie jest najważniejsza – mówimy tu o niewoli. Nawet jeśli tak będzie – czy logicznym jest zakopywać się w dół teraz?

„***Jakość życia jest ważniejsza niż po prostu życie***”

Właśnie! Sugerujesz, że jakość życia uzależnionego jest lepsza niż kogoś, kto nie jest uzależniony? Czy naprawdę wierzysz, że kiedy używasz, twoje życie jest lepsze? Życie z głową w piasku będąc nieszczęśliwym, nie brzmi zbyt zachęcająco.

„***Jestem singlem i nie planuję się z nikim wiązać w przyszłości***”

Nawet jeśli to prawda, to po co bawić się ze swoją neurologiczną kontrolą impulsów? Czy znasz kogoś na tyle głupiego, kto zawsze rozbiera się do rosołu, kiedy jest sam, bez wzięcia pod uwagę, że ktoś może w każdej chwili przyjść? **Tak właśnie postępują uzależnieni od pornografii.**

Progresywne zalewanie naszych mechanizmów nagrody nadmierną stymulacją, prowadzące do niemożności radzenia sobie z normalnym stresem w życiu nie pomaga Ci cieszyć się życiem pełnym entuzjazmu i wigoru. Pornografia i masturbacja zastąpiły twój naturalny apetyt seksualny, tak jak czekolada zastępuje zdrowy posiłek. Nie bez powodu, specjaliści łączą dziś problemy psychiczne z przyczynami fizjologicznymi. Myśl przewodnia w medycynie mówi, że pornografia nigdy nie została potwierdzona jako przyczyna problemów raportowanych przez użytkowników, ale przyznanie się do swojej ograniczonej seksualności, jest niesamowicie wstydliwym doświadczeniem. Po co ktoś miałby to robić, jeśli nie z troski o innych – po znalezieniu źródła problemu i wyeliminowaniu go z własnego życia?

Koniec z Porno pomoże ci pozbyć się pornografii i żyć jako szczęśliwy eksużytkownik. Bez pornografii, masturbacji i niepotrzebnych orgazmów. Jedyną pomocą będzie dotyk, zapach i feromony twojego partnera. Tak jak pełnoziarnisty chleb dla rozwiniętego apetytu, nie będziesz już pragnął słodkiego syropu internetowego porno. Dowodów jest tak dużo, że nie trzeba nic udowadniać – kiedy przywalę w kciuka młotkiem, to boli. Nic nie trzeba udowadniać. Stres indukowany przez pornografię przekłada się na inne sfery życia uzależnionego, co prowadzi do dalszych uzależnień – papierosów, alkoholu, a czasem nawet do myśli samobójczych.

Użytkownicy żyją również w iluzji, że negatywne wymiary porno są przesadzone. Prawda jest odwrotna – nie ma wątpliwości, że pornografia jest główną przyczyną dysfunkcji seksualnych i wielu innych problemów. Nie ma żadnych potwierdzonych badań, ale wystarczy poczytać, co piszą ludzie online, których każdego dnia jest coraz więcej.

Jest jeden epizod Przyjaciół, gdzie chłopaki, którzy dostali dostęp do nieograniczonego, darmowego porno, zaczynają się zastanawiać, dlaczego dostawca pizzy nie chce zobaczyć ich sypialni. Kiedy jesteś uzależniony, przerzucasz swoje fantazje na prawdziwe kobiety i mężczyzn.

Wyobraź sobie, co przypadkowy klip w ciemniejszej części Internetu może zrobić dla kogoś, kto już ma problemy. Walka z tymi 'myślami porno' jest źródłem problemów ze zdrowiem umysłowym.

Kolejny eksperyment myślowy: wyobraź sobie, że ktoś przychodzi do ciebie i mówi, że nie chce orgazmu, chce po prostu się kochać. Chcą to robić najdłużej jak to możliwe, ale bez orgazmu – ale jeśli do niego dojdzie, to też będzie ok. Zapewniam cię, to będzie fantastyczne nowe doświadczenie, lepsze niż jakiekolwiek inne, jeśli kiedyś ktoś złoży ci taką ofertę. Spróbuj sam.

Efekty prania mózgu sprawiają, że myślimy jak ten gość, który zeskoczył z wieżowca.
Kiedy przelatuje koło 50-tego piętra, myśli sobie „*Na razie jest git!*” Myślimy, że skoro na razie nam się udawało uniknąć konsekwencji, jeszcze jedna sesja z pornografią nic nie zmieni. Spójrz na to jeszcze inaczej – twój 'nawyk' to łańcuch na całe życie, w którym każda sesja wytwarza potrzebę odbycia kolejnej sesji. Kiedy zaczniesz to robić, odpalasz lont. Problem jest taki, *że nie wiesz jak długi*.
Za każdym razem, gdy odpalasz porno, jesteś bliżej do eksplozji. **SKĄD WIESZ, CZY NIE WYBUCHNIE NASTĘPNYM RAZEM?**

## Złowieszcze Czarne Cienie

Użytkownikom ciężko uwierzyć, że to pornografia powoduje to niepewne uczucie, które nachodzi cię wieczorem po długim dniu pracy albo w domu. Nieużywający nigdy nie mają tego uczucia, bo to pornografia je wywołuje.

Kolejną z wielkich zalet rzucenia porno jest uwolnienie się od tych złowieszczych cieni z tyłu naszej głowy. Każdy użytkownik wie, że jest głupcem, kiedy zamyka się na te ciemne strony pornografii. Przez większość życia robimy to z automatu, ale te cienie ciągle siedzą w naszej podświadomości, od razu pod powierzchnią. Częściowo zyski są świadome, takie jak mniej zmarnowanego czasu albo zaprzestanie uprawiania miłości z dwuwymiarowym obrazkiem.

W ostatnich rozdziałach zajęliśmy się zaletami nie używania, ale żeby być sprawiedliwym – trzeba sprawiedliwie podać oba punkty widzenia. Dlatego w następnym rozdziale zajmiemy się zaletami korzystania z pornografii.

# Zalety korzystania z pornografii
