# Metoda na siłę woli

Powszechnie akceptuje się w społeczeństwie, że rzucenie porno jest trudne. Książki i fora, które namawiają do rzucenia, zwykle rozpoczynają od mówienia, jakie to jest trudne. Prawda jest odwrotna – tak naprawdę to bułka z masłem. Rozumiem, że powątpiewasz, ale zastanów się przez moment. Jeśli chcesz przebiec kilometr w dwie minuty, to jest trudne i będziesz musiał przejść przez lata treningu, po których i tak możesz nie być fizycznie w stanie osiągnąć takiego wyniku.

Żeby zatrzymać pornografię, jedyne co musisz zrobić to po prostu jej nie oglądać i się nie masturbować. Nikt nie zmusza cię do masturbacji (poza tobą samym), a w przeciwieństwie do jedzenia i picia, nie potrzebujesz jej, by przeżyć. Więc jeśli chcesz przestać, to czemu to by miało być trudne? Tak po prostu nie jest. To użytkownik sobie wszystko utrudnia, bo używa metod, które sprawiają, że czujesz, jakbyś z czegoś rezygnował. Przemyślmy to.

Nie decydujemy o staniu się użytkownikiem, po prostu eksperymentujemy z magazynami albo stronami internetowymi, a z racji tego, że są one okropne (tak, okropne), nie licząc tego jednego klipu, jesteśmy przekonani, że możemy przestać, kiedy tylko zechcemy. Na początku oglądamy swoje klipy tylko wtedy, kiedy mamy ochotę. Zanim zdamy sobie z tego sprawę, nie tylko odwiedzamy te strony, by się masturbować, kiedy najdzie nas ochota, robimy to codziennie.
Pornografia staje się jednym ze stałych elementów naszego życia, wymagając od nas stałego dostępu do Internetu. Wtedy zaczynamy wierzyć, że miłość, seks, orgazm i rozładunek stresu przez pornografię nam się należy. Nie zdajemy sobie sprawy, że ten sam klip i aktorzy nie dają nam już tej samej satysfakcji, więc rozpoczynamy walkę z czerwoną linią, unikając 'złego porno'. Prawda jest taka, że masturbacja i pornografia nie niwelują naszego stresu, ani nie czynią z nas lepszych kochanków. Zaczyna nam się wydawać, że nie będziemy się bez tego cieszyć życiem, a bez orgazmu – doświadczymy napięcia.

Długo trwa, zanim zdamy sobie sprawę z faktu, że jesteśmy uzależnieni, bo wierzymy, że pornografię oglądamy dla przyjemności, a nie dlatego że musimy. Kiedy bawimy się dobrze przy porno, co jest niemożliwe bez nowych klipów, szoku i eskalacji, wtedy wydaje nam się, że możemy przestać, kiedy chcemy. To jest pułapka: „*Pornografia mnie nie bawi, więc mogę przestać*”.
Problem jest taki, że nigdy nie masz ochoty przestać.

Dopiero kiedy spróbujemy rzucić, zdajemy sobie sprawę, że mamy problem. Pierwsze próby pojawiają się zwykle, kiedy znajdziemy partnera, który okazuje się niewystarczający po kilku pierwszych randkach. Inną częstą przyczyną jest dostrzeżenie negatywnych efektów w życiu codziennym.

Niezależnie od przyczyny, użytkownik zawsze czeka na stresującą sytuację, nieważne czy dotyczy ona życia, czy związków. A jak tylko przestanie na jakiś czas – mały potwór robi się głodny. Użytkownik szuka wtedy czegoś co napompuje dopaminę – papierosów, alkoholu albo swojego ulubionego porno – a harem jest oddalony tylko o kilka kliknięć. Skrytka z pornolami nie jest już ograniczona do szuflady w piwnicy, teraz jest dostępna online i z każdego miejsca. A jeśli partner bądź inni ludzie są wokół, a użytkownik nie ma dostępu do swojego haremu – to powoduje tylko więcej stresu.

Kiedy użytkownik natrafi na materiały naukowe albo do jakiejś społeczności online, zacznie wewnętrzną walkę z pokusami i głodem. Jego metoda radzenia sobie ze stresem jest teraz niedostępna, co tylko dolewa oliwy do ognia. Najczęściej ta tortura kończy się kompromisem – „*po prostu ograniczę*” albo „*to był nieodpowiedni moment*”, albo nawet „*poczekam, aż skończą się moje inne problemy*”. Jednak, kiedy stres się skończy – nie ma powodu, żeby przestawać, więc użytkownik nie chce kończyć, dopóki nie pojawią się kolejne problemy.

Oczywiście odpowiedni moment nigdy nie nadejdzie, bo życie większości z nas jest coraz bardziej stresujące. Opuszczamy bezpieczne gniazdo naszych rodziców, a potem się zaczyna - ułożenie sobie domu, wzięcie kredytu, potem dzieci i bardziej wymagająca praca. Życie użytkownika nie może być mniej stresujące, ponieważ pornografia jest przyczyną stresu. Im szybciej przechodzisz w fazę eskalacji, tym więcej stresu czujesz, a tym bardziej rośnie twoja zależność od iluzji.

Prawda jest taka, że iluzją jest, że życie jest coraz trudniejsze i jest to iluzja spowodowana pornografią bądź inną podporą. To wytłumaczymy niedługo, ale po tych wstępnych niepowodzeniach uzależniony zaczyna marzyć o dniu, kiedy się obudzi i po prostu nie będzie chciał używać pornografii do masturbacji. Ta nadzieja jest często rozpalana przez historie zasłyszane od innych eksużytkowników: „*Nie brałem tego na poważnie, dopóki nie miałem problemów z erekcją i od tego momentu straciłem zainteresowanie pornografią i przestałem się masturbować*”.

Nie oszukuj się – przeanalizuj te plotki, a odkryjesz, że nie są takie proste, jak się wydają.
Zwykle użytkownik chciał przestać już wcześniej i użył takiej sytuacji jako odskoczni. Dla ludzi, którzy 'po prostu' przestali, katalizatorem był szok; może odkrycie sekretu przez partnera, oglądanie porno o innej orientacji seksualnej niż normalnie, albo po prostu seksualna dysfunkcja. „*Ja po prostu taki jestem*”. Nie gadaj głupot, nie przestaniesz, dopóki sam nie będziesz chciał przestać.

Zajmijmy się pytaniem – dlaczego metoda na siłę woli jest taka trudna? Przez większość życia przyjmujemy taktykę chowania głowy w piasek i podejścia „*Skończę jutro*”. Raz na jakiś czas coś wywoła w nas potrzebę rzucenia. Może problemy ze zdrowiem, jurnością, albo samoanaliza, z której wynika, że nic a nic się nam w pornografii nie podoba. Niezależnie od przyczyny, zaczynamy myśleć o plusach i minusach pornografii. Seks dzieli się na elementy tantryczne (dotyk, zapach, głos) oraz rozrodcze (orgazm). To jest jeden z głównych kluczy do naszego umysłu, bez tego rozróżnienia będziemy się gubić, co doprowadzi do porażki. Po racjonalnym spojrzeniu na sprawę dojdziemy do tego samego wniosku, do którego dochodziliśmy przez całe życie – wielkiego, głośnego **PRZESTAŃ OGLĄDAĆ!**

Jakbyś miał usiąść i przypisać punkty zaletom rzucenia porno, a potem porównać je do zalet oglądania porno, to ilość punktów za rzuceniem byłaby wielokrotnie większa. Jeśli zastosujesz zakład Pascala - rzucając nie tracisz prawie nic, a masz dużą szansę na ogromne zyski no i wyższą szansę mniejszych strat. Mimo że użytkownik wie, że będzie mu lepiej, gdy przestanie używać, wiara w to, że z czegoś rezygnuje sprawia, że ma wątpliwości. Jest to bardzo silna iluzja. Nie wiadomo czemu, użytkownik wierzy, że pornografia pomaga mu w trakcie trudnych i łatwych momentów życia. I już na starcie, przed próbą, społeczne pranie mózgu, wspieranie przez pranie mózgu uzależnienia łączy się z jeszcze mocniejszą gadką o tym, jak 'trudno' jest przestać.

Czytasz historie o tych którzy przestali na wiele miesięcy, a nadal odczuwają desperacki głód, albo tych niezadowolonych, którzy przestali a przez resztę życia marzą o kolejnej sesji.
Historie użytkowników, którzy rzucili na długi czas, a potem, po jednej sesji, znowu wpadli w sidła uzależnienia. Znasz też prawdopodobnie ludzi ciężko uzależnionych w zaawansowanym stadium choroby, którzy wyraźnie niszczą siebie i swoje życie – mimo to, nadal używają. Do tego sami pewnie przechodzili przez te doświadczenia.

Więc, zamiast zaczynać z pozytywnym nastawieniem „*Świetnie! Nie muszę już oglądać pornografii!*” zaczynają od czarnych myśli o zagładzie – jakby chcieli wejść na Everest – i błędnie zakładają, że jak już raz się uzależnisz – to jesteś uzależniony na całe życie. Wielu użytkowników zaczyna od przepraszania swoich dziewczyn i żon - „*Słuchaj, próbuję odstawić porno. Prawdopodobnie będę podenerwowany przez najbliższe kilka tygodni, wybacz mi*” W ten sposób większość prób jest skazana na niepowodzenie od samego początku.

Załóżmy, że użytkownik przeżyje kilka dni bez sesji, ich podniecenie wraca i czują się lepiej. Nie odwiedzają swoich ulubionych stron, więc czują podniecenie wywołane normalnymi bodźcami, na które wcześniej nie zwracali uwagi. Przyczyny, dla których zrezygnowali, szybko uciekają z ich głów, jak kiedy zobaczysz wypadek podczas jazdy samochodem. Zwalniasz na moment, ale kiedy musisz się śpieszyć – i tak dociskasz pedał gazu.

Z drugiej strony tej walki jest mały potwór, który nadal nie został nakarmiony. Nie ma fizycznego bólu – jakbyś miał te same symptomy przez przeziębienie, to byś je olał i pracował dalej bez depresji. Ale co jest pewne, to fakt, że użytkownik chce odwiedzić swój harem. Mały potwór o tym wie i uruchamia wielkiego potwora prania mózgu, który sprawia, że ta osoba, która wyliczała dzień wcześniej powody, dla których warto przestać, zaczyna się zastanawiać nad wymówkami, żeby znowu zacząć. Użytkownik myśli wtedy:
- „*To nie był odpowiedni moment*”
- „*Życie jest zbyt krótkie, w każdej chwili może się coś stać. Mogę wpaść pod samochód. Zbyt późno się zabrałem za rzucanie. Dziś wszystko uzależnia*”
- „*Mogłem poczekać, aż skończy się sesja i nie będę już odczuwał tego stresu*”
- „*Nie umiem się skoncentrować, jestem wkurzony i zdenerwowany, nie jestem w stanie pracować*”
- „*Moja rodzina i bliscy mnie nie zaakceptują. Prawda jest taka, że powinienem zacząć znowu dla innych. Jestem od tego uzależniony i nigdy nie będę zaspokojony bez orgazmu*”
- „*Nikt nie jest w stanie przeżyć bez seksu*”
- „*Wiedziałem, że tak będzie, mój mózg jest uczulony przez DeltaFosB przez zmiany wywołane zalewaniem dopaminy, przez moje uzależnienie od pornografii. Nigdy się tego nie pozbędę*”

W tej sytuacji użytkownik zwykle się poddaje. Odpala przeglądarkę, a schizofrenia się pogłębia. Z jednej strony wielka ulga po zaspokojeniu głodu, kiedy mały potwór w końcu zostaje nakarmiony. Z drugiej strony orgazm jest nieprzyjemny, a użytkownik nie wie, po co to zrobił. Dlatego wydaje się, że brakuje siły woli. Ale tak naprawdę jej nie brakuje, jedyne co się wydarzyło to racjonalna decyzja w świetle nowych informacji.

„*Po co być zdrowym i bogatym, kiedy jesteś nieszczęśliwy?*”

Dobre pytanie! Lepiej mieć krótkie i szczęśliwe życie niż długie i okropne. Na szczęście nieużywający nie ma takiego problemu, bo jego życie jest nieskończenie lepsze. Cierpienie, którego doświadcza uzależniony, nie wynika z głodu – mimo że może on je powodować – cierpienie to wewnętrzna walka w głowie, wywołana wątpliwościami i niepewnością. Jeśli rezygnujesz z pornografii – tracisz coś, a przez to czujesz się wybrakowany, co prowadzi do stresu.

Jednym z najbardziej stresujących momentów jest, kiedy mózg podpowiada, aby tylko zerknąć na porno. Żeby wrócić do normalności, jak tylko to zrobisz. Ale kiedy już spojrzysz, jesteś przekonany, że jednak nie dasz rady, przez co czujesz jeszcze większą depresję, co wywołuje kolejny głód. Kolejnym problemem są oczekiwania – kiedy idziesz na egzamin z prawa jazdy, jak tylko go zaliczysz, osiągasz cel. Używając metody na siłę woli, narracja brzmi tak - „*Jeśli nie będę oglądał porno wystarczająco długo, ochota sama przejdzie*”. W praktyce możesz o tym poczytać na forach, gdzie uzależnieni piszą o tym, ile dni wytrzymali w abstynencji.

Jak pisałem wyżej, agonia użytkownika jest mentalna i wynika z niepewności. Mimo że nie ma fizycznego bólu, to jej efekty są odczuwalne. Z uczuciami nieszczęścia i niepewności, użytkownik nie zapomina i jest przepełniony wątpliwościami i strachem:

- *Ile jeszcze to będzie trwało?*
- *Czy kiedykolwiek będę szczęśliwy?*
- *Czy kiedyś będzie mi się chciało wyjść z łóżka?*
- *Jak będę radzić sobie ze stresem w przyszłości?*

Użytkownik czeka na polepszenie sytuacji, ale kiedy płacze – harem staje się coraz bardziej atrakcyjny. Prawda jest taka, że coś się dzieje, ale w podświadomości, więc jeśli wytrzymają kilka tygodni, to mały potwór zniknie. Ale tak jak mówiłem wcześniej, ukłucia głodu dopaminy i opioidów są tak delikatne, że nie zdajemy sobie z nich sprawy. W tej sytuacji użytkownikowi wydaje się, że uzależnienie zniknęło, więc testuje się, spoglądając na porno, co sprowadza go z powrotem prosto na zjeżdżalnię. Po takiej dawce dopaminy, mały głos z tyłu głowy męczy – chcesz więcej. I rzeczywiście – uzależnienie się skończyło, ale sam z powrotem w nie wpadłeś.

Jako dziecko oglądałeś kreskówki i twój mózg wytworzył ścieżki (DeltaFosB) związane z nimi. Jeśli chcesz zniechęcić dziecko do oglądania, to obserwujesz te ścieżki i pytasz dorosłych, dlaczego nie lubią już oglądać swoich ulubionych bajek. Po pierwsze – jest lepsza rozrywka, a po drugie – kreskówki nie mają już tego 'czegoś'. Używając metody siły woli, odbierasz dziecku bajkę.
Z metodą Koniec z Porno, uczysz je, że kreskówki nie mają żadnej wartości. Co jest lepsze?

Użytkownik nie przechodzi od razu do kolejnej sesji, myśląc „*nie chcę się znowu uzależnić*” i pozwala sobie na bezpieczny okres kilku godzin, dni, a nawet tygodni. Wtedy może powiedzieć - „*No cóż, nie uzależniłem się, to mogę spróbować jeszcze raz*”. Znowu wpada w tę samą pułapkę, w którą wpadł na samym początku i już pędzi w dół na zjeżdżalni.

Użytkownicy, którzy rzucili używając metody siły woli, często długo walczą ze sobą, gdyż głównym problemem jest pranie mózgu. Po tym, jak fizyczne uzależnienie się skończyło, użytkownik nadal idzie przez życie nieszczęśliwy. Po przetrzymaniu tej długiej tortury zdają sobie sprawę, że się nie poddadzą i kończą z płaczem, akceptując, że życie bez pornografii jest w porządku. Jest stanowczo więcej porażek niż sukcesów, a niektórzy z tych, którym udało się odnieść sukces, nadal prowadzą przewrażliwione życie z wypranym mózgiem, który wierzy, że pornografia jest mu w stanie pomóc. To tłumaczy, dlaczego niektórzy, nawet po długiej przerwie wracają do uzależnienia.

Wielu eksużytkowników nadal pozwala sobie na okazjonalną sesję raz na jakiś czas albo żeby przekonać samych siebie o swojej sile. I tak jest, ale jak tylko dopamina opuszcza nasz mózg po sesji, to mały głos z tyłu głowy kieruje nas prosto ku kolejnej. Jeśli zdecydują się na grę, wydaje się ona pod ich kontrolą, żadnych szokujących materiałów, eskalacji, mówią: „*Świetnie, nie do końca dobrze się bawię, ale nie jestem uzależniony. Po świętach albo po tym problemie po prostu przestanę*”. Nie zdają sobie sprawy, że zjeżdżalnia jest już naoliwiona.

Za późno! Są znowu uzależnieni. Pułapka, z której wyszli, znowu działa i schwytała ofiarę.

Jak mówiłem wcześniej, nie ma tu przyjemności. Nigdy jej nie było! Gdybyśmy oglądali dla przyjemności, nikt nie siedziałby na stronach z pornografią dłużej niż to konieczne. Nawet jeśli, to lepszy sposób na masturbację to wspomnienia. Zakładamy, że pornografia się nam podoba, bo nie wierzymy ze jesteśmy tacy głupi, żeby uzależnić się od czegoś, co nam się nie podoba.

Większość użytkowników nie rozumie nadnaturalnych bodźców albo dreszczyku poszukiwań szokujących materiałów, nawet jak o tym poczytają, więc nie wierzą, że ich używanie jest motywowane układem nagrody. Dlatego pornografia jest tak naprawdę podświadoma, bo gdybyś był świadomy zmian neurologicznych i strat pieniężnych, przestałbyś wierzyć w iluzję przyjemności.

Kiedy blokujemy swój umysł przed 'złą' stroną, czujemy się głupio. Jeśli mielibyśmy się z tym zmierzyć, to byłoby to nie do przeżycia! Jeśli zobaczysz użytkownika w działaniu, zauważysz, że jest szczęśliwy tylko, kiedy nie myśli o tym, że używa. Jak zwróci na to uwagę, to czuje dyskomfort i wymyśla wymówki. Pornografia karmi małego potwora, więc kiedy pozbędziesz się go ze swojego ciała, razem z praniem mózgu (duży potwór), nie będziesz miał ani potrzeby, ani ochoty oglądać pornografii!