# Uwaga na ograniczanie

Wielu użytkowników próbuje ograniczać spożycie jako pierwszy krok do rzucenia albo żeby kontrolować małego potwora. Wielu poleca ograniczenie albo 'dietę' pornograficzną. Ta metoda jest katastrofalna. To te próby ograniczenia trzymają nas w pułapce do końca życia. Ogólnie mówiąc, ograniczanie pojawia się po nieudanych próbach rzucenia. Po kilku godzinach albo dniach użytkownik myśli sobie „*Nie umiem sobie wyobrazić zaśnięcia bez wizyty w moim haremie, więc teraz będę oglądał tylko raz na cztery dni i usunę moją kolekcję złego porno. Jeśli uda mi się wytrzymać na takiej diecie, to wtedy albo to mi wystarczy, albo przestanę w ogóle oglądać*”.

Następnie dzieje się kilka strasznych rzeczy:

1. Użytkownicy zatrzymują się w najgorszym świecie, nadal uzależnieni od pornografii, utrzymując żywego potwora w ciele i umyśle
2. jedyne, o czym myślą to kolejna sesja
3. przed ograniczeniem, kiedy chcieli odwiedzić harem, to po prostu odpalali przeglądarkę i łagodzili głód. Teraz, poza normalnym stresem, celowo wywołują w sobie głód, co sprawia, że są jeszcze bardziej nieszczęśliwi.
4. Podczas używania, nie cieszyli się z tego, albo nie zdawali sobie sprawy, że używają nadnaturalnych bodźców. Wszystko odbywało się automatycznie, a jedyna przyjemna wizyta w haremie to ta, która odbywała się po dłuższym czasie. Teraz czekają chwilę dłużej przed każdą wizytą, więc każda się im 'podoba'. Im dłużej czekają, tym lepiej się bawią, ponieważ 'przyjemność' sesji nie wynika z samej sesji – to tylko zakończenie stresu spowodowanego pragnieniem, czy mówimy o fizycznym, czy psychicznym głodzie. Im dłużej cierpisz, tym ulga jest przyjemniejsza.

Głównym problemem przy rzucaniu porno nie jest więc neurologiczne uzależnienie, które można łatwo obejść. Użytkownik przestanie oglądać ze względu na wiele sytuacji – śmierć bliskiej osoby, problemy w pracy albo domu itd. przeżyje 10 dni bez dostępu do porno i nic mu nie przeszkadza. Ale jeśli miałby przejść te same 10 dni, kiedy może mieć dostęp – to zacząłby rwać włosy.

Wielu użytkowników ogranicza się podczas dnia pracy i przechodzą przez sklepy z bielizną albo basen bez większego problemu. Wielu przestanie, gdy będzie zmuszonym spać na kanapie, albo gdy kogoś odwiedzają. Nawet w barach ze striptizem albo na plażach nudystów nie było rozrób. Tak jakby użytkownicy cieszyli się z przeszkód w oglądaniu pornografii. Dla niektórych te okresy są wręcz przyjemne, bo mają nadzieję, że pewnego dnia ochota sama zniknie.

Prawdziwy problem z rzuceniem to pranie mózgu, iluzja tego, że należy ci się ta nagroda pornografii i że życie bez niej nigdy nie będzie takie samo. Takie ograniczanie sprawia tylko, że czujesz się niepewnie i nieszczęśliwie i nie ma nic wspólnego z leczeniem uzależnienia, przekonując cię, że na świecie najważniejszy jest ten jeden klip, którego nie znalazłeś i że nie ma szans na szczęście bez patrzenia na niego.

Nie ma nic bardziej żałosnego niż użytkownik, który próbuje ograniczyć spożycie.
Cierpiący na przekonanie, że im rzadziej ogląda, tym rzadziej będzie chciał odwiedzać swój harem.
Prawda jest zupełnie odwrotna, im więcej czują głodu, tym przyjemniej się go zaspokaja. I znowu, ich ulubione klipy nie są w stanie zaspokoić potrzeby, ale to ich nie zatrzymuje. Jeśli strony z pornografią skupiałyby się tylko na jednej aktorce albo gatunku, nikt by ich nie odwiedzał.

Ciężko w to uwierzyć? Jaki jest najgorszy element samo kontroli? Czekać cztery dni, a potem mieć orgazm. A jaki jest najważniejszy moment dla ludzi na takiej diecie? No właśnie, ten sam orgazm po czterech dniach! Czy naprawdę wierzysz, że masturbujesz się dla przyjemności z orgazmu, czy może w bardziej racjonalne wytłumaczenie, że musisz zaspokoić swój głód, myśląc, że to ci się należy?

Wyzbycie się tego prania mózgu jest najważniejsze przy usuwaniu iluzji pornograficznych, zanim w ogóle wyłączysz swoją ostatnią sesję. Jeśli nie usuniesz iluzji, że ci się to podoba, zanim wyłączysz tryb incognito, nigdy sobie tego nie udowodnisz bez kolejnej sesji, która znowu cię uzależni. Kiedy przeszukujesz zapisane linki i pliki, zadaj sobie pytanie – co tu jest fajnego? Może wydaje ci się, że niektóre z klipów są w dobrym smaku, te z ulubionego gatunku. Więc po co ci reszta tych filmów? Bo masz taki nawyk? Po co ktoś miałby robić sobie nawyk z robienia wody z mózgu i niszczenia samego siebie? Nic się nie zmienia po miesiącu, więc czemu klip miałby się zmieniać?

Możesz to sam przetestować, znajdź ten idealny klip z poprzedniego miesiąca, żeby udowodnić, że coś się zmieniło. Potem, ustaw sobie przypomnienie, żeby go zobaczyć po miesiącu bez porno. Spodoba ci się w nim prawie to samo co ostatnio. Ten sam klip będzie inny po tym, gdy zostaniesz odrzucony albo przetestowany przez partnerkę. Powód jest prosty – uzależniony nigdy nie będzie zadowolony, kiedy mały potwór nie jest usatysfakcjonowany.

Więc gdzie tu satysfakcja? To tylko nieszczęście spowodowane brakiem zaspokojenia głodu. Różnica między oglądaniem porno, a nie oglądaniem jest taka sama jak różnica między szczęściem i nieszczęściem. Dlatego porno wydaje się lepsze. Natomiast użytkownicy, którzy wskakują na swoją stronę z samego rana, są nieszczęśliwi czy oglądają, czy nie.

Ograniczanie nie tylko nie działa, ale jest też najgorszą formą tortury. Nie działa, bo masz nadzieję, że w ramach ograniczania, będziesz zmniejszał swoją ochotę na oglądanie porno. To nie nawyk, to uzależnienie. Naturą uzależnienia jest chęć brania więcej i więcej, a nie mniej i mniej.

Więc żeby zmniejszyć konsumpcję, musisz użyć swojej siły woli i dyscypliny do końca życia. Więc ograniczenie oznacza siłę woli i dyscyplinę do końca życia. Całkowite rzucenie jest dużo łatwiejsze i mniej bolesne, szczególnie że są setki tysiące osób, którym ograniczanie nie pomogło.

Trudnością w rzuceniu nie jest uzależnienie od dopaminy, z którym łatwo sobie radzić.

Problemem jest twoja wiara w to, że pornografia daje przyjemność, która wynika z prania mózgu, które rozpoczęło się, zanim zacząłeś i jest wzmacniane przez twoje uzależnienie. Ograniczanie tylko wzmacnia ten błąd logiczny do takiego stopnia, że pornografia zaczyna panować nad twoim życiem i przekonuje cię, że najcenniejszą rzeczą na ziemi jest właśnie to uzależnienie.

Znam niewiele przypadków, w których ta metoda zadziałała i wyglądała zwykle tak, że przez krótki czas użytkownicy się ograniczali, a potem po prostu kończyli. Tym ludziom udało się na przekór ograniczaniu, a nie przez nie. Jedyne co osiągnęli to przedłużenie agonii i nieudane próby, które prowadzą do nerwów i przekonania o uzależnieniu na całe życie. To wystarczy, żeby wrócić w ramiona haremu online, podpory i kolejnych sesji przed następną próbą odstawienia.

Mimo to, ograniczanie pomaga dojrzeć próżność pornografii, pokazując nam, że wizyty w haremie wcale nie są zabawne po dłuższym okresie abstynencji. Musisz walić głową w mur (cierpiąc na głód), żeby było miło. Więc wybór masz następujący:
1.  Ograniczyć spożycie do końca życia, co prowadzi do codziennej tortury, co i tak jest niemożliwe,
2. Torturować się coraz bardziej, do końca życia, co nie ma sensu,
3. Być dobrym dla siebie i po prostu rzucić porno raz a porządnie Inny wymiar ograniczania demonstruje, że nie ma czegoś takiego jak okazjonalna wizyta w haremie. Pornografia to reakcja łańcuchowa, która będzie trwała do końca życia, chyba że się z niej wyłamiesz.

**Przypominam: ograniczanie cię zniszczy**