# Tylko zerknę

„*Tylko zerknę*” to mit, który musisz sobie wybić z głowy:

- to właśnie **to jedno spojrzenie** nas uzależniło
- to właśnie **to jedno spojrzenie** stawia nas na trudnej drodze i niweczy nasze próby rzucenia
- to właśnie **to jedno spojrzenie** po wyzbyciu się uzależnienia wysyła nas prosto w pułapkę. Czasem chcemy potwierdzić, że tego nie potrzebujemy – a jedna wizyta w haremie przywraca tę potrzebę

Twoje samopoczucie po takim spojrzeniu będzie okropne i przekona cię, że nigdy się już nie uzależnisz – ale już jesteś uzależniony z powrotem. Myślisz sobie, że coś tak okropnego i wstydliwego nie zmusi cię do powtórki, ale jednak tak się stało.

To myśl o tej 'jednej specjalnej sesji', która powstrzymuje użytkowników przed rzuceniem, ta jedna sesja po długiej konferencji, ciężkim dniu, kłótni z dziećmi, albo gdy partner odmawia ci seksu. Zapamiętaj to **bardzo dokładnie** – nie ma czegoś takiego jak 'zerkanie'. To reakcja łańcuchowa, która będzie się ciągnęła do końca życia, o ile ją przerwiesz. Mit o tej jednej, specjalnej okazji utrzymuje użytkowników w nieszczęściu po rzuceniu. Wejdź w nawyk o niemyśleniu o tej 'małej' sesji, bo to fantazja. Kiedy myślisz o pornografii, to widzisz ten obrzydliwy wykres życia spędzonego przed ekranem dla przywileju niszczenia zdrowia fizycznego i psychicznego i całego życia jako niewolnik bez nadziei. Erekcja nie jest przestępstwem, ale wybór chwilowego zaspokojenia zamiast długotrwałego szczęścia już jest.

Nie ma problemu, z tym że czasem nie mamy czym zastąpić tej pustki 'czymś do roboty'; to jest po prostu niemożliwe w każdym momencie naszego życia. Możemy planować do przodu, ale czasem tak po prostu jest. Dzieją się również dobre i złe rzeczy, które nie mają nic wspólnego z pornografią. Ale zapamiętaj dobrze – porno to nie jest to. Masz do wyboru życie pełne nieszczęścia albo życie bez. Nie śni ci się, żeby łykać cyjanek, bo nie smakuje ci brukselka, więc nie męcz się, stosując najgorsze rozwiązanie, czyli jedną szybką sesję. Zapytaj uzależnionego - „*czy gdybyś mógł cofnąć czas, do momentu, zanim się uzależniłeś – oglądałbyś?*”. Odpowiedź zawsze będzie taka sama - „*W życiu!*” A mimo to, każdy z nas ma ten wybór każdego dnia, więc czemu na niego nie stawiamy? Odpowiedź to strach. Strach, że się nie uda i strach przed tym, że życie się zmieni.

Przestań się okłamywać! Możesz to zrobić, każdy może. To niesamowicie proste, ale musisz sobie wpoić kilka fundamentalnych idei:
1. Z niczego nie rezygnujesz, czekają cię tylko zyski
2. Nigdy nie przekonuj się to 'zerknięcia' ani do jednej sesji. To nie istnieje. Jest tylko całe życie pełne brudu i niewoli.
3. Nie jesteś specjalny - każdy uzależniony może przestać.

Wielu użytkowników myśli, że są potwierdzonymi uzależnionymi i mają po prostu taką osobowość. To wynik czytania szokujących publikacji o neurobiologii. Nie ma czegoś takiego, nikt nie rodzi się z potrzebą masturbacji do klipów, ta pojawia się, dopiero gdy zaczniesz to robić. To narkotyk, który uzależnia, a nie natura twojej osobowości. To właśnie te nadnaturalne bodźce każą ci tak myśleć. Musisz wyzbyć się takiego myślenia, bo jeśli wierzysz, że jesteś uzależniony – to będziesz, nawet jeśli mały potwór w twojej głowie umrze. Musisz usunąć to pranie mózgu.