# Okazjonalny użytkownik

Mocno uzależnieni chcieliby znaleźć się na miejscu tego okazjonalnego użytkownika:

„*Mogę tydzień wytrzymać, nie mam z tym żadnego problemu*”. Wszyscy chcemy tacy być. Może ciężko będzie w to uwierzyć, ale nikomu nie podoba się używanie porno. Nie zapominaj: Żaden z użytkowników nie zdecydowałby nim zostać, czy okazjonalnie, czy nie, więc każdy użytkownik czuje się głupio, więc wszyscy użytkownicy okłamują siebie i innych, żeby usprawiedliwić swoją głupotę.

Fanatycy wędkarstwa przechwalają się, jak często łowią i chcą łowić, więc dlaczego użytkownicy przechwalają się, jak mało używają? Jeśli takie jest kryterium, to na pewno najlepszy jest po prostu brak masturbacji?

Jeśli ktoś mówi „*Mogę nie jeść marchewek przez cały tydzień, nie mam z tym żadnego problemu*” to pomyślisz, że rozmawiasz z szaleńcem. Jeśli lubię marchewki, to czemu miałbym sobie ich przez tydzień odmawiać? Jeśli ich nie lubię, to po co w ogóle to mówić? Więc kiedy ktoś mówi o tym, że może tydzień nie oglądać pornografii, to próbuje przekonać i siebie i ciebie, że nie ma żadnego problemu. Ale jeśli nie ma problemu – to nie ma potrzeby o tym mówić. To zdanie można przetłumaczyć jako „*udało mi się przetrwać tydzień bez pornografii*”. Jak każdy użytkownik, marząc o tym, aby przetrwać całe życie. Możesz wytrzymać tylko tydzień, to wyobraź sobie, jak cenna musiała być ta sesja po tygodniowej przerwie?

Dlatego właśnie okazjonalni użytkownicy są bardziej uzależnieni od tych aktywnych, bo nie tylko iluzja przyjemności jest większa, ale mają też mniejsze ciśnienie, żeby rzucić, bo nie tracą na tym aż tak dużo czasu, przez co czeka ich mniej skutków ubocznych. Czasem może i doświadczą dysfunkcji seksualnej, ale są niepewni, co ją wywołało, więc szukają innego wytłumaczenia.

Pamiętaj, jedyną przyjemnością dla użytkownika jest szukanie, które wydziela dopaminę, oraz zaspokaja głód, co już tłumaczyłem. Przyjemność jest iluzją, bo mały potwór pornografii jest tym nigdy niepodrapanym swędzeniem, z którego nie zdajemy sobie sprawy.

A jeśli ciągle cię coś swędzi – to się podrapiesz. A nasz układ nagrody staje się coraz bardziej odporny na dopaminę i opioidy, więc naturalnym jest dochodzenie, eskalowanie, oglądanie wielu rzeczy po kolei, szukanie szokujących nowości i tak dalej. Są cztery czynniki, które powstrzymują użytkowników przed oglądaniem dużej ilości naraz:
1. Czas – większości ludzi na to nie stać.
2. Zdrowie – żeby się podrapać, musimy skonsumować cały dostępny materiał i jeszcze trochę. Zdolność radzenia sobie z takim ciągiem jest różna dla każdego z nas, w zależności od momentu, w którym się znajdujemy. To nasze naturalne ograniczenie.
3. Dyscyplina – narzucona przez społeczeństwo, pracę, przyjaciół i rodzinę. Czasem nawet przez samego użytkownika jako rezultat przepychanki w głowie.
4. Wyobraźnia – brak wyobraźni obniża szok i obrzydzenie z klipu, który oglądasz.

Łatwo się mówi o silnie uzależnionych jako o słabych, nierozumiejących jak inni są w stanie ograniczać swoje spożycie. Trzeba jednak pamiętać, że ci okazjonalni nie rozumieją idei łańcucha, co wymaga dużej wyobraźni i wytrzymałości. Niektórzy z tych okazjonalnych, którym silnie uzależnieni zazdroszczą, że nie mają fizycznej możliwości używać więcej z powodu ich pracy, społeczeństwa bądź strachu przed wpadką w uzależnienie.

Przyda się nam kilka definicji.

**Nie używający**

Ktoś, kto nigdy nie wpadł w pułapkę, ale nie powinien tracić czujności. Są w tej sytuacji dzięki szczęściu albo woli boskiej. Wszyscy użytkownicy byli przekonani, że nigdy się nie uzależnią, a niektórzy nieuzależnieni i tak próbują od czasu do czasu.

**Okazjonalny użytkownik**

Można ich podzielić na dwa typy:
1. Użytkownik w pułapce, który nie zdaje sobie z niej sprawy. Nie bądź taki jak oni.
Oni po prostu zlizują słodki nektar z brzegu rosiczki i w każdej chwili mogą zostać schwytani w sidła. Pamiętaj, każdy alkoholik zaczynał od piwka do obiadu, więc tutaj sytuacja jest taka sama.
2. Ktoś, kto kiedyś używał dużo i myśli, że nie może przestać. Ci użytkownicy są w najgorszej sytuacji i wpadają w wiele różnych kategorii, a każda z nich wymaga osobnego wytłumaczenia.

**Raz dziennie**

Jeśli podoba im się ich orgazmowanie, to po co używać pornografii raz dziennie? A jeśli w sumie nie ma to większego znaczenia, to po co w ogóle oglądać? Pamiętaj, ten nawyk jest jak walenie głową w mur, żeby zrelaksować się, gdy skończymy. Użytkownik raz dziennie powstrzymuje swój głód, spędzając na tym mniej niż godzinę. I mimo że nie zdaje sobie z tego sprawy, to potem resztę dnia wali w mur i robi to przez większość życia. Używa tylko raz, bo nie chce ryzykować przyłapania, albo zrobienia sobie wody z mózgu. Łatwo przekonać ciężkiego użytkownika, że mu się to nie podoba, ale dużo trudnej przekonać takiego okazjonalnego. Każdy kto przeszedł przez próbę odstawienia, wie, że to najgorsza tortura, która gwarantuje uzależnienie do końca życia.

**Odrzucony**

Ci wymagają dostępu do orgazmu raz dziennie, ale ich partner nie zawsze jest na to gotowy. Na początku używają pornografii, żeby wypełnić tą pustkę, ale po zjechaniu kilka razy na swojej zjeżdżalni wpadają w pułapkę szokujących materiałów i nadnaturalnych bodźców. W końcu cieszą się z odmowy, bo to daje im wymówkę do oglądania pornografii. A skoro porno daje ci tyle dobrego, to po co partner? Może lepiej się rozstać? Sesje nie są tak przyjemne, kiedy myślisz o partnerce. W pewnym momencie zaczniesz szukać tej wymówki, żeby móc trafić do ciemnych alejek Internetu.

**Dietetyk porno**

Znany również jako – *Mogę przestać, kiedy chcę, robiłem to już tysiąc razy!*

Jeśli wydaje im się, że dieta pomaga im w zdobywaniu partnerów, to po co w ogóle być na takiej diecie przez cztery dni? Nikt nie umie przewidzieć przyszłości, co jeśli na przykład okazja przytrafi się godzinę po twoim cheat meal? Tak samo, jeśli okazjonalne przeczyszczenie rur działa tak dobrze na rozładowanie napięcia, to czemu nie robić tego codziennie? Zostało udowodnione, że masturbacja nie jest konieczna do utrzymania zdrowia układu rozrodczego, a już na pewno nie trzeba używać pornografii. Nawet jeśli tak jest, to żaden uwodziciel, który czytał o skutkach neurologicznych oglądania pornografii, nigdy nie zasugeruje, żeby jej używać. Prawda jest taka, że ci też są uzależnieni. Może nie fizycznie, ale nadal pozostaje główny problem wypranego mózgu.
Za każdym razem mają nadzieję, że to ostatni raz, ale szybko znowu wpadają w pułapkę.

Większość użytkowników zazdrości tym dietetykom, bo wydaje im się, że taki to musi mieć szczęście, żeby kontrolować swoje użycie. Jedyny problem polega na tym, że oni wcale go nie kontrolują – bo kiedy używają, woleliby nie używać. Z deszczu pod rynnę. Jeśli się nad tym zastanowisz, to tak właśnie jest w życiu użytkowników, kiedy mogą rozpocząć sesję – należy im się, ale woleliby nie. Tylko jeśli go brakuje, to porno staje się potrzebą. Syndrom zakazanego owocu jest również wielkim problemem dla uzależnionych. Nigdy nie wygrają, bo szukają mitu i iluzji. Jest tylko jedna droga do zwycięstwa – przestać szukać i przestać oglądać porno!

**„Oglądam tylko amatorki”**

Tak, każdy tak robi na początku, ale nie jest niesamowite, jak szybko wartość tych klipów spada i zanim się obejrzymy, znowu czujemy wybrakowanie? W statecznym porno brakuje szoku, więc płacimy za oliwę i zjeżdżamy na zjeżdżalni prosto w poczucie winy. Najgorsze co możesz zrobić to masturbować się do zdjęć swojej partnerki. Dlaczego? Bo robiąc to, uczysz swój mózg czerpania przyjemności z szukania i różnorodności wyrzutów dopaminy. Chemicznie rzecz biorąc, twój mózg zwiększa DeltaFosB, więc będziesz miał potem problem podczas stosunku w prawdziwym życiu.

Kolejną pułapką jest tzw. amatorskie porno. Większość z nich to fejki, o czym dobrze wiesz, a poza tym i tak nie zatrzymasz się na tym jednym, które zobaczysz, będziesz dalej szukał i cieszył się widokami. Pamiętaj, twój mózg pragnie nie tylko orgazmu, ale podniety wyszukiwania, która jest zjazdem w dół. Zawartość pornosa nie ma znaczenia – czy amatorskie, czy profesjonalne – to wyrzut dopaminy w mózgu, dzięki któremu budujesz tolerancję i nasycenie. Pornografia niszczy normalne funkcjonowanie mózgu, masturbacja miesza w twojej koordynacji między mózgiem a mięśniami. Orgazm zalewa mózg opioidami i sprawia, że następnym razem droga jest łatwiejsza.

**Przestałem, ale czasem zaglądnę**

W pewnym sensie ci są najbardziej żałośni. Albo idą przez życie z uczuciem wybrakowania, albo częściej – jedno spojrzenie zamienia się w dwa. Spadają prosto w dół, prędzej czy później wracając do swojego uzależnienia. Po raz kolejny wpadają w tę samą pułapkę.

Są jeszcze dwie kategorie okazjonalnych użytkowników. Pierwszy to ten, który masturbuje się do zdjęć i nagrań celebrytek, które wyciekły do Internetu, albo do czegoś, co 'przynieśli' ze sobą do domu ze szkoły albo pracy. Ci ludzie tak naprawdę nie używają, ale nadal boją się, że coś tracą.
Chcą brać udział a akcji, szczególnie że większość ludzi tak zaczyna. Następnym razem, seks z celebrytką nie jest już taki atrakcyjny, fantazja nie działa. Im bardziej niedostępny obiekt twojej fantazji, tym bardziej frustrujący jest brak orgazmu.

Druga kategoria, coraz popularniejsza, najlepiej opisana przez przypadek opisany online.

Businesswoman, która czytała pornograficzne historie przez wiele lat i nigdy nie używała więcej niż raz dziennie. Przy okazji była też bardzo silną kobietą. Wielu użytkowników zastanowi się, dlaczego w ogóle chciała przestać – przecież nie grożą jej ani problemy z erekcją, ani inne dysfunkcje (ps. to nie prawda). Nie używała przecież nawet obrazków, tylko czytała erotyczne historie, dużo lżejsze niż jakikolwiek materiał używany przez zwykłych użytkowników.

Błędnie zakładasz, że taki okazjonalny użytkownik jest szczęśliwy i kontroluje swoje zachowanie. Może mają trochę więcej kontroli, ale na pewno nie są szczęśliwi. Ta kobieta nie czuła satysfakcji z partnerem ani nie czerpała jej z normalnego seksu oraz była bardzo nerwowa, kiedy spotykały ją trudy życia codziennego. Jej najbliżsi nie umieli dojść do tego, co ją tak nurtuje. Nawet jeśli sama przekonała się do używania poprzez racjonalizację, nadal nie potrafiła cieszyć się prawdziwymi związkami, które mają swoje wzloty i upadki. Jej system nagród nie był w stanie używać normalnych mechanizmów odstresowania obecnych w jej życiu jako rezultat zalewania dopaminą. Jej osłabione receptory zrobiły z niej smutną i zmęczoną osobę przez większość czasu.
Jak wielu z nas, ona również bała się ciemnej strony pornografii i tego, jak traktowane są tam kobiety – przed swoim pierwszym razem. W końcu uległa praniu mózgu i wypróbowała pierwszych filmów. Jednak ona oparła się brutalnym klipom i nie zjechała na tej zjeżdżalni, wybierając czytanie fantazji erotycznych.

Wszystko, co podoba ci się w pornografii to zaspokojenie głodu, który ona sama wywołała, czy to jest nieodczuwalny fizyczny dyskomfort, czy mentalna tortura, gdzie nie możesz się zadowolić w żaden inny sposób. Pornografia to trucizna, więc dlatego cierpisz na iluzję przyjemności po dłuższym okresie abstynencji. Tak jak z normalnym głodem czy pragnieniem, im dłużej cierpisz, tym większa przyjemność z zaspokojenia. Kiedy myślisz, że pornografia to tylko nawyk, popełniasz błąd „*Jeśli uda mi się to ograniczyć do jakiegoś stopnia, albo tylko do wyjątkowych okazji, mój umysł i ciało to zaakceptują. Wtedy będę używał dalej tak rzadko albo nawet bardziej zredukuję*”.

Zrozum, że 'nawyk' nie istnieje. Pornografia to uzależnienie od narkotyku, gdzie naturalną tendencją jest zaspokajanie głodu, a nie wytrzymywanie go. Żeby utrzymać go na tym poziomie, na którym go chcesz trzymać, będzie to od ciebie wymagało ogromnej samodyscypliny i siły woli do końca twojego życia; w miarę jak twój mózg uodparnia się na dopaminę i opioidy, pragnie więcej i więcej, a nie mniej.

W miarę jak porno powoli niszczy twój system nerwowy, odwagę, pewność siebie i kontrolę impulsów, tobie jest co raz trudnej uniknąć zmniejszenia interwału między każdą sesją.
Dlatego na początku w sumie nam nie zależy. Jeśli dostrzeżemy jakiś problem – to przestajemy. Nie pragnij być jak ta kobieta, która ogląda najcenniejszą rzecz na świecie tylko raz na 24 godziny, zamieniając pornografię w zakazany owoc. Przez wiele lat, ta biedna babka stoi w samym centrum wojny w swojej głowie, bez możliwości rzucenia i przerażona, że sięgnie po klipy.

Przez 23 godziny i 50 minut każdego dnia musiała walczyć z pokusą i brakiem uczuć wobec swojego faceta. To wymagało od niej ogromnej siły woli, doprowadzając ją do płaczu. Takie przypadki są rzadkie, ale pomyśl logicznie: albo jest w tym jakaś prawdziwa przyjemność, albo jej nie ma. Jeśli jest, to po co czekać godzinę albo dzień, albo tydzień? Po co masz się wyzbywać tej przyjemności albo podpory? A jeśli nie ma w tym przyjemności – to po co odwiedzać swój harem online?

Tutaj kolejny przypadek dietetyka, który opisuje swoje życie następująco:
> „*Mam 40 lat. Cierpię na PIED (Porn Induced Erectile Dysfucntion – Pornograficzne Zaburzenie Erekcji) z prawdziwymi kobietami oraz podczas oglądania porno, czyli przez większość czasu. Minęło dużo czasu od mojej ostatniej prawdziwej erekcji. Przed przejściem na dietę raz na cztery dni, zawsze smacznie spałem po mojej wieczornej sesji. Teraz budzę się co godzinę i porno to jedyne, o czym myślę. Nawet jak śpię, to mam sny o moich ulubionych filmach. W dni po moich sesjach mam doła, bo dieta zabiera mi całą energię. Moja dziewczyna zostawia mnie samego, bo jestem drażliwy, a jeśli nie może wyjść, to wyrzuca mnie. Idę biegać, ale nadal myślę tylko o pornografii”.*
> 
> „*W wyznaczony dzień zaczynam planować cały wieczór, denerwując się, jeśli coś i wypadnie. Wycofuję się z rozmów w pracy i w domu (czego później żałuję). Nie jestem zbyt kłótliwy, ale nie chcę, żeby rozmowa mnie zajęła. Pamiętam sytuacje, gdzie celowo kłóciłem się z moją dziewczyną. Czekam do dziesiątej i kiedy nadchodzi czas moje ręce się trzęsą. Nie zaczynam zabawy od razu – są nowe filmy, więc muszę je posprawdzać. Mój umysł mówi, że skoro głodziłem się cztery dni, to należy mi się coś specjalnego, więc warto spędzić nad tym czas. W końcu wybieram jeden albo dwa, ale chcę, żeby to trwało jak najdłużej, zanim będzie kolejna przerwa*”.

W dodatku do jego innych problemów, biedak nie ma pojęcia, że bierze truciznę. Najpierw cierpi na syndrom zakazanego owocu, a potem zmuszając swój mózg do produkcji dopaminy. Jego receptory nie są aż tak przygaszone, ale on ciągle naoliwia zjeżdżalnię pornografii, szukając, dochodząc, oczekując różnorodności, szoku i dziwnych klipów, żeby przeżyć kolejne cztery dni.
Może wyobrażasz sobie, że gość jest imbecylem, ale to nie prawda. To były atleta i weteran, nie chciał się od niczego uzależnić. Jednak po powrocie z wojny, zaczął się przyuczać, by zostać pracownikiem w IT, w specjalnym programie dla weteranów.

Kiedy zatrudnił się w cywilnej pracy, dostawał duże wynagrodzenie, pracując w banku i dostał służbowego laptopa. To był też ten rok, kiedy wyciekły zdjęcia wielu celebrytek, więc dużo się o tym gadało. W ten sposób się uzależnił, spędzając swoje życie w nieszczęściu i rujnując się mentalnie i fizycznie. Gdyby był zwierzęciem, ludzie dawno by go uśpili, a mimo to nadal pozwalamy nastolatkom się uzależnić. Może wydaje ci się, że ten przypadek jest przesadzony, ale mimo że może ekstremalny, nie jest unikatowy. Znam setki tysiące podobnych historii. Czy masz pewność, że jego przyjaciele zazdrościli mu, że zredukował użycie do razu na cztery dni? Jeśli myślisz, że takie coś nie dotyczy cię, to **przestań robić sobie jaja**.
**TO SIĘ JUŻ DZIEJE.**

Jak inni uzależnieni, użytkownicy pornografii są kłamcami, szczególnie przed samymi sobą. Muszą być. Większość okazjonalnych użytkowników tak naprawdę ogląda częściej, niż się przyznają. Przy rozmowach z ludźmi „*dwa razy na tydzień*” okazuje się, że używają częściej, często trzy albo cztery razy. Poczytaj Reddita, Wykop i fora NoFap, gdzie znajdziesz historie takich okazjonalnych użytkowników. Zauważysz, że odliczają dni, albo czekają na okazję do porażki. Nie musisz zazdrościć okazjonalnym użytkownikom, nie musisz też używać, bo życie bez tego jest dużo słodsze. Weź taki zapisek:

„*Rozpocząłem od wyzwania, żeby nie dotknąć moich kryształów rodowych przez jeden dzień i mi się to nie udało. Nie myślę już o masturbacji, ona nawet nie pojawia się na chwilę w mojej głowie. To jest możliwe, obiecuję ci to. Bogactwo, które czeka na tych, którym się uda, jest nie do opisania*”.

Nastolatków na ogół trudnej wyleczyć, nie dlatego że im trudnej przestać, ale dlatego, że nie potrafią uwierzyć w uzależnienie, albo w pierwsze sidła pułapki. Wydaje im się, że automatycznie przestaną, jak tylko wejdą zbyt głęboko.

Rodzice dzieci, które brzydzą się pornografią, nie powinni stracić czujności. Wszystkie dzieci brzydzą się ciemną stroną pornografii, zanim się uzależnią. Był taki moment, że byłeś taki sam. Nie daj się też oszukać straszakom, pułapka zawsze jest taka sama. Dzieci wiedzą, że pornografia to nadnaturalne bodźce, ale wiedzą też, że jedna wizyta i oglądanie nie zaspokoją ciekawości. W każdej chwili mogą też zostać namówione przez partnera albo kolegę.

Proszę, nie bądź bierny w tej sprawie. Nasza nieumiejętność zapobiegania uzależnieniu od pornografii i innych substancji jest chyba najbardziej przerażającym elementem tego problemu.
Dojrzewające umysły są dużo bardziej plastyczne i koniecznym jest by je edukować i ochraniać.

Jeśli nie wiesz, gdzie zacząć, dobrze sięgnąć po książkę YourBrainOnPorn, która tłumaczy neurobiologię problemu. Nawet jeśli podejrzewasz, że twój nastolatek ma już problem, ta książka dostarcza podstawy do zrozumienia jak pomóc komuś uciec. W innym przypadku – poleć im Koniec z Porno!