# Użytkownik YouTube/Twitch/Instagrama

Ten użytkownik powinien być zgrupowany z pozostałymi okazjonalnymi użytkownikami, ale efekty są tak niecne, że opiszę je w osobnym rozdziale. Te social media wywołują rozpad samokontroli, prowadząc do tragedii:

> *Moja żona zaczęła martwić się o moją nieregularną erekcję i brak zainteresowania seksem. To spowodowało, że próbowałem przestać przez trzy tygodnie. Powiedziałem jej, że to nie jej wina, że mam problemy w pracy. Ona na to „wiem, że wcześniej radziłeś sobie z pracą, więc to nie to. Jakbyś się poczuł, gdybyś był mną i musiał patrzeć jak ktoś, kogo kochasz systematycznie niszczy samego siebie?” To był argument, którego nie mogłem odbić, więc musiałem przestać.*
>
> *Wiedziała, że jej nie zdradzam, ale to było dużo gorsze. Próba skończyła się po trzech tygodniach, po ostrej kłótni z moim przyjacielem. Dopiero lata później zrozumiałem, że to mój umysł sam wywołał tę kłótnię, czułem się wtedy urażony, ale nie wydaje mi się, że to był przypadek, bo nigdy wcześniej ani później się z nim nie kłóciłem. Jasne było, że to był mały potwór.*
> 
> *No ale cóż, miałem swoją wymówkę. Desperacko potrzebowałem zluzowania i nie miało znaczenia jak. Moja żona nie miała ochoty na igraszki, a ja czułem, że mi się należy, więc przekonałem się, że 'ograniczeniem' będzie niekorzystanie z pornografii i oglądanie tylko filmów na YouTube. Jednak moja żona zmieniła zdanie i chciała iść do łóżka, jednak ja byłem już zmęczony i bez moich 'koni mechanicznych', więc wymyśliłem ból głowy. Nie mogłem znieść tego, jak zawiodłem swoją żonę. Wtedy też powoli zacząłem wracać do problemu, tylko tym razem YouTube stał się domem dla mojego haremu. Byłem nawet całkiem zadowolony, bo w końcu ograniczyłem konsumpcję. W końcu żona oskarżyła mnie, że ignoruję jej potrzeby w łóżku. Ja sam nie zdawałem sobie z tego sprawy, ale ona przywołała sytuacje, kiedy prowokowałem kłótnie i wybiegałem z domu. Innym razem dwie godziny kupowałem jakąś pierdołę, a innym zwichnąłem sobie kostkę. Wymyślałem słabe wymówki, żeby uniknąć zbliżeń, a że miałem swój harem online – było to jeszcze prostsze.*

Największym problemem tego mężczyzny był jego błąd logiczny, że czegoś mu brakuje.
Jednocześnie, sprawił, że stracił do siebie szacunek. Normalnie szczera osoba, okłamuje swoją ukochaną. Tak prawdopodobnie było i w twoim przypadku albo nadal tak jest w jakimś sensie.

Problem, z którym stykamy się w przypadku platform takich jak Twitch, Instagram, TikTok, Twitter (i inne social media), jest taki, że są one suplementacją. Napędzani dopaminą z polowania, oszukujemy się, że jesteśmy na bezpiecznej stronie. Pamiętaj – podnieta to poszukiwanie, a nie finisz, a małego potwora nie obchodzi skąd jest działka. Dla użytkownika 'miękki' materiał dostarczany na stronach z social media tak samo niweluje głód, utrzymując uzależnienie i przygotowując na następną sesję.

Modelka na zdjęciu jest rzeczywiście piękna i gdyby koło ciebie siedziała, na pewno byłoby ci przyjemnie, ale to zdjęcie nie może tego zrobić. Ono jest po prostu nieprawdziwe. Twój mózg jest oszukiwany jak byk biegnący w stronę czerwonej płachty, który nie rozumie, po co to robi. Może pomyślisz, że będziesz patrzał na te obrazy bez masturbacji. Ale pamiętaj, twój mózg jest uzależniony od stałych nowości, a mały potwór może zostać nakarmiony różnymi źródłami. To dokładnie taka sama pułapka.

Może oglądałeś kiedyś serial Columbo, tam tematyka każdego odcinka była podobna.
Złoczyńca, zwykle bogaty i szanowany biznesmen popełnia coś, co w jego głowie jest idealnym morderstwem, a jego pewność siebie się tylko umacnia, kiedy widzi, że sprawą zajmuje się odrapany Detektyw Columbo.

Columbo ma taki denerwujący zwyczaj zamykania drzwi po zakończonym przesłuchaniu, zapewniając podejrzanego, że wszystko jest w porządku. I jak tylko satysfakcja pojawia się na twarzy mordercy, ten wraca do pokoju i pyta „*Jeszcze jedna mała sprawa, może pan mi wytłumaczyć...*”. Podejrzany nie wie, co ze sobą zrobić, bo jest świadomy, że Columbo go powoli pokona. Niezależnie od przestępstwa, nasza sympatia była skierowana ku przestępcy.

Te sytuacje są podobne, napięcie spowodowane niemożnością przejścia przez czerwoną linię, żeby zobaczyć pornografię, która się przecież należy, potem zastanawianie się gdzie była ta przyjemność po skończonym akcie. Strach przed czerwoną linią, utratą kontroli i powrót do łóżka, bojąc się, że twój partner będzie chciał się kochać. 'Bezpieczne' filmy na YouTube nie zaspokoją twojego głodu, bo nie są aż tak ciekawe. Do tego masz pewność, że prędzej czy później znowu trafisz na stronie z pornografią. Ostateczne poniżenie i wstyd to moment, kiedy do tego dochodzi i staje się to faktem, a ty znowu jesteś przykuty do łańcucha.

**Ah, porno - sama przyjemność!**