# Nawyk społeczny?

Zdrowie ciała i umysłu to główne powody, dla których powinniśmy chcieć przestać – i zawsze tak było. Nie potrzebujemy dowodów naukowych i neurobiologii, żeby wiedzieć, że pornografia uzależnia i może nam zniszczyć życie. Nasze ciała są najbardziej skomplikowanymi obiektami na ziemi i każdy z nas wie, od pierwszej sesji, że bodźce mogą być przesadzone i zamienić się w truciznę.

Jedynym powodem, dla którego sięgamy po pornografię, jest fakt, że wpływa ona na nasze ewolucyjne programowanie. Pornografia jest łatwo dostępna, darmowa i można się do niej dostać w każdej chwili. Kiedyś twierdzono, że porno jest bezpieczne, ale wtedy dostępne były tylko stateczne obrazy, a dostęp do filmów wymagał wycieczki do wypożyczalni kaset.

Dziś, nawet użytkownicy, uważają, że pornografia jest nadnaturalnym bodźcem i silnie uzależnia. Dawno temu, mężczyzna nie przyznawał się do masturbacji, a walenie konia było uwłaczające. W każdym pubie, klubie albo barze, większość mężczyzn zabiegała o kobiety, żeby uprawiać prawdziwy seks. Dziś ta sytuacja jest odwrócona dla uzależnionego, dziś mężczyznom wydaje się, że nie potrzebują kobiet. Grupy facetów dyskutują o doświadczeniach, wymyślają strategie i szukają nowych opcji. Dzisiejszy mężczyzna nie chce być zależny od narkotyków.
Poprzez rewolucję społeczną, wszyscy użytkownicy myślą o rzuceniu porno i masturbacji. Dziś pornografię uważa się za bezużyteczną i szkodliwą.

Najważniejszym trendem, który można zaobserwować na forach jest zwiększający się nacisk na antyspołeczne aspekty pornografii. Przechwalanie się codziennymi orgazmami i seksem jest zastępowane zrozumieniem uzależnienia od potwora porno.

Jedynym powodem, dla którego ludzie używają po poznaniu prawdy, jest niemożność rzucenia albo strach przed próbą. Temat jest omawiany szeroko – niektórzy odstawiają pornografię, masturbację i orgazmy zupełnie, niezależnie czy przy partnerze czy bez. Praktyki rozdzielające seks tantryczny od prokreacyjnego, takie jak retencja nasienia czy Karezza są stosowane powszechnie.
Nawet porażki mogą mieć pozytywny wpływ na użytkownika. Gdy wejdziesz na drogę bez PMO, znajdziesz swój najlepszy sposób, zachęcam rozpisanie swojego własnego planu na orgazmy po tym jak zrozumiesz swoje ciało. Jakąkolwiek drogę wybierzesz, zrozumiesz zalety niezalewania swojego mózgu dopaminą i opioidami poprzez orgazm i nieużywania pornografii oraz orgazmu jako przyjemności czy podpory dla swoich emocji.

Wiele ze społeczności online skupia się nie tylko na odstawieniu pornografii, ale również masturbacji. Te strony są korzystne dla tych którzy chcą uciec, ale większość z nich proponuje metodę na siłę woli. Konsekwencją obsesji jak najdłuższej passy bez masturbacji jest użalanie się nad sobą i brak radości. Pranie mózgu nadal pozostaje w głowie. W końcu ktoś się łamie i rozpoczyna się efekt domino, kiedy inni użytkownicy odkrywają, że nie tylko oni nie dali rady.
Mimo tego, lepsze to niż nic. Ci ludzie idą do przodu, ale męczą się, zamykając przeglądarki, a nie swoje pragnienia i wymagania. Koniec z Porno działa odwrotnie, wyłączając pragnienie przed wyłączeniem przeglądarki. Każdego dnia co raz więcej użytkowników ucieka z tonącego statku, a ci, którzy nadal na nim są – boją się, że zostaną sami.

**TO NIE BĘDZIESZ TY!**