# Poczucie czasu

Abstrahując od tego, że porno nic nie wnosi i że teraz jest najlepszy czas, aby przestać, wyczucie czasu jest ważne. Społeczeństwo traktuje porno jako odrobinę niesmaczny nawyk, który nie ma wpływu na zdrowie. To nie prawda. To narkotyk, choroba i niszczyciel relacji społecznych.
Najgorszą rzeczą w życiu wielu użytkowników jest właśnie to uzależnienie. A jeśli nic z tym nie zrobią – dzieją się okropne rzeczy. Więc wyczucie czasu jest ważne, żebyś mógł sobie podać odpowiednie remedium.

Po pierwsze - zidentyfikuj, kiedy pornografia jest dla ciebie ważna. Jeśli pracujesz w biznesie i używasz jej do odstresowania – wybierz jakiś luźny okres. Jeśli używasz pornografii do zabicia nudy, przyjmij odwrotną taktykę. Najważniejsze, abyś wziął to na poważnie i potraktował jako najważniejszą rzecz w twoim życiu.

Spójrz na kolejne trzy tygodnie i zastanów się, co może się wydarzyć, co doprowadzi do porażki. Okazje takie jak konferencje, może twój partner wyjeżdża na kilka dni i tak dalej. One ci nie przeszkodzą, jeśli pomyślisz o nich wcześniej i nie będziesz się czuł wybrakowany. Do tego czasu nie ograniczaj spożycia, to tylko wykreuje iluzję, że wybrakowanie jest przyjemne.
Właściwie to warto wmusić w siebie jak najwięcej sesji jak to możliwe. Kiedy dojdziesz do ostatniej, zapamiętaj swoje rozczarowanie odczuleniem, uczucie niezaspokojenia, ból w ciele, efekty głodu, podenerwowanie i smutek. Pomyśl sobie, jak cudownie będzie przestać.

**Nie wpadnij w pułapkę mówienia 'ok, zrobię to później'. Nie odkładaj tego. Przygotuj plan i ciesz się nim.**

Pamiętaj, z niczego nie rezygnujesz. Wręcz przeciwnie, czekają cię same zyski.

Przez lata medycyna uważała pornografię za bezpieczną, bez rozpoznania różnicy między starą, stateczną pornografią poprzedniej ery, a nowoczesnymi doświadczeniami z VR. Problem wynika z tego, że każdy użytkownik ogląda, żeby zaspokoić głód dopaminy, ale to nie uzależnienie od substancji wciąga uzależnionego, to jego własne pranie mózgu wynikające z uzależnienia.
Inteligentna osoba może dać się nabrać na wytłumaczenie o pewności siebie, ale tylko głupiec da się złapać po poznaniu sekretu. Na szczęście większość użytkowników nie jest głupia; tylko się nam tak wydaje. Każdy z nas ma swoje własne, prywatne pranie mózgu. Dlatego wydaje się, że rodzajów uzależnionych jest tak wiele, co tylko nagromadza tajemnice.

Oryginalna książka uczyła rzucać nikotynę (jeden z najszybciej uzależniających narkotyków). Nadal zaskakuje mnie, że filozofia przedstawiona w oryginale nadal trzyma się kupy, jeśli ją zastosujemy. Wyzwanie, którego podejmuję się razem z Carrem, to jak zakomunikować tę wiedzę każdemu z użytkowników. Wiem, że każdy użytkownik może łatwo i przyjemnie przestać, ale frustruje mnie, że muszę zmusić go do zrozumienia tego. W oryginale Allen Carr tłumaczy swoją kontrowersyjną metodę:

*Wiele ludzi mówi: „Twierdzisz, że mam palić w trakcie czytania książki”. To sprawia, że palacz czyta książkę bardzo długo, albo w ogóle jej nie kończy. Kropka. Więc może zmienić instrukcję? To ma sens, ale jeśli powiedziałbym „natychmiast przestań”, niektórzy palacze nawet nie sięgnęliby po tą książkę. Rozmawiałem kiedyś z palaczem, mówił: „nie podoba mi się to, że muszę prosić o pomoc. Mam silną wolę. W każdym innym aspekcie życia mam kontrolę. Jak to jest, że ci wszyscy palacze rzucają samą siłą woli, a ja muszę przychodzić do ciebie? Jestem przekonany, że dałbym radę sam, gdybym tylko mógł palić podczas rzucania”*

Społeczeństwo jest przekonane, że rzucenie palenia jest okropnie trudne, więc czego potrzeba palaczowi jak coś jest trudne? Małego przyjaciela i podpory. Więc rzucenie palenia to podwójny cios – nie dość, że trudno, to nie możemy polegać na naszym 'odstresowywaczu'.
Najpiękniejszym aspektem tej metody jest to, że nie musisz z niczego rezygnować, kiedy rzucasz.
Najpierw pozbywasz się strachu i wątpliwości, a po ostatniej sesji od razu cieszysz się wolnością.

Dlatego ta książka stosuje tę samą metodę. Niezależnie od tego, jak wiele razy powtórzę, że będzie łatwo i przyjemnie, większość ludzi tego nie zaakceptuje ze względu na swoje własne przekonanie o trudności tego przedsięwzięcia.

Ten rozdział jest jedynym, w który wątpię z oryginalnej metody. Jeśli twoim wyzwalaczem jest stres w pracy, wybierasz wakacje, żeby rzucić i na odwrót. To nie jest najprostszy sposób, bo lepiej wybrać ten najtrudniejszy moment. Niezależnie od tego, czy masturbujesz się ze stresu, czy z odpowiedzialności, czy nudy, jak udowodnisz sobie, że umiesz cieszyć się życiem w najgorszej sytuacji, pozostałe będą jeszcze lepsze. Ale jeśli taka będzie porada – to w ogóle spróbujesz rzucić?

Może użyję analogii. Ja i moja siostra chodzimy razem pływać. Przyjeżdżamy na basen o tej samej godzinie, ale koniec końców rzadko kiedy pływamy razem. Powód jest taki, że ona najpierw zanurza jeden palec i zaczyna pływać pół godziny później. To powolna tortura, a ja jestem świadomy, że w pewnym momencie, niezależnie od temperatury wody, będę musiał się w niej zanurzyć. Więc nauczyłem się prostszego sposobu – po prostu wskakuję. Teraz wyobraź sobie, że stwierdziłbym, że skoro ona nie wskakuje od razu, to znaczy, że nie umie pływać. Rozumiesz?

Z moich informacji wynika, że wielu użytkowników użyło tego rozdziału jako drogi do odsunięcia 'strasznego dnia'. Myślałem potem o technice zastosowanej w rozdziale o zaletach porno, coś w stylu „*wybór odpowiedniego momentu jest ważny, więc w następnym rozdziale powiem ci jak go znaleźć*”, a następna strona to tylko wielkie TERAZ! To jest najlepsza porada, ale zastosowałbyś ją? Jednym z najsubtelniejszych elementów pułapki, jest to, że stresujący okres nie jest odpowiednim momentem na rzucenie, ale w okresie bez stresu nie mamy potrzeby zakończenia tortury. Zadaj sobie pytanie:
1. Kiedy zacząłeś oglądać porno, czy zdecydowałeś, że będziesz oglądał je do końca życia bez możliwości przestania? Oczywiście, że nie!
2. Czy będziesz kontynuował do końca życia? No jasne, że nie!

Więc kiedy przestaniesz? Jutro? Za rok? Może jeszcze później? Czy nie zadajesz sobie tego pytania od chwili, kiedy zdałeś sobie sprawę z uzależnienia? Czy masz nadzieję, że pewnego dnia się obudzisz bez chęci oglądania? Nie oszukuj się, każde uzależnienie wciąga cię coraz głębiej każdego dnia. Będziesz czekał, aż wyjście z łóżka będzie trudniejsze niż masturbacja? To jest trochę bez sensu.

Prawdziwą pułapką jest wiara w to, że teraz jest nieodpowiedni moment. Bo jutro będzie łatwiej. Wierzymy, że nasze życie jest stresujące, ale to nieprawda. Większość stresów nie istnieje.
Kiedy wychodzisz na zewnątrz, nie boisz się ataku dzikiego zwierzęcia, nie musisz się martwić swoim następnym posiłkiem albo tym gdzie będziesz spał. Pomyśl o tym, jak żyje dziki królik. Za każdym razem, gdy wystawia głowę z nory, jest skazany na sajgon. Ale on sobie z tym radzi, ma adrenalinę i inne hormony i my tak samo. Prawda jest taka, że najbardziej stresującym okresem dla ludzi jest dzieciństwo i młodość. Trzy miliardy lat ewolucji i naturalnej selekcji dały nam narzędzia do radzenia sobie ze stresem, a wielu ludzi z ciężkim dzieciństwem dziś prowadzi normalne życie.

Może to kliszka, ale to stwierdzenie jest całkowicie prawdziwe: „*zdrowie jest najważniejsze*”. Jeśli czujesz się dobrze fizycznie i psychicznie, możesz cieszyć się wzlotami i radzić sobie z upadkami. Wiele osób myli stres z odpowiedzialnością, która jest trudna, tylko jeśli wydaje nam się, że nie damy rady z nią sprostać. To, co nas niszczy to nie stres, praca i wiek, to te sztuczne i zbędne podpory, na których polegamy.

Spójrz na to w ten sposób. Zdecydowałeś już, że nie chcesz siedzieć w pułapce do końca życia. Więc w którymś momencie – niezależnie czy to łatwe czy trudne – będziesz musiał się z niej uwolnić. Pornografia to nie nawyk i nie przyjemność, to uzależnienie i choroba. Ustaliliśmy, że jutro będzie jeszcze trudnej. Więc czas skończyć właśnie teraz – albo jak tylko będziesz w stanie.
Zastanów się, jak szybko mija tydzień. Pomyśl, jak miło będzie spędzić resztę życia bez tych cieni w twojej głowie. Jeśli zastosujesz instrukcje, nie będziesz musiał czekać pięciu dni albo trzech tygodni. Rzucanie będzie nie tylko łatwe, ale i przyjemne.