# Czy coś mnie ominie?

**Nie!** Gdy tylko mały potwór zginie, po tym, jak twoje ciało przestanie pragnąć dopaminy, zjeżdżalnie w twoim mózgu zaczną się szybko zamykać ze względu na brak oliwienia, a pranie mózgu będzie znikać. Będziesz w lepszym stanie fizycznym i mentalnym, co pozwoli na łatwiejsze radzenie sobie ze stresem i cieszenie się w pełni najlepszymi elementami życia.

Jest tylko jedno zagrożenie. Ci, którzy nadal używają seksu jako przyjemności i podpory.

„*Wszędzie dobrze, gdzie nas nie ma*” często dotyczy wielu aspektów naszego życia i łatwo to zrozumieć. Dlaczego w przypadku porno – gdzie wady są ogromne w porównaniu do iluzorycznych zalet – eksużytkownik zazdrości tym którzy używają pornografii i seksu jako podpory?

Rozumiemy, że znajdujemy się w pułapce tego całego prania mózgu od dzieciństwa.

Dlaczego więc, kiedy zrozumiemy jaką głupią grą jest pornografia i rezygnujemy z uzależnienia, wchodzimy znowu w sidła? To wpływ społecznego prania mózgów, które łączy pornografię z seksem i przedstawia to jako coś normalnego. Eksużytkownik czuje głód! Niepewna pustka wywołana statusem singla (w czym nie ma nic złego), wywołuje uczucie dyskomfortu i prowadzi prosto na zjeżdżalnię. To jest dopiero anomalia, szczególnie biorąc pod uwagę, że każdy nieużywający jest szczęśliwy, że nie używa, a każdy uzależniony na świecie, nawet ze swoim wykręconym i wypranym umysłem, który cierpi na iluzję relaksu i przyjemności, chciałby nigdy się nie uzależnić. Więc dlaczego eksużytkownicy czują zazdrość?

1. Tylko jedno spojrzenie. Pamiętaj, ono nie istnieje. Przestań patrzeć na to jako wyizolowany przypadek, a spójrz jako uzależniony. Może zazdrościsz, ale oni nie są z siebie zadowoleni i chcą być jak ty. Może gdybyś mógł spojrzeć klinicznie na innego użytkownika, byłoby to dla ciebie największą pomocą. Zobacz, jak szybko otwierają karty przeglądarki, przewijając do odpowiednich momentów, znudzeniu klipami, przeszukują inne gatunki, żeby znaleźć odpowiednio szokujące źródło dopaminy. Cała zabawa jest automatyczna. Pamiętaj, to im się nie podoba, oni po prostu nie potrafią bez tego zaakceptować siebie. Następnego ranka wstają z osłabioną wolą, bez energii i z podkrążonymi oczami, będą myśleć o kolejnej sesji na pierwszą myśl o stresie. Czeka ich życie pełne brudu, problemów psychicznych i braku pewności siebie.
Życie niszczenia samego siebie, z cieniami z tyłu głowy. A po co? Żeby spełnić swoją iluzję przyjemności i otrzymania tego, co się należy.

2. Drugim powodem, dla którego eksużytkownicy odczuwają głód, jest fakt, że użytkownik robi coś – na przykład masturbuje się – a nie używający tego nie robi, więc czuje się, jakby czegoś mu brakowało. Wbij to sobie do głowy – to nie zdrowej osobie czegoś brakuje, to użytkownik pozbywa się:
   - energii
   - zdrowia
   - pewności siebie
   - spokoju ducha
   - odwagi
   - wolności
   - szacunku do samego siebie.

Przestań zazdrościć użytkownikom i zrozum prawdę. To oni są nieszczęśliwymi i żałosnymi istotami. Wiem o tym, bo kiedyś byłem jednym z najgorszych. Dlatego też czytasz tę książkę, a nie słuchasz tych, którzy się oszukują i nie potrafią spojrzeć prawdzie w oczy.

Nie zazdrościłbyś uzależnionemu od heroiny, a tak jak wszystkie inne uzależnienia – twoje nie naprawi się samo. Każdego roku będzie coraz gorzej – jeśli nie podoba ci się używanie dziś, jutro będzie jeszcze gorzej. Nie zazdrość innym użytkownikom – współczuj im. Wierz mi, **oni potrzebują twojego współczucia**.
