# Mogę szufladkować?

Ten mit jest często rozpowiadany przez użytkowników, którzy używają metody na siłę woli. Wymagana jest mentalna gimnastyka, wymagane jest rozdwojenie jaźni: „*Pornografia to moje alter ego, a normalne relacje to moja część romantyczna*”. Nic bardziej mylnego. Zjeżdżalnia, DeltaFosB i zmiany neurologiczne opanują prawdziwy romans, sprawiając, że nie będzie tak atrakcyjny. Szaleństwo na pewno zdominuje racjonalność.

Kiedy używasz porno, stajesz się podglądaczem, zmuszasz się do kolejnego, bardziej podniecającego filmu, gdy tylko twój poziom dopaminy spadnie. Ciągle szukasz tego idealnego klipu, który cię zaspokoi. W końcu masturbujesz się pochylony nad smartfonem w łóżku, doprowadzając do momentu, w którym to jest dla ciebie bardziej atrakcyjne niż prawdziwe kobiety.

Seks jest przeciwny praktycznie każdemu aspektowi haremu, więc nie ma szans wygrać przy porównaniu. Wspomnienia wytworzone, kiedy jesteś młody i silny są wyraźne, więc złamanie ich, bądź wytworzenie nowych zabiera więcej czasu. Ale to nie znaczy, że jest trudne.

Każdy zjazd na zjeżdżalni ją naoliwia, receptory stają się gotowe na dopaminę. Kiedy zaparkujesz koło restauracji typu fast food, zapach frytek wlatuje do twojego nosa i proces sprzedaży właśnie się zakończył. Tak samo, zjeżdżalnia pornografii jest gotowa na zjazd, 24 godziny, 7 dni w tygodniu. Każdy wyzwalacz odpala twój układ nagrody obietnicą seksu. Tylko że to nie seks. Twój układ nerwowy umacnia te połączenia poprzez kreowanie nowych ścieżek w twoim mózgu. Im więcej pornografii, tym silniejsze te połączenia. Koniec końców musisz być podglądaczem, musisz klikać na kolejne, coraz bardziej szokujące materiały, potrzebujesz porno, żeby spać, i potrzebujesz polowania na idealny klip, żeby się zaspokoić.

Tak jak z każdą inną substancją albo nawykiem, ciało buduje odporność, a narkotyk przestaje całkowicie niwelować głód. Gdy tylko użytkownik zakończy sesję, myśli o kolejnej, a jego wieczny głód zostaje niezaspokojony. A naturalnym rozwinięciem jest zwiększanie wyrzutu dopaminy. Jednak większość użytkowników powstrzymuje się przed tym, z dwóch powodów:

**Pieniądze:** nie stać ich na subskrypcje płatnych stron porno.

**Zdrowie:** Ciało może znieść tylko jakąś ilość obciążenia dopaminą albo orgazmami. Do tego, orgazmy niwelują działanie dopaminy. Muszą, bo tak działa ciało człowieka.

Kiedy mały potwór opuści twoje ciało, okropne poczucie niepewności się kończy. Twoja pewność siebie wraca, wraz z szacunkiem do samego siebie, przekonaniem o kontroli nad swoim życiem, co prowadzi do rozwiązania kolejnych problemów. To jest jeden z najlepszych aspektów uwolnienia się od uzależnienia.

Dlatego szufladkowanie jest mitem i jednym z trików małego potwora, który igra z twoją głową. Te pułapki istnieją po to, by trudnej było ci rzucić – w końcu głodu nie da się zaspokoić – co sprawia, że wielu użytkowników zaczyna palić, pić albo nawet brać silniejsze narkotyki, by wypełnić pustkę.

Ludzie to zwierzęta oceniające, siebie i innych. Oglądanie pornografii z partnerem nie jest satysfakcjonujące, gdyż oboje oceniacie się nawzajem w porównaniu do filmu. Chcesz mieć Brada Pitta w swojej sypialni, nawet jeśli to tylko plakat? Nikt nie może równać się z haremem, gdzie każde doświadczenie jest zagrane, napisane i wyreżyserowane. I do tego dostępne w każdej chwili i w każdym miejscu.