# Unikaj fałszywych zachęt

Wielu użytkowników metody na siłę woli próbuje zwiększać swoją motywację poprzez fałszywe zachęty. Jest wiele przykładów, a typowy wygląda tak, że sprawiasz sobie prezent po miesiącu bez porno. To wydaje się logicznym i sensownym podejściem, ale w rzeczywistości jest zupełnie fałszywe, bo każdy użytkownik wolałby po prostu oglądać dalej niż kupować sobie jakiś prezent co miesiąc. To generuje wątpliwości, bo nie dość, że musisz spędzić trzydzieści dni bez porno, to jeszcze nie jesteś pewien, czy będzie ci się to podobało. Jedyna przyjemność została odebrana! To tylko zwiększa rozmiar poświęcenia, sprawiając, że porno staje się cenniejsze.

Inne przykłady:
- Przestanę, bo to mnie zmusi do lepszego życia socjalnego i da mi więcej prawdziwego seksu.
- Przestanę, bo wtedy magiczna energia pozwoli mi na wydajniejszą pracę i wymarzonego partnera.
- Przestanę, żeby tracić mniej energii i entuzjazmu na porno, żeby być silniejszym.

Te rzeczy to prawda, mogą być efektywne i może nawet dojdziesz do tego, czego pragniesz – ale pomyśl przez moment. Jak już dostaniesz to, czego chcesz, to znowu będziesz się czuł wybrakowany. A jeśli nie osiągniesz swojego celu – będziesz nieszczęśliwy. Koniec końców wpadasz do tej samej pułapki.

Łączenie rzucenia z fałszywą zachętą tylko zwiększa wątpliwości, bo jeśli twoja zachęta się nie spełni, zaczniesz myśleć „*Czy rzucenie rzeczywiście mi pomoże? Skoro rzuciłem i nie mam tego, co chciałem, to czy zastosowałem odpowiednią metodę?*”. Takie myśli prowadzą do odczucia rezygnacji, co kreuje głód.

Innym typowym przykładem są pakty na forach internetowych, te mają taką zaletę, że eliminują pokusę na jakiś czas. Jednak zwykle są nieskuteczne, ponieważ:
1. Zachęta jest fałszywa, dlaczego miałbyś przestać tylko dlatego, że inni tez to robią? To prowadzi tylko do tego, że czujesz ciśnienie i masz wrażenie, że z czegoś rezygnujesz. Dobrze jest, gdy użytkownicy chcą przestać w tym samym czasie – ale nie możesz ich zmusić, nawet jeśli wszyscy tego pragną. Dopóki sami nie będą gotowi, dopóty pakt kreuje większe ciśnienie, co sprawia, że bardziej chce się oglądać. To znowu prowadzi do oglądania w sekrecie, co zwiększa uczucie uzależnienia.
2. Zależność od innych używających metody siły woli kreuje uczucie przechodzenia przez okres pokuty, podczas której czekamy, aż ochota sama przejdzie. Jeśli się poddasz – czujesz porażkę. Kiedy używacie siły woli, zawsze jedna osoba się podda, dając pozostałym wymówkę, żeby też się poddali. To nie moja wina, ja bym wytrzymał, no ale Andrzej się poddał, więc co mi tam. Prawda jest taka, że większość z nich i tak oszukuje.
3. Dzielenie się sukcesem jest odwrotnością uzależnienia. Rzucenie porno to duże osiągnięcie i kiedy robisz to sam, a potem zbierasz pochwały od przyjaciół i ludzi online, to jest duże wsparcie przez pierwsze kilka dni. Jednak kiedy robią to też inni, sukces jest rozproszony, a przez to wsparcie też jest mniejsze.
4. Innym przypadkiem jest obietnice dawane przez guru. Rzucenie da ci szczęście, bo nie będziesz już ze sobą walczył, a twój mózg zacznie myśleć zdrowo i regulować twoje impulsy.
   Ale pamiętaj – to nie sprawi, że wygrasz loterię i nie uczyni z ciebie boga seksu. Dosłownie nikogo poza tobą nie obchodzi to, czy rzucisz porno. Nie jesteś słabeuszem, jeśli używasz pornografii 3 razy dziennie i masz zaburzenia erekcji, ani też nie jesteś silny, jeśli jesteś uzależniony i przestałeś.

Przestań się oszukiwać. Jeśli oferta pracy na 10 miesięcy z wypłatą za 12 albo ryzyko związane z twoją niezdolnością do radzenia sobie ze stresem, albo twoje problemy z erekcją, albo żywot spędzony na mentalnych i fizycznych torturach nie zatrzymała twojego uzależnienia, to kilka fałszywych zachęt też tego nie zrobi, a jedyne co osiągniesz to poczucie, że rezygnujesz z czegoś dobrego. Skup się na drugiej stronie: *Co ja z tego mam? Czy muszę oglądać porno?*

Ciągle patrz na drugą stronę walki i pytaj, co porno ci daje. **ABSOLUTNE NIC**. Po co musisz to robić? **NIE MUSISZ! SAM SIĘ PODKOPUJESZ!** Zakład Pascala: nie masz nic do stracenia, szansę na ogromne zyski (podniecenie, spokój mentalny i szczęście), no i żadnych szans na przegraną.

Dlaczego nie zadeklarujesz rzucenia przyjaciołom i rodzinie? No, na pewno będziesz wtedy dumnym eksużytkownikiem, ale nie szczęśliwym nieużywającym. Może twój partner się wystraszy, bo pomyśli, że to jakiś plan w klimacie new-age, żeby uprawiać więcej seksu. Może wystraszy się, że staniesz się maszyną do rżnięcia, ciężko to wtedy wytłumaczyć, chyba że ona też wie, o co chodzi.

Niestety, szukanie pomocy u innych w rzuceniu napędza tylko małego potwora.
Odsunięcie go z głowy i ignorowanie go ma efekt niemyślenia o nim. Zamiast tego, gdy tylko pojawi się myśl albo zachęta, pomyśl sobie „*Świetnie! Nie jestem już niewolnikiem pornografii. Jestem wolny i szczęśliwy, bo potrafię rozróżnić seks od porno!*” To natychmiast odetnie tlen od myśli i powstrzyma twoje pokusy i głód. Można też spróbować medytacji, która wspomoże depersonalizację myśli.