# Łatwa droga do końca

Ten rozdział zawiera instrukcje, jak łatwo rzucić pornografię. Jeśli będziesz za nimi podążał, zauważysz, że rzucenie może być łatwe i przyjemne! Żeby wyzbyć się pornografii, musisz zrobić tylko te dwie rzeczy.

1. Podejmij decyzję, że już nigdy nie chcesz oglądać pornografii.
2. Nie smuć się, tylko raduj!

Więc pytasz teraz – Po co mi reszta tej książki? Czemu nie mogłeś tego powiedzieć na początku? No więc dlatego, że prędzej czy później zacząłbyś się smucić i zmienił swoją decyzję.
Powiem więcej, pewnie już przechodziłeś wielokrotnie przez ten proces.

Jak już wspominałem, pornografia to subtelna i nikczemna pułapka. Głównym problemem nie jest dopamina – która jest problemem, ale nie tym najważniejszym – jest nim pranie mózgu.
Dlatego musiałem zniszczyć wszystkie mity i iluzje. Poznaj swojego wroga, poznaj jego taktyki, a łatwo go pokonasz. Spędziłem długi czas, cierpiąc na najgorszą depresję, próbując przestać, a kiedy w końcu udało mi się uciec – przestałem z dnia na dzień, bez wpadek. Było mi przyjemnie, nawet kiedy cierpiałem na głód, a potem nigdy nie czułem żadnych potrzeb. Była to jedna z najlepszych decyzji w moim życiu.

Moja ostatnia próba była inna. Jak w przypadku wielu użytkowników długo myślałem o moim problemie. Do tego czasu, po każdej porażce pocieszałem się, że następny raz będzie łatwiejszy. Nigdy nie wpadłem na to, że tak będzie musiało wyglądać cale moje życie, a kiedy już to zrozumiałem – poczułem przerażenie i zacząłem głębszą analizę.

Zamiast odpalać przeglądarkę podświadomie, zacząłem analizować moje uczucia i potwierdzać to, co już wiedziałem. Pornografia to nie przyjemność, pornografia jest obrzydliwa i ohydna. Zacząłem obserwować nieużywających w innych miejscach na świecie albo starszych ludzi, którzy nigdy nie obsługiwali takich stron. Do tego czasu uważałem nieużywających za nudnych, antyspołecznych i dziwnych ludzi. Ale kiedy się do nich zbliżyłem, zrozumiałem, że są oni bardziej zrelaksowani i silniejsi. Wyglądali, jakby radzili sobie ze stresem i problemami oraz lepiej spełniali swoje funkcje społeczne niż uzależnieni. Na pewno mieli więcej energii i 'tego czegoś'.

Zacząłem rozmawiać z eksużytkownikami. Do tego momentu myślałem, że zostali zmuszeni do rezygnacji ze względu na zdrowie, albo religię i że zawsze pragnęli wizyty w swoim haremie online. Niektórzy mówili „*A, raz na jakiś czas coś mnie ugryzie, ale tak rzadko że ignoruję i przechodzi*”, ale większość z nich mówiła: „*Tęsknota? Żartujesz chyba. Moje życie nigdy nie było lepsze!*” Nawet porażki pchały ich do przodu, nie potępiali się, tylko akceptowali bezwarunkowo.

Jak trener, który akceptuje błędy dobrego sportowca. Rozmowy z eksużytkownikami zniszczyły moje przekonanie, że jest we mnie jakaś słabość, bo zrozumiałem, że wszyscy przechodzą przez ten prywatny koszmar.

Powiedziałem sobie „*Setki ludzi rzucają i są szczęśliwi, ja nie musiałem tego robić, zanim zacząłem i pamiętam, że sam musiałem pracować, żeby uzależnić się od tych okropności. Więc po co mam to robić dalej?*” W każdym razie nie bawiłem się dobrze przy pornografii, nienawidziłem tego ohydnego rytuału i nie chciałem spędzić reszty życia w uzależnieniu od tego obrzydlistwa.

Następnie powiedziałem sobie po prostu:

„*Czy ci się to podoba, czy nie, to była twoja ostatnia sesja*”.

I wiedziałem, że od tego momentu nigdy więcej nie będę oglądał porno. Nie oczekiwałem, że będzie to proste, wręcz przeciwnie. Wierzyłem, że zapisałem się właśnie na miesiące ciężkiej depresji i życia cały czas z głodem. Zamiast tego, od początku czułem się doskonale.

Długo trwało, zanim doszedłem do tego, dlaczego to było takie proste i dlaczego nie czułem głodu. Powód jest prosty – głód nie istnieje, to tylko wątpliwości i niepewność, które go tworzą. Piękna prawda jest taka, że łatwo rzucić porno. To tylko niezdecydowanie i płacz utrudniają zabawę. Nawet uzależnieni użytkownicy mogą przeżyć długo bez dostępu. Cierpisz tylko, gdy masz pragnienie, którego nie spełniasz.

Więc kluczem do łatwego procesu jest zatrzymanie tego raz i na zawsze. Nie nadzieja, tylko wiedza, że to koniec, bo taką podjąłeś decyzję. Nigdy w to nie powątpiewaj, wręcz przeciwnie, zawsze się ciesz! Jeśli masz pewność od początku, będzie ci łatwo. Ale jak to zrobić?
Dlatego potrzebna jest reszta tej książki. Mamy kilka ważnych punktów do przemyślenia, zanim zaczniesz:

1. Zrozum, że możesz to osiągnąć. Niczym nie różnisz się od innych, a jedyna osoba, która cię pilnuje to ty sam. Nawet w najśmielszych snach nie myślisz o tym, żeby wyzbywać się męskości.
2. Z niczego nie rezygnujesz. Wręcz przeciwnie, będziesz miał z tego same zyski. Nie tylko będziesz zdrowszy i bogatszy, ale będziesz się lepiej bawił i lepiej znosił trudności.
3. Nie ma czegoś takiego jak jedna wizyta. Pornografia to uzależnienie i reakcja łańcuchowa, a jęcząc o jedną wizytę, będziesz się tylko karał.
4. Zrozum, że porno to nie 'chłopcy będą chłopcami' i nie nawyk, który cię skrzywdzi, ale uzależnienie. Zmierz się z faktem, że niezależnie czy ci się to podoba, czy nie, jesteś chory. Nie wyleczysz się z głową w piasku. Pamiętaj, tak jak każda choroba, nie tylko masz ją na zawsze, ale też będzie z nią coraz gorzej. Najlepiej wyleczyć ją od razu.
5. Oddziel chorobę – uzależnienie – od myślenia o tym, czy jesteś użytkownikiem, czy nie. Wszyscy użytkownicy chcieliby cofnąć się w czasie i nigdy nie zacząć. Ty masz tę możliwość dziś. Nie myśl o rezygnacji.

W momencie, kiedy podejmiesz decyzję, że to była twoja ostatnia wizyta, stajesz się nieużywającym. Użytkownik to ten biedak, który idzie przez życie, niszcząc siebie pornografią.
Nieużywający tego nie robi. Kiedy podejmiesz swoją decyzję, osiągasz swój cel. Ciesz się tym i nie płacz, czekając, aż chemiczne uzależnienie zniknie. Wyjdź i ciesz się życiem! Życie jest wspaniałe, nawet gdy jesteś uzależniony, a każdy dzień będzie coraz lepszy.

Kluczem do sukcesu jest absolutne przekonanie, że nie będziesz używał przez okres odstawienia (maksymalnie trzy tygodnie). Jeśli będziesz myślał w odpowiedni sposób, będzie to dla ciebie niesamowicie proste.

W tej chwili, jeśli otwarłeś swój umysł, tak jak prosiłem na początki, to już zdecydowałeś, że kończysz. Powinieneś być podekscytowany, jak pies, który wyrywa się ze smyczy zjeżdżalni DeltaFosB. Jeśli dopadnie cię poczucie zagłady, pojawi się ono z następujących powodów:
1. Coś nie zacementowało się w twojej głowie. Przeczytaj powyższe 5 punktów jeszcze raz i zapytaj, czy wierzysz, że są prawdą. Jeśli w coś wątpisz – przeczytaj odpowiedni rozdział książki.
2. Boisz się porażki. Nie martw się, czytaj dalej, a ci się uda. Biznes pornografii internetowej to oszustwo na wielką skalę. Inteligentni ludzie dają się złapać, ale tylko głupiec wpada w pułapkę, kiedy zna jej działanie.
3. Ze wszystkim się zgadzasz, ale nadal jesteś nieszczęśliwy. Nie bądź! Otwórz oczy, coś wspaniałego właśnie się dzieje. Zaraz uciekniesz z więzienia, więc pomyśl sobie „*Jak dobrze nie używać!*”

Wszystko, co ci pozostało, to pozostać w tym stanie podczas odstawienia, a w kolejnych rozdziałach omówię rzeczy, które ci w tym pomogą. Po odstawieniu nie będziesz już musiał tak myśleć, to będzie automatyczne i będziesz żałował, tylko że nie zacząłeś wcześniej. Mam jeszcze dwa ostrzeżenia:

-  Odłóż swoje plany, aż skończysz czytać książkę.
-  Okres odstawienia, który trwa trzy tygodnie, był już opisywany wielokrotnie i może prowadzić do nieporozumienia. Po pierwsze, możesz podświadomie myśleć, że czekają cię trzy tygodnie cierpienia. To nie prawda. Po drugie, nie myśl „*Muszę wytrzymać trzy tygodnie, a potem wszystko będzie w porządku*”. Nic magicznego nie wydarzy się po tych trzech tygodniach, nie będziesz się czuł, jakbyś nigdy nie używał, bo wolni ludzie czują się podobnie jak użytkownicy.

Jeśli jesteś nieszczęśliwy, że przestajesz na trzy tygodnie, prawdopodobnie nadal będziesz nieszczęśliwy. Podsumowując – jeśli zaczniesz dziś, myśląc „*Ale wspaniale, nigdy już nie będę oglądał porno*”, po trzech tygodniach pokusy znikną. Ale jeśli pomyślisz „muszę przeżyć trzy tygodnie bez porno”, będziesz spragniony wizyty w haremie.

Pomyśl o tym w ten sposób – twój mózg chce utrzymać status quo, więc wierząc, że rezygnujesz z czegoś dobrego, będziesz się czuł okropnie. Niemożliwym jest zmusić się do wiary w coś, jeśli twój mózg w to nie wierzy. Dlatego trzeba znieść iluzję, że pornografia wnosi coś do twojego życia. W ten sposób wiesz, że nic nie tracisz.

Seksualna dysfunkcja odbywa się w większości w twojej głowie. Pornografia zmienia działanie twojego układu nagrody i sprawia, że zaczynasz wątpić. To wątpienie powoduje dysfunkcje. Kiedy jesteś podniecony w głowie, ale nie między nogami – to jest najgorsze, co może ci się przytrafić. Libido idące w parze z romansem jest eliksirem młodości, który będziesz miał aż do śmierci. Uda ci się, jeśli rzucisz porno, ale nie tylko o to chodzi. To gra o twoją wolność!

