# Odstawienie

Przez maksymalnie trzy tygodnie będzie cię kąsał głód. Ten pochodzi z dwóch osobnych źródeł:

1. Głód dopaminy. Puste, niepewne uczucie, podobne do normalnego głodu, uczucie, że musisz coś zrobić, albo masz na coś ochotę.
2. Psychologiczne wyzwalacze z zewnętrznych źródeł takich jak reklamy, przeglądanie Internetu albo nawet rozmowy telefoniczne.

Niezrozumienie tego rozróżnienia utrudnia osiągnięcie sukcesu metodą na siłę woli i dlatego wiele osób z powrotem wpada w pułapkę. Mimo tego, że głód dopaminy nie powoduje fizycznego bólu, nie lekceważ jego mocy. Mówimy tu o złym samopoczuciu z głodu, jakbyś nie jadł przez cały dzień. Możesz poczuć dyskomfort w brzuchu, ale nie poczujesz żadnego bólu. Mimo to, głód jest potężną siłą i na pewno robimy się drażliwi, kiedy brakuje nam jedzenia. Podobnie jest, kiedy nasze ciało pragnie haju z dopaminy. Różnica polega na tym, że w pierwszym przypadku chcemy jeść, a w drugim pragniemy trucizny. Z odpowiednim podejściem, łatwo przebyć te ukąszenia, które szybko znikają.

Po kilku dniach, z metodą siły woli, potrzeba dopaminy szybko znika. To dopiero drugie źródło – pranie mózgu – sprawia trudność. Użytkownik jest przyzwyczajony do zaspokajania głodu przy pewnych okazjach i w pewnych sytuacjach, co prowadzi do skojarzeń (*dostałem erekcji, więc muszę oglądać porno*, albo *leżę z laptopem w łóżku, więc muszę zacząć sesję, żeby się zadowolić*).
Ten efekt pokazuje ten przykład: masz w starym aucie kierunkowskaz po lewej, a w nowym po prawej. Jeszcze przez kilka tygodni uruchamiasz wycieraczki, kiedy chcesz skręcić.

Rzucenie porno jest podobne, w pierwszych dniach ten mechanizm będzie się nadal uruchamiał. Pomyślisz, że masz ochotę na sesję, więc kontra wobec prania mózgu musi być natychmiastowa i sprawi, że te chęci szybko znikną. W metodzie na siłę woli, z racji tego, że użytkownik myśli, że z czegoś rezygnuje, martwi się tym i chce, żeby pokusy same przeszły. Więc, zamiast usuwać te wyzwalacze, intensyfikuje je. Podobnie, idąc myśleniem 'na guru', użytkownik zaczyna zastanawiać się, kiedy zostanie Bogiem i żąda zaprzestania tych myśli, co prowadzi na drogę porażki.

Typowym wyzwalaczem jest samotność, szczególnie podczas spotkań ze znajomymi. Eksużytkownik używający innych metod rzucenia już jest nieszczęśliwy, bo czuje, że czegoś mu brakuje. Jego znajomi są blisko ze swoimi partnerami i zachowują się intymnie. Użytkownik jest albo singlem, albo nie dostaje wystarczającej uwagi od swojego partnera, więc to przyjemne spotkanie ze znajomymi zaczyna mu się nie podobać. Łatwiej wtedy wejść na zjeżdżalnię niż zabiegać o nowego partnera.

Z racji łączenia prawa do seksu z dobrym samopoczuciem, nadchodzi trzecie uderzenie, a pranie mózgu się wzmacnia. Jeśli się uspokoisz i wytrzymasz wystarczająco długo, w końcu zaakceptujesz swój los i przejdziesz nad nim do porządku dziennego. Ale pranie mózgu jest nadal obecne, więc uruchamia się drugi najbardziej żałosny element bycia eksużytkownikiem. Nawet po kilku latach po rzuceniu, nadal pragniesz kolejnej wizyty w haremie w pewnych chwilach.
Koncentrujesz się na iluzji, która istnieje tylko w twojej głowie i bez sensu się torturujesz.

Nawet z Koniec z Porno trudno oprzeć się wyzwalaczom. Eks-użytkownik traktuje porno jako rodzaj placebo albo cukierka. Myśli sobie „Wiem, że porno nic dla mnie nie znaczy, ale jeśli wyobrażę sobie, że tak jest, to czasem może mi pomóc”. Placebo, mimo że nie pomaga, może mieć silny psychologiczny wpływ na człowieka i leczyć ciężkie symptomy. Pornografia i masturbacja to nie placebo. Dlaczego? Pornografia jest przyczyną symptomów, które niweluje i do tego nigdy nie niweluje ich całkowicie.

Może będzie ci łatwiej zrozumieć ten efekt, jeśli odniesiemy go do kogoś, kto nie używa bądź jest wolny od wielu lat. Weźmy osobę, która właśnie przeżyła bolesne rozstanie. Bardzo często, nawet z dobrymi intencjami pomyśli „*Raz odwiedzę harem, to mnie uspokoi*”. Jeśli to zrobi, wcale się nie uspokoi, bo nie jest uzależniona od dopaminy, więc nie czuje głodu. W najlepszym wypadku otrzyma tylko chwilowe psychologiczne wsparcie.

Po skończonej sesji zaczyna się prawdziwa tragedia. Wtedy zacznie się kąsanie głodu, z którym trzeba się mierzyć, albo wrócić do pornografii, żeby go zaspokoić, zaczynając koło nieszczęścia od nowa. Pornografia dostarczyła tylko chwilowe pocieszenie, takie samo, które można znaleźć, czytając książkę, albo oglądając film, nawet zły. Wielu nieużywających i eksużytkowników uzależnia się od nowa w takich chwilach. Zapamiętaj wyraźnie: nie potrzebujesz dopaminy, a jeśli tak ci się wydaje, to będziesz się tym tylko męczył. Nie ma potrzeby się męczyć.

Orgazmy nie budują dobrych relacji; wręcz przeciwnie, mogą je rujnować. Pamiętaj, to nie jest tak, że ludzie okazujący sobie miłość publicznie, zawsze dobrze się razem bawią. Intymność jest najlepsza w intymnych sytuacjach, kiedy można być szczerym i bez wstydu, a ty nie musisz być orgazmującym ćpunem dopaminy. Jeśli tak się dzieje, jako rezultat naturalnego rozwoju twojego życia, to dobrze, ale ciesz się chwilą oraz życiem bez niej.

Kiedy użytkownicy przestają myśleć o porno jako o czymś przyjemnym, często myślą „*Gdyby tylko było coś takiego jak czyste porno*”. Jest, czyste soft porno, a każdy, kto spróbuje, szybko zrozumie, że to strata czasu. Wbij to sobie do głowy – jedynym powodem, dla którego oglądałeś porno, było zalanie dopaminą. Kiedy przejdzie ci ochota na dopaminę, nie będziesz miał potrzeby odwiedzać swojego haremu.

Niezależnie od tego, czy głód kąsa cię ze względu na brak dopaminy, albo ze względu na wyzwalacze, po prostu to zaakceptuj. Fizyczny ból nie istnieje, a z odpowiednim podejściem, głód nie będzie problemem. Nie martw się odstawieniem, bo to uczucie wcale nie jest złe. To połączenie, z pragnieniem, którego nie można spełnić, które jest problemem. Zamiast płakać, uświadom sobie:

„*Wiem co to jest. To kąsający głód odstawienia. Tak użytkownicy czują się przez cały czas, a to uzależnia. Nie używający nie cierpią na taką przypadłość, to jedno z wielu kłamstw uzależnienia. Bardzo dobrze, że usuwam to zło z mojego mózgu!*”

Innymi słowy, przez najbliższe trzy tygodnie będziesz czuł lekki dyskomfort w swoim ciele, ale przez te trzy tygodnie, a potem przez resztę twojego życia zacznie się dziać coś fantastycznego. Pozbędziesz się okropnej choroby, co da ci tyle zysków, że warto będzie przeżyć ten dyskomforcik, a wręcz się nim cieszyć. To będą chwile przyjemności jak zabawa w zagładzanie małego potwora w twojej głowie. Ty musisz go zagłodzić przez trzy tygodnie, kiedy on próbuje cię zaciągnąć do łóżka.

Czasem będzie próbował zepsuć ci humor. Czasem złapie cię w nieodpowiednim momencie. Dostaniesz link do filmu albo trafisz na coś online, zapomnisz, że rzuciłeś i poczujesz to wybrakowanie. Przygotuj się na te triki i nie zależnie od pokusy pamiętaj, że jest ona tam tylko z powodu potwora, a za każdym razem, gdy się jej oprzesz, to zadajesz mu kolejny cios.

No i nie próbuj zapominać o pornografii. To jest to, co powoduje depresję u stosujących metodę siły woli. Każdego dnia żyją, marząc o tym, że w końcu zapomną. To nie jest jak problemy ze snem – im bardziej o tym myślisz, tym trudniej zasnąć. W każdym razie nie będziesz w stanie o tym zapomnieć, przez pierwsze kilka dni mały potwór będzie ci ciągle o tym przypominał i tego nie unikniesz. Tak długo, jak masz laptopa albo smartfona w pobliżu, tak długo będziesz o tym pamiętał.

Chodzi o to, że nie musisz zapomnieć, to nic złego. Dzieje się coś wspaniałego, nawet jeśli myślisz o tym tysiąc razy dziennie – ciesz się każdą chwilą, przypomnij sobie, jak wspaniale być wolnym. Przypomnij sobie o tym, jak to dobrze się już nie torturować. Jak mówiłem wcześniej, ukąszenia głodu staną się przyjemne, a ty zdziwisz się, jak szybko zapomnisz o pornografii.

No i najważniejsze – nigdy nie wątp w swoją decyzję. Gdy tylko zaczniesz wątpić, to zaczniesz płakać, a wtedy będzie gorzej. Zamiast tego wykorzystaj ten moment płaczu i przeistocz go w siłę. Jeśli przyczyną wątpliwości jest depresja – pamiętaj, że to pornografia ją wywołuje. Jeśli kumpel wyśle ci wideo, z dumą powiedz „*Już tego nie potrzebuję*”. To go zrani, ale kiedy zauważy, że to prawda, to szybko do ciebie dołączy.

**Pamiętaj: jest wiele bardzo dobrych powodów dla których rzucasz pornografię.**
Przypomnij sobie o kosztach i zapytaj, czy na pewno chcesz ryzykować problemy fizyczne, mentalne i życie w niewoli do aż do śmierci. Pamiętaj o małym potworze, który szepcze ci do ucha, szukając wymówek. To tylko momentalne uczucie, a każda chwila zbliża cię do celu.

Niektórzy użytkownicy boją się, że spędzą resztę życia, walcząc z wyzwalaczami. Innymi słowy, wydaje im się, że będą musieli iść przez życie, oszukując się, że nie potrzebują porno, używając psychologii. Tak nie jest, pamiętaj, że optymista widzi szklankę w połowie pełną, a pesymista w połowie pustą. W przypadku pornografii szklanka jest pusta, a użytkownik widzi ją jako pełną. Nie ma żadnych zalet używania pornografii. To użytkownik wmawia sobie, że jest inaczej. Kiedy zaczniesz sobie mówić, że nie chcesz i nie potrzebujesz pornografii, bardzo szybko przestaniesz o tym myśleć i dojrzysz prawdę. To ostatnie co musisz zrobić i upewnij się, że tak będzie.