# Jeszcze raz zerknę

To jest koniec gry dla tych, którzy używają metody na siłę woli. Po trzech, czy czterech dniach, rzucą tylko okiem, żeby się uspokoić. Nie zdają sobie sprawy, jak bardzo niszczą swoją siłę woli.

Dla większości użytkowników, pierwsze spojrzenie na harem online nie było tak przyjemne, jak obcowanie z prawdziwym partnerem. 'Czyste' klipy są rzadkie, co ich napędza.

Myślą sobie „*Dobrze, to nie było takie przyjemne. Nie mam więcej ochoty i nie podobają mi się te szalone rzeczy.*” Prawda jest taka, że jest na odwrót. Pamiętaj dokładnie – przyjemność orgazmu to nie powód, dla którego skończyłeś oglądać. Jeśli użytkownicy oglądaliby porno dla orgazmu, nigdy nie oglądaliby więcej niż jednego klipu. Jedynym powodem, dla którego było ci potrzebne porno, było karmienie małego potwora. Pomyśl sobie, po czterech dniach przerwy, jak przyjemnym będzie to jedno spojrzenie. Twoja świadomość nie zdaje sobie z tego sprawy, ale działka, którą otrzymało twoje ciało, poszła prosto do twojej podświadomości, a całe twoje przygotowanie poszło na marne.
Mały głos z tyłu twojej głowy będzie mówił, mimo logiki, twoje sesje są cenne, a ty pragniesz kolejnej.

Jedno spojrzenie ma dwa skutki:
1. Utrzymuje małego potwora przy życiu
2. I co gorsze, utrzymuje także dużego potwora. Każde spojrzenie sprawi, że następne będzie łatwiejsze

Pornografia to pułapka na myszy bez sera, tylko z trucizną. Metoda siły woli sprawia, że przekonujesz się, żeby nie sięgnąć po ser. Koniec z Porno pokazuje ci, że to trucizna. Nie musisz tego unikać, po prostu tego nie rób.

No i pamiętaj:

*Jedno spojrzenie to sposób, w jaki ludzie się uzależniają.*