# Czy będzie mi trudniej?

Jest nieskończona ilość czynników, które determinują, jak łatwo będzie rzucić każdemu z użytkowników. Każdy ma swój charakter, karierę, sytuację osobistą, moment życia, metabolizm i tak dalej. Niektóre przypadki mogą być trudniejsze niż inne, ale jeśli pozbędziemy się prania mózgu – to wcale tak nie musi być. Przytoczę kilka przykładów:

Bywa tak, że pracownikom medycznym trudniej przestać. Wydawałoby się, że powinno być im łatwiej, bo są świadomi skutków ubocznych. To dostarcza powodów, aby przestać, ale wcale nie sprawia, że jest łatwiej z następnych powodów:

1. Stała świadomość skutków ubocznych powoduje strach, który wywołuje ukłucia głodu.
2. Praca lekarza jest bardzo stresująca i zwykle nie mogą ulżyć sobie w trakcie pracy.
3. Mają dodatkowy stres w postaci poczucia winy – przecież powinni świecić przykładem dla reszty ludzi. To nakłada na nich ciśnienie, które wzmacnia pokusę.

Po długim dniu w pracy, kiedy stres natychmiast rozładowuje się przez pornografię, ta sesja niepoprawnie łączona jest z rozluźnieniem. Z powodu tego połączenia, pornografia zbiera pochwałę za swoją wartość relaksacyjną, co sprawia, że robi się atrakcyjna, kiedy odczuwamy głód.

To dotyczy okazjonalnego użytkownika i sprawdza się w każdej sytuacji, w której przerwa jest wymuszona. Używając siły woli, uzależniony jest nieszczęśliwy, bo brakuje mu czegoś i nie umie zasnąć spokojnie po wieczorze bez sesji. Uczucie straty się nasila. Ale jeśli usuniesz pranie mózgu i płacz nad brakiem porno, to przerwa w pracy i sen stają się miłe, nawet jeśli ciało potrzebuje serotoniny, noradrenaliny i dopaminy.

Inną ciężką sytuacją jest nuda, szczególnie w połączeniu ze stresem. Dotyczy to zwykle studentów bądź samotnych rodziców, którzy mają monotonną i stresującą pracę. Podczas próby z użyciem siły woli, singiel ma dużo czasu, żeby płakać nad swoją stratą, co zwiększa depresję.
Łatwo to ominąć, kiedy masz odpowiednie podejście. Nie przejmuj się tym, że ciągle sobie przypominasz o pornografii. Użyj tych chwil, żeby cieszyć się z tego, że wyzbywasz się tego złego potwora.

Z odpowiednim podejściem, te ukąszenia staną się przyjemne. Pamiętaj, każdy użytkownik, bez względu na płeć, wiek, inteligencję czy zawód może rzucić łatwo i przyjemnie, **jeśli będzie podążał za instrukcjami**.


## Główne przyczyny porażki

Są dwie główne przyczyny porażki. Pierwsza to wpływ zewnętrznych bodźców – reklama, artykuł online, przeglądanie Internetu i tak dalej. Jeden moment słabości, zazdrość wobec ludzi, którzy zachowują się intymnie w miejscu publicznym. O tym już rozmawialiśmy. W takiej chwili musisz sobie przypomnieć, że nie ma czegoś takiego jak jedno spojrzenie. Ciesz się, że uciekłeś z więzienia mentalnej niewoli. Pamiętaj, że użytkownik chce być na twoim miejscu, a ty powinieneś im współczuć, bo tego potrzebują.

Inną przyczyną jest 'zły dzień'. Zanim w ogóle zaczniesz, zrozum, że niezależnie od tego, czy używasz, czy nie, zawsze będziesz miał lepsze i gorsze dni. Deszcz pada i na papieża, i na pedofila. Życie jest trudne i nie możesz mieć wzlotów bez upadków. Problem z metodą na siłę woli polega na tym, że jak tylko masz gorszy dzień, to zaczynasz myśleć o wizycie w haremie, co pogarsza sytuację. Nieużywający lepiej radzi sobie z takimi stresami, nie tylko fizycznie, ale i mentalnie. Jeśli masz zły dzień podczas odstawienia, po prostu się z nim zmierz. Przypomnij sobie, że złe dni istniały, kiedy byłeś uzależniony, inaczej byś nie rzucał. Zamiast płakać, to rozpoznaj problem: „*Ok, dziś nie jest zbyt dobry dzień, ale pornografia go nie poprawi. Jutro będzie lepiej, a ja przynajmniej będę czysty od tego okropnego uzależnienia*”.

Kiedy używasz porno, musisz zablokować swój umysł na jego złe strony. Użytkownik nie ma zamglonego mózgu, użytkownik 'bywa nie w sosie'. Kiedy spotykają cię wyzwania życia codziennego, a ty myślisz o pornografii, to jesteś wesoły i szczęśliwy? Oczywiście, że nie. Jak przestaniesz, to każdy problem nagle wynika z tego, że przestałeś.

Jeśli praca cię stresuje, to myślisz „*To jest moment, w którym odbyłbym sesję*”. To prawda, ale pamiętaj, pornografia nie rozwiązuje problemu, a ty sam się każesz, płacząc za iluzorycznym wsparciem. Stwarzasz niemożliwą sytuację, nieszczęśliwy, bo nie możesz się masturbować, a jak to zrobisz, to będzie jeszcze gorzej.

**Wiesz dobrze, że podjąłeś odpowiednią decyzję, więc po co się karać wątpliwościami?**

No i pamiętaj – jak zawsze, pozytywne nastawienie jest najważniejsze.
