# Zamienniki

Zamiennikiem mogą być magazyny z pornografią, obrazki, diety i tak dalej. **NIE STOSUJ ŻADNYCH Z NICH**. One tylko utrudniają ci zadanie. Jeśli poczujesz głód i zastosujesz zamiennik, twój głód tylko się przedłuży. Jedyne co robisz, to wypełniasz pustkę pornografią.

Jakbyś poddał się porywaczowi albo krzyczącemu dziecku, przedłużając swoje tortury. Niezależnie od wszystkiego, zamienniki nie poskromią twojego głodu. Pragniesz aminokwasów w mózgu, więc będziesz tylko więcej myślał o pornografii. Pamiętaj:

1. pornografia nie ma zamienników
2. nie potrzebujesz pornografii. Pornografia to nie jedzenie, tylko trucizna. Kiedy odczuwasz głód, pamiętaj o tym, że tylko użytkownicy go odczuwają. Zrozum, że to kolejny aspekt uzależnienia. Mały potwór umiera z głodu.
3. Pornografia tworzy pustkę; nie wypełnia jej. Im szybciej nauczysz mózg, że nie musi oglądać, tym szybciej się uwolnisz. Unikaj wszystkiego, co przypomina pornografię – magazyny dla mężczyzn, filmy, romanse i reklamy. Nie masz się odsuwać od romansu i seksu, tylko od pornografii. Zawsze łatwo rozróżnić czego unikać a czego nie. Mała część ludzi próbujących rzucić na dietach porno i softach, rzeczywiście rzuca (a przynajmniej tak im się wydaje). Jednak oni rzucają mimo swojego uzależnienia, a nie z jego powodu. Niestety wiele osób nadal poleca te metody.

Nic zaskakującego – jeśli nie rozumiesz pułapki pornografii, dieta albo zamienniki brzmią logicznie. Wynika to z przekonania, że rzucanie porno to walka z:

- nawykiem
- strasznym uczuciem głodu

Kiedy masz dwóch przeciwników do pokonania, ma sens walczyć tylko z jednym naraz.
Więc teoria mówi, że najpierw ograniczasz spożycie, na przykład do jednej sesji w tygodniu, a gdy wyzbędziesz się nawyku, powoli spożywasz coraz mniej, walcząc z każdym wrogiem z osobna.

To brzmi logicznie, ale jest nie prawdą. Pornografia to nie nawyk, to uzależnienie od dopaminy, a fizyczne efekty odstawienia są praktycznie nieodczuwalne. Najlepszym rozwiązaniem jest jak najszybsze zabicie obu potworów w twoim ciele i umyśle. Zamienniki po prostu przedłużają życie małego potwora, a to intensyfikuje pranie mózgu. Koniec z Porno uczy natychmiastowego rzucenia, pozbywając się prania mózgu jeszcze przed twoją ostatnią sesją. Mały potwór niedługo umrze, a jego ostatnie wdechy nie będą większym problemem, niż kiedy używałeś.

Zastanów się – jak można leczyć uzależnienie od substancji, sugerując używanie substancji? Jest wiele historii ludzi, którzy rzucili hardkorową pornografię, ale nadal są uzależnieni od 'soft porno', nadal kontrolowani przez małego potwora. Niech ci się nie wydaje, że soft porno nie jest obrzydliwe. Każdy zamiennik ma dokładnie takie samo działanie jak normalne porno.
Niektórzy zaczynają zajadać problem, a mimo tego, że twoja potrzeba odbycia sesji jest nieodróżnialna od głodu, to jedzenie cię nie usatysfakcjonuje. Prawda jest taka, że zapychanie się jedzeniem prowokuje oglądanie pornografii. Jak tłumaczyłem wcześniej, diety pornograficzne i 'soft' porno postawią cię z powrotem w środku walki, a kiedy pokusa osiągnie apogeum, sięgniesz po swój harem.

Największym problemem z zamiennikami jest przedłużanie prania mózgu. Czy potrzebujesz zamiennika dla grypy, gdy wyzdrowiejesz? Oczywiście, że nie. Jeśli potrzebujesz zamiennika, przyznajesz, że czegoś się wyrzekasz. Depresja wynikająca z metody na siłę woli bierze się właśnie z poświęcenia i rezygnacji. A ty tylko zastępujesz jeden problem drugim. Nie ma przyjemności w zapychaniu się jedzeniem, paleniu papierosów i piciu alkoholu. Przytyjesz, będziesz nieszczęśliwy i prędzej czy później wrócisz do haremu.

Okazjonalny użytkownik ma problem z odrzuceniem wiary w to, że pozbywa się swojej nagrody, tak jak ci, którzy nie mają dostępu do Internetu podczas podróży, albo podczas imprezy rodzinnej. Niektórzy powiedzą „*Nie wiem, jak się zrelaksować bez pornografii*”. To potwierdza to, co mówię. Taki użytkownik robi sobie przerwę, nie dlatego że jej potrzebuje, albo chce, tylko dlatego, że uzależniony – bo nimi właśnie są – desperacko potrzebuje zaspokoić głód.

Pamiętaj, sesje z pornografią to nigdy nie jest prawdziwa nagroda. To jest noszenie za ciasnych butów, żeby poczuć ulgę po ich ściągnięciu. Więc kiedy czujesz potrzebę wynagrodzenia – niech to będzie twoją nagrodą. Podczas pracy włóż za małe buty albo majtki i nie ściągaj ich, aż skończysz pracę, a potem przeżyj ten wspaniały moment, kiedy się ich pozbędziesz. Pewnie wydaje ci się to głupie i masz rację. Może trudno to sobie wyobrazić, ale dokładnie to robią użytkownicy złapani w sidła. Trudno sobie też wyobrazić, że niedługo nie będziesz potrzebował tej 'nagrody' i że już za chwilę będziesz czuł współczucie wobec przyjaciół, którzy nadal są w potrzasku i nie rozumieją problemu.

Natomiast jeśli nadal będziesz się oszukiwał, że wizyta w haremie to nagroda albo że potrzebujesz zamiennika, to poczujesz wybrakowanie i nieszczęście. Prawdopodobnie znowu wpadniesz w pułapkę. Jeśli potrzebujesz relaksu, tak bardzo, jak nauczyciele, lekarze i inni pracownicy, niedługo będziesz się cieszył tym relaksem jeszcze bardziej, bo nie będziesz musiał się uzależniać. Głód dopaminy niedługo zniknie. Niech to będzie twoją myślą przez następnych kilka dni i ciesz się z tego, że wyrzucasz ze swojego ciała niewolnictwo i zależność.