# Mam unikać pokus?

Do tej pory porady były bezpośrednie i prosiłem, żebyś stosował je jako instrukcję. Każda z nich jest praktyczna i potwierdzona tysiącami przypadków. Ale w przypadku pytania o unikanie pokus tak nie jest. Każdy użytkownik musi zdecydować sam. Mam dwie pomocne informacje. To strach przed przyszłym głodem sprawia, że nadal używasz, a ten strach składa się z dwóch faz.

**Faza pierwsza – jak żyć bez porno?**

Ten strach pojawia się, gdy użytkownik jest samotny albo ma niezbyt zainteresowanego partnera. Strach nie jest spowodowany głodem, ale psychologicznym strachem uzależnienia, życia bez seksu i orgazmów. Ten jest najwyższy, kiedy już prawie rzucisz, kiedy twój głód jest najmniejszy. To strach przed nieznanym, coś jak strach ludzi, którzy uczą się skoków do wody.

Trampolina jest 2 metry nad ziemią, ale wydaje się jakby była 10. Woda jest głęboka na 10 metrów, ale wydaje się, jakby miała tylko 2. Wyskok wymaga odwagi, bo jesteś przekonany, że rozwalisz sobie głowę. To jest najgorszy moment, ale jeśli zmusisz się do wybicia, cała reszta jest bardzo prosta. To tłumaczy, dlaczego wielu silnych mentalnie użytkowników nigdy nie próbuje przestać, albo przerywają próbę po kilku dniach. Niektórzy na dietach porno, gdy postanowią rzucić, eskalują do coraz mocniejszych klipów, jakby nigdy nie zdecydowali przestać. Ta decyzja wytwarza panikę, co jest stresujące i każe im wracać do haremu. A teraz, kiedy nie mają do niego dostępu – czują się wybrakowani, co dalej ich stresuje.

Ten wyzwalacz jest bardzo silny i odpalasz przeglądarkę. Nie martw się, panika jest tylko w twojej głowie. To strach przed zależnością. Prawda jest taka, że tej zależności nie ma, nawet jeśli jesteś uzależniony. Nie panikuj, tylko skacz.

**Faza druga – strach na zawsze**

Druga faza trwa znacznie dłużej i wynika ze strachu przed przyszłymi sytuacjami, w których nie będziesz odczuwał szczęścia, albo nie poradzisz sobie z problemem bez pornografii. Nie martw się, jeśli wyskoczysz, to będzie dokładnie na odwrót. Unikanie pokus dzieli się na dwie kategorie:

1. „*Zacznę używać diety pornograficznej, raz na cztery dni. Będę bardziej pewny siebie, wiedząc, że mogę w trudniejszej chwili skorzystać z pomocy. A jeśli mi się nie uda – dodam kolejne dni do mojego następnego cyklu*”.

    Ilość nieudanych prób z użyciem tej metody jest dużo większa niż w przypadku ludzi, którzy rezygnują zupełnie. To wynika z tego, że kiedy masz jakiś problem podczas odstawienia, jest dużo łatwiej odpalić przeglądarkę, bo masz wymówkę. Poniżasz się, łamiąc swoje własne zasady, więc pokusa cię wchłonie. A jeślibyś po prostu zignorował głód, to już by go nie było. Główną przyczyną porażek w tych przypadkach, jest brak całkowitego przekonania do rzucenia. Pamiętaj, żeby rzucić, musisz być
   - pewny
   - i cieszyć się z tego, że nie używasz!
   
   Biorąc to pod uwagę – na co ci sesja? Jeśli nadal musisz odwiedzać harem, przeczytaj książkę jeszcze raz. Coś się nie wchłonęło. Czas zabić wielkiego potwora prania mózgu raz a porządnie.

2. „*Powinienem unikać stresu i wydarzeń socjalnych podczas odstawienia?*”.

   Jeśli chodzi o stresujące sytuacje to tak. Nie ma sensu się obciążać. Jeśli chodzi o chodzenie do barów albo klubów – wręcz przeciwnie. Wyjdź i baw się dobrze, bo nie potrzebujesz seksu, ani orgazmu, nawet jeśli jesteś uzależniony. Wyjdź z domu i ciesz się faktem, że nie musisz uprawiać seksu, żeby być szczęśliwym. Szybko zrozumiesz, że życie jest dużo lepsze bez tego ciśnienia. Pomyśl, jak super będzie, kiedy mały potwór umrze i zabierze te natrętne myśli ze sobą.