# Objawienie

Zwykle doświadczamy go po mniej więcej trzech tygodniach od rzucenia. Niebo wydaje się jaśniejsze i to jest ten moment, kiedy pranie mózgu się kończy. To ten moment, kiedy przestajesz mówić sobie, że nie potrzebujesz porno i rozumiesz, że łańcuch został zerwany, że możesz żyć dalej bez uzależnienia. Od tego momentu zaczynasz współczuć tym którzy oglądają.

Ci, którzy używają metody na siłę woli, normalnie nie doświadczają tego uczucia, bo mimo że się cieszą z tego, że nie używają, nadal idą przez życie, myśląc, że z czegoś zrezygnowali. Im bardziej uzależniony byłeś, tym lepiej smakuje zwycięstwo. W życiu jest wiele przyjemności i często nie da się ich odtworzyć, nie da się poczuć tych doświadczeń ponownie. Z rzuceniem pornografii jest inaczej, bo kiedy masz doła, przypominasz sobie, jak świetnie jest nie być uzależnionym od tego okropnego narkotyku. Wielu twierdzi, że to była najlepsza decyzja w ich życiu. I w większości przypadków to objawienie przychodzi szybciej, nawet po kilku dniach.

Ja objawienia dostałem jeszcze przed ostatnią wizytą w haremie. Jestem przekonany, że wielu z was, zanim skończyliście czytać, już mówi „*Nie musisz więcej gadać. Wszystko rozumiem i wiem, że nie potrzebuję już porno*”. Bazując na tym, co mówią ludzie, tak jest często. Jeśli zrozumiesz instrukcje i psychologię, powinieneś to zrozumieć od razu.

Kiedy mówię, że fizyczne symptomy odstawienia kończą się po mniej więcej pięciu dniach i trzeba około trzech tygodni, by całkowicie się uwolnić, to takie wytyczne mogą prowokować niezrozumienie. Po pierwsze – użytkownik myśli o tym, że będzie cierpiał gdzieś między pięcioma dniami a trzema tygodniami. Po drugie, eksużytkownik myśli „*Jeśli przeżyję ten okres, to potem czeka mnie duża poprawa*”.

Jednak może być tak, że te pięć dni, albo trzy tygodnie będą bardzo przyjemne, a potem wydarzy się coś okropnego, co nie ma nic wspólnego z uzależnieniem, spowodowanego przez jakąś zewnętrzną siłę. Wtedy eksużytkownik, zamiast poprawy, doświadcza depresji. To może złamać pewność siebie. W ten sam sposób, bez instrukcji, eksużytkownik może spędzić całe życie, czekając na coś, co się nie wydarzy. Tak jest z ludźmi, którzy używają metody na siłę woli.

Ludzie często pytają o znaczenie pięciu dni i trzech tygodni. Czy te okresy są wyssane z palca? Nie są to definitywne wyliczenia, ale odzwierciedlają informacje podawane przez eksużytkowników. Po pięciu dniach uzależniony przestaje myśleć o uzależnieniu przez większość czasu. Większość z nich doznaje objawienia mniej więcej w tym momencie, zwykle w stresujących sytuacjach, z którymi zawsze radzili sobie z pomocą haremu. Nagle zdasz sobie sprawę, że nie tylko dobrze się bawisz i świetnie sobie radzisz, ale że nawet nie myślałeś o pornografii. Od tego momentu droga jest prosta. Dokładnie wtedy zaczyna się twoja wolność.

Doświadczenia moje i innych używających metody siły woli mówią, że po mniej więcej trzech tygodniach najczęściej występuje potknięcie. Dzieje się tak, bo wtedy na ogół tracisz ochotę oglądania porno. Musisz sobie to udowodnić, więc odpalasz przeglądarkę i odwiedzasz harem.

Czujesz się dziwnie, co potwierdza, że problemu już nie ma. Ale robiąc to, znowu naoliwiasz swoją zjeżdżalnię DeltaFosB, bo dostajesz nową falę dopaminy, której twoje ciało pragnie od trzech tygodni. Jak tylko skończysz oglądać, dopamina się traci, a głos w twojej głowie mówi „*Nic z tego, nie rzuciłeś, dawaj jeszcze raz*”.

Nie wracasz od razu, bo nie chcesz się znowu uzależnić, więc odczekujesz trochę, żeby się poczuć bezpiecznie. Przy następnej pokusie myślisz „*No już nie jestem uzależniony, więc nic się nie stanie jak znowu spróbuję*”. Wpadasz prosto w pułapkę. Nie czekaj na objawienie, tylko zrozum, że jak zamkniesz przeglądarkę to koniec. Odłączyłeś małego potwora od tlenu. Nie ma takiej siły, która zabroni ci być wolnym, chyba że będziesz płakał i czekał na objawienie. Idź cieszyć się życiem i radź sobie z nim od samego początku. Objawienie przyjdzie samo.