# Ostatnia wizyta

Jeśli już ustaliłeś swój moment, czas na twoją ostatnią wizytę w haremie. Zanim to zrobisz, upewnij się, że

1. Jesteś pewien sukcesu,
2. Czujesz ekscytację i szczęście, że kończysz, a nie zagładę i smutek.

Jeśli masz jakiekolwiek wątpliwości – przeczytaj książkę jeszcze raz.
Pamiętaj, nigdy nie zdecydowałeś się wpaść w tę pułapkę, która jest tak zaprojektowana, abyś nigdy z niej nie wyszedł. Żeby z niej uciec, musisz być pozytywny i mieć świadomość, że to będzie twoja ostatnia wizyta.

Pamiętaj, czytasz tę książkę tylko dlatego, że chcesz uciec. Więc podejmij tę decyzję teraz, przyrzekając sobie, że jak tylko zamkniesz prywatne okno przeglądarki, niezależnie od tego, czy będzie łatwo, czy trudno, nigdy już nie odwiedzisz swojego haremu. Może się martwisz, że już to postanawiałeś w przeszłości i nigdy nie wyszło albo że będziesz musiał przejść przez jakąś traumę.
Nie bój się, najgorsze co może się zdarzyć to porażka, więc nie masz nic do stracenia, a wiele do zyskania.
Przestań w ogóle myśleć o porażce, bo prawda jest taka, że rzucenie jest niesamowicie proste, a cały proces jest przyjemny. Tym razem korzystasz z pomocy Koniec z Porno! Wystarczą ci te dwie wytyczne:

1. Przyrzeknij to sobie i bądź poważny

2. Pooglądaj obrazki i klipy na swojej ulubionej stronie ze świadomością, jak desperacko ci ludzie próbują amplifikować szok, nowinki i bodźce swoich dóbr i zadaj sobie pytanie – gdzie w tym przyjemność?

3. Kiedy w końcu zamkniesz przeglądarkę, nie myśl „*Nigdy nie mogę już oglądać porno*” ani „*Nie mogę sobie pozwolić na kolejną wizytę*”, myśl raczej z poczuciem ulgi i wolności: „*Czy to nie jest piękne? Jestem już wolny i nieuzależniony od pornografii! Nie muszę już nigdy odwiedzać tych obrzydliwych stron!*”

4. Uważaj, bo przez kilka dni w twoim brzuchu będzie siedział mały pornograficzny sabotażysta. Możesz sobie zdawać sprawę z potrzeby odbycia sesji. O małym potworze mówiliśmy jako o fizycznej potrzebie dopaminy. Mówiąc dokładniej, to nie jest do końca prawda, ale trzeba zrozumieć dlaczego. Z racji tego, że umiera on trzy tygodnie, eksużytkownicy myślą, że mały potwór będzie pragnął po ostatniej wizycie, więc będą musieli używać siły woli, żeby zgasić pragnienie. To nie prawda – ciało nie pragnie dopaminy z pornografii, tylko mózg.

Jeśli poczujesz, że masz ochotę spojrzeć przez następne kilka dni, twój mózg ma prosty wybór. Może zinterpretować to uczucie takim, jakim ono jest – niepewna pustka, która rozpoczyna się wraz z odwiedzeniem strony z pornografią, i napędzana każdą kolejną wizytą, co wywoła w tobie ulgę i szczęście, **HURA NIE JESTEM JUŻ UŻYTKOWNIKIEM!**

Albo może zacząć mieć ochotę na pornografię i cierpienie do końca życia. Pomyśl przez moment, nie byłoby to strasznie głupie? Mówić *nie chcę już oglądać pornografii*, a potem do końca życia twierdzić *chciałbym sobie pooglądać*? Tak robią ci, którzy rzucają przez siłę woli, więc nic dziwnego, że są tacy nieszczęśliwi. Idą przez życie tęskniąc za czymś, czego pragną nie mieć. Nic dziwnego, że tak wielu się poddaje, a ci, którzy odnieśli sukces, tak naprawdę nie są wolni.

> „*Wytwórz sobie taki obraz w głowie, bo może ci się on przydać przy pokonywaniu bodźców z zewnątrz. Zobacz siebie, siedzącego cicho, kiedy twój telefon dzwoni, ty ignorujesz alarm i nawet nie drgniesz. Mimo tego, że jesteś świadomy dzwonka, on już ci nie przeszkadza, on tobą nie rządzi. Zapamiętaj, że zewnętrzny sygnał niema na ciebie żadnego wpływu, nie ma mocy poruszenia ciebie. Kiedyś byłeś poddany i odpowiadałeś, ze względu na swój nawyk. Możesz, jeśli chcesz, wytworzyć nowy nawyk niereagowania.*
> 
> *Zwróć też uwagę, że twój brak odpowiedzi to nie wysiłek, opór ani walka. To nie robienie niczego – relaks. Po prostu go olej, ignoruj i nie przejmuj się. Dzwoniący telefon to analogia do każdego zewnętrznego bodźca, któremu się poddajesz, a teraz postanawiasz przestać się poddawać*”.
>
> ---  Maxwell Maltz, „*The New Psycho Cybernetics*”, Rozdział 12

Tylko wątpliwości i oczekiwanie sprawiają, że tak trudno odstawić, więc **nigdy nie żałuj swojej decyzji**. Bo wiesz, że była poprawna. Jeśli masz jakieś wątpliwości, stawiasz się w sytuacji bez wyjścia. Nieszczęśliwy, bo nie możesz odpalić przeglądarki. Bez znaczenia, jaką strategię przyjąłeś, co chcesz osiągnąć, rzucając porno? Nieoglądanie? Nie! Wielu ludzi tak myśli i potem do końca życia czegoś im brakuje.

Jaka jest różnica między użytkownikiem a nieużywającym? Nieużywający nie mają potrzeby oglądania porno, nie czują głodu i nie muszą walczyć ze sobą, żeby tego nie robić. To właśnie chcesz osiągnąć, a to jest bardzo proste i w zasięgu ręki. Nie musisz czekać, aż głód przejdzie, żeby przestać używać. Kiedy wyłączysz swoją ostatnią sesję, to jest ten moment, kiedy stajesz się nieużywającym. I już jesteś szczęśliwy.

I takim pozostaniesz, jeśli:

1. Nie będziesz wątpił w swoją decyzję

2.  Nie będziesz czekał, aż zostaniesz nieużywającym. Jeśli tak zrobisz, to będziesz czekał na nic, kreując strach

3. Nie będziesz próbował zapomnieć o pornografii albo czekać na moment oświecenia, co kreuje strach

4.  Nie będziesz używał zamienników,

5. Zrozumiesz, że użytkownicy wymagają współczucia, a nie zazdrości.

Niezależnie czy masz dobry, czy zły dzień, nie zmieniaj swojego życia, bo rzuciłeś. Jeśli tak zrobisz, to rezygnujesz z czegoś, kiedy nie musisz tego robić. Pamiętaj, nie rezygnujesz z życia.

Niczego nie straciłeś. Wręcz przeciwnie, wyleczyłeś się z okropnej choroby i uciekłeś z przerażającego więzienia. I w trakcie, kiedy twoje zdrowie fizyczne i psychiczne się poprawia, wzloty będą wyższe, a upadki niższe, niż kiedy byłeś użytkownikiem. Gdy tylko pomyślisz o pornografii, pomyśl sobie:

**HURA! PRZESTAŁEM UŻYWAĆ!**

## Ostatnie ostrzeżenie

Każdy użytkownik, który mógłby nigdy nie zacząć, skorzystałby z tej oferty. Dziesiątki tysięcy ludzi rzuciło nałóg, tylko po to, żeby po kilku latach uzależnić się od nowa. Wierzę, że ta książka pomoże ci odnaleźć drogę do prostego rzucenia pornografii. Ale ostrzegam – łatwo przyszło, łatwo poszło. Nie wpadnij w tę pułapkę!

Nie ważne na jak długo przestaniesz albo jak pewien jesteś swojej decyzji i tego, że nie masz już problemu, przyjmij zasadę, że już nigdy nie będziesz oglądał pornografii, bez względu na przyczynę. Oprzyj się aluzjom w mediach i pamiętaj, jak oni grają 'otwartych', kiedy wnoszą pornografię do mainstreamu. Nieświadomi faktu, że pornografia internetowa i masturbacja niszczą związki i dobre samopoczucie u większości mężczyzn i u niektórych kobiet.

Pamiętaj, że pierwsza wizyta i spojrzenie nic dla ciebie nie wniesie. Nie będzie symptomów odstawienia i będziesz się czuł okropnie. Ale w twojej głowie znowu pojawi się przyjemność zalania dopaminą, a głos z tyłu głowy będzie ci podpowiadał następną sesję. Wtedy masz opcję – albo być nieszczęśliwym przez moment, albo znowu przypiąć się do tego okropnego łańcucha.