# Informacje zwrotne

Wojnę toczę nie z użytkownikami, ale z producentami porno i robię to dla czystej przyjemności. Za każdym razem, gdy słyszę historię użytkownika, który uciekł z pułapki, czuję się niesamowicie dobrze. Niestety, często odczuwam też frustrację, wywołaną przez dwie kategorie użytkowników. Mimo ostrzeżeń podanych w poprzednim rozdziale ciągle zaskakuje mnie, ile ludzi z łatwością przestaje, a potem znowu się uzależnia i nie może przestać.

Jakbym znalazł kogoś w bagnie, zanurzonego po szyję. Pomagam im wyjść, oni są wdzięczni, a potem sześć miesięcy później znowu wskakują do bagna. Użytkownicy, którym łatwo przestać, łatwo też zacząć od nowa, a to jest problem. Dlatego, jak już się wydostaniesz, BŁAGAM, NIE POPEŁNIAJ TYCH SAMYCH BŁĘDÓW. Tym ludziom wydaje się, że są nadal uzależnieni i że brakuje im dopaminy. Prawda jest taka – gdy łatwo przestać, tracisz strach przed pornografią. Myślisz sobie wtedy „*Mogę sobie sprawić jedną sesję, a nawet jak się uzależnię, to będzie mi łatwo przestać*”.

Obawiam się, że to tak nie działa. Łatwo jest rzucić porno, ale nie da się kontrolować uzależnienia. Najważniejszym jest nie używać pornografii w ogóle.

Inną kategorią ludzi, którzy mnie frustrują, są ci, którzy boją się przestać, a nawet jak spróbują, to sprawia im to ogromne problemy. Zgłaszają następujące trudności:

**Strach przed porażką**

:    Nie ma nic złego w porażce, ale żeby nawet nie spróbować – to głupota. Spójrz na to w ten sposób, przed niczym się nie chowasz. Najgorsze co może się wydarzyć to porażka, więc skończysz w tym samym miejscu, w którym jesteś teraz. Pomyśl, jak świetnie będzie, gdy ci się uda. Jeśli nie spróbujesz, porażka jest gwarantowana.

**Strach przed bólem i nieszczęściem**

:    Przestań się zamartwiać i po prostu pomyśl: co takiego strasznego się stanie, kiedy przestaniesz oglądać porno? Absolutnie nic. Straszne rzeczy staną się, jeśli będziesz nadal oglądał. Przeczytaj jeszcze raz o zakładzie Pascala. W każdym przypadku panikę powoduje dopamina, a ten problem niedługo zniknie. Największym plusem jest fakt, że niedługo pozbędziesz się tej przypadłości. Przestaniesz odczuwać strach. Czy naprawdę myślisz, że użytkownicy są gotowi na zaburzenia erekcji, słabe wyniki w łóżku i iluzoryczną przyjemność z pornografii? Jeśli zaczniesz panikować, oddychaj głęboko. A jeśli jesteś z innymi ludźmi, którzy ściągają cię w dół – odejdź na chwilę i schowaj się w pustym pomieszczeniu.

:   Jeśli masz ochotę płakać, to się nie wstydź. Płacz to naturalny sposób rozładowania napięcia. Płacz zawsze prowadzi do lepszego samopoczucia. Jedna z okropnych rzeczy, które wmawiamy młodym facetom, to fakt, że nie mogą płakać. Czasem walczą ze łzami i zgrzytają zębami. Uczymy się nie okazywać emocji, ale nie powinniśmy ich zamykać w środku. Krzycz i wkurz się. Kopnij w coś. Pomyśl o swoim problemie, jak o walce bokserskiej, której nie możesz przegrać. Nikt nie powstrzyma czasu, a z każdą minutą mały potwór jest bliżej śmierci. Ciesz się nieuniknionym zwycięstwem.

**Niestosowanie instrukcji**

:    Niektórzy z użytkowników twierdzą, że Koniec z Porno nie działa. A potem opisują, jak nie tylko ignorują jedną z wytycznych, a wręcz wszystkie. Żeby rozjaśnić, rozpisałem je na końcu tego rozdziału.

**Niezrozumienie instrukcji**

:   Główne problemy dzielą się na:

    *Nie umiem przestać myśleć o porno.*

    :   Oczywiście że nie umiesz, a jeśli będziesz próbował, to wykreujesz w sobie strach, co prowadzi do nieszczęścia. To jest jak gdy próbujesz zasnąć – im bardziej próbujesz tym jest trudnej. Nie ma znaczenia czy myślisz o pornografii 90% czasu, to sposób w jaki myślisz jest ważny. Jeśli w twojej głowie pojawia się *Kocham oglądać porno!* Albo *Kiedy w końcu się uwolnię?* to będziesz nieszczęśliwy. Jeśli pomyślisz (HURA! Jestem wolny!* To czeka cię tylko szczęście.

    *Kiedy umrze potwór pornografii?*
    
    :   Zalanie dopaminą szybko się kończy, ale niemożliwym jest zbadać, kiedy skończy się twój głód po odstawieniu tej substancji. To puste, niepewne uczucie jest dokładnie takie samo jak zwykły głód, depresja albo stres. Pornografia tylko je intensyfikuje. Dlatego użytkownicy używający metody na siłę woli zawsze zastanawiają się czy już rzucili, nawet jeśli ciało przestaje czuć odstawienie dopaminy. Jeśli czujesz normalny głód, albo stres, mózg podpowiada im, że to jest dobry powód, żeby odbyć sesję. Chodzi o to, że nie musisz czekać aż głód przejdzie, bo jest on tak delikatny, że prawie go nie czujesz, odbierasz tylko lekki sygnał 'chcenia'. Kiedy wychodzisz od dentysty, nie czekasz aż przestanie boleć cię szczęka, tylko robisz dalej swoje. Nawet jeśli czujesz ból, to i tak jesteś szczęśliwy.

    :   Nie czekaj aż symptomy odstawienia przejdą, bo wtedy kreujesz wątpliwości i zaczynasz się zastanawiać „*Ile to jeszcze będzie trwało? Czy to już to, przecież nie czuję żadnej zmiany?*” Strach to głód, więc czekanie aż życie będzie lepsze po rzuceniu jest wątpliwością. Głodu nie da się odczuć o ile się go boisz, a zmiany neurologiczne są tak powolne, że gdy będziesz ich szukał, nic nie znajdziesz, więc zaczniesz wątpić.

    *Mój moment objawienia jeszcze nie nadszedł.*
    
    :   Jeśli będziesz na niego wyczekiwał, to znowu wpędzasz się w strach. Przestałem kiedyś używać na trzy tygodnie metodą na siłę woli. Rozmawiałem z przyjacielem, który mnie zapytał, jak sobie radzę. „*No, przeżyłem trzy tygodnie.*” On dopytał „*co masz na myśli, że przeżyłeś?*” A ja na to: „*Trzy tygodnie bez pornografii.*” On odpowiedział: „*No i co teraz? Będziesz tak przeżywał do końca dnia? Na co czekasz, już gotowe. Nie jesteś użytkownikiem.*”

    :   Pomyślałem sobie: Ma rację skurczybyk, na co czekam? Niestety ze względu na brak zrozumienia pułapki, szybko wpadłem znowu, ale zapamiętałem rozmowę. Przestajesz używać, gdy zamkniesz przeglądarkę. Najważniejsze to się cieszyć tym faktem.

    *Ciągle mam ochotę na pornosy.*
    
    :   No więc jesteś debilem. Jak możesz twierdzić, że chcesz rzucić, a potem mówić że chcesz pornografii? To sprzeczność. Skoro chcesz pornosów, to chcesz używać. Nie używający nie odwiedzają tych okropnych stron. Wiesz kim chcesz być, więc przestań się biczować.

    *Wypadłem z życia.*

    :   Dlaczego? Wystarczy ze przestaniesz się zabijać i zaczniesz cieszyć się życiem. Nie musisz przestawać żyć. To tylko mały problem przez kilka dni. Twoje ciało odczuje delikatny dyskomfort wywołany brakiem dopaminy. Pamiętaj: na pewno nie jest gorzej niż było. Na to cierpiałeś przez całe życie, za każdym razem, gdy spałeś, byłeś na zakupach, w kościele albo w bibliotece. Nie przeszkadzało ci, gdy używałeś, a jeśli nie przestaniesz teraz – to będziesz cierpiał do końca życia. Pornografia i orgazm nie są specjalnymi okazjami, one ci je zabierają. Nawet jeśli twoje ciało pragnie tej dopaminy, jedzenie i wydarzenia społeczne są wspaniałe. Życie jest wspaniałe, idź na imprezę, nawet jak tańczą tam gołe baby. Pamiętaj, tobie niczego nie brakuje, to one mają problem. Każda z nich chciałaby być na twoim miejscu, gdyby tylko wiedziały gdzie jesteś. Ciesz się, gdy jesteś w centrum uwagi. Rzucenie pornografii to świetny temat do rozmów, mówienie o przyjemności, której inni nie doświadczają. Twoi przyjaciele i znajomi zobaczą, jak zmieniłeś się z nieśmiałej i zmęczonej osoby w szczęśliwą i wesołą. Życie będzie ci się podobało od samego początku i nie ma sensu zazdrościć podrywaczom, bo to oni powinni zazdrościć tobie.
    
    *Jestem nieszczęśliwy i poirytowany.*

    :   Bo nie rozumiesz instrukcji. Zrozum której. Niektórzy wierzą i rozumieją wszystko, a nadal zaczynają od poczucia zagłady, tak jakby działo się coś okropnego. Nie tylko robisz to na co masz ochotę, ale też to co każdy inny użytkownik chce zrobić. Każda metoda rzucenia, prowadzi do pewnego podejścia, więc każda myśl o pornografii musi spotkać się z pewnym siebie **HURA! JESTEM WOLNY!** I skoro to jest twój cel, to po co czekać? Zacznij z tym podejściem i nigdy go nie trać, nie masz wyboru.

    *Miałem dobry tydzień/miesiąc/pół roku, ale znowu wpadłem.*

    :   Pamiętaj, to strach jest głodem. Poddanie się głodowi, powoduje strach, co karmi małego potwora i przekonuje użytkownika, że nie ma drogi wyjścia z uzależnienia. W rzeczywistości pranie mózgu się nie zmieniło, ale dopamina leci już kiedy o tym myślisz. To jest krok do przodu, ale nadal nie słuchasz instrukcji. Zrozum której z poniższych i ciesz się wolnością.

## Lista kontrolna

Jeśli zapamiętasz te instrukcje, nigdy nie poniesiesz porażki:

1. Przyrzeknij sobie, że nigdy, przenigdy nie wejdziesz do swojego haremu online, ani nie będziesz oglądał obrazków, ani grafik, ani niczego co zawiera nadnaturalne bodźce i trzymaj się swojego przyrzeczenia.

2. Zapamiętaj: z niczego nie rezygnujesz. To nie znaczy, że będzie ci lepiej poza cyklem PMO ani że w PMO jest jakaś przyjemność, mimo braku racjonalnego wytłumaczenia skąd ona się bierze. To znaczy, że w PMO nie ma ani przyjemności, ani podpory. To tylko iluzje, jak walenie głową w mur, żeby poczuć ulgę, gdy nie walisz.

3. Nie ma kogoś na zawsze uzależnionego od PMO. Jesteś jednym z setek milionów użytkowników, którzy wpadli w pułapkę. I jak miliony innych, którzy myśleli, że nie uciekną – ty też uciekłeś.

4. Za każdym razem, gdy spróbujesz przeciwstawić wady i zalety oglądania pornografii, dojdziesz do konkluzji, że trzeba natychmiast przestać. Nic tego nie zmieni. Zawsze tak było i zawsze tak będzie. Jak już podjąłeś słuszną decyzję, to nie torturuj się, wątpiąc w nią. Zakład Pascala idealnie odnosi się do cyklu PMO, nic nie tracisz, dużo zyskujesz i unikasz strat.

5. Nie próbuj nie myśleć o porno i nie martw się, że myślisz. Jak tylko myśl pojawi się w twojej głowie, czy dziś, czy jutro, czy za rok, pomyśl **HURA! NIE JESTEM UZALEŻNIONY!**

6. Nigdy nie używaj zamienników. Nie testuj się, trzymając laptopa w łóżku. Nie unikaj filmów i magazynów. Nie zmieniaj swojego stylu życia w żaden sposób, tylko dlatego, że przestałeś. Jeśli będziesz podążał za instrukcjami, szybko doświadczysz momentu objawienia, ale:

7. nie czekaj na ten moment. Po prostu żyj dalej, baw się dobrze i radź sobie z problemami. A już za nie długo oświecenie przyjdzie samo.
