# Pomagaj innym!

Użytkownicy internetowej pornografii panikują, bo odczuwają to, jak pornografia jest odbierana społecznie przez kobiety i mężczyzn. Jej uzależniająca natura coraz częściej jest badana i coraz częściej zwraca się uwagę na rozróżnienie między tradycyjną pornografią a internetową pornografią. Łatwy i bezproblemowy dostęp jest alarmujący, nawet dla samych użytkowników Odczuwają oni, że ich wolność wypowiedzi i myśli jest zagrożona przez wiele czynników. Dziki zachód Internetu jest praktycznie niemożliwy do kontrolowania i nie da się nałożyć limitu wieku na nadnaturalne bodźce. Niestety, to się szybko nie skończy, ale tysiące ludzi przestaje korzystać, a co raz więcej uzależnionych świadomych jest zagrożeń uzależnienia od pornografii. Za każdym razem, gdy jedna osoba ucieknie, pozostali czują się jeszcze gorzej.

Każdy użytkownik instynktownie wie, że oglądanie pornografii jest śmieszne i wyniszczające, a spędzanie czasu przed dwuwymiarowymi pikselami, zalewanie głowy dopaminą i tworzenie ścieżek w mózgu jest gwarancją dysfunkcji seksualnych. Jeśli nadal nie wydaje ci się to śmieszne, to spróbuj pogadać z magazynem pornograficznym w centrum miasta i zapytaj, jaka jest różnica. Jest tylko jedna. Nie znajdziesz tam ani bliskości, ani intymności. Jeśli nie musisz kupować alkoholu i papierosów, za każdym razem, gdy wejdziesz do sklepu, na pewno możesz przestać odwiedzać swój harem. Nikt nie ma racjonalnych powodów, żeby oglądać porno, ale nie wydaje się to śmieszne, kiedy inni też to robią.

Użytkownicy ciągle kłamią o swoim nawyku, nie tylko badaczom, ale też bliskim i samym sobie. Muszą to robić, bo pranie mózgów jest konieczne, żeby nie stracić szacunku do samego siebie. Muszą usprawiedliwiać swój nawyk nie tylko sobie, ale również innym. Ciągle chwalą iluzję pornografii.

Kiedy użytkownik przestanie, używając metody na siłę woli, ciągle będzie czuł wybrakowanie i zacznie jęczeć. A to utwierdza innych w przekonaniu, że warto nadal używać. Jeśli eksużytkownik przestanie oglądać i się z tego cieszy, bo nie musi iść przez życie, wkopując się w dziurę, to nie musi się tłumaczyć. Pamiętaj, to strach trzyma głowę uzależnionego w piasku i wywołuje wątpliwości, gdy przerwie. Pomóż im, odsuwając ten strach. Powiedz im jakie to wspaniałe, nie żyć w więzieniu, jakie to świetne uczucie wstawać rano wyspanym i zdrowym, zamiast zmęczonym i wściekłym, jak to wspaniałe uwolnić się z niewoli, żeby cieszyć się życiem i zabić te czarne cienie. A najlepiej – zmuś ich do przeczytania tej książki.

Bardzo ważne jest, aby nie wyśmiewać użytkownika, który ma żonę, że niszczy swój związek albo że zdradza czy robi coś niemoralnego. Ludziom często się wydaje, że tacy są eksużytkownicy. Może jest w tym ziarno prawdy, ale wynika ono z metody na siłę woli. To dlatego, że taki eksużytkownik, mimo że czysty, to nadal wierzy w pranie mózgu i uważa, że z czegoś zrezygnował. Ci ludzie są wrażliwi, a ich naturalnym mechanizmem obrony jest atak na użytkownika.

To może podbudować jego ego, ale nie pomaga użytkownikowi. W ten sposób jest postawiony pod ścianą, gdzie czuje się jeszcze gorzej, a jego uzależnienie się zwiększa. Nawet jeśli konsensus medyczny się zmienia i rozumiemy już zagrożenia pornografii, to rzucenie wcale nie staje się łatwiejsze. Wręcz przeciwnie, jest trudnej. Większość użytkowników myśli, że musi przestać ze względu na zdrowie – to nie prawda.

Oczywiście, to jest ogromna część problemu, bo użytkownicy sabotują swoją męskość przez długie lata, ale to nie robi różnicy. Użytkownicy rzucają, bo społeczeństwo zaczyna dostrzegać pornografię jako to, czym jest: czyli uzależnieniem od narkotyku. Nasze podejście powoli się zmienia – wiele osób będzie zadawało pytania, jeśli siedzisz na laptopie w środku nocy.

Całkowity ban na pornografię w niektórych krajach albo brak dostępu do Internetu są klasycznymi przykładami dylematu podróżującego użytkownika. Zwykle zakładają, że ta sytuacja pomoże im ograniczyć spożycie. A rezultat jest taki, że zamiast jednego albo dwóch dni bez przyjemności, nie korzystają przez tydzień. Podczas tego wymuszonego okresu abstynencji, nie tylko będą się czuli wybrakowani, czekając na swoją nagrodę, ich ciała też będą pragnąć. A następna wizyta w haremie jest wyjątkowo przyjemna.

Wymuszona abstynencja wcale nie zmniejsza spożycia, ponieważ użytkownik pozwala sobie na więcej przy pierwszej możliwości. To wszystko tylko umacnia przekonanie, że pornografia jest cenna i potrzebna im do życia. Ten proces ma najgorszy wpływ na młodych w okresie dojrzewania. Pozwalamy tym porywaczom wolności ekspresji, producentom porno by celowali prosto w nastolatków, żeby uzależnić ich od wczesnych lat. Wtedy, w tym najbardziej stresującym momencie ich życia, kiedy im wydaje się, że pornografia jest dobra i potrzebna, my odbieramy im narkotyk, by uchronić ich przed krzywdą, którą sobie sprawiają.

Wielu nie daje rady, co wpędza ich (nie z ich winy) w poczucie winy do końca życia.

Wielu udaje się rzucić i myślą „*Ok, dostosuję się, a jak to się skończy – to będę już zdrowy*”. Potem przychodzi ból i strach przed poszukiwaniem pracy i innymi problemami, co prowadzi do haju wywołanego pierwszą pracą. Ból i strach się skończyły i zaczyna się poczucie bezpieczeństwa i stabilności, więc stare przyzwyczajenia wracają. Część prania mózgu ciągle zostaje i zanim zniknie zapach nowego laptopa służbowego, użytkownik stoi już na progu swojego haremu. Radość z tej okazji przyćmiewa poczucie obrzydzenia, a oni nie mają intencji uzależnić się od nowa, ale przecież jedno spojrzenie nie zaszkodzi... za późno! Już jesteś na łańcuchu.

Głód od czasu do czasu się pojawi i nawet jeśli nie uzależnisz się od razu, to depresja po wyrzucie dopaminy na pewno cię dopadnie. Śmieszne, że uzależnieni od heroiny to w świetle prawa przestępcy, a my chcemy im pomagać. Przyjmijmy to samo podejście do biednego użytkownika porno. Oni tego nie robią, bo chcą, oni to robią, bo myślą, że muszą. W przeciwieństwie do uzależnionych od heroiny często cierpią długimi latami. Zawsze mówimy, że szybka śmierć jest lepsza od powolnej, więc nie zazdrość użytkownikowi. **On zasługuje na twoje współczucie**.