# Porady dla nieużywających

## Pomóż przyjacielowi przeczytać tę książkę!

Po pierwsze, przestudiuj to, co tu napisałem i spróbuj stanąć w butach uzależnionego. Nie zmuszaj go do czytania, wmawiając, że rujnuje sobie życie, igrając z ogniem. On już o tym wie, lepiej niż ty. Użytkownik nie ogląda porno dla przyjemności albo bo ma na to ochotę, on tylko tak mówi innym, żeby nie stracić szacunku u siebie i innych. Robi to, bo jest zależny od pornografii i bo wydaje mu się, że ma z tego relaks, pewność siebie i odwagę. Jest też przekonany o tym, że życie bez 'seksu' nie będzie przyjemne. Jeśli będziesz zmuszał użytkownika do rzucenia, to sprawisz, że poczuje się jak w potrzasku, przez co będzie potrzebował swojego haremu jeszcze bardziej. To zamieni go w 'ukrytego' użytkownika, a pornografia stanie się dla niego zakazanym owocem.

Zamiast tego, skup się na drugiej stronie medalu. Pokaż im przykład innych eksużytkowników (na blogach, forach, YourBrainOnPorn albo społeczności NoFap). Niech oni mu opowiedzą, jak sami myśleli, że są uzależnieni do końca życia i jak dobrze im bez tego uzależnienia. Kiedy tylko uwierzy, że może przestać, ich umysł się otworzy. Potem zacznij tłumaczyć iluzję kreowaną przez głód. Nie tylko zalewanie dopaminą nie przynosi pozytywnych skutków, ten proces niszczy pewność siebie i prowadzi do zmęczenia i poirytowania.

Wtedy sam zechce przeczytać tę książkę, oczekując stron wypełnionymi historiami o dysfunkcjach seksualnych i problemach z erekcją. Wytłumacz, że to podejście jest inne, a odniesienia do chorób są tylko minimalne.

Nie pozwól temu umrzeć w ciemności. Mów przyjaciołom, ale nie bądź dziwakiem. Jeśli będziesz próbował 'wygrać' debatę, tylko ich wyalienujesz, zwiększając ich strach.

## Czy powinienem mówić bliskiej mi osobie?

Czy powinienem się przyznawać do mojego uzależnienia bliskiej osobie? Twoją intencją jest pomoc w rzuceniu. Mamy tutaj kilka problemów.

Jeśli już używałeś metody na siłę woli bez skutku i już poinformowałeś swojego partnera, powiedz im o nowym podejściu i pozwól, żeby sami rozumieli, o co chodzi, czytając książkę. W ten sposób będą w stanie pomóc i motywować podczas odstawienia i będą twoją ostoją, gdy mały potwór zaatakuje.

Jeśli dopiero teraz zdałeś sobie sprawę z istnienia pułapki pornografii i nie próbowałeś wcześniej rzucać, najpierw użyj Końca z Porno sam. Jak tłumaczyłem wcześniej będzie to bardzo przyjemne doświadczenie. Jeśli pojawią się trudności – powiedz im o tym i poproś o pomoc. Otwórz się przed swoim partnerem, a to wzmocni twój związek.

Ale jeśli ucieczka ci się podoba i nie masz z nią problemu, nie ma powodu się tym dzielić. Jeśli nie sprawiało to kłopotów w przeszłości – pozwól temu umrzeć. Ale przygotuj się na pytania – twój partner będzie się zastanawiał, dlaczego wyglądasz i czujesz się lepiej, oraz skąd nagle masz tyle ochoty na zabawę!

## Mój partner rzuca pornografię

Pornografia jest wypaczonym niszczycielem związków i chociaż można rzucić z dnia na dzień, leczenie zajmuje trochę czasu. Wielu uzależnionych ze względu na strach i nieracjonalne przekonania wynikające z uzależnienia, wyżywa się na swoich bliskich. Taka osoba może ci zacząć wmawiać, że coś z tobą nie w porządku, mogą się pojawić kłamstwa i manipulacje. To nie dotyczy wszystkich użytkowników, ale im dalej w las, tym częściej można się tego spodziewać. Więc te zachowania może i wynikają z uzależnienia od pornografii, ale i tak warto o nich wiedzieć i jeśli je rozpoznasz – pomyśl o wizycie u terapeuty specjalizującego się w uzależnieniach seksualnych.

Jeśli twój partner jest w okresie odstawienia, zakładaj, że cierpi, nawet jeśli tego nie widać.
Nie próbuj tego minimalizować, powtarzając, że łatwo jest rzucić i że dadzą radę sami. Zamiast tego powtarzaj, że czujesz dumę, że lepiej wyglądają, jak przyjemniej z nimi jest i jak wasz związek się poprawił. Jest to szczególnie ważne, podczas gdy użytkownik próbuje przestać, bo euforia z próby będzie wzmacniana pozytywnym wsparciem, co jest bardzo pomocne. O takich rzeczach łatwo zapomnieć, więc chwal dalej.

Jeśli nie mówią o pornografii, może ci się wydawać, że sami zapomnieli i nie chcą, żeby ktoś o tym przypominał. Zwykle przy metodzie na siłę woli jest odwrotnie, bo eksużytkownik nie myśli o niczym innym. Więc nie bój się o tym rozmawiać i ciągle chwal. W razie czego eksużytkownik powie ci, że nie chce o tym rozmawiać.

Spróbuj ułatwić im życie podczas okresu odstawienia i pomyśl, co możesz zrobić, żeby umilić im dzień. To może być też trudny okres dla nie uzależnionych. Jeśli jeden członek grupy jest poirytowany, może to na tobie wyładować a to prowadzi do nieszczęścia. Więc spodziewaj się tego, jeśli eks-użytkownik jest poirytowany, to może wycelować w ciebie. Nie denerwuj się, bo to czas w którym potrzebują twojego wybaczenia i sympatii. Jeśli sam czujesz się zły, spróbuj tego nie okazywać.

Jednym z trików uzależnionych jest wkurzanie się o byle co, żeby usłyszeć „*Nie mogę już patrzeć jak tak się zachowujesz, do cholery jasnej ulżyj sobie!*” W ten sposób uzależniony nie jest winny i się nie poddaje, ktoś mu kazał się złamać. Jeśli ktoś się tak zachowuje, w żaden sposób nie zachęcaj go do porażki. Zamiast tego powiedz „*Jeśli pornografia czyni z ciebie taką osobę, to dzięki bogu, że niedługo będziesz wolny. Bardzo się cieszę, że postanowiłeś przestać*”.

Pamiętaj, są dwie osoby, które leczą się na tej drodze wyjścia z uzależnienia. Kiedy twój partner rzuca pornografię, ty też musisz mieć swoje wsparcie i granice. Ten proces nie trwa jednego dnia, wymaga zaufania, komunikacji i wzajemnego wsparcia. Pisanie dziennika, rozwijanie pasji i terapia na pewno pomogą.

## Nawrót choroby

Niech ten rozdział służy jako przestroga dla tych, którzy uciekają z pułapki. Osobiście nigdy nie miałem nawrotu, ale użyję doświadczeń z wywiadów z członkami społeczności oraz narzędzi z terapii behawioralnej żeby zilustrować problem.

Po pierwsze, nazywanie tego nawrotem nie jest produktywne. Co się wydarzyło, to potknięcie, które nakarmiło małego potwora, co znowu uruchamia wielkiego potwora prania mózgu. Użytkownicy po potknięciu zaczynają myśleć nieracjonalnie:

- „*Nigdy nie będę wolny*" - **Dramatyzowanie**
- „*Muszę być produktywnym, uczyć się i ćwiczyć każdego dnia*" - tzw. **'zmuszonanizm'**
- „*Dziś odbyłem sesję, więc po co mam czytać te książki i fora... moim celem było się nie masturbować, ale proszę bardzo, przegrałem i mam nawrót*" - **Niska odporność na stres**
- „*Moi przyjaciele, forumowicze i inni dali radę wytrzymać x dni, a ja nie mogę, więc to koniec, nie ma dla mnie szans. Wczoraj wszystko było ok, ale dziś już nie jest... spadam w odmęty*" - **Porównywanie się do innych**
- „*Nie powinienem mieć myśli o seksie*" - Społeczeństwo, rodzice albo sam użytkownik zainstalował w sobie **sztywne zasady** co do relacji seksualnych. Zapytaj się, czy biczowanie pomaga ci osiągnąć cel, a jeśli tak – to podoba ci się to?

Każdy użytkownik ma wyprany mózg na nieskończenie wiele sposobów. Znasz samego siebie lepiej niż ktokolwiek inny, więc wiesz, że porażka wynika z nieużywania instrukcji. Widziałeś wartość w pornografii, ale dlaczego?

Często zapominamy, że wyleczenie z prania mózgu zajmuje więcej czasu. To nie oznacza, że jest trudno. Jednak każdy biznes używa seksu do sprzedaży, a aktywna walka z praniem mózgu jest świadomym procesem (przynajmniej na początku), więc może zająć ci chwilę, zanim w pełni uklepiesz sobie wiedzę z tej książki. Więc zalecam przeczytać ją kilka razy (możesz nawet przeskoczyć prosto do rozdziałów, z którymi masz problem), a pranie mózgu zniknie w mgnieniu oka.

Częstym doświadczeniem religijnych użytkowników podczas ucieczki z pułapki jest chęć cierpienia jako forma zapłaty za grzechy. Rzucenie jest takie proste, więc czują się winni z tego powodu. Po co się sabotować i utrudniać sobie życie? Mały potwór jest szczwany.

Odsuń się od niego, on jest w twojej głowie od dawna, wciśnięty tam przez biznes pornograficzny. Wyobraź sobie łobuza, który wkurza się na placu zabaw. Co mu powiesz? Jeśli się poddasz, to tylko go upewnisz, że dobrze postępuje. Niektórzy po rzuceniu nadal poddają się łobuzowi, zwiększając pranie mózgu, ale ich idea pułapki się nie zmienia. Wstań z kolan, zrozum co poszło nie tak i ciesz się wolnością!

Nie jesteś swoim pragnieniem. Medytacja to praktyka wyłapywania myśli i można z niej wiele wynieść. Polecam medytację, która jest zgodna ze wszystkimi wierzeniami. Możesz walczyć sam ze sobą albo z małym potworem. Musisz kochać siebie i proces bezwarunkowo.

No i usuń z głowy porażkę. Oto sekcja książki „*Medytacje Uzależnionego od Porno*" autorstwa Gulliaco (link do niej znajduje się na końcu książki):

> Z racji tego, że pornografia nic nie wnosi do twojego życia i tylko cię rani, więc jest więc szaleństwem dalej z niej korzystać. Jakbyś pił wybielacz, proszę bardzo:
>
> **Na drodze do nie picia wybielacza**
>
> Dzień dobry! Tutaj kampania Stop Wybielaczowi! Organizujemy wyzwanie, w którym uczestnicy (Wybielaczonauci) przestają pić wybielacz na pewien czas. Nie ważne czy twoim celem jest wypróbowanie swoich sił, czy podjęcie pełnego wyzwania na miesiąc, czy może picie wybielacza sprawia problemy w twoim życiu i chcesz przestać na dłużej, znajdziesz tutaj wspierającą społeczność i dużo informacji o spożywaniu wybielacza.
>
> - „*Czasem pozwalam sobie na wypicie szklaneczki czy dwóch. Wiem, że ta 'jedna kropla' jest kłamstwem, ale nie wydaje mi się, żeby to szkodziło. Przecież to nie anuluje tych wszystkich dni, kiedy nie piłem.*"
> - „*Nie mam problemu z piciem wybielacza, mogę przestać kiedy chcę. Ale czasem, kiedy idę ulicą i widzę, jak ktoś pije wodę, wiecie, ze szklanki, to sobie wyobrażam że w tej szklance jest wybielacz. No i wtedy nachodzi mnie ochota, więc chwilę dyskutuję sam ze sobą czy to zrobić czy nie, no i wieczorem jednak się decyduję na strzelenie jednego głębszego.*"
> - „*Słuchaj, czasem jak jestem sam w kuchni to widzę te wszystkie szklanki, więc trochę się nakręcam otwierając butelkę z wybielaczem, wącham sobie go i.... znowu muszę zaczynać od początku. Czuję się zdesperowany, bo chcę przestać, ale nie wiem czy to w ogóle możliwe.*"
> - „*Nie da się przestać pić wybielacza. Co mogę powiedzieć, nie pozbędę się ust. Jak mam przestać, skoro zawsze będę miał gardło, które przypomina mi o połykaniu świeżego wybielacza?*"
> - „*Stary, szło mi tak dobrze, 19 dni bez ani jednej kropli. Ale trzeba się uczyć na błędach! Wiem czego muszę unikać. Nie mogę patrzeć na detergenty w supermarkecie. Spróbuję wytrzymać miesiąc! Czas na reset, trzymajcie kciuki!*"

> Jeśli czujesz ciśnienie – wyluzuj stary! Pamiętaj, co mówi książka:
>
> „*Wybielacz ciężko rzucić, bo boimy się braku przyjemności i podpory, którą nam daje. Strachu, że pewne sytuacje nigdy nie będą takie same. Innymi słowy, to pranie mózgu wmawia nam, że kupowanie wybielacza i picie go jest konieczne dla każdego człowieka. Co więcej, to wbudowane przekonanie, że czegoś sobie odmawiamy, wytwarzając pustkę. Zapamiętaj dokładnie: Wybielacz nie wypełnia pustki, on ją tworzy!*"
>
> I ja mówię:
> „*Wyobraź sobie, że musisz oglądać, jak ktoś pije wybielacz przez pięć minut. Przypomnij sobie jedną z marek albo zapachów które tak kochałeś. Może jakiś dźwięk albo inny detal. Wybielacz jest przed tobą, a ty nie możesz zamknąć oczu ani się odwrócić, bo ten wybielacz jest w twojej głowie, wspomnienie nagrane w tobie.*
>
> *Czujesz głód? Czy czujesz cokolwiek na języku albo zmianę w tym jak oddychasz? Jakie emocje pamiętasz? Zidentyfikuj je, bo wybielacz chce je zaburzyć, pomieszać i zwrócić twoją uwagę, żeby cię złapać.*"
>
> Pisząc to, nie próbuję odrzucić tego co czujesz, a już na pewno nie mówię „haha ja mądry ty głupi", ale chcę ci pokazać perspektywę, żebyś zrozumiał jak niesamowicie łatwo walczyć z tym uzależnieniem. Oglądanie pornografii to nie włącznik do światła, gdzie możesz powiedzieć „o, jest sytuacja X, to mogę oglądać." Fantazje! Kłamstwa! Jak często pozwalasz sobie na szklaneczkę wybielacza? Nigdy? Czemu? Bo to okropne, dlatego! Jak masz uciec od uzależnienia, jeśli nie rozumiesz, że PMO jest dla ciebie okropne?

## Co z masturbacją i orgazmem?

Ludzie walą konia od wieków. To pornografia jest problemem.

Nadal można się uzależnić od MO (masturbacji i orgazmu), z tych samych powodów co przy pornografii, na przykład z potrzeby orgazmu, złego podejścia, eskalacji, zmuszania się do seksu i z czystej potrzeby szukania przyjemności.

Jest bardzo prawdopodobne, że pornografia i masturbacja są głęboko złączone w twojej głowie. Dla wielu użytkowników nawrót następuje po masturbacji do fantazji wywołanych myśleniem o pornografii. W miarę jak twój mózg się prostuje, to zauważysz, że to pranie mózgu powoli odchodzi, ale lepiej zrobić sobie przerwę od masturbacji i orgazmu na jakiś czas.

Powinieneś też szukać normalnego seksu, żeby przyśpieszyć problem leczenia.

To nie jest instrukcja, ale zastanów się. Raportowane zalety z retencji nasienia są bardzo duże. Skupienie, energia, brak zamglenia w głowie i większa pewność siebie, plus wiele innych. Z osobistego doświadczenia powiem, że różnica jest i zależy od tego w co tą energię obrócisz.

To spekulacje, nie potwierdzone wiedzą naukową, ale zalety wynikają z:

- Po orgazmie, twój mózg wytwarza prolaktynę, która ogranicza produkcję dopaminy
- Powstrzymywanie zalewów dopaminy, pozwala na większe wchłanianie podczas życia codziennego.
- Nasienie jest wchłaniane do krwiobiegu po około 78 dniach i jest bardzo pożywne.
- Przeistoczenie energii seksualnej w inne produktywne nawyki dodaje im skuteczności

Możesz nawet chcieć seksu bez orgazmu, co jak już wspominałem jest wspaniałym doświadczeniem. Możesz to ćwiczyć rozwijając swój mięsień Kegla. Najlepiej ćwiczyć go zatrzymując mocz w trakcie mikcji. Rozłączenie tantrycznych i rozrodczych aspektów seksu jest jednym z wielu bonusów ucieczki z cyklu PMO (moje partnerki też były zadowolone!).

## Odchylenia od porad

Ta sekcja jest nowa i piszę ją niechętnie; ale muszę o tym wspomnieć.

Niektórzy czytający Koniec z Porno nie mają ochoty oglądać pornografii tak bardzo, że nie chcą użyć po raz ostatni. To jest ok, ale nie zapominaj o sile, jaką niesie z sobą ostatnia sesja.
Świadome przeglądanie i zrozumienie cyklu PMO może być bardzo skuteczne. Osobiście było dla mnie bardzo pomocne i cieszyłem się, myjąc ręce po skończeniu. Czułem ulgę, bo wiedziałem, że to ostatni raz. No ale, ty możesz być inny.

Jeśli jesteś już wolny i usuwałeś tylko pranie mózgu, to nie ma potrzeby karmić małego potwora, bo tylko będzie cię męczył. Po prostu ciesz się wolnością!

## Pomóż zakończyć ten skandal

Darmowa internetowa pornografia jest jednym z zagrożeń wolnego społeczeństwa, które opiera się na wolności osobistej obywateli. Podstawa cywilizacji – i przyczyna zaawansowania ludzkości – to nasza umiejętność komunikacji, przekazywania wiedzy i doświadczeń, nie tylko między sobą, ale również dla kolejnych pokoleń. Nawet zwierzęta ostrzegają swoje młode przed niebezpieczeństwami.

Producenci porno nie działają w dobre wierze, myśląc, że pomagają ludzkości, szczególnie teraz, gdy uzależnienie od pornografii jest tak szeroko badane. Może kiedyś ludzie wierzyli, że pornografia pomaga w uczeniu intymności, ale teraz wiadomo, że to nie prawda. Żaden z portali nie próbuje uczyć. Jedyne co chowają to ekstremalnie szokujące materiały, które użytkownicy wrzucali na te strony.

Hipokryzja jest ogromna, bo społeczeństwo walczy z napastowaniem i uprzedmiotowianiem ludzkiego ciała. W porównaniu do internetowego porno te problemy to pryszcze. Co roku, coraz więcej ludzi jest uzależnionych. Spędzają oni godziny z iluzorycznymi pikselowymi ludźmi, niszcząc swoje zdrowie, męskość, energię i czas. Pornografia to zabójca związków, tysiące żyć jest dewastowane każdego roku przez to uzależnienie. Pornografia nie jest reklamowana, bo nie musi być reklamowana, to nasze biologiczne potrzeby nas do niej prowadzą. A pod drzwiami do haremu leżą próbki jak u dilera. Dziś portale pornograficzne zachęcają do wrzucania własnych treści.

Cwane strony pornograficzne wstawiają ostrzeżenia 18+, żeby odstraszyć dzieci, a niektóre z nich nie robią nawet tego. Internetowa pornografia ma wpływ na wszystkich, niezależnie od wieku. Ich podejście jest następujące: „*Ostrzegliśmy cię przed niebezpieczeństwem, więc to twój wybór*”. Czy w jakikolwiek sposób potwierdzają wiek? Nie, bo to zniechęca potencjalnych klientów. A jeśli tylko wystąpią jakieś prawne ograniczenia – wystarczy zmienić kraj działalności. A może zapłacą komuś, żeby opisał, jak prohibicja prowadzi do nielegalnego handlu i mafii?
Oczywiście z pominięciem pytania, dlaczego uchylenie prohibicji wcale nie zmniejszyło ofiar alkoholu i jak to się stało, że policja nie powstrzymała działań mafii.

Możemy zmienić podejście, edukując młodzież. Skoro potrafią nie palić i nie pić, to mogą ignorować też pornografię. Widzimy już zmiany w społeczeństwie, które prowadzą do 'No Nut November' albo memów o 'spermiarzach', które wchodzą do mainstreamu. Użytkownik nie ma wyboru tak jak uzależniony od heroiny. Użytkownicy nie postanawiają się uzależnić, są zwabieni do pułapki. Jeśli byłaby taka możliwość, jedynymi uzależnionymi jutro zostaliby młodzi, którzy dopiero zaczynają, bo wierzą, że mogą w każdej chwili przestać.

I o co chodzi z tymi podwójnymi standardami? Dlaczego odbieramy uzależnionych od heroiny jako przestępców, jednak po zarejestrowaniu jako uzależniony, ci ludzie mają dostęp do metadonu i leczenia, żeby łatwiej im było rzucić? Spróbuj się zarejestrować jako uzależniony od pornografii. Idź do doktora, a usłyszysz „spróbuj ograniczyć, rób to rzadziej” , a przecież wiemy, że to nie działa. W najlepszym wypadku dostaniesz leki, żebyś nie miał 'depresji'. Najgorsza porada jaką można usłyszeć to – znajdź sobie partnera. Kurwa serio? Czy oni nie rozumieją, że pornografia jest lepsza od prawdziwego seksu i korzysta się z niej za plecami partnera?

Straszenie konsekwencjami też nie działa i utrudnia rzucanie. Jedynym efektem jest zastraszenie użytkownika, co sprawia, że czuje on potrzebę oglądania więcej. Na nastolatków tez to nie działa – oni wiedzą, że pornografia niszczy ich libido, ale myślą, że raz na jakiś czas nie zaszkodzi. A z racji tego, że uzależnienie jest tak powszechne, prędzej czy później nastolatek – albo ze względu na presję z zewnątrz, albo na ciekawość – i tak spróbuje. A później wiadomo co się stanie – eskalujące klipy prowadzą do uzależnienia.

Więc dlaczego pozwalamy, by to nadal trwało? Dlaczego władze państwowe nie organizują kampanii? Dlaczego nie mówi się, że pornografia jest narkotykiem i trucizną, że nie relaksuje i nie pomaga na pewność siebie, ale niszczy nerwy. Że wystarczy raz spojrzeć, żeby się uzależnić? Dlaczego nie mogą wprowadzić wymogu sprawdzenia wieku poprzez dowód osobisty?
Mindgeek, firma matka wielu korporacji pornograficznych, próbuje oszukiwać stosując swoje własne metody weryfikacji wieku – nie pozwól na to! W książce H.G. Wellsa, Wehikuł czasu, przeczytamy o mężczyźnie, który wpada do rzeki. Jego towarzysze siedzą biernie na brzegu jak bydło, ignorując jego desperackie krzyki. Nieludzkie i odrzucające, tak samo jak obojętność społeczeństwa na zagrożenia pornografii.

Czuć powiew zmian. Kula śniegu zaczyna toczyć się w dół, a ja mam nadzieję, że ta książka pomoże zmienić ją w lawinę. Też możesz pomóc, roznosząc nowinę.

Prosta sprawa. Jeśli widzisz kogoś, kto próbuje rzucić albo ma problem z pornografią – nakieruj go na tę metodę. Prawdziwym wyzwaniem jest zmiana narracji wokół pornografii. Jeśli zobaczysz pornografię online albo doświadczysz normalizacji tego zjawiska, proszę – z szacunkiem wytłumacz problem i pomóż ludziom się uwolnić.

Może się trafić negatywna reakcja. Ale spodziewaj się wiadomości od wdzięcznych ludzi, dziękujących ci za pomoc w ucieczce z niewoli.

## Ostatnie ostrzeżenie

Ciesz się resztą życia jako szczęśliwy nieużywający. Żeby tak było, pamiętaj o tych wytycznych:

1. Zapisz sobie tę książkę i odnoś się do niej, jeśli potrzebujesz.

2. Jeśli kiedyś zaczniesz zazdrościć użytkownikowi – pamiętaj, to on zazdrości tobie. Tobie niczego nie brakuje, to on ma problem.

3. Pamiętaj, używanie porno nie było przyjemne. Dlatego rzuciłeś. Teraz jesteś szczęśliwy.

4. Nie ma czegoś takiego jak jedno spojrzenie!

5. Nigdy nie czuj wątpliwości. Wiesz, że nieoglądanie pornografii jest najlepszym wyborem.

6. Jeśli masz jakieś trudności, znajdź terapeutę, który zna się na pornografii. W Internecie jest na ten temat dużo informacji.