# Instrukcje

1. Stosuj się do instrukcji

2. Miej otwarty umysł

3. Rozpocznij od uczucia ulgi

4. Ignoruj porady i wpływ, który kłóci się z Koniec z Porno

5. Oprzyj się pokusie chwilowej przyjemności

6. Zapamiętaj dokładnie: pornografia nie jest przyjemna i nie jest podporą, a ty z niczego nie rezygnujesz. Nie ma nic, z czego rezygnujesz, więc niczego ci nie brakuje.

7. Nie czekaj, rzuć już teraz!

8. Podejmij decyzję, żeby nigdy więcej nie oglądać i nigdy się nad nią nie zastanawiaj.

9. Nie ma czegoś takiego jak jedno spojrzenie.

10. Nigdy więcej nie oglądaj pornografii.

## Afirmacje

- Jestem wolny od pornografii

- Łatwo nie myśleć o pornografii

- Do widzenia myśli, do widzenia pragnienia. Koniec głodu.

- Skupiam się na podświadomości, żeby pokonać uzależnienie

- Pornografia okrada mnie z czasu, energii i żywotności

- Pokonanie pornografii jest łatwiejsze każdego dnia

- Cieszę się moim życiem bez pornografii, które jest silne, szczęśliwe i przyjemne.

- Kiedy myślę o tym jak długo jestem wolny, czuję dumę i szczęście.

- Kiedy widzę innych uzależnionych, motywuję się do zerwania łańcucha

- Cała ta energia leczy moje ciało i umysł. Dzięki temu mogę być bardziej produktywny i nie bać się wyzwania podjęcia moich celów.

- Mój mózg wraca do zdrowia, bo nie robię tego, co robiłem kiedyś.

- Cała ta siła pomaga mi radzić sobie ze stresami życia codziennego.

- Jestem wolny! Nie jestem niewolnikiem!