# Koniec książki

Siema stary, tutaj autor. Po pierwsze, dziękuję ci bardzo za przeczytanie tej książki.

Wolność jest wspaniała, cnie? Pierwszy autor tej książki zmienił moje życie i od tego czasu wszystko jest łatwiejsze. Chciałbym podkreślić zajebistość Allena Carra, który pomógł niezliczonym osobom uciec od uzależnienia.

I trochę hiper komunikacji, jakby coś jeszcze nie było jasne: Rzuciłem porno i co teraz? Kąkuter zły, wyjdź na zewnątrz. Pogadaj z ludźmi w prawdziwym życiu, a nie z obcymi w necie > discord, wykop i gry komputerowe sprawiają, że jesteś samotny, bo niszczą twoje umiejętności społeczne i niszczą ci receptory dopaminy. Znajdź ciekawsze rzeczy niż porno, zmieniaj świat i nie narzekaj – dużo osiągniesz, szczególnie jeśli nie będziesz sam! Kiedy jakaś rewolucja zaczęła się od góry? Zmiany zaczynają się od ciebie! Informuj ludzi na poziomie lokalnym. Inne pułapki: nikotyna, alkohol (tak, grube pranie mózgu, zero zalet), kofeina, social media i technologia. Przestań być tiktokowym zoomerem gejmerem w majnkrafta i zacznij coś robić. Spędzaj czas z ludźmi, których kochasz. Musisz znaleźć sobie cel, paliwo i dedykację. Medytuj, podnoś ciężary, bądź otwarty w związkach i ogranicz konsumpcjonizm.

Koniec z Porno jest dalekie od ideału i pracuję nad przepisaniem metody od nowa. Będzie świetnie, jeśli wiedza będzie przejrzysta i łatwa do zrozumienia, a ty zupełnie uwolnisz się od pornografii. Mam zamiar połączyć terapię poznawczo behawioralną z książkami o uzależnieniach oraz informacjami ze społeczności, żeby stworzyć jasny i zrozumiały poradnik, napisany prostym językiem. Chcę, żeby osoba, która nie ma pojęcia o szkodliwości porno przeczytała taką książkę i została wyleczona za pierwszym razem. Jestem zajęty innymi projektami (na przykład książką o uzależnieniu od komputera), ale spokojnie, na pewno wrócę do tego tematu.

## Jak mogę pomóc Koniec z Porno

Z tej strony tłumacz.

Za tłumaczenie tej książki zabrałem się na początku 2022 roku, po kolejnej nieudanej próbie rzucenia pornografii. Nie wiem co będzie dalej, ale jestem przekonany, że już nigdy nie odpalę porno, bo wiem już, o co chodzi i jak to działa.

Nie wiem też czego się spodziewać i jak zabrać się do promocji tej książki. Będę robił wszystko, co w mojej mocy, aby rozesłać ten poradnik moim znajomym, terapeutom leczącym uzależnienia, na grupy AN i AA oraz obcym ludziom na Twitterze i innych forach internetowych, gdzie spermiarstwo jest dziś ogromnym problemem. W ramach rozwoju mojej działalności będę tu dopisywał więcej informacji, ale mogę wam dziś powiedzieć, że ostatecznym celem jest walka o całkowity ban na treści pornograficzne w kraju.

Jeśli ta książka trafiła w twoje ręce i ją przeczytałeś, i chcesz się podzielić swoimi doświadczeniami, nie bój się napisać maila na metodakonieczporno@gmail.com albo na Twitterze

@KoniecZPorno. Przyjmę twoje uwagi, poprawki i przede wszystkim historie o twoim uzależnieniu, i o tym, jak z niego wyszedłeś. Za twoją zgodą udostępnię twoje świadectwo, żeby zarazić innych życiem w trzeźwości.

Książka jest całkowicie darmowa i dostępna dla każdego. Jeśli znasz ludzi uzależnionych – nie wstydź się im podesłać tej metody. Już wiesz jak dobrze być wolnym i na pewno chcesz informować o tym innych.

Na koniec jeszcze kilka porad od autora.

## I co dalej?

Prawdą jest, że nie musisz zmieniać swojego życia, tylko dlatego, że przestałeś oglądać pornografię. Ale wolność od uzależnienia pomoże ci budować życie, o którym nawet nie śniłeś.

Aktualnie piszę książkę o leczeniu uzależnienia od komputera poprzez samorozwój. Piszę ją sam i będzie zupełnie inna od Koniec z Porno. W międzyczasie oto lista rzeczy, które pomogły mi po rzuceniu.

### Pozostałe pułapki

Rzeczy, które tu wypiszę, też są uzależniające, więc jeśli Koniec z Porno ci pomogło, proszę, wesprzyj autorów tych książek:

**Nikotyna**

Oryginalna metoda EasyWay dotyczyła papierosów, a następnie e-papierosów. Nikotyna jest jedną z najbardziej uzależniających substancji, które znamy. Jeśli jej używasz, możesz zastosować tą samą metodę, którą opisałem tutaj, ale jeśli możesz, proszę wesprzyj EasyWay kupując ich książki. Zyski są przeznaczane na leczenie uzależnionych!

**Alkohol**

Wszyscy, których znam, razem ze mną, uznałby mnie za osobę pijącą alkohol okazjonalnie.

Nigdy nie miałem problemu z alkoholem, ale w 2020 postanowiłem rzucić zupełnie, na rok, mówiąc Będzie jeszcze czas na picie, więc czemu teraz się nie ogarnąć na jakiś czas? Podczas rozmowy z przyjacielem o Koniec z Porno, on polecił mi Kick the drink... easily! Autorstwa Jasona Vale (który pracował z Allenem Carrem), która mu pomogła z jego problemem alkoholowym.
Zdecydowałem się ją przeczytać, żeby pomóc przyjacielowi z problemem.

Tak jak Koniec z Porno, Kick the drink nie wytwarza żadnego ciśnienia, a ja rozpocząłem czytać przekonany, że nadal od czasu do czasu pozwolę sobie na drinka. Gdy skończyłem, zrozumiałem, że już nigdy się nie napiję i jestem z tego dumny. Podsumuję krótko treść zawartą w książce:

Odstawienie alkoholu trwa 10 dni, które przedłuża się, bo większość z nas pije co weekend. I tak jak nie ma uzależnionego od porno – są tylko różne stopnie uzależnienia – to samo dotyczy alkoholu. Przyznanie, że nie masz kontroli generuje strach, co prowadzi do łatki alkoholika, więc ignorujesz problem.

Po rzuceniu, nagle sytuacje społeczne stały się dużo przyjemniejsze. Mamy w głowie ideę, że bycie pijanym jest przyjemne, ale jak tylko usuniesz pranie mózgu, szybko zrozumiesz, że tak nie jest. To depresyjna trucizna, która ogranicza cię fizycznie i psychicznie. Nie jesteś sobą, jesteś ogłupiony i wyzbywasz się zahamowań. Nie rozładowujesz stresu, nie relaksujesz się, nie rozmawia ci się łatwiej i nie masz więcej odwagi. Ucieczka oznacza koniec z kacem, więcej pieniędzy i w końcu nie będziesz się musiał zastanawiać czy czegoś nie palnąłeś.

Alkohol to trik, który działa na ludzi od bardzo dawna i czas zmienić narrację. Zastanów się ilu ludzi zrujnowało sobie życie przez alkohol? Bijatyki, jazda po alkoholu, problemy w związkach i wiele, wiele więcej. Jeśli chcesz coś wyciągnąć z tego rozdziału – przeczytaj tę książkę.

**Kofeina**

Pułapka dokładnie taka sama jak pornografia. To stymulant, więc przez tydzień czujesz
działanie, a potem czujesz tylko głód. Poczujesz się lepiej, obiecuję.

**Media społecznościowe**

Media społecznościowe są jak automaty do gier. Jesteś ciągle bombardowany informacjami, więc nie umiesz się skoncentrować, radzić sobie ze stresem i regulować swojego samopoczucia. Co gorsze, twoje poczucie własnej wartości stawiane jest w arbitralnym systemie wartości. Jaką emocję czujesz czytając ten akapit? Strach?

Jak każdy użytkownik social mediów jesteś w pułapce uzależnienia. Czy kiedyś sam zdecydowałeś, że potrzebujesz tych mediów? Że będą one w twoim życiu do końca i będą powodowały uczucia niepewności i paniki, kiedy nie masz do nich dostępu?

Tak jest, nie jesteśmy zbudowani do ciągłych nowinek. To chemiczne uzależnienie i jest milion lepszych rzeczy, które możesz zrobić ze swoim czasem. Pamiętaj, co możesz osiągnąć, jeśli skupisz uwagę – zawalczysz o problemy takie jak środowisko czy edukacja seksualna. Nie narzekaj, bądź aktywny i pytaj, jak możesz ulepszyć świat. Zmiana zaczyna się od ciebie.

Przeczytaj – *Smart Phone, Dumb Phone*, John Dicey, *Ten Arguments for Deleting your Social Media Right Now*, oraz *Exiting Modernity*, Meta-Nomad.

### Pozytywne zmiany

Wolność od pornografii doprowadzi do pytań o naturę związków. Jeśli masz problem z randkowaniem, a nawet jeśli nie masz – bardzo polecam *Models*, autorstwa Marka Mansona, który pisze o wrażliwości i wzajemnym rozumieniu w związkach. Cieszę się też, że nie wpadłem w pułapkę nauki podrywu i incelizmu, bo to niezdrowe. Nawet nie musisz z tym handlować.

**Medytacja**

Już wciskałem medytację, ale definitywnie polecam żebyś spróbował. To nie jest religijne i ważnym jest by rozróżnić medytację – czyli zauważanie myśli – od praktyk buddyjskich. Polecam aplikację Waking Up, która jest płatna, ale bardzo pomocna.

**Sen**

„*Why we sleep*” to świetna książka, dobrze zgadłeś, o spaniu. Bardzo polecam. Wiesz, że najlepszym sposobem na zmęczenie po długim locie samolotem jest post i minimalne spożycie wody 16 godzin przed pobudką? Można to zastosować w innych przypadkach – jeśli rozwaliłeś sobie rytm dobowy, na przykład oglądając porno całą noc, to również ci pomoże.

**Ćwiczenia fizyczne**

Ćwiczenia fizyczne mają bardzo wiele zalet dla zdrowia fizycznego i psychicznego. Ja czytam książkę *The Leangains Method*, autorstwa Martina Berkhana. Dla każdego i w każdym wieku, podnoszenie ciężarów jest najlepszym sposobem na zdrowie. Nawet jeśli nie masz dostępu do siłowni, możesz uprawiać kalistenikę.

**Anty-konsumpcjonizm**

Mój ulubiony tekst na ten temat to *Exiting Modernity*, autorstwa Meta Nomad. Krytykuje on wiele założeń, które przyjmujemy w nowoczesnym życiu i podpowiada jak uciec. To tylko 30 stron, ale uważaj – to dość ciężki dokument, który cię oświeci, jeśli mu na to pozwolisz *Zbyt późno to nie wiek ani czas. Zbyt późno jest, gdy zmęczenie sprawia że się poddajesz i zapominasz siebie, cały potencjał człowieka rozpuszczony w nicość. - Meta Nomad*.
Koniec końców to wszystko to tylko sugestie. Co chcesz osiągnąć? Jesteś wolny od pornografii i możesz użyć tego cudu jak tylko ci się podoba.

## Dziękuję!

Po raz kolejny – dziękuję ci za przeczytanie tej książki. Mam nadzieję, że ci pomoże i jest to dla mnie bardzo ważne. W tej chwili neurony w twoim mózgu łączą się w unikatowy sposób i ważnym jest żebyś to utrzymał. Czytaj tak długo jak potrzebujesz. Wiele osób zapomina, że usunięcie prania mózgu – przynajmniej na początku – jest świadomym procesem, więc nawrót pojawia się, gdy zapomnisz lekcji. Przyrzeknij sobie, że już nigdy nie będziesz oglądał pornografii, niezależnie co się stanie. Nie ma gwarancji, że ta książka zadziała dwa razy, jednak wielu pomogła.
Dużo łatwiej utrzymać ten sposób myślenia niż go złamać i potem do niego wracać.

Pornografia jest tak wielkim potworem, że nie da się jej kontrolować. Odpowiedź społeczna jest powolna. Ale ty bądź optymistą, bo każda osoba, która ucieka, napędza kulę śnieżną.

Przypominam jeszcze raz, możesz się ze mną skontaktować przez metodakonieczporno@gmail.com, albo na twitterze - @KoniecZPorno.

Jeśli masz problem z lekcjami zawartymi w tej książce, zapytaj innych, którzy użyli tej metody. Liczę na to, że wytworzymy społeczność, w której będzie można szukać wsparcia.

Pozdrawiam serdecznie,

Fraser Patterson i Żaba z Brązu