# Die Einfache Methode

Das Ziel dieses Buches ist es, dich in eine Denkweise zu versetzen, in
dem du statt der üblichen Methode des Aufhörens, bei der du zu Beginn
das Gefühl hast, den Mount Everest zu besteigen und die nächsten Wochen
mit Verlangen und Entzug zu verbringen, sofort mit einem Hochgefühl
beginnst, als ob du von einer schrecklichen Krankheit geheilt worden
wärst. Je weiter du dann durchs Leben gehst, desto mehr wirst du auf
diese Zeit zurückblicken und dich fragen, wie du überhaupt jemals Pornos
benutzt hast. Du wirst andere Pornokonsumenten nicht mehr mit Neid,
sondern mit Mitleid betrachten.

Vorausgesetzt, du bist jemand, der nie süchtig geworden ist (du liest
für deinen Partner oder deine Partnerin) oder aufgehört hat (oder sich
in den Fastentagen einer \"Porno-Diät\" befindet), musst du unbedingt
weitermachen, bis du das Buch vollständig gelesen hast. Das mag wie ein
Widerspruch erscheinen, und diese Anweisung, weiter zu Pornos zu
masturbieren, ruft mehr Widerspruch hervor als jede andere, aber wenn du
weiterliest, wird dein Verlangen, Pornos zu benutzen, allmählich
abnehmen. **Nimm diese Anweisung ernst: Der Versuch, vorzeitig
aufzuhören, wird dir nichts bringen.**

Viele beenden das Buch nicht, weil sie das Gefühl haben, etwas aufgeben
zu müssen. Manche lesen sogar absichtlich nur eine Zeile pro Tag, um das
böse Ereignis aufzuschieben. Sieh es doch mal so: Was hast du zu
verlieren? Wenn du am Ende des Buches nicht aufhörst, bist du nicht
schlechter dran als jetzt. Es handelt sich also um eine Pascalsche
Wette, bei der du nichts zu verlieren hast und hohe Chancen auf einen
großen Gewinn hast.

Übrigens: Wenn du seit ein paar Tagen oder Wochen keine Pornos mehr
geschaut hast, dir aber nicht sicher bist, ob du ein Pornonutzer,
Ex-Nutzer oder Nicht-Nutzer bist, dann benutze keine Pornos beim
Masturbieren während du das Buch liest. Eigentlich bist du schon ein
Nicht-Nutzer, aber dein Gehirn muss erst mit deinem Körper mithalten
können. Am Ende des Buches wirst du ein glücklicher Nicht-Nutzer sein.
EasyPeasy ist das komplette Gegenteil der normalen Methode, bei der man
die erheblichen Nachteile von Pornos aufzählt und sagt:\
*\"Wenn ich nur lange genug ohne Pornos auskomme, wird das Verlangen
irgendwann verschwinden und ich kann das Leben wieder genießen, frei von
Sklaverei.\"*\
Das ist der logische Weg, und Tausende hören jeden Tag mit dieser
Methode auf. Allerdings ist es aus den folgenden Gründen sehr schwierig,
erfolgreich zu sein:

Mit PMO aufzuhören ist nicht das eigentliche Problem.

:   Jedes Mal, wenn du deine Session beendest, hast du damit aufgehört.
    Vielleicht hast du am ersten Tag deiner Porno-Diät (einmal alle vier
    Tage), gute Gründe zu sagen: *'Ich will keine Pornos mehr benutzen
    oder gar masturbieren.'* Alle Nutzer tun das, und ihre Gründe sind
    stärker, als du dir vorstellen kannst. Das eigentliche Problem ist
    der zweite, zehnte oder zehntausendste Tag, an dem du in einem
    schwachen Moment \"nur einen Blick\" wirfst, einen weiteren willst
    und plötzlich wieder süchtig bist.

Das Wissen um die gesundheitlichen Risiken erzeugt mehr Angst und macht es schwieriger, aufzuhören.

:   Wenn man einem Nutzer sagt, dass es seine Potenz zerstört, wird er
    als Erstes nach etwas greifen, das ihm einen Dopaminschub
    verschafft: eine Zigarette, Alkohol oder sogar die Suche nach einem
    Porno im Browser.

Alle Gründe, aufzuhören, machen es noch schwieriger.

:   Das hat zwei Gründe. Erstens werden wir ständig gezwungen, unseren
    \"kleinen Freund\" oder eine Requisite, ein Laster oder ein
    Vergnügen (je nachdem, wie der Nutzer es sieht) aufzugeben. Zweitens
    schaffen sie eine \"Blende\". Wir masturbieren nicht aus den
    Gründen, aus denen wir aufhören sollten. Die eigentliche Frage ist,
    warum wir es tun wollen oder müssen.

Mit EasyPeasy vergessen wir (zunächst) die Gründe, warum wir aufhören
möchten, stellen uns dem Pornoproblem und fragen uns Folgendes:

1.  Was tuen Pornos für mich?

2.  Genieße ich es wirklich?

3.  Muss ich wirklich durch mein Leben gehen und meine Denkweise und
    meinen Körper sabotieren?

Die schöne Wahrheit ist, dass *alle Pornos* absolut nichts für dich tun.
Um es ganz klar zu sagen: Es geht nicht darum, dass die Nachteile des
Konsums die Vorteile überwiegen, sondern darum, dass es **null**
Vorteile gibt, wenn man sich Internetpornos ansieht.

Die meisten Nutzer finden es notwendig, rational zu begründen, warum sie
Pornos nutzen, aber die Gründe, die sie anführen, sind allesamt
Trugschlüsse und Illusionen.

Das erste, was wir tun werden, ist, diese Trugschlüsse und Illusionen zu
beseitigen. Du wirst feststellen, dass es nichts aufzugeben gibt. Es
gibt nicht nur nichts aufzugeben, sondern es gibt auch wunderbare,
positive Vorteile, wenn man kein PMOer ist, und Wohlbefinden und Glück
sind nur zwei dieser Vorteile. Sobald die Illusion beseitigt ist, dass
das Leben ohne Pornos niemals so angenehm sein wird; sobald du erkennst,
dass das Leben ohne Pornos nicht nur genauso angenehm ist, sondern
unendlich viel angenehmer; sobald das Gefühl, etwas zu verpassen,
beseitigt ist, können wir uns wieder dem Wohlbefinden und dem Glück
widmen - und den Dutzenden von anderen Gründen, mit Pornos aufzuhören.
Diese Erkenntnisse werden zu positiven zusätzlichen Hilfen, die dir
dabei helfen, das zu erreichen, was du wirklich willst, nämlich dein
ganzes Leben frei von der Sklaverei der Pornosucht zu genießen.
