# Warum ist es schwer aufzuhören?

Alle Nutzer haben das Gefühl, dass etwas Böses von ihnen Besitz
ergriffen hat. Am Anfang ist es eine einfache Frage der Einstellung:
*\"Ich werde aufhören, nur nicht heute\"*, aber irgendwann glauben wir,
dass wir nicht genug Willenskraft haben, um aufzuhören, oder dass Pornos
etwas an sich haben, das wir haben müssen, um das Leben zu genießen.
Pornografiesucht ist vergleichbar mit dem Weg aus einer rutschigen Grube: Wenn
du dich der Kante näherst, siehst du die Sonne, aber du rutschst wieder
hinunter, wenn deine Stimmung sinkt. Schließlich öffnest du deinen
Browser und während du masturbierst, fühlst du dich schrecklich.

Frag einen Nutzer: *\"Wenn du in die Zeit zurückgehen könntest, bevor du
süchtig wurdest, hättest du dann mit dem Wissen, das du jetzt hast,
angefangen, Pornos zu benutzen?\"*

*\"NIEMALS!\"* wäre die Antwort gewesen.

Frag einen eingefleischten Nutzer, der Internetpornografie verteidigt und
nicht glaubt, dass sie das Gehirn schädigen oder die Dopaminrezeptoren
herunterregulieren: *\"Ermutigst du deine Kinder dazu, Pornografie zu
benutzen?\"*

*\"Niemals!\"* ist abermals die Antwort.

Pornografie ist ein außergewöhnliches Rätsel. Wie schon gesagt, liegt das
Problem nicht darin zu erklären, warum es einfach ist, aufzuhören,
sondern warum es schwierig ist. Das eigentliche Problem ist, zu
erklären, warum jemand damit anfängt, *nachdem* er das Wissen über
neurologische Schäden erlangt hat. Einer der Gründe, warum wir damit
anfangen, sind die vielen Millionen, die schon dabei sind, doch all diese Menschen
wünschen sich, dass sie gar nicht erst damit angefangen hätten, und
sagen uns, dass sie ihr Leben mit angezogener Handbremse leben. Wir
können nicht so recht glauben, dass sie es nicht genießen, sondern 
assoziieren Pornografie mit Freiheit oder \"Sexualerziehung\" und arbeiten hart
daran, selbst süchtig zu werden. Wir verbringen dann den Rest unseres
Lebens damit, anderen zu sagen, dass sie es nicht tun sollen, und
versuchen, selbst davon loszukommen, glaubend, dass wir ganz allein damit dastehen.

Außerdem verbringen wir einen großen Teil unserer Zeit damit, uns
hoffnungslos und unglücklich zu fühlen. Uns mit dem
Unnatürlichen \"weiterzubilden\", bringt uns dazu diese
kalten Bilder zu bevorzugen und uns danach zu sehnen,
selbst wenn warme, echte Bilder verfügbar sind! Durch das
ständige Auf und Ab des Dopamins, das durch PMO ausgelöst wird,
verurteilen wir uns selbst zu einem Leben voller Reizbarkeit, Wut,
Stress, Müdigkeit und sexueller Dysfunktion. Wenn wir Pornografie
konsumieren, mit ihrer Abwesenheit von den besten Seiten von Sex
und Beziehung, fühlen wir uns am Ende unglücklich und schuldig.

Wenn wir hier und auf anderen Seiten über die süchtig machenden und
zerstörerischen Fähigkeiten der Internetpornografie lesen, werden wir sogar
noch nervöser und hoffnungsloser! Was ist das für ein Hobby, bei dem du
dir wünschst, du würdest es nicht tun, und wenn du es nicht tust, sehnst
du dich danach? Nutzer verachten sich jedes Mal, wenn sie über
Hypofrontalität und Desensibilisierung lesen, jedes Mal, wenn sie hinter
dem Rücken ihres Partners, der ihnen vertraut, konsumieren, jedes Mal, wenn
sie sich nicht dazu durchringen können, nach einer Sitzung zu
trainieren. Ein ansonsten intelligenter und vernünftiger Mensch
verbringt seinen ganzen Tag mit Verachtung. Aber das Schlimmste ist: Was
haben die Nutzer davon, wenn sie das Leben mit diesen furchtbaren
schwarzen Schatten im Hinterkopf ertragen müssen? **Absolut nichts!**

Du denkst jetzt vielleicht: *\"Das ist ja schön und gut, aber wenn man
einmal süchtig nach diesen Dingen ist, ist es sehr schwer aufzuhören.\"*
Aber warum ist es so schwer? Manche sagen, es läge an den starken
Entzugserscheinungen, aber wie du noch sehen wirst, sind die
tatsächlichen Entzugserscheinungen sehr mild. Das kann man besonders an
der Tatsache festmachen, dass viele PMOer gelebt haben und gestorben sind ohne
zu merken dass sie abhängig waren.

Manche sagen, dass Internetpornos kostenlos sind und die Menschheit
deshalb diese biologische Goldgrube für sich beanspruchen sollte, aber
das stimmt nicht - sie machen süchtig und wirken wie jede Droge. Frag
einen Nutzer, der schwört, dass er nur \"Erotika\" wie Playboy-Magazine
genießt, ob er schon einmal die Grenze zum \"unsicheren Porno\"
überschritten hat. Wenn er komplett ehrlich ist, würde er all die Male zugeben
bei denen er es rationalisiert hat, diese Grenze zu überschreiten, anstatt gar nichts zu benutzen.

Genuss hat auch nichts damit zu tun: Ich mag Flusskrebse, aber ich bin
nie an den Punkt gekommen, an dem ich jeden Tag Flusskrebse essen
musste. Andere Dinge im Leben genießen wir zwar, während wir sie
tun, aber wir sitzen nicht herum und fühlen uns als würde etwas fehlen,
wenn wir es nicht tun.

Manche sagen:\
*\"Es ist lehrreich!\"* Nun denn, wie hat es dich als Person weiter gebracht?
*\"Es ist sexuell befriedigend!\"* Warum also isoliert es dich also und lässt dich ein unersättliches Verlangen verspüren?\
*\"Es ist ein Gefühl der Befreiung!\"* Befreiung vom Stress des echten
Lebens? Okay, vielleicht für eine Stunde, bevor er dann wieder auf dich einwirkt.
Und welchen Stress hat es beseitigt?
*\"Es hilft mir zu schlafen!\"* Warum können andere also wunderbar ohne das schlafen?
Es gibt viele wissenschaftlich nachgewiesene Methoden, um guten Schlaf wiederzuerlangen, ihn sogar noch zu verbessern.

Viele glauben, dass Pornos die Langeweile vertreiben, aber Langeweile ist eine Geisteshaltung. Pornografie gewöhnt dich in kürzester Zeit an die Suche nach Neuem und führt dazu, dass du dich immer mehr langweilst, bis du dich schließlich auf die wilde Jagd
nach dem richtigen Clip begibst und dich immer mehr darauf einstellst, nach allem zu suchen, was neu ist, starke Emotionen hervorruft und, schlussendlich, einen unerhörten Schockwert besitzt.

Manche sagen, sie machen es nur, weil ihre Freunde und alle, die sie
kennen, es auch tun. Wenn dem so ist, bete dafür, dass deine Freunde nicht anfangen,
sich den Kopf abzuschneiden, um ihre Kopfschmerzen zu kurieren! Die meisten Nutzer, die darüber nachdenken, kommen zu dem Schluss, dass es einfach eine Gewohnheit ist. 
Das ist zwar keine wirkliche Erklärung, aber nachdem alle üblichen, 
rationalen Erklärungen ausgeschlossen wurden, scheint es die einzige verbleibende
Entschuldigung zu sein. Leider ist sie genauso unlogisch. Jeden Tag in
unserem Leben ändern wir unsere Gewohnheiten, einige davon sehr
angenehm. Wir wurden einer Gehirnwäsche unterzogen und glauben, dass PMO
eine Gewohnheit ist und dass Gewohnheiten schwer zu durchbrechen sind.

Sind Gewohnheiten schwer zu brechen? Autofahrer in den USA haben die Angewohnheit,
auf der rechten Straßenseite zu fahren, doch wenn sie nach Übersee reisen, 
brechen sie mit dieser Gewohnheit ohne großen Aufwand. Und wenn du eine neue Arbeitsstelle antrittst formst du neue Routinen, also ändern sich auch deine Gewohnheiten.
Das dauert vielleicht ein wenig, aber das ist nichts im Vergleich dazu, einen
lebenslangen Kampf gegen Pornografiesucht zu führen. Wir beginnen und beenden
Gewohnheiten jeden Tag in unserem Leben. Warum fällt es uns dann so schwer, mit einer Gewohnheit zu brechen, die uns beraubt fühlen lässt, wen wir sie nicht
durchführen können, schuldig, wenn wir sie durchführen, eine, die wir am liebsten sowieso einfach brechen würden, wenn das Einzige, was wir dafür tun müssen, es einfach
nur zu unterlassen?

Die Antwort ist, dass Pornografie keine Gewohnheit ist, sondern eine
**Sucht!** Deshalb scheint es auch so schwer zu sein, \"aufzuhören\".
Die meisten Nutzer verstehen nicht, was Sucht ist, und glauben, dass sie
durch Pornografie echtes Vergnügen oder eine Krücke im Leben bekommen, die ihnen hilft. 
Sie glauben, dass sie ein echtes Opfer bringen, wenn sie aufhören.

Die wunderbare Wahrheit ist, dass du, sobald du die wahre Natur der
Pornografiesucht und die Gründe, warum du es benutzt, verstehst, ganz einfach
damit aufhören wirst. Innerhalb von drei Wochen wird das einzige Rätsel
sein, warum du es für nötig befunden hast, so lange Pornografie zu benutzen,
und warum du andere Nutzer nicht davon überzeugen kannst, *wie schön es
ist, kein PMOer zu sein!*

## Die teuflische Falle

Internetpornografie ist eine subtile und teuflische Falle, die der Mensch
und die Natur gemeinsam entwickelt haben. Manche von uns
werden sogar vor den Gefahren gewarnt, aber wir können nicht glauben,
dass sie uns keinen Spaß macht. Aber wie kommen wir überhaupt dazu, in
die Falle zu gehen? Normalerweise sind es kostenlose "Proben" von
Amateuren und Profis, die sie mit uns teilen. So schnappt die Falle zu. Wenn sie uns anstatt dessen vor den Gefahren dessenm, auf was wir uns da einlassen, gewarnt hätten,
bevor wir einen ersten Blick darauf geworfen hätten, wären die Alarmglocken laut am läuten.

Aber sie läuten nicht. Vielleich ist es die schockierende Natur vieler Clips
die unsere jungen Köpfe glauben lässt dass wir niemals abhängig werden, weil wir
denken dass wir sie nicht genießen, und deswegen jederzeit damit aufhören können.
Oder vielleicht ist die vermeintliche Unschuldigkeit weniger harten Materials der Grund, dass die Alarmglocken nicht läuten, ähnlich wie ein geschicktes Gedankenkonstrukt mit dem ein Betrüger unseren Verstand lenken kann. Als intelligente Menschen würden wir dann nämlich verstehen, warum die Hälfte der erwachsenen Bevölkerung systematisch
süchtig nach etwas gemacht wurde, das ihr Potenzial, das zu tun, was sie ansehen,
beschränkt. Neugierde bringt uns näher an die Schwelle zur Sucht, aber
wir trauen uns nicht, auf die Vorschaubilder zu klicken, die wir anschauen, weil wir
befürchten, dass sie uns krank machen oder uns auf einen gefährlichen und unmoralischen Weg bringen könnten. Und wenn du versehentlich auf eines klickst, ist oft der einzige Wunsch, so schnell wie möglich von der Seite wegzukommen, und doch bist du gleichzeitig verzweifelt neugierig auf mehr.

Wenn das erstmal passiert ist, sind wir gefangen. Wir verbringen dann den Rest unseres Lebens damit, zu versuchen zu verstehen, warum wir das tun, sagen unseren Kindern, dass sie nicht damit anfangen sollen, und zuweilen versuchen wir davon zu fliehen. Die Falle ist so konstruiert, dass wir versuchen, nur aufgrund eines \"Vorfalls\" aufzuhören, sei es sexuelle Leistung, der Verlust einer Karriere oder einer Beziehung, Antriebslosigkeit oder einfach nur das Gefühl, wie ein Aussätziger zu sein. Sobald wir aufhören, haben wir aufgrund von Entzugserscheinungen noch mehr Stress und die Methode, auf die wir
uns verlassen haben, um diesen Stress zu beseitigen, ist weg.

Unser Entschluss aufzuhören, beginnt dann zu wackeln. Nach ein paar Tagen der Qual kommen wir zu dem Entschluss, dass wir den falschen Zeitpunkt zum Aufhören gewählt haben, und beschließen, auf stressfreie Zeiten zu warten, die uns dann den Grund zum Aufhören nehmen.
Natürlich wird diese Zeit nie kommen, da wir innerlich glauben, dass unser Leben immer stressiger wird. Wenn wir den Schutz unserer Eltern verlassen, fängt der Stress der Arbeit, des Haushalts, der Hypotheken, der Unterkunft, der Kindererziehung an unser Leben zu füllen. Aber das ist eine Illusion. Die stressigsten Abschnitte im Leben eines jeden Lebewesens sind die frühe Kindheit und die Jugend sind.

Wir neigen dazu, Verantwortung mit Stress zu verwechseln. Das Leben
eines Pornografienutzers - genau wie was eines Drogenkonsumenten-  wird automatisch stressiger, weil Pornografie nicht entspannt und Stress abbaut, wie manche uns weismachen
wollen. Das Gegenteil ist der Fall: Je mehr du konsumierst, desto
stressiger wird dein Leben, mit jeder schuldbeladenen nächtlichen Sitzung, die irgendwann das Fass zum Überlaufen bringt. Sogar Nutzer die sich die Sucht abgewöhnen (wie es die meisten ein- oder mehrmals in ihrem Leben tun), können du ein absolut glückliches Leben
führen und plötzlich wieder süchtig werden. Wenn wir in das Labyrinth der Pornografie eintauchen, vernebelt sich unser Verstand und wir verbringen den Rest unseres Lebens damit, zu entkomme. Viele sind dabei erfolgreich, nur um später wieder in die unheilvolle
Falle zu tappen.

Das Pornografieproblem zu lösen ist ein Rätsel. Es ist komplex und schwer. Aber wenn du die Lösung einmal erkannt hast, ist es einfach und macht Spass, und du wirst dich fragen wieso du es noch nicht vorher verstanden hast. EasyPeasy enthält die Lösung dieses
Rätsels und führt dich aus dem Labyrinth heraus, damit du nie wieder
hineingerätst. Alles, was du tun musst, ist den Anweisungen genau zu folgen.
Wenn du jedoch falsch abbiegst, indem du Kapitel überspringst, oder superschnell durchhetzt ohne eine ernsthafte Absicht beim ersten Lesen, ist der Rest der Anweisungen sinnlos.

Jeder kann es leicht finden, aufzuhören, aber zuerst müssen Fakten
geschaffen werden. Nein, keine Fakten, die dir Angst machen, es gibt
bereits mehr als genug Informationen da draußen. Wenn dich das aufhalten würde,
hättest du schon längst aufgehört. Aber warum fällt es uns so schwer,
aufzuhören? Um diese Frage zu beantworten, müssen wir den wahren Grund
kennen, warum wir immer noch Pornos konsumieren, und der lässt sich auf
zwei Faktoren reduzieren. Diese sind:

-   Natur und Internetpornografie.

-   Gesellschaftliche Gehirnwäsche.

Pornokonsumenten sind intelligente, rationale Menschen. Sie wissen, dass
sie enorme Risiken für die Zukunft eingehen, also verbringen sie viel
Zeit damit, ihre \"Gewohnheit\" zu rationalisieren. Aber in ihrem Herzen
wissen Pornografienutzer, dass sie Idioten sind, denn sie wissen, dass sie
keine Notwendigkeit hatten, Pornografie zu nutzen, bevor sie süchtig
wurden. Die meisten erinnern sich daran, dass ihr erster \"Blick\" eine
Mischung aus Abscheu und neuartiger Neugierde war. Dann spezialisierten sie
sich darauf, Seiten zu finden, zu filtern und zu speichern und
arbeiteten hart daran, süchtig zu werden.

Am ärgerlichsten ist das Gefühl, dass Nicht-Süchtige, meistens Frauen,
ältere Männer und Menschen, die in Ländern leben, in denen es keine
Hochgeschwindigkeits-Internetpornografie gibt, nichts verpassen und die
Situation lächerlich finden. Nachdem wir diese Faktoren in den nächsten
Kapiteln auseinander genommen haben, wirst auch du diese teuflische Falle verstehen!
