# Natur

Internetpornografie funktioniert, indem sie die natürlichen
Belohnungsmechanismen, die dafür sorgen, dass du dich so lange
wie möglich fortpflanzt, aushebelt. Die sofortige und leicht zugängliche Art von
Internetpornografie sorgt dafür, dass der Belohnungsmechanismus des Gehirns
wesentlich länger Dopamin produziert, als es normalerweise möglich wäre.
In der Wissenschaft ist das als der "Coolidge-Effekt" bekannt, von dem du vielleicht schon einmal gehört hast.

Dopamin ist ein Neurotransmitter, der mit Gefühlen des Verlangens in Verbindung gebracht wird, der durch Opioide Lust erzeugt. Mehr Dopamin, mehr Opiate und mehr Action. Ohne Dopamin fühlen sich Handlungen wie Essen nicht angenehm an und werden daher
nicht ausgeführt - wobei fett- und zuckerreiche Lebensmittel die höchste
chemische Freisetzung erzeugen.

Dopamin wird ebenfalls als Reaktion zu Neuartigkeit ausgeschüttet. Durch die scheinbar unendliche Menge an Pornografie, die verfügbagbar ist, wird das limbische System (Belohnungszentrum) überflutet; wenn du also zum ersten Mal einen
Porno siehst, wirst du aktiv, kommst zum Orgasmus und löst eine weitere
Opiatflut aus. Da das Gehirn einen Anreiz hat, so viel Dopamin wie
möglich zu bekommen, speichert es dies als Skript, um es leicht abrufen
zu können, und stärkt die neuronalen Bahnen durch die Freisetzung einer
Chemikalie namens DeltaFosB. Das Gehirn ruft diese Bahnen als Reaktion
auf Signale wie erotische Werbespots, Alleinsein, Stress oder sogar
Niedergeschlagenheit auf und plötzlich bist du bereit, eine Fahrt auf
der \"Wasserrutsche\" zu machen. Jedes Mal, wenn sich dies wiederholt,
wird mehr DeltaFosB freigesetzt, so dass die Wasserrutsche geölt und
bereit ist und du beim nächsten Mal leichter hinunterrutschen kannst.

Das limbische System verfügt über ein selbstkorrigierendes System, bei dem die
Anzahl der Dopamin- und Opioidrezeptoren begrenzt wird, wenn eine
häufige und tägliche Überflutung mit Dopamin festgestellt wird. Unglücklicherweise
werden diese Rezeptoren auch benötigt, um uns zu motivieren die
täglichen Belastungen des Lebens zu bewältigen. Die Mengen an
Dopamin, die durch natürliche Belohnungen ausgeschüttet werden, sind
einfach nicht vergleichbar zu denen von pornografie und werden nicht so effizient von den
verminderten Rezeptoren aufgenommen, was dazu führt, dass du dich
gestresster und gereizter fühlst als sonst. Dieser Prozess wird als
Desensibilisierung bezeichnet.

In diesem Zyklus hast du die \"rote Linie\" überschritten und Emotionen
wie Schuld, Ekel, Scham, Angst und Furcht ausgelöst, die wiederum den
Dopaminspiegel noch weiter in die Höhe treiben und das Gehirn dazu
veranlassen, diese Gefühle fälschlicherweise als sexuelle Erregung zu
interpretieren.

Im Laufe der Zeit wird das Gehirn nicht nur gegenüber früheren Clips,
die es gesehen hat, desensibilisiert, sondern auch gegenüber ähnlichen
Genres und Schockstufen. Diese geringere Motivation führt zu einem
geringeren Gefühl der Befriedigung, da unser Gehirn ständig bewertet und
dich dazu drängt, Clips zu finden, die deinen Hunger stillen. Du suchst
also nach mehr Neuem und klickst auf den amateurhaften, schockierenden
Clip auf der Homepage, von dem du dir beim ersten Besuch sicher warst,
dass du ihn nicht ansehen würdest.

\"Denn im Tau der kleinen Dinge findet das Herz
seinen Morgen und wird erfrischt\" - Kahlil Gibran*

Ein flüchtiges Gefühl der Sicherheit ist alles, was man braucht, um eine
schwierige Phase im Leben zu überstehen, aber wird dein
desensibilisiertes Gehirn in der Lage sein, diesen entstressenden Tropfen zu fangen, den
das Gehirn eines Nicht-Nutzers verwenden kann?

Die Dopaminflut wirkt wie eine schnell wirkende Droge, die schnell
abfällt und Entzugserscheinungen hervorruft. Viele Nutzer haben die
Illusion, dass diese Schmerzen das schreckliche Trauma sind, das sie
erleiden, wenn sie versuchen oder gezwungen werden, aufzuhören. In
Wirklichkeit sind sie in erster Linie psychisch bedingt, da sich der
Nutzer seiner Lust oder Stütze beraubt fühlt.

## Das kleine Monster

Die eigentlichen Entzugserscheinungen von Pornografie sind so subtil, dass
die meisten Nutzer leben und sterben, ohne zu merken dass sie
drogenabhängig sind. Viele Nutzer haben Angst vor Drogen,
dabei sind sie genau das: drogenabhängig. Zum Glück ist es einfach, von
der Droge loszukommen, aber du musst zuerst akzeptieren, dass du
tatsächlich süchtig bist. Entzug von Pornografie verursacht keine
körperlichen Schmerzen, sondern ist lediglich ein leeres, unruhiges
Gefühl, dass etwas fehlt, weshalb viele glauben, dass es etwas mit dem
sexuellen Verlangen zu tun hat. Wenn dieses Gefühl länger anhält, wird
es zu Nervosität, Unsicherheit, Unruhe, geringem Selbstvertrauen und
Reizbarkeit. Es ist wie Hunger - nach Gift.

Innerhalb von Sekunden nach einer Sitzung wird Dopamin ausgeschüttet und
das Verlangen endet, was zu einem Gefühl der Erfüllung führt, während du
die Wasserrutsche hinunter saust. In den ersten Tagen sind die
Entzugserscheinungen und ihre anschließende Linderung so gering, dass
wir sie gar nicht bemerken. Wenn wir zu regelmäßigen Nutzern werden,
glauben wir, dass es daran liegt, dass es uns gefällt oder wir uns daran
gewöhnt haben. In Wahrheit sind wir bereits süchtig, merken es aber
nicht. Das kleine Monster ist bereits in unserem Gehirn, also machen wir ab und zu
einen Ausflug auf der Wasserrutsche, um es zu füttern.

Alle Nutzer fangen aus irrationalen Gründen an, nach Pornografie zu suchen. Der *einzige*
Grund, warum jemand weiterhin Pornografie nutzt, egal ob gelegentlich oder
regelmäßig, ist der, dieses kleine Monster zu füttern. Das ganze Dilemma
ist eine Reihe grausamer und verwirrender Bestrafungen, aber der
vielleicht erbärmlichste Aspekt ist das Gefühl der Freude, das ein
Nutzer nach einer Sitzung empfindet, wenn er versucht, zu dem Gefühl von
Frieden, Ruhe und Selbstvertrauen zurückzukehren, das sein Körper hatte,
bevor er süchtig wurde.

## Der nervige Alarm

Kennst du das Gefühl, wenn die Alarmanlage des Nachbarn schon den ganzen
Tag läutet (oder eine andere kleine, hartnäckige Verärgerung auftritt) - und
der Lärm plötzlich aufhört und dich ein wunderbares Gefühl von Frieden
und Ruhe überkommt? Das ist nicht wirklich Frieden, sondern das Ende
eines Ärgernisses. Bevor wir mit der nächsten Sitzung beginnen, ist
unser Körper vollständig, aber dann beginnen wir, unser Gehirn zu
zwingen, Dopamin hineinzupumpen, und wenn wir fertig sind und das
Dopamin zu verschwinden beginnt, erleiden wir Entzugserscheinungen. Das
sind keine körperlichen Schmerzen, sondern nur ein leeres Gefühl. Wir
sind uns nicht einmal bewusst, dass es existiert, aber es ist wie ein
tropfender Wasserhahn in unserem Körper.

Unser rationaler Verstand versteht es nicht, aber das muss er auch
nicht. Wir wissen nur, dass wir Pornografie wollen, und dass das Verlangen verschwindet wenn wir masturbieren. Doch die Befriedigung ist flüchtig, denn um das Verlangen zu stillen, brauchen wir mehr Pornografie. Sobald du zum Orgasmus kommst, geht das Verlangen wieder los und die Falle hält dich weiter fest. Eine Rückkopplungsschleife, wenn du sie
nicht durchbrichst!

Die Pornofalle ist vergleichbar mit dem Tragen von engen Schuhen, nur um
die Freude zu erleben, sie wieder auszuziehen. Es gibt drei Hauptgründe, warum
Nutzer das nicht so sehen können.

1.  Von Geburt an werden wir einer massiven Gehirnwäsche unterzogen, die
    uns sagt, dass Internetpornografie einfach eine weitere moderne
    Entwicklung ist, die die Printversion von Pornos ersetzt. Dieser
    Trugschluss wird mit der Wahrheit verpackt, dass Masturbation nicht
    schädlich ist, warum also sollten wir ihnen das nicht glauben?

2.  Da der körperliche Dopamin-Entzug keine wirklichen Schmerzen mit
    sich bringt, sondern lediglich ein leeres, unsicheres Gefühl, das
    von Hunger und normalem Stress nicht zu unterscheiden ist,
    manifestiert sich dieses Gefühl in einer Pornositzung, da wir genau
    zu diesen Zeiten dazu neigen, Internetpornografie zu suchen. Wir neigen
    dazu, dieses Gefühl als normal zu betrachten.

3.  Der Hauptgrund, warum Nutzer Internetpornografie nicht im wahren
    Licht sehen, ist jedoch, dass sie verkehrt herum funktioniert. Wenn du sie *nicht* konsumierst, erlebst du das Gefühl der Leere. Da der Prozess des Süchtigwerdens in den ersten Tagen unglaublich subtil und schrittweise verläuft, wird das Gefühl
    der Leere als normal angesehen und nicht auf die vorherige Sitzung
    geschoben. In dem Moment, in dem der Browser gestartet wird und
    du mit deiner Sitzung beginnst, bekommst du einen sofortigen Schub
    und wirst weniger nervös oder entspannter und daher bekommt Internetpornografie dafür den Dank.

Dieser umgekehrte Prozess macht es schwierig, von Drogen aller Art
loszukommen. Stell dir vor, wie panisch ein Heroinsüchtiger ist, wenn er
kein Heroin mehr hat. Jetzt stell dir vor, wie groß die Freude ist, wenn
er endlich eine Nadel in seine Vene stechen kann. Nicht-Heroinabhängige
leiden nicht unter diesem Gefühl der Panik.

Das Heroin lindert das Gefühl nicht, es verursacht es. Genauso wenig
leiden Nicht-Nutzer unter dem leeren Gefühl, Internetpornografie zu
brauchen oder unter Panik, wenn sie offline sind. Nicht-Nutzer können
nicht verstehen, wie Nutzer an zweidimensionalen Videos mit gedämpftem
Ton und abnormalen Körperproportionen Gefallen finden können. Letztendlich
können es auch die Nutzer nicht verstehen.

Wir reden davon, das Internetpornografie entspannend oder befriedigend sei,
aber wie kannst du zufrieden sein, wenn du nicht von vornherein
unzufrieden warst? Ein Nicht-Nutzer leidet nicht unter diesem
unbefriedigten Zustand, sondern ist nach einem Date ohne Sex völlig
entspannt, während der Nutzer das erst ist, wenn er sein \"kleines
Monster\" befriedigt hat.

## Ein Vergnügen oder eine Krücke?

Eine wichtige Erinnerung: Der Hauptgrund, warum es den Nutzern schwer fällt
aufzuhören, ist der Glaube, dass sie ein echtes Vergnügen oder eine
Krücke aufgeben. Es ist unabdingbar zu verstehen, dass du *überhaupt nichts*
aufgibst. Der beste Weg, die Feinheiten der Pornografiefalle zu verstehen, ist
ein Vergleich mit Essen. Die Gewohnheit, regelmäßig zu essen, führt
dazu, dass wir zwischendurch keinen Hunger verspüren, sondern nur, wenn
die Mahlzeit verschoben wird. Es gibt keinen körperlichen Schmerz, nur
ein leeres, unsicheres Gefühl, das als Hunger erkannt wird. Die
Befriedigung unseres Hungers ist eine sehr angenehme Erfahrung.

Pornografie scheint fast identisch zu sein, aber das ist sie nicht. Wie
beim Hunger gibt es keinen körperlichen Schmerz und der
Belohnungsmechanismus verhält sich ähnlich, aber gerade diese
Ähnlichkeit mit Essen gaukelt dem Nutzer ein echtes Vergnügen oder
eine Krücke vor. Obwohl Essen und Pornografie auf den ersten Blick sehr
ähnlich sind, sind sie in Wirklichkeit genau das Gegenteil.

-   Du isst, um zu überleben und um Energie für dein Leben zu bekommen,
    während Pornografie dein Mojo trübt und abbaut.

-   Essen schmeckt wirklich gut und Essen ist eine wirklich angenehme
    Erfahrung, die wir unser ganzes Leben lang genießen. Pornografie
    sabotiert deine Glücksrezeptoren und zerstört so deine
    Chancen, dein Leben zu meistern und dich glücklich zu fühlen.

-   Essen erzeugt keinen Hunger sondern lindert ihn wirklich, während die
    erste Pornografiesitzung das Verlangen nach Dopamin und weitere
    Sitzungen auslöst. Das erleichtert dich nicht, sondern sorgt dafür,
    dass du für den Rest deines Lebens leiden musst.

Ist Essen eine Gewohnheit? Wenn du das denkst, dann versuche mal, damit komplett aufzuhören! Essen als Gewohnheit zu bezeichnen, wäre so, als
würde man Atmen als Gewohnheit bezeichnen - beides ist
überlebenswichtig. Es stimmt zwar, dass Menschen die Angewohnheit haben,
ihren Hunger zu verschiedenen Zeiten mit unterschiedlichen
Nahrungsmitteln zu stillen, aber Essen selbst ist keine Gewohnheit.
Genauso wenig ist es die Pornografie. Der einzige Grund, warum ein Nutzer den
Browser startet, ist der Versuch, die leeren Gefühle zu beenden, die
die vorherige Sitzung hervorgerufen hat, und zwar zu verschiedenen
Zeiten und mit verschiedenen eskalierenden Genres.

Im Internet wird Pornografie häufig als Gewohnheit bezeichnet und der
Einfachheit halber spricht auch EasyPeasy von der \"Gewohnheit\". Sei
dir jedoch stets bewusst, dass Pornografie keine Gewohnheit ist, sondern
eine **Sucht!** Wenn wir anfangen, Pornografie zu benutzen, müssen wir uns
zwingen, damit zurechtzukommen. Ehe wir uns versehen, steigern wir uns
in immer bizarrere und schockierendere Pornografie hinein. Der Nervenkitzel
liegt in der Jagd, nicht im Töten, und das Dopamin verlässt den Körper
nach dem Orgasmus sehr schnell wieder, was erklärt, warum Nutzer den
Orgasmus hinauszögern wollen, indem sie zwischen mehreren
Browserfenstern und Tabs hin und her springen.

## Überschreiten der roten Linie

Wie bei jeder anderen Droge neigt der Körper dazu, eine Immunität gegen
die Wirkung der gleichen alten Clips zu entwickeln, und unser Gehirn will
mehr oder etwas anderes. Nach einer kurzen Zeitspanne, in der wir uns
denselben Clip ansehen, hört dieser auf, die Entzugserscheinungen zu
lindern, die die vorherige Sitzung verursacht hat. In diesem
Pornoparadies findet ein Tauziehen statt: Du willst auf der sicheren
Seite deiner \"roten Linie\" bleiben, aber dein Gehirn fordert dich auf,
auf den Clip mit der verbotenen Frucht zu klicken.

Du fühlst dich nach der Pornografiesitzung besser, aber du bist nervöser und
weniger entspannt als jemand, der nie damit angefangen hat, obwohl du in
einem vermeintlichen Pornoparadies lebst. Dieses Denken ist sogar noch
lächerlicher als das Tragen von engen Schuhen, denn im Laufe des Lebens
bleibt ein immer größeres Unbehagen zurück, nachdem du die Schuhe
ausgezogen hast. Weil die Nutzer wissen, dass das kleine Monster
gefüttert werden muss, bestimmen sie selbst den Zeitpunkt, und zwar
tendenziell zu vier Arten von Anlässen oder einer Kombination davon.\
Langeweile / Konzentration - Zwei komplette Gegensätze!\
Stress / Entspannung - Zwei komplette Gegensätze!

Welche magische Droge kann plötzlich genau den Effekt umkehren, den sie
Minuten zuvor hatte? Die Wahrheit ist, dass Pornografie weder Langeweile und
Stress lindert noch Konzentration und Entspannung fördert. Wenn du mal
darüber nachdenkst, welche anderen Anlässe gibt es in unserem Leben,
außer Schlaf? Wenn du darüber nachdenkst, dich auf andere Arten von
\"realistischer\" oder \"weniger harter\" Pornografie einzulassen, beachte bitte, dass
der Inhalt dieses Buches für sämtliche Pornografie gilt - egal ob Print, Webcams,
Pay-per-Views, Chat, Live-Shows usw. Der menschliche Körper ist das
raffiniersteste Objekt auf unserem Planeten, aber keine Spezies,
selbst die niedrigste Amöbe oder der niedrigste Wurm, überlebt, ohne den
Unterschied zwischen Nahrung und Gift zu kennen.

Durch natürliche Auslese haben unser Verstand und unser Körper
Techniken entwickelt, um Handlungen zu belohnen, die die Menschheit vermehren und erhalten. Sie sind nicht auf übernatürliche Reize vorbereitet, die größer, heller und verbotener sind als alles, was in der Natur vorkommt. Selbst das unschuldigste zweidimensionale Bild kann uns erregen. Aber schau es dir immer und immer wieder an, und du wirst es nicht mehr sein. Im wirklichen Leben sorgen Kontrollmechanismen
dafür, dass du etwas anderes tust, aber bei Internetpornografie gibt es keine
solchen Begrenzer, was dafür sorgt, dass du dein Leben in einem
virtuellen Harem verbringst!

Es ist ein Irrtum, dass körperlich und geistig schwache Menschen zu
Nutzern werden und die, die ihr erstes Mal abstoßend fanden und für immer geheilt sind, die Glücklichen sind. Manche sind auch einfach mental nicht darauf vorbereitet, den schweren Lernprozess zu durchlaufen, bei dem sie darum kämpfen, süchtig zu werden, Angst haben, \"erwischt\" zu werden oder nicht technisch versiert genug sind, um den Ikognitotab des Browsers zu finden. Der vielleicht tragischste Teil der ganzen
Angelegenheit betrifft Teenager, die geschickt darin sind, Material
zu finden und ihre Spuren zu verwischen, und die immer zahlreicher
werden.

Der Genuss von Internetpornografie ist eine Illusion. Man springt von einem
Genre zum anderen und hält sich lediglich innerhalb der \"roten
Linie\" der \"sicheren\" Porno-Genres auf, um den Dopamin-Kick zu
bekommen. Wie bei Heroinsüchtigen ist alles, was man wirklich genießt,
das Ritual, mit dem man seine Gelüste stillt.

## Das Hoch vom Tanz um die rote Linie

Selbst bei dem einen Clip, der bei einem hängen bleibt, lernen
Nutzer ständig, die schlechten und hässlichen Teile der Pornoclips
herauszufiltern. Selbst wenn es sich um einen Solo-Clip handelt, filtern
sie immer noch die Körperteile heraus, die sie am meisten ansprechen.
Tatsächlich finden manche sogar Gefallen an diesem "Tanz um die rote Linie", indem sie
das damit versuchen zu erklären, dass sie das \"weiche Zeug\" mögen und nicht süchtig nach
unnatürlichen Reizen sind. Aber frag mal einen Nutzer, der glaubt, dass
er sich an einen bestimmten Darsteller oder ein bestimmtes Genre hält:
*\"Wenn du deine normale Pornografie nicht bekommst und nur ein
unsicheres Genre bekommen kannst, würdest du dann aufhören zu masturbieren?\"*

Auf keinen Fall! Ein Nutzer wird zu allem masturbieren, zu ausufernden
Genres, unterschiedlichen sexuellen Orientierungen, ähnlich aussehenden
Darstellern, gefährlichen Umgebungen, schockierenden Beziehungen, zu
allem, um das kleine Monster zu sättigen. Am Anfang schmecken sie
furchtbar, aber mit der Zeit wirst du lernen, sie zu genießen. Nach
echtem Sex, nach einem langen Arbeitstag, bei Fieber, Erkältungen,
Grippe, Halsschmerzen und sogar während der Einweisung in Krankenhäuser
suchen die Nutzer nach leerer Erfüllung.

Mit Genuss hat das nichts zu tun. Wenn man Sex will, macht es keinen
Sinn, Zeit mit dem Laptop zu verbringen. Manche Nutzer finden es
erschreckend, wenn sie realisieren, dass sie drogenabhängig sind und glauben,
dass es dadurch noch schwieriger wird aufzuhören. In Wirklichkeit ist
das eine gute Nachricht, und das aus zwei wichtigen Gründen.

1.  Obwohl wir wissen, dass die Nachteile die Vorteile bei weitem
    überwiegen, glauben wir, dass Pornos etwas haben, das uns Spaß
    macht, oder dass sie wie eine Art Requisite wirken. Wir geben uns
    der Illusion hin, dass nach dem Aufhören eine Leere entsteht und
    bestimmte Situationen in unserem Leben nicht mehr dieselben sind. In
    Wirklichkeit bietet Pornografie nicht nur nichts, sie nimmt uns sogar
    etwas weg.

2.  Obwohl Internetpornos der stärkste Auslöser für Neuheits- und sexbasierte Dopaminausschüttungen ist, ist man aufgrund der
    Geschwindigkeit, mit der man süchtig wird, nie wirklich schlimm
    süchtig. Die eigentlichen Entzugserscheinungen sind so gering, dass
    die meisten Nutzer leben und sterben, ohne es zu merken.

Warum fällt es dann vielen Konsumenten so schwer, aufzuhören? Warum quälen sie sich monatelang und verbringen den Rest ihres Lebens damit, sich immer wieder zu seltsamen Zeiten danach zu sehnen? Die Antwort ist der zweite Grund:
Gehirnwäsche. Die Neurotransmittersucht ist leicht zu bewältigen. Die
meisten Nutzer können auf Geschäftsreisen oder auf Reisen tagelang ohne
Internetpornografie auskommen, ohne von Entzugserscheinungen beeinträchtigt zu
werden. Dein kleines Monster ist sich sicher, dass du deinen Laptop
aufklappst, sobald du in dein Hotelzimmer zurückkehrst. Du kannst deinen
unausstehlichen Kunden und deinen größenwahnsinnigen Manager aushalten,
weil du weißt, dass du dir den Kick später holen kannst.

## Die Raucher-Analogie

Eine gute Analogie ist die des Zigarettenrauchers. Wenn sie zehn Stunden
am Tag ohne Zigarette auskommen müssten, würden sie sich die Haare raufen, aber
viele Raucher kaufen sich ein neues Auto und halten davon Abstand darin zu rauchen.
Viele besuchen Theater, Supermärkte oder Kirchen und es bereitet ihnen
keine Probleme, nicht zu rauchen. Selbst in Zügen und Flugzeugen gibt es
keine Unruhen. Raucher sind fast froh, wenn jemand oder etwas sie vom
Rauchen abhält.

Nutzer verzichten bei Familienfeiern im Haus ihrer Eltern und anderen Veranstaltungen
automatisch auf Internetpornografie, ohne dass es ihnen Unannehmlichkeiten bereitet. Tatsächlich haben die meisten Nutzer längere Zeiträume, in denen sie ohne Anstrengung abstinent bleiben. Das kleine neurologische Monster ist leicht zu bewältigen, selbst wenn man noch süchtig ist. Es gibt Millionen von Nutzern, die ihr
ganzes Leben lang Gelegenheitskonsumenten bleiben, und doch sind sie genauso
süchtig wie starken Nutzer. Es gibt sogar starke Nutzer, die ihre
Sucht überwunden haben, aber ab und zu einen Blick darauf werfen, um die
Wasserrutsche zu schmieren, die sie beim nächsten Stimmungsumschwung
hinunterrutschen.

Wie gesagt, die eigentliche Pornosucht ist nicht das Hauptproblem,
sondern dient nur als Katalysator, um uns vom eigentlichen Problem
abzulenken - die Gehirnwäsche. Glaube aber nicht, dass die schlimmen
Auswirkungen von Internetpornografie übertrieben sind, wenn überhaupt, dann
werden sie leider unterschätzt. Gelegentlich kursieren Gerüchte, dass
die entstandenen Nervenbahnen ein Leben lang bestehen bleiben und die
richtige Mischung aus Zufall und Stimulus dich wieder die
lebenszerstörende Wasserrutsche hinunterschickt, aber das ist nicht
wahr. Unser Gehirn und unser Körper sind wunderbare Maschinen, die sich
innerhalb weniger Wochen erholen.

Es ist nie zu spät, aufzuhören! Ein kurzer Blick in Online-Communitys zeigt dir, dass Menschen jeden Alters ihr Leben (und das ihrer Partner) wieder in Gang bringen. Wie bei allem, was Menschen tun, gehen einige auf die nächste Stufe, üben sich in Samenerhalt und Karezza und machen ihre Partner durch die Differenzierung der amativen und
fortpflanzungsfördernden Seiten des Sex glücklicher als je zuvor.

Es mag ein Trost für lebenslange und starke Nutzer sein, dass es
für sie genauso einfach ist, aufzuhören wie für Gelegenheitskonsumenten,
und auf eine bestimmte Art ist es sogar einfacher. Je weiter es dich
nach unten zieht, desto größer ist die Erleichterung. Als ich aufhörte,
ging ich direkt von 180 auf *Null* runter und hatte nicht eine einzige
schlechte Laune. Tatsächlich war der Prozess sogar während der
Entzugsphase angenehm.

Aber zuerst müssen wir die Gehirnwäsche beseitigen.
