# Gehirnwäsche

Der zweite Faktor, warum wir mit dem Konsum beginnen, ist die
Gehirnwäsche. Um dies vollständig zu verstehen, müssen wir zuerst die
mächtigen Effekte von übernormalen Reizen untersuchen. Unser Gehirn
ist einfach nicht darauf vorbereitet, einen \"Online-Harem\" zu
erschaffen, in dem wir in fünfzehn Minuten zwischen mehr potenziellen
Partnern hin und her wechseln können, als unsere Vorfahren in mehreren
Generationen hatten.

In der Vergangenheit wurden viele falsche Ratschläge gegeben, wie zum Beispiel,
dass Masturbation zu Blindheit führt. Das, zusammen mit anderer Panikmache, 
hat es eindeutig übertrieben. Irrtümer wie diese sollten zu Recht von
der Wissenschaft widerlegt werden. Aber das Kind wurde mit dem Badewasser
ausgeschüttet; von klein auf wird unser Unterbewusstsein mit sexuellen
Botschaften und Bildern bombardiert, Zeitschriften und Werbung sind voll
von Anspielungen. Manche Popvideos sind extrem anzüglich, aber
verzweifle nicht, sondern mache es zu einem Spiel, herauszufinden,
welche Dinge sie dafür verwenden - der Schockwert, die Neuheit,
die Farbe, die Größe, das Tabu, usw. Ein solches Spiel kann sogar
Vorschulkindern beigebracht werden, um sie zu erziehen.

Im Kern lautet die Botschaft: *\"Das Wertvollste auf dieser Erde, mein
letzter Gedanke und meine letzte Handlung, wird der Orgasmus sein.\"*
Ist das übertrieben? Wenn du dir eine beliebige Fernseh- oder
Filmhandlung ansiehst, wirst du sehen, wie der amative (Berührung,
Geruch, Stimme) und der propagative (Orgasmus) Teil des Sex miteinander
vermischt werden. Die Auswirkungen davon werden von unserem Bewusstsein
nicht wahrgenommen, aber das Unterbewusstsein hat Zeit, sie zu
verarbeiten.

## Wissenschaftliche Argumentation

Es gibt Werbung in die andere Richtung, Angst vor sexueller Dysfunktion,
Motivationsverlust, die Bevorzugung virtueller Pornografie gegenüber echten
Frauen, YourBrainOnPorn.com und verschiedene Internet-Subkulturen, aber
diese Bewegungen halten die Menschen nicht wirklich vom Konsum ab.
Logisch gesehen sollten sie das, aber die simple Tatsache ist, dass sie
es nicht tun. Selbst die Gesundheitsrisiken, die in von Experten
geprüften Studien auf YourBrainOnPorn.com aufgeführt sind, reichen nicht
aus, um einen Jugendlichen davon abzuhalten, mit dem Konsum zu beginnen.

Ironischerweise ist die stärkste Kraft in dieser Verwirrung der Nutzer
selbst. Es ist ein Irrtum, dass Nutzer willensschwache oder
körperlich schwache Menschen sind. Man muss körperlich stark sein, um
mit einer Sucht fertig zu werden, nachdem man weiß, dass sie existiert.
Die vielleicht schmerzhafteste Sache ist, dass sie sich selbst als
erfolglose Verlierer und unerträgliche Introvertierte darstellen.
Wahrscheinlich könnte ein Freund oder eine Freundin viel interessanter
sein, wenn er/sie sich nicht selbst herunterputzen würde, weil er/sie sich
selbst befriedigt.

## Die Willenskraftmethode

Wer mit der Willenskraftmethode aufhört, gibt seinem eigenen Mangel an
Willenskraft die Schuld und ruiniert seinen Frieden und sein Glück. Es
ist eine Sache, an Selbstdisziplin zu scheitern und eine andere,
sich selbst zu verachten. Schließlich gibt es kein Gesetz, das
vorschreibt, dass du vor dem Sex immer hart sein musst, richtig erregt
und in der Lage, deinen Partner zu befriedigen. Wir arbeiten an einer
Sucht, nicht an einer Gewohnheit, und zu keinem Zeitpunkt argumentierst du
mit dir selbst, um mit einer Gewohnheit wie dem Golfspielen aufzuhören,
aber dasselbe bei der Pornografiesucht zu tun, ist normal? Warum?

Wenn du ständig einem übernormalen Reiz ausgesetzt bist, wird dein
Gehirn umprogrammiert. Deshalb ist es wichtig, dass du dich gegen diese
Gehirnwäsche wehrst, so als würdest du ein Auto von einem
Gebrauchtwagenhändler kaufen und höflich nicken, aber dem Mann kein Wort
glauben. Glaube also nicht, dass du so viel Sex wie möglich haben musst,
der immer besonders gut sein muss, und dass du in seiner Abwesenheit
Pornografie nutzen musst.

Lass dich auch nicht auf das Spiel mit der "sicheren" Pornografie ein, denn dein kleines
Monster hat dieses Spiel erfunden, um dich zu ködern. Sind Amateurpornos
von einer Behörde zertifiziert? Pornografische Seiten sammeln Daten von ihren
Nutzern und nutzen sie, um sich deren Bedürfnissen anzupassen. Wenn sie
einen Aufschwung in einer bestimmten Kategorie feststellen,
konzentrieren sie sich darauf und bringen so schnell wie möglich entsprechende Inhalte
heraus. Lass dich nicht von pädagogischen Absichten oder \"sicheren\"
Clips für Frauen täuschen. Fang an, dich zu fragen: *\"Warum mache ich
das? Muss ich das wirklich tun?\"*

**Nein, natürlich nicht!**

Die meisten Nutzer schwören, dass sie nur statische und Softpornos
schauen und es ihnen deshalb gut geht, obwohl sie in Wirklichkeit an der
Leine zerren und mit ihrer Willenskraft kämpfen, um den Versuchungen zu
widerstehen. Wenn sie das zu oft und zu lange tun, erschöpft das ihre
Willenskraft beträchtlich und sie beginnen, bei anderen Lebensprojekten
zu versagen, bei denen Willenskraft von großem Wert ist, wie z. B.
Sport, Diäten usw. Wenn sie in diesen Bereichen ständig versagen, fühlen
sie sich unglücklich und schuldig, was dazu führt, dass sie wieder in
die Pornografie abrutschen. Wenn sie das nicht tun, lassen sie ihre Wut
und Depression an geliebten Menschen aus.

Wenn du erst einmal süchtig nach Internetpornografie geworden bist, wird die
Gehirnwäsche noch verstärkt. Dein Unterbewusstsein weiß, dass das kleine
Monster gefüttert werden muss und verdrängt alles andere aus deinem
Kopf. Es ist die Angst, die die Menschen davon abhält, aufzuhören, die
Angst vor dem leeren, unsicheren Gefühl, das sie bekommen, wenn sie
aufhören, die Dopaminflut auszulösen. Nur weil du dir dessen nicht
bewusst bist, heißt das nicht, dass es nicht so ist. Du musst es genauso
wenig verstehen, wie eine Katze wissen muss, wo die Warmwasserrohre
sind - die Katze weiß einfach, dass es sich warm anfühlt, wenn sie an
einer bestimmten Stelle sitzt.

## Passivität

Die Passivität unseres Geistes und die Abhängigkeit von Autoritäten, die
zu einer Gehirnwäsche führen, sind die Hauptschwierigkeiten beim
Aufgeben von Pornografie. Unsere Erziehung durch die Gesellschaft, verstärkt
durch die Gehirnwäsche unserer eigenen Sucht und der einflussreichsten Menschen, die wir kennen - unsere Freunde, Verwandten und Kollegen. Die Phrase \"aufgeben\" ist
ein klassisches Beispiel für die Gehirnwäsche, weil sie ein echtes Opfer
impliziert. Die schöne Wahrheit ist, dass es nichts aufzugeben gibt; im
Gegenteil, du wirst dich von einer schrecklichen Krankheit befreien und
wunderbare positive Ergebnisse erzielen. Wir werden jetzt damit
beginnen, diese Gehirnwäsche zu beseitigen, indem wir nicht mehr von
\"aufgeben\" sprechen, sondern von \"aufhören\", \"stoppen\" oder, was
vielleicht die beste Formulierung ist, **entkommen!**

Das Einzige, was uns anfangs dazu bringt, zu konsumieren, sind andere
Menschen, die es tun, und das Gefühl, dass wir etwas verpassen. Wir
arbeiten hart daran, süchtig zu werden, finden aber nie heraus, was diese Leute
verpasst haben. Jedes Mal, wenn wir einen anderen Clip sehen, fühlen wir
uns bestätigt, dass etwas dran sein muss, sonst würden es die anderen
nicht tun und das Geschäft damit wäre nicht so groß. Selbst wenn sie sich die
Gewohnheit abgewöhnen, fühlen sich die Ex-Nutzer beraubt, wenn auf
Partys oder bei gesellschaftlichen Anlässen eine Diskussion über eine
sexy Entertainerin, eine Sängerin oder sogar einen Pornostar aufkommt.
"Sie müssen gut sein, wenn alle meine Freunde über sie reden, oder? Gibt es kostenlose Bilder von ihnen im Internet?"" Sie fühlen sich sicher, dass sie heute
Abend nur einen kurzen Blick darauf werfen wollen und ehe sie sich
versehen, sind sie wieder süchtig.

Die Gehirnwäsche ist extrem stark und du musst dir ihrer Auswirkungen
bewusst sein. Die Technologie entwickelt sich weiter und die Zukunft
wird immer schnellere Websites und Zugangsmethoden mit sich bringen. Die
Pornoindustrie investiert Millionen in die virtuelle Realität, damit sie
das nächste große Ding wird. Wir wissen nicht, wohin wir gehen und können
weder mit der heutigen Technologie noch mit dem, was noch kommen wird,
umgehen.

Wir sind dabei, die Gehirnwäsche abzuschaffen. Nicht der Nichtnutzer
wird beraubt, sondern der Nutzer, der sein ganzes Leben einbüßt an:

-   Gesundheit

-   Energie

-   Reichtum

-   Seelenfrieden

-   Selbstvertrauen

-   Mut

-   Selbstrespekt

-   Glücklichsein

-   Freiheit

Was haben sie von diesen erheblichen Opfern? **ABSOLUT NICHTS**,
abgesehen von der Illusion, den Zustand des Friedens, der Ruhe und der
Zuversicht wiederherstellen zu können, den der Nichtnutzer immer
genießt.

## Entzugserscheinungen

Wie bereits erklärt, glauben die Nutzer, dass sie Pornografie zum Vergnügen,
zur Entspannung oder für eine Art von Bildung nutzen. Der eigentliche
Grund ist die Linderung von Entzugserscheinungen. Unser Unterbewusstsein
lernt, dass Internetpornografie und Selbstbefriedigung zu bestimmten Zeiten
angenehm sind. Je mehr wir nach der Droge süchtig werden, desto größer
wird das Bedürfnis, die Entzugserscheinungen zu lindern, und desto
weiter zieht dich die subtile Falle nach unten. Dieser Prozess läuft so
langsam ab, dass du ihn gar nicht bemerkst. Die meisten jungen
Konsumenten merken erst, dass sie süchtig sind, wenn sie versuchen
aufzuhören, und selbst dann geben es viele nicht zu.

Nimm dieses Gespräch, das ein Therapeut mit Hunderten von Teenagern
geführt hat:\
Therapeut: \"Dir ist klar, dass Internetpornos eine Droge sind und der
einzige Grund, warum du sie konsumierst, ist, dass du nicht aufhören
kannst.\"\
Patient: \"Blödsinn! Ich genieße es, wenn ich es nicht täte, würde ich
aufhören.\"\
Therapeutin: \"Hör einfach eine Woche lang auf, um mir zu beweisen, dass
du es kannst, wenn du willst.\"\
Patient: \"Nicht nötig, ich genieße es. Wenn ich aufhören wollte, würde
ich es tun.\"\
Therapeut: \"Hör einfach eine Woche lang auf, um dir zu beweisen, dass
du nicht süchtig bist.\"\
Patient: \"Was soll das bringen? Es macht mir Spaß.\"\
Wie bereits erwähnt, neigen Konsumenten dazu, ihre Entzugserscheinungen
in Zeiten von Stress, Langeweile, Konzentration oder einer Kombination
davon zu lindern. In den folgenden Kapiteln werden wir auf diese Aspekte
der Gehirnwäsche eingehen.
