# Aspekte der Gehirnwäsche

Das große Monster der Pornografiefalle entsteht durch das Zusammentreffen vieler
Faktoren, darunter gesellschaftliche Einflüsse, Medien,
Gleichaltrige und die eigene innere Einstellung des Nutzers. Wenn es nicht
gelingt, die verschiedenen Trugschlüsse auseinanderzunehmen, während man die
Willenskraftmethode anwendet, führt das den Nutzer durch Gefühle der
Entbehrung zurück in die Falle. Die Dekonstruktion des eingebildeten Werts
von Pornografie ist entscheidend für den Erfolg, denn so kannst du erkennen,
wo du betrogen wirst!

Ein wichtiger Punkt ist die Verbindung zwischen Gehirnwäsche und Angst.
Es ist die Angst vor ***zukünftigen Entzugserscheinungen***, die die
Entzugserscheinungen hervorruft. Angst ist die Entzugserscheinung selbst. Erinnere dich, als du Entzugserscheinungen wie schwitzige Handflächen,
Kurzatmigkeit, Schlafprobleme und die Unfähigkeit, klar zu denken,
hattest. Denke jetzt an ähnliche Situationen, in denen du so fühltest: Vorstellungsgespräche, Nervosität in der Nähe einer attraktiven
Person, Reden in der Öffentlichkeit usw. Das sind die gleichen
Gefühle, die die Angst auslöst. Einfach ausgedrückt: Wie kann eine
physische Droge noch Monate nach dem Absetzen süchtig machen? Es muss
doch psychisch sein, oder?

## Stress

Nicht nur große Tragödien im Leben, sondern auch kleine Belastungen
treiben den Nutzer einen Schritt weiter in den verbotenen Bereich, der
vorher ausgeschlossen war. Dazu gehören Geselligkeiten, Telefonanrufe,
die Ängste der Hausfrau mit kleinen Kindern und viele andere. Nehmen wir
als Beispiel Telefonanrufe, insbesondere die von Geschäftsleute. Die meisten
Anrufe kommen nicht von zufriedenen Kunden oder von deinem Chef, der
dich beglückwünscht, sondern kommen aus Verärgerung. Wenn er nach
Hause kommt und das alltägliche Familienleben mit schreienden Kindern
und den emotionalen Ansprüchen des Partners vorfindet, fantasiert
der Nutzer, wenn er es nicht ohnehin schon tut, von der Erleichterung,
die die Pornografie in dieser Nacht verspricht. Unbewusst erleidet er
Entzugserscheinungen und ist geschwächt und unvorbereitet auf
zusätzliche Belastungen. Die Entzugserscheinungen werden zum Teil
gleichzeitig mit dem normalen Stress gelindert, so dass die Gesamtsumme
reduziert wird und der Nutzer einen vorübergehenden Schub erhält. Der
Schub ist keine Illusion, der Nutzer fühlt sich tatsächlich besser als
vorher, aber er ist angespannter, als er es als Nichtnutzer wäre.

Das folgende Beispiel soll dich nicht schockieren - EasyPeasy
verspricht keine solche Behandlung - sondern soll verdeutlichen, dass
Pornografie deine Nerven eher zerstört als entspannt.

Stell dir vor, du kommst an einen Punkt, an dem du nicht mehr erregt
werden kannst, selbst wenn du einen sexuell sehr attraktiven Partner
hast. Halte einen Moment inne und versuche dir ein Leben vorzustellen, in dem eine sehr hübsche und charmante Person mit den virtuellen
Pornostars aus deinem \"Harem\" um deine Aufmerksamkeit konkurrieren
muss und dabei versagt. Stell dir den Gemütszustand einer Person vor, die, nachdem sie davor gewarnt wurde, weiter konsumiert und stirbt, ohne jemals echten Sex
mit diesem charmanten und willigen Partner zu haben. Es ist leicht,
diese Menschen als Verrückte abzutun, aber solche Geschichten sind nicht ausgedacht, sondern das, was die furchtbare Neuheit der Pornografiedroge mit deinem
Gehirn macht. Je mehr du durch das Leben gehst, desto mehr wird dir der
Mut genommen und desto mehr machst du dir vor, dass Pornografie das Gegenteil
bewirkt.

Wurdest du schon einmal von Panik übermannt, wenn aus heiterem Himmel
das WiFi nicht mehr funktioniert oder zu langsam ist? Nicht-Nutzer
leiden nicht darunter, denn Internetpornografie verursacht dieses
Gefühl. Im Laufe deines Lebens zerstört sie systematisch deine Nerven
und deinen Mut, so dass DeltaFosB eine mächtige neuronale Wasserrutsche
bildet, die nach und nach deine Fähigkeit, "Nein" zu sagen, zerstört. Wenn erstmal die die Potenz abgetötet wurde, glaubt der Nutzer, dass Pornografie sein neuer Partner ist, und ist unfähig, das Leben ohne sie zu meistern.

Internetpornos beruhigen deine Nerven nicht, sie zerstören sie langsam.
Eine der großen Errungenschaften beim Brechen mit dieser Sucht ist die
Rückkehr deines natürlichen Selbstvertrauens und deiner
Selbstsicherheit.

Du musst dich nicht mehr nach deiner Fähigkeit, einen Partner zu
befriedigen, bewerten - das ist keine Freiheit. Aber diese Freiheit
kannst du nicht erlangen, wenn du die Dopaminrutsche weiterhin auf eine
Art und Weise schmierst, die dein Glück und deine Libido untergräbt,
indem du das gleiche destruktive Verhalten wiederholst.

## Langeweile

Wenn du wie viele andere Menschen bist, bist du, sobald du ins Bett gehst,
schon auf deiner Lieblingspornoseite und nimmst es gar nicht wahr, bis du daran erinnert wirst. Es ist zur zweiten Natur geworden. Dass Pornografie die Langeweile vertreibt, ist ein weiterer Irrtum, denn Langeweile ist eine Geisteshaltung, die nur dann auftritt, wenn du lange enthaltsam warst oder versuchst, deinen Konsum zu reduzieren.

In Wirklichkeit ist es so: Wenn du der unnatürlichen Anziehungskraft
von Internetpornografie verfallen bist und dann versuchst, davon loszukommen,
hast du das Gefühl, dass dir etwas fehlt. Wenn du dich mit etwas
beschäftigst, das nicht stressig ist, kannst du lange Zeit durchhalten,
ohne dass dich die Abwesenheit dieser Droge stört. Wenn du aber gelangweilt
bist, gibt es nichts, was dich ablenkt, also fütterst du das Monster.
Wenn du dem nachgibst und nicht versuchst, damit aufzuhören oder es
einzuschränken, wird sogar das Einschalten des privaten Browsers
unbewusst. Dieses Ritual wird automatisch; wenn er
versucht, sich an die Sitzungen der letzten Woche zu erinnern, kann er
das nur zu einem kleinen Teil, wie z.B. die allerletzte Sitzung oder
die nach einer langen Abstinenz.

Die Wahrheit ist, dass Pornografie die Langeweile indirekt verstärkt, denn
Orgasmen machen träge und anstatt einer energetischen Aktivität
nachzugehen, neigen die Nutzer dazu, gelangweilt herumzuliegen
und ihre Entzugserscheinungen zu lindern. Es ist wichtig, der
Gehirnwäsche entgegenzuwirken, denn ein Nutzer der sich Pornografie bei Langeweile anschaut, ringt seinem Gehirn bei, Pornos als interessant anzusehen.
Ebenso wurde uns eine Gehirnwäsche verpasst, die uns glauben lässt, dass
Sex, selbst schlechter Sex, zur Entspannung beiträgt. Es ist eine
Tatsache, dass Paare, die traurig sind oder unter Stress stehen, Sex
haben wollen. Da es dabei keine Unterscheidung zwischen amativem und
propagativem Sex gibt, wollen sie nach dem obligatorischen Orgasmus schnell wieder voneinander weg. Hätte das Paar einfach beschlossen, sich zu umarmen, zu reden oder zu kuscheln und schlafen zu gehen, hätten sie sich erleichtert gefühlt.

## Konzentration

Selbstbefriedigung und Sex sind der Konzentration nicht förderlich. Wenn
du dich konzentrieren willst, versuchst du automatisch, Ablenkungen zu
vermeiden. Wenn man sich also konzentrieren will, denkt man nicht einmal
nach, sondern öffnet automatisch den Browser, füttert das kleine Monster und
beendet das Verlangen teilweise. Wenn man dann mit der anstehenden Sache weitermacht, hat man bereits vergessen, dass man einen Porno angesehen hat. Nach jahrelanger Dopaminüberflutung des Gehirns verändern sich Fähigkeiten wie das Abrufen von Informationen, Planung und Impulskontrolle.

Du wirst auch dazu getrieben, dir für die nächste Sitzung etwas Neues zu
beschaffen, da der gleiche Stoff nicht genug Dopamin und Opiate erzeugt.
Also musst du die Straßen des Internets nach Neuem durchstreifen und
gegen den Drang ankämpfen, die Grenze zu schockierendem Material zu
überschreiten, was wiederum mehr Stress erzeugt und dich nach der
Beendigung unerfüllt lässt.

Die Konzentration wird auch dadurch beeinträchtigt, dass die
Dopaminrezeptoren durch natürliche Toleranz aufgrund der großen Schübe
abgebaut werden, wodurch der Nutzen kleinerer Dopaminschübe durch
natürliche Dinge, verringert wird. Deine Konzentration und
Inspiration werden durch die Verringerung dieses Prozesses erheblich
gesteigert. Für viele ist es der Konzentrationsaspekt, der sie daran
hindert, mit der Willenskraftmethode Erfolg zu haben. Sie könnten die
Reizbarkeit und schlechte Laune in Kauf nehmen, aber das Unvermögen,
sich auf etwas Schwieriges zu konzentrieren, sobald die Krücke weg ist,
ruiniert viele.

Der Konzentrationsverlust, unter dem die Nutzer leiden, wenn sie
versuchen zu fliehen, ist nicht auf die Abwesenheit von Sex, geschweige
denn von Pornografie zurückzuführen. Man hat mentale Blockaden, wenn man
süchtig ist, und was macht man, wenn man eine mentale Blockade hat? Man
schaltet den Browser ein; aber das löst die Blockade nicht, also macht man was?
Man tut, was man tun muss und macht weiter, genau wie Nicht-Nutzer.

Wenn du ein Nutzer bist, wird nichts auf diesen Fakt geschoben: Nutzer
haben nie Erektionsstörungen, nur gelegentliche Ausfälle. In dem Moment,
in dem du mit dem Konsum aufhörst, wird alles, was schief läuft, darauf
geschoben, dass du aufgehört hast. Wenn du jetzt eine mentale Blockade
hast, sagst du dir: *\"Wenn ich jetzt nur meinen Harem checken könnte,
wären alle meine Probleme gelöst\"*. Dann fängst du an, deine
Entscheidung, aufzuhören und der Sklaverei zu entkommen, in Frage zu
stellen.

Wenn du glaubst, dass Pornografie eine echte Konzentrationshilfe ist, wird
das Grübeln darüber garantieren, dass du dich nicht konzentrieren
kannst. Zweifel, nicht die körperlichen Entzugserscheinungen, erschafft das
Problem. Denke immer daran, dass es der Nutzer ist, der unter den Entzugserscheinungen leidet, nicht der Nichtnutzer.

## Entspannung

Die meisten Nutzer denken, dass Pornografie ihnen hilft, sich zu entspannen.
Das tut es aber nicht. Die hektische Suche nach dem Kick in den
\"dunklen Gassen des Internets\" und das innere Zerren an der Leine, um
die rote Linie nicht zu überschreiten, klingen nicht gerade nach einer
entspannenden Tätigkeit.

Wenn die Nacht nach einem Ausflug an einen neuen Ort oder einem langen
Tag hereinbricht, setzen wir uns zum Entspannen hin, stillen unseren
Hunger und Durst und sind rundum zufrieden. Der Nutzer ist es nicht,
denn er hat einen anderen Hunger, den er stillen muss. Pornografie ist das
Sahnehäubchen auf dem Kuchen, aber in Wirklichkeit ist es das \"kleine
Monster\", das gefüttert werden will. Die Wahrheit ist, dass der
Süchtige nie ganz entspannt sein kann und dass es im Laufe des Lebens
immer schlimmer wird. Nimm einen Online-Kommentar von einem Ex-Nutzer:\
*\"Ich habe wirklich geglaubt, dass ich einen bösen Dämon in mir hatte.
Heute weiß ich, dass ich das hatte, aber es war kein angeborener Fehler
in meinem Charakter, sondern das kleine Internetpornomonster, das das
Problem verursachte. Zu der Zeit dachte ich, ich hätte alle Probleme
der Welt, aber wenn ich auf mein Leben zurückblicke, frage ich mich, worin der 
große Stress bestand. Alles andere in meinem Leben hatte ich unter
Kontrolle, das einzige, was mich kontrollierte, war die Pornosklaverei.
Das Traurige ist, dass ich meine Kinder bis heute nicht davon überzeugen
kann, dass es die Sklaverei war, die mich so reizbar gemacht hat.\"*

Jedes Mal, wenn ich höre, wie ein Pornografiesüchtiger versucht, seine Sucht
zu rechtfertigen, lautet die Botschaft: *\"Oh, es hilft mir, mich zu
entspannen.\"* Im Internet habe ich von einem alleinerziehenden Vater
gelesen, dessen sechsjähriger Sohn nachts nach einem Gruselfilm
angsterfüllt in das Bett seines Vaters wollte, aber der Vater weigerte sich, damit
er seine Sitzung haben und stundenlang \"edgen\" konnte.

Hier noch eine Analogie zum Rauchen: Vor ein paar Jahren drohten die
Adoptionsbehörden damit, Raucher an der Adoption von Kindern zu hindern.
Ein Mann rief wütend an. *\"Sie liegen völlig falsch\"*, sagte er.
*\"Ich weiß noch, wie ich als Kind bei Streitigkeiten mit meiner Mutter
gewartet habe, bis sie sich eine Zigarette angezündet hatte, weil sie
dann entspannter war.\"* Warum konnte der Mann nicht mit seiner Mutter
reden, wenn sie gerade keine Zigarette rauchte?

Warum sind manche Nutzer so gestresst, wenn sie ihren Kick
nicht bekommen, selbst nach echtem Sex? Ein Erlebnis, das online gestellt wurde,
berichtet von einem Mann, der in der Werbebranche arbeitet und jederzeit
9er und 10er für Verabredungen verfügbar hat, aber das Interesse daran
verliert, sie zum Essen auszuführen, weil Internetpornografie viel einfacher
ist, keine Ausgaben für ein Restaurant erfordet oder am Ende eines
Abends kein \"Nein\" davon zu erwarten ist. Warum sollte er sich die Mühe machen,
wenn sein kleines Monster ihn sich nach dem risikoarmen und lohnenswerten Plan sehnen lässt, der ihm zur Verfügung steht?

Warum sind dann Nicht-Nutzer völlig entspannt? Warum sind die Nutzer
nicht in der Lage, sich einen oder zwei Tage lang ohne einen Fix zu
entspannen? Lies die Erfahrung eines Nutzers, der einen
Abstinenzschwur abgelegt hat und aufhört, und du wirst feststellen, dass
er mit Versuchungen zu kämpfen hat und offensichtlich überhaupt
nicht entspannt ist, wenn er das \"einzige Vergnügen\", das er
\"genießen darf\", nicht haben kann. Er hat vergessen, wie es ist,
völlig entspannt zu sein. Pornografie kann mit einer Fliege verglichen werden,
die in einer Kannenpflanze gefangen ist. Am Anfang frisst die Fliege den
Nektar, aber irgendwann beginnt die Pflanze, die Fliege zu fressen, ohne
dass sie es merkt.

Ist es nicht an der Zeit, dass du aus der Pflanze herauskletterst?

## Energie

Die meisten Nutzer sind sich der immer größer werdenden Auswirkungen auf das Belohnungs- und Sexualsystem ihres Gehirns bewusst, die die anauernde Suche nach neuer und eskalierender Pronografie mit sich bringt. Sie sind sich jedoch nicht bewusst, welche Auswirkungen dies auf ihr Energieniveau hat.

Eine der Feinheiten der Pornografiefalle ist, dass die Auswirkungen auf
unseren Körper und unsere Psyche so allmählich und unmerklich ablaufen,
dass wir sie nicht wahrnehmen und sie als normal ansehen. Der Effekt ist
ähnlich wie bei schlechten Essgewohnheiten: Wir sehen uns Menschen an,
die stark übergewichtig sind, und fragen uns, wie sie es sich erlauben
konnten, diesen Zustand zu erreichen. Aber stell dir vor, es wäre über
Nacht passiert: Du wärst schlank und muskulös ins Bett gegangen und
hättest kein Gramm Fett an deinem Körper und wachst auf und findest dich
dick, aufgedunsen und dickbäuchig vor. Anstatt ausgeruht und voller Energie
aufzuwachen, fühlst du dich elend, lethargisch und kannst kaum die Augen
öffnen.

Du hast Panik und fragst dich, was für eine schreckliche Krankheit du
dir über Nacht eingefangen hast, und doch ist die Krankheit genau
dieselbe. Die Tatsache, dass es zwanzig Jahre gedauert hat, bis du zu diesem Punkt gekommen bist, ist irrelevant. Bei Pornografie ist es das Gleiche. Wenn es möglich
wäre, deinen Geist und deinen Körper sofort in die Zukunft zu versetzen,
um dir einen direkten Vergleich zu geben, wie du dich fühlen würdest,
wenn du nur drei Wochen lang mit Pornografie aufhören würdest, wäre das alles,
was du brauchst, um überzeugt zu sein. Du würdest dich fragen, ob es sich wirklich so gut anfühlen kann, oder, noch besser: *\"Bin ich wirklich so tief gesunken?* Du würdest dich nicht nur gesünder und energiegeladener fühlen, sondern auch viel mehr Selbstvertrauen ausstrahlen und eine höhere Konzentrationsfähigkeit haben.

Der Mangel an Energie, Müdigkeit und alles, was damit zusammenhängt,
wird gerne unter den Teppich des \"Älterwerdens\" gekehrt. Freunde und
Kollegen, die ebenfalls einen sesshaften Lebensstil führen, verstärken
die Normalisierung dieses Verhaltens noch. Der Glaube, dass Energie ein
ausschließliches Vorrecht von Kindern und Teenagern ist und dass das
Alter in den Zwanzigern beginnt, ist ein weiteres Symptom der
Gehirnwäsche, ebenso wie die Unkenntnis über Ess- und
Bewegungsgewohnheiten als Folge der verstärkenden Wirkung der
Dopamin-Desensibilisierung.

Kurz nachdem du mit der Pornografie aufgehört hast, wird dich das vernebelnde und
drückende Gefühl verlassen. Der Punkt ist, dass du mit Pornografie ständig
deine Energie verbrauchst und dabei die neurologische Chemie deines
Belohnungskreislaufs durcheinander bringst. Anders als beim Aufhören mit Rauchen, 
wo die körperliche und geistige Gesundheit nur allmählich wiederhergestellt werden kann, erzielst du bei Qufhören mit Pornografie vom ersten Tag an hervorragende Ergebnisse. Das \"kleine Monster\" zu töten und die Wasserrutschen zu schließen, braucht ein bisschen Zeit,
aber die Wiederherstellung deines Belohnungskreislaufs ist bei Weitem
nicht so langsam wie die Rutsche in die Grube. Wenn du das Trauma der
Willenskraftmethode durchmachst, wird jeder Gewinn an Gesundheit oder
Energie durch die Depression, die du durchmachst, wieder zunichte
gemacht. Leider ist es nicht möglich, dass EasyPeasy dich in deinen Geist, den du in drei Wochen haben wirst, versetzt, aber du kannst das! Du weißt instinktiv,
dass das, was dir gesagt wird, richtig ist, **du musst nur deine
Vorstellungskraft benutzen!**

## Sessions nach Treffen mit Freunden

Das ist eine Fehlinformation, die scheinbar Sinn macht, aber nicht
stimmt. Um deinen Appetit zu zügeln, isst du zu Hause, bevor du in
ein Restaurant oder auf eine Party gehst? Genau das tust du mit
Sitzungen vor geselligen Abenden: Du siehst müde aus und bist nicht in
Bestform. Die weit verbreitete Einführung von Pick-up-Techniken hat zu
einem Leistungs-, Pick-up- und Erfolgsdruck geführt. Wenn du versuchst,
deine Schmetterlinge mit Pornografie und Drogen zu ertränken, wird das
Problem auf lange Sicht nur noch schlimmer. Ich persönlich mag ein
bisschen Angst, um mich zu fokussieren und zu engagieren, und mich
geistig und körperlich mit einem Orgasmus zu ermüden, wird mir nicht
helfen.

Diese Sitzungen vor geselligen Abenden werden durch zwei oder mehr
unserer üblichen Gründe für die Suche nach Vergnügen und Lust ausgelöst;
Im Grunde sind soziale Treffen sowohl stressig als auch entspannend. Das
mag wie ein Widerspruch erscheinen, aber jede Form der Geselligkeit kann
stressig sein, selbst mit Freunden: Man will einerseits man selbst und
andererseits völlig entspannt sein. Es gibt viele Anlässe, bei denen
mehrere Faktoren gleichzeitig auftreten, zum Beispiel beim Autofahren,
denn schließlich geht es um dein Leben. Es ist anstrengend und du musst
dich über einen längeren Zeitraum konzentrieren. Aber du musst dir
dieser Faktoren nicht bewusst sein, da dein Unterbewusstsein die
Nachricht bereits empfängt. Wenn du im Stau stehst oder dich auf einer
langen Autobahnfahrt langweilst, versprichst du dir vielleicht eine
Sitzung, sobald du zu Hause ankommst.

Ein weiteres gutes Beispiel ist ein erstes Date, bei dem dein Verstand
dir Fragen über die Person stellt, die du treffen wirst. Wenn du die
Person dann in natura triffst und die Begeisterung nachlässt, fühlst du
dich zu entspannt und dann schuldig, weil du dich so fühlst. Das
Tauziehen hat begonnen, *\"Ich will Sex oder so schnell wie möglich hier
raus\"*, und bereitet dich auf die Pornografie nach dem Date vor.

Selbst wenn das Date gut gelaufen ist und du Stunden später wieder bei
ihr/ihm bist, wirst du nicht zufriedengestellt werden, wenn dein einziges Ziel der Orgasmus ist. Ein anderes Mal fährst du allein nach Hause
und denkst nur an deinen Online-Harem, anstatt dich für deine Bemühungen
selbst zu beglückwünschen. Du kannst darauf wetten, dass jemand in dieser Lage
definitiv eine Sitzung abhält, wenn er zu Hause ankommt, und oft denken wir nach
solchen Nächten, wenn wir aufwachen und eine unangenehme Leere
verspüren, dass wir diese am meisten vermissen werden, wenn wir darüber
nachdenken, mit Pornografie aufzuhören. Wir denken, dass das Leben nie wieder
so angenehm sein wird. In Wirklichkeit ist es dasselbe Prinzip: Die
Sitzungen dienen lediglich dazu, die Entzugserscheinungen zu lindern,
wobei das Bedürfnis zu bestimmten Zeiten größer ist als zu anderen und
die Wasserrutsche für den nächsten Auslösereiz geschmiert wird.

Damit das klar ist: Nicht Internetpornografie und Harembewohner sind etwas
Besonderes, sondern die Gelegenheit. Sobald das Bedürfnis nach Pornografie
wegfällt, werden solche Gelegenheiten angenehmer und stressige
Situationen weniger stressig.
