# Was gebe ich auf?

**Absolut gar nichts!** Es ist schwierig, Pornografie aufzugeben, weil wir
Angst haben, dass wir um unser Vergnügen oder unsere Stütze gebracht
werden. Die Angst, dass bestimmte angenehme Situationen nie wieder ganz
so sein werden wie vorher. Die Angst, mit stressigen Situationen nicht
umgehen zu können. Mit anderen Worten: Es sind die Auswirkungen einer
Gehirnwäsche, die uns vorgaukelt, dass Sex und damit auch der Orgasmus
ein Muss für alle Menschen ist. Mehr noch, es ist der Glaube, dass wir
etwas in der Internetpornografie brauchen und dass wir uns selbst verleugnen
und eine Leere schaffen, wenn wir aufhören sie zu benutzen.

Mache dir folgendes dringend bewusst: Pornografie füllt keine Leere, es schafft eine!

Unsere Körper sind die ausgeklügeltsten Objekte auf dem Planeten. Ob
du nun an intelligentes Design, natürliche Auslese oder eine Kombination
von beidem glaubst - unsere Körper sind tausendmal effektiver als der
Mensch selbst! Wir sind nicht in der Lage, die kleinste lebende Zelle oder die
Wunder des Sehvermögens, der Fortpflanzung und der verschiedenen
miteinander verknüpften Systeme in unserem Körper oder Gehirn zu
erschaffen. Hätte der Schöpfer oder der Prozess gewollt, dass wir mit
unnormalen Reizen umgehen, wären wir mit anderen Belohnungssystemen
ausgestattet worden. Unser Körper ist mit ausfallsicheren Warnsystemen
ausgestattet, die wir auf eigene Gefahr ignorieren.

## Du gibst nichts auf

Wenn du das kleine Monster aus deinem Körper und die Gehirnwäsche (das
große Monster) aus deinem Kopf entfernt hast, wirst du weder oft
masturbieren noch Internetpornografie dafür benutzen wollen. Es gibt viel, was wir wissen und was wir nicht wissen, wenn es um Pornografiesucht geht. Viele in der
medizinischen Gemeinschaft haben kein Konzept, um jemanden als
pornografiesüchtig zu bestimmen. Viele der gemeldeten Symptome werden
fälschlicherweise anderen Ursachen zugeschrieben. Es ist nicht so, dass
Pornografienutzer generell dumm sind, es ist nur so, dass sie ohne Pornografie
unglücklich sind. Sie befinden sich in einer Zwickmühle: Wenn sie abstinent sind, fühlen sie sich unglücklich, weil sie keine Pornografie konsumieren können, und wenn sie sie doch nutzen, sind sie unglücklich, weil sie sich schuldig fühlen und anfangen, sich selbst zu verachten. Wenn sie Symptome wie Rückenschmerzen oder PIED bekommen, sind sie hin- und hergerissen entweder Verantwortung zu übernehmen und wegzuschauen.

Noch eine Analogie zum Rauchen: Wir alle kennen Raucher, die Ausreden
finden, um heimlich einen Zug zu nehmen, und wir sehen die wahre Sucht
in diesem Handeln. Süchtige tun das nicht zum Vergnügen, sondern weil sie
sich ohne dies unglücklich fühlen.

Für viele endete ihre erste sexuelle Erfahrung mit einem Orgasmus, so
dass sie glauben, dass sie Sex ohne Orgasmus nicht genießen können. Für
Männer werden Pornos als Hilfsmittel für den Sex vermarktet, manchmal
sogar als Unterricht, um mehr Selbstvertrauen während des Aktes zu bekommen. Das ist
Unsinn, denn die Konditionierung zu unnormalen Reizen führt nur dazu, dass sie abnimmt.

Es gibt nicht nur nichts, was man aufgeben müsste. Es gibt
sogar massive positive Effekte. Wenn Nutzer ans Aufhören denken,
konzentrieren sie sich meist auf Gesundheit und Potenz. Das sind
berechtigte und wichtige Gründe, aber ich persönlich glaube, dass die
größten Vorteile psychologischer Natur sind:

-   Die Rückkehr deines Vertrauens und Mutes.

-   Freiheit von der Sklaverei.

-   Nicht länger schreckliche schwarze Schatten im Hinterkopf zu haben
    und dich selbst zu verachten.

## Leere, die Leere, die schöne Leere!

Stell dir vor, du hast ein Fieberbläschen im Gesicht. Du gehst zum
Apotheker und er gibt dir eine kostenlose Salbe zum Ausprobieren. Du
trägst die Salbe auf und sie verschwindet sofort. Eine Woche später
taucht sie wieder auf, also gehst du wieder in die Apotheke und fragst,
ob sie noch mehr Salbe haben. Der Apotheker sagt: *\"Klar, behalte die
Tube, du brauchst sie vielleicht später.\"*

Du trägst die Salbe auf und schwupps, ist die Wunde wieder verschwunden.
Aber jedes Mal, wenn die Wunde wiederkommt, wird sie größer und
schmerzhafter, und die Abstände werden immer kürzer. Schließlich bedeckt
die Wunde dein ganzes Gesicht, ist unerträglich schmerzhaft und kommt
alle halbe Stunde wieder. Du weißt, dass die Salbe sie vorübergehend
beseitigen wird, aber du machst dir große Sorgen. Wird sich die Wunde
irgendwann auf deinen ganzen Körper ausbreiten? Wird der Abstand dazwischen ganz
verschwinden? Du gehst zu deinem Arzt und der kann es nicht heilen, also
probierst du andere Dinge aus, aber außer der Salbe hilft nichts.

Inzwischen bist du völlig abhängig von der Salbe und gehst nie mehr aus
dem Haus, ohne sicherzugehen, dass du eine Tube dabei hast. Wenn du ins
Ausland fährst, stellst du sicher, dass du gleich mehrere Tuben eingepackt
hast. Zusätzlich zu deinen Sorgen um deine Gesundheit berechnet dir der
Apotheker hundert Dollar pro Tube. Du hast keine andere Wahl, als zu
zahlen.

Du stolperst über einen Artikel, in dem es um dieses Thema geht, und
erfährst, dass es nicht nur dir so geht, sondern dass viele Menschen
unter demselben Problem leiden. Tatsächlich haben Mediziner
herausgefunden, dass die Salbe die Wunde nicht wirklich heilt, sondern
sie nur unter die Hautoberfläche zwingt. Es ist die Salbe, die das
Wundsein verursacht hat. Alles, was du tun musst, um das Wundsein
loszuwerden, ist, die Salbe nicht mehr zu benutzen, und es wird mit der
Zeit verschwinden.

Würdest du die Salbe weiter benutzen? Würde es Willenskraft erfordern,
die Salbe nicht zu benutzen? Wenn du dem Artikel nicht glauben würdest,
könntest du ein paar Tage lang Angst haben, aber sobald du merkst, dass
die Wunde besser wird, würde das Bedürfnis oder der Wunsch, die Salbe zu
benutzen, verschwinden. Würdest du dich unglücklich fühlen? Nein,
natürlich nicht! Du hattest ein schreckliches Problem, von dem du
dachtest, es sei unheilbar, aber jetzt hast du die Lösung gefunden.
Selbst wenn es ein Jahr dauern würde, bis die Wunde verschwindet,
würdest du jeden Tag, an dem es besser wird, daran denken, wie großartig
du dich fühlst. Das ist der Zauber des Aufhörens mit Pornografie.

Die Wunde ist nicht der Schmerz im Körper, der Mangel an normaler Lust,
die nachlassende Erregung, die schwindende Penetration, die
verschwendete Zeit, die du mit zweidimensionalen Bildern verbringst, das
Gefühl der Anspruchsverletzung, die Verachtung der Leute, die dich
erwischt haben, oder noch schlimmer, die Verachtung deiner selbst. All
das kommt noch zu dem wunden Punkt hinzu.

Die Wunde lässt uns vor all diesen Dingen die Augen verschließen, es ist
dieses panische Gefühl, einen Fix zu wollen. Nicht-Nutzer leiden nicht unter diesem Gefühl. Das Schlimmste, was wir erleiden können, ist die Angst, und der größte Gewinn ist es, diese Angst loszuwerden. Sie wird durch die erste Sitzung ausgelöst und durch jede weitere verstärkt und verursacht.

Manche Nutzer sind \"glücklich\", geblendet von ihren gerissenen kleinen Monstern und durchleben denselben Albtraum immer wieder, indem sie falsche Argumente vorbringen, um ihre Dummheit zu rechtfertigen.

*Es ist so schön frei zu sein!*
