# Zeit sparen

Wenn eingefleischte Nutzer aufhören wollen, werden meist gesundheitliche Gründe,
die Religion und das Stigma des Partners als Hauptgründe genannt. Ein
Teil der Gehirnwäsche dieser schrecklichen Droge ist die schiere
Sklaverei, die sie mit sich bringt. Der Mensch hat hart dafür gekämpft,
die Sklaverei in vielen Teilen der Welt abzuschaffen, und doch verbringt
der Nutzer sein Leben in selbst auferlegter Sklaverei. Er ist sich
der Tatsache nicht bewusst, dass er, wenn er Pornografie konsumieren
darf, sich wünscht, dass er kein Konsument wäre. Die einzige Zeit, in
der Pornografie wertvoll wird, ist, wenn er \"versucht\", sie zu
reduzieren oder abstinent zu bleiben, oder wenn ihm die Abstinenz
aufgezwungen wird.

Es kann nicht oft genug betont werden, dass es die Gehirnwäsche ist, die
es schwierig macht, mit Pornografie aufzuhören. Je mehr davon entwirrt wird,
bevor du damit anfängst, desto leichter wirst du dieses Ziel erreichen.
Nutzer, die nicht glauben, dass Pornografie negative Auswirkungen
auf ihre Gesundheit haben (PIED, Hypofrontalität, etc.) und sich nicht
in einem mentalen Tauziehen befinden, sind in der Regel jünger oder
Single mit einem gelegentlichen Sexpartner. Deswegen geht das interne Feedback
aufgrund ihrer Jugend verloren oder ist zu unregelmäßig, um beobachtet
und registriert zu werden.

Ein besseres Argument für einen jüngeren Nutzer ist die damit verbrachte Zeit,
indem man eher sagt: *\"Ich kann nicht glauben, dass du dir keine Gedanken
über die Zeit machst, die du verbringst.\"* In der Regel leuchten ihre
Augen vor Entrüstung auf und sie fühlen sich benachteiligt, wenn das Thema aus
gesundheitlichen Gründen oder wegen der sozialen Stigmatisierung
angegriffen werden, aber bei der Zeit\...\
*\"Oh, ich kann es mir leisten. Es sind nur x Stunden pro Woche und ich
denke, das ist es wert, es ist mein einziges Laster, das mir Freude
bereitet.\"*

*\"Ich kann immer noch nicht glauben, dass du dir keine Sorgen machst.
Wenn wir von einer halben Stunde pro Tag ausgehen und die körperliche
Auszehrung durch den Dopamin-Entzug mit einbeziehen, verbringst du etwa
alle zwei Wochen einen vollen Arbeitstag damit. Ich bin sicher, du stimmst mir
zu, dass eine halbe Stunde pro Tag eine sehr konservative Schätzung ist.
Hast du schon einmal darüber nachgedacht, wie viel Zeit du im Laufe
deines Lebens damit verbringen wirst? Was machst du in dieser Zeit? Echte
Beziehungen aufbauen? Nein, dein Lieblingspornostar hat keine Sympathie
für dich, nur weil du so viel Zeit mit ihren Videos verbringst - du
vergeudest deine Zeit! Nicht nur das, du nutzt diese Zeit sogar, um
deine körperliche Gesundheit zu ruinieren, deine Nerven und dein
Selbstvertrauen zu zerstören, um ein Leben lang unter Sklaverei,
Schmerzen, Melancholie und Verdrossenheit zu leiden. Das muss dir doch
Sorgen machen, oder?\"*

Vor allem bei jüngeren Nutzern ist es offensichtlich, dass sie es nie
als lebenslange Sucht betrachtet haben. Gelegentlich rechnen sie aus,
wie viel Zeit sie in einer Woche damit verschwenden, und das ist alarmierend
genug. Sehr selten, wenn sie ans Aufhören denken, schätzen sie ab, wie
viel sie in einem Jahr davor sitzen, was erschreckend ist, aber ein
Leben lang? Undenkbar. Weil wir uns jedoch mit einem eingefleischten
Nutzer streiten, sagt er impulsiv: \"Ich kann es mir leisten, es kostet
nur so viel pro Woche\", und hauen sich damit selbst übers Ohr.

Würdest du einen Job ablehnen, bei dem du dein aktuelles Jahresgehalt
bekommst und außerdem jedes Jahr einen Monat frei hast? Jeder Nutzer
würde sofort unterschreiben und sich auf die Suche nach Urlaubsangeboten
für exotische Orten machen. Herauszufinden, wie man einen ganzen Monat
ohne Arbeit verbringen kann, wäre das größte Problem, das es zu lösen
gilt. In jedem Gespräch mit einem eingefleischten Nutzer (und bitte bedenke,
dass ich nicht mit jemandem wie dir spreche, der vorhat, aufzuhören) hat
niemand dieses Angebot angenommen. Warum nicht?

Oft sagt ein eingefleischter Nutzer an dieser Stelle: *\"Schau, der finanzielle
Aspekt macht mir eigentlich keine Sorgen.\"* Wenn du so denkst, frage
dich, warum du dir keine Sorgen machst. Warum gibst du dir in anderen
Bereichen deines Lebens so viel Mühe, um hier und da ein paar Dollar zu
sparen, aber schleuderst Tausende raus, um dein Glück zu zerstören?

Jede andere Entscheidung, die du in deinem Leben triffst, ist das
Ergebnis eines analytischen Prozesses, bei dem du die Vor- und Nachteile
abwägst, um zu einer rationalen Entscheidung zu kommen. Es mag die
falsche Entscheidung sein, aber sie wird das Ergebnis einer rationalen
Schlussfolgerung sein. Wann immer ein Nutzer die Vor- und Nachteile der
Nutzung von Internetpornografie abwägt, lautet die Antwort stets:
*\"Hör auf, sie zu nutzen! DU BIST EIN IDIOT!\".* Nutzer tun das nicht, 
weil sie es wollen oder sich dafür entscheiden, sondern weil sie 
nicht aufhören können. Sie MÜSSEN es tun,  verabreichen sich damit eine 
Gehirnwäsche und stecken den Kopf in den Sand.

Nutzer sollten bedenken, dass sich die Situation exponentiell
verschlechtern wird, während mehr Studien veröffentlicht werden und mehr
Menschen über die schädlichen Auswirkungen von Internetpornografie sprechen.
Heute sind es Nicht-Mediziner, die über die Auswirkungen sprechen,
morgen wird es auf der Liste der diagnostischen Tests deines Arztes
stehen. Vorbei sind die Zeiten, in denen der Nutzer seine \"Auszeiten\"
hinter Arbeitsstress verstecken konnte; dein Partner wird dich
fragen, warum du spät abends noch am Laptop sitzt. Der arme Nutzer, der
sich ohnehin schon elend fühlt, möchte nun, dass sich der Boden auftut
und ihn verschluckt.

Das Seltsame ist: Viele Menschen würden gutes Geld für
Fitnessstudio-Mitgliedschaften und persönliche Trainer zahlen, um
Muskeln aufzubauen und gut auszusehen. Viele greifen in ihrer
eingebildeten (und realen) Verzweiflung zu Behandlungen wie der
Steigerung des Testosterons mit zweifelhaften und gefährlichen
Nebenwirkungen. Dabei gibt es viele Menschen in dieser Gruppe, die davon
profitieren würden, wenn sie mit einer Praxis aufhören würden, die
systematisch die natürlichen Entspannungssysteme ihres Gehirns zerstört.

Das liegt daran, dass sie immer noch mit dem gehirngewaschenen Verstand
des Nutzers denken. Wisch dir für einen Moment den Sand aus den Augen.
Internetpornografie ist eine Kettenreaktion und eine Kette fürs Leben, und
wenn du diese Kette nicht unterbrichst, wirst du für den Rest deines
Lebens ein Nutzer bleiben. Schätze mal ab, wie viel Zeit du für den Rest
deines Lebens mit Pornografie verbringen wirst. Natürlich ist das von Person
zu Person unterschiedlich, aber nehmen wir mal an, es sind eineinhalb
Jahre Arbeitszeit. Stell dir vor, du hättest morgen einen Scheck von der
Lotterie über eineinhalb Jahre deines Gehalts auf dem Teppich liegen! Du
würdest vor Freude tanzen, also fang an zu tanzen! Du bist kurz davor,
genau das zu bekommen!

Wenn du denkst, dass das eine schräge Sichtweise auf das Thema ist, machst du 
dir immer noch etwas vor. Rechne aus, wie viel Zeit du gespart hättest, wenn
du überhaupt nicht angefangen hättest.

In Kürze wirst du die Entscheidung treffen, deine letzte Sitzung zu
haben (noch nicht, bitte denk an die Anleitung!) und ein Nicht-Nutzer
zu bleiben, indem du nicht noch einmal in die Falle tappst. Alles, was
du tun musst, um ein Nicht-Nutzer zu bleiben, ist, keine Pornos zu
schauen und \"nur einen Blick\" zu vermeiden. Denke daran, dass wenn du es doch tust,
es dich das kosten wird, was du eben als das Gehalt von eineinhalb Jahren veranschlagt
hast.

Wenn du jemanden wegen seiner Pornosucht berätst, sag ihm, dassdur
jemanden kennst, der ein Jobangebot abgelehnt hat, bei dem er sein
aktuelles Jahresgehalt bekommt und außerdem einen ganzen Monat bezahlten
Urlaub hat. Wenn du gefragt wirst, wer dieser Idiot ist, sagst du:
\"Du!\" Das ist zwar unhöflich, aber manchmal muss man seinen Standpunkt
auf eine weniger höfliche Art und Weise deutlich machen.
