Das ist der Bereich, in dem die Gehirnwäsche am größten ist. Vor allem
junge und alleinstehende Konsumenten denken, dass sie sich der
Gesundheitsrisiken bewusst sind, sind es aber nicht. Viele machen sich
etwas vor, indem sie sagen, sie seien bereit, die Konsequenzen zu
tragen. Wenn dein Internet-Router eine Funktion hätte, die einen
Alarmton mit einer Warnung abspielt, wenn du eine Pornoseite aufrufst,
die sagt: *\"Bis jetzt bist du damit durchgekommen, aber wenn du noch
eine Minute länger bleibst, wird dein Kopf explodieren.\"* Wärst du dann
geblieben? Wenn du dir über die Antwort im Unklaren bist, versuche, auf
eine Klippe zuzugehen, dich mit geschlossenen Augen an den Rand zu
stellen und dir vorzustellen, dass du die Wahl hättest, entweder mit dem
Porno aufzuhören oder mit verbundenen Augen weiter zu gehen.

Es besteht kein Zweifel daran, was deine Wahl wäre, aber wenn du den
Kopf in den Sand steckst und hoffst, dass du eines Morgens aufwachst und
keine Pornos mehr sehen willst, erreichst du nichts. Die Nutzer können
es sich nicht erlauben, an die gesundheitlichen Risiken zu denken, denn
wenn sie das tun, verschwindet das illusorische Vergnügen der Sucht. Das
erklärt, warum Schocktherapien in den ersten Phasen der Entwöhnung so
unwirksam sind. Nur Nichtkonsumenten bringen sich dazu, über die
zerstörerischen Veränderungen im Gehirn zu lesen.

Nimm dieses häufige Gespräch mit Nutzern, meist jüngeren.\
Ich: Warum willst du aufhören?\
Nutzer: *Ich habe im Blog eines Anmachkünstlers gelesen, dass es gut
ist, vier Tage lang aufzuhören, um mich aufzuladen.*\
Ich: Machst du dir keine Sorgen wegen der gesundheitlichen Risiken?\
Nutzer: *Nein, ich könnte morgen von einem Bus überfahren werden.*\
Ich: Aber würdest du dich absichtlich überfahren lassen?\
Nutzer: *Natürlich nicht.*\
Ich: Machst du dir nicht die Mühe, nach links und rechts zu schauen,
wenn du die Straße überquerst?\
Nutzer: *Natürlich mach ich das.*

Genau, sie geben sich große Mühe, nicht von einem Bus überrollt zu
werden, und die Chancen stehen tausend zu eins, dass das nicht passiert.
Doch der Nutzer riskiert mit an Sicherheit grenzender
Wahrscheinlichkeit, durch seine Sucht verkrüppelt zu werden, und scheint
sich dessen gar nicht bewusst zu sein. Das ist die Macht der
Gehirnwäsche: Internetpornos sind ein Wolf im Schafspelz. Ist es nicht
seltsam, dass wir nicht in ein Flugzeug steigen würden, wenn wir das
Gefühl hätten, dass es auch nur den kleinsten Fehler hat, obwohl das
Risiko millionen zu eins ist, aber bei Pornos ist die Wahrscheinlichkeit
mehr als eins zu vier und wir sind uns dessen offenbar nicht bewusst?
Was hat der Nutzer davon? **Absolut nichts!**

Ein weiterer weit verbreiteter Mythos sind Depressionen oder
Miesepetrigkeit. Viele jüngere Menschen machen sich keine Sorgen um ihre
Gesundheit, weil sie nicht unter Depressionen oder Melancholie leiden.
Die Depression oder der Stress ist nicht die Krankheit, sondern ein
Symptom. Jüngere Menschen spüren im Allgemeinen nicht die Reizbarkeit
oder Depression, die durch die natürliche Fähigkeit ihres Körpers, mehr
Dopamin zu produzieren, entsteht. Wenn sie älter werden oder in ihrem
Leben ernsthafte Rückschläge erleiden, werden ihre bereits erschöpften
Ressourcen überstrapaziert und sie bekommen die vollen Symptome zu
spüren. Wenn sich ältere Konsumenten gestresst, deprimiert oder gereizt
fühlen, liegt das daran, dass die natürlichen Schutzmechanismen das
Nervensystem durch das Entfernen einiger Rezeptoren vor einer
übermäßigen Dopaminflutung schützen. Der Konsument entwickelt auch
andere neurologische Veränderungen, die ihn in seinem Trott halten.

Stell dir das so vor: Wenn du ein schönes Auto hättest und es rosten
lassen würdest, ohne etwas dagegen zu tun, wäre das ziemlich dumm. Bald
würde es zu einem unbeweglichen Rosthaufen werden, der dich nirgendwo
mehr hinbringen kann. Das wäre aber nicht das Ende der Welt, denn es ist
nur eine Frage des Geldes. Aber dein Körper ist das Fahrzeug, das dich
durch das Leben trägt. Wir alle sagen, dass unsere Gesundheit unser
größtes Kapital ist, frag mal einen kranken Millionär. Die meisten von
uns können auf eine Krankheit oder einen Unfall in ihrem Leben
zurückblicken, bei dem sie gebetet haben, dass es ihnen besser geht.
Wenn du Pornos konsumierst, lässt du nicht nur den Rost eindringen und
tust nichts dagegen, sondern du zerstörst systematisch das Fahrzeug, mit
dem du durch dein ganzes Leben fährst.

Mach dich schlau. Du musst das nicht tun, denk daran, dass es *absolut
nichts für dich tut.* Wenn du mit Sicherheit wüsstest, dass deine
nächste Sitzung einen Prozess in Gang setzt, der dich für jemanden, den
du sehr liebst, völlig unempfänglich macht, würdest du dann weiter
machen? Wenn du mit den Menschen sprichst, denen das passiert, haben sie
sicher auch nicht damit gerechnet, dass es ihnen passieren würde, und
das Schlimmste ist nicht die Krankheit selbst, sondern das Wissen, dass
sie es sich selbst eingebrockt haben. Versuch dir vorzustellen, wie sich
Menschen fühlen, die \"den Knopf gedrückt\" haben: Für sie ist die
Gehirnwäsche beendet. Sie verbringen den Rest ihres Lebens damit, zu
denken: \"Warum habe ich mir so lange vorgemacht, dass ich zu
Internetpornos masturbieren muss? Wenn ich doch nur die Chance hätte,
zurück zu gehen!\"

Hör auf, dir etwas vorzumachen, du hast diese Chance. Es ist eine
Kettenreaktion: Wenn du dich auf den nächsten Porno einlässt, wird er
dich zum nächsten und zum nächsten führen. Es passiert bereits mit dir.
EasyPeasy verspricht keine Schocktherapie. Wenn du also bereits
beschlossen hast, aufzuhören, wird das Folgende für dich nicht
schockierend sein. Wenn nicht, überspringe den Rest dieses Kapitels und
komm wieder, wenn du den Rest des Buches gelesen hast.

Über den Schaden, den Internetpornos für unser Sexualleben und unser
seelisches Wohlbefinden anrichten, sind bereits Bände über Bände an
Forschungsergebnissen geschrieben worden. Das Problem ist, dass sie es
nicht wissen wollen, bis sie sich entscheiden, aufzuhören. Foren und
Mentorengruppen sind reine Zeitverschwendung, denn Pornos setzen die
Scheuklappen auf. Wenn sie es versehentlich lesen, öffnen sie als Erstes
ihre Lieblingsseite. Pornokonsumenten neigen dazu, die Gefahren von
Glück, Stress und Sex als ein Glücksspiel zu betrachten, als ob man auf
eine Landmine tritt.

Bekomme es in deinen Kopf, es passiert bereits. *Jedes Mal*, wenn du
deine Pornoseite öffnest, löst du eine Dopaminflut aus und die Opiate
machen sich an die Arbeit. Die neuronalen Wasserrutschen sind geschmiert
und die Fahrt führt dich sanft durch die nächsten Schritte, nachdem du
bereits in die Falle getappt bist. Das Nervensystem wird nun von Dopamin
überflutet und da es das x-te Mal ist, schließen sich die
Dopaminrezeptoren und das kleine Monster nutzt diesen leichten Rückgang
der Lust im Vergleich zum letzten Mal, um dich weiter über die rote
Linie zu schockierenderen Pornos oder Verhaltensweisen zu treiben, um
noch mehr Dopamin freizusetzen. Mehr Neuartigkeit, mehr Dopamin und das
kleine Monster sagt dir, dass du weitermachen sollst. So viele Bilder
und Videos in einer einzigen Sitzung lösen einen übernormalen Reiz aus,
der mehr Chemikalien in dein Gehirn schüttet und dich zum Weitermachen
antreibt.

Die ganze Zeit über erhalten deine Rezeptoren die Information, sich als
Reaktion auf die Überflutung abzuschalten. Der Orgasmus verstärkt diesen
Effekt nur und führt zum Entzug. Du leugnest es, denn das kleine Monster
sehnt sich nach seinem Kick ohne wirkliche Schmerzen und
Unannehmlichkeiten. Die Gefahr einer erektilen Dysfunktion macht vielen
Angst, weshalb sie sie verdrängen und mit der Angst vor dem Aufhören
überschatten. Es ist nicht so, dass die Angst größer wäre, aber heute
aufzuhören ist sofort möglich. Warum auf die schwarze Seite schauen?
Vielleicht passiert es ja gar nicht, weil man bis dahin sowieso
aufgehört hat.

Wir neigen dazu, uns Pornos als ein Tauziehen vorzustellen, bei dem auf
der einen Seite die Angst steht: *\"Es ist ungesund, schmutzig und
versklavend.\"* Auf der anderen Seite die positiven Aspekte: *\"Es ist
mein Vergnügen, mein Freund, meine Krücke.\"* Es scheint uns nie in den
Sinn zu kommen, dass diese Seite auch Angst ist; es geht nicht darum,
dass wir Pornos genießen, sondern darum, dass wir ohne sie unglücklich
sind. Ein Heroinsüchtiger, der kein Heroin bekommt, ist unglücklich,
aber stell dir vor, wie groß die Freude ist, wenn er sich endlich eine
Nadel in die Vene stechen darf und das schreckliche Verlangen aufhört.
Versuch dir vorzustellen, wie jemand tatsächlich glauben kann, dass es
ihm Freude bereitet, eine Injektionsspritze in eine Vene zu stechen.
Nicht-Heroinabhängige leiden nicht unter diesem panischen Gefühl und
Heroin lindert dieses Gefühl nicht, sondern verursacht es.

Nicht-Konsumenten fühlen sich nicht unglücklich, wenn sie keine Pornos
konsumieren dürfen, sondern nur die Konsumenten. Internetpornos lindern
das Gefühl nicht, sie verursachen es. Die Angst vor den negativen Folgen
hilft den Nutzern nicht, aufzuhören, denn das Gefühl ist wie ein Gang
durch ein Minenfeld. Wenn du damit durchkommst, gut, aber wenn du Pech
hast, bist du auf eine Mine getreten. Wenn du die Risiken kanntest und
bereit warst, sie einzugehen, was hat das dann mit anderen zu tun?
Süchtige in diesem Zustand entwickeln typischerweise die folgenden
Ausweichtaktiken.

*\"Irgendwann wirst du sowieso alt und verlierst deine sexuellen Fähigkeiten\...\"*

:   Natürlich wirst du das, aber um sexuelle Fähigkeiten geht es hier
    nicht, sondern um Sklaverei. Selbst wenn das der Fall ist, ist das
    ein logischer Grund, sich absichtlich zu limitieren?\"

*\"Lebensqualität ist wichtiger als nur zu leben.\"* Genau! Willst du damit sagen, dass die Lebensqualität eines Süchtigen höher ist als die eines Nicht-Süchtigen? Glaubst du wirklich, dass die Lebensqualität eines Süchtigen besser ist als die eines Nicht-Süchtigen? Ein Leben, in dem man den Kopf in den Sand steckt und unglücklich ist, klingt nicht gerade nach einem angenehmen Leben.

:   Selbst wenn das wahr wäre, ist das ein logischer Grund, um mit den
    Impulskontrollteilen deines Gehirns zu spielen? Kannst du dir
    vorstellen, dass jemand so dumm ist, sich nackt auszuziehen, wenn er
    allein zuhause ist, und sich ständig Gedanken macht, wann wohl wer
    wieder zurück kommt? **Das ist es, was Pornonutzer tatsächlich
    tun!**

Die fortschreitende Verstopfung unserer Belohnungsschaltkreise durch
übermäßige Stimulation macht sie unfähig, mit den normalen Belastungen
des Lebens umzugehen, und trägt nicht dazu bei, das Leben mit
Begeisterung und Elan zu genießen. Porno und Selbstbefriedigung haben
den natürlichen sexuellen Appetit ersetzt, so wie ein Schokoriegel das
echte Essen ersetzt. Es überrascht nicht, dass viele Ärzte und
Psychologen verschiedene psychische Probleme mit physiologischen
Ursachen in Verbindung bringen. Die Mainstream-Medizin beteuert, dass es
nie wissenschaftlich bewiesen wurde, dass Pornos die direkte Ursache für
die Probleme sind, von denen selbst bekennende Menschen berichten. Aber
das Eingeständnis der eigenen sexuellen Unfähigkeit in der
Öffentlichkeit ist ein so schamauslösendes Ereignis. Warum sollte das
jemand tun, wenn er nicht wirklich bestrebt ist, die Ursache zu finden
und sie aus seinem eigenen Leben zu eliminieren?

EasyPeasy wird dir helfen, dich davon zu befreien und ein glücklicher
Ex-Nutzer zu werden. Keine Pornos, pornounterstützte Masturbation oder
unnötige Orgasmen. Das einzige Hilfsmittel werden die Berührung, der
Geruch und der Duft deines Partners sein. Wie ein Vollkornbrot nach
einem gut entwickelten Appetit, wirst du keine Lust mehr auf den
fructosereichen Maissirup der Internetpornos haben. Die Beweise sind so
erdrückend, dass sie nicht bewiesen werden müssen: Wenn ich mir mit
einem Hammer auf den Daumen schlage, tut es weh; Kein Beweis ist nötig.
Der Stress, den Internetpornos auslösen, wirkt sich auch auf andere
Lebensbereiche aus. Viele greifen zu Drogen wie Zigaretten und Alkohol,
um damit fertig zu werden, oder denken sogar über Selbstmord nach.

Die Nutzer geben sich auch der Illusion hin, dass die negativen
Auswirkungen von Internetpornos und Pornos überbewertet werden. Das
Gegenteil ist der Fall: Es besteht kein Zweifel daran, dass
Internetpornos die Hauptursache für PIED (auf Deutsch: Porno verursachte
erektile Dysfunktion) und viele andere Probleme sind. Wie viele
Scheidungen sind durch Pornos verursacht worden? Es gibt keine
zuverlässigen Methoden, um das herauszufinden, aber Recherchen in
Online-Communities legen nahe, dass die Zahl wächst.

Es gibt eine Folge von *\"Friends\"*, in der sich die Jungs, die ständig
kostenlose Pornos im Fernsehen sehen, wundern, warum die
Pizzalieferantin nicht fragt, ob sie ihr \"großes Schlafzimmer\" sehen
darf. Wenn du süchtig bist, projizierst du deine Pornofantasien
unweigerlich auf echte Frauen. Stell dir vor, was ein unvorsichtiger
oder sogar versehentlicher Pornokonsum auf den dunklen Seiten des
Internets bei jemandem anrichten kann, der sich bereits an einem
Wendepunkt in seinem Leben befindet. Der Kampf gegen diese durch Pornos
ausgelösten Gedanken wird eine große Belastung für die psychische
Gesundheit sein.

Hier noch ein Gedankenexperiment: Angenommen, jemand kommt zu dir und
sagt, er wolle nicht unbedingt einen Orgasmus, aber er wolle unbedingt
Liebe machen, auch mit Penetration. Er möchte es so lange und so weit
wie möglich ohne Orgasmus tun, aber wenn er dann doch kommt, ist es in
Ordnung. Ich versichere dir eine phänomenale neue sexuelle Erfahrung,
die weit besser ist als jede andere, wenn du dieses Angebot überhaupt
bekommst. Probiere es aus.

Die Auswirkungen der Gehirnwäsche führen dazu, dass wir dazu neigen, wie
der Mann zu denken, der, nachdem er von einem 100-stöckigen Gebäude
gefallen ist, sagt, während er am fünfzigsten Stockwerk vorbeirauscht:
*\"So weit, so gut!\"* Wir denken, dass wir bisher damit durchgekommen
sind und eine weitere Porno-Session daran nichts ändern wird. Sieh es
mal anders: Die \"Gewohnheit\" ist eine lebenslange Kette, bei der jede
Sitzung das Bedürfnis nach der nächsten weckt. Wenn du mit der
Gewohnheit beginnst, zündest du eine Lunte. Das Problem ist nur, *dass
du nicht weißt, wie lang die Lunte ist.* Jedes Mal, wenn du einer
Pornosession nachgibst, bist du der Explosion der Bombe einen Schritt
näher. **WIE WIRST DU WISSEN, OB ES DIE NÄCHSTE IST?**



## Finstere schwarze Schatten

Für Nutzer ist es sehr schwer zu glauben, dass die Selbstbefriedigung zu
Internetpornos tatsächlich diese unsicheren Gefühle auslöst, wenn du
spät abends noch aus bist oder nach einem anstrengenden Tag bei der
Arbeit. Nicht-Nutzer leiden nicht unter diesem Gefühl; Es sind die
Pornos, die es verursachen.

Eine weitere große Freude, wenn man mit Pornos aufhört, ist die
Befreiung von den finsteren schwarzen Schatten im Hinterkopf. Alle User
wissen, dass sie dumm sind, wenn sie sich vor den negativen Auswirkungen
der Pornografie verschließen. Die meiste Zeit unseres Lebens geschieht
das automatisch, aber die schwarzen Schatten lauern immer in unserem
Unterbewusstsein, direkt unter der Oberfläche. Einige der wunderbaren
Vorteile des Aufhörens sind uns bewusst, wie zum Beispiel die
Zeitverschwendung und die schiere Dummheit, mit einem zweidimensionalen
Bild Liebe zu machen.

Die letzten Kapitel haben sich mit den beträchtlichen Vorteilen eines
Nichtnutzers befasst, aber im Interesse der Fairness ist es notwendig,
eine ausgewogene Darstellung zu geben. Deshalb werden auf der nächsten
Seite die Vorteile eines Nutzers aufgelistet.

# Vorteile eines Porno-Nutzers
