# Die Willenskraftmethode

In der Gesellschaft ist es eine anerkannte Tatsache, dass es sehr
schwierig ist, mit Pornografie aufzuhören. In Büchern und Foren, in denen du
Ratschläge zum Aufhören findest, wird dir in der Regel zuerst gesagt,
wie schwierig es ist. Die Wahrheit ist, dass es lächerlich einfach ist.
Es ist verständlich, dass du diese Aussage in Frage stellst, aber
denke einfach mal drüber nach. Wenn es dein Ziel ist, eine Meile in vier
Minuten zu laufen, ist das schwierig und du musst jahrelang hart
trainieren und bist möglicherweise selbst dann körperlich nicht dazu in
der Lage.

Alles, was du tun musst, um mit Pornografie aufzuhören, ist, sie nicht mehr
anzusehen und/oder nicht mehr zu masturbieren. Niemand zwingt dich, zu
masturbieren (außer du selbst), und im Gegensatz zu Nahrung oder Wasser
brauchst du sie nicht zum Überleben. Warum sollte es also so schwierig sein, damit
aufzuhören? Eigentlich ist es das nicht. Es sind die Nutzer selbst, die es sich schwer machen, indem sie Willenskraft einsetzen oder eine Methode anwenden, die sie
dazu zwingt, das Gefühl zu haben, dass sie eine Art Opfer bringen. Schauen
wir uns diese Methoden an.

Wir beschließen nicht, Nutzer zu werden, wir experimentieren lediglich mit
Pornoheften oder -webseiten, und weil sie schrecklich (ja, richtig,
schrecklich) sind, außer unserem gewünschten Clip, sind wir überzeugt,
dass wir jederzeit aufhören können. Am Anfang schauen wir uns die ersten
Clips an, wenn wir darauf Lust haben und zu besonderen Anlässen. Bevor wir uns versehen, besuchen wir diese Seiten nicht nur regelmäßig und masturbieren,
wenn wir wollen, sondern wir masturbieren täglich zu ihnen. Pornografie ist
zu einem Teil unseres Lebens geworden und sorgt dafür, dass wir überall
eine Internetverbindung brauchen, wo auch immer wir hingehen. Wir
glauben dann, dass wir ein Recht auf Liebe, Sex, Orgasmen und die
stressabbauende Wirkung von Pornografie haben. Es scheint uns nicht in den
Sinn zu kommen, dass die gleichen Clips und Darsteller uns nicht den
gleichen Grad an Erregung verschaffen und wir beginnen, gegen die rote
Linie zu kämpfen, um \"schlechte Pornos\" zu vermeiden. Tatsächlich
verbessern Selbstbefriedigung und Internetpornografie weder unser Sexualleben
noch bauen sie Stress ab, sondern führen lediglich dazu, dass wir
glauben, wir könnten ohne Orgasmus das Leben nicht genießen oder mit Stress
umgehen.

Es dauert in der Regel lange, bis wir merken, dass wir süchtig sind,
weil wir unter der Illusion leiden, dass Nutzer Pornografie anschauen,
weil sie Spaß daran haben, und nicht, weil sie es müssen. Wenn wir
Pornografie nicht genießen (was wir nie tun können, wenn nicht etwas Neues,
schockierendes oder eskalierendes hinzukommt), haben wir die Illusion, dass
wir aufhören können, wann immer wir wollen. Das ist eine
Selbstvertrauensfalle: \"*Ich genieße keine Pornos, also kann ich
aufhören, wann immer ich will\"*. Nur, dass wir scheinbar nie aufhören
\"wollen\".

Meistens merken wir erst dann, dass wir ein Problem haben, wenn wir
tatsächlich versuchen, aufzuhören. Die ersten Versuche werden meist in
den ersten Tagen unternommen, wenn wir einen Partner kennenlernen und
nach den ersten Dates merken, dass er nicht \"genug\" ist. Ein weiterer
häufiger Grund ist das Bemerken von gesundheitlichen Folgen im
täglichen Leben.

Unabhängig vom Grund wartet der Nutzer immer auf eine stressige
Situation, egal ob Gesundheit oder Sex. Sobald er aufhört, wird das
kleine Monster hungrig. Der Nutzer will dann etwas, um sein Dopamin zu
pumpen, z. B. Zigaretten, Alkohol oder seinen Favoriten, die
Internetpornografie, die nur einen Klick entfernt ist. Der Porno-Speicher
befindet sich nicht mehr im Keller, sondern virtuell und von überall
aus zugänglich. Wenn ihr Partner in der Nähe ist oder sie mit Freunden
zusammen sind, haben sie keinen Zugang mehr zu ihrem virtuellen Harem,
was sie noch mehr in Bedrängnis bringt.

Wenn der Nutzer auf wissenschaftliches Material oder Online-Communities
gestoßen ist, hat er ein Tauziehen in seinem Kopf - er widersteht
Versuchungen und fühlt sich gleichzeitig beraubt. Die Art und Weise, wie man
normalerweise Stress abbaut, ist nun nicht mehr verfügbar und man
erleidet einen dreifachen Schlag. Das wahrscheinliche Ergebnis nach
dieser Zeit der Tortur ist ein Kompromiss - *\"Ich werde mich
einschränken\"* oder *\"Ich habe mir die falsche Zeit ausgesucht\"* oder
vielleicht *\"Ich werde warten, bis der Stress aus meinem Leben
verschwunden ist.\"* Wenn der Stress jedoch erst einmal weg ist, gibt es
keinen Grund mehr aufzuhören, und der Nutzer beschließt erst beim
nächsten stressigen Ereignis wieder aufzuhören.

Natürlich gibt es nie einen richtigen Zeitpunkt, weil das Leben für die
meisten Menschen immer stressiger wird. Man verlässt den Schutz der
Eltern und betritt eine Welt, in der man ein Haus gründet, eine Hypothek
aufnimmt, Kinder bekommt und einen Job mit mehr Verantwortung hat.
Trotzdem kann das Leben des Nutzers nicht weniger stressig werden,
denn Pornos verursachen Stress. Je schneller der Nutzer in die
Eskalationsstufe übergeht, desto größer wird sein Stress und desto größer
wird die Illusion, dass er abhängig ist.

Tatsächlich ist es eine Illusion, dass das Leben stressiger wird, und
Pornografie oder ähnliche Krücken erzeugen diese Illusion. Darauf werden
wir später noch genauer eingehen, aber nach diesen anfänglichen
Misserfolgen verlässt sich der Nutzer in der Regel darauf, dass er eines
Tages aufwacht und keine Lust mehr hat, zu masturbieren oder Pornografie zu
benutzen. Diese Hoffnung wird in der Regel durch die Geschichten
anderer ehemaliger Nutzerinnen und Nutzer genährt: *\"Ich habe es nicht
ernst genommen, bis ich eine schwindende Penetration hatte, dann wollte
ich keine Pornos mehr benutzen und habe aufgehört zu masturbieren.\"*

Mach dir nichts vor, überprüfe diese Gerüchte und du wirst feststellen,
dass sie nie so einfach sind, wie sie erscheinen. In der Regel hat
der Nutzer den Ausstieg bereits vorbereitet und den Vorfall lediglich
als Sprungbrett genutzt. Bei Menschen, die \"einfach so\" aufhören,
kommt es häufiger vor, dass sie einen Schock erlitten haben. Vielleicht
hat ihr Partner sie entdeckt, sie haben sich selbst dabei ertappt, wie
sie auf Pornos zugegriffen haben, die nicht ihrer normalen sexuellen
Orientierung entsprechen, oder sie haben sexuelle Dysfunktion erlebt, was sie sehr verstört hat. *\"So bin ich nun mal.\"* Hör auf, dir etwas vorzumachen. 
Es wird nichts geschehen solange du nichts beginnst.

Schauen wir uns genauer an, warum die Willenskraftmethode so schwierig
ist. Die meiste Zeit unseres Lebens stecken wir den Kopf in den Sand und
denken: textit\"Morgen höre ich auf. Doch manchmal gibt es einen
Auslöser für den Versuch, aufzuhören. Das können Sorgen um die
Gesundheit, die Potenz oder eine Selbstanalyse sein, bei der wir
feststellen, dass wir Pornografie eigentlich nicht wirklich genießen. Was auch immer
der Grund ist, wir beginnen, die Vor- und Nachteile von Pornografie
abzuwägen. Sex wird unterteilt in Vergnügen (Berührung, Geruch, Stimme) und Fortpflanzung (Orgasmus). Das ist einer der wichtigsten Schlüssel, um unseren Geist zu öffnen, denn ohne
diese wichtige Unterscheidung entsteht Verwirrung, die wiederum zum Scheitern
führt. Bei rationaler Betrachtung finden wir heraus, was wir schon unser
ganzes Leben lang wussten, nämlich die Schlussfolgerung: \"HÖR AUF, ES ZU SCHAUEN!\"

Wenn du dich hinsetzen und den Vorteilen des Aufhörens Punkte geben würdest und
sie mit den Vorteilen von Pornografie vergleichtest, würde die
Gesamtpunktzahl für das Aufhören bei weitem die der Vorteile übersteigen. Wenn du
die Pascal'sche Wette anwendest, verlierst du fast nichts, wenn du aufhörst, und
hast eine hohe Chance, zu gewinnen und eine noch höhere Chance, *nicht* zu
verlieren. Obwohl der Nutzer weiß, dass er als Nichtnutzer besser
dasteht, stört ihn der Glaube, ein Opfer zu bringen. Obwohl es eine
Illusion ist, ist sie sehr stark. Sie wissen nicht warum, aber die
Nutzer glauben, dass die Sitzungen in guten und schlechten Zeiten des
Lebens zu helfen scheinen. Noch bevor sie ihren Versuch starten, kommt
zu der gesellschaftlichen Gehirnwäsche, die durch die Gehirnwäsche ihrer
eigenen Sucht verstärkt wird, die noch stärkere Gehirnwäsche hinzu, wie
schwierig es ist, \"aufzuhören\".

Du hörst Geschichten von Leuten, die seit vielen Monaten aufgehört haben
und immer noch verzweifelt Verlangen haben, und von verärgerten
Aufhörern, die den Rest ihres Lebens damit verbringen, die Tatsache zu
beklagen, dass sie gerne eine Sitzung hätten. Es gibt Geschichten von
Menschen, die monatelang oder jahrelang aufgehört haben und ein
glückliches Leben führen, nur um plötzlich wieder süchtig zu werden,
als sie nur \"einen Blick\" auf einen Porno warfen. Wahrscheinlich
kennen sie einige, die sich im fortgeschrittenen Stadium der Krankheit
befinden, sich sichtlich selbst zerstören und das Leben nicht mehr
genießen, aber trotzdem weitermachen. Außerdem haben sie wahrscheinlich
selbst schon eine oder mehrere dieser Erfahrungen gemacht.

Anstatt also mit dem Gefühl anzufangen, *\"Toll! Hast du die Neuigkeiten
gehört? Ich muss mir keine Pornos mehr ansehen!\"*, beginnen sie
stattdessen mit einem Gefühl der Niedergeschlagenheit, als ob sie
versuchen würden, den Everest zu besteigen, und das Gefühl haben, dass
sie für immer süchtig sind, wenn das kleine Monster erst einmal seine
Haken in ihnen hat. Viele Nutzer beginnen den Versuch, indem sie sich bei
ihren Freundinnen oder Ehefrauen entschuldigen: *\"Hör zu, ich versuche,
Pornos aufzugeben. Wahrscheinlich werde ich in den nächsten Wochen
reizbar sein, bitte hab Geduld mit mir.\"* Die meisten Versuche sind zum
Scheitern verurteilt, bevor sie beginnen.

Angenommen, der Nutzer überlebt ein paar Tage ohne eine Sitzung. Er fängt an,
wieder normale Erregung zu verspüren und beginnt sich zu erholen. Er hat seine
Lieblingsseiten nicht geöffnet und wird daher durch normale Reize
erregt, bei denen er vorher abgeschaltet hat. Die Gründe, warum er
sich entschieden hat, aufzuhören, verschwinden so schnell aus seinen
Gedanken, wie ein schwerer Verkehrsunfall, den man beim Autofahren sieht. Das bremst
ihn für eine Weile aus, aber wenn er das nächste Mal zu spät zu einem
Termin kommt, tritt er wieder auf das Gaspedal.

Auf der anderen Seite des Krieges steht das kleine Monster, das immer
noch nicht seinen Schuss bekommen hat. Es gibt keine körperlichen
Schmerzen - wenn der Nutzer das gleiche Gefühl wegen einer Erkältung hätte,
würde er nicht aufhören zu arbeiten oder depressiv werden, sondern es
einfach weglachen. Alles, was er weiß, ist, dass er seinen Harem
besuchen will. Das kleine Monster weiß das auch und setzt das große Monster
der Gehirnwäsche in Gang. Das bewirkt, dass dieselbe Person, die ein paar
Stunden oder Tage zuvor noch alle Gründe zum Aufhören aufgelistet hat,
jetzt verzweifelt nach einer Ausrede sucht, um wieder anzufangen. Sie
beginnt Dinge zu sagen wie:

-   *\"Das Leben ist zu kurz; eine Bombe könnte hochgehen, ich könnte
    morgen von einem Bus überfahren werden. Ich habe zu spät aufgehört.
    Heutzutage sagt man, dass alles süchtig macht.\"*

-   *\"Ich habe den falschen Zeitpunkt gewählt.\"*

-   *\"Ich hätte bis nach Weihnachten warten sollen, nach meinen
    Ferien/Prüfungen, nach diesem stressigen Ereignis in meinem
    Leben.\"*

-   *\"Ich kann mich nicht konzentrieren, ich werde reizbar und schlecht
    gelaunt, ich kann nicht einmal meine Arbeit richtig machen.\"*

-   *\"Meine Familie und Freunde werden mich nicht lieben. Seien wir
    ehrlich, allen zuliebe muss ich wieder anfangen. Ich bin ein
    eingefleischter Sexsüchtiger, und ohne Orgasmus werde ich nie wieder
    glücklich sein.\"*

-   *\"Niemand kann ohne Sex überleben.\"* (Gehirnwäsche durch
    wohlmeinende Menschen, die den Unterschied zwischen dem amativen und
    dem propagativen Teil von Sex nicht in Betracht ziehen).

-   *\"Ich wusste, dass das passieren würde. Mein Gehirn ist durch
    DeltaFosB 'sensibilisiert', weil ich in der Vergangenheit exzessiv
    Pornos konsumiert habe und die Dopaminschübe sich dadurch verändert
    haben. Die Sensibilisierung kann 'niemals' aus dem Gehirn entfernt
    werden\".*

In diesem Stadium gibt der Nutzer normalerweise nach. Er schaltet den
Browser ein und die Schizophrenie nimmt zu. Auf der einen Seite ist da die
riesige Erleichterung, weil das kleine Monster endlich seinen Schuss bekommt;
auf der anderen Seite ist der Orgasmus schrecklich und der Nutzer kann
nicht verstehen, warum er das tut. Deshalb denkt er, dass es ihm
an Willenskraft fehlt. In Wirklichkeit fehlt es ihm nicht an
Willenskraft, sondern er hat nur seine Meinung geändert und angesichts
der neuesten Informationen eine völlig rationale Entscheidung getroffen.

*\"Was bringt es, gesund oder reich zu sein, wenn man unglücklich ist?*

Absolut nichts! Es ist viel besser, ein kürzeres, angenehmes Leben zu
haben als ein langes, unangenehmes. Zum Glück ist das für den
Nichtnutzer nicht wahr, denn sein Leben ist unendlich viel angenehmer.
Das Elend, unter dem der Nutzer leidet, ist nicht auf die
Entzugserscheinungen zurückzuführen, auch wenn es anfangs von ihnen
ausgelöst werden, sondern die eigentliche Qual ist das Tauziehen im
Kopf, das durch Zweifel und Unsicherheit verursacht wird. Da der Nutzer
anfängt zu glauben, dass er ein Opfer bringt, fühlt er sich beraubt,
was eine Form von Stress ist.

Einer dieser stressigen Momente ist, wenn das Gehirn ihm sagt, dass
er \"einen Blick riskieren\" soll, und sobald er aufhört, will
er wieder zurück. Aber weil er aufgehört hat, kann er das nicht,
was ihn noch depressiver macht und den Auslöser erneut in Gang setzt.
Ein weiterer Faktor, der das Aufhören so schwierig macht, ist das Warten
darauf, das etwas passiert. Wenn dein Ziel darin besteht, eine
Fahrprüfung zu bestehen, ist es sicher, dass du dein Ziel erreicht hast,
sobald du die Prüfung bestanden hast. Bei der Willenskraftmethode lautet
der innere Gedankengang: *\"Wenn ich lange genug ohne Internetpornografie
auskomme, wird der Drang, sie anzusehen, irgendwann nachlassen.\"* Du
kannst das in der Praxis in Online-Foren sehen, wo Süchtige über ihre
Phasen oder Tage der Abstinenz sprechen.

Wie gesagt, die Qualen, die der Nutzer erleidet, sind psychischer Natur
und werden durch Unsicherheit verursacht. Obwohl es keine körperlichen
Schmerzen gibt, haben sie dennoch starke Auswirkungen. Der Nutzer ist nun
unglücklich und unsicher und ist weit davon entfernt, zu vergessen,
voller Zweifel und Ängste.

-   *\"Wie lange wird das Verlangen anhalten?\"*

-   *\"Werde ich jemals wieder glücklich sein?\"*

-   *\"Werde ich jemals wieder morgens aufstehen wollen?\"*

-   *\"Wie werde ich in Zukunft mit Stress fertig?\"*

Der Nutzer wartet darauf, dass die Dinge besser werden, aber während er
noch Trübsal bläst, wird der \"Harem\" immer wertvoller. In der Tat
passiert *etwas*, aber unterbewusst, und wenn er Wochen überleben können, ohne
den Browser zu öffnen, verschwindet das Verlangen nach dem kleinen
Monster. Wie bereits erwähnt, sind die Entzugserscheinungen von Dopamin
und Opiaten jedoch so mild, dass der Nutzer sie gar nicht wahrnimmt. Zu
diesem Zeitpunkt haben viele Nutzer das Gefühl, dass sie es
\"geschafft\" haben und riskieren einen Blick, um sich das zu beweisen.
Nachdem der Körper dann mit Dopamin versorgt wurde, meldet sich im Hinterkopf
eine kleine Stimme, die sagt: *\"Du willst noch einen.\"* Eigentlich
hatten sie es schon aufgegeben, aber sie haben sich selbst wieder abhängig gemacht.

Als Kind hast du Zeichentrickfilme geschaut und laut Neurowissenschaft
DeltaFosB für sie gebildet. Wenn du ein Kind davon abhalten wolltest,
sie zu schauen, würdest du untersuchen, ob diese Bahnen noch
existieren und Erwachsene befragen, warum sie ihre Lieblingscartoons aus
der Kindheit nicht mehr sehen wollen. Erstens gibt es bessere
Unterhaltungsangebote und zweitens haben Zeichentrickfilme einfach nicht
mehr den gleichen Zauber. Mit der Willenskraft-Methode verweigerst du
dem Kind nur den Zeichentrickfilm, aber mit EasyPeasy sorgst du auch
dafür, dass es keinen Wert darin sieht. Was ist besser?

Der Nutzer wird in der Regel nicht sofort in eine neue Sitzung
einsteigen, weil er denkt: *\"Ich will nicht wieder süchtig werden!\"*,
und lässt eine sichere Zeitspanne von Stunden, Tagen oder sogar Wochen
vergehen. Der Ex-Nutzer kann dann sagen: *\"Nun, ich bin nicht süchtig
geworden, also kann ich sicher eine weitere Sitzung haben.\"* Sie sind
wieder in die gleiche Falle getappt wie zu Beginn und befinden sich
bereits auf rutschigen Boden.

Nutzer, die mit der Willenskraft-Methode Erfolg haben, finden es meist lang und anstrengend, denn das Hauptproblem ist die Gehirnwäsche. Lange nachdem die
körperliche Sucht erloschen ist, bläst der Nutzer immer noch Trübsal.
Irgendwann, wenn sie diese Langzeitfolter überlebt haben, dämmert ihnen,
dass sie nicht nachgeben werden, und sie hören auf, Trübsal zu blasen,
und akzeptieren, dass das Leben auch ohne Pornografie schön ist und
weitergeht. Es gibt deutlich mehr Misserfolge als Erfolge, denn einige,
die erfolgreich sind, gehen in einem verletzlichen Zustand durch ihr
Leben, in dem sie noch eine gewisse Gehirnwäsche haben, die ihnen sagt,
dass Pornografie ihnen tatsächlich einen Kick gibt. Das erklärt, warum viele
Nutzer, die für lange Zeit aufgehört haben, später wieder anfangen.

Viele Ex-Nutzer schauen sich gelegentlich Pornografie an, um sich etwas
'Besonderes zu gönnen' oder um sich davon zu überzeugen, wie stark ihre
Selbstkontrolle ist. Und genau das errichen sie auch - aber sobald der
Konsum beendet ist, wird das Dopamin abgebaut und eine kleine Stimme 
in ihrem Hinterkopf treibt sie zu weiterem Konsum an. Wenn sie sich
entscheiden, mitzumachen, scheint es immer noch unter Kontrolle zu 
sein, keine Schocks, keine Eskalation und keine Suche nach etwas Neuem,
so dass sie sagen: *\"Wunderbar! Ich genieße es zwar nicht wirklich,
aber ich werde auch nicht süchtig. Nach Weihnachten / diesem Urlaub / diesem Trauma
höre ich auf.\"* Sie ahnen nicht, dass die Wasserrutschen ihres Gehirns noch mehr eingefettet wurden.

Zu spät, sie sind bereits gefangen! Die Falle, aus der sie sich
herausgewunden haben, hat ihr Opfer wieder eingeholt.

Wie gesagt, der Spaß spielt dabei keine Rolle. Das hat es nie! Wenn wir
wegen des Vergnügens zuschauen würden, würde niemand länger auf den
Videoseiten bleiben, als es dauert, die 'Tat zu beenden'. Ein besserer
Weg zur Selbstbefriedigung sind die Erinnerungen. Wir gehen davon aus,
dass wir Internetpornografie nur deshalb genießen, weil wir nicht glauben
können, dass wir so dumm sein könnten, süchtig geworden zu sein, wenn wir es
nicht genießen würden. Die meisten Nutzerinnen und Nutzer haben keine
Ahnung von übernormalen Reizen, Neuheit- oder Schocksuche und glauben
auch nach dem Lesen über dieses Thema nicht, dass ihre Nutzung durch die
Verdrahtung des Belohnungskreislaufs motiviert ist. Wenn sie sich der
neurologischen Veränderungen bewusst wären und sich dafür rechtfertigen
müssten, dass es sie in Zukunft Geld kostet, würde sogar die Illusion
des Vergnügens verschwinden.

Wenn wir versuchen, unseren Verstand vor der schlechten Seite des Themas zu
verschließen, kommen wir uns dumm vor. Wenn wir uns ihnen stellen müssten,
wäre das unerträglich! Wenn du einen Nutzer in Aktion beobachtest, wirst
du sehen, dass er nur dann glücklich ist, wenn er nicht weiß, dass er
'nutzt'. Sobald er sich dessen bewusst ist, fühlt er sich oft unwohl
und entschuldigt sich. Pornos füttern das kleine Monster und wenn du
sie zusammen mit der Gehirnwäsche (dem großen Monster) aus deinem Körper
verbannt hast, wirst du weder das Bedürfnis noch das Verlangen haben,
sie anzusehen.
