# Vorsicht vor dem Reduzieren

Viele Nutzer versuchen, ihre Pornosucht zu reduzieren,
um damit aufzuhören oder um das kleine Monster zu kontrollieren. Viele
empfehlen einen Entzug oder eine \"Porno-Diät\" um sich weiterzuhelfen.
Weniger zu konsumieren als Sprungbrett zum Aufhören zu nutzen ist fatal.
Es sind diese Reduzierungsversuche, die uns für den Rest unseres Lebens
gefangen halten. In der Regel folgt das Reduzieren auf gescheiterte
Versuche, aufzuhören. Nach ein paar Stunden oder Tagen der Abstinenz
sagt sich der Nutzer etwas wie:

*\"Ich kann den Gedanken nicht ertragen, schlafen zu gehen, ohne meinen
Online-Harem zu besuchen, also werde ich von nun an nur noch alle vier
Tage einen Porno ansehen oder meine Sammlung von 'schlechten Pornos'
löschen. Wenn ich diese Porno-Diät durchhalte, kann ich sie entweder
beibehalten oder noch weiter einschränken.\"*

Nun geschehen einige schreckliche Dinge:

1.  Er sitzt in der schlimmsten aller Welten fest, immer noch
    süchtig nach Internetpornografie und das Monster nicht nur in
    seinem Körper, sondern auch in seinem Geist am Leben haltend.

2.  Er wünscht sich sein Leben weg, auf die nächste Sitzung wartend.

3.  Bevor er aufhörte, hat er jedes Mal, wenn er seinen Harem
    besuchen wollte, seinen Browser gestartet, um seine
    Entzugserscheinungen zumindest teilweise zu lindern. Jetzt muss
    er zusätzlich zum normalen Stress des Lebens die meiste Zeit seines
    Lebens unter den Entzugserscheinungen leiden, was ihn noch
    unglücklicher und schlecht gelaunter macht.

4.  Während er nachgab, genoss er die meisten Sitzungen nicht und
    merkte auch nicht, dass er sich unnormale Reizen aussetzte. Der
    einzige Haremsbesuch, der genossen wurde, war der nach einer Phase
    der Abstinenz. Jetzt, wo er eine Stunde länger auf jeden Haremsbesuch wartet,
    \"genießt\" er jede einzelne. Je länger er wartet, desto angenehmer
    scheint jede Sitzung zu werden - denn das \"Vergnügen\" an einer Sitzung
    ist nicht die Sitzung selbst, sondern das Ende der Aufregung, die durch
    das Verlangen verursacht wird, sei es ein leichtes körperliches
    Verlangen oder geistiges Trübsalblasen. Je länger das Leiden andauert,
    desto \"erfreulicher\" wird jede Sitzung.

Die Hauptschwierigkeit beim Aufhören liegt nicht in der neurologischen
Abhängigkeit; die ist einfach abzulegen. Der Tod eines geliebten Menschen,
familiäre oder berufliche Angelegenheiten usw. können dazu führen, dass
man ohne Probleme aufhört. Man kann z. B. zehn Tage ohne Zugang zu Pornografie
auskommen und es macht einem nichts aus. Hätte man aber dieselben zehn
Tage gebraucht, in denen man Zugang hätte haben können, würden man sich die Haare raufen.

Viele Nutzer werden während ihres Arbeitstages die Gelegenheit haben, sich zu 
enthalten, sie werden an Victoria's Secret, Schwimmbädern und so weiter 
vorbeigehen, ohne dass es sie übermäßig stört. Viele werden sich enthalten, 
wenn sie vorübergehend auf der Couch schlafen müssen, um Platz für einen 
Besucher zu schaffen oder selbst zu Besuch sind. Auch gab es selbst in Go-Go-Bars 
oder an FKK-Stränden keine Tumulte deswegen. Die Nutzer sind fast schon froh, wenn ihnen jemand sagt, dass sie keine Pornografie ansehen dürfen. Nutzer, die aufhören wollen, empfinden sogar ein heimliches Vergnügen daran, lange Zeit ohne Haremsbesuche
auszukommen, was ihnen die Hoffnung gibt, dass sie es vielleicht eines
Tages gar nicht mehr wollen werden.

Das eigentliche Problem beim Aufhören ist die Gehirnwäsche, die Illusion
des Anspruchs, dass Internetpornografie eine Art Requisite oder Belohnung
ist und das Leben ohne sie nie mehr dasselbe sein wird. Weit entfernt
davon, dich von Internetpornografie loszulösen, ist alles, was das Reduzieren
bewirkt, dass du dich unsicher und unglücklich fühlst und dich davon
überzeugst, dass das Wertvollste auf der Welt der neue Clip ist, den du
verpasst hast, und dass du ohne ihn nie wieder glücklich sein kannst.

Es gibt nichts Erbärmlicheres als den Nutzer, der versucht, den Konsum zu
reduzieren. Er leidet unter dem Wahn, dass, je weniger Pornografie er sieht,
desto weniger er Online-Harems besuchen wollen wird. Das Gegenteil ist
der Fall: Je weniger er Pornografie schaut, desto länger leidet er unter
Entzugserscheinungen und desto mehr genießt er die Erleichterung,
diese zu lindern. Allerdings wird er merken, dass sein Lieblingsgenre
nicht mehr so gut befriedigt. Aber das wird ihn nicht davon abhalten, denn
wenn die Internet-Seiten nur einem Star oder einem Genre gewidmet wären,
würde kein Nutzer mehr als einmal hingehen.

Schwierig zu glauben? Was ist der schlimmste Moment der
Selbstbeherrschung, den man erlebt? Vier Tage lang zu warten und dann
einen Höhepunkt zu haben. Was ist der wertvollste Moment für die meisten
User nach einer viertägigen Porno-Diät? Richtig, der gleiche Höhepunkt
nach vier Tagen Wartezeit! Glaubst du wirklich, dass du masturbierst, um
den Orgasmus zu genießen, oder die rationalere Erklärung - um
Entzugserscheinungen in der Illusion zu lindern, dass du dazu berechtigt
bist?

Die Beseitigung der Gehirnwäsche ist wichtig, um die Illusionen über
Pornografie zu beseitigen, bevor du die letzte Sitzung beendest. Bis du die
Illusion, dass du es genießt, nicht beseitigt hast, bevor du das Fenster dann
schließt, kannst du es hinterher nicht mehr beweisen, ohne wieder
abhängig zu werden. Wenn du über Lesezeichen und gespeicherte Bilder
stolperst, fragst du dich, wo die Ehre in dieser Handlung liegt.
Vielleicht glaubst du, dass nur bestimmte Clips geschmackvoll sind, z.
B. solche zu Gewohnheits- oder Lieblingsthemen. Wenn das so ist, warum
machst du dir dann die Mühe, andere Videos oder Themen anzusehen? Weil
du es dir zur Gewohnheit gemacht hast? Warum sollte jemand aus
Gewohnheit sein Gehirn durcheinander bringen und sich verausgaben?
Nichts ist nach einem Monat anders, warum sollte es bei einem Pornoclip
anders sein?

Du kannst das selbst testen: Finde den heißen Clip vom letzten Monat, um
zu beweisen, dass er anders ist. Dann stellst du eine Erinnerung ein und
schaust dir denselben Clip nach einem Monat ohne Pornografienutzung an. Er wird
(fast) das gleiche befriedigen wie im letzten Monat. Der gleiche
Clip wird nach einem gesellschaftlichen Ereignis, bei dem du von einem
potenziellen Partner abgewiesen oder getestet wurdest, anders sein.
Der Grund dafür ist, dass der Süchtige nie ganz glücklich sein kann,
wenn das kleine Monster unbefriedigt bleibt.

Wo kommt die Befriedigung ins Spiel? Es ist einfach nur so, dass du
unglücklich bist, wenn du deine Entzugserscheinungen nicht lindern
kannst. Der Unterschied zwischen Pornografie schauen und nicht schauen ist der
Unterschied zwischen glücklich sein und unglücklich sein. Deshalb scheinen
Internetpornos besser zu sein. Diejenigen, die sich morgens als Erstes
auf ihre Website begeben, um Pornos zu schauen, sind unglücklich, egal ob 
sie sie sich anschauen oder nicht.

Reduzieren funktioniert nicht nur nicht, sondern ist die schlimmste Form
der Folter. Es funktioniert nicht, weil der Nutzer anfangs hofft, dass
er sein Verlangen, Pornografie zu schauen, verringern kann, wenn er sich
immer weniger daran gewöhnt. Es ist keine Gewohnheit, es ist eine Sucht.
Die Natur jeder Sucht ist es, immer mehr zu wollen, nicht immer weniger.
Um damit aufzuhören, muss der Nutzer für den Rest seines Lebens
Willenskraft und Disziplin aufbringen. Reduzieren bedeutet also
Willenskraft und Disziplin - für immer. Aufhören ist viel einfacher und
weniger schmerzhaft. Es gibt buchstäblich Zehntausende von Fällen, in
denen das Reduzieren fehlgeschlagen ist.

Das Problem beim Aufhören ist nicht die Dopaminabhängigkeit, die leicht
zu bewältigen ist. Es ist der Irrglaube, dass Pornografie Freude bereitet,
der durch die Gehirnwäsche, die wir vor dem Konsum erhalten haben,
hervorgerufen und durch die eigentliche Sucht noch verstärkt wird.
Alles, was der Entzug bewirkt, ist, den Irrglauben weiter zu verstärken,
so dass die Pornografie dein Leben vollständig beherrscht und sich davon
überzeugt, dass deine Sucht das Wertvollste auf der Welt ist.

Die wenigen Fälle, die erfolgreich waren, wurden durch eine relativ
kurze Zeit des Reduzieren erreicht, gefolgt von einem \"kalten Entzug\".
Diese Nutzer hörten TROTZ des Entzugs auf, nicht WEGEN des
Entzugs. Das einzige, was es bewirkt hat, war, die Qualen zu verlängern.
Die gescheiterten Versuche haben die Konsumenten als nervliche Wracks
zurückgelassen und sie noch mehr davon überzeugt, dass sie für immer
süchtig sind. Das reicht in der Regel aus, um sie dazu zu bringen,
wieder in ihren Online-Harem zurückzukehren, um sich dort zu vergnügen,
bevor sie den nächsten Versuch starten.

Reduzieren hilft jedoch dabei, die Sinnlosigkeit von Pornos zu
verdeutlichen und macht klar, dass Besuche im Harem nur nach Zeiten der
Abstinenz Spaß machen. Du musst deinen Kopf gegen eine Mauer schlagen
(Entzugserscheinungen erleiden), um es dir beim Aufhören schön zu
machen. Du hast also die Wahl:

1.  Lebenslang reduzieren und selbst auferlegte Folter zu erleiden, die
    du sowieso nicht durchhalten kannst.

2.  Sich ein Leben lang immer mehr quälen, was sinnlos ist.

3.  Sei nett zu dir selbst und lass es ganz sein.

Der andere Aspekt, den das Reduzieren zeigt, ist, dass es so etwas wie
einen gelegentlichen Haremsbesuch nicht gibt. Internetpornografie ist eine
Kettenreaktion, die den Rest deines Lebens andauern wird, wenn du dich
nicht bewusst darum bemühst, sie zu unterbrechen.

**Denke daran: Reduzieren wird dich nach unten ziehen.**
