# Nur ein Blick

\"Nur ein Blick\" ist ein Mythos, den du aus deinem Kopf streichen
musst:

-   Es ist nur ein Blick, der uns dazu bringt, überhaupt erst
    anzufangen.

-   Es ist nur ein Blick, der uns über eine schwierige Phase hinweghilft
    oder zu einem besonderen Anlass, der die meisten unserer Versuche,
    aufzuhören, zunichte macht.

-   Es ist nur ein Blick, der uns, nachdem wir es geschafft haben, die
    Sucht zu überwinden, zurück in die Falle schickt. Manchmal ist es
    nur die Bestätigung, dass man sie nicht mehr brauchen, und ein
    einziger Haremsbesuch tut genau das.

Die Nachwirkungen von Pornografie sind schrecklich und überzeugen den Nutzer
davon, dass er nie wieder süchtig werden wird - aber er ist es bereits.
Der Nutzer hat das Gefühl, dass etwas, das ihn so unglücklich und
schuldig macht, ihn nicht dazu bringen sollte, es zu tun, und doch hat
er es.

Es ist der Gedanke an die \"EINE besondere Sitzung\", der die Nutzer oft
davon abhält, aufzuhören - die Sitzung nach einer langen Konferenzreise,
einem harten Arbeitstag, einem Streit mit den Kindern oder einem
Vorfall, bei dem dein Partner dich beim Sex zurückgewiesen hat. Sei dir bewusst,
dass es so etwas wie \"nur einen Blick\" nicht gibt. Es ist eine
Kettenreaktion, die den Rest deines Lebens andauern wird, wenn sie nicht
unterbrochen wird. Der Mythos vom gelegentlichen, besonderen Anlass
sorgt dafür, dass die Nutzer nach dem Aufhören Trübsal blasen. Mach dir
zur Gewohnheit, dass du nie die \"keine große Sache\"-Sitzung vor dir siehst,
denn das ist Fantasie. Wann immer du an Pornografie denkst, stell dir ein
schmutziges Leben vor, in dem du Äonen von Zeit hinter einem Bildschirm
verbringst, um dich geistig und körperlich zu zerstören, ein Leben in
Sklaverei und Hoffnungslosigkeit. Es ist kein Verbrechen, wenn deine
Erektionen unzuverlässig sind, aber es ist ein Verbrechen, wenn du
langfristig glücklicher sein könntest, dich aber stattdessen dafür
entscheidest, dies für kurzfristiges \"Vergnügen\" zu opfern.

Es ist okay, dass wir uns nicht immer etwas einfallen lassen können, um die Leere
zu füllen, denn das ist nicht in jedem einzelnen Fall in unserem Leben möglich. 
Wir können die meisten Dinge planen, aber manchmal
passiert es einfach. Gute und schlechte Zeiten gibt es auch unabhängig
von Pornografie. Aber mach dir bewusst, dass es nicht an der Pornografie liegt. Du
hast entweder lebenslanges Elend vor dir oder gar keins. Du würdest
nicht im Traum daran denken, Zyanid zu nehmen, nur weil du den
Geschmack von Mandeln magst, also hör auf, dich mit gelegentlichen
'Keine große Sache'-Sitzungen zu strafen. Frag einen Nutzer mit
Problemen, *\"Wenn du die Möglichkeit hättest, in die Zeit
zurückzugehen, bevor du süchtig wurdest, wärst du dann ein Nutzer
geworden?\"* Die Antwort lautet unweigerlich: *\"Du machst wohl
Witze!\"* Doch jeder Nutzer hat jeden Tag seines Lebens diese Wahl, warum
entscheidet er sich also nicht dafür? Die Antwort ist Angst. Die Angst, dass
er nicht aufhören kann oder dass sein Leben ohne sie nicht mehr
dasselbe sein wird.

Hör auf, dir etwas vorzumachen! Du kannst es, jeder kann es. Es ist
lächerlich einfach, aber damit es das ist, gibt es bestimmte
Grundlagen, die du dir klar machen musst.

1.  Es gibt nichts aufzugeben, sondern nur wunderbare positive Gewinne
    zu erzielen.

2.  Glaube niemals, dass es \"Keine große Sache\"- oder \"Nur ein kurzer
    Blick\"-Sitzungen gibt. Die gibt es nicht! Es gibt nur ein Leben
    voller Schmutz und Sklaverei.

3.  An dir ist nichts anders, jeder Nutzer kann leicht damit aufhören.

Viele Nutzer glauben, dass sie eingefleischte Süchtige sind oder zu Sucht 
tendierende Persönlichkeiten haben. Das passiert meist, weil sie zu viel
schockierende Gehirnforschung lesen. So etwas gibt es nicht - niemand
wird mit dem Bedürfnis geboren, zu Videoclips zu masturbieren. 
Es ist die Droge, die dich süchtig macht, nicht die Art
deines Charakters oder deiner Persönlichkeit. Die Art der süchtig
machenden unnatürlichen Reize lässt dich glauben, dass dies jedoch 
der Fall ist. Es ist sehr wichtig, diesen Glauben zu zerstören, denn wenn du
glaubst, dass du süchtig bist, wirst du es auch bleiben, selbst wenn das
kleine Monster in deinem Körper längst tot ist. Es ist wichtig, dass du
diese Gehirnwäsche ablegst.
