# Gelegenheitsnutzer

Starknutzer tendieren dazu Gelegenheitsnutzer zu beneiden. Wir alle sind solchen Typen schonmal begegnet: "Oh, ich kann die ganze Woche lang ohne Sitzung klarkommen, das stört mich nicht wirklich." Wir wünschten, wir wären so wie sie. Es ist zwar schwer zu glauben, aber kein Nutzer geniesst es, Nutzer zu sein. Vergiss niemals:

Kein Nutzer entscheidet sich, einer zu sein, ob gelegentlich oder oft nutzend, deswegen
kommen alle Nutzer sich dumm vor, deswegen
müssen alle Nutzer sich selbst belügen in dem sinnlosen Versuch ihre Dummheit zu rechtfertigen.
Golffanatiker geben damit an wie OFT sie spielen und wie oft sie spielen wollen, aber warum geben Nutzer damit an wie WENIG sie masturbieren?

Wenn dir jemand sagt: "Ich komme die ganze Woche ohne Möhren aus und das macht mir nicht das geringste aus", würdest du doch denken der hat einen an der Schüssel. Wenn ich Möhren mögen würde, warum sollte ich eine ganze Woche auf sie verzichten? Und wenn ich sie nicht mögen würde, warum mpsste ich das dann so betonen? Wenn ein Nutzer also einen Kommentar darüber macht, dass er eine ganze Woche ohne Sitzung ausgekommen ist, versucht er sich selbst - und dich - davon zu überzeugen dass er kein Problem hat. Übersetzt bedeutet dieser Kommentar "Ich habe es geschafft eine Woche ohne Pornografie zu überleben". Wie jeder Nutzer hoffend darauf dass er den Rest seines Lebens so überleben kann. Wenn er nur eine einzige Woche ohne sie überleben kann, stell dir mal vor, wie erlösend die erste Sitzung danach wohl war, nachdem er eine ganze Woche ohne klarkommen musste.

Das ist der Grund warum Gelegenheitsnutzer im Endeffekt stärker abhängig sind als Starknutzer. Nicht nur ist die Illusion des Vergnügens größer, sondern sie haben noch weniger Ansporn aufzuhören, weil sie damit weniger Zeit verbringen und deswegen weniger anfällig für die gesundheitlichen Risiken sind. Von Zeit zu Zeit mögen sie sexuelle Dysfunktion erleiden, sind sich aber nicht sicher warum das so ist und schieben es auf andere Gründe. Das Vergnügen ist eine Illusion - stell dir das kleine Monster einfach also nahezu nicht wahrnehmbaren Juckreiz vor, dem sie sich die meiste Zeit nicht bewusst sind.

Wenn du einen ständigen Juckreiz hast, neigst du natürlich dazu, ihn zu
kratzen. Da die Belohnungsschaltkreise des Gehirns zunehmend immun gegen
Dopamin und Opiate werden, besteht die natürliche Tendenz, zu edgen, zu
eskalieren, zu bingen (ein Film nach dem anderen gucken), nach Neuem zu
suchen, nach Schockierendem zu suchen usw. Es gibt vier Hauptfaktoren, die
verhindern, dass die Nutzer bingen.

Zeit.

:   Die meisten können sich das nicht leisten.

Gesundheit

:   Um den Reiz zu lindern, müssen wir alles kostenlose Material
    konsumieren, das zur Verfügung steht, und noch einiges mehr. Die
    Fähigkeit, mit dieser Art von Binging umzugehen, variiert bei jedem
    Menschen zu verschiedenen Zeiten und in verschiedenen Situationen
    seines Lebens. Das wirkt wie eine automatische Limitierung.

Disziplin

:   Disziplin ist auferlegt von der Gesellschaft, der Arbeit, den Freunden und
    Verwandten oder vielleicht sogar vom Nutzer selbst als Ergebnis des
    natürlichen Tauziehens, das im Kopf jedes Nutzers stattfindet.

Vorstellungskraft

:   Mangelnde Vorstellungskraft reduziert den Schock, die Neuheit und
    andere Werte des Clips auf einer subjektiven Basis.

Es ist leicht, \"Starknutzer\" für schwach zu halten, die nicht
verstehen können, warum andere ihren \"Konsum\" einschränken können.
Starknutzer sollten jedoch bedenken, dass die meisten
Gelegenheitsnutzer einfach nicht in der Lage sind, viel und stetig Pornografie 
zu schauen, da sie dafür eine sehr starke Vorstellungskraft und große Ausdauer 
brauchen. Einige der Einmal-die-Woche-Konsumenten, die von Starknutzern
beneidet werden, sind körperlich nicht in der Lage, mehr zu tun, oder ihr Job, die
Gesellschaft oder ihr Hass auf mögliche Abhängigkeit lassen es nicht zu, mehr zu
tun.

Es kann von Vorteil sein, ein paar Definitionen zu geben.

Der Nicht-Nutzer

:   Jemand, der nie in die Falle getappt ist, aber nicht selbstgefällig
    sein sollte. Er ist nur durch Glück oder die Gnade des Guten ein
    Nicht-Nutzer. Alle Nutzer waren davon überzeugt, dass sie nie
    süchtig werden würden, und einige Nicht-Nutzer versuchen es immer
    wieder mit einer gelegentlichen Sitzung.

Der Gelegenheitsnutzer

:   Es gibt zwei grundlegende Klassifizierungen von Gelegenheitsnutzern.

    1.  Der Nutzer, der in die Falle getappt ist, es aber nicht bemerkt -
        beneide solche Nutzer nicht. Sie probieren nur den Nektar an der
        Mündung der Kannenpflanze und werden höchstwahrscheinlich bald
        zu Starknutzern. Denke daran: Do wie alle Alkoholiker als
        Gelegenheitstrinker angefangen haben, fangen auch alle
        Starknutzer als Gelegenheitsnutzer an.

    2.  Der Nutzer, der früher ein Starknutzer war und deshalb denkt,
        dass er nicht komplett aufhören kann. Diese Nutzer sind die
        traurigsten von allen und gehören in verschiedene Kategorien, von
        denen jede einen eigenen Kommentar benötigt.

Der Einmal-pro-Tag Nutzer

:   Wenn der Anspruch auf einen Orgasmus genossen wird, warum sollte man
    dann Internetpornografie nur einmal täglich nutzen? Wenn man es auch
    lassen kann, warum sollte man sich dann überhaupt die Mühe machen? Vergiss
    nicht, dass die \"Gewohnheit\" in Wirklichkeit darin besteht, den
    Kopf gegen die Wand zu schlagen, damit es sich beim Aufhören
    entspannend anfühlt. Wer einmal am Tag nutzt, lindert seine
    Entzugserscheinungen für weniger als eine Stunde pro Tag. Auch wenn
    man es nicht merkt, verbringt man den Rest des Tages damit, seinen
    Kopf gegen die Wand zu schlagen, und das tut man für den Großteil seines
    Lebens. Man konsumiert einmal am Tag, weil man nicht riskieren
    kann, erwischt zu werden oder seine neurologische Gesundheit zu
    gefährden. Es ist leicht, einen Starknutzer davon zu überzeugen,
    dass es ihm keinen Spaß macht, aber wesentlich schwieriger, einen
    Gelegenheitskonsumenten zu überzeugen. Jeder, der schon einmal
    versucht hat, seinen Konsum zu reduzieren, weiß, dass dies die
    schlimmste aller Folterungen ist und fast garantiert, dass man für
    den Rest seines Lebens abhängig bleibt.

Der zurückgewiesene Nutzer

:   Er verlangt das Recht, jeden Tag einen Orgasmus zu haben, aber sein
    Sexpartner ist nicht immer bereit, diese Bitte zu erfüllen. Anfangs
    nutzt er Internetpornografie, um diese Leere zu füllen, aber sobald er
    die aufregende \"Wasserrutsche\" nimmt, ist er in einem
    Kreislauf aus Neuheit, Schock, unnatürlichen Bildern usw. gefangen.
    Eigentlich ist er froh über die Ablehnung seines Partners, denn das
    gibt ihm so etwas wie eine Ausrede. Wenn Internetpornografie dir so viel
    geben, warum möchtest du dann überhaupt einen Partner haben? Lass
    sie stattdessen frei. Du genießt nicht einmal die Sitzungen, wenn
    du deinen Partner in deinen Gedanken mit dir rumtragen musst. Irgendwann
    willst du, dass dein Partner im wirklichen Leben dich mit einer Ausrede 
    versorgt, um in das Tal der dunklen Seite des Internets zu
    gehen.

Der Porn-Diät PMOer

:   Auch bekannt als: *\"Ich kann aufhören, wann immer ich will. Ich
    habe es schon tausende Male getan!\"*\
    Wenn sie glauben, dass eine Diät ihnen hilft, in Stimmung zu kommen,
    um sich einen Partner zu suchen, warum machen sie dann überhaupt diese
    Diät Niemand kann die Zukunft vorhersagen. Was ist, wenn das zufällige 
    Treffen eine Stunde nach der geplanten Sitzung stattfindet? Und wenn gelegentliche
    \"Rohrreinigung\" gut ist, um Spannungen abzubauen, warum dann
    nicht jeden Tag? Es ist erwiesen, dass Selbstbefriedigung nicht
    notwendig ist, um die Genitalien gesund zu halten, und
    Internetpornografie ist überhaupt nicht notwendig. Selbst wenn das der
    Fall wäre, wird kein Anmach-Guru, der über die neurologischen
    Schäden gelesen hat, jemals empfehlen, Superstimulus-Pornos
    anzusehen. Die Wahrheit ist, dass sie immer noch süchtig sind. Auch
    wenn sie von der körperlichen Sucht befreit sind, bleibt ihnen das
    Hauptproblem der Gehirnwäsche. Sie hoffen jedes Mal, dass sie für
    immer damit aufhören können, tappen aber bald wieder in die gleiche
    Falle.

    Die meisten Nutzer sind neidisch auf diese Stopp-Starter und
    denken darüber nach, wie \"glücklich\" der Diätwillige ist, dass er
    seinen Konsum kontrollieren kann. Dabei übersehen sie jedoch, dass
    der Diätwillige seinen Konsum nicht unter Kontrolle hat und sich
    wünscht, er würde es nicht tun, wenn er er gerade dabei ist. Sie hören 
    unter Mühen auf, fühlen sich dann beraubt und tappen wieder in die
    Falle und wünschen sich, sie hätten es nicht getan. Sie bekommen das
    Schlimmste aus beiden Welten. Wenn du darüber nachdenkst, ist das
    auch im Leben der Nutzer der Fall, wenn sie eine Sitzung haben
    dürfen und es als ihr Recht ansehen oder sich wünschen, sie hätten
    es nicht getan. Erst wenn man es ihnen vorenthält, wird es wertvoll.
    Das Syndrom der \"verbotenen Frucht\" ist eines der schrecklichen
    Dilemmas für Nutzer. Sie können nie gewinnen, weil sie einem Mythos,
    einer Illusion nachtrauern. Es gibt nur einen einzigen Weg, wie sie
    gewinnen können: indem sie aufhören, Trübsal zu blasen, indem sie
    mit Pornos aufhören!

Der \"Ich gucke nur statische/sichere/Amateur-Pornografie"\"-Nutzer

:   Ja, das macht am Anfang jeder, aber ist es nicht erstaunlich, wie
    der durchschnittliche Schockwert dieser Clips schnell ansteigt, und
    bevor wir uns versehen, fühlen wir uns als würden wir etwas
    vermissen (Toleranz)? Der Reiz des Neuen fehlt bei statischer
    Pornografie, also zahlen wir die Zeche für eine Tasse Fett und fahren die
    Wasserrutsche hinunter in Richtung Groll und Schuld. Das Schlimmste,
    was du tun kannst, ist, die Bilder deines Partners (natürlich mit
    seiner Zustimmung) zur Selbstbefriedigung zu verwenden. Warum? Weil
    du damit dein Gehirn auf die Suche und Abwechslung verursachten
    Dopaminschübe neu kalibrierst. Die Porno-Wasserrutschen in deinem
    Gehirn bauen DeltaFosB auf, so dass du Schwierigkeiten haben wirst,
    wenn du mit ihnen im echten Leben zusammen bist.

    Eine weitere Falle in dieser Kategorie sind \"Amateur\"- und
    \"selbstgemachte\" Pornos. Die meisten sind Fälschungen und du weißt
    das. Du wirst auch nicht beim ersten aufhören, der dir ins Auge
    springt, sondern weiter machen und weiter und suchen. Vergiss nicht, 
    dass das Gehirn nicht nur den Orgasmus will, sondern auch die Neuheit 
    der Jagd, die der Wasserrutsche ihren Nervenkitzel verleiht. Der
    Inhalt ist nicht das Problem, egal ob Amateur oder Professionell, es
    sind die Dopaminschübe im Gehirn, die zu Toleranz und Sättigung
    führen. Pornografie zerstört die normale Gehirnfunktion, Masturbation
    verwirrt die Muskel-Gehirn-Reaktion. Der Orgasmus überflutet das
    Gehirn mit Opiaten, sodass der Weg beim nächsten Mal leichter zu
    beschreiten ist.

Der \"Ich habe aufgehört, aber schaue ab und zu\" Nutzer

:   In gewisser Weise sind die Ab-und-Zu-Nutzer die erbärmlichsten von
    allen. Entweder gehen sie durch ihr Leben und glauben, dass sie
    beraubt werden, oder, was noch häufiger vorkommt, aus dem
    gelegentlichen Blick werden zwei. Sie rutschen auf der schiefen
    Bahn nach unten und werden früher oder später wieder zu
    Starkkonsumenten. Sie sind wieder in die gleiche Falle getappt, in
    die sie schon einmal getappt sind.

Es gibt zwei weitere Kategorien von Gelegenheitsnutzern. Die erste ist
die, die zu Bildern oder Clips der neuesten Sexvideos von Prominenten
masturbiert, die in den Nachrichten auftauchen, oder zu etwas, das sie
von einer \"zufälligen\" Sichtung in der Schule oder auf der Arbeit
\"mit nach Hause genommen\" haben. Diese Menschen sind eigentlich nur
Nichtnutzer, aber sie haben das Gefühl, dass sie etwas verpassen. Sie
wollen Teil des Geschehens sein, und die meisten von uns fangen so an.
Bald schon merkst du, dass der Prominente deiner Fantasie nach
einer Weile nicht mehr so toll ist. Je \"unerreichbarer\" das Ziel
deiner Fantasie ist, desto frustrierender ist der Entzug des Orgasmus.

Die zweite Kategorie hat in letzter Zeit an Aufmerksamkeit gewonnen und
lässt sich am besten anhand eines Falles beschreiben, der online geteilt
wurde. 

Eine berufstätige Frau hatte viele Jahre lang Internetpornografiegeschichten
gelesen, einmal pro Nacht. Sie war im Übrigen eine sehr willensstarke Frau. 
Die meisten Nutzer würden sich fragen, warum sie überhaupt aufhören wollte, und
wiesen gerne darauf hin, dass in ihrem Fall keine Gefahr von PIED oder
PE bestand (was nicht stimmte). Sie benutzte nicht einmal statische
Bilder, die Geschichten waren viel zahmer als die, die die meisten selbst
täglich benutzen.

Sie machen den Fehler, anzunehmen, dass Gelegenheitsnutzer glücklicher
sind und mehr Kontrolle haben. Sie haben vielleicht mehr Kontrolle, sind
aber sicher nicht glücklich. Im Fall der Frau war sie weder mit ihrem
Partner noch mit echtem Sex zufrieden und sehr reizbar, wenn sie auf
ihre täglichen Belastungen reagierte. Ihr Liebster konnte nicht
herausfinden, was sie bedrückte. Selbst wenn sie sich durch
Rationalisierung einredete, dass sie keine Angst vor ihrem Gebrauch
hatte, war sie immer noch nicht in der Lage, echte Beziehungen zu
genießen, die immer mit Höhen und Tiefen verbunden sind. Das
Belohnungszentrum ihres Gehirns war nicht in der Lage, die normalen
De-Stressoren des Lebens zu nutzen, da es täglich mit Dopamin überflutet
wird. Die daraus resultierende Herunterregulierung der Rezeptoren in
ihrem Gehirn hat sie meist mit einem melancholischen Gefühl zurückgelassen.
Wie die meisten hatte sie große Angst vor der dunklen Seite der Pornografie
und der Behandlung von Frauen - bevor sie es zum ersten Mal sah.
Schließlich fiel sie der Gehirnwäsche der Gesellschaft zum
Opfer und probierte ihre erste Webseite aus. Anders als die meisten, die
kapitulieren und zu Kettennutzern werden, widerstand sie dem Abgleiten,
als sie die widerlichen Gewaltclips sah.

Das Einzige, was du je an Pornografie genießt, ist die Beendigung des
Verlangens, das zuvor begonnen hat, sei es das kaum wahrnehmbare
körperliche Verlangen oder die seelische Folter, den Juckreiz nicht
kratzen zu dürfen. Internetpornografie selbst ist Gift, weshalb du die
Illusion, sie zu genießen, nur nach einer gewissen Zeit der Abstinenz
erträgst. Ähnlich wie bei Hunger oder Durst gilt: Je länger du sie
erträgst, desto größer ist die Freude, wenn sie endlich vorbei ist. Du machst
den Fehler zu glauben, dass Pornografie nur eine Gewohnheit ist,
und denkst: *\"Wenn ich es auf ein bestimmtes Maß beschränken kann oder
nur zu besonderen Anlässen, werden mein Gehirn und mein Körper es
akzeptieren. Dann kann ich den Konsum auf diesem Niveau halten oder
weiter reduzieren, wenn ich das möchte.* Sei dir darüber im Kalren, dass es die
\"Gewohnheit\" gar nicht gibt. Pornografie ist eine Drogensucht, bei der die
natürliche Tendenz darin besteht, die Entzugserscheinungen zu lindern,
nicht sie auszuhalten. Um den Konsum auf dem jetzigen Niveau zu halten,
müsstest du für den Rest deines Lebens ein enormes Maß an Disziplin und
Willenskraft aufbringen, denn wenn das Belohnungszentrum deines Gehirns
immun gegen Dopamin und Opiate wird, will es immer mehr und nicht immer
weniger.

Während Pornografie nach und nach dein Nervensystem, deinen Mut, dein
Selbstvertrauen und deine Impulskontrolle zerstört, wirst du gleichzeitig
immer weniger in der Lage sein, dem Verkürzen der Abstände zwischen den
einzelnen Sitzungen zu widerstehen. Deshalb können wir in den ersten
Tagen so leicht aufhören oder anfangen, wie wir wollen. Wenn wir ein
Anzeichen dafür sehen, dass etwas nicht in Ordnung ist, hören wir
einfach auf. Beneide diese Frau nicht, denn wenn du nur einmal alle
vierundzwanzig Stunden einen Porno siehst, erscheint er dir als das
Kostbarste auf der Welt und macht Pornografie zu einer \"verbotenen Frucht\".
Viele Jahre lang stand diese arme Frau im Zentrum eines Tauziehens.

Obwohl sie nicht aufhören konnte, Pornografie zu konsumieren, hatte sie Angst
davor, es mit Streaming-Clips zu übertreiben. Dreiundzwanzig Stunden und
zehn Minuten lang musste sie an jedem dieser Tage gegen die Versuchung
und die fehlenden Gefühle gegenüber ihrem Freund ankämpfen. Es brauchte
enorme Willenskraft, um das zu tun, was sie tat, und am Ende brach sie
in Tränen aus. Solche Fälle sind selten, aber betrachte es logisch:
Entweder gibt es eine echte Krücke oder Freude an Pornografie - oder nicht.
Wenn es sie gibt, wer will dann eine Stunde, einen Tag oder eine Woche
warten? Warum solltest du in der Zwischenzeit auf das Vergnügen
verzichten müssen? Wenn es keine echte Hilfe oder Vergnügen gibt,
warum solltest du dann deinem Online-Harem einen Besuch abstatten?

Hier ist ein weiterer Fall eines Mannes, der einmal in vier Tagen nutzt
und sein Leben wie folgt beschreibt:\
*\"Ich bin vierzig Jahre alt, ich habe PIED mit echten Frauen und sogar
bei der Nutzung von Pornos, was meistens der Fall ist. Es ist schon eine
Weile her, dass ich eine komplette Erektion hatte. Bevor ich mich auf die
Porno-Diät einließ, schlief ich nach einer Sitzung die ganze Nacht durch.
Jetzt wache ich jede Stunde in der Nacht auf und kann an nichts anderes
mehr denken. Selbst wenn ich schlafe, träume ich von meinen
Lieblingsclips. An den Tagen nach meiner geplanten Sitzung fühle ich
mich ziemlich niedergeschlagen, weil die Diät meine ganze Energie
aufbraucht. Meine bessere Hälfte lässt mich allein, weil ich
so schlecht gelaunt bin, und wenn sie nicht gehen kann, will sie mich 
nicht im Haus haben. Ich gehe draußen joggen, aber mein Geist ist wie 
besessen davon. An dem geplanten Tag fange ich schon in der Nacht vorher
an zu planen und werde sehr, gereizt, wenn etwas unvorhergesehenes passiert. 
Ich ziehe mich aus Gesprächen zurück und gebe bei der Arbeit und zu Hause nach 
(nur um es später zu bereuen). Ich bin kein streitsüchtiger Typ, aber ich will
nicht, dass mich das Thema oder die Unterhaltung aufhält. Ich erinnere
mich an Zeiten, in denen ich dumme Streitereien mit meiner besseren Hälfte
angefangen habe. Ich warte darauf, dass es 22 Uhr wird undd wenn es so weit ist, 
zittern meine Hände unkontrolliert. Ich fange nicht gleich damit an, denn es sind
neue Videos hinzugekommen, also \"schaue ich mich um\". Mein Verstand
sagt mir, dass ich, nachdem ich vier Tage lang gehungert habe, einen
\"besonderen\" Clip verdient habe, der die Zeit der Suche wert sein
muss. Schließlich entscheide ich mich für einen oder zwei, aber ich
will, dass es länger hält, damit ich die nächsten vier Tage 'überleben'
kann, also nehme ich mir mehr Zeit, um die Tat zu vollenden.*\

Zusätzlich zu seinen anderen Problemen hat der arme Mann keine Ahnung,
dass er sich selbst mit Gift behandelt. Erst leidet er unter dem
\"Syndrom der verbotenen Früchte\" und dann zwingt er sein Gehirn,
Dopamin auszuschütten. Seine Dopaminrezeptoren sind nicht zu stark geschädigt,
aber er schmiert die Porno-Wasserrutschen, such nach Aufregung, Neuheit, Abwechslung, Schock und Angst, um die nächsten vier Tage zu überleben. Wahrscheinlich stellst du dir
diesen Mann als erbärmlichen Schwachkopf vor, aber das ist nicht so. Als
ehemaliger Sportler und ehemaliger Marineoffizier wollte er nicht
süchtig nach irgendetwas werden. Nach seiner Rückkehr aus dem Krieg
absolvierte er jedoch eine Ausbildung zum IT-Techniker in einem
Reha-Programm für Veteranen. 

Als er in das zivile Arbeitsleben eintrat, war er ein gut bezahlter IT-Fachmann in einer Bank und bekam einen Laptop, um seine Arbeit mit nach Hause zu nehmen. Es war das Jahr, in
dem berühmte Prominente ihre Pornovideos online \"leakten\" und es wurde
viel darüber gesprochen. Daraufhin wurde er süchtig und verbrachte den
Rest seines Lebens damit, viel Geld zu bezahlen und sich körperlich und
geistig zu ruinieren. Wenn er ein Tier wäre, hätte die Gesellschaft ihn
schon längst von seinem Elend erlöst, aber wir lassen es immer noch zu,
dass geistig und körperlich gesunde junge Teenager süchtig werden. Du
magst diesen Fall für übertrieben halten, aber dieser - auch wenn extrem -
ist bei weitem kein Einzelfall. Es gibt Zehntausende von ähnlichen Geschichten. 
Kannst du dir sicher sein, dass keine seiner Freunde und Bekannten ihn darum beneidet hat, dass er nur ein Alle-Vier-Tage-Typ ist? Wenn du denkst, dass dir das nicht passieren
kann, **dann mach dir nichts vor.**

ES PASSIERT JETZT GERADE.

Wie andere Süchtige sind auch Pornografienutzer notorische Lügner, sogar sich
selbst gegenüber. Das müssen sie auch. Die meisten Gelegenheitsnutzer
konsumieren viel öfter und bei viel mehr Gelegenheiten, als sie zugeben.
In vielen Gesprächen mit so genannten Zweimal-pro-Woche-Nutzern geben
sie zu, dass sie es mehr als drei oder vier Mal in der Woche getan
haben. Lies die Beiträge von Gelegenheitsnutzern auf reddit, NoFap und
in Reboot-Foren und du wirst feststellen, dass sie entweder die Tage
zählen oder darauf warten, zu versagen. Du brauchst Gelegenheitsnutzer
nicht zu beneiden, du brauchst auch keine Pornografie zu nutzen, das Leben ist
unendlich viel süßer ohne sie. Lies mal den folgenden Eintrag:

*\"Es begann mit einer einfachen Herausforderung, meinen Penis einen Tag
lang nicht zu berühren, und ich konnte es nicht. Ich denke nicht mehr an
Selbstbefriedigung, sie kommt mir nicht in den Sinn. Das ist möglich,
ich verspreche es dir. Der Reichtum, der auf diejenigen wartet, die dazu
in der Lage sind - er ist unglaublich.\"*

Teenager sind in der Regel schwieriger zu heilen, nicht weil es ihnen
schwerer fällt, aufzuhören, sondern weil sie nicht glauben, dass sie
abhängig sind oder sich im Anfangsstadium der Falle befinden und unter
der Illusion leiden, dass sie automatisch vor dem zweiten Stadium
aufgehört haben.

Eltern von Kindern, die Internetpornografie verabscheuen, sollten sich nicht
in falscher Sicherheit wiegen. Alle Kinder verabscheuen die dunklen
Seiten von Pornografie - bevor sie süchtig werden. Irgendwann hast auch du das
getan. Lass dich auch nicht von Panikmache täuschen, die Falle ist
dieselbe wie immer. Kinder wissen, dass Internetpornografie einen
unnormalen Reiz darstellt, aber sie wissen auch, dass ein \"Besuch\"
oder \"Blick\" nicht ausreicht. Irgendwann werden sie vielleicht von
einem Partner, Mitschüler oder Arbeitskollegen beeinflusst.

Werde bitte nicht selbstgefällig in dieser Angelegenheit. Das Versagen der Gesellschaft, Jugendliche davor zu bewahren, süchtig nach Internetpornos und anderen Drogen zu werden,
ist vielleicht die beunruhigendste der vielen Facetten der Sucht. Es ist notwendig, Jugendliche aufzuklären und davor zu schützen, da ihr Gehirn in ihrem Alter noch sehr plastisch ist. Ein gutes Hilfsmittel ist das Buch YourBrainOnPorn und die Aufklärung über die Neurowissenschaften. Selbst wenn du den Verdacht hast, dass dein Teenager bereits süchtig sein könnte, bietet das Buch eine hervorragende Anleitung, um zu verstehen,
wie man jemandem helfen kann, davon loszukommen. Empfehle ansonsten dieses Buch!
