# Der Youtube-Nutzer

Dieser Nutzer sollte zu den Gelegenheitsnutzern gezählt werden, aber die
Auswirkungen sind so heimtückisch, dass er ein eigenes Kapitel verdient.
Sie führen zum Zusammenbruch der Selbstkontrolle, was bei einem Nutzer des
NoFap-Forums fast zu einer Trennung geführt hätte:

*Ich war in der dritten Woche einer meiner fehlgeschlagenen Versuche aufzuhören, 
und der Auslöser für den Versuch war die Sorge meiner Frau über meine
unzuverlässigen Ständer und mein Desinteresse. Ich hatte ihr gesagt,
dass es nicht an ihr lag, sondern nur am beruflichen Druck. Sie sagte:
\"Ich weiß, dass du mit dem Arbeitsdruck schon zurechtgekommen bist,
aber wie würdest du dich an meiner Stelle fühlen, wenn du zusehen
müsstest, wie sich jemand, den du liebst, systematisch selbst
zerstört?\" Das war ein Argument, das ich bestechend fand, daher
der Versuch, aufzuhören. Sie weiß, dass ich sie nicht betrüge, aber das
ist in gewisser Weise noch schlimmer. Der Versuch endete nach
drei Wochen in einem heftigen Streit mit einem alten Freund. Erst Jahre
später wurde mir klar, dass mein hinterhältiger Verstand den Streit
absichtlich ausgelöst hatte. Ich fühlte mich damals zu Recht verärgert,
aber ich glaube nicht, dass das ein Zufall war, denn ich hatte mich weder
zuvor noch danach mit diesem Freund gestritten. Es war eindeutig das
kleine Monster am Werk.*

*Egal, ich hatte eine Ausrede. Ich brauchte dringend eine Erleichterung
und es war egal, wie. Meine Frau war nicht in der Stimmung, also fühlte
ich mich \"berechtigt\" und redete mir ein, dass es in Ordnung sei, wenn
ich mich selbst \"einschränke\", indem ich Pornografieseiten meide und nur
YouTube-Videos anschaue, um die \"rote Linie\" nicht zu überschreiten.
Aber meine Frau kam im Laufe der Nacht wieder zu sich und wollte mit mir
schlafen, aber ich war müde und hatte keine Kraft mehr, also erfand ich
Kopfschmerzen. Ich konnte es nicht ertragen, an die Enttäuschung zu
denken, die das bei meiner Frau auslösen würde. Dann kehrte ich
allmählich zu meinen alten Gewohnheiten zurück, mit YouTube als
meinem neuen Haremsziel. Ich erinnere mich, dass ich damals recht
zufrieden war, weil ich dachte, dass ich dadurch wenigstens meinen
Konsum einschränken würde. Schließlich warf sie mir vor, ich würde sie
im Bett weiterhin ignorieren. Ich hatte es nicht bemerkt, aber sie
beschrieb, wie oft ich einen Streit ausgelöst hatte und aus dem Haus
gestürmt war. Ein anderes Mal brauchte ich zwei Stunden, um irgendeine
Kleinigkeit zu kaufen und täuschte Verstauchungen vor. Ich hatte mir
schwache Ausreden einfallen lassen, um sie nicht umwerben zu müssen, und
wenn ich einen zuverlässigen Online-Harem habe, ist es noch
schwieriger.\"*

Das Schlimmste für den YouTube-Nutzer ist, dass dies den Trugschluss in
seinem Kopf unterstützt, dass er beraubt wird. Gleichzeitig
führt es zu einem großen Verlust an Selbstachtung; eine ansonsten
ehrliche Person kann sich dazu zwingen, ihren Liebsten zu betrügen. Das
ist dir wahrscheinlich auch schon passiert oder passiert dir noch in
irgendeiner Form.

Die Probleme, die mit Websites wie Twitch, Instagram, TikTok und Twitter
verbunden sind, werden in erster Linie durch "Ergänzung" verursacht. 
Angetrieben von der Suche nach Dopamin-Höhepunkten durch Neuheit, gaukeln sie 
sich selbst vor, dass sie auf einer sicheren Seite sind. Vergiss nicht, der 
Nervenkitzel liegt in der Suche, nicht im Töten, und dem kleinen Monster ist es egal, woher es seinen Kick bekommt. Für die Nutzer sind die \"harmlosen\" Inhalte, die
sie in ihren verschiedenen Online-Feeds erhalten, eine flüchtige
Erleichterung ihrer Entzugserscheinungen, die sie abhängig halten und auf
ihre Sitzung warten lassen.

Das model in dem Bild/Video ist wahrlich schön, und wenn es jetzt bei dir wäre, würde es dir Befriedigung verschaffen, aber das Bild kann es nicht... Es ist einfach nicht real. Dein Gehirn wird ausgetrickst wie ein Stier,  der auf ein rotes Tuch zurennt, und hinterher gar nicht versteht warum. Man könnte meinen dass man sich dann einfach diese Bilder anschauen kann, ohne zu masturbieren. Aber denke daran dass dein Gehirn von dieser endlosen Neuigkeit abhängig ist, und dem kleine Monster ist es egal woher sein Fix kommt.

Vielleicht hast du schon einmal die Fernsehserie Columbo gesehen, die in
jeder Folge ein ähnliches Thema hat. Der Bösewicht, in der Regel ein
wohlhabender und angesehener Geschäftsmann, hat einen Mord begangen, von
dem er überzeugt ist, dass er perfekt ist. Seine Zuversicht, dass sein
Verbrechen unentdeckt bleibt, wird noch gestärkt, als er erfährt, dass
der eher schäbig und unscheinbar aussehende Detective Columbo mit dem
Fall betraut ist.

Columbo hat die frustrierende Angewohnheit, nach dem Verhör die Tür zu
schließen, welches dem Verdächtigen versichert, dass er aus dem
Schneider ist, und kurz bevor der zufriedene Ausdruck aus dem Gesicht
des Mörders verschwunden ist, taucht Columbo wieder auf und sagt: \"Nur
eine Kleinigkeit, Sir, die Sie sicher erklären können\...\" Der
Verdächtige stottert und weiß von da an, dass Columbo ihn allmählich
zermürben wird. Egal, wie abscheulich das Verbrechen war, von diesem
Zeitpunkt an waren die Sympathien auf der Seite des Mörders.

Diese Kämpfe sind ähnlich: die Anspannung, die rote Linie nicht
überschreiten zu dürfen, um den Pornofix zu bekommen, den sie \"zu Recht
verdient\" haben, und sich dann zu fragen, worin das Vergnügen gelegen
hat, nachdem man fertig ist. Angst, die Grenze zu überschreiten, die Kontrolle zu verlieren und ins Bett zurückzukehren, nur um von der Angst verfolgt zu werden, dass dein Partner Sex wollte. Wenn dich die \"sicheren\" YouTube-Videos nicht mehr befriedigen, weil
du desensibilisiert bist, keine Lust mehr auf Neues hast und weißt, dass
du früher oder später deinen Lieblings-Online-Harem besuchen wirst. Die
letzte Demütigung und Schande ist, wenn diese Gewissheit zur Tatsache
wird, gefolgt von der sofortigen Rückkehr zum \"Kettengucken\".

OH, DIE FREUDE, ein PMOer zu sein!
