# Eine Soziale Gewohnheit?

Die Gesundheit von Geist und Körper sind die Hauptgründe, warum wir
aufhören _sollten_ - aber das war schon immer so. Wir brauchen eigentlich
keine wissenschaftliche Forschung und keine Kenntnisse der Neurochemie,
um zu wissen, dass Internetpornografie süchtig macht und unser Leben
zerstören kann. Unsere Körper sind die ausgeklügeltsten Objekte auf
diesem Planeten und jeder Nutzer weiß von der ersten Sitzung an, dass
der Reiz ins Unermessliche steigen und giftig werden kann.

Der einzige Grund, warum wir uns überhaupt auf Pornografie einlassen, ist die
Überschneidung des Zyklus mit unserer evolutionären
Programmierung. Internetpornografie ist stets verfügbar,
kostenlos und streamt rund um die Uhr. Früher galten Pornos als
harmlos, aber das war, als die Bilder noch statisch waren und man für
die Videos noch eine VHS-Kassette aus dem Laden holen musste.

Heute ist generell erkannt - selbst von den Nutzern - dass Pornografie einen unnormalen
Reiz darstellt und süchtig macht. Früher hat der starke Mann nicht
zugegeben, dass er masturbiert hat,und Wichser eine abfällige
Bezeichnung war. In jeder Kneipe, jedem Club oder jeder Bar war die
Mehrheit der Männer stolz darauf, eine Frau mit nach Hause zu nehmen und
echten Sex zu haben. Heute ist die Lage für den Internetpornosüchtigen
genau umgekehrt: Der Mann von heute beginnt zu merken, dass er keine
Frau braucht. Er schließt sich online mit anderen zusammen, um Erfahrungen zu
diskutieren, Strategien zu entwickeln und Optionen zu erkunden. Der
starke Mann von heute will nicht von Drogen abhängig sein. Durch die
soziale Revolution denken alle Nutzer ernsthaft darüber nach,
Internetpornos und Selbstbefriedigung zu stoppen. Die Nutzer von heute
halten Pornografie für eine nutzlose und schädliche Aktivität.

Der wichtigste Trend, der in den Foren zu beobachten ist, ist die
zunehmende Betonung der asozialen Aspekte von Pornos. Die Zeiten, in
denen ein Mann damit prahlte, jeden Tag Sex und Orgasmen zu haben,
werden langsam durch die Erkenntnis der Sklaverei gegenüber dem
Pornomonster ersetzt.

Der einzige Grund, warum die Leute weitermachen, nachdem sie aufgeklärt
wurden, ist, dass sie es nicht geschafft haben, aufzuhören oder zu viel
Angst haben, es zu versuchen. Es gibt ein breites Spektrum an Interesse
an dem Thema, einige wenden sich dem Verzicht auf Pornos, Masturbation
und Orgasmus zu - mit oder ohne Partner. Praktiken, die den lustvollen
und den fortpflanzungsfördernden Teil des Geschlechtsverkehrs
voneinander trennen, wie z.B. das Zurückhalten von Sperma und Karezza,
werden diskutiert und in Scharen angenommen. Viele der oben genannten
Misserfolge sind in Wirklichkeit Rückschritte, die die Menschen, die sie
praktizieren, nach vorne bringen. Wenn du den Weg ohne PMO eingeschlagen
hast, wirst du herausfinden, was am besten zu deinem Leben passt. Wenn
du die sexuelle Trennung verstanden und praktiziert hast, kannst du
deinen eigenen Plan für den Orgasmus entwickeln. Welchen Weg du auch
immer wählst, du wirst sehen, dass es sich lohnt, die Anzahl der
Orgasmus-bedingten Chemikalienflutung deins Hirns zu begrenzen und Pornos, Sex und Orgasmen nie wieder als Vergnügen oder Krücke für dein emotionales Selbst zu sehen.

Verschiedene beliebte Online-Gemeinschaften, die von Nicht-Nutzern
gegründet wurden, widmen sich der Aufgabe, nicht nur mit Pornografie, sondern
auch mit der Selbstbefriedigung aufzuhören. Diese Seiten sind für
diejenigen, die davon fliehen, letztlich nützlich, aber die
meisten Hinweise weisen sie darauf hin, es mit Willenskraft zu
versuchen. Die Folge der Besessenheit von Abstinenzphasen und anderen Maßnahmen
ist Selbstmitleid und mangelndes Hochgefühl. Ein Großteil der
Gehirnwäsche ist immer noch da und funktioniert. Irgendwann bricht jemand ein und
es kommt zu einem Dominoeffekt, und andere Nutzer finden heraus, dass
sie nicht die Einzigen sind. Aber ihre Bemühungen sind nicht vergebens,
sie kommen weiter, wenn auch mit viel Selbstquälerei, da sie zwar ihre
Browser, nicht aber die Lust und das Bedürfnis abschalten. EasyPeasy
funktioniert umgekehrt: Es schaltet zuerst das Bedürfnis und den Wunsch
ab, bevor es den Browser ausschaltet. Jeden Tag verlassen mehr und mehr
Nutzer das sinkende Schiff und die, die übrig bleiben, haben Angst, dass
sie die letzten sind.

SEI NICHT DU DER LETZTE!
