# Der richtige Zeitpunkt

Abgesehen von dem offensichtlichen Punkt, dass es dir nicht gut tut und
dass jetzt der richtige Zeitpunkt zum Aufhören ist, ist das Timing
wichtig. Die Gesellschaft behandelt Internetpornografie leichtfertig als eine
leicht geschmacklose Angewohnheit, die deiner Gesundheit keinen Schaden
zufügt. Das ist nicht wahr. Es ist eine Drogensucht, eine Krankheit und
ein Zerstörer von Beziehungen in der Gesellschaft. Das Schlimmste, was
im Leben der meisten Nutzer passiert, ist, von dieser schrecklichen
Sucht abhängig zu werden. Wenn sie süchtig bleiben, passieren furchtbare
Dinge. Das richtige Timing ist daher wichtig, um dich richtig zu heilen.

Als erstes solltest du herausfinden, zu welchen Zeiten oder Anlässen
Pornografie wichtig für dich zu sein scheint. Wenn du ein Geschäftsmann bist, der sie
für die Illusion des Stressabbaus nutzt, wähle eine relativ ruhige Zeit
oder einen Urlaub. Wenn du Pornografie hauptsächlich in langweiligen oder
entspannenden Zeiten nutzt, gilt das Gegenteil. Wie auch immer, nimm den
Versuch ernst und mach ihn zur wichtigsten Sache in deinem Leben.

Schaue drei Wochen in die Zukunft und versuche, jedes Ereignis
vorauszusehen, das zum Scheitern führen könnte. Anlässe wie Konferenzen,
die Abwesenheit deines Partners usw. brauchen dich nicht abzuschrecken,
wenn du sie im Voraus planst und nicht das Gefühl hast, dass du zu kurz
kommst. Versuche nicht, in der Zwischenzeit zu reduzieren, denn das
würde nur die Illusion erwecken, dass die Verweigerung angenehm ist. Es
ist sogar hilfreich, wenn du dich zwingst, so viele Pornos wie möglich
zu schauen und zu haben. Während du die letzte Sitzung und dein letztes
Mal erlebst, achte auf die Enttäuschung aufgrund der Sättigung,
unerfüllten Erwartungen, körperlichen Schmerzen, Entzugserscheinungen,
Verdrießlichkeit und Melancholie. Denke daran, wie schön es sein wird,
wenn du es dir selbst erlaubst, damit aufzuhören.

WAS AUCH IMMER DU TUST, TAPPE NICHT IN DIE FALLE, EINFACH ZU SAGEN
\"NICHT JETZT, SPÄTER\" UND ES AUS DEINEM KOPF ZU VERDRÄNGEN. ARBEITE
JETZT DEINEN ZEITPLAN AUS UND FREUE DICH DARAUF.

Denke daran, dass du NICHTS aufgibst. Ganz im Gegenteil, du bist dabei,
wunderbare positive Vorteile zu erhalten.

Jahrelang hat die Ärzteschaft Pornografie als harmlos angesehen, ohne den
Unterschied zwischen der zahmen statischen Pornografie von früher und dem
neuesten Virtual-Reality-Streaming-Erlebnis zu kennen. Das Problem ist,
dass zwar jeder Nutzer Internetpornografie nur zur Linderung des
Dopaminverlangens nutzt, aber es ist nicht die Sucht nach der
Chemikalie, die den Nutzer fesselt, sondern die Selbstgehirnwäsche, die
aus der Sucht resultiert. Ein intelligenter Mensch fällt auf einen Trick
herein, aber nur ein Narr würde weiter darauf hereinfallen, wenn er
gemerkt hat, dass es ein Trick ist. Glücklicherweise sind die meisten Nutzer
keine Dummköpfe; sie denken nur, dass sie es sind. Jeder einzelne Nutzer
hat seine eigene Gehirnwäsche. Deshalb scheint es auch so viele
verschiedene Arten von Süchtigen zu geben, was die Rätsel nur noch
größer macht.

Obwohl der Nutzen des ursprünglichen Buches darin bestand, mit der 
Nikotinsucht aufzuhören (eine der schnellsten und süchtig machendsten 
Drogen, die der Menschheit bekannt ist), war ich angenehm überrascht festzustellen,
dass die Philosophie, die im ursprünglichen Buch vertreten wurde, immer
noch solide ist, wenn sie auf etwas anderes übertragen wird. 
Das gesammelte Wissen und die Herausforderung, die
Allen Carr und ich auf uns genommen haben, besteht darin, wie wir dieses
Wissen jedem einzelnen Nutzer vermitteln können. Die Tatsache, dass ich
weiß, dass es jedem Nutzer nicht nur leicht fällt, aufzuhören, sondern
dass er den Prozess sogar genießen kann, ist nicht nur sinnlos, sondern
auch äußerst frustrierend, wenn ich es nicht schaffe, es dem Nutzer zu
vermitteln. Allen Carr erklärt in seinem Originalbuch seinen
kontroversen Ratschlag:

*\"Viele Leute haben zu mir gesagt: \"Du sagst: \"Rauch weiter, bis du
das Buch zu Ende gelesen hast\". Das sorgt dafür, dass der Raucher ewig
braucht das Buch zuende zu lesen oder es einfach nie beendet. Basta.
Deshalb solltest du die Anweisung ändern.' Das klingt logisch, aber ich
weiß, wenn die Anweisung lauten würde: 'Hör sofort auf', würden einige
Raucher nicht einmal anfangen, das Buch zu lesen. In den ersten Tagen
kam ein Raucher zu mir. Er sagte: \"Ich ärgere mich wirklich, dass ich
Ihre Hilfe in Anspruch nehmen muss, denn ich weiß, dass ich einen
starken Willen habe. In jedem anderen Bereich meines Lebens habe ich
alles unter Kontrolle. Warum schaffen es all die anderen Raucher mit
ihrer eigenen Willenskraft und ich muss zu Ihnen kommen?\" Er fuhr fort:
\"Ich glaube, ich könnte es auch allein schaffen, wenn ich dabei rauchen
könnte.\"*

Die gesellschaftliche Meinung besagt, dass es unglaublich schwierig ist,
mit dem Rauchen aufzuhören. Was brauchts also ein Raucher wenn etwas
schwer ist? Seinen kleinen Freund, seine Krücke. Mit dem Rauchen
aufzuhören scheint ein Schlag zu sein: Nicht nur, dass es eine
schwierige Aufgabe zu bewältigen gibt - was schwer genug ist - auch
die Krücke, auf die er sich normalerweise bei solchen Gelegenheiten
verlässt, ist nicht verfügbar. Das vielleicht schönste an dieser Methode
ist, dass du nichts aufgeben musst, während du den Prozess durchläufst.
Du wirst zunächst alle Ängste und Zweifel los, so dass du am Ende der
letzten Sitzung bereits die Freiheit genießt.

Deshalb wird dieses Hackbook die gleichen Ratschläge beibehalten. Egal,
wie oft gesagt wird, dass es einfach ist und Spaß macht, es wird eine
große Mehrheit geben, die das nicht akzeptieren kann, weil sie sich
selbst eine Gehirnwäsche verpasst hat, wie schwer es ist, aufzuhören.

Das Timing ist das einzige Kapitel, das mich dazu veranlasst, Allens
ursprünglichen Rat ernsthaft in Frage zu stellen. Vor allem, wenn zu den
Auslösern der Stress im Büro gehört, solltest du dir einen Feiertag
aussuchen, an dem du es versuchst, und umgekehrt. Das ist nicht der
einfachste Weg - suche dir stattdessen die Zeit aus, die du für am
*schwierigsten* hältst. Ob das nun Stress, soziale Verpflichtungen,
Konzentration oder Langeweile ist: Wenn du erst einmal bewiesen hast,
dass du auch in den schlimmsten Situationen zurechtkommst und das Leben
genießt, ist jede andere angenehm. Aber wenn das der Ratschlag wäre,
würdest du es dann überhaupt versuchen?

Hier ist eine Analogie: Meine Schwester und ich wollen zusammen
schwimmen gehen. Wir kommen zur gleichen Zeit am Schwimmbad an, aber wir
schwimmen selten zusammen. Der Grund dafür ist, dass sie einen Zeh
eintaucht und eine halbe Stunde später tatsächlich schwimmt. Das ist
eine langsame Tortur, denn ich weiß schon vorher, dass ich mich
irgendwann ins Wasser wagen muss, egal wie kalt das Wasser ist. Also
habe ich gelernt, es auf die einfache Art zu tun: Direkt ins Wasser zu
springen. Angenommen, ich könnte darauf bestehen, dass sie gar nicht
schwimmen darf, wenn sie nicht reinspringt. Verstehst du das Problem?

Aus den Rückmeldungen geht hervor, dass viele Nutzer den ursprünglichen
Ratschlag zum Timing verwendet haben, um den vermeintlich \"bösen Tag\"
hinauszuzögern. Mein nächster Gedanke war, die Technik auf die Vorteile
von Pornos anzuwenden, so etwas wie - *\"Timing ist sehr wichtig und im
nächsten Kapitel wirst du über den besten Zeitpunkt für den Versuch
beraten.\"* und auf der nächsten Seite gibt es nur ein massives
*\"JETZT!\"* Das ist in der Tat der beste Ratschlag, aber würdest du ihn
befolgen? Dies ist der vielleicht subtilste Aspekt der Falle: Wenn wir echten
Stress in unserem Leben haben, ist es nicht an der Zeit, aufzuhören,
aber in Zeiten ohne Stress haben wir keine Lust, aufzuhören. Stell dir
die folgenden Fragen:

1.  Als du zum ersten Mal auf Pornografie gestoßen bist, hast du da wirklich
    beschlossen, dass du für den Rest deines Lebens davon abhängig sein
    würdest, ohne jemals aufhören zu können? **Natürlich hast du das
    nicht!**

2.  Wirst du für den Rest deines Lebens weitermachen, ohne jemals
    aufhören zu können? **Natürlich nicht!**

Wann wirst du aufhören? Morgen? Nächstes Jahr? Das Jahr danach? Hast du
dich das nicht auch schon gefragt, als du gemerkt hast, dass du süchtig
bist? Hoffst du, dass du eines Morgens aufwachst und einfach nicht mehr
schauen willst? Mach dir nichts vor: Bei jeder Sucht wird man immer
mehr süchtig, nicht weniger. Willst du warten, bis du merkst, dass es
schwieriger ist, aus dem Bett zu kommen, als nur zu masturbieren? Das
wäre ein bisschen sinnlos.

Die eigentliche Falle ist der Glaube, dass jetzt nicht der richtige
Zeitpunkt ist - morgen wird es immer einfacher sein. Wir glauben, dass
wir ein stressiges Leben führen, aber in Wirklichkeit tun wir das nicht.
Wir haben den meisten echten Stress aus unserem Leben verbannt. Wenn du
dein Haus verlässt, hast du keine Angst, von wilden Tieren angegriffen
zu werden. Die meisten fragen sich nicht, woher wir unsere nächste
Mahlzeit bekommen oder ob wir heute Nacht ein Dach über dem Kopf haben
werden. Stell dir das Leben eines wilden Tieres vor: Jedes Mal, wenn ein
Kaninchen aus seinem Bau kommt, ist es sein ganzes Leben lang mit
Vietnam konfrontiert. Aber das Kaninchen kommt damit klar, es hat
Adrenalin und andere Hormone und wir auch. Die Wahrheit ist, dass die
stressigsten Phasen im Leben eines jeden Lebewesens die frühe Kindheit
und die Jugend sind. Aber drei Milliarden Jahre natürliche Auslese haben
uns dazu gebracht, mit Stress umzugehen, und viele, die eine schwere
Kindheit hatten, führen ein normales Leben.

Es ist ein Klischee zu sagen: *\"Wenn du nicht gesund bist, hast du
nichts\"*, aber es ist absolut wahr. Wenn du dich körperlich und geistig
stark fühlst, kannst du die Hochs genießen und die Tiefs bewältigen.
Verantwortung wird mit Stress verwechselt, und Verantwortung wird nur
dann stressig, wenn wir uns nicht stark genug fühlen, um sie zu
bewältigen. Was die meisten zerstört, sind nicht Stress, Arbeit oder das
Alter, sondern die illusorischen Krücken, auf die sie sich stützen.

Sieh es mal so: Du hast bereits beschlossen, dass du nicht für den Rest
deines Lebens in der Falle sitzen bleibst. Deshalb musst du irgendwann
durch den Prozess der Befreiung gehen, egal ob es dir leicht oder schwer
fällt. Pornografie ist keine Gewohnheit oder ein Vergnügen, es ist eine Sucht
und eine Krankheit. Wir haben festgestellt, dass es morgen nicht
einfacher wird, sondern dass es immer schlimmer wird. Der Zeitpunkt, um
davon loszukommen, ist **jetzt** - oder so nah dran an jetzt, wie du es
schaffen kannst. Denk nur daran, wie schnell jede Woche unseres Lebens
vergeht. Stell dir vor, wie schön es sein wird, den Rest deines Lebens
zu genießen, ohne dass immer größere Schatten über dir hängen. Wenn du
alle Anweisungen befolgst, musst du nicht einmal fünf Tage oder drei
Wochen warten. Es wird dir nicht nur leicht fallen, aufzuhören, sondern
**du wirst es auch genießen!**
