# Verpasse ich den Spaß?

Nein! Wenn das kleine Pornomonster erst einmal tot ist, dein Körper
nicht mehr nach Dopamin verlangt und die Porno-Wasserrutschen in deinem
Gehirn aufgrund der fehlenden \"Schmierung\" zu verblassen beginnen,
wird jede verbleibende Gehirnwäsche verschwinden. Du wirst
feststellen, dass du sowohl körperlich als auch geistig besser gerüstet
bist, um mit dem Stress und den Belastungen des Lebens umzugehen und die
guten Zeiten in vollen Zügen zu genießen.

Es gibt nur eine Gefahr, nämlich den Einfluss derjenigen, die Sex immer
noch als Krücke und Vergnügen benutzen. Der Spruch *\"Das Gras des
anderen ist immer grüner\"* ist in vielen Bereichen unseres Lebens
alltäglich und leicht verständlich. Warum neigt der Ex-Konsument im Fall
von Pornografie, wo die Nachteile im Vergleich zu den illusorischen
\"Vorteilen\" so enorm sind, dazu, diejenigen zu beneiden, die Sex und
Pornografie als Krücke brauchen?

Bei all der Gehirnwäsche in der Kindheit ist es nur allzu verständlich,
dass wir in die Falle getappt sind. Wie kommt es dann, dass wir, nachdem
wir erkannt haben, was für ein dummes Spiel das ist und wir es
geschafft haben, von der Sucht loszukommen, direkt wieder in dieselbe
Falle tappen? Das liegt an der Gehirnwäsche der Gesellschaft, die Pornografie
mit Sex gleichsetzt und als normal darstellt. Der Ex-Konsument hat einen
Schmerz! Das unsichere Gefühl der Leere, dass sie Single sind (was ja
kein Verbrechen ist) verursacht Angstgefühle und treibt sie dazu, die
Wasserrutsche zu nehmen. Das ist in der Tat eine merkwürdige Anomalie,
vor allem, wenn man diese Beobachtung in Betracht zieht: Nicht nur,
dass jeder Nicht-Konsument auf der Welt glücklich darüber ist, so zu
sein, sondern jeder Konsument auf der Welt wünscht sich auch mit seinem
verzerrten, süchtigen, gehirngewaschenen Verstand, der unter dem Wahn
leidet, es zu genießen oder sich zu entspannen, dass er gar nicht erst
süchtig geworden wäre. Warum also sind manche Ex-Konsumenten neidisch?

1.  "Nur ein kurzer Blick". Denke daran, dass es das nicht gibt. Hör auf,
    es als Einzelfall zu sehen und fang an, ihn aus der Sicht des
    Pornografienutzers zu betrachten. Du magst sie vielleicht beneiden, aber
    sie finden sich selbst nicht gut und beneiden dich. Wenn du nur
    irgendwie klinisch einen anderen Nutzer beobachten könntest, könte das der
    Ansporn von allen sein, um dir da rauszuhelfen.
    Fällt dir auf, wie schnell sie viele Tabs und Browserfenster öffnen?
    Sie spulen zu wichtigen Abschnitten vor, langweilen sich schnell bei
    einigen Clips und durchlaufen die ganze Bandbreite an Genres, die
    Neuheit, Schock, Angst usw. erzeugen. Achte vor allem darauf, dass
    die Handlung automatisch zu sein scheint. Vergiss nicht, dass es
    ihnen keinen Spaß macht, sondern dass sie sich ohne es nicht
    amüsieren können. Wenn sie am nächsten Morgen mit einem geschwächten
    Willen, verlorener Energie und trüben Augen aufwachen, müssen sie sich
    beim ersten Anzeichen von Stress und Anspannung wieder selbstgeißeln.
    Ihnen drohen ein Leben voller Schmutz, eine schlechte geistige
    Gesundheit, ein angeschlagenes Selbstvertrauen, ein Leben der
    Selbstzerstörung und schwarzen Schatten im Hinterkopf. Um was zu
    erreichen? Die Illusion, dass du bekommst, was du \"verdienst\" und
    verdammtes Vergnügen?

2.  Der zweite Grund, warum manche Ex-Nutzer Entzugserscheinungen haben,
    ist, dass der Pornografie-Nutzer etwas tut, z. B. Selbstbefriedigung, und
    der Nicht-Nutzer nicht, so dass er sich benachteiligt fühlt. Mach
    dir bewusst, dass es nicht der Nichtnutzer ist, dem etwas vorenthalten
    wird, sondern der arme Süchtige, dem etwas vorenthalten wird:

    -   Gesundheit

    -   Energie

    -   Geld

    -   Selbstvertrauen

    -   Seelenfrieden

    -   Mut

    -   Gelassenheit

    -   Freiheit

    -   Selbstrespekt

    Hör auf, Pornografienutzer zu beneiden und fang an, sie als die
    erbärmlichen, armseligen Kreaturen zu sehen, die sie wirklich sind.
    Ich weiß es, denn ich war selbst einmal einer der Schlimmsten.
    Deshalb liest du dieses Buch und nicht diejenigen, die sich das
    nicht eingestehen können und sich weiterhin etwas vormachen.

Du würdest einen Heroinabhängigen nicht beneiden, und wie jede
Drogensucht wird auch deine nicht besser werden. Jedes Jahr wird es
exponentiell schlimmer. Wenn du es heute nicht genießt, ein Konsument zu
sein, wirst du es morgen noch weniger genießen. Sei nicht neidisch auf
andere Drogenkonsumenten, sondern bemitleide sie. Glaube mir: **Sie
brauchen dein Mitleid!**
