# Kann ich es aufteilen?

Das ist ein weiterer Mythos über Pornografie, der vor allem von Nutzern
verbreitet wird, die beim Versuch, mit der Willenskraftmethode
aufzuhören, mentale Gymnastik betreiben und eine Jekyll und Hyde-Routine
beginnen: *\"Pornografie ist für meine Alter-Ego-Seite und echte Romantik
ist für meine Beziehungsseite.\"* Nichts ist weiter von der Wahrheit
entfernt. Die Porno-Wasserrutschen, das DeltaFosB und die neurologischen
Veränderungen werden die Romantik im echten Leben überrollen und sie
weniger begehrenswert machen. Mr. Hyde wird definitiv die Anweisungen
von Dr. Jekyll umstoßen.

Wenn du Internetpornografie nutzt, trainierst du dich für die Rolle des
Voyeurs, oder für die Möglichkeit, beim geringsten Abfall deines
Dopaminspiegels auf etwas Erregenderes zu klicken. Oder die ständige
Suche nach genau der richtigen Szene, um den maximalen Effekt zu
erzielen. Es kann auch sein, dass du in gebückter Haltung masturbierst
oder nachts im Bett auf dein Smartphone schaust und dich nach diesen
Reizen mehr sehnst als nach dem echten Leben. Sex widerspricht fast
jedem Aspekt des Online-Harems und hat im Vergleich dazu keine Chance.
Die Erinnerungen, die in der Jugend geschaffen werden, sind mächtig und
langlebig, deshalb dauert es länger, diese pornografischen
Wasserrutschen abzubauen und neue zu schaffen. Das heißt aber nicht, dass
es genrell schwieriger ist.

Jedes Mal, wenn du auf der \"Porno-Wasserrutsche\" fährst, fettest du
sie ein und hältst die Nerven frisch und bereit zum Abschuss. Wenn du
neben einem Fast-Food-Restaurant parkst, steigt dir der Geruch der
Fritteuse in die Nase und der Kauf ist bereits abgeschlossen. Genauso
sind die Porno-Wasserrutschen in deinem Gehirn bereit, dich in den Bann
zu ziehen und vierundzwanzig Stunden am Tag geöffnet. Jeder
Hinweis oder Auslöser lässt deinen Belohnungskreislauf mit dem
Versprechen auf Sex aufleuchten, nur dass es eben kein Sex ist. Trotzdem
verfestigen die Nervenzellen diese Assoziationen mit sexueller Erregung,
indem sie neue Verzweigungen sprießen lassen, um die Verbindungen zu
stärken. Je mehr Pornografie du konsumierst, desto stärker werden die
Nervenverbindungen, was dazu führt, dass du am Ende ein Voyeur sein
*musst*, dass du auf neues, stets eskaliernedes Material klicken musst, 
dass du Pornos brauchst, um einzuschlafen, oder dass du nach dem perfekten
Ende suchen musst, um den Job zu erledigen.

Wie bei jeder Substanz oder Verhaltensdroge baut der Körper eine
Immunität auf und die Droge hört auf, die Entzugserscheinungen
vollständig zu lindern. Sobald der Pornografiekonsument eine Sitzung beendet
hat, will er eine weitere und zwar schnell, denn der ständige Hunger
bleibt ungestillt. Die natürliche Neigung ist Eskalation,
um den Dopaminrausch zu bekommen. Die meisten Nutzer werden jedoch aus
einem oder beiden der folgenden Gründe davon abgehalten, dies zu tun.

Geld.

:   Sie können es sich nicht leisten, kostenpflichtige Pornoseiten zu
    abonnieren.

Gesundheit

:   Der Körper kann nur eine bestimmte Menge verkraften, entweder die
    Dopaminschübe oder die Orgasmen. Außerdem werden beim Orgasmus
    Chemikalien freigesetzt, um den Dopaminrausch zu dämpfen. Das muss
    er auch, so funktioniert der Körper nun mal.

Sobald das kleine Monster deinen Körper verlässt, hört das schreckliche
Gefühl der Unsicherheit auf. Dein Selbstvertrauen kehrt zurück, zusammen
mit einem wunderbaren Gefühl der Selbstachtung. Du erhältst die
Gewissheit, dein Leben in die Hand nehmen zu können und das als Sprungbrett zu
nutzen, um andere Probleme anzugehen. Das ist einer der vielen großen
Vorteile, wenn du dich von einer Sucht befreist.

Der Mythos der Aufteilung ist auf einen der vielen Tricks
zurückzuführen, die das kleine Monster mit deinem Verstand spielt. Diese
Tricks erschweren das Aufhören, weil der ständige Hunger nicht
befriedigt werden kann, so dass viele Konsumenten zu Zigaretten, starkem
Alkoholkonsum oder noch härteren Drogen greifen, um die Leere zu
füllen.

Wir Menschen sind Bewertungstiere, sowohl uns selbst als auch anderen
gegenüber. Wenn du dir mit deinem Partner Pornografie ansiehst, ist das
unbefriedigend, denn beide bewerten die Leistung des anderen anhand der
Erzählung. Willst du Brad Pitt in deinem Schlafzimmer haben, auch wenn
er nur auf einem Poster zu sehen ist? Keine Person kann es mit einem Harem
aufnehmen, in dem jede \"Erfahrung\" von Profis gespielt, geschrieben
und inszeniert wird und vierundzwanzig Stunden am Tag sofort verfügbar
ist.
