# Vermeide falsche Anreize

Viele Nutzer, die versuchen, mit der Willenskraftmethode aufzuhören,
versuchen, ihre Motivation durch falsche Anreize zu steigern. Dafür gibt
es viele Beispiele. Ein typisches Beispiel ist, sich mit Geschenken zu
belohnen, wenn man einen Monat lang keine Pornografie geschaut hat. Das
scheint ein logischer und vernünftiger Ansatz zu sein, ist aber in
Wirklichkeit falsch, denn jeder, der etwas auf sich hält, würde lieber
jeden Tag weiter Pornos schauen, als sich mit einem selbst gemachten
Geschenk zu belohnen. Das weckt Zweifel in den Nutzern, denn sie müssen
nicht nur dreißig Tage lang abstinent bleiben, sondern sind sich auch
nicht sicher, ob sie die Tage ohne Pornografie überhaupt genießen können. Ihr
einziges Vergnügen oder Stütze ist weggenommen! Dadurch
wird das Opfer, das der Nutzer zu bringen glaubt, nur noch größer und in
seinen Augen noch wertvoller.

Andere Beispiele sind:

-   Ich höre auf, damit es mich dazu zwingt, ein soziales Leben und mehr
    echten Sex zu haben.

-   Ich höre auf, damit eine magische Energie mir hilft, über die
    Konkurrenz hinauszuwachsen und den Partner zu bekommen, den ich
    suche.

-   Ich höre auf, damit ich mich verpflichten kann, meine Energie und
    meinen Enthusiasmus nicht mit Pornografie zu verschwenden, die den Hunger
    in mir selbst steigert.

Diese sind wahr, können effektiv sein und du könntest am Ende bekommen, was
du willst, aber denk mal kurz darüber nach. Wenn du das bekommst, was du
wolltest, ist auch dieses Neue bald normal; Wenn du es
nicht bekommen hast, fühlst du dich miserabel. So oder so tappst du früher
oder später wieder in dieselbe Falle.

Das Aufhören mit einem falschen Anreiz zu verknüpfen, führt nur zu
Zweifeln, denn wenn du deine Belohnung nicht bekommst (und selbst wenn du
sie bekommst), wirst du anfangen, zweifelnde Gedanken zu denken, wie
zum Beispiel: *\"Wird das Aufhören mein Leben wirklich besser machen?
Wenn ich aufhöre und nicht bekomme, was ich will, habe ich dann die
Methode richtig angewendet?\"* Solche Gedanken verstärken das Gefühl der
Aufopferung und erzeugen daher Entzugserscheinungen.

Ein weiteres typisches Beispiel sind Online- oder Forenpakte. Diese
haben den Vorteil, dass sie die Versuchung für eine bestimmte Zeit
ausschalten. Allerdings scheitern sie in der Regel aus den folgenden
Gründen:

1.  Der Anreiz ist falsch. Warum solltest du aufhören wollen, nur weil
    andere Leute das auch tun? Damit wird nur zusätzlicher Druck
    erzeugt, der das Gefühl des Opfers verstärkt. Es ist in Ordnung,
    wenn alle Nutzer zu einem bestimmten Zeitpunkt wirklich aufhören
    wollen - aber du kannst sie nicht dazu zwingen, auch wenn sie es
    insgeheim wollen. Bis sie dazu bereit sind, erzeugt ein Pakt
    zusätzlichen Druck, der ihre Lust am Schauen erhöht. Das macht sie
    zu heimlichen Nutzern, was das Gefühl der Abhängigkeit noch
    verstärkt.

2.  Die gegenseitige Abhängigkeit durch die Willenskraftmethode erzeugt
    das Gefühl, eine Zeit der Buße zu durchleben, in der sie darauf
    warten, dass der Drang verschwindet. Wenn sie nachgeben, entsteht
    ein Gefühl des Versagens. Bei der Willenskraftmethode wird einer der
    Teilnehmer aufgeben, was den anderen Teilnehmern die Ausrede
    liefert, auf die sie gewartet haben. Es ist nicht ihre Schuld, sie
    hätten durchgehalten, aber \"Fred\" hat sie im Stich gelassen. Die
    Wahrheit ist, dass die meisten von ihnen bereits geschummelt haben.

3.  Anerkennung zu teilen ist das Gegenteil von Abhängigkeit. 
    Es ist ein wunderbares Erfolgserlebnis, 
    mit der Pornografie aufzuhören. Wenn du es alleine schaffst, kann die
    Anerkennung, die du von deinen Freunden und Online-Freunden
    bekommst, in den ersten Tagen ein enormer Ansporn sein. Wenn es
    jedoch alle gleichzeitig tun, muss die Anerkennung geteilt werden
    und der Ansporn wird folglich geringer.

4.  Ein weiteres klassisches Beispiel ist das Guru-Versprechen. Wenn du
    aufhörst, wirst du glücklich sein, weil du nicht mehr in das
    Tauziehen verwickelt bist, dein Gehirn beginnt sich neu zu
    verdrahten und die Impulskontrolle wiederzuerlangen. Du musst jedoch
    bedenken, dass du dadurch weder ein Sexgott wirst noch im Lotto
    gewinnst. Niemanden außer dir interessiert es im Geringsten, ob du
    mit Pornos aufhörst. Du bist weder ein schwacher Mensch, wenn du
    dreimal am Tag Pornografie konsumierst und PIED hast, noch ein starker
    Mensch, wenn du süchtig bist und es nicht bist.

Hör auf, dir etwas vorzumachen. Wenn das Jobangebot von zehn Monaten
Arbeit für zwölf Monate Gehalt im Jahr oder die Risiken, dass dein
Gehirn nicht mehr in der Lage ist, den täglichen Stress und die
Belastungen zu bewältigen, oder dass du keine zuverlässige Erektion mehr
bekommst, oder die lebenslange geistige und körperliche Folter und
Sklaverei dich nicht davon abgehalten haben, werden die oben genannten
falschen Anreize nicht den geringsten Unterschied machen, sondern nur
dazu führen, dass das Opfer noch schlimmer erscheint. Konzentriere dich
stattdessen auf die andere Seite:

\"Was habe ich davon? Warum muss ich Pornos schauen?\"

Schau dir immer wieder die andere Seite des Tauziehens an und frage
dich, was Pornos für dich tun. *ABSOLUT NICHTS.* Warum muss ich es tun?
*DU BRAUCHST ES NICHT! DU BESTRAFST DICH NUR SELBST.* Es ist Pascals
Wette: Du hast fast nichts zu verlieren (schwindende Erregung), Chancen
auf große Gewinne (volle und zuverlässige Erregung, geistiges
Wohlbefinden und Glück) und keine Chance, groß zu verlieren.

Warum erklärst du also nicht deinen Ausstieg vor Freunden und Familie?
Das macht dich zu einem stolzen Ex-Süchtigen oder Ex-Nutzer und nicht zu
einem begeisterten und glücklichen Nicht-Nutzer. Deinem Partner könnte das
ein bisschen Angst machen, denn er könnte das als eine Art
New-Age-Masche sehen, um mehr Sex zu haben. Er könnte auch befürchten,
dass du dich in eine Sexmaschine verwandelst, aber das ist schwer zu
erklären, wenn er nicht aufgeschlossen ist.

Jeder Versuch, andere dazu zu bringen, dir beim Aufhören zu helfen, gibt
dem kleinen Monster noch mehr Macht. Es aus deinem Kopf zu verdrängen
und völlig zu ignorieren hat den Effekt, dass du versuchst, *nicht*
daran zu denken. Sei stattdessen achtsam: Sobald du die Gedanken,
Hinweise (allein zu Hause) oder abwesende Gedanken bemerkst, sag dir
einfach: *\"Toll, ich bin kein Sklave des Pornos mehr. Ich bin frei und
freue mich über die Vielfalt beim Sex!\"* Damit schneidest du dem
Gedanken den Sauerstoff ab und hältst ihn davon ab, sich in Richtung
Triebe und Verlangen zu verbrennen. In dieser Hinsicht kann die
Achtsamkeitsmeditation hilfreich sein, um die Gedanken zu
entpersonalisieren.
