# Der einfache Weg aufzuhören

Dieses Kapitel enthält eine Anleitung, wie du ganz einfach mit Pornografie
aufhören kannst. Wenn du die Anweisungen befolgst, wirst du feststellen,
dass das Aufhören von relativ einfach bis hin zu angenehm ist! Wenn du
die folgenden Anweisungen befolgst, ist es lächerlich einfach, mit
Pornografie aufzuhören, du musst nur zwei Dinge tun.

1.  Triff die Entscheidung, dass du nie wieder Pornografie schauen wirst.

2.  Blase nicht Trübsal. Freue dich.

Du fragst dich wahrscheinlich: *\"Wozu dann der Rest des Buches?
Warum konntest du das nicht von Anfang an sagen?\"* Die Antwort ist,
dass du irgendwann darüber gejammert hättest und daraufhin früher oder
später deine Entscheidung geändert hättest. Das hast du wahrscheinlich
schon viele Male getan.

Wie schon gesagt, ist Pornografie eine subtile, hinterhältige Falle. Das
Hauptproblem beim Aufhören ist nicht die Dopaminsucht, die sicherlich
ein Problem ist, aber nicht das Hauptproblem, sondern die Gehirnwäsche.
Deshalb ist es notwendig, zuerst alle Mythen und Wahnvorstellungen zu
zerstören. Wenn du deinen Feind verstehst und seine Taktiken kennst,
wirst du ihn leicht besiegen. Nachdem ich große Teile meines Lebens mit
schlimmen Depressionen verbracht habe, um aufzuhören, bin ich, als ich
endlich davon loskam, ohne einen schlechten Moment direkt auf Null
gegangen. Sogar die Entzugsphase hat mir Spaß gemacht, und seitdem habe
ich nicht den geringsten Verdruss gehabt. Im Gegenteil, es war das
Schönste, was mir in meinem Leben passiert ist.

Mein letzter Versuch war anders. Wie alle anderen Konsumenten hatte ich
ernsthaft über das Problem nachgedacht. Bis dahin hatte ich mich nach
jedem Fehlschlag mit dem Gedanken getröstet, dass es beim nächsten Mal
einfacher sein würde. Es war mir nie in den Sinn gekommen, dass ich für
den Rest meines Lebens so weitermachen müsste. Dieser Gedanke erfüllte
mich mit Schrecken und ich begann, sehr intensiv über das Thema
nachzudenken.

Anstatt unbewusst den Browser zu starten, analysierte ich meine Gefühle
und bestätigte, was ich bereits wusste. Ich hatte keinen Spaß an Pornografie
und fand sie schmutzig und ekelhaft. Ich fing an, mir Nicht-Nutzer
anzuschauen, die in anderen Teilen der Welt lebten oder ältere Menschen,
die die Tube-Seiten nie kennengelernt hatten. Bis dahin hatte ich
Nicht-Nutzer immer als wischiwaschi, ungesellig und pingelig betrachtet.
Doch als ich sie untersuchte, wirkten sie, wenn überhaupt, stärker und
entspannter. Sie schienen in der Lage zu sein, mit dem Stress und den
Belastungen des Lebens fertig zu werden und schienen gesellschaftliche
Veranstaltungen mehr zu genießen als die Pornonutzer. Sie hatten auf
jeden Fall mehr Ausstrahlung und Lebensfreude als diese.

Ich fing an, mit Ex-Usern zu sprechen. Bis dahin hatte ich immer
gedacht, dass sie aus gesundheitlichen oder religiösen Gründen aufhören
mussten und sich insgeheim immer nach einem Haremsbesuch sehnten. Ein
paar sagten: *Du bekommst gelegentliche Sehnsüchte, aber die sind so
selten, dass es sich nicht lohnt, sich darum zu kümmern.* Die meisten
sagten: *\"Vermissen? Du machst wohl Witze! Das Leben hat sich nie
besser angefühlt!\"* Selbst wenn sie scheiterten, verurteilten sie sich
nicht, sondern akzeptierten es bedingungslos. Wie ein Trainer, der
einen Fehler eines wirklich goldenen Spielers akzeptiert. Das Gespräch
mit ehemaligen Nutzern zerstörte einen weiteren Mythos, den ich immer im
Kopf hatte: Ich dachte, ich hätte eine angeborene Schwäche, bis mir klar
wurde, dass alle diesen privaten Albtraum durchmachen.

Im Grunde sagte ich mir: *\"Viele Leute hören jetzt auf und führen ein
glückliches Leben. Ich musste es nicht tun, bevor ich anfing, und ich
kann mich daran erinnern, dass ich hart arbeiten musste, um mich an
diesen Dreck zu gewöhnen. Warum muss ich es also jetzt tun?\"* Auf jeden
Fall machte mir Pornografie keinen Spaß, ich hasste das ganze schmutzige
Ritual und wollte nicht den Rest meines Lebens als Sklave dieser
ekelhaften Sucht verbringen. Dann sagte ich mir Folgendes:

\"Ob es dir gefällt oder nicht, du hast deine letzte Sitzung hinter
dir.\"

Von diesem Moment an wusste ich, dass ich es nie wieder tun würde. Ich
hatte nicht erwartet, dass es einfach sein würde, im Gegenteil. Ich
glaubte fest daran, dass ich mich auf monatelange schlimme Depressionen
und den Rest meines Lebens auf gelegentliche Sehnsüchte einstellen müsste.
Stattdessen war es von Anfang an ein absolutes Glücksgefühl.

Ich habe lange gebraucht, um herauszufinden, warum es so einfach war und
warum ich nicht unter diesen schrecklichen Entzugserscheinungen gelitten
habe. Der Grund dafür ist, dass es sie nicht gibt. Es sind die Zweifel
und die Ungewissheit, die die Qualen verursachen. Die schöne Wahrheit
ist, dass es *leicht ist, mit Pornografie aufzuhören.* Nur die
Unentschlossenheit und das Trübsalblasen machen es schwierig. Selbst
wenn man süchtig ist, kann man zu bestimmten Zeiten relativ lange
Zeiträume ohne sie auskommen. Nur wenn man es will, aber nicht kann,
leidet man darunter.

Deshalb liegt der Schlüssel zum Erfolg darin, den Ausstieg sicher und
endgültig zu machen. Nicht zu hoffen, sondern zu wissen, dass du es
geschafft hast, weil du die Entscheidung getroffen hast. Zweifle nie
daran und stelle es nicht in Frage, ganz im Gegenteil - freue dich
immer! Wenn du dir von Anfang an sicher sein kannst, wird es leicht
sein. Aber wie kannst du dir von Anfang an sicher sein? Deshalb ist der
Rest des Buches notwendig. Es gibt einige wichtige Punkte, über die du
dir im Klaren sein musst, bevor du anfängst:

1.  Realisiere, dass du es schaffen kannst. An dir ist nichts anders
    und die einzige Person, die dich zum Zuschauen bringen kann, bist du
    selbst. Nicht dieser Star, der in seinen kühnsten Träumen nie daran
    gedacht hätte, dass er zur Reduzierung der Potenz benutzt wird.

2.  Es gibt absolut nichts, was du aufgeben musst. Im Gegenteil, es gibt
    enorme positive Gewinne zu erzielen. Nicht, dass du gesünder und
    reicher wärst, aber du wirst die guten Zeiten mehr genießen und in
    den schlechten weniger unglücklich sein.

3.  So etwas wie einen Blick oder Besuch gibt es nicht. Pornografie ist
    eine Drogensucht und eine Kettenreaktion. Wenn du über einen
    gewünschten gelegentlichen Besuch jammerst, bestrafst du dich nur
    unnötig.

4.  Sieh Pornografie nicht als eine 'Männer bleiben Männer'-Angewohnheit, die
    dich verletzen kann, sondern als eine Drogensucht. Sieh der Tatsache
    ins Auge, ob du es willst oder nicht, dass **du die Krankheit
    hast**. Sie wird nicht verschwinden, weil du den Kopf in den Sand
    steckst. Denk daran, dass sie wie alle lähmenden Krankheiten nicht
    nur ein Leben lang anhält, sondern sich exponentiell verschlimmert.
    Die einfachste Zeit, sie zu heilen, ist jetzt.

5.  Trenne die Krankheit, die neurologische Sucht, von der Einstellung,
    ein Nutzer zu sein oder nicht. Alle Abhängigen würden die Gelegenheit
    nutzen, in die Zeit zurückzukehren, bevor sie süchtig wurden. Diese
    Möglichkeit hast du heute! Denke nicht einmal daran, dass du es
    'aufgibst'.

Wenn du die endgültige Entscheidung triffst, dass du deinen letzten
Besuch hattest, bist du bereits ein Nicht-Nutzer. Ein Nutzer ist einer
dieser armen Schlucker, die sich mit Pornos das Leben versauen. Ein
Nicht-Nutzer ist jemand, der das nicht tut. Wenn du diese endgültige
Entscheidung getroffen hast, hast du dein Ziel bereits erreicht. Freu
dich darüber, blas kein Trübsal und warte nicht darauf, dass die
chemische Sucht verschwindet. Geh raus und genieße das Leben sofort. Das
Leben ist wunderbar, auch wenn du süchtig bist, und jeder Tag wird so
viel besser, wenn du es nicht bist.

Der Schlüssel dazu, dass dir der Ausstieg leicht fällt, ist die
Gewissheit, dass es dir gelingen wird, während der Entzugszeit (maximal
drei Wochen) vollständig abstinent zu bleiben. Wenn du die richtige
Geisteshaltung hast, wird dir das lächerlich leicht fallen.

Wenn du, wie zu Beginn gefordert, deinen Geist dafür geöffnet hast, wirst du bereits
beschlossen haben, dass du dem entfliehen willst. Du solltest dich jetzt
aufgeregt fühlen wie ein Hund, der an der Leine zerrt und es kaum
erwarten kann, die Wasserrutschen der DeltaFosB-Pornografie zu durchbrechen.
Wenn du ein Gefühl der Niedergeschlagenheit hast, dann aus einem der
folgenden Gründe:

1.  Irgendetwas ist in deinem Kopf nicht richtig angekommen. Lies die
    oben genannten fünf Punkte noch einmal und frage dich, ob du sie für
    wahr hältst. Wenn du an einem Punkt zweifelst, lies die
    entsprechenden Abschnitte des Buches noch einmal.

2.  Du hast Angst vor dem Scheitern selbst. Mach dir keine Sorgen, lies
    einfach weiter und du wirst Erfolg haben. Das ganze Geschäft mit
    Internetpornografie ist ein Vertrauenstrick von gigantischem Ausmaß.
    Intelligente Menschen fallen auf Vertrauenstricks herein, aber nur
    ein Narr, der den Trick einmal durchschaut hat, macht sich weiter
    etwas vor.

3.  Du stimmst mit allem überein und bist trotzdem unglücklich. Das muss
    nicht sein! Mach die Augen auf - etwas Wunderbares geschieht. Du bist
    dabei, aus dem Gefängnis zu fliehen, da ist es wichtig, dass du mit
    der richtigen Einstellung beginnst: *\"Es ist wunderbar, dass ich
    ein Nichtnutzer bin!\"*

Alles, was jetzt noch zu tun ist, ist, dich während der Entzugszeit in
dieser Denkweise zu halten, und in den nächsten Kapiteln geht es um
konkrete Punkte, die dir das ermöglichen. Nach der Entziehungskur musst
du nicht mehr so denken, du wirst es automatisch tun und das einzige
Rätsel in deinem Leben wird sein, warum du es vorher nicht erkannt hast. Doch
zwei wichtige Warnungen.

-   Verschiebe deinen Plan, deinen letzten Besuch zu machen, auf nachdem
    du das Buch beendet hast.

-   Eine Entzugszeit von bis zu drei Wochen wurde schon oft erwähnt, was
    zu Missverständnissen führen kann. Erstens hast du vielleicht
    unbewusst das Gefühl, dass du drei Wochen lang leiden musst. Das
    musst du aber nicht. Zweitens solltest du nicht in die Falle tappen
    und denken: *\"Irgendwie muss ich drei Wochen lang abstinent
    bleiben, dann wird es mir schon gut gehen.\"* Nach drei Wochen wird
    nichts Magisches passieren, du wirst dich nicht plötzlich wie ein
    Nicht-Konsument fühlen, die fühlen sich auch nicht anders als die
    Konsumenten. Wenn du in den drei Wochen Trübsal bläst, weil du
    aufhören willst, wirst du höchstwahrscheinlich auch nach den drei
    Wochen noch Trübsal blasen. Zusammenfassend lässt sich sagen: Wenn
    du jetzt sagen kannst, *\"Ich werde nie wieder Pornografie schauen, ist
    das nicht wunderbar?\"*, wird nach drei Wochen jede Versuchung
    verschwinden. Wenn du hingegen sagst: *\"Wenn ich nur diese drei
    Wochen ohne Pornografie überleben kann.\"*, wirst du dich nach Ablauf der
    drei Wochen nach einem Haremsbesuch sehnen.

Betrachte es mal so: Dein Gehirn will den Status quo beibehalten. Wenn
du also glaubst, dass du etwas Gutes verlierst, wenn du aufhörst, wirst
du dich natürlich schrecklich fühlen. Es ist unmöglich, dich zu zwingen,
dich auf eine bestimmte Art und Weise zu fühlen, wenn dein Gehirn nicht
daran glaubt. Deshalb ist es wichtig, dass du dir die Mühe machst, dich
von der Illusion zu befreien, dass Pornografie dir überhaupt irgendetwas gibt.
Nur so weißt du, dass du nichts opferst.

Sexuelle Funktionsstörungen haben viel mit deinem Gehirn und deiner
Denkweise zu tun. Internetpornografie schaltet den Belohnungskreislauf deines
Gehirns um und lässt dich an dir selbst zweifeln. Diese Selbstzweifel
führen zu sexueller Dysfunktion. Wenn du oben Lust hast, aber
unten keine Erregung verspürst, ist das das Schlimmste, was deinem
Verstand passieren kann. Libido geht Hand in Hand mit Romantik und ist
das Elixier der Jugend, das du bis zu deinem Tod haben kannst. Du hältst
die Wahrscheinlichkeit hoch, indem du aufhörst, aber das ist nicht der
einzige oder größte Gewinn. Es ist deine Freiheit von der Sklaverei.
