# Die Entzugsperiode

Bis zu drei Wochen nach deiner letzten Sitzung kannst du unter
Entzugserscheinungen leiden, die aus zwei ganz unterschiedlichen
Faktoren bestehen.

1.  Dopamin-Entzugserscheinungen, dieses leere, unsichere Gefühl, das
    dem Hunger ähnelt, das als Heißhunger oder ein \"Ich muss etwas
    tun\"-Gefühl bezeichnet wird.

2.  Psychologische Auslöser bestimmter äußerer Reize wie Werbung,
    Online-Surfen, Telefongespräche usw.

Wenn du diese beiden Faktoren nicht verstehst und nicht unterscheidest,
ist es schwierig, mit der Willenskraftmethode Erfolg zu haben, und das
ist der Grund, warum viele, die es schaffen, wieder in die Falle tappen.
Obwohl die Dopamin-Entzugserscheinungen keine körperlichen Schmerzen
verursachen, solltest du ihre Kraft nicht unterschätzen. Wir sprechen
von \"Hungerschmerzen\", wenn wir einen Tag lang nichts gegessen haben;
vielleicht knurrt der Magen, aber es gibt keine körperlichen Schmerzen.
Trotzdem ist der Hunger eine starke Kraft und wir werden wahrscheinlich
sehr gereizt, wenn wir keine Nahrung haben. Es ist ähnlich, wie wenn
sich unser Körper nach einem Dopaminrausch sehnt, nur mit dem
Unterschied, dass unser Körper Nahrung braucht und kein Gift. Mit der
richtigen Einstellung sind die Entzugserscheinungen leicht zu überwinden
und verschwinden sehr schnell.

Nach ein paar Tagen Abstinenz mit der Willenskraft-Methode verschwindet
das Verlangen nach Dopaminschüben schnell wieder. Es ist der zweite
Faktor, die Gehirnwäsche, der Schwierigkeiten bereitet. Der Nutzer hat
sich angewöhnt, seine Entzugserscheinungen zu bestimmten Zeiten und
Anlässen zu lindern, was zu einer Assoziation von Gedanken führt (*\"Ich
habe einen Ständer, also muss ich Pornos schauen.\"* oder *\"Ich liege
mit meinem Laptop im Bett und muss eine Sitzung haben, um mich glücklich
zu fühlen\"*). Der Effekt lässt sich am besten mit einem Beispiel
veranschaulichen: Du hast ein Auto und der Blinker ist links, bei deinem
nächsten ist er rechts. Du weißt, dass er rechts ist, aber ein paar
Wochen lang schaltest du die Scheibenwischer ein, wenn du blinken
willst.

Beim Anhalten ist es ähnlich: In den ersten Tagen wird der
Auslösemechanismus zu bestimmten Zeiten aktiviert. Deshalb ist es
wichtig, der Gehirnwäsche von Anfang an entgegenzuwirken, damit diese
Anzeichen und Auslöser schnell verschwinden. Bei der Willenskraftmethode
bläst der Nutzer Trübsal, weil er glaubt, dass er ein Opfer bringt, und
wartet darauf, dass der Drang nachlässt - weit davon entfernt, diese
Auslöser zu beseitigen und sie sogar zu verstärken. Ähnlich verhält es
sich mit dem Guru-Denken: Der Nutzer fragt sich, wann er zum Gott wird,
und verlangt sogar, dass er diese Gedanken nicht haben darf, was den Weg
für Selbsthass und Versagen ebnet.

Ein häufiger Auslöser ist das Alleinsein, besonders bei
gesellschaftlichen Veranstaltungen mit Freunden. Der Ex-Konsument, der
andere Methoden anwendet, ist bereits unglücklich, weil er seiner
üblichen Stütze oder seines Vergnügens beraubt ist. Ihre Freunde sind
mit ihren Partnern zusammen und verhalten sich intim. Der Nutzer ist
entweder Single oder 'bekommt' aus irgendeinem Grund nichts von seinem
Partner und genießt nun nicht mehr, was eigentlich ein angenehmer
gesellschaftlicher Anlass sein sollte. Die vorhandenen Wasserrutschen im
Gehirn führen sie zu Pornos, was einfacher ist, als ihren Partner zu
umwerben.

Da sie den Anspruch auf Sex mit ihrem Wohlbefinden verbinden, erleiden
sie nun einen dreifachen Schlag und die Gehirnwäsche wird sogar noch
verstärkt. Wenn sie entschlossen sind und lange genug durchhalten
können, akzeptieren sie schließlich ihr Schicksal und machen mit ihrem
Leben weiter. Ein Teil der Gehirnwäsche bleibt jedoch bestehen. Der
zweitschlimmste Aspekt ist, dass der Nutzer zwar aufgehört hat, sich
aber auch nach mehreren Jahren noch bei bestimmten Gelegenheiten nach
\"einem letzten Besuch im Harem\" sehnt. Sie sehnen sich nach einer
Illusion, die nur in ihrem Kopf existiert und quälen sich unnötig.

Selbst unter EasyPeasy ist das Reagieren auf Auslöser das häufigste
Versagen. Der Ex-Nutzer neigt dazu, Internetpornos als eine Art Placebo
oder Zuckerpille zu betrachten. Er denkt: *\"Ich weiß, dass Pornos
nichts für mich tun, aber wenn ich denke, dass sie es tun, dann werden
sie bei bestimmten Gelegenheiten hilfreich sein.\"* Auch wenn eine
Zuckerpille keine tatsächliche körperliche Hilfe bietet, kann sie eine
starke psychologische Hilfe sein, um echte Symptome zu lindern, und ist
daher ein Vorteil. Internetpornos und gewohnheitsmäßige
Selbstbefriedigung sind jedoch keine Zuckerpillen. Warum? Pornos
erzeugen die Symptome, die sie lindern, und hören auf, sie vollständig
zu lindern.

Es ist vielleicht einfacher, die Wirkung bei einem Nichtkonsumenten oder
einem Konsumenten zu verstehen, der mehrere Jahre lang erfolgreich
aufgehört hat. Nimm den Fall eines Nutzers, der seinen Partner verliert.
In solchen Momenten ist es durchaus üblich, mit den besten Absichten zu
sagen: *\"Geh doch mal in den Harem, das wird dich beruhigen.\"* Wenn du
das Angebot annimmst, wird es keine beruhigende Wirkung haben, denn es
gibt keine Dopaminabhängigkeit und damit auch keine
Entzugserscheinungen. Im besten Fall wird es ihnen nur einen kurzen
psychologischen Schub geben.

Auch nach der Sitzung ist die ursprüngliche Tragödie noch da. Sie wird
sogar noch verstärkt, weil die Person jetzt unter Entzugserscheinungen
leidet und die Wahl hat, ob sie es aushält oder die Wasserrutschen
wiederholt, um die Kette des Elends von vorne zu beginnen. Alles, was
die Pornos gebracht haben, war ein flüchtiger psychologischer Schub, den
auch ein Buch oder ein guter Film hätte bringen können, selbst ein
schlechter. Viele Nichtnutzer und Ex-Nutzer sind durch solche Erlebnisse
wieder süchtig geworden. Mach dir das ganz klar vor Augen: Du brauchst
den Dopaminrausch nicht und quälst dich nur noch mehr, wenn du ihn
weiterhin als eine Art Stütze oder Ansporn betrachtest. Es gibt keinen
Grund, unglücklich zu sein.

Orgasmen machen keine guten Beziehungen aus; meistens ruinieren sie sie
sogar. Denke auch daran, dass es nicht ganz stimmt, dass diejenigen, die
ihre Zuneigung öffentlich zeigen, jede Gelegenheit genießen. Intimität
genießt man am besten im Privaten, wo die Partner ohne Peinlichkeit
reagieren können. Du musst kein orgasmusbedingter Dopamin-Süchtiger
sein. Wenn er das natürliche Ergebnis einer Reihe von Lebensereignissen
ist, ist das in Ordnung, aber genieße die Gelegenheit und das Leben ohne
ihn.

Da sie Pornos an sich nicht als angenehm empfinden, denken viele Nutzer:
*\"Wenn es doch nur 'saubere' Internetpornos gäbe.\"* Es gibt saubere
Softpornos, aber wer sie ausprobiert, stellt schnell fest, dass sie
Zeitverschwendung sind. Mach dir klar, dass der einzige Grund, warum du
Pornos konsumierst, der Dopaminrausch ist. Sobald du das
Dopaminverlangen nach Pornos los bist, hast du kein Bedürfnis mehr,
deinen Online-Harem zu besuchen.

Egal, ob die Entzugserscheinungen auf tatsächliche
Dopamin-Entzugserscheinungen oder auf Trigger- und Auslösemechanismen
zurückzuführen sind, akzeptiere sie. Der körperliche Schmerz ist nicht
vorhanden und mit der richtigen Einstellung wird es auch kein Problem
sein. Mach dir keine Sorgen über den Entzug, das Gefühl selbst ist nicht
schlimm. Das Problem ist die Assoziation mit dem Verlangen und dem
Gefühl der Verweigerung. Anstatt Trübsal zu blasen, erkenne es an:
*\"Ich weiß, was das ist, das ist der Entzugsschmerz von Pornos.
Darunter leiden Nutzer ihr ganzes Leben lang und bleiben süchtig.
Nicht-Nutzer leiden nicht unter diesen Schmerzen, das ist ein weiteres
der vielen Übel dieser verlogenen Sucht. Es ist wunderbar, dass ich
dieses Übel aus meinem Gehirn vertreibe!\"*

Mit anderen Worten: In den nächsten drei Wochen wirst du ein leichtes
Trauma in deinem Körper haben, aber während dieser Wochen und für den
Rest deines Lebens wird etwas Wunderbares passieren. Du wirst dich von
einer schrecklichen Krankheit befreien, wobei der Bonus das leichte
Trauma mehr als aufwiegt und du die Entzugserscheinungen sogar genießen
kannst. Sie werden zu Momenten des Vergnügens, wie ein aufregendes
Spiel, um den pornografischen Bandwurm, der in deinem Magen lebt,
auszuhungern. Du musst ihn drei Wochen lang aushungern, während er
versucht, dich ins Bett zu locken, um ihn am Leben zu erhalten.

Manchmal wird er versuchen, dich unglücklich zu machen. Manchmal wirst
du unvorbereitet erwischt. Du bekommst eine Porno-URL oder stolperst im
Internet über etwas und vergisst, dass du aufgehört hast, ein leichtes
Gefühl der Entbehrung, wenn du dich daran erinnerst. Bereite dich auf
diese Tricks im Voraus vor. Egal, wie groß die Versuchung auch sein mag,
mach dir klar, dass sie nur wegen des Monsters in deinem Körper da ist
und dass du jedes Mal, wenn du der Versuchung widerstehst, einen
weiteren moralischen Schlag im Kampf ausgeteilt hast.

Was auch immer du tust, versuche nicht, die Pornos zu vergessen. Das ist
einer der Gründe, warum PMOler, die die Willenskraftmethode anwenden,
stundenlang in Depressionen versinken. Sie versuchen, jeden Tag zu
überstehen, in der Hoffnung, dass sie es irgendwann einfach vergessen
werden. Es ist wie mit dem Nicht-Schlafen-Können: Je mehr du dir
Gedanken darüber machst, desto schwieriger wird es. In den ersten Tagen
wird dich das \"kleine Monster\" immer wieder daran erinnern und du
wirst nicht in der Lage sein, es zu vermeiden. Solange es noch Laptops,
Smartphones und Zeitschriften gibt, wirst du ständig daran erinnert.

Der Punkt ist, dass du es nicht vergessen musst, denn es passiert nichts
Schlimmes. Es passiert etwas Wunderbares, auch wenn du tausendmal am Tag
daran denkst. **Genieße jeden Moment und erinnere dich daran, wie
wunderbar es ist, wieder frei zu sein. Erinnere dich an die pure Freude
darüber, dass du dich nicht mehr quälen musst.** Wie schon gesagt, wirst
du feststellen, dass die Qualen zu Momenten der Freude werden und du
wirst überrascht sein, wie schnell du die Pornos dann vergisst.

Was auch immer du tust: *Zweifle nicht an deiner Entscheidung*. Sobald
du anfängst zu zweifeln, wirst du anfangen, Trübsal zu blasen, und es
wird noch schlimmer. Nutze stattdessen den Moment des Trübsal blasens
und wandle ihn in einen Ansporn um. Wenn die Ursache eine Depression
ist, dann erinnere dich daran, dass es das ist, was der Porno mit dir
gemacht hat. Wenn du von einem Freund eine URL weitergeleitet bekommst,
sagst du voller Stolz: *\"Ich bin froh, dass ich das nicht mehr
brauche.* Das wird sie verletzen, aber wenn sie sehen, dass es dich
nicht stört, sind sie schon halbwegs bereit, sich dir anzuschließen.

Erinnere dich daran, dass du unglaublich gute Gründe hast, damit
aufzuhören. Erinnere dich an die Kosten und frage dich, ob du wirklich
riskieren willst, dass dein Körper und dein Geist versagen und du unter
einem Bann stehst. Sei achtsam gegenüber den Bemühungen des kleinen
Monsters, die Gefahren zu minimieren, und vor allem: Denke daran, dass
das Gefühl nur vorübergehend ist und jeder Moment ein Moment näher an
deinem Ziel ist.

Manche Nutzer befürchten, dass sie den Rest ihres Lebens damit
verbringen müssen, die \"automatischen Auslöser\" rückgängig zu machen.
Mit anderen Worten, sie glauben, dass sie sich ihr Leben lang mit Hilfe
von Psychologie vormachen müssen, dass sie keine Pornos brauchen. Das
stimmt nicht, denn der Optimist sieht die Flasche als halb voll und der
Pessimist als halb leer. Im Fall der Pornografie ist die Flasche leer
und der Nutzer sieht sie als voll an. Es gibt keine Vorteile,
Internetpornos zu nutzen. Es ist der Nutzer, der durch eine Gehirnwäsche
davon überzeugt wurde. Wenn du dir erst einmal sagst, dass du keinen
Orgasmus brauchst, wenn du Pornos benutzt, brauchst du es bald gar nicht
mehr zu sagen, weil du die schöne Wahrheit selbst siehst. Es ist das
Letzte, was du tun musst; sorge dafür, dass es nicht das Letzte ist, was
du tust.
