# Nur einmal kurz reingucken

Das ist das Verhängnis vieler, die die Willenskraftmethode anwenden. Sie
halten drei oder vier Tage durch und gönnen sich dann den einen oder
anderen Blick, um sich über Wasser zu halten. Sie sind sich nicht
bewusst, welch verheerende Auswirkungen das auf ihre Moral hat.

Für die meisten Nutzer war der erste Blick in den Harem der Webseite
nicht so gut wie der Sex mit einer echten Person. Die Clips, die sauber
sind, sind rar gesät, und ihr Bewusstsein bekommt Aufwind.
Sie denken: *\"Gut, das war alles in allem nicht ganz so toll. Ich werden
das Verlangen los und stehe auch nicht so auf das schockierende Zeug.\"* 
In Wirklichkeit ist das Gegenteil der Fall. Sei dir bewusst dass die Freude
am Orgasmus nicht der Grund war, warum du mit Pornografie aufgehört hast. Wenn es dir nur um den Orgasmus ginge, würdest du sich nie mehr als einen
Clip ansehen. Der einzige Grund, warum du Pornografie brauchtest, war das
Füttern dieses kleinen Monsters. Stell dir vor, wie wertvoll dieser eine
Blick für dich gewesen sein muss, nachdem du vier Tage lang ausgehungert
warst. Dein Bewusstsein ist sich dessen nicht bewusst, aber den Fix, den
dein Körper erhalten hat, wird an dein Unterbewusstsein weitergegeben
und all deine gute Vorbereitung wird untergraben. Eine kleine Stimme in
deinem Hinterkopf sagt dir, dass die Sitzungen entgegen aller Logik wertvoll 
sind und du noch eine haben willst.

Dieser kleine Blick hat zwei schädliche Auswirkungen:

1.  Es hält das kleine Monster in deinem Körper am Leben.

2.  Schlimmer noch, es hält das große Monster in deinem Kopf am Leben.
    Wenn du einen 'Letzten Blick' hattest, ist es einfacher, den nächsten
    zu haben.

Pornografie ist eine Mausefalle ohne Käse, nur mit Gift. Mit Willenskraft
musst du dich davon überzeugen, nicht nach dem Käse zu greifen, aber mit
EasyPeasy kannst du sehen, dass es Gift ist. Du musst sie nicht meiden,
du gehst einfach nicht hinein.

Und denke vor allem daran:

'Nur ein Blick' ist der Grund, warum Menschen überhaupt erst in die
Sucht geraten.
