# Wird es für mich schwerer sein?

Es gint eine unendliche Kombination an Faktoren die bestimmen, wie leicht jeder 
einzelne Nutzer aufhören wird. Zunächst einmal hat jeder von uns
seinen eigenen Charakter, seine Karriere, seine persönlichen Umstände,
sein Timing, seinen Metabolismus usw. Bestimmte Berufe können es schwerer
machen als andere, aber vorausgesetzt dass die Gehirnwäsche entfernt ist, muss das nicht 
so sein. Betrachte die folgenden paar Beispiele.

Für Angehörige der medizinischen Berufe ist es manchmal schwierig. Wir
denken, dass es für Ärztinnen und Ärzte einfacher sein sollte, weil sie
sich der Auswirkungen bewusster sind, aber obwohl das zwar gewichtigere Gründe 
für das Aufhören liefert, macht es es nicht einfacher. Die Gründe sind die folgenden:

1.  Das ständige Bewusstsein der gesundheitlichen Risiken erzeugt
    Angst, eine der Bedingungen, unter denen wir Entzugserscheinungen
    lindern müssen.

2.  Die Arbeit eines Arztes ist äußerst stressig und sie sind
    normalerweise nicht in der Lage, den zusätzlichen Stress der
    Entzugserscheinungen während der Arbeit zu lindern.

3.  Sie leiden zusätzlich unter Schuldgefühlen und haben das Gefühl,
    dass sie ein Vorbild für den Rest der Bevölkerung sein sollten. Das
    setzt sie noch mehr unter Druck und verstärkt das Gefühl der
    Entbehrung.

Wenn nach einem harten Arbeitstag der Stress kurzzeitig durch einen
Pornoclip abgebaut wird, wird diese Sitzung fälschlicherweise mit der
erlebten Erleichterung in Verbindung gebracht. Aufgrund dieser falschen
Assoziation erntet die Pornografie dafür die Lorbeeren und wird plötzlich
sehr wertvoll, wenn man aufhört und Entzugserscheinungen durchmacht. Das ist
eine Form des Gelegenheitskonsumenten und trifft auf jede Situation zu, in der der
Konsument gezwungen ist, über längere Zeit abstinent zu bleiben. Bei der
Willenskraftmethode fühlt sich der Nutzer unglücklich, weil er denkt ihm
fehlt etwas, und die angenehme Müdigkeit und der Schlaf, die nach einer Sitzung
auftraten, treten nicht mehr auf. Das Gefühl des Verlustes wird stark
vergrößert. Wenn du jedoch zuerst die Gehirnwäsche und das Trübsalblasen
in Bezug auf Pornografie beseitigen kannst, können die Pause und der Schlaf
auch dann noch genossen werden, wenn der Körper sich nach den
Amintransmittern - Serotonin, Noradrenalin und Dopamin - sehnt.

Eine weitere schwierige Situation ist Langeweile, vor allem wenn sie mit
Stressphasen verbunden ist. Typische Beispiele sind Studenten und
Alleinerziehende, deren Arbeit stressig und eintönig ist. Während des
Versuchs, mit der Willenskraftmethode aufzuhören, kann der
Alleinstehende lange Zeit über seinen \"Verlust\" Trübsal blasen, was
das Gefühl der Depression verstärkt. Aber auch das lässt sich leicht
überwinden, wenn du die richtige Einstellung hast. Mach dir keine
Sorgen, dass du ständig daran erinnert wirst, dass du mit der Pornografie
aufgehört hast. Nutze solche Momente, um dich über den Fakt zu freuen, dass du
dich von dem bösen Monster befreit hast.

Wenn du eine positive Einstellung hast, werden diese Schmerzen zu
Momenten der Freude. Denke daran, dass es jedem Nutzer unabhängig von
Alter, Geschlecht, Intelligenz oder Beruf leicht fallen kann,
aufzuhören, wenn **er alle Anweisungen befolgt.**


## Hauptgründe fürs Scheitern

Es gibt zwei Hauptgründe für das Scheitern. Der erste ist der Einfluss
von äußeren Reizen - ein Werbespot, ein Online-Nachrichtenartikel, das
Surfen im Internet, usw. In einem schwachen Moment oder auch bei
gesellschaftlichen Anlässen wird jemand mit seinem Partner intim. Dieses
Thema haben wir bereits ausführlich besprochen. Nutze den Moment, um
dich daran zu erinnern, dass es so etwas wie \"Nur-einen-Besuch\" oder
\"Nur-einen-Blick\" **nicht** gibt. Freue dich darüber, dass du die
Kette der geistigen Sklaverei durchbrochen hast. Denke daran, dass der
Nutzer DICH beneidet und du Mitleid mit IHM haben solltest - denn er hat
es nötig.

Der andere Grund ist, dass du einen schlechten Tag hast. Mach dir bewusst,
dass es gute und schlechte Tage gibt, egal ob du ein Nutzer bist
oder nicht. Es regnet sowohl für den Papst als auch für den Mörder. Das
Leben ist relativ und du kannst keine Höhen ohne Tiefen haben. Das
Problem bei der Willenskraftmethode ist, dass der Nuzer, sobald er einen
schlechten Tag hat, Trübsal bläst und den \"Harem\" aufsuchen will, was
das Problem noch verschlimmert. Der Nicht-Nutzer ist besser gerüstet, um
mit Stress und Belastungen umzugehen, nicht nur körperlich, sondern auch
mental. Wenn du während der Entzugsphase einen schlechten Tag hast,
nimm ihn einfach hin und erinnere dich daran, dass es auch schlechte
Tage gab, als du süchtig warst, sonst hättest du dich nicht entschieden,
aufzuhören. Anstatt Trübsal zu blasen, solltest du sie anerkennen:
*\"Okay, heute ist es nicht so gut, aber Pornografie wird das nicht heilen.
Morgen wird es besser sein und ich habe einen tollen Bonus: Ich habe
diese schreckliche Sucht besiegt.\"*

Wenn du ein Pornografienutzer bist, musst du deinen Verstand vor den
negativen Seiten der Pornografie verschließen. Pornografienutzer haben nie
Hirnnebel, sie sind nur \"ein bisschen down\". Wenn du die
unvermeidlichen Probleme des Lebens durchlebst und einen Gedanken der
dich nach Pornografie sehnen lässt - bist du da glücklich und fröhlich? 
Natürlich bist du das nicht. Wenn du einma laufgehört hast, neigst du dazu, alles,
was schief läuft, auf die Tatsache zu schieben, dass du aufgehört hast.

Wenn dich die Arbeit stresst, denkst du: *\"In solchen Zeiten hätte ich
eine Sitzung gehabt.\"* Das stimmt, aber dabei vergisst du, dass die Pornografie
das Problem nicht gelöst hat und du dich nur selbst bestrafst,
indem du Trübsal bläst und nach illusorischen Krücken suchst. Du
schaffst eine unmögliche Situation: Du bist unglücklich, weil du nicht
zu Pornos masturbieren kannst, aber du wirst noch unglücklicher, wenn du
es tust. Du weißt, dass du mit dem Aufhören die richtige Entscheidung
getroffen hast, also warum bestrafst du dich, indem du an deiner
Entscheidung zweifelst?

Denke daran, dass eine positive mentale Einstellung wichtig ist - immer.
