# Ersatz

Zum Ersatz gehören z.B. die Beschränkung auf Pornomagazine, statische
Bilder, Porno-Diäten usw. **VERWENDE NICHTS DAVON.** Sie
machen es schwieriger, nicht einfacher. Wenn du einen Impuls bekommst
und Ersatz verwendest, verlängert das den Impuls und macht es
noch schwieriger. Was du dir damit sagst, ist, dass du Pornografie
brauchst, um die Leere zu füllen. Das ist so, als würdest du dem
Wutanfall eines Entführers oder eines Kindes nachgeben und so die Folter
verlängern. Auf jeden Fall wird der Ersatz die Sehnsucht nicht
lindern. Dein Verlangen ist nach bestimmten Neurotransmittern im Gehirn, die dich nur dazu
bringen, weiter an Pornografie zu denken. Erinnere dich an folgendes:

1.  Es gibt keinen Ersatz für Pornos.

2.  Du brauchst keine Pornografie. Es ist kein Essen, es ist Gift. Wenn
    die Entzugserscheinungen kommen, erinnere dich daran, dass es die
    Konsumenten sind, die unter Entzugserscheinungen leiden, nicht die
    Nichtkonsumenten. Sieh sie als das, was sie sind: ein weiteres Übel
    der Droge. Sieh sie als den Tod eines Monsters.

3.  Internetpornografie schafft die Leere, sie füllt sie nicht. Je schneller du
    deinem Gehirn beibringst, dass du sie nicht sehen musst, desto
    schneller wirst du frei sein. Vermeide vor allem alles, was Pornografie
    ähnelt, z. B. Männermagazine, Filme, Romane und Werbespots.
    Das heißt nicht, dass du verschlossen bist. Es ist okay, über
    Romantik und Sex zu reden, aber nicht über Pornografie. Es gibt immer
    einen Weg, um herauszufinden, wann und wo man unterscheiden kann.
    Es stimmt, dass ein kleiner Teil der Nutzer, die versuchen, mit
    Softcore-Pornografie oder Porno-Diäten aufzuhören, (aus ihrer Sicht)
    erfolgreich sind und ihren Erfolg auf diese Art von Konsum
    zurückführen. Aber sie hören *trotz* ihres Konsums auf und nicht
    deswegen. Es ist bedauerlich, dass viele diese Maßnahmen immer noch
    empfehlen.

Das ist nicht überraschend, denn wenn du die Pornofalle nicht ganz
verstehst, klingt eine Diät oder ein weniger starker Ersatz sehr logisch. Sie
basiert auf der Annahme, dass du zwei mächtige Feinde zu besiegen hast,
wenn du versuchst, mit Pornografie aufzuhören:

-   Die Gewohnheit brechen.

-   Die schrecklichen körperlichen Entzugserscheinungen überleben.

Wenn du zwei mächtige Feinde zu besiegen hast, ist es sinnvoll, sie
nicht gleichzeitig zu bekämpfen, sondern einen nach dem anderen. Die
Theorie besagt also, dass du, wenn du zum ersten Mal mit dem 
Pornografiekonsum aufhörst, ihn auf einmal pro Woche reduzierst oder
sichere Pornos benutzt. Sobald die Gewohnheit gebrochen ist, reduzierst
du schrittweise die Lieferungen und bekämpfst so jeden Feind einzeln.

Das klingt logisch, basiert aber auf falschen Informationen. Pornografiekonsum ist
keine Gewohnheit, sondern eine Dopaminsucht, und der tatsächliche
körperliche Schmerz beim Entzug ist fast nicht spürbar. Was du erreichen
willst, wenn du aufhörst, ist, beide Monster in deinem Körper und deinem
Gehirn so schnell wie möglich auszuschalten. Alles, was die
Ersatztechniken bewirken, ist, das Leben des kleinen Monsters zu
verlängern und damit auch die Gehirnwäsche zu verlängern. EasyPeasy macht es
dir leicht, sofort auszusteigen und die Gehirnwäsche vor deiner letzten
Sitzung abzuschalten. Das kleine Monster wird bald tot sein und selbst
während es stirbt, wird es kein größeres Problem darstellen als zu
deiner Zeit als Nutzer.

Überleg mal, wie kannst du die Sucht nach einer Droge heilen, indem du
dieselbe Droge empfiehlst? Es gibt viele Geschichten im Internet, die
mit Hardcore-Internetpornografie aufgehört haben, aber nach \"sicheren\"
Alternativen süchtig sind, weil sie auf die Rechtfertigungen ihres
kleinen Monsters hereingefallen sind. Lass dich nicht davon täuschen,
dass die sicheren Pornos nicht furchtbar sind - das war der erste
Highspeed-Clip auch nicht. Jeder Ersatz hat genau die gleiche Wirkung
wie jeder Porno. Manche fangen sogar an zu essen, aber obwohl das leere
Gefühl, eine Sitzung zu wollen, nicht vom Hunger nach Essen zu
unterscheiden ist, wird das eine das andere nicht befriedigen. Wenn es
etwas gibt, das dich dazu bringt, Pornografie zu wollen, dann ist es, dich
mit Essen vollzustopfen. Wie bereits erklärt, bringen dich Porno-Diäten
und sichere Pornografie nur in die Mitte des Tauziehens, wobei der Widerstand
gegen die Versuchung so lästig ist, dass du dich erleichtert fühlen
wirst, wenn du deinen Lieblings-Online-Harem besuchst.

Das Hauptübel des Ersatzes ist die Verlängerung des eigentlichen
Problems, der Gehirnwäsche. Brauchst du einen Ersatz für die Grippe,
wenn sie vorbei ist? Natürlich brauchst du das nicht. Wenn du sagst,
dass du einen Ersatz für Pornografie brauchst, heißt das in Wirklichkeit,
dass du denkst, dass du ein Opfer bringst. Die Depression, die mit der
Willenskraft-Methode einhergeht, wird durch die Tatsache verursacht,
dass der Nutzer glaubt, ein Opfer zu bringen. Dabei tauschst du nur ein
Problem gegen ein anderes aus. Es macht keinen Spaß, sich mit Essen,
Zigaretten oder Alkohol vollzustopfen. Du wirst nur fett und
unglücklich, und im Handumdrehen bist du wieder auf der Droge.

Gelegenheitskonsumenten können sich nur schwer von dem Glauben
verabschieden, dass sie ihrer kleinen Belohnung beraubt werden, z. B.
wenn sie während einer Reise oder eines Familienfestes eine Zeit lang
nicht online gehen dürfen. Manche sagen: *\"Ich wüsste nicht, wie ich
mich entspannen könnte, wenn es keine Pornos gäbe.\"* Das beweist es - die
Pause wird oft nicht deshalb eingelegt, weil der Nutzer sie braucht
oder sogar will, sondern weil der Süchtige (und das ist er) unbedingt
das Bedürfnis hat, das Jucken zu kratzen.

Denk daran, dass die Pornografiesitzungen nie eine echte Belohnung waren. Sie
waren so, als würde man enge Schuhe tragen, um das Vergnügen zu haben,
sie auszuziehen. Wenn du also das Gefühl hast, dass du eine kleine
Belohnung brauchst, dann lass genau das dein Ersatz sein: Zieh während der
Arbeit ein Paar Schuhe oder Unterwäsche an, die eine Nummer zu klein
sind, und erlaube dir nicht, sie auszuziehen, bis du deine Pause hast,
um dann den wunderbaren Moment der Entspannung und Befriedigung zu
erleben, wenn sie ausgezogen sind. Vielleicht denkst du, dass das
ziemlich dumm wäre. Da hast du völlig Recht. Es ist schwer, sich das
vorzustellen, während man noch in der Falle sitzt, aber genau das tun
die Nutzer. Es ist auch schwer, sich vorzustellen, dass du diese kleine
\"Belohnung\" bald nicht mehr brauchst und die Freunde, die noch in der
Falle sitzen, mit echtem Mitleid betrachtest und dich fragst, warum sie
es nicht verstehen.

Wenn du dir jedoch weiterhin vormachst, dass der Besuch im Online-Harem
eine echte Belohnung war oder dass du einen Ersatz brauchst, wirst du
dich unglücklich fühlen und so, als würdest du etwas aufgeben. Die Chancen
stehen gut, dass du am Ende wieder in die ekelhafte Falle tappst. Wenn du
eine echte Pause brauchst, wie es Hausfrauen, Lehrerinnen und Lehrer,
Ärztinnen und Ärzte und andere Berufstätige tun, wirst du diese Pause
bald noch mehr genießen, weil du dich nicht abhängig machen musst. Denke
daran, dass du keinen Ersatz brauchst. Die Heißhungerattacken sind ein
Verlangen nach Dopamin und werden bald verschwunden sein. Lass das für
die nächsten Tage deine Stütze sein und genieße es, deinen Körper und
deinen Geist von Sklaverei und Abhängigkeit zu befreien.
