# Sollte ich Situationen der Versuchung vermeiden?

Die Ratschläge waren bisher direkt und haben dich gebeten, sie als Anweisungen
und nicht als Vorschläge zu betrachten. Es gibt gute, praktische Gründe
für diese Ratschläge, und diese Gründe wurden durch Tausende von
Fallstudien untermauert. Bei der Frage, ob man versuchen soll, der
Versuchung zu entgehen, ist das nicht der Fall. Das muss jeder für sich
selbst entscheiden. Es gibt jedoch zwei hilfreiche Vorschläge, die dir
bei diesem Prozess helfen können. Es ist die Angst vor zukünftigen
Entzugserscheinungen, die uns für den Rest unseres Lebens dazu bringt,
Pornos zu benutzen, und diese Angst besteht aus zwei unterschiedlichen
Phasen.

**Phase Eins - *\"Wie kann ich ohne Pornos überleben?\"***

Diese Angst ist das panische Gefühl, das der Nutzer bekommt, wenn er
Single ist oder einen asexuellen, uninteressierten oder nicht
verfügbaren Partner hat. Die Angst wird nicht durch die
Entzugserscheinungen verursacht, sondern ist eine psychologische Angst
vor Abhängigkeit, ohne Sex und Orgasmus nicht überleben zu können. Sie
erreicht ihren Höhepunkt, wenn du kurz davor bist aufzuhören, wenn deine
Entzugserscheinungen am geringsten sind. Es ist die Angst vor dem
Unbekannten, die Art von Angst, die Menschen haben, wenn sie tauchen
lernen.

Das Sprungbrett ist nur einen Meter hoch, aber es scheint, als wäre es
sechs Fuß hoch. Das Wasser ist drei Meter tief, aber es scheint nur
einen Meter tief zu sein. Es erfordert Mut, zu springen, obwohl du davon
überzeugt bist, dass du dir den Kopf zerschmettern wirst. Der Start ist
der schwierigste Teil, wenn du den Mut dazu findest, ist der Rest
leicht! Das erklärt, warum viele willensstarke Nutzer nie versucht haben
aufzuhören oder nur ein paar Tage überleben, wenn sie es doch tun. Es
gibt sogar einige Nutzer, die eine Porno-Diät machen und nach der
Entscheidung, aufzuhören, schneller ins \"Binge\"-Schauen und härtere
Clips verfallen, als wenn sie sich nicht entschieden hätten, aufzuhören.
Diese Entscheidung löst Panik aus, die stressig ist und den Auslöser für
einen Ausflug in den Harem darstellt. Aber jetzt kannst du keinen haben,
was zu Gedanken der Entbehrung und noch mehr Stress führt.

Der Auslöser wird schnell aktiv, wenn die Lunte durchbrennt und du den
Browser startest. Keine Sorge, die Panik ist nur psychologisch bedingt.
Es ist die Angst, von der du abhängig bist. Die schöne Wahrheit ist,
dass du das nicht bist, auch wenn du noch süchtig bist. Gerate nicht in
Panik und springe ab.

**Phase zwei - Langfristige Furcht**

Die zweite Phase ist langfristig und beinhaltet die Angst, dass
bestimmte Situationen in der Zukunft nicht mehr angenehm sein werden
oder dass du ein Trauma ohne Pornos nicht mehr bewältigen kannst. Keine
Sorge, wenn du springst, wirst du feststellen, dass das Gegenteil der
Fall ist. Das Vermeiden der Versuchung selbst lässt sich in zwei
Kategorien einteilen.

1.  *Ich werde mir eine Porno-Diät von einmal in vier Tagen auferlegen.
    Ich werde mich sicherer fühlen, wenn ich weiß, dass ich online gehen
    kann, wenn es schwierig wird. Wenn ich versage, ist das in Ordnung,
    dann füge ich einfach weitere Tage zu meinem nächsten Zyklus hinzu.*

    Die Misserfolgsquote bei Menschen, die das tun, ist viel höher als
    bei denen, die ganz aufhören. Das liegt vor allem daran, dass es in
    der Entzugszeit, wenn du einen schlechten Moment hast, leicht ist,
    in den Browser zu hüpfen und den Harem mit den oben genannten
    Ausreden zu besuchen. Wenn du die Demütigung hast, deine eigenen
    Regeln eindeutig zu brechen wie eine zerbrochene Glasscheibe, ist es
    wahrscheinlicher, dass du die Versuchung überwinden kannst. In jedem
    Fall wäre der Schmerz wahrscheinlich schon vergangen, wenn du es
    aufgeschoben hättest. Der Hauptgrund für die hohe Misserfolgsquote
    in diesen Fällen ist jedoch, dass sich der Nutzer nicht von
    vornherein dazu verpflichtet fühlte, aufzuhören. Denke daran, dass
    die beiden wichtigsten Voraussetzungen für den Erfolg sind:

    -   Gewissheit.

    -   *\"Ist es nicht herrlich, dass ich keine Pornos mehr brauche?\"*

    In jedem Fall, warum in aller Welt brauchst du eine Sitzung? Wenn du
    immer noch deinen Harem besuchen musst, lies das Buch noch einmal.
    Das bedeutet, dass irgendetwas noch nicht richtig geklickt hat. Nimm
    dir die Zeit, das große Gehirnwäsche-Monster in deinem Kopf komplett
    auszumerzen.

2.  *\"Sollte ich stressige oder gesellschaftliche Anlässe während der
    Entzugszeit vermeiden?\"*

    Im Falle von Stresssituationen, ja. Es macht keinen Sinn, sich
    übermäßig unter Druck zu setzen. Bei gesellschaftlichen Ereignissen,
    wie Bars oder Clubs, ist der Ratschlag umgekehrt. Geh raus und
    genieße es einfach. Du brauchst keinen Sex oder die
    Fortpflanzungsseite von Sex, selbst wenn du pornosüchtig bist. Geh
    raus und genieße die Tatsache, dass du keinen Sex oder die
    Fortpflanzungsseite von Sex haben musst. Das wird dir schnell die
    schöne Wahrheit beweisen, dass das Leben ohne diesen Druck so viel
    besser ist. Stell dir nur vor, wie viel besser es sein wird, wenn
    das kleine Monster dich verlassen hat, zusammen mit diesen
    hilfsbedürftigen Gedanken.
