# Der Aha!-Moment

Meist innerhalb von drei Wochen nach dem Ausstieg erleben Ex-Konsumenten
den Aha!-Moment. Der Himmel scheint heller zu werden und es ist der
Moment, in dem die Gehirnwäsche vollständig aufhört. Anstatt dir
einzureden, dass du keine Pornos mehr sehen musst, wird dir plötzlich
klar, dass der letzte Faden gerissen ist und du den Rest deines Lebens
genießen kannst, ohne es jemals wieder zu brauchen. An diesem Punkt
fängst du normalerweise auch an, die Nutzer mitleidig zu betrachten.

Diejenigen, die mit der Willenskraft-Methode aufhören, erleben diesen
Moment normalerweise nicht, denn obwohl sie froh sind, nicht mehr
abhängig zu sein, gehen sie weiter durchs Leben und glauben, dass sie
ein Opfer bringen. Je länger du süchtig warst, desto schöner ist dieser
Moment und er hält ein Leben lang an. Es gibt zwar viele Freuden im
Leben, aber es ist unmöglich, das eigentliche Gefühl wiederzuerlangen.
Die Freude, keine Pornos mehr anschauen zu müssen, ist eine andere. Wenn
du dich schlecht fühlst und einen Schub brauchst, erinnere dich daran,
wie schön es ist, nicht mehr von dieser schrecklichen Sucht abhängig zu
sein. Viele nennen es das schönste Ereignis in ihrem Leben. In den
meisten Fällen findet der Aha!-Moment nicht nach drei Wochen, sondern
nach ein paar Tagen statt.

In meinem eigenen Fall geschah es, bevor ich meinen letzten Haremsbesuch
beendet hatte. Ich bin mir sicher, dass viele der Leserinnen und Leser
hier, noch bevor sie das Ende der Kapitel erreicht haben, etwas sagen
würden wie: *\"Du brauchst kein weiteres Wort zu sagen. Ich sehe alles
so deutlich vor mir, dass ich weiß, dass ich nie wieder Pornos brauchen
werde.\"* Nach den Rückmeldungen, die wir erhalten haben, kommt das
häufig vor. Im Idealfall, wenn du alle Anweisungen befolgst und die
Psychologie vollständig verstehst, sollte es dir sofort gelingen.

Zwar heißt es, dass es etwa fünf Tage dauert, bis ein spürbarer
körperlicher Entzug schwindet, und etwa drei Wochen, bis ein Ex-User
völlig frei ist, aber solche Richtlinien können zwei Probleme
verursachen. Das erste ist, dass den Menschen suggeriert wird, dass sie
zwischen fünf Tagen und drei Wochen lang leiden müssen. Das zweite ist,
dass der Ex-Konsument dazu neigt, zu denken: *\"Wenn ich fünf Tage oder
drei Wochen überlebe, kann ich am Ende dieses Zeitraums einen echten
Schub erwarten.\"*

Es kann aber sein, dass sie fünf angenehme Tage oder drei angenehme
Wochen haben, auf die dann katastrophale Tage folgen, die jeden treffen
und die nichts mit der Sucht zu tun haben, sondern durch andere Faktoren
in unserem Leben verursacht werden. Dann erlebt unser Ex-Konsument, der
auf den Aha!-Moment wartet, stattdessen eine Depression. Das könnte sein
Selbstvertrauen zerstören. Umgekehrt könnte der Ex-Konsument, wenn es
keine Richtlinien gäbe, den Rest seines Lebens damit verbringen, darauf
zu warten, dass nichts passiert. So ergeht es der großen Mehrheit derer,
die mit der Willenskraftmethode aufhören.

Die Menschen fragen oft nach der Bedeutung der fünf Tage und drei
Wochen. Sind das einfach Zeiträume, die aus heiterem Himmel festgelegt
wurden? Nein, sie sind zwar keine festen Daten, aber sie spiegeln eine
Ansammlung von Rückmeldungen im Laufe der Jahre wider. Ungefähr fünf
Tage nach dem Aufhören ist der Zeitpunkt, an dem der Ex-Konsument
aufhört, die Sucht als Hauptbeschäftigung zu sehen. Die meisten
Ex-Konsumenten erleben in dieser Zeit eine Offenbarung, in der Regel in
stressigen oder sozialen Situationen, die ohne einen Haremsbesuch nicht
mehr zu bewältigen oder zu genießen waren. Plötzlich merkst du, dass du
nicht nur Spaß daran hast oder damit klarkommst, sondern dass dir der
Gedanke an Pornos gar nicht in den Sinn gekommen ist. Von diesem Punkt
an ist es normalerweise ganz einfach. In diesem Moment weißt du, dass du
frei bist.

Ich habe die Erfahrung gemacht, dass die meisten ernsthaften Versuche,
mit der Willenskraftmethode aufzuhören, nach etwa drei Wochen scheitern.
In der Regel merkst du nach etwa drei Wochen, dass du die Lust am
Pornoschauen verloren hast. Du musst es dir selbst beweisen, also
springst du in den Browser und besuchst deinen Harem. Es ist ein
komisches Gefühl, zu beweisen, dass du es geschafft hast. Aber dabei
schmierst du dank des frischen Dopaminrausches, nach dem sich dein
Körper in den letzten drei Wochen gesehnt hat, die
DeltaFosB-Wasserrutsche erneut. Sobald du die Tat vollbracht hast,
verlässt das Dopamin deinen Körper. Jetzt sagt eine kleine Stimme: *\"Du
hast es nicht geschafft, du willst noch einen Kick.\"*

Du rennst nicht sofort zurück, weil du nicht wieder süchtig werden
willst, sondern lässt eine sichere Zeit verstreichen. Wenn du das
nächste Mal in Versuchung gerätst, kannst du dir dann sagen: *\"Na ja,
ich bin nicht wieder süchtig geworden, also kann es nicht schaden, noch
eine zu haben.\"* Dann bist du schon auf dem besten Weg, den Abhang
hinunterzurutschen. Der Schlüssel zum Problem ist nicht, auf den
Aha!-Moment zu warten, sondern zu erkennen, dass es vorbei ist, sobald
du den Browser schließt. Du hast die Sauerstoffzufuhr zu deinem kleinen
Monster unterbrochen. Keine Macht der Welt kann dich daran hindern, frei
zu sein, außer du bläst Trübsal oder wartest auf den Aha!-Moment. Geh
hin und genieße das Leben; bewältige es von Anfang an. Auf diese Weise
wirst du bald den Moment erleben.
