Nachdem du dich für ein Timing entschieden hast, bist du bereit, deinen
Harem ein letztes Mal zu besuchen. Bevor du das tust, überprüfe die
beiden wichtigsten Dinge.

1.  Bist du dir des Erfolgs sicher?

2.  Hast du ein Gefühl der Untergangsstimmung oder ein Gefühl der
    Aufregung, dass du etwas Großartiges erreichen wirst?

Wenn du irgendwelche Zweifel hast, lies das Buch noch einmal. Erinnere
dich daran, dass du dich nie dafür entschieden hast, in die Pornofalle
zu tappen, aber die Falle ist so konstruiert, dass sie dich ein Leben
lang versklavt. Um ihr zu entkommen, musst du die positive Entscheidung
treffen, dass du jetzt aufhören und deinen letzten Besuch machen wirst.

Vergiss nicht, dass du dieses Buch bisher nur gelesen hast, weil du am
liebsten ausbrechen würdest. Triff also jetzt eine positive
Entscheidung, indem du dir feierlich schwörst, dass du deinen Harem nie
wieder besuchen wirst, wenn du dein privates Browserfenster schließt,
egal ob es dir leicht oder schwer fällt. Vielleicht machst du dir
Sorgen, dass du dieses Gelübde schon mehrmals abgelegt hast und immer
noch versagst, oder dass du ein schreckliches Trauma durchmachen musst.
Keine Angst, das Schlimmste, was passieren kann, ist, dass du versagst,
denn du hast ***absolut nichts*** zu verlieren und so viel zu gewinnen.

Aber hör auf, über das Scheitern nachzudenken. Die schöne Wahrheit ist,
dass es nicht nur lächerlich einfach ist, aufzuhören, sondern dass du
den Prozess sogar genießen kannst. Dieses Mal wirst du EasyPeasy
benutzen! Alles, was du tun musst, ist, den einfachen Anweisungen zu
folgen, die du gleich erhältst.

1.  Lege jetzt den feierlichen Schwur ab und meine es ernst.

2.  Durchstöbere die Bilder und Clips auf deiner Lieblings-Tubeseite
    ganz bewusst, betrachte die verzweifelten Versuche der
    Seitenbetreiber, Schauspieler und sogar Amateure, den Schock, die
    Neuartigkeit und den übernormalen Charakter ihrer Ware zu verstärken
    und frage dich, wo das Vergnügen bleibt.

3.  Wenn du den Browser schließlich schließt, tue dies nicht mit einem
    Gefühl von *\"Ich darf nie wieder einen online Harem besuchen\"*
    oder *\"Ich darf keinen anderen besuchen\"*, sondern mit einem
    Gefühl von Freiheit, wie *\"Ist das nicht toll? Ich bin frei! Ich
    bin nicht länger ein Sklave der Pornos! Ich muss nie wieder in
    meinem Leben diese schmutzigen Seiten besuchen.\"*

4.  Sei dir bewusst, dass es für ein paar Tage einen kleinen
    Porno-Saboteur in deinem Bauch geben wird. Vielleicht nimmst du nur
    das Gefühl wahr, dass du eine Sitzung willst. Das kleine
    Pornomonster wird als das leichte körperliche Verlangen nach Dopamin
    bezeichnet. Streng genommen ist das falsch und es ist wichtig zu
    verstehen, warum. Weil es bis zu drei Wochen dauert, bis das kleine
    Monster stirbt, glauben Ex-Nutzer, dass das kleine Monster auch nach
    dem letzten Online-Harem-Besuch weiter nach Dopamin verlangt und sie
    deshalb Willenskraft aufwenden müssen, um der Versuchung in dieser
    Zeit zu widerstehen. Das stimmt nicht, denn der Körper sehnt sich
    nicht nach dem durch Pornos ausgelösten Dopamin. Nur das Gehirn
    sehnt sich nach Dopamin.

Wenn du in den nächsten Tagen das Gefühl bekommst, einen Blick darauf
werfen zu wollen, hat dein Gehirn eine einfache Wahl. Es kann dieses
Gefühl entweder als das interpretieren, was es tatsächlich ist - ein
leeres, unsicheres Gefühl, das durch den ersten Besuch einer
Online-Pornoseite ausgelöst wurde und bei jedem weiteren Besuch
aufrechterhalten wird, indem du dir sagst: **\"YIPPEE! ICH BIN EIN
NICHT-NUTZER!\"**

Oder du fängst an, dich nach Pornos zu sehnen und leidest für den Rest
deines Lebens. Denk doch mal einen Moment nach, wäre das nicht
unglaublich dumm? Zu sagen: *\"Ich will nie wieder Pornos sehen\"* und
dann den Rest deines Lebens damit zu verbringen, zu sagen: /textit\"Ich
würde gerne mal einen sehen\"? Das ist es, was diejenigen tun, die die
Willenskraftmethode anwenden. Kein Wunder, dass sie sich so elend
fühlen. Sie verbringen den Rest ihres Lebens damit, verzweifelt Trübsal
zu blasen für etwas, von dem sie hoffen, dass sie es nie bekommen
werden. Kein Wunder, dass so wenige von ihnen Erfolg haben und die
wenigen, die es schaffen, sich nie völlig frei fühlen.

Es ist nur das Zweifeln und Warten, das es schwierig macht, aufzuhören,
also zweifle nie an deiner Entscheidung, denn du weißt, dass sie richtig
ist. Wenn du anfängst, daran zu zweifeln, bringst du dich selbst in eine
ausweglose Situation. Du sehnst dich elendig nach einem Besuch, kannst
ihn aber nicht bekommen. Egal, welches System du verwendest, was willst
du erreichen, wenn du mit Pornos aufhörst? Nie wieder zu schauen? Nein!
Viele Ex-Nutzer tun das, aber sie gehen mit dem Gefühl der Entbehrung
durch den Rest ihres Lebens.

Was ist der Unterschied zwischen Nutzern und Nichtnutzern? Nicht-Nutzer
haben kein Bedürfnis oder Verlangen, Pornos zu schauen, sie haben kein
Verlangen und müssen keine Willenskraft aufbringen, um sie nicht zu
schauen. Das ist es, was du erreichen willst, und es liegt ganz in
deiner Macht, das zu tun. Du musst nicht warten, bis du kein Verlangen
mehr nach Pornos hast oder ein Nichtnutzer wirst. Das ist in dem Moment
erledigt, in dem du die letzte Browsersitzung schließt und die
Dopaminversorgung unterbrichst: **DU BIST BEREITS EIN GLÜCKLICHER
NICHT-NUTZER!**

Du bleibst ein glücklicher Nicht-Nutzer, solange du:

1.  Du zweifelst nie an deiner Entscheidung.

2.  Du wartest nicht darauf, ein Nichtnutzer zu werden. Wenn du das
    tust, wartest du nur darauf, dass nichts passiert und baust eine
    Phobie auf.

3.  Du versuchst nicht, nicht an Pornos zu denken oder auf den
    \"Aha!-Moment\" zu warten, wodurch du eine Phobie entwickelst.

4.  Du verwendest keine Ersatzstoffe.

5.  Du siehst alle anderen Nutzer so, wie sie wirklich sind, und
    bemitleidest sie, anstatt sie zu beneiden.

Egal, ob es gute oder schlechte Tage sind, ändere dein Leben nicht, nur
weil du aufgehört hast. Wenn du das tust, bringst du ein echtes Opfer,
obwohl es gar nicht nötig ist. Denke daran, dass du das Leben nicht
aufgegeben hast. Du hast nichts aufgegeben. Im Gegenteil, du hast dich
von einer schrecklichen Krankheit geheilt und bist aus einem
heimtückischen Gefängnis entkommen. Wenn die Tage vergehen und sich
deine körperliche und geistige Gesundheit verbessert, werden dir die
Hochs höher und die Tiefs weniger tief erscheinen als zu der Zeit, als
du ein Nutzer warst. Wann immer du in den nächsten Tagen oder für den
Rest deines Lebens an Pornos denkst, denke dies:

\"YIPPEE! ICH BIN EIN NICHT-NUTZER!\"

# Eine letzte Warnung

Kein Nutzer, der die Chance hat, mit dem Wissen, das er jetzt hat, in
die Zeit zurückzukehren, bevor er süchtig wurde, würde sich dafür
entscheiden, wieder anzufangen. Zehntausende, die jahrelang erfolgreich
aufhören, führen ein glückliches Leben, nur um dann wieder in die Falle
zu tappen. Ich vertraue darauf, dass dieses Buch dir helfen wird,
relativ leicht aufzuhören. Aber sei gewarnt: Wem es leicht fällt,
aufzuhören, dem fällt es auch leicht, wieder anzufangen - **tappe nicht
in diese Falle.**

Egal, wie lange du aufgehört hast oder wie sicher du bist, dass du nie
wieder süchtig wirst, mach dir zur Lebensregel, keine Pornos zu schauen,
egal aus welchem Grund. Widerstehe den Anspielungen und Andeutungen in
den Medien und erinnere dich daran, wie sie ihr Image der \"Offenheit\"
pushen, indem sie Pornos in den Mainstream bringen, ohne zu erkennen,
dass Pornos, Internetpornos und zwanghafte Masturbation für eine große
Anzahl von Männern und einige Frauen ein Killer von Beziehungen und des
persönlichen Wohlbefindens sind.

Vergiss nicht, dass der erste Blick oder Besuch nichts für dich
bedeutet. Du wirst keine Entzugserscheinungen haben, die du lindern
kannst, und du wirst dich schrecklich fühlen. Was er jedoch bewirkt, ist
ein Dopaminrausch in deinem Kopf und deinem Gehirn, und eine kleine
Stimme in deinem Hinterkopf wird dir sagen, dass du einen weiteren
willst. Dann hast du die Wahl, eine Weile unglücklich zu sein oder die
ganze schmutzige Kette von vorne zu beginnen.
