# Feedback

Der Krieg richtet sich nicht gegen die Nutzer, sondern gegen die Falle
der Pornoindustrie, und er wird aus dem einfachen Grund geführt, weil es
mir Spaß macht. Jedes Mal, wenn ich von einem Nutzer höre, der aus dem
Gefängnis ausbricht, erfüllt mich das mit ungeheurer Freude. Aber dieses
Vergnügen geht nicht ohne erhebliche Frustration einher, die
hauptsächlich von zwei Kategorien von Pornonutzern verursacht wird.
Trotz der Warnung im vorigen Kapitel bin ich immer wieder überrascht von
der Zahl derer, denen es leicht fällt, aufzuhören, die aber später
süchtig werden und feststellen, dass sie es beim nächsten Mal nicht
schaffen.

Es ist, als würde man jemanden finden, der bis zum Hals in einem Sumpf
steckt und kurz davor ist, unterzugehen. Du hilfst, ihn herauszuziehen,
und er ist dankbar, aber sechs Monate später taucht er wieder in den
Sumpf ein. Ein besonderes Problem stellen Nutzer dar, denen es leicht
fällt, aufzuhören und wieder anzufangen: *\"BITTE, BITTE, MACH NICHT DEN
SELBEN FEHLER.* Sie glauben, dass solche Menschen wieder anfangen, weil
sie immer noch süchtig sind und ihnen das Dopamin fehlt. Tatsächlich
fällt es ihnen so leicht aufzuhören, dass sie ihre Angst vor Pornos
verlieren. Sie denken: *\"Ich kann eine gelegentliche Session haben,
selbst wenn ich wieder süchtig werde, fällt es mir leicht,
aufzuhören.\"*

Ich fürchte, so funktioniert das nicht. Es ist leicht, mit Pornos
aufzuhören, aber unmöglich, die Sucht zu kontrollieren. Das Einzige, was
wichtig ist, um mit Pornos aufzuhören, ist, sie nicht zu benutzen.

Die andere Kategorie von frustrierten Nutzern sind diejenigen, die zu
ängstlich sind, um den Versuch zu unternehmen, aufzuhören, oder wenn sie
es doch tun, ist es ein großer Kampf. Die Hauptschwierigkeiten scheinen
die folgenden zu sein:

Angst vor dem Scheitern

:   Scheitern ist keine Schande, aber es nicht zu versuchen, ist
    schlichtweg Dummheit. Sieh es doch mal so: Du versteckst dich vor
    nichts. Das Schlimmste, was dir passieren kann, ist, dass du
    scheiterst, aber dann bist du nicht schlechter dran als jetzt. Denk
    einfach daran, wie schön es wäre, wenn du Erfolg hast. Wenn du es
    nicht versuchst, hast du das Scheitern bereits garantiert.

Angst vor Schmerzen und dem Unglücklichsein

:   Mach dir keine Gedanken darüber, sondern denke einfach: Was könnte
    dir Schlimmes passieren, wenn du nie wieder Pornos schaust? Absolut
    nichts. Schreckliche Dinge werden passieren, wenn du es doch tust,
    lies noch einmal die Notizen zu Pascals Wette. Auf jeden Fall wird
    die Panik durch Dopamin ausgelöst und ist bald wieder weg. Der
    größte Gewinn ist, diese Angst loszuwerden. Glaubst du wirklich,
    dass die Nutzer bereit sind, schwindende Penetrationen,
    unzuverlässige sexuelle Leistungen oder die Orgasmusfreude, die sie
    aus Pornos kennen, in Kauf zu nehmen? Wenn du merkst, dass du in
    Panik gerätst, hilft dir tiefes Atmen. Wenn du mit anderen Menschen
    zusammen bist und sie dich fertig machen, flüchte vor ihnen und geh
    in die Garage, ein leeres Büro oder sonst wohin.

    Wenn dir zum Weinen zumute ist, brauchst du dich nicht zu schämen.
    Weinen ist die natürliche Art, Spannungen abzubauen. Niemand hat
    sich je ausgeweint, ohne sich danach besser zu fühlen. Eines der
    schrecklichen Dinge, die wir jungen Männern antun, ist, sie darauf
    zu konditionieren, nicht zu weinen. Du kannst sehen, wie sie
    versuchen, die Tränen zurückzuhalten, aber beobachte, wie der Kiefer
    knirscht. Wir bringen uns selbst bei, keine Gefühle zu zeigen, aber
    wir sollen sie nicht in uns hineinfressen. Schrei, brülle oder hab
    einen Wutanfall. Tritt etwas. Betrachte deinen Kampf als einen
    Boxkampf, den du nicht verlieren kannst. Niemand kann die Zeit
    anhalten und mit jedem Moment, der vergeht, schwindet das kleine
    Monster in dir. Genieße deinen unausweichlichen Sieg.

Den Anweisungen nicht folgen.

:   Unglaublich, dass einige Nutzer sagen, dass die Methode bei ihnen
    nicht funktioniert hat. Dann beschreiben sie, wie sie nicht nur eine
    Anweisung, sondern praktisch alle ignoriert haben. Der
    Übersichtlichkeit halber sind diese Punkte am Ende dieses Kapitels
    in einer Checkliste zusammengefasst.

Missverständnis von Anweisungen

:   Die Hauptprobleme scheinen folgende zu sein:

    \"Ich kann nicht aufhören, an Pornos zu denken.\"

    :   Natürlich kannst du das nicht und wenn du es versuchst,
        entwickelst du eine Phobie und wirst unglücklich. Es ist wie der
        Versuch, nachts einzuschlafen: Je mehr du es versuchst, desto
        schwieriger wird es. Es ist egal, ob du neunzig Prozent deines
        Lebens an Pornos denkst, wichtig ist, was du denkst. Wenn du
        denkst: \"Oh, ich liebe es, Pornos anzuschauen\" oder \"Wann
        werde ich frei sein?\", wirst du unglücklich sein. Wenn du
        stattdessen denkst: *\"YIPPEE! Ich bin frei!\"*, wirst du
        glücklich sein.

    \"Wann wird das kleine Pornomonster sterben?\"

    :   Der Dopaminrausch verlässt deinen Körper sehr schnell, aber es
        ist unmöglich zu sagen, wann dein Körper nicht mehr unter dem
        leichten körperlichen Gefühl des Dopaminentzugs leiden wird.
        Dieses leere, unsichere Gefühl ist identisch mit normalem
        Hunger, Depressionen oder Stress. Alles, was Pornos tun, ist,
        das Level davon zu erhöhen. Deshalb sind sich Nutzer, die mit
        der Willenskraftmethode aufhören, nie ganz sicher, ob sie es
        geschafft haben, auch wenn ihr Körper nicht mehr unter
        Dopamin-Entzug leidet. Wenn sie unter normalem Hunger oder
        Stress leiden, sagt ihnen ihr Gehirn immer noch, dass dies ein
        triftiger Grund ist, ihren Anspruch auf eine Sitzung geltend zu
        machen. Der Punkt ist, dass du nicht darauf warten musst, dass
        das Verlangen verschwindet. Es ist so gering, dass wir es gar
        nicht bemerken, sondern nur als ein Gefühl des Verlangens
        wahrnehmen. Wenn du den Zahnarzt verlässt, wartest du dann, bis
        dein Kiefer nicht mehr schmerzt? Natürlich nicht, du machst
        einfach weiter mit deinem Leben. Auch wenn dein Kiefer immer
        noch schmerzt, freust du dich.

        Warte nicht darauf, dass die Entzugserscheinungen verschwinden,
        denn du erzeugst Zweifel, indem du dich ständig fragst: *\"Wie
        lange wird das dauern? Bin ich überhaupt frei, wenn ich mich
        nicht anders fühle?\"* Die Angst ist der eigentliche Schmerz,
        deshalb erzeugt das Warten darauf, dass das Leben nach dem
        Aufhören besser wird, Zweifel. Der Entzug ist nicht spürbar, es
        sei denn, du hast Angst davor. Die exponentiellen Verbesserungen
        in der Neurologie sind langsam, wenn du also darauf wartest,
        dass du dich anders fühlst, wird es sich so anfühlen, als würde
        nichts passieren, was Zweifel erzeugt.

    Auf den Aha!-Moment warten

    :   Wenn du auf ihn wartest, verursachst du nur eine weitere Phobie.
        Ich habe einmal drei Wochen lang mit der Willenskraftmethode
        aufgehört. Bei einem Gespräch mit einem alten Freund fragte er
        mich, wie ich vorankomme.\
        Ich sagte: *\"Ich habe drei Wochen überlebt.\"*\
        Er fragte: *\"Was meinst du damit, du hast drei Wochen
        überlebt?\"*\
        Ich klärte ihn auf: *\"Ich habe drei Wochen ohne Pornos
        überlebt.\"*\
        Er sagte: *\"Was willst du denn machen? Den Rest deines Lebens
        überleben? Worauf wartest du noch, du hast es geschafft. Du bist
        ein Nicht-Nutzer.\"*

        Ich dachte: *\"Er hat völlig recht, worauf warte ich noch?\"*
        Leider war ich mangels Verständnis für die Falle bald wieder
        drin, aber ich habe mir den Punkt gemerkt. Wenn du deinen
        Browser schließt, wirst du zu einem Nicht-Nutzer. Das Wichtigste
        ist, dass du von Anfang an ein glücklicher Nicht-Nutzer bist.

    \"Ich habe immer noch Lust auf Pornos.\"

    :   Dann bist du sehr dumm. Wie kannst du behaupten, dass du ein
        Nicht-Nutzer sein willst, und dann sagen, dass du Pornos willst?
        Das ist ein Widerspruch. Wenn du sagst, dass du Pornos willst,
        sagst du damit, dass du ein Nutzer sein willst. Nicht-Nutzer
        wollen die ekelhaften Tube-Seiten nicht besuchen. Du weißt
        bereits, was du sein willst, also hör auf, dich zu bestrafen.

    \"Ich habe mich aus dem Leben verabschiedet.\"

    :   Warum? Du musst nur aufhören, dich selbst zu töten und
        stattdessen anfangen, Energie zu tanken. Du musst nicht im
        Geringsten aufhören zu leben. Es ist ganz einfach: In den
        nächsten paar Tagen wirst du ein leichtes Trauma in deinem Leben
        haben. Dein Körper wird fast unmerklich unter dem Entzug von
        Ansprüchen und Forderungen nach einem Dopaminschub leiden. Aber
        bedenke: Du bist nicht schlechter dran als vorher. Darunter hast
        du dein ganzes Leben lang gelitten, jedes Mal, wenn du
        geschlafen hast, in der Kirche, im Supermarkt oder in der
        Bibliothek. Es schien dich nicht zu stören, als du ein Nutzer
        warst. Wenn du nicht aufhörst, wirst du für den Rest deines
        Lebens darunter leiden.

        Pornos und Orgasmen schaffen keine Gelegenheiten, sie nehmen sie
        dir weg. Auch wenn dein Körper noch nach Dopamin verlangt, sind
        Mahlzeiten und gesellschaftliche Anlässe wunderbar. Das Leben
        ist wunderbar, geh zu gesellschaftlichen Anlässen, auch wenn
        dort nackte Tänzerinnen sind. Denke daran, dass nicht du beraubt
        wirst, sondern sie. Jeder Einzelne von ihnen wäre gerne in
        deiner Lage, wenn sie es nur wüssten. Genieße es, die Primadonna
        zu sein und im Mittelpunkt der Aufmerksamkeit zu stehen. Mit
        Pornos aufzuhören ist ein wunderbares Gesprächsthema, weil du
        dir ein geheimes Vergnügen gönnst, das sie nicht haben. Deine
        Freunde und Kollegen werden überrascht sein, dass du, der früher
        schüchtern und müde aussah, jetzt glücklich und fröhlich bist.
        Du wirst das Leben von Anfang an genießen. Es gibt keinen Grund,
        Anmachkünstler auf Partys zu beneiden, sie werden dich
        beneiden - wenn sie es nur wüssten.

    \"Ich bin unglücklich und reizbar.\"

    :   Das ist das Nichtbefolgen von Anweisungen. Finde heraus, um
        welche es sich handelt. Manche Menschen verstehen und glauben
        alles, was geschrieben steht, haben aber trotzdem das Gefühl,
        als würde etwas Schreckliches passieren. Du tust nicht nur das,
        was du gerne tun würdest, sondern auch das, was jeder Nutzer auf
        dem Planeten möchte. Bei jeder Methode des Aufhörens versucht
        der Ex-Konsument, eine bestimmte Geisteshaltung zu erreichen,
        sodass jeder Gedanke an Pornos zu einem *\"YIPPEE! ICH BIN
        FREI!\"* wird. Wenn das dein Ziel ist, warum dann noch warten?
        Fange mit dieser Einstellung an und verliere sie nie wieder, es
        gibt keine Alternative.

    \"Ich hatte eine gute Woche / einen guten Monat / ein gutes halbes Jahr, aber ich bin wieder in der Falle.\"

    :   Denk daran, dass die Angst selbst der Schmerz ist. Wenn du einem
        Schmerz nachgibst, erzeugt das noch mehr Angst, füttert das
        geschwächte kleine Monster und führt dazu, dass der Nicht-Nutzer
        denkt, er sei für immer süchtig. In Wirklichkeit hat sich ihre
        Vorstellung von der Gehirnwäsche nicht geändert, aber sie haben
        den Gedankenprozess mit Dopamin versorgt. Das ist per Definition
        ein Vorwärtsfallen, aber ein Versagen, den Anweisungen zu
        folgen. Finde welche im Folgenden und freue dich:

# Die Prüfliste

Wenn du diese Anweisungen befolgst, kannst du nicht scheitern:

1.  Lege einen feierlichen Schwur ab, dass du niemals, niemals, online
    gehen wirst, um deinen Harem zu besuchen *Oder* dich mit statischen
    Bildern zufrieden geben *Oder* Frieden schließen mit erotischen
    Grafiken *Oder* allem, was übernormale Reize enthält, und halte dich
    an deinen Schwur.

2.  Mach dir das klar: Es gibt absolut nichts, was du aufgeben musst.
    Damit ist nicht gemeint, dass du als Nicht-PMOer besser dran bist
    (das wusstest du schon die ganze Zeit); auch nicht, dass es zwar
    keinen rationalen Grund gibt, warum du PMO machst, du aber trotzdem
    ein Vergnügen oder eine Krücke davon hast, sonst würdest du es nicht
    tun. Gemeint ist, dass es *kein echtes Vergnügen oder eine Krücke
    beim PMOing gibt.* Es ist nur eine Illusion, so wie wenn du deinen
    Kopf gegen eine Wand schlägst, um Freude zu empfinden, wenn du
    aufhörst.

3.  So etwas wie einen eingefleischten PMOer gibt es nicht. Du bist nur
    einer von Millionen, die auf die subtile Falle hereingefallen sind.
    Wie Millionen anderer Ex-PMOer, die einst dachten, sie könnten nicht
    entkommen, bist auch du entkommen.

4.  Wenn du zu irgendeinem Zeitpunkt in deinem Leben die Vor- und
    Nachteile von PMO abwägen müsstest, würde die überwältigende
    Schlussfolgerung immer lauten: *\"Hör auf damit. Du bist ein
    Idiot!\"* Daran wird sich nie etwas ändern. Das war schon immer so
    und wird immer so bleiben. Wenn du eine Entscheidung getroffen hast,
    von der du weißt, dass sie richtig ist, darfst du dich nicht mit
    Zweifeln quälen. Die Pascalsche Wette mit keiner Chance auf
    Verluste, hohen Chancen auf Gewinne und hohen Chancen auf die
    Vermeidung von Verlusten trifft perfekt auf PMO zu.

5.  Versuche nicht, nicht an Pornos zu denken, oder mache dir Sorgen,
    dass du ständig daran denkst. Wann immer du daran denkst, ob heute,
    morgen oder für den Rest deines Lebens, denke **\"YIPPEE! Ich bin
    ein Nicht-PMOer!\"**

6.  **Verwende keine** Form von Ersatz. **Habe keinen** Laptop neben
    dir, wenn du schläfst. **Vermeide keine** Spiele, Filme oder
    Zeitschriften. Verändere deinen Lebensstil in **keiner** Weise, nur
    weil du aufgehört hast. Wenn du die oben genannten Anweisungen
    befolgst, wirst du bald den 'Aha!-Moment' erleben, aber:

7.  Warte nicht auf den 'Aha!-Moment'. Mache einfach weiter mit deinem
    Leben, genieße die Höhen und meistere die Tiefen. Du wirst
    feststellen, dass der Moment im Handumdrehen kommen wird.
