# Hilf denen auf dem Sinkenden Schiff

Pornonutzer sind heutzutage in Panik, weil sie spüren, dass sich die Art
und Weise, wie Internetpornos von Männern und Frauen wahrgenommen
werden, verändert. Der Suchtcharakter von Internetpornos wird von immer
mehr Menschen untersucht und zu Recht als etwas anderes als die
traditionelle Pornografie angesehen. Die Leichtigkeit und Verfügbarkeit
lässt sogar die Herzen der Pornofans höher schlagen. Sie spüren auch,
dass ihr Kreuzzug für Rede- und Gedankenfreiheit von verschiedenen
Elementen unterwandert wird. Der wilde Westen des unkontrollierten
Internets macht es fast unmöglich, Altersbeschränkungen für
außergewöhnliche Reize durchzusetzen. Es wird zwar nicht so bald ein
Ende haben, aber Tausende von Nutzern hören auf, und die meisten
Süchtigen sind sich der Studien bewusst, die Ähnlichkeiten zwischen
Pornos und Drogensucht aufzeigen. Jedes Mal, wenn ein Nutzer das
sinkende Schiff verlässt, fühlen sich die Verbliebenen noch elender.

Jeder Nutzer weiß instinktiv, dass es lächerlich ist, sich selbst zu
sabotieren und Zeit vor zweidimensionalen Pixeln zu verbringen, die das
Gehirn überfluten und Hirnwasserrutschen entwickeln, die schlechte
sexuelle Leistungen garantieren. Wenn du es immer noch nicht für albern
hältst, versuche mal, mit einem Pornomagazin zu reden, das im Zentrum
deiner Stadt steht, und frage dich, was der Unterschied ist. Nur einen.
So bekommst du nicht den Genuss von Wärme und Intimität. Wenn du
aufhören kannst, jedes Mal Alkohol und Zigaretten zu kaufen, wenn du
einkaufen gehst, kannst du definitiv auch aufhören, deinen Online-Harem
zu besuchen. Nutzer können keinen rationalen Grund für das Anschauen von
Pornos finden, aber wenn es jemand anderes tut, kommen sie sich nicht
ganz so dumm vor.

Die Drogenkonsumenten lügen nicht nur gegenüber Forschern und anderen,
sondern vor allem gegenüber sich selbst. Das müssen sie auch, denn die
Gehirnwäsche ist unerlässlich, wenn sie ihre Selbstachtung bewahren
wollen. Sie haben das Bedürfnis, ihre \"Angewohnheit\" nicht nur vor
sich selbst, sondern auch vor Nichtkonsumenten zu rechtfertigen. Sie
werben ständig mit subtileren Mitteln für die illusorischen Vorteile von
Pornos.

Wenn ein Nutzer mit der Willenskraftmethode aufhört, fühlt er sich immer
noch beraubt und neigt dazu, zu jammern. Das bestätigt den anderen
Nutzern nur, wie richtig es ist, weiter zu konsumieren. Wenn es dem
Ex-Konsumenten gelingt, von der Sucht loszukommen, ist er dankbar, dass
er sich nicht mehr selbst sabotieren oder Energie verschwenden muss. Sie
haben es nicht nötig, sich zu rechtfertigen. Sie sitzen nicht da und
sagen, wie toll es ist, keine Pornos mehr zu benutzen, nur wenn sie
gefragt werden, aber nie vom Nutzer selbst. Vergiss nicht, dass es die
Angst ist, die den Kopf in den Sand steckt und das eigene Verhalten erst
dann in Frage stellt, wenn man aufhört. Hilf dem Nutzer, indem du ihm
diese Ängste nimmst. Sag ihnen, wie wunderbar es ist, nicht in einem
Gefängnis leben zu müssen, wie schön es ist, morgens aufzuwachen und
sich fit und gesund zu fühlen, anstatt energielos und selbstverachtend
zu sein, wie wunderbar es ist, von der Sklaverei befreit zu sein, das
Leben in vollen Zügen genießen zu können und die schwarzen Schatten los
zu sein. Oder noch besser: Bring sie dazu, dieses Buch zu lesen.

Es ist wichtig, einen verheirateten User nicht herabzusetzen, indem man
ihm unterstellt, dass er seine Beziehung absichtlich ruiniert oder in
irgendeiner Weise betrügt oder unsauber ist. Es ist ein weit
verbreiteter Irrglaube, dass der Ex-Nutzer in dieser Hinsicht der
Schlimmste ist. Diese Vorstellung ist zwar nicht ganz unberechtigt, aber
in der Regel liegt es an der Willenskraft aufzuhören. Weil der
Ex-Konsument, obwohl er die Sucht überwunden hat, immer noch einen Teil
der Gehirnwäsche in sich trägt, glaubt ein Teil von ihm, dass er ein
Opfer gebracht hat. Sie fühlen sich verletzlich und ihr natürlicher
Verteidigungsmechanismus besteht darin, den Pornokonsumenten
anzugreifen.

Das mag dem Ex-Nutzer helfen, aber dem Nutzer hilft es nicht. Das
Einzige, was es bewirkt, ist, dass sie sich noch erbärmlicher fühlen und
ihr Bedürfnis nach Pornos noch größer wird. Auch wenn die veränderte
Haltung der medizinischen Einrichtungen gegenüber Internetpornos der
Hauptgrund dafür ist, dass viele Nutzer aufhören, macht es das nicht
einfacher. Im Gegenteil, es wird dadurch viel schwieriger. Die meisten
Nutzer glauben heutzutage, dass sie vor allem aus gesundheitlichen
Gründen aufhören. Das ist aber nicht ganz richtig.

Obwohl das enorme Gesundheitsrisiko natürlich ein großer Ansporn für den
Ausstieg sein sollte, sabotieren die Nutzer ihre Potenz schon seit
Jahren und es hat nicht den geringsten Unterschied gemacht. Der
Hauptgrund, warum die Nutzer aufhören, ist, dass die Gesellschaft
beginnt, Pornos als das zu erkennen, was sie sind: Drogensucht. Der
Genuss war immer eine Illusion, diese Einstellung nimmt die Illusion
weg, so dass dem Nutzer nichts mehr bleibt. Viele Partner würden jetzt
Fragen stellen, wenn du mitten in der Nacht an deinem Laptop sitzt.

Vollständige Pornoverbote in einigen Ländern oder die Nichtverfügbarkeit
des Internets sind klassische Beispiele für das Dilemma des reisenden
Nutzers. Der Nutzer nimmt entweder die Haltung ein: *\"Okay, wenn ich
keine Pornos haben kann, werde ich einen Weg finden, mich zu
verdrücken.\"* Das nützt ihm aber nichts, wenn sein Job davon abhängt.
Oder sie sagen: *\"Gut, das hilft mir, meinen Konsum einzuschränken.\"*
Das Ergebnis ist, dass sie statt ein oder zwei Tage, die sie auch nicht
genossen hätten, eine ganze Woche lang abstinent bleiben. Während dieser
erzwungenen Abstinenz warten sie aber nicht nur mental auf ihre
Belohnung, sondern auch ihr Körper verlangt danach. Oh, wie wertvoll ist
dieser Online-Harem-Besuch, wenn er endlich erlaubt wird.

Erzwungene Abstinenz reduziert den Konsum nicht wirklich, weil der
Nutzer sich nur noch mehr vergnügt, wenn er endlich allein sein darf.
Das Einzige, was es bewirkt, ist, dass die Nutzer merken, wie wertvoll
Internetpornos sind und wie abhängig sie von ihnen sind. Der
heimtückischste Aspekt dieser erzwungenen Abstinenz ist ihre Wirkung auf
Jugendliche. Wir lassen es zu, dass die Entführer der \"freien
Meinungsäußerung\", die Pornoproduzenten, unglückliche Jugendliche
ansprechen, um sie überhaupt erst süchtig zu machen. Dann, in der
wahrscheinlich stressigsten Zeit ihres Lebens, in der sie in ihrer
verblendeten Vorstellung Pornos am dringendsten brauchen, erpressen wir
sie, damit sie aufhören, weil sie sich damit selbst schaden.

Viele sind dazu nicht in der Lage und müssen unverschuldet für den Rest
ihres Lebens unter einem Schuldkomplex leiden. Viele schaffen es und
sind froh darüber, weil sie denken: *\"Gut. Ich mache das jetzt und wenn
es vorbei ist, bin ich sowieso geheilt.\"* Dann kommen der Schmerz und
die Angst bei der Arbeitssuche und andere Kämpfe als Erwachsener,
gefolgt von dem größten \"Hoch\" ihres Lebens - dem Finden eines Jobs.
Der Schmerz und die Angst sind vorbei, jetzt fühlen sie sich sicher und
der alte Auslösemechanismus kommt wieder in Gang. Ein Teil der
Gehirnwäsche ist noch da und bevor der Geruch des neuen Arbeits-Laptops
verflogen ist, steht der Nutzer an der Schwelle seines
Lieblings-Online-Harems. Die Freude über das Ereignis verdrängt die
unangenehmen Gefühle, sie haben nicht die Absicht, wieder süchtig zu
werden, aber ein Blick kann nicht schaden\... Zu spät! Sie sind schon
wieder süchtig.

Das alte Verlangen des kleinen Monsters wird wieder einsetzen und selbst
wenn sie nicht sofort wieder süchtig werden, wird sie die Depression
nach dem Hochgefühl wahrscheinlich einholen. Es ist seltsam, dass,
obwohl Heroinabhängige vor dem Gesetz Kriminelle sind, die Gesellschaft
diesen Menschen hilft. Lasst uns die gleiche Haltung gegenüber den armen
Pornokonsumenten einnehmen. Sie tun es nicht, weil sie es wollen,
sondern weil sie denken, dass sie es müssen. Im Gegensatz zu
Heroinsüchtigen müssen sie meist jahrelang psychische und physische
Qualen erleiden. Wir sagen immer, ein schneller Tod ist besser als ein
langsamer, also beneide den armen Pornokonsumenten nicht. Sie verdienen
dein Mitleid.
