# Ratschläge für Nicht-Nutzer

## Hilf deinen Porno nutzenden Freunden, dieses Buch zu lesen

Studiere zunächst den Inhalt dieses Buches und versuche, dich in die
Lage des Nutzers zu versetzen. Zwinge sie nicht, dieses Buch zu lesen,
indem du ihnen sagst, sie würden ihre Gesundheit ruinieren oder mit dem
Feuer spielen. Sie wissen das besser als du. Die Nutzer schauen sich
Pornos nicht an, weil es ihnen Spaß macht oder weil sie es wollen; sie
erzählen das nur, weil sie sich selbst und anderen das einreden, um ihre
Selbstachtung zu bewahren. Sie tun es, weil sie von Pornos abhängig
sind, weil sie denken, dass es sie entspannt, ihnen Mut oder
Selbstvertrauen gibt (Vergnügen oder Krücke) und weil sie das Gefühl
haben, dass das Leben ohne \"Sex\", zumindest ihre Version davon,
niemals angenehm sein wird. Wenn du versuchst, einen Nutzer zum Aufhören
zu zwingen, wird er sich wie ein gefangenes Tier fühlen und seinen Harem
noch mehr wollen. Das kann dazu führen, dass sie zu heimlichen Usern
werden und Pornos in ihren Augen noch wertvoller werden.

Konzentriere dich stattdessen auf die andere Seite der Medaille. Bringe
sie in die Gesellschaft von Ex-Usern (Blogs, Foren, YBOP, NoFap, ect).
Bring sie dazu, den Nutzern zu erzählen, wie auch sie dachten, sie wären
für immer süchtig und wie viel besser das Leben als Nicht-Nutzer ist.
Sobald du sie davon überzeugt hast, dass sie aufhören können, wird sich
ihr Verstand öffnen. Dann erkläre ihnen die Täuschung, die durch die
Entzugserscheinungen entsteht. Die \"Dopaminschübe\" geben ihnen nicht
nur keinen Auftrieb, sondern zerstören auch ihr Selbstvertrauen und
machen sie reizbar und müde.

Sie sollten jetzt bereit sein, dieses Buch selbst zu lesen und erwarten,
dass sie seitenweise Geschichten über unzuverlässige Erregung,
schwindende Penetration, PIED, PE usw. lesen werden. Erkläre ihnen, dass
dieser Ansatz völlig anders ist und die Hinweise auf Krankheiten nur
einen winzigen Bruchteil des Materials ausmachen.

## Soll ich es meinem Partner sagen?

Sollte ich meiner Frau, Freundin oder Partnerin von meiner Gewohnheit
erzählen? Die Absicht ist, dich beim Aufhören zu unterstützen. Hier
spielen mehrere Faktoren eine Rolle.

Wenn du bereits mit der Willenskraftmethode gescheitert bist und deinem
Partner oder deiner Partnerin davon erzählt hast, solltest du ihm oder
ihr von deinem neuen Ansatz erzählen und ihm oder ihr die Möglichkeit
geben, sich durch das Lesen des Buches zu informieren. Sie können dich
während der Entzugsphase unterstützen und motivieren und sind eine
starke Stütze, wenn das kleine Monster versucht, dir ein Bein zu
stellen.

Wenn du erst jetzt von der Existenz der Pornofalle erfährst und noch nie
versucht hast, aufzuhören, solltest du zunächst EasyPeasy selbst
benutzen. Wie bereits erwähnt, sollte das eine angenehme Erfahrung sein.
Wenn es dir jedoch schwerfällt, bitte um Hilfe. Wenn du deinem Partner
gegenüber offen und verletzlich bist, wird das eure Beziehung stärken.

Solange du die Flucht genießt und sie nicht durch Unentschlossenheit
erschwert wird, gibt es keinen Grund, es deinem Partner zu sagen. Wenn
es in der Vergangenheit kein Problem war, dann lass es sein. Sei aber
darauf vorbereitet, dass dein Partner sich wundern könnte, warum du
besser aussiehst, dich besser fühlst und 'bessere' Leistungen erbringst!

## Mein Partner lässt Pornos hinter sich

Pornografie ist ein perverser Zerstörer von Beziehungen und während man
sofort aufhören kann, braucht die Heilung Zeit. Viele Nutzer lassen
aufgrund irrationaler Überzeugungen, die aus ihrer Sucht entstanden
sind, ihre Wut an Partnern und geliebten Menschen aus. Diese
Verhaltensweisen äußern sich in Gaslighting (jemanden psychologisch
manipulieren, sodass er seine eigene Vernuft anzweifelt), Lügen und
manipulativen Verhaltensweisen. Das ist nicht bei allen Betroffenen der
Fall, kommt aber in späteren Stadien der Krankheit immer häufiger vor.
Auch wenn diese Verhaltensweisen von der zugrunde liegenden Pornosucht
herrühren, ist es wichtig, dass du dich über diese Verhaltensweisen
informierst und, falls sie erkannt werden, einen auf Sexualsucht
spezialisierten Therapeuten aufsuchst.

Wenn dein Partner in der Entzugsphase ist, gehe davon aus, dass er oder
sie leidet, egal ob er oder sie es ist oder nicht. Versuche nicht, sein
Leiden herunterzuspielen, indem du ihm sagst, dass es einfach ist,
aufzuhören, das kann er selbst. Sag ihnen stattdessen immer wieder, wie
stolz du bist, wie viel besser sie aussehen, wie viel schöner es ist,
mit ihnen zusammen zu sein und wie viel einfacher sie im Allgemeinen
sind. Es ist besonders wichtig, dies immer wieder zu tun, denn wenn ein
Nutzer einen Versuch unternimmt, aufzuhören, können ihm die Euphorie des
Versuchs und das Lob von ihm wichtigen Personen helfen. Sie neigen
jedoch dazu, es schnell zu vergessen, also lob sie immer wieder.

Weil sie nicht über Pornos reden, denkst du vielleicht, dass sie es
schon vergessen haben und nicht daran erinnert werden wollen. Bei der
Willenskraft-Methode ist normalerweise genau das Gegenteil der Fall, da
der Ex-Konsument dazu neigt, von nichts anderem besessen zu sein. Hab
also keine Angst, das Thema anzusprechen und lobe sie immer wieder, sie
werden dir schon sagen, wenn sie nicht erinnert werden wollen.

Bemühe dich, sie während der Entzugsphase zu entlasten und überlege dir,
wie du ihr Leben interessant und angenehm gestalten kannst. Auch für
Nichtkonsumenten, die die Sucht noch nie erlebt haben, kann dies eine
schwierige Zeit sein. Wenn ein Mitglied einer Gruppe reizbar ist, kann
das zu allgemeinem Unglück führen. Stell dich also darauf ein, dass der
Ex-Konsument seine Gereiztheit vielleicht an dir auslässt, aber räche
dich nicht, denn in dieser Zeit brauchen sie dein Lob und dein Mitgefühl
am meisten. Wenn du dich selbst gereizt fühlst, was verständlich ist,
versuche, es nicht an ihm auszulassen.

Einer der Tricks, die Süchtige anwenden, wenn sie versuchen, mit Hilfe
der Willenskraftmethode aufzuhören, besteht darin, Wutanfälle zu
bekommen, in der Hoffnung, dass ihr Partner oder ihre Freunde sagen:
*\"Ich kann es nicht ertragen, dich so leiden zu sehen. Um Himmels
willen, nimm doch einfach dein Gift.\"* Der Nutzer muss also nicht sein
Gesicht verlieren, er \"gibt nicht auf\", er wurde angewiesen. Wenn der
Ex-Konsument diese Masche abzieht, solltest du ihn auf keinen Fall zu
einem Rückfall ermutigen. Sage stattdessen: *\"Wenn es das ist, was
Pornos mit dir machen, bist du zum Glück bald frei. Wie schön, dass du
den Mut hattest, aufzugeben.\"*

Denke daran, dass es auf dem Weg der Genesung zwei heilende Parteien
gibt. Wenn dein Partner oder deine Partnerin mit Pornos aufhört, ist es
wichtig, dass du ein eigenes Unterstützungsnetzwerk,
Selbstfürsorgeroutinen und Grenzen hast. Dieser Prozess geht nicht von
heute auf morgen und erfordert Vertrauen, Kommunikation und
Verantwortlichkeit. Das Führen von Tagebüchern, das Entwickeln eigener
Leidenschaften und vor allem eine Therapie unterstützen diesen Prozess.

## Hilf mit, diesen Skandal zu beenden

Internetpornografie ist eine der Gefahren in einer freien Gesellschaft,
die sich auf die gut gemeinten Bemühungen um persönliche Freiheiten
stützt. Die Grundlage der Zivilisation, der Grund, warum die menschliche
Spezies so weit fortgeschritten ist, liegt darin, dass wir in der Lage
sind, unser Wissen und unsere Erfahrungen nicht nur einander, sondern
auch zukünftigen Generationen mitzuteilen. Selbst Tiere finden es
notwendig, ihre Nachkommen vor den Tücken des Lebens zu warnen.

Die Produzenten von Pornos tun dies nicht in gutem Glauben und in der
Überzeugung, dass sie der Menschheit helfen, vor allem jetzt, wo die
Sucht nach Internetpornos weithin untersucht wird. Vielleicht haben die
Menschen in der Anfangsphase wirklich geglaubt, dass Pornos die Menschen
über Intimität aufklären, aber die Behörden wissen, dass das ein
Trugschluss ist. Sieh dir eine beliebige Tube-Seite an, die heutzutage
keine Behauptungen über Erziehung aufstellt. Die einzigen Behauptungen,
die aufgestellt werden, beziehen sich auf den Schock, die Neuartigkeit
und die eskalierenden Qualitäten ihrer Produkte.

Die schiere Heuchelei ist unglaublich: Als Gesellschaft regen wir uns
über Mobbing in der Schule und die Objektivierung des menschlichen
Körpers auf. Verglichen mit Internetpornos sind diese Probleme nur
Pickel. Die Zahl der Süchtigen, die auf Kosten ihrer Gesundheit, Potenz,
Energie und Zeit viel Zeit mit imaginären und illusorischen
Pixelmenschen verbringen, steigt jedes Jahr in neue Höhen. Zehntausende
von Leben werden jedes Jahr ruiniert, weil sie süchtig werden. Die
Produzenten von Internetpornos machen keine Werbung in den gängigen
Publikationen - das haben sie auch nicht nötig, denn unser biologischer
Trieb führt uns zu den Schwellen ihrer gut bestückten Harems, in denen
sie kostenlose Proben verteilen wie der örtliche Drogendealer.
Heutzutage bieten die Tube-Websites weniger die Ware an, sondern
ermutigen die Besucher, Inhalte zu posten.

Wie schlau, dass Pornofirmen die 18+-Warnung auf der Startseite
anzeigen, um minderjährige Nutzer abzuschrecken - manche machen sich
nicht einmal die Mühe, das zu tun. Internetpornos betreffen jeden, egal
welchen Alters. *\"Wir haben dich vor der Gefahr gewarnt, es ist deine
Entscheidung\"*, lautet ihre Haltung. Ergreifen sie irgendwelche
Maßnahmen, um das Alter zu überprüfen? Nein, das würde ihre Kunden
abschrecken. Wenn eine Altersüberprüfung gesetzlich vorgeschrieben wird,
suchen sie sich natürlich einfach ein anderes Land, von dem aus sie
arbeiten. Oder werden sie eine \"Elite\" dafür bezahlen, darüber zu
schreiben, wie die Prohibition zu Alkoholschmuggel und der Entstehung
der Mafia geführt hat? Die Frage, warum die Aufhebung der Prohibition
nicht dazu geführt hat, dass die Zahl der alkoholbedingten Todesfälle
gesunken ist und dass die Strafverfolgungsbehörden das Wachstum der
Mafia nicht kontrollieren konnten, wird leider vergessen.

Wir können dies anders angehen, indem wir die junge Generation
aufklären. Wenn sie die Zigaretten- und Alkoholregale in
Lebensmittelläden umgehen können, können sie das auch mit Internetpornos
tun. Wir sehen bereits gesellschaftliche Veränderungen wie \"No Nut
November\" und \"Coomer\"-Memes, die zum Mainstream werden. Der Nutzer
hat genauso wenig die Wahl wie der Heroinsüchtige. Die Konsumenten
entscheiden sich nicht dafür, süchtig zu werden, sie werden in eine
subtile Falle gelockt. Hätten sie die Wahl, wären die einzigen
Konsumenten morgen früh Jugendliche, die gerade erst anfangen und
glauben, dass sie jederzeit aufhören können, wenn sie es wollen.

Warum die falschen Normen? Warum werden Heroinabhängige als Kriminelle
angesehen, können sich aber als Süchtige registrieren lassen und
erhalten Methadon und eine angemessene medizinische Behandlung, um davon
loszukommen? Versuch doch mal, dich als Pornosüchtiger anzumelden. Wenn
du deinen Arzt um Hilfe bittest, wird er dir entweder sagen: *\"Hör auf,
so viel zu konsumieren, versuch es in Maßen\"*, was, wie du bereits
weißt, nicht funktionieren wird, oder sie verschreiben dir Medikamente
gegen deine \"Depression\". Noch schlimmer ist der Ratschlag, dir einen
richtigen Partner zu suchen, ernsthaft? Wissen sie von Nutzern, die
Pornos besser finden und es hinter dem Rücken ihres Partners tun? Manche
Leute verstehen es einfach nicht.

Panikmache hilft den Nutzern nicht, aufzuhören, sondern macht es noch
schwieriger. Sie machen den Nutzern nur Angst, was dazu führt, dass sie
noch mehr schauen wollen. Außerdem verhindern sie nicht, dass Teenager süchtig
werden. Teenager wissen, dass Pornos ihre Libido töten, aber sie wissen
auch, dass ein einziger Blick nicht ausreicht. Weil die Gewohnheit so
weit verbreitet ist, werden die Teenager früher oder später durch
sozialen Druck oder Neugierde einen einzigen Besuch wagen. Da kostenlose
Pornos schreckliche Clips enthalten, ist es wahrscheinlich, dass sie
süchtig werden.

Warum lassen wir zu, dass dieser Skandal weitergeht? Warum führt unsere
Regierung keine richtige Kampagne durch? Warum sagt sie uns nicht, dass
Internetpornos eine Droge und ein tödliches Gift sind, dass sie dich
nicht entspannen oder dir Selbstvertrauen geben, sondern deine Nerven
zerstören und du nur einen Blick brauchst, um süchtig zu werden? Warum
können sie nicht eine Altersverifizierung durchsetzen, indem sie eine
registrierte Kreditkarte verlangen, vielleicht bei einer dritten Partei?
H. G. Wells Text *\"Die Zeitmaschine\" (original: The Time Machine)*
beschreibt einen Vorfall in der fernen Zukunft, bei dem ein Mann in
einen Fluss fällt. Seine Begleiter sitzen nur wie Vieh am Ufer und
nehmen die Verzweiflungsschreie nicht wahr. Unmenschlich und verstörend,
genau wie die allgemeine Apathie der Gesellschaft gegenüber der
Pornokrise.

Es weht ein frischer Wind in der Gesellschaft. Ein Schneeball hat
begonnen, den Berg hinunterzurollen, und ich hoffe, dass dieses Buch
dazu beitragen wird, ihn in eine Lawine zu verwandeln. Auch du kannst
helfen, indem du die Botschaft verbreitest.

## Letzte Warnung

Jetzt kannst du den Rest deines Lebens als glücklicher Nichtnutzer
genießen. Um das sicherzustellen, musst du diese einfachen Anweisungen
befolgen.

1.  Bewahre diese Seite in deinen Lesezeichen auf und beziehe dich
    darauf, so oft du willst.

2.  Wenn du jemals anfängst, einen anderen Nutzer zu beneiden, mach dir
    klar, dass er dich beneiden wird. Du bist nicht benachteiligt. Sie
    sind es.

3.  Erinnere dich daran, dass es dir keinen Spaß gemacht hat, ein Nutzer
    zu sein. Deshalb hast du aufgehört. Du genießt es, ein Nicht-Nutzer
    zu sein.

4.  Denke daran, dass es 'nur einen Blick' nicht gibt.

5.  Zweifle nie an deiner Entscheidung, nie wieder Pornos zu schauen. Du
    weißt, dass es die richtige Entscheidung ist.

6.  Wenn du Schwierigkeiten hast, suche dir einen Therapeuten, der sich
    mit Internetpornos auskennt, und kontaktiere ihn. Du kannst Listen
    davon online finden.
