# Die Anweisungen

1.  Befolge alle Anweisungen.

2.  Sei unvoreingenommen.

3.  Beginne mit einem Gefühl der Begeisterung.

4.  Ignoriere alle Ratschläge und Einflüsse, die im Widerspruch zu
    EASYPEASY stehen.

5.  Widerstehe jedem Versprechen einer vorübergehenden Lösung.

6.  Mach dir klar, was du willst: Pornos bieten kein echtes Vergnügen
    oder eine Stütze und du bringst kein Opfer. Es gibt nichts
    aufzugeben und keinen Grund, sich benachteiligt zu fühlen.

7.  Warte nicht mit dem Aufhören, tu es jetzt!

8.  Triff die Entscheidung, nie wieder zuzuschauen, und stelle sie nicht
    in Frage.

9.  Denke daran, dass es 'nur einen Blick' nicht gibt.

10. Sieh dir nie wieder Pornos an.

## Affirmationen

-   Ich bin frei von der Sklaverei der Pornos.

-   Es ist leicht, meine Gedanken an Pornos zu ignorieren.

-   Bye bye Gedanken, bye bye Verlangen. Oh, da geht mein Verlangen.

-   Ich fokussiere mein Unterbewusstsein, um die Pornosucht zu
    überwinden.

-   Porno raubt mir Zeit, Energie und Lebenskraft.

-   Die Pornosucht zu besiegen wird von Tag zu Tag und in jeder Hinsicht
    exponentiell leichter.

-   Ich genieße und schätze meinen pornofreien, starken, glücklichen,
    leichten und unbeschwerten Lebensstil.

-   Wenn ich zurückblicke und über meine Fortschritte nachdenke, erfüllt
    mich das mit großer Freude und Stolz auf mich selbst.

-   Jedes Mal, wenn ich andere Pornokonsumenten sehe, werde ich noch
    motivierter, selbst diese Kette zu durchbrechen.

-   All diese angesammelte Energie heilt meinen Körper und meinen Geist.
    Dann kann ich produktiver und anspruchsvoller an meinen Werten und
    Zielen arbeiten.

-   Mein Gehirn wird wieder in die richtige Form gebracht und trainiert,
    indem ich das tue, was ich vorher *nicht* getan habe.

-   Jetzt wird die ganze angesammelte Willenskraft genutzt, um mit den
    leichten Belastungen des Lebens umzugehen.

-   Großartig, ich bin frei und nicht länger ein Sklave!
