# Das Ende des Buches

Hallo noch mal, vielen Dank, dass du dieses Buch gelesen hast. Freiheit
ist unglaublich, nicht wahr! Das Originalbuch des Hackautors hat mein
Leben buchstäblich verändert und seitdem läuft es wie am Schnürchen.
Natürlich danke ich auch dem verstorbenen Allen Carr, der unzähligen
Menschen geholfen hat, der Suchtfalle zu entkommen.

Wenn dieses Hackbook dir geholfen hat, kannst du ein paar Dinge tun, um
zu helfen:

Empfehle EasyPeasy.

:   Freunde lassen ihre Freunde nicht mit der Willenskraftmethode
    leiden. Wenn du einen Ratgeber, einen Beitrag oder jemanden im
    Internet siehst, der Willenskraft erwähnt, verlinke das Buch und
    frage, warum sie nicht EasyPeasy benutzen. Es braucht nur einen
    Link, um jemanden vor der bösen Falle zu retten. Wenn du ein Kind
    bist, dann versuche vielleicht, Pornos in dein Aufklärungsprogramm
    aufzunehmen. Anstatt ein \"basierter und rotgefärbter Fortnite
    Memelord\" zu sein, könntest du tatsächlich etwas tun.

Verbessere das Buch.

:   EasyPeasy ist Open Source und in LaTeX geschrieben. Wenn dir eine
    Verbesserung auffällt, gehe zu Gitlab und reiche deine Vorschläge
    ein. Ich würde auch gerne deine Erfahrungen auf r/pmohackbook hören,
    aber lösche stattdessen lieber gleich reddit, wenn du einen Account
    hast. Um bei meinem vorherigen Punkt zu bleiben: Lösche alle
    sozialen Medien, denn sie sind eine Droge, die deine Aufmerksamkeit
    raubt. Ohne sie geht es dir wirklich besser und es ist leicht, mit
    ihnen aufzuhören. EasyWay hat sogar ein Buch darüber, das ich
    allerdings nicht gelesen habe. Verfolge zumindest, wie viel Zeit du
    mit deinen Geräten verbringst.

Vor COVID war ich in Neuseeland. Wusstest du, dass die beste Art, einem
Jetlag vorzubeugen, darin besteht, sechzehn Stunden vor dem Aufwachen zu
fasten und möglichst wenig Wasser zu trinken? Das gilt nicht nur für den
Jetlag, sondern auch, wenn dein Tagesrhythmus aus irgendeinem Grund aus
dem Gleichgewicht geraten ist, z. B. weil du lange aufgeblieben bist und
dir Pornos angeschaut hast, kann das helfen.

Wenn du schon eine schlechte Angewohnheit loswirst, warum nimmst du
nicht stattdessen eine gesunde auf?

Meditation ist Liegestütze für dein Gehirn. Achtsamkeit ist vielleicht
eines der wichtigsten Werkzeuge, die man in der heutigen Zeit
kultivieren sollte, und sie ist eine praktikable Fähigkeit. Es ist
wichtig, die Lehren des Buddha vom Buddhismus zu trennen - der Meister
Lin Chi aus dem neunten Jahrhundert soll gesagt haben: \"Wenn du den
Buddha auf der Straße triffst, töte ihn.\" Außerdem hast du gerade etwas
Zeit in deinem Tag frei, also sollte es sich gut einfügen. Ich empfehle
die App *Waking Up*, die du unter dem unten stehenden Link einen Monat
lang kostenlos nutzen kannst. Sam Harris ist so ein toller Kerl, dass du
ein kostenloses Jahr anfordern kannst, wenn du es dir nicht leisten
kannst.

Die Befreiung von Pornografie wird wahrscheinlich Fragen zu Beziehungen
aufwerfen. Wenn du Probleme bei der Partnersuche oder in einer Beziehung
hast, empfehle ich **unbedingt** das Buch *Models* von Mark Manson, in
dem es um Bedürftigkeit, Verletzlichkeit und ihre Auswirkungen geht. Ich
würde es sogar jedem empfehlen. Ich bin auch froh, dass ich nicht in die
Pick-up-Artist- oder Incel-Falle getappt bin, denn das ist wirklich
nicht gesund; referenziere mich nicht mit @!

Du solltest auch anfangen zu trainieren, mein Lieblingsbuch zu diesem
Thema ist *The Leangains Method* von Martin Berkhan. Egal ob Mann oder
Frau, egal welchen Alters, Gewichtheben ist so ziemlich der beste Weg,
um gesund und fit zu bleiben. Ich kann gar nicht genug betonen, dass es
verdammt gut ist, sich gesunde Gewohnheiten anzueignen, statt sich
hinzusetzen und zu konsumieren. Du kannst entweder deine Laster
kontrollieren oder dich von ihnen kontrollieren lassen. Ein Zitat aus
[*Exiting Modernity*](https://www.meta-nomad.net/exiting-modernity/) --

*\"Zu spät ist kein Alter oder eine Zeit; zu spät ist, wenn Müdigkeit
zur Unterwerfung führt und du dich selbst völlig vergisst, ein
potenzieller Mensch, der sich in Nichts auflöst\"*

Letztlich sind das alles nur Vorschläge. Was würdest du gerne erreichen?
Du bist frei von dieser schrecklichen Falle und kannst dieses Geschenk
nutzen, wie du willst.

Die pornografische Hydra ist außer Kontrolle geraten. Obwohl die
Gesellschaft nur langsam reagiert, bin ich optimistisch, denn jede
Person, die entkommt, beschleunigt den Schneeball. Denke immer daran,
was du erreichen kannst, wenn du deine Energie bündelst und dich für
lokale Themen einsetzt, die dir am Herzen liegen, wie Nachhaltigkeit,
Sexualerziehung und andere. Beschwere dich nie, sondern sei proaktiv und
frage dich, wie du die Welt um dich herum beeinflussen kannst. Erinnere
dich daran, dass eine Revolution von oben nach unten noch nie
funktioniert hat: Veränderung beginnt bei dir selbst.

Prost Kumpel,\
Hackauthor²
