# Ressourcen {-}

[Meditationen eines Pornosüchtigen](../resources/meditations.pdf) - Guillaco

[EasyPeasy Aussagen Checkliste](https://pastebin.com/dybv6qkD) - SWATxKATS

[9 Minuten Meditation](https://www.youtube.com/watch?v=tw7XBKhZJh4) - Sam Harris

[Kostenloser einmonatiger Waking Up Meditationskurs](https://share.wakingup.com/a13290) - Sam Harris

[Ausstieg aus der Moderne](https://meta-nomad.net/exiting-modernity) - Meta Nomad

[Brief, den ich an Schulen schicke](../resources/principal.pdf)

[Freiheit für immer (PMO Hacknotes)](https://sites.google.com/view/freeforever/home)

[Warum du rückfällig wirst - u/Different_Guide_5205](https://old.reddit.com/r/pmohackbook/comments/mynwjl/why_youre_relapsing/)

[Gegen die Angst - u/Different_Guide_5205](https://old.reddit.com/r/pmohackbook/comments/n5027n/countering_fear/)

## REBT Bewältigungssätze {-}

- *"Ich kann mit PMO aufhören, auch wenn es 'schwer' zu sein scheint. Es ist nicht zu schwer, und egal, wie viel Mühe es kostet, es ist es wert!"*

- *"Wenn ich mein starkes Verlangen nach PMO ignoriere und ihm nicht nachgebe, wird es mir immer leichter fallen, ihm zu widerstehen."*

- *"Ich kann mich selbst vollständig und bedingungslos akzeptieren - ja, sogar mit all meinen Fehlern und Schwächen "*

- *"PMO scheint meine Probleme schnell zu "heilen", macht sie aber nur noch schlimmer."*

- *"Manchmal würde ich meine Probleme gerne in PMO ertränken, aber das ist kein Grund, es zu tun.

- *"Am unangenehmsten ist es, wenn ich nicht das bekomme, was ich wirklich will. Aber es ist nicht furchtbar oder schrecklich, solange ich mich nicht dafür entscheide, es zu glauben, und ich mich dafür entscheide, etwas Realistischeres und Hilfreicheres zu glauben. "*

- *"Ich werde ungerechte Behandlung nie mögen, aber ich kann sie verdammt gut ertragen und vielleicht Pläne schmieden, um sie zu verhindern.

- *"Egal, wie oft ich bei dieser wichtigen Aufgabe versage, mein Versagen macht mich nicht zu einer inkompetenten Laus. Es macht mich nur zu einer Person, die zu diesem Zeitpunkt vielleicht inkompetent gehandelt hat.

- *"Ich brauche das, was ich will, nicht unbedingt, aber ich kann trotzdem einigermaßen glücklich sein, wenn auch nicht so glücklich, wie wenn ich es nicht bekomme."*

- *"Ich möchte bei meiner Arbeit am liebsten hervorragend sein, aber das muss ich nicht. Schade, wenn ich es nicht bin, aber das macht mich nicht minderwertig. Ich kann immer versuchen, es besser zu machen, ohne es besser machen zu müssen. "*

- *"Viele Dinge können dazu beitragen, dass ich traurig und enttäuscht bin, aber wenn ich verlange und befehle, dass es diese Dinge nicht geben darf, dann mache ich mich selbst panisch, deprimiert und wütend. "*

- *"Ja, ich habe oft versäumt, das zu tun, was ich versprochen habe, aber das heißt nicht, dass ich dieses Versprechen nicht einhalten kann oder will."*

- *"Ich hasse es wie die Hölle, ängstlich und deprimiert zu sein, aber ich muss diese Gefühle nicht sofort mit PMO auflösen. Wenn ich PMO mache, geht es mir vorübergehend besser mit meinen Problemen, aber ich werde nicht besser. Auf lange Sicht macht PMO sie nur noch schlimmer."*

- *"Menschen ärgern mich nicht, indem sie mich schlecht behandeln. Ich entscheide mich stur dafür, mich über ihre schlechte Behandlung zu ärgern, indem ich verlange und befehle, dass sie sich besser verhalten. "*

## Die Kombination von EasyPeasy mit Jack Trimpeys Addictive Voice Recognition Technique (AVRT) {-}

*Credit to az#8773 on Discord*

Dies ist für Menschen, die Schwierigkeiten haben, Allen Carrs Easyway-Methode anzuwenden, um sich von einer Sucht zu erholen, obwohl die Gehirnwäsche entfernt wurde. Ich gehe davon aus, dass jeder, der das hier liest, eines der Bücher von Allen Carr gelesen und seine Easyway-Methode (auch bekannt als Easypeasy) verstanden hat. Falls nicht, empfehle ich das dringend. Es wäre auch hilfreich, wenn du "Rational Recovery" von Jack Trimpey lesen würdest. Wenn du es nicht gelesen hast, ist das kein Problem, denn ich werde hier nur die Grundlagen behandeln, aber ich empfehle dir, es trotzdem zu lesen, denn es geht viel mehr ins Detail als ich. Dieser Artikel ist nicht auf eine bestimmte Sucht ausgerichtet und kann daher auf jede Sucht angewendet werden. Der Zweck dieses Textes ist es, Easyway mit einer anderen erfolgreichen Suchtmethode namens "Addictive Voice Recognition Technique" (AVRT) zu vergleichen und beide miteinander zu kombinieren. Obwohl ich glaube, dass Easyway allen anderen Methoden zur Suchtbewältigung bei weitem überlegen ist, glaube ich, dass das Verständnis von AVRT auch das fehlende Glied für so viele sein könnte, die mit Easyway scheitern, obwohl sie das große Monster getötet haben.

Es gibt viele konkurrierende Methoden zur Überwindung der Sucht, jede mit unterschiedlichen Erfolgsquoten. Ich werde keine von ihnen erwähnen, weil die meisten davon Zeitverschwendung sind und ich mich so kurz wie möglich fassen möchte. Die einzigen Methoden, über die ich schreiben werde, sind Allen Carrs Easyway und Jack Trimpeys (Gründer von Rational Recovery) AVRT. Beide Methoden haben extrem hohe Erfolgsquoten, aber jede zielt auf eine andere Sache ab. Easyway und AVRT ähneln sich darin, dass Easyway die Sucht in das "kleine Monster" und das "große Monster" unterteilt und AVRT deinen Verstand in die "süchtige Stimme" (auch bekannt als das Biest) und "dich". Die süchtige Stimme und das kleine Monster sind ein und dasselbe, und das große Monster (auch bekannt als Gehirnwäsche) ist das Glaubenssystem, das dich glauben lässt, dass deine Sucht dir eine Art Vorteil oder Krücke verschafft. Easyway konzentriert sich auf die Beseitigung des großen Monsters ohne Rücksicht auf das kleine Monster, während AVRT sich auf das kleine Monster ohne Rücksicht auf das große Monster konzentriert. Während Easyway die psychologische Sucht zerstört, lehrt dich AVRT, die körperliche Sucht zu erkennen, die sich als dich ausgibt, und dich von ihr zu trennen. Ich finde es interessant, dass Easyway und AVRT beide sehr hohe Erfolgsquoten haben, obwohl sie sich auf das Gegenteil konzentrieren.

Obwohl ich der Meinung bin, dass Easyway allen anderen Methoden zur Suchtentwöhnung weit überlegen ist und ich es vor allen anderen Methoden empfehle, kann ich zwei kleine Schwachstellen ausmachen. Erstens finde ich, dass er das kleine Monster unterschätzt. Ich möchte hier keine persönlichen Anekdoten erzählen, aber aus meinen Erfahrungen und den Erfahrungen anderer scheint es, dass einige von uns bei Easyway scheitern, und zwar nicht, weil wir das große Monster nicht vollständig beseitigt haben (obwohl das durchaus passieren kann), sondern weil wir das kleine Monster unterschätzt haben. Das kleine Monster ist für die meisten Menschen kein Problem, was die hohen Erfolgsquoten von Easyway erklärt, aber für andere, mich eingeschlossen, kann es ein Problem sein. Das zweite Problem ist, dass Easyway behauptet, dass alle Misserfolge darauf zurückzuführen sind, dass man entweder die Anweisungen nicht befolgt oder das große Monster nicht entfernt hat.

Der Grundgedanke von Easyway ist folgender. Die Sucht hat zwei Komponenten: die körperliche Sucht nach Dopamin und die psychologische Sucht, die aus der Überzeugung (Gehirnwäsche) besteht, dass deine Sucht dir eine Art Vergnügen oder eine Krücke verschafft. Diese beiden Komponenten werden das kleine und das große Monster genannt. Laut Easyway ist das kleine Monster nichts weiter als ein leeres, leicht unsicheres Gefühl, das kaum wahrnehmbar ist. Sobald du das große Monster tötest, indem du die Gehirnwäsche rückgängig machst, indem du lernst, dass deine Sucht keinen Nutzen hat und dass jedes vermeintliche Vergnügen oder jede Krücke nur eine Illusion ist, und - was genauso wichtig ist - dass du nichts von einem Leben ohne deine Sucht zu befürchten hast, verschwindet das Verlangen. Das Verlangen rührt von deiner Angst her, dass das Leben ohne deine kleine Krücke unerträglich wäre, was dazu führt, dass du am Aufhören zweifelst, was das Verlangen ist. Du überwindest die Angst, indem du dir bewusst machst, wie viel angenehmer dein Leben ohne deine Sucht sein wird, und du behältst dieses Hochgefühl bei.

Ich glaube zwar, dass dies die beste Methode ist, um sich von einer Sucht zu erholen, aber sie legt keinen Wert auf das kleine Monster, denn theoretisch wird das hilflose, machtlose kleine Monster von selbst verkümmern und sterben, wenn man sich erst einmal um das große Monster gekümmert hat, und es ist sowieso kaum wahrnehmbar, also wen kümmert es. Das kleine Monster mag für viele Menschen unbedeutend sein, aber aus meinen eigenen Erfahrungen und denen anderer scheint das nicht immer der Fall zu sein. Wenn Menschen mit Easyway scheitern, gibt es laut Easyway nur 2 mögliche Gründe: Entweder hast du die Anweisungen nicht richtig befolgt oder du hast es versäumt, das große Monster zu entfernen. Ich glaube, dass das nachteilig ist und werde später erklären, warum.

Die Addictive Voice Recognition Technique (AVRT) trennt das Gehirn in zwei Teile: das untere Gehirn (limbisches System), in dem sich deine Sucht befindet, und das höhere Gehirn (präfrontaler Cortex), in dem du (oder zumindest deine Gedanken und dein Ego) sitzt. Jack Trimpey nennt die süchtige Stimme die Bestie, weil sie im tierischen Teil unseres Gehirns sitzt und nur eines weiß: "ICH WILL ES UND ICH WILL ES JETZT". Ich selbst finde es nicht hilfreich, sie als Bestie zu bezeichnen, aber es ist wohl besser, als zu glauben, sie sei du selbst. Die süchtige Stimme (AV, kleines Monster) wird deine Gedankenstimme kapern und sie gegen dich verwenden, um dich dazu zu bringen, deiner Sucht nachzugeben. Sie muss das tun, weil sie deine motorischen Funktionen nicht selbst kontrollieren kann. Du kannst das jetzt ausprobieren: Hebe deine Hand vor dein Gesicht und wackle mit den Fingern. Bitte jetzt deine Sucht, das Gleiche zu tun. Das kann sie nicht. Das bedeutet, dass du letztendlich die Kontrolle darüber hast.

![Das "Zwei-Gehirn-Modell" der Sucht] (images/avrt.png)

Das AV kapert nicht nur deine Gedankenstimme, sondern versteckt sich auch hinter dem Pronomen "Ich". Sie sagt: "Ich könnte X jetzt wirklich gut gebrauchen", "Ich vermisse es wirklich, X zu tun", "Wäre es nicht schön, X jetzt zu tun, schließlich habe ich es nach dem heutigen Tag verdient." AVRT betont die Tatsache, dass du nicht deine süchtige Stimme bist, sondern nur denkst, dass du es bist. Wenn du die AV als "nicht du" erkennst und Nein zu ihr sagst, lässt sie das "Ich" fallen und beginnt, "du", "uns" oder "wir" zu verwenden. Das ist der Beweis dafür, dass es nicht du bist.

Wenn du "Nein" zu deinem AV sagst, passiert genau das:
Aus "Ich könnte X jetzt wirklich gut gebrauchen" wird "Ach komm, du könntest X jetzt wirklich gut gebrauchen und du weißt es". Aus "Ich vermisse X wirklich" wird "Ach komm, du vermisst X wirklich, merkst du das nicht?" Aus "Wäre es nicht schön, jetzt X zu tun, schließlich habe ich es nach dem heutigen Tag verdient?" wird "Wir haben es verdient, jetzt X zu tun, nach allem, was wir durchgemacht haben, wie kannst du uns das verweigern?"

An dieser Stelle muss ich etwas klarstellen. Dies ist nicht das "Tauziehen", von dem Allen Carr spricht. Das "Tauziehen" ist eine kognitive Dissonanz, bei der du zwei oder mehr widersprüchliche Glaubenssysteme hast und die entsteht, wenn du das große Monster nicht tötest. "Ich will X wirklich nicht tun, weil es sich negativ auf mich auswirkt, aber es macht mich auch X, also will ich es tun". Das ist das Tauziehen und das Werk des großen Monsters. Sobald das große Monster durch die Beseitigung der Gehirnwäsche tot ist, kommen die einzigen Stimmen, die dir sagen, dass du deine Sucht ausleben sollst, von dem kleinen Monster (dem AV). Da das AV das Pronomen "ich" verwendet, ist es möglich, das AV mit dem großen Monster zu verwechseln.

Es ist auch wichtig, darauf hinzuweisen, dass der AV ein großer Lügner ist. Sein einziges Interesse ist es, Dopamin zu bekommen, koste es, was es wolle. Dein AV wird versuchen, dich davon zu überzeugen, dich in potenziell tödliche Situationen zu begeben, wenn du dadurch einen Schuss bekommst.

Vorhin sagte ich: "Wenn Menschen mit Easyway scheitern, gibt es laut Easyway nur 2 mögliche Gründe: Entweder hast du die Anweisungen nicht richtig befolgt oder du hast es versäumt, das große Monster zu entfernen. Ich glaube, dass das nachteilig ist und werde später erklären, warum." Ich glaube, dass dies schädlich ist, weil das Nicht-Erkennen der AV bei mir und anderen, die Easyway benutzt haben, dazu geführt hat, dass wir fälschlicherweise glaubten, das große Monster nicht vollständig getötet zu haben, so dass wir das Buch erneut gelesen haben, um zu versuchen, die Gehirnwäsche erneut zu töten, obwohl wir es bereits getan haben. Wenn du die AV nicht erkennst und glaubst, dass "wenn du mit Easyway gescheitert bist, bedeutet das, dass du das große Monster nicht getötet hast", wirst du deine Bemühungen erneut auf das große Monster richten, obwohl es bereits besiegt ist. Du könntest in einen Kreislauf geraten, in dem du die Bücher von Allen Carr immer wieder liest, eine Weile durchhältst und dann immer wieder rückfällig wirst.

Wenn der AV etwas sagt wie "Ich will jetzt X tun, weil es mich zu X macht", denkst du vielleicht: "Aber ich weiß, dass das nicht stimmt, warum glaube ich es dann noch? Habe ich es versäumt, die Gehirnwäsche vollständig rückgängig zu machen". Die Wahrheit ist, dass du die Gehirnwäsche entfernt hast, was sich darin zeigt, dass du es besser weißt, als das, was dein AV dir erzählt. Du denkst nur, dass das AV du bist, weil es das Pronomen "ich" benutzt. Wenn du das AV erkennst und es zwingst, sich zu offenbaren, indem es das "ich" durch "du", "wir" oder "uns" ersetzt, sollte dir klar werden, dass es nicht das große Monster ist, sondern das kleine Monster. Wenn es tatsächlich das große Monster wäre, würde es nicht das "I" für "du", "wir" oder "uns" ersetzen.

Wenn der AV sagt: "Bitte, können wir X nur noch einmal machen, um der alten Zeiten willen, nur noch einmal?" und du "Nein" sagst, wirst du vielleicht eine emotionale Reaktion spüren. Du fühlst vielleicht Angst oder Traurigkeit. Es ist sehr wichtig zu erkennen, dass dieses Gefühl nicht von dir kommt, sondern von ihm. Wenn du nicht in der Lage bist, das AV zu erkennen, wirst du denken, dass dieses Gefühl von dir kommt und eher dazu neigen, nachzugeben. Erkenne die AV und die Tatsache, dass die Emotionen, die von ihr ausgehen, nicht von dir kommen, und freue dich dann darüber.

Wenn du diese beiden Methoden zusammen anwendest (falls nötig, denn nicht alle Menschen scheinen ein Problem mit dem kleinen Monster zu haben) und ein Gefühl der Freude und des Hochgefühls aufrechterhältst, wann immer du das AV erkennst, ist der Erfolg dein.
