# Metoda ușoară

Obiectivul acestei cărți este de a vă direcționa către o nouă modalitate de a gandi. Spre deosebire de metoda obișnuită de oprire - prin care porniți cu sentimentul de a escalada Muntele Everest și petreceți următoarele câteva săptămâni cu pofte și senzație de lipsuri - începeți imediat cu un sentiment de exaltare, ca și cum v-ați fi vindecat de o boală teribilă. Din acel moment, cu cât veți merge mai departe în viață, cu atât mai mult vă veți uita la această perioadă de timp și vă veți întreba cum de ați folosit vreodată porno în primul rând. Îi veți privi pe ceilalți utilizatori de pornografie cu milă, spre deosebire de invidie.

Cu condiția să nu fiți o persoană care nu a devenit niciodată dependentă (citind pentru partenerul dvs. semnificativ) sau care a renunțat (sau se află în zilele de post ale unei "diete porno"), este esențial să continuați să consumați până când ați terminat complet cartea. Acest lucru poate părea o contradicție, iar această instrucțiune de a continua să vă masturbați la pornografie provoacă mai multe obiecții decât oricare alta, dar pe măsură ce citiți mai departe, dorința de a folosi pornografia va fi redusă treptat. ** Luați în serios această instrucțiune: Încercarea de a renunța mai devreme nu vă va fi benefică.**. 

Mulți nu termină cartea pentru că simt că trebuie să renunțe la ceva, unii chiar citesc în mod deliberat doar un rând pe zi pentru a amâna ziua in care se vor opri. Privește lucrurile astfel: ce ai de pierdut? Dacă nu te oprești la sfârșitul cărții, nu vei fi mai rău decât ești acum. Este, prin definiție, un Pariu Pascal, un pariu făcut atunci când nu ai nimic de pierdut și șanse mari de câștiguri mari.

Apropo, dacă nu ați vizionat porno timp de câteva zile sau săptămâni, dar nu sunteți sigur dacă sunteți un utilizator porno, un fost utilizator sau un non-utilizator, atunci nu folosiți porno pentru a vă masturba în timp ce citiți. De fapt, sunteți deja un non-utilizator, dar trebuie să vă lăsăm creierul să vă ajungă din urmă cu corpul. Până la sfârșitul cărții, veți fi un non-utilizator fericit. EasyPeasy este complet opusă metodei normale, în care se enumeră dezavantajele considerabile ale pornografiei și se spune:  
*"Dacă pot rezista suficient de mult timp fără porno, în cele din urmă dorința va dispărea și mă voi putea bucura din nou de viață, fără sclavie. "*.  
Acesta este modul logic de a proceda, mii de persoane oprindu-se în fiecare zi folosind această metodă. Cu toate acestea, este foarte dificil să reușești din următoarele motive: 

**Stoparea PMO nu este adevărata problemă.**
De fiecare dată când îți termini sesiunea, înseamnă că ai încetat să o folosești. S-ar putea să aveți motive puternice în prima zi a dietei porno o dată la patru pentru a spune *"Nu vreau să mai folosesc porno, nici măcar să mă masturbez. "* Toți utilizatorii fac acest lucru, iar motivele lor sunt mai puternice decât vă puteți imagina. Adevărata problemă este ziua a doua, zece sau zece-mii, unde într-un moment de slăbiciune vei avea "doar o privire", vei dori alta și, dintr-o dată, vei fi din nou dependent.

**Conștientizarea riscurilor pentru sănătate generează mai multă teamă, ceea ce face mai dificilă oprirea.
Spuneți-i unui utilizator că îi distruge virilitatea și primul lucru pe care îl va face va fi să caute ceva care să-i crească dopamina: o țigară, alcool sau chiar să deschidă browserul pentru a căuta pornografie.

**Toate motivele pentru a te opri fac oprirea mai dificilă.**
Acest lucru se datorează din două motive. În primul rând, suntem forțați în mod continuu să renunțăm la "micul nostru prieten" sau la o recuzită, viciu sau plăcere (indiferent de modul în care o percepe utilizatorul). În al doilea rând, ele creează un "orb". Nu ne masturbăm din motivele pentru care ar trebui să ne oprim. Adevărata întrebare este: de ce vrem sau avem nevoie să o facem?

Cu EasyPeasy, uităm (inițial) motivele pentru care am dori să ne oprim, ne confruntăm cu problema porno și ne punem următoarele întrebări:

1.  Ce face pornografia pentru mine?

2.  Îmi place de fapt?

3.  Chiar trebuie să trec prin viață sabotându-mi mintea și corpul?

Frumosul adevăr este că *tot pornografia* nu face absolut nimic pentru tine, în nici un fel. Permiteți-mi să fiu foarte clar, nu este vorba de faptul că dezavantajele de a fi un utilizator depășesc avantajele, ci că există ***zero*** avantaje în a privi pornografia.

Majoritatea utilizatorilor consideră că este necesar să raționalizeze folositul pornografiei, dar motivele pe care le găsesc sunt toate falsuri și iluzii.

În primul rând, vom elimina aceste falsuri și iluzii. De fapt, vă veți da seama în curând că nu este nimic la care să renunțați. Nu numai atât, dar există câștiguri minunate și pozitive din a fi un non-PMOer, bunăstarea și fericirea fiind doar două dintre aceste câștiguri. Odată ce iluziile că viața nu va fi niciodată la fel de plăcută fără porno este eliminată - realizând că nu numai că viața este la fel de plăcută fără ea, ci infinit mai mult - și odată ce sentimentele de a fi privat sau de a pierde sunt eradicate, vom reveni pentru a reconsidera bunăstarea și fericirea sporită - și zecile de alte motive pentru a renunța la porno. Aceste realizări vor deveni ajutoare pozitive pentru a vă ajuta să obțineți ceea ce vă doriți cu adevărat: să vă bucurați de viața voastră liberă de sclavia dependenței de pornografie!
