# De ce este complicat sa te opresti din a te uita la porno?

Toti utilizatorii se simt posedati de ceva malefic. La inceput ne gandim ca vom renunta la obicei, dar nu incepand de azi, poate maine. Pe parcurs ajungem sa credem ca nu avem suficienta vointa sa ne oprim, sau ca este ceva inerent bun la pornofrafie si ca avem nevoie de acel ceva ca sa putem sa ne bucuram de viata. Dependenta de pornografie este comparabila cu a incerca sa urci un perete alunecos. De indata ce ajungi aproape de varf, vezi calea de scapare, dar imediat cum starea ta de spirit se schimba, aluneci si ajungi in locul de unde ai inceput. Deschizi browserul si masturbandu-te te simti ingrozitor. 

Intreaba un utilizator: *"Daca ai putea sa te intorci la momentul cand te-ai apucat de pornografie cu informatia de acum, ai mai incepe?"*

*"Niciodata!"* ar fi raspunsul.

Intreaba un utilizator care se complace in comportamentul lui si apara utilizarea pornografiei pe internet, necrezand ca poate fi daunatoare, daca el si-ar incuraja copiii sa foloseasca pornografia. 


*"In niciun caz!"* ar fi rapsunsul.

Pornografia este o enigma. Asa cum am discutat mai devreme, problema nu este sa explici cuiva de ce este usor sa te lasi de PMO, problema estes sa-i explici de ce este dificil. Problema este sa-i explici de ce cineva continua sa se uite la porno *dupa* ce a aflat despre problemele de sanatate asociate cu utilizatul. Parte a motivului pentru care incepem sa ne uitam la porno este ca alte zeci de mii de persoane o fac deja, desi discutand cu aceste persoane ne dam seama ca ei traiesc viata constant in viteza a doua. Noi nu-i credem asa ca muncim catre a deveni si noi dependenti, pana la urma stim din societate ca privitul pornografiei este "educativ" si asociat cu libertatea sexuala. Odata ajunsi dependenti ne petrecem restul vietii incercand sa ne lasam de obicei, gandindu-ne ca suntem singuri in aceasta calatorie. 

De asemenea, petrecem o mare parte a timpului nostru simtindu-ne mizerabili si fara speranta. "Educandu-ne" cu stimuli puternici, ajungem sa tanjim dupa acele poze sau filmulete reci, chiar si atunci cand suntem intr-o relatie cu cineva care si doreste afectiune. Prin poftele constante induse de caderea si suplimentarea dopaminei de catre PMO, ne condamnam la o viata de izolare, iritabilitate, stres, furie si disfunctie sexuala. Prin absenta celor mai bune parti ale sexului cum ar fi conexiunea si comunicarea, ne simtim mizerabili si vinovati.

Adevarul este ca si citiul depre efectele daunatoare ale pornografiei asupra creierului nostru induce senitmentele de nervozitate si lipsa de speranta. Ce fel de hobby mai este si asta daca atunci cand il faci ti-ai dori sa nu-l mai faci, dar atunci cand nu-l faci tot ce-ti doresti este o noua "sesiune". Utilizatorii se dispretuiesc de fiecare data cand folosesc pornografia pe la spatele partenerului, cand nu pot sa faca fata unui antrenament din cauza letargiei produsa de PMO, dar si de fiecare data cand citesc despre efectele pornogafiei asupra corpului. Mai rau decat toate acestea este faptul ca utilizatorul nu primeste nimic in schimbul unei vieti torturate, poate doar niste umbre negre in spatele constiintei.  

Poate te gandesti ca deja stii totul despre ce am discutat mai sus, dar cu toate astea, odata ce esti prins in capcana este foarte greu sa te opresti. Dar de ce sa fie greu? Unii spun ca este din cauza simptomelor grele din perioada sevrajului, dar asa cum vei intelege din carte, aceste simptome nu sunt dificile, ele fiind chiar banale. Foarte multi utilizatori au trait si murit fara a stii ca sunt dependenti de pornografie.  

Unele persoane considera ca pornografie de pe net este gratuita deci toata umanitatea ar trebui sa se bucure de acest beneficiu. Dar asa cum vom intelege mai tarziu, acest lucru nu este adevarat, pornografia actionand si comportandu-se ca un drog. Intreaba pe cineva care se mandreste ca se masturbeaza numai la materiale "sigure" gen reviste porno, daca intr-o zi nu ar mai avea acces la acestea, ar incerca si alte modalitati de satisfactie si mai putin sigure. Daca sunt complet sinceri iti vro confesui ca s-au gandit in trecut la a trece linia catre o pornografie mai dura si mai palpitanta, orice numai sa nu ramana fara materiale pentru dependenta sa. 

Placerea nu are nimic de a face cu vizionatul pornografiei. Personal, iubesc ceafa de porc, dar asta nu inseamna ca o consum zilnic. Ca si alte lucruri in viata, ne bucuram de ele cat le avem, dar nu ne petrecem restul timpului simtindu-ne prost ca nu le mai avem. 

Unii spun: 
 
*"pornografia este educativa*" Daca asta spui, atunci cu ce te-a ajutat sa cresti ca persoana? 
 
*"Pornografia este o placere care mi satisface nevoia de sex*" Atunci de ce te face sa te izolezi si sa nu fii in stare sa comunici cu persoanele de care te simti atras? 
 
*"Pornografia imi da un sentiment de relaxare!*" Pentru cat timp? O ora? Dupa care totul ca reveni la loc.  
 
*"Ma ajuta sa dorm mai bine"* Sunt mult mai multe metode bune de a trata insomnia decat sa depinzi de un obicei asa daunator. 


Multi cred ca pornografia reduce plictiseala, dar plictiseala este un fel de a gandi. Pornografia te va face sa cauti constant lucrui noi, astfel provocand plictiseala pe care ai incercat atat timp sa o alungi. Pornografia te va face sa cauti constant acel clip potrivit la care sa te poti masturba, astfel tu devenind din ce in ce mai axat sa cauti si in viata de zi cu zi experiente care evoca emotii puternice, noutate si care au un factor de soc. 

Noi credem ca daca prietenii nostri folosesc pornografia, atunci trebuie sa fie ceva bun la ea. De fapt, ne spalam singuri pe creier sa credem asta. Pentru ca multi nu se considera dependenti, ei spun ca au doar obiceiul de a se masturba la pornografie, dar se pot opri oricand. Cu timpul insa, se dovedeste ca acest lucru nu este adevarat, deoarece PMO nu este un obicei, ci o dependenta. 

Sunt obiceiurile dificil de oprit? In Romania suntem obisnuiti sa conducem pe partea dreapta a drumului, dar cand ajungem in Anglia ne obisnuim dupa o perioada scurta sa conducem pe partea opusa. Adunam si pierdem obiceiuri tot timpul, dar oare de ce este asa de greu sa renuntam la pornografie?  

Raspunsul este ca pornografia nu este un obicei, ci o *dependenta!*. Din aceasta cauzaa este asa de greu sa renuntam. Majoritatea utilizatorilor nu inteleg dependenta si din acest motiv le este foarte greu sa renunte. Ei cred cu tarie ca PMO le aduce fericire si o alinare de la stresul vietii de zi cu zi. Ei cred ca daca s-ar lasa ar face un adevarat sacrificiu. 

Dulcele adevar este ca odata ce ai inteles adevarata natura a dependentei de pornografie si motivele pentru care continui sa o folosesti, te vei opri din a o face fara nicio durere. In trei saptamani singurul mister va fi de ce ti-a luat asa de mult sa faci acest pas.

## Capcana Sinistra

Pornografia pe internet este o capcană subtilă și sinistră. Unii dintre noi sunt chiar avertizați cu privire la pericolele pe care le prezintă, dar nu ne vine să credem că au atatea pericole. Dar ce ne face să folosim în primul rând? De obicei, este vorba de mostre gratuite de la amatori și profesioniști care împart. Așa se întinde capcana. Dacă, în schimb, ne-ar avertiza de pericolele în care ne băgăm înainte de a arunca chiar și prima privire, atunci beculetele rosii s-ar aprinde. 
 
Dar aceste beculete nu se aprind. Poate că natura șocantă a multor clipuri este cea care ne asigură mințile noastre tinere că nu vom deveni niciodată dependenți, crezând că, pentru că nu ne plac, ne putem opri oricând dorim. Sau poate că aparenta inocență a materialului soft nu declanșează niciun semnal de alarmă, la fel ca o schema abilă pe care un escroc o poate juca pentru a ne dirija mintea. Ca ființe umane inteligente, am înțelege atunci de ce jumătate din populația adultă este dependentă în mod sistematic de ceva care ne reduce chiar potențialul de a realiza ceea ce vizionăm. Curiozitatea ne aduce mai aproape de pragul dependenței, dar nu îndrăznim să dăm click pe imaginile pe care le privim, de teamă că ne vor îmbolnăvi sau ne vor trimite pe o cale periculoasă și imorală. Iar dacă din greșeală am dat click pe una dintre ele, de multe ori singura noastră dorință este să ne îndepărtăm cât mai repede de pagină, fiind în același timp disperați și mai curioși.

Odată ce acest proces a început, suntem prinși în capcană. De acum încolo ne petrecem restul vieții încercând să înțelegem de ce o facem, spunându-le copiilor noștri să nu înceapă și, în rareori, încercând să scăpăm noi înșine. Capcana este concepută în așa fel încât încercăm să ne oprim doar din cauza unui "incident", fie că este vorba de performanțe sexuale scazute, de pierderea unei cariere sau a unei relații, de lipsa de energie sau pur și simplu de sentimentul de lepră. De îndată ce ne oprim, avem mai mult stres din cauza senzației de sevraj, iar metoda pe care ne bazam pentru a elimina acest stres este acum indisponibilă.

Hotărârea noastră de a renunța se dovedește a fi șubredă. După câteva zile de tortură, ne convingem că am ales momentul nepotrivit pentru a renunța, hotărând că vom aștepta perioade fără stres, ceea ce, la sosire, ne înlătură motivul pentru care ne-am oprit inițial. Desigur, acea perioadă nu va sosi niciodată pe deplin, iar noi începem să credem că viața noastră tinde să devină din ce în ce mai stresantă. Părăsim protecția părinților noștri, iar stresul muncii, al gospodăriei, al ipotecilor, al cumpărării unui adăpost și al creșterii copiilor începe să ne aglomereze viața. Dar aceasta este o iluzie. Cele mai stresante părți din viața oricărei creaturi sunt, de fapt, copilăria timpurie și adolescența.

Avem tendința de a confunda responsabilitatea cu stresul. Viața unui utilizator - ca și cea a unui dependent de droguri - devine automat mai stresantă, deoarece pornografia nu ne relaxează și nu ne ușurează stresul, așa cum încearcă unii să ne facă să credem. Este exact invers, făcându-ne să devenim și mai stresați pe măsură ce continuăm să folosim, cu fiecare sesiune nocturnă încărcată de vinovăție care pune si mai multe paie pe foc. Chiar și consumatorii care renunță la acest obicei - așa cum majoritatea o fac de una sau mai multe ori de-a lungul vieții - pot duce o viață perfect fericită, dar devin brusc dependenți din nou. Rătăcind în labirintul pornografic, mintea noastră devine încețoșată și ne petrecem restul vieții încercând să evadăm. Mulți reușesc, doar pentru a cădea mai târziu în capcana sinistră.

Rezolvarea problemei dependenței de pornografie este o ghicitoare. Este complexă și dificilă. Dar odată ce vezi răspunsul, este simplu și distractiv și te întrebi de ce nu te-ai gândit la asta! EasyPeasy conține soluția acestei enigme, conducându-vă afară din labirint, fără să vă mai rătăciți niciodată în el. **Tot ce trebuie să faci este să urmezi fiecare instrucțiune literă cu literă**. Cu toate acestea, dacă iei **o cotitură greșită, sărind capitole**, sau **traversând cartea cu viteza fulgerului** fără a face un efort deliberat și atent la prima lectură, atunci restul instrucțiunilor sunt inutile.

Oricui îi este ușor să se oprească, dar mai întâi trebuie să stabilim realitatea. Nu, nu realități menite să vă sperie, există deja mai mult decât suficiente informații. Dacă ar fi fost să vă oprească, v-ați fi oprit deja. Dar de ce ne este greu să ne oprim? Pentru a răspunde la această întrebare este necesar să cunoaștem adevăratul motiv pentru care încă folosim pornografia, care se reduce la doi factori. Aceștia sunt:


- Natura și pornografia pe internet.


- Spălarea socială a creierului.


Utilizatorii de porno sunt ființe umane inteligente și raționale. Ei știu că își asumă riscuri enorme în viitor, așa că petrec mult timp raționalizându-și "obiceiul". Dar utilizatorii de porno în inimile lor știu că sunt proști, știind că nu aveau nevoie să folosească porno înainte de a deveni dependenți. Cei mai mulți își amintesc că prima lor "privire" a fost un amestec de repulsie și curiozitate inedită. Apoi se specializează în localizarea, filtrarea și marcarea site-urilor, lucrând din greu pentru a deveni dependenți.


Cel mai enervant, există sentimentul că cei care nu sunt dependenți - majoritatea femeilor, băieții mai în vârstă și persoanele care trăiesc în țări în care pornografia pe internet de mare viteză nu este disponibilă - nu pierd nimic și consideră situația ridicolă. Demonstrând acești factori în capitolele următoare, veți înțelege și dumneavoastră capcana sinistră!

