# Spălarea pe creier

Acesta este al doilea motiv pentru care începem să folosim pornografia. Înțelegerea deplină a acestei spălări pe creier a necesitat să examinăm mai întâi efectele puternice ale stimulilor supranormali. Creierele noastre pur și simplu nu sunt pregătite pentru crearea unui "harem online", care ne permite să schimbăm între mai multe posibile partenere în cincisprezece minute decât au avut strămoșii noștri în mai multe vieți.

Au existat multe sfaturi greșite în trecut, un exemplu fiind acela că masturbarea duce la orbire. Aceasta, împreună cu alte tactici înfricoșătoare, au exagerat în mod clar efectele negative. Concepții greșite ca acestea au fost dovedite a fi gresite. Incă din primii ani de viață, mințile noastre subconștiente sunt bombardate cu mesaje și imagini sexuale, reviste și reclame încărcate cu aluzii. Unele videoclipuri pop sunt extrem de sugestive, dar nu dispera, fă un joc din a identifica ce componente folosesc fie ca este vorba de valoarea de șoc, de noutate, de culoare, de mărime, de tabu, de nostalgie, etc. Un astfel de joc poate fi predat chiar și preadolescenților, ca o modalitate de a-i educa.

În esența sa, mesajul este *"Cel mai prețios lucru de pe acest pământ, ultimul meu gând și ultima mea acțiune, va fi orgasmul. "* Este oare o exagerare? Urmăriți orice intrigă de televiziune sau film și veți vedea amestecul dintre părțile senzoriale (atingere, miros, voce) și cele propagatoare (orgasmice) ale sexului. Impactul acestui lucru nu se înregistrează în conștientul nostru, dar subconștientul are timp să îl absoarbă.


## Raționament științific


Există și publicitate în sens invers: temerile legate de disfuncțiile sexuale, pierderea motivației, preferința pentru pornografia virtuală în locul fetelor reale, YourBrainOnPorn.com și diverse subculturi de pe internet, dar aceste mișcări nu îi împiedică de fapt pe oameni să consume. Din punct de vedere logic, ar trebui să o facă, dar simplul fapt este că nu o fac. Nici măcar riscurile pentru sănătate enumerate în studiile de specialitate de pe site-ul YourBrainOnPorn.com nu sunt suficiente pentru a împiedica un adolescent să înceapă.

În mod ironic, cea mai puternică forță în această confuzie este chiar utilizatorul. Este o eroare faptul că utilizatorii sunt persoane slabe de voință sau slabe din punct de vedere fizic. Trebuie să fii puternic din punct de vedere fizic pentru a face față unei dependențe odată ce știi că aceasta există. Poate că cel mai dureros aspect este faptul că se plasează pe ei înșiși ca ratați nereușiți și introvertiți insuportabili. Este probabil că un prieten ar putea fi mai interesant în persoană dacă nu s-ar fi pus la pământ pentru că își dorește propria plăcere.


## Probleme legate de folosirea puterii voinței  

Utilizatorii care se lasă de PMO folosind metoda voinței dau vina pe propria lipsă de voință și își distrug liniștea și fericirea. Una este să eșuezi în autodisciplină și alta este să te disprețuiești pe tine însuți. La urma urmei, nu există nicio lege care să-ți impună să fii tot timpul în erecție înainte de sex, excitat corespunzător și capabil să-ți satisfaci partenerul. Lucrăm la o dependență, nu la un obicei și în nici un moment nu te cerți cu tine însuți pentru a opri un obicei cum ar fi golful, dar să faci același lucru cu dependența de porno este normalizat - de ce?

Expunerea constantă la un stimul supranormal îți reconectează creierul, așa că este esențial să construiești o rezistență la această spălare a creierului, ca și cum ai cumpăra o mașină de la un dealer de mașini la mâna a doua - dai din cap politicos, dar nu crezi un cuvânt din ce spune omul. Așadar, nu trebuie credeți că trebuie să faceți cât mai mult sex, folosind pornografia în lipsa acestuia.

Pornografia de amatori este certificată de vreo autoritate? Nu. Asa ca nu trebuie sa cazi prada jocurilor micului monstru. Site-urile porno adună date de la utilizatorii lor și le folosesc pentru a răspunde nevoilor lor, iar dacă văd o creștere într-o anumită categorie, se vor concentra pe ea și vor scoate conținut cât mai repede. Nu vă lăsați păcăliți de intenția educațională sau de clipurile "sigure" comercializate de femei. Începeți să vă întrebați: *"? Chiar am nevoie de PMO? "*.

**Nu, bineînțeles că nu ai nevoie!**

Cei mai mulți utilizatori jură că se uită doar la porno static(poze) și soft și că, prin urmare, sunt în regulă, când, de fapt, se chinuie, luptându-se cu voința lor pentru a rezista tentațiilor. Dacă o fac prea des și pentru prea mult timp, acest lucru le epuizează considerabil voința și încep să eșueze în alte proiecte de viață în care voința este de mare valoare, cum ar fi exercițiile fizice, dieta etc. Eșecul în aceste domenii îi face să se simtă nefericiți și vinovați, ceea ce duce la folosirea din nou a pornografiei. Dacă acest lucru nu se întâmplă, își vor descărca furia și depresia pe cei dragi.

Odată ce deveniți dependenți de pornografia pe internet, spălarea creierului este sporită. Mintea subconștientă știe că micul monstru trebuie hrănit, blocând orice altceva. Frica este cea care îi împiedică pe oameni să renunțe, frica de acel sentiment de gol, de nesiguranță pe care îl au atunci când încetează să-și inunde creierul cu dopamină. Doar pentru că nu ești conștient de ea nu înseamnă că nu există. Nu trebuie să o înțelegeți așa cum o pisică nu trebuie să înțeleagă unde sunt țevile de apă caldă: pisica știe doar că dacă stă într-un anumit loc se simte caldă.

## Pasivitate

Pasivitatea minții noastre și dependența de autoritate care duce la spălarea creierului reprezintă principala dificultate a renunțării la pornografie. Educația noastră primita în societate, întărită de spălarea creierului de propria noastră dependență este combinata cu cea de la prietenii, rudele și colegii noștri. Expresia " a renunța" este un exemplu clasic de spălare a creierului, implicând un sacrificiu autentic. Frumosul adevăr este că nu este nimic la care să renunți; dimpotrivă, te vei elibera de o boală teribilă și vei obține câștiguri pozitive minunate. Vom începe să eliminăm această spălare a creierului acum, începând cu a nu mai face referire la "renunțare", ci la oprire, încetare sau si mai adecvat la  **evadare!**.

Singurul lucru care ne convinge să consumăm inițial este faptul că alți oameni o fac și să simțim că pierdem ceva daca nu utilizam si noI pornografie virtuala. Ne străduim din greu să devenim dependenți, dar nu găsim niciodată fericirea si relaxarea promisa. De fiecare dată când vedem un alt clip ne asigură că trebuie să fie ceva bun la el, altfel oamenii nu s-ar uita și afacerea nu ar fi atât de mare. Chiar și atunci când renunță la viciu, fostul consumator se simte privat atunci când în timpul petrecerilor sau al funcțiilor sociale apare o discuție despre un artist sexy, un cântăreț sau chiar un star porno. *"Trebuie să fie bune dacă toți prietenii mei vorbesc despre ele, nu? Au poze gratuite online? "* Se simt în siguranță, vor arunca o singură privire în seara asta și, înainte de a-și da seama, sunt din nou dependenți.

Spălarea creierului este extrem de puternică și trebuie să fiți conștienți de efectele sale. Tehnologia continuă să crească, iar viitorul va aduce site-uri și metode de acces exponențial de rapide. Industria pornografică investește milioane de euro în realitatea virtuală, astfel încât aceasta să devină următorul lucru la moda. Nu știm încotro ne îndreptăm, nefiind echipați pentru a face față tehnologiei actuale sau a ceea ce va urma.


Suntem pe cale să eliminăm această spălare pe creier. Nu non-utilizatorul este cel privat, ci utilizatorul care renunță la o viață întreagă:

- Sănătate

- Energie

- Bogăție

- Pacea sufletească

- Încredere

- Curaj

- Respectul de sine

- Fericire

- Libertate

Ce câștigă ei din aceste sacrificii considerabile? **ABSOLUT NIMIC**, în afară de iluzia de a încerca să revină la starea de pace, liniște și încredere de care se bucură întotdeauna non-utilizatorul. 

## Dureri de sevraj

După cum s-a explicat mai devreme, utilizatorii cred că folosesc pornografia pentru plăcere, relaxare sau pentru un anumit tip de pregătire. Motivul real este ușurarea senzației de sevraj. Mintea noastră subconștientă începe să învețe că pornografia pe internet și masturbarea în anumite momente tinde să fie plăcută. Pe măsură ce devenim din ce în ce mai dependenți de drog, cu atât mai mare devine nevoia de a ameliora durerile de sevraj și cu atât mai mult capcana subtilă te trage în jos. Acest proces se întâmplă atât de încet încât nici măcar nu sunteți conștienți de el, majoritatea tinerilor consumatori nu își dau seama că sunt dependenți decât atunci când încearcă să se oprească și chiar și atunci, mulți nu vor recunoaște acest lucru.


Luați ca exemplu această conversație pe care un terapeut a avut-o cu sute de adolescenți:

>**Terapeut:** "*Îți dai seama că pornografia pe internet este un drog și singurul motiv pentru care folosești este că nu te poți opri.*"
>
>**Pacient:** "*Tontule! Îmi place, dacă nu mi-ar plăcea, m-aș opri.*"
>
>**Terapeut:** "*Să te oprești doar o săptămână ca să-mi dovedești că poți, dacă vrei.*"
>
>**Pacient:** "*Nu e nevoie, îmi place. Dacă aș vrea să mă opresc, m-aș opri.*" 
>
>**Terapeut:** "*Să te oprești doar o săptămână ca să-ți dovedești că nu ești dependent.*"
>
>**Pacient:** "*Ce rost are? Îmi place. "*

După cum s-a spus deja, consumatorii au tendința de a-și ușura senzația de sevraj în momente de stres, plictiseală, concentrare sau combinații ale acestora. În capitolele următoare, vom viza aceste aspecte ale spălării de creier.