# La ce renunț?

**Absolut nimic!** Este dificil să renunți la pornografie din cauza fricii că suntem privați de plăcere sau de sprijin. Teama că anumite situații plăcute nu vor mai fi niciodată la fel. Teama că vei rămâne incapabil să faci față unor situații stresante. Cu alte cuvinte, este vorba de efectele spălării creierului care ne amăgește să credem că sexul - și, prin extensie, orgasmul - este o necesitate pentru toate ființele umane. Chiar mai departe, este vorba de convingerea că există ceva inerent în pornografia pe internet de care avem nevoie și că, atunci când ne oprim din utilizare, ne vom nega pe noi înșine și vom crea un gol.

Clarificați acest lucru în mintea dumneavoastră: **Porn-ul nu umple un gol,** ***creează unul!***

Corpurile noastre sunt cele mai sofisticate lucruri de pe planetă. Indiferent dacă credeți în designul inteligent, în selecția naturală sau într-o combinație a celor două, corpurile noastre sunt de mii de ori mai eficiente decât omul in sine! Suntem incapabili să creăm cea mai mică celulă vie sau miracolele de vedere, reproducere și diversele sisteme interconectate prezente în corpul sau creierul nostru. Dacă acest creator sau acest proces ar fi intenționat să gestionăm stimuli supranormali, am fi fost prevăzuți cu sisteme de recompensă diferite. Corpurile noastre sunt prevăzute cu dispozitive de avertizare de siguranță și le ignorăm pe riscul nostru. 

## Nu renunti la nimic

Odată ce ai curățat monstrul mic din corpul tău și spălarea creierului (monstrul mare) din mintea ta, nu vei mai dori să te masturbezi des și nici să folosești porno pe internet pentru asta. Există multe lucruri cunoscute și necunoscute atunci când vine vorba de dependența de pornografie, mulți din comunitatea medicală neavând conceptul de a pune la îndoială sau de a determina pe cineva ca fiind dependent de pornografie. O mulțime de simptome raportate sunt etichetate în mod greșit sub alte cauze. Nu este vorba că utilizatorii sunt în general oameni proști, ci doar că sunt nefericiți fără porno. Prins între diavol și marea albastră adâncă, abținându-se și fiind nefericit pentru că nu pot folosi porno, sau nefericit pentru că sunt vinovați și încep să se disprețuiască din cauza asta. Când au simptome precum durerile lombare sau disfuncțiile sexuale, mințile lor sunt împărțite între a accepta responsabilitatea și a privi în altă parte.

O altă analogie cu fumătorii: cu toții am văzut fumători care dezvoltă scuze pentru a se strecura pentru un fum viclean și vedem adevărata dependență în acțiune. Dependenții nu fac acest lucru pentru plăcere, în schimb o fac pentru că se simt nefericiți fără ea.

Pentru mulți, prima lor experiență sexuală s-a încheiat cu un orgasm, așa că au dobândit convingerea că nu se pot bucura de sex fără unul. În cazul bărbaților, pornografia este comercializată ca un ajutor pentru a face sex, uneori chiar ca o educație în ceea ce privește încrederea în timpul actului. Acest lucru este un nonsens, condiționarea stimulilor supranormali nu reușește decât să o doboare.

Nu numai că nu trebuie să renunțați la nimic, dar puteți obține câștiguri pozitive masive. Atunci când utilizatorii se gândesc să renunțe, ei tind să se concentreze asupra sănătății și virilității. Acestea sunt motive valide și importante, dar eu personal cred că cele mai mari câștiguri sunt psihologice:

- Revenirea încrederii și a curajului.

- Eliberarea de sclavie.

- Faptul de a nu mai avea umbre negre îngrozitoare în spatele minții și de a te disprețui.

## Vid, vid, vidul, frumosul vid!

Imaginează-ți că ai o rană de herpes pe față, așa că te duci la farmacist și acesta îți dă un unguent gratuit pentru a-l încerca. Îți pui unguentul și dispare imediat. O săptămână mai târziu reapare, așa că vă întoarceți la farmacist și îl întrebați dacă mai are unguent. Farmacistul spune *"Sigur; păstrați tubul, s-ar putea să aveți nevoie de el mai târziu. "*.

Aplicați unguentul și, hei, gata, rana dispare din nou. Dar de fiecare dată când rana revine, devine mai mare și mai dureroasă, iar intervalul devine din ce în ce mai scurt. În cele din urmă, rana îți acoperă întreaga față și este insuportabil de dureroasă, iar aceasta revine la fiecare jumătate de oră. Știi că unguentul o va îndepărta temporar, dar ești foarte îngrijorat. Se va răspândi în cele din urmă rana pe tot corpul dumneavoastră? Va dispărea complet intervalul? Te duci la medic și nu o poate vindeca, așa că încerci și alte lucruri, dar nimic nu te ajută în afară de unguent.

De acum înainte sunteți complet dependent de unguent, nu ieșiți niciodată fără să vă asigurați că aveți un tub cu dumneavoastră. Dacă plecați în străinătate, vă asigurați că luați mai multe tuburi cu dumneavoastră. Pe lângă grijile legate de sănătatea ta, farmacistul îți cere o sută de dolari pe tub. Nu aveți de ales decât să plătiți.

Dai peste un articol în care se discută despre acest lucru și afli că nu ți se întâmplă doar ție, ci multor oameni li se întâmplă aceeași problemă. De fapt, comunitatea medicală a descoperit că unguentul nu vindecă de fapt rana, ci doar o duce sub suprafața pielii. Unguentul este cel care a provocat creșterea rănii, așa că tot ce trebuie să faci pentru a scăpa de rană este să nu mai folosești unguentul și aceasta va dispărea în timp util.

Ați continua să folosiți unguentul? Ar fi nevoie de voință pentru a nu mai folosi unguentul? Dacă nu ați crede articolul, ar putea exista câteva zile de reținere, dar odată ce ați realizat că rana începe să se amelioreze, nevoia sau dorința de a folosi unguentul ar dispărea. Ați fi nefericit? Bineînțeles că nu! Ați avut o problemă îngrozitoare pe care o credeați incurabilă, dar acum ați găsit soluția. Chiar dacă ar dura un an până când durerea ar dispărea, în fiecare zi, pe măsură ce se ameliorează, v-ați gândi la cât de minunat vă simțiți. Aceasta este magia renunțării la pornografie.

Durerea nu este reprezentată de durerile corporale, de lipsa poftei normale, de excitarea în scădere, de penetrarea care se estompează, de timpul pierdut cu imagini bidimensionale, de sentimentele de  disprețuire a celor care te-au prins sau, mai rău, de disprețul față de tine însuți. Toate acestea se adaugă la durere.

Durerea ne face să ne închidem mintea la toate aceste lucruri - este acel sentiment de panică de a dori o doză. Cei care nu consumă nu suferă de acest sentiment. Cel mai rău lucru pe care îl suferim este frica, cel mai mare câștig fiind scăparea de acea frică. Este cauzată de prima ședință, întărită și provocată în continuare de fiecare ședință ulterioară.

Unii utilizatori sunt "fericiți", orbiți de micii lor monștri vicleni și astfel trec prin același coșmar, aducând argumente false pentru a încerca să își justifice prostia.

*Este atât de frumos să fii liber!*
