# Economisirea timpului

De obicei, atunci când utilizatorii încearcă să se oprească, principalele motive invocate sunt sănătatea, religia și stigmatizarea din partea partenerului. O parte a spălării pe creier pe care o face acest drog îngrozitor este însăși sclavia; omul a luptat din greu pentru a aboli sclavia în multe părți ale lumii - totuși, utilizatorul își petrece viața suferind o sclavie autoimpusă. Ei sunt inconștienți de faptul că, atunci când li se permite să folosească pornografia, își doresc să fie un non-utilizator. Singurul moment în care pornografia devine prețioasă este atunci când "încercăm" să reducem sau să ne abținem, sau când abstinența ne este impusă.

Nu poate fi repetat suficient de des că spălarea creierului face dificilă oprirea pornografiei, așa că, cu cât risipim mai mult înainte de a începe, cu atât mai ușor vă va fi să vă atingeți obiectivul. Utilizatorii confirmați, care nu cred că pornografia are vreun efect negativ asupra sănătății lor (disfuncție erectilă indusă de pornografie, hipofrontalitate etc.) și nu au o luptă mentală sunt de obicei mai tineri sau singuri cu un partener sexual ocazional. Astfel, feedback-ul intern este pierdut din cauza naturii tinereții lor sau este prea puțin frecvent pentru a fi observat și înregistrat.

Un argument mai bun pentru un utilizator mai tânăr este timpul petrecut, mai degrabă spunând "*Nu pot să cred că nu ești îngrijorat de timpul pe care îl petreci.*" În general, ochii lor se luminează, simțindu-se dezavantajați dacă sunt atacați pe motive de sănătate sau stigmat social, dar pe timp...  

"*Oh, îmi pot permite. Sunt doar* x *ore pe săptămână și cred că merită, este singurul meu viciu.*"

"*Încă nu-mi vine să cred că nu ești îngrijorat. Să presupunem o medie zilnică de jumătate de oră, care include și epuizarea fizică a sevrajului de dopamină, petreci aproximativ o zi întreagă de lucru la fiecare două săptămâni. Sunt sigur că vei fi de acord că o jumătate de oră pe zi este o estimare foarte conservatoare. V-ați gândit la cât timp veți petrece în timpul vieții dumneavoastră? Ce veți face în acest timp? Dezvolți relații reale? Nu, vedeta ta porno preferată nu are simpatie pentru tine, doar pentru că ai petrecut atât de mult timp pe videoclipurile lor - arunci timpul pe apa sâmbetei! Nu numai atât, de fapt, folosești acel timp pentru a-ți distruge sănătatea fizică, distrugându-ți nervii și încrederea în tine, pentru a suferi o viață întreagă de sclavie, durere, melancolie și bășcălie. Cu siguranță asta trebuie să te îngrijoreze, nu-i așa?*"

Este evident în acest moment - mai ales în cazul utilizatorilor mai tineri - că aceștia nu au considerat niciodată că este o dependență pe viață. Ocazional, ei calculează timpul pe care îl pierd într-o săptămână și asta este destul de alarmant. Foarte ocazional, și numai atunci când se gândesc să se oprească, vor estima cât cheltuiesc într-un an, ceea ce este înspăimântător - dar pentru o viață întreagă este de neconceput. Cu toate acestea, pentru că ne aflăm într-o discuție, utilizatorul confirmat va spune impulsiv: *"Îmi pot permite, este doar atât pe săptămână "*, făcând un număr de vânzător de enciclopedii pe cont propriu.

Ați refuza o ofertă de muncă care să vă plătească salariul anual actual și care să vă ofere o lună liberă în fiecare an? Orice utilizator ar semna într-o clipită și s-ar ocupa să găsească oferte de vacanță în locații exotice. Să-ți dai seama cum să petreci o lună întreagă fără muncă ar fi cea mai mare problemă de rezolvat. În fiecare discuție cu un utilizator confirmat (și vă rog să aveți în vedere că nu este vorba de cineva ca dumneavoastră care plănuiește să se oprească) nimeni nu mi-a acceptat vreodată această ofertă. De ce nu?

Adesea, în acest punct, un utilizator confirmat spune: "*Uite, nu sunt foarte îngrijorat de aspectul financiar.*" Dacă te gândești în acest sens, întreabă-te de ce nu ești îngrijorat. De ce, în alte aspecte ale vieții tale, te vei chinui foarte mult pentru a economisi câțiva dolari ici și colo, dar vei cheltui mii de dolari omorându-ți fericirea și atârnând de cheltuieli?

Orice altă decizie pe care o iei în viața ta va fi rezultatul unui proces analitic de cântărire a avantajelor și dezavantajelor pentru a ajunge la o decizie rațională. Poate fi o decizie greșită, dar va fi rezultatul unei deducții raționale. Ori de câte ori orice utilizator cântărește avantajele și dezavantajele utilizării pornografiei pe internet, răspunsul este de zeci de ori, **"NU MAI FOLOSIȚI! EȘTI UN NEBUN!"** Prin urmare, toți utilizatorii folosesc nu pentru că vor sau decid să o facă, ci pentru că nu se pot opri. Ei ***trebuie*** să folosească pornografia, și astfel își spală creierul, ținându-și capul în nisip. 

Utilizatorii confirmați ar trebui să țină cont de faptul că situația se va înrăutăți exponențial, odată cu apariția mai multor studii și a tot mai multor persoane care vorbesc despre efectele negative ale pornografiei pe internet. Astăzi, sunt persoane fără studii medicale care discută despre efecte, mâine va fi pe lista de teste de diagnosticare a medicului dumneavoastră. Au dispărut zilele în care utilizatorul poate ascunde "timpul mort" în spatele stresului de la locul de muncă în viața sa sexuală; partenerul tău va întreba de ce stai pe laptop noaptea târziu. Bietul utilizator - care se simte deja nenorocit - vrea acum ca pământul să se deschidă și să îl înghită.

Lucrul ciudat este că, deși mulți oameni ar plăti bani buni pentru abonamente la sală și antrenori personali pentru a-și face mușchi și a arăta sculptați (și mulți dintre ei, în disperarea lor imaginară (și reală), apelează la tratamente precum stimularea testosteronului, cu efecte secundare dubioase și periculoase), există multe persoane din acest grup care ar beneficia de pe urma opririi unei practici care le distruge sistematic sistemele naturale de relaxare a creierului.

Acest lucru se datorează faptului că ei încă gândesc cu mintea spălată pe creier a utilizatorului. Ștergeți-vă pentru o clipă nisipul din ochi. Pornografia pe internet este o reacție în lanț și un lanț pentru toată viața, iar dacă nu rupeți acest lanț veți rămâne un utilizator pentru tot restul vieții. Estimați cât timp credeți că veți petrece pe porno pentru restul existenței dvs. Evident, cantitatea va varia de la o persoană la alta, dar să presupunem că este vorba de un an și jumătate de ore de muncă. Imaginați-vă dacă mâine ar exista un cec de la loto în valoare de un an și jumătate din salariul dvs. așezat pe covorul dvs. Ați dansa de încântare, așa că începeți să dansați! Sunteți pe cale să începeți să primiți aceste beneficii!

Dacă vi se pare că acesta este un mod complicat de a vedea lucrurile, vă păcăliți în continuare. Calculați cât timp ați fi economisit dacă nu ați fi aruncat prima privire chiar de la început.

În scurt timp, veți lua decizia de a utiliza ultima sesiune (nu încă, vă rugăm să țineți minte instrucțiunile!), rămânând un non-utilizator prin faptul că nu veți mai cădea din nou în capcană. Tot ce trebuie să faceți pentru a rămâne un non-utilizator este să nu folosiți pornografia și să evitați "doar o singură privire". Amintiți-vă că dacă o faceți, vă va costa ceea ce ați estimat că va fi câștigul salarial. 

Dacă îndrumați pe cineva pentru dependența lor de pornografie, spuneți-le că știu pe cineva care a refuzat o ofertă de muncă care îi plătește salariul anual actual și îi oferă, de asemenea, o lună întreagă de timp liber plătit. Când este întrebat cine este acel idiot, spuneți-i: ***"Tu!"*** Este nepoliticos, dar uneori trebuie să te faci înțeles într-un mod mai puțin politicos.
