# Sănătate

Acesta este domeniul în care spălarea creierului este cea mai puternică în cazul utilizatorilor - în special al celor tineri și singuri - care cred că sunt conștienți de riscurile pentru sănătate, dar nu sunt. Mulți se amăgesc spunând că sunt pregătiți să accepte consecințele. Dacă routerul dvs. de internet ar avea o funcție care să emită un semnal de alarmă cu un avertisment atunci când accesați un site porno, care să spună: "*Până acum ați scăpat, dar dacă mai stați încă un minut vă va exploda capul*". Ați fi rămas? Dacă aveți îndoieli cu privire la răspuns, încercați să mergeți până la o stâncă, să stați pe margine cu ochii închiși și să vă imaginați că aveți posibilitatea de a alege între a renunța la pornografie sau de a urca legat la ochi.

Nu există nicio îndoială care ar fi alegerea ta, dar dacă îți îngropi capul în nisip și speri că te vei trezi într-o dimineață și nu vei mai dori să te uiți la porno, nu realizezi nimic. Utilizatorii nu-și pot permite să se gândească la riscurile pentru sănătate, pentru că, dacă o fac, plăcerea iluzorie a dependenței dispare. 
Take this common conversation with users, generally younger ones.

> **Eu:** "De ce vrei să te oprești?"
>
> **Utilizator:** "*Am citit pe blogul unui artist de agățat că e bine să mă opresc pentru patru zile ca să mă energizez.*"
>
> **Eu:** "Nu ești îngrijorat de riscurile pentru sănătate?"
>
> **Utilizator:** "*Nu, mâine aș putea să trec sub un autobuz.*"
>
> **Mi:** "Dar ai păși deliberat sub un autobuz?"
>
> **Utilizator:** "Bineînțeles că nu."  
>
> **Eu:** "Nu te deranjezi să te uiți în stânga și în dreapta când traversezi strada?"
>
> **Utilizator:** "Sigur că da."

Exact, se străduiesc foarte mult să nu calce sub un autobuz, iar șansele sunt de mii la unu ca să nu se întâmple asta. Cu toate acestea, utilizatorul riscă să fie aproape sigur că va fi schilodit de dependența sa și pare să fie complet inconștient. Aceasta este puterea de spălare a creierului; pornografia pe internet este un lup în blană de oaie. Nu este ciudat că, dacă am simți că există cea mai mică defecțiune într-un avion, nu ne-am urca în el - chiar dacă riscurile sunt de ordinul milioanelor la unu - dar ne asumăm mai mult de o certitudine în cazul pornografiei și, aparent, nu ne dăm seama de acest lucru? Ce obține utilizatorul din asta? **Absolut nimic!**

Un alt mit comun este depresia sau irascibilitatea. Mulți tineri nu sunt îngrijorați de sănătatea lor pentru că nu suferă de depresie sau melancolie. Depresia sau stresul nu sunt boala, ci un simptom. Persoanele mai tinere, în general, nu simt iritabilitatea sau depresia creată datorită capacității naturale a corpului lor de a produce mai multă dopamină. Pe măsură ce îmbătrânesc sau viața lor întâmpină piedici serioase, resursele lor deja epuizate sunt suprasolicitate și vor experimenta simptome în toată regula. Atunci când utilizatorii mai în vârstă se simt stresați, deprimați sau iritați, se datorează faptului că mecanismele de siguranță ale naturii protejează sistemul nervos de o inundație excesivă de dopamină prin tăierea receptorilor. De asemenea, utilizatorul dezvoltă și alte modificări neurologice care îl mențin în rutină.

Gândește-te la asta astfel: dacă ai avea o mașină frumoasă și ai lăsa-o să ruginească fără să faci nimic în privința ei, ar fi destul de stupid. Ar deveni rapid o grămadă de rugină imobilă, incapabilă să te transporte undeva. Cu toate acestea, nu ar fi sfârșitul lumii, deoarece este doar o chestiune de bani. Dar corpul tău este vehiculul care te poartă prin viață. Cu toții spunem că sănătatea noastră este cel mai mare bun al nostru - întrebați orice milionar bolnav. Cei mai mulți dintre noi ne putem aminti de o boală sau de un accident din viața noastră în care ne-am rugat să ne facem bine. Fiind un utilizator de pornografie, nu numai că lași rugina să intre înăuntru și nu faci nimic în privința asta, dar distrugi sistematic singurul vehicul folosit pentru a trece prin întreaga ta viață.

Desteapta-te. Nu trebuie să faci asta. Nu uita, nu te ajută cu absolut nimic. Doar pentru o clipă, scoate-ți capul din nisip și întreabă-te că, dacă ai ști cu certitudine că următoarea ședință va începe un proces care te va face complet insensibil la cineva pe care îl iubești profund, ai continua să folosești? Vorbind cu persoanele cărora li se întâmplă acest lucru, cu siguranță că nici ei nu se așteptau să li se întâmple, iar cel mai rău lucru nu este boala în sine, ci faptul că știu că și-au provocat-o singuri. Încercați să vă imaginați cum se simt cei care au "apăsat pe buton", pentru ei spălarea creierului s-a încheiat. Își petrec restul vieții gândindu-se: "*De ce m-am amăgit atât de mult timp că am nevoie să mă masturbez la porno pe internet? Dacă aș avea ocazia să mă întorc înapoi!*".

Nu te mai amăgi singur, ai această șansă. Este o reacție în lanț, dacă te angajezi în următoarea sesiune pornografică, te va duce la următoarea și la următoarea și la următoarea. Deja ți se întâmplă. EasyPeasy nu promite niciun tratament șocant, așa că dacă ai decis deja că te vei opri, cele ce urmează nu vor fi șocante pentru tine. Dacă nu ați făcut-o, săriți peste *rezumatul acestui capitol* și reveniți la el după ce ați citit restul cărții.

S-au scris deja volume și volume de cercetări despre daunele pe care pornografia pe internet le provoacă vieții noastre sexuale și bunăstării mentale. Problema este că, până să se decidă să se oprească, nu vor să știe. Forumurile și grupurile de mentori sunt o pierdere de timp, deoarece pornografia i-a spalat pe creier. În cazul în care, din neatenție, citesc, primul lucru pe care îl fac este să deschidă site-ul lor preferat de porno. Utilizatorii de porno tind să se gândească la fericire, stres și pericolele sexuale ca la o afacere hit-and-miss, ca și cum ar călca pe o mină de teren.

Bagă-ți în cap, se întâmplă deja. ***De fiecare dată*** când deschideți site-ul porno declanșați inundarea de dopamină și opioidele care se pun la treabă. Toboganele neuronale de apă sunt unse și plimbarea te duce lin prin următorii pași, creierul tău a cedat deja scenariului. Sistemul nervos este acum inundat de dopamină și, din moment ce este a mia oară, receptorii de dopamină se închid, iar micul monstru folosește această ușoară scădere a plăcerii în comparație cu ultima dată pentru a vă conduce mai departe peste linia roșie către un comportament sau un porno mai șocant pentru a elibera mai multă dopamină. Mai multă noutate, mai multă dopamină, iar micul monstru vă spune să continuați. Atât de multe imagini și videoclipuri într-o singură sesiune declanșează un stimulent supranormal, injectând mai multe substanțe chimice în creier și determinându-vă să continuați.

În tot acest timp, receptorii dvs. primesc informații pentru a se opri ca răspuns la inundarea de dopamina. Orgasmul nu face decât să sporească acest efect și duce la sevraj. Sunteți în negare, deoarece micul monstruleț tânjește după doza sa fără durere și disconfort real. Amenințarea de a avea disfuncție erectilă îi îngrozește pe mulți, motiv pentru care o blochează din mintea lor și o umbresc cu teama de a se opri. Nu este vorba că frica este mai mare, dar renunțarea astăzi este imediată. De ce să privim partea negativă? Poate că nu se va întâmpla, având oricum obligația de a se fi lăsat până atunci.

Avem tendința de a ne gândi la pornografie ca la un tras de mânecă: de o parte este frica: "*Este nesănătos, murdar și înrobitor*". De cealaltă parte, aspectele pozitive: "*Este plăcerea mea, prietenul meu, suportul meu.*" Nu pare să ne treacă niciodată prin cap că această parte este și frica; nu este vorba că ne place pornografia, ci că tindem să fim nefericiți fără ea. Dependenții de heroină privați de heroină trec prin suferință, dar imaginați-vă bucuria totală atunci când li se permite în sfârșit să își înfunde un ac în venă și să pună capăt acelei pofte teribile. Încercați să vă imaginați cum ar putea cineva să creadă cu adevărat că obține plăcere înfigând o seringă hipodermică într-o venă. Persoanele care nu sunt dependente de heroină nu suferă acel sentiment de panică, iar heroina nu ameliorează acest sentiment, ci îl provoacă.

Non-utilizatorii nu se simt nefericiți dacă nu li se permite să folosească pornografia - doar utilizatorii suferă de acest sentiment. Pornografia pe internet nu ameliorează acest sentiment, ci îl provoacă. Teama de consecințele negative nu îi ajută pe utilizatori să renunțe, deoarece aceștia compară acest sentiment cu mersul pe un câmp minat. Dacă reușești să scapi, bine, dar dacă ai fost ghinionist ai călcat pe o mină și te-ai confruntat cu consecințele. Dacă tu cunoșteai riscurile și erai pregătit să ți le asumi, ce legătură avea cu ceilalți? Dependenții aflați în această stare dezvoltă, de obicei, următoarele tactici evazive.

"***În cele din urmă vei îmbătrâni și oricum îți vei pierde aptitudinile sexuale...***"  

Bineînțeles că da, dar nu despre aptitudini sexuale este vorba - vorbim de sclavie aici. Chiar dacă ar fi așa, este acesta un motiv logic pentru a te limita în mod deliberat?

"Calitatea vieții este mai importantă decât să trăiești."  

  Exact! Vrei să spui că calitatea vieții unui dependent este mai mare decât a cuiva care nu este dependent? Chiar credeți că calitatea vieții unui consumator este mai bună decât a unui ne-consumator? O viață petrecută acoperindu-și capul în nisip și fiind nefericit nu pare a fi una plăcută.

"***sunt singur și nu am de gând să mă stabilesc în viitor, așa că de ce nu?***"

Chiar dacă ar fi adevărat, este acesta un motiv logic pentru a ne juca cu mecanismele neurologice de control al impulsurilor? Poți concepe că cineva ar fi atât de prost încât să se dezbrace si sa se masturbeze ori de câte ori este singur?**Asta e ceea ce fac utilizatorii de filme porno!

Îngrădirea progresivă a circuitelor noastre de recompensă cu o stimulare excesivă, făcându-le incapabile să facă față stresului normal al vieții, nu ajută la a te bucura de viață cu entuziasm și vigoare. Pornografia și masturbarea au înlocuit apetitul sexual natural, precum un baton de ciocolată care înlocuiește mâncarea adevărată. Nu este surprinzător faptul că mulți medici și psihologi leagă acum diverse probleme de sănătate mintală de cauze fiziologice. Comunitatea medicală tradițională a lucrat că nu s-a dovedit niciodată științific că pornografia este cauza directă a problemelor raportate de persoanele care se mărturisesc pe sine, dar recunoașterea incapacității sexuale a cuiva în public este un eveniment care declanșează o asemenea rușine, așa că de ce ar face cineva acest lucru dacă nu ar fi cu adevărat îngrijorat, după ce a găsit cauza și a eliminat-o din propria viață?

EasyPeasy vă va ajuta să scăpați de pornografie și să deveniți un fost utilizator fericit. Fără pornografie, masturbare asistată de pornografie sau orgasme inutile. Singurul ajutor va fi atingerea, vederea și mirosul partenerului tău. La fel ca pâinea integrală după un apetit bine dezvoltat, nu veți mai dori siropul de porumb bogat în fructoză al pornografiei pe internet. Stresul provocat de pornografia pe internet are efecte de propagare asupra altor aspecte ale vieții utilizatorului, predispunându-i pe mulți să apeleze la droguri, cum ar fi țigările și alcoolul, pentru a face față, iar în unele cazuri chiar determinând gazda să ia în considerare sinuciderea.

Utilizatorii suferă, de asemenea, iluzii că efectele negative ale pornografiei sunt exagerate. Dimpotrivă, nu există nicio îndoială că pornografia pe internet este cauza principală a disfuncțiilor sexuale și a multor alte probleme. Câte divorțuri au fost cauzate de pornografie? Nu există modalități fiabile de a ști, dar căutările în comunitățile online sugerează că numărul crește exponențial.

Există un episod din *Friends* în care băieții, care primeau continuu porno gratuit la televizor, au început să se întrebe de ce fata care livra pizza nu le-a cerut să le verifice "dormitorul lor mare". Când ești dependent, invariabil proiectezi fanteziile porno pe femeile reale. Imaginați-vă ce ar putea face expunerea neglijentă sau chiar accidentală la pornografie pe părțile întunecate ale internetului unei persoane aflate deja într-un punct de cotitură în viața lor. Lupta împotriva acestor gânduri induse de pornografie va fi o pierdere majoră pentru sănătatea lor mintală.

(Iată un alt experiment de gândire: să spunem că cineva vine la tine și spune că nu dorește neapărat un orgasm, dar își dorește foarte mult să facă dragoste, chiar și în mod penetrant. Ei vor să o facă cât de mult și cât de departe puteți merge fără orgasm - dar dacă se întâmplă, atunci este în regulă. Te asigur de o nouă experiență sexuală fenomenală, mult mai bună decât oricare alta, dacă vei primi vreodată această ofertă. Încearcă).

Efectele spălării creierului ne fac să avem tendința de a gândi ca omul care, după ce a căzut de pe o clădire de 100 de etaje, este citat spunând, în timp ce trece pe lângă etajul cincizeci: "*Acum, până acum, totul e bine!*". Ne gândim că, din moment ce am scăpat până acum, încă o ședință porno nu va face diferența. Vedeți altfel: "obiceiul" este un lanț continuu pe viață, fiecare sesiune generând nevoia de următoarea. Când începeți obiceiul, aprindeți o fitilă. Problema este că *nu știi cât de lungă este fitilul.* De fiecare dată când cedezi la o sesiune porno, ești cu un pas mai aproape de explozia bombei. **CUM VEI ȘTI DACĂ ESTE URMĂTOAREA? **

##  Umbre Negre

Utilizatorilor le este foarte greu să creadă că pornografia pe internet provoacă de fapt acele sentimente de nesiguranță atunci când ieșiți noaptea târziu după o zi controversată acasă sau la serviciu. Non-utilizatorii nu suferă de acest sentiment, ci pornografia este cea care îl provoacă.

O altă mare bucurie a renunțării la pornografie este eliberarea de umbrele negre sinistre din spatele minții noastre. Toți utilizatorii știu că sunt proști dacă își închid mintea la efectele rele ale pornografiei. Pentru cea mai mare parte a vieții noastre este un automatism, dar umbrele negre sunt mereu la pândă în subconștientul nostru, chiar sub suprafață. Câteva dintre beneficiile minunate ale renunțării sunt conștiente, cum ar fi sfârșitul pierderii de timp și al prostiei pure de a face dragoste cu o imagine bidimensională.

Ultimele capitole s-au ocupat de avantajele considerabile ale faptului de a nu fi utilizator, dar, în interesul corectitudinii, este necesar să facem o prezentare echilibrată. Prin urmare, capitolul următor enumeră avantajele de a fi utilizator.

# Avantajele de a fi utilizator de pornografie
