# Metoda Willpower

Este un fapt acceptat în societate că este foarte dificil să te oprești din pornografie. Cărțile și forumurile care vă sfătuiesc cum să vă opriți încep de obicei prin a vă spune cât de dificil este. Adevărul este că este ridicol de ușor. Este de înțeles să pui la îndoială această afirmație, dar mai întâi ia-o în considerare. Dacă obiectivul tău este să alergi o milă în patru minute, *ceea este* dificil și va trebui să te supui unor ani de antrenamente grele, și chiar și atunci este posibil să fii incapabil din punct de vedere fizic.

Cu toate acestea, tot ce trebuie să faci pentru a opri pornografia este să nu te mai uiți la ea și/sau să nu te mai masturbezi. Nimeni nu te obligă să te masturbezi (în afară de tine însuți) și, spre deosebire de mâncare sau apă, nu este necesar pentru supraviețuire. Deci, dacă doriți să nu o mai faceți, de ce ar trebui să fie dificil? De fapt, nu este. Utilizatorii sunt cei care își îngreunează situația prin utilizarea voinței sau prin orice metodă care îi obligă pe utilizatori să simtă că fac un fel de sacrificiu. Să luăm în considerare aceste metode. 

Nu decidem să devenim utilizatori, ci doar experimentăm reviste sau site-uri porno și, pentru că sunt îngrozitoare (așa este, îngrozitoare), în afară de clipul nostru dorit, suntem convinși că ne putem opri oricând dorim. La început, ne uităm la acele prime câteva clipuri atunci când vrem și la ocazii speciale. Înainte să ne dăm seama, nu numai că vizităm acele site-uri în mod regulat și ne masturbăm când vrem - ne masturbăm la ele zilnic. Pornografia a devenit o parte din viața noastră, asigurându-ne că avem nevoie de o conexiune la internet oriunde am merge. Apoi credem că avem dreptul la dragoste, sex, orgasm și la proprietățile de ameliorare a stresului pe care le oferă pornografia. Nu pare să ne treacă prin cap că același clip și aceiași actori nu ne oferă același grad de excitare și începem să ne luptăm cu linia roșie pentru a evita "porno-ul de proastă calitate". De fapt, masturbarea și pornografia pe internet nu ne îmbunătățesc viața sexuală și nici nu reduc stresul, ci pur și simplu utilizatorii cred că nu se pot bucura de viață sau că nu pot face față stresului fără ele.

De obicei, este nevoie de mult timp pentru a ne da seama că suntem dependenți, deoarece suferim de iluzia că utilizatorii se uită la pornografie pentru că le place - și nu pentru că au ***nevoie*** să o facă. Atunci când nu ne "bucurăm" de pornografie, ceea ce nu putem face niciodată dacă nu se adaugă noutatea, șocul sau escaladarea, avem iluzia că ne putem opri oricând. Aceasta este o capcană a încrederii. "*Nu mă bucur de pornografie, așa că mă pot opri când vreau*". Numai că niciodată nu pari să "vrei" să te oprești.

De obicei, nu ne dăm seama că există o problemă decât atunci când încercăm să ne oprim. Primele încercări sunt, în general, timpurii - declanșate de întâlnirea cu un partener și de faptul că, după primele întâlniri, observăm că nu este "suficient". Un alt motiv frecvent este observarea efectelor asupra sănătății prezente în viața de zi cu zi.

Indiferent de motiv, utilizatorul așteaptă întotdeauna o situație stresantă, fie că este vorba de sănătate sau de sex. De îndată ce se opresc, micul monstruleț începe să se înfometeze. Utilizatorul dorește apoi ceva care să îi pompeze dopamina, cum ar fi țigările, alcoolul sau preferatul lor - pornografia pe internet - cu haremul lor la doar un clic distanță. Colectia de pornografie nu se mai află în subsol, ci este virtuală și accesibilă de oriunde. Dacă partenerul lor este prin preajmă sau sunt cu prietenii, nu mai au acces la haremul lor virtual, ceea ce îi face să fie și mai neliniștiți.

Dacă utilizatorul a dat peste materiale științifice sau comunități online, acesta va avea o luptă în minte, rezistând tentațiilor și simțindu-se privat. Modalitatea lor de a scăpa de obicei de stres este acum indisponibilă, suferind o triplă lovitură. Rezultatul probabil după această perioadă de tortură este compromisul - "*Voi reduce consumul*" sau "*Am ales momentul nepotrivit*" sau poate, "*Aștept până când stresul va dispărea din viața mea*". Cu toate acestea, odată ce stresul a dispărut, nu mai există niciun motiv pentru a se opri, iar utilizatorul nu se decide să renunțe din nou până la următorul moment stresant. 

Bineînțeles, nu există niciodată un moment potrivit, pentru că viața celor mai mulți oameni devine mai stresantă. Părăsim protecția părinților noștri, intrăm în lumea în care ne stabilim o casă, ne asumăm o ipotecă, avem copii și avem slujbe mai responsabile. Indiferent - viața utilizatorului nu poate deveni mai puțin stresantă, deoarece pornografia provoacă de fapt stres. Cu cât utilizatorul trece mai repede la stadiul de intensificare, cu atât devine mai stresat și cu atât mai mare este iluzia dependenței.

De fapt, este o iluzie că viața devine mai stresantă, iar pornografia - sau un suport similar - creează această iluzie. Acest lucru va fi discutat mai detaliat mai târziu, dar după aceste eșecuri inițiale, utilizatorul se bazează de obicei pe posibilitatea ca într-o zi să se trezească și pur și simplu să nu mai vrea să se masturbeze sau să folosească porno. Această speranță este de obicei aprinsă de poveștile auzite de la alți foști utilizatori: "*Nu am fost serios până când am avut o penetrare care se pierde, apoi nu am mai vrut să folosesc porno și am încetat să mă masturbez.*" 

Nu vă faceți iluzii, cercetați aceste zvonuri și veți descoperi că nu sunt niciodată atât de simple pe cât par. De obicei, utilizatorul se pregătea deja să se oprească și doar a folosit incidentul ca o rampă de lansare. Cel mai adesea, în cazul persoanelor care se opresc "așa, pur și simplu", acestea au suferit un șoc: poate o descoperire din partea partenerului, un incident de autosesizare a accesării de materiale pornografice care nu corespund orientării lor sexuale normale sau au avut ei înșiși o sperietură din cauza unei disfuncții sexuale. "*Este exact genul de persoană care sunt*". Nu te mai amăgi singur. Nu se va întâmpla decât dacă tu faci să se întâmple.

Haideți să analizăm mai în detaliu de ce metoda voinței este atât de dificilă. În cea mai mare parte a vieții noastre, adoptăm abordarea cu capul în nisip, "*Mâine mă voi opri*". În momente rare, ceva va declanșa o încercare de a ne opri. Poate fi vorba de preocupări legate de sănătate, de virilitate sau de o criză de autoanaliză și de faptul că ne dăm seama că nu ne place de fapt. Oricare ar fi motivul, începem să cântărim avantajele și dezavantajele pornografiei. Sexul este împărțit în tantric (atingere, miros, voce) și propagativ (orgasm); aceasta este una dintre cheile majore în deschiderea minții noastre, iar fără această distincție importantă, va exista confuzie, ceea ce duce la eșec. La o evaluare rațională, aflăm ceea ce am știut toată viața, concluzia este de o mie de ori "***NU VĂ MAI UITAȚI!" 

Dacă ar fi să stați jos și să acordați puncte avantajelor opririi și să le comparați cu avantajele pornografiei, numărul total de puncte pentru oprire ar depăși cu mult orice "dezavantaje". Dacă folosiți pariul lui Pascal, prin renunțare nu pierdeți aproape nimic, cu șanse mari de câștiguri și șanse mai mari de a *nu* pierde. Deși utilizatorul știe că îi va fi mai bine ca neutilizator, credința că face un sacrificiu îl împiedică. Deși este o iluzie, este puternică. Nu știu de ce, dar utilizatorul are convingerea că în momentele bune și rele ale vieții, sesiunile par să ajute. Chiar înainte de a începe tentativa, spălarea socială a creierului, întărită în continuare de spălarea creierului din cauza propriei dependențe, este apoi combinată cu spălarea și mai puternică a creierului cu privire la cât de dificil este să "renunți".

Utilizatorii aud povești despre cei care au renunțat timp de mai multe luni și încă tânjesc cu disperare după ea sau despre cei care au renunțat nemulțumiți, care, după ce au renunțat, își petrec restul vieții plângându-se de faptul că le-ar plăcea să aibă o ședință. Există povești despre utilizatori care s-au oprit timp de multe luni sau ani, trăind o viață fericită, doar pentru a avea o "privire" la porno și sunt brusc dependenți din nou. Utilizatorii cunosc probabil mai mulți în stadii avansate ale bolii, care se distrug vizibil și în mod clar nu se bucură de viață - dar continuă să folosească. În plus, probabil că au suferit ei înșiși una sau mai multe dintre aceste experiențe.

Deci, în loc să începi cu sentimentul "* Grozav! Ați aflat veștile? Nu mai am nevoie să mă uit la filme porno!*", ei încep în schimb cu sentimente de tristețe - ca și cum ar încerca să escaladeze Everestul - și stabilesc în mod eronat că, odată ce micul monstruleț și-a pus cârligele în tine, ești prins pe viață. Mulți utilizatori încep încercarea prin a se scuza față de prietenele sau soțiile lor: "*Uite, încerc să renunț la pornografie. Probabil că voi fi iritabil în următoarele două săptămâni, așa că încearcă să ai răbdare cu mine.*". Majoritatea încercărilor sunt condamnate înainte de a începe.

Presupuneți că utilizatorul supraviețuiește câteva zile fără o sesiune. Își recuperează excitația și încep să-și revină. Nu au deschis site-urile preferate de porno și, prin urmare, se excită la stimuli normali la care se pierduseră anterior. Motivele pentru care au decis să se oprească în primul rând dispar rapid din gândurile lor, ca și cum ar vedea un accident rutier grav în timp ce conduc. Te va încetini pentru o vreme, dar vei călca din nou pe accelerație data viitoare când vei întârzia la o întâlnire.

De cealaltă parte a războiului se află micul monstru care încă nu și-a primit doza. Nu există durere fizică - dacă ai avea aceeași senzație din cauza unei răceli, nu te-ai opri din lucru sau ai fi deprimat, ci ai râde de ea. Tot ce știe utilizatorul este că vrea să-și viziteze haremul. Micul monstru știe acest lucru și pune în mișcare marele monstru de spălare a creierului, determinând aceeași persoană care, cu câteva ore sau zile mai devreme, enumera toate motivele pentru a se opri, să caute acum cu disperare orice scuză pentru a începe din nou. Începe să spună lucruri de genul:

- "*Viața este prea scurtă, o bombă ar putea exploda, aș putea să mă calce mâine un autobuz. Am renunțat prea târziu. Ți se spune că totul îți dă dependență în zilele noastre.*"

- "*Am ales momentul nepotrivit.*"

- "*Ar fi trebuit să aștept până după Crăciun, după sărbători/teste, după acest eveniment stresant din viața mea.*"

- "*Nu mă pot concentra, devin iritabil și irascibil, nu pot nici măcar să-mi fac treaba cum trebuie.*"

- "*Familia și prietenii mei nu mă vor mai iubi. Să recunoaștem, pentru binele tuturor trebuie să o iau de la capăt. Sunt o dependentă de sex confirmată și nu am cum să fiu din nou fericită fără orgasm.*"

- "*Nimeni nu poate supraviețui fără sex.*" (Spălat pe creier de oameni bine intenționați care nu iau în considerare distincția dintre părțile tantrice și cele propice ale sexului).

- "* Știam că se va întâmpla asta, creierul meu este "sensibilizat" de DeltaFosB datorită schimbărilor afectate de creșterile de dopamină din cauza utilizării mele excesive de porno din trecut. Sensibilizarea nu poate fi "niciodată" eliminată din creier.*"

În această etapă, utilizatorul cedează de obicei. Pornind browserul, starea de schizofrenie crește. Pe de o parte, există ușurarea extraordinară de a pune capăt dorinței, deoarece micul monstru își găsește în sfârșit doza; pe de altă parte, orgasmul este îngrozitor, iar utilizatorul nu poate înțelege de ce o face. Acesta este motivul pentru care utilizatorul crede că îi lipsește voința. De fapt, nu este vorba de lipsă de voință, tot ceea ce au făcut este să se răzgândească și să ia o decizie perfect rațională în lumina ultimelor informații.

"*Ce rost are să fii sănătos sau bogat dacă ești nefericit?*"

Absolut niciunul! Mult mai bine să ai o viață scurtă și plăcută decât una lungă și nefericită. Din fericire, acest lucru nu este adevărat pentru cei care nu sunt utilizatori, deoarece viața este infinit mai plăcută. Nefericirea de care suferă utilizatorul nu se datorează senzației de sevraj - deși este declanșată inițial de aceasta - agonia reală este lupta din minte cauzată de îndoială și incertitudine. Deoarece utilizatorul începe prin a simți că face un sacrificiu, începe apoi să se simtă lipsit, ceea ce reprezintă o formă de stres.

Unul dintre aceste momente stresante este atunci când creierul le spune să "tragă cu ochiul", dorind să se întoarcă imediat ce se opresc. Dar, pentru că s-au oprit, nu pot, iar acest lucru îi face să fie și mai deprimați și declanșează din nou declanșatorul. Un alt factor care face ca renunțarea la fumat să fie atât de dificilă este așteptarea ca ceva să se întâmple. Dacă obiectivul tău este să treci un examen de conducere, de îndată ce ai trecut examenul, este sigur că ți-ai atins obiectivul. În cadrul metodei de voință, narațiunea internă este - "*Dacă pot rezista suficient de mult timp fără pornografie pe internet, nevoia de a mă uita la ea va dispărea în cele din urmă.*" Puteți vedea acest lucru în practică pe forumurile online, unde dependenții vorbesc despre dungi sau zile de abstinență.

După cum s-a spus mai sus, agonia prin care trece utilizatorul este mentală și cauzată de incertitudine. Deși nu există o durere fizică, are totuși efecte puternice. Devenit nefericit și nesigur, utilizatorul este departe de a uita, fiind acum plin de îndoieli și temeri. 

- "Cât timp va dura această poftă?"

- "*Voi fi vreodată fericit din nou?*"

- "*Voi dori vreodată să mă trezesc dimineața?*"

- "*Cum voi face față stresului în viitor?*"

Utilizatorul așteaptă ca lucrurile să se amelioreze, dar în timp ce încă se mai deprimă, "haremul" devine din ce în ce mai prețios. De fapt, ceva *se întâmplă*, dar în mod inconștient, dacă reușesc să supraviețuiască săptămâni întregi fără să deschidă browserul, pofta pentru micul monstruleț dispare. Cu toate acestea, așa cum s-a spus anterior, durerile de sevraj de la dopamină și opioide sunt atât de ușoare încât utilizatorul nici măcar nu este conștient de ele. În acest moment, mulți utilizatori simt că au "scăpat" și astfel aruncă o privire pentru a dovedi acest lucru, trimițându-i înapoi pe toboganul de apă. După ce au furnizat dopamină în organism, există acum o voce mică în spatele minții lor care spune "*Vrei încă una.*" De fapt, au scapat, dar au inceput din nou.

Când erați copil, v-ați uitat la desene animate și, conform neuroștiinței, ați format căi neuronale (DeltaFosB) pentru acestea. Dacă ați dori să descurajați un copil să se uite la desene animate, ați studia dacă aceste căi există încă și ați chestiona adulții cu privire la motivele pentru care nu le mai place să se uite la desenele animate preferate din copilărie. În primul rând, există divertisment mai bun și, în al doilea rând, desenele animate pur și simplu nu mai au magia lor. Cu metoda voinței doar îi refuzi copilului desenul animat, dar cu EasyPeasy te asiguri, de asemenea, că acesta nu vede nicio valoare în el. Ce este mai bine?

De obicei, utilizatorul nu va intra imediat într-o altă sesiune, gândindu-se "*Nu vreau să fiu din nou dependent!*" și lasă să treacă o perioadă sigură de ore, zile sau chiar săptămâni. Fostul utilizator poate spune apoi: "*Bine, nu am devenit dependent, așa că pot avea o altă sesiune în siguranță.*" Ei au căzut din nou în aceeași capcană ca atunci când au început și sunt deja pe o pantă alunecoasă.

Utilizatorii care reușesc folosind metoda voinței tind să considere că este un proces lung și dificil, deoarece problema principală este spălarea creierului. Mult timp după ce dependența fizică a murit, utilizatorul încă se mai moțăie, nefericit. În cele din urmă, după ce supraviețuiește acestei torturi pe termen lung, începe să se dea seama că nu va ceda, oprindu-se din mobbing și acceptând că viața merge mai departe și este plăcută fără porno. Există semnificativ mai multe eșecuri decât succese, deoarece unii dintre cei care reușesc trec prin viața lor într-o stare vulnerabilă, rămasă cu o anumită spălare a creierului care le spune că pornografia le dă, de fapt, un impuls. Acest lucru explică de ce mulți utilizatori care s-au oprit pentru perioade lungi de timp sfârșesc prin a începe din nou mai târziu.

Mulți foști utilizatori vor avea ocazional o sesiune ocazională ca un "tratament special" sau pentru a se convinge cât de puternic este autocontrolul lor. Exact asta face - dar imediat ce se termină sesiunea, dopamina începe să plece și o voce mică din mintea lor începe să îi împingă spre o altă sesiune. Dacă se decid să ia parte la ea, pare să fie încă sub control, fără șocuri, escaladare sau căutare de noutate, așa că spun: "* Minunat! Deși nu-mi place cu adevărat, nu mă voi lăsa prins. După Crăciun / această sărbătoare / această traumă, mă voi opri.*". Ei nu știu că toboganele de apă ale creierului lor au fost unse și mai mult.

Prea târziu, sunt deja dependenți! Capcana din care au reușit să iasă cu ghearele și-a făcut din nou victima.

Așa cum am mai spus, nu este vorba de plăcere. Niciodată nu a fost! porno mai mult timp decât este nevoie pentru a termina fapta. Indiferent de asta, o modalitate mai bună de a te masturba este prin amintiri. Presupunem că ne bucurăm de pornografia pe internet doar pentru că nu putem crede că am fi atât de proști încât să devenim dependenți dacă nu ne-am bucurat de ea. Cei mai mulți utilizatori nu au nicio idee despre stimulii supranormali, noutatea sau căutarea de șocuri și chiar și după ce au citit despre asta, nu cred că utilizarea lor este motivată de cablarea evolutivă a circuitului de recompensă. Acesta este motivul pentru care o mare parte din pornografie este subconștientă - dacă ai fi conștient de schimbările neurologice și ar trebui să justifici că te costă bani în viitor, chiar și iluzia de plăcere ar dispărea.

Când încercăm să ne blocăm mintea la partea rea, ne simțim prost. Dacă ar trebui să ne confruntăm cu ea, ar fi intolerabil! Dacă urmăriți un utilizator în acțiune, veți vedea că este fericit doar atunci când nu este conștient că folosește. Odată ce sunt conștienți, au tendința de a se simți inconfortabil și de a se scuza. Pornografia hrănește micul monstru, astfel încât, după ce îl vei epura din corpul tău împreună cu spălarea creierului (monstrul mare), nu vei mai avea nici nevoia, nici dorința de a te uita!
