# Ferește-te de reducerea consumului

Mulți utilizatori recurg la reducerea momentelor de folosire a pornografiei ca un pas înainte spre oprire sau ca o încercare de a controla micul monstru. Mulți recomandă reducerea sau o "dietă pornografică" pentru a se revigora. Folosirea reducerii ca o piatră de hotar pentru a se opri este ***fatală.*** Aceste încercări de reducere a consumului sunt cele care ne țin prinși în capcană pentru tot restul vieții noastre. În general, întreruperea urmează încercărilor eșuate de a se opri. După câteva ore sau zile de abstinență, consumatorul spune ceva de genul

"*Nu pot face față gândului de a merge la culcare fără să-mi vizitez haremul online, așa că de acum înainte voi folosi porno doar o dată la patru zile sau îmi voi curăța colecția de "porno de prost gust". Dacă pot să urmez această dietă pornografică, pot fie să o țin acolo, fie să o reduc și mai mult.*"

Anumite lucruri teribile se întâmplă acum:

1.  Sunt blocați cu cea mai rea dintre toate lumile, încă dependenți de porno pe internet și menținând monstrul viu nu numai în corpul lor, ci și în mintea lor.

2.  Își doresc viața în așteptarea următoarei sesiuni.

3.  Înainte de a reduce, ori de câte ori doreau să-și viziteze haremul, își aprindeau browserul și își ușurau cel puțin parțial durerile de retragere. Acum, în plus față de stresul normal al vieții, ei se fac să sufere de senzația de sevraj pentru cea mai mare parte a vieții lor, ceea ce îi face și mai nefericiți și mai irascibili.

4.  În timp ce se răsfățau, nu s-au bucurat de majoritatea sesiunilor și nici nu și-au dat seama că foloseau un stimulent supranormal. A fost automat, singura vizită la harem de care s-au bucurat a fost una după o perioadă de abstinență. Acum, că așteaptă o oră în plus pentru fiecare vizită la harem, se "bucură" de fiecare. Cu cât se așteaptă mai mult, cu atât mai "plăcută" pare să devină fiecare ședință, deoarece "plăcerea" într-o sesiune nu este sesiunea în sine - ci încetarea agitației provocate de pofta - fie că este vorba de o ușoară poftă fizică sau de o melancolie mentală. Cu cât suferința este mai lungă, cu atât mai "plăcută" devine fiecare sesiune.

Principala dificultate în a te opri nu este dependența neurologică, care este ușoară. Utilizatorii se vor opri fără dificultate în diverse ocazii - moartea unei persoane dragi, afaceri familiale sau profesionale etc. Vor sta, să zicem, zece zile fără acces și nu îi deranjează. Dar dacă ar fi trecut aceleași zece zile când ar fi putut avea acces la porno, și-ar fi smuls părul din cap.

Mulți utilizatori vor avea șanse în timpul zilei de lucru și se vor abține, sau vor trece prin Victoria's Secret sau prin piscine și așa mai departe fără inconveniente nejustificate. Mulți se vor abține dacă vor fi nevoiți să doarmă temporar pe canapea pentru a face loc unui vizitator sau dacă sunt ei înșiși în vizită. Chiar și în barurile Go-Go sau pe plajele pentru nudiști nu au existat revolte. Utilizatorii sunt aproape încântați ca cineva sau ceva să le spună că nu pot viziona filme porno. De fapt, utilizatorii care vor să se lase obțin o plăcere secretă de a merge perioade lungi de timp fără vizite de harem, dându-le speranța că poate într-o zi nu vor mai dori asta.

Adevărata problemă atunci când se oprește este spălarea creierului, o iluzie de îndreptățire că pornografia pe internet este un fel de sprijin sau recompensă și că viața nu va fi niciodată la fel fără ea. Departe de a te opri de la pornografia pe internet, tot ceea ce reușește reducerea este să te lase nesigur și nefericit, convingându-te că cel mai prețios lucru de pe acest pământ este noul clip pe care l-ai ratat, că nu ai cum să fii din nou fericit fără să-l vezi. 

Nimic nu este mai patetic decât utilizatorul care încearcă să reducă consumul, suferind de iluzia că, cu cât se uită mai puțin la filme porno, cu atât va dori mai puțin să își viziteze haremul online. Invers este adevărat - cu cât se uită mai puțin la porno, cu atât mai mult suferă mai mult timp de dureri de sevraj și cu atât mai mult se "bucură" de ușurarea de a le ușura. Cu toate acestea, vor observa că genul lor preferat nu mai dă rezultate. Dar asta nu îi va opri: dacă site-urile de tuburi ar fi dedicate doar unei singure vedete sau unui singur gen, niciun utilizator nu ar merge mai mult de o dată.

Greu de crezut? Care este cel mai rău moment de autocontrol pe care îl simte cineva? Să aștepți patru zile și apoi să ai un punct culminant. Apoi, care este cel mai prețios moment pentru cei mai mulți utilizatori aflați la o dietă porno de patru zile? Exact, același punct culminant după ce a așteptat patru zile! Credeți cu adevărat că vă masturbați pentru a vă bucura de orgasm, sau explicația mai rațională că aveți nevoie să vă ușurați durerile de sevraj sub iluzia că aveți dreptul?

Îndepărtarea spălării creierului este esențială pentru a elimina iluziile despre porno înainte de a avea acea sesiune finală. Dacă nu ați eliminat iluzia că vă place înainte de a închide acea fereastră, nu aveți cum să o dovediți după aceea fără să vă prindeți din nou. Atunci când treceți peste favorite și imagini salvate, întrebați-vă unde este gloria în această acțiune. Poate credeți că doar anumite clipuri sunt de bun gust, cum ar fi cele pe teme obișnuite sau preferate. Dacă este așa, de ce să vă mai obosiți să vizionați alte clipuri sau teme? Pentru că ați căpătat acest obicei? De ce și-ar încurca cineva în mod obișnuit creierul și s-ar irosi? Nimic nu este diferit după o lună, așa că de ce ar trebui ca un clip porno să fie diferit?

Puteți testa acest lucru singur. Găsiți acel clip fierbinte de luna trecută pentru a dovedi că este diferit. Apoi, setați un memento și urmăriți același clip după o lună fără porno. Acesta va stimula (aproape) aceleași puncte ca și luna trecută. Același clip va fi diferit după un eveniment social în care sunteți refuzat sau testat de un potențial partener. Motivul este că dependentul nu poate fi niciodată pe deplin fericit dacă micul monstruleț rămâne nesatisfăcut.

Unde intervine satisfacția? Utiliztorii se simt mizerabil dacă nu-și pot ameliora simptomele de sevraj. Diferența dintre vizionarea porno și nu este diferența dintre a fi fericit și mizerabil. De aceea, pornografia pe internet pare a fi mai bună. Utilizatorii care intră pe site-urile lor la prima oră a dimineții pentru porno sunt nefericiți, indiferent dacă se uită sau nu.

Diminuarea sesiunilor nu numai că nu funcționează, dar este cea mai rea formă de tortură. Nu funcționează pentru că, inițial, utilizatorul speră că, prin faptul că își face obiceiul din ce în ce mai puțin, își va reduce dorința de a viziona porno. Nu este un obicei, ci o dependență. Natura oricărei dependențe este de a dori mai mult și mai mult, nu mai puțin și mai puțin. Prin urmare, pentru a reduce, utilizatorul trebuie să exercite voința și disciplina pentru tot restul vieții lor. Așadar, reducerea înseamnă voință și disciplină pentru totdeauna. Oprirea este mult mai ușoară și mai puțin dureroasă; există literalmente zeci de mii de cazuri în care reducerea a eșuat.

Problema opririi nu este dependența de dopamină, care este ușor de gestionat. Este convingerea greșită că pornografia îți oferă plăcere, determinată inițial de spălarea creierului primită înainte de a începe să consumăm, întărită ulterior de dependența propriu-zisă. Tot ceea ce face diminuarea nu face decât să întărească și mai mult această eroare, în măsura în care pornografia le domină complet viața și îi convinge că cel mai prețios lucru de pe pământ este dependența lor.

Cele câteva cazuri care reușesc au fost realizate printr-o perioadă relativ scurtă de reducere a consumului, urmată de o "întrerupere bruscă". Acești utilizatori s-au oprit în ciuda reducerii, nu din cauza ei. Tot ceea ce a făcut a fost să prelungească agonia, încercările eșuate lăsându-i pe consumatori epave nervoase și chiar mai convinși că sunt dependenți pe viață. De obicei, acest lucru este suficient pentru a-i face să se întoarcă la haremul lor online pentru plăcere și sprijin, sau cel puțin pentru încă o perioadă înainte de următoarea încercare.

Cu toate acestea, reducerea ajută la ilustrarea inutilității pornografiei, demonstrând în mod clar că vizitele la harem nu sunt plăcute după perioade de abstinență. Prin urmare, alegerile sunt: 

1.  Reducerea pe viață și suferința unei torturi autoimpuse, pe care oricum nu o vei putea face.

2.  Să te torturezi din ce în ce mai mult pe viață, ceea ce este inutil.

3.  Fiind drăguț cu tine însuți și eliminând complet pornografia.

Celălalt aspect pe care îl demonstrează reducerea este că nu există un astfel de lucru ca o vizită rară sau ocazională la harem. Pornografia pe internet este o reacție în lanț care va dura tot restul vieții tale, dacă nu faci un efort pozitiv pentru a o întrerupe.

** Amintiți-vă: Reducerea numarului de sesiuni vă va trage în jos.**
