# Doar o singura privire

"Doar o singură privire" este un mit pe care trebuie să ți-l îndepărtezi din minte:

- Este *doar o singură privire* cea care ne face să începem în primul rând.

- Este *doar o singură privire* care să ne ajute să trecem peste o perioadă dificilă sau la o ocazie specială care înfrânge majoritatea încercărilor noastre de a ne opri.

- Este *doar o singură privire* care, după ce am reușit să ne rupem de dependență, ne trimite înapoi în capcană. Uneori este doar pentru a confirma că nu mai au nevoie de porno și o vizită la harem face exact asta.


Efectele ulterioare ale pornografiei vor fi oribile și îi vor convinge pe utilizatori că nu vor deveni niciodată dependenți din nou - dar deja sunt. Utilizatorul simte că ceva care îl face atât de nefericit și vinovat nu ar fi trebui să duca la o sesiune, dar totuși a făcut-o. 

Gândul la "o sesiune specială" este cel care îi împiedică adesea pe utilizatori să se oprească, cea de după o călătorie lungă la conferință, o zi grea la serviciu, o ceartă cu copiii sau un incident în care partenerul tău iti respinge dorinta de a face sex. Bagă-ți în cap ***clar*** că nu există "doar o singură privire". Este o reacție în lanț care va dura tot restul vieții tale dacă nu este întreruptă. Mitul despre ocazii speciale, rare, îi ține pe utilizatori abătându-se după ce se opresc. Obișnuiește-te să nu vezi niciodată sesiunea ca ceva care "nu e mare lucru", este o fantezie. Ori de câte ori vă gândiți la pornografie, vedeți o viață murdară de petrecut veacuri întregi în spatele unui ecran pentru privilegiul de a vă distruge mental și fizic - o viață de sclavie și disperare. Nu este o crimă dacă erecțiile tale sunt nefiabile, dar este atunci când ai putea fi mai fericit pe termen lung, dar în schimb alegi să sacrifici asta pentru "plăcerea" pe termen scurt.

Este în regulă că nu putem găsi întotdeauna "ceva de făcut" pentru a umple golul; acest lucru nu este posibil în mod realist în fiecare caz, pentru întreaga noastră viață. Putem planifica pentru cele mai multe dintre ele, dar uneori se întâmplă pur și simplu. Se întâmplă și momente bune și rele, indiferent de pornografie. Dar fiti sigur ca sesiunea de pornografie nu se intampla fara stiinta voastra. Ești blocat fie cu o viață de mizerie, fie cu niciuna. Nu ai visa să iei cianură doar pentru că ți-a plăcut gustul de migdale, așa că nu te mai pedepsi cu sesiunea ocazională de "ma voi uita doar odata, nu e mare lucru". Întrebați un consumator cu probleme: "*Dacă ați avea ocazia să vă întoarceți în timp, înainte de a deveni dependent, ați fi devenit consumator?*" Răspunsul este inevitabil: "*Trebuie să glumești!*" Cu toate acestea, fiecare utilizator are această alegere în fiecare zi din viața sa, așa că de ce nu optează pentru ea? Răspunsul este frica, teama că nu se pot opri sau că viața nu va mai fi la fel fără el.

Nu vă mai faceți iluzii! Poți să o renunti, oricine poate. Este ridicol de ușor, dar pentru a face acest lucru, există anumite principii fundamentale care trebuie să îți fie clare în minte.

1.  Nu renunti la nimic de valoare, dar in schimb primesti lucruri minunate.

2.  Nu vă convingeți niciodată de sesiunea ocazională de "nu-i mare lucru" sau de "doar o privire". Acestea nu există. Există doar o viață întreagă de mizerie și sclavie.

3.  Nu este nimic diferit la tine; orice utilizator poate găsi ușor să se oprească.

Mulți consumatori cred că sunt dependenți confirmați sau că au personalități dependente. Acest lucru se întâmplă de obicei ca urmare a citirii unor cantități excesive de materiale șocante. Nu există așa ceva, nimeni nu se naște cu nevoia de a se masturba la clipuri video înainte de a deveni dependent. Drogul este cel care te prinde, nu natura caracterului sau a personalității tale. Natura stimulilor supranormali care creează dependență te face să crezi că așa stau lucrurile. Cu toate acestea, este esențial să înlături această convingere, deoarece dacă crezi că ești dependent, vei fi, chiar și după ce micul monstru din corpul tău a murit de mult. Este esențial să îndepărtezi toată această spălare a creierului.
