# Utilizatori ocazionali


Utilizatorii extremi au tendința de a invidia utilizatorii ocazionali de pornografie. Cu toții am întâlnit aceste personaje: "*Oh, pot să stau toată săptămâna fără o sesiune, nu mă deranjează cu adevărat.*" Ne-am dori să fim așa. Poate fi greu de crezut, dar niciunui utilizator nu-i place să fie un utilizator. Nu uitați niciodată:  


| Niciun utilizator nu a decis vreodată să devină unul, ocazional sau nu, de aceea...

| Toți utilizatorii se simt proști, de aceea...

| Toți utilizatorii trebuie să se mintă pe ei înșiși și pe alții într-o încercare zadarnică de a-și justifica prostia.


Pasionații de golf se laudă cu cât de des joacă și cât de des vor să joace, așa că de ce se laudă utilizatorii cu cât de puțin se masturbează? Dacă acesta este adevăratul criteriu, atunci, cu siguranță, lauda este să nu te masturbezi deloc, nu-i așa?

Dacă cineva ți-ar spune: "*Pot să stau toată săptămâna fără morcovi și nu mă deranjează câtuși de puțin*", ai crede că vorbești cu un nebun. Dacă mi-ar plăcea morcovii, de ce aș vrea să stau toată săptămâna fără ei? Dacă nu mi-ar plăcea, de ce aș face o astfel de afirmație? Așadar, atunci când un utilizator face un comentariu despre faptul că a supraviețuit o săptămână fără o sesiune, încearcă să se convingă pe sine - și pe tine - că nu are o problemă. Dar nu ar fi fost nevoie să facă o declarație dacă nu ar fi avut o problemă. Tradus, acest comentariu este "*Am reușit să supraviețuiesc o săptămână întreagă fără porno.*" Ca fiecare utilizator, în speranța că, după aceasta, ar putea supraviețui restul vieții lor. Dacă doar a reușit să supraviețuiască o săptămână, vă puteți imagina cât de prețioasă trebuie să fi fost sesiunea de după, după ce s-a simțit lipsit de o săptămână întreagă?

Acesta este motivul pentru care utilizatorii ocazionali sunt efectiv mai dependenți decât cei care folosesc foarte mult. Nu numai că iluzia plăcerii este mai mare, dar au și mai puține motive să renunțe, pentru că petrec mai puțin timp cu ei și, prin urmare, sunt mai puțin vulnerabili la riscurile pentru sănătate. Ocazional, aceștia pot experimenta disfuncții sexuale, dar nu sunt siguri de cauza lor și astfel sunt puși pe seama altor factori. Nu uitați că singura plăcere pe care o obțin consumatorii este în ciclul de căutare a dopaminei și în ameliorarea senzației de sevraj, așa cum s-a explicat deja. Plăcerea este o iluzie - imaginați-vă micul monstru porno ca o mâncărime aproape imperceptibilă de care rămânem inconștienți în cea mai mare parte a timpului.

Dacă aveți o mâncărime permanentă, tendința naturală este de a o scărpina. Pe măsură ce circuitele de recompensă devin din ce în ce mai imune la dopamină și la opioide, tendința naturală este de a se mărgini, de a escalada, de a se îmbuiba, de a căuta noutăți, de a căuta șocuri etc. Există patru factori principali care îi împiedică pe utilizatori să vizioneze în lanț.

**Timpul.**
Cei mai mulți nu își pot permite să o facă.

**Sănătate.**
Pentru a ne ușura senzația de mâncărime, trebuie să consumăm toate materialele gratuite disponibile și chiar mai mult. Capacitatea de a face față acestui tip de îmbuibare variază în funcție de fiecare individ, în momente și situații diferite din viața lor. Acest lucru acționează ca o constrângere automată.

**Disciplină.**
Disciplina este impusă de societate, de locul de muncă al utilizatorului, de prieteni și rude, sau poate chiar de către utilizatorul însuși, ca urmare a luptei naturale care are loc în mintea fiecărui utilizator.

**Imaginație.**
Lipsa de imaginație minimizează șocul, noutatea și alte valori ale clipului pe o bază subiectivă.

Este ușor să ne gândim la utilizatorii "non-casuali" ca fiind slabi, incapabili să înțeleagă de ce alții sunt capabili să își limiteze "consumul". Cu toate acestea, utilizatorii extremi ar trebui să țină cont de faptul că majoritatea utilizatorilor ocazionali sunt pur și simplu incapabili de a viziona în lanț, ceea ce necesită o imaginație și o rezistență foarte puternice. Unii dintre acești utilizatori o dată pe săptămână, pe care utilizatorii grei tind să îi invidieze, sunt fizic incapabili să facă mai mult, sau pentru că locul de muncă, societatea sau propria ură de a deveni dependenți nu le permit acest lucru.

Ar putea fi avantajos să se ofere câteva definiții.

**Neutilizatorul**

Cineva care nu a căzut niciodată pradă capcanei, dar care nu ar trebui să se complice. Ei sunt non-utilizatori doar prin noroc sau prin harul bunătății. Toți utilizatorii au fost convinși că nu vor deveni niciodată dependenți, iar unii non-utilizatori continuă să încerce o sesiune ocazională.

**Utilizatorul ocazional**

Dintre care există două clasificări de bază:

1.  Utilizatorul care a căzut în capcană, dar nu-și dă seama de asta - nu invidiați astfel de utilizatori. Aceștia nu fac decât să guste nectarul de la gura ulciorului și, după toate probabilitățile, vor deveni în curând mari consumatori. Nu uitați, așa cum toți alcoolicii au început ca băutori ocazionali, tot așa și toți consumatorii încep ocazional.

2.  Utilizatorul care a fost anterior un consumator intensiv, și astfel crede că nu se poate opri. Acești utilizatori sunt cei mai triști dintre toți și se încadrează în diverse categorii, fiecare dintre ele necesitând un comentariu separat.

**Utilizatorul de o dată pe zi**

Dacă se bucură de dreptul lor la orgasm, de ce folosesc porno pe internet doar o dată pe zi? Dacă o pot lua sau o pot lăsa, de ce să se deranjeze deloc? Amintiți-vă, "obiceiul" este - în realitate - să vă dați cu capul de perete pentru a vă relaxa la oprire. Utilizatorul o dată pe zi își ușurează durerile de sevraj pentru mai puțin de o oră în fiecare zi. Deși nu este conștient, restul zilei și-l petrece dându-se cu capul de acest perete, făcând acest lucru pentru cea mai mare parte a vieții. Consumă o dată pe zi pentru că nu pot risca să fie prinși sau să se joace cu sănătatea lor neurologică. Este ușor să convingi un consumator intensiv că nu se bucură, dar semnificativ mai greu să convingi un consumator ocazional. Oricine a trecut printr-o încercare de a reduce consumul știe că este cea mai rea tortură dintre toate și aproape garantat că te va menține dependent pentru tot restul vieții.

**Utilizatorul respins**

Își cer dreptul de a avea orgasm în fiecare zi, dar partenerul lor sexual nu este întotdeauna fericit să îndeplinească cererea. Inițial, folosesc pornografia pe internet pentru a umple acest gol, dar după ce iau "toboganul de apă" excitant, sunt prinși într-un ciclu de noutate, șoc, imagini supranormale etc. De fapt, ei sunt fericiți cu respingerea partenerului lor, deoarece le oferă un fel de scuză. Dacă pornografia pe internet îți oferă atât de mult, de ce să te mai obosești să ai un partener? Eliberați-i în schimb. Nici măcar nu se bucură de sesiuni când trebuie să-și "poarte" partenerul în minte. La un moment dat, ei caută partenerul din viața reală pentru a le oferi o scuză pentru a se aventura în văile întunecate ale internetului.

**Utilizatorul de dietă pornografică**

Cunoscut și ca: "*Pot să mă opresc oricând vreau. Am făcut-o de mii de ori!*".

Dacă ei cred că dieta îi ajută să aibă chef de agățat partenere, de ce mai țin dieta de "o dată la patru zile? De asemenea, dacă "masturbarea ocazionala" este bună pentru a elibera tensiunea, de ce să nu se facă în fiecare zi? S-a dovedit că masturbarea nu este necesară pentru a menține organele genitale sănătoase, iar pornografia pe internet nu este necesară deloc. Chiar dacă ar fi așa, niciun "guru" de pick-up-artist care a citit despre daunele neurologice nu va recomanda vreodată vizionarea de porno cu super-stimuli. Adevărul este că utilizatorul de dietă porno este încă dependent. Deși au scăpat de dependența fizică, au rămas cu problema principală a spălării creierului. Ei speră de fiecare dată că se vor opri definitiv, dar în curând cad din nou în aceeași capcană.

Cei mai mulți consumatori îi invidiază de fapt pe acești utilizatori care incep si se opresc des și se gândesc la cât de "norocoși" sunt cei care țin dietă pentru că reușesc să își controleze consumul. Cu toate acestea, ei trec cu vederea faptul că persoana care ține dietă nu își controlează consumul - atunci când consumă, își doresc să nu o facă. Aceștia trec prin complicația de a se opri, apoi încep să se simtă privați și cad din nou în capcană, dorindu-și să nu o fi făcut. Au parte de ceea ce este mai rău din ambele lumi. Dacă vă gândiți bine, acest lucru este valabil în viața utilizatorilor atunci când li se permite să aibă o sesiune - să o ia ca pe un drept sau să-și dorească să nu o facă. Doar atunci când este privat, pornografia devine prețioasă. Sindromul "fructului interzis" este una dintre dilemele îngrozitoare pentru utilizatori. Ei nu pot câștiga niciodată pentru că se tânguiesc după un mit, o iluzie. Există doar o singură cale prin care pot câștiga, oprindu-se din jale prin oprirea porno!

**Utilizatorul "Mă uit doar la porno static/ de casă/ de tip "cuviincios "**.

Da, toată lumea face acest lucru pentru început, dar nu este uimitor cum valoarea medie de șoc a clipurilor pare să crească rapid și, înainte de a ne da seama, ne simțim privați (toleranță)? Noutatea lipsește cu pornografia statică, așa că incepem sa folosim pornografie cu valoare crescuta de soc, astfel aducand in viata noastra resentimente și vinovăție. Cel mai rău lucru pe care îl puteți face este să folosiți imaginile partenerului (cu aprobare, desigur) pentru masturbare. De ce? Pentru că, în acest proces, îți cablați creierul pentru bufeurile de dopamină induse de căutare, căutare și varietate. Din punct de vedere chimic,  DeltaFosB se acumulează pe circuitele asociate cu pornografia, așa că te vei trezi că ai dificultăți atunci când ești cu ei în timp real.

O altă capcană din această categorie este pornografia "amatoare" și "artizanală". Cele mai multe sunt falsuri și știi asta, în plus, nici nu te vei opri la primul care îți sare în ochi, ci vei continua să cauți și să cauți. Nu uitați, nu doar orgasmul este cel pe care îl caută creierul, ci și noutatea vânătorii care dă emoția toboganului de apă. Conținutul porno nu este problema - fie că este vorba de amatori sau profesioniști - ci de fluxurile de dopamină din creier care provoacă acumularea de toleranță și sațietate. Pornografia distruge funcționarea normală a creierului, masturbarea derutând răspunsul musculo-cerebral; orgasmul inundă creierul cu opioide și face ca traseul să fie mai ușor de urmat data viitoare.

**Utilizatorul "M-am oprit, dar arunc ocazional o privire" **.

Într-un fel, utilizatorii care trag cu ochiul sunt cei mai patetici dintre toți. Fie își duc viața crezând că sunt privați, fie, cel mai adesea, tracul ocazional se transformă în două, alunecând în jos pe panta alunecoasă, mai devreme sau mai târziu căzând din nou în situația de mari consumatori. Au căzut din nou în aceeași capcană în care au căzut de la început.

Există alte două categorii de utilizatori ocazionali. Prima este tipul care se masturbează la imagini sau clipuri cu cele mai recente înregistrări sexuale ale celebrităților care apar la știri sau la ceva ce au "adus acasă" de la vizionarea "accidentală" la școală sau la serviciu. Acești oameni sunt de fapt doar ne-utilizatori, dar au impresia că pierd ceva. Ei vor să fie parte din acțiune, majoritatea dintre noi începând astfel. Data viitoare, observați că, după un timp, celebritatea fanteziei dvs. nu vă mai face plăcere. Cu cât este mai "de neatins" ținta fanteziei tale, cu atât mai frustrantă este retragerea orgasmului.

A doua categorie a captat atenția recent, cel mai bine descrisă prin conturarea unui caz împărtășit online.

O femeie citise povești porno pe internet de mulți ani și nu folosise aceste povesti  mai mult sau mai puțin de o dată în fiecare noapte. De altfel, era o doamnă cu o voință foarte puternică. Majoritatea utilizatorilor s-ar întreba de ce a vrut să se oprească în primul rând - subliniind cu plăcere că nu exista niciun risc de PIED, sau PE în cazul ei (neadevărat). Ea nici măcar nu folosea imagini statice, poveștile fiind mult mai blânde decât orice material pe care ei înșiși îl folosesc zilnic.

Aceștia fac greșeala de a presupune că utilizatorii ocazionali sunt mai fericiți și mai stăpâni pe situație. S-ar putea să fie mai stăpâni pe situație, dar cu siguranță nu sunt fericiți. În cazul femeii, aceasta nu era mulțumită nici de partenerul ei, nici de sexul real și era extrem de iritabilă atunci când răspundea la stresul și tensiunile zilnice. Apropiații ei nu reușeau să-și dea seama ce o deranja. Chiar dacă s-a convins să nu se teamă de utilizarea ei prin raționalizare, tot nu se găsea în stare să se bucure de relații reale, care implică invariabil suișuri și coborâșuri. Centrul de recompensă al creierului ei era incapabil să se folosească de destresoarele normale prezente în viață ca urmare a inundației zilnice de dopamină. Reglarea ulterioară a receptorilor cerebrali o făcuse să devină melancolică în majoritatea circumstanțelor. La fel ca majoritatea, ea avea o mare teamă de partea întunecată a pornografiei și de tratamentul femeilor - înainte de prima ei experiență. În cele din urmă, a căzut victimă a spălării creierului data de sociatate și a încercat primul ei site. Spre deosebire de majoritatea celor care capitulează și devin utilizatori în lanț, la vederea clipurilor murdare de violență, ea a rezistat derapajului.

Singurul lucru de care te bucuri vreodată în porno este să pui capăt poftei , fie că este vorba de pofta fizică aproape imperceptibilă, fie de tortura mentală de a nu i se permite să se scarpine "mâncărimea". Pornografia pe internet în sine este o otravă, motiv pentru care suferiți doar iluzia de a vă bucura de ea după perioade de abstinență. În mod similar cu foamea sau setea, cu cât o suferiți mai mult timp, cu atât mai mare este plăcerea atunci când în cele din urmă este ușurată. Făcând greșeala de a crede că pornografia este doar obișnuință, ei gândesc: "*Dacă o pot menține la un anumit nivel sau doar la ocazii speciale, creierul și corpul meu o vor accepta. Apoi, pot continua să consum la acel nivel sau pot să îl reduc și mai mult dacă doresc.*".

Înțelegeți clar în mintea voastră, "obiceiul" nu există. Pornografia este dependența de droguri, tendința naturală fiind aceea de a ușura durerile de sevraj, nu de a le suporta. Pentru a o menține la nivelul la care vă aflați în prezent, ar fi necesar să exercitați cantități enorme de disciplină și voință pentru tot restul vieții. Pe măsură ce centrul de recompensă al creierului dumneavoastră devine tolerant la dopamină și opioide, acesta vrea din ce în ce mai mult, nu din ce în ce mai puțin.
Pe măsură ce pornografia începe să-ți distrugă treptat sistemul nervos, curajul, încrederea și controlul impulsurilor, devii din ce în ce mai incapabil să reziști la reducerea intervalului dintre fiecare sesiune. Acesta este motivul pentru care, în primele zileale dependentei putem sa consumam foarte putin. Dacă primim un semn că ceva nu este în regulă din punct de vedere mental sau fizic, pur și simplu ne oprim. Nu o invidiați pe această femeie - atunci când vă uitați doar o dată la douăzeci și patru de ore, pare să fie cel mai prețios lucru de pe pământ, transformând pornografia într-un "fruct interzis". Timp de mulți ani, această biată femeie a fost în centrul unui război intre doua parti.

Deși era incapabilă să se oprească din consum, îi era frică să escaladeze la clipuri de streaming. Timp de douăzeci și trei de ore și zece minute din fiecare dintre aceste zile, ea a trebuit să lupte cu tentația și cu lipsa de sentimente față de iubitul ei. A fost nevoie de o voință extraordinară pentru a face ceea ce a făcut, ceea ce a redus-o în cele din urmă la lacrimi. Astfel de cazuri sunt rare, dar priviți-o logic: fie există un mecanism de suport sau o plăcere autentică în porno, fie nu există. Dacă există, cine vrea să aștepte o oră, o zi sau chiar o săptămână? De ce ar trebui să fiți privați de cârja sau plăcerea între timp? Dacă nu există o cârjă sau o plăcere autentică, de ce să te deranjezi să faci o vizită la haremul tău online?

Iată un alt caz al unui bărbat care apare o dată la patru zile, descriindu-și viața în felul următor:

> "* Am patruzeci de ani, am suferit PIED (disfuncție erectilă indusă de pornografie) cu femei reale și chiar și atunci când folosesc porno, care este cea mai mare parte a timpului. A trecut ceva timp de când am avut o erecție completă. Înainte de a merge la dieta porno o dată la patru, obișnuiam să dorm liniștit toată noaptea după sesiunea mea. Acum mă trezesc la fiecare oră din noapte și este tot ce mă pot gândi. Chiar și atunci când dorm, visez la clipurile mele preferate. În zilele de după sesiunea mea programată mă simt destul de abătut, dieta luându-mi toată energia. SO-ul meu m-ar lăsa singură pentru că sunt foarte irascibilă și dacă nu poate pleca, nu mă vrea în casă. Ies la alergat afară, dar mintea mea este obsedată de asta.*.
>
> "*În ziua programată încep să fac planuri mai devreme în timpul nopții, devenind foarte iritată dacă se întâmplă ceva împotriva planurilor mele. Mă retrag din conversații și cedez (doar pentru a regreta mai târziu) la serviciu și acasă. Nu sunt un tip certăreț, dar nu vreau ca subiectul sau conversația să mă rețină. Îmi amintesc de ocazii în care mă luam la bătaie prostește cu SO-ul meu. Aștept ora zece și când sosește îmi tremură mâinile incontrolabil. Nu încep imediat fapta - pentru că sunt videoclipuri noi care au fost adăugate - și "fac cumpărături". Mintea mea îmi spune că, din moment ce m-am înfometat timp de patru zile, merit un clip "special" care trebuie să merite timpul petrecut căutând. În cele din urmă mă mulțumesc cu unul sau două, dar vreau să dureze pentru a putea 'supraviețui' în următoarele patru zile, așa că îmi iau mai mult timp pentru a termina fapta.*"  

Pe lângă celelalte probleme pe care le are, bietul om habar nu are că se tratează cu otravă. Mai întâi, suferă de "sindromul fructului interzis" și apoi își forțează creierul să elimine dopamina. Comparativ, receptorii săi de dopamină nu sunt la fel de reduși, dar el unge toboganele de apă pornografică, căutând, căutând edging, noutate, varietate, șoc și anxietate pentru a supraviețui în următoarele patru zile. Probabil că vă imaginați acest om ca pe un imbecil patetic, dar nu este așa. Ca fost atlet și sergent de marină, el nu a vrut să devină dependent. Cu toate acestea, la întoarcerea din război, el s-a antrenat ca tehnician IT într-un program de dezintoxicare pentru veterani. 

Când a intrat în câmpul muncii în sectorul civil, era un profesionist IT bine plătit într-o bancă și i s-a dat un laptop pe care să îl ia acasă. A fost anul în care celebrii mondeni și-au "scurs" videoclipurile porno online și s-a vorbit mult despre asta. A devenit apoi dependent, petrecându-și restul vieții plătind până la refuz și ruinându-se fizic și psihic. Dacă ar fi fost un animal, societatea l-ar fi scăpat de mult timp de suferință, însă noi încă permitem ca tineri adolescenți sănătoși din punct de vedere mental și fizic să devină dependenți. Poate credeți că acest caz și notele sunt exagerate, dar acest caz - deși extrem - este departe de a fi unic. Există zeci de mii de povești similare. Puteți fi siguri că niciunul dintre prietenii și cunoscuții săi nu l-a invidiat pentru că este un om care se întâmplă o dată la patru? Dacă credeți că acest lucru nu vi s-ar putea întâmpla și dumneavoastră, **nu vă mai amăgiți.**

**SE ÎNTÂMPLĂ DEJA.

Ca și alți dependenți, utilizatorii de pornografie sunt mincinoși notorii, chiar și față de ei înșiși. Ei trebuie să fie. Cei mai mulți utilizatori ocazionali se complac de mult mai multe ori și cu mult mai multe ocazii decât vor recunoaște. Multe conversații cu așa-numiții utilizatori "de două ori pe săptămână" vor recunoaște că au făcut-o de mai mult de trei sau patru ori în acea săptămână. Citiți poveștile reddit, NoFap și rebooting-forum de la utilizatorii ocazionali și veți descoperi că fie numără zilele, fie așteaptă să eșueze. Nu trebuie să invidiați utilizatorii ocazionali și nici nu trebuie să folosiți, viața este infinit mai dulce fără ea. Luați următorul jurnal:

"*A început cu o simplă provocare de a nu-mi atinge junk-ul timp de o zi și de a fi incapabil. Nu mă mai gândesc la masturbare, nu-mi trece prin minte. Este posibil, vă promit. Bogățiile care îi așteaptă pe cei care sunt capabili - sunt incredibile.*"

Adolescenții sunt în general mai greu de vindecat, nu pentru că le este mai greu să se oprească, ci pentru că nu cred că sunt dependenți sau se află în stadiile inițiale ale capcanei, suferind în general de iluzia că se vor fi oprit automat înainte de cea de-a doua etapă.

Părinții copiilor care detestă pornografia pe internet nu ar trebui să aibă un fals sentiment de siguranță. Toți copiii detestă părțile întunecate ale pornografiei înainte de a deveni dependenți. La un moment dat, și tu ai făcut-o. Nu vă lăsați păcăliți nici de campaniile de alarmă, capcana este aceeași ca întotdeauna. Copiii știu că pornografia pe internet este un stimulent supranormal, dar ei știu, de asemenea, că o "vizită" sau o "privire" nu va fi suficientă. La un moment dat, ei pot fi influențați de un partener, de un coleg de clasă sau de serviciu.

Vă rugăm să nu deveniți mulțumiți în această privință. Eșecul societății de a împiedica adolescenții să devină dependenți de pornografia pe internet și de alte droguri este poate cea mai îngrijorătoare fațetă a acestei dependențe. Creierele adolescenților sunt semnificativ mai plastice și este necesar să le educăm și să le protejăm. Dacă nu sunteți sigur de unde să începeți, printre resursele bune se numără cartea YourBrainOnPorn.com pentru a vă educa în domeniul neuroștiinței. Chiar dacă bănuiți că adolescentul dvs. ar putea fi deja dependent, cartea oferă o înțelegere fundamentală pentru a ajuta pe cineva să scape. În rest, recomandați această carte!
