# Un obicei social?

Sănătatea minții și a corpului sunt principalele motive pentru care *ar trebui* să ne oprim - dar întotdeauna au fost. De fapt, nu avem nevoie de cercetări științifice și cunoștințe în domeniul neuroștiinței pentru a ne spune că pornografia creează dependență și ne poate distruge  viețile. Aceste corpuri ale noastre sunt cele mai sofisticate obiecte de pe planetă și orice utilizator știe de la prima sesiune că stimulii pot merge în exces și se pot transforma în otravă.

Singurul motiv pentru care ne implicăm vreodată în pornografie este suprapunerea peste programarea noastră evolutivă. Pornografia pe internet este extrem de disponibilă, gratuită și difuzată douăzeci și patru de ore pe zi. Pornografia a fost considerată cândva inofensivă, dar asta se întâmpla când imaginile erau statice, iar videoclipurile implicau un drum la magazinul local pentru o casetă VHS.
Astăzi, se consideră în general - chiar și de către utilizatorii înșiși - că pornografia este un stimulent supranormal și că formează dependență. Pe vremuri, bărbatul puternic nu recunoștea că se masturbează, nesimțit fiind un termen depreciativ. În fiecare pub, club sau bar, majoritatea bărbaților ar fi dorit cu mândrie să ia o femeie acasă și să facă sex adevărat. Astăzi, poziția este complet inversată pentru dependentul de pornografie pe internet. Bărbatul de astăzi își dă seama că începe să simtă că nu are nevoie de o femeie. Reunindu-se online, el discută experiențe, elaborează strategii și explorează opțiuni. Bărbatul puternic de astăzi nu vrea să depindă de droguri. Prin intermediul revoluției sociale, toți utilizatorii se gândesc serios la oprirea pornografiei pe internet și a masturbării. Utilizatorii de astăzi consideră că pornografia este o activitate inutilă și dăunătoare.

Cea mai semnificativă tendință observată pe forumuri este accentul din ce în ce mai mare pus pe aspectele antisociale ale porno, zilele în care un bărbat se lăuda că are sex și orgasme în fiecare zi sunt încet înlocuite cu realizarea sclaviei față de monstrul porno.

Singurul motiv pentru care oamenii continuă după ce au fost educați este pentru că nu au reușit să se oprească sau sunt prea speriați să încerce. Există un spectru larg de interes pentru acest subiect, unii abținându-se de la pornografie, masturbare și orgasm - cu sau fără partener. Practicile care separă părțile tantrice și cele de propagare a sexului, cum ar fi retenția de spermă și Karezza, sunt discutate și adoptate în masă. Multe dintre eșecurile menționate mai sus sunt, în realitate, căderi în față, aducând astfel un oarecare beneficiu persoanelor care le practică. Odată ce începeți traseul no-PMO, veți găsi cea mai bună potrivire care se aplică vieții dumneavoastră; este încurajat să vă concepeți propriul plan privind orgasmele după ce înțelegeți și practicați separarea sexuală. Oricare ar fi traseul tău, vei vedea valoarea limitării numărului de ori când îți inundă creierul cu substanțe chimice prin orgasm și nu vei mai vedea niciodată pornografia, sexul și orgasmul ca pe o plăcere sau o cârjă pentru sinele tău emoțional. 

Diferite comunități online populare fondate de non-utilizatori sunt dedicate renunțării nu numai la pornografie, ci și la masturbare. Aceste site-uri sunt în cele din urmă benefice pentru cei care evadează, dar majoritatea notelor le indică să încerce voința. Consecința obsesiei cu dungi de abstinență și alte măsuri este autocompătimirea și lipsa de euforie. O mare parte din spălarea creierului rămâne vie și sănătoasă. În cele din urmă, cineva cedează și are loc un efect de domino, alți consumatori aflând că nu sunt singurii. Cu toate acestea, eforturile lor nu sunt în zadar, ei cad înainte, deși cu multă autotorturare, pe măsură ce își închid browserele, dar nu și dorința și nevoia. EasyPeasy funcționează în sens invers, închizând mai întâi nevoia și dorința, înainte de a închide browserul. În fiecare zi, tot mai mulți utilizatori părăsesc corabia care se scufundă, iar cei rămași pe ea devin îngroziți că vor fi ultimii.

**NU TE LASA PACALIT DE PMO!**
