# Timing

În afară de faptul evident că nu vă face bine și că acum este momentul potrivit pentru a vă opri, momentul este important. Societatea tratează pornografia pe internet ca pe un obicei ușor dezagreabil care nu dăunează sănătății. Acest lucru nu este adevărat. Este o dependență de droguri, o boală și un distrugător de relații în societate. Cel mai rău lucru care se întâmplă în viața celor mai mulți utilizatori este să devină dependenți de această dependență îngrozitoare. Dacă rămân dependenți, se întâmplă lucruri îngrozitoare. Timpul este, prin urmare, important pentru a vă da dreptul la un tratament adecvat.

În primul rând, identificați momentele sau ocaziile în care pornografia pare să fie importantă pentru dumneavoastră. Dacă sunteți un om de afaceri care îl folosește pentru iluzia eliberării de stres - alegeți o perioadă relativ liniștită sau o vacanță. Dacă folosiți pornografia în principal în perioadele plictisitoare sau de relaxare, se aplică opusul. Indiferent, luați în serios încercarea și faceți din ea cel mai important lucru din viața dumneavoastră.

Priviți în perspectivă pentru o perioadă de trei săptămâni și încercați să anticipați orice eveniment care ar putea duce la eșec. Ocazii precum deplasările la conferințe, faptul că partenerul dvs. este plecat din oraș etc. nu trebuie să vă descurajeze, cu condiția să le anticipați din timp și să nu simțiți că veți fi privați. Nu încercați să reduceți între timp, deoarece acest lucru nu va face decât să vă creeze iluzia că a fi privat este plăcut. De fapt, vă ajută să vă forțați să vizionați și să aveți cât mai multe sesiuni porno. În timp ce aveți ultima sesiune și ultima dată, fiți atenți la dezamăgirea datorată sațiozității, la așteptările neîmplinite, la orice durere corporală, la efectele de retragere, la pișcături și la melancolie. Gândiți-vă la cât de minunat va fi când vă veți permite să nu mai faceți asta.

**CU ORICE AȚI FACE, NU CĂDEȚI ÎN CAPCANA DE A SPUNE DOAR "NU ACUM, MAI TÂRZIU" ȘI DE A O SCOATE DIN MINTE. ÎNTOCMEȘTE-ȚI ACUM UN PROGRAM ȘI AȘTEAPTĂ CU NERĂBDARE. **.
Remember, *you aren't giving anything up*. On the contrary, you're about to receive marvellous positive gains.

Ani de zile, profesia medicală a considerat porno ca fiind inofensivă, fără să știe care este diferența dintre porno static de odinioară și cea mai recentă experiență de streaming în realitate virtuală. Problema este că, deși fiecare utilizator consumă pornografie pe internet pur și simplu pentru a ameliora pofta de dopamină provocată de aceasta, nu dependența de substanța chimică este cea care îl prinde pe utilizator, ci auto-spălarea creierului rezultată din dependență. O persoană inteligentă se va lăsa păcălită de un truc de încredere, dar numai un prost ar continua să se lase păcălit după ce își dă seama de truc. Din fericire, majoritatea utilizatorilor nu sunt proști, ci doar cred că sunt. Fiecare utilizator în parte are propria spălare a creierului. De aceea, se pare că există o gamă atât de diversă de tipuri de dependenți, ceea ce nu face decât să agraveze și mai mult misterele.

Deși beneficiul cărții originale a fost renunțarea la nicotină (unul dintre cele mai rapide și mai dependente droguri cunoscute de om), a fost plăcut surprinzător să realizez că filozofia propusă în cartea originală este încă solidă atunci când este adaptată. Cunoștințele acumulate și provocarea pe care Carr și cu mine o asumăm este cum să comunicăm aceste cunoștințe fiecărui utilizator în parte. Faptul că știu că fiecare utilizator nu numai că poate găsi ușor să se oprească, dar poate chiar să se bucure de acest proces, este nu numai inutil, ci și extrem de frustrant, dacă utilizatorul nu poate fi făcut să realizeze acest lucru. În cartea sa originală, Allen Carr își explică sfatul său controversat:

>"Mulți oameni mi-au spus: *'Spui: "Continuă să fumezi până termini cartea." Acest lucru tinde să îl facă pe fumător să întârzie mult timp să citească cartea sau pur și simplu să nu o termine. Punct. Prin urmare, ar trebui să schimbați instrucțiunile. "* Sună logic, dar știu că dacă instrucțiunile ar fi fost: *"Opriți-vă imediat "*, unii fumători nici măcar nu ar începe să citească cartea. Un fumător m-a consultat în primele zile. El a spus: *'Chiar mă deranjează că trebuie să vă cer ajutorul, știu că am o voință puternică. În orice alt domeniu al vieții mele dețin controlul. De ce toți ceilalți fumători se lasă de fumat folosindu-și propria voință, dar eu trebuie să vin la dumneavoastră? "* El a continuat: *"Cred că aș putea s-o fac singur, dacă aș putea fuma în timp ce o fac. "* "*

Credința socială dictează că renunțarea la fumat este incredibil de dificilă, deci de ce are nevoie un fumător când ceva este dificil? De micul nostru prieten, de cârja noastră. Scăparea de fumat pare a fi o dublă lovitură: nu numai că există o sarcină dificilă de îndeplinit - ceea ce este destul de greu - dar cârja pe care ne bazăm în mod normal pentru astfel de ocazii nu este disponibilă. Poate că adevărata frumusețe a acestei metode este că nu trebuie să "renunți" în timp ce treci prin acest proces. În schimb, scăpăm inițial de toate temerile și îndoielile, astfel încât, la terminarea ultimei sesiuni, vă bucurați deja de libertate.

Prin urmare, acest manual va păstra aceleași sfaturi intacte. Indiferent cât de mult se spune că va fi ușor și plăcut, va exista o mare majoritate care nu va putea accepta acest lucru din cauza spălării personale a creierului cu privire la cât de dificil este să renunți la fumat.

Sincronizarea este singurul capitol care mă face să pun serios la îndoială sfatul inițial al lui Allen. Mai presus de toate, dacă printre factorii declanșatori se numără stresul de la birou, atunci alegerea unei vacanțe pentru a face o încercare, și invers. Aceasta nu este cea mai ușoară cale, alegând în schimb ceea ce considerați a fi cel mai *dificil* moment. Fie că este vorba de stres, obligații sociale, concentrare sau plictiseală, odată ce ai dovedit că faci față și te bucuri de viață în cele mai rele situații, orice altă situație este plăcută. Dar dacă acesta ar fi sfatul, ai face măcar o încercare?

Iată o analogie. Eu și sora mea intenționăm să înotăm împreună. Ajungem la piscină în același timp, dar rareori ajungem să înotăm împreună. Motivul este că ea își scufundă un deget de la picior și jumătate de oră mai târziu înoată efectiv. Asta e o tortură lentă. Știu dinainte că, la un moment dat, indiferent cât de rece este apa, va trebui să o înfrunt la un moment dat. Așa că am învățat să o fac în modul cel mai simplu: să mă scufund direct în apă. Acum, imaginați-vă dacă aș fi în poziția de a insista că, dacă nu se scufundă direct în apă, nu știe să înoate. Dacă ar fi așa, nu ar mai înota deloc. Vedeți care este problema?

Din feedback-ul primit, mulți utilizatori au folosit sfatul inițial de sincronizare pentru a întârzia ceea ce ei cred că va fi "ziua cea rea". Următoarele mele gânduri au fost de a folosi o tehnică similară cu cea din capitolul "avantajele pornografiei", ceva de genul - *"Sincronizarea este foarte importantă și în capitolul următor veți fi sfătuiți cu privire la cel mai bun moment pentru a face încercarea. "* și pe pagina următoare există doar un masiv *"ACUM!"* Acesta este, de fapt, cel mai bun sfat, dar l-ați urma? Poate că cel mai subtil aspect al capcanei este acela că, atunci când avem un stres autentic în viața noastră, nu este momentul potrivit pentru a ne opri, dar în momentele fără stres, nu avem nicio dorință de a pune capăt torturii. Puneți-vă următoarele întrebări:

1.  Atunci când ai intrat pentru prima dată în lumea porno, ai decis cu adevărat că vei continua să depinzi de ea pentru tot restul vieții tale fără să te poți opri vreodată? ***Bineînțeles că nu!

2.  Ai de gând să continui tot restul vieții tale fără să te poți opri vreodată? ***Bineînțeles că nu!***

Deci, când te vei opri? Mâine? Anul viitor? Nu asta te-ai întrebat de când ți-ai dat seama că ești dependent? Speri că într-o dimineață te vei trezi și nu vei mai vrea să te uiți? Nu te mai amăgi singur, cu orice dependență devii progresiv mai dependent, nu mai puțin. Ai de gând să aștepți până când vei începe să simți că e mai greu să te ridici din pat decât să te masturbezi? Ar fi cam inutil.

Adevărata capcană este credința că acum nu este momentul potrivit - mâine va fi întotdeauna mai ușor. Credem că trăim vieți stresante, dar în realitate nu este așa. Cea mai mare parte a stresului veritabil a fost eliminat din viața noastră. Atunci când pleci de acasă nu trăiești cu teama de a fi atacat de animale sălbatice, majoritatea nu se întreabă de unde va veni următoarea masă sau dacă vor avea un acoperiș deasupra capului la noapte. Gândiți-vă la viața unui animal sălbatic, de fiecare dată când un iepure iese din vizuina sa, se confruntă cu Vietnamul pentru întreaga sa viață. Dar iepurele se descurcă, are adrenalină și alți hormoni, la fel ca și noi. Adevărul este că perioadele cele mai stresante pentru viața oricărei creaturi sunt copilăria timpurie și adolescența. Dar trei miliarde de ani de selecție naturală ne-au echipat pentru a face față stresului, iar mulți dintre cei care cresc cu o copilărie grea duc o viață normală.

Este un clișeu să spui: *"Dacă nu ai sănătate, nu ai nimic "*, dar este absolut adevărat. Atunci când te simți puternic din punct de vedere fizic și mental, te poți bucura de momentele bune și poți face față celor rele. Mulți confundă responsabilitatea cu stresul; responsabilitatea devine stresantă doar atunci când nu ne simțim suficient de puternici pentru a o gestiona. Ceea ce îi distruge pe cei mai mulți nu este stresul, locurile de muncă sau bătrânețea, ci cârjele iluzorii și mincinoase la care apelează.

Priviți lucrurile astfel - ați decis deja că nu veți rămâne în capcană pentru tot restul vieții. Prin urmare, la un moment dat - indiferent dacă ți se pare ușor sau dificil - va trebui să treci prin procesul de eliberare. Pornografia nu este un obicei sau o plăcere, ci o dependență de droguri și o boală. Am stabilit că, departe de a fi mai ușor mâine, va fi din ce în ce mai rău. Momentul de a scăpa de el este **acum** - sau cât mai aproape de acum, cât de mult poți reuși. Gândește-te cât de repede trece fiecare săptămână din viața noastră. De atât este nevoie. Gândește-te cât de frumos va fi să te bucuri de restul vieții tale fără umbre din ce în ce mai mari atârnând deasupra ta. Cu condiția să urmați toate instrucțiunile, nici măcar nu va trebui să așteptați cinci zile sau trei săptămâni. Nu numai că îți va fi ușor să te lași de fumat, dar îți va face plăcere**!
