# Voi rata distracția?

**Nu!** Odată ce micul monstru porno este mort, după ce corpul tău nu mai tânjește după dopamină, iar toboganele de apă porno din creierul tău încep să se estompeze rapid din cauza lipsei de "ungere", orice spălare a creierului rămasă va dispărea. Nu numai că vă veți găsi atât fizic cât și mental mai bine echipat pentru a face față stresului și tensiunilor vieții, dar vă veți bucura din plin de momentele bune.

Există un singur pericol, și anume influența celor care încă folosesc sexul ca pe o cârjă și o plăcere. *" Gazonul celuilalt este întotdeauna mai verde "* este un loc comun în multe aspecte ale vieții noastre și este ușor de înțeles. De ce în cazul pornografiei - cu dezavantaje atât de enorme în comparație cu "avantajele" iluzorii - fostul utilizator tinde să-i invidieze pe cei care cer sex și pornografie ca cârjă? 

Cu toată spălarea creierului din copilărie, este destul de ușor de înțeles că am căzut în capcană. De ce atunci - după ce ne-am dat seama ce joc prostesc este pornografia și am reușit să renunțăm la acest obicei - ne întoarcem direct în aceeași capcană? Este vorba de influența spălării creierului societății, care asociază pornografia cu sexul, prezentat ca fiind normal. Fostul utilizator are o durere! Sentimentul de gol nesiguranță al faptului că sunt singuri (ceea ce nu este o crimă oricum) provoacă sentimente de anxietate și îi determină să se dea pe toboganul cu apă. Aceasta este într-adevăr o anomalie curioasă, mai ales dacă se ia în considerare această observație: nu numai că fiecare non-utilizator din lume este fericit să fie așa, dar fiecare utilizator din lume, chiar și cu mintea lor deformată, dependentă și spălată pe creier care suferă iluzia plăcerii sau relaxării, își dorește să nu fi devenit niciodată dependent în primul rând. Așadar, de ce invidiază foști consumatori pe cei inca dependenți?

1.  "Doar o privire". Nu uitați că nu există. Încetați să mai vedeți ocazia izolată și începeți să o priviți din punctul de vedere al utilizatorului de pornografie. S-ar putea să-i invidiați, dar ei nu se aprobă pe ei înșiși și vă invidiază. Dacă ați putea cumva să urmăriți clinic un alt utilizator, deoarece ei pot fi cel mai puternic impuls dintre toate pentru a vă ajuta să ieșiți din ea. Observați cât de repede deschid multe file și ferestre de browser? Trec repede la secțiunile importante, se plictisesc repede de clipuri și parcurg toată gama de genuri care produc noutăți, șoc, anxietate etc. Observați mai ales că actul pare să fie automat. Nu uitați - nu le face plăcere, este vorba de faptul că nu se pot bucura fără PMO. A doua zi dimineață, trezindu-se cu voința slăbită, cu energia pierdută și cu ochii învinețiți, vor trebui să continue să se sufoce la prima apariție a stresului și a tensiunii. Se confruntă cu o viață întreagă de mizerie, sănătate mintală precară și încredere pătată - o viață întreagă în care se vor distruge cu umbre negre în fundul minții lor. Pentru a atinge ce scop? Iluzia că primești ceea ce "meriți" și plăcerea blestemată?

2.  Al doilea motiv pentru care unii foști utilizatori au dureri este că utilizatorul de pornografie face ceva - cum ar fi auto-plăcerea - iar non-utilizatorul nu, astfel încât tind să se simtă privați. Înțelegeți clar în mintea voastră, nu non-utilizatorul este cel care este privat, ci bietul dependent care este privat de:

    - Sănătate

    - Energie

    - Încredere

    - Pacea sufletească

    - Curaj

    - Tranchilitate

    - Libertate

    - Respectul de sine

Ieșiți din obiceiul de a invidia utilizatorii de pornografie și începeți să îi vedeți ca pe creaturile mizerabile și patetice care sunt cu adevărat. Știu, am fost odată unul dintre cei mai răi. De aceea citești această carte și nu pe cei care nu pot face față și continuă să se amăgească.

Nu ai invidia un dependent de heroină și, ca orice dependență de droguri, nici a ta nu se va îmbunătăți. În fiecare an se va înrăutăți exponențial - dacă astăzi nu te bucuri să fii consumator, mâine te vei bucura și mai puțin. Nu-i invidiați pe ceilalți consumatori, compătimiți-i. Credeți-mă: ***Ei au nevoie de mila ta!***
