# Pot să compartimentalizez?

Acest mit este răspândit în primul rând de utilizatorii care încearcă să se oprească prin metoda voinței, care fac gimnastică mentală și încep o rutină Jekyll-and-Hyde: "*Pornul este pentru alter ego-ul meu, iar romantismul din viața reală este pentru partea mea de relație.*" Nimic nu este mai departe de adevăr - toboganele de apă porno, DeltaFosB și modificările neurologice vor depăși romantismul din viața reală, făcându-l mai puțin de dorit. Domnul Hyde va anula cu siguranță instrucțiunile doctorului Jekyll.

Dacă folosiți porno pe internet, vă antrenați pentru rolul de voyeur, sau care necesită opțiunea de a face clic pe ceva mai excitant la cea mai mică scădere a nivelului de dopamină. Sau, căutarea continuă a *doar* scenei potrivite pentru un efect maxim. În plus, s-ar putea să te masturbezi într-o poziție cocoșată sau să te uiți la smartphone în pat pe timp de noapte, dorindu-ți în cele din urmă aceste indicii mai mult decât stimulii din viața reală. Sexul contravine aproape tuturor aspectelor haremului online, așa că nu are nicio șansă atunci când este comparat. Amintirile create când ești tânăr sunt puternice și de lungă durată, așa că descompunerea acelor diapozitive pornografice și reconectarea sau crearea altora noi durează mai mult. Cu toate acestea, asta nu înseamnă că este mai dificil.

De fiecare dată când te dai pe "toboganul de apă porno", îl ungi, menținând nervii proaspeți și gata să pornească. Când parchezi lângă un fast-food, mirosul de frigărui îți plutește în nări și vânzarea este deja făcută. La fel, toboganele de apă porno din creierul tău sunt pregătite să te tragă în ele și sunt deschise douăzeci și patru de ore pe zi. Fiecare indiciu sau declanșator vă aprinde circuitul de recompensă cu promisiunea de sex - numai că nu este sex. Cu toate acestea, celulele nervoase solidifică aceste asocieri cu excitarea sexuală prin apariția de noi ramuri pentru a consolida conexiunile. Cu cât folosiți mai mult pornografia, cu atât mai puternice devin conexiunile nervoase. Rezultatul final este că, în cele din urmă, s-ar putea să aveți *nevoie* de a fi un voyeur, având nevoie să faceți clic pe materiale mereu în creștere și noi, având nevoie de pornografie pentru a adormi sau având nevoie să căutați finalul perfect pentru a face treaba.

La fel ca în cazul oricărei substanțe sau al oricărui drog comportamental, organismul dezvoltă toleranță și drogul încetează să mai aline complet durerile de sevraj. De îndată ce utilizatorul de pornografie închide o sesiune, își dorește o alta, și repede, foamea permanentă rămânând nesatisfăcută. Înclinația naturală este escaladarea, pentru a obține adrenalina de dopamină. Cu toate acestea, cei mai mulți utilizatori sunt împiedicați să facă acest lucru din unul sau din următoarele două motive sau din ambele.

**Bani:** Nu-și permit să se aboneze la site-uri porno plătite.

**Sănătate:** Corpul nu poate suporta prea mult, fie că e vorba de valurile de dopamină sau de orgasme. În plus, orgasmele declanșează de fapt substanțe chimice pentru a reduce fluxul de dopamină. Trebuie să o facă, așa funcționează corpul.

Odată ce micul monstruleț părăsește corpul tău, sentimentul îngrozitor de nesiguranță se termină. Încrederea revine, împreună cu un minunat sentiment de respect de sine, obținând siguranța de a prelua controlul asupra vieții tale și folosindu-l ca o trambulină pentru a aborda alte probleme. Acesta este unul dintre multele avantaje mari ale eliberării de orice dependență.

Mitul compartimentării este unul dintre multele trucuri pe care micul monstruleț le joacă cu mintea ta. Aceste trucuri fac mai greu să te oprești - din cauza imposibilității de a satisface foamea permanentă - determinându-i pe mulți consumatori să apeleze la țigări, la consumul excesiv de alcool sau chiar la droguri mai dure pentru a-și satisface golul.

Vizionarea de filme porno cu partenerul este nesatisfăcătoare, deoarece amândoi evaluați performanța celuilalt în raport cu narațiunea. Îl vrei pe Brad Pitt în dormitorul tău, chiar dacă este pe un poster? Nicio persoană nu poate egala un harem în care fiecare "experiență" este jucată, scenarizată, regizată de profesioniști și disponibilă imediat, douăzeci și patru de ore pe zi.

