# Evitați stimulentele false

Mulți utilizatori ai metodei voinței încearcă să își sporească motivația prin construirea de stimulente false. Există multe exemple în acest sens, unul tipic fiind acela de a se recompensa cu cadouri după ce nu se uită la filme porno timp de o lună. Aceasta pare a fi o abordare logică și sensibilă, dar este de fapt falsă, deoarece orice utilizator care se respectă ar prefera să continue să se uite la porno în fiecare zi decât să se recompenseze cu un cadou oferit de el însuși. Acest lucru generează îndoieli în mintea utilizatorului, deoarece nu numai că va trebui să se abțină timp de *treizeci de zile*, dar nici nu este sigur că se va *bucura* de zilele fără porno. Singura lor plăcere sau cârjă le-a fost luată! Tot ceea ce face acest lucru este să crească dimensiunea sacrificiului pe care utilizatorul simte că îl face, acum și mai prețios în mintea lui.

Rationamentele utilizaotrului:

- O să mă opresc ca să mă forțeze să am o viață socială și mai mult sex adevărat.

- Mă voi opri pentru ca o energie magică să mă ajute să depășesc concurenții și să obțin partenerul pe care îl urmăresc.

- Mă voi opri astfel încât să mă angajez să nu-mi irosesc energia și entuziasmul cu porno pentru a crește foamea în mine.

Acestea sunt adevărate, pot fi eficiente și s-ar putea să ajungeți să obțineți ceea ce doriți - dar gândiți-vă la asta pentru o secundă. Dacă obțineți ceea ce ați vrut, odată ce noutatea a dispărut, vă veți simți privați; dacă nu ați făcut-o, vă veți simți mizerabil. Oricum ar fi, mai devreme sau mai târziu veți cădea din nou în aceeași capcană.

Legătura renunțării cu un stimulent fals nu face decât să sporească îndoiala, pentru că dacă nu primești stimulentul (și chiar dacă îl primești) vei începe să te gândești la gânduri îndoielnice, cum ar fi: "*Va face renunțarea la PMO viață mai bună? Dacă renunț și nu obțin ceea ce vreau, am folosit corect metoda?*". Gândurile de acest gen sporesc sentimentul de sacrificiu și, prin urmare, creează dureri.

Un alt exemplu tipic este reprezentat de pactele online sau de pe forumuri. Acestea au avantajul de a elimina tentația pentru anumite perioade. Cu toate acestea, ele eșuează în general din următoarele motive:

1.  Stimulentul este fals. De ce ați vrea să vă opriți doar pentru că alți oameni fac acest lucru? Tot ceea ce se obține astfel este generarea unei presiuni suplimentare și creșterea sentimentului de sacrificiu. Este în regulă dacă toți utilizatorii doresc cu adevărat să se oprească la un moment dat - dar nu îi puteți forța să se oprească, deși toți își doresc în secret acest lucru. Până când nu sunt pregătiți să facă acest lucru, un pact creează o presiune suplimentară, care nu face decât să le sporească dorința de a se uita. Acest lucru îi transformă în spectatori secreți, sporind și mai mult sentimentul de dependență.

2.  Dependența reciprocă folosind metoda voinței generează sentimentul de a trece printr-o perioadă de abstinență, în care așteaptă ca nevoia să dispară. Dacă cedează, există un sentiment de eșec. Atunci când se folosește metoda voinței, cel puțin unul dintre participanți este obligat să renunțe, oferindu-le celorlalți participanți scuza pe care o așteptau. Nu este vina lor, ei ar fi rezistat, dar "Fred" i-a dezamăgit. Adevărul este că cei mai mulți dintre ei au trișat deja.

3.  Împărțirea meritelor este inversul dependenței. Există un minunat sentiment de realizare în oprirea pornografiei și, atunci când o faci singur, aplauzele pe care le primești de la prietenii și prietenii online pot fi un impuls extraordinar în primele zile. Cu toate acestea, atunci când toată lumea o face în același timp, creditul trebuie împărțit și, în consecință, impulsul este redus.

4.  Un alt exemplu clasic este promisiunea guru. Oprirea îți va da fericire pentru că nu mai ești angajat în acest război de intre doua lumi, creierul tău începând să se reconecteze și să-și recapete controlul impulsurilor. Cu toate acestea, trebuie să rețineți că acest lucru nu vă va face nici un zeu al sexului și nici nu vă va face să câștigați la loto. Nimănui, în afară de tine, nu-i pasă câtuși de puțin dacă te oprești din pornografie. Nu ești o persoană slabă dacă folosești porno de trei ori pe zi și ai PIED, sau o persoană puternică dacă ești dependent și nu ai.

Nu te mai amăgi. Dacă oferta de muncă de zece luni de muncă pentru un salariu de douăsprezece luni pe an, sau riscurile de a-ți reduce capacitatea creierului de a face față stresului și tensiunilor zilnice, sau de a te pune în imposibilitatea de a avea o erecție fiabilă, sau viața de tortură și sclavie mentală și fizică pe viață nu i-au oprit, cele câteva stimulente false de mai sus nu vor face nici cea mai mică diferență și vor reuși doar să facă sacrificiul să pară mai rău. În schimb, concentrați-vă asupra celeilalte părți:

\"Cu ce mă aleg din asta? De ce am nevoie să mă uit la filme porno?\"

Continuați să priviți cealaltă parte a războiului de tracțiune și întrebați-vă ce face pornografia pentru dumneavoastră. *ABSOLUT NIMIC.* De ce am nevoie să o fac? *NU AI NEVOIE! NU faci decât să te pedepsești pe tine însuți.* Este pariul lui Pascal: nu ai aproape nimic de pierdut (excitare care se estompează), șanse de profituri mari (excitare completă și fiabilă, bunăstare mentală și fericire) și nici o șansă de a pierde mult.

De ce să nu vă declarați apoi renunțarea prietenilor și familiei? Ei bine, acest lucru vă va face un fost dependent sau un fost consumator mândru, nu un non-consumator exaltat și fericit. S-ar putea să vă sperie puțin partenerul, deoarece ar putea să vadă acest lucru ca pe o schemă de a face mai mult sex, într-un fel de New Age. De asemenea, s-ar putea să se teamă că vă transformați într-o mașină de sex. Este greu de explicat dacă nu sunt deschiși la minte.

Orice încercare de a-i face pe alții să te ajute să te lași de fumat îi dă mai multă putere micului monstru. Alungarea lui din minte și ignorarea totală a acestuia are ca efect încercarea de a *nu* te gândi la el. Fiți atenți în schimb, de îndată ce observați gândurile, indicii (singur acasă) sau gânduri absente, spuneți-vă doar *\"Grozav, nu mai sunt un sclav al porno. Sunt liber și fericit să cunosc diferențele în sex!\"* Acest lucru va tăia oxigenul către gând și îl va opri să ardă spre impulsuri și pofte. În acest aspect, practicarea meditației mindfulness poate fi utilă pentru a ajuta la depersonalizarea gândurilor.
