# Cales usoara de a opri consumul de pornografie

Acest capitol conține instrucțiuni referitoare la modul simplu de a opri consumul de pornografie. Cu condiția să urmați instrucțiunile, veți descoperi că oprirea variază de la relativ ușoară la plăcută! Cu condiția să urmați instrucțiunile de mai jos, este ridicol de ușor să vă opriți din porno. Tot ce trebuie să faceți sunt două lucruri:

1.  Luați decizia că nu veți mai viziona niciodată filme porno.

2.  Nu vă întristați din cauza asta. Bucurați-vă.

Probabil că vă întrebați: *"De ce este nevoie de restul cărții? De ce nu puteai să spui asta de la început?*". Ei bine, răspunsul este că, în cele din urmă, te-ai fi plâns de asta și, în consecință, ți-ai fi schimbat în cele din urmă decizia. Probabil că ați făcut deja acest lucru de multe ori înainte.

După cum s-a spus deja, pornografia este o capcană subtilă și sinistră. Principala problemă a opririi nu este dependența de dopamină - care este cu siguranță o problemă, dar nu cea principală - ci spălarea creierului. Prin urmare, este necesar să distrugem mai întâi toate miturile și iluziile. Înțelege-ți inamicul, cunoaște-i tacticile și îl vei învinge cu ușurință. După ce mi-am petrecut mari părți din viață suferind de depresie neagră în timp ce încercam să mă las de fumat, după ce am scăpat în sfârșit, am trecut direct la zero, fără niciun moment rău. A fost plăcut chiar și în perioada de sevraj și de atunci nu am mai avut nici cea mai mică durere. Dimpotrivă, a fost unul dintre cele mai minunate lucruri care s-au întâmplat în viața mea.

Ultima mea încercare a fost diferită. La fel ca toți utilizatorii din zilele noastre, problema fusese gândită serios în mintea mea. Până atunci, după eșec, era o rutină să mă consolez cu gândul că data viitoare va fi mai ușor. Nu-mi trecuse niciodată prin cap că va trebui să continui în acest fel pentru tot restul vieții mele. Acest gând m-a umplut de groază și am început să mă gândesc foarte profund la acest subiect.

În loc să pornesc browserul în subconștient, mi-am analizat sentimentele și am confirmat ceea ce știam deja. Nu-mi plăcea pornografia și o găseam murdară și dezgustătoare. Am început să mă uit la non-utilizatorii care locuiesc în alte părți ale lumii sau la persoanele mai în vârstă care nu au ajuns să cunoască site-urile de tuburi. Până atunci, întotdeauna am privit non-utilizatorii ca pe niște oameni nesiguri, nesociabili și pretențioși. Cu toate acestea, examinându-i atunci când apăreau, păreau a fi - dacă nu cumva - mai puternici și mai relaxați. Ei păreau să poată face față stresului și tensiunilor vieții și păreau să se bucure de funcțiile sociale mai mult decât utilizatorii de porno. Aveau cu siguranță mai multă strălucire și zvâcnet decât ei.

Am început să vorbesc cu foști utilizatori. Până în acel moment, îi considerasem întotdeauna ca fiind forțați să renunțe din motive de sănătate sau religioase și întotdeauna tânjeau în secret după o vizită în harem. Câțiva mi-au spus: *"Ai parte de unele pofte rare, dar sunt atât de puține și de îndepărtate încât nu merită să te deranjezi. "* Cei mai mulți au spus în schimb: *"Îți lipsește? Cred că glumești! Viața nu s-a simțit niciodată mai bine!"* Chiar și eșecurile au fost o cădere în față pentru ei - nu s-au condamnat pe ei înșiși și în schimb s-au acceptat necondiționat. La fel ca un antrenor care acceptă o greșeală a unui jucător cu adevărat de aur. Discuțiile cu foștii consumatori au distrus un alt mit pe care îl aveam mereu în minte, acela că în mine există o slăbiciune inerentă, până când mi-am dat seama că toți trec prin acest coșmar propriu. 

Practic, mi-am spus: *"O mulțime de oameni se opresc acum și duc o viață perfect fericită, eu nu am avut nevoie să o fac înainte de a începe și îmi amintesc că a trebuit să muncesc din greu pentru a mă obișnui cu această mizerie. Deci, de ce am nevoie să o fac acum? "* În orice caz, nu mi-a plăcut pornografia, urând întregul ritual murdar și nu am vrut să-mi petrec restul vieții mele în sclavia acestei dependențe dezgustătoare. Apoi mi-am spus acest lucru:

*"Fie că-ți place sau nu, ai terminat ultima sesiune. "*

Am știut, chiar din acel moment, că nu voi mai avea niciodată o altă sesiune. Nu mă așteptam să fie ușor, ci exact invers. Am crezut pe deplin că m-am înscris pentru luni de depresie neagră și pentru a-mi petrece restul vieții având ocazional câte o înțepătură. În schimb, a fost o fericire absolută încă de la început.

Mi-a luat mult timp să-mi dau seama de ce a fost atât de ușor și de ce nu am suferit acele chinuri terifiante de sevraj. Motivul este că acestea nu există, ci îndoiala și incertitudinea sunt cele care generează durerile. Frumosul adevăr este că ***este ușor să te oprești de la pornografie.*** Doar indecizia și melancolia o fac dificilă. Chiar și în timp ce sunt dependenți, utilizatorii pot rezista pentru perioade relativ lungi în anumite momente fără ea. Doar atunci când o vrei, dar nu o poți avea, suferi.

Prin urmare, cheia pentru a face acest lucru mai ușor este de a face oprirea sigură și definitivă. Nu sperând, ci *știind* că ai renuntat definitiv, după ce ai luat decizia. Niciodată să nu te îndoiești, de fapt, exact invers - întotdeauna să te bucuri! Dacă poți fi sigur de la început, va fi ușor. Dar cum poți fi sigur de la început? De aceea, restul cărții este necesar. Există anumite puncte esențiale necesare pentru a vă lămuri în minte înainte de a începe:

1.  Realizează că poți reuși. Nu există nimic diferit la tine și singura persoană care te poate face să privești este tu însuți. Nu acea vedetă, care nici în cele mai nebunești vise nu s-a gândit vreodată că ar putea fi folosită pentru reducerea virilității.

2.  Nu este absolut nimic la care să renunți. Dimpotrivă, există câștiguri pozitive enorme de obținut. Nu numai că vei fi mai sănătos și mai bogat, dar te vei bucura mai mult de momentele bune și vei fi mai puțin nefericit în timpul celor rele.

3.  Nu există o privire sau o singură vizită. Pornografia este o dependență de droguri și o reacție în lanț, plângându-te de vizita ciudată nu vei face decât să te pedepsești inutil.

4.  Priviți pornografia nu ca pe un obicei "băieții vor fi băieți" care ar putea să vă rănească, ci ca pe o dependență de droguri. Înfruntați faptul că, fie că vă place sau nu, **aveți boala.** Nu va dispărea pentru că vă îngropați capul în nisip. Ține minte că, la fel ca toate bolile paralizante, nu numai că durează toată viața, dar se agravează exponențial. Cel mai simplu moment pentru a o vindeca este acum.

5.  Separați boala - dependența neurologică - de mentalitatea de a fi sau nu consumator. Toți utilizatorii, dacă li s-ar oferi posibilitatea de a se întoarce la perioada de dinainte de a deveni dependenți, ar sări pe această oportunitate. Aveți această oportunitate astăzi! Nici măcar nu vă gândiți la asta ca la "renunțare".

În momentul în care veți lua decizia finală că ați avut ultima vizită, veți fi deja un non-utilizator. Un utilizator este unul dintre acei bieți nenorociți care trec prin viață distrugându-se cu porno. Un non-utilizator este cineva care nu o face. Odată ce ați luat această decizie finală, v-ați atins deja obiectivul. Bucurați-vă de acest fapt, nu stați să vă plângeți și să așteptați ca dependența chimică să plece. Ieșiți și bucurați-vă de viață imediat. Viața este minunată chiar și atunci când ești dependent și fiecare zi va fi mult mai bună atunci când nu vei mai fi dependent.

Cheia pentru a facilita renunțarea este să fii sigur că vei reuși să te abții complet în perioada de sevraj, de maximum trei săptămâni. Dacă ești în starea de spirit corectă, vei găsi acest lucru ridicol de ușor.

În acest stadiu, dacă ți-ai deschis mintea așa cum ți s-a cerut la început, vei fi decis deja că vei evada. Ar trebui să aveți acum sentimente de entuziasm, ca un câine care se încordează în lesă, nerăbdător să aștepte să rupă toboganele porno DeltaFosB. Dacă aveți un sentiment de tristețe, asta se poate intampla din unul dintre următoarele motive:

1.  Ceva nu ți s-a coagulat în minte. Recitește cele cinci puncte de mai sus și întreabă-te dacă le crezi adevărate. Dacă vă îndoiți de vreun punct, recitiți secțiunile corespunzătoare din carte.

2.  Vă temeți de eșecul în sine. Nu vă faceți griji, citiți mai departe și veți reuși. Întreaga afacere a pornografiei pe internet este un truc de încredere la scară gigantică. Oamenii inteligenți pot fi păcăliți de trucurile de încredere, dar numai un prost, odată ce a aflat despre truc, continuă să se păcălească singur.

3.  Sunteți de acord cu totul, dar tot vă simțiți nefericit. Să nu fiți! Deschideți ochii, se întâmplă ceva minunat. Ești pe cale să evadezi din închisoare, este esențial să începi cu o stare de spirit corectă: *"Este minunat că sunt un non-utilizator!" *.

Tot ceea ce trebuie făcut acum este să vă mențineți în această stare de spirit în timpul perioadei de retragere, iar următoarele câteva capitole se referă la puncte specifice care să vă permită să faceți acest lucru. După perioada de retragere nu va mai trebui să gândiți în acest mod, veți gândi automat. Singurul mister din viața ta va fi de ce nu ai văzut-o înainte. Totuși, două avertismente importante.

- Amână-ți planul de a face ultima vizită până când vei termina cartea. 
 
- O perioadă de sevraj de până la trei săptămâni a fost menționată de mai multe ori, ceea ce poate cauza neînțelegeri. În primul rând, s-ar putea ca, în subconștient, să simțiți că trebuie să suferiți timp de trei săptămâni. Nu este așa. În al doilea rând, evitați capcana de a gândi *"Cumva trebuie să mă abțin timp de trei săptămâni și apoi voi fi bine. "* Nimic magic nu se va întâmpla de fapt după trei săptămâni, nu vă veți simți brusc ca un non-consumator, deoarece aceștia nu se simt de fapt diferiți de consumatori. Dacă vă plângeți de faptul că vă opriți în timpul celor trei săptămâni, după toate probabilitățile veți continua să vă plângeți și după cele trei săptămâni. În concluzie, dacă puteți începe chiar acum prin a spune *"Nu voi mai consuma niciodată, nu este minunat? "*, după trei săptămâni va dispărea orice tentație. În timp ce dacă spui, *"Dacă aș putea supraviețui acestor trei săptămâni fără porno ... "*, vei muri pentru o vizită în harem după ce se termină cele trei săptămâni.

Gândește-te la asta în felul următor - creierul tău vrea să mențină status quo-ul, așa că, dacă ești convins că pierzi ceva bun atunci când renunți la PMO, evident că te vei simți oribil. Este imposibil să te forțezi să te simți într-un anumit fel dacă creierul tău nu crede asta. Acesta este motivul pentru care este important să vă chinuiți să eliminați iluzia că pornografia vă oferă ceva. Așa știi că nu sacrifici nimic.

Disfuncția sexuală are foarte mult de-a face cu creierul și cu starea ta de spirit. Pornografia pe internet reconectează circuitul de recompensă al creierului tău și îi conferă minții tale o stare de spirit "îndoielnică". Această îndoială de sine va provoca, fără îndoială, disfuncții sexuale. Să ai toată dorința în partea superioară, dar să suporți lipsa de excitare în partea inferioară este cel mai rău lucru care i se poate întâmpla mentalității tale. Libidoul mergând mână în mână cu romantismul este elixirul tinereții pe care îl poți avea până la moarte. Vei menține probabilitățile ridicate dacă renunți, dar acesta nu este singurul sau principalul câștig. Este eliberarea ta din sclavie!
