# Perioada de sevraj

Timp de până la trei săptămâni după ultima ședință, este posibil să fiți supuși unor dureri de sevraj. Acestea constau în doi factori :

1.  Durerile de sevraj ale dopaminei. O senzație de gol, de nesiguranță, asemănătoare cu foamea, identificată ca fiind o poftă sau o senzație de "ceva ce trebuie să fac".

2.  Declanșarea psihologică a anumitor stimuli externi, cum ar fi reclamele, navigarea online, conversațiile telefonice etc.

Eșecul de a înțelege și de a face diferența între acești doi factori distincți face dificilă obținerea succesului folosind metoda voinței și este motivul pentru care mulți dintre cei care reușesc ajung să cadă din nou în capcană. Deși durerile de sevraj ale dopaminei nu provoacă dureri fizice, nu le subestimați puterea. Vorbim de "dureri de foame" dacă stăm fără mâncare timp de o zi; s-ar putea să existe rumoare în stomac, dar nu există nicio durere fizică. Chiar și așa, foamea este o forță puternică și este posibil să devenim foarte iritabili atunci când suntem privați de mâncare. Este similar cu momentul în care corpul nostru tânjește după o dopamină, diferența fiind că organismul nostru are nevoie de hrană, nu de otravă. Cu o stare de spirit potrivită, senzația de sevraj este ușor de depășit și dispare foarte repede.

După ce vă abțineți câteva zile prin metoda voinței, pofta de dopamină dispare curând. Cel de-al doilea factor - spălarea creierului - este cel care provoacă dificultăți. Utilizatorul a căpătat obiceiul de a-și ușura senzația de sevraj la anumite momente și în anumite ocazii, ceea ce determină o asociere de idei (*"Am o erecție, așa că trebuie să mă uit la filme porno. "* sau "*Sunt în pat cu laptopul meu și trebuie să am o sesiune pentru a mă simți fericit*"). Efectul este cel mai bine ilustrat cu un exemplu: aveți o mașină și indicatorul este în stânga, dar pe următoarea, este în dreapta. Știi că este pe stânga, dar timp de câteva săptămâni pornești ștergătoarele de parbriz atunci când vrei să indici.

Oprirea este similară: în primele zile, mecanismul de declanșare va acționa în anumite momente. Vă veți gândi că vreți o sesiune, așa că, prin urmare, contracararea spălării creierului este esențială încă de la început și va face ca aceste indicii și declanșatoare să dispară rapid. În cadrul metodei de voință, deoarece utilizatorul crede că face un sacrificiu, se moaie și așteaptă ca impulsurile să plece, opusul eliminării acestor mecanisme de declanșare, și de fapt sfârșește prin a le spori. În mod similar, în cadrul gândirii de guru, utilizatorul începe să se întrebe când va deveni un zeu și chiar cere să nu aibă aceste gânduri, deschizând calea spre dezgustul de sine și eșec.

Un factor declanșator obișnuit este timpul petrecut singur, în special la evenimentele sociale cu prietenii. Fostul consumator care folosește alte metode pentru a renunța se simte deja nefericit din cauza faptului că se simte privat de cârja sau plăcerea sa obișnuită. Prietenii lor sunt cu partenerii lor și se comportă intim. Consumatorul este fie singur, fie nu "primește nimic" de la partenerul său și acum nu se mai bucură de ceea ce ar trebui să fie o ocazie socială plăcută. Toboganele de apă existente în creierul lor îi conduc la porno, ceea ce este mai ușor decât să încerce să-și curteze partenerul.

Din cauza asocierii dreptului la sex cu bunăstarea lor, ei suferă acum o lovitură triplă, iar spălarea creierului este de fapt crescută. Dacă sunt hotărâți și pot rezista suficient de mult timp, în cele din urmă își acceptă soarta și își continuă viața. Cu toate acestea, o parte a spălării creierului rămâne în continuare, al doilea aspect cel mai patetic fiind faptul că utilizatorul a renunțat, dar chiar și după mai mulți ani încă mai râvnește la "doar o ultimă vizită la harem" în anumite ocazii. Tânjesc după o iluzie care există doar în mintea lor și se torturează inutil.

Chiar și în cadrul EasyPeasy, răspunsul la factorii declanșatori este cel mai frecvent eșec. Fostul utilizator tinde să privească pornografia pe internet ca pe un fel de placebo sau de pastilă de zahăr, gândindu-se: "*Știu că pornografia nu face nimic pentru mine, dar dacă cred că in anumite ocazii va fi de ajutor.*" O pastilă de zahăr, deși nu oferă niciun ajutor fizic real, poate fi un ajutor psihologic puternic pentru a ameliora simptomele reale și, prin urmare, este benefică. Cu toate acestea, pornografia pe internet și masturbarea obișnuită nu sunt pastile de zahăr. De ce? Pornografia creează simptomele pe care le ameliorează și încetează să le amelioreze complet.

S-ar putea să vă fie mai ușor să înțelegeți efectul atunci când vă raportați la un ne-utilizator sau la un utilizator de succes care a renunțat timp de mai mulți ani. Luați cazul unui utilizator care își pierde partenerul. Este destul de obișnuit ca în astfel de momente, cu cele mai bune intenții, să se spună: "*Fă o vizită la harem, te va ajuta să te calmezi.*" Dacă oferta este acceptată, nu va avea un efect calmant, deoarece nu există dependență de dopamină și, prin urmare, nu există dureri de sevraj. În cel mai bun caz, tot ceea ce va face este să le dea un impuls psihologic momentan.

Chiar și după ce sesiunea s-a încheiat, tragedia inițială este acolo. De fapt, aceasta va fi accentuată, deoarece persoana suferă acum de senzația de sevraj și astfel trebuie să facă o alegere: să o suporte sau să caute alinare repetând cursa cu toboganul de apă pentru a începe din nou lanțul de suferință. Tot ceea ce a oferit pornografia a fost un impuls psihologic trecător, același lucru care ar fi putut fi obținut printr-o carte sau un film de bun augur, chiar și unul prost. Mulți non-consumatori și foști consumatori au redevenit dependenți ca urmare a unor astfel de ocazii. Aveți foarte clar în minte: nu aveți nevoie de adrenalina de dopamină și nu faceți decât să vă torturați și mai mult dacă continuați să o considerați ca pe un fel de recuzită sau de impuls. Nu este nevoie să vă simțiți nefericit.

Orgasmele nu fac relațiile bune, de cele mai multe ori le strică. Amintiți-vă, de asemenea, că nu este întru totul adevărat că cei care dau dovadă de afecțiune în public se bucură de orice ocazie; intimitatea este cel mai bine savurată în privat, unde partenerii pot răspunde fără jenă. Nu trebuie să fii un dependent de dopamină indusă de orgasm. Dacă se întâmplă ca un rezultat natural al unei serii de evenimente de viață, este bine, dar bucurați-vă de ocazie și de viață fără el.

După ce au abandonat conceptul de porno ca fiind plăcut în sine, mulți utilizatori se gândesc: "* Dacă ar exista porno curat pe internet.*" Există *există* pornografie soft curată, iar cei care o încearcă descoperă repede că este o pierdere de timp. Înțelegeți clar în mintea dvs. că singurul motiv pentru care ați folosit porno este obținerea dopaminei. Odată ce ați scăpat de dorința de dopamină pentru porno, nu veți avea nevoie să vă vizitați haremul online.

Indiferent dacă durerile se datorează simptomelor reale de sevraj de dopamină sau mecanismelor de declanșare / provocare, acceptați-le. Durerea fizică este inexistentă și, cu o stare de spirit potrivită, nu va fi o problemă. Nu vă faceți griji cu privire la sevraj - senzația în sine nu este rea. Problema este asocierea cu dorința și apoi cu sentimentul de negare. În loc să vă plângeți de asta, recunoașteți-o: "*Știu ce este asta, este durerea de sevraj de la pornografie. Asta este ceea ce suferă utilizatorii toată viața lor și îi menține dependenți. Non-utilizatorii nu suferă aceste dureri, este un alt rău dintre multele rele ale acestei dependențe mincinoase. Nu-i așa că este minunat că îmi curăț acest rău din creierul meu!"*. 

Cu alte cuvinte, în următoarele trei săptămâni veți avea o ușoară traumă în interiorul corpului vostru, dar în timpul acestor săptămâni și pentru tot restul vieții voastre se va întâmpla ceva minunat. Vei scăpa de o boală îngrozitoare, cu bonusuri care depășesc cu mult trauma ușoară și temporară, și chiar te vei bucura de senzația de sevraj. Acestea vor deveni momente de plăcere, ca un joc incitant pentru a înfometa tenia pornografică care trăiește în stomacul tău. Trebuie să o înfometezi timp de trei săptămâni în timp ce încearcă să te păcălească să te bagi în pat pentru a o menține în viață.

În unele momente, va încerca să te facă să te simți mizerabil. Alteori, vei fi prins cu garda jos. Vei primi un URL porno sau vei da peste ceva online și vei uita că te-ai oprit, dând un ușor sentiment de privare atunci când îți amintești. Pregătește-te dinainte pentru aceste trucuri și, indiferent de tentație, bagă-ți în cap că ea este acolo doar din cauza monstrului din interiorul corpului tău și că de fiecare dată când reziști tentației ai mai dat o lovitură mortală în luptă.
Whatever you do, don't try to forget about porn. This is one of the things that causes PMOers using the willpower method hours of depression. They try and get through each day hoping that eventually they’ll just forget about it. It's like not being able to sleep — the more you worry about it, the harder it becomes. In any event, you won't be able to forget about it, for the first few days the ‘little monster’ will keep reminding you and you won't be able to avoid it. While there are still laptops, smartphones, and magazines around you’ll have constant reminders.

The point being that you have no need to forget, since nothing bad is happening. In fact, something marvellous and wonderful is happening and even if you’re thinking about it a thousand times a day, **savor each moment, remind yourself of how marvellous it is to be free again. Remind yourself of the sheer joy of not having to torture yourself anymore.** As said previously, you’ll find that pangs become moments of pleasure, being surprised how quickly you’ll then forget about porn. 

Orice ați face, nu încercați să uitați de pornografie. Acesta este unul dintre lucrurile care cauzează PMO-erilor care folosesc metoda voinței ore de depresie. Ei încearcă să treacă prin fiecare zi în speranța că, în cele din urmă, vor uita de ea. Este ca și cum nu poți să dormi - cu cât îți faci mai multe griji în legătură cu asta, cu atât mai greu devine. În orice caz, nu veți putea uita de ea, în primele zile "micul monstru" vă va aminti în continuare și nu veți putea să îl evitați. Cât timp vor mai exista laptopuri, smartphone-uri și reviste în jur, veți avea în permanență continut pentru a-ti satisface poftele.

Ideea este că nu aveți nevoie să uitați, din moment ce nu se întâmplă nimic rău. De fapt, se întâmplă ceva minunat și, chiar dacă te gândești la asta de o mie de ori pe zi, **savurează fiecare moment, amintește-ți cât de minunat este să fii din nou liber. Amintește-ți de bucuria pură de a nu mai fi nevoit să te torturezi.** Așa cum am spus anterior, vei descoperi că durerile devin momente de plăcere, fiind surprins cât de repede vei uita apoi de pornografie. 

Orice ai face, *nu te îndoi de decizia ta*. Odată ce începi să te îndoiești, vei începe să te întristezi și va fi din ce în ce mai rău. În schimb, folosește acel moment de melancolie și transformă-l într-un impuls. Dacă cauza este depresia, atunci amintește-ți că pornografia a fost * cauza * acesteia. Dacă un prieten vă transmite o adresă URL, mândriți-vă cu faptul că spuneți: "*Sunt fericit să spun că nu mai am nevoie de asta*." Acest lucru îi va răni, dar când vor vedea că nu te deranjează, vor fi la un pas să ți se alăture.

**Amintește-ți: ai motive incredibil de puternice pentru a te opri în primul rând.** Amintește-ți de costuri și întreabă-te dacă chiar vrei să riști o funcționare defectuoasă a corpului, a minții și simplul fapt că vei trăi sub o vrajă pentru tot restul vieții tale. Fii atent la eforturile micului monstruleț de a minimiza pericolele și, mai presus de toate, amintește-ți că senzația este doar temporară și că fiecare moment este un moment mai aproape de obiectivul tău. 

Unii utilizatori se tem că vor trebui să își petreacă tot restul vieții inversând "declanșatoarele automate". Cu alte cuvinte, ei cred că vor trebui să treacă toată viața păcălindu-se singuri că nu au nevoie de pornografie, prin utilizarea psihologiei. Nu este așa; amintiți-vă că optimistul vede sticla pe jumătate plină, iar pesimistul o vede pe jumătate goală. În cazul pornografiei, sticla este goală, iar utilizatorul o vede ca fiind plină. Nu există niciun avantaj în utilizarea pornografiei pe internet. Utilizatorul este cel care a fost spălat pe creier să creadă că există. Odată ce începi să-ți spui că nu ai nevoie sau nu vrei pornografie, într-un timp foarte scurt nici nu va mai fi nevoie să o spui, văzând singur frumosul adevăr. Este ultimul lucru pe care trebuie să îl faceți - asigurați-vă că nu este ultimul lucru pe care îl faceți.
