# Doar o mică privire

Aceasta este pieirea multora dintre cei care folosesc metoda voinței. Ei vor trece prin trei sau patru zile și apoi vor arunca câte o privire ocazională pentru a-i da peste cap. Ei nu realizează efectul devastator pe care îl are acest lucru asupra moralului lor.

Pentru cei mai mulți utilizatori, prima privire aruncată la haremul de pe site-ul de porno nu a fost la fel de bună ca sexul cu o persoană reală. Clipurile care sunt curate sunt puține și rare, ceea ce le dă un impuls minții lor conștiente, gândindu-se: "*Bine, nu a fost chiar atât de plăcută. Îmi pierd pofta și nu sunt atât de pasionat de chestiile șocante*". De fapt, se întâmplă exact invers. Fiți clari, plăcerea orgasmului nu a fost motivul pentru care ați renunțat la porno. Dacă utilizatorii ar fi fost acolo doar pentru orgasm, nu s-ar fi uitat niciodată la mai mult de un clip. Singurul motiv pentru care aveai nevoie de pornografie era alimentarea acelui mic monstru. Gândește-te, după ce ai fost înfometat timp de patru zile, cât de prețios trebuie să fi fost pentru el acea singură privire. Mintea ta conștientă nu realizeaza, dar satisfactia de pe urma orgasmului pe care corpul tău a primit-o este comunicată subconștientului tău, iar toată buna ta pregătire va fi subminată. Va exista o voce mică în spatele minții tale care îți va spune că, în ciuda oricărei logici, ședințele sunt prețioase și că vrei încă una.

Această mică privire are două efecte dăunătoare:

1.  Menține micul monstruleț în viață în corpul tău.

2.  Mai rău, îl ține în viață pe monstrul mare în mintea ta. Dacă ai avut "ultima privire", îți va fi mai ușor să o ai pe următoarea.

Pornografia este o capcană pentru șoareci fără brânză, doar cu otravă. Folosind voința, trebuie să te convingi să nu iei brânza, dar EasyPeasy îți permite să vezi că branza este otravă si nu are sens sa te gandesti la ea. Nu trebuie să o eviți, pur și simplu nu te duci la ea.

Mai presus de toate, nu uitați:

*"Doar o singură privire" este modul în care oamenii intră în dependență în primul rând.*

