# Înlocuitori

Câteva exemple de înlocuitori includ limitarea la reviste porno, imagini statice de pe internet, diete porno etc. **NU FOLOSIȚI NICIUNUL dintre ele.** Acestea îngreunează, nu ușurează. Dacă aveți o senzație și folosiți un substitut, acesta nu va face decât să prelungească senzația, făcând-o mai grea. Ceea ce spui cu adevărat este că ai nevoie de porno pentru a umple golul. Va fi ca și cum ai ceda la un hoț sau la o criză de furie a unui copil, doar menținând durerile care vin și prelungind tortura. În orice caz, înlocuitorii nu vor ușura durerile. Pofta ta este pentru anumiți neurotransmițători din creier și tot ce va face este să te țină gândindu-te la porno. Amintiți-vă aceste puncte:

1.  Nu există un substitut pentru porno.

2.  Nu aveți nevoie de porno. Nu este hrană, este otravă. Când vin durerile, amintiți-vă că sunt utilizatorii care suferă de dureri de sevraj, nu non-utilizatorii. Vedeți-le pentru ceea ce sunt, un alt rău al drogului. Priviți-le ca pe moartea unui monstru.

3.  Pornografia pe internet creează golul, nu îl umple. Cu cât îți înveți mai repede creierul că nu ai nevoie să te uiți, cu atât mai repede vei fi liber. În special, evitați tot ceea ce seamănă cu pornografia, cum ar fi revistele pentru bărbați, filmele, romanele de dragoste și reclamele. Acest lucru nu înseamnă să fii închis la minte, este în regulă să vorbești despre romantism și sex, dar nu despre porno. Există întotdeauna o modalitate de a găsi când și unde să discriminezi. Este adevărat că o mică proporție de utilizatori care încearcă să renunțe la utilizarea pornografiei softcore sau a dietelor pornografice reușesc (din perspectiva lor) și își atribuie succesul unei astfel de utilizări. Cu toate acestea, ei renunță în * în ciuda * utilizării lor și nu din cauza acesteia. Este regretabil că mulți încă recomandă aceste măsuri.

Acest lucru nu este surprinzător, deoarece dacă nu înțelegeți pe deplin capcana porno, o dietă sau un înlocuitor moale sună foarte logic. Se bazează pe convingerea că atunci când încercați să renunțați la porno, aveți doi dușmani puternici de învins:

- Ruperea obiceiului.

- Supraviețuirea unor dureri fizice teribile de sevraj fizic. 

Dacă ai de învins doi inamici puternici, este bine să nu te lupți cu ei simultan, ci pe rând. Deci, teoria spune că atunci când încetați pentru prima dată să mai folosiți porno, reduceți la o dată pe săptămână sau folosiți porno softcore. Apoi, odată ce obiceiul este rupt, reduceți treptat aportul, abordând astfel fiecare inamic separat.

Acest lucru sună logic, dar se bazează pe informații incorecte. Pornografia nu este obișnuință, ci dependență de dopamină, iar durerea fizică reală de sevraj este aproape imperceptibilă. Ceea ce încercați să obțineți atunci când renunțați este să ucideți cât mai repede posibil atât monștrii din corp, cât și pe cei din creier. Tot ceea ce fac tehnicile de substituție este să prelungească viața micului monstruleț și, la rândul său, acest lucru prelungește spălarea creierului. EasyPeasy facilitează renunțarea imediată, ucigând spălarea creierului înainte de ultima sesiune. Micul monstruleț va fi în curând mort și chiar și în timp ce moare, nu va fi o problemă mai mare decât a fost atunci când erați utilizator.

Gândiți-vă, cum puteți vindeca dependența de un medicament prin recomandarea aceluiași medicament? Există multe povești online despre cei care au renunțat să mai folosească pornografia hardcore pe internet, dar sunt dependenți de alternativele "sigure", după ce au căzut în plasa justificărilor micului lor monstruleț. Nu vă lăsați păcăliți de faptul că pornografia sigură nu este îngrozitoare - la fel a fost și primul clip de mare viteză. Toți înlocuitorii au exact aceleași efecte ca orice porno. Unii chiar încep să mănânce mult, dar, deși senzația de gol de a dori o sesiune este imposibil de distins de foamea de mâncare, una nu o va satisface pe cealaltă. De fapt, dacă există ceva care este conceput pentru a vă face să vă doriți porno, este să vă îndopați cu mâncare. După cum am explicat anterior, dietele porno și porno sigur nu vor face decât să vă pună în mijlocul luptei, rezistența la tentație fiind atât de enervantă încât vă veți simți ușurat să vizitați haremul dvs. online preferat.

Răul principal al înlocuitorilor este prelungirea adevăratei probleme, spălarea creierului. Aveți nevoie de un substitut pentru gripă când aceasta se va termina? Bineînțeles că nu ai nevoie. Spunând că ai nevoie de un substitut pentru pornografie, ceea ce spui de fapt este că faci un sacrificiu. Depresia asociată cu metoda voinței este cauzată de faptul că utilizatorul crede că face un sacrificiu. Tot ceea ce veți face este să înlocuiți o problemă cu alta. Nu există nicio plăcere în a te îndopa cu mâncare, țigări sau alcool. Te vei îngrășa, te vei simți mizerabil și în cel mai scurt timp te vei întoarce la droguri. 

Utilizatorilor ocazionali le este greu să respingă convingerea că sunt privați de mica lor recompensă, cum ar fi cei cărora nu li se permite să se conecteze la internet în timpul unei perioade de timp în timpul unei călătorii, al unui eveniment de familie etc. Unii spun: "*Nu aș ști cum să mă relaxez dacă nu ar fi pornografia*". Acest lucru dovedește punctul de vedere - de multe ori pauza este luată nu pentrucă utilizatorul are nevoie sau chiar o dorește, ci pentru că dependentul - ceea ce ei sunt - are nevoie disperată de a se scărpina de mâncărime.

Amintiți-vă, sesiunile porno nu au fost niciodată recompense autentice. Ele au fost echivalente cu purtarea de pantofi strâmți pentru a simți plăcerea de a-i da jos. Așa că, dacă simțiți că trebuie să aveți o mică recompensă, lăsați ca aceasta să fie înlocuitorul vostru; în timp ce lucrați purtați pantofi sau lenjerie intimă cu o mărime mai mică și nu vă permiteți să îi scoateți până când nu aveți pauza, apoi experimentați momentul minunat de relaxare și satisfacție atunci când sunt scoși. Poate vi se pare că ar fi mai degrabă o prostie. Aveți perfectă dreptate. Poate fi dificil să vizualizezi în timp ce ești încă în capcană, dar asta fac utilizatorii. Este, de asemenea, greu să vizualizezi că în curând nu vei mai avea nevoie de acea mică "recompensă" și că în curând îți vei privi prietenii care sunt încă în capcană cu milă sinceră și te vei întreba de ce nu pot vedea rostul. 

However, if you continue kidding yourself that the online harem visit was a genuine reward, or that you need a substitute, you'll feel deprived and miserable. The chances are that you'll end up falling into the disgusting trap again. If you need a genuine break as housewives, teachers, doctors, and other workers do, you'll soon be enjoying that break even more because you won't have to addict yourself. Remember that you don't need a substitute. The pangs are a craving for dopamine and will soon be gone. Let that be your prop for the next few days and enjoy ridding your body and mind of slavery and dependence.
 
Cu toate acestea, dacă continui să te amăgești că vizita la haremul online a fost o recompensă autentică sau că ai nevoie de un înlocuitor, te vei simți lipsit și nefericit. Șansele sunt că veți ajunge să cădeți din nou în capcana dezgustătoare. Dacă aveți nevoie de o pauză autentică, așa cum fac gospodinele, profesorii, medicii și alți lucrători, în curând vă veți bucura și mai mult de acea pauză, deoarece nu va trebui să vă faceți dependentă. Amintiți-vă că nu aveți nevoie de un înlocuitor. Durerile sunt o poftă de dopamină și vor dispărea în curând. Lasă asta să fie recuzita ta pentru următoarele câteva zile și bucură-te de eliberarea corpului și a minții tale de sclavie și dependență.