# Ar trebui să evit situațiile de tentație?

Sfaturile au fost directe până acum și v-au cerut să le tratați mai degrabă ca pe niște instrucțiuni decât ca pe niște sugestii. Există motive solide și practice pentru acest sfat, iar aceste motive au fost susținute de mii de studii de caz. În ceea ce privește întrebarea dacă trebuie sau nu să încerci să eviți tentația, nu este cazul. Fiecare utilizator va trebui să decidă pentru el însuși. Cu toate acestea, se pot face două sugestii utile pentru a vă ajuta în acest proces. Frica de viitoarele dureri de sevraj este cea care ne face să folosim pornografia pentru tot restul vieții noastre, iar această frică constă în două faze distincte.

**Prima fază - "*Cum pot supraviețui fără porno?*"**

Această teamă este sentimentul de panică pe care îl are utilizatorul atunci când este singur sau are un partener asexual, neinteresat sau indisponibil. Frica nu este cauzată de senzația de sevraj, ci este teama psihologică de dependență, de a nu putea supraviețui fără sex și orgasm. Aceasta atinge apogeul atunci când sunteți pe punctul de a renunța, când durerile de sevraj sunt la cel mai scăzut nivel. Este frica de necunoscut, genul de frică pe care o au oamenii când învață să se scufunde.

Trambulina are o înălțime de un metru, dar pare să aibă șase metri. Apa are o adâncime de doi metri, dar pare a avea un metru. E nevoie de curaj pentru a te lansa, convins fiind că îți vei sparge capul. Lansarea este partea cea mai grea, dacă găsești curajul de a o face - restul este ușor! Așa se explică de ce mulți consumatori cu voință puternică nu au încercat niciodată să se oprească, sau pot supraviețui doar câteva zile atunci când o fac. De fapt, există unii utilizatori care țin diete pornografice care, după ce decid să se oprească, de fapt, fac binge watching și escaladează la clipuri mai dure mai repede decât dacă nu ar fi decis să se oprească. Decizia provoacă panică, ceea ce este stresant și declanșează un indiciu pentru a face o excursie la harem. Dar acum nu mai poți avea unul, ceea ce duce la gânduri de privare, agravând stresul.

Declanșatorul se activează rapid atunci când se arde fitilul și porniți browserul. Nu vă faceți griji, panica este doar psihologică. Este teama că ești dependent. Frumosul adevăr este că nu ești, chiar dacă ești încă dependent. Nu te panica și lansează-te.

**Faza a doua - Frica pe termen mai lung**.

Cea de-a doua fază este pe termen lung, implicând teama că anumite situații în viitor nu vor fi plăcute sau că nu veți putea face față traumei fără porno. Nu vă faceți griji, dacă puteți să vă lansați, veți constata că se va întâmpla contrariul. Evitarea tentației în sine se încadrează în două categorii.

1.  "* Voi subscrie la o dietă pornografică de o dată în patru zile. Mă voi simți mai încrezător știind că pot merge online dacă devine dificil. Dacă nu reușesc, este în regulă, voi adăuga doar zile suplimentare la următorul meu ciclu.*"

    Rata de eșec la persoanele care fac acest lucru este ** mult mai mare** decât cei care renunță cu totul. Acest lucru se datorează în principal faptului că, dacă ai un moment prost în timpul perioadei de abstinență, este ușor să sari pe browser și să vizitezi haremul cu scuzele de mai sus. Dacă ai parte de indignarea de a-ți încălca în mod clar propriile reguli ca un geam de sticlă spartă, este mai probabil să depășești tentația. În orice caz, probabil că pofta ar fi trecut deja dacă ai fi amânat-o. Cu toate acestea, principalul motiv pentru rata mare de eșec în aceste cazuri este faptul că utilizatorul nu s-a simțit complet angajat să se oprească de la bun început. Amintiți-vă că cele două elemente esențiale pentru a reuși sunt:

    - Certitudine.

    - "*Nu e minunat că nu mai am nevoie de pornografie?*"

    În orice caz, de ce naiba ai nevoie de o ședință? Dacă încă mai ai nevoie să-ți vizitezi haremul, recitește mai întâi cartea. Ceva nu s-a închegat bine. Ia-ți timp să omori marele monstru de spălare a creierului din mintea ta

2.  "*Ar trebui să evit ocaziile stresante sau sociale în timpul perioadei de sevraj?*"

    În cazul situațiilor stresante, da. Nu are rost să vă puneți o presiune nejustificată pe voi înșivă. În cazul evenimentelor sociale, cum ar fi barurile sau cluburile, sfatul este invers. Ieșiți în oraș și distrați-vă imediat! Nu ai nevoie de sex sau de latura propagatoare a sexului nici măcar în timp ce ești dependent de pornografie. Ieși în oraș și bucură-te de faptul că nu trebuie să faci sex sau sex propagativ, îți va dovedi rapid frumosul adevăr că viața este mult mai bună fără aceste presiuni. Gândește-te cât de mult mai bine va fi atunci când micul monstruleț te va părăsi, împreună cu acele gânduri de nevoie.
