# Momentul Revelației

De obicei, în decurs de trei săptămâni după evadare, foștii consumatori experimentează momentul revelației. Cerul pare să devină mai luminos și este momentul în care spălarea creierului se termină complet. Când, în loc să vă spuneți că nu aveți nevoie să vă uitați la porno, vă dați brusc seama că ultimul fir este rupt și vă puteți bucura de restul vieții fără să mai aveți nevoie de el vreodată. De asemenea, din acest moment, de obicei, începeți să priviți utilizatorii ca pe niște obiecte de milă.

Cei care renunță folosind metoda voinței nu experimentează în mod normal acest moment, deoarece, deși sunt bucuroși că sunt foști consumatori, ei continuă să meargă prin viață crezând că fac un sacrificiu. Cu cât ai fost mai dependent, cu atât mai minunat este acest moment, care durează o viață întreagă. Deși există multe bucurii în viață, este imposibil să recapturezi sentimentul real de a le trăi. Bucuria de a nu mai fi nevoit să te uiți la porno este diferită, dacă te simți deprimat și ai nevoie de un impuls, amintește-ți cât de minunat este să nu fii dependent de acea dependență îngrozitoare. Mulți o enumeră ca fiind unul dintre cele mai mari evenimente din viața lor. În cele mai multe cazuri, momentul de revelație are loc nu după trei săptămâni, ci după câteva zile. 

În cazul meu, s-a întâmplat înainte de a termina ultima mea vizită în harem. Sunt sigur că mulți dintre cititorii de aici, înainte de a ajunge la sfârșitul capitolelor, ar fi spus ceva de genul "*Nu trebuie să mai spui nimic. Pot să văd totul atât de clar, încât știu că nu voi mai avea nevoie de porno niciodată.*" Pe baza feedback-ului primit, acest lucru se întâmplă frecvent. În mod ideal, dacă urmați toate instrucțiunile și înțelegeți complet psihologia, ar trebui să vi se întâmple imediat.

Deși se afirmă că este nevoie de aproximativ cinci zile pentru ca sevrajul fizic vizibil să dispară și de aproximativ trei săptămâni pentru ca un fost utilizator să se elibereze complet, astfel de indicații pot cauza două probleme. Prima fiind faptul că se implantează în mintea oamenilor sugestia că vor trebui să sufere între cinci zile și trei săptămâni. A doua este că fostul utilizator tinde să gândească: "*Dacă pot supraviețui timp de cinci zile sau trei săptămâni, mă pot aștepta la un impuls real la sfârșitul acestei perioade.*"

Cu toate acestea, ei pot avea cinci zile plăcute sau trei săptămâni plăcute, urmate apoi de zile dezastruoase care lovesc pe toată lumea, care nu au nimic de-a face cu dependența, ci sunt cauzate de alți factori din viața noastră. Atunci, fostul nostru consumator care așteaptă momentul revelației experimentează în schimb depresia. Aceasta le poate distruge încrederea în sine. În aceeași ordine de idei, dacă nu ar exista îndrumări, fostul utilizator și-ar putea petrece tot restul vieții așteptând să nu se întâmple nimic. Aceasta este ceea ce li se întâmplă marii majorități a celor care renunță să mai folosească metoda voinței. 

Oamenii se întreabă adesea despre semnificația celor cinci zile și a celor trei săptămâni. Sunt pur și simplu perioade trase din senin? Nu, deși nu sunt date precise, ele reflectă o acumulare de feedback de-a lungul anilor. Aproximativ cinci zile după ce s-a oprit este momentul în care fostul consumator încetează să mai aibă dependența ca ocupație principală a minții sale. Cei mai mulți foști consumatori experimentează revelații în jurul acestei perioade, în general în situații stresante sau sociale cărora la un moment dat nu erau capabili să le facă față sau nu erau plăcute fără o vizită la harem. Dintr-o dată vă dați seama că nu numai că vă bucurați sau faceți față, dar gândul la pornografie nici măcar nu v-a trecut prin cap. Din acel moment, de obicei, totul este simplu. Atunci știi că ești liber.

Este atât experiența mea, cât și a multor altora care încearcă să se oprească folosind * metoda voinței * că în jurul perioadei de trei săptămâni este momentul în care majoritatea încercărilor serioase de a se opri eșuează. Ceea ce se întâmplă de obicei este că, după aproximativ trei săptămâni, simțiți că ați pierdut dorința de a vă uita la porno. Trebuie să vă dovediți acest lucru, așa că săriți pe browser pentru a vă vizita haremul. Se simte ciudat, dovedind că ați renunțat la ea. Dar, în acest proces, ești uns pe toboganul de apă DeltaFosB datorită grabei proaspete de dopamină, ceea ce corpul tău a dorit în ultimele trei săptămâni. De îndată ce termini fapta, dopamina începe să părăsească organismul tău. O voce mică reapare: "*Nu ai renuntat cu adevarat, mai vrei încă o sesiune*".

Nu vă grăbiți să vă întoarceți imediat pentru că nu vreți să vă molipsiți din nou, lăsând să treacă o perioadă de siguranță. Atunci când ești tentat din nou, poți să-ți spui: "*Bine, nu am fost dependent din nou, așa că nu e nici un rău să mai fac inca o sesiune. "* Ești deja pe drumul cel bun spre panta alunecoasă a dependenței. Cheia problemei nu constă în a aștepta momentul revelației, ci în a realiza că, odată ce ai închis browserul, s-a terminat. Ai tăiat alimentarea cu oxigen a micului tău monstruleț. Nicio forță de pe Pământ nu te poate împiedica să fii liber, *cu excepția cazului în care te plângi de asta sau aștepți revelația.* Du-te și bucură-te de viață; fă-i față de la bun început. Momentul va sosi în curând.
