# Vizita finală

După ce ați decis asupra momentului, sunteți gata să vă vizitați haremul pentru ultima oară. Înainte de a face acest lucru, verificați cele două lucruri esențiale.

1.  Vă simțiți sigur de reușită?

2.  Aveți un sentiment de pesimism sau un sentiment de entuziasm că sunteți pe cale să realizați ceva minunat?

Dacă aveți îndoieli, recitiți mai întâi cartea. Amintiți-vă că nu ați decis niciodată să cădeți în capcana porno, dar capcana este concepută pentru a vă înrobi pe viață. Pentru a scăpa, trebuie să luați decizia pozitivă că sunteți pe cale să vă opriți și să faceți ultima vizită.  

Nu uita, singurul motiv pentru care ai citit această carte până acum este pentru că ți-ar plăcea foarte mult să evadezi. Așa că ia acum această decizie pozitivă, făcând un jurământ solemn că atunci când vei închide fereastra privată a browserului, fie că ți se pare ușor sau dificil, nu vei mai vizita niciodată haremul tău. Poate că ești îngrijorat că ai făcut acest jurământ de mai multe ori în trecut și tot nu reușești, sau că va trebui să treci printr-o traumă îngrozitoare. Nu vă temeți, cel mai rău lucru care se poate întâmpla este să eșuați, așa că, prin urmare, nu aveți ***absolut nimic*** de pierdut și atât de multe de câștigat.

Dar nu vă mai gândiți nici măcar la eșec - frumosul adevăr este că nu numai că este ridicol de ușor să renunți, dar chiar te poți bucura de acest proces. De data aceasta vei folosi EasyPeasy! Tot ce trebuie să faci este să urmezi instrucțiunile simple care urmează să ți se dea.

1.  Faceți acum jurământul solemn și fiți serioși.

2.  Răsfoiți în mod conștient imaginile și clipurile de pe site-ul dvs. preferat de porno, uitându-vă la încercările disperate ale administratorilor site-ului, ale actorilor și chiar ale amatorilor de a amplifica șocul, noutatea și natura supranormală a mărfii lor și întrebați-vă unde este plăcerea.

3.  Când, în cele din urmă, închideți browserul, nu o faceți cu un sentiment de  "*Nu am voie să mai vizitez alt site porno*", ci cu un sentiment de libertate, de genul "*Nu este minunat? Sunt liberă! Nu mai sunt sclavul pornografiei! Nu trebuie să mai vizitez niciodată în viața mea aceste site-uri murdare*".

4.  Fiți conștienți de faptul că, pentru câteva zile, va exista un mic sabotor porno în interiorul stomacului dvs. S-ar putea să fii conștient doar de sentimentul de a dori o sesiune. Micul monstru pornografic a fost denumit ca fiind o ușoară poftă fizică de dopamină. Strict vorbind, acest lucru este incorect și este important să înțelegem de ce. Deoarece este nevoie de până la trei săptămâni pentru ca acel mic monstru să moară, foștii utilizatori cred că micul monstru va continua să tânjească după ultima vizită la haremul online și, prin urmare, trebuie să folosească voința pentru a rezista tentației în această perioadă. Nu este așa, corpul nu tânjește după dopamina declanșată de porno; doar creierul tânjește.

Dacă în următoarele zile veți simți că vreți să aruncați o privire, creierul dumneavoastră are o alegere simplă. Poate fie să interpreteze acest sentiment pentru ceea ce este de fapt - un sentiment de gol, de nesiguranță, declanșat de prima vizită pe un site porno online și perpetuat de fiecare vizită ulterioară, și să îți spui **"YIPPEE! SUNT UN NON-UTILIZATOR!"**.

Sau, puteți începe să tânjiți după porno și să suferiți pentru restul vieții. Gândiți-vă pentru un moment, nu ar fi un lucru incredibil de prostesc de făcut? Să spui: "*Nu vreau să mă mai uit niciodată la porno*" și apoi să-ți petreci restul vieții spunând "*Aș dori o vizită*"? Asta fac cei care folosesc metoda voinței și nu e de mirare că se simt atât de nefericiți. Petrecându-și restul vieții plângând cu disperare pentru ceva ce speră cu disperare că nu vor avea niciodată. Nu e de mirare că atât de puțini reușesc, iar cei puțini care reușesc nu se simt niciodată complet liberi.

> *'Întipărește-ți clar în minte această imagine mentală, pentru că ea poate fi de mare ajutor în a depăși puterea stimulilor externi de a te tulbura. Imaginați-vă stând liniștit, lăsând telefonul să sune, ignorând semnalul acestuia, nemișcat de comanda sa. Deși ești conștient de el, nu-l mai bagi în seamă și nici nu i te mai supui. De asemenea, aveți clar în minte faptul că semnalul exterior în sine nu are nicio putere asupra voastră, nicio putere de a vă mișca. În trecut, l-ați ascultat, i-ați răspuns, pur și simplu din obișnuință. Puteți, dacă doriți, să vă formați un nou obicei, acela de a nu-i răspunde.*
>
> *"Observați, de asemenea, că eșecul vostru de a răspunde nu constă în a face ceva, în a face un efort, în a rezista sau a lupta, ci în a nu face nimic - în a vă relaxa de la a face. Pur și simplu te relaxezi, ignori semnalul și lași chemarea lui să rămână fără răspuns. Telefonul care sună este o analogie simbolică pentru orice alt stimul exterior căruia i-ai putea da controlul în mod obișnuit și acum alegi să modifici acest obicei în mod foarte intenționat. "*'
>
> --- Maxwell Maltz, *The New Psycho Cybernetics* Cap. 12. 

Doar îndoiala și așteptarea fac dificilă renunțarea, *** deci nu te îndoi niciodată de decizia ta***, pentru că știi că este cea corectă. Dacă începi să te îndoiești de ea, te vei pune într-o situație fără ieșire. Mizerabil în timp ce tânjești după o vizită, dar nu poți avea una. Indiferent de sistemul pe care îl folosiți, ce încercați să obțineți atunci când renunțați la porno? Să nu te uiți niciodată din nou? Nu! Mulți foști utilizatori fac asta, dar trec prin restul vieții lor simțindu-se privați.

Care este diferența dintre utilizatori și non-utilizatori? Non-utilizatorii nu au nici nevoia, nici dorința de a se uita la porno, sunt fără poftă și nu au nevoie să exercite voința pentru a nu se uita la el. Asta este ceea ce încercați să obțineți și este complet în puterea dvs. de a face acest lucru. Nu trebuie să așteptați să încetați să mai poftiți la porno sau să deveniți un non-utilizator, totul este gata în momentul în care închideți acea ultimă fereastră de browser, tăind aprovizionarea cu dopamină. **EȘTI DEJA UN NON-UTILIZATOR FERICIT!**

Veți rămâne un non-utilizator fericit cu condiția să: 

1.  Nu te îndoiești niciodată de decizia ta.

2.  Nu aștepți să devii un non-utilizator. Dacă o faci, nu vei face decât să aștepți să nu se întâmple nimic și să creezi o fobie.

3.  Nu încerci să *nu* te gândești la pornografie sau să aștepți să vină "momentul de revelație", creând o fobie.

4.  Nu folosești înlocuitori.

5.  Îi vezi pe toți ceilalți utilizatori așa cum sunt cu adevărat și îi compătimești în loc să îi invidiezi.

Indiferent dacă sunt zile bune sau rele, nu-ți schimba viața in rau doar pentru că te-ai lăsat. Dacă o vei face, vei face un sacrificiu autentic atunci când nu este nevoie. Ține minte, nu ai renunțat la viață. Nu ai renunțat la nimic. Dimpotrivă, te-ai vindecat de o boală îngrozitoare și ai evadat dintr-o închisoare insidioasă. Pe măsură ce zilele trec și sănătatea ta - atât fizică, cât și mentală - se îmbunătățește, maximele vor părea mai mari și minimele mai puțin scăzute decât atunci când erai consumator. Ori de câte ori vă gândiți la pornografie în următoarele câteva zile sau în restul vieții, gândiți-vă:

***"YIPPEE! SUNT UN NON-UTILIZATOR!"***

## Un ultim avertisment

Niciun utilizator, dacă ar avea șansa de a se întoarce în timp înainte de a deveni dependent, cu cunoștințele pe care le are acum, nu ar opta să înceapă. Zeci de mii de persoane care reușesc să renunțe cu succes la viciu timp de mulți ani duc o viață perfect fericită, doar pentru a fi prinși din nou în capcană. Am încredere că această carte vă va ajuta să vă fie relativ ușor să vă opriți. Dar fiți atenți, utilizatorii cărora le este ușor să se oprească găsesc la fel de ușor să înceapă din nou. **Nu cădeți în această capcană.**

Indiferent de cât de mult timp ați oprit sau cât de încrezător sunteți sigur că nu veți deveni din nou dependent, faceți o regulă pentru viață să nu vă uitați la porno pentru nici un motiv. Rezistați aluziilor și aluziilor din mass-media și amintiți-vă cum împing imaginea de "deschidere" prin aducerea pornografiei în mainstream, fără să știe că pornografia și masturbarea compulsivă sunt ucigași ai relațiilor și ai sentimentului personal de bunăstare pentru un număr imens de bărbați și un număr tot mai mare de femei.

Amintiți-vă că acea primă privire sau vizită nu va face nimic pentru dvs. Nu veți avea nicio durere de sevraj care trebuie eliminata printr-o sesiune si care va face să vă simțiți groaznic. Ceea ce va face va fi să vă pună în minte și în creier plăcerea de a vă simțiți plin de dopamină, iar o voce mică din spatele minții vă va spune că vreți alta sesiune. Apoi ai de ales între a te simți nefericit pentru o vreme sau a începe din nou întregul lanț mizerabil.

