# Feedback

Războiul nu este împotriva utilizatorilor, ci împotriva capcanei industriei porno, și este purtat pentru simplul motiv că îmi place să îl duc. De fiecare dată când aud despre un utilizator care scapă din închisoare, am un sentiment de imensă plăcere. Dar această plăcere nu a fost lipsită de o frustrare considerabilă, cauzată în principal de două categorii de utilizatori porno. În ciuda avertismentului din capitolul anterior, sunt surprins continuu de numărul celor cărora le este ușor să se oprească, dar care, mai târziu, devin dependenți și constată că nu mai reușesc data viitoare.

Este ca și cum ai găsi pe cineva băgat până la gât într-o mlaștină și pe cale să se scufunde. Îl ajuți să îl scoți și îți este recunoscător, dar apoi, șase luni mai târziu, se scufundă din nou direct în mlaștină. Utilizatorii cărora le este ușor să se oprească și să o ia de la capăt reprezintă o problemă specială, însă atunci când vă eliberați ***VĂ RUGĂM, vă rog, NU FACEȚI ACEEAȘI GREȘEALĂ.*** Ei cred că astfel de oameni încep din nou pentru că sunt încă dependenți și le lipsește dopamina. De fapt, le este atât de ușor să se oprească încât își pierd frica de pornografie. Ei se gândesc: "*Pot să am o sesiune din cand in cand și chiar dacă voi deveni din nou dependent, îmi va fi ușor să mă opresc*".

Mă tem că nu funcționează așa, pentru că este ușor să te oprești din pornografie, dar este imposibil să controlezi dependența. Singurul lucru esențial pentru a opri pornografia este să nu o folosești.
People usually come back to porn because they misunderstand the “easy" in EasyPeasy.

De obicei, oamenii se întorc la pornografie pentru că nu înțeleg ce înseamnă "ușor" în EasyPeasy(Metoda ușoară).

Imaginați-vă că cineva stă pe podeaua rece de beton dintr-o cameră înghețată. Pe peretele opus se află o fereastră care arată o zi perfectă de primăvară afară - copaci care se leagănă ușor, păsări care ciripesc - chiar lângă o ușă descuiată. 

Este nevoie de voință pentru a ieși din acea cameră înghețată? Nu! Este mai greu să evadezi decât să rămâi? Bineînțeles că nu! (De fapt, este un pic mai ușor datorită mișcării corpului). De ce s-ar pune cineva întreg la minte într-o astfel de situație, provocându-și luni sau ani de frustrări, dacă nu a fost păcălit?

EasyPeasy dă la o parte perdelele pentru ca utilizatorul să poată vedea clar afară și pentru a elimina **iluziile** despre cât de groaznic poate fi afară și cât de confortabil se simte utilizatorul în cameră.

Cealaltă categorie de utilizatori frustrați sunt cei prea speriați pentru a face încercarea de a se opri sau, atunci când o fac, consideră că este o mare luptă. Principalele dificultăți par a fi următoarele.

**Teama de eșec.** 

:   Nu este o rușine să eșuezi, dar să nu încerci este o prostie. Privește lucrurile astfel, te ascunzi de nimic. Cel mai rău lucru care se poate întâmpla este să eșuezi, caz în care nu ești mai rău decât ești acum. Gândiți-vă cât de minunat ar fi să reușiți. Dacă nu faceți încercarea, ați garantat deja eșecul.

**Frica de durere și de a fi nefericit.**

:   Nu-ți face griji în legătură cu asta, gândește-te doar: ce lucru îngrozitor ți s-ar putea întâmpla dacă nu te-ai mai uita niciodată la porno? Absolut nimic. Lucruri teribile *se vor* întâmpla dacă o faci; recitește notele despre Pariul lui Pascal. În orice caz, panica este cauzată de dopamină și va dispărea în curând. Cel mai mare câștig este să scapi de acea frică. Chiar credeți că utilizatorii sunt pregătiți să aibă penetrări care se estompează, performanțe sexuale nesigure sau plăcerea iluzorie pe care o obțin din porno? Dacă vă aflați în panică, respirația profundă vă va ajuta. Dacă sunteți cu alte persoane și vă deprimă, scăpați de ele și mergeți în garaj, într-un birou gol sau undeva.

    Dacă vă vine să plângeți, nu vă fie rușine. Plânsul este un mod natural de eliberare a tensiunii. Nimeni nu a plâns vreodată fără să se simtă mai bine după aceea. Unul dintre lucrurile îngrozitoare pe care le facem tinerilor este să-i condiționăm să nu plângă. Îi puteți vedea cum încearcă să se împotrivească lacrimilor, dar urmăriți cum le macină maxilarul. Ne învățăm să nu ne arătăm emoțiile, dar nu suntem meniți să le îmbuteliem în interior. Țipă sau lovește ceva. Privește-ți lupta ca pe un meci de box pe care nu-l poți pierde. Nimeni nu poate opri timpul, cu fiecare clipă care trece acel mic monstru din tine moare. Bucură-te de victoria ta inevitabilă.

**Nu respecți instrucțiunile.**

:   Incredibil, unii utilizatori spun că metoda nu a funcționat pentru ei. Ei descriu apoi cum au ignorat nu doar o instrucțiune, ci practic toate instrucțiunile. Pentru claritate, acestea sunt rezumate sub forma unei liste de verificare la sfârșitul acestui capitol.

**Înțelegerea greșită a instrucțiunilor.**

:   Principalele probleme par a fi următoarele:

    "Nu mă pot opri să nu mă gândesc la porno."

    :   Bineînțeles că nu poți și dacă încerci, vei crea o fobie, devenind nefericit. Este ca și cum ai încerca să adormi noaptea: cu cât încerci mai mult, cu atât mai greu devine. Nu contează dacă te gândești la pornografie timp de nouăzeci la sută din viața ta, important este ceea ce gândești. Dacă te gândești "*Oh, îmi place să mă uit la porno*" sau "*Când voi fi liber?*", vei fi nefericit. Dacă în schimb te gândești "*YIPPEE! Sunt liber!*" vei fi fericit.

    "*Când va muri micul monstru porno?*"

    :   Fluxul de dopamină părăsește corpul foarte repede, dar este imposibil de spus când corpul dumneavoastră va înceta să mai sufere de senzația fizică ușoară de sevraj de dopamină. Acea senzație de gol, de nesiguranță este identică cu foamea normală, depresia sau stresul. Tot ceea ce face pornografia este să crească nivelul acestuia. Acesta este motivul pentru care utilizatorii care încetează să mai folosească metoda voinței nu sunt niciodată foarte siguri că au renunțat la ea, chiar și după ce corpul lor a încetat să mai sufere de sevraj de dopamină. Dacă suferă de foame sau stres normal, creierul lor încă le spune că acesta este un motiv valabil pentru a-și revendica sesiunea îndreptățită. Ideea este că nu trebuie să așteptați ca pofta să dispară, deoarece este atât de ușoară încât nici măcar nu știm că este acolo, cunoscând-o doar ca pe o senzație de dorință. Când plecați de la dentist așteptați să nu vă mai doară maxilarul? Bineînțeles că nu, îți continui viața. Chiar dacă încă te doare maxilarul, ești exaltat.

Nu așteptați ca sevrajul să plece pentru că veți crea îndoieli întrebându-vă în mod constant "*Cât va dura? Sunt măcar liber dacă nu mă simt diferit?*". Frica este durerea propriu-zisă, prin urmare, așteptând ca viața să se îmbunătățească după ce te-ai lăsat de PMO, vei crea îndoială. Sevrajul este imperceptibil dacă nu vă temeți de el, iar îmbunătățirile exponențiale ale neurologiei sunt lente, așa că, dacă așteptați să vă simțiți diferit, veți avea impresia că nu se întâmplă nimic, creând îndoială.

    *"Momentul revelației nu a sosit încă." *

    :   Dacă îl aștepți, nu faci decât să provoci o altă fobie. Odată m-am oprit timp de trei săptămâni pe metoda voinței. Discutând cu un vechi prieten, m-a întrebat cum mă descurc.
        "*Am supraviețuit trei săptămâni*", i-am răspuns.
        El m-a întrebat: "*Cum adică ai supraviețuit trei săptămâni?*".
        Am clarificat: "*Am rezistat trei săptămâni fără porno.*"
        El a spus: "*Ce ai de gând să faci? Să supraviețuiești tot restul vieții tale? Ce mai aștepți, ai reușit. Ești un non-utilizator.*"

        M-am gândit: "*A are perfectă dreptate, ce mai aștept?*" Din nefericire, din cauza lipsei de înțelegere a capcanei, în scurt timp am intrat din nou în ea, dar ideea a fost notată. Deveniți un non-utilizator atunci când închideți browserul. Important este să fii un non-utilizator fericit încă de la început.

    "*Încă mai am poftă de pornografie.*"

    :   Atunci ești foarte prost. Cum poți pretinde că vrei să fii un non-utilizator și apoi să spui că îți dorești porno? Aceasta este o contradicție. Dacă spui că îți dorești porno, spui că vrei să fii un utilizator. Non-utilizatorii nu vor să viziteze site-urile de porno dezgustătoare. Știi deja ce vrei să fii, așa că nu te mai pedepsi.

    "*Am renunțat la viață.*"   :   De ce? Tot ce trebuie să faceți este să nu vă mai omorâți și să începeți să vă energizați în schimb. Nu trebuie să încetezi câtuși de puțin să trăiești. Este la fel de simplu ca și cum ar fi așa: în următoarele două zile vei avea o ușoară traumă în viața ta. Corpul tău va suferi agravarea aproape imperceptibilă a sevrajului față de cererile și pretențiile pentru un val de dopamină. Acum, țineți cont de acest lucru: nu sunteți mai prejos decât erați. Este ceea ce ați suferit toată viața, de fiecare dată când ați dormit, în biserică, la supermarket sau la bibliotecă. Nu părea să vă deranjeze cât timp erați consumator și, dacă nu vă opriți, veți continua să suferiți această suferință pentru tot restul vieții.

        Pornografia și orgasmele nu creează ocazii, ci te privează de ele. Chiar și în timp ce corpul tău încă tânjește după dopamină, mesele și ocaziile sociale sunt minunate. Viața este minunată - mergeți la evenimente sociale, chiar dacă acolo sunt dansatoare dezbrăcate. Țineți minte că nu voi sunteți privați, ci ei. Fiecare dintre ei ar vrea să fie în locul tău, dacă ar ști. Bucurați-vă de a fi primadonna și centrul atenției. Stoparea pornografiei este un minunat punct de conversație, luând o plăcere secretă pe care ei nu o pot face. Prietenii și colegii tăi vor fi surprinși să vadă că tu, care înainte erai timid și aveai un aspect obosit, ești acum fericit și vesel. Te vei bucura de viață încă de la început; nu este nevoie să invidiezi artiștii de agățat la petreceri, ei te vor invidia pe tine - dacă ar ști.

    "*Sunt mizerabil și iritabil*"   :   Aceasta este o nerespectare a instrucțiunilor. Aflați despre care este vorba. Unii oameni înțeleg și cred tot ce este scris, dar totuși încep cu un sentiment de tristețe, ca și cum s-ar întâmpla ceva teribil. Nu faci doar ceea ce ți-ar plăcea să faci, ci și ceea ce și-ar dori orice utilizator de pe planetă. Cu orice metodă de oprire, fostul utilizator încearcă să atingă o anumită stare de spirit, așa că fiecare gând legat de pornografie este punctat de "*YIPPEE! SUNT LIBER!*" Dacă acesta este obiectivul tău, de ce să mai aștepți? Începeți în această stare de spirit și nu o pierdeți niciodată. Nu există alternativă.

    "*Am avut o săptămână / lună / șase luni bune, dar m-am întors în capcană.*"

    :   Nu uitați, frica este însăși sentimentul de dorinta. A ceda în fața unei senzații de dorinta generează și mai multă frică, alimentând micul monstruleț slăbit și reușind să îl sperie pe ne-utilizator, făcându-l să creadă că este dependent pe viață. În realitate, conceptualizarea lor de spălare a creierului nu s-a schimbat, dar au dat dopamină procesului de gândire. Acest lucru este prin definiție o cădere în față, un eșec în a urma instrucțiunile. Înțelegeți care dintre dintre regulile de mai jos a fost incalcate și bucurați-vă, mergand inainte.  

## Lista de verificare

Dacă urmați aceste instrucțiuni, nu puteți da greș:

1.  Fă un jurământ solemn că niciodată, dar niciodată, nu vei intra pe internet pentru a-ți vizita haremul *sau* nu te vei mulțumi cu imagini statice *sau* nu te vei împăca cu grafica erotică *sau* cu orice conține stimuli supranormali, și respectă-ți jurământul.

2.  Înțelegeți clar acest lucru în mintea voastră: Nu este absolut nimic la care să renunți. Prin asta nu se înțelege că îți va fi mai bine ca ne-PMOer (ai știut asta tot timpul); nici că, deși nu există niciun motiv rațional pentru care faci PMO, obții o anumită plăcere sau o cârjă din asta, deoarece altfel nu ai face-o. Ceea ce înseamnă că nu există ***nu există o plăcere autentică sau o cârjă în PMOing.*** Este doar o iluzie, ca și cum te-ai da cu capul de perete pentru a obține plăcere atunci când te oprești.

3.  Nu există așa ceva ca un PMOer confirmat. Ești doar unul dintre sutele de milioane care au căzut în capcana subtilă. La fel ca milioanele de alți foști PMMOeri care au crezut cândva că nu pot scăpa, ai scăpat.

4.  Dacă în orice moment din viața ta ar trebui să cântărești avantajele și dezavantajele PMOing-ului, concluzia copleșitoare ar fi întotdeauna "*Nu mai face asta. Ești un prost!*" Nimic nu va schimba vreodată acest lucru. Întotdeauna a fost așa și așa va fi. După ce ai luat ceea ce știi că este decizia corectă, nu te mai chinui niciodată să te îndoiești. Pariul lui Pascal se aplică perfect la PMO, fără șanse de pierdere, cu șanse mari de câștig și șanse mari de a evita pierderile.  

5.  Nu încercați să nu vă gândiți la pornografie sau să vă faceți griji că vă gândiți la ea în mod constant. Ori de câte ori te gândești la porno, fie astăzi, mâine sau pentru tot restul vieții tale, gândește-te **"YIPPEE! Sunt un NON-PMOer!"**.

6.  **Nu** folosiți nicio formă de substitut. **Nu** vă provocați pe voi înșivă ținând laptopul lângă voi în timp ce dormiți. **Nu** evitați piesele de teatru, filmele sau revistele. **Nu** îți schimbați în niciun fel stilul de viață doar pentru că v-ați oprit. Dacă urmați instrucțiunile de mai sus, veți experimenta în curând "momentul revelației", dar:

7.  Nu așteptați ca "momentul revelației" să vină. Pur și simplu continuați-vă viața, bucurându-vă de momentele bune și făcând față celor rele. Vei vedea că în scurt timp momentul va sosi.
