# Ajutați-i pe cei de pe nava care se scufundă

Utilizatorii de filme porno intră în panică în zilele noastre, simțind schimbări în modul în care pornografia pe internet este percepută de bărbați și femei. Natura dependentă a pornografiei pe internet este studiată din ce în ce mai des, fiind considerată acum, pe bună dreptate, diferită de pornografia tradițională. Lipsa de efort și disponibilitatea ridică alarma chiar și în inimile susținătorilor porno. Aceștia simt, de asemenea, că cruciada lor pentru libertatea de exprimare și de gândire este deturnată de diverse elemente. Vestul sălbatic al internetului nepăzit face aproape imposibilă aplicarea restricțiilor de vârstă pentru stimulii supranormali. Este regretabil că acest lucru nu se va termina prea curând, dar sute de mii de utilizatori se opresc, majoritatea dependenților fiind conștienți de studiile care arată asemănări între pornografie și dependența de substanțe. De fiecare dată când un utilizator părăsește corabia care se scufundă, cei rămași pe ea se simt din ce în ce mai nefericiți.

Fiecare utilizator știe instinctiv că este ridicol să se autosaboteze și să petreacă timp în fața pixelilor bidimensionali, suprasolicitându-și creierul și dezvoltând în acest proces căi neuronale care garantează performanțe sexuale slabe. Dacă tot nu credeți că este o prostie, încercați să vorbiți cu o revistă porno care stă în centrul orașului dvs. și întrebați-vă care este diferența. Doar una singură. Nu poți obține plăcerea căldurii și a intimității în acest fel. Dacă poți să nu mai cumperi alcool și țigări de fiecare dată când mergi la cumpărături, cu siguranță poți să nu-ți mai vizitezi haremul online. Utilizatorii nu pot găsi motive raționale pentru a se uita la filme porno, dar nu se simt atât de prostiți dacă și alți oameni o fac.

Utilizatorii mint în mod flagrant în legătură cu obiceiul lor, nu doar în fața cercetătorilor și a celor din jur, ci și în fața lor înșiși. Trebuie să o facă - spălarea creierului este esențială pentru a-și păstra respectul de sine. Ei simt nevoia să își justifice "obiceiul" nu numai față de *săi*, ci și față de non-utilizatori. Întotdeauna fac publicitate la avantajele iluzorii ale pornografiei prin mijloace mai subtile.

Dacă un utilizator se oprește prin metoda voinței, acesta se simte în continuare privat, având tendința de a deveni un plângăcios. Tot ceea ce face acest lucru este să confirme celorlalți utilizatori cât de îndreptățiți sunt să continue să consume. Dacă fostul utilizator reușește să renunțe la viciu, atunci este recunoscător că nu mai trebuie să treacă prin viață autosabotat sau irosind energie și nu mai are nevoie să se justifice. Nu uitați, frica este cea care îi ține pe consumatori cu capul în nisip, punându-și la îndoială comportamentul doar atunci când se opresc. Ajutați utilizatorul prin eliminarea acestor temeri. Spuneți-i cât de minunat este să nu fie nevoit să treacă prin viață trăind într-o închisoare, cât de minunat este să se trezească dimineața simțindu-se în formă și sănătos în loc să fie lipsit de energie și să se disprețuiască pe sine, cât de minunat este să fie liber de sclavie, să se poată bucura de întreaga viață și să scape de acele umbre negre. Sau, și mai bine, convingeți-i să citească această carte.

Este esențial să nu denigrați un utilizator căsătorit, indicând că își distruge în mod deliberat relația sau că este într-un fel înșelător sau necurat. Există o concepție greșită comună conform căreia fostul utilizator este cel mai rău în acest aspect. Această concepție are o anumită substanță, dar se datorează în general metodei de oprire prin voință. Pentru că fostul utilizator - deși a renunțat la viciu - încă păstrează o parte din spălarea creierului și încă mai crede că a făcut un sacrificiu. Ei se simt vulnerabili și mecanismul lor natural de apărare este de a ataca utilizatorul de pornografie.

Acest lucru ar putea stimula orgoliul fostului utilizator, dar nu ajută cu nimic utilizatorul. Tot ceea ce face este să îi pună cu spatele la zid, făcându-i să se simtă și mai mizerabil și, în consecință, nevoia lor de pornografie să fie și mai mare. Cu toate că schimbarea atitudinii instituțiilor medicale față de pornografia pe internet este principalul motiv pentru care mulți utilizatori renunță, aceasta nu facilitează deloc acest lucru. De fapt, o face mult mai dificilă. Majoritatea utilizatorilor din zilele noastre cred că se opresc în primul rând din motive de sănătate. Acest lucru nu este strict adevărat.

Deși riscul enorm pentru sănătate este, în mod evident, principalul motiv pentru a renunța, utilizatorii își sabotează virilitatea de ani de zile și acest lucru nu a făcut nici cea mai mică diferență. Principalul motiv pentru care utilizatorii se opresc este că societatea începe să vadă pornografia demascată pentru ceea ce este: dependență de droguri. Atitudinea societății se schimbă încet-încet: mulți parteneri ar pune acum întrebări dacă ai sta pe laptop în mijlocul nopții.

Interzicerea completă a pornografiei în unele țări sau indisponibilitatea internetului sunt exemple clasice ale dilemei utilizatorului călător. În general, aceștia adoptă atitudinea că acest lucru îi va ajuta să își reducă consumul. Rezultatul este că, în loc de una sau două pe zi, niciuna dintre ele nu le-ar fi plăcut, se abțin o săptămână întreagă. Totuși, în timpul acestei perioade de abstinență forțată, nu numai că vor fi lipsiți mental în așteptarea recompensei, dar și corpul lor are poftă. Oh, cât de prețioasă este acea vizită în haremul online când, în cele din urmă, li se permite.

Abstinența forțată nu reduce de fapt consumul, deoarece utilizatorul se răsfață și mai mult atunci când, în sfârșit, i se permite să fie singur. Tot ceea ce face este să întipărească în mintea utilizatorului cât de prețioasă este pornografia pe internet și cât de dependentă este de ea. Cel mai insidios aspect al acestei abstinențe forțate este efectul său asupra adolescenților. Le permitem deturnatorilor "libertății de exprimare", producătorii de pornografie, să vizeze adolescenții nefericiți pentru a-i face dependenți. Apoi, în ceea ce este probabil cea mai stresantă perioadă din viața lor, când, în mințile lor iluzorii, au nevoie de pornografie cel mai mult, îi șantajăm pentru a renunța la ea din cauza răului pe care și-l provoacă. 

Mulți nu sunt în măsură să facă acest lucru și sunt forțați, fără să aibă vreo vină, să sufere un complex de vinovăție pentru tot restul vieții lor. Mulți reușesc și sunt mulțumiți de acest lucru, gândindu-se: *"Bine. O să fac asta deocamdată și după ce se va termina, oricum voi fi vindecat.\"* Apoi vin durerea și teama de a găsi un loc de muncă și alte lupte ale adulților, urmate de cel mai mare "high" din viața lor - găsirea unui loc de muncă. Durerea și teama au trecut, acum se simt în siguranță, vechiul mecanism de declanșare intră din nou în funcțiune. O parte din spălarea creierului fiind încă acolo și înainte ca mirosul noului laptop de lucru să dispară, utilizatorul se află în pragul haremului lor online preferat. Euforia ocaziei blochează sentimentele murdare din mintea lor, nu au nicio intenție de a deveni din nou dependenți, dar doar o singură privire nu putea face rău... Prea târziu! Sunt deja din nou dependenți.

Vechea poftă de la micul monstruleț va începe din nou și chiar dacă nu devin din nou dependenți imediat, depresia post-high îi va prinde probabil din urmă. Este ciudat că, deși dependenții de heroină sunt infractori în fața legii, răspunsul societății este de a-i ajuta pe acești indivizi. Haideți să adoptăm aceeași atitudine față de bietul utilizator de pornografie. Ei nu o fac pentru că vor, ci pentru că ei cred că trebuie să o facă. Spre deosebire de dependentul de heroină, aceștia suferă de obicei ani și ani de tortură mentală și fizică. Întotdeauna spunem că o moarte rapidă este mai bună decât una lentă, așa că nu-l invidiați pe bietul utilizator de pornografie. ***Ei merită mila ta.