# Sfaturi pentru neutilizatori

## Ajută-ți prietenii care folosesc porno să citească această carte

În primul rând, studiați conținutul acestei cărți și încercați să vă puneți în locul utilizatorului. Nu-i forțați să citească această carte spunându-le că își distrug sănătatea sau că se joacă cu focul. Ei știu acest lucru mai bine decât tine. Utilizatorii nu continuă să vizioneze pornografie pentru că le place sau pentru că vor să o facă, ei doar își spun lor înșiși și altor persoane acest lucru pentru a-și păstra respectul de sine. Ei o fac pentru că sunt dependenți de pornografie, deoarece cred că îi relaxează, le dă curaj sau încredere (plăcere sau cârjă) și pentru că simt că viața nu va fi niciodată plăcută fără "sex" - cel puțin versiunea lor. Dacă încercați să forțați un utilizator să se oprească, se va simți ca un animal prins în capcană și își va dori și mai mult haremul. Acest lucru îi poate transforma într-un utilizator secret, iar pornografia va deveni și mai prețioasă în mintea lor.

În schimb, concentrați-vă pe cealaltă parte a monedei. Duceți-i în compania foștilor utilizatori (bloguri, forumuri, YBOP, NoFap, etc., deși aveți grijă la pledoaria pentru metoda voinței). Puneți-i să le spună utilizatorilor cum au crezut și ei că sunt dependenți pe viață și cât de bună este viața ca ne-utilizator. Odată ce i-ați făcut să creadă că se pot opri, mintea lor va începe să se deschidă. Apoi, începeți să explicați iluzia creată de durerile de sevraj. Nu numai că "drogurile de dopamină" nu le dau un impuls, dar le distrug încrederea în sine și îi fac iritabil și obosit.
They should now be ready to read this book themselves, expecting to read pages upon pages of stories about unreliable arousal, fading penetrations, PIED, PE, etc. Explain that this approach is completely different and references to illness are tiny fractions of material.

Pe scurt, nu lăsați acest lucru să moară în întuneric. Spuneți-le prietenilor voștri, dar nu fiți ciudați în legătură cu asta. Dacă încerci să "câștigi" conversația sau să porți o dezbatere, nu vei reuși decât să îi îndepărtezi și să le sporești și mai mult teama.

## Ar trebui să-i spun partenerului meu semnificativ?

Ar trebui să îi spun soției, iubitei sau partenerului meu despre obiceiul meu? (Intenția fiind aceea de a vă ajuta să renunțați.) Există mai mulți factori în joc aici.

Dacă nu ați reușit deja să renunțați folosind metoda voinței și i-ați spus deja partenerului, spuneți-i despre noua dvs. abordare și permiteți-i să se informeze citind cartea. Ei vor putea să vă ajute și să vă motiveze în timpul perioadei de sevraj și reprezintă un bastion atunci când micul monstru încearcă să vă împiedice.

Dacă abia acum ați devenit conștient de existența capcanei pornografice și nu ați încercat să renunțați în trecut, folosiți mai întâi EasyPeasy pentru dumneavoastră. După cum s-a explicat anterior, aceasta ar trebui să fie o experiență plăcută. Cu toate acestea, dacă vi se pare dificil, solicitați-le asistență. Fiți deschis și vulnerabil cu partenerul dvs. și vă va consolida relația.

Cu condiția să vă bucurați de evadare și să nu vă fie dificil din cauza indeciziei, nu există prea multe motive pentru a vă anunța partenerul. Dacă nu a fost o problemă în trecut, lăsați-o balta. Cu toate acestea, fiți pregătită că partenerul dumneavoastră s-ar putea să se întrebe de ce arătați, vă simțiți și sunteți mai performantă!  

## Partenerul meu se lasă de porno

Pornografia este un distrugător pervers al relațiilor și, deși renunțarea se poate face instantaneu, vindecarea necesită timp. Mulți utilizatori, din cauza convingerilor iraționale generate de dependența lor, își descarcă furia pe parteneri și pe cei dragi. Aceste comportamente se manifestă prin gaslighting, minciună și comportamente manipulatoare. Acest lucru nu este valabil pentru toți utilizatorii, dar este din ce în ce mai frecvent în stadiile ulterioare ale bolii. În timp ce aceste comportamente se pot fi manifestat din dependența pornografică de bază, este important să vă educați cu privire la aceste comportamente și, dacă sunt recunoscute, luați în considerare consultarea unui terapeut specializat în dependențele sexuale.

Dacă partenerul dvs. se află în perioada de sevraj, presupuneți că suferă, fie că este sau nu. Nu încercați să o minimalizați spunându-le că este ușor să se oprească, că pot face asta singuri. În schimb, continuați să le spuneți cât de mândru sunteți, cât de bine arată, cât de dulce este să fii cu ei și cât de ușor sunt în general. Este deosebit de important să continuați să faceți acest lucru, deoarece, atunci când un utilizator face o încercare de a se opri, euforia încercării și laudele pe care le primește de la colegi îl pot ajuta. Cu toate acestea, ei tind să uite repede, așa că continuați să lăudați. 

Pentru că nu vorbesc despre pornografie, s-ar putea să credeți că au uitat și nu vor să le amintiți. De obicei, în cazul metodei de voință se întâmplă exact opusul, deoarece fostul utilizator tinde să nu fie obsedat de nimic altceva. Așa că nu vă fie teamă să aduceți subiectul în discuție și continuați să îi lăudați (vă vor spune dacă nu vor să li se reamintească).

Faceți tot posibilul pentru a-i scuti de presiuni în timpul perioadei de sevraj, gândindu-vă la modalități de a le face viața interesantă și plăcută. Aceasta poate fi o perioadă de încercare și pentru cei care nu sunt consumatori și care nu au avut niciodată această dependență. Dacă un membru al unui grup este iritabil, poate provoca o suferință generală în toată lumea. Așa că anticipați acest lucru dacă fostul consumator se simte iritabil, este foarte posibil să se răzbune pe dumneavoastră, dar nu vă răzbunați, în acest moment are cea mai mare nevoie de laudele și simpatia dumneavoastră. Dacă vă simțiți și dumneavoastră iritabil, ceea ce este de înțeles, încercați să nu o arătați.

Unul dintre trucurile pe care un dependent le va juca atunci când încearcă să renunțe cu ajutorul metodei voinței este să facă crize de furie, în speranța că partenerul sau prietenii îi vor spune "*Nu pot suporta să te văd suferind așa. Pentru numele lui Dumnezeu, fa-ți tabietul*". Prin urmare, utilizatorul nu trebuie să-și piardă aparențele, deoarece nu "renunță", ci a fost instruit. Dacă fostul consumator recurge la această stratagemă, în niciun caz nu-l încurajați să recidiveze. În schimb, spuneți: "*Dacă asta îți face pornografia, slavă Domnului că în curând vei fi liber. Ce minunat că ai avut curajul să renunți la ea.*".

Nu uitați, există două părți de vindecare în cadrul călătoriei de recuperare. Atunci când partenerul dvs. renunță la pornografie, este important să aveți propria rețea de sprijin, rutine de autoîngrijire și limite. Acest proces nu se întâmplă peste noapte, necesitând încredere, comunicare și responsabilitate. Jurnalul, dezvoltarea propriilor pasiuni și, cel mai important, terapia, ajută acest proces.

## Alunecarea (recidiva)

Existența acestei secțiuni ar trebui să servească drept avertisment pentru cei care părăsesc capcana. Personal, nu am recidivat niciodată, dar voi folosi experiențe din interviurile cu membrii comunității și instrumente din terapia cognitiv-comportamentală pentru a ilustra. 

În primul rând, a o numi recidivă este contraproductiv. Tot ceea ce s-a întâmplat este că ai alunecat și ai alimentat micul monstru, care, la rândul său, pornește marele monstru de spălare a creierului. Utilizatorii care alunecă (ceea ce, prin definiție, înseamnă căderea înainte) generează de obicei o întreagă gamă de credințe iraționale:

  - "*Niciodată nu voi fi liber*" - **Catastrofizare**
  - "*Ar trebui/trebuie să fac exerciții fizice, să studiez și să fiu rodnic în fiecare zi a vieții mele*" (aka - **Musterbating**)
  - "*Astăzi am făcut PMO, așa că ce rost are să citesc toate cărțile și forumurile... Scopul meu a fost să nu fac nici măcar M, dar iată-mă aici - un eșec - recidivând.*" - **Toleranță scăzută la frustrare**
  - "*Amicii mei / cititorii forumului / alții nu fac PMO timp de (n) zile, dar eu nu pot, așa că sunt un caz fără speranță. M-am simțit bine ieri, deoarece am studiat bine și am fost fructuoasă, dar astăzi nu am... Mă duc la vale.*" - **Compararea între sine și ceilalți**
  - "Nu ar trebui să am gânduri sexuale" - Ei înșiși, părinții sau societatea în ansamblul ei au instalat **credințe rigide** în legătură cu sexul. Întrebați-vă dacă autoflagelarea vă ajută să vă atingeți obiectivele și, dacă da, vă bucurați de călătorie?

Factorii care culminează cu spălarea creierului fiecărui utilizator sunt aparent infiniti. Te cunoști pe tine însuți mai bine decât oricine altcineva, dar este evident că nu reușești să urmezi instrucțiunile. Ai văzut valoarea în pornografie, dar cum?

Ceea ce este adesea trecut cu vederea este faptul că este nevoie de timp pentru a inversa spălarea creierului. Acest lucru nu o face mai dificilă, dar aproape toate industriile folosesc sexul, iar contracararea activă a spălării creierului este un proces conștient (cel puțin pentru început), așa că ar putea dura ceva timp pentru a solidifica pe deplin lecțiile conținute. Prin urmare, se recomandă mai multe lecturi (puteți sări peste capitolele la care întâmpinați dificultăți) și nu ar trebui să vă ia mult timp.

O experiență surprinzător de frecventă pentru utilizatorii religioși care părăsesc capcana este aceea de a dori ca aceasta să doară puțin, ca o formă de ispășire. Li se pare atât de ușor să renunțe, apoi se simt vinovați că se simt astfel. Dar de ce să te autosabotezi și să faci să fie greu? Micul monstruleț este foarte șiret în această privință.

Dezasociați-vă de micul monstru - a fost adăugat de industria porno cu mult timp în urmă. Imaginați-vă un bătăuș care are o criză de furie pe terenul de joacă al școlii. Ce îi spui unui bătăuș? Dacă cedezi, nu vei face decât să-i întărești. Unii dintre cei care renunță sfârșesc prin a alimenta bătăușul și astfel îi sporesc spălarea creierului, dar conceptualizarea capcanei nu s-a schimbat. Ridică-te, dă-ți seama unde ai greșit și bucură-te de libertate!

Nu tu ești îndemnul tău. Meditația mindfulness este practica de a observa gândul, iar acolo se pot găsi lecții fundamentale despre natura minții. Este foarte recomandat să meditezi în general și, de asemenea, este complet compatibilă cu practica religioasă. Nu te poți lupta cu tine însuți, nici cu micul monstru. Trebuie să te iubești necondiționat pe tine însuți și procesul.

Dar elimină eșecul din mintea ta. Iată o secțiune din "*Meditațiile unui dependent de pornografie*" de Gulliaco (cu link în secțiunea Resurse de la sfârșitul cărții): 

> Din moment ce vizionarea de filme porno nu îți oferă niciun beneficiu, este ceva care îți face doar rău și este extrem de ridicol să vrei să faci așa ceva, îl compar cu a bea înălbitor. Poftim:
>
> ** Călătoria grea de a nu bea înălbitor. **
>
> Bună! Suntem NoBleach și găzduim provocări de reboot în care participanții ("Bleachstronauts") se abțin de la consumul de înălbitor pentru o perioadă de timp. Fie că scopul tău este participarea ocazională la o provocare lunară ca un test de autocontrol, fie că consumul excesiv de înălbitor a devenit o problemă în viața ta și vrei să renunți pentru o perioadă mai lungă de timp, vei găsi aici o comunitate de susținere și o mulțime de resurse.
>
> - "*Câteodată îmi permit să beau unul sau doua pahare de înălbitor. Știu despre faptul că "o picătură" este o minciună, dar nu cred că un singur pahar va face rău. Nu se pot distruge toate orele pe care le-am petrecut fără să fac acest lucru.*"
> - "*Nu am o problemă în a nu mai bea înălbitor, dar uneori merg pe stradă și văd pe cineva care bea apă, știți, într-un pahar, și îmi imaginez că paharul are în el înălbitor. Atunci am o poftă și, după ce mă cert cu mine însumi dacă ar trebui să o fac sau nu, în cele din urmă cedez seara și beau un pahar.*"
> - "*Uite, problema mea este că uneori, când sunt singur în bucătărie, încep să văd paharele, uneori mă tentează să deschid recipientul în care țin înălbitorul, uneori îl miros și... Ei bine, ajung înapoi de unde am plecat. Sunt atât de disperată să mă opresc din asta, dar nu sunt sigură dacă voi reuși vreodată să mă pot opri.*"
> - "*Să mă opresc din băut înălbitor este imposibil, adică, am mereu o gură, știi? Cum aș putea să mă opresc dacă am mereu un gât care îmi amintește că pot înghiți înălbitor?*"
> - "*Oh, omule, mergea atât de bine, 19 zile întregi fără să o fac. Important este să înveți din eșecuri! Acum știu ce să evit să fac: să mă uit la produsele de curățenie din supermarket. Voi încerca să ajung la o lună! O să-mi resetez contorul. Urați-mi noroc!*"

> Dacă ai un impuls, calmează-te, amice! Amintește-ți ce spune hackbook-ul:
>
> "*Este greu să renunți din cauza fricii că suntem privați de plăcerea sau de sprijinul nostru. Teama că anumite situații plăcute nu vor mai fi niciodată la fel. Teama de a nu putea face față unor situații stresante. Cu alte cuvinte, este vorba de efectele spălării creierului care ne amăgește să credem că a cumpăra înălbitor și, prin extensie, a-l bea, este o necesitate pentru toate ființele umane. Chiar mai mult, este credința că există ceva inerent în înălbitorul accesibil de care avem nevoie și că, atunci când nu mai folosim, ne vom nega pe noi înșine și vom crea un gol. Fă-ți clar acest lucru în minte: Înălbitorul nu umple un gol, ci creează unul!*".
> 
> Și eu spun:
> "*Să presupunem că ești forțat să privești un pahar plin cu înălbitor timp de cinci minute. Încercați să vă amintiți una dintre acele mărci sau mirosuri care v-au plăcut atât de mult. Poate că este însoțit de un sunet, sau vă amintiți doar anumite detalii. Înălbitorul este acolo și nu poți închide ochii sau întoarce capul, pentru că acest înălbitor este în mintea ta, este o amintire înregistrată în tine.*
>
> *Simțiți vreo poftă? Simțiți ceva în limbă sau vreo schimbare în respirație? Ce sentimente aveți în legătură cu ceea ce vă amintiți? Identificați-le, înălbitorul vrea să le tulbure, să le facă confuze și să vă facă să fiți atenți doar la ceea ce vrea să vă prindă.*"
>
> Cu cele de mai sus, nu încerc să-ți resping sentimentele, cu atât mai puțin să spun ceva de genul "haha eu deștept, tu prost", ci să-ți ofer o perspectivă, astfel încât să-ți dai seama cât de ridicol de ușor este (și va fi întotdeauna) să depășești această dependență.
> Vizionarea porno nu este ca un întrerupător pornit / oprit în care spui "*oh bine, sunt în situația X, atunci mă voi uita la porno *". Fantezii! Minciuni! Cât de des vă permiteți să beți un pahar de înălbitor? Niciodată? De ce? Pentru că este un lucru oribil, de aceea! Cum ai putea scăpa de dependență dacă nu
realizezi că PMO este un lucru oribil pe care ți-l faci singur?

## Cum rămâne cu MO (masturbare, orgasm)?

Oamenii se masturbează de veacuri fără probleme. Pentru a fi clar, pornografia este problema.

Acestea fiind spuse, puteți deveni în continuare dependent de MO din aceleași motive ca și porno, cum ar fi "nevoia de a avea un orgasm", escaladarea mentală, forțarea corpului pentru a face sex și pur și simplu căutarea plăcerii hedoniste.

Este extrem de probabil ca pornografia și masturbarea să fi devenit profund împletite în mintea ta. Mulți utilizatori constată că ajung să recidiveze ca urmare a masturbării la fantezii induse de pornografie. Pe măsură ce creierul tău se reconectează, vei descoperi că această spălare a creierului se estompează în cele din urmă, dar cel mai bine este să iei o pauză de la MO pentru o vreme. De asemenea, ar trebui să căutați sexul real pentru a accelera acest proces.

Aceasta nu este o instrucțiune, dar evaluați-o: beneficiile raportate de la reținerea spermei sunt numeroase - concentrare și energie sporite, eliminarea "ceții cerebrale" și creșterea încrederii, împreună cu o mulțime de alte beneficii. Din experiența personală, există o diferență clară, iar totul se reduce la modul în care sublimați această energie sporită.

Speculând, și fără cunoștințe științifice stricte, beneficiile ar putea fi determinate de câțiva factori diferiți.

- După orgasm, creierul eliberează prolactină, care inhibă eliberarea de dopamină.

- Privarea creierului de fluxurile de dopamină permite o mai mare absorbție din simpla trăire a vieții.

- Materialul seminal este reabsorbit de fluxul sanguin după ~78 de zile și este unul dintre cei mai buni nutrienți pe care îi poate primi corpul tău.

- Sublimarea energiei sexuale în obiceiuri productive aduce cu ea un strat suplimentar de productivitate.

Este posibil să dorești să faci sex și fără orgasm, ceea ce, așa cum am menționat mai devreme, este o experiență sexuală minunată (adesea denumită Karezza). Vă puteți întări capacitatea de a face acest lucru prin practicarea exercițiilor Kegel. Din experiența personală, cel mai simplu și mai eficient mod de a viza acest mușchi este oprirea și pornirea urinei la mijlocul jetului (deși aveți grijă să nu exagerați, ceea ce poate cauza probleme de sine stătătoare). Separarea părții tantrice de cea propice sexului este unul dintre multele bonusuri ale evadării din capcana PMO (și partenerilor mei le-a plăcut la nebunie!).

## Abateri de la sfatul standard

Această secțiune este nouă și este scrisă cu o oarecare îngrijorare; chiar și așa, ea trebuie menționată.

Unele persoane care folosesc EasyPeasy constată că dorința lor de a se uita la filme porno devine atât de redusă încât nu se mai pot hotărî să aibă o ultimă sesiune. **Este în regulă**, dar nu subestimați puterea de a avea una. Navigarea conștientă și solidificarea cât de mult vă displace PMO poate fi foarte puternică. Personal, am găsit-o foarte utilă și am fost fericit să mă spăl pe mâini de ea, cu adevărat ușurat să nu mai trebuiască să o fac vreodată. Cu toate acestea, experienta dvs. poate varia.

Dacă ați fost deja liber de capcană pentru o vreme și tocmai ați eliminat spălarea creierului, nu este nevoie să hrăniți micul monstru, deoarece acesta doar v-ar cicăli. Bucură-te în schimb de libertate!

## Ajutați să puneți capăt acestui scandal
Pornografia pe internet este unul dintre pericolele unei societăți libere, care se bazează pe eforturile binevoitoare ale susținătorilor libertății personale. Cu siguranță, însăși baza civilizației - motivul pentru care specia umană a avansat atât de mult - se datorează faptului că suntem capabili să ne comunicăm cunoștințele și experiențele, nu numai unii altora, ci și generațiilor viitoare. Chiar și animalele consideră că este necesar să își protejeze urmașii de capcanele vieții.

Producătorii de filme porno nu fac acest lucru cu bună credință, crezând cu adevărat că ajută omenirea, mai ales acum, când dependența de pornografia pe internet este studiată pe scară largă. Poate că în stadiile sale inițiale oamenii credeau cu adevărat că pornografia îi educă pe oameni în ceea ce privește intimitatea, dar autoritățile știu că este un fals. Niciun site de porno nu face afirmații reale despre educație. Singurele afirmații făcute se referă la șocul, noutatea și calitățile de escaladare ale produselor lor.

Ipocrizia pură este incredibilă: ca societate, în rest, suntem crispați în legătură cu hărțuirea în școli și cu obiectificarea corpului uman. Numărul celor dependenți urcă la noi cote în fiecare an, petrecând timp de calitate cu persoane pixelate imaginare și iluzorii în detrimentul sănătății, virilității, energiei și timpului lor. Este de departe cel mai mare ucigaș în relații, iar sute de mii de vieți sunt ruinate în fiecare an din cauza dependenței. Producătorii de pornografie pe internet nu își fac reclamă în publicațiile mainstream - nu au nevoie, impulsurile noastre biologice ne conduc spre pragurile haremurilor lor bine aprovizionate, oferind mostre gratuite precum dealerul local de droguri. În zilele noastre, site-urile cu porno nu își aprovizionează atât de mult marfa, cât încurajează vizitatorii să posteze conținut. 

Cât de inteligent este faptul că firmele pornografice afișează avertismente *18+* ca mijloc de descurajare pentru utilizatorii minori, deși unele nici măcar nu se obosesc să facă acest lucru. Pornografia pe internet afectează pe toată lumea la toate vârstele. "*Te-am avertizat de pericol, așa că este alegerea ta*", este atitudinea lor. Fac vreun pas pentru a verifica vârsta? Nu, asta i-ar descuraja pe clienții lor. Desigur, dacă verificarea vârstei este legiferată, vor găsi o altă țară de unde să opereze. Sau vor plăti o "elită" care să scrie despre cum a dus prohibiția la contrabandă și la crearea Mafiei? În mod convenabil, se uită întrebarea de ce abrogarea prohibiției nu a avut ca rezultat reducerea numărului de victime legate de alcool și eșecul aplicării legii de a controla creșterea Mafiei. 

Putem aborda această problemă în mod diferit prin educarea tinerei generații. Dacă pot evita țigările și alcoolul atunci când merg la cumpărături, pot face același lucru cu pornografia pe internet. Vedem deja schimbări societale, cum ar fi "No Nut November" și meme-urile "Coomer", care au devenit mainstream. Utilizatorul nu are de ales, așa cum nu are nici dependentul de heroină. Utilizatorii nu decid să devină dependenți, ci sunt atrași într-o capcană subtilă. Dacă ar avea de ales, singurii consumatori de mâine dimineață ar fi adolescenți aflați la început de drum, crezând că se pot opri în orice moment dacă vor dori. 

De ce aceste standarde false? De ce dependenții de heroină sunt văzuți ca niște infractori, dar pot fi înregistrați ca dependenți și pot primi metadonă și tratament medical adecvat pentru a-i ajuta să renunțe la ea? Încearcă să te înregistrezi ca dependent de pornografie - dacă te duci la doctorul tău pentru ajutor, acesta îți va spune fie: "*Nu o mai face atât de mult, încearcă moderația*", ceea ce deja știi că nu va funcționa, sau va prescrie medicamente pentru a aborda "depresia" ta. Mai rău este sfatul de a merge și de a-ți găsi parteneri adevărați - serios? Nu au auzit niciodată de utilizatorii care găsesc porno mai plăcut și o fac pe la spatele partenerului lor? Unii oameni pur și simplu nu înțeleg.

Campaniile de alarmă nu îi ajută pe utilizatori să se oprească, ci le îngreunează situația. Tot ceea ce fac este să-i sperie pe utilizatori, ceea ce îi face să vrea să se uite și mai mult. De asemenea, ele nu împiedică adolescenții să devină dependenți. Adolescenții știu că pornografia le ucide libidoul, dar știu și că o singură privire nu va fi de ajuns. Deoarece dependența este atât de răspândită, mai devreme sau mai târziu, adolescentul - fie din cauza presiunilor sociale, fie din curiozitate - va încerca doar o singură vizită. Pentru că pornografia gratuită are clipuri îngrozitoare, este probabil că vor deveni dependenți.

De ce permitem ca acest scandal să continue? De ce nu ies guvernele cu campanii adecvate? De ce nu ni se spune că pornografia pe internet este un drog și o otravă ucigașă, că nu te relaxează și nu-ți dă încredere, ci îți distruge nervii, fiind suficientă o singură privire pentru a deveni dependent? De ce nu se poate impune verificarea vârstei prin solicitarea de carduri de credit înregistrate, poate cu o terță parte? MindGeek, proprietarul multora dintre cele mai importante site-uri porno, încearcă să înșele guvernele pentru a folosi propria soluție proprie de verificare a vârstei - nu-i lăsați să o facă! Cartea lui H. G. Well *Mașina timpului* descrie un incident dintr-un viitor îndepărtat în care un om cade într-un râu. Însoțitorii săi stau pur și simplu pe mal ca niște vite fără să țină cont de strigătele de disperare. Inuman și deranjant, la fel ca apatia generală a societății față de criza pornografică.

Există un vânt de schimbare a societății. Un bulgăre de zăpadă a început să se rostogolească pe deal și se speră că această carte va contribui la transformarea lui într-o avalanșă. Și tu poți ajuta, răspândind mesajul.

Ca atare, pentru a cere - dacă vedeți pe cineva care se luptă folosind voința sau încearcă să renunțe la pornografie, vă rugăm să le arătați cu amabilitate spre această metodă. Cu toate acestea, adevărata sarcină la îndemână este schimbarea narațiunii în jurul porno în general. Vă rugăm să vă gândiți să vă faceți un obicei ca, dacă vedeți online sau chiar experimentați normalizarea porno, sa educati oamenii care au cazut prada dependentei de PMO. 

Ocazional, s-ar putea să primiți o reacție negativă, dar uneori un comentariu este tot ce este necesar. Așa cum mulți au făcut-o înaintea ta, te poți aștepta să primești mesaje de la oameni recunoscători care îți mulțumesc pentru libertatea lor.

## Avertisment final

Acum vă puteți bucura de restul vieții ca un non-utilizator fericit. Pentru a vă asigura că o veți face, trebuie să urmați aceste instrucțiuni simple.

1.  Păstrați aceasta pagină în marcajele dvs. și consultați-o ori de câte ori aveți nevoie.

2.  Dacă începeți vreodată să invidiați un alt utilizator, realizați că acesta va fi invidios pe dumneavoastră. Nu sunteți privați. Ei sunt.

3.  Amintește-ți că nu ți-a plăcut să fii utilizator. De aceea te-ai oprit. Îți place să fii un non-utilizator.

4.  Amintește-ți că nu există doar o singură privire.

5.  Nu te îndoi niciodată de decizia ta de a nu te mai uita niciodată la filme porno. Știi că este cea corectă.

6.  Dacă întâmpinați dificultăți, găsiți și contactați un terapeut cu cunoștințe în domeniul pornografiei pe internet. Puteți găsi liste ale acestora online.
