# Instrucțiunile

1.  Urmați toate instrucțiunile.

2.  Păstrați o minte deschisă.

3.  Începeți cu un sentiment de euforie.

4.  Ignorați toate sfaturile și influențele care intră în conflict cu EasyPeasy.

5.  Rezistați oricărei promisiuni de rezolvare temporară.

6.  Aveți clar în minte: pornografia nu oferă nicio plăcere sau ajutor autentic și nu faceți un sacrificiu. Nu trebuie să renunțați la nimic și nu există niciun motiv să vă simțiți privați.

7.  Nu așteptați să renunțați, faceți-o acum!

8.  Luați o decizie de a nu mai privi niciodată și nu o puneți niciodată la îndoială.

9.  Amintește-ți că nu există doar o singură privire.

10. Nu vă mai uitați niciodată la filme porno.

## Afirmații

- Sunt liber de sclavia pornografiei.

- Este ușor să-mi ignor gândurile despre porno.

- Adio gânduri, adio impulsuri. Oh, acolo se duc poftele mele.

- Îmi concentrez subconștientul pentru a depăși dependența de pornografie.

- Pornografia îmi fură timpul, energia și vitalitatea.

- Învingerea porno devine exponențial mai ușoară zi de zi și în fiecare aspect.

- Mă bucur și apreciez stilul meu de viață fără porno, puternic, fericit și ușor.

- Dacă mă uit înapoi și mă gândesc la progresul meu, îmi dă o mare bucurie și mândrie în mine.

- De fiecare dată când văd alți utilizatori de porno, mă motivez și mai mult să mă văd pe mine însumi rupând acest lanț.

- Toată această energie reținută îmi vindecă corpul și mintea. Apoi, pot face o muncă mai productivă și mai provocatoare pentru valorile și obiectivele mele.

- Creierul meu își revine în forma corectă, fiind antrenat de mine *nu* făcând ceea ce făceam înainte.

- Acum, toată această voință reținută este folosită pentru a face față stresului și tensiunilor ușoare ale vieții.

- Minunat, sunt liber și nu mai sunt un sclav!
