# Sfârșitul cărții

Vă mulțumesc că ați citit; după cum știți, mă umple de o bucurie sinceră faptul că ați găsit libertatea.

Visez la o lume în care să nu fiți nevoiți să o faceți.

O lume în care ați început să puneți la îndoială pornografia înainte de a o găsi, observând efectele pe care le-ați învățat la școală.

În cazul în care cineva care își menționează starul porno preferat a fost întâmpinat cu acea vibrație de "mistep social ciudat", dar imediat urmată de o dorință sinceră de a ajuta.

Una în care toată lumea era puțin mai puțin pe muchie de cuțit; lucrând împreună cu comunitățile locale care sunt mai durabile, mai apropiate și mai grijulii.

Nu suntem atât de departe pe cât credeți.

## Unde ne aflăm acum? {-}

Existați în cazul în care pornografia a fost normalizată în cultură, mass-media și viața de zi cu zi. Fiți siguri că acest lucru nu va sta în picioare: știința este absolută, iar tot ceea ce stă în picioare cu timpul trebuie să se bazeze pe adevăr.

Sunteți martorii unei schimbări sociale împotriva ei; comunitățile online, lunile de abstinență celebrate și conversațiile împing bulgărele de zăpadă - dar cât timp doriți să așteptați?

## Cum așa? {-}

Obiectivele noastre sunt simple:

1. Până la sfârșitul anului 2023, educația pornografică ar trebui să fie obligatorie în toate programele de educație sexuală. Pur și simplu nu mai este timp de pierdut.
2. Până la sfârșitul anului 2024, pornografia este opțională și restricționată în funcție de vârstă la nivelul furnizorului de servicii, astfel încât copiii mici să o poată evita.
3. Până la sfârșitul anului 2025, EasyWay al lui Allen Carr ar trebui să fie în fruntea campaniilor de nicotină.

## Cum vă pot ajuta? {-}

În acest moment elaborez comunități online care să se coordoneze.

Puteți folosi următoarele platforme.

**[Urbit](https://urbit.org/overview) ~mogsub-possum/coomer** - puteți găsi ghiduri despre [aderarea la rețea] și [utilizarea ei] aici.

**[Discord](https://discord.com/invite/bCXEnf9)** -- care în prezent este doar o centrală de shitposting pe care nu mă deranjez să o verific, dar lucrez în fundal cu oamenii pentru a o transforma în ceva mișto.

**[Email](https://docs.google.com/forms/d/e/1FAIpQLSfi27XGmChe_qtu4fP6E6lNyjY8Ia_93TlfGbjbKgiI1VNdkg/viewform)** -- unde vă puteți înscrie pentru a primi foarte ocazional emailuri de la mine.

Deci, dacă ești orice persoană, de oriunde, cu orice abilități sau timp liber, vei putea ajuta la eliberarea altora.

Nu este încă gata, pentru că totul trebuie să fie perfect structurat, dar vă puteți alătura acum diferitelor canale și puteți discuta. 

### Dar tu? {-}

Mă numesc Fraser și sunt un student la psihologie în vârstă de 23 de ani din Australia.

Îmi place foarte mult să ajut oamenii și consider că cu cât mai mulți oameni sunt liberi de pornografie, cu atât mai bine!

Aș prefera să te întâlnesc în persoană, dar iată unde exist online.

**yt:** [Fraser Patterson](https://www.youtube.com/channel/UChMZhvS7eV-WoLDu_mRjEEw) -- Postarea de videoclipuri calme despre viața mea și mici pepite de înțelepciune

**ig:** [@deleteinstaplease](https://instagram.com/deleteinstaplease) -- Ocazional, poze din natură, sau ce fac.

**tw:** [@deletetwitpls](https://twitter.com/deletetwitpls) -- Nu postez aici.

*Vă rog să nu vă simțiți presați să mă urmăriți*, dar știi, puțină presiune pentru că îmi dă mai multă "influență" ca să pot spune la podcast-uri și alte chestii "hei, amice, te superi dacă apar și eu?".
## Putina Intelepciune {-}

Renunțarea la pornografie este partea ușoară, partea "grea" este călătoria care urmează.

Iată câteva lucruri care te-ar putea ajuta în ea.

Dacă simți că ești ** dependentă de tehnologie,** înțelege că gândurile tale se potrivesc cu viteza vieții. Încetinește-ți viața prin experimentarea naturii și postul uscat pentru 24h într-o cameră întunecată.

Acesta nu este un "leac pentru toate", dar îți oferă timp de gândire și liniște cu gândurile tale.

Apropo, **meditația mindfulness** a fost recomandată înainte.

Meditația este practica de a înțelege cum este mintea ta întotdeauna. Gândurile apar continuu și trec.

Te vei gândi la pornografie - desigur - și meditația te ajută să le recunoști ca fiind doar atât: gânduri.

Aș recomanda cu căldură să obțineți o [lună gratuită de Waking Up](
Nu sunt plătit pentru a recomanda acest lucru, este doar o aplicație foarte, foarte bună. Aș recomanda cu căldură cursul introductiv mai întâi, apoi niște Alan Watts și Texte de înțelepciune de Jayasara. Toate sunt experiențe foarte frumoase. 

Bineînțeles, **respiratia controlata** ar ajuta și mai mult.

V-aș recomanda tehnicile de respirație Bukeuko și Wim Hof.

Deocamdată, puneți o mână pe burtă și una pe piept.

Apoi, inspirați în timp ce scoateți buzele în formă de O (da... haha xd!!)

Vei simți cum ți se activează diafragma, adică modul în care respirai în mod natural când erai copil. Este mai bine pentru tine din toate punctele de vedere și necesită mai puțin efort din partea corpului tău.

Ai preluat respirația superficială pentru că toți ceilalți o fac, iar noi ne oglindim în mod natural în oameni.

Vă sună cunoscut?

Ei bine, în ceea ce privește dependențele, nu există nicio îndoială că ți-ar face plăcere să renunți...

**Alcool!**

Pe lângă faptul că generează un sevraj de 10 zile, alcoolul reușește să "stupefieze" băutorii și nu îți oferă plăcere, încredere, curaj sau relaxare.

Cartea lui Jason Vale, *Kick the Drink... Ușor!" deconstruiește alcoolul în întregime și complet. El susține că nu există un alcoolic - persoanele care "pierd controlul" (al unui vid adictiv) sunt doar stigmatizate și evitate - și că renunțarea este extrem de ușoară.

Am renunțat la alcool după PMO și am constatat că viața și ocaziile sociale sunt cu adevărat mult mai plăcute fără el.

Un drog pentru a te amorți și a te otrăvi este foarte "boomer", nu crezi?

Dar poate că toată lumea este pur și simplu victimă a...

**Consumului.**

Așadar, iată un citat despre asta.

>

...

>*Nu mă bucur adesea și nici nu găsesc prea mult folos în deconstrucția excesivă, dar actul de divertisment contemporan imploră un astfel de proces pentru a-l târî în instanță. Pentru că asta uită cei mai mulți oameni când se uită la televizor sau când dau scroll pe telefon, este un act, desfășoară o acțiune, oricât de banală și de plictisitoare ar fi ea. Orice acțiune efectuată în mod constant devine în cele din urmă un obicei, cel puțin într-un anumit sens, fie că vă place sau nu. Și, la bază, acțiunea pe care o efectuați atunci când sunteți absorbit de divertismentul contemporan este apatia. Așa este, omul a găsit o modalitate nu doar de a fi activ apatent, ci și de a cultiva acest comportament în așa fel încât să devină o virtute - "Frate, mi-am petrecut tot weekendul uitându-mă la Netflix!" Haideți să o luăm de la capăt, să ne uităm la modul în care omul decide să își petreacă viața care i-a fost dată-*
>
>*Este un bărbat sau o femeie, așezat pe o canapea. Corpul lor este într-o poziție ciudată și nefirească, tot împăturit și rotund, nu are rost să ia mai multă greutate decât oricare altul, sunt o grămadă mare de mâzgă. Vor rămâne aici, pur și simplu așezați, în același spațiu de 1,5 metri pe 1,5 metri, ore întregi - apropo, lumea este mult mai mare decât atât - își vor mișca brațul, poate se vor repoziționa, dar cam atât în ceea ce privește folosirea corpului lor. În ceea ce privește mintea lor, aceasta funcționează literalmente la cel mai scăzut nivel. Spre deosebire de lectură, învățare, meditație, practică sau concentrare, actele contemporane de divertisment nu cer nimic de la spectator, în afară de un singur lucru, să privească într-o anumită direcție. Acestea sunt mijloace ale apatiei. Cineva ar putea, dacă și-ar dori, să fie amorțit peste tot, cu excepția ochilor, și tot ar întreprinde actul de "divertisment", atât de patetic este acest act. Nu am nimic împotriva a ceea ce se difuzează la televizor, nici împotriva mijloacelor de comunicare vizuală, ci împotriva mijloacelor de comunicare care sunt un mijloc pentru atingerea unui scop. Oamenilor nu le mai plac emisiunile TV sau filmele specifice, ci Netflix sau vizionarea televiziunii în ansamblu. Distracția lor preferată este să fie apatici față de tot ceea ce pot fi. Este din nou o întrebare dacă ți-ai dorit vreodată acest lucru de la bun început sau dacă altcineva a decis că aceasta este dorința normală de a avea?*.

--- Meta Nomad, [Exiting Modernity](https://jdemeta.net/2019/09/15/exiting-modernity/) // ([pdf](https://jdemeta.net/wp-content/uploads/2019/09/Exiting-Modernity.pdf))

Petrecerea mai puțin timp în fața ecranelor (alături de o anumită învățare a ochilor) îmbunătățește, de asemenea,...

** miopia.**

Cele mai multe cazuri de miopie (nu poți vedea la distanță) sunt perfect vindecabile.

Pe scurt, prea multă vedere de aproape slăbește un mușchi al ochiului. Punerea ochelarilor în față îl slăbește și mai mult, iar acum ai nevoie de ochelari mai puternici. Puteți reeduca acest mușchi.

Consultați,

- [EndMyopia](https://endmyopia.org)
- [Myopia is Mental](https://www.myopiaismental.com/)
- [Visions of Joy](https://visionsofjoy.org)

De asemenea, nu trebuie să cheltuiți bani pentru a vindeca...

**Căderea parului.**

Deoarece puteți vindeca multe cazuri folosind un simplu masaj al scalpului.

Ei bine, după spusele unui amic de-al meu care găsește adesea lucruri care "sună ca niște tâmpenii, dar sunt de fapt adevărate".

El recomandă <https://perfecthairhealth.com>, dar și...

**Detoxifiere cu mercur.**

Despre care a spus că a funcționat pentru el. 

Pe scurt, mercurul se găsește în mediul înconjurător (uneori), în plombele de amalgam și chiar în uterul mamei, iar acesta este un metal foarte greu (și toxic) de care organismul tău nu poate scăpa.

Poți, totuși, să treci printr-un proces de descris în "The Mercury Detoxification Handbook" pentru a scăpa de el.

El spune că nu toată lumea este afectată, dar este bine de luat în considerare: mai ales dacă ai probleme de sănătate ciudate.

Oricum, în ceea ce privește **relațiile intime**, v-aș recomanda trei cărți:

- *Modele: Atrage femeile prin onestitate* de Mark Manson pentru a înțelege vulnerabilitatea emoțională și a elimina nevoia de a avea nevoie de ele.
- *The Rational Male* de Rollo Tomassi, utilă pentru evitarea relațiilor toxice.
- *The Way of The Superior Man* de David Dieda, care oferă o înțelegere mai spiritală a energiilor masculine, feminine și echilibrate. Destul de "new-agey", dar este corect.

și, de asemenea, să vă trimit o sinceră felicitare. Tocmai v-ați eliberat de o boală teribilă. Privește lumea cu ochi noi și cu un sens reînnoit și bucură-te întotdeauna de călătorie.

Bun venit în restul vieții tale.

Vă doresc mult succes în viață,

[Fraser Patterson](https://fraserpatterson.au)

