# 쉬운 방법

이 책의 목적은 당신을 새로운 마음가짐으로 인도하는 것입니다. 에베레스트 산을 오르는 기분으로 시작해서 그 다음 몇 주를 갈망하고 박탈감을 느끼는 일반적인 중단 방법과는 대조적으로, 끔찍한 질병에서 치유된 것처럼 기쁨의 기분으로 바로 시작합니다. 그때부터 인생을 더 살아갈수록 이 기간을 돌아보며 처음에 어떻게 포르노를 사용했을까 궁금해할 것입니다. 부러움이 아닌 연민으로 다른 포르노 사용자를 바라볼 것입니다.

중독된 적이 없는 사람(상대방을 위해 책을 읽는 사람)이거나 끊은 사람(또는 "포르노 다이어트"의 금식 기간 중이 아닌 사람)이 아니라면 책을 다 읽을 때까지 계속 사용하는 것이 필수적입니다. 이것은 모순처럼 보일 수 있으며 포르노를 계속 자위하라는 이 지시는 다른 어떤 것보다 더 많은 반대를 불러일으키지만 더 읽을수록 포르노를 사용하고 싶은 욕구가 점차 줄어들 것입니다. **이 지침을 진지하게 받아들이세요: 일찍 끊으려고 시도하는 것은 당신에게 도움이 되지 않습니다.**

많은 사람들이 무언가를 포기해야 한다고 느껴서 책을 다 읽지 않고, 어떤 사람들은 심지어 사악한 사건을 미루기 위해 하루에 한 줄만 의도적으로 읽기도 합니다. 이렇게 생각해 보세요. 잃을 것이 뭐가 있나요? 책을 다 읽고 멈추지 않는다고 해서 지금보다 더 나쁘지는 않습니다. 정의상 파스칼의 내기입니다. 잃을 것이 없고 큰 이익을 얻을 가능성이 높은 내기를 하는 것입니다.

그런데 며칠이나 몇 주 동안 포르노를 보지 않았지만 포르노 사용자인지, 전 사용자인지, 아니면 비사용자인지 확신할 수 없다면, 책을 읽는 동안 포르노를 사용해서 자위하지 마세요. 사실, 당신은 이미 비사용자이지만, 우리는 당신의 뇌가 당신의 몸을 따라잡도록 해야 합니다. 책을 다 읽을 때쯤이면 당신은 행복한 비사용자가 될 것입니다. EasyPeasy는 포르노의 상당한 단점을 나열하고 이렇게 말하는 일반적인 방법과는 정반대입니다.
*"포르노 없이 충분히 오래 버틸 수만 있다면 결국 그 욕망은 사라지고 노예 상태에서 벗어나 삶을 다시 즐길 수 있을 것입니다."*
이것은 매일 수천 명이 이 방법을 사용하여 중단하는 논리적인 방법입니다. 그러나 다음과 같은 이유로 성공하기는 매우 어렵습니다.

**PMO 중단이 진짜 문제는 아닙니다.**
세션을 마칠 때마다 사용을 중단하게 됩니다. 4분의 1 포르노 다이어트 첫날에 *"포르노를 사용하고 싶지 않고, 더 이상 자위하고 싶지도 않습니다."*라고 말할 강력한 이유가 있을 수 있습니다. 모든 사용자가 그렇게 하며, 그들의 이유는 여러분이 상상할 수 있는 것보다 더 강력합니다. 진짜 문제는 2일차, 10일차 또는 10,000일차입니다. 약한 순간에 '한 번만 엿보기'를 하고, 또 한 번 엿보고 싶어하고, 갑자기 다시 중독자가 되는 것입니다.

**건강 위험에 대한 인식은 더 큰 두려움을 불러일으켜 중단하기 어렵게 만듭니다.**
사용자에게 그것이 그들의 활력을 파괴한다고 말하면, 그들이 하는 첫 번째 일은 도파민을 급증시키는 무언가, 즉 담배, 술, 또는 포르노를 검색하기 위해 브라우저를 시작하는 것입니다.

**모든 중단 이유는 실제로 중단을 더 어렵게 만듭니다.**
이는 두 가지 이유 때문입니다. 첫째, 우리는 계속해서 우리의 '작은 친구'나 어떤 소품, 악습, 또는 쾌락(사용자가 그것을 어떻게 인식하든)을 포기하도록 강요받고 있습니다. 둘째, 그들은 "맹목"을 만듭니다. 우리는 중단해야 할 이유로 자위행위를 하지 않습니다. 진짜 질문은, 왜 우리는 그것을 원하거나 필요로 하는가입니다.

EasyPeasy를 사용하면 (처음에는) 중단하고 싶은 이유를 잊고 포르노 문제에 직면하여 다음과 같은 질문을 스스로에게 던집니다.

1. 포르노는 나에게 무엇을 하는가?

2. 나는 그것을 실제로 즐기고 있는가?

3. 나는 정말로 내 마음과 몸을 파괴하면서 인생을 살아야 하는가?

아름다운 진실은 *모든 포르노*가 당신에게 전혀 도움이 되지 않는다는 것입니다. 제가 분명히 말씀드리자면, 사용자로서의 단점이 장점보다 크다는 것이 아니라 포르노를 보는 데는 ***전혀***의 장점이 없다는 것입니다.

대부분 사용자는 포르노를 사용하는 이유를 합리화할 필요가 있다고 생각하지만, 그들이 내놓는 이유는 모두 오류와 환상입니다.

먼저, 우리는 이러한 오류와 환상을 제거할 것입니다. 사실, 당신은 곧 포기할 것이 없다는 것을 깨닫게 될 것입니다. 그뿐만 아니라, PMO가 아닌 사람이 되는 데에는 놀랍고 긍정적인 이득이 있으며, 웰빙과 행복은 이러한 이득 중 두 가지에 불과합니다. 포르노 없이는 삶이 결코 즐겁지 않을 것이라는 환상이 사라지고, 포르노 없이도 삶이 똑같이 즐겁고 무한히 더 즐겁다는 것을 깨닫고, 박탈감이나 놓침의 감정이 근절되면, 우리는 웰빙과 행복의 증가를 재고하게 될 것입니다. 그리고 포르노를 끊는 수십 가지 다른 이유도 재고하게 될 것입니다. 이러한 깨달음은 여러분이 정말로 원하는 것, 즉 포르노 중독의 노예에서 벗어나 삶을 즐기는 것을 이루는 데 도움이 되는 긍정적인 도움이 될 것입니다!