# 시간 절약

일반적으로 사용자가 중단을 시도할 때, 주된 이유는 건강, 종교, 파트너 낙인입니다. 이 끔찍한 약물에 대한 세뇌의 일부는 순전히 노예제입니다. 인간은 세계 여러 지역에서 노예제를 폐지하기 위해 열심히 노력했지만, 사용자는 스스로 부과한 노예제에 시달리며 삶을 보냅니다. 그들은 포르노를 사용할 수 있게 되면 자신이 사용하지 않는 사람이기를 바란다는 사실을 모릅니다. 포르노가 소중해지는 유일한 때는 우리가 줄이거나 금욕하려고 '노력'할 때나 금욕이 강요될 때입니다.

세뇌로 인해 포르노를 중단하기 어렵다는 것은 아무리 반복해도 지나치지 않습니다. 따라서 시작하기 전에 더 많이 없앨수록 목표를 달성하기가 더 쉬워집니다. 포르노가 건강에 부정적인 영향을 미치지 않는다고 믿고(포르노로 인한 발기 부전, 최면성 등) 정신적으로 힘겨워하지 않는 확진 사용자는 일반적으로 젊거나 가끔 섹스 파트너가 있는 독신입니다. 따라서 내부 피드백은 젊음의 특성으로 인해 손실되거나 관찰 및 등록하기에는 너무 드뭅니다.

젊은 사용자에게 더 나은 주장은 "*당신이 소비하는 시간에 대해 걱정하지 않는다고 믿을 수 없어요.*"라고 말하는 것보다 소비하는 시간입니다. 일반적으로 건강상의 이유나 사회적 낙인으로 인해 공격을 받으면 불이익을 당했다고 느끼며 눈이 밝아지지만 제때...
"*아, 저는 감당할 수 있어요. 일주일에 *x*시간밖에 안 되고 그만한 가치가 있다고 생각해요. 제 유일한 즐거움이에요.*"

"*아직도 걱정하지 않는다고 믿을 수 없어요. 도파민 금단으로 인한 신체적 소모를 포함한 하루 평균 30분을 가정해 봅시다. 2주마다 약 하루 종일 근무하는 셈이죠. 하루에 30분이 매우 보수적인 추정치라는 데 동의하실 겁니다. 평생 얼마나 많은 시간을 보낼지 생각해 보셨나요? 그 시간 동안 무엇을 하고 계신가요? 진짜 관계를 발전시키고 계신가요? 아니요, 좋아하는 포르노 스타가 당신에게 동정심을 갖는 것은 아닙니다. 당신이 그들의 비디오에 너무 많은 시간을 보냈다고 해서 시간을 낭비하는 것이 아닙니다! 그뿐만 아니라, 실제로 그 시간을 이용해 신체 건강을 망치고, 신경과 자신감을 파괴하여 평생 노예, 고통, 우울, 짜증을 겪습니다. 분명 걱정되시겠죠?*"

이 시점에서 특히 젊은 사용자의 경우, 그들은 평생 중독이라고 생각한 적이 없다는 것이 분명합니다. 가끔씩 일주일에 낭비하는 시간을 계산하는데, 그것만으로도 충분히 놀랍습니다. 아주 가끔, 그리고 중단하는 것을 생각할 때만, 일년에 얼마를 지출하는지 추정하는데, 무섭지만 평생은 생각할 수 없습니다. 그러나 우리가 논쟁 중이기 때문에 확인된 사용자는 충동적으로 *"저는 감당할 수 있어요. 일주일에 그렇게 많은 시간만 있으면 돼요"*라고 말하며 백과사전 판매원처럼 행동합니다.

현재 연봉을 지급하고 매년 한 달간 휴가를 주는 직장 제안을 거부하시겠습니까? 모든 사용자는 눈 깜짝할 새에 가입하고 이국적인 장소로 휴가 상품을 찾는 데 바쁠 것입니다. 일 없이 한 달을 보내는 방법을 알아내는 것이 가장 큰 문제일 것입니다. 확인된 사용자와 논의할 때마다(그리고 여러분처럼 그만두려고 계획하는 사람이 아니라는 점을 명심하세요) 아무도 그 제안을 수락하지 않았습니다. 왜 안 될까요?

이 시점에서 확인된 사용자는 종종 "*저는 돈에 대해 실제로 걱정하지 않습니다.*"라고 말할 것입니다. 그런 식으로 생각한다면 왜 걱정하지 않는지 자문해 보세요. 왜 삶의 다른 측면에서는 여기저기서 몇 달러를 절약하기 위해 많은 노력을 기울이지만, 행복을 죽이고 비용을 희생하는 수천 달러를 지출할까요?

인생에서 내리는 다른 모든 결정은 합리적인 결정에 도달하기 위해 장단점을 따져보는 분석 과정의 결과입니다. 잘못된 결정일 수도 있지만 합리적인 추론의 결과일 것입니다. 어떤 사용자가 인터넷 포르노 사용의 장단점을 따져볼 때마다, 답은 열두 번 이상, **"사용 중단! 넌 멍청이야!"**입니다. 따라서 모든 사용자는 원하거나 결정해서가 아니라, 중단할 수 없어서 사용합니다. 그들은 포르노를 ***사용해야*** 하기 때문에, 모래 속에 머리를 파묻고 스스로를 세뇌합니다.

확인된 사용자는 더 많은 연구가 나오고 더 많은 사람들이 인터넷 포르노의 해로운 영향에 대해 이야기함에 따라 상황이 기하급수적으로 악화될 것이라는 점을 명심해야 합니다. 오늘은 비의학적 사람들이 그 영향에 대해 논의하지만, 내일은 의사가 진단 검사 목록에 올릴 것입니다. 사용자가 성생활에서 직장 스트레스 뒤에 '휴식 시간'을 숨길 수 있는 시대는 사라졌습니다. 파트너는 왜 늦은 밤에 노트북을 하고 있는지 물을 것입니다. 이미 비참함을 느끼는 불쌍한 사용자는 이제 땅이 열리고 자신을 삼키기를 원합니다.

이상한 점은 많은 사람들이 근육을 키우고 조각처럼 보이기 위해 헬스장 멤버십과 개인 트레이너에게 많은 돈을 지불할 의향이 있지만(그리고 그들 중 많은 사람들이 상상 속(그리고 실제) 절박함 속에서 의심스럽고 위험한 부작용이 있는 테스토스테론 증가와 같은 치료법에 의지하지만), 이 그룹에는 뇌의 자연스러운 이완 시스템을 체계적으로 파괴하는 관행을 중단하면 도움이 될 사람들이 많다는 것입니다.

이는 그들이 여전히 사용자의 세뇌된 마음으로 생각하고 있기 때문입니다. 잠시 눈에서 모래를 닦아내세요. 인터넷 포르노는 연쇄 반응이며 평생의 사슬이며, 그 사슬을 끊지 않으면 평생 사용자로 남게 됩니다. 남은 인생 동안 포르노에 얼마나 많은 시간을 보낼지 추산해 보세요. 물론 사람마다 다르겠지만, 1년 반의 근무 시간이라고 가정해 봅시다. 내일 카펫 위에 급여의 1년 반 분을 복권에서 받은 수표가 놓여 있다면 어떨까요? 당신은 기쁨에 춤을 추고 있을 테니, 춤을 추기 시작하세요! 당신은 그 혜택을 받기 시작할 것입니다!

만약 당신이 이것을 보기 어려운 방식이라고 생각한다면, 당신은 여전히 ​​자신을 속이고 있는 것입니다. 당신이 처음부터 첫 엿보기를 하지 않았다면 얼마나 많은 시간을 절약했을지 계산해 보세요.

곧 당신은 마지막 세션을 사용하기로 결정할 것입니다(아직은 아니에요, 지침을 기억하세요!), 다시 함정에 빠지지 않음으로써 비사용자로 남을 것입니다. 비사용자로 남으려면 포르노를 사용하지 않고 '한 번 엿보기'를 피하는 것뿐입니다. 그렇게 하면 예상했던 급여 상승이 무엇이든 손해를 볼 것입니다.

누군가의 포르노 중독에 대해 멘토링을 하고 있다면, 현재 연봉을 지불하고 한 달치의 유급 휴가를 제공하는 직장 ​​제안을 거부한 사람을 알고 있다고 말하세요. 그 바보가 누구냐고 물으면, ***"당신!"***이라고 말하세요. 무례하지만, 때로는 예의 바르지 못한 방식으로 요점을 전달해야 합니다.
