# 의지력 방법

사회에서 포르노를 끊는 것이 매우 어렵다는 것은 널리 알려진 사실입니다. 끊는 방법에 대한 조언을 제공하는 책과 포럼은 보통 그것이 얼마나 어려운지 말하면서 시작합니다. 사실은 엄청나게 쉽습니다. 그 진술에 의문을 제기하는 것은 이해할 수 있지만, 먼저 생각해보세요. 만약 당신의 목표가 4분 안에 1마일을 달리는 것이라면, *그것은* 어렵고 당신은 수년간의 힘든 훈련을 거쳐야 하며, 심지어 그때조차도 신체적으로 무능해질 수도 있습니다.

그러나 포르노를 끊기 위해 해야 할 일은 포르노를 보지 않거나 더 이상 자위행위를 하지 않는 것입니다. 아무도 당신에게 자위행위를 강요하지 않으며(자신을 제외하고는) 음식이나 물과 달리 생존에 필요하지 않습니다. 그러니 만약 당신이 그것을 멈추고 싶다면, 왜 어려울까요? 사실, 그렇지 않습니다. 의지력을 사용하거나 사용자에게 어떤 종류의 희생을 하는 것처럼 느끼게 하는 방법을 사용하여 스스로를 어렵게 만드는 것은 사용자입니다. 이러한 방법을 고려해 보겠습니다.

우리는 사용자가 되기로 결정하지 않고, 포르노 잡지나 웹사이트를 실험할 뿐이며, 그것들이 끔찍하기 때문에(맞아요, 끔찍하죠) 원하는 클립을 제외하고는 언제든지 멈출 수 있다고 확신합니다. 처음에는 원할 때와 특별한 경우에 처음 몇 개의 클립을 봅니다. 깨닫기도 전에 우리는 그 사이트를 정기적으로 방문하고 원할 때 자위행위를 할 뿐만 아니라 매일 그 사이트에서 자위행위를 합니다. 포르노는 우리 삶의 일부가 되어 어디를 가든 인터넷 연결이 필요합니다. 그러면 우리는 사랑, 섹스, 오르가즘, 그리고 포르노의 스트레스 해소 효과를 누릴 자격이 있다고 믿습니다. 같은 클립과 배우가 우리에게 같은 정도의 각성을 제공하지 않는다는 사실을 깨닫지 못하고 '나쁜 포르노'를 피하기 위해 한계에 맞서 싸우기 시작합니다. 사실, 자위행위와 인터넷 포르노는 우리의 성생활을 개선하거나 스트레스를 줄이는 데 도움이 되지 않습니다. 그저 사용자들이 그것 없이는 삶을 즐기거나 스트레스를 처리할 수 없다고 믿을 뿐입니다.

사용자가 포르노를 보는 것은 ***필요하기 때문***이 아니라, 포르노를 좋아해서 보는 것이라는 착각에 시달리기 때문에 중독되었다는 것을 깨닫는 데는 보통 오랜 시간이 걸립니다. 포르노를 '즐기지' 않을 때, 참신함, 충격 또는 에스컬레이션이 추가되지 않는 한 절대 즐길 수 없는 일인데, 우리는 언제든지 멈출 수 있다는 착각에 빠져 있습니다. 이것이 자신감의 함정입니다. “*저는 포르노를 즐기지 않아서 원할 때 멈출 수 있어요*". 하지만 당신은 절대 멈추고 싶어하지 않는 것 같아요.

보통 우리가 실제로 멈추려고 시도할 때까지는 문제가 있다는 걸 깨닫지 못합니다. 첫 번째 시도는 일반적으로 일찍 일어납니다. 파트너를 만나서 첫 데이트 후에 그들이 '충분하지 않다'는 것을 알아차리는 것입니다. 또 다른 일반적인 이유는 일상 생활에서 나타나는 건강 문제를 알아차리는 것입니다.

이유와 상관없이 사용자는 건강이든 섹스든 스트레스가 많은 상황을 항상 기다립니다. 멈추자마자 작은 괴물은 배고픔을 느끼기 시작합니다. 그러면 사용자는 담배, 술 또는 좋아하는 인터넷 포르노와 같이 도파민을 펌핑할 무언가를 원합니다. 클릭 한 번으로 하렘과 함께 할 수 있습니다. 포르노 캐시는 더 이상 지하에 있지 않고 가상이며 어디에서나 액세스할 수 있습니다. 파트너가 주변에 있거나 친구와 함께 있으면 더 이상 가상 하렘에 액세스할 수 없으므로 더욱 괴로워합니다.

사용자가 과학 자료나 온라인 커뮤니티를 접했다면 마음속에서 줄다리기를 하며 유혹에 저항하고 박탈감을 느낀다. 스트레스를 해소하는 평소의 방법은 이제 사용할 수 없게 되어 세 배의 타격을 입는다. 이 고문 기간 후에 나올 수 있는 결과는 타협이다. "*줄여버릴게*" 또는 "*잘못된 시기를 골랐어*" 또는 아마도 "*스트레스가 내 삶에서 사라질 때까지 기다릴게*" 그러나 스트레스가 사라지면 멈출 이유가 없고 사용자는 다음 스트레스가 많은 시간이 될 때까지 다시 그만두기로 결정하지 않는다.

물론, 대부분의 사람들의 삶이 더 스트레스가 많아지기 때문에 적절한 시기는 없습니다. 우리는 부모의 보호를 떠나 집을 마련하고, 모기지를 지고, 아이를 낳고, 더 책임감 있는 직업을 갖는 세상에 들어갑니다. 그럼에도 불구하고 사용자의 삶은 포르노가 실제로 스트레스를 유발하기 때문에 덜 스트레스가 될 수 없습니다. 사용자가 에스컬레이션 단계로 더 빨리 넘어갈수록 더 괴로워지고 의존의 환상이 커집니다.

사실, 삶이 더 스트레스가 많아지고 포르노나 비슷한 버팀목이 그 환상을 만들어낸다는 것은 환상입니다. 이에 대해서는 나중에 더 자세히 설명하겠지만, 이러한 초기 실패 이후에 사용자는 보통 어느 날 깨어나서 자위행위나 포르노를 사용하고 싶지 않을 가능성에 의지합니다. 이러한 희망은 일반적으로 다른 전 사용자로부터 들은 이야기에 의해 불붙습니다. "*나는 침투가 희미해지기 전까지는 진지하지 않았고, 그 후 포르노를 더 이상 사용하고 싶지 않았고 자위 행위를 멈췄습니다.*"

자신을 속이지 말고, 이러한 소문을 조사하면 보이는 것처럼 결코 간단하지 않다는 것을 알게 될 것입니다. 일반적으로 사용자는 이미 중단할 준비를 했고 그 사건을 발판으로 삼았습니다. "그냥 그렇게" 중단한 사람들의 경우 더 자주 충격을 받았습니다. 아마도 파트너가 발견했거나, 정상적인 성적 지향이 아닌 포르노에 접근하는 자기 발견 사건이 있었거나, 스스로 성적 기능 장애에 대한 두려움을 겪었을 수 있습니다. "*그저 제가 그런 사람입니다.*" 자신을 속이지 마세요. 당신이 그것을 이루지 않는 한 일어나지 않을 것입니다.

의지력 방법이 왜 그렇게 어려운지 더 자세히 생각해 보겠습니다. 우리 삶의 대부분은 모래 속에 머리를 처박은 "*내일은 그만둘게*"라는 접근 방식을 채택합니다. 이상한 때에 무언가가 중단하려는 시도를 촉발합니다. 건강, 활력 또는 자기 분석에 대한 우려일 수 있으며, 실제로 즐기지 못한다는 것을 깨닫는 것일 수 있습니다. 이유가 무엇이든, 우리는 포르노의 장단점을 따져보기 시작합니다. 섹스는 탄트라(촉각, 후각, 음성)와 전파(오르가즘)로 나뉩니다. 이것은 우리의 마음을 여는 주요 열쇠 중 하나이며, 이 중요한 구별이 없다면 혼란이 생겨 실패로 이어질 것입니다. 합리적으로 평가하면 우리는 평생 알고 있던 것을 알게 되고, 결론은 "***그만 봐!***"보다 천 배는 더 큽니다.

앉아서 중단의 장점에 점수를 매기고 포르노의 장점과 비교한다면, 중단에 대한 총 점수는 '단점'보다 훨씬 더 많을 것입니다. 파스칼의 내기를 사용하면 중단함으로써 거의 아무것도 잃지 않고, 이득을 얻을 가능성이 높고 *잃지 않을* 가능성이 더 높습니다. 사용자는 비사용자가 더 나을 것이라는 것을 알고 있지만, 희생을 한다는 믿음이 그들을 넘어뜨립니다. 환상이기는 하지만 강력합니다. 그들은 이유를 모르지만, 사용자는 삶의 좋은 때와 나쁜 때 모두 세션이 도움이 되는 것처럼 보인다고 믿습니다. 시도를 시작하기도 전에, 자신의 중독에 대한 세뇌로 더욱 강화된 사회적 세뇌는 '포기'가 얼마나 어려운지에 대한 훨씬 더 강력한 세뇌와 결합됩니다.

사용자들은 몇 달 동안 중단했지만 여전히 간절히 그것을 갈구하는 사람들, 또는 중단한 후 남은 인생을 세션을 원한다는 사실을 한탄하며 보내는 불만스러운 포기자들의 이야기를 듣습니다. 몇 달 또는 몇 년 동안 중단하고 행복한 삶을 살다가 포르노를 '한 번' '엿보기'만 하고 갑자기 다시 중독되는 사용자들의 이야기도 있습니다. 사용자들은 아마도 질병의 진행 단계에 있는 몇몇 사람들을 알고 있을 것입니다. 그들은 스스로를 눈에 띄게 파괴하고 삶을 즐기지 못하지만 계속 사용합니다. 게다가 그들은 아마도 그러한 경험 중 하나 이상을 겪었을 것입니다.

따라서 "*좋아요! 뉴스 들었어요?"라는 느낌으로 시작하는 대신 더 이상 포르노를 볼 필요가 없어!*"라고 말하는 대신, 그들은 마치 에베레스트 산을 오르려고 하는 것처럼 암울하고 우울한 기분으로 시작하고, 작은 괴물이 당신을 낚아채면 평생 중독된다고 잘못 판단합니다. 많은 사용자는 여자친구나 아내에게 사과하면서 "*포르노를 끊으려고 노력하고 있어요. 앞으로 몇 주 동안은 짜증이 날 거예요. 참아주세요.*"라고 말하면서 시도를 시작합니다. 대부분의 시도는 시작하기도 전에 실패합니다.

사용자가 세션 없이 며칠을 버틴다고 가정해 보겠습니다. 그들은 각성을 되찾고 회복을 시작하고 있습니다. 그들은 좋아하는 튜브 사이트를 열지 않았고 그 결과 이전에는 집중하지 못했던 정상적인 자극에 각성됩니다. 처음에 중단하기로 결정한 이유는 운전 중에 심각한 교통사고를 보는 것처럼 생각에서 빠르게 사라집니다. 잠시는 속도가 느려지겠지만, 다음에 약속에 늦을 때는 스로틀을 밟을 겁니다.

전쟁의 반대편에는 아직 고칠 수 없는 작은 괴물이 있습니다. 육체적 고통은 없습니다. 감기에 걸려서 같은 기분이 든다면 일을 멈추거나 우울해지지 않고, 웃어넘길 것입니다. 사용자가 아는 전부는 하렘을 방문하고 싶다는 것입니다. 작은 괴물은 이를 알고 큰 세뇌 괴물을 가동시켜 몇 시간 또는 며칠 전에 중단할 이유를 모두 나열했던 사람이 이제는 필사적으로 다시 시작할 변명을 찾게 합니다. 그들은 다음과 같은 말을 하기 시작합니다.

-   “*인생은 너무 짧아, 폭탄이 터질 수도 있고, 내일 버스 밑으로 발을 디딜 수도 있어. 너무 늦었어. 요즘은 모든 게 중독을 불러온다고 하잖아.*"

-   “*제가 잘못된 시간을 골랐네요.*”

-   “*크리스마스 이후, 휴가/시험 이후, 인생의 스트레스가 많은 이 사건이 지난 후까지 기다려야 했어요.*"

-   “*집중도 안 되고, 짜증도 나고, 성격도 나빠지고, 직장도 제대로 못 다니고 있어요.*"

-   “*제 가족과 친구들은 저를 사랑하지 않을 겁니다. 솔직히 말해서, 모든 사람을 위해 다시 시작해야 합니다. 저는 확실한 섹스 중독자이고 오르가즘 없이는 결코 행복할 수 없습니다.*"

-   “*아무도 섹스 없이는 살아남을 수 없습니다.*" (섹스의 탄트라와 전파적 부분의 구분을 고려하지 않는 선의의 사람들에게 세뇌당함).

-   “*저는 이런 일이 일어날 거라는 걸 알았습니다. 제 뇌는 과거의 과도한 포르노 사용으로 인해 도파민 급증으로 인해 변화한 델타포스비에 '민감해졌습니다. 민감성은 '결코' 뇌에서 제거될 수 없습니다.*"

이 단계에서 사용자는 보통 포기합니다. 브라우저를 실행하면 정신분열증이 증가합니다. 한편으로는 작은 괴물이 마침내 고침을 받으면서 갈망을 끝내는 엄청난 안도감이 있습니다. 다른 한편으로는 오르가즘이 끔찍하고 사용자는 왜 그렇게 하는지 이해할 수 없습니다. 이것이 사용자가 의지력이 부족하다고 생각하는 이유입니다. 사실 의지력이 부족한 것이 아니라, 그들이 한 일은 마음을 바꾸고 최신 정보에 비추어 완벽하게 합리적인 결정을 내린 것뿐입니다.

"*비참하다면 건강하거나 부유해지는 의미가 뭐예요?*"

절대 없습니다! 길고 비참한 삶보다 짧은 즐거운 삶을 사는 것이 훨씬 낫습니다. 다행히도 이것은 사용자가 아닌 사람에게는 사실이 아닙니다. 왜냐하면 삶은 무한히 더 즐겁기 때문입니다. 사용자가 겪는 비참함은 금단 증상 때문이 아닙니다. 처음에는 금단 증상으로 인해 발생하지만 실제로 고통스러운 것은 의심과 불확실성으로 인해 마음 속에서 줄다리기를 하는 것입니다. 사용자는 희생을 한다는 느낌으로 시작하기 때문에 박탈감을 느끼기 시작하는데, 이는 스트레스의 한 형태입니다.

이러한 스트레스가 많은 시간 중 하나는 뇌가 그들에게 '엿보기'를 말하면서 멈추자마자 뒤로 돌아가고 싶어할 때입니다. 하지만 이미 멈췄기 때문에 그럴 수 없고, 이는 그들을 더욱 우울하게 만들고 다시 방아쇠를 당깁니다. 그만두기를 어렵게 만드는 또 다른 요인은 무언가가 일어날 때까지 기다리는 것입니다. 운전 면허 시험에 합격하는 것이 목표라면 시험에 합격하자마자 목표를 달성했는지 여부가 확실합니다. 의지력 방법에서 내부 서사는 "*인터넷 포르노 없이 충분히 오래 버틸 수 있다면, 결국 그것을 보고 싶은 충동이 사라질 것이다.*" 중독자들이 자신의 연속 또는 금욕의 날에 대해 이야기하는 온라인 포럼에서 이를 실제로 볼 수 있습니다.

위에서 말했듯이, 사용자가 겪는 고통은 정신적이며 불확실성으로 인해 발생합니다. 신체적 고통은 없지만 여전히 강력한 영향을 미칩니다. 이제 비참하고 불안한 사용자는 잊는 것과는 거리가 멀고, 이제 의심과 두려움으로 가득 차 있습니다.

-   “*갈망은 얼마나 오래 지속되나요?*"

-   “*다시 행복해질 수 있을까?*"

-   “*아침에 일어나고 싶을까?*"

-   “*앞으로 스트레스를 어떻게 견뎌낼까?*"

사용자는 상황이 나아지기를 기다리고 있지만 여전히 침울해하는 동안 '하렘'은 점점 더 소중해지고 있습니다. 사실, 무언가가 *일어나고* 있지만 무의식적으로 브라우저를 열지 않고 몇 주를 버틸 수 있다면 작은 괴물에 대한 갈망이 사라집니다. 그러나 앞서 언급했듯이 도파민과 오피오이드 금단 증상은 너무 약해서 사용자는 그것을 인식하지 못합니다. 이때 많은 사용자는 '그것을 걷어차 버렸다'고 느끼고 그것을 증명하기 위해 엿보고 워터 슬라이드로 돌아갑니다. 신체에 도파민을 공급한 후, 이제 그들의 마음 뒤편에서 "*또 하나 원해.*"라고 말하는 작은 목소리가 들립니다. 사실, 그들은 그것을 걷어차 버렸지만 다시 중독되었습니다.

어린 시절에 만화를 보고 신경 과학에 따르면 만화에 대한 신경 경로(DeltaFosB)를 형성했습니다. 아이가 만화를 보는 것을 막고 싶다면, 그 경로가 여전히 존재하는지 연구하고 어른들에게 왜 그들이 더 이상 좋아하는 어린 시절 만화를 보는 것을 좋아하지 않는지 조사할 것입니다. 첫째, 더 나은 엔터테인먼트가 있고 둘째, 만화가 더 이상 마법을 가지고 있지 않습니다. 의지력 방법을 사용하면 아이에게 만화를 거부하는 것이지만 EasyPeasy를 사용하면 아이가 만화에 아무런 가치를 두지 않도록 하는 것입니다. 어느 것이 더 낫습니까?

사용자는 일반적으로 "*다시 중독되고 싶지 않아!*"라고 생각하면서 즉시 다른 세션에 들어가지 않고 몇 시간, 며칠 또는 몇 주가 지나도록 안전하게 허용합니다. 전 사용자는 "*음, 중독되지 않았으니 안전하게 또 다른 세션을 할 수 있겠어.*"라고 말할 수 있습니다. 처음 시작했을 때와 같은 함정에 다시 빠져 이미 미끄러지는 경사로에 있습니다.

의지력 방법을 사용하여 성공한 사용자는 주된 문제가 세뇌이기 때문에 길고 어려움을 겪는 경향이 있습니다. 신체적 중독이 사라진 후에도 사용자는 여전히 우울하고 비참합니다. 결국 이 장기적인 고문에서 살아남은 후, 포기하지 않을 것이라는 것을 깨닫기 시작하고 우울함을 멈추고 포르노 없이도 삶이 계속되고 즐겁다는 것을 받아들입니다. 성공보다 실패가 훨씬 더 많은데, 성공한 일부 사람들은 취약한 상태에서 삶을 살아가고 포르노가 실제로 그들에게 활력을 준다고 말하는 일정량의 세뇌를 받기 때문입니다. 이는 오랫동안 중단한 많은 사용자가 나중에 다시 시작하는 이유를 설명합니다.

많은 전 사용자는 '특별한 대접'으로 가끔 세션을 갖거나 자기 통제력이 얼마나 강한지 스스로 확신시킵니다. 정확히 그렇게 합니다. 하지만 세션이 끝나자마자 도파민이 사라지기 시작하고 마음 뒤편의 작은 목소리가 그들을 다른 세션으로 몰고 가기 시작합니다. 참여하기로 결정하면 여전히 통제 하에 있는 것처럼 보이고 충격, 에스컬레이션 또는 새로운 것을 추구하는 것이 없으므로 "*대단해! 정말 즐겁지는 않지만 중독되지는 않을 거야."라고 말합니다. 크리스마스/이번 휴일/이번 트라우마가 지나면 그만둘게요.*" 그들은 그들의 뇌의 워터 슬라이드가 더욱 기름칠을 했다는 사실을 잘 모릅니다.

너무 늦었어요, 그들은 이미 빠져나왔어요! 그들이 스스로를 잡아낸 함정이 다시 희생자를 잡았어요.

앞서 말했듯이, 즐거움은 거기에 들어오지 않아요. 절대 없었어요! 만약 우리가 즐거움 때문에 시청한다면, 아무도 행위를 끝내는 데 걸리는 시간보다 더 오래 튜브 사이트에 머물지 않을 거예요. 그럼에도 불구하고, 자기 만족을 위한 더 나은 방법은 기억에서 나오는 거예요. 우리는 인터넷 포르노를 즐긴다고 생각하는 건, 그것을 즐기지 않으면 중독될 만큼 어리석을 거라고 믿을 수 없기 때문일 뿐이에요. 대부분의 사용자는 초자연적 자극, 참신함 또는 충격 추구에 대해 전혀 모르고, 그것에 대해 읽은 후에도 자신의 사용이 진화적 보상 회로 배선에 의해 동기가 부여되었다고 믿지 않아요. 그래서 포르노의 많은 부분이 잠재의식적인 거예요. 만약 당신이 신경학적 변화를 알고 미래에 그것이 당신에게 돈을 들일 것이라는 것을 정당화해야 한다면, 심지어 즐거움은 사라질 것입니다.

나쁜 쪽으로 마음을 막으려고 할 때, 우리는 어리석다고 느낍니다. 우리가 직면해야 한다면, 그것은 참을 수 없을 것입니다! 사용자가 행동하는 것을 보면, 그들이 사용하고 있다는 것을 모를 때만 행복해하는 것을 볼 수 있습니다. 일단 알게 되면, 그들은 불편하고 사과하는 경향이 있습니다. 포르노는 작은 괴물을 먹이기 때문에 세뇌(큰 괴물)와 함께 몸에서 그것을 정화하면, 볼 필요도 없고 보고 싶어하지도 않을 것입니다!
