# 단 한 번 엿보기

"단 한 번 엿보기"는 당신이 마음에서 제거해야 할 신화입니다.

- 처음에 우리를 시작하게 하는 것은 *단 한 번 엿보기*입니다.

- 대부분의 중단 시도를 무산시키는 어려운 시기나 특별한 경우에 *단 한 번 엿보기*입니다.

- 중독을 끊는 데 성공한 후에 우리를 다시 함정으로 보내는 것은 *단 한 번 엿보기*입니다. 때로는 더 이상 포르노가 필요하지 않다는 것을 확인하기 위한 것일 뿐이며, 한 번의 하렘 방문이 바로 그것을 합니다.

포르노의 후유증은 끔찍할 것이고 사용자는 다시는 중독되지 않을 것이라고 확신하지만, 그들은 이미 중독되었습니다. 사용자는 자신을 너무 비참하고 죄책감에 시달리게 만드는 무언가가 그렇게 해서는 안 된다고 생각하지만, 그렇게 되었습니다.

종종 사용자가 중단하지 못하게 하는 것은 '한 번의 특별한 세션'이라는 생각입니다. 긴 컨퍼런스 여행, 힘든 하루의 직장, 아이들과의 싸움, 파트너가 당신을 섹스를 거부하는 사건 이후의 세션입니다. '한 번만 엿보기'라는 것은 없다는 것을 ***확고히*** 명심하세요. 그것은 깨지지 않는 한 평생 지속되는 연쇄 반응입니다. 이상하고 특별한 경우에 대한 신화는 사용자가 멈춘 후 침울하게 만듭니다. '별거 아니야' 세션을 절대 보지 않는 습관을 들이세요. 그것은 환상입니다. 포르노를 생각할 때마다 정신적으로나 육체적으로 자신을 파괴하는 특권을 위해 화면 뒤에서 수천 년을 보내는 더러운 삶을 상상하세요. 평생 노예와 절망에 빠져 있습니다. 발기가 신뢰할 수 없다고 해서 범죄는 아니지만 장기적으로 더 행복할 수 있지만 대신 단기적인 '쾌락'을 위해 그것을 희생하기로 선택할 때는 범죄입니다.

우리가 공허함을 위해 항상 '할 일'을 생각해 낼 수 없다는 것은 괜찮습니다. 평생 모든 경우에 그렇게 하는 것은 현실적으로 가능하지 않습니다. 우리는 대부분을 계획할 수 있지만 때로는 그저 그렇게 됩니다. 포르노와 상관없이 좋은 때와 나쁜 때가 있습니다. 하지만 포르노가 아니라는 것을 분명히 명심하세요. 당신은 평생 비참하거나 전혀 비참하지 않을 것입니다. 아몬드 맛이 마음에 들어서 시안화물을 복용할 생각은 하지 않을 테니, 가끔씩 '별거 아닌' 세션으로 자신을 벌하는 것을 멈추세요. 문제가 있는 사용자에게 "*중독되기 전으로 돌아갈 기회가 있었다면 사용자가 되었겠습니까?*"라고 물어보세요. 대답은 피할 수 없이 "*농담이시죠!*"입니다. 하지만 모든 사용자는 매일 그 선택권을 가지고 있는데, 왜 그들은 그것을 선택하지 않을까요? 답은 두려움입니다. 멈출 수 없거나 그것 없이는 삶이 똑같지 않을 것이라는 두려움입니다.

자신을 속이는 것을 멈추세요! 누구나 할 수 있습니다. 엄청나게 쉬운 일이지만, 그렇게 하려면 마음속으로 몇 가지 기본 사항을 분명히 해야 합니다.

1. 포기할 것은 없고, 달성할 수 있는 놀라운 긍정적인 이득만 있습니다.

2. 이상한 '별거 아니야' 또는 '한 번 엿보기' 세션에 대해 결코 자신을 설득하지 마십시오. 그런 것은 존재하지 않습니다. 평생 동안 더럽고 노예가 될 뿐입니다.

3. 당신은 다른 것이 없습니다. 모든 사용자는 쉽게 중단할 수 있습니다.

많은 사용자는 자신이 중독자이거나 중독성 성격을 가지고 있다고 믿습니다. 이는 일반적으로 충격적인 신경 과학을 지나치게 많이 읽은 결과로 발생합니다. 그런 것은 없습니다. 중독되기 전에 비디오 클립을 보고 자위할 필요성을 가지고 태어난 사람은 없습니다. 당신을 사로잡는 것은 당신의 성격이나 성격의 본질이 아니라 약물입니다. 중독성 있는 초자연적 자극의 본질은 이것이 사실이라고 믿게 만듭니다. 그러나 이러한 믿음을 제거하는 것이 필수적입니다. 왜냐하면 당신이 중독되었다고 믿는다면, 당신의 몸 속의 작은 괴물이 오래 전에 죽은 후에도 중독될 것이기 때문입니다. 이 모든 세뇌를 제거하는 것이 필수적입니다.