# 사회적 습관?

정신과 신체의 건강은 우리가 *중단*해야 하는 주된 이유입니다. 하지만 항상 그래왔습니다. 포르노가 중독성이 있고 잠재적으로 우리의 삶을 산산조각 낼 수 있다는 것을 알려주기 위해 신경과학에 대한 과학적 연구와 지식이 실제로 필요하지 않습니다. 우리의 몸은 지구상에서 가장 정교한 물체이며, 모든 사용자는 첫 세션부터 자극이 과도하게 되어 독이 될 수 있다는 것을 알고 있습니다.

우리가 포르노에 관여하게 되는 유일한 이유는 진화적 프로그래밍과 주기가 겹치기 때문입니다. 인터넷 포르노는 매우 쉽게 이용할 수 있고 무료이며 하루 24시간 스트리밍됩니다. 포르노는 한때 무해하다고 여겨졌지만, 그 당시에는 이미지가 고정되어 있었고 비디오를 보려면 지역 상점에 가서 VHS 테이프를 사야 했습니다.

오늘날에는 포르노가 초자연적 자극이며 중독을 유발한다고 일반적으로 생각합니다. 사용자 자신도 마찬가지입니다. 옛날에는 강한 남자가 자위행위를 했다는 것을 인정하지 않았고, 멍청이라는 말은 경멸적인 용어였습니다. 모든 술집, 클럽 또는 바에서 대부분의 남성은 여성을 집으로 데려가 진짜 섹스를 하고 싶어할 것입니다. 오늘날 인터넷 포르노 중독자의 입장은 완전히 역전되었습니다. 오늘날의 남성은 여성이 필요 없다고 느끼기 시작했다는 것을 깨닫습니다. 온라인에서 뭉쳐서 경험을 논의하고, 전략을 고안하고, 옵션을 탐구합니다. 오늘날의 강한 남성은 약물에 의존하고 싶어하지 않습니다. 사회 혁명을 통해 모든 사용자는 인터넷 포르노와 자위 행위를 중단하는 것에 대해 진지하게 생각하고 있습니다. 오늘날의 사용자는 포르노를 쓸모없고 해로운 활동으로 생각합니다.

포럼에서 가장 눈에 띄는 추세는 포르노의 반사회적 측면에 대한 강조가 증가하고 있다는 것입니다. 남자가 매일 섹스와 오르가즘을 자랑하던 시절은 포르노 괴물에 대한 노예 의식으로 천천히 대체되고 있습니다.

사람들이 교육을 받은 후에도 계속하는 유일한 이유는 중단하지 못했거나 시도하기에는 너무 두려웠기 때문입니다. 이 주제에 대한 관심의 폭이 넓고, 일부는 파트너가 있든 없든 포르노, 자위 행위, 오르가즘을 삼가합니다. 정자 유지와 카레차와 같이 섹스의 탄트라와 전파 부분을 분리하는 관행이 무리 지어 논의되고 채택됩니다. 앞서 언급한 많은 실패는 실제로는 실패로 이어지고, 따라서 이를 실행하는 사람들에게 어느 정도 이롭습니다. PMO가 없는 경로를 시작하면 자신의 삶에 적용되는 가장 적합한 경로를 찾을 수 있습니다. 성적 분리를 이해하고 실행한 후 오르가즘에 대한 자신의 계획을 고안하는 것이 좋습니다. 어떤 경로이든 오르가즘을 통해 뇌에 화학 물질을 흘려보내는 횟수를 제한하고 포르노, 섹스, 오르가즘을 다시는 감정적 자아를 위한 즐거움이나 버팀목으로 보지 않는 데 가치가 있음을 알게 될 것입니다.

비사용자가 만든 다양한 인기 온라인 커뮤니티는 포르노뿐만 아니라 자위 행위도 끊는 데 전념합니다. 이러한 사이트는 궁극적으로 탈출하는 사람들에게 유익하지만 대부분의 메모는 의지력을 시도하라고 지적합니다. 금욕 행진과 다른 조치에 대한 집착의 결과는 자기 연민과 기쁨의 부족입니다. 세뇌의 대부분은 여전히 ​​살아 있고 건강합니다. 결국 누군가가 무너지고 도미노 효과가 발생하여 다른 사용자들은 자신들이 유일한 사람이 아니라는 것을 알게 됩니다. 그러나 그들의 노력은 헛되지 않고, 그들은 앞으로 넘어지고 있습니다. 비록 브라우저는 닫지만 욕망과 필요성은 닫지 않으면서 많은 자기 고문을 겪기는 하지만요. EasyPeasy는 반대로 작동하여 브라우저를 닫기 전에 먼저 필요성과 욕망을 닫아버립니다. 매일 점점 더 많은 사용자가 가라앉는 배를 떠나고, 그 배에 남겨진 사람들은 자신이 마지막이 될까봐 두려워합니다.

**당신이 되지 않도록 하세요!**