# 재미가 그리울까요?

**아니요!** 작은 포르노 괴물이 죽고, 몸이 도파민을 갈구하지 않고, 뇌의 포르노 워터 슬라이드가 '기름칠'이 부족해서 빠르게 사라지기 시작하면, 남아 있는 세뇌는 사라질 것입니다. 육체적으로나 정신적으로 삶의 스트레스와 긴장을 더 잘 처리할 수 있을 뿐만 아니라, 즐거운 시간을 최대한 즐길 수 있을 것입니다.

위험은 하나뿐입니다. 바로 섹스를 여전히 버팀목과 쾌락으로 사용하는 사람들의 영향입니다. *'다른 남자의 풀은 항상 더 푸르다'*는 우리 삶의 여러 측면에서 흔히 볼 수 있고 쉽게 이해할 수 있습니다. 포르노의 경우 - 환상적 '이점'에 비해 엄청난 단점이 있음에도 불구하고 - 전 사용자가 섹스와 포르노를 버팀목으로 요구하는 사람들을 부러워하는 경향이 있는 이유는 무엇일까요?

어린 시절의 모든 세뇌로 인해 우리가 함정에 빠졌다는 것은 충분히 이해할 수 있습니다. 그렇다면 왜 - 멍청이의 게임 포르노가 무엇인지 깨닫고, 그 습관을 걷어낸 뒤에도 - 우리는 똑같은 함정에 바로 빠지게 되는 걸까요? 포르노를 정상적인 것으로 제시하는 사회적 세뇌의 영향 때문입니다. 전 사용자는 화를 냅니다! 그들이 싱글이라는 불안한 공허감(어쨌든 범죄는 아닙니다)은 불안감을 유발하고, 그들을 워터 슬라이드를 타게 만듭니다. 이것은 실제로 이상한 변칙입니다. 특히 이 관찰을 고려한다면 더욱 그렇습니다. 세상의 모든 비사용자가 그렇게 되는 것을 기뻐할 뿐만 아니라, 세상의 모든 사용자는 왜곡되고, 중독되고, 세뇌된 마음이 즐거움이나 휴식의 망상에 시달리더라도 처음부터 중독되지 않았으면 좋겠다고 바랍니다. 그렇다면 일부 전 사용자는 왜 부러워할까요?

1. '한 번만 엿보기.' 기억하세요, 그런 것은 존재하지 않습니다. 고립된 상황을 보는 것을 멈추고 포르노 사용자의 관점에서 바라보기 시작하세요. 당신은 그들을 부러워할지도 모르지만, 그들은 자신을 인정하지 않고 당신을 부러워합니다. 다른 사용자를 임상적으로 관찰할 수만 있다면, 그들은 당신을 도울 수 있는 가장 강력한 도움이 될 수 있습니다. 그들이 얼마나 빨리 많은 탭과 브라우저 창을 여는지 알아차리세요? 중요한 섹션으로 빨리 넘어가서 클립에 금방 질려하고 참신함, 충격, 불안 등을 유발하는 모든 장르를 실행합니다. 특히 그 행동이 자동적인 것처럼 보인다는 점에 유의하세요. 기억하세요. 그들은 그것을 즐기는 것이 아니라, 그것 없이는 즐길 수 없다는 것입니다. 다음날 아침, 약해진 의지, 잃어버린 에너지, 흐릿한 눈으로 깨어나 스트레스와 긴장의 첫 등장에 계속해서 스스로를 질식시켜야 할 것입니다. 그들은 평생의 더러움, 열악한 정신 건강, 얼룩진 자신감에 직면하게 됩니다. 평생 마음 뒤편에 검은 그림자를 두고 스스로를 파괴하는 것입니다. 어떤 목적을 달성하기 위해서? 당신이 '받을 만한' 것을 얻고 저주받은 쾌락을 얻는다는 환상?

2. 일부 전 사용자가 괴로워하는 두 번째 이유는 포르노 사용자가 무언가를 하고 있고(예: 자위 행위) 비사용자는 그렇지 않기 때문에 박탈감을 느끼는 경향이 있기 때문입니다. 박탈당하는 것은 비사용자가 아니라 가난한 중독자라는 것을 명심하세요.

- 건강

- 에너지

- 자신감

- 마음의 평화

- 용기

- 평온

- 자유

- 자존심

포르노 사용자를 부러워하는 습관을 버리고 그들이 실제로 비참하고 불쌍한 존재라는 것을 보세요. 저도 한때 최악이었습니다. 그래서 이 책을 읽고, 그것을 마주할 수 없고 계속해서 스스로를 속이는 사람들이 아닌 것입니다.

헤로인 중독자를 부러워하지 않을 것이고, 모든 약물 중독과 마찬가지로 당신의 중독은 나아지지 않을 것입니다. 매년 기하급수적으로 더 나빠질 겁니다. 오늘 사용자로서의 삶을 즐기지 못한다면 내일은 더 즐길 수 없을 겁니다. 다른 사용자를 부러워하지 말고, 그들을 불쌍히 여기세요. 저를 믿으세요: ***그들은 당신의 불쌍히 여기는 마음이 필요합니다!***