# 구획화할 수 있나요?

이 신화는 주로 의지력 방법을 중단하려는 사용자들에 의해 퍼졌습니다. 이들은 정신적 체조를 하고 제킬 앤 하이드 루틴을 시작합니다. "*포르노는 내 분신을 위한 것이고 실제 로맨스는 내 관계적 측면을 위한 것입니다.*" 아무것도 진실과 거리가 멉니다. 포르노 워터 슬라이드, DeltaFosB 및 신경학적 변화가 실제 로맨스를 압도하여 덜 바람직하게 만들 것입니다. 하이드 씨는 분명히 제킬 박사의 지시를 무시할 것입니다.

인터넷 포르노를 사용하면 관음증 환자 역할을 위해 스스로를 훈련시키거나 도파민 수치가 약간 떨어지면 더 흥분되는 것을 클릭해야 하는 옵션이 필요합니다. 또는 최대 효과를 위해 *딱* 적절한 장면을 계속 검색합니다. 또한 몸을 구부린 자세로 자위하거나 매일 밤 침대에서 스마트폰을 보면서 결국 실제 자극보다 그러한 신호를 더 원하게 될 수 있습니다. 섹스는 온라인 하렘의 거의 모든 측면에 어긋나므로 비교할 때 기회가 없습니다. 젊을 때 만든 기억은 강력하고 오래 지속되므로 포르노 워터 슬라이드를 분해하고 다시 배선하거나 새로 만드는 데는 더 오랜 시간이 걸립니다. 그러나 더 어렵다는 것은 아닙니다.

'포르노 워터 슬라이드'를 탈 때마다 윤활유를 바르고 신경을 상쾌하게 유지하고 불타오르게 합니다. 패스트푸드 레스토랑 옆에 주차하면 프라이어 냄새가 코로 들어오고 이미 판매가 성립됩니다. 마찬가지로 뇌의 포르노 워터 슬라이드는 빨려들 준비가 되어 있으며 하루 24시간 열려 있습니다. 각 신호 또는 트리거는 섹스의 약속으로 보상 회로를 밝힙니다. 그러나 그것은 섹스가 아닙니다. 그럼에도 불구하고 신경 세포는 연결을 강화하기 위해 새로운 가지를 돋우어 성적 각성과의 이러한 연관성을 굳건히 합니다. 포르노를 많이 사용할수록 신경 연결이 강해집니다. 최종 결과는 궁극적으로 *관음증자*가 되어야 하고, 점점 더 심해지는 새로운 자료를 클릭해야 하고, 잠들기 위해 포르노가 필요하거나, 일을 끝내기 위해 완벽한 엔딩을 찾아야 할 수도 있다는 것입니다.

모든 물질이나 행동 약물과 마찬가지로 신체는 내성을 키우고 약물은 금단 증상을 완전히 완화하지 못합니다. 포르노 사용자가 세션을 마치자마자 또 다른 세션을 원하고, 금세 영구적인 배고픔이 충족되지 않습니다. 자연스러운 경향은 도파민 러시를 얻기 위해 에스컬레이션하는 것입니다. 그러나 대부분의 사용자는 다음 두 가지 이유 중 하나 또는 둘 다로 인해 이를 수행하지 못합니다.

**돈:** 유료 포르노 사이트에 가입할 여유가 없습니다.

**건강:** 신체가 감당할 수 있는 것에는 도파민 급증이나 오르가즘이 있습니다. 게다가 오르가즘은 실제로 도파민 플러시를 줄이기 위해 화학 물질을 유발합니다. 그래야만 합니다. 신체가 작동하는 방식이기 때문입니다.

작은 괴물이 몸을 떠나면 끔찍한 불안감이 사라집니다. 자신감이 돌아오고, 자존감이 놀라울 정도로 강해져서 인생을 통제하고 다른 문제를 해결하는 발판으로 삼을 수 있는 확신을 얻습니다. 이것은 중독에서 벗어나는 것의 많은 장점 중 하나입니다.

구획화 신화는 작은 괴물이 당신의 마음을 가지고 노는 많은 속임수 중 하나입니다. 이러한 속임수는 영구적인 배고픔을 만족시킬 수 없기 때문에 중단하기 어렵게 만들고, 많은 사용자가 공허함을 채우기 위해 담배, 폭음, 심지어 더 강한 약물에 의지하게 만듭니다.

인간은 자신과 다른 사람 모두에게 동물을 평가합니다. 파트너와 함께 포르노를 보는 것은 만족스럽지 않습니다. 두 사람 모두 내러티브에 대해 서로의 성과를 평가하기 때문입니다. 포스터에 나와 있더라도 침실에 브래드 피트가 있기를 원하십니까? 각 '경험'이 연기되고, 대본이 작성되고, 전문가가 감독하고 하루 24시간 즉시 이용할 수 있는 하렘과 맞먹는 사람은 없습니다.