# 거짓 인센티브 피하기

의지력 방법을 사용하는 많은 사용자는 거짓 인센티브를 구축하여 동기를 부여하려고 시도합니다. 이에 대한 많은 예가 있는데, 대표적인 예는 한 달 동안 포르노를 보지 않은 후 선물로 자신을 보상하는 것입니다. 이는 논리적이고 합리적인 접근 방식으로 보이지만 사실은 거짓입니다. 자존심이 있는 사용자는 스스로에게 선물을 주는 것보다 매일 포르노를 계속 보는 것을 선호하기 때문입니다. 이는 사용자의 마음에 의심을 불러일으킵니다. *30일* 동안 금욕해야 할 뿐만 아니라 포르노 없는 날을 *즐길* 수 있을지 확신할 수 없기 때문입니다. 그들의 유일한 즐거움이나 버팀목이 앗겨간 것입니다! 이 모든 것은 사용자가 자신이 하고 있다고 느끼는 희생의 크기를 증가시킬 뿐이며, 이제 그들의 마음속에서 더욱 소중해집니다.

다른 예는 다음과 같습니다.

- 사회생활과 더 많은 실제 섹스를 하도록 강요하기 위해 멈출 것입니다.

- 경쟁자를 뛰어넘고 내가 추구하는 파트너를 얻는 데 도움이 되는 마법의 에너지를 얻기 위해 멈출 것입니다.

- 포르노에 에너지와 열정을 낭비하지 않고 내 안에 배고픔을 키우지 않겠다고 다짐하기 위해 멈출게요.

이것들은 사실이고 효과적일 수 있으며 결국 원하는 것을 얻을 수도 있지만 잠깐 생각해보세요. 원하는 것을 얻는다면, 그 참신함이 사라지면 박탈감을 느낄 것이고, 얻지 못했다면 비참함을 느낄 것입니다. 어느 쪽이든 조만간 같은 함정에 다시 빠지게 될 것입니다.

그만두는 것을 거짓된 인센티브와 연결하면 의심이 커질 뿐입니다. 인센티브를 얻지 못하면(그리고 얻더라도) "*그만두는 것이 실제로 내 삶을 더 좋게 만들까? 그만두고 원하는 것을 얻지 못하면, 그 방법을 올바르게 사용했을까?*"와 같은 의심스러운 생각을 하기 시작할 것이기 때문입니다. 이런 생각은 희생의 감정을 증가시키고 따라서 괴로움을 만듭니다.

또 다른 전형적인 예는 온라인이나 포럼 협정입니다. 이는 일정 기간 동안 유혹을 없애는 장점이 있습니다. 그러나 일반적으로 다음과 같은 이유로 실패합니다.

1.  인센티브가 거짓입니다. 다른 사람들이 그렇게 한다고 해서 왜 멈추고 싶어합니까? 이 모든 것은 추가적인 압력을 생성하고 희생의 느낌을 증가시킬 뿐입니다. 모든 사용자가 특정 시간에 진정으로 멈추고 싶어한다면 괜찮지만, 모두가 비밀리에 원하더라도 멈추도록 강요할 수는 없습니다. 그들이 그렇게 할 준비가 될 때까지 협정은 추가적인 압력을 생성하여 시청하려는 욕구만 증가시킵니다. 이것은 그들을 비밀 시청자로 만들어 의존감을 더욱 증가시킵니다.

2.  의지력 방법을 사용하여 서로에게 의존하면 속죄 기간을 거치는 느낌이 들며, 그 동안 충동이 사라질 때까지 기다립니다. 그들이 포기하면 실패감이 있습니다. 의지력 방법을 사용하면 참가자 중 적어도 한 명이 포기하게 되어 다른 참가자에게 그들이 기다려온 변명을 제공합니다. 그것은 그들의 잘못이 아닙니다. 그들은 참았을 것이지만 '프레드'가 그들을 실망시켰습니다. 진실은 그들 대부분이 이미 부정행위를 했다는 것입니다.

3.  공로를 공유하는 것은 의존의 반대 개념입니다. 포르노를 끊는 데는 놀라운 성취감이 있으며, 혼자 할 때 친구와 온라인 친구로부터 받는 찬사는 처음 며칠 동안 엄청난 도움이 될 수 있습니다. 그러나 모든 사람이 동시에 할 때 공로를 공유해야 하며 결과적으로 도움이 줄어듭니다.

4.  또 다른 고전적인 예는 구루의 약속입니다. 중단하면 더 이상 줄다리기에 참여하지 않기 때문에 행복을 얻을 수 있으며, 뇌가 다시 배선되고 충동 제어를 회복합니다. 그러나 이것이 당신을 섹스 신으로 만들거나 복권에 당첨시키지는 않을 것이라는 점을 명심해야 합니다. 당신 외에는 아무도 당신이 포르노를 끊는지에 대해 조금도 신경 쓰지 않습니다. 하루에 세 번 포르노를 보고 PIED가 있다고 해서 약한 사람이 아니고, 중독자이지만 그렇지 않다고 해서 강한 사람이 아닙니다.

자신을 속이는 것을 멈추세요. 연봉 12개월치에 10개월치 일할 수 있는 일자리 제안이나, 일상의 스트레스와 긴장에 대처하는 뇌의 능력을 저하시킬 위험, 신뢰할 수 있는 발기와의 갈등, 평생의 정신적, 신체적 고문과 노예 생활이 그들을 멈추지 못했다면, 위의 몇 가지 허황된 인센티브는 아무런 차이를 만들지 못할 것이고, 희생이 더 나쁘게 보이게 만들 뿐입니다. 대신, 반대편에 집중하세요.

\"내가 그걸로 뭘 얻는 거지? 왜 포르노를 봐야 할까?\"

줄다리기의 반대편을 계속 바라보고 포르노가 당신에게 무엇을 해주고 있는지 자문해보세요. *전혀 아무것도 아닙니다.* 왜 그럴 필요가 있을까요? *당신은 그럴 필요가 없습니다! 당신은 그저 스스로를 벌하고 있을 뿐입니다.* 파스칼의 내기입니다. 잃을 것이 거의 없고(각성 감소), 큰 이익(완전하고 안정적인 각성, 정신적 안녕과 행복)을 얻을 가능성이 있으며 큰 손실을 볼 가능성도 없습니다.

그럼 왜 친구와 가족에게 그만두겠다고 선언하지 않나요? 글쎄요, 그러면 당신은 기뻐하고 행복한 비사용자가 아니라 자랑스러운 전 중독자 또는 전 사용자가 될 것입니다. 파트너가 이것을 일종의 뉴에이지 방식으로 더 많은 섹스를 하려는 계략으로 볼 수 있기 때문에 약간 무서워할 수도 있습니다. 그들은 또한 당신이 섹스 머신으로 변하는 것을 두려워할 수도 있습니다. 그들이 열린 마음을 가지고 있지 않으면 설명하기 어렵습니다.

다른 사람들이 당신을 도와서 그만두게 하려는 시도는 그 작은 괴물에게 더 많은 힘을 줍니다. 그것을 당신의 마음에서 밀어내고 완전히 무시하는 것은 그것에 대해 생각하지 않으려고 하는 효과가 있습니다. 대신 마음챙김을 하세요. 생각, 신호(혼자 집에 있음) 또는 무심한 생각을 발견하자마자, 그냥 스스로에게 *\"좋아, 나는 더 이상 포르노의 노예가 아니야. 나는 자유롭고 성별의 차이를 알게 되어 행복해!\"*라고 말하세요. 이렇게 하면 생각으로 가는 산소가 차단되고 충동과 갈망으로 타오르는 것을 멈출 것입니다. 이 측면에서 마음챙김 명상을 연습하는 것은 생각의 비인격화를 돕는 데 도움이 될 수 있습니다.
