# 금단 기간

마지막 세션 후 최대 3주 동안 금단 증상을 겪을 수 있습니다. 이는 두 가지 완전히 별개이지만 뚜렷한 요인으로 구성됩니다.

1. 도파민 금단 증상. 배고픔과 유사한 공허하고 불안한 느낌으로, 갈망이나 '꼭 해야 할 일'이라는 느낌으로 식별됩니다.

2. 광고, 온라인 검색, 전화 대화 등과 같은 특정 외부 자극의 심리적 트리거.

이 두 가지 뚜렷한 요인을 이해하고 구별하지 못하면 의지력 방법을 사용하여 성공하기 어렵고, 결국 많은 사람이 다시 함정에 빠지는 이유입니다. 도파민 금단 증상은 신체적 고통을 유발하지 않지만, 그 힘을 과소평가하지 마십시오. 하루 동안 음식을 먹지 않으면 '배고픔 통증'이라고 말합니다. 배가 울릴 수는 있지만 신체적 고통은 없습니다. 그럼에도 불구하고 배고픔은 강력한 힘이며 음식을 박탈당하면 매우 짜증이 날 가능성이 있습니다. 우리 몸이 도파민 러시를 갈구할 때와 비슷한데, 차이점은 우리 몸이 독이 아니라 음식을 필요로 한다는 것입니다. 올바른 마음가짐을 갖고 있다면 금단 증상은 쉽게 극복되고 매우 빠르게 사라집니다.

의지력 방법으로 며칠 동안 금단을 하면 도파민 플러시에 대한 갈망이 곧 사라집니다. 어려움을 유발하는 것은 두 번째 요인인 세뇌입니다. 사용자는 특정 시간과 특정 상황에서 금단 증상을 완화하는 습관이 생겨서 아이디어가 연관됩니다("발기가 되었으니 포르노를 봐야겠다." 또는 "노트북을 놓고 침대에 누워서 행복감을 느끼려면 세션을 해야겠다."). 이 효과는 예를 들어 가장 잘 설명할 수 있습니다. 차가 있고 방향 지시등이 왼쪽에 있지만 다음 차에서는 오른쪽에 있습니다. 왼쪽에 있다는 것을 알고 있지만 몇 주 동안은 방향을 지시하고 싶을 때 와이퍼를 켭니다.

정지도 비슷합니다. 초기에는 트리거 메커니즘이 특정 시간에 작동합니다. 세션을 원한다고 생각할 것이므로 세뇌에 맞서는 것이 처음부터 필수적이며 이러한 신호와 트리거가 빠르게 사라지게 할 것입니다. 의지력 방법에서 사용자는 자신이 희생을 하고 있다고 믿기 때문에 그것에 대해 침울해하고 충동이 사라질 때까지 기다리고 있으며 이러한 트리거 메커니즘을 제거하는 것과는 반대로 실제로는 증가하게 됩니다. 마찬가지로 구루 사고에서 사용자는 언제 신이 될지 궁금해하기 시작하고 심지어 그러한 생각을 하지 말라고 요구하여 자기 혐오와 실패의 길을 닦습니다.

일반적인 트리거는 혼자 있는 시간, 특히 친구들과 함께하는 사교 모임입니다. 다른 방법을 사용하여 그만두는 전 사용자는 평소의 버팀목이나 즐거움을 박탈당했다고 느끼기 때문에 이미 비참합니다. 그들의 친구들은 파트너와 함께 있고 친밀하게 행동합니다. 사용자는 싱글이거나 파트너로부터 '아무것도' 얻지 못하고 있으며 이제는 즐거운 사교 모임이어야 할 것을 더 이상 즐기지 않습니다. 그들의 기존의 뇌 워터 슬라이드는 파트너를 유혹하려고 하는 것보다 더 쉬운 포르노로 이어집니다.

섹스에 대한 권리 의식과 웰빙의 연관성 때문에 그들은 이제 세 배의 타격을 입고 있으며 세뇌는 실제로 증가합니다. 그들이 단호하고 충분히 오래 버틸 수 있다면 결국 자신의 운명을 받아들이고 삶을 계속 살아갑니다. 그러나 세뇌의 일부는 여전히 남아 있으며 두 번째로 비참한 측면은 사용자가 그만두었지만 몇 년이 지난 후에도 특정 경우에 '하렘에 마지막으로 한 번만 방문'하고 싶어한다는 것입니다. 그들은 자신의 마음 속에만 존재하는 환상을 그리워하고 있으며 불필요하게 스스로를 고문합니다.

EasyPeasy에서도 트리거에 대응하는 것이 가장 흔한 실패입니다. 전 사용자는 인터넷 포르노를 일종의 위약이나 설탕 알약으로 여기는 경향이 있으며, "*포르노가 나에게 아무런 효과가 없다는 건 알지만, 효과가 있다고 생각하면 어떤 경우에는 도움이 될 거야.*"라고 생각합니다. 설탕 알약은 실제적인 신체적 도움은 주지 않지만, 진정한 증상을 완화하는 강력한 심리적 도움이 될 수 있으므로 유익합니다. 그러나 인터넷 포르노와 습관적인 자위 행위는 설탕 알약이 아닙니다. 왜 그럴까요? 포르노는 완화하는 증상을 만들어내고 완전히 완화하지 못합니다.

비사용자 또는 몇 년 동안 중단한 성공적인 사용자와 관련될 때 효과를 이해하는 것이 더 쉬울 수 있습니다. 파트너를 잃은 사용자의 경우를 생각해 보세요. 그런 때, 좋은 의도로 "*하렘 방문을 한 번 하면 진정될 거야.*"라고 말하는 것은 꽤 흔한 일입니다. 제안이 수락되면 도파민 중독이 없고 따라서 금단 증상도 없기 때문에 진정 효과가 없습니다. 기껏해야 잠깐 심리적으로 활력을 북돋아줄 뿐입니다.

세션이 끝난 후에도 원래의 비극은 그대로입니다. 사실, 그 사람은 이제 금단 증상을 겪고 선택을 해야 하기 때문에 더 심해질 것입니다. 참을지, 아니면 워터 슬라이드를 반복해서 타서 비참함의 사슬을 다시 시작해서 구제책을 찾을지 말입니다. 제공된 모든 포르노는 덧없는 심리적 활력을 주었을 뿐이며, 책이나 기분 좋은 영화, 심지어 나쁜 영화로도 얻을 수 있는 것과 같은 것입니다. 많은 비사용자와 전사용자가 이런 경우로 인해 다시 중독되었습니다. 마음속으로 확실히 기억하세요. 도파민 러시가 필요한 것이 아니라 그것을 어떤 것으로 계속 간주함으로써 자신을 더 괴롭히고 있을 뿐입니다. 일종의 소품이나 부스트입니다. 비참할 필요는 없습니다.

오르가즘은 좋은 관계를 만들어내지 못하고, 대부분 관계를 망칩니다. 또한 공개적으로 애정을 표현하는 사람들이 모든 상황을 즐긴다는 것은 전적으로 사실이 아니라는 점을 기억하세요. 친밀감은 파트너가 부끄러움 없이 반응할 수 있는 사적인 상황에서 가장 잘 즐길 수 있습니다. 오르가즘으로 유도된 도파민 중독자가 될 필요는 없습니다. 일련의 삶의 사건의 자연스러운 결과로 발생하는 경우 괜찮지만, 그 상황과 그 상황 없이 삶을 즐기세요.

포르노가 그 자체로 즐거운 것이라는 개념을 포기한 후, 많은 사용자는 "*만약 깨끗한 인터넷 포르노가 있었으면*"이라고 생각합니다. *깨끗한* 소프트 포르노가 있고, 그것을 시도한 사람은 곧 그것이 시간 낭비라는 것을 알게 됩니다. 포르노를 사용하는 유일한 이유는 도파민 플러시를 얻기 위한 것이라는 것을 마음속으로 분명히 하십시오. 포르노에 대한 도파민 갈망이 사라지면 온라인 하렘을 방문할 필요가 없을 것입니다.

고통이 실제 도파민 금단 증상 또는 트리거/신호 메커니즘 때문인지는 상관없이 받아들이십시오. 신체적 고통은 존재하지 않으며 올바른 마음가짐이라면 문제가 되지 않을 것입니다. 금단에 대해 걱정하지 마십시오. 그 감정 자체는 나쁘지 않습니다. 문제는 원하고 거부당하는 느낌과 관련이 있다는 것입니다. 그것에 대해 침울해하는 대신 인정하십시오. "*이게 뭔지 알아요, 포르노 금단이에요. 사용자들은 평생 이런 고통을 겪고 중독자로 만듭니다. 비사용자는 이런 고통을 겪지 않습니다. 고통, 그것은 이 거짓말 중독의 많은 악 중 하나입니다. 내 뇌에서 이 악을 정화하고 있다는 것이 놀랍지 않습니까!"*

즉, 앞으로 3주 동안 몸 안에 약간의 트라우마가 있겠지만, 그 주와 남은 인생 동안 놀라운 일이 일어날 것입니다. 당신은 끔찍한 질병을 스스로 없애고, 보너스가 가볍고 일시적인 트라우마보다 훨씬 더 크고, 실제로 금단 증상을 즐길 것입니다. 그것은 당신의 뱃속에 사는 포르노 촌충을 굶기는 흥미진진한 게임처럼 즐거움의 순간이 될 것입니다. 당신은 그것이 당신을 살리기 위해 침대에 들도록 속이려고 하는 동안 3주 동안 그것을 굶겨야 합니다.

때때로, 그것은 당신을 비참하게 만들려고 할 것입니다. 때때로, 당신은 방심할 것입니다. 당신은 포르노 URL을 받거나 온라인에서 무언가를 우연히 발견하고는 멈췄다는 것을 잊어버리고, 기억할 때 약간의 박탈감을 느낄 것입니다. 이러한 속임수에 미리 대비하고, 어떤 유혹이 오더라도 그것은 오로지 당신 몸 안에 있는 괴물 때문에 온다는 것을 명심하고, 유혹에 저항할 때마다 전투에서 치명적인 일격을 가하는 셈이라는 것을 명심하세요.

무엇을 하든 포르노를 잊으려고 하지 마세요. 이것은 의지력 방법을 사용하는 PMOer가 몇 시간 동안 우울증에 빠지게 하는 원인 중 하나입니다. 그들은 결국 잊어버릴 수 있기를 바라며 매일을 보내려고 노력합니다. 잠을 잘 수 없는 것과 같습니다. 걱정할수록 더 어려워집니다. 어떤 경우든 잊을 수 없을 것입니다. 처음 며칠 동안은 '작은 괴물'이 계속 상기시키고 피할 수 없을 것입니다. 여전히 노트북, 스마트폰, 잡지가 있지만 끊임없이 상기시켜 줄 것입니다.

요점은 나쁜 일이 일어나지 않으므로 잊을 필요가 없다는 것입니다. 사실, 놀랍고 멋진 일이 일어나고 있으며 하루에 천 번이나 그것에 대해 생각하더라도 **매 순간을 음미하고 다시 자유로워지는 것이 얼마나 놀라운지 스스로에게 상기시키세요. 더 이상 스스로를 괴롭히지 않아도 된다는 순수한 기쁨을 상기하세요.** 앞서 말했듯이, 고통이 즐거움의 순간이 되고, 포르노를 얼마나 빨리 잊을 수 있는지 놀라게 될 것입니다.

무엇을 하든 *자신의 결정을 의심하지 마세요*. 의심하기 시작하면 우울해지기 시작하고 더 악화될 것입니다. 대신, 우울한 순간을 이용해 활력을 북돋우세요. 우울증이 원인이라면 포르노가 우울증을 *원인*이라고 스스로에게 상기하세요. 친구가 URL을 전달해 주었다면, "*더 이상 필요 없다고 말할 수 있어서 기뻐요.*"라고 말하는 것을 자랑스러워하세요. 그러면 상대방이 상처받을 수 있지만, 상대방이 그것이 당신을 괴롭히지 않는다는 것을 알게 되면 반쯤은 당신에게 동참하게 될 것입니다.

**기억하세요: 처음부터 중단해야 할 엄청나게 강력한 이유가 있습니다.** 비용을 상기하고 몸과 마음의 오작동과 평생 마법에 시달리게 될 단순한 사실을 감수하고 싶은지 자문해보세요. 위험을 최소화하려는 작은 괴물의 노력을 염두에 두고, 무엇보다도 그 감정은 일시적일 뿐이며, 매 순간이 목표에 한 걸음 더 가까워진다는 것을 기억하세요.

일부 사용자는 평생 '자동 트리거'를 역전해야 할까봐 두려워합니다. 다시 말해, 심리학을 사용하여 포르노가 필요 없다고 스스로를 속이며 살아야 한다고 믿습니다. 그렇지 않습니다. 낙관주의자는 병이 반만 차 있다고 보고 비관론자는 그것을 반쯤 비어 있다고 봅니다. 포르노의 경우, 병은 비어 있고 사용자는 그것이 가득 찼다고 봅니다. 인터넷 포르노를 사용하는 데는 이점이 없습니다. 이점이 있다고 생각하도록 세뇌된 사람은 사용자입니다. 포르노가 필요 없거나 원하지 않는다고 스스로에게 말하기 시작하면, 아주 짧은 시간 안에 말할 필요도 없게 되고, 스스로 아름다운 진실을 보게 됩니다. 그것은 당신이 해야 할 마지막 일입니다. 그것이 당신이 하는 마지막 일이 되지 않도록 하십시오.
