# 나에게 더 어려울까?

각 개인 사용자가 얼마나 쉽게 끊을지 결정하는 요인의 무한한 조합이 있습니다. 우선, 우리 각자는 고유한 성격, 직업, 개인적 상황, 타이밍, 신진대사 등을 가지고 있습니다. 특정 직업은 다른 직업보다 더 어려울 수 있지만 세뇌를 제거한다면 그럴 필요가 없습니다. 다음 몇 가지 예를 들어 보겠습니다.

가끔 의료 종사자에게는 어려울 수 있습니다. 우리는 의사들이 그 효과를 더 잘 알고 있기 때문에 더 쉬울 것이라고 생각하지만, 이것이 중단에 대한 더 강력한 이유를 제공하더라도 달성하는 것을 더 쉽게 만들지는 않습니다. 그 이유는 다음과 같습니다.

1. 건강 위험에 대한 끊임없는 인식은 두려움을 만들어내는데, 이는 금단 증상을 완화해야 할 필요성을 느끼는 상황 중 하나입니다.

2. 의사의 업무는 극도로 스트레스가 많고 일하는 동안 금단 증상의 추가 스트레스를 해소할 수 없습니다.

3. 그들은 나머지 인구에게 모범을 보여야 한다는 죄책감이라는 추가 스트레스를 받습니다. 이것은 그들에게 더 많은 압박을 가하고 박탈감을 증가시킵니다.

직장에서 힘든 하루를 보낸 후 포르노로 인해 스트레스가 잠시 해소되면 그 세션은 경험한 안도감과 잘못 연결됩니다. 이러한 잘못된 생각의 연관으로 인해 포르노가 모든 상황의 공로를 차지하게 되고, 포르노를 끊고 금단 증상을 겪으면서 갑자기 매우 소중해집니다. 이것은 일반 사용자의 한 형태이며 사용자가 장기간 금욕해야 하는 모든 상황에 적용됩니다. 의지력 방법에 따르면 사용자는 박탈당하고 세션 후에 오는 피로와 수면을 즐기지 못하기 때문에 비참합니다. 그들의 상실감은 크게 증가합니다. 그러나 먼저 포르노에 대한 세뇌와 침울함을 제거할 수 있다면 신체가 아민 전달 물질인 세로토닌, 노르에피네프린, 도파민을 갈구하는 동안에도 휴식과 수면을 여전히 즐길 수 있습니다.

또 다른 어려운 상황은 지루함인데, 특히 스트레스 기간과 결합될 때 그렇습니다. 전형적인 예로는 학생과 싱글 맘, 스트레스가 많지만 단조로운 직장입니다. 의지력 방법을 중단하려고 시도하는 동안, 독신자는 '상실'에 대해 침울해하는 기간이 길어지고, 이는 우울증을 증가시킵니다. 다시 말하지만, 마음가짐이 올바르다면 이것도 쉽게 극복할 수 있습니다. 포르노를 끊었다는 사실을 계속해서 상기시켜준다고 걱정하지 마세요. 그런 순간을 이용해 사악한 괴물을 스스로 없애고 있다는 사실을 기뻐하세요.

긍정적인 마음가짐을 가지고 있다면 이런 고통은 즐거움의 순간이 될 것입니다. 기억하세요, 나이, 성별, 지능 또는 직업에 관계없이 모든 사용자는 **모든 지침을 따른다면** 쉽고 즐겁게 중단할 수 있습니다.

## 실패의 주요 이유

실패에는 두 가지 주요 이유가 있습니다. 첫 번째는 상업적, 온라인 뉴스 기사, 인터넷 검색 등 외부 자극의 영향입니다. 그들은 약한 순간에 처하거나 사회적 상황에서 친밀감을 보면 질투하기도 합니다. 이 주제는 이미 자세히 논의되었습니다. 그 순간을 이용해 한 번의 방문이나 엿보기라는 것은 없다는 것을 상기시키세요. 정신적 노예의 사슬을 끊었다는 사실에 기뻐하세요. 사용자가 당신을 부러워하고 당신은 그들을 불쌍히 여겨야 합니다. 왜냐하면 그들은 당신을 필요로 하기 때문입니다.

또 다른 이유는 나쁜 하루를 보내는 것입니다. 시작하기 전에 사용자이든 아니든 좋은 날과 나쁜 날이 있을 것이라는 것을 마음속으로 분명히 하세요. 교황과 살인자 모두에게 비가 내립니다. 인생은 상대적이며 기복 없이는 기복을 겪을 수 없습니다. 의지력 방법의 문제점은 사용자가 나쁜 하루를 보내자마자 '하렘'을 방문하고 싶어서 우울해지기 시작하여 문제가 더욱 복잡해진다는 것입니다. 비사용자는 육체적으로뿐만 아니라 정신적으로도 스트레스와 긴장을 더 잘 처리할 수 있습니다. 금단 기간 동안 나쁜 날이 있다면 그냥 받아들이세요. 중독되었을 때도 나쁜 날이 있었다는 것을 기억하세요. 그렇지 않았다면 끊기로 결정하지 않았을 겁니다. 그것에 대해 침울해하는 대신, 대신 인식하세요: *"좋아요, 오늘은 별로 좋지 않지만 포르노가 그것을 치료할 수는 없을 거예요. 내일은 나아질 거고 적어도 놀라운 보너스가 있어. 그 끔찍한 중독을 끊었거든."*

포르노를 사용하는 사람이라면 포르노의 부정적인 면에 마음을 닫아야 합니다. 포르노를 사용하는 사람은 뇌 안개가 없고 그저 '조금 침체'에 빠져 있을 뿐입니다. 인생에서 피할 수 없는 문제가 생기고 포르노를 원한다는 생각이 들 때, 당신은 행복하고 쾌활합니까? 물론 그렇지 않습니다. 일단 멈추면, 잘못된 모든 일을 당신이 멈췄다는 사실로 돌리는 경향이 있습니다.

일이 스트레스를 받으면, "*이런 때라면 세션을 했을 거야.*"라고 생각합니다. 사실이지만, 잊고 있는 중요한 것은 포르노가 문제를 해결하지 못했고, 당신은 그저 허황된 목발에 대해 침울해하면서 스스로를 벌하고 있다는 것입니다. 당신은 불가능한 상황을 만들고 있고, 포르노를 보고 자위할 수 없기 때문에 비참하지만, 그렇게 하면 더 비참해질 것입니다. *당신은 그것을 멈추는 것으로 올바른 결정을 내렸다는 것을 알고 있는데, 왜 당신의 결정을 의심함으로써 스스로를 처벌합니까?*

기억하세요, 긍정적인 정신적 접근 방식은 필수적입니다. 항상.
