# 계시의 순간

일반적으로 탈출 후 3주 이내에 전 사용자는 계시의 순간을 경험합니다. 하늘이 더 밝아지고 세뇌가 완전히 끝나는 순간입니다. 포르노를 볼 필요가 없다고 스스로에게 말하는 대신 갑자기 마지막 실이 끊어졌고 다시는 필요하지 않고 남은 인생을 즐길 수 있다는 것을 깨닫습니다. 또한 이 지점에서 사용자를 동정의 대상으로 보기 시작합니다.

의지력 방법을 사용하는 중단자는 일반적으로 이 순간을 경험하지 못합니다. 왜냐하면 그들은 전 사용자가 된 것을 기쁘게 생각하지만 희생을 하고 있다고 믿으며 삶을 계속 살아가기 때문입니다. 중독이 심할수록 이 순간은 더욱 경이롭고 평생 지속됩니다. 인생에는 많은 즐거움이 있지만 실제로 경험하는 느낌을 다시 포착하는 것은 불가능합니다. 더 이상 포르노를 볼 필요가 없다는 기쁨은 다릅니다. 기분이 나쁘고 활력이 필요할 때 그 끔찍한 중독에 빠지지 않는 것이 얼마나 사랑스러운지 스스로에게 상기시킵니다. 많은 사람들이 그것을 인생에서 가장 위대한 사건 중 하나로 꼽습니다. 대부분의 경우 계시의 순간은 3주 후가 아니라 며칠 후에 일어납니다.

제 경우에는 마지막 하렘 방문을 마치기 전에 일어났습니다. 여기 있는 많은 독자들이 장을 다 읽기도 전에 "*더 이상 말할 필요 없어요. 저는 모든 것을 너무나 분명하게 볼 수 있어서 다시는 포르노가 필요 없을 거라는 걸 알 수 있을 거예요.*" 받은 피드백에 따르면 이런 일이 자주 일어납니다. 이상적으로는 모든 지침을 따르고 심리학을 완전히 이해한다면 즉시 일어날 겁니다.

눈에 띄는 신체적 금단 증상이 사라지는 데는 약 5일이 걸리고, 전 사용자가 완전히 벗어나는 데는 약 3주가 걸린다고 하지만, 이런 지침은 두 가지 문제를 일으킬 수 있습니다. 첫 번째는 사람들의 마음에 5일에서 3주 동안 고통을 겪어야 한다는 생각이 자리 잡는 것입니다. 두 번째는 전 사용자가 "*5일이나 3주 동안 살아남을 수 있다면 그 기간이 끝날 때 실제로 활력을 얻을 수 있을 거야.*"라고 생각하는 경향이 있다는 것입니다.

하지만, 그들은 즐거운 5일이나 3주를 보낸 다음, 중독과는 아무런 관련이 없지만 우리 삶의 다른 요인으로 인해 발생하는 모든 사람을 강타하는 재앙적인 날이 뒤따를 수 있습니다. 그러면 계시의 순간을 기다리는 전 사용자는 대신 우울증을 겪습니다. 자신감을 파괴할 수 있습니다. 마찬가지로, 지침이 없다면 전 사용자는 아무 일도 일어나지 않기를 기다리며 남은 인생을 보낼 수 있습니다. 이것이 의지력 방법을 사용하는 것을 중단한 대부분의 사람들에게 일어나는 일입니다.

사람들은 종종 5일과 3주의 의미에 대해 묻습니다. 그것은 그저 갑자기 그려진 기간일까요? 아니요, 확실한 날짜는 아니지만 수년에 걸친 피드백의 축적을 반영합니다. 중단한 지 약 5일이 되면 전 사용자는 중독을 마음의 주된 관심사로 삼지 않게 됩니다. 대부분의 전 사용자는 이 기간 동안 계시를 경험하는데, 일반적으로 한때 대처할 수 없었거나 하렘 방문 없이는 즐겁지 않았던 스트레스가 많은 상황이나 사회적 상황에서 그렇습니다. 당신은 그것을 즐기거나 대처하고 있을 뿐만 아니라 포르노에 대한 생각이 전혀 떠오르지 않았다는 것을 갑자기 깨닫습니다. 그 지점부터는 보통 순조롭게 진행됩니다. 그때가 당신이 자유롭다는 것을 알게 되는 때입니다.

*의지력 방법*을 사용하여 중단하려는 많은 사람들의 경험과 제 경험에 따르면, 중단하려는 대부분의 진지한 시도가 실패하는 시기는 대략 3주입니다. 일반적으로 일어나는 일은 약 3주 후에 포르노를 보고 싶은 욕구를 잃었다는 것을 느낀다는 것입니다. 스스로에게 이를 증명해야 하므로 브라우저에 접속하여 하렘을 방문합니다. 이상한 느낌이 들지만, 그것을 걷어차 버렸다는 것을 증명합니다. 하지만 그 과정에서 신선한 도파민 러시 덕분에 DeltaFosB 워터 슬라이드에 기름을 바르게 되는데, 이는 지난 3주 동안 몸이 갈구했던 것입니다. 행위를 마치자마자 도파민이 몸에서 빠져나가기 시작합니다. 작은 목소리가 다시 들립니다. "*아직 끊지 않았어, 또 끊고 싶어.*"

다시 끊기지 않으려고 바로 뒤로 물러나지 않고, 안전한 기간을 보내게 합니다. 다음에 유혹을 받을 때 "*음, 다시 끊지 않았으니까, 또 끊는 건 해가 없어."*라고 스스로에게 말할 수 있습니다. 당신은 이미 미끄러운 경사로를 내려가고 있습니다. 문제의 핵심은 계시의 순간을 기다리는 것이 아니라 브라우저를 닫으면 끝났다는 것을 깨닫는 것입니다. 당신은 당신의 작은 괴물에게 산소 공급을 차단했습니다. 지구상의 어떤 힘도 당신이 자유로워지는 것을 막을 수 없습니다. *그것에 대해 침울해하거나 계시를 기다리지 않는 한*. 가서 삶을 즐기세요. 처음부터 대처하세요. 그 순간은 곧 올 것입니다.