# 마지막 방문

타이밍을 정했으니, 이제 마지막으로 하렘을 방문할 준비가 되었습니다. 방문하기 전에 두 가지 필수 사항을 확인하세요.

1. 성공할 자신이 있나요?

2. 암울하거나 뭔가 놀라운 것을 성취할 수 있다는 설렘이 있나요?

의심이 들면 먼저 책을 다시 읽어보세요. 포르노 함정에 빠지기로 결정한 적이 없다는 것을 기억하세요. 하지만 함정은 평생 당신을 노예로 만들기 위해 고안된 것입니다. 탈출하려면 멈추고 마지막 방문을 하겠다는 긍정적인 결정을 내려야 합니다.

지금까지 이 책을 읽은 유일한 이유는 탈출하고 싶어서라는 것을 기억하세요. 그러니 지금 긍정적인 결정을 내리고, 개인 브라우저 창을 닫을 때, 쉽든 어렵든, 다시는 하렘을 방문하지 않겠다고 엄숙하게 맹세하세요. 아마도 여러분은 과거에 이 서약을 여러 번 했지만 여전히 실패하고 있거나 끔찍한 트라우마를 겪어야 할까봐 걱정하고 있을 것입니다. 두려워하지 마십시오. 일어날 수 있는 최악의 일은 실패하는 것이므로 잃을 것이 ***전혀*** 없고 얻을 것이 많습니다.

하지만 실패에 대해 생각하는 것조차 멈추십시오. 아름다운 진실은 포기하기가 엄청나게 쉬울 뿐만 아니라 실제로 그 과정을 즐길 수 있다는 것입니다. 이번에는 EasyPeasy를 사용할 것입니다! 해야 할 일은 곧 주어질 간단한 지침을 따르는 것뿐입니다.

1. 지금 엄숙한 서약을 하고 그것을 의미하십시오.

2. 좋아하는 튜브 사이트의 사진과 클립을 의식적으로 탐색하고 사이트 관리자, 배우, 심지어 아마추어가 상품의 충격, 참신함, 초자연적 특성을 확대하려는 필사적인 시도를 살펴보고 즐거움이 어디에 있는지 자문하십시오.

3. 마침내 브라우저를 닫을 때는 "*다시는 온라인 하렘을 방문하지 말아야지*" 또는 "*다른 하렘을 방문할 수 없어*"라는 느낌으로 닫지 말고 "*좋지 않아? 자유로워! 더 이상 포르노의 노예가 아니야!"와 같은 자유로움을 느끼면서 닫으세요. 저는 인생에서 이런 더러운 사이트를 다시 방문할 필요가 없습니다.*"

4. 며칠 동안 뱃속에 작은 포르노 방해자가 있을 것이라는 점을 알아두십시오. 세션을 원하는 느낌만 알 ​​수 있습니다. 이 작은 포르노 괴물은 도파민에 대한 약간의 신체적 갈망이라고 불립니다. 엄밀히 말해서 이것은 잘못된 것이며, 그 이유를 이해하는 것이 중요합니다. 그 작은 괴물이 죽는 데 최대 3주가 걸리기 때문에 전 사용자는 작은 괴물이 마지막 온라인 하렘 방문 후에도 계속 갈망할 것이라고 믿고, 따라서 이 기간 동안 유혹에 저항하기 위해 의지력을 사용해야 합니다. 사실이 아닙니다. 신체는 포르노에서 유발되는 도파민을 갈망하지 않습니다. 오직 뇌만이 갈망합니다.

다음 며칠 동안 엿보고 싶은 느낌이 든다면 뇌는 간단한 선택을 할 수 있습니다. 뇌는 그 느낌을 실제로 무엇인지 해석할 수 있습니다. 즉, 온라인 포르노 사이트를 처음 방문했을 때 시작된 공허하고 불안한 느낌이며, 그 다음에는 각각 "와!"하고 중얼거립니다. "나는 비사용자입니다!"**

또는 포르노에 대한 갈망을 느끼고 남은 인생을 고통받을 수도 있습니다. 잠깐 생각해보세요. 그게 엄청나게 어리석은 일이 아닐까요? "*다시는 포르노를 보고 싶지 않아요*"라고 말한 다음 남은 인생을 "*방문하고 싶어요*"라고 말하는 건요? 그게 의지력 방법을 사용하는 사람들이 하는 일이고, 그들이 그렇게 비참하게 느끼는 것도 당연합니다. 남은 인생을 절실하게 자신이 절대 가질 수 없기를 바라는 무언가를 위해 절망적으로 우울하게 보냅니다. 성공하는 사람이 매우 적고 성공하는 사람 중 일부는 결코 완전히 자유로울 수 없다고 느끼는 것도 당연합니다.

> *'이 정신적 그림을 마음속에 선명하게 그려보세요. 외부 자극이 당신을 방해하는 힘을 극복하는 데 매우 도움이 될 수 있기 때문입니다. 조용히 앉아 전화가 울리도록 내버려두고, 신호를 무시하고, 전화의 명령에 흔들리지 않는 모습을 그려보세요. 당신은 그것을 알고 있지만 더 이상 신경 쓰지 않고 따르지 않습니다. 또한 외부 신호 자체가 당신에게 아무런 힘이 없다는 사실을 마음속으로 선명하게 그려보세요. 당신을 움직일 힘이 없습니다. 과거에 당신은 순전히 습관적으로 그것에 복종하고, 반응했습니다. 원한다면, 반응하지 않는 새로운 습관을 형성할 수 있습니다.*
>
> *‘또한, 반응하지 않는 것은 무언가를 하거나, 노력하거나, 저항하거나, 싸우는 것이 아니라 아무것도 하지 않는 것입니다. 하는 일에서 이완하는 것입니다. 당신은 그저 이완하고, 신호를 무시하고, 그 소환을 무시합니다. 전화벨은 당신이 습관적으로 통제하고 지금은 그 습관을 매우 의도적으로 바꾸기로 선택할 수 있는 모든 외부 자극에 대한 상징적 비유입니다.*'
>
> --- 맥스웰 몰츠, *새로운 사이코 사이버네틱스* 12장.

의심하고 기다리는 것만이 그만두기 어렵게 만듭니다. ***그러니 결코 자신의 결정을 의심하지 마세요***. 당신은 그것이 올바른 결정이라는 것을 알고 있기 때문입니다. 의심하기 시작하면 이길 수 없는 상황에 처하게 됩니다. 방문을 갈구하지만 방문할 수 없는 비참한 상황입니다. 어떤 시스템을 사용하든 포르노를 끊을 때 무엇을 달성하려고 합니까? 다시는 보지 않으려고? 아니요! 많은 전 사용자가 그렇게 하지만 남은 인생을 박탈당한 기분으로 보냅니다.

사용자와 비사용자의 차이점은 무엇입니까? 비사용자는 포르노를 볼 필요도 없고 볼 의욕도 없으며, 갈망이 없고 보지 않기 위해 의지력을 행사할 필요가 없습니다. 그것이 당신이 달성하려고 하는 것이고, 그렇게 하는 것은 전적으로 당신의 힘 안에 있습니다. 포르노에 대한 갈망을 멈추거나 비사용자가 될 때까지 기다릴 필요가 없습니다. 마지막 브라우저 창을 닫고 도파민 공급을 차단하는 순간 완료됩니다. **당신은 이미 행복한 비사용자입니다!**

다음과 같은 경우 행복한 비사용자로 남을 것입니다.

1.  당신은 결코 당신의 결정을 의심하지 않습니다.

2.  당신은 비사용자가 되는 것을 기다리지 않습니다. 그렇게 한다면, 당신은 그저 아무 일도 일어나지 않기를 기다리며 공포증을 만들 것입니다.

3.  당신은 포르노에 대해 생각하지 않으려고 *하지* 않거나 '계시의 순간'이 오기를 기다리며 공포증을 만들지 않습니다.

4.  당신은 대체물을 사용하지 않습니다.

5.  당신은 다른 모든 사용자를 있는 그대로 보고 부러워하기보다는 그들을 불쌍히 여깁니다.

좋은 날이든 나쁜 날이든, 그만두었다고 해서 삶을 바꾸지 마세요. 바꾸면, 필요 없을 때 진정한 희생을 하는 셈이 됩니다. 기억하세요, 삶을 ​​포기한 게 아닙니다. 아무것도 포기한 게 아닙니다. 오히려 끔찍한 질병에서 스스로를 치료하고 교활한 감옥에서 탈출한 겁니다. 시간이 흐르고 신체적, 정신적으로 건강이 좋아지면, 중독자였을 때보다 기분이 더 좋아지고 기분이 나쁠 때가 덜 나빠 보일 겁니다. 앞으로 며칠 동안이나 앞으로의 인생 내내 포르노에 대해 생각할 때마다 이렇게 생각하세요.

***“와! "저는 비사용자입니다!"***

## 마지막 경고

어떤 사용자도 중독되기 전으로 돌아갈 기회가 주어지고 지금의 지식을 가지고 있다면, 중독되기 전으로 돌아가려고 하지 않을 것입니다. 수만 명의 사람들이 수년간 중독에서 벗어나는 데 성공했지만, 다시 한번 중독되고 맙니다. 이 책이 중독에서 벗어나는 것을 비교적 쉽게 찾는 데 도움이 될 것이라고 믿습니다. 하지만 쉽게 끊을 수 있는 사용자는 다시 시작하는 것도 마찬가지로 쉽다는 점을 경고합니다. **이 함정에 빠지지 마십시오.**

얼마나 오랫동안 끊었든, 다시 중독되지 않을 것이라고 얼마나 확신하든, 어떤 이유로든 포르노를 보지 않는 것을 평생의 규칙으로 삼으십시오. 미디어의 암시와 풍자에 저항하고, 포르노와 강박적 자위 행위가 많은 남성과 점점 더 많은 여성의 관계와 개인적 웰빙 감각을 파괴한다는 사실을 모른 채 포르노를 주류로 끌어들여 '개방성'이라는 이미지를 어떻게 밀어붙이고 있는지 기억하십시오.

그 첫 번째 엿보기 또는 방문은 당신에게 아무런 도움이 되지 않습니다. 당신은 해소할 금단 증상이 없을 것이고, 그것은 당신을 끔찍하게 만들 것입니다. 그것은 당신의 마음과 뇌에 도파민 러시의 즐거움을 심어주고, 당신의 마음 뒤편에서 작은 목소리가 당신에게 다른 것을 원한다고 말할 것입니다. 그러면 당신은 잠시 비참하게 지내거나, 다시 모든 더러운 사슬을 시작하는 선택을 하게 됩니다.
