# Metoda e lehtë

Objektivi i këtij libri është t'ju drejtojë në një kornizë të re mendore. Ndryshe nga metoda e zakonshme e ndalimit – ku filloni me ndjenjën e ngjitjes në malin Everest dhe kaloni javët e ardhshme me mall dhe duke u ndjerë i privuar – filloni menjëherë me një ndjenjë gëzimi, sikur të kuroheni nga një sëmundje e tmerrshme. Që atëherë e tutje, sa më tej të shkoni në jetë, aq më shumë do ta shikoni këtë periudhë kohore dhe do të pyesni veten se si keni përdorur ndonjëherë ndonjë pornografi në radhë të parë. Ju do t'i shikoni përdoruesit e tjerë të pornografisë me keqardhje, në krahasim me zili.

Me kusht që të mos jeni dikush që nuk është bërë kurrë i varur (duke lexuar për të dashurin tuaj) ose që e keni lënë (jeni në ditët e agjërimit të një "dietë pornografike"), është thelbësore të vazhdoni ta përdorni derisa ta keni përfunduar plotësisht librin. Kjo mund të duket se është një kontradiktë dhe ky udhëzim për të vazhduar masturbimin ndaj pornografisë shkakton më shumë kundërshtime se çdo tjetër, por ndërsa lexoni më tej dëshira juaj për të përdorur pornografi gradualisht do të reduktohet. **Merreni seriozisht këtë udhëzim: Përpjekja për ta lënë herët nuk do t'ju sjellë dobi.**

Shumë nuk e mbarojnë librin sepse mendojnë se duhet të heqin dorë nga diçka, madje disa lexojnë qëllimisht vetëm një rresht në ditë për të shtyrë ngjarjen e keqe. Shikoje në këtë mënyrë, çfarë ke për të humbur? Nëse nuk ndaleni në fund të librit, nuk jeni më keq se tani. Është me përkufizim një bast i Paskalit, një bast ku nuk keni asgjë për të humbur dhe shanse të larta për fitime të mëdha.

Rastësisht, nëse nuk keni parë pornografi për disa ditë ose javë, por nuk jeni i sigurt nëse jeni përdorues pornografie, ish-përdorues ose jo përdorues, atëherë mos përdorni pornografi për të masturbuar gjatë leximit. Në fakt, ju jeni tashmë një jo-përdorues, por ne duhet ta lëmë trurin tuaj të arrijë trupin tuaj. Deri në fund të librit, do të jeni një jo-përdorues i lumtur. EasyPeasy është krejtësisht e kundërta e metodës normale, ku renditen disavantazhet e konsiderueshme të pornografisë dhe thonë:
*"Nëse mund të kaloj mjaftueshëm pa pornografi, më në fund dëshira do të largohet dhe unë mund të shijoj përsëri jetën, pa skllavërinë."*
Kjo është mënyra logjike për ta bërë këtë, me mijëra që ndalojnë çdo ditë duke përdorur këtë metodë. Sidoqoftë, është shumë e vështirë të kesh sukses për arsyet e mëposhtme:

**Ndalimi i PMO-së nuk është problemi i vërtetë.**
Sa herë që përfundoni seancën tuaj, e keni ndaluar përdorimin e tij. Ju mund të keni arsye të fuqishme në ditën e parë të dietës pornografike një herë në katër për të thënë *"Nuk dua të përdor pornografi, madje as të masturboj më."* Të gjithë përdoruesit e bëjnë këtë, dhe arsyet e tyre janë më të fuqishme se ju mund të imagjinoni. Problemi i vërtetë është dita e dytë, e dhjetë ose e dhjetë mijë, ku në një moment të dobët do të kesh 'vetëm një shikim', do të duash një tjetër dhe papritmas do të jesh përsëri një i varur.

**Ndërgjegjësimi për rreziqet shëndetësore gjeneron më shumë frikë, duke e bërë më të vështirë ndalimin.**
Tregojini një përdoruesi se po shkatërron fuqinë e tij dhe gjëja e parë që ata do të bëjnë është të kërkojnë diçka për të rritur dopaminën e tyre: një cigare, alkool, apo edhe të ndezin shfletuesin për të kërkuar pornografi.

**Të gjitha arsyet për të ndaluar në fakt e bëjnë më të vështirë.**
Kjo është për shkak të dy arsyeve. Së pari, ne vazhdimisht jemi të detyruar të heqim dorë nga 'miku ynë i vogël' ose nga ndonjë mbështetje, ves ose kënaqësi (në çdo mënyrë që përdoruesi e percepton atë). Së dyti, ata krijojnë një "të verbër". Ne nuk masturbohemi për arsyet që duhet të ndalojmë. Pyetja e vërtetë është, pse duam apo kemi nevojë ta bëjmë atë?

Me EasyPeasy, ne (fillimisht) harrojmë arsyet që do të donim të ndalonim, përballemi me problemin e pornografisë dhe i bëjmë vetes pyetjet e mëposhtme:

1. Çfarë po bën pornografia për mua?

2. A po e shijoj vërtet?

3. A duhet vërtet të kaloj jetën duke sabotuar mendjen dhe trupin tim?

E vërteta e bukur është se *të gjitha pornografitë* nuk bëjnë absolutisht asgjë për ju. Më lejoni ta bëj mjaft të qartë, nuk është se disavantazhet e të qenit përdorues peshojnë më shumë se avantazhet, është se ka ***zero*** avantazhe për të parë pornografi.

Shumica e përdoruesve e shohin të nevojshme të arsyetojnë pse përdorin pornografi, por arsyet që ata nxjerrin janë të gjitha gabime dhe iluzione.

Së pari, ne do t'i heqim këto gabime dhe iluzione. Në fakt, së shpejti do të kuptoni se nuk ka asgjë për të hequr dorë. Jo vetëm kaq, por ka përfitime të mrekullueshme, pozitive nga të qenit jo-PMOer, me mirëqenie dhe lumturi vetëm dy nga këto përfitime. Sapo të hiqen iluzionet se jeta nuk do të jetë kurrë aq e këndshme pa pornografi - duke kuptuar se jo vetëm jeta është po aq e këndshme pa të, por pafundësisht më shumë - dhe sapo ndjenjat e të qenit të privuar ose të humbur të zhduken, ne do të kthehemi për të rishqyrtuar rritjen e mirëqenies dhe lumturisë - dhe dhjetëra arsye të tjera për të lënë pornografinë. Këto realizime do të bëhen ndihmesa pozitive shtesë për t'ju ndihmuar të arrini atë që dëshironi vërtet: të shijoni jetën tuaj të lirë nga skllavëria e varësisë nga pornografia!
