# Pse është e vështirë të ndalosh?

Të gjithë përdoruesit mendojnë se diçka e keqe i ka pushtuar. Në ditët e para, është një pyetje e thjeshtë e *“Do të ndaloj, jo sot”*. Përfundimisht ne përparojmë duke besuar se nuk kemi vullnet të mjaftueshëm për të ndaluar, ose se ka diçka të natyrshme në pornografi që duhet të kemi për të shijuar jetën. Varësia ndaj pornografisë është si të dalim nga një gropë e rrëshqitshme: ndërsa afrohemi majës, shohim rrezet e diellit, por e gjejmë veten duke u rrëshqitur poshtë ndërsa humori ynë bie. Përfundimisht ne hapim shfletuesin tonë dhe ndërsa masturbohemi, ndihemi të tmerrshëm.

Pyetni një përdorues, *"Nëse do të mund të ktheheshit në kohën para se të tërhiqeshit, me njohuritë që keni tani, a do të kishit filluar të përdorni pornografi?"*

Përgjigja do të ishte "ASNJË MENYRË!".

Pyetni përdoruesin e konfirmuar, dikë që mbron pornografinë në internet dhe nuk beson se shkakton dëmtim të trurit ose ulje të receptorëve të dopaminës: *“A i inkurajoni fëmijët tuaj të përdorin pornografi?”*

*“ASNJË MENYRË!”* është sërish përgjigjja.

Pornografia është një enigmë e jashtëzakonshme. Siç u tha më parë, problemi nuk është të shpjegosh pse është e lehtë të ndalosh, por të shpjegosh pse është e vështirë të ndalosh. Problemi i vërtetë është të shpjegojë pse dikush e bën atë *pasi* të marrë njohuri mbi dëmtimet neurologjike. Një pjesë e arsyes që ne fillojmë është për shkak të dhjetëra milionëve të tjerë që tashmë janë në të, megjithatë të gjithë këta njerëz do të donin të mos kishin filluar që në fillim, duke na thënë se është si të jetosh jetën me shpejtësinë e dytë. Ne nuk besojmë se ata nuk po e shijojnë atë, pasi ne e lidhim atë me lirinë ose të qenit 'të edukuar për seksin' dhe punojmë shumë për t'u lidhur vetë. Ne pastaj kalojmë pjesën tjetër të jetës duke u thënë të tjerëve që të mos e bëjnë këtë dhe duke u përpjekur ta heqim vetë zakonin, duke menduar shpesh se jemi unikë në këtë.

Ne gjithashtu kalojmë një pjesë të konsiderueshme të kohës duke u ndjerë të pashpresë dhe të mjerë. 'Edukimi' i vetes me supernormalen na bën të preferojmë dhe të dëshirojmë për këto imazhe të ftohta, edhe kur ato të ngrohta dhe reale janë të disponueshme. Nëpërmjet rritjes dhe rënies së vazhdueshme të dopaminës të shkaktuar nga PMO, ne e dënojmë veten me një jetë izolimi, nervozizmi, zemërimi, stresi, lodhjeje dhe mosfunksionimi seksual. Duke përdorur pornografinë, me mungesën e pjesëve më të mira të seksit dhe lidhjes, ne përfundojmë të ndihemi të mjerë dhe fajtorë.

Në fakt, leximi i aftësive të varësisë dhe shkatërrimit të pornografisë në internet këtu dhe në faqe të tjera na bën edhe më nervozë dhe të pashpresë! Çfarë lloj hobi është ai që kur e bën atë, do të doje që të mos ishe, dhe kur nuk je, e dëshiron atë? Përdoruesit e përbuzin veten sa herë që lexojnë për hipofrontalitetin dhe desensibilizimin, sa herë që përdorin pas shpinës së partnerit të tyre të besuar dhe sa herë që nuk mund ta bëjnë veten të ushtrohen pas një seance ditore. Një qenie njerëzore ndryshe inteligjente dhe racionale i kalon të gjitha ditët në përbuzje. Por më e keqja nga të gjitha, çfarë përfitojnë përdoruesit nga detyrimi për të duruar jetën me këto hije të tmerrshme të zeza në fund të mendjes së tyre? **Absulutisht asgje!**

Ju mund të jeni duke menduar *"Kjo është gjithçka shumë mirë, unë e di këtë, por sapo të jeni të lidhur me këto gjëra është shumë e vështirë të ndaleni."* Por pse është kaq e vështirë? Disa thonë se kjo është për shkak të simptomave të fuqishme të tërheqjes, por siç do të mësoni së shpejti, simptomat aktuale të tërheqjes janë në fakt shumë të lehta. Dhe kjo është e dukshme kur mendon se shumë PMOer kanë jetuar dhe kanë vdekur pa e kuptuar se ishin të varur.

Disa thonë se pornografia në internet është falas dhe për këtë arsye njerëzimi duhet të pretendojë këtë bonancë biologjike, por kjo është e pavërtetë - është e varur dhe vepron si çdo drogë. Pyetni një përdorues që betohet se kënaqet vetëm me 'erotikën' si revistat Playboy nëse e kanë kaluar ndonjëherë kufirin e 'pornografisë së pasigurt'. Dhe nëse janë plotësisht të sinqertë, ata do të rrëfenin për herët kur e kishin racionalizuar kalimin e kësaj kufiri, në vend që të mos përdornin asgjë.

As kënaqësia nuk ka të bëjë me të. Mua më pëlqen karkaleca, por kurrë nuk arrita në pikën që të më duhej të pija karavidhe çdo ditë. Me gjërat e tjera në jetë, ne i shijojmë ato ndërkohë që i bëjmë, por nuk rrimë duke u ndjerë të privuar kur nuk jemi.

Disa thonë: 
*“Është edukative!”* Pra, si ju ka bërë të rriteni si person?
*“Është kënaqësi seksuale!”* Pra, pse të izolon dhe të bën të ndjesh dëshira të pangopura?
*“Është një ndjenjë çlirimi!”* Çlirim nga streset e jetës reale? Ok, për një orë, para se gjithçka të të kthehet përsëri? Dhe çfarë stresesh ka zgjidhur?
*“Më ndihmon të fle”* Pra, pse të tjerët mund të flenë mirë pa të? Ka [shume](https://www.sleepfoundation.org/insomnia/treatment/meditation) demonstruar shkencërisht [metoda](https://www.sleepfoundation.org/insomnia/treatment/cognitive-behavioral-therapy-insomnia) të [rregullosh](https://www.amazon.com/Uvex-Blocking-Computer-SCT-Orange-S1933X/dp/B000USRG90) gjumin, dhe [më shumë](https://www.menshealth.com.au/what-is-the-military-method-the-technique-that-promises-to-help-you-sleep-in-2-minutes).

Shumë besojnë se pornografia lehtëson mërzinë, por mërzia është një kornizë e mendjes. Pornografia do t'ju mësojë në kërkimin e risive në një kohë të shkurtër, duke ju bërë të mërziteni gjithnjë e më shumë derisa të merrni pjesë më në fund në atë ndjekje të patës së egër vetëm për klipin e duhur, duke u bërë gjithnjë e më i prirur për të kërkuar çdo gjë që ngjall risi, emocione të forta dhe përfundimisht, vlerë skandaloze e shokuar.

Disa thonë se e bëjnë këtë vetëm sepse e bëjnë miqtë e tyre dhe të gjithë ata që njohin. Nëse po, lutuni që miqtë tuaj të mos fillojnë të presin kokën për të kuruar një dhimbje koke! Shumica e përdoruesve që mendojnë për të, arrijnë në përfundimin se është thjesht një zakon. Ky nuk është në të vërtetë një shpjegim, por duke i zbritur të gjitha shpjegimet e zakonshme, racionale, duket se është i vetmi justifikim i mbetur. Fatkeqësisht, është po aq e palogjikshme. Çdo ditë të jetës sonë ne ndryshojmë zakone, disa prej tyre shumë të këndshme. Na është larë truri për të besuar se PMO është një zakon dhe se zakonet janë të vështira për t'u thyer.

A janë zakonet e vështira për t'u thyer? Drejtuesit e automjeteve në SHBA e kanë zakon të ngasin makinën në anën e djathtë të rrugës, por kur udhëtojnë jashtë shtetit, ata e thyejnë zakonin me pothuajse asnjë përkeqësim. Dhe kur merrni një punë të re, merrni një rutinë tjetër, kështu që zakonet tuaja ndryshojnë. Këto mund të kërkojnë pak për t'u mësuar, por nuk është asgjë si të prishësh një luftë të përjetshme me varësinë ndaj pornografisë. Ne krijojmë dhe thyejmë zakone çdo ditë të jetës sonë, kështu që pse e kemi të vështirë të heqim dorë nga një zakon që na bën të ndihemi të privuar kur nuk e kemi atë, fajtor kur e kemi, një zakon që do të donim ta hiqnim gjithsesi, kur gjithçka që duhet të bëjmë është *të mos e bëjmë më?*

Përgjigja është se pornografia nuk është zakon, *është varësi!* Kjo është arsyeja pse duket se është kaq e vështirë të "heqësh dorë". Shumica e përdoruesve nuk e kuptojnë varësinë dhe besojnë se ata marrin një kënaqësi të vërtetë nga pornografia. Ata besojnë se po bëjnë një sakrificë të vërtetë nëse heqin dorë.

E vërteta e bukur është se sapo të kuptoni natyrën e vërtetë të varësisë ndaj pornografisë dhe arsyet pse e përdorni atë, do të ndaloni ta bëni atë, ashtu si kjo. Brenda tre javësh, misteri i vetëm do të jetë pse e pate të nevojshme të përdorni pornografi për aq kohë dhe pse nuk mund t'i bindni përdoruesit e tjerë *sa bukur është të mos jesh PMOer!*

## Kurthi i keq

Pornografia në internet është një kurth delikate dhe e keqe që njeriu dhe natyra e kanë kombinuar për të krijuar. Madje disa prej nesh janë paralajmëruar për rreziqet, por nuk mund ta besojmë se si nuk po e shijojmë atë. Por çfarë na fut në të në radhë të parë? Zakonisht janë mostra falas nga profesionistë që ndajnë. Kështu hapet kurthi. Në vend të kësaj, nëse do të na paralajmëronte për rreziqet e asaj që po futeshim para se të hidhnim shikimin e parë, atëherë zilet e alarmit do të bërtisnin.

Por këto zile nuk bërtasin. Ndoshta është natyra tronditëse e shumë klipeve që i siguron mendjet tona të reja se nuk do të ndikojmë kurrë, duke menduar se nuk na pëlqejnë ato, ne mund të ndalojmë sa herë të duam. Ose ndoshta pafajësia në dukje e materialit të butë nuk shkakton ndonjë zile alarmi, njësoj si një thurje e aftë që një mashtrues mund të luajë për të drejtuar mendjen tonë. Si qenie njerëzore inteligjente, atëherë do të kuptonim pse gjysma e popullsisë së rritur ishte sistematikisht e varur nga diçka që ul potencialin tonë për të kryer atë që po shohim. Kurioziteti na afron më pranë pragut të varësisë, por ne nuk guxojmë të klikojmë mbi fotografitë që po i hedhim një sy, nga frika se do të na sëmurnin ose do të na dërgonin në një shteg të rrezikshëm dhe imoral. Dhe nëse kemi klikuar aksidentalisht në një, shpesh dëshira jonë e vetme është të largohemi nga faqja sa më shpejt të jetë e mundur, ndërsa në të njëjtën kohë jemi dëshpërimisht kurioz edhe më shumë.

Pasi ka nisur ky proces, ne jemi të bllokuar. Që tani e tutje ne kalojmë pjesën tjetër të jetës duke u përpjekur të kuptojmë pse e bëjmë këtë, duke u thënë fëmijëve tanë që të mos fillojnë dhe në raste të çuditshme duke u përpjekur të shpëtojmë nga vetja. Kurthi është krijuar në mënyrë që ne të përpiqemi dhe të ndalojmë vetëm për shkak të një 'incidenti', qoftë performanca seksuale, humbja e një karriere ose marrëdhënieje, mungesa e dëshirës ose thjesht ndjenja si lebroz. Sapo ndalojmë, kemi më shumë stres për shkak të dhembjeve të tërheqjes, dhe me metodën në të cilën u mbështetëm për ta hequr atë stres, tani nuk është e disponueshme.

Vendosmëria jonë për të hequr dorë rezulton të jetë e lëkundur. Pas disa ditësh torturash, ne e bindim veten se kemi zgjedhur kohën e gabuar për ta lënë, duke vendosur se do të presim periudha pa stres, gjë që me të mbërritur na heq arsyen për të ndaluar fillimisht. Sigurisht, ajo periudhë nuk do të arrijë kurrë plotësisht, dhe ne fillojmë të besojmë se jeta jonë ka tendencë të bëhet gjithnjë e më stresuese. Ne e lëmë mbrojtjen e prindërve tanë dhe streset e punës, bërjes së shtëpisë, hipotekave, blerjes së strehës dhe rritjes së fëmijëve për të mbushur jetën tonë. Por ky është një iluzion. Pjesët më stresuese të jetës së çdo krijese janë në fakt fëmijëria e hershme dhe adoleshenca.

Ne priremi të ngatërrojmë përgjegjësinë dhe stresin. Jeta e një përdoruesi – si ajo e një të droguari – bëhet automatikisht më stresuese sepse pornografia nuk na relakson ose nuk na lehtëson stresin, siç përpiqen disa të na bëjnë të besojmë. Është vetëm e kundërta, duke na bërë të stresohemi më shumë ndërsa vazhdojmë ta përdorim, me çdo faj të ngarkuar vonë natën që pason grumbullon më shumë kashtë mbi shpinën e devesë. Edhe përdoruesit që e heqin këtë zakon - siç bëjnë shumica një ose më shumë herë gjatë jetës së tyre - mund të bëjnë jetë krejtësisht të lumtur, por papritmas bëhen sërish të lidhur. Duke u endur në labirintin pornografik, mendjet tona bëhen të mjegullta dhe kalojmë pjesën tjetër të jetës duke u përpjekur të arratisemi. Shumë ia dalin, vetëm për të rënë në grackën e keqe në një datë të mëvonshme.

Zgjidhja e problemit të varësisë ndaj pornografisë është një enigmë. Është komplekse dhe e vështirë. Por sapo të shihni përgjigjen, është e thjeshtë dhe argëtuese, dhe pyesni veten pse nuk e keni menduar këtë! EasyPeasy përmban zgjidhjen për këtë enigmë, duke ju nxjerrë nga labirinti, duke mos u endur më. **Gjithçka që duhet të bëni është të ndiqni çdo udhëzim sipas shkronjës**. Megjithatë, nëse bëni **një kthesë të gabuar duke kërcyer kapitujt**, ose **duke shfletuar librin me shpejtësi rrufeje** pa bërë me kujdes përpjekje të qëllimshme kur lexoni herën e parë, atëherë pjesa tjetër e udhëzimeve janë të kota.

Çdokush mund ta ketë të lehtë të ndalojë, por së pari duhet të vërtetojmë faktet. Jo, jo fakte të krijuara për t'ju frikësuar, tashmë ka më shumë se informacion të mjaftueshëm atje. Nëse kjo do të të ndalonte, do të kishe ndaluar tashmë. Por pse e kemi të vështirë të ndalemi? Përgjigjja për këtë kërkon që ne të dimë arsyen e vërtetë që ne po përdorim ende pornografi, duke u zbërthyer në dy faktorë. Ata janë:

-   Natyra dhe pornografia në internet.

-   Shpëlarje truri shoqëror.

Përdoruesit e pornos janë qenie njerëzore inteligjente dhe racionale. Ata e dinë se po marrin rreziqe të mëdha në të ardhmen, kështu që shpenzojnë shumë kohë duke racionalizuar "zakonin" e tyre. Por përdoruesit e pornografisë në zemrat e tyre e dinë se janë budallenj, duke e ditur se nuk kishin nevojë të përdornin pornografi përpara se të fiksoheshin. Shumica e kujtojnë se "shikimi" i tyre i parë ishte një përzierje e neverisë dhe kuriozitetit të ri. Më pas ata specializohen në gjetjen, filtrimin dhe shënimin e faqeve, duke punuar shumë për t'u fiksuar.

Më e bezdisshme është se ka kuptimin që personat që nuk janë të varur - shumica e grave, djemve të moshuar dhe njerëzve që jetojnë në vende ku pornografia me internet me shpejtësi të lartë nuk është e disponueshme - nuk po humbasin asgjë dhe e shohin situatën për të qeshur. Duke i çmontuar këta faktorë në kapitujt e ardhshëm, edhe ju do të kuptoni kurthin e keq!
