# Nga çfarë po heq dorë?

**Absolutisht asgjë!** Pornografia është e vështirë të heqësh dorë për shkak të frikës se po privohemi nga kënaqësia ose mbështetja jonë. Frika se disa situata të këndshme nuk do të jenë më kurrë të njëjta. Frika se do të mbeteni të paaftë për të përballuar situatat stresuese. Me fjalë të tjera, janë efektet e larjes së trurit që na mashtrojnë për të besuar se seksi - dhe si rrjedhojë orgazma - është një domosdoshmëri për të gjitha qeniet njerëzore. Edhe më tej, është besimi se ka diçka të natyrshme në pornografinë e internetit që na nevojitet, dhe se kur të ndalojmë së përdoruri, do ta mohojmë veten dhe do të krijojmë një boshllëk.

Bëjeni të qartë këtë në mendjen tuaj: **Pornografia nuk mbush një boshllëk, ** ***e krijon një të tillë!***

Trupat tanë janë objektet më të sofistikuara në planet. Pavarësisht nëse besoni në dizajnin inteligjent, përzgjedhjen natyrore ose një kombinim të të dyjave, trupat tanë janë mijëra herë më efektiv se njeriu! Ne nuk jemi në gjendje të krijojmë qelizën më të vogël të gjallë ose mrekullitë e shikimit, riprodhimit dhe sistemeve të ndryshme të ndërlidhura të pranishme në trupin ose trurin tonë. Nëse ky krijues ose proces do të kishte synuar që ne të trajtonim stimulin supernormal, do të na ishin pajisur me sisteme të ndryshme shpërblimi. Trupat tanë janë të pajisur me pajisje paralajmëruese të sigurta për dështimin dhe ne i injorojmë këto në rrezik.

## Nuk ka asgjë për të hequr dorë

Sapo të pastroni përbindëshin e vogël nga trupi juaj dhe larjen e trurit (përbindëshin e madh) nga mendja juaj, nuk do të dëshironi të masturboni shpesh dhe as të përdorni pornografi në internet për të. Ka shumë të njohura dhe të panjohura kur bëhet fjalë për varësinë ndaj pornografisë, më shumë në komunitetin mjekësor që nuk kanë konceptin e pyetjes ose përcaktimit e dikujt si të varur nga pornografia. Shumë simptoma të raportuara janë etiketuar gabimisht nën shkaqe të tjera. Nuk është se përdoruesit janë përgjithësisht njerëz budallenj, por thjesht janë të mjerë pa pornografi. Të kapur mes djallit dhe detit të thellë blu, duke abstenuar dhe duke qenë të mjerë sepse nuk mund të përdorin pornografi, ose të mjerë sepse janë fajtorë dhe fillojnë të përbuzin veten për shkak të saj. Kur ata marrin simptoma të tilla si dhimbja e shpinës ose mosfunksionimi seksual, mendjet e tyre janë të ndara midis pranimit të përgjegjësisë dhe shikimit nga ana tjetër.

Një tjetër analogji e duhanpirësit: të gjithë ne kemi parë duhanpirës që krijojnë justifikime për t'u larguar fshehurazi për një fryrje dinak dhe ne e shohim varësinë e vërtetë në veprim. Të varurit nuk e bëjnë këtë për kënaqësi, përkundrazi e bëjnë sepse janë të mjerë pa të.

Për shumë njerëz, përvoja e tyre e parë seksuale përfundoi në një orgazmë, kështu që ata fituan besimin se nuk mund të shijojnë seksin pa të. Për meshkujt, pornografia tregtohet si një ndihmë për seksin, ndonjëherë edhe si një edukim për besimin gjatë aktit. Kjo është e pakuptimtë, kushtëzimi i stimulit supernormal arrin vetëm ta rrëzojë atë.

Jo vetëm që nuk ka asgjë për të hequr dorë, por edhe përfitime masive pozitive. Kur përdoruesit mendojnë ta lënë, ata priren të përqendrohen te shëndeti dhe viriliteti. Këto janë arsye të vlefshme dhe të rëndësishme, por unë personalisht besoj se përfitimet më të mëdha janë psikologjike:

-   Kthimi i besimit dhe guximit tuaj.

-   Liria nga skllavëria.

-   Nuk keni më hije të zeza të tmerrshme në fund të mendjes tuaj dhe duke përbuzur veten.

## Bosh, boshllëk, zbrazëti e bukur!

Imagjinoni të keni një plagë të ftohtë në fytyrë, kështu që shkoni te farmacisti dhe ai ju jep një pomadë falas për ta provuar. E vendosni pomadën dhe ajo zhduket menjëherë. Një javë më vonë ajo rishfaqet, kështu që ju ktheheni te farmacisti dhe pyesni nëse kanë ndonjë pomadë tjetër. Farmacistja thotë *“Sigurisht; mbajeni tubin, mund t'ju duhet më vonë."*

E vendos pomadën dhe hej presto, plaga zhduket edhe një herë. Por sa herë që plaga kthehet, bëhet më e madhe dhe më e dhimbshme, me intervalin gjithnjë e më të shkurtër. Përfundimisht, plaga mbulon të gjithë fytyrën tuaj dhe është jashtëzakonisht e dhimbshme, dhe ajo kthehet çdo gjysmë ore. E dini që pomada do ta heqë përkohësisht, por jeni shumë i shqetësuar. A do të përhapet plaga përfundimisht në të gjithë trupin tuaj? A do të zhduket plotësisht intervali? Ju shkoni te mjeku juaj dhe ata nuk mund ta kurojnë, kështu që ju provoni gjëra të tjera, por asgjë nuk ju ndihmon përveç pomadës.

Deri tani ju jeni plotësisht të varur nga pomada, duke mos dalë kurrë pa u siguruar që keni një tub me vete. Nëse shkoni jashtë vendit, sigurohuni që të merrni disa tuba me vete. Përveç shqetësimeve tuaja për shëndetin tuaj, farmacisti po ju taton njëqind dollarë për tub. Nuk keni zgjidhje tjetër veçse të paguani.

Ju ndesheni me një artikull që diskuton këtë dhe zbuloni se nuk po ju ndodh vetëm juve, por shumë njerëz vuajnë nga i njëjti problem. Në fakt, komuniteti mjekësor ka zbuluar se vaji në fakt nuk e shëron plagën, dhe përkundrazi e merr atë vetëm nën sipërfaqen e lëkurës. Është pomada që shkaktoi rritjen e plagës, kështu që gjithçka që duhet të bëni për të hequr qafe plagën është të ndaloni përdorimin e pomadës dhe ajo do të zhduket në kohën e duhur.

A do të vazhdoni të përdorni pomadën? A do të duhej vullnet për të mos përdorur pomadën? Nëse nuk e besonit artikullin, mund të ketë disa ditë shqetësimi, por sapo të kuptoni se plaga po fillonte të përmirësohej, nevoja ose dëshira për të përdorur vajin do të largohej. A do të ishe i mjerë? Sigurisht që nuk do ta bënit! Keni pasur një problem të tmerrshëm që mendonit se ishte i pashërueshëm, por tani e keni gjetur zgjidhjen. Edhe nëse u desh një vit që plaga të largohej, çdo ditë ndërsa përmirësohej do të mendonit se sa e mrekullueshme ndiheshit. Kjo është magjia e lënies së pornografisë.

Dhimbja nuk është dhimbja e trupit, mungesa e epshit normal, zgjimi i flaktë, depërtimi i zbehur, koha e humbur e shpenzuar për imazhe dydimensionale, ndjenjat e shkeljes së të drejtës dhe përçmimi i njerëzve që ju kapën ose akoma më keq, përçmimi i vetvetes. Të gjitha këto janë përveç plagës.

Dhimbja na bën të mbyllim mendjen ndaj të gjitha këtyre gjërave - është ajo ndjenjë paniku e dëshirës për një rregullim. Jo-përdoruesit nuk vuajnë nga kjo ndjenjë. Gjëja më e keqe që kemi përjetuar ndonjëherë është frika, fitimi më i madh është të shpëtojmë nga ajo frikë. Është shkaktuar nga sesioni juaj i parë, i forcuar më tej dhe i shkaktuar nga secila pasardhëse.

Disa përdorues janë 'të lumtur', të verbuar nga përbindëshat e tyre të vegjël dinakë dhe kështu kalojnë të njëjtin makth, duke paraqitur argumente të rreme për të provuar dhe justifikuar marrëzinë e tyre.

*Është shumë bukur të jesh i lirë!*
