# Kursimi i kohës

Zakonisht kur përdoruesit përpiqen të ndalojnë, arsyet kryesore të dhëna janë shëndeti, feja dhe stigma e partnerit. Një pjesë e shpëlarjes së trurit të kësaj droge të tmerrshme është skllavëria e plotë e saj; njeriu ka luftuar shumë për të shfuqizuar skllavërinë në shumë pjesë të botës – megjithatë përdoruesi e kalon jetën duke vuajtur nga skllavëria e vetë-imponuar. Ata janë të pavëmendshëm për faktin se kur u lejohet të përdorin pornografi, do të dëshironin të ishin jo-përdorues. E vetmja herë që pornografia bëhet e çmuar është kur ne 'përpiqemi' të shkurtojmë ose të abstenojmë, ose kur abstenimi na detyrohet.

Nuk mund të përsëritet mjaft shpesh që shpëlarja e trurit e bën të vështirë ndalimin e pornografisë, kështu që sa më shumë ta shpërndajmë përpara se të fillojmë, aq më lehtë do ta gjeni për të arritur qëllimin tuaj. Përdoruesit e konfirmuar, të cilët nuk besojnë se pornografia ka ndonjë efekt negativ në shëndetin e tyre (disfunksioni erektil i shkaktuar nga pornografia, hipofrontaliteti, etj.) dhe që nuk kanë një tërheqje mendore, janë zakonisht më të rinj ose beqarë me një partner seksual të rastësishëm. Kështu, reagimet e brendshme humbasin për shkak të natyrës së rinisë së tyre ose janë shumë të rralla për t'u vëzhguar dhe regjistruar.

Një argument më i mirë për një përdorues më të ri është koha e shpenzuar, më tepër duke thënë "*Nuk mund ta besoj që nuk shqetësoheni për kohën që po shpenzoni.*" Në përgjithësi sytë e tyre ndriçojnë, duke u ndjerë të pafavorizuar nëse sulmohen për arsye shëndetësore ose sociale. stigmë, por në kohë...
"*Oh, mund ta përballoj. Është vetëm* x *orë në javë dhe mendoj se ia vlen, është vesi im i vetëm i kënaqësisë.*"

"*Ende nuk mund ta besoj se nuk jeni të shqetësuar. Le të supozojmë një mesatare ditore gjysmë ore që përfshin kullimin fizik të tërheqjes së dopaminës, ju po kaloni afërsisht një ditë të plotë pune çdo dy javë. Jam i sigurt që do të jeni dakord. se gjysmë ore në ditë është një vlerësim shumë konservator. A keni menduar se sa kohë do të shpenzoni në jetën tuaj? Çfarë jeni duke bërë në atë kohë? Zhvillimi i marrëdhënieve reale? Jo, ylli juaj i preferuar porno nuk ka simpati për ju, vetëm sepse keni shpenzuar kaq shumë kohë në videot e tyre - po humbisni kohë! Jo vetëm kaq, ju po e përdorni atë kohë për të prishur shëndetin tuaj fizik, duke shkatërruar nervat dhe besimin tuaj në mënyrë që të vuani një jetë skllavëria, dhimbja, melankolia dhe mërzitja. Sigurisht që kjo duhet t'ju shqetësojë, apo jo?*"

Është e qartë në këtë pikë - veçanërisht me përdoruesit më të rinj - se ata kurrë nuk e kanë konsideruar atë një varësi të përjetshme. Herë pas here, ata përpunojnë kohën që humbasin në një javë dhe kjo është mjaft alarmante. Shumë herë pas here, dhe vetëm kur mendojnë të ndalojnë, ata do të vlerësojnë atë që shpenzojnë në një vit që është e frikshme - por gjatë gjithë jetës është e paimagjinueshme. Megjithatë, për shkak se jemi në një debat, përdoruesi i konfirmuar do të thotë në mënyrë impulsive, *"Unë mund ta përballoj atë, është vetëm kaq shumë një javë"*, duke tërhequr mbi vete një rutinë të shitësit të enciklopedisë.

A do të refuzonit një ofertë pune e cila paguan pagën tuaj aktuale vjetore dhe gjithashtu ju jep një muaj pushim çdo vit? Çdo përdorues do të regjistrohej me një rrahje zemre dhe do të merrej me gjetjen e ofertave për pushime në vende ekzotike. Të kuptoni se si të kaloni një muaj të plotë pa punë do të ishte problemi më i madh për t'u zgjidhur. Në çdo diskutim me një përdorues të konfirmuar (dhe ju lutem mbani në mend se nuk është dikush si ju që planifikon të ndalojë) askush nuk më ka pranuar ndonjëherë në atë ofertë. Pse jo?

Shpesh në këtë pikë, një përdorues i konfirmuar do të thotë: "*Shiko, nuk jam vërtet i shqetësuar për aspektin e parave.*" Nëse po mendoni në këtë drejtim, pyesni veten pse nuk jeni të shqetësuar. Pse në aspekte të tjera të jetës suaj do të kaloni probleme të mëdha për të kursyer disa dollarë aty-këtu, por shpenzoni mijëra duke vrarë lumturinë tuaj dhe duke i varur shpenzimet?

Çdo vendim tjetër që merrni në jetën tuaj do të jetë rezultat i një procesi analitik të peshimit të avantazheve dhe disavantazheve për të arritur në një vendim racional. Mund të jetë vendim i gabuar, por do të jetë rezultat i zbritjes racionale. Kurdoherë që ndonjë përdorues peshon të mirat dhe të këqijat e përdorimit të pornografisë në internet, përgjigja është një duzinë herë më shumë, **"STOP TË PËRDORIMIN! JENI NJË TURI!"** Prandaj, të gjithë përdoruesit po përdorin jo sepse duan ose vendosin, por sepse nuk mund të ndalojnë. Ata ***duhet*** të përdorin pornografi, dhe kështu të lajnë trurin e tyre, duke e mbajtur kokën në rërë.

Përdoruesit e konfirmuar duhet të kenë parasysh se situata do të përkeqësohet në mënyrë eksponenciale, me më shumë studime që do të dalin dhe më shumë njerëz që flasin për efektet e këqija të pornografisë në internet. Sot, janë njerëz jo-mjekësorë që diskutojnë efektet, nesër do të jetë në listën e testeve diagnostikuese të mjekut tuaj. Kanë ikur ditët kur përdoruesi mund të fshihet pas stresit të punës në jetën e tyre seksuale; partneri juaj do të pyesë pse jeni në laptop vonë natën. Përdoruesi i mjerë - tashmë ndihet i mjerë - tani dëshiron që toka të hapet dhe t'i gëlltisë.

Gjëja e çuditshme është se megjithëse shumë njerëz do të paguanin para të mira për anëtarësimin në palestër dhe trajnerët personalë për të ndërtuar muskuj dhe për t'u dukur të skalitur (dhe shumë prej tyre në dëshpërimin e tyre imagjinar (dhe real) kthehen në trajtime të tilla si rritja e testosteronit, me anë të dyshimta dhe me efekte të rrezikshme), ka shumë njerëz në këtë grup që do të përfitonin nga ndalimi i një praktike që shkatërron sistematikisht sistemet natyrore të relaksimit të trurit të tyre.

Kjo për shkak se ata ende po mendojnë me mendjen e shpëlarë trurin e përdoruesit. Fshijeni rërën nga sytë tuaj për një moment. Pornografia në internet është një reaksion zinxhir dhe një zinxhir për jetën, dhe nëse nuk e thyeni atë zinxhir, do të mbeteni përdorues për pjesën tjetër të jetës tuaj. Llogaritni sa kohë mendoni se do të shpenzoni në pornografi për pjesën e mbetur të ekzistencës suaj. Natyrisht, shuma do të ndryshojë nga personi në person, por le të supozojmë se është një vit e gjysmë orët e punës. Imagjinoni nëse nesër do të ishte një çek nga shorti për një vit e gjysmë të pagës suaj në tapetin tuaj? Ju do të kërceni me kënaqësi, kështu që filloni të kërceni! Ju jeni gati të filloni të merrni ato përfitime!

Nëse mendoni se kjo është një mënyrë e ndërlikuar për ta parë atë, ju ende po tallni veten. Mendoni se sa kohë do të kishit kursyer nëse nuk do të hidhnit kurrë shikimin tuaj të parë që në fillim.

Së shpejti, ju do të merrni vendimin për të përdorur seancën tuaj përfundimtare (jo ende, ju lutemi mbani mend udhëzimet!), duke mbetur një jo-përdorues duke mos rënë përsëri në grackën. Gjithçka që duhet të bëni për të mbetur jo-përdorues është të mos përdorni pornografi dhe të shmangni 'vetëm një shikim'. Mos harroni nëse e bëni këtë, do t'ju kushtojë çfarëdo që vlerësoni se do të jetë fitimi i pagës suaj.

Nëse jeni duke mentoruar dikë për varësinë e tyre ndaj pornografisë, tregojuni që ata njohin dikë që ka refuzuar një ofertë pune që paguan pagën e tyre aktuale vjetore dhe gjithashtu u jep atyre një pushim të plotë me pagesë për një muaj. Kur pyeteni se kush është ai idiot, thuaju atyre: ***"Ti!"*** Është e vrazhdë, por ndonjëherë duhet ta kuptosh çështjen në një mënyrë më pak se të sjellshme.

