# Shëndeti

Kjo është zona ku shpërlarja e trurit është më e madhe me përdoruesit – veçanërisht të rinjtë dhe beqarët – të cilët mendojnë se janë të vetëdijshëm për rreziqet shëndetësore, por nuk janë të vetëdijshëm. Shumë e dënojnë veten duke thënë se janë të përgatitur të pranojnë pasojat. Nëse ruteri juaj i internetit do të kishte një funksion që luante një ton alarmi me një paralajmërim kur goditni një faqe pornografie duke thënë - "*Deri tani e keni shpëtuar, por nëse qëndroni edhe një minutë koka juaj do të shpërthejë." Nëse jeni në dyshim për përgjigjen, provoni të ecni deri në një shkëmb, të qëndroni në buzë me sytë mbyllur dhe të imagjinoni të zgjidhni ose të hiqni dorë nga pornografia ose të ecni lart me sy të lidhur.

Nuk ka dyshim se cila do të ishte zgjedhja juaj, por duke e zhytur kokën në rërë dhe duke shpresuar se do të zgjoheni një mëngjes dhe nuk do të dëshironi të shikoni më pornografi, nuk arrini asgjë. Përdoruesit nuk mund t'i lejojnë vetes të mendojnë për rreziqet shëndetësore, sepse nëse e bëjnë këtë, kënaqësia iluzore e varësisë shkon. Kjo shpjegon pse trajtimet e goditjes janë kaq të paefektshme në fazat e para të lënies: janë vetëm jo-përdoruesit që detyrohen të lexojnë për ndryshimet shkatërruese të trurit.

Merrni këtë bisedë të zakonshme me përdoruesit, përgjithësisht ata më të rinj.

> **Unë:** "Pse dëshiron të ndalosh?"
>
> **Përdoruesi:** "*Kam lexuar në blogun e një artisti tërheqës se është mirë të ndalem për katër ditë për të përmirësuar veten.*"
>
> **Unë:** "A nuk jeni të shqetësuar për rreziqet shëndetësore?"
>
> **Përdoruesi:** "*Jo, nesër mund të futem nën autobus.*"
>
> **Unë:** "Por a do të futeshit qëllimisht nën një autobus?"
>
> **Përdoruesi:** "*Sigurisht që jo.*"
>
> **Unë:** "A nuk ju shqetëson të shikoni majtas e djathtas kur kaloni rrugën?"
>
> **Përdoruesi:** "*Sigurisht që po.*"

Pikërisht, ata kalojnë shumë mundime për të mos u futur nën autobus dhe shanset janë mijëra me një që kjo të mos ndodhë. Megjithatë, përdoruesi rrezikon pothuajse sigurinë që të jetë i gjymtuar nga varësia e tyre dhe duket se është plotësisht i pavëmendshëm. E tillë është fuqia e larjes së trurit; pornografia në internet është një ujk në petkun e deleve. A nuk është e çuditshme që nëse do të ndjenim se ka fajin më të vogël në një aeroplan, ne nuk do të hipnim në të - edhe pse rreziqet janë miliona në një - megjithatë ne marrim më shumë se një në katër siguri me pornografinë dhe me sa duket janë të pavëmendshëm ndaj saj? Çfarë përfiton përdoruesi nga kjo? **Absulutisht asgje!**

Një tjetër mit i zakonshëm është depresioni ose nervozizmi. Shumë të rinj nuk janë të shqetësuar për shëndetin e tyre sepse nuk vuajnë nga depresioni apo melankolia. Depresioni apo stresi nuk është sëmundje, është një simptomë. Të rinjtë në përgjithësi nuk e ndiejnë nervozizmin ose depresionin e krijuar për shkak të aftësisë natyrore të trupit të tyre për të prodhuar më shumë dopaminë. Ndërsa plaken ose jeta e tyre ndeshet me pengesa serioze, burimet e tyre tashmë të varfëruara janë të mbingarkuar dhe ata do të përjetojnë simptoma të plota. Kur përdoruesit e moshuar ndihen të stresuar, të dëshpëruar ose të irrituar, kjo është për shkak se mekanizmat e natyrës të sigurt për dështimin po mbrojnë sistemin nervor nga vërshimi i tepërt i dopaminës përmes receptorëve zvogëlues. Përdoruesi zhvillon gjithashtu ndryshime të tjera neurologjike që i mbajnë ata në rrëmujë.

Mendojeni në këtë mënyrë, nëse do të kishit një makinë të bukur dhe do ta linit të ndryshket pa bërë asgjë për të, do të ishte goxha marrëzi. Do të bëhej shpejt një grumbull ndryshku i palëvizshëm, i paaftë për t'ju transportuar kudo. Megjithatë, nuk do të ishte fundi i botës pasi është vetëm një çështje parash. Por trupi juaj është mjeti që ju çon në jetë. Ne të gjithë themi se shëndeti ynë është pasuria jonë më e madhe - pyesni çdo milioner të sëmurë. Shumica prej nesh mund të shikojnë prapa për një sëmundje ose aksident në jetën tonë ku jemi lutur për t'u përmirësuar. Duke qenë përdorues pornografie, jo vetëm që po e lini ndryshkun të hyjë dhe nuk po bëni asgjë për të, por po shkatërroni sistematikisht automjetin e vetëm të përdorur për të kaluar gjatë gjithë jetës suaj.

Zgjohuni. Ju nuk duhet ta bëni këtë. Mbani mend, nuk po bën *absolutisht asgjë për ju*. Vetëm për një moment, nxirrni kokën nga rëra dhe pyesni veten se nëse do ta dinit me siguri se seanca juaj e radhës do të fillonte një proces që do t'ju bënte krejtësisht të papërgjegjshëm ndaj dikujt që e doni thellësisht, a do të vazhdonit ta përdornit? Duke u folur njerëzve me të cilët u ndodh kjo, ata sigurisht që nuk e prisnin që do t'u ndodhte as atyre, dhe gjëja më e keqe nuk është vetë sëmundja, por njohuria që e kanë sjellë vetë. Përpiquni të imagjinoni se si ndihen njerëzit që ‘kanë shtypur butonin’, për ta shpëlarja e trurit ka marrë fund. Ata e kalojnë pjesën e mbetur të jetës së tyre duke menduar: “*Pse bëra shaka me veten për kaq shumë kohë që më duhej të masturboja në pornografi në internet? Sikur të kisha mundësi të kthehesha!*"

Mos u tallni me veten, ju e keni atë shans. Është një reaksion zinxhir, nëse përfshiheni në seancën e ardhshme pornografike, do t'ju çojë tek tjetra dhe tjetra. Tashmë po ju ndodh. EasyPeasy nuk premton asnjë trajtim tronditëse, kështu që nëse tashmë keni vendosur që do të ndaloni, sa vijon nuk do të jetë tronditëse për ju. Nëse nuk e keni bërë, kaloni *pjesën e mbetur të këtij kapitulli* dhe kthehuni tek ai pasi të keni lexuar pjesën tjetër të librit.

Vëllime mbi vëllime kërkimesh janë shkruar tashmë për dëmin që pornografia e internetit shkakton në jetën tonë seksuale dhe mirëqenien mendore. Problemi është se derisa të vendosin të ndalojnë ata nuk duan ta dinë. Forumet dhe grupet e mentorëve janë një humbje kohe, sepse pornografia i vë sythat. Nëse lexojnë pa dashje, gjëja e parë që bëjnë është të hapin faqen e tyre të preferuar të tubit. Përdoruesit e pornos priren të mendojnë për lumturinë, stresin dhe rreziqet e seksit si një aferë goditëse, si të shkelësh në një minë tokësore.

Merreni në kokën tuaj, tashmë po ndodh. ***Çdo herë*** që hapni faqen tuaj pornografike, po shkaktoni vërshime dopamine dhe opioidet që hyjnë në punë. Rrëshqitjet e ujit nervor janë lyer me yndyrë dhe udhëtimi ju çon pa probleme në hapat e ardhshëm, ndërsa truri juaj tashmë i është dorëzuar skenarit. Sistemi nervor tani është i përmbytur nga dopamina dhe duke qenë se është hera e njëmbëdhjetë, receptorët e dopaminës mbyllen dhe përbindëshi i vogël përdor këtë rënie të lehtë kënaqësie në krahasim me herën e fundit për t'ju shtyrë më tej në vijën e kuqe drejt pornografisë ose sjelljes më tronditëse për të çliruar më shumë dopaminë. Më shumë risi, më shumë dopaminë dhe përbindëshi i vogël ju thotë të vazhdoni. Kaq shumë foto dhe video në një seancë të vetme shkaktojnë një stimul supernormal, duke injektuar më shumë kimikate në tru dhe duke ju shtyrë të vazhdoni.

Gjatë gjithë kohës, receptorët tuaj po marrin informacion për t'u mbyllur në përgjigje të përmbytjeve. Orgazma vetëm e rrit këtë efekt dhe çon në tërheqje. Ju jeni në mohim pasi përbindëshi i vogël dëshiron për rregullimin e tij pa dhimbje dhe shqetësim të vërtetë. Kërcënimi për të patur mosfunksionim erektil tmerron shumë, kjo është arsyeja pse ata e bllokojnë atë nga mendja e tyre dhe e errësojnë atë me frikën e ndalimit. Nuk është se frika është më e madhe, por lënia sot është e menjëhershme. Pse të shikoni në anën negative? Ndoshta nuk do të ndodhë, gjithsesi, duke qenë i detyruar të kem lënë deri atëherë.

Ne priremi ta mendojmë pornografinë si një tërheqje lufte: nga njëra anë është frika, "* Është e pashëndetshme, e ndyrë dhe skllavëruese.*" Nga ana tjetër, pozitivet: "*Është kënaqësia ime, miku im, mbështetësja ime .*" Nuk na duket kurrë se kjo anë është gjithashtu frikë; nuk është se na pëlqen pornografia, është se ne priremi të jemi të mjerë pa të. Të varurit nga heroina, të privuar nga heroina, kalojnë nëpër mjerim, por imagjinojnë gëzimin e plotë kur më në fund lejohen të fusin një gjilpërë në venë e tyre dhe t'i japin fund asaj mall të tmerrshëm. Përpiquni të imagjinoni se si dikush mund të besojë në të vërtetë se gëzon duke ngjitur një shiringë hipodermike në venë. Të varurit nga heroina nuk e vuajnë atë ndjenjë paniku dhe heroina nuk e lehtëson ndjenjën, por e shkakton atë.

Jo-përdoruesit nuk ndihen të mjerë nëse nuk u lejohet të përdorin pornografi - janë vetëm përdoruesit që e vuajnë atë ndjenjë. Pornografia në internet nuk e lehtëson ndjenjën, por e shkakton atë. Frika nga pasojat negative nuk i ndihmon përdoruesit të heqin dorë, sepse ata e krahasojnë ndjenjën me ecjen nëpër një fushë të minuar. Nëse ia del, mirë, por nëse ke qenë i pafat ke shkelur në një minë dhe ke përballuar pasojat. Nëse i njihje rreziqet dhe ishe i përgatitur për t'i marrë ato, çfarë lidhje kishte me dikë tjetër? Të varurit në këtë gjendje zakonisht zhvillojnë taktikat e mëposhtme evazive.

"***Më në fund do të plakeni dhe do të humbni gjithsesi aftësinë tuaj seksuale...***"

Sigurisht që po, por aftësia seksuale nuk është qëllimi - ne po flasim për skllavërinë. Edhe nëse është kështu, a është kjo një arsye logjike për të shkurtuar qëllimisht veten?

"***Cilësia e jetës është më e rëndësishme sesa thjesht të jetosh.***"

  Pikërisht! A po sugjeroni që cilësia e jetës së një të varur është më e madhe se dikujt që nuk është i varur? A besoni vërtet se cilësia e jetës së një përdoruesi është më e mirë se ajo e një jo-përdoruesi? Një jetë e kaluar duke mbuluar kokën në rërë dhe duke qenë të mjerë nuk tingëllon si e këndshme.

"***Unë jam beqar dhe nuk planifikoj të vendosem në të ardhmen, kështu që pse jo?***"

Edhe nëse kjo do të ishte e vërtetë, a është kjo një arsye logjike për të luajtur me mekanizmat neurologjikë të kontrollit të impulsit? A mund të imagjinoni që dikush të jetë aq budalla sa të zhvishet lakuriq sa herë që është vetëm, pavarësisht se sa i sigurt që nuk pret askënd? **Kjo është ajo që përdoruesit e pornografisë bëjnë në mënyrë efektive!**

Ngritja progresive e qarqeve tona të shpërblimit me stimulim të tepruar dhe duke i bërë ata të paaftë për të përballuar streset normale të jetës nuk ndihmon për të shijuar jetën tuaj me entuziazëm dhe energji. Pornografia dhe masturbimi kanë zëvendësuar oreksin natyral seksual, si një çokollatë që zëvendëson ushqimin e vërtetë. Çuditërisht, shumë mjekë dhe psikologë po i lidhin tani problemet e ndryshme të shëndetit mendor me shkaqe fiziologjike. Komuniteti kryesor mjekësor ka thënë se pornografia nuk është vërtetuar kurrë shkencërisht se është shkaku i drejtpërdrejtë i çështjeve të raportuara nga individë që rrëfejnë veten, por pranimi i paaftësisë seksuale të dikujt në publik është një ngjarje kaq e turpshme, kështu që pse dikush do ta bënte këtë nëse nuk ata ishin vërtet të shqetësuar, pasi kishin gjetur shkakun dhe e kishin eliminuar atë nga jeta e tyre?

EasyPeasy do t'ju ndihmojë të shpëtoni nga pornografia dhe të bëheni një ish-përdorues i lumtur. Asnjë pornografi, masturbim me ndihmën e pornografisë ose orgazma të panevojshme. Ndihma e vetme do të jetë prekja, shikimi dhe aroma e partnerit tuaj. Ashtu si buka me drithëra integrale pas një oreksi të zhvilluar mirë, nuk do të dëshironi më shurupin e misrit me fruktozë të lartë të pornografisë në internet. Provat kaq dërrmuese nuk kanë nevojë për prova; kur godas gishtin e madh me çekiç dhe më dhemb, nuk ka nevojë të vërtetohet. Stresi i pornografisë në internet ka efekte rrjedhëse në aspekte të tjera të jetës së përdoruesit, duke i predispozuar shumë për t'iu drejtuar drogave të tilla si cigaret dhe alkooli për ta përballuar, dhe në disa raste madje duke e kthyer hostin të mendojë për vetëvrasje.

Përdoruesit gjithashtu vuajnë iluzione se efektet e këqija të pornografisë janë të mbivlerësuara. E kundërta është rasti, nuk ka dyshim se pornografia në internet është shkaku kryesor i mosfunksionimit seksual dhe shumë problemeve të tjera. Sa divorce janë shkaktuar nga pornografia? Nuk ka mënyra të besueshme për të ditur, por kërkimet e komuniteteve në internet sugjerojnë se numri po rritet në mënyrë eksponenciale.

Është një episod i *Friends* ku djemtë, të cilët po merrnin vazhdimisht pornografi falas në TV, filluan të pyesin veten pse dërguesi i picës nuk kërkoi të kontrollonte 'dhomën e madhe të gjumit' të tyre. Kur je i varur, pa ndryshim projekton fantazi pornografike te femrat e vërteta. Imagjinoni se çfarë mund t'i bëjë ekspozimi i pakujdesshëm apo edhe aksidental i pornografisë në anët më të errëta të internetit për dikë që tashmë është në një pikë kthese në jetën e tyre. Lufta kundër këtyre mendimeve të shkaktuara nga pornografia do të jetë një dëmtim i madh për shëndetin e tyre mendor.

(Këtu është një eksperiment tjetër mendimi: le të themi se dikush vjen tek ju dhe thotë se nuk dëshiron domosdoshmërisht një orgazmë, por dëshiron shumë të bëjë dashuri, madje edhe në mënyrë depërtuese. Ata duan ta bëjnë atë për aq kohë sa mund të shkosh pa një orgazmë - por nëse ndodh atëherë është mirë. Ju siguroj për një përvojë të re seksuale shumë më të mirë se çdo tjetër, nëse e merrni ndonjëherë atë ofertë. Provojeni.)

Efektet e shpëlarjes së trurit na bëjnë të priremi të mendojmë si njeriu që, pasi ra nga një ndërtesë 100-katëshe, citohet duke thënë teksa kalonte katin e pesëdhjetë, "*Deri tani, aq mirë!" Ne mendojmë se si ne' deri më tani e ke larguar, një seancë më shumë pornografike nuk do të bëjë ndryshimin. Shihni në një mënyrë tjetër: 'zakoni' është një zinxhir i vazhdueshëm për jetën me çdo seancë që krijon nevojën për tjetrën. Kur filloni zakonin, ju ndezni një fitil. Problemi është, *nuk e dini sa e gjatë është fitili.* Sa herë që dorëzoheni në një seancë pornografike, jeni një hap më afër shpërthimit të bombës. **SI DO TA DINI NËSE ËSHTË E TJETRA?**

## Hijet e Zeza Sinister

Përdoruesit e kanë shumë të vështirë të besojnë se pornografia në internet në fakt shkakton ato ndjenja të pasigurta kur jeni jashtë natën vonë pas një dite të diskutueshme në shtëpi ose në punë. Jo-përdoruesit nuk vuajnë nga kjo ndjenjë, pornografia e shkakton atë.

Një tjetër nga gëzimet e mëdha të lënies së pornografisë është liria nga hijet e zeza të këqija në fund të mendjes sonë. Të gjithë përdoruesit e dinë se janë budallenj për të mbyllur mendjen nga efektet e këqija të pornografisë. Për shumicën e jetës sonë është automatike, por hijet e zeza janë gjithmonë të fshehura në mendjet tona nënndërgjegjeshëm, pak nën sipërfaqe. Disa nga përfitimet e mrekullueshme të lënies së duhanit janë të vetëdijshme, të tilla si përfundimi i humbjes së kohës dhe marrëzia e plotë e të bërit dashuri me një imazh dydimensional.

Kapitujt e fundit kanë trajtuar avantazhet e konsiderueshme të të qenit jopërdorues, por në interes të drejtësisë është e nevojshme të jepet një llogari e balancuar. Prandaj, kapitulli tjetër rendit avantazhet e të qenit përdorues.

# Avantazhet e të qenit përdorues i pornos
