# Metoda e vullnetit

Është një fakt i pranuar në shoqëri që është shumë e vështirë të ndalosh pornografinë. Librat dhe forumet që ju këshillojnë se si të ndaloni, zakonisht fillojnë duke ju treguar se sa e vështirë është. E vërteta është se është qesharake e lehtë. Është e kuptueshme të vihet në dyshim kjo deklaratë, por së pari thjesht merrni parasysh atë. Nëse qëllimi juaj është të vraponi një milje në katër minuta, *kjo është* e vështirë dhe do t'ju duhet të kaloni vite të tëra trajnimi të vështirë, madje edhe atëherë mund të jeni fizikisht të paaftë.

Megjithatë, gjithçka që duhet të bëni për të ndaluar pornografinë është të mos e shikoni më dhe/ose të masturboni. Askush nuk ju detyron të masturboni (përveç vetes) dhe ndryshe nga ushqimi apo uji, ai nuk është i nevojshëm për mbijetesë. Pra, nëse doni të ndaloni së bëri atë, pse duhet të jetë e vështirë? Në fakt, nuk është. Janë përdoruesit që e bëjnë të vështirë për veten e tyre përmes përdorimit të vullnetit ose ndonjë metode që e detyron përdoruesin të ndihet sikur po bën një lloj sakrifice. Le të shqyrtojmë këto metoda.

Ne nuk vendosim të bëhemi përdorues, ne thjesht eksperimentojmë me revista pornografike ose faqe interneti dhe për shkak se ato janë të tmerrshme (kjo është e vërtetë, e tmerrshme), përveç klipit tonë të dëshiruar, ne jemi të bindur se mund të ndalojmë sa herë të duam. Në fillim, ne i shikojmë ato klipet e para kur duam dhe në raste të veçanta. Përpara se ta kuptojmë, ne jo vetëm që po i vizitojmë ato faqe rregullisht dhe po masturbojmë kur duam - ne po masturbohemi me ta çdo ditë. Pornografia është bërë pjesë e jetës sonë, duke siguruar që ne kemi nevojë për një lidhje interneti kudo që shkojmë. Atëherë ne besojmë se kemi të drejtë për dashuri, seks, orgazmë dhe veçoritë e pornografisë që lehtësojnë stresin. Nuk na duket se na shkon mendja se i njëjti klip dhe aktorë nuk na ofrojnë të njëjtën shkallë zgjimi dhe ne fillojmë të luftojmë kundër vijës së kuqe për të shmangur "pornon e keqe". Në fakt, masturbimi dhe pornografia në internet as nuk e përmirësojnë jetën tonë seksuale dhe as nuk e reduktojnë stresin, është thjesht se përdoruesit besojnë se nuk mund ta shijojnë jetën ose të përballojnë stresin pa të.

Zakonisht duhet shumë kohë për të kuptuar se jemi të fiksuar sepse vuajmë nga iluzioni që përdoruesit shikojnë pornografi sepse e shijojnë atë - dhe jo sepse ***kanë nevojë***. Kur nuk po “shijojmë” pornografinë, gjë që nuk mund ta bëjmë kurrë nëse nuk shtohet risia, tronditja ose përshkallëzimi, ne jemi nën iluzionin se mund ta ndalojmë kurdoherë. Ky është një kurth besimi. "*Mua nuk më pëlqen pornografia, kështu që mund të ndaloj kur të dua*". Vetëm ju duket se kurrë nuk 'doni' të ndaloni.

Zakonisht nuk kuptojmë se ekziston një problem derisa të përpiqemi të ndalojmë. Përpjekjet e para në përgjithësi janë të hershme – nxiten nga takimi me një partner dhe vërehet se ato nuk janë ‘mjaftueshëm’ pas datave fillestare. Një arsye tjetër e zakonshme është vërejtja e efekteve shëndetësore të pranishme në jetën e përditshme.

Pavarësisht arsyes, përdoruesi gjithmonë pret një situatë stresuese, qoftë shëndetësore apo seksi. Sapo ndalojnë, përbindëshi i vogël fillon të ketë uri. Përdoruesi më pas dëshiron diçka për të pompuar dopaminën e tij, të tilla si cigare, alkool ose të preferuarën e tij - pornografinë në internet - me haremin e tyre vetëm një klikim larg. Memoria e pornografisë nuk është më në bodrum, është virtuale dhe e aksesueshme nga kudo. Nëse partneri i tyre është afër ose janë me miqtë, ata nuk kanë më akses në haremin e tyre virtual, duke i bërë ata edhe më të shqetësuar.

Nëse përdoruesi ka hasur në materiale shkencore ose komunitete në internet, ata do të kenë një tërheqje në mendjen e tyre, duke u rezistuar tundimeve dhe duke u ndjerë i privuar. Mënyra e tyre për të lehtësuar zakonisht stresin tani është e padisponueshme, duke pësuar një goditje të trefishtë. Rezultati i mundshëm pas kësaj periudhe torture është kompromisi – “*Do të shkurtoj*” ose “*Kam zgjedhur kohën e gabuar*” ose ndoshta, “*Do të pres derisa stresi të largohet nga jeta ime. *" Megjithatë, pasi stresi ka ikur, nuk ka asnjë arsye për të ndaluar dhe përdoruesi nuk vendos të lërë përsëri deri në momentin tjetër stresues.

Sigurisht, nuk ka kurrë një kohë të duhur sepse jeta për shumicën e njerëzve bëhet më stresuese. Ne largohemi nga mbrojtja e prindërve tanë, duke hyrë në botën e krijimit të shtëpisë, marrjes së hipotekave, lindjes së fëmijëve dhe punës më të përgjegjshme. Pavarësisht - jeta e përdoruesit nuk mund të bëhet më pak stresuese sepse pornografia në fakt shkakton stres. Sa më shpejt që përdoruesi të kalojë në fazën e përshkallëzimit, aq më i shqetësuar bëhet ai dhe aq më i madh rritet iluzioni i varësisë.

Në fakt, është një iluzion që jeta bëhet më stresuese dhe pornografia - ose një mbështetëse e ngjashme - e krijon atë iluzion. Kjo do të diskutohet më në detaje më vonë, por pas këtyre dështimeve fillestare përdoruesi zakonisht mbështetet në mundësinë që një ditë të zgjohen dhe thjesht të mos duan të masturbojnë ose të përdorin pornografi. Kjo shpresë zakonisht ndizet nga historitë e dëgjuara nga ish-përdorues të tjerë, "*Nuk isha serioze derisa pata një depërtim të zbehur, atëherë nuk doja të përdorja më pornografi dhe ndalova së masturbuari."

Mos u tallni, hetoni këto thashetheme dhe do të zbuloni se ato nuk janë kurrë aq të thjeshta sa duken. Zakonisht përdoruesi tashmë është përgatitur të ndalojë dhe thjesht e ka përdorur incidentin si trampolinë. Më shpesh, në rastin e njerëzve që ndalojnë "tamam ashtu", ata kanë pësuar një tronditje: ndoshta një zbulim nga partneri i tyre, një incident i vetëdijshëm i aksesit në pornografi jo të orientimit të tyre normal seksual ose kanë pasur një marrëdhënie seksuale. mosfunksionimi tremb veten e tyre. Nuk do të ndodhë nëse nuk e realizoni.

Le të shqyrtojmë më në detaje pse metoda e vullnetit është kaq e vështirë. Për pjesën më të madhe të jetës sonë ne adoptojmë qasjen kokë-në-rërë, "*Do të ndaloj nesër*". Në raste të çuditshme, diçka do të shkaktojë një përpjekje për të ndaluar. Mund të jenë shqetësime për shëndetin, burrërinë ose një periudhë e vetë-analizës dhe të kuptuarit se nuk e shijojmë atë. Cilado qoftë arsyeja, ne fillojmë të peshojmë të mirat dhe të këqijat e pornografisë. Seksi ndahet në tantric (prekje, erë, zë) dhe propagandues (orgazmë); është një nga çelësat kryesorë për të hapur mendjen tonë, dhe pa këtë dallim të rëndësishëm, do të ketë konfuzion, i cili çon në dështim. Në vlerësimin racional ne zbulojmë atë që kemi ditur gjatë gjithë jetës sonë, përfundimi është një mijë herë "*** NDALONI TA SHIKONI!***"

Nëse do të uleshit dhe do të jepnit pikë për avantazhet e ndalimit dhe do t'i krahasonit ato me avantazhet e pornografisë, numri total i pikëve për ndalimin do të peshonte shumë më tepër se çdo 'disvantazh'. Nëse përdorni bast Pascal's, duke hequr dorë nuk do të humbisni pothuajse asgjë, me shanse të larta fitimi dhe shanse më të larta për *mos* humbje. Megjithëse përdoruesi e di se do të jetë më mirë si jo-përdorues, besimi se ata po bëjnë një sakrificë i pengon ata. Edhe pse një iluzion, është i fuqishëm. Ata nuk e dinë pse, por përdoruesi ka besimin se gjatë periudhave të mira dhe të këqija të jetës, seancat duket se ndihmojnë. Edhe para fillimit të përpjekjes së tyre, shpëlarja e trurit shoqëror e përforcuar më tej nga shpëlarja e trurit nga varësia e tyre kombinohet më pas me shpëlarjen edhe më të fuqishme të trurit se sa e vështirë është të "heqësh dorë".

Përdoruesit dëgjojnë histori të atyre që kanë ndaluar për shumë muaj dhe ende e dëshirojnë dëshpërimisht atë, ose të atyre që e kanë lënë të pakënaqur, të cilët, pasi kanë ndaluar, kalojnë pjesën tjetër të jetës së tyre duke u qarë për faktin se do të donin të bënin një seancë. Ka përralla të përdoruesve që ndalojnë për shumë muaj apo vite, jetojnë jetë të lumtur, vetëm për të parë një "shikim" në pornografi dhe befas janë fiksuar përsëri. Përdoruesit ndoshta i njohin disa në fazat e avancuara të sëmundjes, duke shkatërruar dukshëm veten e tyre dhe qartësisht që nuk e shijojnë jetën – megjithatë vazhdojnë ta përdorin. Për më tepër, ata ndoshta kanë vuajtur një ose më shumë nga ato përvoja vetë.

Pra, në vend që të filloni me ndjenjën, “*Shkëlqyeshëm! I keni dëgjuar lajmet? Nuk kam më nevojë të shikoj pornografi!*", ata fillojnë në vend të kësaj me ndjenja dënimi dhe zymtësie - sikur po përpiqen të ngjiten në Everest - dhe përcaktojnë në mënyrë të rreme se sapo përbindëshi i vogël të futet në ju, ju jeni të fiksuar. Shumë përdorues e nisin përpjekjen duke u kërkuar falje të dashurave ose grave të tyre, "*Shiko, po përpiqem të heq dorë nga pornografia. Ndoshta do të jem nervoz për dy javët e ardhshme, kështu që përpiquni të duroni me mua.*" Shumica e përpjekjeve janë të dënuara para se të fillojnë.

Supozoni se përdoruesi mbijeton disa ditë pa një seancë. Ata po e rikthejnë eksitimin e tyre dhe kanë filluar të rikuperohen. Ata nuk i kanë hapur vendet e tyre të preferuara të tubave dhe si pasojë po eksitohen nga stimujt normalë në të cilët ishin zonuar më parë. Arsyet që ata vendosën të ndalojnë në radhë të parë po zhduken me shpejtësi nga mendimet e tyre, si të shohin një aksident të keq rrugor gjatë vozitjes. Do t'ju ngadalësojë për njëfarë kohe, por do të shkelni këmbën në mbyt herën tjetër që do të vonoheni për një takim.

Në anën tjetër të luftës është përbindëshi i vogël që ende nuk e ka ndrequr. Nuk ka dhimbje fizike - nëse do të kishit të njëjtën ndjenjë për shkak të një ftohjeje, nuk do të ndalonit së punuari ose do të bini në depresion, do të qeshnit. Gjithçka që përdoruesi di është se ata duan të vizitojnë haremin e tyre. Përbindëshi i vogël e di këtë, dhe fillon përbindëshin e madh të larjes së trurit, duke bërë që i njëjti person që disa orë ose ditë më parë renditi të gjitha arsyet për t'u ndalur, tani të kërkojë me dëshpërim ndonjë justifikim për të filluar përsëri. Ata fillojnë të thonë gjëra të tilla si:

- “*Jeta është shumë e shkurtër, mund të shpërthejë një bombë, nesër mund të futem nën autobus. E kam lënë shumë vonë. Të thonë se çdo gjë të jep varësi në ditët e sotme.*"

- "*Kam zgjedhur kohën e gabuar.*"

- “*Duhet të kisha pritur deri pas Krishtlindjeve, pas pushimeve/testeve të mia, pas kësaj ngjarje stresuese në jetën time.*”

- "*Nuk mund të përqendrohem, po bëhem nervoz dhe keqdashës, as punën time nuk mund ta bëj siç duhet.*"

- “* Familja dhe miqtë e mi nuk do të më duan. Le ta pranojmë, për hir të të gjithëve duhet të filloj përsëri. Unë jam një i varur i konfirmuar ndaj seksit dhe nuk ka asnjë mënyrë që të jem i lumtur përsëri pa një orgazëm.*"

- "*Askush nuk mund të mbijetojë pa seks.*" (I larë trurin nga njerëzit me kuptim të mirë që nuk marrin parasysh dallimin midis pjesëve tantrike dhe përhapëse të seksit).

- "*E dija se kjo do të ndodhte, truri im është 'sensibilizuar' nga DeltaFosB për shkak të ndryshimeve të prekura nga rritjet e dopaminës për shkak të përdorimit të tepruar të pornografisë në të kaluarën. Sensibilizimi nuk mund të hiqet kurrë nga truri.*"

Në këtë fazë, përdoruesi zakonisht dorëzohet. Duke ndezur shfletuesin, skizofrenia rritet. Nga njëra anë është lehtësimi i jashtëzakonshëm i dhënies fund të dëshirës pasi përbindëshi i vogël më në fund merr zgjidhjen e tij; nga ana tjetër, orgazma është e tmerrshme dhe përdoruesi nuk mund ta kuptojë pse po e bën atë. Kjo është arsyeja pse përdoruesi mendon se i mungon vullneti. Nuk është në fakt mungesë vullneti, gjithçka që ata kanë bërë është të ndryshojnë mendje dhe të marrin një vendim krejtësisht racional në dritën e informacionit më të fundit.

"*Çfarë kuptimi ka të jesh i shëndetshëm apo i pasur nëse je i mjerë?"*

Absolutisht asnjë! Shumë më mirë të kesh një jetë më të shkurtër të këndshme sesa një jetë të gjatë të mjerueshme. Për fat të mirë, kjo është e pavërtetë për jo-përdoruesin, pasi jeta është pafundësisht më e këndshme. Mjerimi që po vuan përdoruesi nuk është për shkak të dhembjeve të tërheqjes - megjithëse fillimisht është shkaktuar prej tyre - agonia aktuale është tërheqja e luftës në mendje e shkaktuar nga dyshimi dhe pasiguria. Për shkak se përdoruesi fillon duke ndjerë se po bën një sakrificë, ata më pas fillojnë të ndihen të privuar, që është një formë stresi.

Një nga këto momente stresuese është kur truri u thotë atyre që të ‘kanë një sy’, duke dashur të tërhiqen sapo të ndalojnë. Por për shkak se ata janë ndalur, ata nuk munden dhe kjo i bën ata edhe më të dëshpëruar dhe e ndez përsëri shkasin. Një faktor tjetër që e bën kaq të vështirë lënien është të presësh që diçka të ndodhë. Nëse objektivi juaj është të kaloni një test shoferi, sapo të keni kaluar testin është e sigurt nëse e keni arritur objektivin tuaj. Sipas metodës së fuqisë së vullnetit, tregimi i brendshëm është - "*Nëse mund të shkoj mjaftueshëm pa pornografi në internet, dëshira për ta parë atë përfundimisht do të zhduket." Ju mund ta shihni këtë në praktikë në forumet online ku të varurit flasin për brezat e tyre ose ditët e tyre abstinencë.

Siç u tha më lart, agonia që pëson përdoruesi është mendore dhe e shkaktuar nga pasiguria. Edhe pse nuk ka dhimbje fizike, ajo ka ende efekte të fuqishme. Tani i mjerë dhe i pasigurt, përdoruesi është larg nga harrimi, tashmë plot dyshime dhe frikë.

- "*Sa do të zgjasë malli?*"

- "*A do të jem ndonjëherë i lumtur përsëri?*"

- "*A do të dua ndonjëherë të zgjohem në mëngjes?*"

- "*Si do ta përballoj stresin në të ardhmen?*"

Përdoruesi pret që gjërat të përmirësohen, por ndërsa ata janë ende duke pastruar, "haremi" po bëhet gjithnjë e më i çmuar. Në fakt, diçka *po* ndodh, por në mënyrë të pavetëdijshme, nëse ata mund të mbijetojnë me javë pa hapur shfletuesin, dëshira për përbindëshin e vogël zhduket. Megjithatë, siç u tha më parë, dhembjet e tërheqjes nga dopamina dhe opioidet janë aq të lehta sa përdoruesi nuk është as i vetëdijshëm për to. Në këtë kohë, shumë përdorues ndiejnë se e kanë "shkelur" dhe kështu hidhini një sy për ta vërtetuar atë, duke i dërguar ata përsëri poshtë rrëshqitjes së ujit. Pasi kanë furnizuar trupin me dopaminë, tani ka një zë të vogël në fund të mendjes së tyre duke thënë "*Ti do një tjetër".

Si fëmijë keni parë filma vizatimorë dhe sipas neuroshkencës keni krijuar rrugë nervore (DeltaFosB) për ta. Nëse dëshironi të dekurajoni një fëmijë nga shikimi, do të studionit nëse ato rrugë do të ekzistonin ende dhe do të anketoni të rriturit se pse nuk u pëlqen të shikojnë më filmat vizatimorë të tyre të preferuar të fëmijërisë. Për një, ka argëtim më të mirë në dispozicion dhe së dyti, filmat vizatimorë thjesht nuk e mbajnë më magjinë. Me metodën e vullnetit thjesht po ia mohoni fëmijës filmin vizatimor, por me EasyPeasy po siguroheni gjithashtu që ai të mos shohë asnjë vlerë në të. Cila është më e mirë?

Përdoruesi zakonisht nuk do të hyjë në një seancë tjetër menjëherë, duke menduar "*Nuk dua të fiksohem përsëri!*" dhe lejon të kalojë një periudhë të sigurt orësh, ditësh apo edhe javësh. Ish-përdoruesi më pas mund të thotë: "*Epo, nuk u lidha, kështu që mund të bëj një seancë tjetër të sigurtë.*" Ata kanë rënë përsëri në të njëjtin kurth si kur filluan për herë të parë dhe tashmë janë në shpatin e rrëshqitshëm.

Përdoruesit që kanë sukses duke përdorur metodën e vullnetit priren ta kenë të gjatë dhe të vështirë sepse problemi kryesor është shpëlarja e trurit. Shumë kohë pasi ka vdekur varësia fizike, përdoruesi është ende i mjeruar. Përfundimisht, pasi i mbijetuan kësaj torture afatgjatë, fillon t'u kuptojë se nuk do të dorëzohen, duke ndaluar fshirjen dhe duke pranuar se jeta vazhdon dhe është e këndshme pa pornografi. Ka shumë më shumë dështime sesa suksese, sepse disa që kanë sukses kalojnë jetën e tyre në një gjendje të cenueshme, të mbetur me një sasi të caktuar të larjes së trurit duke u thënë atyre se pornografia në fakt u jep atyre një shtysë. Kjo shpjegon pse shumë përdorues që janë ndalur për periudha të gjata përfundojnë të rifillojnë më vonë.

Shumë ish-përdorues do ta kenë seancën e rastit si një "trajtim special" ose për të bindur veten se sa i fortë është vetëkontrolli i tyre. E bën pikërisht këtë - por sapo përfundon seanca e tyre, dopamina fillon të largohet dhe një zë i vogël në fund të mendjes së tyre fillon t'i shtyjë ata drejt një tjetri. Nëse vendosin të marrin pjesë, duket se është ende nën kontroll, pa tronditje, përshkallëzim apo kërkim risi, kështu që ata thonë: “*E mrekullueshme! Ndonëse nuk po e shijoj vërtet, nuk do të tërhiqem. Pas Krishtlindjeve / kësaj feste / kësaj traume, unë do të ndaloj.*" Ata nuk e dinë që rrëshqitjet e ujit të trurit të tyre janë lyer edhe më shumë.

Shumë vonë, ata tashmë janë të lidhur! Kurthi nga i cili arritën të nxirrnin veten ka marrë sërish viktimën e tij.

Siç u tha më parë, kënaqësia nuk vjen në të. Nuk bëri kurrë! Nëse do të shikonim për shkak të kënaqësisë, askush nuk do të qëndronte në faqet e tubave për më shumë sesa duhet për të përfunduar veprën. Pavarësisht, një mënyrë më e mirë për të kënaqur veten është nga kujtimet. Ne supozojmë se na pëlqen pornografia në internet vetëm sepse nuk mund të besojmë se do të ishim aq budallenj sa të bëheshim të varur nëse nuk do ta shijonim atë. Shumica e përdoruesve nuk kanë asnjë ide për stimulin supernormal, risinë ose kërkimin e shokut dhe madje edhe pasi lexojnë për të, ata nuk besojnë se përdorimi i tyre është i motivuar nga instalimet elektrike të qarkut evolucionar të shpërblimit. Kjo është arsyeja pse një pjesë e madhe e pornografisë është nënndërgjegjshëm - nëse do të ishit të vetëdijshëm për ndryshimet neurologjike dhe do të duhej të justifikonit se do t'ju kushtonte para në të ardhmen, edhe iluzioni i kënaqësisë do të largohej.

Kur përpiqemi të bllokojmë mendjet tona në anën e keqe, ndihemi budallenj. Nëse do të duhej ta përballonim, kjo do të ishte e patolerueshme! Nëse shikoni një përdorues në veprim, do të shihni se ata janë të lumtur vetëm kur nuk janë të vetëdijshëm që po përdorin. Pasi të jenë të vetëdijshëm, ata priren të jenë të pakëndshëm dhe të kërkojnë falje. Pornografia ushqen përbindëshin e vogël, kështu që pasi ta pastroni atë nga trupi së bashku me larjen e trurit (përbindësh i madh), nuk do të keni as nevojë dhe as dëshirë për të parë!
