# Kujdes nga pakësimi

Shumë përdorues përdorin prerjen si një hap drejt ndalimit, ose si një përpjekje për të kontrolluar përbindëshin e vogël. Shumë rekomandojnë uljen ose një "dietë pornografike" si një zgjedhje. Përdorimi i prerjes si një gur për të ndaluar është ***fatale.*** Janë këto përpjekje për të pakësuar që na mbajnë të bllokuar për pjesën e mbetur të jetës sonë. Në përgjithësi, reduktimi pason përpjekjet e dështuara për të ndaluar. Pas disa orësh ose ditësh abstinence, përdoruesi thotë diçka si:

"*Nuk mund ta përballoj mendimin për të fjetur pa vizituar haremin tim në internet, kështu që tani e tutje do të përdor pornografi një herë në katër ditë ose do të pastroj koleksionin tim nga 'pornografia e keqe'. Nëse mund të ndjek këtë dietë pornografike , ose mund ta mbaj atje ose mund ta shkurtoj edhe më tej.*"

Tani ndodhin disa gjëra të tmerrshme:

1. Ata janë të mbërthyer me më të keqen e të gjitha botëve, ende të varur nga pornografia në internet dhe e mbajnë gjallë përbindëshin jo vetëm në trupin e tyre, por edhe në mendjen e tyre.

2. Duke uruar jetën e tyre larg duke pritur për seancën e ardhshme.

3. Përpara pakësimit, sa herë që dëshironin të vizitonin haremin e tyre ata ndeznin shfletuesin e tyre dhe të paktën pjesërisht i lehtësonin dhembjet e tërheqjes. Tani, përveç streseve normale të jetës, ata po i shkaktojnë vetes edhe dhimbjet e tërheqjes për pjesën më të madhe të jetës së tyre, gjë që i bën ata edhe më të mjerë dhe më keq.

4. Ndërsa kënaqeshin, ata as nuk i shijuan shumicën e seancave dhe as nuk e kuptuan se po përdornin një stimul supernormal. Ishte automatike, e vetmja vizitë në harem që u gëzua ishte ajo pas një periudhe abstinence. Tani që presin një orë shtesë për çdo vizitë në haremin, ata ‘shijojnë’ secilën prej tyre. Sa më gjatë të pritet, aq më e ‘kënaqshme’ duket se çdo seancë bëhet, sepse ‘kënaqësia’ në një seancë nuk është vetë seanca – është fundi i agjitacionit të shkaktuar nga dëshira – qoftë dëshira e lehtë fizike apo fshirja mendore. Sa më e gjatë të jetë vuajtja, aq më e ‘kënaqshme’ bëhet çdo seancë.

Vështirësia kryesore në ndalimin nuk është varësia neurologjike, e cila është e lehtë. Përdoruesit do të ndalojnë pa vështirësi në raste të ndryshme - vdekja e një personi të dashur, familja ose punë, etj. Ata do të qëndrojnë, të themi, dhjetë ditë pa akses dhe kjo nuk i shqetëson. Por nëse do të kalonin të njëjtat dhjetë ditë kur mund të kishin akses në pornografi, ata do t'i shqyejn flokët.

Shumë përdorues do të kenë mundësi gjatë ditës së tyre të punës dhe do të abstenojnë, ose do të kalojnë nëpër Victoria's Secret ose pishina e kështu me radhë pa shqetësime të panevojshme. Shumë do të abstenojnë nëse duhet të flenë përkohësisht në divan për të lënë hapësirë ​​për një vizitor, ose nëse janë vetë duke vizituar. Edhe në lokalet Go-Go apo plazhet nudiste nuk ka pasur trazira. Përdoruesit janë pothuajse të kënaqur që dikush ose diçka thonë se nuk mund të shikojnë pornografi. Në fakt, përdoruesit që duan të lënë marrin një kënaqësi të fshehtë duke shkuar për periudha të gjata pa vizita në harem, duke u dhënë atyre shpresë se ndoshta një ditë nuk do ta duan kurrë.

Problemi i vërtetë kur ndalohet është shpëlarja e trurit, një iluzion i të drejtës që pornografia në internet është një lloj mbështetjeje ose shpërblimi dhe jeta nuk do të jetë kurrë e njëjtë pa të. Larg nga të çaktivizoni pornografinë në internet, gjithçka që arrin pakësimin po ju lë të ndiheni të pasigurt dhe të mjerë, duke ju bindur se gjëja më e çmuar në këtë tokë është klipi i ri që keni humbur, se nuk ka mundësi të jeni sërish të lumtur pa e parë. atë.

Nuk ka asgjë më patetike se përdoruesi që po përpiqet të reduktojë, duke vuajtur nga iluzioni se sa më pak pornografi që shikojnë, aq më pak do të duan të vizitojnë haremin e tyre në internet. E kundërta është e vërtetë – sa më pak të shikojnë pornografi, aq më gjatë vuajnë dhimbjet e tërheqjes dhe aq më shumë ‘shijojnë’ lehtësimin e lehtësimit të tyre. Megjithatë, ata do të vërejnë se zhanri i tyre i preferuar nuk po godet në vend. Por kjo nuk do t'i ndalojë ata: nëse faqet e tubave do t'i kushtoheshin vetëm një ylli ose një zhanri, asnjë përdorues nuk do të shkonte më shumë se një herë.

Vështirë të besohet? Cili është momenti më i keq i vetëkontrollit që ndjen një person? Duke pritur për katër ditë dhe më pas duke pasur një kulm. Atëherë, cili është momenti më i çmuar për shumicën e përdoruesve në një dietë katërditore pornografike? Ashtu është, e njëjta kulm pas pritjes për katër ditë! A besoni vërtet se po masturboni për të shijuar orgazmën, apo shpjegimin më racional që ju nevojitet për të lehtësuar dhembjet e tërheqjes nën iluzionin që keni të drejtë?

Heqja e larjes së trurit është thelbësore për të hequr iluzionet rreth pornografisë përpara se të shuani seancën e fundit. Nëse nuk e keni hequr iluzionin se ju pëlqen para se të mbyllni atë dritare, nuk ka asnjë mënyrë që ta provoni më pas pa u fiksuar përsëri. Kur qëndroni pezull mbi faqeshënuesit dhe fotot e ruajtura, pyesni veten se ku është lavdia në këtë veprim. Ndoshta ju besoni se vetëm disa klipe janë me shije të mirë, si ato me tema të zakonshme ose të preferuara. Nëse po, pse të shqetësoheni për të parë video ose tema të tjera? Sepse e keni bërë zakon? Pse dikush zakonisht do të ngatërronte trurin e tij dhe do ta shpërdoronte veten? Asgjë nuk është ndryshe pas një muaji, kështu që pse një klip porno duhet të jetë ndryshe?

Ju mund ta provoni këtë vetë. Gjeni atë klipin e nxehtë të muajit të kaluar për të vërtetuar se është ndryshe. Pastaj, vendosni një kujtesë dhe shikoni të njëjtin klip pas një muaji pa pornografi. Do të godasë (pothuajse) të njëjtat pika si muajin e kaluar. I njëjti klip do të jetë i ndryshëm pas një ngjarjeje sociale ku ju refuzoni ose testoheni nga një partner i mundshëm. Arsyeja është se një i varur nuk mund të jetë kurrë plotësisht i lumtur nëse përbindëshi i vogël mbetet i pakënaqur.

Ku vjen kënaqësia në të? Thjesht ata janë të mjerë nëse nuk mund të lehtësojnë simptomat e tyre të tërheqjes. Dallimi midis shikimit të pornografisë dhe jo është ndryshimi midis të qenit i lumtur dhe i mjerë. Kjo është arsyeja pse pornografia në internet duket të jetë më e mirë. Përdoruesit që hyjnë në faqet e tyre gjëja e parë në mëngjes për pornografi janë të mjerë pavarësisht nëse e shikojnë atë apo jo.

Prerja jo vetëm që nuk funksionon, por është forma më e keqe e torturës. Nuk funksionon sepse fillimisht përdoruesi shpreson që duke e krijuar zakonin gjithnjë e më pak, do të ulin dëshirën për të parë pornografi. Nuk është zakon, është varësi. Natyra e çdo varësie është dëshira gjithnjë e më shumë, jo më pak e më pak. Prandaj, për të pakësuar, përdoruesi duhet të ushtrojë vullnet dhe disiplinë për pjesën tjetër të jetës së tyre. Pra, pakësimi do të thotë vullnet dhe disiplinë përgjithmonë. Ndalimi është shumë më i lehtë dhe më pak i dhimbshëm; ka fjalë për fjalë dhjetëra mijëra raste në të cilat reduktimi ka dështuar.

Problemi i ndalimit nuk është varësia ndaj dopaminës, e cila është e lehtë për t'u përballuar. Është besimi i gabuar se pornografia të jep kënaqësi, e shkaktuar fillimisht nga shpëlarja e trurit e marrë përpara se të fillonim përdorimin, e përforcuar më tej nga varësia aktuale. Gjithçka që bën pakësimi është të përforcojë më tej gabimin, deri në atë masë që pornografia dominon plotësisht jetën e tyre dhe i bind se gjëja më e çmuar në tokë është varësia e tyre.

Një pjesë e vogël e rasteve që kanë sukses janë arritur nga një periudhë relativisht e shkurtër e pakësimit, e ndjekur nga "gjeli i ftohtë". Këta përdorues u ndalën pavarësisht pakësimit, jo për shkak të tij. Gjithçka që bëri ishte zgjatja e agonisë, përpjekjet e dështuara duke i lënë përdoruesit nervozë dhe akoma më të bindur se janë të lidhur për jetën. Kjo zakonisht është e mjaftueshme për t'i mbajtur ata të kthehen në haremin e tyre në internet për kënaqësi dhe mbështetje, ose të paktën për një shtrirje tjetër përpara përpjekjes së radhës.

Megjithatë, pakësimi ndihmon për të ilustruar kotësinë e pornografisë, duke demonstruar qartë se vizitat në harem nuk janë të këndshme pas periudhave të abstinencës. Ju duhet të përplasni kokën pas një muri me tulla (vuani nga dhimbjet e tërheqjes) në mënyrë që ta bëni atë të këndshme kur ndaloni. Prandaj, zgjedhjet janë:

1. Pakësimi për jetën dhe vuajtja e torturave të vetë-imponuara, të cilat gjithsesi nuk do të jeni në gjendje ta bëni.

2. Të torturosh gjithnjë e më shumë veten për gjithë jetën, gjë që është e pakuptimtë.

3. Të jesh i sjellshëm me veten dhe të heqësh pornografinë fare.

Aspekti tjetër që tregon se pakësimi demonstron se nuk ka gjë të tillë si vizita e çuditshme ose e rastësishme në harem. Pornografia në internet është një reaksion zinxhir që do të zgjasë pjesën tjetër të jetës nëse nuk bëni një përpjekje pozitive për ta thyer atë.

**Mos harroni: pakësimi do t'ju tërheqë poshtë.**
