# Vetëm një vështrim

"Vetëm një shikim" është një mit që duhet ta hiqni nga mendja:

- Është *vetëm një vështrim* që na bën të fillojmë në radhë të parë.

- Është *vetëm një vështrim* për të na vënë mbi një pjesë të vështirë ose në një rast të veçantë që mposht shumicën e përpjekjeve tona për të ndaluar.

- Është *vetëm një vështrim* që pasi kemi arritur të largojmë varësinë, na kthen përsëri në kurth. Ndonjëherë është thjesht për të konfirmuar se ata nuk kanë më nevojë për pornografi dhe një vizitë në harem e bën këtë.

Pasojat e pornografisë do të jenë të tmerrshme dhe do ta bindin përdoruesin se nuk do të fiksohen më kurrë – por tashmë janë. Përdoruesi mendon se diçka që i bën ata kaq të mjerë dhe fajtorë nuk duhet t'i kishte bërë ta bëjnë këtë, por e bëri.

Është mendimi i 'një sesioni special' që shpesh i pengon përdoruesit të ndalojnë, ai pas udhëtimit tuaj të gjatë në konferencë, ditës së vështirë në punë, grindjeve me fëmijët ose incidentit ku partneri juaj ju refuzon për seks. Merreni ***fort*** në mendjen tuaj se nuk ka gjë të tillë si 'vetëm një shikim'. Është një reaksion zinxhir që do të zgjasë pjesën tjetër të jetës nëse nuk prishet. Miti rreth rastit të çuditshëm dhe të veçantë i mban përdoruesit të lagësht pasi ndalojnë. Bëhuni zakon që të mos e shihni kurrë seancën "jo e madhe", është fantazi. Kurdoherë që mendoni për pornografinë, shihni një jetë të ndyrë duke kaluar pas një ekrani për privilegjin e shkatërrimit të vetes mendërisht dhe fizikisht - një jetë skllavërie dhe dëshpërimi. Nuk është krim nëse ereksionet tuaja nuk janë të besueshme, por është kur mund të jeni më të lumtur për një kohë të gjatë, por zgjidhni ta sakrifikoni atë për "kënaqësi" afatshkurtër.

Është në rregull që nuk mund të gjejmë gjithmonë ‘diçka për të bërë’ për zbrazëtinë; ta bësh këtë nuk është realisht e mundur në çdo rast për gjithë jetën tonë. Ne mund të planifikojmë për shumicën prej tyre, por ndonjëherë ndodh. Kohët e mira dhe të këqija ndodhin gjithashtu, pavarësisht nga pornografia. Por futeni qartë në mendjen tuaj, pornografia nuk është ajo. Ju jeni të mbërthyer ose me një jetë mjerimi ose aspak. Ju nuk do të ëndërronit të merrni cianid vetëm sepse ju pëlqente shija e bajameve, kështu që ndaloni së ndëshkuari veten me seancat e rastësishme 'jo-big-deal'. Pyete një përdorues me probleme, "*Nëse do të kishe mundësinë të ktheheshe në kohën para se të tëriheshe, a do të ishe bërë përdorues?*" Përgjigja është në mënyrë të pashmangshme, "*Duhet të bësh shaka!*" Megjithatë, çdo përdorues e ka atë zgjedhje çdo ditë të jetës së tyre, kështu që pse nuk e zgjedhin atë? Përgjigja është frika, frika se ata nuk mund të ndalojnë ose se jeta nuk do të jetë e njëjtë pa të.

Mos u tallni me veten! Ju mund ta bëni atë, çdokush mundet. Është qesharake e lehtë, por për ta bërë atë të tillë, ka disa baza për të qartësuar në mendjen tuaj.

1. Nuk ka asgjë për të hequr dorë, vetëm përfitime të mrekullueshme pozitive për të arritur.

2. Asnjëherë mos e bind veten për seancën e çuditshme "jo-big-deal" ose "vetëm një shikim". Nuk ekziston. Ka vetëm një jetë të ndyrë dhe skllavëri.

3. Nuk ka asgjë të ndryshme tek ju; çdo përdorues mund ta ketë të lehtë të ndalojë.

Shumë përdorues besojnë se ata janë të varur të konfirmuar ose kanë personalitete të varur. Kjo zakonisht ndodh si rezultat i leximit të sasive të tepërta të neuroshkencës tronditëse. Nuk ka një gjë të tillë, askush nuk ka lindur me nevojën për të masturbuar në videoklipe para se të fiksohej. Është droga që ju ngërthen, jo natyra e karakterit apo personalitetit tuaj. Natyra e stimulit supernormal të varur ju bën të besoni se ky është rasti. Megjithatë, është thelbësore të hiqni këtë besim, sepse nëse besoni se jeni të varur, do të jeni, edhe pasi përbindëshi i vogël në trupin tuaj të ketë vdekur prej kohësh. Është thelbësore për të hequr të gjithë këtë shpëlarje truri.
