# Përdorues të rastësishëm

Përdoruesit e rëndë priren të kenë zili përdoruesin e rastësishëm të pornografisë. Të gjithë i kemi takuar këta personazhe: "*Oh, mund të shkoj gjithë javën pa një seancë, nuk më shqetëson vërtet.*" Do të dëshironim të ishim të tillë. Kjo mund të jetë e vështirë të besohet, por asnjë përdorues nuk kënaqet të jetë përdorues. Kurrë nuk harrojmë:


|   *Asnjë përdorues nuk ka vendosur ndonjëherë të bëhet i tillë, i rastësishëm apo ndryshe, **prandaj,** *

|       *Të gjithë përdoruesit ndihen budallenj, **prandaj,** *

|         *Të gjithë përdoruesit duhet të gënjejnë veten dhe të tjerët në një përpjekje të kotë për të justifikuar marrëzinë e tyre.*


Fanatikët e golfit mburren se sa shpesh luajnë dhe duan të luajnë, kështu që pse përdoruesit mburren se sa pak masturbojnë? Nëse ky është kriteri i vërtetë, atëherë me siguri që vlerësimi nuk është aspak masturbues, apo jo?

Nëse dikush do t'ju thoshte: "*Mund të shkoj gjithë javën pa karota dhe nuk më shqetëson aspak*", do të mendonit se po flisnit me një arrë. Nëse më pëlqenin karotat, pse do të doja të shkoja gjithë javën pa to? Nëse nuk i kam shijuar, pse do të bëja një deklaratë të tillë? Pra, kur një përdorues bën një koment në lidhje me mbijetesën e një jave pa një seancë, ai po përpiqet të bindë veten — dhe ju — se nuk e kanë problem. Por nuk do të kishte nevojë të bënin një deklaratë nëse nuk do të kishin problem. Përkthyer, ky koment është "*Kam arritur të mbijetoj një javë të tërë pa pornografi.*" Si çdo përdorues, duke shpresuar se pas kësaj ata mund të mbijetojnë pjesën tjetër të jetës së tyre. Nëse mund të mbijetoni vetëm një javë, a mund ta imagjinoni se sa e çmuar duhet të ketë qenë seanca më pas, duke u ndjerë i privuar për një javë të tërë?

Kjo është arsyeja pse përdoruesit e rastësishëm janë efektivisht më të fiksuar sesa përdoruesit e rëndë. Jo vetëm që iluzioni i kënaqësisë është më i madh, por ata kanë më pak nxitje për ta lënë sepse shpenzojnë më pak kohë për të dhe për këtë arsye janë më pak të prekshëm ndaj rreziqeve shëndetësore. Herë pas here, ata mund të përjetojnë mosfunksionim seksual, por nuk janë të sigurt se çfarë e ka shkaktuar atë dhe kështu fajësohet për faktorë të tjerë. Mos harroni, e vetmja kënaqësi që përdoruesit marrin është në ciklin e kërkimit dhe kërkimit të dopaminës dhe lehtësimin e dhimbjeve të tërheqjes, siç është shpjeguar tashmë. Kënaqësia është një iluzion - imagjinoni përbindëshin e vogël pornografik si një kruarje thuajse të padukshme, për të cilën mbetemi të pavetëdijshëm shumicën e kohës.

Nëse keni një kruarje të përhershme, prirja natyrale është ta gërvishtni atë. Teksa qarqet e shpërblimit bëhen gjithnjë e më imun ndaj dopaminës dhe opioideve, tendenca e natyrshme është që të përkeqësohet, të përshkallëzohet, të hahet, të kërkojë risi, të kërkojë tronditje, etj. Ka katër faktorë kryesorë që i pengojnë përdoruesit të shikojnë zinxhir.

**Koha.**
Shumica nuk mund të përballojnë.

**Shëndeti.**
Për të lehtësuar kruajtjen, duhet të konsumojmë të gjithë materialin falas që kemi në dispozicion dhe pas disa. Kapaciteti për të përballuar atë lloj të tepruar ndryshon me secilin individ, dhe në periudha të ndryshme dhe situata të ndryshme në jetën e tyre. Kjo vepron si një kufizim automatik.

**Disiplina.**
Disiplina imponohet nga shoqëria, nga puna e përdoruesit, miqtë dhe të afërmit, ose ndoshta edhe nga vetë përdoruesi si rezultat i tërheqjes natyrore që ndodh në mendjen e çdo përdoruesi.

**Imagjinata.**
Mungesa e imagjinatës zvogëlon tronditjen, risinë dhe vlerat e tjera të klipit mbi baza subjektive.

Është e lehtë të mendosh për përdoruesit "jo rastësor" si të dobët, të paaftë për të kuptuar pse të tjerët janë në gjendje të kufizojnë "marrjen" e tyre. Sidoqoftë, përdoruesit e rëndë duhet të kenë parasysh se shumica e përdoruesve të rastësishëm janë thjesht të paaftë për të parë zinxhir, gjë që kërkon imagjinatë dhe qëndrueshmëri shumë të fortë. Disa nga këta përdorues një herë në javë, të cilëve përdoruesit e rëndë priren t'i kenë zili, janë fizikisht të paaftë për të bërë më shumë, ose sepse puna e tyre, shoqëria ose urrejtja e tyre për t'u lidhur nuk do t'ua lejojë këtë.

Mund të jetë e dobishme të jepen disa përkufizime.

**Jo-përdoruesi **

Dikush që nuk ka rënë kurrë pre e kurthit, por nuk duhet të jetë i vetëkënaqur. Ata janë jo-përdorues vetëm nga fati ose hiri i mirësisë. Të gjithë përdoruesit ishin të bindur se nuk do të lidheshin kurrë dhe disa jopërdorues vazhdojnë të provojnë një seancë të rastësishme.

**Përdoruesi i rastësishëm**

Nga të cilat ekzistojnë dy klasifikime bazë:

1. Përdoruesi që ka rënë në kurth, por nuk e kupton - mos i keni zili përdoruesit e tillë. Ata thjesht po marrin mostra nga nektari në grykën e shtambës dhe me shumë gjasa së shpejti do të jenë përdorues të rëndë. Mbani mend, ashtu si të gjithë alkoolistët filluan si pijanec të rastësishëm, po ashtu edhe të gjithë përdoruesit fillojnë rastësisht.

2. Përdoruesi që më parë ishte përdorues i rëndë dhe kështu mendon se nuk mund të ndalet. Këta përdorues janë më të trishtuarit nga të gjithë dhe ndahen në kategori të ndryshme, secila kërkon komente të veçanta.

**Përdoruesi një herë në ditë**

Nëse ata gëzojnë të drejtën e tyre për orgazëm, pse të përdorin pornografinë në internet vetëm një herë në ditë? Nëse mund ta marrin ose ta lënë, pse të shqetësohen fare? Mbani mend, "zakoni" është - në fakt - të përplasësh kokën pas një muri për ta bërë atë të relaksohet kur ndalon. Përdoruesi një herë në ditë i lehtëson dhembjet e tërheqjes për më pak se një orë çdo ditë. Edhe pse të pavetëdijshëm, pjesën tjetër të ditës e kalojnë duke përplasur kokën pas këtij muri, duke e bërë këtë për pjesën më të madhe të jetës së tyre. Ata po përdorin një herë në ditë sepse nuk mund të rrezikojnë të kapen ose të ngatërrojnë shëndetin e tyre neurologjik. Është e lehtë të bindësh përdoruesin e rëndë se nuk i pëlqen, por shumë më e vështirë për të bindur një përdorues të rastësishëm. Kushdo që ka kaluar nëpër një përpjekje për të reduktuar do të dijë se kjo është tortura më e keqe nga të gjitha, dhe pothuajse e garantuar se do t'ju mbajë të varur për pjesën tjetër të jetës tuaj.

**Përdoruesi i refuzuar**

Ata kërkojnë të drejtën e orgazmës çdo ditë, por partneri i tyre seksual nuk është gjithmonë i lumtur ta përmbushë këtë kërkesë. Fillimisht, ata po përdorin pornografinë e internetit për të mbushur këtë boshllëk, por me marrjen e 'rrëshqitjes së ujit' emocionues ata janë të bllokuar në një cikël risish, tronditjesh, imazhesh supernormale, etj. Në fakt, ata janë të kënaqur me refuzimin e partnerit të tyre pasi ofron diçka si një justifikim. Nëse pornografia në internet ju jep kaq shumë, pse të shqetësoheni të keni një partner? Në vend të kësaj lirojini ato. Ata nuk po i shijojnë as seancat kur duhet të ‘mbajnë’ në mendje partnerin e tyre. Në një moment, ata po kërkojnë për partnerin e tyre të jetës reale për t'u dhënë atyre një justifikim për të hyrë në luginat e errëta të internetit.

**Përdoruesi i dietës pornografike**

I njohur gjithashtu si, "*Unë mund të ndaloj sa herë të dua. E kam bërë mijëra herë!"

Nëse ata mendojnë se mbajtja e dietës i ndihmon t'i krijojnë humorin për të zgjedhur partnerë, pse janë në dietë një herë në katër ditë? Askush nuk mund të parashikojë të ardhmen, dhe po sikur rasti i takimit të ndodhte një orë pas seancës suaj të planifikuar? Gjithashtu, nëse herë pas here ‘pastrimi i hidraulikës’ është i mirë për të lehtësuar tensionin, pse të mos kryeni hidraulik çdo ditë? Është vërtetuar se masturbimi nuk kërkohet për të mbajtur organet gjenitale të shëndetshme dhe pornografia në internet nuk kërkohet fare. Edhe nëse është kështu, asnjë ‘guru’ i artistit që ka lexuar për dëmtimin neurologjik nuk do të rekomandojë ndonjëherë shikimin e pornografisë super-stimuluese. E vërteta është se përdoruesi i dietës pornografike është ende i tëri. Edhe pse ata janë larguar nga varësia fizike, ata ende kanë mbetur me problemin kryesor të larjes së trurit. Ata shpresojnë çdo herë që do të ndalojnë për mirë, por së shpejti bien përsëri në të njëjtin kurth.

Shumica e përdoruesve në fakt i kanë zili këta ndalues ​​dhe fillestarë dhe mendojnë se sa "me fat" është ai që mban dietë që mund të kontrollojë përdorimin e tyre. Megjithatë, ata anashkalojnë faktin që dieta nuk po kontrollon përdorimin e tyre - kur ata janë duke përdorur, ata dëshirojnë që të mos ishin. Ata kalojnë nëpër sherr për të ndaluar, pastaj fillojnë të ndihen të privuar dhe bien përsëri në grackën, duke uruar që të mos e kishin bërë. Ata marrin më të keqen nga të dyja botët. Nëse mendoni për këtë, kjo është e vërtetë në jetën e përdoruesve kur lejohet të kenë një seancë - duke e marrë atë si të drejtë ose duke dashur që ata të mos e kishin. Pornografia bëhet e çmuar vetëm kur privohet. Sindroma e ‘frutit të ndaluar’ është një nga dilemat e tmerrshme për përdoruesit. Ata nuk mund të fitojnë kurrë, sepse janë duke mashtruar për një mit, një iluzion. Ka vetëm një mënyrë të vetme që ata mund të fitojnë, të ndalojnë fshirjen duke ndaluar pornografinë!

**Përdoruesi "Unë shikoj vetëm porno statike/të zbutur/e bërë në shtëpi"**

Po, të gjithë e bëjnë këtë si fillim, por a nuk është e mahnitshme se si vlera mesatare e goditjes së klipeve duket se rritet me shpejtësi, dhe para se ta kuptojmë ndihemi të privuar (tolerancë)? Risia mungon me pornografinë statike, kështu që ne paguajmë piperin për një filxhan me yndyrë dhe ecim poshtë rrëshqitjes së ujit drejt pakënaqësisë dhe fajit. Gjëja më e keqe që mund të bëni është të përdorni fotot e partnerit tuaj (me miratim, sigurisht) për masturbim. Pse? Sepse në këtë proces ju po rilidhni trurin tuaj për rrjedhjet e dopaminës të shkaktuara nga kërkimi, kërkimi dhe shumëllojshmëria. Kimikisht, uji pornografik që rrëshqet në tru po ndërton DeltaFosB, kështu që do ta gjeni veten duke pasur vështirësi kur të jeni me ta në kohë reale.

Një kurth tjetër në këtë kategori është pornografia 'amatore' dhe 'e bërë në shtëpi'. Shumica janë falsifikime dhe ju e dini këtë, plus gjithashtu nuk do të ndaleni në të parën që ju bie në sy, përkundrazi të vazhdoni të kërkoni dhe kërkoni. Mos harroni, nuk është vetëm orgazma që kërkon truri, por risia e gjuetisë që i jep rrëshqitjes së ujit emocionin e saj. Përmbajtja e pornografisë nuk është çështja - qoftë amatore apo profesionale - është rrjedhja e dopaminës në tru që shkakton ngritje të tolerancës dhe ngopjes. Pornografia shkatërron funksionimin normal të trurit, masturbimi ngatërron reagimin muskul-tru; Orgazma e vërshon trurin me opioidë dhe e bën më të lehtë rrugën për t'u ndjekur herën tjetër.

**Përdoruesi "Unë kam ndaluar, por kam një vështrim të rastësishëm" **

Në një farë mënyre, përdoruesit që shikojnë janë më patetikët nga të gjithë. Ose kalojnë jetën duke besuar se po privohen, ose më shpesh, vështrimi i herëpashershëm bëhet dy, duke rrëshqitur poshtë në shpatin e rrëshqitshëm, herët a vonë duke u kthyer në përdorues të rëndë. Ata përsëri kanë rënë në grackën në të cilën ranë në radhë të parë.

Ekzistojnë dy kategori të tjera përdoruesish të rastësishëm. E para është lloji që masturbohet ndaj imazheve ose klipeve të kasetave më të fundit të seksit të personazheve të famshëm që transmetojnë lajmet, ose diçka që ata "e kanë sjellë në shtëpi" nga shikimi i tyre "aksidental" në shkollë ose në punë. Këta njerëz janë me të vërtetë thjesht jo përdorues, por ata mendojnë se po humbasin. Ata duan të jenë pjesë e aksionit, ku shumica prej nesh e nisim në këtë mënyrë. Herën tjetër, vini re se pas një kohe personi i famshëm i fantazisë suaj nuk po e bën më për ju. Sa më i ‘paarritshëm’ objektivi i fantazisë suaj, aq më frustruese është tërheqja e orgazmës.

Kategoria e dytë ka fituar vëmendje kohët e fundit, e përshkruar më së miri duke përshkruar një rast të shpërndarë në internet.

Një grua profesioniste kishte lexuar histori pornografike në internet për shumë vite dhe nuk kishte përdorur kurrë më shumë ose më pak se një herë çdo natë. Rastësisht, ajo ishte një zonjë shumë e fortë. Shumica e përdoruesve do të pyesnin veten pse ajo donte të ndalonte në radhë të parë - duke theksuar me kënaqësi se nuk kishte rrezik të PIED, ose PE në rastin e saj (e pavërtetë). Ajo as që përdorte imazhe statike, historitë ishin shumë më të buta se çdo material që ata vetë përdorin në baza ditore.

Ata bëjnë gabim duke supozuar se përdoruesit e rastësishëm janë më të lumtur dhe më të kontrolluar. Ata mund të kenë më shumë kontroll, por sigurisht që nuk janë të lumtur. Në rastin e gruas, ajo nuk ishte e kënaqur me partnerin e saj dhe as me seksin e vërtetë, dhe shumë nervoz kur i përgjigjej streseve dhe tendosjeve të saj të përditshme. Më i afërmi dhe më i dashuri i saj nuk ishte në gjendje të kuptonte se çfarë po e shqetësonte. Edhe nëse ajo e bindi veten të mos kishte frikë nga përdorimi i saj nëpërmjet racionalizimit, ajo përsëri e gjeti veten të paaftë për të shijuar marrëdhënie reale që përfshijnë pa ndryshim ulje-ngritje. Qendra e shpërblimit të trurit të saj nuk ishte në gjendje të përdorte destresorët normalë të pranishëm në jetë si rezultat i përmbytjeve të përditshme të dopaminës. Rregullimi i mëvonshëm i receptorëve të trurit të saj e kishte bërë atë melankolike në shumicën e rrethanave. Ashtu si shumica, ajo kishte një frikë të madhe nga ana e errët e pornografisë dhe trajtimi i grave – para herës së saj të parë. Përfundimisht, ajo ra viktimë e shpëlarjes së trurit shoqëror dhe provoi faqen e saj të parë. Ndryshe nga shumica që kapitullojnë dhe bëhen përdorues zinxhirësh, duke parë videot e ndyra të dhunës, ajo i rezistoi rrëshqitjes.

Gjithçka që ju pëlqen ndonjëherë në pornografi është t'i jepni fund dëshirës që kishte filluar para saj, qoftë dëshira fizike pothuajse e padukshme, qoftë tortura mendore e të mos lejuarit të gërvish kruajtjen. Pornografia në internet në vetvete është helm, prandaj vuani iluzionin e shijimit të saj vetëm pas periudhave të abstinencës. Ngjashëm me urinë ose etjen, sa më gjatë ta vuani, aq më e madhe është kënaqësia kur të lehtësoheni përfundimisht. Bërja e gabimit për të besuar pornografinë është thjesht zakon, ata mendojnë: "*Nëse mund ta mbaj atë në një nivel të caktuar ose vetëm në raste të veçanta, truri dhe trupi im do ta pranojnë atë. Pastaj, unë mund të vazhdoj të përdor në atë nivel ose të zvogëloj më tej duhet të dëshiroj.*"

Kuptoni qartë në mendjen tuaj, "zakoni" nuk ekziston. Pornografia është varësi nga droga, me tendencën e natyrshme që të lehtësojë dhembjet e tërheqjes, duke mos i duruar ato. Për ta mbajtur atë në nivelin në të cilin jeni aktualisht, do t'ju kërkonte të ushtronit sasi të jashtëzakonshme disipline dhe vullneti për pjesën tjetër të jetës tuaj. Ndërsa qendra e shpërblimit të trurit tuaj bëhet tolerante ndaj dopaminës dhe opioideve, ajo dëshiron gjithnjë e më shumë, jo më pak e më pak.

Ndërsa pornografia fillon të shkatërrojë gradualisht sistemin tuaj nervor, guximin, besimin dhe kontrollet e impulsit, ju bëheni gjithnjë e më të paaftë për t'i rezistuar reduktimit të intervalit midis çdo seance. Kjo është arsyeja pse, në ditët e para, ne mund ta marrim ose ta lëmë atë. Nëse marrim një shenjë se diçka nuk shkon mendërisht ose fizikisht, ne thjesht ndalojmë. Mos e ki zili këtë grua – kur shikon vetëm një herë në njëzet e katër orë, duket se është gjëja më e çmuar në tokë, duke e kthyer pornografinë në një ‘frut të ndaluar’. Për shumë vite kjo grua e varfër ishte në qendër të një tërheqjeje lufte.

Ndonëse nuk mund ta ndalonte përdorimin, ajo u frikësua të përshkallëzohej në klipe të transmetimit. Për njëzet e tre orë e dhjetë minuta nga çdo ditë asaj iu desh të luftonte tundimin dhe mungesën e ndjenjave ndaj të dashurit të saj. U desh një vullnet i jashtëzakonshëm për të bërë atë që bëri, duke e bërë atë përfundimisht në lot. Raste të tilla janë të rralla, por shikojeni logjikisht: ose ka një patericë ose kënaqësi të vërtetë në pornografi, ose nuk ka. Nëse ka, kush dëshiron të presë një orë, një ditë apo edhe një javë? Pse duhet të privoheni nga mbështetja apo kënaqësia ndërkohë? Nëse nuk ka patericë apo kënaqësi të vërtetë, pse të shqetësoheni të bëni një vizitë në haremin tuaj online?

Këtu është një rast tjetër i një njeriu një herë në katër ditë, që e përshkruan jetën e tij si më poshtë:

> "*Unë jam dyzet vjeç, kam vuajtur PIED (disfunksion erektil të shkaktuar nga pornografia) me gra të vërteta dhe madje edhe kur përdor pornografi, që është në shumicën e rasteve. Ka kohë që kam pasur një ereksion të plotë. Më parë duke ndjekur dietën pornografike një në katër, flija i qetë gjatë gjithë natës pas seancës sime. Tani zgjohem çdo orë të natës dhe është gjithçka për të cilën mund të mendoj. Edhe kur fle, ëndërroj për klipet e mia të preferuara . Ditët pas seancës sime të planifikuar ndihem shumë i mërzitur, dieta më merr të gjithë energjinë. SO ime do të më linte të qetë sepse jam shumë keq dhe nëse ajo nuk mund të largohet, ajo nuk do të më pranojë. Unë shkoj për vrapim jashtë por mendja ime është e fiksuar pas saj.*
>
> "*Në ditën e planifikuar filloj të planifikoj më herët gjatë natës, duke u nervozuar shumë nëse ndodh diçka kundër planeve të mia. Do të tërhiqesha nga bisedat dhe do të dorëzohesha (vetëm për t'u penduar më vonë) në punë dhe në shtëpi. Nuk jam një djalë debatues, por nuk dua që tema apo biseda të më pengoje. Mbaj mend raste kur zgjidhja zënkat budallaqe me SO-në time. Pres orën dhjetë dhe kur mbërrin, duart më dridhen në mënyrë të pakontrolluar. Nuk e filloj veprën menjëherë — pasi ka video të reja që janë shtuar — dhe 'blerje'. Mendja ime më thotë se meqenëse kam mbajtur veten për katër ditë, meritoj një klip 'special' që duhet të ia vlej koha e shpenzuar për të kërkuar. Përfundimisht, pranoj një ose dy, por dua që të zgjasë në mënyrë që të mund të 'mbijetoj' gjatë katër ditëve të ardhshme, kështu që marr më shumë kohë për të përfunduar veprën.*"  

Përveç halleve të tjera, ky njeri i gjorë nuk e ka idenë se po e trajton veten me helm. Së pari, ai vuan nga "sindroma e frutave të ndaluara" dhe më pas e detyron trurin e tij të lajë dopaminën. Krahasues, receptorët e tij të dopaminës nuk janë aq të reduktuar, por ai po lyen rrëshqitjet e ujit pornografik, duke kërkuar, duke kërkuar për skajet, risinë, shumëllojshmërinë, tronditjen dhe ankthin në mënyrë që të mbijetojë katër ditët e ardhshme. Ju ndoshta e imagjinoni këtë njeri si një budalla patetik, por nuk është kështu. Si një ish-atlet dhe rreshter detar, ai nuk donte të bëhej i varur nga asgjë. Megjithatë, pas kthimit nga lufta ai u trajnua si teknik IT në një program rehabilitimi të veteranëve.

Kur hyri në fuqinë punëtore civile, ai ishte një profesionist i IT-së i paguar mirë në një bankë dhe iu dha një laptop për ta marrë në shtëpi. Ishte viti që socialistët e famshëm ‘rrudhën’ videot e tyre porno në internet dhe u fol shumë për këtë. Më pas ai u fiksua, duke kaluar pjesën tjetër të jetës së tij duke paguar përmes hundës dhe duke e shkatërruar veten fizikisht dhe mendërisht. Nëse ai do të ishte një kafshë, shoqëria do ta kishte nxjerrë prej kohësh nga mjerimi i tij, megjithatë ne ende lejojmë që adoleshentët e rinj të shëndetshëm mendërisht dhe fizikisht të fiksohen. Ju mund të mendoni se ky rast dhe shënimet janë të ekzagjeruara, por ky rast - edhe pse ekstrem - nuk është aspak unik. Ka dhjetëra mijëra histori të ngjashme. A mund të jeni i sigurt se asnjë nga miqtë dhe të njohurit e tij nuk e kishte zili që ishte një burrë një herë në katër? Nëse mendoni se kjo nuk mund t'ju ndodhte, **ndaloni së tallurit**.

**TASHMË PO NDODH.**

Ashtu si të varurit e tjerë, përdoruesit e pornografisë janë gënjeshtarë famëkeq, madje edhe për veten e tyre. Ata duhet të jenë. Shumica e përdoruesve të rastësishëm kënaqen shumë më shumë herë dhe në shumë më tepër raste sesa do ta pranojnë. Shumë biseda me të ashtuquajturit përdorues "dy herë në javë" do të pranojnë se e kanë bërë më shumë se tre ose katër herë atë javë. Lexoni historitë e reddit, NoFap dhe forumit të rindezjes nga përdoruesit e rastësishëm dhe do të zbuloni se ata ose po numërojnë ditë ose po presin të dështojnë. Ju nuk keni nevojë t'i keni zili përdoruesit e rastësishëm, dhe nuk keni nevojë t'i përdorni as ato, jeta është pafundësisht më e ëmbël pa të. Merrni regjistrin e mëposhtëm:

"*Filloi me një sfidë të thjeshtë për të mos prekur mbeturinat e mia për një ditë dhe të paaftë. Nuk mendoj më për masturbim, nuk më shkon në mendje. Kjo është e mundur, ju premtoj. Pasuritë që i presin ata. të cilët janë në gjendje - ata janë të jashtëzakonshëm.*"

Adoleshentët në përgjithësi janë më të vështirë për t'u kuruar, jo sepse e kanë më të vështirë të ndalojnë, por sepse nuk besojnë se janë të lidhur ose janë në fazat fillestare të kurthit, në përgjithësi vuajnë nga iluzioni që do të kenë automatikisht. u ndal para fazës së dytë.

Prindërit e fëmijëve që urrejnë pornografinë në internet nuk duhet të kenë një ndjenjë të rreme sigurie. Të gjithë fëmijët i urrejnë anët e errëta të pornografisë përpara se të tërhiqen. Në një moment, edhe ti. Mos u mashtroni as nga fushatat e frikësimit, kurthi është i njëjtë si gjithmonë. Fëmijët e dinë që pornografia në internet është një stimul supernormal, por ata gjithashtu e dinë se një "vizitë" ose "shikim" nuk do ta bëjë këtë. Në një fazë ata mund të ndikohen nga një partner, shok klase ose koleg pune.

Ju lutemi mos u bëni të vetëkënaqur në këtë çështje. Dështimi i shoqërisë për të parandaluar që adoleshentët të bëhen të varur nga pornografia në internet dhe droga të tjera është ndoshta aspekti më shqetësues i kësaj varësie. Truri i adoleshentëve është dukshëm më plastik dhe është i nevojshëm edukimi dhe mbrojtja e tyre. Nëse nuk jeni të sigurt se ku të filloni, burimet e mira përfshijnë librin YourBrainOnPorn.com për të edukuar veten mbi neuroshkencën. Edhe nëse dyshoni se adoleshenti juaj mund të jetë tashmë i varur, libri ofron kuptim themelor për të ndihmuar dikë që të arratiset. Përndryshe, rekomandojeni këtë libër!