# Një zakon social?

Shëndeti i mendjes dhe trupit janë arsyet kryesore pse ne *duhet* të duam të ndalemi – por më pas, ato kanë qenë gjithmonë. Ne në fakt nuk kemi nevojë për kërkime shkencore dhe njohuri në neuroshkencë për të na thënë se pornografia është e varur dhe potencialisht mund të shkatërrojë jetën tonë. Këta trupat tanë janë objektet më të sofistikuara në planet dhe çdo përdorues e di që në seancën e parë se stimuli mund të shkojë në tepricë dhe të bëhet helmues.

Arsyeja e vetme pse ne përfshihemi ndonjëherë me pornografinë është mbivendosja e ciklit me programimin tonë evolucionar. Pornografia në internet është shumë e disponueshme, falas dhe transmetohet njëzet e katër orë në ditë. Pornografia dikur konsiderohej e padëmshme, por kjo ishte kur imazhet ishin statike dhe videot përfshinin një udhëtim në dyqanin lokal për një kasetë VHS.

Sot, përgjithësisht konsiderohet - madje edhe nga vetë përdoruesit - se pornografia është një stimul supernormal dhe formues i varësisë. Në kohët e vjetra, i forti nuk e pranonte që masturbonte, me hov të cilin ishte një term nënçmues. Në çdo pub, klub apo bar, shumica e meshkujve do të donin me krenari të merrnin një grua në shtëpi dhe të bënin seks të vërtetë. Sot, pozicioni është krejtësisht i kundërt për të varurit nga pornografia në internet. Burri i sotëm e kupton se ka filluar të ndiejë se nuk ka nevojë për një grua. Duke u bashkuar në internet, ai diskuton përvojat, harton strategji dhe eksploron opsione. Burri i fortë i sotëm nuk dëshiron të varet nga droga. Përmes revolucionit social, të gjithë përdoruesit po mendojnë seriozisht për të ndaluar pornografinë në internet dhe masturbimin. Përdoruesit e sotëm e konsiderojnë pornografinë një aktivitet të padobishëm dhe të dëmshëm.

Trendi më domethënës që vihet re në forume është theksimi në rritjen e aspekteve antisociale të pornografisë, ditët kur një burrë mburrej se bënte seks dhe orgazma çdo ditë po zëvendësohet ngadalë me realizimin e skllavërisë ndaj përbindëshit të pornografisë.

Arsyeja e vetme pse njerëzit vazhdojnë pasi janë arsimuar është sepse ata nuk kanë arritur të ndalojnë ose janë shumë të frikësuar për të provuar. Ka një spektër të gjerë interesi për këtë temë, disa që abstenojnë nga pornografia, masturbimi dhe orgazma - me ose pa partnerë. Praktikat që ndajnë pjesët tantrike dhe përhapëse të seksit, si mbajtja e spermës dhe Karezza, diskutohen dhe miratohen në grup. Shumë dështime të lartpërmendura janë në të vërtetë bie-përpara, duke përfituar kështu disi njerëzit që i praktikojnë ato. Pasi të filloni rrugën pa PMO, do të gjeni përshtatjen më të mirë që vlen për jetën tuaj; është e inkurajuar që të krijoni planin tuaj për orgazmat pasi të keni kuptuar dhe praktikuar ndarjen seksuale. Cilado qoftë rruga juaj, do të shihni vlerë në kufizimin e numrit të herëve që e shpërlani trurin tuaj me kimikate përmes orgazmës dhe kurrë nuk do ta shihni më pornografinë, seksin dhe orgazmën si një kënaqësi apo mbështetje për veten tuaj emocionale.

Komunitete të ndryshme të njohura në internet të themeluara nga jo-përdorues janë të përkushtuar për të lënë jo vetëm pornografinë, por edhe masturbimin. Këto vende janë në fund të fundit të dobishme për ata që ikin, por shumica e shënimeve i tregojnë ata të provojnë vullnetin. Pasoja e obsesionit me vargjet e abstinencës dhe masave të tjera është keqardhja për veten dhe mungesa e ngazëllimit. Pjesa më e madhe e shpëlarjes së trurit mbetet e gjallë dhe e mirë. Përfundimisht, dikush prishet dhe ndodh një efekt domino, përdoruesit e tjerë zbulojnë se nuk janë të vetmit. Megjithatë, përpjekjet e tyre nuk janë të kota, ata po bien përpara, megjithëse me shumë vetë-torturime pasi mbyllin shfletuesit e tyre, por jo dëshirën dhe nevojën. EasyPeasy funksionon në të kundërt, duke mbyllur së pari nevojën dhe dëshirën, përpara se të mbyllë shfletuesin. Çdo ditë e më shumë përdorues largohen nga anija që po fundoset dhe ata që mbeten në të tmerrohen se do të jenë të fundit.

**MOS E LËR TË JESH TI!**