# Koha

Përveç pikës së dukshme që nuk ju bën mirë dhe se tani është koha e duhur për të ndaluar, koha është e rëndësishme. Shoqëria e trajton pornografinë në internet në mënyrë të pahijshme si një zakon paksa të pakëndshëm që nuk dëmton shëndetin tuaj. Kjo është e pavërtetë. Është varësia nga droga, një sëmundje dhe shkatërruese e marrëdhënieve në shoqëri. Gjëja më e keqe që ndodh në jetën e shumicës së përdoruesve është të fiksohen pas kësaj varësie të tmerrshme. Nëse qëndrojnë të lidhur, ndodhin gjëra të tmerrshme. Prandaj, koha është e rëndësishme për t'i dhënë vetes të drejtën për një shërim të duhur.

Së pari, identifikoni kohët ose rastet kur pornografia duket të jetë e rëndësishme për ju. Nëse jeni një biznesmen që e përdorni atë për iluzionin e lehtësimit të stresit - zgjidhni një periudhë relativisht të lirë ose një pushim. Nëse përdorni pornografi kryesisht gjatë periudhave të mërzitshme ose relaksuese, vlen e kundërta. Pavarësisht, merrni seriozisht përpjekjen dhe bëjeni atë gjënë më të rëndësishme në jetën tuaj.

Shikoni përpara për një periudhë prej tre javësh dhe përpiquni të parashikoni çdo ngjarje që mund të çojë në dështim. Raste si udhëtimet në konferenca, partneri juaj jashtë qytetit, etj., nuk duhet t'ju pengojnë, me kusht që t'i parashikoni ato paraprakisht dhe të mos mendoni se do të privoheni. Mos u përpiqni të shkurtoni ndërkohë, pasi kjo do të krijojë vetëm iluzionin se mohimi është i këndshëm. Në fakt, ju ndihmon të detyroni veten të shikoni dhe të keni sa më shumë seanca pornografike. Ndërsa jeni duke bërë seancën e fundit dhe herën tuaj të fundit, jini të vetëdijshëm për zhgënjimin për shkak të ngopjes, pritshmërive të paplotësuara, çdo dhimbje trupore, efektet e tërheqjes, nervozizmin dhe melankolinë. Mendoni se sa e mrekullueshme do të jetë kur t'i lejoni vetes të ndaloni së bëri atë.

**ÇDO TË BËNI, MOS BINI NË GRACKËN E THJESHT TË THËNIT, "JO TANI, MË VONË" DHE TA SHQYRNI NGA MENDJA. PËRFUNDONI TANI DHE PRITNI ATË.**

Mbani mend, *nuk po hiqni dorë nga asgjë*. Përkundrazi, ju do të merrni përfitime të mrekullueshme pozitive.

Për vite me radhë, profesioni mjekësor e ka parë pornografinë si të padëmshme pa e ditur dallimin midis pornografisë statike të zbutur të dikurshme dhe përvojës më të fundit të transmetimit të realitetit virtual. Problemi është se megjithëse çdo përdorues konsumon pornografi në internet thjesht për të lehtësuar dëshirën për dopaminë të shkaktuar prej saj, nuk është varësia ndaj kimikateve që e ngërthen përdoruesin, por vetë-larja e trurit që rezulton nga varësia. Një person inteligjent do të bjerë pas një mashtrimi të vetëbesimit, por vetëm një budalla do të vazhdojë ta pranojë atë pasi ta kuptojë mashtrimin. Për fat të mirë, shumica e përdoruesve nuk janë budallenj, ata vetëm mendojnë se janë. Çdo përdorues individual ka lavazhin e tij privat të trurit. Kjo është arsyeja pse duket se ka një gamë kaq të larmishme llojesh të varur, që shërben vetëm për të komplikuar më tej misteret.

Ndërsa përfitimi i librit origjinal ishte lënia e nikotinës (një nga drogat më të shpejta dhe më të varura të njohura për njeriun), ishte befasuese të kuptosh se filozofia e propozuar në librin origjinal është ende e shëndoshë kur përshtatet. Njohuria dhe sfida e grumbulluar që Carr dhe unë marrim përsipër është se si t'ia komunikojmë atë njohuri çdo përdoruesi individual. Fakti që unë e di që çdo përdorues jo vetëm që mund ta ketë të lehtë të ndalojë, por mund ta shijojë në të vërtetë procesin, nuk është vetëm i pakuptimtë, por jashtëzakonisht frustrues, nëse përdoruesi nuk mund të detyrohet ta kuptojë atë. Në librin e tij origjinal, Allen Carr shpjegon këshillat e tij të diskutueshme:

>"Shumë njerëz më kanë thënë: *'Ti thua, "Vazhdo të pish duhan derisa të mbarosh librin." Kjo ka tendencë që duhanpirësit t'i duhen mosha për ta lexuar librin ose thjesht të mos e mbarojë atë. Periudha. Prandaj, duhet të ndryshoni udhëzimin.'* Kjo tingëllon logjike, por unë e di nëse udhëzimi do të ishte: *'Ndaloni menjëherë'*, disa duhanpirës as nuk do të fillonin të lexonin librin. Unë kisha një duhanpirës të konsultohej me mua në ditët e para. Ai tha, *'Më vjen shumë keq që duhet të kërkoj ndihmën tuaj, e di që kam vullnet të fortë. Në çdo fushë tjetër të jetës sime e kam kontrollin. Pse të gjithë këta duhanpirës të tjerë e lënë duhanin duke përdorur vullnetin e tyre, por unë kam për të ardhur tek ju?'* Ai vazhdoi, *'Mendoj se mund ta bëja vetë, nëse do të mund të pija duhan ndërsa po e bëja.'\"*

Besimi shoqëror dikton se ndalimi i pirjes së duhanit është tepër i vështirë, kështu që çfarë i nevojitet një duhanpirësi kur diçka është e vështirë? Miku ynë i vogël, mbështetja jonë. Ikja nga duhanpirja duket të jetë një goditje e dyfishtë: jo vetëm që ka një detyrë të vështirë për t'u kryer - e cila është mjaft e vështirë - por mbështetja në të cilën zakonisht mbështetemi për raste të tilla nuk është e disponueshme. Ndoshta e bukura e vërtetë e kësaj metode është se ju nuk keni nevojë të ‘dorëzoheni’ gjatë procesit. Në vend të kësaj, ne i heqim qafe të gjitha frikërat dhe dyshimet fillimisht, kështu që me mbarimin e seancës përfundimtare ju tashmë po shijoni lirinë.

Prandaj, ky hackbook do të mbajë të njëjtat këshilla të paprekura. Pavarësisht se sa shumë thuhet se do të jetë e lehtë dhe e këndshme, do të ketë një shumicë dërrmuese që nuk do të jetë në gjendje ta pranojë atë për shkak të larjes së trurit personal se sa e vështirë është lënia.

Koha është i vetmi kapitull që më bën të vë në dyshim seriozisht këshillën origjinale të Allen. Mbi të gjitha, nëse shkaktarët përfshijnë stresin në zyrë, atëherë zgjedhja e një pushimi për të bërë një përpjekje dhe anasjelltas. Kjo nuk është mënyra më e lehtë, përkundrazi zgjidhni atë që e konsideroni kohën më *të vështirë*. Qoftë ky stres, detyrime sociale, përqendrim apo mërzitje, pasi të keni vërtetuar se përballeni dhe shijoni jetën në situatat më të këqija, çdo tjetër është e këndshme. Por nëse kjo do të ishte këshilla, a do ta bënit këtë përpjekje?

Këtu është një analogji. Unë dhe motra ime kemi ndërmend të notojmë së bashku. Ne mbërrijmë në pishinë në të njëjtën kohë, por rrallë përfundojmë duke notuar së bashku. Arsyeja është se ajo zhyt një gisht dhe gjysmë ore më vonë është në fakt noti. Kjo është torturë e ngadaltë. Unë e di paraprakisht se në një fazë, sado i ftohtë të jetë uji, do të më duhet ta përballoj atë në një moment. Kështu që unë kam mësuar ta bëj atë në mënyrën më të lehtë: të zhytesha direkt. Tani, imagjinoni nëse do të isha në gjendje të insistoja që nëse ajo nuk zhytej direkt, ajo nuk mund të notonte. Nëse do të ishte kështu, ajo nuk do të notonte fare. E shihni problemin?

Nga reagimet, shumë përdorues kanë përdorur këshillat origjinale të kohës për të vonuar atë që ata mendojnë se do të jetë 'dita e keqe'. Mendimet e mia të radhës ishin duke përdorur një teknikë të ngjashme me kapitullin 'përparësitë e pornografisë', diçka si — *"Koha është shumë e rëndësishme dhe në kapitullin tjetër do të këshilloheni për kohën më të mirë për të bërë përpjekje."* dhe mbi faqjen tjetër ka vetëm një *"TANI!"* Kjo është në fakt, këshilla më e mirë, por a do ta pranonit? Ndoshta aspekti më delikat i kurthit është se kur kemi stres të vërtetë në jetën tonë, nuk është koha e duhur për të ndaluar, por në momente pa stres, ne nuk kemi dëshirë t'i japim fund torturës. Bëjini vetes pyetjet e mëposhtme:

1. Kur u futët në pornografi për herë të parë, a keni vendosur vërtet që do të vazhdonit të vareshit nga ajo për pjesën tjetër të jetës tuaj pa qenë në gjendje të ndaleni kurrë? ***Sigurisht që nuk e keni bërë!***

2. A do të vazhdoni pjesën tjetër të jetës tuaj pa qenë në gjendje të ndaloni kurrë? ***Sigurisht që nuk jeni!***

Pra, kur do të ndaloni? Nesër? Vitin tjeter? Vitin pas? A nuk është kjo ajo që e keni pyetur veten që kur kuptove për herë të parë se ishe i tëri? A po shpresoni se një mëngjes do të zgjoheni dhe thjesht nuk do të dëshironi të shikoni më? Ndaloni të tallni veten, me çdo varësi, ju fiksoheni gradualisht më shumë, jo më pak. A do të prisni derisa të filloni të mendoni se të ngriheni nga shtrati është më e vështirë sesa thjesht të masturboheni? Kjo do të ishte pak e kotë.

Kurthi i vërtetë është besimi se tani nuk është koha e duhur – do të jetë gjithmonë më e lehtë nesër. Ne besojmë se jetojmë jetë stresuese, por në fakt jo. Pjesa më e madhe e stresit të vërtetë është hequr nga jeta jonë. Kur largoheni nga shtëpia, nuk jetoni me frikën se mos sulmoheni nga kafshët e egra, shumica nuk e pyesin veten se nga do t'u vijë vakti i radhës, ose nëse do të jetë një çati mbi kokën e tyre sonte. Mendoni për jetën e një kafshe të egër, sa herë që një lepur del nga strofulla e tij, ai përballet me Vietnamin gjatë gjithë jetës së tij. Por lepuri e trajton atë, ka adrenalinë dhe hormone të tjera, dhe ne po ashtu. E vërteta është se periudhat më stresuese për jetën e çdo krijese janë fëmijëria e hershme dhe adoleshenca. Por tre miliardë vjet seleksionim natyror na ka pajisur për të përballuar stresin dhe shumë që rriten me fëmijëri të vështira bëjnë jetë normale.

Është klishe të thuash, *"Nëse nuk e ke shëndetin, nuk ke asgjë"* por është absolutisht e vërtetë. Kur ndihesh i fortë fizikisht dhe mendërisht, mund të kënaqesh me kulmin dhe të përballosh të ulëtat. Shumë ngatërrojnë përgjegjësinë me stresin; Përgjegjësia bëhet stresuese vetëm kur nuk ndihemi mjaftueshëm të fortë për ta përballuar atë. Ajo që shkatërron më shumë nuk është stresi, puna apo pleqëria, por patericat iluzore, të gënjyera ku ata kthehen.

Shikojeni në këtë mënyrë - ju tashmë keni vendosur që nuk do të qëndroni në kurth për pjesën tjetër të jetës tuaj. Prandaj, në një moment - pavarësisht nëse e keni të lehtë apo të vështirë - do t'ju duhet të kaloni përmes procesit të çlirimit. Pornografia nuk është zakon apo kënaqësi, është varësi nga droga dhe sëmundje. Ne kemi vërtetuar se jo të jetë më e lehtë nesër, por do të përkeqësohet gradualisht. Koha për ta hequr qafe është **tani** — ose aq afër tani sa mund ta menaxhoni. Vetëm mendoni se sa shpejt kalon çdo javë e jetës sonë. Kaq duhet. Mendoni se sa bukur do të jetë të shijoni pjesën tjetër të jetës tuaj pa hije gjithnjë në rritje të varur mbi ju. Me kusht që të ndiqni të gjitha udhëzimet, nuk do t'ju duhet as të prisni pesë ditë ose tre javë. Jo vetëm që do ta keni të lehtë të hiqni dorë, **Do të kënaqeni!**
