# A do të më mungojë argëtimi?

**Jo!** Sapo përbindëshi i vogël pornografik të ketë vdekur, pasi trupi juaj pushon së dëshiruari dopaminën dhe uji i pornografisë që rrëshqet në trurin tuaj fillon të zbehet me shpejtësi për shkak të mungesës së 'lyrimit', çdo shpëlarje truri e mbetur do të zhduket. Jo vetëm që do ta gjeni veten fizikisht dhe mendërisht më të pajisur për të përballuar streset dhe sforcimet e jetës, por do të shijoni në maksimum momentet e mira.

Ekziston vetëm një rrezik, ai është ndikimi i atyre që ende e përdorin seksin si mbështetje dhe kënaqësi. *'Bari i tjetrit është gjithmonë më i gjelbër'* është e zakonshme në shumë aspekte të jetës sonë dhe lehtësisht e kuptueshme. Pse në rastin e pornografisë – me disavantazhe kaq të mëdha kur krahasohen me ‘përparësitë’ iluzionare – ish-përdoruesi tenton t’i ketë zili ata që kërkojnë seks dhe pornografi si mbështetje?

Me gjithë shpëlarjen e trurit nga fëmijëria, është mjaft e kuptueshme që kemi rënë në grackën. Pse atëherë – pasi kuptojmë se çfarë është pornografia e një loje me turi dhe arrijmë ta heqim këtë zakon – që ne të kthehemi drejt e në të njëjtin kurth? Është ndikimi i shpëlarjes së trurit shoqëror që ngatërron pornografinë me seksin, i paraqitur si normal. Ish-përdoruesi ka një dhimbje! Ndjenjat e pasigurta të zbrazëtisë së tyre duke qenë beqarë (që nuk është krim gjithsesi) shkakton ndjenja ankthi dhe i shtyn ata të hipin në rrëshqitësin e ujit. Kjo është me të vërtetë një anomali kurioze, veçanërisht nëse merret parasysh ky vëzhgim: jo vetëm që çdo jo-përdorues në botë është i lumtur që është i tillë, por çdo përdorues në botë, edhe me mendjen e tij të deformuar, të varur, të shpëlarë trurin që vuan mashtrimin e kënaqësisë ose relaksim, uroj që në radhë të parë të mos fiksoheshin kurrë. Pra, pse i kanë zili disa ish-përdorues?

1. 'Vetëm një vështrim.' Mbani mend, nuk ekziston. Mos e shihni rastin e veçuar dhe filloni ta shikoni nga këndvështrimi i përdoruesit të pornografisë. Ju mund t'i keni zili, por ata nuk e miratojnë veten dhe ju kanë zili. Sikur të mund të shikonit disi klinikisht një përdorues tjetër, pasi ata mund të jenë nxitësi më i fuqishëm nga të gjithë për t'ju ndihmuar të dilni prej tij. Vini re se sa shpejt hapin shumë skeda dhe dritare të shfletuesit? Përcjellja e shpejtë në seksionet e rëndësishme, mërzitja e shpejtë nga klipet dhe kalimi nëpër gamën e zhanreve që prodhojnë risi, tronditje, ankth, etj. Vini re veçanërisht se akti duket të jetë automatik. Mos harroni - ata nuk po e shijojnë atë, është se nuk mund të kënaqen pa të. Të nesërmen në mëngjes, duke u zgjuar me një vullnet të dobësuar, energji të humbur dhe sy të zymtë, ata do të duhet të vazhdojnë të mbyten në shfaqjen e parë të stresit dhe tendosjes. Ata po përballen me një jetë të ndyrë, shëndet të dobët mendor dhe vetëbesim të njollosur - një jetë të tërë duke e shkatërruar veten me hije të zeza në fund të mendjes së tyre. Për të arritur çfarë qëllimi? Iluzioni që po merrni atë që ‘meritoni’ dhe kënaqësinë e mallkuar?

2. Arsyeja e dytë që disa ish-përdorues kanë dhimbje është sepse përdoruesi i pornografisë është duke bërë diçka - si p.sh. vetëkënaqësi - dhe jo-përdoruesi nuk është, kështu që ata priren të ndihen të privuar. Kuptoni qartë në mendjen tuaj, nuk është jo-përdoruesi ai që po privohet, por i varuri i varfër ai që po privohet nga:

    - Shëndeti

    - Energjia

    - Besimi

    - Paqe e mendjes

    - Guxim

    - Qetësi

    - Liria

    - Respekt për veten

Hiqni zakonin për t'i pasur zili përdoruesit e pornografisë dhe filloni t'i shihni ata si krijesat e mjera dhe patetike që janë në të vërtetë. E di, dikur kam qenë një nga më të këqijtë. Kjo është arsyeja pse ju po e lexoni këtë libër dhe jo ata që nuk mund ta përballojnë atë dhe vazhdojnë të bëjnë shaka.

Ju nuk do ta kishit zili një të varur nga heroina, dhe si çdo varësi ndaj drogës, edhe e juaja nuk do të përmirësohet. Çdo vit do të përkeqësohet në mënyrë eksponenciale – nëse nuk ju pëlqen të jeni përdorues sot, do ta shijoni edhe më pak nesër. Mos i keni zili përdoruesit e tjerë, mëshirojini ata. Më besoni: ***Ata kanë nevojë për keqardhjen tuaj!***
