# A mund të ndahem?

Ky mit është përhapur kryesisht nga përdoruesit që përpiqen të ndalen në metodën e vullnetit, të cilët kryejnë gjimnastikë mendore dhe fillojnë një rutinë Jekyll-and-Hyde: "*Pornografia është për alter egon time dhe romanca e jetës reale është për anën time të marrëdhënies.*". Asgjë nuk është më larg nga e vërteta – rrëshqitjet e ujit pornografikë, DeltaFosB dhe ndryshimet neurologjike do të kapërcejnë romancën e jetës reale, duke e bërë atë më pak të dëshirueshme. Zoti Hyde patjetër do të anulojë udhëzimet e Dr Jekyll.

Nëse përdorni pornografi në internet, ju jeni duke e trajnuar veten për rolin e sodit, ose kërkoni mundësinë e klikimit për diçka më eksituese me rënien më të vogël të niveleve të dopaminës. Ose, kërkimi i vazhdueshëm për *vetëm* skenën e duhur për efekt maksimal. Për më tepër, ju mund të masturboni në një pozicion të përkulur ose duke parë telefonin inteligjent në shtrat gjatë natës, duke i dëshiruar përfundimisht këto sinjale më shumë se stimujt e jetës reale. Seksi shkon kundër pothuajse çdo aspekti të haremit në internet, kështu që nuk ka asnjë shans kur krahasohet. Kujtimet e krijuara kur je i ri janë të fuqishme dhe të qëndrueshme, kështu që prishja e këtyre rrëshqitjeve pornografike dhe rilidhja ose krijimi i të rejave kërkon më shumë kohë. Megjithatë, kjo nuk do të thotë se është më e vështirë.

Sa herë që hipni në 'rrëshqitësin e ujit pornografik', po e lyeni atë, duke i mbajtur nervat të freskëta dhe gati për t'u ndezur. Kur parkoni pranë një restoranti të ushqimit të shpejtë, aroma e fryerjes noton në vrimat e hundës dhe shitja është bërë tashmë. Po kështu, rrëshqitjet e ujit pornografikë në trurin tuaj janë gati për t'u thithur dhe janë të hapura njëzet e katër orë në ditë. Çdo sinjal ose shkas ndriçon qarkun tuaj të shpërblimit me premtimin e seksit - vetëm se nuk është seksi. Sidoqoftë, qelizat nervore i forcojnë këto lidhje me zgjimin seksual duke mbirë degë të reja për të forcuar lidhjet. Sa më shumë të përdorni pornografi, aq më të forta bëhen lidhjet nervore. Rezultati përfundimtar është se në fund të fundit mund të *duhet* të jesh soditës, të kesh nevojë të klikosh në një material gjithnjë në rritje dhe të ri, të kesh nevojë për pornografi për të fjetur ose të kesh nevojë të kërkosh përfundimin e përsosur për të përfunduar punën.

Ashtu si me çdo substancë ose drogë të sjelljes, trupi ndërton tolerancë dhe ilaçi pushon së lehtësuari plotësisht dhembjet e tërheqjes. Sapo përdoruesi i pornografisë mbyll një seancë, ai dëshiron një tjetër, dhe shpejt, uria e përhershme mbetet e pakënaqur. Prirja natyrore është përshkallëzimi, për të marrë nxitimin e dopaminës. Megjithatë, shumica e përdoruesve pengohen ta bëjnë këtë për njërën ose të dyja arsyet e mëposhtme.

**Para:** Ata nuk mund të përballojnë të abonohen në faqet pornografike me pagesë.

**Shëndeti:** Trupi mund të marrë vetëm kaq shumë, ose rritjet e dopaminës ose orgazmat. Plus, orgazmat në fakt shkaktojnë kimikate në mënyrë që të zvogëlojnë rrjedhjen e dopaminës. Kështu funksionon trupi.

Sapo përbindëshi i vogël largohet nga trupi juaj, ndjenja e tmerrshme e pasigurisë merr fund. Vetëbesimi juaj kthehet, së bashku me një ndjenjë të mrekullueshme respekti për veten, duke marrë sigurinë për të marrë kontrollin e jetës suaj dhe duke e përdorur atë si një trampolinë për të trajtuar probleme të tjera. Ky është një nga shumë përparësitë e mëdha të çlirimit nga çdo varësi.

Miti i ndarjes është një nga truket e shumta që përbindëshi i vogël luan me mendjen tuaj. Këto truke e bëjnë më të vështirë ndalimin - për shkak të kënaqësisë së pamundur të urisë së përhershme - duke bërë që shumë përdorues t'i drejtohen cigareve, pijeve të rënda apo edhe drogave më të vështira për të kënaqur boshllëkun.

Njerëzit vlerësojnë kafshët, si për veten ashtu edhe për të tjerët. Shikimi i pornografisë me partnerin tuaj është i pakënaqshëm, pasi të dy e vlerësoni performancën e njëri-tjetrit kundrejt tregimit. Dëshironi Brad Pitt në dhomën tuaj të gjumit, edhe nëse ai është në një poster? Askush nuk mund të krahasohet me një harem ku çdo 'përvojë' është aktruar, skenar, drejtuar nga profesionistë dhe në dispozicion menjëherë njëzet e katër orë në ditë.