# Shmangni stimujt e rremë

Shumë përdorues të metodës së vullnetit përpiqen të rrisin motivimin e tyre përmes ndërtimit të stimujve të rremë. Ka shumë shembuj të kësaj, një shembull tipik është që të shpërblehen me dhurata pasi nuk kanë parë pornografi për një muaj. Kjo duket të jetë një qasje logjike dhe e arsyeshme, por në fakt është e rreme, sepse çdo përdorues që respekton veten preferon të vazhdojë të shikojë pornografi çdo ditë sesa të shpërblejë veten me një dhuratë që i jepet vetes. Kjo krijon dyshime në mendjen e përdoruesit, sepse jo vetëm që do t'u duhet të abstenojnë për *tridhjetë ditë*, por nuk janë të sigurtë se do të *shijojnë* ditët pa pornografi. E vetmja kënaqësi apo mbështetje u është hequr! E gjithë kjo është të rrisë madhësinë e sakrificës që përdoruesi ndjen se po bën, tani gjithnjë e më të çmuar në mendjen e tyre.

Shembuj të tjerë përfshijnë:

- Do të ndaloj që të më detyrojë të kem një jetë sociale dhe seks më të vërtetë.

- Do të ndalem që pak energji magjike të më ndihmojë të kapërcej mbi konkurrentët dhe të marr partnerin që ndjek.

- Do të ndalem që të mund të angazhohem që të mos e harxhoj energjinë dhe entuziazmin tim me pornografi në mënyrë që të rrit urinë në veten time.

Këto janë të vërteta, mund të jenë efektive dhe mund të përfundoni duke marrë atë që dëshironi - por mendoni për këtë për një sekondë. Nëse e merrni atë që dëshironit, pasi risia të ketë kaluar, do të ndiheni të privuar; nëse nuk e bëni, do të ndiheni të mjerë. Sido që të jetë, herët a vonë do të bini përsëri në të njëjtin kurth.
Lidhja e lënies së duhanit me një nxitje të rreme vetëm rrit dyshimin, sepse nëse nuk e merrni nxitjen tuaj (dhe edhe nëse e merrni) do të filloni të mendoni mendime të dyshimta si “*A do ta bëjë vërtet jetën time më të mirë lënia? Nëse e lë dhe nuk arrij atë që dua, a e kam përdorur saktë metodën?*" Mendime të tilla shtojnë ndjenjat e sakrificës dhe për këtë arsye krijojnë dhembje.

Një shembull tjetër tipik janë paktet në internet ose forum. Këto kanë avantazhin e eliminimit të tundimit për periudha të caktuara. Sidoqoftë, ato zakonisht dështojnë për arsyet e mëposhtme:

1. Nxitja është e rreme. Pse dëshironi të ndaloni vetëm sepse njerëzit e tjerë po e bëjnë këtë? E gjithë kjo që arrihet është gjenerimi i presionit shtesë dhe rrit ndjenjën e sakrificës. Është mirë nëse të gjithë përdoruesit vërtet duan të ndalojnë në një kohë të caktuar - por nuk mund t'i detyrosh ata të ndalojnë, megjithëse të gjithë duan fshehurazi. Derisa të jenë gati ta bëjnë këtë, një pakt krijon presion shtesë, i cili vetëm sa rrit dëshirën e tyre për të parë. Kjo i kthen ata në shikues të fshehtë, duke rritur më tej ndjenjën e varësisë.

2. Varësia nga njëri-tjetri duke përdorur metodën e vullnetit lind ndjenjat e kalimit të një periudhe pendimi, gjatë së cilës ata presin që dëshira të zhduket. Nëse dorëzohen, ka një ndjenjë dështimi. Kur përdorni metodën e fuqisë së vullnetit, të paktën njëri prej pjesëmarrësve është i detyruar të heqë dorë, duke u dhënë pjesëmarrësve të tjerë justifikimin që ata kanë pritur. Nuk është faji i tyre, ata do të duronin por ‘Fred’ i zhgënjeu. E vërteta është se shumica prej tyre tashmë kanë mashtruar.

3. Ndarja e kredisë është e kundërta e varësisë. Ka një ndjenjë të mrekullueshme arritjeje në ndalimin e pornografisë dhe kur e bëni atë vetëm, vlerësimi që merrni nga miqtë dhe miqtë tuaj në internet mund të jetë një nxitje e jashtëzakonshme gjatë ditëve të para. Megjithatë, kur të gjithë e bëjnë atë në të njëjtën kohë, kredia duhet të ndahet dhe nxitja si pasojë reduktohet.

4. Një shembull tjetër klasik është premtimi guru. Ndalimi do t'ju japë lumturi, sepse nuk jeni më i përfshirë në tërheqje të luftës, truri juaj fillon të rilidhet dhe të rifitojë kontrollin e impulsit. Megjithatë, duhet të keni parasysh që kjo as nuk do t'ju bëjë perëndi të seksit dhe as nuk do t'ju fitojë llotarinë. Askujt përveç teje nuk i intereson aspak nëse ndalon pornografinë. Ju nuk jeni një person i dobët nëse përdorni pornografi tre herë në ditë dhe keni PIED, ose një person i fortë nëse jeni i varur dhe nuk e bëni këtë.

Mos u tallni me veten. Nëse oferta e punës prej dhjetë muajsh pune për 12 muaj pagë në vit, ose rreziqet e uljes së aftësisë së trurit tuaj për të përballuar stresin dhe tendosjet e përditshme, ose të vini veten në kundërshtim me një ereksion të besueshëm, ose jeta e torturave dhe skllavërisë mendore dhe fizike nuk i ndaloi ata, stimujt e mësipërm të rremë nuk do të bëjnë as edhe më të voglin ndryshim dhe do të kenë sukses vetëm që ta bëjnë sakrificën të duket më e keqe. Në vend të kësaj, përqendrohuni në anën tjetër:

\"Çfarë përfitoj nga kjo? Pse më duhet të shikoj porno?\"

Vazhdoni të shikoni anën tjetër të tërheqjes së luftës dhe pyesni veten se çfarë po bën pornografia për ju. *ABSOLUTISHT ASGJË.* Pse duhet ta bëj? *JU JO! TI PO DËNON VETËM VETEN.* Është bast i Paskalit: nuk ke pothuajse asgjë për të humbur (eksitimi në zbehje), shanse për fitime të mëdha (eksitim i plotë dhe i besueshëm, mirëqenie mendore dhe lumturi) dhe asnjë shans për të humbur të mëdha.

Pse të mos ia deklaroni më pas dorëheqjes miqve dhe familjes? Epo, kjo do t'ju bëjë një ish-varur ose ish-përdorues krenar, jo një jo-përdorues të gëzuar dhe të lumtur. Mund ta trembë pak partnerin tuaj, pasi ai mund ta shohë këtë si një skemë për të bërë më shumë seks, në një farë mënyre të Epokës së Re. Ata gjithashtu mund të kenë frikë se do të ktheheni në një makinë seksi. Është e vështirë të shpjegohet nëse nuk janë mendjehapur.

Çdo përpjekje për t'i bërë të tjerët t'ju ndihmojnë në lënien i jep më shumë fuqi përbindëshit të vogël. Duke e shtyrë atë nga mendja juaj dhe duke e injoruar plotësisht atë, ka efektin e përpjekjes *mos* për të menduar për të. Jini të vëmendshëm në vend të kësaj, sapo të dalloni mendimet, shenjat (vetëm në shtëpi) ose mendimet e pamenduara, thjesht thoni vetes *\"Shkëlqyeshëm, unë nuk jam më skllav i pornografisë. Jam i lirë dhe i lumtur ti di dallimet në seks!\"* Kjo do të shkurtojë oksigjenin tek mendimi dhe do ta ndalojë atë të digjet drejt dëshirave dhe dëshirave. Në këtë aspekt, praktikimi i meditimit të vetëdijes mund të jetë i dobishëm për të ndihmuar në depersonalizimin e mendimeve.
