# Mënyra e lehtë për të ndaluar

Ky kapitull përmban udhëzime në lidhje me mënyrën e thjeshtë për të ndaluar pornografinë. Me kusht që të ndiqni udhëzimet, do të zbuloni se ndalimi varion nga relativisht i lehtë në i këndshëm! Me kusht që të ndiqni udhëzimet më poshtë, është jashtëzakonisht e lehtë të ndalosh pornografinë. Gjithçka që duhet të bëni janë dy gjëra:

1. Merrni vendimin që nuk do të shikoni më kurrë pornografi.

2. Mos u mërzit për këtë. Gëzohu.

Ju ndoshta po pyesni: *“Pse nevojitet pjesa tjetër e librit? Pse nuk mund ta kishe thënë këtë në radhë të parë?*" Epo, përgjigja është se përfundimisht do të kishit hequr dorë për këtë dhe si pasojë do të kishit ndryshuar përfundimisht vendimin tuaj. Ju ndoshta e keni bërë tashmë këtë shumë herë më parë.
Siç u tha tashmë, pornografia është një kurth delikate, i keq. Problemi kryesor i ndalimit nuk është varësia ndaj dopaminës – që sigurisht është një problem, por jo kryesori – është shpëlarja e trurit. Prandaj, është e nevojshme që së pari të shkatërrohen të gjitha mitet dhe iluzionet. Kuptoni armikun tuaj, njihni taktikat e tij dhe do ta mposhtni lehtësisht. Pasi kalova pjesë të mëdha të jetës sime duke vuajtur nga depresioni i zi, ndërsa përpiqesha të lija duhanin, pasi u arratisa përfundimisht, shkova drejt e në zero pa një moment të keq. Ishte e këndshme edhe gjatë periudhës së tërheqjes dhe nuk kam pasur kurrë më të voglin dhimbje që atëherë. Përkundrazi, ishte një nga gjërat më të mrekullueshme që më kanë ndodhur në jetën time.

Përpjekja ime e fundit ishte ndryshe. Si të gjithë përdoruesit në ditët e sotme, problemi ishte menduar seriozisht në mendjen time. Deri atëherë, pas dështimit, ishte rutinë të ngushëllohesha me mendimin se herën tjetër do të ishte më e lehtë. Nuk më kishte shkuar kurrë në mendje se do të duhej të vazhdoja në këtë mënyrë për pjesën tjetër të jetës sime. Ky mendim më mbushi me tmerr dhe fillova të mendoj shumë thellë për këtë temë.

Në vend që të aktivizoja shfletuesin në mënyrë të pandërgjegjshme, unë analizova ndjenjat e mia dhe konfirmova atë që dija tashmë. Nuk po shijoja pornografinë dhe e pashë atë të ndyrë dhe të neveritshme. Fillova të shikoja jo-përdorues që jetojnë në pjesë të tjera të botës, ose njerëz të moshuar që nuk i njohën kurrë vendet e tubave. Deri në atë kohë, unë i konsideroja gjithmonë jo-përdoruesit si njerëz të çuditshëm, të pashoqërueshëm dhe mendjemprehtë. Megjithatë, duke i ekzaminuar kur u shfaqën, ata dukeshin të ishin - në mos ndonjë gjë - më të fortë dhe më të relaksuar. Ata dukej se ishin në gjendje të përballonin streset dhe tendosjet e jetës dhe dukej se gëzonin funksionet sociale më shumë sesa përdoruesit e pornografisë. Ata sigurisht kishin më shumë shkëlqim dhe gjallëri se ata.

Fillova të flas me ish-përdoruesit. Deri në atë pikë, unë gjithmonë i konsideroja ata si të detyruar të hiqnin dorë për arsye shëndetësore ose fetare dhe gjithmonë dëshiroja fshehurazi për një vizitë në harem. Disa thanë, *"Ju i keni dhimbjet e çuditshme, por ato janë kaq të pakta dhe nuk ia vlen të shqetësoheni." !"* Edhe dështimet ishin fatkeqe për ta - ata nuk e dënuan veten dhe pranuan pa kushte. Si një trajner që do të pranojë një gabim nga një lojtar vërtet i artë. Biseda me ish-përdoruesit shkatërroi një tjetër mit që e kisha gjithmonë në mendje, se kishte një dobësi të natyrshme brenda meje, derisa m'u duk se të gjithë kaluan këtë makth privat.

Në thelb, thashë me vete: *“Shumë njerëz po ndalojnë tani dhe po bëjnë një jetë krejtësisht të lumtur, nuk kisha nevojë ta bëja para se të filloja dhe mbaj mend që duhej të punoja shumë për t'u mësuar me këtë pisllëk. Pra, pse duhet ta bëj tani?"* Në çdo rast, nuk më pëlqente pornografia, e urreja të gjithë ritualin e ndyrë dhe nuk doja të kaloja pjesën tjetër të jetës sime në skllavëri ndaj kësaj varësie të neveritshme. Më pas thashë këtë për veten time:

*"Pavarësisht nëse ju pëlqen apo jo, ju keni përfunduar seancën tuaj të fundit."*

E dija që nga ajo pikë se nuk do të kisha më kurrë një seancë tjetër. Nuk e prisja që të ishte e lehtë, vetëm e kundërta. Unë besoja plotësisht se isha regjistruar për muaj të tërë depresioni të zi dhe do të kisha kaluar pjesën tjetër të jetës sime duke pasur dhimbje të herëpashershme. Në vend të kësaj, ka qenë lumturi absolute që në fillim.

M'u desh shumë kohë për të kuptuar pse kishte qenë kaq e lehtë dhe pse nuk i kisha vuajtur ato dhimbje të tmerrshme të tërheqjes. Arsyeja është se ato nuk ekzistojnë, është dyshimi dhe pasiguria që krijon dhimbje. E vërteta e bukur është se ***është e lehtë të ndalosh pornografinë.*** Është vetëm pavendosmëria dhe shakaja që e bëjnë të vështirë. Edhe kur janë të varur, përdoruesit mund të shkojnë për periudha relativisht të gjata në periudha të caktuara pa të. Vuani vetëm kur e dëshironi, por nuk mund ta keni.

Prandaj, çelësi për ta bërë më të lehtë është ta bëni ndalimin të sigurt dhe përfundimtar. Jo duke shpresuar, por duke *e ditur* që e keni nisur, pasi keni marrë vendimin. Asnjëherë mos e dyshoni ose mos e vini në dyshim, në fakt, vetëm e kundërta - gjithmonë duke u gëzuar! Nëse mund të jeni të sigurt që në fillim, do të jetë e lehtë. Por si mund të jesh i sigurt që në fillim? Kjo është arsyeja pse pjesa tjetër e librit është e nevojshme. Ka disa pika thelbësore të nevojshme për t'u qartësuar në mendjen tuaj përpara se të filloni:

1. Kuptoni se mund ta arrini atë. Nuk ka asgjë të ndryshme tek ju dhe i vetmi person që mund t'ju bëjë të shikoni është vetvetja. Jo ai ylli, asnjëherë në ëndrrat e tyre më të çmendura nuk kanë menduar që ata të përdoren për të reduktuar virilitetin.

2. Nuk ka absolutisht asgjë për të hequr dorë. Përkundrazi, ka përfitime të mëdha pozitive për t'u bërë. Jo vetëm që do të jeni më të shëndetshëm dhe më të pasur, por do t'i shijoni më shumë kohët e mira dhe do të jeni më pak të mjerë gjatë të këqijave.

3. Nuk ka gjë të tillë si një shikim apo një vizitë e vetme. Pornografia është varësi nga droga dhe një reaksion zinxhir, duke rënkuar për vizitën e çuditshme, vetëm do të ndëshkoni veten pa nevojë.

4. Shihni pornografinë jo si një zakon "djem-do të jenë djem" që mund t'ju lëndojë, por si varësi ndaj drogës. Përballuni me faktin se ju pëlqen apo nuk doni, **ju keni marrë sëmundjen.** Nuk do të largohet sepse e fusni kokën në rërë. Mos harroni se si të gjitha sëmundjet gjymtuese, jo vetëm që zgjat për gjithë jetën, por përkeqësohet në mënyrë eksponenciale. Koha më e lehtë për ta kuruar është tani.

5. Ndani sëmundjen - varësinë neurologjike - nga mendësia për të qenë përdorues ose jo. Të gjithë përdoruesve, nëse u jepet mundësia për t'u kthyer në kohën para se të fiksoheshin, do të hidheshin në këtë rast. Ju e keni atë mundësi sot! As mos e mendoni si 'dorëzim'.

Pasi të merrni vendimin përfundimtar që keni pasur vizitën tuaj të fundit, ju do të jeni tashmë një jo-përdorues. Një përdorues është një nga ata të mjerët e varfër që kalon jetën duke e shkatërruar veten me pornografi. Një jo-përdorues është dikush që nuk e bën këtë. Pasi të keni marrë vendimin përfundimtar, tashmë e keni arritur objektivin tuaj. Gëzohuni për faktin, mos u ulni duke pastruar dhe duke pritur që të largohet varësia kimike. Dilni dhe shijoni jetën menjëherë. Jeta është e mrekullueshme edhe kur je i varur dhe çdo ditë do të bëhet shumë më e mirë kur nuk je.

Çelësi për ta bërë më të lehtë lënien është të jeni të sigurt se do të keni sukses të abstenoni plotësisht gjatë periudhës së tërheqjes, maksimumi tre javë. Nëse jeni në kuadrin e duhur mendor, do ta keni kaq të lehtë.

Në këtë fazë, nëse e keni hapur mendjen siç është kërkuar në fillim, do të keni vendosur tashmë se do të arratiseni. Tani duhet të keni ndjenja eksitimi, si një qen që shtrëngon zinxhirin, i paaftë të presë të prishë rrëshqitjet e ujit pornografikë DeltaFosB. Nëse keni një ndjenjë dënimi dhe zymtësie, kjo do të jetë për një nga arsyet e mëposhtme:

1. Diçka nuk ju ka ardhur në mendje. Rilexoni pesë pikat e mësipërme dhe pyesni veten nëse besoni se ato janë të vërteta. Nëse dyshoni për ndonjë pikë, rilexoni pjesët përkatëse të librit.

2. Keni frikë nga vetë dështimi. Mos u shqetësoni, thjesht lexoni dhe do të keni sukses. I gjithë biznesi i pornografisë në internet është një truk besimi në një shkallë gjigande. Njerëzit inteligjentë bien në truket e besimit, por vetëm një budalla, pasi të ketë marrë vesh për trukun, vazhdon të tallet me veten.

3. Jeni dakord me gjithçka, por jeni ende të mjerë. Mos u bëj! Hapi sytë, diçka e mrekullueshme po ndodh. Ju jeni gati të arratiseni nga burgu, është thelbësore të filloni me mendjen e duhur: *“Është e mrekullueshme që nuk jam përdorues!”*

Gjithçka që duhet bërë tani është t'ju mbajë në atë kornizë mendore gjatë periudhës së tërheqjes, dhe kapitujt e ardhshëm trajtojnë pika specifike për t'ju mundësuar ta bëni këtë. Pas periudhës së tërheqjes nuk do të duhet të mendoni kështu, do ta mendoni automatikisht. I vetmi mister në jetën tuaj do të jetë arsyeja pse nuk e keni parë më parë. Megjithatë, dy paralajmërime të rëndësishme.

- Vonesë e planit tuaj për të bërë vizitën tuaj të fundit derisa të keni përfunduar librin.

- Është përmendur shumë herë një periudhë tërheqjeje deri në tre javë, e cila mund të shkaktojë keqkuptim. Së pari, ju mund të ndjeheni të nënndërgjegjshëm se duhet të vuani për tre javë. Ju nuk e bëni. Së dyti, shmangni kurthin e të menduarit *"Disi duhet të abstenoj për tre javë dhe më pas do të jem mirë."* Asgjë magjike nuk do të ndodhë në të vërtetë pas tre javësh, nuk do të ndiheni befas si një jo-përdorues. pasi ata në fakt nuk ndihen ndryshe nga përdoruesit. Nëse jeni duke lagur për të ndaluar gjatë tre javëve, sipas të gjitha gjasave do të vazhdoni të pastroni për këtë edhe pas tre javësh. Përmbledhur, nëse mund të filloni që tani duke thënë *“Nuk do ta përdor më kurrë, a nuk është e mrekullueshme?”*, pas tre javësh i gjithë tundimi do të shkojë. Ndërsa nëse thoni, *"Nëse mund t'i mbijetoj këto tre javë pa pornografi..."*, do të vdisni për një vizitë në harem pas mbarimit të tre javëve.

Mendoni për këtë në këtë mënyrë – truri juaj dëshiron të ruajë status quo-në, kështu që nëse jeni nën besimin se po humbisni diçka të mirë kur e lëni, padyshim që do të ndiheni të tmerrshëm. Është e pamundur të detyrosh veten të ndihesh në një mënyrë të caktuar nëse truri yt nuk e beson atë. Kjo është arsyeja pse është e rëndësishme të kaloni nëpër mundimin për të hequr iluzionin se pornografia ju jep diçka fare. Kështu e dini se nuk po sakrifikoni asgjë.

Mosfunksionimi seksual ka të bëjë shumë me trurin dhe strukturën e mendjes. Pornografia e internetit rilidh qarkun e shpërblimit të trurit tuaj dhe i jep mendjes suaj një mentalitet 'dyshues'. Ky vetë-dyshim do të shkaktojë padyshim mosfunksionim seksual. Të kesh gjithë dëshirën në pjesën e sipërme, por të durosh pa eksitim në pjesën e poshtme është gjëja më e keqe që mund t'i ndodhë mentalitetit tuaj. Libido që shkon dorë për dore me romancën është eliksiri i rinisë që mund ta kesh derisa të vdesësh. Ju do t'i mbani të larta probabilitetet duke e lënë, por ky nuk është fitimi i vetëm apo i madh. Është liria jote nga skllavëria!
