# The Withdrawal Period

Deri në tre javë pas seancës suaj të fundit, ju mund t'i nënshtroheni dhimbjeve të tërheqjes. Këto përbëhen nga dy faktorë mjaft të veçantë, por të ndryshëm:

1. Dhimbjet e tërheqjes së dopaminës. Një ndjenjë e zbrazët, e pasigurt e ngjashme me urinë, e identifikuar si dëshira ose një ndjenjë "diçka që duhet të bëj".

2. Shkaktarë psikologjikë të disa stimujve të jashtëm si reklama, shfletim online, biseda telefonike etj.

Dështimi për të kuptuar dhe bërë dallimin midis këtyre dy faktorëve të veçantë e bën të vështirë arritjen e suksesit duke përdorur metodën e vullnetit dhe është arsyeja pse shumë nga ata që përfundojnë përsëri bien në grackë. Megjithëse dhembjet e tërheqjes së dopaminës nuk shkaktojnë dhimbje fizike, mos e nënvlerësoni fuqinë e tyre. Ne flasim për 'dhimbje urie' nëse qëndroni pa ushqim për një ditë; mund të ketë zhurmë stomaku, por nuk ka dhimbje fizike. Megjithatë, uria është një forcë e fuqishme dhe ka të ngjarë të bëhemi shumë nervoz kur privojmë ushqimin. Është e ngjashme me atë kur trupi ynë kërkon një nxitim dopamine, ndryshimi është se trupi ynë ka nevojë për ushqim, jo ​​helm. Me mendjen e duhur, dhembjet e tërheqjes kapërcehen lehtësisht dhe zhduken shumë shpejt.

Pas abstenimit për disa ditë në metodën e vullnetit, dëshira për skuqje të dopaminës zhduket shpejt. Është faktori i dytë – shpëlarja e trurit – që shkakton vështirësi. Përdoruesit e kanë zakon të lehtësojnë dhembjet e tyre të tërheqjes në momente të caktuara dhe raste të caktuara, gjë që shkakton një lidhje idesh (*"E kam të vështirë, kështu që duhet të shikoj pornografi."* ose "*Unë jam në shtrat me laptopin tim dhe duhet të bëj një seancë që të ndihem i lumtur*"). Efekti ilustrohet më së miri me një shembull: ju keni një makinë dhe treguesi është në të majtë, por në anën tjetër, është në të djathtë. E dini se është në të majtë, por për disa javë i ndizni fshirëset e xhamit kur dëshironi të tregoni.

Ndalimi është i ngjashëm: gjatë ditëve të para mekanizmi i këmbëzës do të funksionojë në kohë të caktuara. Ju do të mendoni të dëshironi një seancë, kështu që kundërshtimi i larjes së trurit është thelbësor që nga fillimi dhe do të bëjë që këto shenja dhe shkaktarë të zhduken shpejt. Sipas metodës së fuqisë së vullnetit, për shkak se përdoruesi beson se po bën një sakrificë, ai po mashtron për të dhe po pret nxitjet për t'u larguar, e kundërta e heqjes së këtyre mekanizmave nxitës dhe në fakt përfundon duke i rritur ato. Në mënyrë të ngjashme, nën të menduarit guru, përdoruesi fillon të pyesë veten se kur do të bëhet zot dhe madje kërkon që ata të mos kenë ato mendime, duke i hapur rrugën neverisë ndaj vetvetes dhe dështimit.

Një shkaktar i zakonshëm është koha e vetëm, veçanërisht në ngjarje sociale me miqtë. Ish-përdoruesi që përdor metoda të tjera për ta lënë është tashmë i mjerë për shkak të ndjenjës së privimit nga mbështetja ose kënaqësia e zakonshme. Miqtë e tyre janë me partnerët e tyre dhe sillen në mënyrë intime. Përdoruesi është ose beqar ose nuk 'merr asgjë' nga partneri i tij dhe tani nuk e shijon më atë që duhet të jetë një rast i këndshëm shoqëror. Rrëshqitjet ekzistuese me ujë të trurit të tyre i çojnë në pornografi, gjë që është më e lehtë sesa të përpiqen të josh partnerin e tyre.

Për shkak të lidhjes së të drejtës për seks me mirëqenien e tyre, ata tani po vuajnë një goditje të trefishtë dhe shpëlarja e trurit në fakt është rritur. Nëse ata janë të vendosur dhe mund të qëndrojnë mjaftueshëm, ata përfundimisht pranojnë fatin e tyre dhe vazhdojnë jetën e tyre. Megjithatë, një pjesë e larjes së trurit mbetet ende, aspekti i dytë më patetik është përdoruesi që e ka lënë, por edhe pas disa vitesh ende dëshiron 'vetëm një vizitë të fundit në harem' në raste të caktuara. Ata janë të prirur për një iluzion që ekziston vetëm në mendjen e tyre dhe e torturojnë veten pa nevojë.

Edhe nën EasyPeasy, përgjigjja ndaj shkaktarëve është dështimi më i zakonshëm. Ish-përdoruesi priret ta konsiderojë pornografinë e internetit si një lloj placebo ose pilule sheqeri, duke menduar: "*E di që pornografia nuk bën asgjë për mua, por nëse mendoj se bën, atëherë në raste të caktuara do të jetë e dobishme.*" Një pilulë sheqeri , megjithëse nuk jep asnjë ndihmë fizike, mund të jetë një ndihmë e fuqishme psikologjike për të lehtësuar simptomat e vërteta dhe për këtë arsye është e dobishme. Pornografia në internet dhe masturbimi i zakonshëm, megjithatë, nuk janë pilula sheqeri. Pse? Pornografia krijon simptomat që i lehtëson dhe nuk i lehtëson ato plotësisht.

Mund ta keni më të lehtë të kuptoni efektin kur lidheni me një jo-përdorues ose një përdorues të suksesshëm që e ka lënë për disa vite. Merrni rastin e një përdoruesi që humbë partnerin e tij. Është mjaft e zakonshme në momente të tilla, me qëllimet më të mira, të thuash, "*Kaloni një vizitë në harem, do t'ju ndihmojë të qetësoheni.*" Nëse oferta pranohet, nuk do të ketë një efekt qetësues pasi nuk ka varësia ndaj dopaminës dhe për këtë arsye pa dhimbje tërheqjeje. Në rastin më të mirë, gjithçka që do të bëjë është t'u japë atyre një nxitje psikologjike momentale.

Edhe pas përfundimit të seancës, tragjedia origjinale është aty. Në fakt, do të rritet sepse personi tani vuan dhembjet e tërheqjes dhe kështu duhet të bëjë një zgjedhje: t'i durojë ato ose të kërkojë lehtësim duke përsëritur rrëshqitjen e ujit për të filluar përsëri zinxhirin e mjerimit. E gjithë pornografia e ofruar ishte një nxitje psikologjike kalimtare, e njëjta gjë që mund të ishte arritur nga një libër ose një film i mirë, madje edhe i keq. Shumë jo-përdorues dhe ish-përdorues janë rivarësuar si rezultat i rasteve të tilla. Merreni fare qartë në mendjen tuaj: nuk keni nevojë për nxitimin e dopaminës dhe vetëm po e torturoni veten më tej duke vazhduar ta konsideroni atë si një lloj mbështetjeje ose nxitjeje. Nuk ka nevojë të jesh i mjerë.

Orgazmat nuk krijojnë marrëdhënie të mira, në shumicën e rasteve i prishin ato. Mos harroni gjithashtu se nuk është plotësisht e vërtetë që ata që shfaqin shfaqje publike dashurie gëzojnë çdo rast; intimiteti shijohet më së miri në privat, ku partnerët mund të përgjigjen pa siklet. Ju nuk duhet të jeni një i varur nga dopamina e shkaktuar nga orgazma. Nëse kjo ndodh si rezultat i natyrshëm i një sërë ngjarjesh të jetës, kjo është mirë, por shijoni rastin dhe jetën pa të.

Pas braktisjes së konceptit të pornografisë si kënaqësi në vetvete, shumë përdorues mendojnë "*Sikur të kishte pornografi të pastër në internet.*" *Ekziston* pornografi e pastër e butë, dhe kushdo që e provon shpejt zbulon se është humbje kohe. Është e qartë në mendjen tuaj se e vetmja arsye për të cilën keni përdorur pornografi është marrja e dopaminës. Pasi të shpëtoni nga dëshira për pornografi për dopaminën, nuk do të keni nevojë të vizitoni haremin tuaj në internet.

Nëse dhembjet janë për shkak të simptomave aktuale të tërheqjes së dopaminës ose mekanizmave të nxitjes / sinjalizimit, pranojeni atë. Dhimbja fizike është inekzistente dhe me qëndrimin e duhur mendor nuk do të jetë problem. Mos u shqetësoni për tërheqjen - ndjenja në vetvete nuk është e keqe. Problemi është shoqërimi me dëshirën dhe më pas ndjenja e mohuar. Në vend që të mashtroni për këtë, pranojeni: “*E di se çfarë është kjo, është dhimbja e tërheqjes nga pornografia. Kjo është ajo që përdoruesit vuajnë gjatë gjithë jetës së tyre dhe i mban ata të varur. Jo-përdoruesit nuk i vuajnë këto dhimbje, është një tjetër nga të këqijat e shumta të kësaj varësie të gënjeshtrës. A nuk është e mrekullueshme që po e pastroj këtë të keqe nga truri im!"*

Me fjalë të tjera, për tre javët e ardhshme do të keni një traumë të lehtë brenda trupit tuaj, por gjatë atyre javëve dhe për pjesën tjetër të jetës do të ndodhë diçka e mrekullueshme. Ju do të shpëtoni nga një sëmundje e tmerrshme, me shpërblimet që peshojnë shumë më tepër se trauma e lehtë, e përkohshme dhe në fakt do të shijoni dhembjet e tërheqjes. Ato do të bëhen momente kënaqësie, si një lojë emocionuese për të ngordhur uriturën e shiritit pornografik që jeton brenda stomakut tuaj. Duhet ta vdisni nga uria për tre javë, ndërkohë që po përpiqet t'ju mashtrojë të futeni në shtrat për ta mbajtur gjallë.

Ndonjëherë, do të përpiqet t'ju bëjë të mjerë. Ndonjëherë, do të kapeni pa kujdes. Do të marrësh një URL pornografike ose do të ndeshesh me diçka në internet dhe do të harrosh që ke ndaluar, duke dhënë një ndjenjë të lehtë privimi kur të kujtohet. Përgatituni paraprakisht për këto truke dhe cilido qoftë tundimi, merrni parasysh se është aty vetëm për shkak të përbindëshit brenda trupit tuaj dhe sa herë që i rezistoni tundimit ju keni dhënë një goditje tjetër vdekjeprurëse në betejë.

Çfarëdo që të bëni, mos u përpiqni të harroni pornografinë. Kjo është një nga gjërat që shkakton PMOers duke përdorur metodën e vullnetit për orë të tëra depresioni. Ata përpiqen të kalojnë çdo ditë me shpresën se përfundimisht thjesht do ta harrojnë atë. Është si të mos jesh në gjendje të flesh – sa më shumë të shqetësohesh për këtë, aq më e vështirë bëhet. Në çdo rast, nuk do ta harroni dot, në ditët e para ‘përbindëshi i vogël’ do t’ju ​​kujtojë vazhdimisht dhe nuk do mund ta shmangni. Ndërsa ka ende laptopë, telefona inteligjentë dhe revista rreth jush, do të keni përkujtues të vazhdueshëm.

Çështja është se nuk keni nevojë të harroni, pasi asgjë e keqe nuk po ndodh. Në fakt, diçka e mrekullueshme po ndodh dhe edhe nëse po e mendoni një mijë herë në ditë, **shijoni çdo moment, kujtojini vetes se sa e mrekullueshme është të jesh sërish i lirë. Kujtojini vetes gëzimin e plotë që nuk duhet ta torturoni më veten.** Siç u tha më parë, do të zbuloni se dhembjet bëhen momente kënaqësie, duke u habitur se sa shpejt do të harroni më pas pornografinë.

Çfarëdo që të bëni, *mos dyshoni në vendimin tuaj*. Sapo të filloni të dyshoni, do të filloni të mashtroni dhe do të përkeqësohet. Në vend të kësaj, përdorni momentin e pastrimit dhe shndërrojeni atë në një nxitje. Nëse shkaku është depresioni, atëherë kujtojuni vetes se pornografia po e *shkaktonte* atë. Nëse ju përcillet një URL nga një mik, krenohu duke thënë, "*Jam i lumtur të them se nuk kam më nevojë për këtë.*" Kjo do t'i lëndojë ata, por kur ata shohin se nuk po ju shqetëson ata do të jetë në gjysmë të rrugës për t'u bashkuar me ju.

**Mos harroni: në radhë të parë keni arsye tepër të fuqishme për të ndaluar.** Kujtojini vetes kostot dhe pyesni veten nëse vërtet dëshironi të rrezikoni mosfunksionimin e trupit, mendjes dhe faktit të thjeshtë nën të cilin do të jetoni një magji për pjesën tjetër të jetës tuaj. Kini parasysh përpjekjet e përbindëshit të vogël për të minimizuar rreziqet dhe mbi të gjitha, mbani mend se ndjenja është vetëm e përkohshme dhe çdo moment është një moment më afër qëllimit tuaj.

Disa përdorues kanë frikë se do të duhet të kalojnë pjesën tjetër të jetës së tyre duke kthyer "shkaktuesit automatikë". Me fjalë të tjera, ata besojnë se do të duhet të kalojnë jetën e tyre duke u tallur se nuk kanë nevojë për pornografi, përmes përdorimit të psikologjisë. Kjo nuk është kështu; mos harroni se optimisti e sheh shishen gjysmë të mbushur dhe pesimisti e sheh atë gjysmë bosh. Në rastin e pornografisë, shishja është bosh dhe përdoruesi e sheh atë të mbushur. Përdorimi i pornografisë në internet nuk ka asnjë avantazh. Është përdoruesi që i është larë truri për të menduar se ka. Sapo të filloni t'i thoni vetes se nuk keni nevojë dhe nuk dëshironi pornografi, në një kohë shumë të shkurtër nuk do të keni nevojë as ta thoni, duke parë vetë të vërtetën e bukur. Është gjëja e fundit që duhet të bëni – sigurohuni që të mos jetë gjëja e fundit që bëni.
