# Vetëm një vështrim i vogël

Ky është zhbërja e shumë njerëzve duke përdorur metodën e vullnetit. Ata do të kalojnë tre ose katër ditë dhe më pas do të kenë një vështrim të çuditshëm për t'i kaluar. Ata nuk e kuptojnë efektin shkatërrues që kjo ka në moralin e tyre.

Për shumicën e përdoruesve, shikimi i tyre i parë në haremin e zonës së tubit nuk ishte aq i mirë sa seksi me një person të vërtetë. Klipet që janë të pastra janë të pakta, duke i dhënë një shtysë mendjes së tyre të vetëdijshme, duke menduar: “*Mirë, kjo nuk ishte edhe aq e këndshme. Unë po e humb dëshirën dhe nuk jam aq në gjërat tronditëse.*" Në fakt, e kundërta është rasti. Merreni të qartë në mendjen tuaj, kënaqësia e orgazmës nuk ishte arsyeja që e braktise pornografinë. Nëse përdoruesit do të ishin aty për vetëm në orgazmë, ata kurrë nuk do të shikonin më shumë se një klip. E vetmja arsye pse ju nevojitej pornografia ishte të ushqente atë përbindësh të vogël. Vetëm mendoni, pasi u vuaj nga uria për katër ditë, sa e çmuar duhet të ketë qenë ajo një shikim. Mendja juaj e ndërgjegjshme është i pavetëdijshëm, por rregullimi i marrë nga trupi juaj i komunikohet nënndërgjegjes suaj dhe e gjithë përgatitja juaj e zërit do të dëmtohet. Do të ketë një zë të vogël në fund të mendjes tuaj duke thënë se, pavarësisht nga gjithë logjika, seancat janë të çmuara dhe ju doni një tjetër.

Ky shikim i vogël ka dy efekte të dëmshme:

1. E mban gjallë përbindëshin e vogël në trupin tuaj.

2. Më keq, ju mban gjallë përbindëshin e madh në mendjen tuaj. Nëse keni pasur 'shikimin e fundit', do të jetë më e lehtë të keni një tjetër.

Pornografia është një kurth miu pa djathë, vetëm helm. Duke përdorur vullnetin duhet të bindni veten që të mos e kapni djathin, por EasyPeasy ju lejon të shihni se është helm. Ju nuk keni nevojë ta shmangni atë, thjesht nuk duhet të hyni në të.

Mbi të gjitha mbani mend:

*"Vetëm një shikim" është mënyra se si njerëzit futen në varësi në radhë të parë.*
