# A do të jetë më e vështirë për mua?

Ka kombinime të pafundme faktorësh që përcaktojnë se sa lehtë do të largohet çdo përdorues individual. Si fillim, secili prej nesh ka karakterin, karrierën, rrethanat personale, kohën, metabolizmin, etj. Disa profesione mund ta bëjnë më të vështirë se të tjerët, por me kusht që të hiqet shpëlarja e trurit, kjo nuk duhet të jetë kështu. Merrni disa shembuj të mëposhtëm.

Herë pas here, është e vështirë për anëtarët e profesionit mjekësor. Ne mendojmë se duhet të jetë më e lehtë për mjekët, sepse ata janë më të vetëdijshëm për efektet, por megjithëse kjo ofron arsye më të forta për ndalimin, nuk e bën më të lehtë për t'u realizuar. Arsyet janë si më poshtë:

1. Ndërgjegjësimi i vazhdueshëm për rreziqet shëndetësore krijon frikë, një nga kushtet në të cilat ndjejmë nevojën për të lehtësuar dhembjet e tërheqjes.

2. Puna e një mjeku është jashtëzakonisht stresuese dhe ata zakonisht nuk janë në gjendje të lehtësojnë stresin shtesë të dhembjeve të tërheqjes gjatë punës.

3. Ata kanë stresin shtesë të fajit, duke ndjerë se duhet të jenë shembull për pjesën tjetër të popullsisë. Kjo u bën më shumë presion dhe shton ndjenjën e privimit.

Pas një dite të vështirë në punë, kur stresi i tyre lehtësohet për një moment nga pornografia, ajo seancë lidhet gabimisht me lehtësimin e përjetuar. Për shkak të këtij mosshoqërimi të ideve, pornografia merr meritat për të gjithë situatën, duke u bërë befas shumë e çmuar pas heqjes dorë dhe kalimit të dhimbjeve të tërheqjes. Kjo është një formë e përdorimit të rastësishëm dhe zbatohet për çdo situatë ku përdoruesi detyrohet të abstenojë për periudha të gjata. Sipas metodës së fuqisë së vullnetit, përdoruesi është i mjerë sepse po privohet dhe nuk shijon lodhjen dhe gjumin që vjen pas një seance. Ndjenja e tyre e humbjes është rritur shumë. Sidoqoftë, nëse së pari mund të hiqni larjen e trurit dhe fshirjen në lidhje me pornografinë, pushimi dhe gjumi mund të shijohen akoma edhe kur trupi ka dëshirë për transmetuesit e aminës - serotoninën, norepinefrinën dhe dopaminën.

Një situatë tjetër e vështirë është mërzia, veçanërisht kur kombinohet me periudha stresi. Shembuj tipikë janë studentët dhe prindërit e vetëm, puna është stresuese, por monotone. Gjatë një përpjekjeje për të ndaluar metodën e fuqisë së vullnetit, personi i vetëm ka periudha të gjata në të cilat mund të parandalojë "humbjen" e tij, e cila nga ana tjetër rrit ndjenjat e depresionit. Përsëri, kjo mund të kapërcehet lehtësisht nëse mendja juaj është e saktë. Mos u shqetësoni se ju kujtohet vazhdimisht se keni ndaluar pornografinë. Përdorni momente të tilla për t'u gëzuar për faktin se po çlironi veten nga përbindëshi i keq.

Nëse keni një qëndrim pozitiv, këto dhimbje do të bëhen momente kënaqësie. Mbani mend, çdo përdorues, pavarësisht nga mosha, gjinia, inteligjenca ose profesioni mund ta ketë të lehtë dhe të këndshme të ndalojë me kusht që **të ndiqni të gjitha udhëzimet.**

## Arsyet kryesore të dështimit

Ka dy arsye kryesore për dështimin. E para është ndikimi i stimujve të jashtëm - një artikull komercial, lajmesh në internet, shfletim në internet, etj. Ata e gjejnë veten në një moment të dobët, apo edhe bëhen xhelozë kur shohin intimitet në skenarë shoqërorë. Kjo temë tashmë është diskutuar gjatë. Përdorni momentin për t'i kujtuar vetes se nuk ka gjë të tillë si një vizitë apo shikim. Gëzohu për faktin që ke thyer zinxhirin e skllavërisë mendore. Mos harroni se përdoruesi ju ka zili dhe ju duhet të ndjeni keqardhje për të, sepse ata kanë nevojë për të.

Arsyeja tjetër është të kalosh një ditë të keqe. Bëjeni të qartë në mendjen tuaj përpara se të filloni, se pavarësisht nëse jeni përdorues apo jo, do të keni ditë të mira dhe të këqija. Bie shi edhe për papën edhe për vrasësin. Jeta është relative dhe nuk mund të kesh ngritje pa ulje. Problemi me metodën e vullnetit është se sapo përdoruesi të ketë një ditë të keqe, ata fillojnë të pastrojnë për një vizitë në 'harem', gjë që e komplikon më tej çështjen. Jo-përdoruesi është i pajisur më mirë për të trajtuar streset dhe sforcimet, jo vetëm fizikisht, por edhe mendërisht. Nëse keni një ditë të keqe gjatë periudhës së tërheqjes, thjesht merrni atë në mjekër; kujtojuni vetes se ditët e këqija ekzistonin kur ishit të varur, përndryshe nuk do të kishit vendosur të ndalonit. Në vend që të fshiheni për këtë, njihni në vend të kësaj: *“Mirë, kështu që e sotmja nuk është aq e mirë, por pornografia nuk do ta shërojë atë. Nesër do të jetë më mirë dhe të paktën kam marrë një bonus të mrekullueshëm, e kam larguar atë varësi të tmerrshme."*

Kur je përdorues pornografie, duhet ta bllokosh mendjen ndaj negativëve të pornografisë. Përdoruesit nuk kanë kurrë mjegull të trurit, ata janë thjesht 'pak poshtë'. Kur keni probleme të pashmangshme të jetës dhe përjetoni një mendim të dëshirës për pornografi, a jeni të lumtur dhe të gëzuar? Sigurisht që nuk je. Pasi të ndaloni, tendenca është duke fajësuar gjithçka që shkon keq për faktin që keni ndaluar.

Nëse puna ju streson, ju mendoni, "*Në momente të tilla unë do të kisha pasur një seancë.*" Kjo është e vërtetë, por gjëja e rëndësishme që harrohet është se pornografia nuk e zgjidhi problemin, dhe ju thjesht jeni duke e ndëshkuar veten duke lagur për mbështetje iluzore. Po krijon një situatë të pamundur, të mjerë sepse nuk mund të masturbosh në pornografi, megjithatë do të jesh edhe më i mjerë nëse e bën. *Ju e dini që keni marrë vendimin e duhur duke e ndaluar atë, atëherë pse ta ndëshkoni veten duke dyshuar në vendimin tuaj?*

Mbani mend, një qasje mendore pozitive është thelbësore - gjithmonë.
