# Zëvendësues

Disa shembuj zëvendësuesish përfshijnë kufizimin në revista pornografike, imazhe statike në internet, dieta pornografike, etj. **MOS PËRDORNI ASNJË PREJ TYRE.** Ato e bëjnë më të vështirë, jo më të lehtë. Nëse ju merrni një dhimbje dhe përdorni një zëvendësues, ai thjesht do ta zgjasë dhimbjen, duke e bërë më të vështirë. Ajo që po thua në të vërtetë është se të duhet pornografi për të mbushur boshllëkun. Do të jetë njësoj si t'i dorëzohesh një rrëmbyesi ose zemërimit të një fëmije, thjesht duke mbajtur dhembjet që vijnë dhe duke zgjatur torturën. Në çdo rast, zëvendësuesit nuk do t'i lehtësojnë dhembjet. Dëshira juaj është për disa neurotransmetues në tru, dhe gjithçka që do të bëjë është t'ju mbajë të mendoni për pornografinë. Mbani mend këto pika:

1. Nuk ka asnjë zëvendësim për pornografinë.

2. Nuk keni nevojë për pornografi. Nuk është ushqim, është helm. Kur të vijnë dhembjet, kujtojini vetes se janë përdoruesit që vuajnë nga dhembjet e tërheqjes, jo jo-përdoruesit. Shihni se çfarë janë, një tjetër e keqe e drogës. Shihni ato si vdekjen e një përbindëshi.

3. Pornografia e internetit krijon boshllëkun; nuk e mbush. Sa më shpejt t'i mësoni trurit tuaj se nuk keni nevojë të shikoni, aq më shpejt do të jeni të lirë. Në veçanti, shmangni çdo gjë që i ngjan pornografisë, siç janë revistat për meshkuj, filmat, romanet romantike dhe reklamat. Kjo nuk është mendjembyllje, është në rregull të flasim për romancë dhe seks, por jo pornografi. Gjithmonë ka një mënyrë për të gjetur se kur dhe ku të diskriminohet. Është e vërtetë që një pjesë e vogël e përdoruesve që përpiqen të heqin dorë nga përdorimi i dietave pornografike të buta ose pornografike kanë sukses (nga këndvështrimi i tyre) dhe ia atribuojnë suksesin e tyre përdorimit të tillë. Megjithatë, ata u larguan *pavarësisht* përdorimit të tyre dhe jo për shkak të tij. Është për të ardhur keq që shumë ende rekomandojnë këto masa.

Kjo nuk është befasuese sepse nëse nuk e kuptoni plotësisht kurthin e pornografisë, një dietë ose një zëvendësues i butë tingëllon shumë logjike. Ajo bazohet në besimin se kur përpiqeni të hiqni dorë nga pornografia, keni dy armiq të fuqishëm për të mposhtur:

- Thyerja e zakonit.

- Të mbijetosh nga dhimbjet e tmerrshme të tërheqjes fizike.

Nëse keni dy armiq të fuqishëm për të mposhtur, është e arsyeshme të mos i luftoni ata njëkohësisht, por një nga një. Pra, teoria thotë se kur ndaloni së pari përdorimin e pornografisë, reduktoni në një herë në javë ose përdorni pornografi të sigurt. Pastaj, pasi të prishet zakoni, zvogëloni gradualisht furnizimin, duke trajtuar kështu secilin armik veç e veç.

Kjo tingëllon logjike, por bazohet në informacione të pasakta. Pornografia nuk është zakon, por varësia ndaj dopaminës dhe dhimbja aktuale fizike nga tërheqja është pothuajse e padukshme. Ajo që po përpiqeni të arrini kur e lini duhanin është të vrisni sa më shpejt që të jetë e mundur të dy përbindëshat në trupin dhe trurin tuaj. Gjithçka që bëjnë teknikat e zëvendësimit është të zgjasin jetën e përbindëshit të vogël dhe nga ana tjetër kjo zgjat larjen e trurit. EasyPeasy e bën të lehtë heqjen dorë menjëherë, duke vrarë larjen e trurit përpara seancës suaj të fundit. Përbindëshi i vogël së shpejti do të jetë i vdekur dhe, edhe kur është duke vdekur, nuk do të jetë më problem sesa kur ishit përdorues.

Vetëm mendoni, si mund ta kuroni varësinë ndaj një droge duke rekomanduar të njëjtin ilaç? Ka shumë histori në internet për ata që kanë hequr dorë nga përdorimi i pornografisë së fortë në internet, por janë të fiksuar pas alternativave 'të sigurta', pasi kanë rënë në justifikimet e përbindëshit të tyre të vogël. Mos u mashtroni nga fakti se pornografia e sigurt nuk është e tmerrshme – kështu ishte edhe klipi i parë me shpejtësi të lartë. Të gjithë zëvendësuesit kanë saktësisht të njëjtat efekte si çdo pornografi. Disa madje fillojnë të hanë, por megjithëse ndjenja e zbrazët e dëshirës për një seancë nuk dallohet nga uria për ushqim, njëra nuk do ta kënaqë tjetrën. Në fakt, nëse ka diçka që është krijuar për t'ju bërë të dëshironi pornografi, është duke e mbushur veten me ushqim. Siç u shpjegua më parë, dietat pornografike dhe pornografia e sigurt do t'ju vendosin vetëm në mes të tërheqjes së luftës, me rezistencën ndaj tundimit që është aq e bezdisshme sa do të ndiheni të lehtësuar duke vizituar haremin tuaj të preferuar në internet.

E keqja kryesore e zëvendësuesve është zgjatja e problemit real, shpëlarja e trurit. Keni nevojë për një zëvendësues për gripin kur të ketë mbaruar? Sigurisht që jo. Duke thënë se keni nevojë për një zëvendësim për pornografinë, çfarë po thoni në të vërtetë se po bëni një sakrificë. Depresioni i lidhur me metodën e vullnetit shkaktohet nga fakti që përdoruesi beson se po bën një sakrificë. Gjithçka që do të bëni është të zëvendësoni një problem me një tjetër. Nuk ka kënaqësi ta mbushësh veten me ushqim, cigare apo alkool. Thjesht do të shëndoshesh, do të mjerohesh dhe në asnjë moment nuk do t'i rikthehesh drogës.

Përdoruesit e rastësishëm e kanë të vështirë të hedhin poshtë besimin se po privohen nga shpërblimi i tyre i vogël, si ata që nuk lejohen të hyjnë në internet gjatë një periudhe kohore gjatë udhëtimeve, një ngjarjeje familjare, etj. Disa thonë, “*Nuk do të di se si të çlodhesha nëse nuk do të ishte për pornografinë.*" Kjo dëshmon çështjen - shpesh pushimi bëhet jo sepse përdoruesi ka nevojë ose madje e dëshiron atë, por sepse i varur - që është ai që janë - ka dëshpërimisht nevojë për të kruaj kruarje.

Mos harroni, seancat pornografike nuk ishin kurrë shpërblime të vërteta. Ato ishin të barabarta me veshjen e këpucëve të ngushta për të ndjerë kënaqësinë e heqjes së tyre. Pra, nëse mendoni se duhet të keni një shpërblim të vogël, le të jetë ai zëvendësuesi juaj; ndërsa jeni duke punuar vishni këpucë ose të brendshme me një madhësi shumë të vogël dhe mos ia lejoni vetes t'i hiqni ato derisa të keni pushim, atëherë përjetoni momentin e mrekullueshëm të relaksimit dhe kënaqësisë kur ato hiqen. Ndoshta ju mendoni se kjo do të ishte budallallëk. Ti ke absolutisht te drejtë. Mund të jetë e vështirë të vizualizohet ndërsa jeni ende në kurth, por kjo është ajo që bëjnë përdoruesit. Është gjithashtu e vështirë të imagjinohet se së shpejti nuk do të keni nevojë për atë "shpërblim" të vogël dhe se së shpejti do t'i konsideroni miqtë që janë ende në grackë me keqardhje të sinqertë dhe pyesin veten pse nuk mund ta kuptojnë qëllimin.

Megjithatë, nëse vazhdoni të tallni veten se vizita në internet në haremin ishte një shpërblim i vërtetë, ose se keni nevojë për një zëvendësues, do të ndiheni të privuar dhe të mjerë. Gjasat janë që të përfundoni sërish në grackën e neveritshme. Nëse keni nevojë për një pushim të vërtetë siç bëjnë amvisat, mësuesit, mjekët dhe punëtorët e tjerë, së shpejti do ta shijoni atë pushim edhe më shumë, sepse nuk do t'ju duhet të jeni të varur. Mos harroni se nuk keni nevojë për një zëvendësues. Dhimbjet janë një mall për dopaminën dhe së shpejti do të zhduken. Lëreni atë të jetë mbështetja juaj për ditët e ardhshme dhe kënaquni duke çliruar trupin dhe mendjen tuaj nga skllavëria dhe varësia.
