# A duhet t'i shmang situatat e tundimit

Këshilla ka qenë e drejtpërdrejtë deri më tani dhe ju ka kërkuar që ta trajtoni si udhëzim dhe jo si sugjerim. Ka arsye të shëndosha, praktike për këtë këshillë dhe ato arsye janë mbështetur nga mijëra raste studimore. Përsa i përket pyetjes nëse duhet të përpiqeni apo jo të shmangni tundimin, ky nuk është rasti. Çdo përdorues duhet të vendosë vetë. Megjithatë, mund të bëhen dy sugjerime të dobishme për t'ju ndihmuar në këtë proces. Është frika nga dhembjet e tërheqjes në të ardhmen që na mban të përdorim pornografinë për pjesën e mbetur të jetës sonë dhe kjo frikë përbëhet nga dy faza të dallueshme.

**Faza e parë - "*Si mund të mbijetoj pa pornografi?*"**

Kjo frikë është ndjenja e panikut që merr përdoruesi kur është beqar ose ka një partner aseksual, të painteresuar ose të padisponueshëm. Frika nuk shkaktohet nga dhembjet e tërheqjes, por është frika psikologjike e varësisë, e pamundësisë për të mbijetuar pa seks dhe orgazmë. Ajo arrin kulmin kur jeni në prag të lënies, kur dhembjet tuaja të tërheqjes janë në nivelin më të ulët. Është frika nga e panjohura, lloji i frikës që njerëzit kanë kur mësojnë të zhyten.

Bordi i zhytjes është një këmbë i lartë, por duket se është gjashtë këmbë i lartë. Uji është gjashtë këmbë i thellë, por duket se është një këmbë i thellë. Duhet guxim për të nisur veten, i bindur se do të thyesh kokën. Nisja është pjesa më e vështirë, nëse gjeni guximin për ta bërë atë - pjesa tjetër është e lehtë! Kjo shpjegon pse shumë përdorues me vullnet të fortë nuk janë përpjekur kurrë të ndalojnë, ose mund të mbijetojnë vetëm për disa ditë kur bëjnë. Në fakt, ka disa përdorues që ndjekin dietat pornografike, të cilët, pasi vendosin të ndalojnë, në fakt hanë ushqime dhe kalojnë në klipe më të ashpra më shpejt sesa nëse nuk do të kishin vendosur të ndalonin. Vendimi shkakton panik, i cili është stresues dhe shkakton një shenjë për të bërë një udhëtim në harem. Por tani nuk mund ta kesh një të tillë, duke çuar në mendime privimi, duke shtuar stresin.

Aktivizuesi aktivizohet shpejt kur siguresa fryn dhe ju ndezni shfletuesin. Mos u shqetësoni, paniku është thjesht psikologjik. Është frika se je i varur. E vërteta e bukur është se ju nuk jeni, edhe kur jeni ende i varur. Mos u frikësoni dhe nisni veten.

**Faza e dytë - Frika afatgjatë**

Faza e dytë është afatgjatë, duke përfshirë frikën se situata të caktuara në të ardhmen nuk do të jenë të këndshme ose nuk do të jeni në gjendje të përballoni traumën pa pornografi. Mos u shqetësoni, nëse mund të filloni veten, do të gjeni të kundërtën të jetë rasti. Vetë shmangia e tundimit ndahet në dy kategori.

1.  “*Do të regjistrohem në një dietë pornografike një herë në katër ditë. Do të ndihem më i sigurt duke ditur se mund të hyj në internet nëse bëhet e vështirë. Nëse dështoj, është në rregull, thjesht do të shtoj ditë shtesë në ciklin tim të ardhshëm.*"

    Shkalla e dështimit me njerëzit që e bëjnë këtë është **shumë më e lartë** sesa ata që braktisin plotësisht. Kjo është kryesisht për faktin se nëse jeni duke kaluar një moment të keq gjatë periudhës së tërheqjes, është e lehtë të hipni në shfletuesin dhe të vizitoni haremin me arsyetimet e mësipërme. Nëse keni indinjitetin të thyeni qartë rregullat tuaja si një dritare xhami e thyer, ka më shumë gjasa të kapërceni tundimin. Në çdo rast, dhimbja ndoshta do të kishte kaluar tashmë nëse do ta vononit. Megjithatë, arsyeja kryesore për shkallën e lartë të dështimit në këto raste është se përdoruesi nuk ndihej plotësisht i përkushtuar për të ndaluar në radhë të parë. Mos harroni dy gjërat thelbësore për të pasur sukses janë:

    -   Siguria.

    -   “*A nuk është e mrekullueshme që nuk kam më nevojë për pornografi*"

    Në secilin rast, pse në tokë keni nevojë për një seancë? Nëse ende keni nevojë të vizitoni haremin tuaj, së pari rilexoni librin. Diçka nuk është bërë shumë. Merrni kohë për të vrarë përbindëshin e madh të larjes së trurit në mendjen tuaj të vdekur.

2.  “*A duhet t'i shmang rastet stresuese ose sociale gjatë periudhës së tërheqjes?*"

    Në rastin e situatave stresuese, po. Nuk ka kuptim t'i bëni vetes presion të panevojshëm. Në rastin e ngjarjeve sociale, si bare apo klube, këshilla është e kundërta. Dilni dhe kënaquni menjëherë! Ju nuk keni nevojë për seks apo anën propaganduese të seksit edhe kur jeni të varur nga pornografia. Dilni dhe gëzohuni për faktin që nuk keni nevojë të bëni seks apo seks propagandues, kjo do t'ju vërtetojë shpejt të vërtetën e bukur që jeta është shumë më e mirë pa këto presione. Vetëm mendoni se sa më mirë do të jetë kur përbindëshi i vogël të largohet nga ju, së bashku me ato mendime nevojtare.
