# Momenti i Shpalljes

Zakonisht brenda tre javësh pas arratisjes, ish-përdoruesit përjetojnë momentin e zbulimit. Qielli duket se bëhet më i ndritshëm dhe është momenti kur shpërlarja e trurit përfundon plotësisht. Kur në vend që t'i thuash vetes se nuk ke nevojë të shikosh pornografi, befas kupton se filli i fundit është prishur dhe mund të shijosh pjesën tjetër të jetës tënde pa pasur kurrë nevojë për të. Është gjithashtu nga kjo pikë që ju zakonisht filloni t'i shikoni përdoruesit si objekte keqardhjeje.

Ata që braktisin përdorimin e metodës së vullnetit normalisht nuk e përjetojnë këtë moment, sepse megjithëse janë të lumtur që janë ish-përdorues, ata vazhdojnë të ecin në jetë duke besuar se po bëjnë një sakrificë. Sa më shumë të jesh i varur, aq më i mrekullueshëm është ky moment dhe zgjat gjithë jetën. Ndërsa ka shumë gëzime në jetë, është e pamundur të rimarrë ndjenjën aktuale të përjetimit të tyre. Gëzimi i të mos pasurit më të shikuar pornografi është i ndryshëm, nëse ndiheni të dobët dhe keni nevojë për një nxitje, kujtojini vetes se sa bukur është të mos jesh i lidhur me atë varësi të tmerrshme. Shumë e rendisin atë si një nga ngjarjet më të mëdha të jetës së tyre. Në shumicën e rasteve, momenti i shpalljes ndodh jo pas tre javësh, por pas disa ditësh.

Në rastin tim, kjo ndodhi përpara se të mbaroja vizitën time të fundit në harem. Jam i sigurt që shumë nga lexuesit këtu, para se të arrinin në fund të kapitujve, do të thoshin diçka të tillë si “*Nuk duhet të thuash asnjë fjalë tjetër. Unë mund t'i shoh të gjitha kaq qartë, do ta di se nuk do të kem më nevojë për pornografi.*" Bazuar në komentet e marra, kjo ndodh shpesh. Në mënyrë ideale, nëse ndiqni të gjitha udhëzimet dhe kuptoni plotësisht psikologjinë, kjo duhet t'ju ndodhë menjëherë.

Ndërsa thuhet se duhen rreth pesë ditë që të kalojë tërheqja e dukshme fizike dhe rreth tre javë që një ish-përdorues të jetë plotësisht i lirë, udhëzime të tilla mund të shkaktojnë dy probleme. E para është që sugjerimi është futur në mendjet e njerëzve se ata do të duhet të vuajnë nga pesë ditë deri në tre javë. E dyta është se ish-përdoruesi priret të mendojë "*Nëse mund të mbijetoj për pesë ditë ose tre javë, mund të pres një nxitje të vërtetë në fund të asaj periudhe."

Megjithatë, ato mund të kenë pesë ditë të këndshme ose tre javë të këndshme, pastaj të pasuara nga ditë katastrofike që godasin të gjithë, të cilat nuk kanë të bëjnë fare me varësinë, por shkaktohen nga faktorë të tjerë në jetën tonë. Më pas, ish-përdoruesi ynë që pret momentin e zbulimit përjeton depresion. Mund të shkatërrojë besimin e tyre. Në të njëjtën mënyrë, nëse nuk do të kishte udhëzime, ish-përdoruesi mund të kalonte pjesën tjetër të jetës së tij duke pritur që asgjë të mos ndodhte. Kjo është ajo që ndodh me shumicën dërrmuese të atyre që ndalojnë përdorimin e metodës së vullnetit.

Njerëzit shpesh pyesin për rëndësinë e pesë ditëve dhe tre javëve. A janë ato thjesht perioda të nxjerra nga bluja? Jo, megjithëse nuk janë data të përcaktuara, ato pasqyrojnë një grumbullim të reagimeve ndër vite. Rreth pesë ditë pas ndalimit është kur ish-përdoruesi pushon së pasuri varësinë si profesionin kryesor të mendjes së tij. Shumica e ish-përdoruesve përjetojnë zbulime rreth kësaj periudhe, përgjithësisht në situata stresuese ose sociale që në një moment nuk ishin në gjendje t'i përballonin ose nuk ishin të këndshme pa një vizitë në harem. Papritur e kuptoni se jo vetëm që po kënaqeni apo po e përballoni atë, por as që ju ka shkuar në mendje mendimi i pornografisë. Nga ajo pikë zakonisht është lundrim i thjeshtë. Kjo është kur ju e dini se jeni të lirë.

Është e imja dhe përvoja e shumë të tjerëve që përpiqen të ndalojnë përdorimin e *metodës së fuqisë së vullnetit* që rreth periudhës trejavore është kur përpjekjet më serioze për të ndaluar dështojnë. Ajo që ndodh zakonisht është se pas rreth tre javësh ndjen se e ke humbur dëshirën për të parë pornografi. Ju duhet t'ia vërtetoni këtë vetes, kështu që hipni në shfletuesin për të vizituar haremin tuaj. Ndihet e çuditshme, duke dëshmuar se e ke shkelmuar. Por gjatë procesit ju lyeni rrëshqitjen e ujit DeltaFosB falë dopaminës së freskët, atë që trupi juaj ka dëshiruar për tre javët e fundit. Sapo përfundoni veprën, dopamina fillon të largohet nga trupi juaj. Rishfaqet një zë i vogël, "*Nuk e ke shkelmuar, do një tjetër.*"

Ju nuk do të ktheheni menjëherë, sepse nuk dëshironi të fiksoheni përsëri, duke lejuar që të kalojë një periudhë e sigurt. Kur të tundoheni, mund t'i thoni vetes "*Epo, nuk u lidha përsëri, kështu që nuk ka të keqe të kesh një tjetër."* Ju tashmë jeni duke zbritur në shpatin e rrëshqitshëm. Çelësi i problemit nuk është të presësh për momentin e zbulimit, por të kuptosh se sapo të mbyllësh shfletuesin, ai ka mbaruar. Ti ke ndërprerë furnizimin me oksigjen për përbindëshin tënd të vogël. Asnjë forcë në Tokë nuk mund të të pengojë të jesh i lirë , *përveç rastit kur nuk e shqetësoni ose prisni për zbulesë.* Shkoni dhe shijoni jetën; përballeni me të që në fillim. Momenti do të vijë së shpejti.
