# Reagimet

Lufta nuk është kundër përdoruesve, por kurthit të industrisë së pornografisë, dhe është bërë për arsyen e thjeshtë se unë e bëj me kënaqësi. Sa herë që dëgjoj për arratisjen e një përdoruesi nga burgu, ndjej një ndjenjë kënaqësie të jashtëzakonshme. Por kjo kënaqësi nuk ka kaluar pa zhgënjime të konsiderueshme, të shkaktuara kryesisht nga dy kategori përdoruesish të pornografisë. Pavarësisht nga paralajmërimi në kapitullin e mëparshëm, unë jam vazhdimisht i befasuar nga numri i atyre që e kanë të lehtë të ndalojnë, por më vonë fiksohen dhe zbulojnë se nuk mund të kenë sukses herën tjetër.

Është si të gjesh dikë deri në qafë në një moçal dhe gati të shkosh poshtë. Ju ndihmoni t'i largoni dhe ata janë mirënjohës, por më pas, gjashtë muaj më vonë zhyten përsëri në moçal. Përdoruesit që e kanë të lehtë të ndalojnë dhe të fillojnë përsëri paraqesin një problem të veçantë, megjithatë kur të liroheni ***JU LUTEM, JU LUTEM, MOS BËNI TË NJËJTËN GABIM.*** Ata besojnë se njerëz të tillë fillojnë përsëri sepse janë ende të lidhur dhe u mungon dopamina. Në fakt, ndalimin e kanë aq të lehtë saqë humbasin frikën nga pornografia. Ata mendojnë, "*Mund të bëj një seancë të çuditshme, dhe edhe nëse më lidh sërish, do ta kem të lehtë të ndaloj.*"

Kam frikë se thjesht nuk funksionon në këtë mënyrë, sepse është e lehtë të ndalosh pornografinë, por e pamundur të kontrollosh varësinë. E vetmja gjë thelbësore për të ndaluar pornografinë është mospërdorimi i saj.

Njerëzit zakonisht kthehen në pornografi sepse e keqkuptojnë "të lehtë" në EasyPeasy.

Imagjinoni dikë të ulur në dyshemenë e ftohtë të betonit të një dhome ngrirjeje. Në murin përballë tyre ka një dritare që tregon një ditë të përsosur pranvere jashtë - pemët që lëkunden butësisht, zogjtë që cicërijnë - pikërisht pranë një dere të hapur.

A duhet ndonjë vullnet për të dalë nga ajo dhomë ngrirjeje? Jo! A është më e vështirë të ikësh sesa të qëndrosh? Sigurisht që jo! (Në fakt, është pak më e lehtë për shkak të lëvizjes së trupit). Pse dikush me mendje të drejtë do ta vendoste veten në një situatë të tillë, duke i shkaktuar vetes muaj apo vite zhgënjim nëse nuk mashtrohej?

EasyPeasy i shtyn mënjanë perdet në mënyrë që përdoruesi të shohë qartë jashtë dhe për të hequr **iluzionet** se sa e tmerrshme mund të jetë jashtë dhe sa rehat është përdoruesi në dhomë.

Kategoria tjetër e përdoruesve zhgënjyes janë ata që janë shumë të frikësuar për të bërë përpjekjen për të ndaluar, ose kur e bëjnë, e shohin atë një luftë të madhe. Vështirësitë kryesore duket se janë si më poshtë.

**Frika nga dështimi.**

:   Nuk ka turp në dështim, por të mos provosh është një marrëzi e thjeshtë. Shikoni në këtë mënyrë, ju po fshiheni nga asgjëja. Gjëja më e keqe që mund të ndodhë është që të dështoni, në këtë rast nuk jeni më keq se tani. Vetëm mendoni se sa e mrekullueshme do të ishte të kishim sukses. Nëse nuk e bëni këtë përpjekje, tashmë e keni të garantuar dështimin.

**Frika nga dhimbja dhe të qenit i mjerë.**

:   Mos u shqetësoni për këtë, vetëm mendoni: çfarë gjëje e tmerrshme mund të ndodhë me ju nëse nuk shikoni më kurrë pornografi? Absulutisht asgjë. Gjëra të tmerrshme *do* të ndodhin nëse bëni; rilexoni shënimet mbi bastin e Paskalit. Në çdo rast, paniku është shkaktuar nga dopamina dhe së shpejti do të zhduket. Fitimi më i madh është të çlirohesh nga ajo frikë. A besoni vërtet se përdoruesit janë të përgatitur të kenë depërtime të zbehta, performancë seksuale jo të besueshme ose kënaqësi iluzore që marrin nga pornografia? Nëse e gjeni veten në panik, frymëmarrja e thellë do t'ju ndihmojë. Nëse jeni me njerëz të tjerë dhe ata po ju zhgënjejnë, ikni prej tyre dhe shkoni në garazh, një zyrë bosh ose diku.

    Nëse të vjen të qash, mos u turpëro. E qara është mënyra e natyrës për të lehtësuar tensionin. Askush nuk ka pasur ndonjëherë një qarje të mirë pa u ndjerë më mirë më pas. Një nga gjërat e tmerrshme që u bëjmë të rinjve është t'i kushtëzojmë ata të mos qajnë. Ju mund t'i shihni ata duke u përpjekur të luftojnë lotët, por shikoni nofullën duke u larguar. Ne e mësojmë veten të mos tregojmë emocione, por nuk jemi të destinuar t'i fusim ato brenda. Bërtisni, bërtisni ose keni zemërim. Goditni diçka. Konsideroni luftën tuaj si një ndeshje boksi që nuk mund ta humbni. Askush nuk mund ta ndalojë kohën, çdo moment që kalon ai përbindësh i vogël brenda teje po vdes. Shijoni fitoren tuaj të pashmangshme.

**Duke mos ndjekur udhëzimet.**

:   Në mënyrë të pabesueshme, disa përdorues thonë se metoda nuk funksionoi për ta. Më pas ata përshkruajnë se si ata injoruan jo vetëm një udhëzim, por praktikisht të gjithë. Për qartësi, këto janë përmbledhur si një listë kontrolli në fund të këtij kapitulli.

**Udhëzimet e keqkuptimit.**

:   Problemet kryesore duket se janë këto:

    “*Nuk mund të ndaloj së menduari për pornografinë.*"

    :   Sigurisht që nuk mundesh dhe nëse provon, do të krijoni një fobi, duke u bërë i mjerë. Është si të përpiqesh të flesh natën: sa më shumë të përpiqesh, aq më e vështirë bëhet. Nuk ka rëndësi nëse mendoni për pornografinë për nëntëdhjetë për qind të jetës tuaj, është ajo që mendoni se është e rëndësishme. Nëse po mendoni "*Oh, më pëlqen të shikoj pornografi*" ose "*Kur do të jem i lirë?*" do të jeni të mjerë. Nëse në vend të kësaj jeni duke menduar “*YIPPEE! Unë jam i lirë!*" do të jeni të lumtur.

    “*Kur do të vdesë përbindëshi i vogël pornografik?*"

    :   Skuqja e dopaminës largohet nga trupi juaj shumë shpejt, por është e pamundur të thuhet se kur trupi juaj do të pushojë së vuajtur nga ndjesia e lehtë fizike e tërheqjes së dopaminës. Kjo ndjenjë boshe, e pasigurt është identike me urinë, depresionin ose stresin normal. Gjithçka që bën pornografia është të rrisë nivelin e saj. Kjo është arsyeja pse përdoruesit që ndalojnë përdorimin e metodës së fuqisë së vullnetit nuk janë kurrë plotësisht të sigurt nëse e kanë shkelmuar atë, edhe pasi trupi i tyre ka pushuar së vuajturi nga tërheqja e dopaminës. Nëse vuajnë nga uria ose stresi normal, truri i tyre ende u thotë atyre se kjo është një arsye e vlefshme për të kërkuar seancën e tyre të drejtë. Çështja është se nuk duhet të presësh që të largohet dëshira, pasi është aq e lehtë saqë as nuk e dimë se është aty, vetëm duke e ditur si një ndjenjë e dëshirës. Kur largoheni nga dentisti, prisni që nofulla juaj të ndalojë së dhemburi? Sigurisht që nuk e bëni, ju vazhdoni me jetën. Edhe pse nofulla juaj ende dhemb, ju jeni të gëzuar.

        Mos prisni që tërheqjet të largohen sepse do të krijoni dyshime duke pyetur vazhdimisht veten “*Sa kohë do të zgjasë kjo? A jam i lirë edhe nëse nuk ndihem ndryshe?*" Frika është dhimbja aktuale, prandaj pritja që jeta të përmirësohet pas lënies do të krijojë dyshime. Tërheqja është e padukshme nëse nuk e keni frikë dhe përmirësimet eksponenciale në neurologji janë të ngadalta, kështu që nëse prisni të ndiheni ndryshe, do të ndiheni sikur asgjë nuk po ndodh, duke krijuar dyshime.

    *"'Momenti i zbulesës' nuk ka ardhur ende."*

    :   Nëse e prisni, thjesht po shkaktoni një fobi tjetër. Një herë ndalova për tre javë në metodën e vullnetit. Duke biseduar me një mik të vjetër, ai më pyeti se si po kaloja.
        “*Kam mbijetuar tre javë*”, iu përgjigja.
        Ai pyeti: "* Çfarë do të thotë, ke mbijetuar tre javë?*"
        Unë sqarova, "*Kam kaluar tre javë pa pornografi.*"
        Ai tha: “*Çfarë do të bësh? Të mbijetosh pjesën tjetër të jetës? Çfarë prisni, e keni bërë. Ju jeni një jo-përdorues.*"

        Mendova, "*Ai ka absolutisht të drejtë, çfarë po pres?*" Fatkeqësisht, për shkak të mungesës së kuptimit të kurthit, u ktheva shpejt, por pika u vu re. Ju bëheni një jo-përdorues kur mbyllni shfletuesin tuaj. Gjëja e rëndësishme është të jesh një jo-përdorues i lumtur që në fillim.

    “*Unë kam ende mall për pornografi.*"

    :   Atëherë po tregohesh shumë budalla. Si mund të pretendoni se dëshironi të jeni jo-përdorues dhe më pas të thoni se doni pornografi? Kjo është një kontradiktë. Nëse thoni se doni pornografi, po thoni që dëshironi të jeni përdorues. Jo-përdoruesit nuk duan të vizitojnë faqet e neveritshme të tubave. Ju tashmë e dini se çfarë dëshironi të jeni, ndaj ndaloni së ndëshkuari veten.

    “*Unë kam hequr dorë nga jeta.*"

    :   Pse? E tëra çfarë ju duhet të bëni është të ndaloni së vrari veten dhe në vend të kësaj të filloni të jepni energji. Ju nuk duhet të ndaloni së jetuari sadopak. Është kaq e thjeshtë, për dy ditët e ardhshme do të keni një traumë të lehtë në jetën tuaj. Trupi juaj do të pësojë një përkeqësim pothuajse të padukshëm të tërheqjes nga kërkesat dhe pretendimet për një rritje të dopaminës. Tani, mbani në mend këtë: nuk jeni më keq se sa ishit. Kjo është ajo që keni vuajtur për gjithë jetën tuaj, sa herë që keni fjetur, në kishë, supermarket apo bibliotekë. Dukej se nuk të shqetësonte kur ishe përdorues dhe nëse nuk ndalesh, do të vazhdosh ta vuash këtë shqetësim për pjesën tjetër të jetës.

        Pornografia dhe orgazmat nuk krijojnë raste, ato ju privojnë prej tyre. Edhe kur trupi juaj është ende i dëshiruar për dopaminën, vaktet dhe rastet sociale janë të mrekullueshme. Jeta është e mrekullueshme - shkoni në funksione sociale, edhe nëse atje ka kërcimtarë të zhveshur. Mos harroni se ju nuk jeni duke u privuar, ata janë. Secili prej tyre do të donte të ishte në pozicionin tuaj, sikur ta dinte. Kënaquni të jeni prima donna dhe qendra e vëmendjes. Ndalimi i pornografisë është një pikë e mrekullueshme bisede, duke marrë një kënaqësi të fshehtë që ata nuk munden. Miqtë dhe bashkëmoshatarët tuaj do të befasohen kur të shohin se ju, më parë me turp dhe me pamje të lodhur, tani jeni të lumtur dhe të gëzuar. Ju do të shijoni jetën që në fillim; nuk ka nevojë t'i keni zili piktorët në festa, ata do t'ju kenë zili - vetëm sikur ta dinin.

    “*Unë jam i mjerë dhe nervoz.*"

    :   Ky është një dështim për të ndjekur udhëzimet. Zbuloni se cila është. Disa njerëz kuptojnë dhe besojnë gjithçka që është shkruar, por gjithsesi fillojnë me një ndjenjë dënimi dhe zymtësie, sikur diçka e tmerrshme po ndodhte. Ju nuk po bëni vetëm atë që dëshironi të bëni, por edhe atë që do të donte çdo përdorues në planet. Me çdo metodë ndalimi, ish-përdoruesi po përpiqet të arrijë një kornizë të caktuar mendore, kështu që çdo mendim i lidhur me pornografinë shënohet nga "*YIPPEE! Unë jam i lirë!*" Nëse ky është objektivi yt, pse të presësh? Fillo me atë mendje dhe mos e humb kurrë. Nuk ka alternativë.

    “*Kam kaluar një javë / muaj / gjashtë muaj të mirë, por jam kthyer në kurth.*"

    :   Mos harroni, frika është vetë dhembja. Dhënia në një dhembje gjeneron më shumë frikë, duke ushqyer përbindëshin e vogël të dobësuar dhe duke pasur sukses në frikësimin e jo-përdoruesit që të mendojë se është i lidhur për jetën. Në realitet, konceptimi i tyre për larjen e trurit nuk ka ndryshuar, por ata i kanë dhënë dopaminë procesit të të menduarit. Kjo sipas definicionit bie përpara, por është një dështim për të ndjekur udhëzimet. Kuptojeni se cilën më poshtë dhe gëzohuni.

## Lista e Kontrollit

Nëse ndiqni këto udhëzime, nuk mund të dështoni:

1.  Bën një betim solemn se kurrë, kurrë, nuk do të shkosh në internet për të vizituar haremin tuaj *OSE* kënaquni me fotografi statike *OSE* bëni paqe me grafika erotike *OSE* çdo gjë që përmban stimuj supernormalë dhe qëndroni në zotimin tuaj.

2.  Merreni qartë këtë në mendjen tuaj: Nuk ka absolutisht asgjë për të hequr dorë. Me këtë, nuk do të thotë se do të jeni më mirë si jo-PMOer (e keni ditur këtë gjatë gjithë kohës); as që edhe pse nuk ka asnjë arsye racionale pse ju PMO, ju merrni një kënaqësi ose mbështetje prej saj, pasi përndryshe nuk do ta bënit. Ajo që do të thotë është se ***nuk ka kënaqësi të vërtetë apo mbështetje në PMOing.*** Është thjesht një iluzion, si të përplasësh kokën pas një muri për të marrë kënaqësi kur ndalon.

3.  Nuk ka gjë të tillë si PMOer i konfirmuar. Ju jeni vetëm një nga qindra miliona që kanë rënë në kurthin delikate. Ashtu si miliona ish-PMO të tjerë që dikur mendonin se nuk mund të shpëtonin, ju keni shpëtuar.

4.  Nëse në çdo moment në jetën tuaj do të peshonit të mirat dhe të këqijat e PMOing, përfundimi dërrmues do të ishte gjithmonë “*Ndaloni ta bëni atë. Ti je një budalla!*" Asgjë nuk do ta ndryshojë kurrë këtë. Ka qenë gjithmonë kështu dhe gjithmonë do të jetë. Pasi të keni marrë atë që dini se është vendimi i duhur, mos e torturoni kurrë veten duke dyshuar. Basti i Paskalit vlen në mënyrë të përsosur për PMO, pa asnjë shans për humbje, shanse të larta fitimi dhe shanse të larta për të shmangur humbjet.

5.  Mos u mundoni të mos mendoni për pornografinë, ose mos u shqetësoni se po mendoni vazhdimisht për të. Kurdoherë që mendoni për këtë, qoftë sot, nesër, apo pjesën tjetër të jetës suaj, mendoni **“YIPPEE! Unë jam JO-PMOer!"**

6.  **Mos** përdorni asnjë formë zëvendësuesi. **Mos** sfidoni veten duke e mbajtur laptopin pranë jush ndërsa flini. **Mos** shmangni shfaqjet, filmat ose revistat. **Mos** e ndryshoni stilin tuaj të jetesës në asnjë mënyrë thjesht sepse keni ndaluar. Nëse ndiqni udhëzimet e mësipërme, së shpejti do të përjetoni 'momentin e zbulesës', por:

7.  Mos prisni që të vijë ‘momenti i shpalljes’. Thjesht vazhdoni jetën tuaj, duke shijuar momentet më të larta dhe duke u përballur me të ulëtat. Ju do të gjeni në asnjë kohë fare, momenti do të arrijë.
