# Ndihmoni ata në anijen që po fundosen

Përdoruesit e pornos janë në panik në ditët e sotme, duke ndjerë ndryshime në mënyrën se si pornografia e internetit perceptohet nga burrat dhe gratë. Natyra e varur e pornografisë në internet po studiohet gjithnjë e më shpesh, tani me të drejtë konsiderohet si e ndryshme nga pornografia tradicionale. Pamundësia dhe disponueshmëria ngre alarmin edhe në zemrat e mbështetësve të pornografisë. Ata gjithashtu ndjejnë se kryqëzata e tyre për fjalën dhe mendimin e lirë po rrëmbehet nga elementë të ndryshëm. Perëndimi i egër i internetit pa policë e bën pothuajse të pamundur zbatimin e kufizimeve të moshës ndaj stimujve supernormalë. Është për të ardhur keq që kjo nuk do të përfundojë së shpejti, por qindra mijëra përdorues po ndalojnë, me shumicën e të varurve të vetëdijshëm për studimet që tregojnë ngjashmëri midis varësisë nga pornografia dhe substancave. Sa herë që një përdorues largohet nga anija që po fundoset, ata që mbeten në të ndihen gjithnjë e më të mjerueshëm.

Çdo përdorues e di instinktivisht se është qesharake të vetësabotosh dhe të kalosh kohë përballë pikselëve dydimensionale, duke tejkaluar trurin e tyre dhe në proces duke zhvilluar rrugë nervore që garantojnë performancë të dobët seksuale. Nëse ende nuk mendoni se është marrëzi, provoni të flisni me një revistë porno që qëndron në qendër të qytetit tuaj dhe pyesni veten se cili është ndryshimi. Vetëm një. Nuk mund ta marrësh kënaqësinë e ngrohtësisë dhe intimitetit në këtë mënyrë. Nëse mund të ndaloni blerjen e alkoolit dhe cigareve sa herë që shkoni në pazar ushqimor, patjetër që mund të ndaloni së vizituari haremin tuaj në internet. Përdoruesit nuk mund të gjejnë arsye racionale për të parë pornografi, por ata nuk ndihen aq budallenj nëse e bëjnë edhe njerëzit e tjerë.

Përdoruesit gënjejnë hapur për zakonin e tyre, jo vetëm për studiuesit dhe ata përreth tyre, por edhe për veten e tyre. Ata duhet të bëjnë – shpëlarja e trurit është thelbësore nëse duan të ruajnë njëfarë respekti për veten. Ata ndjejnë nevojën për të justifikuar 'zakonin' e tyre jo vetëm për *veten e tyre* por edhe për jo-përdoruesit. Ata reklamojnë përgjithmonë avantazhet iluzore të pornografisë me mjete më delikate.

Nëse një përdorues ndalon duke përdorur metodën e vullnetit, ai ende ndihet i privuar, duke u prirur të bëhet ankues. E gjithë kjo është t'u konfirmojë përdoruesve të tjerë se sa të drejtë kanë ata për të vazhduar përdorimin. Nëse ish-përdoruesi arrin të heqë dorë nga zakoni, atëherë ata janë mirënjohës që nuk duhet të kalojnë më jetën duke vetësabotuar ose duke humbur energji dhe nuk kanë nevojë të justifikohen. Mos harroni, është frika që e mban kokën e përdoruesit në rërë, duke vënë në dyshim sjelljen e tyre vetëm kur ndalon. Ndihmoni përdoruesin duke hequr ato frikë. Tregoju atyre se sa e mrekullueshme është të mos kalosh jetën në një burg, sa bukur është të zgjohesh në mëngjes duke u ndjerë në formë dhe të shëndetshme në vend që të kesh mungesë energjie dhe urrejtje ndaj vetvetes, sa e mrekullueshme është të jesh i lirë nga skllavëria , për të qenë në gjendje të shijoni tërë jetën tuaj dhe të shpëtoni nga ato hije të zeza. Ose akoma më mirë, bëjini të lexojnë këtë libër.

Është thelbësore të mos nënçmoni një përdorues të martuar duke treguar se ata po e prishin qëllimisht marrëdhënien e tyre ose se është në një farë mënyre mashtrim ose i papastër. Ekziston një keqkuptim i zakonshëm se ish-përdoruesi është më i keqi në këtë aspekt. Ky konceptim ka një përmbajtje, por në përgjithësi është për shkak të metodës së vullnetit të ndalimit. Sepse ish-përdoruesi - megjithëse e ka hequr këtë zakon - ende ruan një pjesë të larjes së trurit dhe ende beson se ka bërë një sakrificë. Ata ndihen të pambrojtur dhe mekanizmi i tyre mbrojtës natyror është të sulmojnë përdoruesin e pornografisë.

Kjo mund të rrisë egon e ish-përdoruesit, por nuk e ndihmon asgjë. Gjithçka që bën është të vendosë kurrizin pas murit, duke i bërë ata të ndihen edhe më të mjerë dhe rrjedhimisht nevojën e tyre për pornografi edhe më të madhe. Megjithëse ndryshimi në qëndrimin e institucionit mjekësor ndaj pornografisë në internet është arsyeja kryesore pse shumë përdorues po e lënë, kjo nuk e bën më të lehtë për ta bërë këtë. Në fakt, kjo e bën shumë më të vështirë. Shumica e përdoruesve në ditët e sotme besojnë se po ndalojnë kryesisht për arsye shëndetësore. Kjo nuk është rreptësisht e vërtetë.

Edhe pse rreziku i madh për shëndetin është padyshim arsyeja kryesore për të lënë duhanin, përdoruesit kanë sabotuar virtytin e tyre për vite me rradhë dhe kjo nuk ka bërë as më të voglin ndryshim. Arsyeja kryesore pse përdoruesit po ndalojnë është sepse shoqëria ka filluar të shohë pornografi të demaskuar për atë që është: varësinë ndaj drogës. Qëndrimet e shoqërive po ndryshojnë ngadalë: shumë partnerë tani do të bëjnë pyetje nëse jeni në laptop në mes të natës.

Ndalimet e plota të pornografisë në disa vende ose padisponueshmëria e internetit janë shembuj klasikë të dilemës së përdoruesit udhëtues. Në përgjithësi ata mbajnë qëndrimin se kjo do t'i ndihmojë ata të reduktojnë marrjen e tyre. Rezultati ishte se në vend të një ose dy në ditë, asnjë prej të cilave nuk do të kishin shijuar, ata abstenojnë për një javë të tërë. Megjithatë, gjatë kësaj periudhe të detyrueshme të abstinencës, jo vetëm që do të jenë të privuar mendërisht duke pritur shpërblimin e tyre, por edhe trupi i tyre ka mall. Oh, sa e çmuar është ajo vizitë e haremit në internet kur ato lejohen përfundimisht.

Abstinencat e detyrueshme në fakt nuk e reduktojnë marrjen sepse përdoruesi thjesht kënaq veten edhe më shumë kur më në fund lejohet të jetë vetëm. Gjithçka që bën është të ngulitë në mendjen e përdoruesit se sa e çmuar është pornografia e internetit dhe sa e varur janë ata prej saj. Aspekti më tinëzar i kësaj abstinence të detyruar është efekti i tij tek adoleshentët. Ne i lejojmë rrëmbyesit e 'lirisë së shprehjes', prodhuesit e pornografisë, të synojnë adoleshentët fatkeq për t'i kapur në radhë të parë. Pastaj, në atë që është ndoshta periudha më stresuese në jetën e tyre, kur, në mendjet e tyre të mashtruara, ata kanë nevojë më shumë për pornografi, ne i shantazhojmë që të heqin dorë për shkak të dëmit që po i shkaktojnë vetes.

Shumë prej tyre nuk janë në gjendje ta bëjnë këtë dhe janë të detyruar, pa fajin e tyre, të vuajnë një kompleks faji për pjesën tjetër të jetës së tyre. Shumë ia dalin dhe janë të kënaqur ta bëjnë këtë, duke menduar, *\“Mirë. Do ta bëj këtë për momentin dhe pasi të përfundojë do të shërohem gjithsesi.\"* Më pas vjen dhimbja dhe frika e gjetjes së punës dhe vështirësitë e tjera të të rriturve, të ndjekura nga 'high' më i madh i jetës së tyre – gjetja e një pune. Dhimbja dhe frika kanë mbaruar, tani ndihen të sigurt, mekanizmi i vjetër i ndezjes kthehet në funksion. Një pjesë e larjes së trurit është ende aty dhe përpara se aroma e laptopit të ri të punës të jetë zhdukur, përdoruesi është në pragun e haremit të tij të preferuar në internet. Ngazëllimi i rastit ua bllokon ndjenjat e ndyra nga mendja, ata nuk kanë ndërmend të tërhiqen përsëri, por vetëm një shikim nuk mund të dëmtonte\... Shumë vonë! Ata tashmë janë fiksuar sërish.

Dëshira e vjetër nga përbindëshi i vogël do të fillojë përsëri dhe edhe nëse ata nuk fiksohen përsëri menjëherë, depresioni pas rritjes me siguri do t'i kapë ata. Është e çuditshme që megjithëse të varurit nga heroina janë kriminelë në ligj, përgjigja e shoqërisë është duke i ndihmuar këta individë. Le të mbajmë të njëjtin qëndrim ndaj përdoruesit të varfër të pornografisë. Ata nuk po e bëjnë sepse duan, por sepse mendojnë se duhet. Ndryshe nga të varurit nga heroina, ata zakonisht vuajnë vite pas vitesh tortura mendore dhe fizike. Ne gjithmonë themi se një vdekje e shpejtë është më e mirë se një e ngadaltë, ndaj mos e kini zili përdoruesin e varfër të pornografisë. ***Ata e meritojnë keqardhjen tuaj.***
