# Këshilla për jo-përdoruesit

## Ndihmoni që pornografia juaj të përdorë miqtë për të lexuar këtë libër

Së pari, studioni përmbajtjen e këtij libri dhe përpiquni të vendosni veten në vendin e përdoruesit. Mos i detyroni të lexojnë këtë libër duke u thënë se po ua prishin shëndetin ose po luajnë me zjarrin. Ata e dinë këtë më mirë se ju. Përdoruesit nuk vazhdojnë të shikojnë pornografi sepse u pëlqen ose sepse duan, ata vetëm ua thonë këtë gjë vetes dhe njerëzve të tjerë në mënyrë që të ruajnë respektin për veten. Ata e bëjnë këtë sepse janë të varur nga pornografia sepse mendojnë se ajo i relakson, u jep kurajo ose besim (kënaqësi ose mbështetje) dhe sepse mendojnë se jeta nuk do të jetë kurrë e këndshme pa "seks" - të paktën versioni i tyre. Nëse përpiqeni dhe detyroni një përdorues të ndalojë, ai do të ndihet si një kafshë e bllokuar dhe do ta dëshirojë haremin e tyre edhe më shumë. Kjo mund t'i kthejë ata në një përdorues të fshehtë dhe pornografia do të bëhet edhe më e çmuar në mendjen e tyre.

Në vend të kësaj, përqendrohuni në anën tjetër të medaljes. Bëjini ata në shoqërinë e ish-përdoruesve (blog, forume, YBOP, NoFap, etj., megjithëse kini kujdes nga mbrojtja e metodës së vullnetit). Bëjini ata t'i tregojnë përdoruesit se si edhe ata menduan se ishin të lidhur gjatë gjithë jetës dhe sa më mirë është jeta si jopërdorues. Pasi t'i keni bërë të besojnë se mund të ndalojnë, mendja e tyre do të fillojë të hapet. Më pas filloni të shpjegoni iluzionin e krijuar nga dhembjet e tërheqjes. Jo vetëm që 'ngutjet e dopaminës' nuk u japin atyre një nxitje, por po shkatërrojnë besimin e tyre dhe po e bëjnë veten nervoz dhe të lodhur.

Ata tani duhet të jenë gati ta lexojnë vetë këtë libër, duke pritur të lexojnë faqe pas faqe tregimesh rreth zgjimit jo të besueshëm, depërtimeve të zbehta, PIED, PE, etj. Shpjegoni se kjo qasje është krejtësisht e ndryshme dhe referencat ndaj sëmundjes janë pjesë të vogla të materialit.

Me pak fjalë, mos e lini këtë të vdesë në errësirë. Tregojuni miqve tuaj, por mos u bëni të çuditshëm për këtë. Nëse përpiqeni të 'fitoni' bisedën ose të bëni një debat, do të keni sukses vetëm t'i largoni ata dhe t'i rrisni më tej frikën.

## A duhet t'i tregoj të tjerëve tim të rëndësishëm?

A duhet t'i tregoj gruas, të dashurës ose partnerit tim për zakonin tim? (Qëllimi është t'ju ndihmojmë në lënien.) Këtu luajnë një rol të madh faktorësh.

Nëse tashmë keni dështuar të hiqni dorë duke përdorur metodën e fuqisë së vullnetit dhe i keni thënë tashmë partnerit tuaj, tregojini për qasjen tuaj të re dhe lejojini të edukohen duke lexuar librin. Ata do të jenë në gjendje t'ju ndihmojnë dhe motivojnë gjatë periudhës së tërheqjes dhe janë një fortesë kur përbindëshi i vogël përpiqet t'ju pengojë.

Nëse sapo jeni bërë të vetëdijshëm për ekzistencën e kurthit pornografik dhe nuk keni tentuar ta lini në të kaluarën, fillimisht përdorni vetë EasyPeasy. Siç u shpjegua më parë, kjo duhet të jetë një përvojë e këndshme. Megjithatë, nëse e keni të vështirë, kërkoni ndihmën e tyre. Jini të hapur dhe të pambrojtur me partnerin tuaj dhe kjo do të forcojë marrëdhënien tuaj.

Me kusht që të kënaqeni me arratisjen dhe nuk e keni të vështirë nga pavendosmëria, nuk ka shumë arsye për ta bërë të ditur partnerin tuaj. Nëse nuk ishte një problem në të kaluarën, le të vdesë. Megjithatë, jini të përgatitur që partneri juaj mund të pyesë veten pse po dukeni, ndiheni dhe performoni më mirë!

## Partneri im po lë pornografinë

Pornografia është një shkatërrues pervers i marrëdhënieve dhe ndërsa lënia mund të bëhet menjëherë, shërimi kërkon kohë. Shumë përdorues, për shkak të besimeve irracionale të lindura nga varësia e tyre, e largojnë zemërimin e tyre ndaj partnerëve dhe njerëzve të dashur. Këto sjellje manifestohen në sjellje me gaz, gënjeshtra dhe manipuluese. Kjo nuk është e gjithë përdoruesit, por është gjithnjë e më e zakonshme në fazat e mëvonshme të sëmundjes. Ndërkohë që këto sjellje mund të jenë shfaqur nga varësia themelore ndaj pornografisë, është e rëndësishme të edukoni veten rreth këtyre sjelljeve dhe nëse njiheni, merrni parasysh të shihni një terapist të specializuar në varësitë seksuale.

Nëse partneri juaj është brenda periudhës së tërheqjes, supozoni se është duke vuajtur nëse janë apo jo. Mos u përpiqni ta minimizoni duke u thënë atyre se është e lehtë ta ndaloni, ata mund ta bëjnë këtë vetë. Në vend të kësaj, vazhdoni t'u tregoni atyre se sa krenarë jeni, sa më mirë duken ata, sa më e ëmbël është të jesh me ta dhe sa më të lehtë janë në përgjithësi. Është veçanërisht e rëndësishme të vazhdosh ta bësh këtë, sepse kur një përdorues përpiqet të ndalojë, euforia e përpjekjes dhe lavdërimet që marrin nga bashkëmoshatarët mund t'i ndihmojnë. Megjithatë, ata kanë tendencë të harrojnë shpejt, kështu që vazhdoni të lavdëroni.

Për shkak se ata nuk po flasin për pornografi, ju mund të mendoni se e kanë harruar dhe nuk dëshironi që t'ua kujtoni. Zakonisht e kundërta ndodh me metodën e vullnetit, pasi ish-përdoruesi priret të jetë i fiksuar pas asgjë tjetër. Pra, mos kini frikë të ngrini temën dhe vazhdoni t'i lavdëroni ata (ata do t'ju thonë nëse nuk duan t'u kujtohet).

Dilni nga rruga juaj për t'i lehtësuar ata nga presionet gjatë periudhës së tërheqjes, duke menduar mënyra për ta bërë jetën e tyre interesante dhe të këndshme. Kjo mund të jetë gjithashtu një periudhë provuese për jo-përdoruesit që nuk kanë pasur kurrë varësinë. Nëse një anëtar i një grupi është nervoz, mund të shkaktojë mjerim të përgjithshëm të gjithanshëm. Pra, parashikoni këtë nëse ish-përdoruesi ndihet i irrituar, ai mund ta heqë atë kundër jush, por mos u hakmerrni, është në këtë moment ata kanë më shumë nevojë për lavdërimin dhe simpatinë tuaj. Nëse ndiheni vetë të nervozuar, gjë që është e kuptueshme, përpiquni të mos e shfaqni.

Një nga truket që një i varur do të luajë kur përpiqet të heqë dorë me ndihmën e metodës së fuqisë së vullnetit është të nxehet, duke shpresuar që partneri ose miqtë e tyre të thonë “*Nuk mund të duroj të të shoh duke vuajtur kështu. Për hir të Zotit, vetëm merrni helmin tuaj.*" Prandaj, përdoruesi nuk duhet të humbasë fytyrën, pasi nuk 'dorëzohet', ai është udhëzuar. Nëse ish-përdoruesi e bën këtë marifet, në asnjë mënyrë inkurajojini ata që të kthehen përsëri. Në vend të kësaj thuaj, "*Nëse kjo është ajo që të bën pornografia, faleminderit zotit që së shpejti do të jesh i lirë. Sa e mrekullueshme që kishe guximin të hiqje dorë nga ajo.*"

Mbani mend, ka dy palë shëruese brenda rrugëtimit të rimëkëmbjes. Kur partneri juaj po lë pornografinë, është e rëndësishme të keni rrjetin tuaj të mbështetjes, rutinat dhe kufijtë e vetë-kujdesit. Ky proces nuk ndodh brenda natës, duke kërkuar besim, komunikim dhe llogaridhënie. Gazetarja, zhvillimi i pasioneve tuaja dhe më e rëndësishmja, terapia, e ndihmojnë këtë proces.

## Rrëshqitje (rikthim)

Ekzistenca e këtij seksioni duhet të shërbejë si paralajmërim për ata që largohen nga kurthi. Personalisht, nuk kam rikthyer kurrë, por do të përdor përvoja nga intervistat me anëtarët e komunitetit dhe mjete nga terapia konjitive e sjelljes për të ilustruar.

Së pari, ta quash atë një rikthim është kundërproduktive. Gjithçka që ka ndodhur është se ju keni rrëshqitur dhe keni ushqyer përbindëshin e vogël, i cili nga ana tjetër fillon përbindëshin e madh të larjes së trurit. Përdoruesit që rrëshqasin (që sipas përkufizimit bie përpara) zakonisht krijojnë një gamë të tërë besimesh irracionale:

  - "*Nuk do të jem kurrë i lirë*" - **Katastrofizimi**
  - "*Unë duhet / duhet të ushtrohem, të studioj dhe të jem i frytshëm çdo ditë të jetës sime*" (edhe si - **Musterbating**)
  - "*Sot kam bërë PMO, kështu që ç'dobi ka të lexoj të gjithë librat dhe forumet... Qëllimi im ishte të mos bëja as M, por ja ku jam — një dështim — duke u rikuperuar.*" - **Tolerancë e ulët frustrimi**
  - “*Miqtë e mi / lexuesit e forumit / të tjerët nuk bëjnë PMO për (n) ditë, por nuk mundem kështu që jam një rast i pashpresë. U ndjeva mirë dje pasi studiova mirë dhe isha frytdhënës, por sot nuk e bëra... Po shkoj tatëpjetë.*" - **Vlerësimi midis vetvetes dhe të tjerëve**
  - "Unë nuk duhet të kem mendime seksuale" - Vetë, prindërit ose shoqëria e tyre në tërësi kanë instaluar **besime të ngurta** në lidhje me seksin. Pyesni veten nëse vetëflagjelimi po ju ndihmon të arrini qëllimet tuaja dhe nëse po, a po e shijoni udhëtimin?

Faktorët që arrijnë kulmin në larjen e trurit të çdo përdoruesi janë në dukje të pafund. Ju e njihni veten më mirë se kushdo tjetër, por padyshim që është një dështim për të ndjekur udhëzimet. E keni parë vlerën në pornografi, por si?

Ajo që shpesh neglizhohet është se duhet kohë për të ndryshuar larjen e trurit. Kjo nuk e bën më të vështirë, por pothuajse çdo industri përdor seksin dhe kundërvënia në mënyrë aktive e larjes së trurit është një proces i ndërgjegjshëm (të paktën për të filluar), kështu që mund të duhet kohë për të ngurtësuar plotësisht mësimet e përfshira brenda. Prandaj, rekomandohen lexime të shumta (mund të kaloni te kapitujt me të cilët keni vështirësi) dhe nuk duhet t'ju marrë shumë kohë.

Një përvojë çuditërisht e zakonshme për përdoruesit fetarë që largohen nga kurthi është dëshira që ajo të lëndojë pak, si një formë shlyerjeje. Ata e kanë kaq të lehtë të heqin dorë, pastaj ndihen fajtorë që ndihen në këtë mënyrë. Por pse të vetësabotoni dhe ta bëni të vështirë? Përbindëshi i vogël është shumë i poshtër në këtë drejtim.

Shkëputeni veten nga përbindëshi i vogël - ai u shtua nga industria e pornografisë shumë kohë më parë. Imagjinoni një ngacmues që ka një zemërim në sheshin e lojërave të shkollës. Çfarë i thoni një dhunuesi? Nëse dorëzoheni, thjesht do t'i përforconi ato. Disa që e lënë dorën përfundojnë duke ushqyer ngacmuesit, dhe kështu rrisin larjen e trurit të tyre, por konceptimi i tyre për kurthin nuk ka ndryshuar. Merrni veten, kuptoni se ku keni gabuar dhe shijoni lirinë!

Ju nuk jeni dëshira juaj. Meditimi i vetëdijes është praktika e vërejtjes së mendimit dhe ka mësime themelore në natyrën e mendjes që duhen gjetur. Rekomandohet shumë që të meditoni në përgjithësi, dhe është gjithashtu plotësisht në përputhje me praktikën fetare. Nuk mund të luftosh as me veten, as me përbindëshin e vogël. Ju duhet ta doni pa kushte veten dhe procesin.

Por hiqni dështimin nga mendja juaj. Këtu është një seksion nga "*Meditimet e një të varur nga porno*" nga Gulliaco (lidhur në seksionin e Burimeve në fund të librit):

> Meqenëse shikimi i pornografisë të ofron zero përfitime, është diçka që vetëm të dhemb, dhe është jashtëzakonisht qesharake të duash të bësh diçka të tillë, unë e krahasoj atë me pirjen e zbardhuesit. Ja ku shkoni:
>
> **Udhëtimi i vështirë për të mos pirë zbardhues.**
>
> Përshëndetje! Ne jemi NoBleach dhe organizojmë sfida të rinisjes në të cilat pjesëmarrësit ("Bleachstronauts") abstenojnë nga pirja e zbardhuesit për një periudhë kohore. Nëse qëllimi juaj është pjesëmarrja e rastësishme në një sfidë mujore si një provë e vetëkontrollit, ose nëse pirja e tepërt e zbardhuesve është bërë problem në jetën tuaj dhe dëshironi të lini për një periudhë më të gjatë kohore, do të gjeni një komunitet mbështetës dhe shumë të burimeve këtu.
>
> - “*Ndonjëherë e lejoj veten të pi një ose një gotë zbardhues. Unë e di se "një pikë" është një gënjeshtër, por nuk mendoj se një gotë e vetme do të dëmtojë. Nuk mund të shkatërrohen të gjitha orët që kam kaluar pa e bërë këtë.*”
> - “*Nuk e kam problem të mos pi zbardhues, por ndonjëherë shkoj në rrugë dhe shoh dikë që pi ujë, e dini, në një gotë dhe imagjinoj se gota ka zbardhues në të. Më pas kam mall dhe, pasi debatoj me veten nëse duhet ta bëj apo jo, më në fund dorëzohem natën dhe pi një gotë.*”
> - “*Shiko, problemi im është se ndonjëherë, kur jam vetëm në kuzhinë, filloj të shoh gotat, herë tundoj veten duke hapur enën ku mbaj zbardhuesin, herë e marr erën dhe… Epo, Përfundoj aty ku e nisa. Jam shumë i dëshpëruar ta ndaloj këtë, por nuk jam i sigurt nëse do ta bëj ndonjëherë
në gjendje të ndalojë.*”
> - “*Të ndalosh së piri zbardhues është e pamundur, dua të them, unë gjithmonë e kam gojën, e kupton? Si duhet të ndaloj nëse kam gjithmonë një fyt që më kujton se mund të gëlltis zbardhuesin?*”
> - “*O burrë, po kalonte kaq mirë, 19 ditë të tëra pa e bërë. E rëndësishme është të mësosh nga dështimi! Tani e di se çfarë të shmang të bëj: të shikoj produktet e pastrimit në supermarket. Do të mundohem ta bëj deri në një muaj! Unë do të rivendos numrin tim. Më uro fat!*"

> Nëse ke dëshirë, qetësohu shoku! Mbani mend se çfarë thotë Hackbook:
>
> "*Zbardhuesi është i vështirë të heqësh dorë nga frika se po privohemi nga kënaqësia ose mbështetja jonë. Frika se disa situata të këndshme nuk do të jenë më kurrë të njëjta. Frika për të qenë të paaftë për të përballuar situatat stresuese. Me fjalë të tjera, janë efektet e larjes së trurit që na mashtrojnë për të besuar se blerja e zbardhuesit, dhe si rrjedhim pirja e tij, është një domosdoshmëri për të gjitha qeniet njerëzore. Edhe më tej, është besimi se ka diçka të natyrshme në zbardhuesin e përballueshëm që na nevojitet, dhe se kur të ndalojmë së përdoruri, do të mohojmë veten dhe do të krijojmë një boshllëk. Bëje të qartë këtë në mendjen tënde: Zbardhuesi nuk mbush një boshllëk, ai krijon një të tillë!*”
>
> Dhe unë them:
> “* Supozoni se jeni të detyruar të shikoni një gotë plot me zbardhues për pesë minuta. Mundohuni të mbani mend një nga ato markat ose aromat që ju pëlqeu aq shumë. Ndoshta shoqërohet me ndonjë tingull, ose mbani mend vetëm detaje të zgjedhura. Zbardhuesi është aty dhe nuk mund të mbyllësh sytë apo të kthesh kokën, sepse ky zbardhues është në mendjen tënde, është një kujtim i regjistruar në ty.*
>
> *A ndjeni ndonjë mall? A ndjeni ndonjë gjë në gjuhën tuaj apo ndonjë ndryshim në frymëmarrje? Cilat janë ndjenjat tuaja për atë që po mbani mend? I identifikoni, zbardhuesi dëshiron t'i turbullojë, t'i bëjë konfuze dhe t'ju bëjë t'i kushtoni vëmendje vetëm asaj që dëshiron t'ju kapë.*"
>
> Me sa më sipër, nuk po përpiqem të shpërfill ndjenjat e tua, aq më pak të them diçka të tillë si "haha më i zgjuar ti budalla", por për të të dhënë perspektivë në mënyrë që të kuptosh se sa qesharake është (dhe gjithmonë do të jetë) ta kapërcesh këtë varësi.
> Shikimi i pornografisë nuk është si një çelës ndezës/fikës ku thua "*oh mirë, jam në situatën X, atëherë do të shikoj pornografi*". Fantazi! Gënjeshtra! Sa shpesh e lejoni veten të pini një gotë zbardhues? Asnjëherë? Pse? Sepse është një gjë e tmerrshme, kjo është arsyeja pse! Si duhet t'i shpëtoni varësisë tuaj nëse nuk e bëni këtë kuptoni se PMO është një gjë e tmerrshme për t'i bërë vetes?

## Po në lidhje me MO (masturbim, orgazmë)?

Njerëzit kanë mbetur pa probleme për shekuj me radhë. Për të qenë të qartë, pornografia është problemi.

Thënë kjo, ju mund të jeni ende të lidhur me MO për të njëjtat arsye si pornografia, të tilla si mentaliteti 'nevoja për të pasur një orgazmë', përshkallëzimi mendor, detyrimi i trupit për të bërë seks dhe thjesht kënaqësi hedoniste - duke kërkuar.

Ka shumë të ngjarë që pornografia dhe masturbimi të jenë ndërthurur thellë në mendjen tuaj. Shumë përdorues zbulojnë se përfundojnë duke u përsëritur si rezultat i masturbimit ndaj fantazive të shkaktuara nga pornografia. Ndërsa truri juaj rifiton, do të zbuloni se ky shpëlarje truri përfundimisht zbehet, por është më mirë të bëni një pushim nga MO për një kohë. Ju gjithashtu duhet të kërkoni seks të vërtetë në mënyrë që ta përshpejtoni këtë proces.

Ky nuk është një udhëzim, por vlerësojeni: përfitimet e raportuara nga mbajtja e spermës janë të shumta - rritja e fokusit dhe energjisë, heqja e 'mjegullës së trurit' dhe rritja e besimit, së bashku me një mori përfitimesh të tjera. Nga përvoja personale, ka një ndryshim të qartë, dhe gjithçka varet nga mënyra se si e sublimoni këtë energji të shtuar.

Duke spekuluar dhe pa njohuri strikte shkencore, përfitimet mund të vijnë nga disa faktorë të ndryshëm.

– Pas orgazmës, truri lëshon prolaktinë, e cila pengon çlirimin e dopaminës.

- Privimi i trurit tuaj nga rrjedhjet e dopaminës lejon më shumë marrje nga jeta e thjeshtë.

- Sperma rithithet nga qarkullimi i gjakut pas ~78 ditësh dhe është një nga lëndët ushqyese më të mira që trupi juaj mund të marrë.

- Sublimimi i energjisë seksuale në zakone produktive sjell me vete një shtresë shtesë produktiviteti.

Ju gjithashtu mund të dëshironi të bëni seks pa orgazmë, e cila siç u përmend më herët, është një përvojë e mrekullueshme seksuale (shpesh e referuar si Karezza). Ju mund të forconi aftësinë tuaj për ta bërë këtë duke praktikuar ushtrimet Kegel. Nga përvoja personale, mënyra më e lehtë dhe më efektive për të synuar këtë muskul është ndalimi dhe fillimi i urinës në mes të rrjedhës (megjithëse kini kujdes të mos e teproni, gjë që mund të shkaktojë probleme më vete). Ndarja e pjesëve tantrike dhe përhapëse të seksit është një nga shpërblimet e shumta të arratisjes nga kurthi i PMO (dhe partnerët e mi e kanë dashur atë gjithashtu!).

## Devijimet nga këshillat standarde

Ky seksion është i ri dhe është shkruar disi me frikë; akoma, duhet përmendur.

Disa njerëz që përdorin EasyPeasy mendojnë se dëshira e tyre për të parë pornografi zvogëlohet aq shumë sa nuk mund ta detyrojnë veten të bëjnë një seancë të fundit. **Kjo është mirë**, por mos e nënvlerësoni fuqinë e të pasurit një të tillë. Shfletimi i kujdesshëm dhe konfirmimi se sa shumë nuk ju pëlqen PMO mund të jetë vërtet i fuqishëm. Personalisht, e pashë me të vërtetë të dobishme dhe isha i lumtur që laja duart nga ajo, me të vërtetë i lehtësuar që nuk duhej ta bëja më kurrë. Megjithatë, kilometrazhi juaj mund të ndryshojë.

Nëse tashmë keni qenë të lirë nga kurthi për një kohë dhe sapo keni hequr larjen e trurit, nuk ka nevojë të ushqeni përbindëshin e vogël pasi thjesht do t'ju shqetësonte. Në vend të kësaj, shijoni lirinë!

## Ndihmoni t'i jepet fund këtij skandali

Pornografia në internet është një nga rreziqet në një shoqëri të lirë, duke mbështetur përpjekjet vullnetare të avokatëve për lirinë personale. Sigurisht që vetë baza e qytetërimit - arsyeja pse speciet njerëzore ka përparuar deri tani - është sepse ne jemi të aftë të komunikojmë njohuritë dhe përvojat tona, jo vetëm njëri-tjetrit, por edhe brezave të ardhshëm. Edhe kafshët e kanë të nevojshme të ruajnë pasardhësit e tyre nga grackat e jetës.

Prodhuesit e pornografisë nuk po e bëjnë këtë me mirëbesim, duke besuar vërtet se e ndihmojnë njerëzimin, veçanërisht tani pasi varësia ndaj pornografisë në internet është studiuar gjerësisht. Ndoshta në fazat e tij fillestare njerëzit besonin vërtet se pornografia i edukonte njerëzit për intimitetin, por autoritetet e dinë se kjo është një gabim. Asnjë faqe tube nuk bën pretendime të vërteta për arsimin. Pretendimet e vetme të bëra janë për tronditjen, risinë dhe cilësitë në rritje të mallrave të tyre.

Hipokrizia e plotë është e pabesueshme: si shoqëri ne përndryshe shqetësohemi për bullizmin në shkollë dhe objektivizimin e trupit të njeriut. Krahasuar me pornografinë në internet, këto probleme janë thjesht puçrra. Një numër i të varurve ngjiten në lartësi të reja çdo vit, duke kaluar kohë cilësore me njerëz imagjinarë dhe iluzorë pikselë në kurriz të shëndetit, fuqisë, energjisë dhe kohës së tyre. Është deri tani vrasësi më i madh në marrëdhënie, dhe qindra mijëra jetë shkatërrohen çdo vit sepse janë të lidhur. Prodhuesit e pornografisë në internet nuk reklamojnë në botimet kryesore - ata nuk kanë nevojë, nxitjet tona biologjike na çojnë në pragjet e haremeve të tyre të pajisur mirë, duke dhënë mostra falas si tregtari lokal i drogës. Në ditët e sotme, faqet e tubacioneve nuk rezervojnë aq shumë mallrat sa inkurajojnë vizitorët të postojnë përmbajtje.

Sa e zgjuar është që kompanitë pornografike tregojnë paralajmërime *18+* si pengesë për përdoruesit e mitur, edhe pse disa as që mundohen ta bëjnë këtë. Pornografia në internet prek të gjithë në të gjitha moshat. "*Ne ju paralajmëruam për rrezikun, kështu që është zgjedhja juaj*", është qëndrimi i tyre. A ndërmarrin ndonjë hap për të verifikuar moshën? Jo, kjo do t'i dekurajonte klientët e tyre. Sigurisht, nëse verifikimi i moshës legalizohet, ata thjesht do të të gjejë një vend tjetër nga ku të operojë. Ose, do të paguajnë ndonjë 'elitë' për të shkruar se si ndalimi rezultoi në vjedhje dhe krijimin e mafies? Është harruar me lehtësi pyetja se pse shfuqizimi i ndalimit nuk rezultoi në uljen e alkoolit- viktima të lidhura, dhe dështimi i zbatimit të ligjit për të kontrolluar rritjen e mafies.

Këtë mund ta trajtojmë ndryshe duke edukuar brezin e ri. Nëse ata mund të shkelin cigaren dhe alkoolin kur blejnë, ata mund të bëjnë të njëjtën gjë me pornografinë në internet. Tashmë po shohim ndryshime shoqërore të tilla si memet "No Nut November" dhe "Coomer" duke u bërë të zakonshme. Përdoruesi nuk ka zgjedhje më shumë sesa i varur nga heroina. Përdoruesit nuk vendosin të fiksohen, ata janë të joshur në një kurth delikate. Nëse do të kishin zgjedhjen, përdoruesit e vetëm nesër në mëngjes do të ishin adoleshentët që sapo kishin filluar, duke besuar se mund të ndalonin në çdo kohë nëse dëshironin.

Pse standardet e rreme? Pse personat e varur nga heroina shihen si kriminelë, por mund të regjistrohen si të varur dhe të marrin metadon dhe trajtimin e duhur mjekësor për të ndihmuar në largimin e tij? Thjesht provo të regjistrohesh si i varur nga pornografia – nëse shkoni te mjeku juaj për ndihmë, ai ose do t'ju thotë: "*Mos e bëni kaq shumë, provoni moderimin*", që tashmë e dini se nuk do të funksionojë, ose do të përshkruajë ilaçe për të trajtuar 'depresionin' tuaj. Më e keqe është këshilla për të shkuar dhe për të gjetur partnerë të vërtetë — seriozisht? A nuk kanë dëgjuar kurrë për përdorues që gjejnë pornografi më mirë dhe e bëjnë atë pas shpinës së partnerit të tyre? Disa njerëz thjesht nuk e kuptojnë.

Fushatat e frikësimit nuk i ndihmojnë përdoruesit të ndalojnë, ato e bëjnë më të vështirë. Gjithçka që ata bëjnë është të trembin përdoruesit, gjë që i bën ata të duan të shikojnë edhe më shumë. Ata gjithashtu nuk i pengojnë adoleshentët që të fiksohen. Adoleshentët e dinë se pornografia ua vret epshin, por gjithashtu e dinë se një shikim i vetëm nuk do ta bëjë këtë. Për shkak se varësia është kaq e përhapur, herët a vonë adoleshenti - qoftë përmes presioneve sociale apo kuriozitetit - do të provojë vetëm një vizitë. Për shkak se pornografia falas ka klipe të tmerrshme, ka të ngjarë që ato të fiksohen.

Pse e lejojmë të vazhdojë ky skandal? Pse qeveritë nuk dalin me fushatat e duhura? Pse nuk na thuhet se pornografia në internet është një drogë dhe helm vrasës, që nuk të relakson apo të jep besim, por të shkatërron nervat, duke marrë vetëm një shikim për t'u fiksuar? Pse nuk mund të zbatojnë verifikimin e moshës duke kërkuar karta krediti të regjistruara, ndoshta me një palë të tretë? MindGeek, pronar i shumë prej faqeve kryesore pornografike, po përpiqet të mashtrojë qeveritë që të përdorin zgjidhjen e tyre të verifikimit të moshës - mos i lini ta bëjnë këtë! H. G. Well's *The Time Machine* përshkruan një incident në të ardhmen e largët ku një njeri bie në një lumë. Shokët e tij thjesht ulen rreth bregut si bagëti të pavëmendshme ndaj britmave të dëshpërimit. Çnjerëzore dhe shqetësuese, njëlloj si apatia e përgjithshme e shoqërisë ndaj krizës pornografike.

Ka një erë ndryshimi të shoqërisë. Një top bore ka filluar të rrokulliset poshtë kodrës dhe shpresohet se ky libër do të ndihmojë në shndërrimin e tij në një ortek. Edhe ju mund të ndihmoni duke përhapur mesazhin.

Si i tillë, për të pyetur - nëse shihni dikë që po lufton duke përdorur vullnetin, ose duke u përpjekur të heqë dorë nga pornografia, drejtojini ata drejt kësaj metode. Megjithatë, detyra e vërtetë në dorë është ndryshimi i narrativës rreth pornografisë në përgjithësi. Ju lutemi, merrni parasysh të krijoni një zakon që nëse shihni në internet ose madje përjetoni normalizimin e pornografisë nga dora e parë, synoni t'i edukoni dhe t'i lironi ata *me respekt*.

Herë pas here, mund të merrni një reagim negativ, por ndonjëherë një koment është gjithçka që duhet. Siç kanë bërë shumë para jush, ju mund të prisni të merrni mesazhe nga njerëz mirënjohës që ju falënderojnë për lirinë e tyre.

## Paralajmërim Përfundimtar

Tani mund të shijoni pjesën tjetër të jetës si një jo-përdorues i lumtur. Për t'u siguruar që po e bëni këtë, duhet të ndiqni këto udhëzime të thjeshta.

1.  Mbajeni faqen e mëposhtme në faqeshënuesit tuaj dhe referojuni asaj aq sa ju nevojitet.

2.  Nëse ndonjëherë filloni të keni zili një përdorues tjetër, kuptoni se ata do t'ju kenë zili. Ju nuk jeni duke u privuar. Ata janë.

3.  Mos harroni se nuk ju pëlqeu të jeni përdorues. Prandaj ndaluat. Ju pëlqen të jeni jo-përdorues.

4.  Mos harroni, nuk ka gjë të tillë si vetëm një vështrim.

5.  Asnjëherë mos dyshoni në vendimin tuaj për të parë më kurrë pornografi. Ti e di që është e duhura.

6.  Nëse keni ndonjë vështirësi, gjeni dhe kontaktoni një terapist me njohuri në pornografinë e internetit. Ju mund të gjeni listat e tyre në internet.
