# Udhëzimet

1.  Ndiqni të gjitha udhëzimet.

2.  Mbani një mendje të hapur.

3.  Filloni me një ndjenjë gëzimi.

4.  Injoroni të gjitha këshillat dhe ndikimin që bie ndesh me EasyPeasy.

5.  Rezistoni çdo premtim për një rregullim të përkohshëm.

6.  Kuptoni qartë në mendjen tuaj: pornografia nuk ofron kënaqësi të vërtetë apo patericë dhe ju nuk po bëni një sakrificë. Nuk ka asgjë për të hequr dorë dhe asnjë arsye për t'u ndjerë i privuar.

7.  Mos prisni të hiqni dorë, bëjeni tani!

8.  Merrni një vendim që të mos shikoni më kurrë dhe të mos e vini në dyshim.

9.  Mos harroni se nuk ka gjë të tillë si vetëm një vështrim.

10. Mos shikoni më kurrë pornografi.

## Pohime

-   Unë jam i lirë nga skllavëria e pornografisë.

-   Është e lehtë të injorosh mendimet e mia për pornografinë.

-   Mirupafshim mendime, lamtumirë nxitje. Oh, ja ku shkojnë dëshirat e mia.

-   Unë e fokusoj mendjen time nënndërgjegjshëm për të kapërcyer varësinë ndaj pornografisë.

-   Pornografia më vjedh kohën, energjinë dhe vitalitetin.

-   Rrahja e pornografisë bëhet në mënyrë eksponenciale më e lehtë dita ditës dhe në çdo aspekt.

-   Më pëlqen dhe vlerësoj stilin tim të jetesës pa pornografi, të fortë, të lumtur, dhe të lehtë.

-   Nëse shikoj prapa dhe mendoj për përparimin tim, më jep gëzim dhe krenari të madhe për veten time.

-   Sa herë që shoh përdorues të tjerë pornografie, motivohem më shumë për të parë veten duke e thyer atë zinxhir.

-   E gjithë ajo energji e ndrydhur po shëron trupin dhe mendjen time. Më pas, mund të bëj punë më produktive dhe sfiduese drejt vlerave dhe qëllimeve të mia.

-   Truri im po kthehet në formën e duhur, duke u ushtruar nga unë *jo* duke bërë atë që bëja më parë.

-   Tani gjithë ai vullnet i ndrydhur po përdoret për të përballuar streset dhe sforcimet e lehta të jetës.

-   Shkëlqyeshëm, jam i lirë dhe nuk jam më skllav!
