# Fundi i Librit

Faleminderit që lexuat; siç e dini, më mbush me një gëzim të sinqertë që keni gjetur lirinë.

Ëndërroj për një botë ku nuk kishe nevojë.

Një botë ku filluat të pyesni pornografinë përpara se ta gjenit, duke vënë re efektet që kishit mësuar në shkollë.

Aty ku dikush që përmendte pornostarin e tyre të preferuar u takua me atë atmosferë të 'gabimit të vështirë shoqëror', por menjëherë u pasua nga një dëshirë e sinqertë për të ndihmuar.

Një ku të gjithë ishin pak më pak në buzë; duke punuar së bashku me komunitetet lokale që janë më të qëndrueshme, më të afërta dhe të vëmendshme.

Nuk jemi aq larg sa mendoni.

## Ku jemi tani? {-}

Ju ekzistoni aty ku pornografia është normalizuar në kulturë, media dhe jetën e përditshme. Jini të sigurt se kjo nuk do të qëndrojë: shkenca është absolute dhe gjithçka që qëndron me kohën duhet të bazohet në të vërtetën.

Ju jeni dëshmitar i një ndryshimi shoqëror kundër tij; komunitetet në internet, muajt e festuar të abstenimit dhe bisedat e shtyjnë topin e borës -- por sa kohë dëshironi të prisni?

## Si keshtu? {-}

Qëllimet tona janë të thjeshta:

1. Deri në fund të vitit 2023, edukimi me pornografi duhet të jetë i detyrueshëm në të gjitha programet e edukimit seksual. Thjesht nuk ka kohë për të humbur.
2. Deri në fund të vitit 2024, pornografia është e zgjedhur dhe e kufizuar sipas moshës në nivelin e ofruesit të shërbimit, në mënyrë që fëmijët e vegjël ta shmangin atë.
3. Deri në fund të vitit 2025, EasyWay e Allen Carr duhet të jetë në krye të fushatave të nikotinës.

## Si mund të ndihmoj? {-}

Tani për tani unë jam duke krijuar komunitete në internet për të koordinuar veten.

Ju mund të përdorni platformat e mëposhtme.

**[Urbit](https://urbit.org/overview) ~mogsub-possum/coomer** -- ju mund të gjeni udhëzues për [bashkimin në rrjet] dhe [përdorimin e tij] këtu.

**[Discord](https://discord.com/invite/bCXEnf9)** -- e cila aktualisht është thjesht duke postuar në qendër që nuk shqetësohem t'i kontrolloj, por po punoj në sfond me njerëz për ta kthyer atë në diçka interesante.

**[Email](https://docs.google.com/forms/d/e/1FAIpQLSfi27XGmChe_qtu4fP6E6lNyjY8Ia_93TlfGbjbKgiI1VNdkg/viewform)** -- ku mund të regjistroheni për të marrë emaile shumë të rastësishme nga unë

Pra, nëse jeni dikush, nga kudo, me ndonjë aftësi ose sasi të kohës së lirë, do të jeni në gjendje të ndihmoni në çlirimin e të tjerëve.

Nuk është ende gati sepse gjithçka duhet të jetë e strukturuar në mënyrë perfekte, por mund të bashkoheni në kanale të ndryshme tani dhe të bisedoni.

### Po ti? {-}

Emri im është Fraser dhe jam një student psikologjie 23 vjeçar nga Australia.

Më pëlqen shumë të ndihmoj njerëzit dhe mendoj se sa më shumë njerëz të lirë nga pornografia, aq më mirë!

Do të preferoja të takohesha personalisht, por ja ku ekzistoj në internet.

**yt:** [Fraser Patterson](https://www.youtube.com/channel/UChMZhvS7eV-WoLDu_mRjEEw) -- Postimi i videove të qeta për jetën time dhe pak urtësira

**ig:** [@deleteinstaplease](https://instagram.com/deleteinstaplease) -- Herë pas here, foto të natyrës, ose çfarë po bëj.

**tw:** [@deletetwitpls](https://twitter.com/deletetwitpls) -- Nuk postoj këtu

*Ju lutem, mos u ndjeni nën presion për të më ndjekur*, por e dini, pak presion sepse më jep më shumë 'ndikim' në mënyrë që të mund t'u them podkasteve dhe gjërave "hey mate mendje nëse hapem?"

## Nuggets Mençurie {-}

Lënia e pornografisë është pjesa e lehtë, pjesa 'e vështirë' është udhëtimi përpara.

Këtu janë disa gjëra që mund t'ju ndihmojnë për të.

Nëse ndjeni se jeni **varur nga teknologjia**, kuptoni se mendimet tuaja përputhen me shpejtësinë e jetës. Ngadalësoni jetën tuaj duke përjetuar natyrën dhe thajeni agjërimin për 24 orë në një dhomë të errët.

Ky nuk është një "shërim i të gjitha", por ju jep kohë për të menduar dhe paqe me mendimet tuaja.

Duke folur për këtë, **meditimi i ndërgjegjes** rekomandohej më parë.

Meditimi është praktikë e të kuptuarit se si është gjithmonë mendja juaj. Mendimet lindin vazhdimisht dhe kalojnë.

Ju do të mendoni për pornografinë -- sigurisht -- dhe meditimi ndihmon në njohjen e tyre si vetëm kaq: mendimet.

Unë do të rekomandoja shumë të merrni një [muaj falas Waking Up]
Nuk po paguhem për rekomandimin e kësaj, është thjesht një aplikacion vërtet, vërtet i shkëlqyeshëm. Do të rekomandonim shumë fillimisht kursin hyrës, pastaj disa tekste Alan Watts dhe Wisdom nga Jayasara. Të gjitha përvojat shumë të bukura.

Sigurisht, **frymëmarrja** do të ndihmonte akoma.

Unë do të rekomandoja teknikat e frymëmarrjes Bukeuko dhe Wim Hof.

Tani për tani, vendosni një dorë në bark dhe një në gjoks.

Më pas, merrni frymë ndërsa nxirrni buzët në formë O (po.. haha ​​xd!!)

Ju do të ndjeni diafagmën tuaj të aktivizuar, gjë që keni marrë frymë natyrshëm si fëmijë. Është më mirë për ju në çdo mënyrë dhe kërkon më pak përpjekje nga trupi juaj.

Ju morët frymëmarrje të cekët sepse të gjithë të tjerët po e bëjnë këtë, dhe ne i pasqyrojmë natyrshëm njerëzit.

Tingëllon e njohur?

Epo, për varësitë, nuk ka dyshim se do të kënaqeshit ta lini...

**Alkooli!**

Krahas krijimit të një tërheqjeje 10-ditore, alkooli arrin të 'marrëzisë' konsumatorët dhe nuk ju jep kënaqësi, besim, kurajo apo relaksim.

Libri i Jason Vale *Kick the Drink... Easily!" dekonstrukton alkoolin plotësisht. Ai argumenton se nuk ka gjë të tillë si një alkoolist -- njerëzit që 'humbin kontrollin' (të një boshllëku që krijon varësi) thjesht stigmatizohen dhe shmangen -- dhe se lënia është jashtëzakonisht e lehtë.

E lashë alkoolin pas PMO-së dhe i kam gjetur jetën dhe rastet sociale vërtet shumë më të këndshme pa të.

Një ilaç për mpirjen dhe helmimin e vetes është shumë 'boomer', nuk mendoni?

Por ndoshta të gjithë janë thjesht viktima të...

**Konsumimi.**

Pra, këtu është një citat në lidhje me të.

>
>
...

>*Nuk më pëlqen shpesh dhe as nuk gjej shumë përdorim në dekonstruksionin e tepruar, por akti i argëtimit bashkëkohor kërkon një proces të tillë për ta tërhequr atë në gjyq. Për shkak se kjo është ajo që shumica e njerëzve harrojnë kur shikojnë televizor ose lëvizin nëpër telefonin e tyre, është një akt, ata po kryejnë një veprim, sado banal dhe i mpirë të jetë ai. Çdo veprim i kryer vazhdimisht përfundimisht bëhet zakon, të paktën në një kuptim të caktuar, pavarësisht nëse ju pëlqen apo jo. Dhe në rrënjë, veprimi që po kryeni kur dikush është i përfshirë në argëtimin bashkëkohor është apatia. Kjo është e drejtë, njeriu ka gjetur një mënyrë jo vetëm që të jetë aktivisht apatik, por gjithashtu ka gjetur një mënyrë për ta kultivuar këtë sjellje në një mënyrë të tillë që të jetë bërë virtyt - "Vëlla, e kalova gjithë fundjavën duke parë Netflix!" Le ta ndajmë këtë, le të shohim se si njeriu vendos të kalojë jetën që i është dhënë-*
>
>*Ka një burrë ose një grua, të mbytur në një divan. Trupi i tyre në një pozicion të çuditshëm të panatyrshëm, i gjithi i palosur dhe i rrumbullakosur, nuk ka kuptim të marrin më shumë peshë se çdo tjetër, ata janë një grumbull i madh gome. Ata do të qëndrojnë këtu, thjesht do të ulen, në të njëjtën hapësirë ​​4 këmbë me 4 këmbë për orë të tëra - bota është shumë më e madhe se kjo meqë ra fjala - ata do të lëvizin krahun, ndoshta do të ripozicionohen, por kjo është për të përdorur trupin e tyre. Sa i përket mendjes së tyre, ajo fjalë për fjalë është duke punuar në vendosjen e saj më të ulët. Ndryshe nga leximi, mësimi, meditimi, praktikimi apo përqendrimi, aktet bashkëkohore të argëtimit nuk kërkojnë asgjë nga shikuesi, përveç një gjëje, që ata të shikojnë në një drejtim të caktuar. Ata janë mediumet e apatisë. Dikush, po të donte, mund të mpihej gjithkund, përveç syve, dhe do të vazhdonin të bënin aktin e ‘argëtimit’, ja sa patetik është ky akt. Unë nuk kam asgjë kundër asaj që është në TV, as asgjë kundër mediave vizive, ajo që jam kundër është media që është një mjet për të arritur qëllimin. Njerëzit nuk i pëlqejnë më shfaqjet televizive ose filmat specifikë, ata pëlqejnë Netflix-in ose shikimin e TV në tërësi. Ata janë argëtimet e preferuara janë të qenit apatikë ndaj gjithçkaje që mund të jenë. Është edhe një herë një pyetje nëse e keni dëshiruar ndonjëherë këtë në radhë të parë, apo dikush tjetër ka vendosur që kjo është dëshira normale për të pasur?*

--- Meta Nomad, [Dalja nga Moderniteti](https://jdemeta.net/2019/09/15/exiting-modernity/) // ([pdf](https://jdemeta.net/wp-content/uploads/2019/09/Exiting-Modernity.pdf))

Shpenzimi i më pak kohë para ekraneve (krahas mësimit të syve) përmirëson gjithashtu...

**Shkurtërpamje.**

Shumica e rasteve të miopisë (nuk mund të shihet gjatë) janë krejtësisht të shërueshme.

Me pak fjalë, shumë nga afër dobëson muskulin e syrit. Vendosja e syzeve përpara e dobëson atë edhe më shumë dhe tani keni nevojë për syze më të forta. Ju mund ta ritrajnoni këtë muskul.

Shikoni,

- [EndMyopia](https://endmyopia.org)
- [Myopia is Mental](https://www.myopiaismental.com/)
- [Visions of Joy](https://visionsofjoy.org)

Gjithashtu nuk keni nevojë të shpenzoni para për të kuruar...

** Tullaciteti.**

Siç mund të kuroni shumë raste duke përdorur masazh të thjeshtë të kokës.

Epo, sipas një shokut tim, i cili shpesh gjen gjëra që "duke ngjajnë me bullgare, por në të vërtetë janë të vërteta".

Ai rekomandon <https://perfecthairhealth.com>, dhe gjithashtu...

**Detoksifikimi i merkurit.**

Gjë që ai tha se funksionoi për të.

Me pak fjalë, ju merrni merkur nga mjedisi (ndonjëherë), mbushjet me amalgamë dhe madje edhe në mitër, dhe është një metal vërtet i rëndë (dhe toksik) që trupi juaj nuk mund ta heqë qafe.

Sidoqoftë, mund të kaloni një proces 'kelimi' të përshkruar në "Doracakun e Detoksifikimit të Mërkurit" për ta hequr qafe atë.

Ai thotë se jo të gjithë janë të prekur, por është mirë të merret parasysh: veçanërisht nëse keni probleme të çuditshme shëndetësore.

Gjithsesi, mbi **marrëdhëniet intime** unë do të rekomandoja tre libra:

- *Models: Attract Women Through Honesty* nga Mark Manson për të kuptuar cenueshmërinë emocionale dhe për të hequr nevojën.
- *The Rational Male* nga Rollo Tomassi, i cili është i dobishëm për të shmangur marrëdhëniet toksike.
- *The Way of The Superior Man* nga David Dieda, duke dhënë një kuptim më shpirtëror të energjive mashkullore, femërore dhe të ekuilibruar. Pretty 'new-agey' por është e drejtë.

dhe gjithashtu, për t'ju dërguar paqe të sinqertë. Sapo e keni çliruar veten nga një sëmundje e tmerrshme. Shikoni botën me sy të freskët dhe kuptim të përtërirë dhe shijoni gjithmonë udhëtimin.

Mirë se vini në pjesën tjetër të jetës tuaj.

Urimet më të ngrohta,

[Fraser Patterson](https://fraserpatterson.au)
