# Il metodo facile

L'obiettivo di questo libro è indirizzarvi verso un nuovo stato d'animo. Contrariamente al metodo abituale di smettere - per cui si inizia con la sensazione di scalare l'Everest e si passano le settimane successive a desiderare e a sentirsi privati - si inizia subito con una sensazione di euforia, come se si fosse guariti da una terribile malattia. Da quel momento in poi, più andrete avanti nella vita, più guarderete a questo periodo di tempo e vi chiederete come avete fatto a usare il porno. Guarderete gli altri utilizzatori del porno con pietà, anziché con invidia.

A condizione che siate persone che non hanno mai avuto una dipendenza (leggete per qualcun altro) o che hanno smesso (o che si trovano nei giorni di astinenza di una "dieta del porno"), è essenziale continuare a usare il porno fino a quando non avrete finito completamente il libro. Può sembrare una contraddizione, e questa istruzione di continuare a masturbarsi con il porno suscita più obiezioni di qualsiasi altra, ma proseguendo nella lettura il desiderio di usare il porno si ridurrà gradualmente. **Prendete questa istruzione sul serio: Tentare di smettere prima del tempo non vi porterà alcun beneficio**.

Molti non finiscono il libro perché sentono di dover rinunciare a qualcosa, alcuni addirittura leggono deliberatamente solo un rigo al giorno per rimandare l'evento malefico. Vedetela in questo modo: cosa avete da perdere? Se non si smette alla fine del libro, non si sta peggio di adesso. Si tratta per definizione di una scommessa di Pascal, una scommessa fatta quando non si ha nulla da perdere e si hanno alte probabilità di ottenere grandi guadagni.

Se non guardate porno da qualche giorno o settimana, ma non siete sicuri di essere consumatori, ex consumatori o non consumatori, allora non usate il porno per masturbarvi mentre leggete. In realtà, siete già un non-utilizzatore, ma dobbiamo lasciare che il vostro cervello si metta in pari con il vostro corpo. Alla fine del libro, sarete dei felici non-utenti. EasyPeasy è l'esatto contrario del metodo normale, in cui si elencano i notevoli svantaggi della pornografia e si dice: *"Se solo riuscissi a stare abbastanza a lungo senza porno, alla fine il desiderio svanirebbe e potrei godermi di nuovo la vita, libero dalla schiavitù"*.\
Questo è il modo logico di procedere, e migliaia di persone smettono ogni giorno di usare questo metodo. Tuttavia, è molto difficile riuscirci per i seguenti motivi:

**Smettere il PMO non è il vero problema.** Ogni volta che finisci la tua masturbazione, hai smesso di usarlo. Il primo giorno della tua "dieta dal porno", hai dei motivi validi per dire *"Non voglio più usare il porno e nemmeno masturbarmi"*. Tutti gli utilizzatori lo fanno, e i loro motivi sono più potenti di quanto possiate immaginare. Il vero problema è il secondo, il decimo o il decimillesimo giorno, quando in un momento di debolezza si dà "solo una sbirciatina", se ne vuole un'altra e improvvisamente si torna a essere dipendenti.

**La consapevolezza dei rischi per la salute genera più paura, rendendo più difficile smettere.** Dite ad un utilizzatore che sta distruggendo la sua virilità e la prima cosa che farà sarà cercare qualcosa per aumentare la dopamina: una sigaretta, l'alcol o persino aprire il browser per cercare un porno.

**Tutti i motivi per smettere, lo rendono in realtà più difficile.** Ciò è dovuto a due ragioni. In primo luogo, siamo continuamente costretti a rinunciare al nostro "piccolo amico" o al vizio o piacere (a seconda del modo in cui l'utente lo percepisce). In secondo luogo, creano un "cieco". Non ci masturbiamo per i motivi per cui dovremmo smettere. La vera domanda è: perché vogliamo o abbiamo bisogno di farlo?

Con EasyPeasy, (inizialmente) dimentichiamo i motivi per cui vorremmo smettere, affrontiamo il problema del porno e ci poniamo le seguenti domande:

1.  Cosa fa il porno per me?

2.  Mi piace davvero?

3.  Ho davvero bisogno di vivere la vita sabotando la mia mente e il mio corpo?

La bella verità è che *tutto il porno* non fa assolutamente nulla per voi. Sia ben chiaro, non è che gli svantaggi di essere un utente superino i vantaggi, è che ci sono ***zero*** vantaggi nel guardare la pornografia.

La maggior parte degli utenti trova necessario razionalizzare il motivo per cui fa uso del porno, ma le ragioni che escogitano sono tutte fallaci e illusorie.

Per prima cosa, elimineremo queste fallacie e illusioni. In realtà, vi renderete presto conto che non c'è nulla a cui rinunciare. Non solo, ma ci sono meravigliosi vantaggi positivi nell'essere un non-PMOer, e il benessere e la felicità sono solo due di questi vantaggi. Una volta eliminata l'illusione che la vita non sarà mai altrettanto piacevole senza il porno - rendendosi conto che la vita non solo è altrettanto piacevole senza di esso, ma lo è infinitamente di più - e una volta sradicato il sentimento di privazione o di mancanza, torneremo a riconsiderare l'aumento del benessere e della felicità e le decine di altre ragioni per smettere di usare il porno. Queste constatazioni diventeranno ulteriori aiuti positivi per aiutarvi a raggiungere ciò che desiderate veramente: godervi la vostra vita liberi dalla schiavitù della dipendenza dal porno!
