# Perchè è così difficile smettere?

Tutti gli utenti sentono che qualcosa di malvagio li ha posseduti. Nei primi giorni, si tratta di una semplice affermazione: "Smetterò, ma non oggi"\*. Alla fine si arriva a credere di non avere abbastanza forza di volontà per smettere, o che ci sia qualcosa di intrinseco nel porno che dobbiamo avere per goderci la vita. La dipendenza dal porno è come un tentativo di uscire da un pozzo scivoloso: Quando ci avviciniamo alla cima, vediamo il sole, ma ci ritroviamo a scivolare giù quando il nostro umore si abbassa. Alla fine apriamo il browser e, mentre ci masturbiamo, ci sentiamo malissimo.

Chiedete a un utente: *"Se potessi tornare indietro al momento prima di diventare dipendente, con le conoscenze che hai ora, avresti iniziato a usare il porno?"*.

*"ASSOLUTAMENTE NO!"* sarebbe la risposta.

Chiedete a un utente abituale, a qualcuno che difende il porno su Internet e non crede che provochi lesioni al cervello o una downregulation dei recettori della dopamina: *"Incoraggi i tuoi figli a usare il porno?"*.

*"ASSOLUTAMENTE NO!"* sarebbe ancora una volta la risposta.

Il porno è un enigma straordinario. Come detto in precedenza, il problema non è spiegare perché è facile smettere, ma perché è difficile smettere. Il vero problema è spiegare perché qualcuno lo fa *dopo* aver ricevuto informazioni sui danni neurologici. Parte del motivo per cui iniziamo è dovuto alle altre decine di milioni di persone che già lo fanno, eppure tutte queste persone vorrebbero non aver mai iniziato, dicendoci che è come vivere la vita in seconda marcia. Non riusciamo a credere che non si divertano, perché lo associamo alla libertà o all'essere "educati al sesso", e lavoriamo duramente per diventare dipendenti anche noi. Passiamo poi il resto della nostra vita a dire agli altri di non farlo e a cercare di abbandonare l'abitudine, spesso pensando di essere unici in questo.

Passiamo anche una parte significativa del nostro tempo a sentirci senza speranza e infelici. L'educazione al supernormale ci fa preferire e desiderare queste immagini fredde, anche quando sono disponibili quelle calde e reali. Attraverso il costante aumento e calo di dopamina indotto dal PMO, ci condanniamo a una vita di isolamento, irritabilità, rabbia, stress, stanchezza e disfunzioni sessuali. Usando il porno, astenendoci dalle parti migliori del sesso e della connessione, finiamo per sentirci infelici e colpevoli.

In effetti, leggere delle capacità di instaurare dipendenza e distruzione da parte della pornografia su Internet, qui e su altri siti, ci rende ancora più nervosi e disperati! Che tipo di hobby è quello che quando lo fai, vorresti non farlo e quando non lo fai, lo desideri? Gli utilizzatori si disprezzano ogni volta che leggono di ipofrontalità e desensibilizzazione, ogni volta che ne fanno uso alle spalle del loro partner fidato e ogni volta che non riescono a fare esercizio dopo una sessione di PMO. Un essere umano intelligente e razionale che passa tutte le sue giornate nel disprezzo. Ma la cosa peggiore è: che cosa ottengono gli utenti dal dover sopportare la vita con queste terribili ombre nere in fondo alla mente? **Assolutamente nulla!**

Forse starete pensando: *"È tutto molto bello, lo so, ma una volta che si è dipendenti da queste cose è molto difficile smettere".* Ma perché è così difficile? Alcuni dicono che è a causa dei forti sintomi di astinenza, ma come imparerai presto, i veri sintomi di astinenza sono in realtà molto lievi. E questo è evidente se si considera che molti PMOer hanno vissuto e sono morti senza rendersi conto di essere dipendenti.

Alcuni sostengono che il porno su Internet è gratuito e che quindi l'umanità dovrebbe rivendicare questa bonanza biologica, ma questo non è vero: crea dipendenza e agisce proprio come una qualsiasi droga. Chiedete a un utente che giura di usufruire solo di "erotismo" come le riviste di Playboy se ha mai superato il limite del "porno non sicuro". E se è completamente onesto, confesserà le volte in cui ha razionalizzato il superamento di quel limite, piuttosto che non farne uso per niente.

Anche il piacere non ha nulla a che fare con questo. A me piacciono i gamberi, ma non sono mai arrivato al punto di doverli mangiare tutti i giorni. Con altre cose nella vita ci divertiamo mentre le facciamo, ma non ci sentiamo privati quando non le facciamo.

Alcuni dicono:\
*"È educativo!"* Allora in che modo ti ha fatto crescere come persona? *"È una soddisfazione sessuale!"* Allora perché ti isola e ti fa sentire un desiderio insaziabile? *"È una sensazione di liberazione!"* Liberazione dallo stress della vita reale? Ok, per un'ora, prima che tutto si ritorca contro di te? E quali problemi ha risolto? *"Mi aiuta a dormire"* Allora perché altri riescono a dormire benissimo senza? Ci sono [tanti](https://www.sleepfoundation.org/insomnia/treatment/meditation) [metodi](https://www.sleepfoundation.org/insomnia/treatment/cognitive-behavioral-therapy-insomnia) dimostrati scientificamente per [risolvere](https://www.amazon.com/Uvex-Blocking-Computer-SCT-Orange-S1933X/dp/B000USRG90) i problemi col sonno, e [molti altri](https://www.menshealth.com.au/what-is-the-military-method-the-technique-that-promises-to-help-you-sleep-in-2-minutes).

Molti credono che il porno allevi la noia, ma la noia è uno stato d'animo. Il porno ti abituerà in poco tempo alla ricerca di novità, facendoti annoiare sempre di più fino a quando non parteciperai nuovamente alla caccia sfrenata del video giusto, diventando sempre più incline a cercare tutto ciò che evoca novità, forti emozioni e, infine, un sentimento di oltraggioso shock.

Alcuni dicono di farlo solo perché lo fanno i loro amici e tutti quelli che conoscono. Se è così, pregate che i vostri amici non inizino a tagliarsi la testa per curare il mal di testa! La maggior parte degli utenti che ci pensano arriva a concludere che si tratta solo di un'abitudine. Non si tratta di una vera e propria spiegazione, ma avendo scartato tutte le spiegazioni consuete e razionali, sembra essere l'unica scusa rimasta. Purtroppo è altrettanto illogica. Ogni giorno della nostra vita cambiamo abitudini, alcune delle quali molto piacevoli. Ci è stato fatto il lavaggio del cervello per farci credere che il PMO è un'abitudine e che le abitudini sono difficili da interrompere.

Le abitudini sono difficili da interrompere? Negli Stati Uniti gli automobilisti hanno l'abitudine di guidare sul lato destro della strada, ma quando viaggiano all'estero non hanno problemi a interrompere l'abitudine. E quando si trova un nuovo lavoro, la routine cambia e le abitudini cambiano. Ci vuole un po' di tempo per abituarsi ma, col porno, non è come interrompere la dipendenza di una vita. Instauriamo e interrompiamo abitudini ogni giorno della nostra vita, quindi perché troviamo difficile interrompere un'abitudine che ci fa sentire privi quando non ce l'abbiamo, colpevoli quando ce l'abbiamo, che vorremmo interrompere a prescindere, quando tutto ciò che dobbiamo fare è *smettere di farlo?*

La risposta è che il porno non è un'abitudine, ma una dipendenza! Ecco perché sembra essere così difficile "smettere". La maggior parte degli utenti non capisce la dipendenza e crede di trarre dal porno un piacere genuino o un appoggio. Credono di fare un vero sacrificio se smettono.

La bella verità è che una volta compresa la vera natura della dipendenza dal porno e le ragioni per cui ne fai uso, smetterai di farlo, proprio così. Entro tre settimane, l'unico mistero sarà il motivo per cui hai ritenuto necessario usare il porno così a lungo e perché non riesci a convincere gli altri utenti *di quanto sia bello non essere un PMOer!*

## La trappola sinistra

Il porno su Internet è una trappola sottile e sinistra che l'uomo e la natura hanno ideato insieme. Alcuni di noi vengono persino avvertiti dei pericoli, ma non riescono a credere che non ci piaccia. Ma cosa ci spinge a farlo? In genere sono i campioni gratuiti offerti da amatoriali e professionisti che li condividono sui vari siti. È così che scatta la trappola. Se invece ci avvertisse dei pericoli a cui andiamo incontro prima ancora di dare la prima occhiata, allora i campanelli d'allarme urlerebbero.

Ma questi campanelli non urlano. Forse è la natura scioccante di molti filmati a rassicurare le nostre giovani menti che non diventeremo mai dipendenti, pensando che non ci piaccia e che possiamo smettere quando vogliamo. O forse l'apparente innocenza del materiale soft non fa scattare alcun campanello d'allarme, proprio come un'abile tessitura che un artista della truffa può mettere in atto per dirigere la nostra mente. Come esseri umani intelligenti, allora capiremmo perché metà della popolazione adulta è sistematicamente dipendente da qualcosa che riduce il nostro stesso potenziale, per eseguire ciò che stiamo guardando. La curiosità ci avvicina alla soglia della dipendenza, ma non osiamo cliccare sulle miniature che stiamo guardando, temendo che ci facciano ammalare o che ci portino su una strada pericolosa e immorale. E se per sbaglio ne clicchiamo una, spesso il nostro unico desiderio è quello di allontanarci dalla pagina il prima possibile, ma allo stesso tempo di essere ancora più curiosi.

Una volta avviato questo processo, siamo in trappola. D'ora in poi passeremo il resto della nostra vita a cercare di capire perché lo facciamo, a dire ai nostri figli di non iniziare e, in momenti strani, a cercare di scappare da noi stessi. La trappola è progettata in modo tale da cercare di smettere solo a causa di un "incidente", che sia una prestazione sessuale, la perdita di una carriera o di una relazione, la mancanza di stimoli o semplicemente la sensazione di essere un lebbroso. Non appena smettiamo, lo stress aumenta a causa delle crisi di astinenza e il metodo su cui contavamo per eliminare lo stress non è più disponibile.

La nostra determinazione a smettere si rivela quindi vacillante. Dopo alcuni giorni di tortura ci convinciamo di aver scelto il momento sbagliato per smettere, decidendo di aspettare un periodo senza stress, che al suo arrivo elimina il motivo per cui avevamo inizialmente smesso. Naturalmente quel periodo non arriverà mai del tutto, e cominciamo a credere che la nostra vita tenda a diventare sempre più stressante. Lasciamo la protezione dei nostri genitori e così lo stress del lavoro, della casa, del mutuo, dell'acquisto di un alloggio e dell'educazione dei figli affollano la nostra vita. Ma questa è un'illusione. Le fasi più stressanti della vita di qualsiasi creatura sono in realtà la prima infanzia e l'adolescenza.

Tendiamo a confondere responsabilità e stress. La vita di un consumatore, come quella di un tossicodipendente, diventa automaticamente più stressante perché il porno non ci rilassa o allevia lo stress, come alcuni cercano di farci credere. Anzi, è proprio il contrario: ci stressa sempre di più man mano che continuiamo a farne uso, e come conseguenza della notte passata con i sensi di colpa aggiunge altra paglia alla schiena del cammello. Anche i consumatori che abbandonano l'abitudine - come la maggior parte di essi fa una o più volte nel corso della vita - possono condurre una vita perfettamente felice, ma improvvisamente tornare ad essere dipendenti. Vagando nel labirinto della pornografia, la nostra mente si annebbia e passiamo il resto della nostra vita a cercare di uscirne. Molti ci riescono, per poi ricadere nella sinistra trappola in un secondo momento.

Risolvere il problema della dipendenza dal porno è un enigma. È complesso e difficile. Ma una volta che si vede la risposta, è semplice e divertente, e ci si chiede perché non ci si è pensato! EasyPeasy contiene la soluzione a questo enigma, che ti condurrà fuori dal labirinto, per non tornarci mai più. **Tutto ciò che devi fare è seguire alla lettera ogni istruzione**. Tuttavia, se si prende **una strada sbagliata saltando i capitoli**, o **sfogliando il libro alla velocità della luce** senza fare uno sforzo deliberato durante la prima lettura, allora il resto delle istruzioni è inutile.

Chiunque può trovare facile smettere, ma dobbiamo prima guardare ai fatti. No, non fatti pensati per spaventarvi, ci sono già abbastanza informazioni in giro. Se questo dovesse fermarvi, vi sareste già fermati. Ma perché abbiamo difficoltà a fermarci? Per rispondere a questa domanda è necessario conoscere il vero motivo per cui continuiamo a usare il porno, che si riduce a due fattori. Sono:

-   Natura e porno su Internet.

-   Lavaggio del cervello da parte della società.

I consumatori di porno sono esseri umani intelligenti e razionali. Sanno di correre enormi rischi futuri e passano molto tempo a razionalizzare la loro "abitudine". Ma gli utenti del porno in cuor loro sanno di essere degli sciocchi, sapendo che non avevano alcun bisogno di usare il porno prima di diventarne dipendenti. La maggior parte ricorda che la prima "sbirciatina" è stata un misto di repulsione e di curiosità inedita. In seguito si sono specializzati nel localizzare, filtrare e inserire nei segnalibri nei siti, lavorando duramente per diventare dipendenti.

La cosa più fastidiosa è la sensazione che i non-dipendenti - la maggior parte delle donne, degli anziani e delle persone che vivono in paesi in cui il porno su Internet ad alta velocità non è disponibile - non si perdano nulla e trovino la situazione ridicola. Smontando questi fattori nei prossimi capitoli, anche voi capirete la trappola sinistra!
