# Cosa sto abbandonando?

**Assolutamente nulla!** Il porno è difficile da abbandonare a causa del timore di essere privati del nostro piacere o del nostro oggetto di culto. La paura che certe situazioni piacevoli non siano più le stesse. Il timore di non essere più in grado di affrontare le situazioni di stress. In altre parole, sono gli effetti del lavaggio del cervello che ci illudono di credere che il sesso - e per estensione l'orgasmo - sia un must per tutti gli esseri umani. Inoltre, è la convinzione che nel porno su Internet ci sia qualcosa di cui abbiamo bisogno e che, se smettiamo di usarlo, ci neghiamo e creiamo un vuoto.

Chiaritevi questo concetto nella vostra mente: **Il porno non riempie un vuoto, ne crea uno!**

I nostri corpi sono gli oggetti più sofisticati del pianeta. Che si creda nel disegno perfetto della creazione, nella selezione naturale o in una combinazione di entrambi, i nostri corpi sono migliaia di volte più efficaci dell'uomo! Non siamo in grado di creare la più piccola cellula vivente o i miracoli della vista, della riproduzione e dei vari sistemi interconnessi presenti nel nostro corpo o nel nostro cervello. Se questo creatore o processo avesse voluto che noi gestissimo stimoli supernormali, ci avrebbe fornito sistemi di ricompensa diversi. Il nostro corpo è dotato di dispositivi di allarme a prova di errore, che ignoriamo a nostro rischio e pericolo.

## Non c'è nulla da abbandonare

Una volta eliminato il piccolo mostro dal corpo e il lavaggio del cervello (il grande mostro) dalla mente, non avrete più voglia di masturbarvi spesso né di usare il porno su Internet. Quando si parla di dipendenza dal porno ci sono molte cose note e molte sconosciute, e molti nella comunità medica non hanno voglia di mettere in discussione o diagnosticare una persona come dipendente dal porno. Molti dei sintomi riportati vengono erroneamente etichettati come sintomi da altre cause. Non è che gli utenti siano generalmente stupidi, è solo che sono infelici senza il porno. Sono in bilico tra il diavolo e il mare blu profondo, si astengono e sono infelici perché non possono usare il porno o sono infelici perché si sentono in colpa e iniziano a disprezzarsi per questo. Quando si manifestano sintomi come dolori lombari o disfunzioni sessuali, la loro mente è combattuta tra l'accettare la responsabilità e il voltarsi dall'altra parte.

Un'altra analogia con i fumatori: tutti noi abbiamo visto fumatori che trovano scuse per fumare di nascosto e vediamo così la vera dipendenza in azione. I tossicodipendenti non lo fanno per piacere, ma perché sono infelici senza.

Per molti la prima esperienza sessuale si è conclusa con un orgasmo, quindi si è acquisita la convinzione di non poter godere del sesso senza. Per gli uomini, il porno viene commercializzato come un aiuto per il sesso, a volte anche come un'educazione alla sicurezza durante l'atto. È un'assurdità, il condizionamento dello stimolo supernormale riesce solo ad abbassarlo.

Non solo non c'è nulla da abbandonare, ma si possono ottenere enormi guadagni positivi nel farlo. Quando gli utenti pensano di smettere, tendono a concentrarsi sulla salute e sulla virilità. Si tratta di ragioni valide e importanti, ma personalmente ritengo che i maggiori vantaggi siano di natura psicologica:

-   Il ritorno della fiducia e del coraggio.

-   La libertà dalla schiavitù.

-   Non avere più terribili ombre nere in fondo alla mente e disprezzarsi.

## Vuoto, il vuoto, il bellissimo vuoto!

Immagina di avere un'infiammazione sul viso, vai dal farmacista che ti dà una pomata gratuita da provare. La pomata viene applicata e l'infiammazione scompare immediatamente. Una settimana dopo ricompare, così torni dal farmacista e chiedi se ha dell'altra pomata. Il farmacista dice: "Certo, tieni il tubetto, potrebbe servirti più in là".

Applichi la pomata e, ecco, la piaga scompare di nuovo. Ma ogni volta che la piaga ritorna, diventa più grande e più dolorosa, con un intervallo sempre più breve. Alla fine la piaga copre tutto il viso, è dolorosa e ritorna ogni mezz'ora. Sai che la pomata la eliminerà temporaneamente, ma sei molto preoccupato. Alla fine la piaga si estenderà a tutto il corpo? L'intervallo scomparirà completamente? Vai dal medico, che non riesce a curarla, e provi altre cose, ma niente vi aiuta, a parte la pomata.

Ormai sei completamente dipendente dalla pomata e non esci mai senza esserti assicurato di avere con te un tubetto. Se vai all'estero, ti assicuri di portare con te diversi tubetti. Oltre alle preoccupazioni per la tua salute, il farmacista ti fa pagare un centinaio di dollari a tubetto. Non hai altra scelta che pagare.

Ti imbatti in un articolo che parla di questo problema e scopri che non succede solo a te, ma che molte persone soffrono dello stesso problema. La comunità medica ha scoperto che la pomata non cura effettivamente la piaga, ma si limita a portarla sotto la superficie della pelle. È la pomata che ha causato la crescita della piaga, quindi per eliminarla basta smettere di usare la pomata e la piaga scomparirà col tempo.

Continueresti a usare la pomata? Ci vorrebbe forza di volontà per non usare la pomata? Se non credi all'articolo, potresti avere qualche giorno di apprensione, ma quando ti accorgerai che la piaga comincia a migliorare, il bisogno o il desiderio di usare la pomata sparirà. Saresti infelice? Certo che no! Avevi un problema terribile che pensavi fosse incurabile, ma ora hai trovato la soluzione. Anche se ci volesse un anno per far sparire la piaga, ogni giorno, man mano che migliora, penseresti a quanto ti senti bene. Questa è la magia dell'abbandono del porno.

La piaga non sono i dolori del corpo, la mancanza di normale desiderio, l'eccitazione in calo, la penetrazione che si affievolisce, il tempo sprecato su immagini bidimensionali, il sentimento di violazione del diritto e il disprezzo delle persone che ti hanno beccato o, peggio ancora, il disprezzo di te stesso. Tutto questo si aggiunge alla piaga.

La piaga ci fa chiudere la mente a tutte queste cose, è quella sensazione di panico che ci fa desiderare una dose. I non consumatori non soffrono di questa sensazione. La cosa peggiore di cui soffriamo è la paura, il guadagno più grande è liberarsi di quella paura. È causata dalla prima masturbazione, ulteriormente rafforzata da ogni masturbazione successiva.

Alcuni utenti sono "felici", accecati dai loro piccoli mostri astuti, e quindi vivono lo stesso incubo, adducendo argomenti fasulli per cercare di giustificare la propria stupidità.

*È così bello essere liberi!*
