# Risparmiare tempo

Di solito, quando i consumatori provano a smettere, le ragioni principali per cui lo fanno sono la salute, la religione e lo stigma del partner. Parte del lavaggio del cervello di questa terribile droga è la sua pura schiavitù: l'uomo ha lottato duramente per abolire la schiavitù in molte parti del mondo, eppure chi ne fa uso passa la vita a subire una schiavitù autoimposta. Sono ignari del fatto che quando gli viene permesso di usare il porno, vorrebbero essere dei non consumatori. L'unico momento in cui il porno diventa prezioso è quando "cerchiamo" di ridurlo o di astenerci, o quando l'astinenza ci viene imposta.

Non si ripeterà mai abbastanza che il lavaggio del cervello rende difficile smettere di usare il porno: più lo sfatiamo prima di iniziare, più sarà facile raggiungere l'obiettivo. Gli utenti abituali, che non credono che il porno abbia effetti negativi sulla loro salute (disfunzione erettile indotta dal porno, ipofrontalità, ecc.) e che non stanno vivendo una lotta mentale, sono in genere più giovani o single con un partner sessuale occasionale. Pertanto, il feedback interno è perso a causa della natura della loro giovinezza o è troppo poco frequente per essere osservato e registrato.

Un argomento utile per l'utente più giovane è il tempo trascorso, dicendo "*Non posso credere che non ti preoccupi del tempo che stai sprecando*". In genere i loro occhi si illuminano, sentendosi non colpiti se attaccati sui motivi di salute o di stigma sociale, ma sul tempo...\
"*Oh, posso permettermelo. Sono solo x ore a settimana e penso che ne valga la pena, è il mio unico vizio di piacere "*.

*"Non riesco ancora a credere che tu non sia preoccupato. Ipotizziamo una media di mezz'ora al giorno, che include il sentimento di drenaggio fisico delle crisi di astinenza da dopamina, stai spendendo circa un'intera giornata lavorativa ogni quindici giorni. Sono certo che converrai che mezz'ora al giorno è una stima molto prudente. Hai pensato a quanto tempo passerai nella tua vita? Cosa fafrai in quel tempo? Sviluppi relazioni reali? No, la tua pornostar preferita non ha compassione di te, solo perché hai passato tanto tempo sui suoi video: stai buttando via del tempo! Non solo, stai anche usando quel tempo per rovinare la tua salute fisica, distruggendo i tuoi nervi e la tua fiducia in te stesso per soffrire una vita di schiavitù, dolore, malinconia e scontrosità. Questo deve preoccuparti, vero?".*

A questo punto è evidente lo spreco di tempo, soprattutto con i consumatori più giovani, che non hanno mai considerato una dipendenza a vita. Di tanto in tanto, calcolano il tempo che sprecano in una settimana e questo è abbastanza allarmante. Molto occasionalmente, e solo quando pensano di smettere, valutano quanto spendono in un anno, il che è spaventoso, ma per tutta la vita è impensabile. Tuttavia, poiché siamo in una discussione, l'utente abituale dirà impulsivamente: *"Posso permettermelo, sono solo x ore a settimana"*.

Rifiutereste un'offerta di lavoro che paga come il vostro attuale stipendio annuale e vi dà anche un mese di ferie all'anno? Qualsiasi utente firmerebbe in un batter d'occhio e si darebbe da fare per trovare offerte di vacanze in luoghi esotici. Trovare il modo di trascorrere un mese intero senza lavorare sarebbe il problema più grande da risolvere. In ogni discussione con un utente abituale (e tieni presente che non si tratta di qualcuno che, come te, ha intenzione di smettere) nessuno ha mai accettato l'offerta. Perché no?

Spesso, a questo punto, un utente abituale dirà: "*Guarda, non sono davvero preoccupato dell'aspetto economico*". Se stai pensando a questo, chiediti perché non sei preoccupato. Perché in altri aspetti della tua vita ti dai un gran da fare per risparmiare qualche dollaro qua e là, ma ne spendi migliaia uccidendo la tua felicità?

Ogni altra decisione che prenderai nella tua vita sarà il risultato di un processo analitico di ponderazione di vantaggi e svantaggi per arrivare a una decisione razionale. Può essere la decisione sbagliata, ma sarà il risultato di una deduzione razionale. Ogni volta che un utente valuta i pro e i contro dell'uso del porno su Internet, la risposta è: **"SMETTI DI USARLO! SEI UNO STUPIDO!"** Pertanto, tutti gli utenti usano il porno non perché lo vogliono o lo decidono, ma perché non possono smettere. Devono usare il porno e si fanno il lavaggio del cervello, tenendo la testa sotto la sabbia.

Gli utenti abituali dovrebbero tenere presente che la situazione non potrà che peggiorare esponenzialmente, con l'uscita di altri studi e l'aumento delle persone che parlano degli effetti negativi del porno su Internet. Oggi sono i non addetti ai lavori a parlarne, domani saranno i medici a dover fare i test diagnostici. Sono finiti i giorni in cui l'utente può giustificare i "momenti down" nella sua vita sessuale con lo stress lavorativo, il tuo partner ti chiederà perché stai al computer fino a tarda notte. Il povero utente, che già si sente in colpa, ora vuole che la terra si apra e lo inghiotta.

La cosa strana è che molte persone pagherebbero fior di quattrini per iscriversi a palestre e personal trainer per aumentare i muscoli e avere un aspetto scolpito, e molti nella loro immaginaria (e reale) disperazione si rivolgono a trattamenti come l'aumento del testosterone con effetti collaterali dubbi e pericolosi. Eppure ci sono molte persone in questo che trarrebbero beneficio dall'interruzione di una pratica che distrugge sistematicamente i sistemi di rilassamento naturale del cervello.

Questo perché stanno ancora ragionando con la mente sottoposta a lavaggio del cervello dell'utilizzatore. Togliti la sabbia dagli occhi per un momento. Il porno su Internet è una reazione a catena, una catena per tutta la vita e, se non si interrompe questa catena, si rimarrà un utente per il resto della vita. Stimate quanto tempo pensate di passare sul porno per il resto della vostra esistenza; ovviamente la quantità varia da persona a persona, ma supponiamo che sia un anno e mezzo di ore. Immagina se domani sul tuo tappeto ci fosse un biglietto della lotteria vincente un anno e mezzo di stipendio: balleresti di gioia, quindi inizia a ballare! Stai per iniziare a ricevere questi benefici!

Se pensi che questo sia un modo complicato di vedere le cose, ti stai ancora prendendo in giro. Calcola quanto tempo avresti risparmiato se non avessi dato la prima occhiata all'inizio.

A breve, prenderai la decisione di effettuare la tua ultima masturbazione (non ancora, ricordate le istruzioni!), rimanendo un non-utente e non cadendo di nuovo nella trappola. Tutto ciò che devi fare per rimanere un non-utente è non usare il porno ed evitare di dare "solo una sbirciatina". Ricorda che se lo fai, ti costerà quanto hai stimato come guadagno di stipendio.

Se stai facendo da tutor a qualcuno per la sua dipendenza dal porno, digli che conosci qualcuno che ha rifiutato un'offerta di lavoro che pagava il suo attuale stipendio annuale e gli dava anche un mese intero di ferie pagate. Quando vi chiederanno chi è quell'idiota, digli: ***"Tu!"***. È scortese, ma a volte è necessario far capire il concetto in modo un pò meno che educato.
