# Salute

Questo è il settore in cui il lavaggio del cervello è maggiore, con i consumatori - soprattutto giovani e single - che pensano di essere consapevoli dei rischi per la salute, ma non lo sono. Molti si illudono dicendo di essere pronti ad accettare le conseguenze. Se il tuo router internet avesse una funzione che riproduce un segnale acustico con un avviso quando si entra in un sito porno che dice: "Fino ad ora l'hai fatta franca, ma se rimani un altro minuto la tua testa esploderà" rimarresti? Se sei in dubbio sulla risposta, prova a camminare fino a una scogliera, a stare sul bordo con gli occhi chiusi e a immaginare di poter scegliere se smettere con il porno o risalire la scogliera bendato.

Non c'è dubbio su quale sarebbe la tua scelta, ma se nascondi la testa sotto la sabbia e speri di svegliarti una mattina e di non voler più guardare porno, non otterrai nulla. Gli utenti non possono permettersi di pensare ai rischi per la salute, perché se lo fanno il piacere illusorio della dipendenza svanisce. Questo spiega perché le terapie d'urto sono così inefficaci nelle prime fasi della disassuefazione: solo i non consumatori riescono a leggere i cambiamenti distruttivi del cervello.

Prendete questa conversazione comune con gli utenti, generalmente più giovani.

> **Io**: "Perché vuoi smettere?".
>
> **Utente:** "*Ho letto sul blog di un fanatico del rimorchio che è bene smettere per quattro giorni per darmi la carica*".
>
> **Io:** "Non sei preoccupato dei rischi per la salute?".
>
> **Utente:** "*No, potrei finire sotto un autobus domani.*"
>
> **Io:** "Ma tu ti metteresti deliberatamente sotto un autobus?".
>
> **Utente:** "*Certo che no.*"
>
> **Io:** "Non ti preoccupi di guardare a destra e a sinistra quando attraversi la strada?".
>
> **Utente:** "*Certo che lo faccio.*"

Esattamente, si fanno un sacco di problemi per non finire sotto un autobus e le probabilità che ciò accada sono una su migliaia. Eppure l'utente rischia la quasi certezza di essere paralizzato dalla sua dipendenza e sembra esserne completamente ignaro. Il potere del lavaggio del cervello è tale che il porno su Internet è un lupo travestito da pecora. Non è strano che se pensassimo che c'è un minimo difetto in un aereo non ci saliremmo - anche se i rischi sono uno su un milione - eppure con il porno abbiamo più di una certezza su quattro e apparentemente non ne siamo consapevoli? Cosa ne ricava l'utente? **Assolutamente nulla!**

Un altro mito comune è quello della depressione o del malumore. Molti giovani non si preoccupano della loro salute perché non soffrono di depressione o malinconia. La depressione o lo stress non sono la malattia, ma un sintomo. Le persone più giovani, in generale, non sentono l'irritabilità o la depressione che si creano grazie alla capacità naturale del loro corpo di produrre più dopamina. Con l'avanzare dell'età o con l'insorgere di gravi problemi di vita, le risorse già esaurite vengono sovraccaricate e i sintomi si manifestano in tutta la loro gravità. Quando gli utenti più anziani si sentono stressati, depressi o irritati, è perché i meccanismi di sicurezza naturali del corpo proteggono il sistema nervoso dall'eccessivo afflusso di dopamina attraverso la down-regulation dei recettori. L'utilizzatore sviluppa anche altri cambiamenti neurologici che lo mantengono nella routine.

Pensa a questo aspetto: se avessi una bella macchina e la lasciassi arrugginire senza fare nulla, sarebbe piuttosto stupido. Diventerebbe rapidamente un ammasso di ruggine inamovibile, incapace di trasportarti da qualsiasi parte. Tuttavia, non sarebbe la fine del mondo, perché sarebbe solo una questione di soldi. Ma il tuo corpo è il veicolo che ti trasporta nella vita. Tutti diciamo che la nostra salute è il nostro bene più grande, chiedete a qualsiasi milionario malato. La maggior parte di noi può ricordare una malattia o un incidente della propria vita in cui ha pregato pur di guarire. Se sei un consumatore di porno, non solo lasci che la ruggine entri e non fai nulla, ma stai anche distruggendo sistematicamente l'unico veicolo utilizzato per attraversare tutta la tua vita.

Sii saggio. Non sei obbligato a farlo, ricorda che non ti serve assolutamente a nulla. Solo per un momento, toglia la testa dalla sabbia e chiediti: se sapessi con certezza che la tua prossima seduta avvierà un processo che ti renderà totalmente insensibile a una persona che amate profondamente, continueresti a farne uso? Parlando con le persone a cui succede, di certo non si aspettavano che sarebbe successo anche a loro, e la cosa peggiore non è la malattia in sé, ma la consapevolezza di essersela procurata da soli. Provate a immaginare come si sentono le persone che hanno "premuto il pulsante": per loro il lavaggio del cervello è finito. Passano il resto della loro vita a pensare: "*Perché mi sono illuso così a lungo di aver bisogno di masturbarmi con il porno su Internet? Se solo avessi la possibilità di tornare indietro"*.

Smettila di illuderti, hai questa possibilità. È una reazione a catena, se ti avvii alla prossima sessione di porno, questa ti porterà a quella successiva e a quella ancora successiva. Ti sta già accadendo. EasyPeasy non promette alcun trattamento d'urto, quindi se hai già deciso di smettere, quanto segue non sarà sconvolgente per te. Se non l'hai fatto, salta il *resto di questo capitolo* e tornaci quando avrai letto il resto del libro.

Sono già stati scritti volumi e volumi di ricerche sui danni che il porno su Internet provoca alla nostra vita sessuale e al nostro benessere mentale. Il problema è che, finché non decidi di smettere, non vuoi saperlo. I forum e i gruppi sono una perdita di tempo perché il porno mette i paraocchi. Se inavvertitamente leggi, la prima cosa che fai è aprire il tuo sito tube preferito. Gli utenti del porno tendono a considerare i rischi legati alla felicità, allo stress e al sesso come un'attività a rischio, come calpestare una mina antiuomo.

Mettitelo in testa, sta già succedendo. ***Ogni volta*** che apri il tuo sito porno stai innescando un'inondazione di dopamina e gli oppioidi si mettono al lavoro. Gli scivoli neurali sono lubrificati e la corsa ti porta senza problemi attraverso le fasi successive, poiché il tuo cervello ha già accettato il copione. Il sistema nervoso è ora inondato di dopamina poiché, per l'ennesima volta, i recettori della dopamina diminuiscono e il mostriciattolo sfrutta questo leggero calo di piacere rispetto all'ultima volta per spingervi a superare la linea rossa verso porno o comportamenti più scioccanti, al fine di rilasciare altra dopamina. Più novità, più dopamina e il mostriciattolo ti dice di continuare. Così tante immagini e video in un'unica sessione innescano uno stimolo supernormale, iniettando più sostanze chimiche nel cervello e spingendoti a continuare.

Per tutto il tempo i recettori ricevono informazioni per diminuire in risposta all'inondazione. L'orgasmo non fa che aumentare questo effetto e porta all'astinenza. Il mostro desidera la sua dose senza provare alcun dolore o disagio. La minaccia di avere una disfunzione erettile terrorizza molti, ed è per questo che la bloccano nella loro mente e la oscurano e sostituiscono con la paura di smettere. Non è che la paura è maggiore della minaccia di sviluppare una disfunzione erettile, è che smettere oggi è immediato. Perché guardare il lato negativo dello smettere? Potresti non sviluppare disfunzione erettile, e potresti smettere prima che succede.

Tendiamo a pensare al porno come a un braccio di ferro, da una parte c'è la paura: "*È malsano, sporco e schiavizzante*", dall'altro lato, gli aspetti positivi: *"È il mio piacere, il mio amico, la mia stampella"*. Sembra che non ci si renda mai conto che questo lato è anche paura; non è che ci piace il porno, è che tendiamo a essere infelici senza di esso. I tossicodipendenti privati dell'eroina vivono una situazione di infelicità, ma immaginate la gioia assoluta quando finalmente possono inserire un ago nella vena e porre fine a quel terribile desiderio. Provate a immaginare come si possa credere di provare piacere nell'infilare una siringa in una vena. I non eroinomani non soffrono di quella sensazione di panico e l'eroina non allevia la sensazione, la provoca.

I non utenti non si sentono infelici se non possono usare il porno: sono solo gli utenti a provare questa sensazione. Il porno su Internet non allevia questa sensazione, la provoca. La paura delle conseguenze negative non aiuta gli utenti a smettere, né lo fa paragonare la sensazione a quella di camminare in un campo minato. Se si riesce a farla franca, bene, ma se si è sfortunati si calpesta una mina e si affrontano le conseguenze. In quel caso, di chi sarebbe la colpa? I tossicodipendenti in questo stato sviluppano di solito le seguenti tattiche evasive.

"***Alla fine invecchierai e perderai comunque la tua abilità sessuale...***".

Certo che sì, ma la prestanza sessuale non è il punto: qui stiamo parlando di schiavitù. Anche se fosse così, è un motivo logico per togliersi deliberatamente la vita?".

"***La qualità della vita è più importante della semplice vita***".

Esatto! Stai forse suggerendo che la qualità della vita di un tossicodipendente è maggiore di quella di chi non è dipendente? Credi davvero che la qualità della vita di un consumatore sia migliore di quella di un non consumatore? Una vita passata a nascondere la testa sotto la sabbia e ad essere infelice non sembra una vita piacevole.

"***Sono single e non ho intenzione di fidanzarmi in futuro, quindi perché no?***".

Anche se fosse vero, è una ragione logica per giocare con i meccanismi neurologici di controllo degli impulsi? È possibile concepire che qualcuno sia così stupido da spogliarsi nudo ogni volta che è da solo, anche se è sicuro di non star aspettando nessuno? **È quello che fanno effettivamente gli utenti del porno!**

Il progressivo intasamento dei nostri circuiti di ricompensa con una stimolazione eccessiva, che li rende incapaci di gestire i normali stress della vita, non aiuta a godersi la vita con entusiasmo e vigore. Il porno e la masturbazione hanno sostituito il naturale appetito sessuale, come una barretta di cioccolato sostituisce il vero cibo. Non sorprende che molti medici e psicologi abbiano iniziato a collegare vari problemi di salute mentale a cause fisiologiche. La comunità medica tradizionale ha affermato che non è mai stato scientificamente provato che il porno sia la causa diretta dei problemi segnalati dagli individui che si ne confessano l'utilizzo, è però anche vero che ammettere la propria incapacità sessuale in pubblico è un evento che scatena molta vergogna, perché mai qualcuno dovrebbe farlo se non fosse davvero impegnato nel trovare la causa ed eliminarla dalla propria vita?

EasyPeasy ti aiuterà a liberarti dal porno e a diventare un ex-utente felice. Niente porno, masturbazione assistita o orgasmi inutili. L'unico aiuto sarà il tocco, l'odore e il profumo del tuo partner. Come il pane integrale dopo un appetito ben sviluppato, non vorrai più lo sciroppo di mais ad alto contenuto di fruttosio del porno su Internet. Una prova così schiacciante da non aver bisogno di essere dimostrata: quando mi batto il pollice con un martello fa male, non c'è bisogno di dimostrarlo. Lo stress del porno su Internet si ripercuote su altri aspetti della vita degli utenti, predisponendo molti a ricorrere a droghe come le sigarette e l'alcol per far fronte alla situazione, e in alcuni casi portando l'utente a considerare il suicidio.

Gli utenti si illudono anche che gli effetti negativi del porno siano sopravvalutati. Al contrario, non c'è dubbio che il porno su Internet sia la causa principale di disfunzioni sessuali e di molti altri problemi. Quanti divorzi sono stati causati dal porno? Non ci sono modi affidabili per saperlo, ma le ricerche nelle comunità online indicano che il numero sta crescendo in modo esponenziale.

C'è un episodio di *Friends* in cui i ragazzi, che ricevevano continuamente porno gratis in TV, cominciavano a chiedersi perché la ragazza che consegnava le pizze non chiedesse di dare un'occhiata alla loro "grande camera da letto". Quando si è dipendenti, si proiettano immancabilmente le fantasie porno su donne reali. Immaginate cosa potrebbe fare un'esposizione incauta o anche accidentale al porno a una persona che si trova già a un punto critico della sua vita.

Ecco un altro esperimento: supponiamo che qualcuno venga da voi e vi dica che non vuole necessariamente un orgasmo, ma che desidera ardentemente fare l'amore, anche penetrativo. Vuole farlo per tutto il tempo e fino a dove è possibile arrivare senza un orgasmo, ma se questo avviene va bene. Vi assicuro che è un'esperienza sessuale fenomenale, migliore di qualsiasi altra, se vi viene proposta. Provate.

Gli effetti del lavaggio del cervello ci fanno pensare come l'uomo che, dopo essere caduto da un edificio di 100 piani, afferma, mentre sfreccia di piano in piano: "*Fino a qui, tutto bene!*". Pensiamo che, visto che finora l'abbiamo fatta franca, un'altra sessione di porno non farà la differenza. Vediamola in un altro modo: l'abitudine" è una catena continua per tutta la vita, con ogni sessione che crea il bisogno di quella successiva. Quando inizia l'abitudine, si accende una miccia. Il problema è che *non si sa quanto sia lunga la miccia*. Ogni volta che si cede a una sessione porno si è un passo più vicini all'esplosione della bomba. **COME FARAI A SAPERE SE È LA PROSSIMA CHE LA FARÀ ESPLODERE?**

## Sinistre ombre nere

Per gli utenti è molto difficile credere che il porno su Internet provochi davvero quelle sensazioni di insicurezza che si provano quando si esce a tarda sera dopo una giornata conflittuale a casa o al lavoro. I non utenti non soffrono di questa sensazione, è il porno che la provoca.

Un'altra delle grandi gioie dell'abbandono del porno è la libertà dalle sinistre ombre nere in fondo alla mente. Tutti gli utenti sanno di essere sciocchi a chiudere la mente agli effetti negativi della pornografia. Per la maggior parte della nostra vita è automatico, ma le ombre nere sono sempre in agguato nel nostro subconscio, appena sotto la superficie. Molti dei meravigliosi benefici dell'abbandono sono consapevoli, come la fine della perdita di tempo e della pura stupidità di fare l'amore con un'immagine bidimensionale.

Gli ultimi capitoli hanno trattato i notevoli vantaggi di essere un non-utente, ma per correttezza è necessario fornire un resoconto equilibrato. Pertanto, nella prossima pagina sono elencati i vantaggi di essere un utente.

# Vantaggi di essere un utilizzatore del porno
