# Il metodo della forza di volontà

È un dato di fatto accettato dalla società che sia molto difficile smettere con il porno. I libri e i forum che consigliano come smettere di solito iniziano dicendo che è difficile. La verità è che è ridicolmente facile. È comprensibile mettere in dubbio questa affermazione, ma prima considerala. Se il tuo obiettivo è correre un miglio in quattro minuti, *è difficile* e devi sottoporti ad anni di duro allenamento, e anche in quel caso potresti essere fisicamente incapace.

Tuttavia, tutto ciò che devi fare per smettere con il porno è non guardarlo e/o non masturbarti più. Nessuno ti obbliga a masturbarvi (a parte te stesso) e, a differenza del cibo o dell'acqua, non è necessario per la sopravvivenza. Quindi, se vuoi smettere di farlo, perché dovrebbe essere difficile? In realtà, non lo è. Sono gli utenti che si rendono la cosa difficile attraverso l'uso della forza di volontà o di qualsiasi metodo che costringa l'utente a sentire che sta facendo una sorta di sacrificio. Consideriamo questi metodi.

Non decidiamo di diventare utenti, ma ci limitiamo a sperimentare riviste o siti web porno e, poiché sono terribili (proprio così, terribili), a parte il nostro desiderato video, ci convinciamo che possiamo smettere quando vogliamo. All'inizio, guardiamo i primi filmati quando ne abbiamo voglia e in occasioni speciali. Prima di rendercene conto, non solo visitiamo regolarmente quei siti e ci masturbiamo quando vogliamo, ma ci masturbiamo quotidianamente. Il porno è diventato parte integrante della nostra vita e ce lo permette avere una connessione a Internet ovunque andiamo. Crediamo quindi di avere diritto all'amore, al sesso, all'orgasmo e alle proprietà antistress del porno. Non ci accorgiamo che gli stessi filmati e gli stessi attori non ci procurano lo stesso grado di eccitazione e iniziamo a lottare contro la linea rossa per evitare il "porno cattivo". In realtà, la masturbazione e il porno su Internet non migliorano la nostra vita sessuale né riducono lo stress, ma semplicemente gli utenti credono di non potersi godere la vita o gestire lo stress senza un orgasmo.

Di solito ci vuole molto tempo per rendersi conto che si è schiavi della dipendenza, perché si soffre dell'illusione che gli utenti guardino il porno perché gli piace, e non perché ne hanno bisogno. Quando il porno non ci "piace", cosa che non può mai accadere a meno che non si aggiungano novità, shock o escalation, ci illudiamo di poter smettere in qualsiasi momento. Questa è una trappola di fiducia: "*Non mi piace il porno, quindi posso smettere quando voglio*". Solo che non sembra mai che si "voglia" smettere.

In genere, i primi tentativi sono precoci, quando si incontra un partner e si nota che non è "abbastanza" dopo i primi appuntamenti. Un'altra ragione comune è quella di notare gli effetti sulla salute presenti nella vita quotidiana.

Indipendentemente dal motivo, l'utente aspetta sempre una situazione di stress, che sia la salute o il sesso. Non appena si ferma, il piccolo mostro inizia ad avere fame. L'utente vuole quindi qualcosa che gli faccia pompare la dopamina, come le sigarette, l'alcol o il suo preferito, il porno su Internet, con il suo harem a portata di clic. La fonte del porno non è più in cantina, ma è virtuale e accessibile da qualsiasi luogo. Se il partner è in giro o se è con gli amici, non ha più accesso al suo harem virtuale, il che lo rende ancora più angosciato.

Se l'utente si è imbattuto in materiale scientifico o in comunità online, avrà un braccio di ferro nella sua mente, resiste alle tentazioni e si sente privato. Il suo modo di alleviare lo stress di solito non è più disponibile, subisce così un triplo colpo. Il risultato probabile dopo questo periodo di tortura è il compromesso: "*diminuirò*" o "*ho scelto il momento sbagliato*" o forse "*aspetterò che lo stress sparisca dalla mia vita*". Tuttavia, una volta passato lo stress, non c'è più motivo di smettere e l'utente non decide di smettere di nuovo fino al prossimo momento di stress.

Naturalmente non c'è mai un momento giusto, perché la vita della maggior parte delle persone diventa sempre più stressante. Si lascia la protezione dei genitori e si entra nel mondo delle case, dei mutui, dei figli e del lavoro con maggiori responsabilità. A prescindere da ciò, la vita dell'utente non può diventare meno stressante, perché la pornografia in realtà provoca stress. Quanto più rapidamente l'utente passa alla fase di escalation, tanto più è angosciato e tanto più cresce la dipendenza dall'illusione.

In realtà, è un'illusione che la vita diventi più stressante e il porno, o un appoggio simile, crea questa illusione. Questo aspetto sarà discusso in dettaglio più avanti, ma dopo questi primi fallimenti l'utente di solito si affida alla possibilità che un giorno si sveglierà e non vorrà più masturbarsi o usare il porno, ecc. Questa speranza è di solito accesa da storie sentite da altri ex-utenti: "*Non ero serio finché non ho avuto una penetrazione sfumata, poi non ho più voluto usare il porno e ho smesso di masturbarmi*".

Non illudetevi, sondate queste voci e scoprirete che non sono mai così semplici come sembrano. Di solito l'utente si stava già preparando a smettere e ha semplicemente usato l'incidente come trampolino di lancio. Più spesso, nel caso di persone che smettono "così, su due piedi", hanno subito uno shock; forse una scoperta da parte del partner, un episodio di auto-accertamento dell'accesso a materiale pornografico che non rientra nel loro normale orientamento sessuale o hanno avuto una disfunzione sessuale che li ha spaventati. "Questo è il tipo di persona che sono". Smettila di prenderti in giro. Non accadrà se non lo farete accadere voi.

Vediamo più in dettaglio perché il metodo della forza di volontà è così difficile. Per la maggior parte della nostra vita adottiamo l'approccio con la testa nella sabbia, "*smetterò domani*". A volte, però, qualcosa fa scattare il tentativo di smettere. Può trattarsi di preoccupazioni per la salute, per la virilità o di un momento di autoanalisi in cui ci rendiamo conto che in realtà non ci piace. Qualunque sia la ragione, iniziamo a valutare i pro e i contro del porno. Il sesso si divide in tantrico (tatto, olfatto, voce) e propagativo (orgasmo); questa è una delle chiavi principali per aprire la nostra mente, senza questa importante distinzione si crea confusione che porta al fallimento. Con una valutazione razionale si scopre ciò che si sa da sempre, la conclusione è mille volte "***SMETTI DI GUARDARLO!*** ".

Se ci si sedesse e si attribuisse un punteggio ai vantaggi dell'interruzione e li si confrontasse con i vantaggi del porno, il totale dei punti a favore dell'interruzione sarebbe di gran lunga superiore agli "svantaggi". Se si utilizza la scommessa di Pascal, smettendo non si perde quasi nulla, con alte probabilità di guadagno e alte probabilità di *non* perdere. Anche se l'utente sa che starà meglio da non utente, la convinzione di fare un sacrificio lo spaventa. Anche se è un'illusione, è potente. Non si sa perché, ma l'utente ha la convinzione che, nei momenti belli e brutti della vita, le sedute sembrano aiutare. Anche prima di iniziare il tentativo, il lavaggio del cervello della società, ulteriormente rafforzato dal lavaggio del cervello della propria dipendenza, si combina con il lavaggio del cervello ancora più potente di quanto sia difficile "smettere".

Si sentono storie di chi ha smesso per molti mesi e continua a desiderare disperatamente e racconti di chi ha smesso scontenti, che hanno smesso e passano il resto della loro vita a lamentarsi del fatto che vorrebbero avere una seduta. Racconti di utenti che hanno smesso per molti mesi o anni, vivendo una vita felice, per poi dare una nuova "sbirciatina" ritrovandosi improvvisamente e nuovamente dipendenti. Probabilmente conoscono persone in fase avanzata della malattia, visibilmente distrutte e che chiaramente non si godono la vita, eppure continuano a farne uso. Inoltre, sicuramente hanno vissuto in prima persona una o più di queste esperienze.

Quindi, invece di iniziare con la sensazione: "*Bene! Hai sentito la notizia? Non ho più bisogno di guardare il porno!", iniziano invece con sentimenti di tristezza e malinconia - come se stessero cercando di scalare l'Everest - e stabiliscono falsamente che una volta che il mostriciattolo ha messo le sue grinfie su di te, sei dipendente per tutta la vita. Molti utenti iniziano il tentativo scusandosi con le loro fidanzate o mogli: "Senti, sto cercando di rinunciare al porno. Probabilmente sarò irritabile per le prossime due settimane, cerca di sopportarmi"*. La maggior parte dei tentativi è condannata prima di iniziare.

Supponiamo che l'utente sopravviva qualche giorno senza sessioni, che si ecciti di nuovo e che cominci a riprendersi. Non ha aperto i suoi siti preferiti di tube e di conseguenza si sta eccitando con i normali stimoli che aveva precedentemente eliminato. I motivi per cui aveva deciso di smettere stanno rapidamente scomparendo dai suoi pensieri, come se avesse visto un brutto incidente stradale mentre guidava. Il rallentamento è immediato, ma la prossima volta che si è in ritardo a un appuntamento, si preme nuovamente il piede sull'acceleratore.

Dall'altra parte della guerra c'è il piccolo mostro che non ha ancora avuto la sua dose. Non c'è dolore fisico: se aveste la stessa sensazione a causa di un raffreddore, non smettereste di lavorare o vi deprimereste, ma ci ridereste su. Tutto ciò che l'utente sa è che vuole visitare il suo harem. Il piccolo mostro lo sa e mette in moto il grande mostro del lavaggio del cervello, facendo sì che la stessa persona che poche ore o giorni prima elencava tutte le ragioni per smettere, ora cerchi disperatamente qualsiasi scusa per ricominciare. Comincia a dire cose come:

-   "*La vita è troppo breve, potrebbe esplodere una bomba, potrei finire sotto un autobus domani. Ho lasciato la dipendenza troppo tardi. Ti dicono che tutto ti dà una dipendenza, al giorno d'oggi*".

-   "*Ho scelto il momento sbagliato*".

-   "*Avrei dovuto aspettare fino a dopo Natale, dopo le vacanze/gli esami, dopo questo evento stressante della mia vita*".

-   "*Non riesco a concentrarmi, divento irritabile e irascibile, non riesco nemmeno a fare bene il mio lavoro*".

-   "*La mia famiglia e i miei amici non mi ameranno più. Ammettiamolo, per il bene di tutti devo ricominciare. Sono un sessodipendente conclamata e non c'è modo che io possa essere di nuovo felice senza un orgasmo.*".

-   "*Nessuno può sopravvivere senza sesso*". (Lavaggio del cervello da parte di persone con buone intenzioni che non considerano la distinzione tra la parte tantrica e quella propagativa del sesso).

-   "*Sapevo che sarebbe successo, il mio cervello è 'sensibilizzato' dal DeltaFosB a causa dei cambiamenti influenzati dai picchi di dopamina dovuti al mio passato uso eccessivo di porno. La sensibilizzazione non può mai essere rimossa dal cervello*".

A questo punto, l'utente di solito cede. Accendendo il browser, la schizofrenia aumenta. Da un lato c'è l'enorme sollievo di porre fine al desiderio, perché il piccolo mostro ha finalmente la sua dose; dall'altro, l'orgasmo è terribile e l'utente non riesce a capire perché lo sta facendo. Questo è il motivo per cui l'utente pensa di non avere forza di volontà. In realtà non si tratta di mancanza di forza di volontà, tutto ciò che ha fatto è cambiare idea e prendere una decisione perfettamente razionale alla luce delle ultime informazioni.

"*Che senso ha essere sani o ricchi se poi si è infelici?*".

Assolutamente no! È molto meglio avere una vita breve e piacevole che una lunga e infelice. Fortunatamente, questo non è vero per chi non ne fa uso, perché la vita è infinitamente più piacevole. L'infelicità di cui soffre l'utente non è dovuta alle crisi di astinenza, anche se all'inizio è scatenata da queste ultime, ma la vera agonia è data dal conflitto mentale causato dal dubbio e dall'incertezza. Poiché l'utente inizia con la sensazione di fare un sacrificio, comincia a sentirsi privato, il che è una forma di stress.

Uno di questi momenti di stress è quello in cui il cervello gli dice di "dare una sbirciatina"; vuole tornare indietro non appena si ferma. Ma poiché ha smesso, non può farlo e questo lo rende ancora più depresso e fa scattare di nuovo la molla. Un altro fattore che rende difficile smettere è l'attesa che qualcosa accada. Se il tuo obiettivo è quello di superare un esame di guida, non appena lo avrai superato sarai certo di aver raggiunto il vostro obiettivo. Con il metodo della forza di volontà la narrazione interna è: "*Se riesco a stare abbastanza a lungo senza porno su Internet, alla fine mi passerà la voglia di guardarlo*". Lo si può vedere in pratica nei forum online dove i tossicodipendenti parlano dei loro periodi o giorni di astinenza.

Come già detto, l'agonia che l'utente prova è mentale e causata dall'incertezza. Anche se non c'è dolore fisico, gli effetti sono comunque potenti. Ormai infelice e insicuro, l'utente è lontano dall'oblio, ormai pieno di dubbi e paure.

-   "*Quanto durerà il desiderio?*".

-   "*Sarò mai di nuovo felice?*".

-   "*Avrò mai voglia di alzarmi la mattina?*".

-   "Come potrò mai affrontare lo stress in futuro?\*".

L'utente aspetta che le cose migliorino, ma mentre continua a deprimersi, l'"harem" diventa sempre più prezioso. In realtà, qualcosa *sta accadendo* ma inconsciamente, se riesce a sopravvivere tre settimane senza aprire il browser, la voglia di quel mostriciattolo scompare. Tuttavia, come detto in precedenza, le crisi di astinenza da dopamina e oppioidi sono così lievi che l'utente non se ne accorge nemmeno. A questo punto, molti consumatori sentono di aver "smesso" e quindi danno una sbirciatina per dimostrarlo, tornando ad alimentare nuovamente lo scivolo. Avendo fornito dopamina al corpo, ora c'è una vocina in fondo alla mente che dice: "Ne vuoi un altro pò". In realtà, l'avevano abbandonata, ma si sono ri-agganciati ad essa.

Da bambino guardavi i cartoni animati e, secondo le neuroscienze, hai formato dei percorsi neurali (DeltaFosB) per essi. Se si volesse dissuadere un bambino dal guardarli, si studierebbe se questi percorsi esistono ancora e si farebbe un sondaggio tra gli adulti per capire perché non amano più guardare i loro cartoni animati preferiti dell'infanzia. In primo luogo, esistono intrattenimenti migliori e, in secondo luogo, i cartoni animati non hanno più la stessa magia. Con il metodo della forza di volontà si nega al bambino il cartone animato, ma con EasyPeasy ci si assicura anche che non ne veda il valore.

Di solito l'utente non si sottopone immediatamente a un'altra sessione, pensando "*non voglio essere agganciato di nuovo!*" e lascia passare un periodo sicuro di ore, giorni o addirittura settimane. L'ex-utente può quindi dire: "*Beh, non sono stato agganciato, quindi posso tranquillamente fare un'altra sessione*". È ricaduto nella stessa trappola di quando ha iniziato e si trova già su una china scivolosa.

Gli utenti che hanno successo con il metodo della forza di volontà tendono a trovarlo lungo e difficile, perché il problema principale è il lavaggio del cervello. Molto tempo dopo che la dipendenza fisica si è esaurita, l'utente continua a deprimersi. Alla fine, dopo essere sopravvissuto a questa tortura a lungo termine, inizia a capire che non si arrenderà, smettendo di deprimersi e accettando che la vita continua ed è piacevole anche senza il porno. Ci sono molti più fallimenti che successi, alcuni di coloro che hanno successo attraversano la loro vita in uno stato di vulnerabilità, lasciati con una certa dose di lavaggio del cervello che dice loro che il porno in effetti dà loro una spinta. Questo spiega perché molti utenti che hanno smesso per lunghi periodi finiscono per ricominciare in seguito.

Molti ex-utenti si concedono una sessione occasionale come "regalo speciale" o per convincersi di quanto sia forte il loro autocontrollo. Ma non appena la sessione termina la dopamina inizia ad andarsene e una vocina in fondo alla mente li spinge a farne un'altra. Se decidono di partecipare, la situazione sembra ancora sotto controllo, senza scosse, escalation o ricerca di novità, così dicono: "*Meraviglioso! Anche se non mi sta piacendo molto, non mi lascerò coinvolgere. Dopo Natale / queste vacanze / questo trauma, smetterò*". Non sanno che gli scivoli del loro cervello sono stati nuovamente lubrificati.

Troppo tardi, sono già agganciati! La trappola da cui erano riusciti a liberarsi ha fatto di nuovo la sua vittima.

Come già detto, il piacere non c'entra. Non c'è mai stato! Se guardassimo per divertimento, nessuno resterebbe sui siti della TV per più tempo di quello necessario a finire l'azione. Ad ogni modo, un modo migliore di auto-compiacersi è quello dei ricordi. Pensiamo che il porno su Internet ci piaccia solo perché non possiamo credere che saremmo così stupidi da diventarne dipendenti se non ci piacesse. La maggior parte degli utenti non ha idea dello stimolo supernormale, della ricerca di novità o di shock e, anche dopo aver letto qualcosa al riguardo, non crede che il suo uso sia motivato dal rewiring evolutivo del circuito di ricompensa. È per questo che gran parte del porno è subconscio: se si fosse consapevoli dei cambiamenti neurologici e si dovesse giustificare il costo futuro, anche l'illusione del piacere verrebbe meno.

Quando cerchiamo di bloccare la nostra mente sul lato negativo, ci sentiamo stupidi. Se dovessimo affrontarlo, sarebbe intollerabile! Se osservate un utente in azione, vedrete che è felice solo quando è inconsapevole del suo utilizzo. Una volta consapevoli, tendono a sentirsi a disagio e a scusarsi. Il porno alimenta il piccolo mostro, quindi, dopo averlo eliminato dal corpo insieme al lavaggio del cervello (il grande mostro), non avrai più bisogno né voglia di guardarlo!
