# Attenzione alla riduzione

Molti utenti ricorrono alla riduzione come tappa intermedia verso la cessazione, o come tentativo di controllare il piccolo mostro. Molti consigliano la riduzione o una "dieta del porno" come tattica per smettere. L'uso della riduzione come trampolino di lancio per smettere è ***fatale.*** Sono questi tentativi di riduzione che ci tengono intrappolati per il resto della nostra vita. In genere, la riduzione segue i tentativi falliti di smettere. Dopo alcune ore o giorni di astinenza, l'utente dice qualcosa come:

"*Non riesco ad affrontare il pensiero di andare a dormire senza aver visitato il mio harem online, quindi d'ora in poi userò il porno solo una volta ogni quattro giorni o epurerò la mia collezione di 'porno cattivo'. Se riesco a seguire questa dieta del porno, posso mantenerla o ridurla ulteriormente"*.

Ora accadono alcune cose terribili:

1.  Sono bloccati nel peggiore dei mondi, ancora dipendenti dal porno su Internet e mantengono il mostro vivo non solo nel loro corpo, ma anche nella loro mente.

2.  Vivono la propria vita in attesa della prossima sessione.

3.  Prima di smettere, ogni volta che volevano visitare il loro harem accendevano il browser e alleviavano almeno in parte le loro crisi di astinenza. Ora, in aggiunta al normale stress della vita, si stanno causando le crisi di astinenza per la maggior parte della loro vita, il che li rende ancora più infelici e di cattivo umore.

4.  Mentre si concedevano, non si godevano la maggior parte delle sessioni né si rendevano conto che stavano usando uno stimolo supernormale. Era automatico, l'unica visita all'harem di cui hanno goduto è stata quella dopo un periodo di astinenza. Ora che aspettano un'ora in più per ogni visita all'harem, "godono" di ogni visita. Più si aspetta, più ogni sessione sembra diventare "piacevole", perché il "piacere" di una sessione non è la sessione stessa, ma la fine dell'agitazione causata dal desiderio, sia esso un leggero desiderio fisico o un rimuginio mentale. Più lunga è la sofferenza, più "piacevole" diventa ogni seduta.

La difficoltà principale nello smettere non è la dipendenza neurologica, che è facile. I consumatori smettono senza difficoltà in varie occasioni: morte di una persona cara, problemi familiari o di lavoro, ecc. Possono passare, ad esempio, dieci giorni senza accedervi e la cosa non li disturba. Ma se passassero gli stessi dieci giorni in cui avrebbero potuto avere accesso al porno, si strapperebbero i capelli.

Molti utenti hanno la possibilità di astenersi durante il giorno lavorativo, passano per Victoria's Secret, piscine e così via senza eccessivi disagi. Molti si astengono se devono dormire temporaneamente sul divano per far posto a un visitatore o se sono loro stessi in visita. Anche nei Go-Go bar o nelle spiagge per nudisti non ci sono state rivolte. Gli utenti sono quasi contenti che qualcuno o qualcosa dica che non possono vedere il porno. In effetti, gli utenti che vogliono smettere provano un piacere segreto nel passare lunghi periodi senza visite all'harem, dando loro la speranza che forse un giorno non ne avranno più voglia.

Il vero problema quando si smette è il lavaggio del cervello, un'illusione che il porno su Internet sia una sorta di sostegno o ricompensa e che la vita non sarà più la stessa senza di esso. Lungi dall'abbandonare il porno su Internet, l'unica cosa che si ottiene con la riduzione è quella di sentirsi insicuri e infelici, convincendosi che la cosa più preziosa su questa terra è il nuovo filmato che si è perso, che non c'è modo di essere di nuovo felici senza vederlo.

Non c'è niente di più patetico dell'utente che sta cercando di ridurre il proprio consumo. Soffre dell'illusione che meno porno guarda, meno avrà voglia di visitare gli harem online. È vero il contrario: meno guardano il porno, più a lungo soffrono le crisi di astinenza e più "godono" del sollievo di alleviarle. Tuttavia, si accorgeranno che il loro genere preferito non è più all'altezza. Ma questo non li fermerà: se i siti tube fossero dedicati a una sola star o a un solo genere, nessun utente ci andrebbe più di una volta.

Difficile da credere? Qual è il peggior momento di autocontrollo che si prova? Aspettare per quattro giorni e poi avere un orgasmo. E qual è il momento più prezioso per la maggior parte degli utenti che seguono una dieta porno di quattro giorni? Esatto, lo stesso climax dopo aver aspettato quattro giorni! Credete davvero di masturbarvi per godervi l'orgasmo o la spiegazione più razionale è che avete bisogno di alleviare le crisi di astinenza nell'illusione di averne diritto?

La rimozione del lavaggio del cervello è essenziale per eliminare le illusioni sul porno prima di spegnere l'ultima sessione. Se non si elimina l'illusione di provare piacere prima di chiudere la finestra, non c'è modo di dimostrarlo in seguito senza rimanere agganciati di nuovo. Quando passate sopra i segnalibri e le immagini salvate, chiedetevi dove sia la gloria in questa azione. Forse credete che solo certi filmati siano di buon gusto, come quelli su temi abituali o preferiti. Se è così, perché preoccuparsi di guardare altri video o temi? Perché avete preso l'abitudine? Perché mai qualcuno dovrebbe incasinare abitualmente il proprio cervello e sprecare se stesso? Dopo un mese non c'è nulla di diverso, perché un video porno dovrebbe essere diverso?

Potete verificarlo voi stessi, trovando quel video hot del mese scorso. Fissate un promemoria e guardate lo stesso filmato dopo un mese senza porno. Il filmato colpirà (quasi) gli stessi punti del mese scorso. Lo stesso filmato sarà diverso dopo un evento sociale in cui si è rifiutati o messi alla prova da un potenziale partner. Il motivo è che il tossicodipendente non potrà mai essere pienamente felice se il piccolo mostro rimane insoddisfatto.

Che c'entra la soddisfazione? È solo che sono infelici se non possono alleviare i sintomi dell'astinenza. La differenza tra guardare un porno e non guardarlo è la differenza tra essere felici e infelici. Ecco perché il porno su Internet sembra essere migliore. Gli utenti che si collegano ai loro siti di prima mattina per il porno sono infelici, sia che lo guardino sia che non lo guardino.

La riduzione non solo non funziona, ma è la peggiore forma di tortura. Non funziona perché inizialmente l'utente spera che, prendendo sempre meno l'abitudine, si riduca il desiderio di guardare il porno. Non è un'abitudine, è una dipendenza. La natura di qualsiasi dipendenza è quella di volere sempre di più, non sempre di meno. Per questo motivo, per ridurre la dipendenza, l'utente deve esercitare la forza di volontà e la disciplina per il resto della sua vita. Quindi, smettere significa esercitare forza di volontà e disciplina per sempre. Smettere è molto più facile e meno doloroso, ci sono letteralmente decine di migliaia di casi in cui la riduzione è fallita.

Il problema di smettere non è la dipendenza da dopamina, che è facile da gestire. È l'errata convinzione che il porno dia piacere, causata inizialmente dal lavaggio del cervello ricevuto prima di iniziare a farne uso e ulteriormente rafforzata dalla dipendenza vera e propria. La riduzione della dipendenza non fa altro che rafforzare ulteriormente l'errore, fino a far sì che il porno domini completamente la loro vita e li convinca che la cosa più preziosa sulla terra sia la loro dipendenza.

La manciata di casi che hanno avuto successo sono stati raggiunti con un periodo relativamente breve di riduzione, seguito da un "cold turkey". Questi consumatori hanno smesso nonostante la riduzione, non grazie ad essa. Tutto ciò che ha fatto è stato prolungare l'agonia, i tentativi falliti hanno lasciato i consumatori nervosi e ancora più convinti di essere dipendenti a vita. Questo di solito è sufficiente per farli tornare al loro harem online come piacere e stampella, o per un altro tratto prima del prossimo tentativo.

Tuttavia, la riduzione del numero di siti aiuta a illustrare l'inutilità del porno, mostrando chiaramente che le visite all'harem non sono piacevoli dopo i periodi di astinenza. Bisogna sbattere la testa contro un muro di mattoni (soffrire di crisi di astinenza) per rendere piacevole il momento in cui si smette. Pertanto, le scelte sono:

1.  Ridursi per tutta la vita e subire una tortura autoimposta, che comunque non si potrà fare.

2.  Torturarsi sempre più a vita, il che è inutile.

3.  Essere gentili con se stessi e tagliare completamente con il porno.

L'altro aspetto che la riduzione dimostra è che non esiste una visita occasionale o saltuaria all'harem. Il porno su Internet è una reazione a catena che durerà per il resto della tua vita, a meno che tu non faccia uno sforzo positivo per interromperla.

**Ricorda: La riduzione della pornografia ti trascinerà verso il basso.**
