# Solo una sbirciatina

"Solo una sbirciatina" è un mito che dovete rimuovere dalla vostra mente:

- È *una sola sbirciatina* che ci fa iniziare.

- È *una sola sbirciatina* per superare un momento difficile o un'occasione speciale che vanifica la maggior parte dei nostri tentativi di smettere.

- È *una sola sbirciatina* che, dopo essere riusciti a rompere la dipendenza, ci fa ricadere nella trappola. A volte è solo per confermare che non abbiamo più bisogno del porno e una visita all'harem serve proprio a questo.

I postumi del porno sono orribili e convincono l'utente che non sarà mai più dipendente, ma lo è già. L'utente sente che qualcosa che lo rende così infelice e colpevole non avrebbe dovuto spingerlo a farlo, eppure lo ha fatto.

È il pensiero di "una sessione speciale" che spesso impedisce agli utenti di smettere, quella dopo un lungo viaggio in conferenza, una dura giornata di lavoro, un litigio con i bambini o un incidente in cui il vostro partner vi rifiuta per il sesso. Mettetevi in testa che non esiste "una sola sbirciatina". È una reazione a catena che, se non viene interrotta, durerà per il resto della vita. Il mito dell'occasione speciale continua a tenere gli utenti in ansia dopo aver smesso. Prendete l'abitudine di non vedere mai la sessione "senza problemi", è una fantasia. Ogni volta che pensi al porno, vedi una sporca vita passata dietro uno schermo per il privilegio di distruggerti mentalmente e fisicamente, una vita di schiavitù e disperazione. Non è un crimine se le tue erezioni sono inaffidabili, ma lo è quando potresti essere più felice a lungo termine e invece scegli di sacrificarla per un "piacere" a breve termine.

È vero che non possiamo sempre trovare "qualcosa da fare" per il vuoto; non è realisticamente possibile farlo in ogni occasione per tutta la vita. Possiamo pianificare la maggior parte di essa, ma a volte succede e basta. Anche i momenti belli e brutti accadono, a prescindere dal porno. Ma mettetevelo bene in testa: non è il porno. Sei bloccato tra una vita di infelicità o nessuna, non ti sogneresti mai di prendere il cianuro solo perché ti piace il sapore delle mandorle, quindi smetti di punirti con una sessione occasionale di "niente di che". Chiedete a un utente con problemi: "*Se avessi avuto l'opportunità di tornare indietro al tempo prima di diventare dipendente, saresti diventato un utente?*". La risposta è inevitabilmente: "*Stai scherzando!*". Eppure ogni utente ha questa possibilità di scelta ogni giorno della sua vita, perché non la sceglie? La risposta è la paura. La paura di non poter smettere o che la vita non sarà più la stessa senza.

Smettila di prenderti in giro! Puoi farlo, chiunque può farlo. È ridicolmente facile, ma per renderlo tale ci sono alcuni elementi fondamentali da avere ben chiari in mente.

1.  Non c'è nulla a cui rinunciare, ma solo meravigliosi guadagni positivi da raggiungere.

2.  Non farti convincere mai da una sessione di "niente di che" o di "solo una sbirciatina". Non esiste. Esiste solo una vita di sporcizia e schiavitù.

3.  Non c'è nulla di diverso in te, qualsiasi utente può smettere facilmente.

Molti utenti credono di essere tossicodipendenti accertati o di avere una personalità che crea dipendenza. Questo accade di solito a seguito di letture eccessive di articoli di neuroscienza sconvolgenti. Non è così, nessuno nasce con il bisogno di masturbarsi con i porno prima di diventarne dipendente. È la droga che ti aggancia, non la natura del tuo carattere o della tua personalità. La natura dello stimolo supernormale che crea dipendenza fa credere che sia così. Tuttavia, è essenziale rimuovere questa convinzione perché se credete di essere dipendenti, lo sarete anche dopo che il piccolo mostro nel vostro corpo sarà morto da tempo. È essenziale rimuovere tutto questo lavaggio del cervello.
