# Utilizzatori casuali

Gli utenti abituali tendono a invidiare gli utenti occasionali del porno, abbiamo tutti incontrato questi personaggi: "*Oh, posso stare tutta la settimana senza una sessione, non mi disturba affatto*". Vorremmo essere così. Può essere difficile da credere, ma a nessun utente piace essere un utente. Non dimenticatelo mai:  


| Nessun utente ha mai deciso di diventarlo, né occasionalmente né in altro modo.

| Tutti gli utenti si sentono stupidi, perciò...

| Tutti gli utenti devono mentire a se stessi e agli altri nel vano tentativo di giustificare la propria stupidità.


I fanatici del golf si vantano di quanto spesso giocano e vogliono giocare, quindi perché gli utenti si vantano di quanto poco si masturbano? Se questo è il vero criterio, allora sicuramente il riconoscimento è quello di non masturbarsi affatto, non è vero?

Se qualcuno vi dicesse: "*Posso stare tutta la settimana senza carote e non provo il minimo fastidio*", pensereste di parlare con un pazzo. Se mi piacciono le carote, perché dovrei stare tutta la settimana senza? Se non mi piacessero, perché farei un'affermazione del genere? Quindi, quando un utente fa un commento sul fatto di sopravvivere una settimana senza sessione, sta cercando di convincere se stesso - e voi - che non ha un problema. Ma non ci sarebbe bisogno di fare una dichiarazione se non avesse un problema. Tradotto, questo commento è "*Sono riuscito a sopravvivere un'intera settimana senza porno*". Come ogni utente, spera di poter sopravvivere al resto della propria vita. Riuscendo a sopravvivere solo una settimana, riuscite a immaginare quanto preziosa debba essere stata la sessione successiva, dopo essersi sentiti privati per un tempo così?

Questo è il motivo per cui i consumatori occasionali sono di fatto più coinvolti di quelli abituali: non solo l'illusione del piacere è maggiore, ma hanno anche meno incentivi a smettere perché passano meno tempo e sono quindi meno vulnerabili ai rischi per la salute. Occasionalmente, possono sperimentare disfunzioni sessuali, ma non sono sicuri di cosa le abbia causate e quindi vengono attribuite ad altri fattori. Ricordate che l'unico piacere che i consumatori traggono è il ciclo di ricerca della dopamina e l'alleviamento delle crisi di astinenza, come è già stato spiegato. Il piacere è un'illusione, immaginate il piccolo mostro del porno come un prurito quasi impercettibile di cui non ci rendiamo conto per la maggior parte del tempo.

Se si ha un prurito permanente, la tendenza naturale è quella di grattarlo. Poiché i circuiti di ricompensa diventano sempre più immuni alla dopamina e agli oppioidi, la tendenza è quella di eccedere, intensificare, abbuffarsi, cercare la novità, cercare lo shock, ecc. Ci sono quattro fattori principali che impediscono agli utenti di avere una visione ininterrotta.

**Tempo**.
La maggior parte non può permettersi di farlo.

**Salute**.
Per alleviare il prurito, dobbiamo consumare tutto il materiale gratuito disponibile e anche di più. La capacità di far fronte a questo tipo di abbuffate varia da individuo a individuo, in momenti e situazioni diverse della vita. Questo agisce come un freno automatico.

**Disciplina**.
Imposta dalla società o dal lavoro, dagli amici e dai parenti dell'utente; forse anche dall'utente stesso, come risultato del naturale braccio di ferro che si scatena nella mente di ogni utente.

**Immaginazione**.
La mancanza di immaginazione riduce lo shock, la novità e altri valori della clip su base soggettiva.

È facile pensare che gli utenti "non occasionali" siano deboli, incapaci di capire perché gli altri riescano a limitare la loro "assunzione". Tuttavia, gli utenti più assidui dovrebbero tenere a mente che la maggior parte degli utenti occasionali è semplicemente incapace di guardare ininterrottamente, perché richiede un'immaginazione e una resistenza molto forti. Alcuni di questi utenti che tendono a invidiare gli utenti occasionali sono fisicamente incapaci di fare di più, o perché il loro lavoro, la società o il loro stesso odio per la dipendenza non glielo permettono.

Può essere utile fornire alcune definizioni.

**Il non utente**

Qualcuno che non è mai caduto nella trappola, ma che non dovrebbe essere compiaciuto. È un non-utente solo per fortuna o per grazia della bontà. Tutti gli utenti erano convinti di non essere mai stati agganciati e alcuni non utenti continuano a immergersi in una sessione occasionale.

**L'utente occasionale**

Di cui esistono due classificazioni di base:

1.  L'utente che è caduto nella trappola ma non se ne rende conto - non invidiate questi utenti. Stanno solo assaggiando il nettare all'imboccatura della pianta e, con ogni probabilità, diventeranno presto consumatori abituali. Ricordate che, così come tutti gli alcolisti hanno iniziato come bevitori occasionali, anche tutti i consumatori iniziano casualmente.

2.  L'utente che in precedenza era un forte consumatore e che quindi pensa di non poter smettere. Questi utenti sono i più tristi di tutti e si dividono in varie categorie, ognuna delle quali richiede un commento a parte.

**L'utente "una volta al giorno"**.

Se si godono il diritto all'orgasmo, perché usare il porno su Internet solo una volta al giorno? Se possono prendere o lasciare, perché preoccuparsi? Ricordate, l'"abitudine" è, in realtà, sbattere la testa contro il muro per rilassarsi quando si smette. Chi assume una volta al giorno allevia le proprie crisi di astinenza per meno di un'ora al giorno. Anche se non ne è consapevole, il resto della giornata lo passa sbattendo la testa contro questo muro, e lo fa per la maggior parte della sua vita. Si fa uso di una volta al giorno perché non si può rischiare di essere scoperti o di compromettere la propria salute neurologica. È facile convincere un consumatore abituale che non si diverte, ma è molto più difficile convincere un consumatore occasionale. Chiunque abbia provato a ridurla sa che è la tortura peggiore di tutte e che è quasi garantito che la dipendenza rimanga per il resto della vita.

**L'utente rifiutato**

Esigono il diritto all'orgasmo ogni giorno, ma il loro partner sessuale non è sempre felice di soddisfare la richiesta. Inizialmente usano il porno su Internet per riempire questo vuoto, ma dopo aver preso l'eccitante "scivolo d'acqua" rimangono intrappolati in un ciclo di novità, shock, immagini supernormali, ecc. In realtà, sono contenti del rifiuto del partner perché fornisce una sorta di scusa. Se il porno su Internet ti dà così tanto, perché preoccuparsi di avere un partner? Lasciateli liberi. Non si godono nemmeno le sessioni quando devono "portare" il partner nella loro mente. A un certo punto, cercano il loro partner nella vita reale per avere una scusa per avventurarsi nelle valli oscure di Internet.

**L'utente della dieta del porno**

Conosciuto anche come "*Posso smettere quando voglio. L'ho fatto migliaia di volte!".

Se pensano che stare a dieta li aiuti a trovare l'umore giusto per rimorchiare, perché sono a dieta una volta ogni quattro giorni? Nessuno può prevedere il futuro, e se l'incontro avvenisse un'ora dopo la seduta programmata? Inoltre, se "pulire le tubature" di tanto in tanto è utile per alleviare la tensione, perché non farlo ogni giorno? È stato dimostrato che la masturbazione non è necessaria per mantenere i genitali in salute e che il porno su Internet non è affatto necessario. Anche se fosse così, nessun "guru" dell'arte del rimorchio che abbia letto dei danni neurologici consiglierebbe mai di guardare porno super-stimolanti. La verità è che sono ancora presi. Anche se si sono liberati della dipendenza fisica, rimangono con il problema primario del lavaggio del cervello. Sperano ogni volta di smettere definitivamente, ma presto ricadono nella stessa trappola.

La maggior parte degli utenti in realtà invidia questi "stopper" e "starter" e pensa a quanto sia "fortunato" chi è a dieta per essere in grado di controllare il proprio consumo. Tuttavia, trascurano il fatto che chi è a dieta non controlla il proprio consumo: quando lo fa, vorrebbe non farlo. Si sottopongono al fastidio di smettere, poi iniziano a sentirsi privati e cadono di nuovo nella trappola, desiderando di non averlo fatto. In questo modo si ottiene il peggio di entrambi i mondi. Se ci pensate, questo è vero nella vita degli utenti quando viene concesso loro di avere una sessione: prenderla come un diritto o desiderare di non averla. È solo quando ne sono privati che il porno diventa prezioso. La sindrome del "frutto proibito" è uno dei terribili dilemmi degli utenti. Non possono mai vincere perché si struggono per un mito, un'illusione. C'è un solo modo per vincere: smettere di deprimersi smettendo di usare il porno!

**L'utente "Guardo solo porno statico/amatoriale"**.

Sì, all'inizio lo fanno tutti, ma non è incredibile come il valore di shock medio di queste clip sembri aumentare rapidamente, e prima che ce ne accorgiamo ci sentiamo privati (tolleranza)? La novità manca con il porno statico, quindi "paghiamo il pifferaio per una tazza di grasso" e scendiamo lungo lo scivolo verso il risentimento e il senso di colpa. La cosa peggiore che si possa fare è usare le foto del partner (ovviamente con l'approvazione) per masturbarsi. Perché? Perché in questo modo si ricreano nel cervello le vampate di dopamina indotte dalla ricerca e dalla varietà. Dal punto di vista chimico, l'acqua che scorre nel cervello è il DeltaFosB, per cui vi troverete in difficoltà quando sarete con lui/lei in tempo reale.

Un'altra trappola di questa categoria è il porno "amatoriale" e "fatto in casa". La maggior parte sono falsi e lo sapete, inoltre non vi fermerete al primo che vi capita sotto gli occhi, ma continuerete a cercare e ricercare. Ricordate, non è solo l'orgasmo che il cervello cerca, ma la novità della caccia che dà il brivido allo scivolo. Il problema non è il contenuto del porno, sia esso amatoriale o professionale, ma le vampate di dopamina nel cervello che causano l'accumulo di tolleranza e sazietà. Il porno distrugge il normale funzionamento del cervello, la masturbazione confonde la risposta muscolo-cervicale; l'orgasmo inonda il cervello di oppioidi e rende il percorso più facile da seguire la prossima volta.

**L'utente che "ha smesso ma sbircia di tanto in tanto "**.

In un certo senso, i consumatori sbiricianti sono i più patetici di tutti. O passano la vita credendo di essere privati, o più spesso, le sbirciatine occasionali diventano due. Scivolano verso il basso sul pendio e prima o poi tornano a essere forti consumatori. Sono caduti di nuovo nella stessa trappola iniziale.

Esistono altre due categorie di utenti occasionali. La prima è quella che si masturba con le immagini o i filmati degli ultimi video hard delle celebrità che fanno notizia, o con qualcosa che si sono "portati a casa" da una visione "accidentale" a scuola o al lavoro. Queste persone sono in realtà dei non utenti, ma sentono che si stanno perdendo qualcosa. Vogliono essere parte dell'azione, e la maggior parte di noi ha iniziato in questo modo. La prossima volta, notate che dopo un po' la celebrità della vostra fantasia non fa più per voi. Quanto più "irraggiungibile" è l'obiettivo della vostra fantasia, tanto più frustrante è l'astinenza dall'orgasmo.

La seconda categoria è stata recentemente oggetto di attenzione, descritta al meglio da un caso condiviso online.

Una donna professionista leggeva storie porno su Internet da molti anni e non le aveva mai usate più di una volta a notte. Era inoltre una donna dalla volontà molto forte. La maggior parte degli utenti si sarebbe chiesta perché volesse smettere - sottolineando volentieri che nel suo caso non c'era alcun rischio di PIED o PE (falso). Non stava nemmeno usando immagini statiche, le storie erano molto più leggere di qualsiasi materiale che loro stessi usano quotidianamente.

Questi commettono l'errore di ritenere che gli utenti occasionali siano più felici e più controllati. Forse hanno più controllo, ma di certo non sono felici. Nel caso della donna, non era soddisfatta del suo partner né del sesso reale, ed era molto irritabile quando rispondeva alle sollecitazioni quotidiane. Le persone più care non riuscivano a capire cosa la preoccupasse. Anche se si convinceva di non temere il suo uso attraverso la razionalizzazione, si trovava comunque nell'impossibilità di godere di relazioni vere e proprie che comportavano inevitabilmente alti e bassi. Il centro di ricompensa del suo cervello non era in grado di affrontare i normali distress presenti nella vita, a causa dell'inondazione quotidiana di dopamina. La conseguente riduzione dei recettori cerebrali l'aveva resa malinconica nella maggior parte delle giornate. Come molti, aveva una grande paura del lato oscuro della pornografia e del trattamento riservato alle donne, prima della sua prima volta. Alla fine è stata vittima del lavaggio del cervello della società e ha provato il suo primo sito. A differenza della maggior parte di coloro che capitolano e diventano utenti abituali, dopo aver visto i filmati di violenza, è fuggita.

Tutto ciò per cui godi nel porno è il mettere fine al desiderio iniziato prima, sia che si tratti di un desiderio fisico quasi impercettibile, sia che si tratti della tortura mentale di non potersi grattare durante un prurito. Il porno su Internet è di per sé un veleno, ed è per questo che si ha l'illusione di goderne solo dopo periodi di astinenza. Come per la fame o la sete, più a lungo si soffre, più grande è il piacere quando finalmente ci si libera. Commettendo l'errore di credere che il porno sia solo un'abitudine, si pensa: "*Se riesco a mantenerlo a un certo livello o solo in occasioni speciali, il mio cervello e il mio corpo lo accetteranno. Poi, posso continuare a usarlo a quel livello o ridurlo ulteriormente se lo desidero "*.

Mettete in chiaro nella vostra mente che l'"abitudine" non esiste. Il porno è una tossicodipendenza, con la tendenza naturale ad alleviare le crisi di astinenza, non a sopportarle. Per mantenerla al livello in cui si trova attualmente dovresti esercitare un'enorme quantità di disciplina e forza di volontà per il resto della tua vita; man mano che il centro di ricompensa del cervello diventa immune alla dopamina e agli oppioidi, vuole sempre di più, non sempre di meno.

Quando il porno inizia a distruggere gradualmente il sistema nervoso, il coraggio, la fiducia e il controllo degli impulsi, si diventa sempre più incapaci di resistere riducendo l'intervallo tra una sessione e l'altra. Ecco perché nei primi tempi possiamo prendere o lasciare. Se avvertiamo un segnale di malessere mentale o fisico, ci fermiamo. Non invidiate questa donna, quando si usufruisce del porno solo una volta ogni ventiquattro ore sembra essere la cosa più preziosa sulla terra, trasformando il porno in un "frutto proibito". Per molti anni questa povera donna è stata al centro di un braccio di ferro.

Non riusciva a smettere di usarlo, ma aveva paura di passare ai video Per ventitré ore e dieci minuti di tutti quei giorni ha dovuto combattere la tentazione e la mancanza di sentimenti verso il suo ragazzo. Le è servita un'enorme forza di volontà per fare quello che ha fatto, che alla fine l'ha ridotta in lacrime. Casi del genere sono rari, ma guardate la situazione in modo logico: O c'è un vero e proprio sostegno o un vero e proprio piacere nel porno, oppure non c'è. Se c'è, chi vuole aspettare un'ora, un giorno o addirittura una settimana? Perché privarsi del sostegno o del piacere nel frattempo? Se non c'è un vero sostegno o un vero piacere, perché disturbarsi a visitare il proprio harem online?

Ecco un altro caso di un uomo che si concede una volta ogni quattro giorni e che descrive la sua vita come segue:

> "*Ho quarant'anni, ho sofferto di PIED (disfunzione erettile indotta dal porno) con donne reali e anche quando uso il porno, cioè la maggior parte delle volte. Era da un po' che non avevo un'erezione completa. Prima di seguire la dieta del porno una volta su quattro, dormivo tranquillamente tutta la notte dopo la sessione. Ora mi sveglio a ogni ora della notte e non riesco a pensare ad altro. Anche quando dormo, sogno i miei filmati preferiti. Nei giorni successivi alla seduta programmata mi sento piuttosto giù di morale, perché la dieta assorbe tutte le mie energie. Il mio compagno mi lascerebbe solo perché sono irascibile e se non può andarsene, non mi vuole in casa. Faccio jogging all'aperto, ma la mia mente è ossessionata da questo.
>
> Il giorno stabilito comincio a pianificare la sera e mi irrito molto se succede qualcosa che va contro i miei piani. Mi tiro indietro nelle conversazioni e mi estraneo (per poi pentirmene) al lavoro e a casa. Non sono un tipo litigioso, ma non voglio che l'argomento o la conversazione mi trattengano. Ricordo le occasioni in cui ho litigato stupidamente con il mio compagno in modo da liberarmi. Aspetto le dieci e quando arrivano mi tremano le mani in modo incontrollabile. Non inizio subito - perché sono stati aggiunti nuovi video - e quindi prima "faccio un giro". La mia mente mi dice che, visto che ho fatto la fame per quattro giorni, mi merito un video "speciale" che deve valere il tempo speso a cercarlo. Alla fine mi accontento di uno o due, ma voglio che durino per poter 'sopravvivere' nei quattro giorni successivi, quindi mi prendo più tempo per finire l'opera"*.  

Oltre agli altri problemi, questo pover'uomo non ha idea che si sta avvelenando. Prima soffre della "sindrome del frutto proibito" e poi costringe il suo cervello a scaricare la dopamina. I suoi recettori della dopamina non sono così ridotti, ma lui sta alimentando gli scivoli del porno, cercando di ottenere emozioni, novità, varietà, shock e ansia per sopravvivere ai prossimi quattro giorni. Probabilmente vi immaginate quest'uomo come un patetico imbecille, ma non è così. Come ex atleta ed ex sergente della Marina, non voleva diventare dipendente da nulla. Tuttavia, al ritorno dalla guerra si è formato come tecnico informatico in un programma di riabilitazione per veterani. 

Quando è entrato nel mondo del lavoro civile, era un professionista informatico ben pagato in una banca e gli è stato dato un computer portatile da portare a casa. Era l'anno in cui alcuni famosi socialite "facevano trapelare" i loro video porno online e se ne parlava molto. Si è fatto prendere la mano e ha trascorso il resto della sua vita pagando fior di quattrini e rovinandosi fisicamente e mentalmente. Se fosse stato un animale, la società avrebbe già da tempo posto fine alle sue sofferenze, eppure permettiamo ancora a giovani adolescenti sani mentalmente e fisicamente di diventarne dipendenti. Potreste pensare che questo caso sia esagerato ma, per quanto estremo, è tutt'altro che unico. Ci sono decine di migliaia di storie simili. Potete essere certi che molti dei suoi amici e conoscenti lo invidiavano per essere un uomo che si masturba una volta ogni quattro giorni? Se pensate che non possa accadere a voi, smettete di prendervi in giro.

**STA GIÀ ACCADENDO.**

Come altri tossicodipendenti, i consumatori di pornografia sono noti per essere bugiardi, anche a se stessi. Devono esserlo. La maggior parte degli utenti occasionali si concede molte più volte e in molte più occasioni di quanto ammetta. In molte conversazioni con i cosiddetti "utenti bisettimanali" ammettono di averlo fatto più di tre o quattro volte a settimana. Leggete le storie su reddit, NoFap e i forum degli utenti occasionali, e scoprirete che o contano i giorni o aspettano di fallire. Non c'è bisogno di invidiare gli utenti occasionali, non c'è bisogno di usare nessuno dei due, la vita è infinitamente più dolce senza. Prendete il seguente diario:

"*È iniziato con la semplice sfida di non toccarmi per un giorno e non ci sono riuscito. Non penso più alla masturbazione, non mi passa per la testa. Questo è possibile, ve lo prometto. Le ricchezze che attendono coloro che sono in grado di farlo sono incredibili*".

Gli adolescenti sono in genere più difficili da curare, non perché trovino più difficile smettere, ma perché non credono di essere dipendenti o sono nelle fasi iniziali della trappola. In genere soffrono dell'illusione di smettere automaticamente prima della seconda fase.

I genitori dei bambini che amano il porno su Internet non devono avere un falso senso di sicurezza. Tutti i bambini detestano i lati oscuri del porno prima di diventarne dipendenti. A un certo punto lo avete fatto anche voi. Non fatevi ingannare nemmeno dalle campagne di allarmismo, la trappola è la stessa di sempre. I bambini sanno che il porno su Internet è uno stimolo supernormale, ma sanno anche che una "visita" o una "sbirciatina" non bastano. A un certo punto potrebbero essere influenzati da un partner, un compagno di classe o un collega di lavoro.

Non bisogna compiacersi di questo problema. L'incapacità della società di impedire che gli adolescenti diventino dipendenti dal porno su Internet e da altre droghe è forse l'aspetto più preoccupante di questa dipendenza. I cervelli degli adolescenti sono molto più plastici ed è necessario educarli e proteggerli. Se non sapete da dove cominciare, tra le buone risorse c'è il libro YourBrainOnPorn, che vi permetterà di conoscere le neuroscienze. Anche se sospettate che il vostro adolescente sia già dipendente dal porno, il libro fornisce le conoscenze fondamentali per aiutarlo a fuggire. Altrimenti, raccomandate questo libro!
