# Un'abitudine sociale?

La salute della mente e del corpo sono le ragioni principali per cui *dovremmo* voler smettere, ma lo sono sempre state. Non abbiamo bisogno di ricerche scientifiche e di conoscenze nel campo delle neuroscienze per sapere che il porno crea dipendenza e può potenzialmente distruggere le nostre vite. I nostri corpi sono gli oggetti più sofisticati del pianeta e ogni utente sa fin dalla prima sessione che lo stimolo può arrivare all'eccesso e diventare velenoso.

L'unica ragione per cui ci facciamo coinvolgere dal porno è la sovrapposizione del ciclo con la nostra programmazione evolutiva. Il porno su Internet è altamente disponibile, gratuito e in streaming ventiquattro ore al giorno. Un tempo il porno era considerato innocuo, ma quando le immagini erano statiche e i video richiedevano un viaggio al negozio locale per acquistare una cassetta VHS.

Oggi è opinione diffusa, anche tra gli stessi utenti, che il porno sia uno stimolo supernormale e che crei dipendenza. Un tempo, l'uomo forte non ammetteva di essersi masturbato, e masturbarsi era un termine dispregiativo. In ogni pub, club o bar, la maggior parte degli uomini era orgogliosa di voler portare a casa una donna e fare sesso vero. Oggi, la posizione è completamente invertita per il porno-dipendente di Internet, l'uomo di oggi si rende conto che sta iniziando a sentire che non ha bisogno di una donna. Si riunisce in rete e discute di esperienze, elabora strategie ed esplora opzioni. L'uomo forte di oggi non vuole dipendere dalle droghe. Grazie alla rivoluzione sociale, tutti gli utenti stanno pensando seriamente di smettere con il porno e la masturbazione su Internet. Gli utenti di oggi considerano il porno un'attività inutile e dannosa.

La tendenza più significativa notata sui forum è la crescente enfasi sugli aspetti antisociali del porno, i giorni in cui un uomo si vantava di avere sesso e orgasmi ogni giorno sono stati lentamente sostituiti dalla consapevolezza della schiavitù del mostro del porno.

L'unica ragione per cui le persone continuano dopo essere state istruite è perché non sono riuscite a smettere o sono troppo spaventate per provarci. C'è un ampio spettro di interesse per l'argomento, alcuni si astengono dal porno, dalla masturbazione e dall'orgasmo - con o senza partner. Le pratiche che separano le parti tantriche e propagative del sesso, come la ritenzione dello sperma e la Karezza, sono discusse e adottate in massa. Molti dei fallimenti sopra citati sono in realtà dei passi indietro, e quindi beneficiano in qualche modo le persone che li praticano. Una volta iniziato il percorso no-PMO, troverete l'adattamento migliore per la vostra vita; è consigliato elaborare il proprio obiettivo sugli orgasmi solo dopo aver compreso e praticato l'astensione sessuale. Qualunque sia il vostro percorso, vedrete l'utilità di limitare il numero di volte in cui riempite il vostro cervello di sostanze chimiche attraverso l'orgasmo e non vedrete mai più il porno, il sesso e l'orgasmo come un piacere o un appoggio per il vostro io emotivo.

Diverse comunità online molto popolari, fondate da non utenti, sono dedicate all'abbandono non solo del porno ma anche della masturbazione. Questi siti sono utili a chi sta allontanandosi dalla dipendenza, ma la maggior parte dei consigli indica loro di provare la forza di volontà. La conseguenza dell'ossessione è l'autocommiserazione e la mancanza di euforia. Gran parte del lavaggio del cervello è vivo e vegeto. Alla fine qualcuno crolla e si scatena un effetto domino: altri utenti scoprono di non essere gli unici. Tuttavia, i loro sforzi non sono vani, stanno facendo passi avanti, anche se con molta autotortura, perché chiudono i loro browser ma non il desiderio e il bisogno. EasyPeasy funziona al contrario, spegnendo prima il bisogno e il desiderio e poi il browser. Ogni giorno un numero sempre maggiore di utenti abbandona la nave che affonda e quelli rimasti a bordo hanno il terrore di essere gli ultimi.

**NON LASCIATE CHE SIA IL VOSTRO CASO!**
