# Tempismo

A parte l'ovvio punto che non vi sta facendo bene e che è il momento giusto per smettere, il tempismo è importante. La società tratta il porno su Internet con leggerezza, come un'abitudine leggermente sgradevole che non danneggia la salute. Questo non è vero. Si tratta di una tossicodipendenza, una malattia che distrugge le relazioni nella società. La cosa peggiore che accade nella vita della maggior parte degli utenti è l'aggancio a questa terribile dipendenza. Se si rimane agganciati, succedono cose orribili. Il tempismo è quindi importante per concedersi il diritto a una cura adeguata.

In primo luogo, individuate i momenti o le occasioni in cui il porno sembra essere importante per voi. Se sei un uomo d'affari che lo usa per avere l'illusione di alleviare lo stress, scegli un periodo relativamente tranquillo o una vacanza. Se invece utilizzate il porno soprattutto nei periodi di noia o di relax, vale il contrario. In ogni caso, prendete il tentativo seriamente e fatelo diventare la cosa più importante della vostra vita.

Guardate avanti per un periodo di tre settimane e cercate di anticipare qualsiasi evento che potrebbe portare al fallimento. Occasioni come viaggi per conferenze, il vostro partner fuori città, ecc. non devono scoraggiarvi, a patto che li anticipiate e non vi sentiate privati. Non cercate di ridurvi nel frattempo, perché questo creerebbe solo l'illusione che negarsi sia piacevole. Anzi, è utile forzarsi a guardare e a fare quante più sessioni porno possibile. Durante l'ultima sessione e l'ultima volta, fate attenzione alla delusione dovuta alla sazietà, alle aspettative non soddisfatte, a eventuali dolori corporei, agli effetti di astinenza, all'irritazione e alla malinconia. Pensate a quanto sarà meraviglioso quando vi permetterete di smettere di farlo.

**QUALUNQUE COSA FACCIATE, NON CADETE NELLA TRAPPOLA DI DIRE "NON ORA, PIÙ TARDI" E TOGLIETE QUESTO PENSIERO DALLA TESTA. STABILITE ORA IL VOSTRO CALENDARIO E GUARDATE AVANTI**.

Ricordate che *non state rinunciando a nulla*. Al contrario, state per ricevere meravigliosi vantaggi positivi.

Per anni, la professione medica ha considerato il porno come innocuo, senza conoscere la differenza tra il porno statico di un tempo e l'ultima esperienza di realtà virtuale in streaming. Il problema è che, sebbene ogni utente consumi porno su Internet solo per alleviare il desiderio di dopamina che ne deriva, non è la dipendenza dalla sostanza chimica ad agganciare l'utente, ma l'auto-lavaggio cerebrale che deriva dalla dipendenza. Una persona intelligente può cadere in un trucco, ma solo uno sciocco continuerebbe a cascarci dopo aver capito il trucco. Fortunatamente, la maggior parte dei consumatori non sono sciocchi, ma solo credono di esserlo. Ogni singolo utente subisce il proprio lavaggio del cervello. Ecco perché sembra esserci una gamma così varia di tipi di tossicodipendenti, che serve solo a complicare ulteriormente i misteri.

Sebbene l'obiettivo del libro originale fosse quello di smettere con la nicotina (una delle droghe più rapide e coinvolgenti che si conoscano), è stato piacevolmente sorprendente rendersi conto che la filosofia proposta è ancora valida se adattata. La conoscenza accumulata e la sfida che Carr e io affrontiamo è come comunicare questa conoscenza a ogni singolo utente. Il fatto che io sappia che ogni utente possa non solo trovare facile smettere, ma anche godere del processo, non è solo inutile ma estremamente frustrante, a meno che non si riesca a farlo capire a lui. Nel suo libro originale, Allen Carr spiega il suo consiglio controverso:

> "Molte persone mi hanno detto: *"Lei dice:"Continua a fumare finché non finisci il libro" Questo tende a far sì che il fumatore impieghi secoli a leggere il libro o semplicemente non lo finisca. Punto. Pertanto, dovresti cambiare le istruzioni. "* Sembra logico, ma so che se le istruzioni fossero: *"Smetti immediatamente"*, alcuni fumatori non inizierebbero nemmeno a leggere il libro. Un fumatore mi ha consultato nei primi giorni. Mi disse: *"Mi dà fastidio dover chiedere il suo aiuto, so di essere volitivo. In ogni altro ambito della mia vita ho il controllo. Perché tutti gli altri fumatori smettono di fumare usando la loro forza di volontà, mentre io devo venire da lei?"* E continuò: *"Penso che potrei farcela da solo, se potessi fumare mentre lo faccio"*.

La credenza sociale vuole che smettere di fumare sia incredibilmente difficile, quindi di cosa ha bisogno un fumatore quando qualcosa è difficile? Il nostro piccolo amico, il sostegno. Smettere di fumare sembra essere un doppio colpo: non solo c'è un compito da svolgere - che è già abbastanza difficile - ma l'appoggio su cui normalmente facciamo affidamento in queste occasioni non è disponibile. Forse la vera bellezza di questo metodo è che non è necessario "arrendersi" durante il processo; al contrario, ci si libera inizialmente di tutte le paure e i dubbi, per cui al termine della sessione finale si sta già godendo della libertà.

Pertanto, questo manuale manterrà intatto lo stesso consiglio. Non importa quanto si dica che sarà facile e piacevole, ci sarà una grande maggioranza che non sarà in grado di accettarlo a causa del lavaggio del cervello su quanto sia difficile smettere.

La tempistica è l'unico capitolo che mi fa dubitare seriamente del consiglio originale di Allen. Soprattutto, se tra i fattori scatenanti c'è lo stress da ufficio, allora scegliete un giorno festivo per fare un tentativo e viceversa. Questo non è il modo più semplice, ma scegliere quello che si considera il momento più *difficile*. Che si tratti di stress, obblighi sociali, concentrazione o noia, una volta dimostrato che si riesce a gestire e a godersi la vita nelle situazioni peggiori, ogni altra diventa piacevole. Ma se questo fosse il consiglio, fareste anche solo un tentativo?

Ecco un'analogia: io e mia sorella vogliamo nuotare insieme. Arriviamo in piscina alla stessa ora, ma raramente finiamo per nuotare insieme. Il motivo è che lei si immerge con un dito del piede e mezz'ora dopo nuota davvero. È una tortura lenta, so in anticipo che a un certo punto, per quanto fredda sia l'acqua, dovrò sfidarla. Così ho imparato a farlo nel modo più semplice: tuffarmi direttamente. Ora, immaginate se fossi nella posizione di insistere che se non si tuffasse subito, non saprebbe nuotare. Se così fosse, non nuoterebbe affatto. Capite il problema?

Dai feedback ricevuti, molti utenti hanno utilizzato il consiglio originale sulla tempistica per ritardare quello che pensano sarà il "giorno del male". Ho pensato di usare una tecnica simile a quella del capitolo sui "vantaggi del porno", qualcosa del tipo: *"Il tempismo è molto importante e nel prossimo capitolo ti verrà consigliato il momento migliore per fare il tentativo"* e nella pagina successiva c'è solo un enorme *"ORA!"* Questo è in effetti il consiglio migliore, ma tu lo seguiresti? Forse l'aspetto più sottile della trappola è che quando abbiamo un vero e proprio stress nella nostra vita non è il momento giusto per smettere, ma a volte senza stress non abbiamo alcun desiderio di porre fine alla tortura. Ponetevi le seguenti domande:

1.  Quando sei entrato nel mondo del porno per la prima volta, hai davvero deciso che avresti continuato a dipendere da esso per il resto della tua vita senza poter mai smettere? ***Certo che no!***

2.  Hai intenzione di continuare per il resto della tua vita senza poterti fermare? ***Certo che no!***

Allora quando smetterete? Domani? L'anno prossimo? L'anno dopo? Non è questo che vi chiedete da quando vi siete accorti di essere presi dalla dipendenza? Sperate che una mattina vi sveglierete e non avrete più voglia di guardarlo? Smettila di prenderti in giro: con qualsiasi dipendenza si diventa progressivamente più dipendenti, non meno. Hai intenzione di aspettare fino a quando non inizierai a sentire che alzarti dal letto è più difficile che masturbarti? Sarebbe un po' inutile.

La vera trappola è la convinzione che non sia il momento giusto: domani sarà sempre più facile. Crediamo di vivere una vita stressante, ma in realtà non è così. La maggior parte del vero stress è stato eliminato dalla nostra vita. Quando si esce di casa non si vive nella paura di essere attaccati da animali selvatici, la maggior parte non si chiede da dove verrà il prossimo pasto o se ci sarà un tetto sopra la testa stasera. Pensate alla vita di un animale selvatico: ogni volta che un coniglio esce dalla sua tana, deve affrontare il Vietnam, per tutta la vita. Ma il coniglio lo gestisce, ha l'adrenalina e altri ormoni, e lo stesso vale per noi. La verità è che i periodi più stressanti per la vita di qualsiasi creatura sono la prima infanzia e l'adolescenza. Ma tre miliardi di anni di selezione naturale ci hanno attrezzato per affrontare lo stress e molti di coloro che crescono con un'infanzia difficile conducono una vita normale.

È un luogo comune dire: *"Se non hai la salute, non hai niente"* ma è assolutamente vero. Quando ci si sente forti fisicamente e mentalmente, si possono godere gli alti e gestire i bassi. Molti confondono le responsabilità con lo stress, ma le responsabilità diventano stressanti solo quando non ci sentiamo abbastanza forti per gestirle. Ciò che distrugge la maggior parte delle persone non è lo stress, il lavoro o la vecchiaia, ma gli appoggi illusorie a cui si rivolgono.

Guarda la cosa in questo modo: hai già deciso che non rimarrai nella trappola per il resto della tua vita. Pertanto, a un certo punto, che sia facile o difficile, dovrai affrontare il processo di liberazione. Il porno non è un'abitudine o un piacere, è una tossicodipendenza e una malattia. Abbiamo stabilito che, lungi dall'essere più facile domani, peggiorerà progressivamente. Il momento di liberarsene è adesso, o il più vicino possibile a questo momento. Pensa a quanto velocemente passa ogni settimana della nostra vita, basta questo. Pensa a quanto sarà bello godersi il resto della vita senza ombre sempre più pesanti che incombono su di te Se segui tutte le istruzioni, non dovrai nemmeno aspettare cinque giorni o tre settimane. Non solo sarà facile smettere, ma **ti piacerà!**
