# Mi mancherà il divertimento?

**No!** Una volta che il piccolo mostro del porno sarà morto, dopo che il tuo corpo avrà smesso di desiderare la dopamina e gli scivoli d'acqua del porno, nel tuo cervello questi inizieranno rapidamente a svanire a causa della mancanza di "lubrificazione", ogni residuo di lavaggio del cervello svanirà. Non solo ti troverai fisicamente e mentalmente meglio equipaggiato per gestire lo stress e le tensioni della vita, ma godrai appieno dei bei momenti.

C'è solo un pericolo: l'influenza di coloro che usano ancora il sesso come appoggio e piacere. L'espressione *"l'erba del vicino è sempre più verde"* è comune in molti aspetti della nostra vita e facilmente comprensibile. Perché nel caso del porno - con svantaggi così enormi se paragonati agli illusori "vantaggi" - l'ex-utente tende a invidiare coloro che usano il sesso e la pornografia come appoggio?

Con tutto il lavaggio del cervello subito dall'infanzia, è comprensibile che siamo caduti nella trappola. Perché allora, dopo aver capito che il porno è un gioco da ragazzi ed essere riusciti a smettere, torniamo subito nella stessa trappola? È l'influenza del lavaggio del cervello della società che confonde il porno con il sesso, presentandolo come normale. L'ex-utente ha una fitta! L'insicurezza di essere single (che comunque non è un crimine) provoca sentimenti di ansia e lo spinge a salire sullo scivolo. Questa è davvero una curiosa anomalia, soprattutto se si considera questa osservazione: non solo tutti i non consumatori del mondo sono felici di esserlo, ma tutti i consumatori del mondo, anche con la loro mente distorta, assuefatta e sottoposta a lavaggio del cervello che si illude di godere o rilassarsi, vorrebbero non essere mai stati coinvolti. Allora, perché alcuni ex-utenti invidiano?

1.  Solo una sbirciatina. Ricordate che non esiste. Smettete di vedere l'occasione isolata e iniziate a guardarla dal punto di vista di chi usa il porno. Forse tu li stai invidiando, ma loro non si approvano e ti invidiano. Se solo poteste in qualche modo osservare clinicamente un altro utente, perché può essere la spinta più potente di tutte per aiutarvi a uscirne. Nota come aprono velocemente molte schede e finestre del browser? Vanno avanti velocemente alle sezioni importanti, si annoiano rapidamente dei filmati e passano attraverso la gamma di generi che producono novità, shock, ansia, ecc. Nota in particolare che l'atto sembra essere automatico. Ricorda: non è che si divertono, è che non riescono a divertirsi senza. La mattina dopo, svegliandosi con la volontà indebolita, l'energia persa e gli occhi spenti, dovranno continuare a soffocarsi alla prima apparizione di stress e tensione. Si troveranno di fronte a una vita di sporcizia, scarsa salute mentale e fiducia macchiata: una vita a distruggersi con ombre nere nella mente. Per raggiungere quale scopo? L'illusione di ottenere ciò che si "merita" e un dannato piacere?

2.  Il secondo motivo per cui alcuni ex-utenti hanno delle crisi è che chi usa il porno sta facendo qualcosa - come l'auto-piacere - e chi non lo fa tende a sentirsi privato. Chiaritevi bene le idee: non è il non-utente ad essere privato, ma il povero tossicodipendente ad essere privato:

    -   salute

    -   energia

    -   Fiducia

    -   Pace mentale

    -   coraggio

    -   Tranquillità

    -   Libertà

    -   Rispetto di sé

    Abbandona l'abitudine di invidiare i consumatori di pornografia e inizia a vederli come le creature miserabili e patetiche che sono in realtà. Lo so, una volta ero uno dei peggiori. È per questo che sei tu a leggere questo libro e non quelli che non riescono ad affrontarlo e continuano a prendersi in giro.

Non invidieresti un eroinomane, e come tutte le tossicodipendenze la tua non migliorerà. Ogni anno peggiorerà in modo esponenziale: se non ti piace essere un consumatore oggi, ti piacerà ancora meno domani. Non invidiare gli altri consumatori, compatiscili. Credimi: ***Hanno bisogno della tua pietà!***
