# Posso compartimentare?

Questo mito è diffuso soprattutto dagli utenti che cercano di smettere con il metodo della forza di volontà, che fanno ginnastica mentale e iniziano una routine alla Jekyll e Hyde: "*Il porno è per il mio alter ego e le storie d'amore della vita reale sono per il mio lato relazionale*". Non c'è niente di più sbagliato: gli scivoli d'acqua del porno, il DeltaFosB e i cambiamenti neurologici stanno per sopraffare il romanticismo della vita reale, rendendolo meno desiderabile. Mr. Hyde sta per annullare le istruzioni del Dr. Jekyll.

Se utilizzi il porno su Internet, ti stai allenando per il ruolo di voyeur o per avere la possibilità di cliccare su qualcosa di più eccitante al minimo calo dei livelli di dopamina. Oppure, la ricerca continua della scena giusta per ottenere il massimo effetto. Inoltre, potresti masturbarti in una posizione ingobbita o star guardando il tuo smartphone a letto ogni notte, finendo per desiderare questi spunti più degli stimoli della vita reale. Il sesso va contro quasi tutti gli aspetti dell'harem online, quindi non ha alcuna possibilità di essere confrontato. I ricordi creati quando si è giovani sono potenti e duraturi, quindi per smontare gli scivoli pornografici e ricablarli o crearne di nuovi ci vuole più tempo. Tuttavia, questo non significa che sia più difficile.

Ogni volta che si sale sullo "scivolo del porno" lo si lubrifica, mantenendo i nervi freschi e pronti a scattare. Quando si parcheggia accanto a un fast food, l'odore della friggitrice entra nelle narici e la vendita è già fatta. Allo stesso modo, gli scivoli porno nel vostro cervello sono pronti per essere ri-attivati e sono aperti ventiquattro ore al giorno. Ogni spunto o innesco accende il vostro circuito di ricompensa con la promessa di sesso, solo che non si tratta di sesso. Tuttavia, le cellule nervose solidificano queste associazioni con l'eccitazione sessuale facendo germogliare nuovi rami per rafforzare le connessioni. Più si usa il porno, più le connessioni nervose diventano forti. Il risultato finale è che alla fine si può avere *bisogno* di essere un voyeur, di cliccare su materiale sempre nuovo e crescente, di avere bisogno del porno per addormentarsi o di cercare il finale perfetto per finire il lavoro.

Come per qualsiasi sostanza o farmaco comportamentale, il corpo sviluppa un'immunità e la droga cessa di alleviare completamente le crisi di astinenza. Non appena l'utente chiude una sessione, ne vuole un'altra e in fretta, la fame permanente rimane insoddisfatta. L'inclinazione naturale è quella di aumentare il consumo per ottenere la scarica di dopamina. Tuttavia, la maggior parte degli utenti è impossibilitata a farlo per uno o entrambi i seguenti motivi.

**Soldi:** Non possono permettersi di abbonarsi a siti porno a pagamento.

**Salute:** il corpo non può sopportare più di tanto, né i picchi di dopamina né gli orgasmi. Inoltre, gli orgasmi innescano sostanze chimiche per ridurre il flusso di dopamina. Deve farlo, è così che funziona il corpo.

Una volta che il piccolo mostro lascia il corpo, la terribile sensazione di insicurezza finisce. Ritorna la fiducia in se stessi, insieme a una meravigliosa sensazione di rispetto per se stessi, ottenendo la certezza di prendere il controllo della propria vita e di usarla come trampolino di lancio per affrontare altri problemi. Questo è uno dei tanti grandi vantaggi di liberarsi da qualsiasi dipendenza.

Il mito della compartimentazione è uno dei tanti trucchi che il piccolo mostro gioca con la vostra mente. Questi trucchi rendono più difficile smettere - a causa dell'impossibile soddisfazione della fame permanente - inducendo molti consumatori a ricorrere alle sigarette, al bere pesante o a droghe ancora più pesanti per soddisfare il vuoto.

Gli esseri umani sono animali da rating, sia verso loro stessi che verso gli altri. Guardare un porno con il proprio partner è insoddisfacente, perché entrambi valutano le prestazioni dell'altro rispetto alla narrazione. Volete Brad Pitt nella vostra camera da letto, anche se è su un poster? Nessuna persona può eguagliare un harem in cui ogni "esperienza" è recitata, sceneggiata, diretta da professionisti e immediatamente disponibile ventiquattro ore al giorno.
