# Evita falsi incentivi

Molti utenti del metodo della forza di volontà cercano di aumentare la loro motivazione attraverso la costruzione di falsi incentivi. Ci sono molti esempi di questo tipo, uno tipico è quello di premiarsi con dei regali dopo aver evitato di guardare porno per un mese. Questo sembra un approccio logico e sensato, ma in realtà è falso, perché qualsiasi utente che si rispetti preferisce continuare a guardare porno ogni giorno piuttosto che premiarsi con un regalo fatto da sé. Questo genera un dubbio nella mente dell'utente, perché non solo dovrà astenersi per *trenta giorni*, ma non è nemmeno sicuro di *godersi* i giorni senza porno. Il loro unico piacere o sostegno è stato tolto! Tutto ciò non fa altro che aumentare la dimensione del sacrificio che l'utente sente di fare, ora sempre più prezioso nella sua mente.

Altri esempi sono:

- Smetterò perché mi costringa a farmi una vita sociale e a fare più sesso vero.

- Smetterò perché un'energia magica mi aiuti a superare i concorrenti e ad ottenere il partner che desidero.

- Smetterò per impegnarmi a non sprecare le mie energie e il mio entusiasmo con il porno, per far crescere la fame in me stesso.

Queste frasi sono vere, possono essere efficaci e potresti finire per ottenere ciò che vuoi, ma pensaci un attimo. Se otterrai ciò che desideri, una volta passata la novità ti sentirai privato; se non lo otterrai, ti sentirai infelice. In ogni caso, prima o poi cadrai di nuovo nella stessa trappola.

Collegare l'abbandono a un falso incentivo non fa che aumentare i dubbi, perché se non si ottiene l'incentivo (e anche se lo si ottiene) si iniziano a fare pensieri dubbiosi del tipo: "*L'abbandono migliorerà davvero la mia vita? Se smetto e non ottengo ciò che voglio, ho usato il metodo correttamente?*". Pensieri di questo tipo aumentano il senso di sacrificio e quindi creano le frustrazioni.

Un altro esempio tipico sono i patti online o sui forum, che hanno il vantaggio di eliminare le tentazioni per alcuni periodi. Tuttavia, in genere falliscono per i seguenti motivi:

1.  L'incentivo è falso: perché mai si dovrebbe smettere solo perché gli altri lo fanno? Tutto ciò che si ottiene è generare ulteriore pressione e aumentare la sensazione di sacrificio. Va bene se tutti gli utenti vogliono veramente smettere in un determinato momento, ma non si può costringerli a smettere, anche se tutti lo vogliono segretamente. Finché non sono pronti a farlo, un patto crea un'ulteriore pressione, che non fa che aumentare il loro desiderio di guardare. Questo li trasforma in spettatori segreti, aumentando ulteriormente il senso di dipendenza.

2.  La dipendenza reciproca con il metodo della forza di volontà genera il sentimento di sottoporsi a un periodo di penitenza, durante il quale si aspetta che lo stimolo scompaia. Se si cede, si prova un senso di fallimento. Quando si utilizza il metodo della forza di volontà, almeno uno dei partecipanti è destinato a rinunciare, fornendo agli altri partecipanti la scusa che stavano aspettando. Non è colpa loro, avrebbero resistito ma "Fred" li ha delusi. La verità è che la maggior parte di loro ha già barato.

3.  Condividere il merito è il contrario della dipendenza. Smettere di usare porno dà un meraviglioso senso di realizzazione e, quando lo si fa da soli, il plauso degli amici e dei compagni online può essere un'enorme spinta nei primi giorni. Tuttavia, quando tutti lo fanno contemporaneamente, il merito deve essere condiviso e la spinta si riduce di conseguenza.

4.  Un altro esempio classico è la promessa del guru. Smettere ti darà felicità perché non sei più impegnato nel tiro alla fune, il tuo cervello inizia a ricablarsi e a recuperare il controllo degli impulsi. Tuttavia, devi tenere presente che questo non ti farà diventare un Dio del sesso o vincere la lotteria. A nessuno, a parte voi, interessa minimamente che smettiate di fare porno. Non sei una persona debole se fai uso di porno tre volte al giorno e hai la PIED, né una persona forte se sei dipendente e non ce l'hai.

Smettila di prenderti in giro. Se l'offerta di dieci mesi di lavoro per dodici mesi di stipendio all'anno, o il rischio di ridurre la capacità del vostro cervello di far fronte allo stress e alle tensioni quotidiane, o il rischio di avere un'erezione affidabile, o la vita di torture mentali e fisiche e di schiavitù non ti hanno fermato, i pochi incentivi fasulli di cui sopra non faranno la minima differenza, riuscendo solo a far sembrare il sacrificio peggiore. Concentrati invece sull'altro lato:

"Cosa ci guadagno? Perché ho bisogno di guardare il porno?"

Continua a guardare l'altro lato del tiro alla fune e chiediti cosa sta facendo il porno per te. Perché ho bisogno di farlo? *NON NE HAI BISOGNO!* È la scommessa di Pascal: non hai quasi nulla da perdere (eccitazione che si affievolisce), possibilità di grandi guadagni (eccitazione piena e affidabile, benessere mentale e felicità) e nessuna possibilità di perdere molto.

Perché allora non dichiarare il tuo abbandono ad amici e familiari? Beh, questo ti renderà un orgoglioso ex-tossicodipendente o ex-utente, non un non-utente euforico e felice. Potrebbe spaventare un po' il tuo partner, che potrebbe vederlo come un piano per fare più sesso, in un modo un po' new-age. Potrebbero anche temere che vi trasformiate in una macchina del sesso, è difficile da spiegare se non hanno una mentalità aperta.

Ogni tentativo di farsi aiutare da altri a smettere dà più potere al piccolo mostro. Scacciarlo dalla mente e ignorarlo completamente ha l'effetto di cercare di *non* pensarci. Siate invece attenti, non appena individuate i pensieri, gli spunti (a casa da soli) o i pensieri distratti, dite a voi stessi *"Fantastico, non sono più schiavo del porno. Sono libero e felice di conoscere le differenze nel sesso!"* Questo taglierà l'ossigeno al pensiero e gli impedirà di dirigersi verso gli impulsi e le voglie. A questo proposito, la pratica della meditazione mindfulness può essere utile per aiutare la depersonalizzazione dei pensieri stessi.
