# Il modo più semplice per smettere

Questo capitolo contiene istruzioni sul modo più semplice per smettere di usare il porno. Se segui le istruzioni, scoprirai che smettere è relativamente facile e piacevole! Se segui le istruzioni che seguono, smettere di usare il porno è ridicolmente facile: tutto ciò che devi fare sono due cose.

1.  Decidere che non guarderai mai più un film porno.

2.  Non deprimerti per questo. Rallegrati.

Probabilmente vi starete chiedendo: "*Perché c'è bisogno del resto del libro? Perché non potevi dirlo fin dall'inizio?*". Beh, la risposta è che alla fine ci avresti rimuginato sopra e di conseguenza avresti cambiato la tua decisione. Probabilmente l'hai già fatto molte volte.

Come già detto, la pornografia è una trappola sottile e sinistra. Il problema principale dell'interruzione non è la dipendenza da dopamina - che è certamente un problema, ma non il principale - ma il lavaggio del cervello. Pertanto, è necessario distruggere prima tutti i miti e le illusioni. Capisci il tuo nemico, conosci le sue tattiche e lo sconfiggerai facilmente. Avendo passato gran parte della mia vita a soffrire di depressione nera mentre cercavo di smettere, quando finalmente sono riuscito a fuggire, sono passato direttamente a zero senza un momento negativo. È stato piacevole anche durante il periodo di astinenza e da allora non ho mai avuto il minimo dolore. Al contrario, è stata una delle cose più belle che mi siano capitate nella vita.

Il mio ultimo tentativo è stato diverso. Come tutti gli utenti di oggi, avevo pensato seriamente al problema. Fino ad allora, dopo aver fallito, mi consolavo pensando che la prossima volta sarebbe stato più facile. Non mi era mai venuto in mente che avrei dovuto continuare così per il resto della mia vita, questo pensiero mi riempì di orrore e cominciai a riflettere molto profondamente sull'argomento.

Invece di accendere il browser inconsciamente, ho analizzato i miei sentimenti e ho confermato ciò che già sapevo. Il porno non mi piaceva e lo trovavo sporco e disgustoso. Ho iniziato a guardare i non utenti che vivevano in altre parti del mondo o le persone più anziane che non avevano mai conosciuto i siti di tube. Fino a quel momento avevo sempre considerato i non utenti come persone svagate, asociali e schizzinose. Tuttavia, esaminandoli quando apparivano, sembravano, se non altro, più forti e rilassati. Sembravano in grado di affrontare lo stress e le tensioni della vita e sembravano godere delle funzioni sociali più dei consumatori di porno. Di certo avevano più brio e più entusiasmo di loro.

Iniziai a parlare con gli ex-utenti. Fino a quel momento li avevo sempre considerati costretti a smettere per motivi di salute o religiosi e avevano sempre desiderato segretamente una visita all'harem. Alcuni mi dissero: *"Ti capita di avere qualche fitta, ma sono così poche che non vale la pena di preoccuparsene"*. La maggior parte invece mi disse: *"Ti manca? Stai scherzando! La vita non è mai stata così bella!"* Anche i fallimenti erano per loro delle cadute, ma non si condannavano e anzi si accettavano incondizionatamente. Come un allenatore che accetta un errore di un giocatore veramente d'oro. Parlare con gli ex-utenti ha distrutto un altro mito che avevo sempre avuto nella mia mente, ovvero che ci fosse una debolezza intrinseca in me, finché non mi sono reso conto che tutti passano attraverso questo incubo in privato.

In sostanza, mi sono detto: *"Migliaia di persone stanno smettendo ora e conducono una vita perfettamente felice, io non ne ho avuto bisogno prima di iniziare e ricordo di aver dovuto lavorare sodo per abituarmi a questo schifo.* In ogni caso, non mi piaceva il porno, odiavo l'intero sporco rituale e non volevo passare il resto della mia vita in schiavitù di questa disgustosa dipendenza. Allora mi sono detto questo:

*"Che ti piaccia o no, hai completato la tua ultima sessione"*.

Da quel momento ho capito che non avrei mai più avuto un'altra seduta. Non mi aspettavo che fosse facile, ma il contrario. Ero pienamente convinto di aver firmato per mesi di depressione nera e di passare il resto della mia vita con qualche dolore occasionale. Invece, è stata una beatitudine assoluta fin dall'inizio.

Mi ci è voluto molto tempo per capire perché fosse così facile e perché non avessi sofferto di quelle terrificanti crisi di astinenza. Il motivo è che non esistono, sono il dubbio e l'incertezza a creare le crisi. La bella verità è che è facile smettere con il porno, sono solo l'indecisione e il rimuginio a renderlo difficile. Anche quando si è dipendenti, si può fare a meno del porno per periodi relativamente lunghi. È solo quando lo si desidera, ma non lo si può avere, che si soffre.

Pertanto, la chiave per rendere la cosa più facile è rendere la cessazione certa e definitiva. Non sperare, ma *sapere* di averla abbandonata, di aver preso la decisione. Non bisogna mai dubitare o mettere in discussione la decisione, anzi, è proprio il contrario: bisogna sempre gioire! Se si riesce a esserne certi fin dall'inizio, sarà facile. Ma come si può essere certi fin dall'inizio? Ecco perché il resto del libro è necessario. Ci sono alcuni punti essenziali che devono essere chiari nella tua mente prima di iniziare:

1.  Renditi conto che puoi farcela. Non c'è nulla di diverso in te e l'unica persona che può farti guardare un video sei tu stesso. Non quella pornostar, che nei suoi sogni più sfrenati non ha mai pensato di essere usata per ridurre la tua virilità.

2.  Non c'è assolutamente nulla a cui rinunciare. Al contrario, si possono ottenere enormi guadagni positivi. Non solo sara più sano e più ricco, ma godrai di più dei momenti belli e sarai meno infelice in quelli brutti.

3.  Non esistono cose come una sbirciatina o una visita. La pornografia è una tossicodipendenza e una reazione a catena, lamentandoti per le visite occasionali non farai altro che punirti inutilmente.

4.  Considera il porno non come un'abitudine che potrebbe ferirti, ma come una tossicodipendenza. Affronta il fatto che, che ti piaccia o no, hai la malattia, che non sparirà perché nascondi la testa sotto la sabbia. Ricorda che, come tutte le malattie invalidanti, non solo dura per tutta la vita, ma peggiora esponenzialmente. Il momento più facile per curarla è adesso.

5.  Separa la malattia - la dipendenza neurologica - dalla mentalità di essere o meno un consumatore. Tutti i consumatori, se avessero l'opportunità di tornare indietro nel tempo prima della dipendenza, la coglierebbero al volo. Oggi hai questa opportunità! Non pensare nemmeno che si tratti di una "rinuncia".

Quando deciderai di aver fatto la tua ultima visita, sarai già un non-utente. Un utente è uno di quei poveri disgraziati che si distruggono la vita con il porno. Un non utente è una persona che non lo fa. Una volta presa questa decisione finale, hai già raggiunto il tuo obiettivo. Rallegrati di questo fatto, non stare seduto a deprimerti e ad aspettare che la dipendenza chimica se ne vada. Esi e goditi subito la vita. La vita è meravigliosa anche quando si è dipendenti e ogni giorno sarà molto migliore quando non lo si sarà più.

La chiave per facilitare lo smettere è essere certi di riuscire ad astenersi completamente durante il periodo di astinenza (massimo tre settimane). Se sei nello stato d'animo giusto, vi risulterà incredibilmente facile.

A questo punto, se hai aperto la mente come richiesto all'inizio, avrai già deciso di fuggire. Dovresti provare un sentimento di eccitazione, come un cane che tende il guinzaglio e non vede l'ora di rompere gli scivoli DeltaFosB del porno. Se hai una sensazione di tristezza, sarà per uno dei seguenti motivi:

1.  Qualcosa non ha funzionato nella tua mente. Rileggi i cinque punti precedenti e chiediti se li ritieni veri. Se dubiti di qualche punto, rileggi le sezioni appropriate del libro.

2.  Temi il fallimento in sé. Non preoccuparti, continua a leggere e avrai successo. L'intero business del porno su Internet è un trucco di fiducia di dimensioni gigantesche. Le persone intelligenti cadono nei trucchi di fiducia, ma solo uno sciocco, una volta scoperto il trucco, continua a prendersi in giro.

3.  Sei d'accordo con tutto ma sei ancora infelice. Non fatelo! Apri gli occhi, sta accadendo qualcosa di meraviglioso. Stai per evadere dalla prigione, è essenziale iniziare con il giusto stato d'animo: *"È meraviglioso che io sia un non-utente!"*.

L'unica cosa da fare ora è mantenere questo stato d'animo durante il periodo di astinenza, e i prossimi capitoli trattano i punti specifici che ti permetteranno di farlo. Dopo il periodo di astinenza non dovrai più pensare in questo modo, lo farai automaticamente e l'unico mistero nella tua vita sarà il motivo per cui non l'hai capito prima. Tuttavia, due importanti avvertenze.

-   Rimanda l'ultima visita a quando avrai finito il libro.

-   È stato più volte menzionato un periodo di astinenza di tre settimane, che può causare malintesi. In primo luogo, potresti pensare inconsciamente di dover soffrire per tre settimane. Non è così. In secondo luogo, evita la trappola di pensare *"In qualche modo devo astenermi per tre settimane e poi starò bene"*. In realtà, dopo tre settimane non accadrà nulla di magico, non ti sentirai improvvisamente come un non consumatore, perché in realtà non si sentono diversi dai consumatori. Se durante le tre settimane ti lamenti per aver smesso, con ogni probabilità lo farai anche dopo le tre settimane. Riassumendo, se si inizia subito dicendo *"Non lo farò mai più, non è meraviglioso?"*, dopo tre settimane la tentazione svanirà. Mentre se dici: *"Se solo riuscissi a sopravvivere a queste tre settimane senza porno"*, dopo le tre settimane morirai dalla voglia di visitare un harem.

Vedila in questo modo: il tuo cervello vuole mantenere lo status quo, quindi se sei convinto di perdere qualcosa di buono quando smetti, ovviamente ti sentirai malissimo. È impossibile costringersi a sentirsi in un certo modo se il cervello non ci crede. Ecco perché è importante eliminare l'illusione che la pornografia ti dia qualcosa. È così che si sa che non si sta sacrificando nulla.

Le disfunzioni sessuali hanno molto a che fare con il cervello e la struttura mentale. Il porno su Internet ricrea il circuito di ricompensa del cervello e instaura una mentalità di "dubbio". Questo dubbio provoca disfunzioni sessuali. Puoi avere tutto il desiderio a livello mentale, ma non potrai eccitare la parte bassa. Ti assicuro che è la cosa peggiore che possa capitare alla tua mentalità. La libido che va di pari passo con il romanticismo è l'elisir di giovinezza migliore che potrai avere fino alla morte. Smettendo di usare il porno manterrai alte le probabilità di ottenere questo elisir, ma questo non è l'unico o il principale guadagno. È la tua libertà dalla schiavitù!
