# Il periodo di astinenza

Per un massimo di tre settimane dopo l'ultima seduta si può essere soggetti a crisi di astinenza. Queste consistono in due fattori ben distinti ma separati:

1.  Fastidi da astinenza da dopamina. Una sensazione di vuoto e insicurezza simile alla fame, identificata come desiderio o sensazione di "qualcosa che devo fare".

2.  I fattori psicologici scatenati da alcuni stimoli esterni come la pubblicità, la navigazione online, le conversazioni telefoniche, ecc.

La mancata comprensione e differenziazione di questi due fattori distinti rende difficile raggiungere il successo con il metodo della forza di volontà ed è il motivo per cui molti di coloro che ci riescono finiscono per cadere nuovamente nella trappola. Anche se le crisi di astinenza da dopamina non provocano dolore fisico, non bisogna sottovalutare il loro potere. Si parla di "dolori della fame" quando si sta senza cibo per un giorno; ci possono essere dei brontolii allo stomaco, ma non c'è alcun dolore fisico. Tuttavia, la fame è una forza potente ed è probabile che diventiamo molto irritabili quando siamo privati del cibo. È simile a quando il nostro corpo desidera una scarica di dopamina, con la differenza che il nostro corpo ha bisogno di cibo, non di veleno. Con il giusto stato d'animo, le crisi di astinenza sono facilmente superabili e scompaiono molto rapidamente.

Dopo un'astinenza di qualche giorno con il metodo della forza di volontà, il desiderio di vampate di dopamina scompare presto. È il secondo fattore, il lavaggio del cervello, a creare difficoltà. L'utente ha preso l'abitudine di alleviare le proprie crisi di astinenza in determinati momenti e occasioni, il che provoca un'associazione di idee (*"Ho un'erezione, quindi devo guardare un porno"* o *"Sono a letto con il mio portatile e devo fare una sessione per sentirmi felice*"). L'effetto è meglio illustrato con un esempio: Avete un'auto e l'indicatore di direzione è a destra, ma sulla vostro nuova auto è a sinistra Sapete che è a sinistra, ma per un paio di settimane accendete i tergicristalli quando volete girare.

Anche le soste sono simili: nei primi giorni il meccanismo di attivazione si attiva in determinati momenti. Si penserà di volere una seduta, quindi contrastare il lavaggio del cervello è essenziale fin dal primo momento e farà sì che questi spunti e fattori scatenanti scompaiano rapidamente. Con il metodo della forza di volontà, l'utente, credendo di fare un sacrificio, si deprime e aspetta che gli impulsi se ne vadano; lungi dall'eliminare questi meccanismi scatenanti, li aumenta. Allo stesso modo, con il metodo del guru thinking, l'utente inizia a chiedersi quando diventerà un Dio e pretende addirittura di non avere questi pensieri, aprendo la strada al disgusto di sé e al fallimento.

Un fattore scatenante comune è il tempo trascorso da soli, in particolare durante gli eventi sociali con gli amici. L'ex consumatore che utilizza altri metodi per smettere è già infelice perché si sente privato del suo sostegno o del suo piacere abituale. I suoi amici sono con i loro partner e si comportano in modo intimo. L'utente è single o non "riceve" nulla dal partner e non si gode più quella che dovrebbe essere una piacevole occasione sociale. I suoi scivoli cerebrali lo portano al porno, che è più facile del tentativo di corteggiare il partner.

A causa dell'associazione del diritto al sesso con il loro benessere, ora sta subendo un triplo colpo e il lavaggio del cervello è di fatto aumentato. Se è risoluto e riesce a resistere abbastanza a lungo, alla fine accetta la sua sorte e va avanti con la sua vita. Tuttavia, una parte del lavaggio del cervello rimane, il secondo aspetto più patetico è che l'utente ha smesso, ma anche dopo diversi anni desidera ancora "solo un'ultima visita all'harem" in certe occasioni. Si strugge per un'illusione che esiste solo nella sua mente e si tortura inutilmente.

Anche con EasyPeasy, la risposta ai fattori scatenanti è il fallimento più comune. L'ex utente tende a considerare il porno su Internet come una sorta di placebo o pillola di zucchero. Pensando: "*So che il porno non fa nulla per me, ma se penso che lo faccia allora in certe occasioni mi sarà utile*". Una pillola di zucchero, anche se non dà alcun aiuto fisico effettivo, può essere un potente aiuto psicologico per alleviare i sintomi reali ed è quindi benefica. Il porno su Internet e la masturbazione abituale, tuttavia, non sono pillole di zucchero. Perché? Il porno crea i sintomi che allevia e cessa di alleviarli completamente.

Può essere più facile capire l'effetto se lo si mette in relazione con un non consumatore o con un consumatore di successo che ha smesso da diversi anni. Prendiamo il caso di un utente che perde il proprio partner: in questi momenti è abbastanza comune, con le migliori intenzioni, dire: "*Fai una visita all'harem, ti aiuterà a calmarti*". Se l'offerta viene accettata, non avrà un effetto calmante perché non c'è dipendenza da dopamina e quindi non ci sono crisi di astinenza. Nel migliore dei casi, l'unica cosa che farà è dare una spinta psicologica momentanea.

Anche dopo la fine della sessione, la tragedia originale è presente. Anzi, aumenterà perché la persona ora soffre di crisi d'astinenza, potendo scegliere se sopportarle o trovare sollievo ripetendo le corse sugli scivoli d'acqua per ricominciare la catena dell'infelicità. Tutto ciò che il porno forniva era un'effimera spinta psicologica, la stessa che si sarebbe potuta ottenere con un libro o un film piacevole, anche se brutto. Molti non consumatori o ex consumatori sono diventati nuovamente dipendenti a seguito di queste occasioni. Mettetelo bene in chiaro nella vostra mente: Non avete bisogno della scarica di dopamina e vi state solo torturando ulteriormente continuando a considerarla come una sorta di sostegno o di spinta. Non c'è bisogno di essere infelici.

Gli orgasmi non creano buone relazioni, anzi, il più delle volte le rovinano. Ricordate anche che non è del tutto vero che chi fa dimostrazioni di affetto in pubblico gode in ogni occasione. L'intimità è meglio goduta in privato, dove i partner possono rispondere senza imbarazzo, non è necessario essere dipendenti dalla dopamina indotta dall'orgasmo. Se accade come risultato naturale di una serie di eventi della vita, va bene, ma godetevi l'occasione e la vita senza di essa.

Dopo aver abbandonato il concetto di porno come piacere in sé, molti utenti pensano: "*Se solo esistesse un porno pulito su Internet*". Il porno soft pulito esiste, e chi lo prova scopre presto che è una perdita di tempo. Metti in chiaro nella tua mente che l'unico motivo per cui stai usando il porno è la voglia di dopamina. Una volta eliminata la voglia di porno, non avrai più bisogno di visitare il tuo harem online.

Che i dolori siano dovuti a veri e propri sintomi di astinenza da dopamina o a meccanismi di innesco/spinta, accettateli. Il dolore fisico è inesistente e con il giusto stato d'animo non sarà un problema. Non preoccuparti dell'astinenza, la sensazione in sé non è negativa. Il problema è l'associazione con il desiderio e la sensazione di essere negati. Invece di rimuginarci sopra, riconoscilo: "*So cos'è, è la sensazione di astinenza da porno. È quello di cui soffrono gli utenti per tutta la vita e che li rende dipendenti. Chi non ne fa uso non soffre di questi dolori, è un altro dei tanti mali di questa dipendenza bugiarda. Non è meraviglioso che io stia eliminando questo male dal mio cervello?*".

In altre parole, per le prossime tre settimane avrai un leggero trauma all'interno del vostro corpo, ma durante queste settimane e per il resto della tua vita accadrà qualcosa di meraviglioso. Ti libererai di una terribile malattia, i cui vantaggi superano di gran lunga il leggero trauma, e godrai delle crisi di astinenza. Diventeranno momenti di piacere, come un gioco eccitante per affamare il verme della cassetta pornografica che vive nel tuo stomaco. Devi farlo morire di fame per tre settimane, mentre cerca di ingannarti per portarti a letto e tenervi in vita.

A volte, cercherà di renderti infelice. A volte, sarai colto di sorpresa. Riceverai un URL porno o ti imbatterai in qualcosa online e dimenticherai di aver smesso, con una leggera sensazione di privazione quando te ne ricorderai. Preparati a questi trucchi in anticipo e, qualunque sia la tentazione, mettiti in testa che è lì solo a causa del mostro che hai dentro il corpo e che ogni volta che resisti alla tentazione avrai dato un altro colpo morale alla battaglia.

Qualunque cosa tu faccia, non cercare di dimenticare il porno. Questa è una delle cose che provoca nei PMO che utilizzano il metodo della forza di volontà ore di depressione. Cercano di superare ogni giorno sperando che alla fine se ne dimenticheranno. È come non riuscire a dormire: più ci si preoccupa, più diventa difficile. In ogni caso, non riuscirai a dimenticartene, per i primi giorni il "piccolo mostro" continuerà a ricordartelo e non riuscirai a evitarlo. Ci sono ancora computer portatili, smartphone e riviste in giro, avrai continui promemoria.

Il punto è che non c'è bisogno di dimenticare, non sta succedendo nulla di male. Anzi, sta accadendo qualcosa di meraviglioso e meraviglioso e anche se ci pensi mille volte al giorno, **assapora ogni momento, ricorda a te stesso quanto sia meraviglioso essere di nuovo liberi. Ricorda a te stesso la pura gioia di non doverti più torturare** Come detto in precedenza, scoprirai che i dolori diventano momenti di piacere, sorprendendoti della rapidità con cui dimenticherai il porno.

Qualunque cosa tu faccia, *non dubitare della tua decisione*. Se inizi a dubitare, inizierai a deprimerti e la situazione peggiorerà. Invece, sfrutta quel momento di sconforto e trasformalo in una spinta. Se la causa è la depressione, ricordati che il porno la stava *causando*. Se un amico ti inoltra un URL, sii orgoglioso di dire: "*Sono felice di dire che non ne ho più bisogno*". Questo li ferirà, ma quando vedranno che non ti dà fastidio saranno a metà della strada per unirsi a voi.

**Ricorda: hai ragioni incredibilmente valide per smettere fin dall'inizio.** Ricorda a te stesso i costi e chiediti se vuoi davvero rischiare il malfunzionamento del tuo corpo, della tua mente e il semplice fatto che vivrai sotto un incantesimo per il resto della tua vita. Fai attenzione agli sforzi del mostriciattolo per ridurre al minimo i pericoli e soprattutto ricorda che la sensazione è solo temporanea e ogni momento è un momento più vicino alla meta.

Alcuni utenti temono di dover passare il resto della loro vita a invertire i "trigger automatici". In altre parole, credono di dover passare la vita a illudersi di non aver bisogno del porno attraverso l'uso della psicologia. Non è così, ricorda che l'ottimista vede la bottiglia mezza piena e il pessimista mezza vuota. Nel caso della pornografia, la bottiglia è vuota e l'utente la vede piena. Non ci sono vantaggi nell'uso del porno su Internet. È l'utente che ha subito il lavaggio del cervello per pensare che ci siano. Una volta che inizi a dire a te stesso che non hai bisogno o che non vuoi il porno, in breve tempo non avrai nemmeno più il bisogno di dirlo, vedendo da te stesso la bellissima verità. Assicurati che vedere che non c'è niente di buono nel porno non sia l'ultima cosa che fai.
