# Solo una piccola sbirciatina

Questa è la rovina di molti dei quali utilizzano il metodo della forza di volontà. Passano tre o quattro giorni e poi si concedono qualche sbirciatina per tirare avanti. Non si rendono conto dell'effetto devastante che questo ha sul loro morale.

Per la maggior parte degli utenti, la prima sbirciatina al sito tube harem non è stata all'altezza del sesso con una persona reale. Le clip "safe" sono molto rare e questo dà alla loro mente una spinta. Pensano: "*Bene, non è stato poi così piacevole. Mi sta passando la voglia e non mi piacciono le cose sconvolgenti"*. In realtà, è vero il contrario. Mettiti in testa che il piacere dell'orgasmo non era il motivo per cui avete smesso con il porno. Se gli utenti fossero lì solo per l'orgasmo, non guarderebbero mai più di un filmato. L'unico motivo per cui avevi bisogno del porno era nutrire quel piccolo mostro. Pensa, dopo essere stati affamati per quattro giorni, quanto deve essere stata preziosa per lui quell'unica sbirciatina. La tua mente cosciente non ne è consapevole, ma la spinta che il tuo corpo ha ricevuto viene comunicata al tuo subconscio, e tutta la tua solida preparazione sarà compromessa. Una vocina in fondo alla mente ti dirà che, nonostante tutta la logica, le sedute sono preziose e che ne volete un'altra.

Questa piccola voce ha due effetti dannosi:

1.  Mantiene vivo il piccolo mostro nel tuo corpo.

2.  Peggio ancora, mantiene vivo il grande mostro nella tua mente. Se hai dato l'"ultima sbirciatina", sarà più facile che avvenga la prossima.

Il porno è una trappola per topi senza formaggio, solo veleno. Con la forza di volontà devi convincerti a non prendere il formaggio, ma EasyPeasy ti permette di vedere che è veleno. Non è necessario evitarla, basta non entrarci.

Soprattutto, ricorda:

*"Una sola sbirciatina" è il modo in cui le persone entrano in una dipendenza*".
