# Sarà difficile per me?
Esistono infinite combinazioni di fattori che determinano la facilità con cui ogni singolo utente smetterà. Per cominciare, ognuno di noi ha il proprio carattere, la propria carriera, le proprie circostanze personali, il proprio tempismo, metabolismo, ecc. Alcune professioni possono renderlo più difficile di altre, ma a condizione che il lavaggio del cervello venga rimosso, non deve essere così. Prendi i seguenti pochi esempi.

Occasionalmente, è difficile per i membri della professione medica. Pensiamo che dovrebbe essere più facile per i medici perché sono più consapevoli degli effetti ma, anche se questo fornisce ragioni più valide per fermarsi, non lo rende più facile da realizzare. Le ragioni sono le seguenti:

1. La costante consapevolezza dei rischi per la salute crea paura, una delle condizioni in cui dobbiamo alleviare i morsi dell'astinenza.

2. Il lavoro di un medico è estremamente stressante e di solito non è in grado di alleviare lo stress aggiuntivo dei dolori di astinenza durante il lavoro.

3. Hanno lo stress aggiuntivo del senso di colpa, sentendo che dovrebbero essere un esempio per il resto della popolazione. Questo mette più pressione su di loro e aumenta la sensazione di privazione.

Dopo una dura giornata di lavoro in cui il loro stress è momentaneamente alleviato dal porno, quella sessione diventa erroneamente collegata al sollievo provato. A causa di questa errata associazione di idee, il porno ottiene il merito dell'intera situazione, diventando improvvisamente molto prezioso dopo aver smesso e attraversato i morsi dell'astinenza. Si tratta di una forma di utenza occasionale e si applica a qualsiasi situazione in cui l'utente sia costretto ad astenersi per lunghi periodi. Con il metodo della forza di volontà, l'utente è infelice perché viene privato e non gode della stanchezza e del sonno che arrivano dopo una sessione. Il loro senso di perdita è notevolmente aumentato. Tuttavia, se riesci prima a rimuovere il lavaggio del cervello e il deprimerti riguardo al porno, la pausa e il sonno possono ancora essere goduti anche mentre il corpo brama i trasmettitori amminici: serotonina, norepinefrina e dopamina.

Un'altra situazione difficile è la noia, in particolare se combinata con periodi di stress. Esempi tipici sono studenti e genitori single, il lavoro è stressante ma monotono. Durante un tentativo di fermare il metodo della forza di volontà, la singola persona ha lunghi periodi in cui deprimersi per la propria "perdita", che a sua volta aumenta i sentimenti di depressione. Ancora una volta, questo può essere facilmente superato se il tuo stato d'animo è corretto. Non preoccuparti se ti viene continuamente ricordato che hai interrotto il porno. Usa questi momenti per rallegrarti del fatto che ti stai liberando del mostro malvagio.

Se hai uno stato d'animo positivo, questi dolori diventeranno momenti di piacere. Ricorda, qualsiasi utente indipendentemente dall'età, dal sesso, dall'intelligenza o dalla professione può trovare facile e divertente smettere se **segue tutte le istruzioni.**

## Motivi principali per il fallimento

Ci sono due ragioni principali per il fallimento. Il primo è l'influenza dello stimolo esterno: una pubblicità, un articolo di notizie online, la navigazione in Internet, ecc. Gli utenti si trovano in un momento di debolezza o addirittura diventano gelosi quando vedono l'intimità negli scenari sociali. Questo argomento è già stato discusso a lungo. Usa il momento per ricordare a te stesso che non esiste una visita o una sbirciatina. Rallegrati del fatto che hai spezzato la catena della schiavitù mentale. Ricorda che l'utente ti invidia e che dovresti provare pietà per loro, perché ne hanno bisogno.

L'altro motivo è avere una brutta giornata. Metti in chiaro nella tua mente prima di iniziare che, che tu sia un utente o meno, avrai giorni buoni e giorni cattivi. Piove sia per il papa che per l'assassino. La vita è relativa e non puoi avere alti senza bassi. Il problema con il metodo della forza di volontà è che non appena l'utente ha una brutta giornata, inizia a deprimersi per una visita all'"harem", il che aggrava ulteriormente il problema. Il non utente è meglio equipaggiato per gestire stress e sforzi, non solo fisicamente ma anche mentalmente. Se hai una brutta giornata durante il periodo di astinenza, prendila in mano; ricordati che esistevano giorni brutti quando eri dipendente, altrimenti non avresti deciso di smettere. Invece di deprimerti, riconoscilo: *"Okay, oggi non è così bello ma il porno non lo cambierà la situazione. Domani andrà meglio e almeno ho un meraviglioso bonus, ho preso a calci quella terribile dipendenza."*

Quando sei un utente utilizzatore del porno, devi fissare la tua mente sugli aspetti negativi del porno. Gli utenti non hanno mai la nebbia del cervello, sono solo "un po' giù". Quando hai gli inevitabili problemi della vita e provi il pensiero di volere il porno, sei felice e allegro? Certo che no. Una volta che ti fermi, la tendenza è dare la colpa di tutto ciò che va storto al fatto che ti sei fermato.

Se il lavoro ti stressa, pensi: "*In momenti come questo avrei avuto una sessione.*" Questo è vero, ma la cosa importante che viene dimenticata è che il porno non ha risolto il problema, e tu stai semplicemente spingendoti  verso un appoggio illusorio. Stai creando una situazione impossibile, sei infelice perché non puoi masturbarti davanti al porno, ma se lo fai sarai ancora più infelice. *Sai che hai preso la decisione giusta interrompendola, quindi perché punirti mettendo in dubbio la tua decisione?*

Ricorda, un approccio mentale positivo è essenziale, sempre.