# Sostituti

Alcuni esempi di sostituti includono la limitazione a riviste porno, immagini Internet statiche, diete porno, ecc. **NON USARE NESSUNO DI ESSI.** Rendono il percorso più difficile, non più facile. Se provi una fitta e usi un sostituto, prolungherà solo la fitta, rendendola più dura. Quello che stai davvero dicendo è che hai bisogno del porno per riempire il vuoto. Sarà come cedere a un dirottatore o ai capricci di un bambino, prolungando la tortura. In ogni caso, i sostituti non allevieranno le fitte. Il tuo desiderio è per le ammine nel cervello, tutto ciò che farà è farti pensare al porno. Ricorda questi punti:

1.  Non c'è sostituto per il porno.

2.  Non hai bisogno del porno. Non è cibo, è veleno. Quando arrivano i dolori, ricorda a te stesso che sono gli utenti a soffrire di crisi di astinenza, non i non utenti. Guardali per quello che sono, un altro male della droga. Vedili come la morte di un mostro.

3.  Il porno su Internet crea il vuoto; non lo riempie. Prima insegni al tuo cervello che non hai bisogno di guardare, prima sarai libero. In particolare, evita qualsiasi cosa che assomigli al porno, come riviste, film, romanzi rosa e pubblicità. Questo non significa avere una mentalità chiusa, va bene parlare di romanticismo e sesso, ma non di porno. È vero che una piccola percentuale di utenti che tentano di smettere usando porno soft o "diete" hanno successo (dal loro punto di vista) e attribuiscono il loro successo a tale uso. Tuttavia, hanno smesso *nonostante* il loro uso e non a causa di esso. È un peccato che molti raccomandino ancora queste misure.

Questo non sorprende perché se non si comprende appieno la trappola pornografica, una dieta o un sostituto morbido sembrano molto logici. Si basa sulla convinzione che quando tenti di abbandonare il porno, hai due potenti nemici da sconfiggere:

-   Interrompere un'abitudine.

-   Sopravvivere a terribili rimorsi di astinenza fisica.

Se hai due potenti nemici da sconfiggere, è ragionevole non combatterli contemporaneamente ma uno alla volta. Quindi la teoria dice che quando smetti di usare il porno per la prima volta, riduci a una volta alla settimana o usi il porno sicuro. Quindi, una volta rotta l'abitudine, riduci gradualmente l'offerta, affrontando così ogni nemico separatamente.

Sembra logico ma si basa su informazioni errate. Il porno non è abitudine, ma dipendenza da dopamina, e l'effettivo dolore fisico da astinenza è quasi impercettibile. Quello che stai cercando di ottenere quando smetti è uccidere sia i mostri nel tuo corpo che nel tuo cervello il più rapidamente possibile. Tutte le tecniche di sostituzione non fanno altro che prolungare la vita del piccolo mostro, e questo a sua volta prolunga il lavaggio del cervello. EasyPeasy rende facile smettere immediatamente, eliminando il lavaggio del cervello prima della sessione finale. Il piccolo mostro sarà presto morto, e anche mentre sta morendo, non sarà più un problema di quanto lo fosse quando eri un utente.

Pensa, come puoi curare la dipendenza da una droga raccomandando la stessa droga? Ci sono molte storie online su coloro che hanno smesso di usare il porno hardcore su Internet, ma sono appassionati di alternative "sicure", essendosi innamorati delle giustificazioni del loro piccolo mostro. Non lasciarti ingannare dal fatto che il porno sicuro non è orribile, così come la prima clip. Tutti i sostituti hanno esattamente gli stessi effetti di qualsiasi porno. Alcuni iniziano persino a mangiare, ma sebbene la sensazione di vuoto di volere una sessione sia indistinguibile dalla fame di cibo, uno non soddisferà l'altro. In effetti, se c'è qualcosa progettato per farti desiderare il porno, è rimpinzarti di cibo. Come spiegato in precedenza, le diete porno e il porno sicuro ti metteranno solo nel mezzo del tiro alla fune, con la resistenza alla tentazione così fastidiosa che ti sentirai sollevato visitando il tuo harem online preferito.

Il male principale dei sostituti è prolungare il vero problema, il lavaggio del cervello. Hai bisogno di un sostituto per l'influenza quando sarà finita? Certo che no. Dicendo che hai bisogno di un sostituto del porno, in realtà stai dicendo che stai facendo un sacrificio. La depressione associata al metodo della forza di volontà è causata dal fatto che l'utente crede di fare un sacrificio. Tutto quello che farai è sostituire un problema con un altro. Non c'è piacere nel rimpinzarsi di cibo, sigarette o alcool. Diventerai solo grasso, miserabile e in men che non si dica tornerai a prendere la droga.

Gli utenti occasionali trovano difficile respingere la convinzione di essere stati privati della loro piccola ricompensa, come quelli a cui non è consentito andare sui siti durante un viaggio, un evento familiare, ecc. Alcuni dicono: "*Vorrei, non so come, rilassarmi e non saprei come farlo se non con il porno.*" Questo dimostra il punto, spesso la pausa viene presa non perché l'utente ne abbia bisogno o addirittura lo voglia, ma perché il tossicodipendente - che è quello che sono - disperatamente ha bisogno di grattarsi il prurito.

Ricorda, le sessioni porno non sono mai state vere ricompense. Equivalevano a indossare scarpe strette per avere il piacere di togliersele. Quindi, se ritieni di dover avere una piccola ricompensa, lascia che sia il tuo sostituto; mentre lavori indossa scarpe o biancheria intima di una taglia troppo piccola, e non permetterti di toglierle fino alla tua pausa, poi vivi il meraviglioso momento di relax e soddisfazione quando vengono tolte. Forse ritieni che sarebbe piuttosto stupido. Hai assolutamente ragione. Può essere difficile da visualizzare mentre si è ancora nella trappola, ma è quello che fanno gli utenti. È anche difficile immaginare che presto non avrai più bisogno di quella piccola "ricompensa" e che presto guarderai gli amici che sono ancora nella trappola con genuina pietà e ti chiederai perché non riescono a capire il punto.

Tuttavia, se continui a illuderti che la visita all'harem online sia stata una vera ricompensa o che hai bisogno di un sostituto, ti sentirai privato e infelice. È probabile che finirai per cadere di nuovo nella disgustosa trappola. Se hai bisogno di una vera pausa come fanno le casalinghe, gli insegnanti, i dottori e altri lavoratori, presto ti godrai ancora di più quella pausa perché non dovrai diventare dipendente da te stesso. Ricorda che non hai bisogno di un sostituto. I rimorsi sono un desiderio di dopamina e presto scompariranno. Lascia che questo sia il tuo sostegno per i prossimi giorni e divertiti a liberare il tuo corpo e la tua mente dalla schiavitù e dalla dipendenza.
