# Dovrei evitare le situazioni di tentazione

Finora il consiglio è stato diretto e ti ho chiesto di trattarlo come un'istruzione piuttosto che come un suggerimento. Ci sono valide ragioni pratiche per questo consiglio e quelle ragioni sono state sostenute da migliaia di studi. Sulla questione se cercare o meno di evitare la tentazione: ogni utente dovrà decidere da solo. Tuttavia, è possibile fornire due utili suggerimenti per assisterti in questo processo. È la paura di futuri dolori di astinenza che ci fa usare il porno per il resto della nostra vita e questa paura consiste in due fasi distinte.

**Fase uno - "*Come posso sopravvivere senza il porno?*"**

Questa paura è la sensazione di panico che l'utente prova quando è single o ha un partner asessuato, disinteressato o non disponibile. La paura non è causata dai rimorsi dell'astinenza, ma è la paura psicologica della dipendenza, dell'incapacità di sopravvivere senza sesso e orgasmo. Raggiunge il picco quando sei sul punto di smettere, quando i tuoi rimorsi di astinenza sono al minimo. È la paura dell'ignoto, il tipo di paura che le persone provano quando imparano ad immergersi.

Il trampolino è alto un piede ma sembra essere alto sei piedi. L'acqua è profonda sei piedi ma sembra essere profonda un piede. Ci vuole coraggio per lanciarsi, convinti di spaccarsi la testa. Il lancio è la parte più difficile, se trovi il coraggio di farlo, il resto è facile! Questo spiega perché molti utenti volitivi non hanno mai tentato di smettere o possono sopravvivere solo per pochi giorni quando lo fanno. In effetti, ci sono alcuni utenti che seguono diete pornografiche che, dopo aver deciso di smettere, in realtà si abbuffano e passano a clip più dure più rapidamente che se non avessero deciso di smettere. Questa decisione provoca il panico, che è stressante e fa scattare un segnale per fare un viaggio nell'harem. Ma ora non puoi averne uno, portando a pensieri di privazione e stress aggravante.

Il grilletto si attiva rapidamente quando la miccia si brucia e apri il browser. Non preoccuparti, il panico è solo psicologico. È la paura che tu sia dipendente. La bella verità è che non lo sei, anche quando sei ancora dipendente. Non farti prendere dal panico e lanciati.

**Fase due - Paura a lungo termine**

La seconda fase è a lungo termine, comporta la paura che certe situazioni in futuro non saranno piacevoli o che non sarai in grado di affrontare il trauma senza il porno. Non preoccuparti, se riesci a lanciarti scoprirai che è vero il contrario. Lo stesso evitare la tentazione rientra in due categorie.

1.  "*Farò una dieta dal porno di una volta ogni quattro giorni. Mi sentirò più sicuro sapendo che posso andare online se diventa difficile. Se fallisco va bene, aggiungerò solo altri giorni a il mio prossimo ciclo.*"

Il tasso di fallimento delle persone che lo fanno è **molto più alto** rispetto a quelli che smettono del tutto. Ciò è dovuto principalmente al fatto che se stai attraversando un brutto momento durante il periodo di sospensione, è facile saltare sul browser e visitare l'harem con le scuse di cui sopra. Se hai l'umiliazione di infrangere chiaramente le tue stesse regole come con una finestra di vetro, è più probabile che superi la tentazione. In ogni caso, la fitta sarebbe probabilmente già passata se l'avessi ritardata. Tuttavia, il motivo principale dell'elevato tasso di fallimento in questi casi è che l'utente non si sentiva completamente impegnato a fermarsi in primo luogo. Ricorda che i due elementi essenziali per avere successo sono:

-   Certezza.

-   "*Non è meraviglioso che non abbia più bisogno del porno?*"

In entrambi i casi, perché diavolo hai bisogno di una sessione? Se hai ancora bisogno di visitare il tuo harem, rileggi prima il libro. Qualcosa non è del tutto gelificato. Prenditi il tempo per uccidere il grande mostro del lavaggio del cervello nella tua mente.

2.  "*Dovrei evitare occasioni stressanti o sociali durante il periodo di astinenza?*"

In caso di situazioni stressanti, sì. Non ha senso esercitare pressioni indebite su te stesso. Nel caso di eventi mondani, come bar o discoteche, il consiglio è il contrario. Esci e divertiti subito, non hai bisogno del sesso o del lato propagativo del sesso anche quando sei dipendente dal porno. Esci e rallegrati del fatto che non devi fare sesso o sesso propagativo, ti dimostrerà rapidamente la bellissima verità che la vita è molto migliore senza queste pressioni. Pensa solo a quanto sarà meglio quando il piccolo mostro ti avrà lasciato, insieme a quei pensieri.
