# Il momento della rivelazione

Di solito avviene entro tre settimane dallo stop, gli ex utenti sperimentano il momento della rivelazione. Il cielo sembra diventare più luminoso ed è il momento in cui il lavaggio del cervello finisce completamente. Quando invece di dirti che non hai bisogno di guardare il porno, all'improvviso ti rendi conto che l'ultimo filo è rotto e puoi goderti il resto della tua vita senza mai più averne bisogno. È anche da questo punto che di solito inizi a guardare gli utenti come oggetti di pietà.

I rinunciatari che usano il metodo della forza di volontà normalmente non sperimentano questo momento perché, sebbene siano contenti di essere ex utenti, continuano a muoversi nella vita credendo di fare un sacrificio. Più eri dipendente, più meraviglioso è questo momento e dura una vita. Mentre ci sono molte gioie nella vita, è impossibile ritrovare la vera sensazione di averle vissute. La gioia di non dover più guardare il porno è diversa, se ti senti giù e hai bisogno di una spinta, ricordati quanto sia bello non essere agganciato a quella terribile dipendenza. Molti lo elencano come uno dei più grandi eventi della loro vita. Nella maggior parte dei casi, il momento della rivelazione non avviene dopo tre settimane, ma dopo alcuni giorni.

Nel mio caso, è successo prima di finire la mia ultima visita all'harem. Sono sicuro che molti dei lettori qui, prima ancora di arrivare alla fine dei capitoli, dicono qualcosa del tipo "*Non c'è bisogno che tu dica un'altra parola. Posso vedere tutto così chiaramente, lo so, non avrò mai più bisogno del porno.*" Sulla base del feedback ricevuto, questo accade spesso. Idealmente, se segui tutte le istruzioni e comprendi completamente la psicologia, dovrebbe succedere immediatamente.

Sebbene sia affermato che occorrono circa cinque giorni per un notevole ritiro fisico e circa tre settimane affinché un ex utente diventi completamente gratuito, tali linee guida possono causare due problemi. Il primo è che nella mente delle persone è impiantato il suggerimento che dovranno soffrire per un periodo compreso tra cinque giorni e tre settimane. Il secondo è che l'ex utente tende a pensare "*Se posso sopravvivere per cinque giorni o tre settimane, posso aspettarmi un vero boost alla fine di quel periodo.*"

Tuttavia, possono avere cinque giorni piacevoli o tre settimane piacevoli seguite da giorni disastrosi che colpiscono tutti, che non hanno nulla a che fare con la dipendenza ma sono causati da altri fattori della nostra vita. Quindi il nostro ex utente che sta aspettando il momento della rivelazione sperimenta invece la depressione. Potrebbe distruggere la sua fiducia. Allo stesso modo, se non ci fossero linee guida, l'ex utente potrebbe passare il resto della vita aspettando quando non accadrà in realtà nulla. Questo è ciò che succede alla stragrande maggioranza di coloro che smettono di usare con il metodo della forza di volontà.

Le persone spesso chiedono il significato dei cinque giorni e delle tre settimane. Sono solo periodi nati dal nulla? No, sebbene non siano date definite, riflettono un accumulo di feedback nel corso degli anni. Circa cinque giorni dopo l'interruzione è quando l'ex utente cessa di avere la dipendenza come occupazione principale della propria mente. La maggior parte degli ex utenti sperimenta la rivelazione in questo periodo, generalmente in situazioni stressanti o sociali che a un certo punto non potevano essere affrontate o piacevoli senza una visita all'harem. All'improvviso ti rendi conto che non solo ti stai divertendo o stai affrontando, ma il pensiero del porno non ti è mai venuto in mente. Da quel punto di vista solitamente la situazione è tranquilla. È allora che sai di essere libero.

È sia la mia che l'esperienza di molti altri che tentano di smettere con il metodo della forza di volontà: intorno alle tre settimane è quando i tentativi più seri di smettere falliscono. Quello che succede di solito è che dopo circa tre settimane senti di aver perso il desiderio di guardare il porno. Devi dimostrarlo a te stesso, quindi salti sul browser per visitare il tuo harem. È strano, dimostrare che l'hai preso a calci. Ma nel processo riavvii lo scivolo d'acqua DeltaFosB grazie alla fresca scarica di dopamina, ciò che il tuo corpo ha bramato nelle ultime tre settimane. Non appena finisci l'atto, la dopamina inizia a lasciare il tuo corpo. Riappare una vocina, "*Non l'hai preso a calci, ne vuoi un altro.*"

Non corri subito indietro perché non vuoi essere agganciato di nuovo, lasci quindi passare un periodo sicuro. La prossima volta che sei tentato sei in grado di dire a te stesso "*Beh, non sono stato agganciato di nuovo, quindi non c'è niente di male a guardarne un altro."* Sei già sulla buona strada lungo il pendio scivoloso. La chiave del problema non è aspettare il momento della rivelazione, ma rendersi conto che una volta chiuso il browser è finita. Hai interrotto la fornitura di ossigeno al tuo piccolo mostro. Nessuna forza sulla terra può impedirti di essere libero, *a meno che tu non ti lamenti o attenda la rivelazione.* Vai e goditi la vita; affrontarlo fin dall'inizio. Il momento arriverà presto.