# La visita finale

Dopo aver deciso il tempismo, ora sei pronto per visitare il tuo harem un'ultima volta. Prima di farlo, controlla i due elementi essenziali.

1. Ti senti sicuro del successo?

2. Hai una sensazione di rovina e tristezza, o un senso di eccitazione per il fatto che stai per realizzare qualcosa di meraviglioso?

Se hai dei dubbi, rileggi prima il libro. Ricorda che non hai mai deciso di cadere nella trappola del porno, ma la trappola è progettata per renderti schiavo per tutta la vita. Per scappare, devi prendere la decisione positiva che stai per fermarti e fare la tua ultima visita.

Ricorda, l'unico motivo per cui hai letto questo libro finora è perché ti piacerebbe molto scappare. Quindi prendi questa decisione positiva ora, facendo un voto solenne sul fatto che quando chiuderai la finestra del tuo browser privato, sia che lo trovi facile o difficile, non visiterai mai più il tuo harem. Forse sei preoccupato di aver fatto questo voto diverse volte in passato e stai ancora fallendo, o che dovrai affrontare un terribile trauma. Non aver paura, la cosa peggiore che ti può capitare è che fallisci, quindi non hai ***assolutamente niente*** da perdere e tanto da guadagnare.

Ma smettila anche solo di pensare al fallimento, la bella verità è che non è solo ridicolmente facile smettere, ma puoi davvero goderti il processo. Questa volta userai EasyPeasy! Tutto quello che devi fare è seguire le semplici istruzioni che ti verranno date.

1. Fai il voto solenne ora e con sincerità.

2. Sfoglia consapevolmente le immagini e le clip sul tuo sito di tube preferito, osservando i disperati tentativi degli amministratori del sito, degli attori e persino dei dilettanti di amplificare lo shock, la novità e la natura soprannaturale delle loro merci e chiediti dove sia il piacere.

3. Quando finalmente chiudi il browser, non farlo con la sensazione di "*non devo mai più visitare un altro harem online*" o "*non mi è permesso visitarne un altro*", ma piuttosto con una sensazione di libertà , come "*Non è fantastico? Sono libero! Non sono più schiavo del porno! Non dovrò mai più visitare questi siti sporchi nella mia vita.*"

4. Tieni presente che per alcuni giorni ci sarà un piccolo sabotatore porno dentro il tuo stomaco. Potresti solo essere consapevole della sensazione di volere una sessione. Il piccolo mostro è stato definito come il leggero desiderio fisico di dopamina. A rigor di termini questo non è corretto ed è importante capire perché. Poiché ci vogliono fino a tre settimane perché quel mostriciattolo muoia, gli ex utenti credono che il mostriciattolo continuerà a desiderare dopo l'ultima visita all'harem online, e quindi devono usare la forza di volontà per resistere alla tentazione durante questo periodo. Non è così, il corpo non brama la dopamina innescata dal porno; solo il cervello brama.

Se hai la sensazione di voler dare un'occhiata nei prossimi giorni, il tuo cervello ha una scelta semplice. Può interpretare quella sensazione per quello che è in realtà -- una sensazione vuota e insicura iniziata dalla prima visita a un sito porno online e ulteriormente perpetuata da ogni visita successiva, dicendo a te stesso **"YIPPEE! SONO UN NON- UTENTE!"**

Oppure puoi iniziare a desiderare il porno e soffrire per il resto della tua vita. Pensa solo per un momento, non sarebbe una cosa incredibilmente stupida da fare? Dire "*Non voglio più guardare il porno*" e poi passare il resto della tua vita a dire "*Mi piacerebbe una visita*"? Questo è ciò che fanno coloro che usano il metodo della forza di volontà, e non c'è da meravigliarsi che si sentano così infelici. Trascorrono il resto della loro vita deprimendosi disperatamente per qualcosa che sperano disperatamente di non avere mai. Non c'è da stupirsi che così pochi abbiano successo e quei pochi che non si sentono mai completamente liberi.

> *'Ottieni questa immagine mentale chiaramente nella tua mente, perché può essere molto utile per superare il potere degli stimoli esterni che ti disturbano. Immaginati seduto in silenzio, mentre lasci squillare il telefono, ignorando il suo suono, impassibile al suo comando. Anche se ne sei consapevole, non ti preoccupi né gli obbedisci più. Inoltre, tieni chiaramente in mente il fatto che il segnale esterno di per sé non ha alcun potere su di te, nessun potere di muoverti. In passato gli hai obbedito, gli hai risposto, per pura abitudine. Puoi, se lo desideri, prendere una nuova abitudine a non rispondere.*
>
> * Nota anche che la tua incapacità di rispondere non consiste nel fare qualcosa, o fare uno sforzo, o resistere o lottare, ma nel non fare nulla - nel rilassamento dal fare. Ti rilassi semplicemente, ignori il segnale e lasci che i suoi richiami passino inascoltati. Lo squillo del telefono è un'analogia simbolica con qualsiasi altro stimolo esterno sul quale potresti abitualmente avere il controllo e ora scegli di modificare intenzionalmente quell'abitudine.*'
>
> --- Maxwell Maltz, "The New Psycho Cybernetics" Cap 12.

Sono solo i dubbi e l'attesa che rendono difficile smettere, ***quindi non dubitare mai della tua decisione*** perché sai che è quella giusta. Se inizi a dubitarne, ti ritroverai in una situazione senza possibilità di vittoria. Infelice mentre brami una visita ma non riesci ad averne una. Indipendentemente dal sistema che stai utilizzando, cosa stai cercando di ottenere quando lasci il porno? Mai più guardare? No! Molti ex utenti lo fanno, ma passano il resto della loro vita sentendosi privati.

Qual è la differenza tra utenti e non utenti? I non utenti non hanno alcun bisogno, né desiderio di guardare il porno, sono senza desiderio e non hanno bisogno di esercitare la forza di volontà per non guardarlo. Questo è ciò che stai cercando di ottenere ed è completamente in tuo potere farlo. Non devi aspettare per smettere di desiderare il porno o diventare un non utente, è completato nel momento in cui chiudi l'ultima finestra del browser, interrompendo la fornitura di dopamina: **SEI GIÀ UN FELICE NON UTENTE!**

Rimarrai un felice non utente a condizione che:

1. Non dubiti mai della tua decisione.

2. Non aspetti a diventare un non utente. Se lo fai, starai semplicemente aspettando che non accada nulla e creerai una fobia.

3. Non provi a *non* pensare al porno o ad aspettare che arrivi il 'momento della rivelazione', creando una fobia.

4. Non usi sostituti.

5. Vedi tutti gli altri utenti come sono veramente e li compatisci piuttosto che invidiarli.

Che siano giornate belle o brutte, non cambiare la tua vita solo perché hai smesso. Se lo fai, farai un vero sacrificio quando non ce n'è bisogno. Ricorda, non hai rinunciato a vivere. Non hai rinunciato a niente. Al contrario, sei guarito da una terribile malattia ed evaso da una prigione insidiosa. Con il passare dei giorni e la tua salute, sia fisica che mentale, migliora, gli alti appariranno più alti e i bassi meno bassi rispetto a quando eri un utente. Ogni volta che pensi al porno nei prossimi giorni o per il resto della tua vita, pensa:

***"YIPPEE! SONO UN NON UTENTE!"***

## Un ultimo avvertimento

Nessun utente, se avesse la possibilità di tornare indietro nel tempo prima di diventare dipendente dalla conoscenza che ha ora, sceglierebbe di iniziare. Decine di migliaia di persone che riescono a liberarsi dall'abitudine per molti anni conducono vite perfettamente felici, solo per rimanere intrappolate ancora una volta. Confido che questo libro ti aiuterà a trovare relativamente facile smettere. Ma attenzione, gli utenti che trovano facile smettere trovano altrettanto facile ricominciare, **non cadere in questa trappola.**

Non importa per quanto tempo ti sei fermato o quanto sei sicuro che non rimarrai mai più agganciato, fai in modo che sia una regola per la vita non guardare il porno per nessun motivo. Resisti alle allusioni e alle allusioni dei media e ricorda come stanno spingendo l'"apertura" portando il porno nel mainstream; ignari del fatto che il porno, il porno su Internet e la masturbazione compulsiva sono assassini delle relazioni e del senso di benessere personale per un numero enorme di uomini e alcune donne.

Ricorda che la prima occhiata o visita non farà nulla per te. Non avrai dolori di astinenza da alleviare e ti farà sentire malissimo. Quello che farà è mettere il piacere della scarica di dopamina nella tua mente e nel tuo cervello, e una vocina in fondo alla tua mente ti dirà che ne vuoi un'altra. Poi hai la scelta di essere infelice per un po', o ricominciare da capo l'intera sudicia catena.
