# Feedback

La guerra non è contro gli utenti, ma contro la trappola dell'industria del porno, ed è condotta per il semplice motivo che mi diverto. Ogni volta che sento di un utente che evade provo una sensazione di immenso piacere. Ma questo piacere non è nato senza una notevole frustrazione, causata principalmente da due categorie di utenti porno. Nonostante l'avvertimento del capitolo precedente, rimango continuamente sorpreso dal numero di coloro che trovano facile smettere, ma in seguito ricadono nella trappola e scoprono di non poter avere successo.

È come trovare qualcuno immerso fino al collo in una palude e sul punto di affondare. Li aiuti a tirarli fuori e loro sono grati ma poi, sei mesi dopo, si tuffano di nuovo nella palude. Gli utenti che trovano facile fermarsi e ricominciare pongono un problema particolare, tuttavia quando riesci a smettere ***PER FAVORE, PER FAVORE, NON RIFARE LO STESSO ERRORE.*** Credono di ricominciare perché sono ancora agganciati e manca loro la dopamina. In effetti, trovano così facile fermarsi che perdono la paura del porno. Pensano: "*Posso avere una nuova sessione, e anche se dovessi rimanere intrappolato di nuovo, sarà facile smettere.*"

Temo che non funzioni in questo modo, è facile fermare il porno ma impossibile controllare la dipendenza. L'unica cosa essenziale per fermare il porno è non usarlo.

Le persone di solito tornano al porno perché fraintendono il "facile" in easypeasy.

Immagina qualcuno seduto sul freddo pavimento di cemento di una stanza gelida. Sulla parete di fronte a lui c'è una finestra che mostra una bellissima giornata primaverile - alberi che ondeggiano dolcemente, uccellini che cinguettano - proprio accanto, una porta aperta.

Ci vuole forza di volontà per uscire da quella stanza gelida? No! Scappare è più difficile che restare? Ovviamente no! (In effetti, è un po' più facile a causa del movimento del corpo). Perché qualcuno sano di mente dovrebbe mettersi in una situazione del genere, causandosi mesi o anni di frustrazione a meno che non sia stato ingannato?

Easypeasy sposta le tende in modo che l'utente possa vedere chiaramente all'esterno e per rimuovere le false **illusioni** sul quanto possa essere terribile l'esterno e quanto sia a suo agio l'utente nella stanza.

L'altra categoria di utenti frustranti sono quelli troppo spaventati per fare il tentativo di smettere, o quelli che quando lo fanno, lo trovano una grande lotta. Le principali difficoltà sembrano essere le seguenti.

**Paura di sbagliare.**

:   Non c'è disonore nel fallimento, ma non provarci è pura stupidità. Guardala in questo modo, ti stai nascondendo dal nulla. La cosa peggiore che può succedere è che tu fallisca, nel qual caso non stai peggio di adesso. Pensa solo a quanto sarebbe meraviglioso avere successo. Se non fai il tentativo, hai già garantito il fallimento.

**Paura del dolore e di essere infelice.**

:   Non preoccuparti, pensa solo: che cosa terribile potrebbe accaderti se non guardi mai più il porno? Assolutamente niente. Cose terribili *accadranno* se lo fai, rileggi le note sulla scommessa di Pascal. In ogni caso, il panico è causato dalla dopamina e presto scomparirà. Il guadagno più grande è liberarsi di quella paura. Credi davvero che gli utenti siano pronti ad avere penetrazioni sbiadite, prestazioni sessuali inaffidabili o il piacere illusorio che ottengono dal porno? Se ti accorgi di essere preso dal panico, la respirazione profonda ti aiuterà. Se sei con altre persone e ti stanno demotivando, scappa da loro e vai in garage, in un ufficio vuoto o da qualche parte.

    Se hai voglia di piangere, non vergognarti. Piangere è il modo in cui la natura allevia la tensione. Nessuno ha mai pianto senza sentirsi meglio dopo. Una delle cose orribili che facciamo ai giovani è condizionarli a non piangere. Puoi vederli mentre cercano di trattenere le lacrime, mentre la mascella digrigna. Insegniamo a noi stessi a non mostrare emozioni, ma non siamo destinati a tenerle dentro. Urla, grida o fai i capricci. Calcia qualcosa. Considera la tua lotta come un incontro di boxe che non puoi perdere. Nessuno può fermare il tempo, ogni momento che passa quel piccolo mostro dentro di te sta morendo. Goditi la tua inevitabile vittoria.

**Non seguendo le istruzioni.**

:   Incredibilmente, alcuni utenti affermano che il metodo non ha funzionato per loro. Poi descrivono come hanno ignorato non solo un'istruzione ma praticamente tutte. Per chiarezza, queste sono riassunte come lista di controllo alla fine di questo capitolo.

**Istruzioni errate.**

:   I problemi principali sembrano essere questi:

    "*Non riesco a smettere di pensare al porno.*"

    :   Certo che non puoi e se ci provi, creerai una fobia, diventando infelice. È come cercare di addormentarsi la notte; più ci provi, più difficile diventa. Non importa se pensi al porno per il novanta percento della tua vita, è quello che pensi che è importante. Se stai pensando "*Oh, mi piace guardare il porno*" o "*Quando sarò libero?*" sarai infelice. Se invece stai pensando "*YIPPEE! Sono libero!*" sarai felice.

    "*Quando morirà il piccolo mostro?*"

    :   Il flusso di dopamina lascia il tuo corpo molto rapidamente, ma è impossibile dire quando il tuo corpo cesserà di soffrire della leggera sensazione fisica di astinenza da dopamina. Quella sensazione di vuoto e insicurezza è identica alla normale fame, depressione o stress. Tutto ciò che fa il porno è aumentarne il livello. Questo è il motivo per cui gli utenti che smettono di usare il metodo della forza di volontà non sono mai del tutto sicuri di averlo preso a calci, anche dopo che il loro corpo ha smesso di soffrire di astinenza da dopamina. Se soffrono di fame o stress a livelli normali, il loro cervello continua a dire loro che questo è un motivo valido per concedersi una sessione. Il punto è che non devi aspettare che il desiderio se ne vada, è così lieve che non sai nemmeno che è lì, lo percepisci solo come un sentimento di desiderio. Quando esci dal dentista aspetti che la mascella smetta di farti male? Certo che no, vai avanti con la vita. Anche se la mascella ti fa ancora male, sii euforico.

        Non aspettare che questa lieve sofferenza se ne vada perché creerai dubbi chiedendoti costantemente "*Quanto tempo ci vorrà? Sono libero anche se non mi sento diverso?*" La paura è la vera fitta, quindi l'attesa per migliorare dopo aver smesso creerà dubbi. L'astinenza è impercettibile a meno che tu non ne abbia paura e i miglioramenti cerebrali esponenziali sono lenti, quindi se aspetti di sentirti diverso, sembrerà che non stia accadendo nulla, creando dubbi.

    *"Il 'momento della rivelazione' non è ancora arrivato."*

    :   Se aspetti, stai solo causando un'altra fobia, una volta ho smesso per tre settimane con il metodo della forza di volontà. Chiacchierando con un vecchio amico, mi ha chiesto come stavo. "*Sono sopravvissuto a tre settimane*", risposi. Ha chiesto, "*Cosa vuoi dire, sei sopravvissuto a tre settimane?*" Ho chiarito, "*Sono stato tre settimane senza porno.*" Disse: "*Cosa hai intenzione di fare? Sopravvivere per il resto della tua vita? Cosa stai aspettando, l'hai fatto. Sei un non utente.*" Ho pensato: "*Ha assolutamente ragione, cosa sto aspettando?*" Sfortunatamente, a causa della mancanza di comprensione della trappola, sono ridivientato un utente, ma avevo imparato la lezione. Diventi un non utente quando chiudi il browser. L'importante è essere un felice non utente fin dall'inizio.

    "*Ho ancora voglia di porno.*"

    :   Allora sei stupido. Come puoi affermare di voler essere un non utente e poi dire che vuoi il porno? Questa è una contraddizione. Se dici che vuoi il porno, stai dicendo che vuoi essere un utente. I non utenti non vogliono visitare i disgustosi siti. Sai già cosa vuoi essere, quindi smettila di punirti.

    "*Ho rinunciato alla vita.*"

    :   Come mai? Tutto quello che devi fare è smettere di ucciderti e iniziare invece a darti energia. Non devi assolutamente smettere di vivere. È così semplice, per i prossimi due giorni avrai un leggero trauma nella tua vita. Il tuo corpo subirà l'aggravamento quasi impercettibile delle richieste di un aumento della dopamina. Ora, tienilo a mente: non stai peggio di prima. Questo è ciò che hai sofferto per tutta la tua vita, ogni volta che dormivi, eri in chiesa, al supermercato o in biblioteca. Non sembrava darti fastidio mentre eri un utente e se non smetti, continuerai a soffrire di questo disagio per il resto della tua vita.

        Il porno e gli orgasmi non creano occasioni, te le privano. Anche mentre il tuo corpo brama ancora la dopamina, i pasti e le occasioni sociali sono meravigliosi. La vita è meravigliosa, vai alle funzioni sociali. Ricorda che non sei stato privato di nulla, gli utenti lo sono. Ognuno di loro vorrebbe essere nella tua posizione, se solo lo sapesse. Divertiti a essere la "prima donna" e al centro dell'attenzione. I tuoi amici e coetanei saranno sorpresi di vedere che tu, prima timido e stanco, ora sei felice e allegro. Ti godrai la vita fin da subito, non c'è bisogno di invidiare i rimorchiatori alle feste, ti invidieranno loro.

    "*Sono infelice e irritabile.*"

    :   Si tratta di un mancato rispetto delle istruzioni. Scopri qual è. Alcune persone capiscono e credono a tutto ciò che è scritto, ma iniziano comunque con una sensazione di sventura e tristezza, come se stesse accadendo qualcosa di terribile. Non stai solo facendo quello che ti piacerebbe fare, ma anche quello che vorrebbe ogni utente del pianeta. Con qualsiasi metodo per fermarsi, l'ex utente sta cercando di raggiungere un certo stato d'animo, quindi ogni pensiero relativo al porno è costellato dall'affermazione "*YIPPEE! SONO LIBERO!*" Se questo è il tuo obiettivo, perché aspettare? Inizia con quello stato d'animo e non perderlo mai, non c'è alternativa.

    "*Ho avuto una buona settimana/mese/sei mesi ma sono di nuovo nella trappola.*"

    :   Ricorda, la paura è la fitta stessa. Cedere a una fitta genera più paura, nutrendo il piccolo mostro indebolito e riuscendo a spaventare il non utente facendogli credere di essere dipendente per la vita. In realtà, la sua concettualizzazione del lavaggio del cervello non è cambiata, ma ha dato dopamina al processo mentale. Questo è per definizione buttarsi in avanti, ma è un fallimento nel seguire le istruzioni. Comprendi quale delle istruzioni sotto e rallegrati.

## La lista di controllo

Se segui queste istruzioni, non puoi fallire:

1.  Fai un voto solenne che non andrai mai e poi mai online per visitare il tuo harem *O* immagini statiche *O* grafica erotica *O* qualsiasi cosa contenga stimoli soprannaturali e mantieni il tuo voto.

2.  Tienilo bene in mente: non c'è assolutamente nulla a cui rinunciare. Con ciò, non si intende che starai meglio come non PMOer (l'hai sempre saputo); né che sebbene non vi sia alcuna ragione razionale per cui fai il PMO, ne trai piacere o appoggio, poiché altrimenti non lo faresti. Ciò significa che non c'è ***nessun piacere genuino nel PMOing.*** È solo un'illusione, come sbattere la testa contro un muro per provare piacere quando ti fermi.

3.  Non esiste un PMOer confermato. Sei solo uno delle centinaia di milioni che sono caduti nella sottile trappola. Come i milioni di altri ex membri del PMO che una volta pensavano di non poter scappare, tu sei scappato.

4.  Se in qualsiasi momento della tua vita dovessi soppesare i pro e i contro del PMOing, la conclusione travolgente sarebbe sempre "*Smettila di farlo. Sei uno stupido!*" Niente potrà mai cambiarlo. È sempre stato così e sempre lo sarà. Avendo preso quella che sai essere la decisione giusta, non torturarti mai con i dubbi. La scommessa di Pascal si applica perfettamente al PMO, senza possibilità di perdita, alte possibilità di guadagni e alte possibilità di evitare perdite.

5.  Non cercare di non pensare al porno o di preoccuparti di pensarci costantemente. Ogni volta che ci pensi, che sia oggi, domani o per il resto della tua vita, pensa **"YIPPEE! SONO UN NON-PMOer!"**

6.  **Non** utilizzare alcuna forma di sostituto. **Non** metterti alla prova tenendo il tuo laptop accanto a te mentre dormi. **Non** evitare opere teatrali, film o riviste. **Non** cambiare il tuo stile di vita in alcun modo solo perché hai smesso. Se segui le istruzioni di cui sopra, sperimenterai presto il "momento della rivelazione", ma:

7.  Non aspettare che arrivi il 'momento della rivelazione'. Vai avanti con la tua vita, godendoti gli alti e affrontando i bassi. Scoprirai che in men che non si dica il momento arriverà.
