# Aiuta quelli sulla nave che affonda

Gli utenti del porno sono oggi in preda al panico, capiscono i cambiamenti nel modo in cui il porno su Internet viene percepito da uomini e donne. La base della dipendenza da porno su Internet viene studiata sempre più spesso e ora viene giustamente considerata diversa dalla pornografia tradizionale. La facilità e la disponibilità suscitano allarme anche nei cuori dei sostenitori del porno. Essi percepiscono anche che la loro crociata per la libertà di parola e di pensiero viene dirottata da vari elementi. Il selvaggio west di Internet, privo di controlli, rende quasi impossibile imporre restrizioni di età agli stimoli supernormali. È un peccato che tutto questo non finirà sicuramente presto, ma centinaia di migliaia di utenti si stanno fermando, e la maggior parte dei dipendenti è consapevole degli studi che mostrano le analogie tra il porno e la dipendenza da sostanze. Ogni volta che un utente abbandona la nave che affonda, chi resta a bordo si sente sempre più infelice.

Ogni utente sa istintivamente che è ridicolo autosabotarsi e passare il tempo davanti a pixel bidimensionali, sovralimentando il proprio cervello e sviluppando così percorsi neurali che garantiscono prestazioni sessuali scadenti. Se ancora non vi sembra ridicolo, provate a parlare con una rivista porno in piedi al centro della vostra città e chiedetevi qual è la differenza. Solo una. Non si può ottenere il piacere del calore e dell'intimità in questo modo. Se potete smettere di comprare alcol e sigarette ogni volta che fate la spesa, potete sicuramente smettere di visitare il vostro harem online. Gli utenti non riescono a trovare ragioni razionali per guardare il porno, ma non si sentono così sciocchi se anche gli altri lo fanno.

Gli utenti mentono palesemente sulla loro abitudine, non solo ai ricercatori e a chi li circonda, ma anche a se stessi. Devono farlo, il lavaggio del cervello è essenziale per mantenere il rispetto di sé. Sentono il bisogno di giustificare la loro "abitudine" non solo a *loro stessi* ma anche ai non consumatori. Non fanno altro che pubblicizzare gli illusori vantaggi del porno con mezzi più sottili.

Se un utente smette con il metodo della forza di volontà, si sente comunque privato, tendendo a diventare un lamentoso. Tutto ciò non fa altro che confermare agli altri utenti quanto sia giusto continuare a farne uso. Se l'ex consumatore riesce ad abbandonare l'abitudine, è grato di non dover più vivere la vita autosabotandosi o sprecando energia e non ha bisogno di giustificarsi. Ricordate che è la paura a tenere la testa sotto la sabbia e a mettere in discussione il comportamento dell'utente solo quando smette. Aiutate l'utente eliminando queste paure. Ditegli quanto sia meraviglioso non dover vivere in una prigione, quanto sia bello svegliarsi la mattina sentendosi in forma e in salute invece di essere privi di energia e pieni di disgusto per se stessi, quanto sia meraviglioso essere liberi dalla schiavitù, poter godere di tutta la vita e liberarsi di quelle ombre nere. O meglio ancora, fate leggere loro questo libro.

È fondamentale non sminuire un utente sposato indicando che sta deliberatamente rovinando la sua relazione o che è in qualche modo traditore o impuro. È diffusa l'idea errata che l'ex consumatore sia peggiore sotto questo aspetto. Questa concezione ha un certo senso, ma è generalmente dovuta all'utilizzo del metodo della forza di volontà per smettere. Perché l'ex consumatore, pur avendo abbandonato l'abitudine, conserva ancora parte del lavaggio del cervello e crede di aver fatto un sacrificio. Si sente vulnerabile e il suo naturale meccanismo di difesa è quello di attaccare l'utente del porno.

Questo può rafforzare l'ego dell'ex utente, ma non aiuta l'utente. Non fa altro che metterlo con le spalle al muro, facendolo sentire ancora più miserabile e, di conseguenza, aumentando il suo bisogno di porno. Sebbene il cambiamento dell'atteggiamento della medicina nei confronti del porno su Internet sia la ragione principale per cui molti utenti stanno smettendo, ciò non rende più facile farlo. Anzi, lo rende molto più difficile. La maggior parte degli utenti oggi crede di smettere principalmente per motivi di salute. Questo non è del tutto vero.

Sebbene l'enorme rischio per la salute sia ovviamente il motivo principale per smettere, gli utenti hanno sabotato la loro virilità per anni senza che questo abbia fatto la minima differenza. Il motivo principale per cui gli utenti smettono è che la società sta iniziando a vedere il porno per quello che è: una dipendenza da droghe. Gli atteggiamenti della società stanno lentamente cambiando: molti partner ora farebbero domande se tu fossi sul tuo portatile nel bel mezzo della notte.

I divieti totali sul porno in alcuni paesi o l'indisponibilità di Internet sono esempi classici del dilemma dell'utente che viaggia. In genere si pensa che questo li aiuterà a ridurre l'assunzione di materiale pornografico. Il risultato è che invece di uno o due filmati al giorno, dei quali non avrebbero goduto, si astengono per un'intera settimana. Durante questo periodo di astinenza forzata, tuttavia, non solo si sentono mentalmente privati in attesa della loro ricompensa, ma anche il loro corpo ne ha voglia. Oh, quanto è preziosa la visita all'harem online quando alla fine gli viene concessa.

Le astinenze forzate in realtà non riducono l'assunzione, perché l'utente si concede ancora di più quando finalmente può stare da solo. L'unica cosa che fa è radicare nella mente dell'utente quanto sia prezioso il porno su Internet e quanto egli sia dipendente da esso. L'aspetto più insidioso di questa astinenza forzata è il suo effetto sugli adolescenti. Permettiamo ai dirottatori della "libertà di espressione", i produttori di porno, di prendere di mira adolescenti sfortunati per farli appassionare in primo luogo. Poi, in quello che probabilmente è il periodo più stressante della loro vita, quando nella loro mente illusa hanno bisogno soprattutto del porno, li ricattiamo per farli smettere a causa del danno che stanno causando a se stessi.

Molti non ci riescono e sono costretti, senza colpa, a soffrire di complessi per il resto della loro vita. Molti ci riescono e sono contenti di farlo, pensando: *"Bene. Lo farò per ora e quando sarà tutto finito sarò comunque guarito"* Poi arrivano il dolore e la paura di trovare lavoro e le altre vicissitudini da adulti. Quando il dolore e la paura sono finiti, si sentono sicuri e il vecchio meccanismo torna a funzionare. Una parte del lavaggio del cervello è ancora presente e prima che l'odore del nuovo portatile da lavoro sia svanito, l'utente si trova sulla soglia del suo harem online preferito. L'euforia dell'occasione blocca i sentimenti negativi dalla loro mente, non hanno intenzione di diventare di nuovo dipendenti, ma una sola sbirciatina non può far male... Troppo tardi! Sono già stati agganciati di nuovo.

Il vecchio desiderio di quel piccolo mostro ricomincerà e, anche se non si ricadrà subito nella dipendenza, la depressione post-sbornia probabilmente li coglierà di sorpresa. È strano che, sebbene gli eroinomani siano criminali per la legge, la risposta della società sia aiutare questi individui. Adottiamo lo stesso atteggiamento nei confronti dei poveri consumatori di pornografia. Non lo fanno perché lo vogliono, ma perché pensano di doverlo fare. E, a differenza dell'eroinomane, non devono subire anni e anni di torture mentali e fisiche. Diciamo sempre che una morte rapida è meglio di una lenta, quindi non invidiate il povero utente del porno. ***Meritano la vostra pietà.***
