# Consigli ai non-utilizzatori

## Smetti con il porno usando gli amici per leggere questo libro

Per prima cosa, studia il contenuto di questo libro e prova a metterti nei panni dell'utente. Non costringerli a leggere questo libro dicendo loro che stanno rovinando la loro salute o giocando con il fuoco. Loro lo sanno meglio di te. Gli utenti non continuano a guardare il porno perché si divertono o perché lo desiderano, lo dicono solo a se stessi e ad altre persone per mantenere il rispetto di sé. Lo fanno perché dipendono dal porno perché pensano che li rilassi, dia loro coraggio o sicurezza (piacere o sostegno) e perché sentono che la vita non sarà mai piacevole senza il "sesso" -- almeno la loro versione di quest'ultimo. Se provi a costringere un utente a fermarsi, si sentirà come un animale in trappola e desidererà ancora di più il suo harem. Questo potrebbe trasformarlo in un utente segreto e il porno diventerà ancora più prezioso nella sua mente.

Invece, concentrati sull'altro lato della medaglia. Portali da ex utenti (blog, forum, YBOP, NoFap, ecc.). Chiedi loro di dire all'utente come anche loro pensavano di essere agganciati per la vita e quanto è migliore la vita come non utente. Una volta che li avrai fatti credere di potersi fermare, la loro mente inizierà ad aprirsi. Quindi inizia a spiegare l'illusione creata dai rimorsi dell'astinenza. Non solo gli "scarichi di dopamina" non danno loro una spinta, ma stanno distruggendo la loro fiducia e li rendono irritabili e stanchi.

Ora dovrebbero essere pronti a leggere questo libro da soli, aspettandosi di leggere pagine su pagine di storie su eccitazione inaffidabile, penetrazioni in dissolvenza, PIED, PE, ecc. Spiega che questo approccio è completamente diverso e i riferimenti alla malattia sono minuscole frazioni di materiale.

In breve, non lasciare che questo muoia nell'oscurità. Dillo ai tuoi amici, ma non essere strano. Se cerchi di "vincere" la conversazione o di avere un dibattito, riuscirai solo ad alienare e aumentare ulteriormente la loro paura.

## Devo dirlo alla mia dolce metà?

Devo dire a mia moglie, fidanzata o partner della mia abitudine? L'intenzione è di aiutarti a smettere. Ci sono più fattori in gioco qui.

Se non sei riuscito a smettere usando il metodo della forza di volontà e l'hai già detto al tuo partner, parlagli del tuo nuovo approccio e consentigli di istruirsi leggendo il libro. Sarà in grado di assisterti e motivarti durante il periodo di astinenza e sarà una roccaforte quando il piccolo mostro tenterà di farti inciampare.

Se sei appena venuto a conoscenza dell'esistenza della trappola e non hai mai tentato di smettere in passato, usa prima EasyPeasy tu stesso. Come spiegato in precedenza, questa dovrebbe essere un'esperienza piacevole. Tuttavia, se lo trovi difficile, richiedi la sua assistenza. Sii aperto e vulnerabile con il tuo partner e ciò rafforzerà la tua relazione.

A condizione che ti piaccia smettere e non trovi difficoltà a causa dell'indecisione, non ci sono molti motivi per farlo sapere al tuo partner. Se non è stato un problema in passato, lascialo morire. Tuttavia, sii preparato al fatto che il tuo partner potrebbe chiedersi perché hai un aspetto, una sensazione e un rendimento migliori!

## Il mio partner sta abbandonando il porno

La pornografia è un perverso distruttore di relazioni e mentre smettere può essere fatto all'istante, la guarigione richiede tempo. Molti utenti, a causa di convinzioni irrazionali generate dalla loro dipendenza, sfogano la loro rabbia su partner e persone care. Questi comportamenti si manifestano in atteggiamenti di gaslighting, menzogne e manipolazioni. Questo non riguarda tutti gli utenti, ma è sempre più comune nelle fasi avanzate della malattia. Sebbene questi comportamenti possano essere manifestazione della sottostante dipendenza dal porno, è importante informarsi e, se riconosciuti, prendere in considerazione la possibilità di consultare un terapista specializzato in dipendenze sessuali.

Se il tuo partner è nel periodo di astinenza, supponi che stia soffrendo anche se non lo da a vedere. Non tentare di minimizzarlo dicendogli che è facile smettere, possono farlo da soli. Invece, continua a dirgli quanto sei orgoglioso, quanto è migliorato il suo aspetto , quanto è più dolce stare con lui e quanto sono migliorati in generale. È particolarmente importante continuare a farlo, quando un utente tenta di fermarsi, l'euforia del tentativo e le lodi che riceve dai colleghi possono aiutarlo. Tuttavia, tende a dimenticarle rapidamente, quindi continua a farlo.

Poiché non stanno parlando di porno, potresti pensare che se ne siano dimenticati e non vuoi che tu glielo ricordi. Di solito accade l'esatto contrario con il metodo della forza di volontà, poiché l'ex utente tende ad essere ossessionato da . Quindi non aver paura di sollevare l'argomento e continuare a lodarlo, te lo diranno se non vogliono che glielo ricordi.

Fai di tutto per sollevarli dalle pressioni durante il periodo di astinenza, pensando a modi per rendere la sua vita interessante e piacevole. Questo può anche essere un periodo di prova per i non utenti che non hanno mai avuto la dipendenza. Se un membro di un gruppo è irritabile, può causare infelicità a tutto il gruppo. Quindi preparati e, se l'ex utente si sente irritabile, potrebbe prendersela con te, ma non vendicarti, è in questo momento che ha più bisogno della tua lode e simpatia. Se anche tu ti senti irritabile, il che è comprensibile, cerca di non darlo a vedere.

Uno degli scherzi che fa un dipendente quando cerca di arrendersi con l'aiuto del metodo della forza di volontà è fare i capricci, sperando che il suo partner o i suoi amici dicano "*Non posso sopportare di vederti soffrire così. Per l'amor del cielo , prendi il tuo veleno.*" L'utente quindi non deve perdere la faccia, non si sta 'arrendendo', è stato autorizzato. Se l'ex utente mette in atto questo stratagemma, in nessun caso incoraggialo a ricadere. Dì invece: "*Se questo è ciò che il porno ti fa, grazie al cielo sarai presto libero. Che meraviglia che tu abbia avuto il coraggio di rinunciare.*"

Ricorda che nel percorso di guarigione ci sono due parti che guariscono (tu e lui). Quando il tuo partner sta abbandonando il porno, è importante che abbia la tua rete di supporto e la cura di sé. Questo processo non avviene dall'oggi al domani e richiede fiducia, comunicazione e responsabilità. Lo scrivere un diario, lo sviluppo delle proprie passioni e, soprattutto, la terapia, aiutano questo processo.

## Scivolamento (ricaduta)

L'esistenza di questa sezione dovrebbe servire da monito per coloro che escono dalla trappola. Personalmente non ho mai avuto ricadute, ma userò esperienze tratte da interviste con membri della comunità e strumenti della terapia cognitivo comportamentale per illustrarla.

In primo luogo, definirla una ricaduta è controproducente. Tutto quello che è successo è che sei scivolato e hai dato da mangiare al piccolo mostro, che a sua volta avvia il grande mostro del lavaggio del cervello. Gli utenti che scivolano in genere generano un'intera gamma di credenze irrazionali:

-   "*Non sarò mai libero*" - **Catastrofizzante**
-   "*Dovrei/devo esercitarmi, studiare ed essere fruttuoso ogni singolo giorno della mia vita*" (aka - **musterbating**)
-   "*Oggi ho fatto il PMO, a che serve leggere tutti i libri e i forum... Il mio obiettivo era nemmeno quello di M, ma eccomi qui -- un fallimento -- con una ricaduta.*" - **Bassa tolleranza alla frustrazione**
-   "*I miei amici / lettori del forum / altri non stanno facendo PMO per (n) giorni, ma io non posso quindi sono un caso senza speranza. Ieri mi sono sentito bene dato che ho studiato bene ed è stato fruttuoso, ma oggi non l'ho fatto ... sto andando in discesa.*" - **Valutazione di sé in base gli altri**
-   "*Non dovrei avere pensieri sessuali*" - Loro stessi, i genitori o la loro società nel suo complesso hanno insinuato **credenze rigide** in relazione al sesso. Chiediti se l'autoflagellazione ti sta aiutando a raggiungere i tuoi obiettivi e, in tal caso, ti stai godendo il viaggio?

I fattori che culminano nel lavaggio del cervello di ogni utente sono apparentemente infiniti. Ti conosci meglio di chiunque altro,ma hai ovviamente fallito nel seguire le istruzioni. Hai percepito un valore nella pornografia, come?

Ciò che viene spesso trascurato è che ci vuole tempo per invertire il lavaggio del cervello. Questo non lo rende più difficile, ma quasi ogni industria usa il sesso e contrastare attivamente il lavaggio del cervello è un processo consapevole (almeno all'inizio), quindi potrebbe volerci del tempo per consolidare completamente le lezioni contenute all'interno del libro. Pertanto, si consigliano più letture (puoi saltare ai capitoli con cui hai difficoltà) e ciò non dovre richiedere molto tempo.

Un'esperienza sorprendentemente comune per gli utenti religiosi che lasciano la trappola è desiderare che faccia un po' male, come forma di espiazione. Trovano che smettere sia così facile, quindi si sentono in colpa per essersi sentiti in questo modo. Ma perché autosabotarsi e renderlo difficile? Il piccolo mostro è molto subdolo in questo senso.

Dissociati dal piccolo mostro, è stato aggiunto dall'industria del porno molto tempo fa. Immagina un bullo che fa i capricci nel cortile della scuola. Cosa si dice a un bullo? Se ti arrendi, li rafforzerai solo. Alcuni che smettono finiscono per nutrire il bullo, e così aumentano il loro lavaggio del cervello, ma la loro concettualizzazione della trappola non è cambiata. Riprenditi, scopri dove hai sbagliato e goditi la libertà!

Non sei la tua voglia. La meditazione consapevole è la pratica di notare il pensiero e ci sono lezioni fondamentali sulla natura della mente da trovare. Si consiglia vivamente di meditare in generale ed è anche completamente compatibile con la pratica religiosa. Non puoi combattere con te stesso o con il piccolo mostro. Devi amare incondizionatamente te stesso e il processo.

Ma rimuovi il fallimento dalla tua mente. Ecco una sezione da "*Meditations of a Porn Addict*" di Gulliaco (collegato nella sezione risorse alla fine del libro)

> Dal momento che guardare il porno non ti offre alcun vantaggio, è qualcosa che ti fa solo male, ed è estremamente ridicolo voler fare una cosa del genere, lo paragono a bere candeggina. Ecco qui:
>
> **Il duro viaggio di non bere candeggina.**
>
> Ciao! Siamo NoBleach e ospitiamo sfide di riavvio in cui i partecipanti ("Bleachstronauts") si astengono dal bere candeggina per un periodo di tempo. Sia che il tuo obiettivo sia la partecipazione occasionale a una sfida mensile come prova di autocontrollo, sia che il consumo eccessivo di candeggina sia diventato un problema nella tua vita e tu voglia smettere per un periodo di tempo più lungo, troverai una comunità solidale e molto di risorse qui.
>
> -   "*A volte mi permetto di bere un bicchiere di candeggina. So che dire "solo una goccia" è una bugia, ma non credo che un solo bicchiere farà male. Non si possono distruggere tutte le ore che ho passato senza farlo.*"
> -   "*Non ho problemi a smettere di bere candeggina, ma a volte vado per strada e vedo qualcuno che beve acqua, sai, in un bicchiere, e immagino che il bicchiere contenga candeggina. Poi mi viene una voglia matta e, dopo aver discusso con me stesso se devo farlo o meno, alla fine mi arrendo la sera e bevo un bicchiere.*"
> -   "*Guarda, il mio problema è che a volte, quando sono solo nella mia cucina, comincio a vedere i bicchieri, a volte mi faccio tentare aprendo il contenitore dove tengo la candeggina, a volte ne sento l'odore e... beh, Finisco proprio dove ho iniziato. Sono così disperato, ma non sono sicuro se sarò mai in grado di fermarmi.*"
> -   "*Smettere di bere candeggina è impossibile, voglio dire, ho sempre la bocca, sai? Come faccio a fermarmi se ho sempre la gola che mi ricorda che posso ingoiare candeggina?*"
> -   "*Oh amico, stava andando così bene, 19 giorni interi senza bere. L'importante è imparare dal fallimento! Ora so cosa evitare di fare: guardare i prodotti per la pulizia al supermercato. Cercherò di farcela per un mese! Ripristinerò il mio contatore. Augurami buona fortuna!*"

> Se hai voglia, calmati amico! Ricorda cosa dice l'hackbook:
>
> "*È difficile rinunciare per paura di essere privati del nostro piacere o del nostro sostegno. La paura che certe situazioni piacevoli non saranno mai più le stesse. La paura di non essere in grado di far fronte a situazioni stressanti. In altre parole, sono gli effetti del lavaggio del cervello che ci illudono di credere che comprare la candeggina, e per estensione berla, sia un dovere per tutti gli esseri umani. Inoltre, è la convinzione che ci sia qualcosa di inerente alla candeggina a prezzi accessibili di cui abbiamo bisogno e che quando smetteremo di usarla negheremo noi stessi e creeremo un vuoto. Mettilo in chiaro nella tua mente: la candeggina non riempie un vuoto, lo crea!*"
>
> e io dico: "*Supponi di essere costretto a guardare un bicchiere pieno di candeggina per cinque minuti. Prova a ricordare uno di quei marchi o odori che ti sono piaciuti così tanto. Forse è accompagnato da qualche suono, o ne ricordi solo dettagli. La candeggina è lì e non puoi chiudere gli occhi o girare la testa, perché questa candeggina è nella tua mente, è un ricordo registrato in te.*
>
> *Senti qualche desiderio? Senti qualcosa nella tua lingua o qualche cambiamento nel tuo respiro? Quali sono i tuoi sentimenti riguardo a ciò che stai ricordando? Falli identificare, la candeggina vuole annebbiarli, renderli confusi e farti prestare attenzione solo a ciò che vuole catturarti.*"
>
> Con quanto sopra, non sto cercando di respingere i tuoi sentimenti, tanto meno di dire qualcosa come "haha io sono intelligente tu stupido", ma voglio darti una prospettiva in modo che tu ti renda conto di quanto sia ridicolmente facile (e sarà sempre) superare questo dipendenza. Guardare il porno non è come avere un interruttore on/off in cui dici "*oh beh, sono nella situazione X, allora guarderò il porno*". Bugie! Quanto spesso ti permetti di bere un bicchiere di candeggina? Mai? Come mai? Perché è una cosa orribile, ecco perché! Come vorresti sfuggire alla tua dipendenza se non ti rendi conto che il PMO è una cosa orribile da fare a te stesso?

## Che mi dici di MO (masturbazione, orgasmo)?

La gente si masturba da eoni senza problemi. Per essere chiari, il porno è il problema.

Detto questo, puoi ancora essere catturato da MO per le stesse ragioni del porno, come la mentalità del "bisogno di avere un orgasmo", l'escalation mentale, costringere il corpo a fare sesso è semplicemente la ricerca del piacere endonista.

È estremamente probabile che il porno e la masturbazione si siano profondamente intrecciati nella tua mente. Molti utenti scoprono di finire per ricadere a causa della masturbazione con fantasie indotte dal porno. Man mano che il tuo cervello si ricollega, scoprirai che questo lavaggio del cervello alla fine svanisce, ma è meglio prendersi una pausa dal MO per un po'. Dovresti anche cercare il vero sesso per accelerare questo processo.

Questa non è un'istruzione, ma valutala. I benefici riportati dalla ritenzione del seme sono numerosi: maggiore concentrazione ed energia, rimozione della "nebbia del cervello" e maggiore fiducia insieme a una serie di altri benefici. Per esperienza personale, c'è una chiara differenza, e tutto dipende da come investite questa maggiore energia.

Speculando e senza una rigorosa conoscenza scientifica, i benefici potrebbero ridursi a un paio di fattori diversi.

-   Dopo l'orgasmo, il cervello rilascia prolattina, che inibisce il rilascio di dopamina.

-   Privare il cervello delle vampate di dopamina consente un maggiore assorbimento della stessa dal semplice vivere la vita.

-   Lo sperma viene riassorbito dal flusso sanguigno dopo circa 78 giorni ed è uno dei migliori nutrienti che il tuo corpo può ottenere.

-   Trasmutare l'energia sessuale in abitudini produttive porta con sé un ulteriore livello di produttività.

Potresti desiderare di fare sesso anche senza orgasmo, che come accennato in precedenza, è una meravigliosa esperienza sessuale. Puoi rafforzare la tua capacità di farlo praticando gli esercizi di Kegel. Per esperienza personale, il modo più semplice ed efficace per allenare questo muscolo è fermare l'urina a metà del flusso. La separazione delle parti tantrica e propagativa del sesso è uno dei tanti vantaggi di sfuggire alla trappola del PMO (e anche i miei partner l'hanno adorato!).

## Deviazioni dai consigli standard

Questa sezione è nuova ed è scritta con un po' di apprensione; giustamente, deve essere menzionata.

Alcune persone che usano EasyPeasy scoprono che il loro desiderio di guardare il porno si riduce così tanto che non riescono a fare una sessione finale. **Va bene**, ma non sottovalutare il potere di averne uno. Navigare e consolidare consapevolmente quanto non ti piace il PMO può essere davvero potente. Personalmente l'ho trovato davvero utile ed ero felice di lavarmene le mani; sinceramente sollevato di non doverlo fare mai più. Tuttavia, il tuo caso può variare.

Se sei già stato libero dalla trappola per un po' e hai appena rimosso il lavaggio del cervello, non c'è bisogno di dar da mangiare al piccolo mostro perché ti assillerebbe. Goditi invece la libertà!

## Aiutaci a porre fine a questo scandalo

Il porno su Internet è uno dei pericoli in una società libera, che sostiene gli sforzi volontari delle libertà personali. Sicuramente la vera base della civiltà - il motivo per cui la specie umana è avanzata così tanto - è perché siamo in grado di comunicare le nostre conoscenze ed esperienze, non solo gli uni agli altri ma anche alle generazioni future. Anche gli animali ritengono necessario avvertire la loro prole delle insidie della vita.

I produttori di porno non lo fanno in buona fede, credendo sinceramente di aiutare l'umanità, soprattutto ora che la dipendenza dal porno su Internet è ampiamente studiata. Forse nelle sue fasi iniziali le persone credevano sinceramente che il porno educasse le persone all'intimità, ma i medici sanno che è un errore. Nessun sito di tube è utile'istruzione. Le uniche affermazioni fatte riguardano lo shock, la novità e le crescenti qualità delle loro merci.

La pura ipocrisia è incredibile, come società siamo tesi al bullismo scolastico e all'oggettivazione del corpo umano. Rispetto al porno su Internet, questi problemi sono semplici brufoli. I numeri di coloro che ne sono dipendenti raggiungono nuove vette ogni anno, trascorrendo del tempo di qualità con persone in pixel immaginarie e illusorie a scapito della loro salute, virilità, energia e tempo. Di gran lunga il più grande assassino nelle relazioni, centinaia di migliaia di vite vengono rovinate ogni anno perché iniziano. I produttori di porno su Internet non fanno pubblicità nelle principali pubblicazioni -- non ne hanno bisogno, i nostri impulsi biologici ci portano alle soglie dei loro harem ben forniti, distribuendo campioni gratuiti come uno spacciatore locale. Al giorno d'oggi, i siti di tube non immagazzinano tanto la merce quanto incoraggiano i visitatori a pubblicare contenuti.

Com'è inutile che le compagnie pornografiche mostrino un avviso 18+ come deterrente per gli utenti minorenni, alcuni non si preoccupano nemmeno di farlo. Il porno su Internet colpisce tutti a tutte le età. "*Ti abbiamo avvertito del pericolo, è una tua scelta.*" è il loro atteggiamento. Prendono provvedimenti per verificare l'età? No, questo scoraggerebbe i loro clienti. Naturalmente, se la verifica dell'età è legiferata, troveranno semplicemente un altro paese da cui operare. Oppure pagheranno qualche "élite" per scrivere di come il proibizionismo abbia portato al contrabbando e alla creazione della mafia? È opportunamente dimenticata la questione del perché l'abrogazione del divieto non abbia comportato la riduzione delle vittime legate all'alcol e l'incapacità delle forze dell'ordine di controllare la crescita della mafia.

Possiamo affrontare questo problema in modo diverso educando le giovani generazioni. Se riescono a evitare sigarette e alcol durante lo shopping, possono fare lo stesso con il porno su Internet. Stiamo già assistendo a cambiamenti sociali come i meme "No Nut November" e "Coomer" che diventano mainstream. L'utente non ha scelta più di quanto ne abbia l'eroinomane. Gli utenti non decidono di diventare dipendenti, sono attirati in una sottile trappola. Se potessero scegliere, domani mattina gli unici utenti sarebbero gli adolescenti che hanno appena iniziato, convinti di poter smettere in qualsiasi momento se lo volessero.

Perché gli standard fasulli? Perché i tossicodipendenti da eroina sono visti come criminali, eppure possono registrarsi come tossicodipendenti e ottenere metadone e cure mediche adeguate per aiutarli a uscirne? Prova a registrarti come tossicodipendente, se vai dal tuo dottore per chiedere aiuto, ti diranno: "*Smettila di farlo così tanto, prova la moderazione*" che sai già che non funzionerà, o ti prescriverà farmaci pre affrontare la tua "depressione". Ancor peggio è il consiglio di andare a trovare veri partner, sul serio? Conoscono utenti che trovano migliore il porno e lo fanno alle spalle del loro partner. Alcune persone semplicemente non capiscono. Le campagne di paura non aiutano gli utenti a fermarsi, lo rendono più difficile. Tutto ciò che fanno è spaventare gli utenti, il che li fa desiderare di guardare ancora di più. Inoltre, non impediscono agli adolescenti di diventare agganciati. Gli adolescenti sanno che il porno uccide la loro libido, ma sanno anche che una sbirciatina non lo farà. Poiché la dipendenza è così diffusa, prima o poi l'adolescente, a causa delle pressioni sociali o della curiosità, tenterà una sola visita. Poiché il porno gratuito ha clip orribili, è probabile che ne diventino dipendenti.

Perché permettiamo che questo scandalo continui? Perché i governi non sviluppano campagne adeguate? Perché non ci viene detto che il porno su Internet è una droga e un veleno mortale, che non ti rilassa né ti dà fiducia, ma distrugge i tuoi nervi, che basta una sbirciatina per diventare dipendente? Perché non possono imporre la verifica dell'età richiedendo carte di credito registrate? Mindgeek, proprietario di molti dei principali siti porno, sta tentando di convincere i governi a utilizzare la propria soluzione proprietaria di verifica dell'età: non lasciare che lo facciano! *The Time Machine* di H. G. Well descrive un incidente in un lontano futuro in cui un uomo cade in un fiume. I suoi compagni siedono semplicemente intorno alla riva come bestiame ignaro delle grida della disperazione. Inumano e inquietante, proprio come l'apatia generale della società nei confronti della crisi del porno.

C'è un vento di cambiamento della società. Una palla di neve ha iniziato a rotolare giù per la collina e si spera che questo libro contribuirà a trasformarla in una valanga. Anche tu puoi aiutare diffondendo il messaggio.

Pertanto, per chiedere: se vedi qualcuno che lotta per usare la forza di volontà o tenta di abbandonare il porno, indirizzalo gentilmente verso questo metodo. Tuttavia, il vero compito a portata di mano è cambiare la narrativa sul porno in generale. Per favore, considera di prendere l'abitudine che se vedi online, o addirittura sperimenti in prima persona la normalizzazione del porno, mira con *rispetto* ad educarli e liberarli.

Occasionalmente potresti ricevere una reazione negativa, ma a volte un commento è tutto ciò che serve. Come molti hanno fatto prima di te, puoi aspettarti di ricevere messaggi da persone riconoscenti che ti ringraziano per la loro libertà.

## Avviso finale

Ora puoi goderti il resto della tua vita come un felice non utente. Per assicurarti di farlo, devi seguire queste semplici istruzioni.

1.  Conserva la pagina seguente nei tuoi segnalibri e fai riferimento ad essa tutte le volte che ti serve.

2.  Se inizi a invidiare un altro utente, renditi conto che è lui ad essere invidioso di te. Non sei stato privato. Loro lo sono.

3.  Ricorda che non ti è piaciuto essere un utente. Ecco perché ti sei fermato. Ti piace essere un non utente.

4.  Ricorda, non esiste solo una sbirciatina.

5.  Non dubitare mai della tua decisione di non guardare mai più il porno. Sai che è quella giusto.

6.  In caso di difficoltà, trova e contatta un terapista esperto di pornografia su Internet.
