# Le istruzioni

1.  Segui tutte le istruzioni.

2.  Mantieni una mentalità aperta.

3.  Inizia con una sensazione di euforia.

4.  Ignora tutti i consigli e le influenze che contrastano con EasyPeasy.

5.  Resisti a qualsiasi promessa di soluzione temporanea.

6.  Metti in chiaro le cose nella tua mente: Il porno non fornisce un vero piacere o un appoggio e tu non stai facendo un sacrificio. Non c'è nulla a cui rinunciare e non c'è motivo di sentirsi privati.

7.  Non aspettare a smettere, fallo subito!

8.  Prendi la decisione di non guardarlo mai più e non metterla mai in discussione.

9.  Ricorda che non esiste una sola sbirciatina.

10. Non guardare mai più il porno.

## Affermazioni

- Sono libero dalla schiavitù del porno.

- È facile ignorare i miei pensieri sul porno.

- Addio pensieri, addio pulsioni. Ecco le mie voglie.

- Concentro la mia mente subconscia per superare la dipendenza dal porno.

- Il porno mi ruba tempo, energia e vitalità.

- Sconfiggere il porno diventa esponenzialmente più facile giorno dopo giorno e sotto ogni aspetto.

- Mi piace e apprezzo il mio stile di vita libero dal porno, forte, felice, leggero e facile.

- Se mi guardo indietro e penso ai miei progressi, provo grande gioia e orgoglio per me stesso.

- Ogni volta che vedo altri utenti del porno sono più motivato a vedere me stesso rompere la catena.

- Tutta l'energia accumulata sta curando il mio corpo e la mia mente. Quindi, posso svolgere un lavoro più produttivo e stimolante verso i miei valori e obiettivi.

- Il mio cervello sta tornando in forma, si sta allenando grazie al fatto che io *non* faccio quello che facevo prima.

- Ora tutta quella forza di volontà repressa viene utilizzata per gestire lo stress leggero e le tensioni della vita.

- Fantastico, sono libero e non più schiavo!
