# O Método Fácil

O objetivo desse livro é te direcionar a um novo modo de pensar. Ao contrário do método tradicional de parar – em que você começa com um sentimento de estar subindo o Monte Everest e passa as próximas semanas ansiando e se sentindo privado - aqui você já começa com um sentimento de exaltação, como se tivesse sido curado de uma doença terrível. A partir de então, quanto mais você avança na vida, mais você vai olhar para esse momento e se perguntar por que você usou qualquer pornô em primeiro lugar. Você olhará para outros usuários com um sentimento de pena, ao invés de inveja.

Se você não é alguém que nunca foi viciado (lendo para seu parceiro) ou tenha parado (ou está nos dias de jejum de uma "dieta pornô"), é essencial que você continue usando até que você termine o livro completamente. Isso pode soar contraditório, e essa instrução para continuar se masturbando com pornografia causa mais objeções que qualquer outra, mas enquanto você continuar lendo seu desejo de usar pornografia vai diminuir gradualmente. **Leve a sério essa instrução: tentar sair do vício cedo não irá lhe beneficiar**

Muitos não terminam o livro porque sentem que têm que desistir de algo, alguns até leem uma linha por dia para procrastinar o evento de enfim parar de assistir. Olhe para isso da seguinte forma: o que você tem a perder? Se você não parar ao final do livro, você não está pior do que está agora. É como a Aposta de Pascal: uma aposta feita quando você não tem nada a perder e muitas chances de ganhar (e muito).

A propósito, se você não assistiu pornô há algumas semanas ou dias, mas não tem certeza de se você é um usuário, ex-usuário ou um não-usuário; ou você descobriu que o seu desejo de assistir pornografia tem diminuído conforme você absorve o material, então não use pornô para se masturbar enquanto você lê. Na verdade, você já é um não-usuário, mas temos que deixar seu cérebro se entender com seu corpo. Ao final do livro, você será um não-usuário feliz. O Método Fácil é completamente contrário ao método normal, onde se lista as consideradas desvantagens da pornografia e diz:
*"Se eu ficar tempo longo suficiente sem pornô, eventualmente o desejo vai desaparecer e eu posso desfrutar da vida de novo, livre da escravidão"*
Esse é o modo lógico, com milhares parando todo dia usando esse método. Contudo, é difícil ter sucesso pelas seguintes razões:

**Parar de se masturbar com pornografia não é o problema real.** Toda vez que você termina uma sessão, você parou de usar. Você pode ter fortes razões no primeiro dia da sua "dieta" de "uma a cada quatro dias" para dizer *"Não quero usar pornô, nem me masturbar mais."* Todos os usuários fazem, e as razões deles são mais poderosas que você pode imaginar. O problema real é o dia dois, dez, ou dez mil, quando num momento de fraqueza você dá "só uma olhadinha", quer outra e de repente você está viciado de novo.

**A consciência dos riscos à saúde gera mais medo, tornando mais difícil parar.** Diga a um usuário que está destruindo sua virilidade e a primeira coisa que ele irá fazer é procurar algo para levantar a dopamina: cigarro, álcool, ou até abrir o navegador e procurar pornografia.

**Todas as razões para parar na verdade tornam o processo de parar mais difícil.** Isso é por duas razões. Primeiro, estamos continuamente sendo forçados a abandonar nosso "pequeno amigo" ou alguma muleta, vício ou prazer (seja qual for a maneira que o usuário perceba). Segundo, elas criam uma "cortina". Nós não nos masturbamos pelas razões que devemos parar. A verdadeira questão é, por que queremos ou precisamos fazer isso?

Com o Método Fácil, nós (inicialmente) nos esquecemos das razões pelas quais queremos parar, encaramos o problema da pornografia de frente e perguntamos a nós mesmos as seguintes questões:

1. O que pornografia está fazendo por mim?

2. Eu realmente estou gostando?

3. Eu realmente preciso viver sabotando minha mente e corpo?

A bela verdade é que *toda pornografia* não faz nada para você. Deixe-me deixar mais claro, não é que as desvantagens de ser um usuário pesam mais que as vantagens, é que há ***ZERO*** vantagens em procurar pornografia.

A maioria dos usuários sentem necessidade de encontrar motivos para usar pornografia, mas todas as razões que eles encontram são falácias e ilusões.

Primeiramente nós vamos remover essas falácias e ilusões. Na verdade, você logo irá notar que não há nada para desistir. Não apenas isso, mas há ganhos positivos e maravilhosos em não ser mais um usuário -- sendo a felicidade e o bem-estar apenas dois desses ganhos. Uma vez que as ilusões de que a vida não será boa sem pornografia são removidas, percebemos que não só a vida é boa sem isso, mas infinitamente melhor; e uma vez que os sentimentos de estar sendo privado ou de se estar perdendo algo são erradicados, nós voltaremos a reconsiderar o aumento de bem-estar e felicidade (e outras milhares de razões para sair da pornografia). Esses entendimentos se tornarão auxílios adicionais positivos para te ajudar a alcançar o que você realmente deseja: **desfrutar a sua vida livre da escravidão do vício em pornografia!**

## A Armadilha Sinistra

A pornografia online é a armadilha mais sutil e sinistra que o homem, combinado com a natureza, criou. Alguns de nós somos até avisados sobre os perigos, mas não conseguimos acreditar que quem está usando não está gostando. Mas o que nos leva a isso em primeiro lugar? Geralmente, amostras grátis de amadores ou profissionais que compartilham. Assim é que a armadilha floresce, sua primeira ’espiada’ tem manchas e buracos. A maioria das imagens de capa de qualquer página pornográfica é composta de atrizes amadoras e clipes feitos em casa por modelos desconhecidas. Se o primeiro olhar tivesse apenas modelos lindas, profissionais e angelicais, então um alarme interno soaria.

Porém o alarme não soa. Talvez devido à natureza chocante de muitos vídeos, nossas mentes jovens reafirmam que nunca nos viciaremos, pensando que já que não gostamos, podemos parar quando quisermos. Ou talvez a aparente inocência de materiais mais leves não acione nenhum alarme. Como seres humanos inteligentes, entenderíamos o porquê da metade da população adulta ter se tornado sistematicamente viciada em algo que tira o potencial de realizar o que eles estão vendo. A curiosidade nos leva para perto da porta, mas não ousamos clicar em alguns vídeos, temendo que isso nos tornará doentes ou nos colocar em caminho perigoso e imoral. E se você acidentalmente clicasse em um, seu único desejo seria sair da página o mais rápido possível, enquanto ao mesmo te deixaria ainda mais desesperadamente curioso.

Uma vez que esse processo iniciou, estamos presos na armadilha. A partir de então passamos o resto de nossas vidas tentando entender o porquê de fazermos isso, dizendo às nossas crianças para nunca começarem, e em alguns momentos inoportunos tentando escapar. A armadilha é feita de forma que tentamos parar somente por causa de um ’incidente’, seja performance sexual, perda de carreira ou relacionamentos, perda de motivação ou simplesmente se sentindo como um leproso. Assim que paramos de usar, sentimos mais estresse por causa dos anseios que vêm com a retirada. E com o modo de “remover” o estresse que tínhamos a falsa impressão de possuir indisponível.

Nossa decisão de quitar então se mostra frágil. Depois de uns dias de tortura tomamos a decisão de que escolhemos a hora errada para parar, decidindo que esperaremos por períodos sem estresse, que ao chegar tira nossos motivos para parar. Claro, essa época nunca chegará completamente, visto que que intencionalmente acreditamos que nossas vidas tendem a se tornarem mais e mais estressantes. Sair da casa dos pais, estresses de trabalho, arrumar a casa, aluguéis, bebês, maiores casas e mais bebês: tudo isso é estressante e enche as nossas vidas. Isso é uma ilusão. A verdade é que o período mais estressante na vida de qualquer criatura é o início da infância e a adolescência.
Tendemos a confundir responsabilidade com estresse. A vida de um usuário -- como a de um viciado em droga -- automaticamente se torna mais estressante porque a pornografia não te ajuda a relaxar ou a aliviar o estresse, como alguns tentam fazer você acreditar. É justamente o contrário: ela causa mais estresse enquanto você continua usando, colocando mais carga nas suas costas. Até usuários que param com o hábito (como muitos fazem uma ou mais vezes durante a vida) podem levar vidas felizes e repentinamente se viciarem de novo. Passeando no labirinto da pornografia, nossas mentes se tornam nebulosas e passamos o resto de nossas vidas tentando escapar. Alguns obtêm sucesso, apenas para cair na armadilha sinistra depois de um tempo.

O vício em pornografia é como uma charada. É complexo e difícil. Mas uma vez que você percebe a resposta, é simples e divertido, e você se pergunta porque não pensou nisso antes! O Método Fácil contém a solução para esse quebra-cabeça, te levando para fora do labirinto para nunca mais voltar a vagar nele. **Tudo que você tem que fazer é seguir cada instrução ao pé da letra**. Entretanto, se você seguir **o caminho errado ao pular capítulos**, ou **fingir que está lendo o livro na velocidade da luz** sem fazer um esforço real na sua primeira leitura, então o resto das instruções passa a não fazer sentido.

Todo mundo pode achar fácil parar, mas primeiro precisamos estabelecer alguns fatos. Não, não são fatos feitos para te assustar, há mais do que informações suficientes por aí para cumprir esse propósito. Se isso fosse te fazer parar, você já teria parado. Mas por que achamos difícil parar? Responder isso nos requer saber o verdadeiro motivo que nos faz continuar a usar pornografia, resumindo em dois fatores. Sendo eles:

-   Natureza e pornografia.

-   Lavagem cerebral.

Usuários de pornografia são seres humanos inteligentes e racionais. Eles sabem que estão tomando riscos futuros grandes, então eles passam bastante tempo racionalizando o ’hábito’. Mas usuários de pornografia no seu coração sabem que agem feito imbecis, sabem que não possuíam a necessidade de usar pornografia antes de se tornarem viciados. A maioria lembra que a primeira ’espiada’ foi um misto de repulsa e curiosidade. Logo, então, eles se especializam em encontrar, filtrar, e favoritar sites, se esforçando para ficarem viciados.

Mais irritantemente, há a sensação de que não-viciados -- a maioria mulheres, homens mais velhos e pessoas vivendo em países onde conexões rápidas de Internet são indisponíveis -- não estão perdendo nada e acham essa situação risível. Ao desmontar esses fatores no próximo capítulo, você também entenderá a armadilha sinistra!
