# De makkelijke manier

Dit boek heeft als doel je een nieuwe manier van denken bij te brengen. In plaats van de gebruikelijke methode om te stoppen—waarbij je begint met het gevoel dat je de Mount Everest moet beklimmen en de komende weken verlangend en beroofd voelt—begin je hier meteen met een gevoel van opluchting, alsof je genezen bent van een verschrikkelijke ziekte. Vanaf dat moment, hoe verder je in het leven gaat, hoe meer je zult terugkijken op deze periode en je afvragen hoe je ooit in de eerste plaats porno hebt kunnen gebruiken. Je zult met medelijden naar andere pornogebruikers kijken, in plaats van met jaloezie.

Tenzij je iemand bent die nooit verslaafd is geraakt (en leest voor je partner) of al gestopt is (of zich in de 'vasten' dagen van een 'pornodieet' bevindt), is het essentieel om door te blijven gaan met het kijken naar porno totdat je het boek helemaal hebt uitgelezen. Dit lijkt misschien een tegenstrijdigheid, en deze instructie om door te gaan met masturberen terwijl je porno kijkt veroorzaakt meer bezwaar dan welke andere dan ook, maar naarmate je verder leest, zal je verlangen om porno te gebruiken geleidelijk afnemen. Neem deze instructie serieus: proberen om te stoppen terwijl je het boek nog aan het lezen bent, zal je niet ten goede komen.

Veel mensen maken het boek niet af omdat ze het gevoel hebben dat ze iets moeten opgeven. Sommigen lezen zelfs opzettelijk maar één regel per dag om het ‘nare moment’ uit te stellen. Bekijk het op deze manier: wat heb je te verliezen? Als je niet stopt aan het eind van het boek, ben je er niet slechter aan toe dan nu. Het is per definitie een ‘Weddenschap van Pascal’, een gok waarbij je niets te verliezen hebt en grote winstkansen.

Overigens, als je al een paar dagen of weken geen porno hebt gekeken, maar niet zeker weet of je een gebruiker, ex-gebruiker of niet-gebruiker bent; of als je merkt dat je verlangen om porno te kijken is afgenomen naarmate je het materiaal in je opneemt, dan moet je geen porno gebruiken om te masturberen terwijl je leest. Sterker nog, je bent al een niet-gebruiker, maar we moeten je hersenen nog laten inhalen op je lichaam. Aan het eind van het boek ben je een gelukkige niet-gebruiker. EasyPeasy is het tegenovergestelde van de normale methode, waarbij men de aanzienlijke nadelen van porno opsomt en zegt: _“Als ik maar lang genoeg zonder porno kan, zal het verlangen uiteindelijk verdwijnen en kan ik weer genieten van het leven, vrij van slavernij.”_

Dit is de logische manier om het aan te pakken, en duizenden stoppen elke dag met deze methode. Echter, het is erg moeilijk om te slagen om de volgende redenen:

Stoppen met PMO is niet het echte probleem. Elke keer dat je je sessie beëindigt, ben je gestopt met gebruiken. Op de eerste dag van je vierjaarlijkse 'pornodieet' heb je misschien krachtige redenen om te zeggen: _“Ik wil geen porno meer gebruiken, of zelfs niet meer masturberen.”_ Alle gebruikers doen dat, en hun redenen zijn krachtiger dan je je kunt voorstellen. Het echte probleem is dag twee, tien, of tienduizend, wanneer je in een zwak moment 'even een kijkje' neemt, nog een wilt, en plotseling ben je weer verslaafd.


Bewustzijn van de gezondheidsrisico’s zorgt voor meer angst, wat het moeilijker maakt om te stoppen. Vertel een gebruiker dat het hun mannelijkheid vernietigt en het eerste wat ze zullen doen, is grijpen naar iets om hun dopamine op te schroeven: een sigaret, alcohol, of zelfs de browser openen om naar porno te zoeken.

Alle redenen om te stoppen maken het eigenlijk moeilijker. Dit komt door twee redenen:
- Ten eerste worden we voortdurend gedwongen om afscheid te nemen van ons 'kleine vriendje' of een andere steunpilaar, ondeugd of genot (hoe de gebruiker het ook ziet). 
- Ten tweede creëren ze een 'blinddoek'. We masturberen niet om de redenen waarom we zouden moeten stoppen. De echte vraag is: waarom willen of moeten we het doen?

Met EasyPeasy vergeten we (in eerste instantie) de redenen waarom we zouden willen stoppen, en stellen we onszelf de volgende vragen over het pornoprobleem:
1.  Wat doet porno voor mij?
2.  Geniet ik er eigenlijk van?
3.  Moet ik echt mijn leven doorbrengen door mijn geest en lichaam te saboteren?

De prachtige waarheid is dat alle porno absoluut niets voor je doet, **helemaal niets**. Laat me het heel duidelijk maken, het is niet zo dat de nadelen van het een gebruiker zijn opwegen tegen de voordelen, het is dat er geen enkel voordeel is aan het kijken naar porno. 

De meeste gebruikers vinden het nodig om te rationaliseren waarom ze porno gebruiken, maar de redenen die ze bedenken, zijn allemaal drogredenen en illusies. Eerst zullen we deze drogredenen en illusies wegnemen. Je zult namelijk al snel beseffen dat er niets is om op te geven. Sterker nog, er zijn geweldige, positieve voordelen van het niet meer gebruiken van porno, met welzijn en geluk als slechts twee van die voordelen. Zodra de illusie verdwijnt dat het leven zonder porno nooit meer zo leuk zal zijn—en je je realiseert dat het leven niet alleen net zo leuk is zonder, maar zelfs oneindig veel leuker—en zodra gevoelens van gemis of tekortkoming verdwijnen, zullen we opnieuw kijken naar het toegenomen welzijn en geluk, en de tientallen andere redenen om met porno te stoppen. Deze inzichten zullen positieve extra hulpmiddelen worden om je te helpen bereiken wat je echt wilt: genieten van je leven, vrij van de slavernij van pornoverslaving!