# Tijd besparen

Wanneer gebruikers proberen te stoppen, worden de belangrijkste redenen vaak genoemd: gezondheid, religie en het stigma van hun partner. Een van de aspecten van deze verschrikkelijke verslaving is de pure slavernij ervan; de mens heeft hard gevochten om slavernij in veel delen van de wereld af te schaffen — en toch lijdt de gebruiker aan zelfopgelegde slavernij. Ze beseffen niet dat wanneer ze porno mogen kijken, ze wensen dat ze geen gebruiker waren. Porno wordt alleen kostbaar op momenten dat we proberen te minderen, te stoppen of wanneer onthouding ons wordt opgelegd.

Het kan niet vaak genoeg herhaald worden dat hersenspoeling het moeilijk maakt om met porno te stoppen, dus hoe meer we deze hersenspoeling ontkrachten voordat we beginnen, hoe makkelijker het zal zijn om je doel te bereiken. Porno-gebruiker s die niet geloven dat porno negatieve effecten heeft op hun gezondheid (zoals door porno veroorzaakte erectiestoornissen, hypofrontaliteit, enz.) en geen innerlijke strijd voeren, zijn meestal jonger of single en hebben af en toe een seksuele partner. Hierdoor gaat de interne feedback verloren door hun jeugdigheid of is deze te zeldzaam om opgemerkt te worden.

Een beter argument voor jongere gebruikers is de tijd die ze besteden. In plaats van te zeggen: "Ik kan niet geloven dat je je geen zorgen maakt over de tijd die je eraan besteedt," kun je zeggen: “Laten we eens aannemen dat je dagelijks gemiddeld een half uur besteedt, inclusief de fysieke uitputting door dopamineonttrekking. Je besteedt dan ongeveer een volledige werkdag om de twee weken aan porno. Ik ben er zeker van dat een half uur per dag een conservatieve schatting is. Heb je wel eens nagedacht over hoeveel tijd je in je leven hieraan zult besteden? Wat doe je in die tijd? Ontwikkel je echte relaties? Nee, je favoriete pornoster heeft geen medelijden met je omdat je zoveel tijd aan hun video's hebt besteed — je gooit tijd weg! Niet alleen dat, je gebruikt die tijd om je fysieke gezondheid te ruïneren, je zenuwen en zelfvertrouwen te vernietigen, zodat je een leven vol slavernij, pijn, melancholie en prikkelbaarheid tegemoet gaat. Dat moet je toch wel zorgen baren?”

Op dit punt wordt het duidelijk — vooral bij jongere gebruikers — dat ze nooit hebben overwogen dat dit een levenslange verslaving kan zijn. Soms rekenen ze uit hoeveel tijd ze in een week verspillen, en dat is al alarmerend genoeg. Heel af en toe, en alleen wanneer ze overwegen te stoppen, schatten ze in wat ze in een jaar besteden, wat beangstigend is — maar over een heel leven is ondenkbaar. Omdat we in een discussie zitten, zal de porno-gebruiker impulsief zeggen: "Ik kan het me veroorloven, het is maar zoveel per week," waarbij ze zichzelf voor de gek houden.
		
Zou je een baan afslaan die je huidige jaarsalaris betaalt en je naast je normale vrije dagen een extra maand vrij per jaar geeft? Elke gebruiker zou meteen tekenen en beginnen met het zoeken naar vakantieaanbiedingen naar exotische locaties. Het grootste probleem zou zijn hoe je een volledige maand zonder werk zou doorbrengen. In elke discussie met een porno-gebruiker (en houd er rekening mee dat dit niet iemand zoals jij is die van plan is te stoppen) heeft nog nooit iemand dit aanbod aangenomen. Waarom niet?

Op dit punt zal een porno-gebruiker vaak zeggen: "Kijk, ik maak me echt geen zorgen over het financiële aspect." Als je zo denkt, vraag jezelf dan af waarom je je geen zorgen maakt. Waarom doe je in andere aspecten van je leven veel moeite om een paar euro’s te besparen, maar besteed je duizenden euro's aan iets dat je geluk vernietigt en de kosten voor lief neemt?

Elke andere beslissing die je in je leven neemt, is het resultaat van een analytisch proces waarbij je de voor- en nadelen afweegt om tot een rationele beslissing te komen. Het kan de verkeerde beslissing zijn, maar het zal het resultaat zijn van rationele deductie. Telkens wanneer een gebruiker de voor- en nadelen van internetporno overweegt, is het antwoord keer op keer: "STOP MET GEBRUIKEN! JE BENT EEN SUKKEL!" Daarom gebruiken alle gebruikers niet omdat ze willen of beslissen om te gebruiken, maar omdat ze niet kunnen stoppen. Ze moeten porno gebruiken en hersenspoelen zichzelf om hun hoofd in het zand te steken.

Porno-gebruiker s moeten in gedachten houden dat de situatie alleen maar exponentieel erger zal worden, met meer studies die uitkomen en meer mensen die praten over de nadelige effecten van internetporno. Vandaag de dag zijn het nog niet-medische mensen die de effecten bespreken, maar morgen staat het op de lijst met diagnostische tests van je arts. De dagen zijn voorbij dat de gebruiker zijn ‘downtime’ op seksueel gebied achter werkstress kan verbergen; je partner gaat vragen waarom je ’s avonds laat op je laptop zit. De arme gebruiker — die zich al ellendig voelt — wil nu het liefst door de grond zakken.

Het vreemde is dat hoewel veel mensen veel geld zouden betalen voor sportschoolabonnementen en personal trainers om spieren op te bouwen en er goed uit te zien (en velen van hen, in hun denkbeeldige (en echte) wanhoop, hun toevlucht nemen tot behandelingen zoals testosteronboosters, met dubieuze en gevaarlijke bijwerkingen), er veel mensen in deze groep zijn die zouden profiteren van het stoppen met een praktijk die systematisch de natuurlijke ontspanningssystemen van hun hersenen vernietigt.

Dit komt omdat ze nog steeds denken met de gehersenspoelde geest van de gebruiker. Veeg het zand uit je ogen voor een moment. Internetporno is een kettingreactie en een ketting voor het leven, en als je die ketting niet breekt, blijf je de rest van je leven een gebruiker. Schat hoeveel tijd je denkt te zullen besteden aan porno voor de rest van je bestaan. Uiteraard zal het bedrag variëren van persoon tot persoon, maar laten we aannemen dat het anderhalf jaar aan werkuren is. Stel je voor dat er morgen een cheque van de loterij op je tapijt ligt voor anderhalf jaar van je salaris? Je zou van vreugde dansen, dus begin maar met dansen! Je staat op het punt om die voordelen te gaan ontvangen!

Als je denkt dat dit een slimme manier is om het te bekijken, houd je jezelf voor de gek. Reken uit hoeveel tijd je zou hebben bespaard als je nooit je eerste blik had geworpen, helemaal aan het begin.

Binnenkort zul je de beslissing nemen om je laatste sessie te gebruiken (nog niet, onthoud de instructies!), en door niet opnieuw in de val te trappen, een niet-gebruiker blijven. Het enige wat je hoeft te doen om een niet-gebruiker te blijven, is geen porno te gebruiken en te vermijden dat je ‘slechts één blik werpt’. Onthoud dat als je dat doet, het je zal kosten wat je had geschat als je salariswinst.

Als je iemand begeleidt bij hun pornoverslaving, vertel ze dan dat ze iemand kennen die een baanaanbod heeft geweigerd dat hun huidige jaarsalaris betaalt en hen ook een volledige maand betaald verlof geeft. Wanneer ze vragen wie die idioot is, zeg je: “Jij!” Het is grof, maar soms moet je het punt op een minder beleefde manier overbrengen.