# Normale gebruikers

Mensen die veel porno kijken, wensen vaak dat ze net als anderen waren die het maar af en toe doen. We kennen allemaal zulke mensen: "Oh, ik kan een hele week zonder een sessie, het stoort me echt niet." We wensen dat we ook zo waren. Dit is misschien moeilijk te geloven, maar geen enkele gebruiker geniet ervan om een gebruiker te zijn. Vergeet nooit: Geen enkele gebruiker heeft ooit besloten om er een te worden, casual of niet, dus, Alle gebruikers voelen zich dom, en daarom moeten alle gebruikers tegen zichzelf en anderen liegen in een vergeefse poging hun domheid te rechtvaardigen.

Golfliefhebbers pronken met hoe vaak ze spelen en willen spelen, dus waarom pochen gebruikers over hoe weinig ze masturberen? Als dat het echte criterium is, dan zou de hoogste eer toch zijn helemaal niet te masturberen, nietwaar?
Als iemand tegen je zou zeggen: "Ik kan een hele week zonder wortels en het stoort me helemaal niet," zou je denken dat je met een gek praat. Als ik van wortels hou, waarom zou ik dan een hele week zonder willen? En als ik er niet van hou, waarom zou ik zo’n opmerking maken? Dus wanneer een gebruiker een opmerking maakt over een week zonder een sessie te overleven, proberen ze zichzelf — en jou — ervan te overtuigen dat ze geen probleem hebben. Maar er zou geen reden zijn om zo'n opmerking te maken als er geen probleem was. In werkelijkheid zeggen ze: "Ik heb een hele week zonder porno overleefd." Zoals elke gebruiker hopen ze dat ze na die week de rest van hun leven zonder kunnen. Maar als je maar net een week kunt overleven, kun je je voorstellen hoe waardevol de sessie daarna moet zijn geweest, nadat ze zich een hele week beroofd hebben gevoeld?

Dit is waarom casual gebruikers eigenlijk meer verslaafd zijn dan zware gebruikers. Niet alleen is de illusie van plezier groter, maar ze hebben ook minder motivatie om te stoppen omdat ze er minder tijd aan besteden en daardoor minder kwetsbaar zijn voor gezondheidsrisico’s. Af en toe kunnen ze last krijgen van seksuele disfunctie, maar ze weten niet waardoor het komt en wijten het dus aan andere factoren. Onthoud dat het enige plezier dat gebruikers krijgen in de zoek-en-vind-dopaminecyclus zit en in het verlichten van de ontwenningsverschijnselen, zoals al eerder uitgelegd. Het plezier is een illusie — stel je het kleine pornomonster voor als een bijna onmerkbare jeuk waar we meestal niet van bewust zijn.

Als je een permanente jeuk hebt, is de natuurlijke neiging om te krabben. Naarmate de beloningscircuits steeds minder gevoelig worden voor dopamine en opioïden, is de natuurlijke neiging om te 'edge-en', escaleren, binge-kijken, op zoek te gaan naar nieuwigheid, schokerend materiaal, enz. Er zijn vier belangrijke factoren die gebruikers ervan weerhouden om continu te kijken.


1.	Tijd. De meesten kunnen zich dat niet veroorloven.
2.	Gezondheid. Om de jeuk te verlichten, moeten we al het beschikbare gratis materiaal consumeren en meer. Het vermogen om met dat soort binge-gedrag om te gaan verschilt per individu en varieert op verschillende momenten en in verschillende situaties in hun leven. Dit werkt als een automatische beperking.
3.	Discipline. Discipline wordt opgelegd door de maatschappij, door het werk van de gebruiker, vrienden en familie, of misschien zelfs door de gebruiker zelf als gevolg van de natuurlijke innerlijke strijd die in elke gebruiker plaatsvindt.
4.	Verbeelding. Gebrek aan verbeelding speelt de schok, nieuwigheid en andere waarden van de clip op een subjectieve basis naar beneden.

Het is makkelijk om niet-casual gebruikers als zwak te beschouwen, niet in staat te begrijpen waarom anderen hun 'inname' kunnen beperken. Zware gebruikers moeten echter in gedachten houden dat de meeste casuale gebruikers simpelweg niet in staat zijn om aan een binge te beginnen, wat een zeer sterke verbeeldingskracht en uithoudingsvermogen vereist. Sommige van deze een-keer-per-week-gebruikers, die zware gebruikers vaak benijden, zijn fysiek niet in staat om meer te doen, of hun baan, de maatschappij, of hun eigen afkeer van verslaving laat het niet toe.

Het kan nuttig zijn om een paar definities te geven van verschillende gebruikers.

**De Niet-gebruiker**
Iemand die nooit in de val is gelopen maar niet zelfgenoegzaam moet zijn. Ze zijn alleen een niet-gebruiker door geluk of genade. Alle gebruikers waren ervan overtuigd dat ze nooit verslaafd zouden raken en sommige niet-gebruikers blijven af en toe een sessie proberen.

**De Casuale Gebruiker
Er zijn twee basiscategorieën:**

De gebruiker die in de val is gelopen maar het niet beseft – benijd zulke gebruikers niet. Ze proeven slechts de nectar aan de mond van de bekerplant en zullen hoogstwaarschijnlijk snel zware gebruikers worden. Onthoud, net zoals alle alcoholisten begonnen als casuale drinkers, zo beginnen alle gebruikers als casuale gebruikers.
De gebruiker die vroeger een zware gebruiker was en denkt dat ze niet kunnen stoppen. Deze gebruikers zijn de triestste van allemaal en vallen in verschillende categorieën, die elk afzonderlijk commentaar vereisen.

**De Een-keer-per-dag Gebruiker**
Als ze genieten van hun recht op een orgasme, waarom gebruiken ze dan maar één keer per dag internetporno? Als ze het kunnen nemen of laten, waarom doen ze dan überhaupt de moeite? Onthoud, de 'gewoonte' is in werkelijkheid je hoofd tegen een muur slaan om het ontspannend te vinden wanneer je stopt. De een-keer-per-dag-gebruiker verlicht hun ontwenningsverschijnselen minder dan een uur per dag. Hoewel ze zich er niet van bewust zijn, brengen ze de rest van hun dag door met hun hoofd tegen deze muur te slaan, en dat doen ze voor het grootste deel van hun leven. Ze gebruiken één keer per dag omdat ze het risico niet kunnen lopen betrapt te worden of hun neurologische gezondheid te schaden. Het is makkelijk om de zware gebruiker ervan te overtuigen dat ze er niet van genieten, maar aanzienlijk moeilijker om een casuale gebruiker te overtuigen. Iedereen die heeft geprobeerd te minderen, weet dat het de ergste marteling is, en bijna gegarandeerd je voor de rest van je leven verslaafd houdt.


**De afgewezen Gebruiker**
Ze eisen het recht op een dagelijks orgasme, maar hun sekspartner is niet altijd bereid om aan dat verzoek te voldoen. In eerste instantie gebruiken ze internetporno om dit gemis op te vullen, maar zodra ze de spannende ‘waterglijbaan’ nemen, zitten ze vast in een cyclus van nieuwigheid, schokken, supernormale beelden, enz. Eigenlijk zijn ze blij met de afwijzing van hun partner, omdat het hen een excuus biedt. Als internetporno je zoveel geeft, waarom zou je dan überhaupt een partner hebben? Laat ze in plaats daarvan vrij. Ze genieten niet eens van sessies wanneer ze hun partner in gedachten moeten 'meedragen'. Op een gegeven moment hopen ze dat hun partner hen een excuus geeft om de duistere valleien van het internet te verkennen.

**De Porno-dieet Gebruiker**
Ook wel bekend als: "Ik kan stoppen wanneer ik wil. Ik heb het duizenden keren gedaan!" Als ze denken dat diëten hen helpt in de stemming te komen om partners op te pikken, waarom zitten ze dan überhaupt op een dieet van één keer in de vier dagen? Niemand kan de toekomst voorspellen, en wat als het toeval van een ontmoeting zich voordeed een uur na je geplande sessie? Bovendien, als af en toe 'de leidingen schoonmaken' goed is om spanning te verlichten, waarom zou je dan niet elke dag ontluchten? Het is bewezen dat masturbatie niet nodig is om de geslachtsorganen gezond te houden en internetporno is helemaal niet nodig. Zelfs als dat het geval is, zal geen enkele pick-up-goeroe die heeft gelezen over de neurologische schade ooit aanraden om superstimulerende porno te kijken. De waarheid is dat de porno-dieet gebruiker nog steeds verslaafd is. Hoewel ze van de fysieke verslaving af zijn, blijven ze zitten met het primaire probleem van hersenspoeling. Ze hopen elke keer dat ze voorgoed stoppen, maar vallen al snel weer voor dezelfde val.

De meeste gebruikers benijden deze stoppers-en-starters eigenlijk en denken hoe 'gelukkig' de diëter is dat hij zijn gebruik kan beheersen. Maar ze zien over het hoofd dat de diëter zijn gebruik niet beheerst — wanneer ze gebruiken, wensen ze dat ze het niet deden. Ze gaan door de moeite van stoppen, beginnen zich dan beroofd te voelen en vallen weer voor de val, waarna ze wensen dat ze dat niet hadden gedaan. Ze krijgen het slechtste van beide werelden. 
Voor de dietgebruiker is dit de werkelijkheid: — ze verlangen nog steeds naar porno terwijl ze wensen dat ze dat niet deden. Pas wanneer ze zich onthouden, wordt porno waardevol. Het ‘verboden-vrucht’-syndroom is een van de verschrikkelijke dilemma’s voor gebruikers. Ze kunnen nooit winnen, want ze zijn verdrietig om een mythe, een illusie. Er is maar één manier waarop ze kunnen winnen, en dat is stoppen met verdrietig zijn door te stoppen met porno!


**De "Ik kijk alleen naar simpele/onschuldige/zelfgemaakte porno" gebruiker.**
Iedereen begint hiermee, maar het is opvallend hoe snel de gemiddelde schokwaarde van de video's lijkt toe te nemen. Voordat je het weet, voel je je ontevreden (tolerantie). De nieuwigheid ontbreekt bij statische porno, dus geven we toe aan de verleiding en glijden we af naar wrok en schuldgevoel. Het slechtste wat je kunt doen is de foto's van je partner gebruiken (met toestemming natuurlijk) om te masturberen. Waarom? Omdat je in dat proces je brein opnieuw bedraad voor de dopamineflitsen die worden veroorzaakt door het zoeken en verlangen naar variatie. Chemisch gezien is het effect op het brein te vergelijken met het opbouwen van DeltaFosB, waardoor je problemen zult ondervinden wanneer je daadwerkelijk samen bent met je partner.

Een andere valkuil in deze categorie is ‘amateur’ en ‘huisgemaakte’ porno. De meeste zijn nep, en dat weet je ook, plus je stopt niet bij de eerste die je ziet, je blijft zoeken. Onthoud, het gaat je brein niet alleen om het orgasme, maar ook om de nieuwigheid van de jacht die de ervaring spannend maakt. De inhoud van de porno is niet het probleem — of het nu amateur of professioneel is — het zijn de dopamineflitsen in je brein die leiden tot tolerantie en verzadiging. Porno verstoort de normale werking van het brein, en masturbatie verstoort de spier-brein respons; orgasme overspoelt het brein met opioïden en maakt de weg vrij voor een volgend keer.


**De "Ik ben gestopt, maar werp af en toe een blik" gebruiker**
Op een bepaalde manier zijn gebruikers die af en toe ‘pieken’ het meest zielig van allemaal. Of ze gaan hun leven door met het gevoel dat ze iets missen, of de occasionele blik wordt er één te veel, waardoor ze weer langzaam afglijden naar hun oude gewoonte en uiteindelijk weer zware gebruikers worden. Ze zijn opnieuw in dezelfde val getrapt als in het begin.

Er zijn nog twee andere categorieën van **gelegenheidsgebruikers**. 
**De eerste is het type dat masturbeert op beelden of video's van de nieuwste celebrity-sekstapes** die in het nieuws komen, of iets wat ze ‘per ongeluk’ zagen op school of werk. Deze mensen zijn eigenlijk gewoon niet-gebruikers, maar ze hebben het gevoel dat ze iets missen. Ze willen deel uitmaken van de actie, net zoals de meesten van ons begonnen zijn. Let de volgende keer maar op, na een tijdje doet de celebrity uit je fantasie het niet meer voor je. Hoe meer ‘onbereikbaar’ het doel van je fantasie is, hoe frustrerender het uitblijven van het orgasme wordt.

**De tweede categorie** krijgt de laatste tijd meer aandacht, het best beschreven aan de hand van een geval dat online werd gedeeld. Een professionele vrouw had jarenlang internetpornografie gelezen en gebruikte het nooit meer of minder dan één keer per nacht. Ze was een zeer wilskrachtige vrouw. De meeste gebruikers zouden zich afvragen waarom ze überhaupt wilde stoppen – en zouden snel opmerken dat er geen risico was op PIED (porn-induced erectile dysfunction) of PE (premature ejaculation) in haar geval (niet waar). Ze gebruikte niet eens statische beelden, de verhalen waren veel milder dan het materiaal dat ze dagelijks gebruikten.

Men maakt de fout te denken dat gelegenheidsgebruikers gelukkiger en meer in controle zijn. Ze zijn misschien meer in controle, maar ze zijn zeker niet gelukkig. In het geval van de vrouw was ze niet tevreden met haar partner, noch met echte seks, en was ze zeer prikkelbaar in haar dagelijkse leven. Haar naasten konden niet begrijpen wat haar dwarszat. Zelfs als ze zichzelf overtuigde dat ze niet bang hoefde te zijn voor haar gebruik door het te rationaliseren, vond ze het nog steeds moeilijk om te genieten van echte relaties, die onvermijdelijk ups en downs kennen. Het beloningscentrum van haar brein kon niet meer normaal reageren op de dagelijkse stress omdat het constant overstroomd werd met dopamine. De daaropvolgende downregulatie van de receptoren in haar brein maakte haar melancholisch in de meeste situaties.

Alle genot dat je uit porno haalt, is het verlichten van de drang die ervoor al aanwezig was, of dat nu een bijna onmerkbare fysieke drang is of de mentale kwelling van het niet mogen krabben aan de jeuk. Internetporno is zelf vergif, en daarom lijkt het alleen maar alsof je ervan geniet na periodes van onthouding. Net als honger of dorst, hoe langer je het verdragen hebt, hoe groter het ‘genot’ wanneer je het eindelijk verlicht. De fout maken door te denken dat porno slechts een gewoonte is, leidt tot het denken: “Als ik het op een bepaald niveau kan houden of alleen op speciale gelegenheden, zal mijn brein en lichaam het accepteren. Dan kan ik het op dat niveau houden of verder verminderen als ik dat wil.”

Zorg ervoor dat het duidelijk is in je hoofd: de 'gewoonte' bestaat niet. Porno is verslaving aan drugs, waarbij de natuurlijke neiging is om afkickverschijnselen te verlichten, niet om ze te verdragen. Om het op het niveau te houden waar je nu bent, zou je de rest van je leven enorme hoeveelheden discipline en wilskracht moeten uitoefenen. Terwijl het beloningscentrum in je brein tolerant wordt voor dopamine en opioïden, wil het steeds meer, niet minder.

Terwijl porno je zenuwstelsel, moed, zelfvertrouwen en impulscontrole geleidelijk vernietigt, wordt je steeds minder in staat om de verleiding te weerstaan en de tijd tussen elke sessie te verkorten. Daarom kunnen we het in het begin nemen of laten. Als we iets opmerken dat mentaal of fysiek niet goed gaat, stoppen we gewoon. Wees niet jaloers op deze vrouw — als je maar één keer per vierentwintig uur kijkt, lijkt het het kostbaarste op aarde, waardoor porno een ‘verboden vrucht’ wordt. Veel jaren was deze arme vrouw het middelpunt van een innerlijk gevecht.

Hoewel ze niet in staat was om te stoppen met gebruiken, was ze bang om over te gaan op het streamen van clips. Gedurende drieëntwintig uur en tien minuten van elke dag moest ze de verleiding en het gebrek aan gevoelens jegens haar vriendje bestrijden. Het vergde enorm veel wilskracht om te doen wat ze deed, uiteindelijk bracht het haar tot tranen. Dergelijke gevallen zijn zeldzaam, maar bekijk het logisch: ofwel is er een oprecht hulpmiddel of plezier in porno, of niet. Als dat wel zo is, wie wil er dan een uur, een dag of zelfs een week wachten? Waarom zou je in de tussentijd van het hulpmiddel of plezier worden beroofd? Als er geen oprecht hulpmiddel of plezier is, waarom zou je dan überhaupt een bezoek brengen aan je online harem?

Hier is nog een geval van een man die eens in de vier dagen kijkt, waarbij hij zijn leven als volgt beschrijft:

> " *Ik ben veertig jaar oud en ik heb last van PIED (pornogerelateerde erectiestoornis) gehad bij echte vrouwen, zelfs wanneer ik porno gebruik, wat meestal het geval is. Het is al een tijdje geleden dat ik een volledige erectie heb gehad. Voordat ik overstapte naar het eenmaal-in-de-vier-dagen-pornodieet, sliep ik na mijn sessie altijd goed door de nacht. Nu word ik elke uur van de nacht wakker en het is het enige waar ik aan kan denken. Zelfs als ik slaap, droom ik over mijn favoriete clips. Op dagen na mijn geplande sessie voel ik me behoorlijk bedroefd, het dieet kost al mijn energie. Mijn partner laat me met rust omdat ik zo slechtgehumeurd ben, en als ze niet weg kan, wil ze me niet in huis hebben. Ik ga buiten joggen, maar mijn gedachten zijn geobsedeerd door porno.*
>
> " *Op de geplande dag begin ik eerder op de avond te plannen en raak ik erg geïrriteerd als er iets tegen mijn plannen ingaat. Ik trek me terug uit gesprekken en geef toe (om later spijt van te hebben) op het werk en thuis. Ik ben geen ruziemaker, maar ik wil niet dat het onderwerp of het gesprek me tegenhoudt. Ik herinner me gelegenheden waarop ik domme ruzies met mijn partner begon. Ik wacht tot tien uur en als het zover is, trillen mijn handen oncontroleerbaar. Ik begin niet meteen aan de daad — omdat er nieuwe video's zijn toegevoegd — en 'winkel rond'. Mijn gedachten vertellen me dat ik mezelf vier dagen heb uitgehongerd en dat ik een 'speciale' clip verdien die de tijd die ik heb besteed aan zoeken waard moet zijn. Uiteindelijk kies ik er één of twee, maar ik wil dat het lang duurt zodat ik 'overleef' tot de volgende vier dagen, dus neem ik meer tijd om de daad te voltooien.*"  

Naast zijn andere problemen heeft deze arme man geen idee dat hij zichzelf vergiftigt. Eerst lijdt hij aan het 'verboden-vrucht-syndroom' en dwingt hij vervolgens zijn hersenen om dopamine te produceren. In vergelijking hiermee zijn zijn dopamine-receptoren niet zo ernstig aangetast, maar hij smeert de porno-waterglijbanen, op zoek naar opwinding, variatie, schok en angst om de volgende vier dagen te overleven. Je denkt waarschijnlijk dat deze man een zielige dwaas is, maar dat is niet zo. Als voormalig atleet en marinier wilde hij niet verslaafd raken aan iets. Echter, na terugkeer uit de oorlog volgde hij een opleiding tot IT-technicus in een revalidatieprogramma voor veteranen.

Bij het betreden van het burgerleven was hij een goed betaalde IT-professional bij een bank en kreeg hij een laptop mee naar huis. Het was het jaar waarin beroemde sterren hun porno-video's 'lekten' op internet en er veel over werd gesproken. Hij raakte toen verslaafd en heeft de rest van zijn leven betaald en zichzelf fysiek en mentaal geruïneerd. Als hij een dier was, zou de samenleving hem al lang uit zijn lijden hebben verlost, maar we laten nog steeds mentaal en fysiek gezonde jonge tieners verslaafd raken. Je denkt misschien dat dit geval en deze notities overdreven zijn, maar dit geval — hoewel extreem — is verre van uniek. Er zijn tienduizenden soortgelijke verhalen. Kun je er zeker van zijn dat geen van zijn vrienden en kennissen hem benijdde omdat hij een eens-in-de-vier man was? Als je denkt dat dit jou niet zou kunnen overkomen, **stop dan met jezelf voor de gek te houden.**

**HET GEBEURD AL.**

Zoals andere verslaafden zijn pornogebruikers beruchte leugenaars, zelfs tegen zichzelf. Ze moeten wel. De meeste af en toe gebruikers geven toe veel vaker toe te geven en op veel meer gelegenheden dan ze zullen toegeven. Veel gesprekken met zogenaamde 'twee-keer-per-week' gebruikers zullen toegeven dat ze het die week meer dan drie of vier keer hebben gedaan. Lees Reddit, NoFap en reboot-forumverhalen van af en toe gebruikers, en je zult merken dat ze ofwel dagen tellen of wachten om te falen. Je hoeft niet jaloers te zijn op af en toe gebruikers, en je hoeft ook niet te gebruiken, het leven is oneindig zoeter zonder. Bekijk het volgende logboek:

"*Het begon met een eenvoudige uitdaging om mijn geslachtsdeel een dag lang niet aan te raken en het niet kunnen volbrengen. Ik denk niet meer aan masturbatie, het komt niet meer in me op. Dat is mogelijk, ik beloof het je. De rijkdommen die wachten op degenen die daartoe in staat zijn - ze zijn ongelooflijk.*"

Jongeren zijn over het algemeen moeilijker te genezen, niet omdat ze het moeilijker vinden om te stoppen, maar omdat ze niet geloven dat ze verslaafd zijn of zich in de beginfase van de valstrik bevinden. vaak lijden ze aan de waan dat ze automatisch zullen stoppen voordat de tweede fase komt.

Ouders van kinderen die een hekel hebben aan internetporno mogen niet denken dat ze veilig zitten. Alle kinderen hebben een hekel aan de duistere kanten van porno voordat ze verslaafd raken. Op een bepaald moment deed jij dat ook. Laat je ook niet misleiden door angstcampagnes, de valstrik is nog steeds hetzelfde. Kinderen weten dat internetporno een bovennormale prikkel is, maar ze weten ook dat één 'bezoek' of 'gluur' het niet zal doen. Op een gegeven moment kunnen ze beïnvloed worden door een partner, klasgenoot of collega.

Wees alsjeblieft niet laks in deze kwestie. Het falen van de samenleving om adolescenten te weerhouden van verslaving aan internetporno en andere drugs is misschien wel het meest verontrustende aspect van deze verslaving. De hersenen van adolescenten zijn aanzienlijk flexibeler, en het is noodzakelijk om hen op te voeden en te beschermen. Als je niet weet waar je moet beginnen, zijn goede bronnen onder meer het boek YourBrainOnPorn.com om jezelf te informeren over de neurowetenschap. Zelfs als je vermoedt dat je tiener al verslaafd is, biedt het boek een fundamenteel begrip om iemand te helpen ontsnappen. Anders, beveel dit boek aan!
