# Ga ik het plezier missen?

**Nee!** Zodra het kleine pornomonster dood is, je lichaam stopt met het verlangen naar dopamine, en de "waterglijbanen" in je brein snel beginnen te vervagen door gebrek aan stimulatie, zal elke resterende hersenspoeling verdwijnen. Je zult niet alleen fysiek en mentaal beter in staat zijn om de stress en druk van het leven aan te kunnen, maar je zult ook meer van de goede momenten genieten.

Er is maar één gevaar: de invloed van mensen die seks nog steeds als hun ondersteuning en genot gebruiken. Het gezegde "het gras is altijd groener aan de overkant" is heel herkenbaar in veel aspecten van ons leven. Maar waarom, als het om porno gaat — met zulke enorme nadelen vergeleken met de illusoire 'voordelen' — neigt de ex-gebruiker ernaar om jaloers te zijn op degenen die seks en porno als een kruk gebruiken?

Met alle hersenspoeling vanaf onze jeugd is het begrijpelijk dat we in de val zijn gelopen. Maar waarom lopen we, nadat we ons realiseren wat een zinloze bezigheid porno is en erin geslaagd zijn om de gewoonte af te leren, toch weer terug in dezelfde val? Het is de invloed van maatschappelijke hersenspoeling die porno met seks verwart en het als normaal presenteert. De ex-gebruiker voelt een steek van verlangen! Het gevoel van onzekerheid of leegte, vooral als ze single zijn (wat trouwens geen misdaad is), veroorzaakt angst en drijft hen om weer de glijbaan af te gaan.

Dit is inderdaad een merkwaardige tegenstrijdigheid, vooral als je bedenkt dat niet alleen elke niet-gebruiker in de wereld blij is om geen gebruiker te zijn, maar dat zelfs elke gebruiker, ondanks hun verknipte, verslaafde, gehersenspoelde geest die denkt te genieten of te ontspannen, wenst dat ze nooit verslaafd waren geraakt. Dus, waarom zijn sommige ex-gebruikers dan jaloers?

**"Ik wil gewoon één keer kijken!"** Onthoud, 'één keer kijken' bestaat niet echt. Stop met het zien van die ene geïsoleerde gelegenheid en begin het te bekijken vanuit het perspectief van de pornogebruiker. Misschien ben je jaloers op hen, maar zij keuren hun eigen gedrag niet goed en zijn jaloers op jou. Als je op de een of andere manier klinisch naar een andere gebruiker zou kunnen kijken, zou dat je het beste kunnen helpen om eruit te komen. Let op hoe snel ze meerdere tabbladen en browservensters openen, hoe ze vooruitspoelen naar de 'belangrijke' delen, hoe ze snel verveeld raken en verschillende genres doorlopen die zorgen voor nieuwigheid, schok, angst, enzovoort. Vooral opvallend is dat het allemaal automatisch lijkt te gaan. Onthoud — ze genieten er niet van, maar ze kunnen uberhaupt niet meer genieten zonder dit middel. De volgende ochtend worden ze wakker met een verzwakte wil, verloren energie en wazige ogen, en zullen ze zichzelf moeten blijven verstikken bij de eerste tekenen van stress en spanning. Ze staan voor een leven vol vuiligheid, slechte mentale gezondheid en aangetaste zelfvertrouwen — een leven waarin ze zichzelf vernietigen met zwarte schaduwen in hun achterhoofd. 
En waarvoor? De illusie dat je krijgt wat je 'verdient' en verdomd plezier?

De tweede reden waarom sommige ex-gebruikers verlangen voelen, is omdat ze zich tekortgedaan voelen. De pornogebruiker doet iets — zoals zelfbevrediging — en de niet-gebruiker doet dat niet, waardoor ze zich tekortgedaan voelen en een soort van FOMO hebben. Wees duidelijk in je hoofd: het is niet de niet-gebruiker die wordt tekortgedaan, maar de arme verslaafde die wordt beroofd van:


-   Gezondheid

-   Energie

-   Zelfvertrouwen

-   Innerlijke rust

-   Moed

-   Gemoedsrust

-   Vrijheid

-   Zelfrespect

Stop met jaloers zijn op pornogebruikers en begin ze te zien als de ellendige, zielige wezens die ze werkelijk zijn. Misschien zeg je “ik was ooit een van de ergste”. Daarom lees je dit boek, en niet degenen die het niet aankunnen en zichzelf blijven voor de gek houden.

Je zou niet jaloers zijn op een heroïneverslaafde, en net als bij elke andere drugsverslaving, zal jouw situatie niet beter worden. Elk jaar zal het exponentieel erger worden — als je er vandaag niet van geniet om een gebruiker te zijn, zul je er morgen nog minder van genieten. Wees niet jaloers op andere gebruikers, heb medelijden met ze. 
Geloof me: *Ze hebben je medelijden nodig!*
