# Vermijd Valse Beweegredenen

Veel mensen die de wilskrachtmethode gebruiken, proberen hun motivatie te verhogen door het creëren van valse beweegredenen. Een typisch voorbeeld is jezelf belonen met cadeaus als je een maand geen porno kijkt. Dit lijkt logisch en verstandig, maar is eigenlijk een valkuil. Elke zelfrespecterende persoon zou liever dagelijks porno blijven kijken dan zichzelf te belonen met een eigen cadeau. Dit zorgt voor twijfel, omdat je niet alleen dertig dagen moet volhouden, maar ook onzeker bent of je die dagen zonder porno wel leuk gaat vinden. Het enige genot of hulpmiddel is weggenomen! Dit vergroot alleen maar het gevoel van opoffering, wat nu nog kostbaarder lijkt.

Andere voorbeelden zijn:

-   "Ik stop zodat ik een sociaal leven en meer echte seks krijg."
-   "Ik stop zodat een magische energie me zal helpen mijn concurrenten te verslaan en de partner te krijgen die ik wil."
-   "Ik stop zodat ik mijn energie niet meer verspilt aan porno en mezelf een honger naar het echte leven kan aanleren."


Deze gedachten kunnen waar zijn en effectief lijken, en misschien krijg je wat je wilt, maar denk er even over na. Als je krijgt wat je wilde, voel je je beroofd zodra het nieuwe eraf is. En als je het niet krijgt, word je ellendig. Hoe dan ook, vroeg of laat val je weer in dezelfde valkuil.

Het koppelen van stoppen aan een valse stimulans vergroot alleen maar de twijfel. Als je je doel niet bereikt (of zelfs als je dat wel doet), begin je te twijfelen: "Maakt stoppen mijn leven echt beter? Als ik stop en niet krijg wat ik wil, heb ik de methode dan verkeerd toegepast?" Zulke gedachten vergroten het gevoel van opoffering en veroorzaken daardoor juist verlangens.

Een ander typisch voorbeeld zijn online of forum-pacten. Deze hebben als voordeel dat ze de verleiding tijdelijk wegnemen, maar falen meestal om de volgende redenen:


1.	De stimulans is vals. Waarom zou je stoppen alleen omdat anderen dat doen? Dit creëert alleen extra druk en versterkt het gevoel van opoffering. Het is prima als iedereen oprecht op hetzelfde moment wil stoppen, maar je kunt ze niet dwingen, ook al willen ze dat in het geheim wel. Totdat ze er klaar voor zijn, creëert een pact extra druk, wat hun verlangen om te kijken alleen maar vergroot. Dit verandert ze in geheime kijkers, wat hun afhankelijkheidsgevoel versterkt.

2.	Afhankelijkheid van anderen bij de wilskrachtmethode zorgt voor het gevoel dat je een soort boetedoening ondergaat, terwijl je wacht tot de drang verdwijnt. Als iemand toegeeft, voelt dat als falen. Vaak geeft minstens één deelnemer het op, wat de anderen het excuus geeft waar ze op wachtten. Het is niet hun schuld, ze zouden het volgehouden hebben, maar ‘Fred’ liet hen in de steek. In werkelijkheid hebben de meesten allang vals gespeeld.
3.	Het delen van de eer is het tegenovergestelde van afhankelijkheid. Er is een geweldig gevoel van prestatie als je stopt met porno, en als je het alleen doet, is de waardering van je vrienden en online kennissen een enorme opsteker in de eerste dagen. Maar als iedereen het tegelijk doet, moet de eer gedeeld worden en is de boost kleiner.
4.	Een ander klassiek voorbeeld is de belofte van een goeroe. Stoppen zal je geluk brengen omdat je niet meer verwikkeld bent in het mentale touwtrekken, je brein herstelt en je impulsen beter kan beheersen. Maar vergeet niet, het zal je geen seksgod maken of de loterij laten winnen. Niemand behalve jij geeft er iets om als je stopt met porno. Je bent geen zwak persoon als je drie keer per dag porno kijkt en last hebt van PIED (porn-induced erectile dysfunction), en ook geen sterk persoon als je een verslaafde bent en niet stopt.

Stop met jezelf voor de gek te houden. Als zaken zoals een baan van tien maanden voor een jaarsalaris of de risico’s van het verminderen van je vermogen om met stress om te gaan, of het hebben van een betrouwbare erectie je niet tegenhouden, dan zullen deze paar valse beweegredenen dat ook niet doen. Ze vergroten alleen maar het gevoel van opoffering. Richt je in plaats daarvan op het volgende:
"Wat haal ik hier eigenlijk uit? Waarom moet ik porno kijken?"
Blijf naar de andere kant van het mentale touwtrekken kijken en vraag jezelf af wat porno voor je doet. HELEMAAL NIETS. Waarom moet ik het doen? JE HOEFT HET NIET TE DOEN! JE STRAFT JEZELF ALLEEN MAAR. Het is net als Pascal’s Weddenschap: je hebt bijna niets te verliezen (afnemende opwinding), kans op grote winsten (volledige en betrouwbare opwinding, mentaal welzijn en geluk) en geen kans op grote verliezen.

Waarom zou je dan niet aan je vrienden en familie laten weten dat je stopt? Wel, het maakt je een trotse ex-verslaafde, maar geen gelukkige niet-gebruiker. Het zou je partner zelfs kunnen afschrikken, omdat ze dit misschien zien als een manier om meer seks te willen, op een soort New Age-manier. Ze zouden ook kunnen vrezen dat je een seksmachine wordt. Het is moeilijk uit te leggen, tenzij ze er heel open voor staan.

Elke poging om anderen te betrekken bij het stoppen, geeft het kleine monstertje juist meer macht. Het wegduwen uit je gedachten en het volledig negeren ervan heeft als effect dat je er alleen maar meer aan denkt. Wees in plaats daarvan bewust. Zodra je de gedachten, signalen (zoals alleen thuis zijn) of afwezige gedachten opmerkt, zeg dan tegen jezelf: "Geweldig, ik ben geen slaaf van porno meer. Ik ben vrij en blij dat ik nu het verschil in seks ken!" Dit zal de zuurstof wegnemen van de gedachte en voorkomt dat het zich ontwikkelt tot drang en verlangens. In dit opzicht kan het beoefenen van mindfulness-meditatie nuttig zijn om gedachten te leren loskoppelen.
