# Slechts één klein kijkje

Dit is de valkuil voor velen die de methode van wilskracht gebruiken. Ze houden het drie of vier dagen vol, maar nemen dan een klein kijkje om zichzelf te kalmeren. Ze realiseren zich niet hoe verwoestend dit is voor hun moraal.

Voor de meeste gebruikers was hun eerste kijkje op de website niet zo goed als seks met een echt persoon. De clips die schoon zijn, zijn zeldzaam, wat hun verstand een boost geeft. Ze denken: "Goed, dat was niet zo heel leuk. Ik verlies de drang en ben niet zo geïnteresseerd in het schokkende spul." In werkelijkheid is het tegenovergestelde waar. Begrijp goed, het genot van een orgasme was niet de reden dat je met porno stopte. Als gebruikers alleen voor het orgasme gingen, zouden ze nooit meer dan één clip kijken. De enige reden waarom je porno nodig had, was om dat kleine monstertje te voeden. Denk eens na, na vier dagen uitgehongerd te zijn, hoe waardevol dat ene kijkje voor dat monstertje moet zijn geweest. Je bewuste geest is zich er niet van bewust, maar de kick die je lichaam kreeg, wordt doorgegeven aan je onderbewuste, en al je goede voorbereiding wordt ondermijnd. Er zal een stemmetje achterin je hoofd fluisteren dat, ondanks alle logica, die sessies kostbaar zijn en je er nog een wilt.

Dat kleine kijkje heeft twee schadelijke effecten:

1.  Het houdt het kleine monster in je lichaam in leven.

2.  Erger nog, het houdt het grote monster in je gedachten levend. Als je dat 'laatste kijkje' hebt genomen, wordt het makkelijker om het volgende te nemen.

Pornografie is een muizenval zonder kaas, alleen gif. Met wilskracht moet je jezelf overtuigen om de kaas niet te pakken, maar EasyPeasy laat je zien dat het gif is. Je hoeft het niet te vermijden, je gaat er gewoon niet op in.

Onthoud vooral: 'slechts één klein kijkje' is hoe mensen in de verslaving terechtkomen. *'Gewoon even kijken' is hoe mensen in de eerste plaats verslaafd raken.*
