# Help Degenen op het Zinkende Schip

Porno-gebruikers voelen de veranderingen in hoe internetporno door hun omgeving wordt gezien. De verslavende aard van internetporno wordt steeds vaker onderzocht en wordt nu terecht als iets anders beschouwd dan traditionele pornografie. De gemakkelijke toegankelijkheid en beschikbaarheid baart zelfs de voorstanders van porno zorgen. Ze voelen ook dat hun strijd voor vrijheid van meningsuiting en gedachten wordt gekaapt door verschillende invloeden. Het wilde westen van het ongereguleerde internet maakt het bijna onmogelijk om leeftijdsbeperkingen te handhaven op deze supernormale stimuli. Helaas zal dit niet snel stoppen, maar honderdduizenden gebruikers stoppen ermee, waarbij de meeste verslaafden op de hoogte zijn van studies die overeenkomsten aantonen tussen porno- en middelenverslaving. Elke keer dat een gebruiker het zinkende schip verlaat, voelen degenen die achterblijven zich steeds ellendiger.

Elke gebruiker weet instinctief dat het belachelijk is om zichzelf te saboteren en tijd door te brengen voor tweedimensionale pixels, waarmee ze hun brein overbelasten en in het proces neurale paden ontwikkelen die slechte seksuele prestaties garanderen. Als je het nog steeds niet dom vindt, probeer dan maar eens midden in je stad tegen een pornoblad te praten en vraag jezelf af wat het verschil is. Slechts één verschil: je krijgt niet de warmte en intimiteit op die manier. Als je kunt stoppen met het kopen van alcohol en sigaretten wanneer je boodschappen doet, dan kun je zeker stoppen met het bezoeken van je online harem. Gebruikers kunnen geen rationele redenen vinden om porno te kijken, maar voelen zich minder belachelijk als anderen het ook doen.

Gebruikers liegen openlijk over hun gewoonte, niet alleen tegen onderzoekers en de mensen om hen heen, maar ook tegen zichzelf. Ze moeten wel – de zelfmisleiding is essentieel om een beetje zelfrespect te behouden. Ze voelen de behoefte om hun 'gewoonte' niet alleen voor zichzelf te rechtvaardigen, maar ook voor niet-gebruikers. Ze promoten voortdurend subtiel de illusoire voordelen van porno.

Als een gebruiker stopt met de wilskrachtmethode, blijft hij zich toch beroofd voelen en verandert hij vaak in een klager. Dit bevestigt alleen maar voor andere gebruikers hoe ‘gelijk’ ze hebben door door te gaan. Als de ex-gebruiker erin slaagt te stoppen, is hij dankbaar dat hij niet langer door het leven hoeft te gaan met zelfdestructie of het verspillen van energie, en hoeft hij zichzelf niet meer te rechtvaardigen. Onthoud dat het angst is die ervoor zorgt dat de gebruiker zijn hoofd in het zand steekt, en zijn gedrag pas in twijfel trekt wanneer hij stopt. Help de gebruiker door die angsten weg te nemen. Vertel hem hoe geweldig het is om niet langer in een gevangenis te leven, hoe heerlijk het is om 's ochtends wakker te worden met een fit en gezond gevoel in plaats van uitgeput en vol zelfhaat, hoe fantastisch het is om vrij te zijn van slavernij en te genieten van je hele leven zonder die donkere schaduwen. Of beter nog, laat ze dit boek lezen.

Het is belangrijk om een getrouwde gebruiker niet te vernederen door te suggereren dat hij zijn relatie opzettelijk aan het ruïneren is, of dat het op de een of andere manier bedrog of onrein is. Er is een veelvoorkomende misvatting dat de ex-gebruiker in dit opzicht het ergst is. Deze misvatting heeft enige basis, maar komt meestal voort uit de wilskrachtmethode om te stoppen. Omdat de ex-gebruiker – hoewel hij van de gewoonte af is – nog steeds een deel van de zelfmisleiding behoudt en gelooft dat hij een offer heeft gebracht. Hij voelt zich kwetsbaar en zijn natuurlijke verdedigingsmechanisme is om de porno-gebruiker aan te vallen.

Dit kan het ego van de ex-gebruiker opkrikken, maar het helpt de gebruiker niet. Het zorgt er alleen maar voor dat de gebruiker zich nog ellendiger voelt, waardoor zijn behoefte aan porno juist groter wordt. Hoewel de verandering in de houding van de medische wereld tegenover internetporno de belangrijkste reden is waarom veel gebruikers stoppen, maakt dit het niet gemakkelijker om te doen. Sterker nog, het maakt het veel moeilijker. De meeste gebruikers denken tegenwoordig dat ze vooral om gezondheidsredenen stoppen. Dit is niet helemaal waar.

Hoewel het enorme gezondheidsrisico uiteraard de belangrijkste reden is om te stoppen, hebben gebruikers hun vitaliteit al jarenlang gesaboteerd zonder dat het enige invloed had. De belangrijkste reden waarom gebruikers stoppen, is dat de samenleving begint in te zien dat porno verslaving is. De houding van de samenleving verandert langzaam: veel partners zouden nu vragen stellen als je 's nachts op je laptop zit.

Een volledig pornoverbod in sommige landen of de onbeschikbaarheid van internet zijn klassieke voorbeelden van het dilemma van de reizende gebruiker. Over het algemeen nemen ze de houding aan dat dit hen zal helpen om minder te consumeren. Het resultaat is dat ze in plaats van één of twee keer per dag – waar ze trouwens niet van genoten – een hele week zonder doen. Maar tijdens deze gedwongen onthouding worden ze niet alleen mentaal beroofd in afwachting van hun beloning, hun lichaam snakt er ook naar. Oh, hoe kostbaar is dat bezoek aan de online harem wanneer het eindelijk weer mag.

Gedwongen onthoudingen verminderen het gebruik niet, omdat de gebruiker zichzelf uiteindelijk alleen maar meer laat gaan als hij eindelijk alleen is. Het enige wat het doet, is in het hoofd van de gebruiker inprenten hoe waardevol internetporno is en hoe afhankelijk hij ervan is. Het meest verraderlijke aspect van deze gedwongen onthouding is het effect op jongeren. We staan toe dat de kapers van 'vrijheid van meningsuiting', de pornoproducenten, ongelukkige tieners targeten om hen in eerste instantie verslaafd te maken. Terwijl jongeren in de meest stressvolle periode van hun leven zitten en ze in hun verwarde geest behoefte denken te hebben aan porno, chanteren we hen om te stoppen omdat ze zichzelf schade toebrengen.

Veel jongeren zijn niet in staat om te stoppen en krijgen door de maatschappelijke druk een enorm schuldgevoel over hun pornogebruik. Velen slagen erin te stoppen en zijn blij dat ze het hebben gedaan, denkend: _“Prima. Ik doe dit nu en als het voorbij is, ben ik toch genezen.”_ Dan komt de pijn en angst van het zoeken naar werk en andere volwassen problemen, gevolgd door de grootste ‘high’ van hun leven: het vinden van een baan. De pijn en angst zijn voorbij, en nu ze zich veilig voelen, treedt het oude mechanisme weer in werking. Een deel van de zelfmisleiding zit er nog steeds, en voor ze het weten, staan ze weer aan de drempel van hun favoriete online harem. De opwinding van het moment verdringt de nare gevoelens, ze zijn niet van plan weer verslaafd te raken, maar een snelle blik kan toch geen kwaad... Te laat! Ze zijn alweer verslaafd.

De oude drang van het ‘kleine monstertje’ begint opnieuw en zelfs als ze niet meteen weer volledig verslaafd raken, zal de depressie na de euforie hen waarschijnlijk alsnog te pakken krijgen. Het is vreemd dat hoewel heroïneverslaafden criminelen zijn volgens de wet, de samenleving hen helpt. Laten we dezelfde houding aannemen ten opzichte van de arme porno-gebruiker. Ze doen het niet omdat ze willen, maar omdat ze denken dat ze moeten. In tegenstelling tot de heroïneverslaafde lijden zij vaak jarenlang onder mentale en fysieke kwelling. We zeggen altijd dat een snelle dood beter is dan een langzame, dus ben niet jaloers op de arme porno-gebruiker. ***De pornogebruiker verdient jouw medelijden.***
