# Advies voor Niet-gebruikers

## Help je vrienden die porno gebruiken om dit boek te lezen

Begin eerst met het bestuderen van de inhoud van dit boek en probeer je in de gebruiker te verplaatsen. Dwing hen niet om het boek te lezen door te zeggen dat ze hun gezondheid kapotmaken of met vuur spelen. Ze weten dat waarschijnlijk beter dan jij. Gebruikers blijven geen porno kijken omdat ze het leuk vinden of omdat ze het willen. Ze zeggen dat tegen zichzelf en anderen om hun zelfrespect te behouden. Ze doen het omdat ze afhankelijk zijn van porno, omdat ze denken dat het hen ontspant, moed of zelfvertrouwen geeft (plezier of steun) en omdat ze het gevoel hebben dat het leven nooit leuk zal zijn zonder ‘seks’, tenminste hun versie ervan. Als je een gebruiker probeert te dwingen te stoppen, zal hij zich als een gevangen dier voelen en juist meer verlangen naar zijn ‘harem’. Dit kan hen veranderen in een geheime gebruiker, waardoor porno in hun gedachten nog waardevoller wordt.

Richt je in plaats daarvan op de positieve kant. Breng hen in contact met ex-gebruikers (blogs, forums, YBOP, NoFap, enz., maar pas op voor het promoten van de wilskrachtmethode). Laat ex-gebruikers hen vertellen hoe zij ook dachten dat ze voor altijd verslaafd zouden blijven en hoe veel beter hun leven nu is zonder porno. Zodra ze beginnen te geloven dat ze kunnen stoppen, zal hun geest zich openen. Leg dan uit hoe de illusie van ontwenningsverschijnselen werkt. Niet alleen geven die ‘dopamine-kicks’ hen geen energie, ze ondermijnen hun zelfvertrouwen en maken hen prikkelbaar en moe.

Op dit punt zouden ze klaar moeten zijn om het boek zelf te lezen, verwachtend dat het vol staat met verhalen over mislukte opwinding, falende penetratie, door porno veroorzaakte erectiedisfunctie, voortijdige ejaculatie, enz. Leg uit dat deze aanpak heel anders is en dat verwijzingen naar ziektes maar een klein deel van het materiaal uitmaken.

Kortom, laat dit niet in de duisternis verdwijnen. Vertel het je vrienden, maar doe het op een normale manier. Als je probeert de discussie te ‘winnen’ of een debat aan te gaan, vervreemd je hen alleen maar en vergroot je hun angst.

## Moet ik het mijn partner vertellen?

Moet ik mijn vrouw, vriendin of partner vertellen over mijn gewoonte? (Met de bedoeling om je te helpen stoppen.) Hier spelen meerdere factoren mee.

Als je eerder hebt geprobeerd te stoppen met de wilskrachtmethode en dit is mislukt, en je hebt je partner al ingelicht, vertel hen dan over je nieuwe aanpak en laat hen het boek lezen om zichzelf te informeren. Ze kunnen je ondersteunen en motiveren tijdens de ontwenningsperiode en zijn een belangrijke steun wanneer de verleiding toeslaat.

Als je net hebt ontdekt wat de 'pornoval' is en nog niet eerder hebt geprobeerd te stoppen, begin dan eerst zelf met EasyPeasy. Zoals eerder uitgelegd, zou dit een plezierige ervaring moeten zijn. Maar als je het moeilijk vindt, vraag dan om hulp van je partner. Wees open en kwetsbaar met je partner, dat zal je relatie versterken.

Als je het ontsnappen uit de val als plezierig ervaart en het je niet moeilijk valt door twijfel, is er niet veel reden om je partner in te lichten. Als het in het verleden geen probleem was, laat het dan rusten. Maar wees erop voorbereid dat je partner misschien zal opmerken dat je er beter uitziet, je beter voelt en beter presteert!

## Mijn partner stopt met het kijken naar porno.

Pornografie is een schadelijke verstorende kracht in relaties, en hoewel stoppen met kijken direct kan gebeuren, kost het tijd om te herstellen. Veel gebruikers, door irrationele overtuigingen voortgekomen uit hun verslaving, richten hun frustratie vaak op partners en dierbaren. Dit uit zich soms in gaslighting, liegen en manipulatief gedrag. Dit geldt niet voor alle gebruikers, maar komt steeds vaker voor in latere stadia van de verslaving. Hoewel deze gedragingen voortkomen uit de onderliggende pornoverslaving, is het belangrijk dat je jezelf hierover informeert. Als je deze gedragingen herkent, overweeg dan om een therapeut te raadplegen die gespecialiseerd is in seksverslavingen.

Als je partner in de ontwenningsperiode zit, ga er dan vanuit dat ze lijden, of ze dat nu laten merken of niet. Minimaliseer dit niet door te zeggen dat het makkelijk is om te stoppen; dat kunnen ze zelf wel zeggen. Blijf in plaats daarvan benadrukken hoe trots je op ze bent, hoe veel beter ze eruitzien, hoe fijn het is om bij ze te zijn, en hoe rustiger ze in het algemeen zijn. Dit is vooral belangrijk omdat de euforie van de poging om te stoppen en de lof van vrienden hen kan helpen, maar die positieve gevoelens kunnen snel vervagen, dus blijf hen prijzen.

Omdat ze niet over porno praten, kun je denken dat ze het zijn vergeten en dat ze niet willen dat je het onderwerp aansnijdt. Meestal is het tegenovergestelde waar, vooral bij de wilskrachtmethode, waar de ex-gebruiker vaak nergens anders aan kan denken. Wees dus niet bang om erover te beginnen en blijf hen aanmoedigen (ze laten je wel weten als ze er niet over willen praten).

Doe je best om hen te ontlasten tijdens de ontwenningsperiode en bedenk manieren om hun leven interessant en plezierig te maken. Deze periode kan ook zwaar zijn voor niet-gebruikers, vooral als je zelf nooit die verslaving hebt gehad. Als één persoon in een groep prikkelbaar is, kan dit voor iedereen vervelend zijn. Dus anticipeer hierop; als de ex-gebruiker prikkelbaar is, kunnen ze dit misschien op jou afreageren. Reageer daar niet op, want op zulke momenten hebben ze je lof en steun het hardst nodig. Als je zelf prikkelbaar bent, wat begrijpelijk is, probeer het dan niet te laten merken.

Een veel voorkomende truc van een verslaafde die probeert te stoppen met behulp van de wilskrachtmethode, is boos worden in de hoop dat hun partner of vrienden zullen zeggen: _"Ik kan niet aanzien dat je zo lijdt. Neem gewoon je 'gif' weer."_ Zo hoeft de gebruiker zijn gezicht niet te verliezen, want ze ‘geven niet op’, ze zijn ‘geadviseerd’. Als de ex-gebruiker dit probeert, moedig hen dan op geen enkele manier aan om terug te vallen. Zeg in plaats daarvan: _"Als dit is wat porno met je doet, wat geweldig dat je er bijna vanaf bent. Hoe geweldig dat je de moed hebt gehad om te stoppen."_

Onthoud dat er tijdens het herstelproces twee partijen genezen. Als je partner stopt met porno, is het belangrijk dat jij je eigen steunnetwerk, zelfzorgroutines en grenzen hebt. Dit proces gebeurt niet van de ene op de andere dag en vereist vertrouwen, communicatie en verantwoordelijkheid. Journaling, het ontwikkelen van je eigen passies en ook therapie kan hierbij helpen.

## Uitglijden (relapse)

Het bestaan van deze sectie dient als waarschuwing voor degenen die de val verlaten. Persoonlijk ben ik nooit teruggevallen, maar ik zal ervaringen gebruiken uit interviews met leden van de gemeenschap en hulpmiddelen uit cognitieve gedragstherapie om dit te illustreren.

Ten eerste is het contraproductief om het een 'terugval' te noemen. Wat er is gebeurd, is dat je bent uitgegleden en het 'kleine monstertje' hebt gevoed, wat op zijn beurt het grote hersenspoelmonster activeert. Gebruikers die uitglijden (wat, volgens de definitie, vooruitvallen betekent) krijgen vaak te maken met een reeks irrationele overtuigingen:

  - “*Ik zal nooit vrij zijn*" - **Dramatiseren**
  - “*k zou / moet elke dag van mijn leven moeten sporten, studeren en vruchtbaar moeten zijn*" (Ook wel **moetivatie** genoemd)
  - “*Vandaag heb ik PMO gedaan, dus wat heeft het voor zin om al die boeken en forums te lezen... Mijn doel was zelfs om niet eens M te doen, maar hier ben ik - een mislukking - terugval.*" - **Lage frustratietolerantie**
  - “*Mijn vrienden / forumlezers / anderen doen al (x) dagen geen PMO, maar ik kan het niet, dus ik ben een hopeloos geval. Gisteren voelde ik me goed omdat ik goed studeerde en vruchtbaar was, maar vandaag niet... Ik ga achteruit.*" - **Vergelijken met anderen**
 - “Ik mag geen seksuele gedachten hebben" - Ze hebben starre overtuigingen over seks, verkregen door henzelf, hun ouders of hun samenleving. Vraag jezelf af of zelfkastijding je helpt om je doelen te bereiken, en zo ja, geniet je van de reis?

Factoren die bijdragen aan de hersenspoeling van elke gebruiker lijken eindeloos. Je kent jezelf beter dan wie dan ook, maar het is duidelijk dat je de instructies niet hebt gevolgd. Je zag waarde in porno, maar hoe dan?

Wat vaak over het hoofd wordt gezien, is dat het tijd kost om de hersenspoeling ongedaan te maken. Dit maakt het niet moeilijker, maar bijna elke industrie gebruikt seks, en het actief tegengaan van hersenspoeling is een bewust proces (in elk geval in het begin), dus het kan tijd kosten om de lessen echt te verankeren. Daarom wordt aanbevolen om het boek meerdere keren te lezen (je kunt de hoofdstukken waar je moeite mee hebt overslaan). Het kost je niet veel tijd.

Een verrassend veelvoorkomende ervaring bij religieuze gebruikers die de verslaving verlaten, is dat ze willen dat het proces een beetje pijn doet, als een vorm van boetedoening. Ze vinden het zo gemakkelijk om te stoppen dat ze zich schuldig voelen over hoe gemakkelijk het gaat. Maar waarom jezelf saboteren en het moeilijk maken? Het kleine monstertje (de verslaving) is hierin erg sluw.

Verbreek de associatie met dat kleine monstertje — het is ooit door de porno-industrie toegevoegd. Stel je een pestkop voor die op het schoolplein een woedeaanval heeft. Wat zeg je tegen zo’n pestkop? Als je toegeeft, versterk je alleen maar hun gedrag. Sommigen die stoppen, voeden de pestkop nog steeds, waardoor hun hersenspoeling toeneemt, maar hun begrip van de verslaving is niet veranderd. Herpak jezelf, ontdek waar het misging, en geniet van je vrijheid!

Je bent niet je drang. Mindfulnessmeditatie is de oefening van het opmerken van gedachten, en er zijn fundamentele lessen over de aard van de geest te vinden. Het wordt sterk aanbevolen om te mediteren in het algemeen, en dit is volledig compatibel met religieuze beoefening. Je kunt niet tegen jezelf vechten, of tegen het kleine monstertje. Je moet jezelf en het proces onvoorwaardelijk liefhebben.

Verwijder het idee van falen uit je gedachten. Hier is een passage uit “Meditations of a Porn Addict” door Gulliaco (gelinkt in de sectie Bronnen aan het einde van het boek):

“Omdat porno kijken je nul voordelen biedt, is het iets dat je alleen maar pijn doet, en het is extreem belachelijk om zoiets te willen doen. Ik vergelijk het met het drinken van bleekmiddel. Hier heb je een voorbeeld:

> De moeilijke reis van het niet drinken van bleekmiddel.
>
>Hallo! Wij zijn NoBleach en we organiseren uitdagingen waarin deelnemers (“Bleachstronauts”) zich onthouden van het drinken van bleekmiddel voor een bepaalde periode. Of je nu meedoet voor een maandelijkse uitdaging om je zelfbeheersing te testen, of omdat overmatig bleek drinken een probleem in je leven is geworden en je voor langere tijd wilt stoppen, je zult hier een ondersteunende gemeenschap en veel bronnen vinden.>
> - “Soms sta ik mezelf toe om een glas bleekmiddel te drinken. Ik weet dat die ‘één druppel’ een leugen is, maar ik denk niet dat één glas pijn zal doen. Je kunt niet al die uren die ik zonder heb gedaan vernietigen.”
> - “Ik heb geen probleem met stoppen, maar soms loop ik over straat en zie ik iemand water drinken, in een glas, en ik stel me voor dat het glas bleekmiddel bevat. Dan krijg ik een verlangen, en na een interne discussie geef ik 's avonds toe en drink ik een glas.”
> - “Mijn probleem is dat ik, als ik alleen ben in mijn keuken, naar de glazen begin te kijken, soms mezelf verleid door de fles bleekmiddel te openen, soms ruik ik eraan, en... Nou, dan zit ik weer terug bij af. Ik wil hier zo graag mee stoppen, maar ik weet niet zeker of dat ooit lukt.”
> - “Bleek drinken stoppen is onmogelijk, ik heb tenslotte altijd een mond, toch? Hoe kan ik stoppen als mijn keel me eraan herinnert dat ik altijd kan slikken?”
> - “*Oh man, het ging zo goed, 19 hele dagen zonder het te doen. Het belangrijkste is om van mislukkingen te leren! Nu weet ik wat ik moet vermijden: kijken naar schoonmaakproducten in de supermarkt. Ik ga proberen om een maand vol te houden! Ik reset mijn teller. Wens me geluk!*”
> Als je een drang voelt, kalmeer dan! Onthoud wat het hackboek zegt: “Bleekmiddel is moeilijk op te geven vanwege de angst dat we ons plezier of steun verliezen. De angst dat bepaalde fijne situaties nooit meer hetzelfde zullen zijn. De angst dat we niet met stressvolle situaties om kunnen gaan. Kortom, het zijn de effecten van hersenspoeling die ons doen geloven dat het kopen van bleekmiddel, en dus het drinken ervan, essentieel is voor elk mens. Zelfs verder, het geloof dat er iets inherent waardevols zit in betaalbaar bleekmiddel, en dat als we stoppen, we onszelf iets ontzeggen en een leegte creëren. Maak dit duidelijk in je hoofd: Bleekmiddel vult geen leegte, het creëert er één!”
> 
> En ik zeg:
> “Stel je voor dat je gedwongen wordt vijf minuten naar een glas bleekmiddel te kijken. Herinner je je één van die geuren of merken die je zo lekker vond? Misschien gaat het gepaard met een geluid, of herinner je je alleen bepaalde details. Het bleekmiddel is daar, en je kunt je ogen niet sluiten of je hoofd wegdraaien, want het bleekmiddel zit in je hoofd, het is een herinnering.“
>
> Wat voel je nu? Heb je een verlangen? Voel je iets op je tong of verandert je ademhaling? Wat zijn je gevoelens over wat je herinnert? Identificeer ze, het bleekmiddel wil ze vertroebelen en je verwarren, zodat je alleen nog maar aandacht hebt voor datgene dat je wil verleiden.”
>
Met dit alles wil ik je gevoelens niet bagatelliseren, en zeker niet iets zeggen als “haha, kijk hoe dom de gebruiker is”, maar ik wil je een perspectief bieden, zodat je beseft hoe belachelijk makkelijk het eigenlijk is (en altijd zal zijn) om deze verslaving te overwinnen. Pornokijken is niet als een aan/uit-knop waar je zegt “nou ja, ik zit in situatie X, dan kijk ik maar porno”. Fantasieën! Leugens! Hoe vaak sta je jezelf toe een glas bleekmiddel te drinken? Nooit? Waarom niet? Omdat het vreselijk is! Hoe kun je je verslaving overwinnen als je niet inziet dat PMO net zo vreselijk is om te doen?"

## En wat vind je van MO (masturbatie, orgasme)?

Mensen masturberen al eeuwen zonder problemen. Om duidelijk te zijn: het probleem zit bij porno.

Dat gezegd hebbende, kun je ook verslaafd raken aan masturbatie (MO) om dezelfde redenen als bij porno, zoals de ‘noodzaak om een orgasme te hebben’-mentaliteit, mentale escalatie, het forceren van je lichaam om seks te hebben, en puur hedonistisch plezier.

Waarschijnlijk zijn porno en masturbatie sterk met elkaar verweven in je gedachten. Veel gebruikers geven aan dat ze uiteindelijk terugvallen doordat ze masturberen naar door porno-geïnduceerde fantasieën. Terwijl je hersenen opnieuw bedraden, zal deze hersenspoeling geleidelijk verdwijnen, maar het is verstandig om een tijdje pauze te nemen van masturbatie. Zoek ook naar echte seksuele ervaringen om dit proces te versnellen.

DDit is geen bevel, maar iets om te overwegen: de gerapporteerde voordelen van onthouding van orgasme (spermaretentie) zijn talrijk — meer focus en energie, het verdwijnen van ‘hersenmist’ en meer zelfvertrouwen, samen met een reeks andere voordelen. Uit persoonlijke ervaring merk ik een duidelijk verschil, en het hangt allemaal af van hoe je deze extra energie kanaliseert.

Zonder strikte wetenschappelijke kennis te claimen, kan het zijn dat de voordelen voortkomen uit een paar verschillende factoren:

Kortom, terwijl sommige mensen positieve effecten kunnen ervaren van semenretentie, is het belangrijk om deze beweringen met enige voorzichtigheid te benaderen en te erkennen dat wetenschappelijk bewijs mogelijk ontbreekt.

- Na een orgasme komt er prolactine vrij in de hersenen, wat de afgifte van dopamine remt.
- Het onthouden van je hersenen van dopaminestoten zorgt ervoor dat er meer opname is van gewoonweg het leven leiden.
- Sperma wordt na ongeveer 78 dagen opnieuw opgenomen door de bloedbaan en is een van de beste voedingsstoffen die je lichaam kan krijgen.
- Het omzetten van seksuele energie in productieve gewoonten brengt een extra laag van productiviteit met zich mee.

Je kunt ook seks hebben zonder orgasme, wat, zoals eerder genoemd, een prachtige seksuele ervaring is (vaak aangeduid als Karezza). Je kunt je vermogen om dit te doen versterken door Kegel-oefeningen te doen. Uit persoonlijke ervaring is de eenvoudigste en meest effectieve manier om deze spier te trainen, het stoppen en starten van je urinestroom (maar wees voorzichtig, overdrijf het niet, dit kan op zichzelf weer problemen veroorzaken). Het scheiden van de tantrische en reproductieve onderdelen van seks is een van de vele voordelen van het ontsnappen aan de PMO-val (en mijn partners waren er ook dol op!).

## Afwijkingen van standaardadvies

Dit deel schrijf ik met enige terughoudendheid, maar het moet toch worden genoemd.

Sommige mensen die EasyPeasy gebruiken, merken dat hun verlangen om porno te kijken zo sterk is verminderd dat ze geen laatste sessie meer kunnen doen. Dat is prima, maar onderschat de kracht van zo’n laatste keer niet. Bewust door porno bladeren en echt beseffen hoeveel je het haat, kan heel krachtig zijn. Persoonlijk vond ik het erg nuttig en was blij om mijn handen ervan af te wassen, oprecht opgelucht dat ik het nooit meer hoef te doen. Maar jouw ervaring kan anders zijn.

Als je al een tijdje vrij bent van de val en de hersenspoeling hebt verwijderd, hoef je het kleine monstertje niet meer te voeden — het zou alleen maar aan je blijven knagen. Geniet in plaats daarvan van je vrijheid!

## Help mee om dit schandaal te beëindigen

 Internetporno is een van de gevaren in een vrije samenleving en lift mee op de welwillende inspanningen van voorstanders van persoonlijke vrijheid. De basis van beschaving — de reden waarom de mensheid zo ver is gevorderd — is onze capaciteit om kennis en ervaringen te delen, niet alleen met elkaar, maar ook met toekomstige generaties. Zelfs dieren beschermen hun kroost tegen de valkuilen van het leven.

Porno-producenten handelen niet te goeder trouw, ze geloven niet oprecht dat ze de mensheid helpen, vooral nu de verslaving aan internetporno breed wordt bestudeerd. Misschien dachten mensen in de beginfase oprecht dat porno mensen iets leerde over intimiteit, maar autoriteiten weten nu dat dit een misvatting is. Geen enkele tube-site maakt echt educatieve claims. De enige beweringen gaan over de schokkende, nieuwe en escalerende aard van hun aanbod.

De hypocrisie is ongelooflijk: als samenleving maken we ons druk over pesten op school en de objectificatie van het menselijk lichaam. In vergelijking met internetporno zijn deze problemen maar kleinigheden. Het aantal mensen dat verslaafd raakt, stijgt elk jaar, terwijl ze kostbare tijd doorbrengen met illusies en denkbeeldige pixelmensen, ten koste van hun gezondheid, vitaliteit, energie en tijd. Porno is een van de grootste oorzaken van relatieproblemen, en honderdduizenden levens worden elk jaar verwoest doordat mensen eraan verslaafd raken. Internetporno-producenten hoeven niet te adverteren in reguliere media — dat is niet nodig, onze biologische drang brengt ons vanzelf naar hun goed gevulde harems, waar gratis monsters worden uitgedeeld als door een lokale drugsdealer. Tegenwoordig moedigen tube-sites bezoekers vooral aan om zelf content te plaatsen.

Hoe slim is het dat porno-bedrijven 18+ waarschuwingen tonen als afschrikmiddel voor minderjarigen, hoewel sommigen dat niet eens doen. Internetporno raakt iedereen, ongeacht de leeftijd. Hun houding is: "We hebben je gewaarschuwd voor het gevaar, dus de keuze is aan jou." Nemen ze stappen om leeftijden te verifiëren? Nee, want dat zou hun klanten ontmoedigen. En als leeftijdsverificatie wordt verplicht, verhuizen ze gewoon naar een ander land. Of ze betalen iemand om te schrijven over hoe verboden alcohol leidde tot illegale handel en de opkomst van de maffia. Wat daarbij vergeten wordt, is waarom het intrekken van dat verbod niet leidde tot een vermindering van alcoholgerelateerde slachtoffers, en waarom de wetshandhaving er niet in slaagde de groei van de maffia te stoppen.

We kunnen dit probleem anders aanpakken door de jongere generatie te onderwijzen. Als ze sigaretten en alcohol kunnen vermijden tijdens het winkelen, kunnen ze hetzelfde doen met internetporno. We zien al maatschappelijke verschuivingen zoals ‘No Nut November’ en ‘Coomer’-memes die mainstream worden. De gebruiker heeft niet meer keuze dan een heroïneverslaafde. Gebruikers besluiten niet om verslaafd te raken, ze worden in een subtiele val gelokt. Als ze een keuze hadden, zouden alleen nieuwelingen morgen nog kijken, overtuigd dat ze elk moment kunnen stoppen als ze willen.

Waarom die dubbele standaarden? Waarom worden heroïneverslaafden als criminelen gezien, maar kunnen ze zich wel registreren om methadon en medische hulp te krijgen? Probeer jezelf maar eens als porno-verslaafde te registreren — als je hulp vraagt aan je arts, zeggen ze waarschijnlijk: "Doe het gewoon wat minder, probeer matiging," wat je al weet dat niet werkt, of ze schrijven medicatie voor tegen je 'depressie'. Nog erger is het advies om echte partners te zoeken — serieus? Hebben ze nog nooit gehoord van mensen die porno verkiezen en het stiekem doen achter de rug van hun partner om? Sommige mensen begrijpen het gewoon niet.

Angstcampagnes helpen gebruikers niet om te stoppen, ze maken het juist moeilijker. Ze maken mensen alleen maar banger, waardoor ze juist meer willen kijken. Ze voorkomen ook niet dat tieners verslaafd raken. Tieners weten dat porno hun libido doodt, maar ze weten ook dat één keer kijken geen kwaad kan. Omdat de verslaving zo wijdverspreid is, zullen tieners vroeg of laat door sociale druk of nieuwsgierigheid een keer proberen. En omdat gratis porno slechte clips aanbiedt, is de kans groot dat ze verslaafd raken.

Waarom laten we dit schandaal voortduren? Waarom komen overheden niet met echte campagnes? Waarom krijgen we niet te horen dat internetporno een verslavende en gevaarlijke drug is, die je zenuwen sloopt, en dat één keer kijken genoeg is om verslaafd te raken? Waarom kunnen ze geen leeftijdsverificatie afdwingen door bijvoorbeeld geregistreerde creditcards te eisen, mogelijk via een derde partij? MindGeek, eigenaar van veel grote porno-sites, probeert overheden te bedriegen om hun eigen leeftijdsverificatiesysteem te gebruiken — laat dit niet gebeuren! In het boek The Time Machine van H.G. Wells is er een scène waarin iemand in de rivier valt en zijn metgezellen apathisch aan de oever zitten, ongevoelig voor zijn wanhoopskreten. Dit is even verontrustend als de algemene apathie van de samenleving voor de pornocrisis.Er waait echter een wind van verandering door de samenleving. Een sneeuwbal is begonnen te rollen, en hopelijk zal dit boek helpen om er een lawine van te maken. Jij kunt ook helpen door de boodschap te verspreiden.

Als je iemand ziet worstelen met wilskracht of proberen te stoppen met porno, verwijs ze dan vriendelijk naar deze methode. Maar de echte taak is om het verhaal rond porno in het algemeen te veranderen. Overweeg om, als je online of in het echt de normalisering van porno tegenkomt, respectvol te proberen om mensen te onderwijzen en te bevrijden.

Af en toe kun je een negatieve reactie krijgen, maar soms is één opmerking genoeg. Net als velen voor jou, kun je berichten verwachten van dankbare mensen die je zullen bedanken voor hun vrijheid.

## Laatste Waarschuwing

 Je kunt nu de rest van je leven genieten als een gelukkige niet-gebruiker. Om ervoor te zorgen dat dit zo blijft, volg je deze eenvoudige instructies:

1.	Houd dit boek bij je en raadpleeg deze zo vaak als nodig is.
2.	Als je ooit jaloers wordt op een andere gebruiker, bedenk dan dat zij jaloers op jou zullen zijn. Jij wordt niet iets ontnomen, zij wel.
3.	Herinner je dat je het niet leuk vond om een gebruiker te zijn. Daarom ben je gestopt. Je geniet van het leven als niet-gebruiker.
4.	Vergeet niet, er bestaat niet zoiets als “maar één keer kijken”.
5.	Twijfel nooit aan je beslissing om nooit meer porno te kijken. Je weet dat het de juiste keuze is.
6.	Als je problemen ondervindt, zoek en neem contact op met een therapeut die kennis heeft van internetporno. Je kunt lijsten van deze therapeuten online vinden. Ook kan je steun zoeken bij een supportgroepen zoals Sexaholics Anonymous (SA) of Sex and Love Addicts Anonymous (SLAA). 