# De Instructies

1.  Volg alle instructies.

2.  behoud een open geest.

3.  Begin met een gevoel van gelukzaligheid.

4.  Negeer alle advies en invloed die in strijd zijn met EasyPeasy.

5.  Weersta elke belofte van een tijdelijke oplossing.

6.  Maak het duidelijk in je gedachten: porno biedt geen echt plezier of steun en je maakt geen opoffering. Er is niets om op te geven en geen reden om je beroofd te voelen.

7.  Wacht niet met stoppen, doe het nu!

8.  Neem het besluit om nooit meer te kijken en twijfel er nooit aan.

9.  Onthoud dat er niet zoiets bestaat als slechts één blik.

10.  Kijk nooit meer naar porno.

## Affirmaties 

-  Ik ben bevrijd van de slavernij van porno.

-  Het is makkelijk om mijn gedachten over porno te negeren.

-  Dag gedachten, dag neigingen. Daar gaan mijn verlangens.

-  Ik focus mijn innerlijke zelf om de verslaving aan porno te overwinnen.

-  Porno steelt mijn tijd, energie en levenskracht.

-  Het verslaan van porno wordt elke dag exponentieel makkelijker en in elk opzicht.

-  Ik geniet en waardeer mijn porno-vrije, sterke, gelukkige, lichte en gemakkelijke levensstijl.

-  Als ik terugkijk en denk aan mijn vooruitgang, geeft het me veel vreugde en trots in mezelf.

-  Elke keer dat ik andere pornogebruikers zie, word ik meer gemotiveerd om mezelf die keten te zien doorbreken.

-  Al die opgekropte energie geneest mijn lichaam en geest. Dan kan ik meer productief en uitdagend werk doen naar mijn waarden en doelen toe.

-  Mijn brein komt weer in de juiste vorm, wordt door mij getraind door niet te doen wat ik eerder deed.

-  Nu wordt al die opgekropte wilskracht gebruikt om de lichte stress en spanningen van het leven aan te kunnen.

-  Geweldig, ik ben vrij en geen slaaf meer!
