# Простой метод

Цель этой книги -- направить вас в новое русло. В отличие от обычного метода прекращения -- в котором вы начинаете с ощущения восхождения на Эверест и проводите следующие несколько недель, испытывая тягу и лишения -- здесь вы сразу же начинаете испытывать чувство восторга, как будто излечились от страшной болезни. С этих пор, чем дальше вы будете идти по жизни, тем чаще вы будете смотреть на этот период времени и удивляться, как вы вообще пользовались порнографией. Вы будете смотреть на других пользователей порно с жалостью, а не с завистью.

При условии, что вы не тот, кто никогда не был зависим (читаете для своего близкого человека) или бросил (или находится в постных днях "порнодиеты"), необходимо продолжать "употребление", пока вы не дочитаете книгу до конца. Это может показаться противоречием, и это указание продолжать мастурбировать на порно вызывает больше возражений, чем любое другое, но по мере дальнейшего чтения ваше желание использовать порно постепенно будет уменьшаться. **Отнеситесь к этому указанию серьезно: Попытки бросить раньше времени не принесут вам пользы.**

Многие не дочитывают книгу до конца, потому что чувствуют, что должны от чего-то отказаться, некоторые даже сознательно читают только одну строчку в день, чтобы отсрочить злое событие. Посмотрите на это с другой стороны: что вы теряете? Если вы прочитаете всё книгу, вам будет не хуже, чем сейчас. По определению, это пари Паскаля, пари, заключенное так, что вам нечего терять, а шансы на большой выигрыш высоки.

Кстати, если вы не смотрели порно в течение нескольких дней или недель и не уверены, являетесь ли вы пользователем порно, бывшим пользователем или непользователем, то не используйте порно для мастурбации во время чтения. На самом деле, вы уже не употребляете, только нужно дать мозгу догнать тело. К концу книги вы станете счастливым не-пользователем. EasyPeasy -- это полная противоположность обычному методу, когда человек перечисляет значительные недостатки порно и говорит:  
*"Если только я смогу достаточно долго обходиться без порно, в конце концов, желание пропадет, и я снова смогу наслаждаться жизнью, свободной от рабства."*  
Это логичный путь, и каждый день тысячи людей прекращают использовать порно, используя этот метод. Однако добиться успеха очень сложно по следующим причинам:

**Прекращение ПМО - это не настоящая проблема.**
Каждый раз, когда вы заканчиваете сеанс, вы прекращаете употребление. У вас могут быть веские причины в первый день вашей порно-диеты "смотрю только раз в четыре дня" сказать: *“Я не хочу больше использовать порно или даже мастурбировать”.* Все пользователи так делают, и их причины более весомы, чем вы можете себе представить. Настоящая проблема -- это второй, десятый или десятитысячный день, когда в момент слабости вы подумаете ‘только один разочек’, вы захотите ещё, и вы снова вдруг станете зависимым.

**Осознание риска для здоровья порождает еще больший страх, что еще больше затрудняет прекращение употребления.**
Скажите пользователю, что порно разрушает его мужественность, и первое, что он сделает, -- это потянется за чем-нибудь, чтобы получить дофамин: за сигаретой, за алкоголем или даже откроет браузер для поиска порно.

**Все причины для остановки на самом деле усложняют задачу.**
Это происходит по двум причинам. Во-первых, нас постоянно извне подталкивают отказаться от нашего ’маленького друга’ или от поддержки, порока или удовольствия (в зависимости от того, как воспринимает это пользователь). Во-вторых, на самом деле причины ослепляют нас. Мы не перестаём мастурбировать по тем причинам, по которым мы должны были бы перестать. Настоящий вопрос заключается в том, почему мы хотим этого или нуждаемся в этом?

С EasyPeasy мы (вначале) забываем о причинах, по которым мы хотели бы прекратить, смотрим в лицо проблеме порнографии и задаем себе следующие вопросы:

1.  Что порнография даёт мне?

2.  Действительно ли мне это нравится?

3.  Действительно ли мне нужно идти по жизни, саботируя свой разум и тело?

Прекрасная правда заключается в том, что *вся порнография* не приносит вам абсолютно никакой пользы. Позвольте мне внести ясность: дело не в том, что минусы просмотра порнографии перевешивают плюсы, а в том, что в просмотре порнографии нет ***никаких*** преимуществ.

Большинство пользователей считают необходимым рационализировать, почему они используют порно, но все причины, которые они придумывают, являются заблуждениями и иллюзиями.

Сначала мы устраним эти заблуждения и иллюзии. Собственно говоря, вскоре вы поймете, отказываться не от чего. Мало того, вы получите замечательные положительные результаты отказа от порнографии, причем благополучие и счастье -- лишь два из этих результатов. Как только иллюзии о том, что без порно жизнь никогда не будет такой же приятной, будут развеяны -- осознав, что без него жизнь не только не менее приятна, но и бесконечно более приятна, -- и как только исчезнет чувство обделенности или упущенного, мы вернемся к рассмотрению вопроса о повышении благосостояния и счастья и десяткам других причин отказа от порно. Эти осознания станут позитивным дополнительным подспорьем, которое поможет вам достичь того, чего вы действительно хотите: наслаждаться жизнью, свободной от рабства порнозависимости!
