# Почему трудно остановиться?

Все пользователи чувствуют, что в них вселилось что-то дурное. На первых порах это простое обещание себе: *"Я остановлюсь, просто не сегодня"*. В конце концов, мы начинаем верить, что у нас недостаточно силы воли, чтобы остановиться, или что в порно есть что-то, что нам нужно получать, чтобы наслаждаться жизнью. Порнозависимость похожа на то, как мы когтями выбираемся из скользкой ямы: И когда мы приближаемся к вершине, мы видим солнечный свет, но из-за того, что наш настрой и энтузиазм падает, мы снова скатываемся вниз. В конце концов мы открываем браузер и, подрочив, чувствуем себя ужасно.

Спросите у пользователя, *"Если бы вы могли вернуться во время, ещё до того как попали на крючок, с тем опытом, который у вас есть сейчас, начали бы вы использовать порно?"*

*"НИ В КОЕМ СЛУЧАЕ!"* -- ответ был бы именно таким.

Спросите подтвержденного пользователя, того, кто защищает интернет-порно и не верит, что оно вызывает травмы мозга или снижение чувствительности дофаминовых рецепторов: *"Поощряете ли вы своих детей в использовании порнографии?"*

*"КОНЕЧНО ЖЕ НЕТ!"* -- снова ответят вам.

Порно -- это необыкновенная загадка. Как уже говорилось, проблема не в том, чтобы объяснить, почему это легко прекратить, а в том, почему прекратить смотреть порно трудно. Настоящая проблема заключается в том, чтобы понять, почему каждый человек продолжает это даже после того, как получил представление о неврологических повреждениях. Отчасти мы начинаем это делать из-за других десятков миллионов людей, которые уже этим увлекаются, но все эти люди жалеют, что вообще начали, и говорят, что это все равно что жить на пониженных мощностях. Мы не совсем верим, что они не получают от этого удовольствия, поскольку ассоциируем это со свободой или "сексуальным просвещением", и прилагаем все усилия, чтобы самим оказаться на крючке. Затем мы проводим остаток жизни, уговаривая других не делать этого и пытаясь избавиться от этой привычки сами, часто думая, что в этом мы уникальны.

Мы проводим значительную часть времени, чувствуя себя безнадежными и несчастными. 'Обучая' себя сверхнормальными образами, мы предпочитаем и жаждем этих холодных образов, даже когда теплые, реальные люди доступны. Благодаря постоянному всплеску и спаду дофамина, вызываемому ПМО, мы обрекаем себя на пожизненную изоляцию, раздражительность, гнев, стресс, усталость и сексуальную дисфункцию. Используя порно, в котором отсутствуют лучшие стороны секса и связи, мы в итоге чувствуем себя несчастными и виноватыми.

На самом деле, читая здесь и на других сайтах об аддиктивных и деструктивных сторонах интернет-порнографии, мы еще больше нервничаем и теряем надежду! Что это за хобби такое, что когда ты им занимаешься, то жалеешь, что не занимаешься, а когда не занимаешься, то жаждешь его? Пользователи презирают себя каждый раз, когда читают о гипофронтальности и десенсибилизации, каждый раз, когда употребляют порно за спиной своего доверчивого партнера, и каждый раз, когда не могут заставить себя заняться спортом после дневного сеанса. В остальном разумное и рациональное человеческое существо проводит все свои дни в презрении. Но знаете, что хуже всего. Что пользователи получают от вынужденной жизни с этими ужасными черными тенями на задворках сознания? **Абсолютно ничего!**

Вы можете подумать *"Это всё хорошо, я в курсе, но как только вы подсели на эти вещи, остановиться практически невозможно."* Но почему это так трудно? Некоторые говорят, что это из-за сильных симптомов при отмене использования, но, как вы вскоре узнаете, на самом деле симптомы отмены очень слабые. И это очевидно, так как многие любители ПМО жили и умерли, даже не подозревая о своей зависимости.

Кто-то скажет, что интернет-порно бесплатно и, значит, люди могут претендовать на этот природный источник халявного кайфа, но это неправда -- он не халявный, порно вызывает привыкание и действует так же, как и любой наркотик. Спросите пользователя, который клянется, что ему нравится только " мягкая эротика" вроде журналов Playboy, переходил ли он когда-нибудь черту "небезопасного порно". И если они полностью честны, они скорее признаются в тех случаях, когда они вместо того чтобы ничего не употреблять, они находили какие-то причины и переходили черту "дозволенного".

И наслаждение не имеет к этому никакого отношения. Мне нравятся раки, но я ещё никогда не доходил до того, чтобы есть раков каждый день. Что касается других вещей в жизни, мы наслаждаемся ими, пока делаем их, но не сидим и не чувствуем себя обделенными, когда заняты чем-то другим.

Кто-то скажет:  
*"Порно познавательно!"* И как это помогло вам в личностном росте? 
*"Это сексуальное удовлетворение!"* Так почему же оно изолирует вас от общества и заставляет испытывать неутолимую тягу?
*"Это чувство разрядки!"* Освобождение от давления стрессов реальной жизни? Хорошо, на час, прежде чем все это обрушится на вас снова? И какие проблемы это решает?
*"Это помогает мне заснуть"* Так почему же другие могут прекрасно спать без порно? Существует [множество](https://www.sleepfoundation.org/insomnia/treatment/meditation) научно доказанных [методов](https://www.sleepfoundation.org/insomnia/treatment/cognitive-behavioral-therapy-insomnia) [, как наладить](https://www.amazon.com/Uvex-Blocking-Computer-SCT-Orange-S1933X/dp/B000USRG90) сон, и [даже больше](https://www.menshealth.com.au/what-is-the-military-method-the-technique-that-promises-to-help-you-sleep-in-2-minutes).

Многие считают, что порно избавляет от скуки, но скука -- это образ мыслей. Порно быстро приучит вас к поиску новизны, вызывая всё большую скуку, пока вы, наконец, не пуститесь в погоню за нужным роликом, становясь всё более и более зацикленным на поиске всего, что влечёт за собой новизну, сильные эмоции и, в конце концов, возмутительную шокирующую расплату.

Некоторые утверждают, что делают это только потому, что так делают их друзья и все, кого они знают. Если это так, молитесь, чтобы для избавления от головной боли ваши друзья не начали отрезать себе голову! Большинство пользователей, которые задумываются об этом, приходят к выводу, что это просто привычка. Это не совсем точное объяснение, но если отбросить все обычные, рациональные объяснения, это кажется единственным оставшимся оправданием. К сожалению, оно столь же нелогично, как и пример с отрезанием головы. Каждый день нашей жизни мы меняем привычки, некоторые из них очень приятные. Нам промыли мозги, внушив, что ПМО -- это привычка, и что от привычек очень трудно отказываться.

От привычек трудно отказываться? Водители в США привыкли ездить по правой стороне дороги, но, путешествуя за границей, они почти без всякого напряжения отказываются от этой привычки. Когда вы устраиваетесь на новую работу, у вас меняется распорядок дня, а значит, меняются и ваши привычки. К ним, возможно, придется привыкать, но это не сравнится с преодолением многолетней борьбы с порнозависимостью. Мы создаем и разрушаем привычки каждый день нашей жизни, так почему же нам так трудно отказаться от привычки, которая заставляет нас чувствовать себя обделенными, когда её у нас нет, и виноватыми, когда она у нас есть, от которой мы все равно хотели бы избавиться, если всё, что нам нужно сделать -- это *прекратить её делать?*

Ответ заключается в том, что порно -- это не привычка, *это зависимость!* Вот почему от неё так трудно "отказаться". Большинство пользователей не понимают, что такое зависимость, и считают, что получают от порно истинное удовольствие или поддержку. Они думают, что принесут большую жертву, если бросят порно.

Прекрасная правда заключается в том, что как только вы поймете истинную природу порнозависимости и причины, по которым вы используете порно, вы перестанете это делать. Так просто. В течение трех недель единственной загадкой будет то, почему вы считали необходимым использовать порно настолько долго, насколько вы это делали, и почему вы не можете убедить других пользователей в том, *как хорошо не быть ПМОером!*

## Зловещая ловушка

Интернет-порно - это изощренная и зловещая ловушка, выстроенная человеком и природой. Некоторых из нас даже предупреждают об опасности, но мы не можем поверить, нам кажется, что нам это нравится. Но что привлекает нас в первую очередь? Как правило, это бесплатные ролики от любителей и профессионалов, которые делятся ими. Вот так и срабатывает ловушка. Если бы вместо этого нас предупреждали об опасности того, во что мы ввязываемся, ещё до того, как мы делаем первый взгляд, тогда бы мы были обеспокоены и настороже.

Но никто не бьёт тревогу. Возможно, именно шокирующий характер многих клипов убеждает наши юные умы, что мы никогда не попадем на крючок, думая, что раз нам не нравится, то мы можем остановиться, когда захотим. Или, может быть, кажущаяся невинность мягкого материала не вызывает никаких тревожных сигналов, подобно тому как мошенник направляет наше внимание, куда ему надо, чтобы исполнить свой искусный фокус. Если бы нас предупреждали, мы бы, как разумные человеческие существа, поняли, почему половина взрослого населения систематически пристрастилась к чему-то, что очень сильно уменьшает наш потенциал в исполнения того действа, что мы смотрим. Любопытство приближает нас к порогу зависимости, но мы не осмеливаемся щелкнуть по обложкам роликов, на которые падает взгляд, боясь, что они сделают нас больными или направят на опасный и аморальный путь. А если мы случайно кликнули на одну из них, то зачастую наше единственное желание -- как можно скорее уйти со страницы, но в то же время отчаянно любопытствуем ещё больше.

Как только этот процесс начался, мы оказываемся в ловушке. С этого момента мы проводим остаток своей жизни, пытаясь понять, почему мы это делаем, уговаривая своих детей не начинать, а иногда пытаясь вырваться сами. Ловушка устроена таким образом, что мы пытаемся остановиться только в результате "инцидента", будь то сексуальная неудача, потеря карьеры или отношений, недостаток драйва или просто ощущение себя прокажённым. Как только мы останавливаемся, мы испытываем еще больший стресс из-за абстинентного синдрома, а метод, который мы использовали, чтобы снять этот стресс, теперь недоступен.

Наша решимость бросить порно оказывается шаткой. И после нескольких дней мучений мы убеждаем себя, что выбрали неподходящее время для отказа, и решаем переждать периоды без стресса, который, когда наступит, отменяет причины по которым мы значально прекратили -- всё хорошо, стресса нет, с чего бы прекращать. Конечно, этот период никогда не наступает насовсем, и мы начинаем считать, что наша жизнь становится все более и более стрессовой. Мы выходим из-под опеки наших родителей, и стрессы, связанные с работой, домашним хозяйством, ипотекой, покупкой жилья и воспитанием детей, начинают заполнять нашу жизнь. Но это иллюзия. Самые стрессовые периоды жизни любого существа -- это раннее детство и юность.

Мы склонны воспринимать ответственность, как стресс. Жизнь пользователя порно, как и жизнь наркомана, автоматически становится более стрессовой, потому что порно не расслабляет нас и не снимает стресс, как некоторые пытаются нас убедить. Всё происходит как раз наоборот: по мере того, как мы продолжаем употреблять порно, мы испытываем всё больший стресс, и чувство вины, возникающее после поздней ночи, подливает ещё больше масла в огонь. Даже те, кто бросил привычку -- а большинство делает это один или несколько раз на протяжении жизни -- могут вести абсолютно счастливую жизнь, но внезапно снова попасть на крючок. Заблудившись в порнографическом лабиринте, наш разум затуманивается, и мы проводим остаток жизни, пытаясь выбраться из него. Многим это удается, но позже они снова попадают в зловещую ловушку.

Решение проблемы порнозависимости -- это загадка. Она сложна и трудна. Но как только вы узнаёте ответ, он оказывается простым и забавным, и вы удивляетесь, как же вы не додумались до этого сами! EasyPeasy содержит решение этой загадки, оно выведет вас из лабиринта и вы больше никогда туда не забредете. Все, что вам нужно сделать, -- это в точности следовать всем инструкциям. Однако если вы сделаете **неправильный выбор, перескакивая между главами**, или **быстро пробежитесь по книге, читая по диагонали**, не приложив должных усилий при первом прочтении, то остальные инструкции будут бессмысленны.

Любой человек может легко прекратить использовать порно, но сначала мы должны установить некоторые факты. Нет, не страшные пугающие факты, подобной информации у вас уже более чем достаточно. Если бы это могло вас остановить, вы бы уже остановились. Почему же нам так трудно остановиться? Для ответа на этот вопрос необходимо знать истинную причину, по которой мы все еще используем порно, и она сводится к двум факторам. Это:

-   Природа человека + интернет-порно.

-   Промывание мозгов в обществе.

Пользователи порнографии -- разумные, рациональные человеческие существа. Они знают, что подвергают себя огромному риску в будущем, поэтому тратят много времени на рационализацию своей "привычки". Но в глубине души порнопользователи знают, что они глупцы, поскольку до того, как они подсели на порно, у них не было необходимости использовать его. Большинство помнит, что их первый "просмотр" был смесью отвращения и любопытства. Затем они специализируются на поиске, фильтрации и сохранению порно-роликов, упорно стараясь попасть на крючок.

Самое неприятное, что все, у кого нет порнозависимости -- большинство женщин, пожилых мужчин и людей, живущих в странах, где высокоскоростной интернет недоступен, -- ничего не теряют и считают всё это просто смешным. Разобравшись с этими факторами в следующих главах, вы тоже поймете, в чём же заключается зловещая ловушка!

