# От чего я отказываюсь?

**Абсолютно ничего!** От порно очень трудно отказаться из-за страха, что нас лишают удовольствия или опоры. Страх, что некоторые приятные ситуации уже никогда не будут такими, как прежде. Страх, что вы не сможете справиться со стрессовыми ситуациями. Другими словами, это последствия промывки мозгов, заставляющей нас верить в то, что секс -- и, следовательно, оргазм -- обязательное условие для всех человеческих существ. Более того, это убеждение, что в интернет-порно есть нечто, присущее нам, в чем мы нуждаемся, и что, прекратив его использование, мы отказываем себе и создаем пустоту.

Уясните это для себя: **Порно не заполняет пустоту,** ***а создает ее!***

Наши тела -- самые сложные объекты на планете. Верите ли вы в разумный замысел, естественный отбор или сочетание того и другого, наши тела в тысячи раз эффективнее людей! Мы не способны воссоздать ни мельчайшую живую клетку, ни чудеса зрения, размножения и различных взаимосвязанных систем, присутствующих в нашем теле или мозге. Если бы этот создатель или процесс эволюции предназначал бы нас для обработки сверхнормальных стимулов, мы были бы снабжены другими системами вознаграждения. Наше тело снабжено безотказными системами реагирования на внешние стимулы, которые мы игнорируем на свой страх и риск.

## Не от чего отказываться

Как только вы очистите свое тело от маленького монстра, а свой разум -- от большого монстра, вам не захочется ни часто мастурбировать, ни использовать для этого порно в Интернете. Существует множество известных и неизвестных фактов, когда речь идет о порнозависимости, причем многие представители медицинского сообщества не имеют понятия о том, как ставить вопрос или определять человека как порнозависимого. Многие симптомы ошибочно относят к другим причинам. И дело не в том, что пользователи -- глупые люди, просто без порно они несчастны. Они метаются из огня да в полымя -- если они воздерживаются, они несчастны, от того что не могут использовать порно, или если используют порно, чувствуют себя несчастными, потому что испытывают чувство вины и начинают презирать себя из-за этого. Когда у них появляются такие симптомы, как боли в пояснице или сексуальная дисфункция, их сознание разрывается между принятием ответственности и уходом в сторону.

Еще одна аналогия с курильщиками: все мы видели курильщиков, которые придумывают отговорки, чтобы украдкой сделать затяжечку, и мы видим истинную зависимость в действии. Наркоманы делают это не ради удовольствия, а потому что без этого они несчастны.

Для многих их первый сексуальный опыт закончился оргазмом, поэтому они приобрели убеждение, что не могут наслаждаться сексом без оргазма. Для мужчин порнография продвигается как подспорье в сексе, иногда даже как воспитание уверенности во время акта. Это нонсенс, обусловленность супер-интенсивными стимулами делает всё только хуже.

Не только не нужно ни от чего отказываться, но и можно добиться огромных положительных результатов. Когда пользователи задумываются о том, чтобы бросить курить, они, как правило, сосредотачиваются на здоровье и мужественности. Это веские и важные причины, но я лично считаю, есть что-то, что вы получаете, что важнее здоровья:

-   Возвращение вашей уверенности в себе и мужества.

-   Свобода от рабства.

-   У вас больше не будет темных секретов на задворках сознания и презрения к себе.

## Пустота, пустота, прекрасная пустота!

Представьте, что у вас на лице появилась сыпь, вы идете к фармацевту, он дает вам бесплатную мазь. Вы наносите мазь, и сыпь сразу же исчезает. Через неделю она появляется снова, вы возвращаетесь к фармацевту и спрашиваете, есть ли у него ещё мазь. Фармацевт говорит: *"Конечно, оставьте тюбик себе, он может понадобиться вам позже."*

Вы наносите мазь, и вуаля, болячка снова исчезает. Но каждый раз, болячка возвращается, и она становится все больше и больнее, а временной промежуток без сыпи всё короче и короче. В конце концов, болячка покрывает всё лицо, становится мучительно болезненной и возвращается каждые полчаса. Вы знаете, что мазь временно снимет её, но вы очень беспокоитесь. Распространится ли болячка со временем на все тело? Исчезнет ли интервал полностью? Вы ходите к врачу, но он не может вылечить болячку, поэтому вы пробуете другие средства, но кроме мази ничего не помогает.

И теперь вы уже полностью зависите от мази, вы никогда не выходите на улицу без тюбика. Если вы едете за границу, обязательно берете с собой несколько штук. Помимо того, что вы беспокоитесь о своем здоровье, аптекарь берет с вас по сто долларов за тюбик. У вас нет другого выбора, кроме как платить.

Вы натыкаетесь на статью об этом и узнаете, что это происходит не только с вами, многие люди страдают от такой же проблемы. На самом деле, медицинское сообщество обнаружило, что мазь на самом деле не лечит болячку, а только убирает её под поверхность кожи. И именно мазь вызвала рост болячки, поэтому всё, что вам нужно сделать, чтобы избавиться от болячки, -- это прекратить пользоваться мазью, и со временем болячка пройдёт.

Будете ли вы продолжать пользоваться мазью? Потребуется ли вам сила воли, чтобы больше не пользоваться мазью? Если вы не поверили статье, возможно, несколько дней вы будете испытывать опасения, но как только вы поймёте, что сыпь начинает проходить, необходимость или желание использовать мазь исчезнет. Будете ли вы несчастны? Конечно, нет! У вас была ужасная проблема, которую вы считали неизлечимой, но теперь вы нашли решение. Даже если бы потребовался год, чтобы болячка прошла, каждый день, по мере улучшения состояния, вы бы думали о том, как прекрасно себя чувствуете. В этом и состоит волшебство отказа от порно.

Болячка -- это не боль в теле, а отсутствие нормального сексуального влечения, слабое возбуждение, угасающая потенция, время, потраченное впустую на двухмерные изображения, чувство ущемления себя, презрение к людям, или, что ещё хуже, презрение к себе. Всё это в дополняет болезнь.

Она заставляет нас закрывать глаза на все эти вещи. Болячка -- это то чувство паники, когда хочется всё исправить. Люди, не употребляющие наркотики, не страдают от этого чувства. Самое худшее, что мы испытываем, -- это страх, а самое большое достижение -- избавление от этого страха. Он возникает после первого сеанса, укрепляется и вызывается каждым последующим.

Некоторые пользователи "счастливы", они ослеплены своими маленькими монстрами, и проходят через тот же кошмар, пытаясь оправдать свою глупость, выдвигая фальшивые аргументы.

*Так приятно быть свободным!*
