# Экономия времени

Обычно основными причинами, по которым пользователи пытаются бросить, являются здоровье, религия и осуждение партнёра. Частью промывания мозгов этим ужасным наркотиком является рабство в которое попадает пользователь; человек упорно боролся за отмену рабства -- но всё равно пользователь по собственному выбору проводит жизнь в рабстве. Они не замечают тот факт, что когда у них есть возможность использовать порно, они жалеют, что являются пользователями. Но когда мы "пытаемся" сократить потребление или воздержаться, или когда нас принуждают к воздержанию, порно становится ценным.

Невозможно переоценить, насколько промывка мозгов усложняет отказ от порнографии, поэтому чем больше заблуждений мы сейчас развенчаем, тем проще вы достигнете своей цели. Убежденные пользователи, которые не верят в негативное влияние порно на их здоровье (эректильная дисфункция, вызванная порно, гипофронтальность и т.д.) и не испытывают душевного беспокойства, как правило, молоды или одиноки и лишь иногда имеют случайные сексуальные связи. Таким образом, в силу их юного возраста внутренняя петля обратной связи утрачивается или же возникает слишком редко, и ничего не получается заметить или как-то отрефлексировать.

Более подходящим доводом для молодых пользователей является упущенное время. Если им говорят о здоровье или осуждения в социуме, они готовы поспорить и могут чувствовать себя ущемленными, но по когда речь заходит о времени... Если вы скажете: "*Не могу поверить, что тебя не беспокоит время, которое ты тратишь на порно.*". 
Скорее всего, вам ответят: "*О, ну я могу себе это позволить. Это всего лишь X часов в неделю, я думаю, оно того стоит, я так получаю удовольствие, это мой единственный грех.*"

"*Я всё ещё не могу поверить, что вам всё равно. Давайте предположим, что в среднем это занимает полчаса в день, включая физический отток дофамина, значит вы тратите примерно полный рабочий день каждые две недели. Я уверен, вы согласитесь, что полчаса в день -- это очень скромная оценка. Задумывались ли вы о том, сколько вашей жизни вы потратите на порно? Чем вы заняты в это время? Формируете настоящие отношения? Нет, ваша любимая порнозвезда не испытывает к вам симпатии только потому, что вы потратили столько времени на её видео -- вы просто тратите время впустую! Мало того, вы тратите это время, чтобы разрушить свое физическое здоровье, уничтожить свои нервы и уверенность, и для чего? Чтобы всю жизнь страдать от рабства, боли, меланхолии и раздражительности. Несомненно, это вас должно встревожить, верно?*"

В этот момент становится очевидно, особенно в случае молодых пользователей, что они никогда не задумывались о том, что это зависимость на ВСЮ ЖИЗНЬ. Иногда они подсчитывают, сколько времени они тратят за неделю, и это уже достаточно тревожно. Очень редко, и только когда они думают о том, чтобы завязать, они посчитают, сколько они тратят за год, это пугает, но то, сколько времени выходит за всю жизнь -- это немыслимо. Однако, поскольку мы спорим, убеждённый пользователь, как бы торгуясь, импульсивно скажет: *"Я могу себе это позволить, это всего лишь столько-то часов в неделю"*.

Откажетесь ли вы от предложения работы, где платят вашу текущую годовую зарплату, но дополнительно предлагают месяц отпуска каждый год? Любой пользователь согласился бы в мгновение ока и занялся бы поиском путёвок в экзотические места. Решить, как провести целый месяц без работы, было бы большой проблемой. Каждый разговор с подтвержденным пользователем (и, пожалуйста, имейте в виду, что он, в отличие от вас, не планирует останавливаться) заканчивался тем, что никто никогда не принимал моего предложения. Почему?

Часто на этом этапе убежденный пользователь говорит: *"Послушайте, меня не очень беспокоит денежный аспект".* Если вы думаете подобным образом, спросите себя, почему вы не беспокоитесь о времени. Почему в других аспектах вашей жизни вы идете на большие трудности, чтобы сэкономить несколько долларов здесь и там, но тратите тысячи, убивая свое счастье и вешая на себя порно-расходы?

Каждое рациональное решение, которое вы принимаете в своей жизни, будет результатом аналитического процесса взвешивания преимуществ и недостатков. Это может быть неправильное решение, но оно будет результатом рационального умозаключения. Когда любой пользователь взвешивает плюсы и минусы использования интернет-порно, ответ будет десятки раз повторяться: **"ОСТАНОВИСЬ! ТЫ - ЛОХ!"** Следовательно, все пользователи продолжают не из-за того, что они так решили или хотят этого, но из-за того, что не могут остановиться. Они ***вынуждены*** использовать порно, усиленно промывая себе мозги и пряча голову в песок.

Убежденные пользователи должны понять, что ситуация будет ухудшаться в геометрической прогрессии, появляется всё больше исследований и всё больше людей говорят о плохом влиянии интернет-порно. Сегодня это всё ещё не связанные с медициной люди, но завтра порнозависимость будет в списке заболеваний вашего врача. Прошли те времена, когда пользователь мог объяснить "простой" в своей сексуальной жизни рабочим стрессом; ваш партнер будет спрашивать, почему вы сидите за ноутбуком поздно ночью. Бедный пользователь -- и без того чувствующий себя несчастным и виноватым -- теперь хочет, чтобы земля разверзлась и поглотила его.

И вот что странно: многие люди готовы платить хорошие деньги за абонементы в спортзал и персональных тренеров, чтобы нарастить мышцы и выглядеть рельефно (и многие из них в своем мнимом (и реальном) отчаянии обращаются к таким методам лечения, как повышение тестостерона, с сомнительными и опасными побочными эффектами). Хотя большинству из них гораздо полезней было бы просто прекратить использование порнографии, систематически разрушающее естественные системы релаксации их мозга.

Это происходит потому, что они всё ещё думают мозгами пользователя. Выньте на мгновение голову из жопы. Интернет-порно -- это цепная реакция, цепь на всю жизнь, и если вы не разорвете эту цепь, то останетесь пользователем до конца своих дней. Оцените, сколько времени, по вашему мнению, вы будете тратить на порно до конца своего существования. Очевидно, что сумма будет разной у разных людей, но предположим, что это полтора года рабочих часов, именно рабочих. Представьте, если бы завтра на вашей простыне оказался чек на сумму, которую вы заработаете за рабочее время равное полутора годам, допустим 6 лет? Вы бы танцевали от восторга, так что начинайте танцевать! Вы вот-вот начнете получать эти блага!

Если вы думаете, что это хитрая уловка, вы всё ещё обманываете себя. Посчитайте, сколько времени вы бы сэкономили, если бы не начинали смотреть порно.

Вскоре вы примете решение о проведении свеого последнего сеанса (не сейчас, пожалуйста, помните инструкции!), оставаясь непользователем, не попавшись в ловушку снова. Всё, что вам нужно сделать, чтобы остаться непользователем, -- это не пользоваться порнографией и избегать "последних разочков". Помните, что если вы это сделаете, это будет стоить вам столько, сколько, по вашим расчетам, составляет ваша прибыль за упущенное время.

Если вы наставляете кого-либо в борьбе с порнозависимостью, скажите ему, что он очень хорошо знает человека, который отказался от предложения работы, где платят его текущую годовую зарплату, а также предоставляет ему оплачиваемый отпуск на целый месяц. Когда он спросит, кто этот идиот, ответьте: ***"Ты!"*** Грубо, но иногда, чтобы донести смысл, это необходимо.
