# Здоровье

Именно в этой области пользователям пробывают мозги больше всего, особенно молодым и одиноким, которые думают, что знают о рисках для здоровья, но это не так. Многие обманывают себя, говоря, что готовы принять последствия. Если бы ваш интернет-маршрутизатор имел функцию, что, когда вы попадаете на порносайт, воспроизводился бы сигнал тревоги с предупреждением: "До сих пор это сходило вам с рук, но если вы продолжите, ваша голова взорвется". Вы бы продолжили? Если вы сомневаетесь в ответе, попробуйте подойти к обрыву, встать на краю с закрытыми глазами и представить, что у вас есть выбор: либо бросить порно, либо идти вперёд с завязанными глазами.

И нет никаких сомнений, зарывая голову в песок и надеясь, что однажды утром вы проснетесь и больше не захотите смотреть порно, вы ничего не добьетесь. Пользователи не могут позволить себе думать о риске для здоровья, потому что если они это сделают, то иллюзорное удовольствие от зависимости исчезнет. Это объясняет, почему шоковая терапия так неэффективна на первых этапах выхода из зависимости: только те, кто не употребляет, могут заставить себя прочитать о разрушительных изменениях в мозге (и действительно воспринять это).

Возьмите к примеру этот обычный разговор с пользователями, как правило, более молодыми.

> **Я:** "Почему ты хочешь остановиться?"
>
> **Пользователь:** "*Я прочитал в блоге одного пикапера, что полезно воздерживаться четыре дня, чтобы поднять себе настроение.*"
>
> **Я:** "Вас не беспокоит риск для здоровья?"
>
> **Пользователь:** "*Нет, я же могу попасть завтра под автобус.*"
>
> **Я:** "Но стали бы вы сознательно бросаться под автобус?"
>
> **Пользователь:** "*Конечно, нет.*"  
>
> **Я:** "Но при этом ты не утруждаешься смотреть налево, направо, когда переходишь дорогу?"
>
> **Пользователь:** "*Нет же, конечно я смотрю по сторонам.*"

Именно, люди прилагают массу усилий, чтобы не попасть под автобус, и вероятность того, что это произойдет, составляет тысячи к одному. Однако пользователь рискует наверняка стать калекой из-за своей зависимости и, как будто, совершенно не замечает этого. Такова сила промывания мозгов; интернет-порно -- это волк в овечьей шкуре. Разве не странно, что если мы знаем, что в самолете есть малейшая неисправность, то не стали бы подниматься в него -- даже если бы риск был миллион к одному, -- в то время как с порнографией мы имеем более чем один к четырем, и, похоже, не обращаем на это внимания? А что получает от этого пользователь? **Абсолютно ничего!**

Ещё один распространенный миф -- это депрессия и тоска. Многие молодые люди не беспокоятся о своем здоровье, потому что не страдают депрессией или меланхолией. Но депрессия и стресс -- это не болезнь, а симптом. Молодые люди в целом не чувствуют раздражительности или депрессии, которые возникают из-за естественной способности их организма вырабатывать больше дофамина. Когда они стареют или в их жизни происходят серьезные неудачи, их и без того истощенные ресурсы расходуются ещё больше, и они испытывают полноценные симптомы. Когда пожилые пользователи чувствуют стресс, депрессию или раздражение, это происходит потому, что природные механизмы защиты защищают нервную систему от чрезмерного наводнения дофамином путем снижения чувствительности рецепторов. У пользователей также развиваются другие неврологические изменения, которые удерживают их в колее.

Подумайте об этом так: если бы у вас был хороший автомобиль и вы позволили ему ржаветь, ничего с этим не делая, это было бы довольно глупо. Он быстро превратится в неподвижную кучу ржавчины, не способную никуда вас доставить. Однако это не будет концом света, ведь речь идет только о деньгах. Но ваше тело -- это транспортное средство, которое везет вас по жизни. Мы все знаем, что здоровье -- это наш самый большой актив -- спросите любого больного миллионера. Большинство из нас могут вспомнить болезнь или несчастный случай, когда мы молились о выздоровлении. Пользуясь порнографией, вы не только позволяете ржавчине въедаться и ничего с этим не делаете, но и систематически разрушаете единственное транспортное средство, на котором вы ехали всю жизнь.

Поумнейте. Вам не нужно этого делать. Помните, что порно *абсолютно ничего* вам не даёт. Просто на мгновение вытащите голову из песка и спросите себя: если бы вы точно знали, что следующий сеанс запустит процесс, который сделает вас совершенно отстранённым по отношению к тому, кого вы глубоко любите, продолжали бы вы использовать порно? Говоря с людьми, с которыми такое случилось, они, конечно, не ожидали, что это произойдет и с ними, и самое страшное -- это не сама болезнь, а осознание того, что они сами её на себя навлекли. Попробуйте представить себе, что чувствуют люди, которые "нажали на волшебную кнопку", для них промывание мозгов закончилось. Они всю оставшуюся жизнь думают: *"Почему я так долго обманывал себя, что мне нужно мастурбировать на порно в Интернете? Если бы только у меня был шанс вернуться назад!".*

Перестаньте обманывать себя, у вас есть такой шанс. Это цепная реакция, если вы примете участие в следующем порносеансе, это приведет вас к следующему и следующему. Это уже происходило с вами. EasyPeasy не обещает шоковой терапии, поэтому если вы уже решили, что собираетесь остановиться, всё последующее не будет для вас шокирующим. Если ещё не решили, *пропустите остаток этой главы* и вернитесь к ней, когда прочитаете остальную часть книги.

О том, какой вред наносит интернет-порно нашей сексуальной жизни и психическому благополучию, уже написаны многие тома исследований. Проблема в том, что пока человек не решит остановиться, он и знать этого не хочет. Форумы и группы наставников -- пустая трата времени, потому что порно надевает на глаза повязку. Даже если они случайно прочитают все эти статьи, всё равно первое, что они сделают -- это откроют свой любимый порносайт. Пользователи порно склонны думать, что проблемы со счастьем, стрессом и сексом являются для них чем-то вроде наступления на мину.

Вбейте себе в голову, что это уже происходит. ***Каждый раз***, когда вы открываете порносайт, вы запускаете дофаминовое наводнение и опиоиды приступают к работе. Нейронные водные горки смазаны, и аттракцион плавно ведет вас через следующие шаги, ваш мозг уже поддался сценарию. Нервная система теперь наводнена дофамином, и поскольку это уже в десятый раз, дофаминовые рецепторы закрываются, и маленький монстр использует этот небольшой спад в удовольствии по сравнению с прошлым разом, чтобы заставить вас еще дальше переступить красную черту к более шокирующему порно или поведению, чтобы высвободить больше дофамина. Больше новизны, больше дофамина, и маленький монстр говорит вам продолжать. Множество фотографий и видео за один сеанс вызывают сверхнормальный стимул, впрыскивая в мозг больше химических веществ и побуждая вас продолжать.

Всё это время ваши рецепторы получают информацию о необходимости отключиться в ответ на наводнение. Оргазм только усиливает этот эффект и приводит к абстиненции. Вы отрицаете, поскольку маленький монстр жаждет получить свою порцию без реальной боли и дискомфорта. Угроза эректильной дисфункции пугает многих, поэтому они блокируют её в своем сознании и заслоняют ее страхом, они боятся бросить порно. И дело не в самом страхе, а в том, что бросить сейчас -- это значит прямо сейчас. Ваше мышление таково (возможно вы этого не осознаёте): зачем мне вообще смотреть на негативную сторону, если к тому времени, как что-то страшное могло бы произойти, я уже точно брошу.

Мы склонны думать о порно как о перетягивании каната: на одной стороне страх: *"Это нездорóвое, грязное рабство"*. С другой стороны -- позитив: *"Это мое удовольствие, мой друг, моё небольшое подспорье"*. Нам никогда не приходит в голову, что эта сторона -- на самом деле тоже страх; и дело не в том, что нам нравится порно, а в том, что без него мы, несчастны. Героиновые наркоманы, лишенные героина, проходят через страдания, но представьте себе безмерную радость, когда им наконец-то разрешают воткнуть иглу в вену и покончить с этим ужасным страстным желанием. Только представьте, кто-то реально верит, что получает удовольствие от введения в вену шприца для подкожных инъекций. Но подумайте, обычные люди никогда не испытывают такой паники, это значит, что героин не снимает чувство паники от ломки, а наоборот, он его вызывает.

Непользователи не чувствуют себя несчастными, если им запрещают использовать порно -- от этого страдают только пользователи. Интернет-порно не снимает это чувство, оно его вызывает. Страх перед негативными последствиями не помогает пользователям бросить, потому что они отождествляют это чувство с хождением по минному полю. Если вам все сойдет с рук, то всё хорошо, а если вам не повезло, вы наступили на мину и столкнулись с последствиями. Если бы вы реально понимали риски и были бы готовы их принять, тогда ладно, о чём тут говорить? Но порно-наркоманы обычно вырабатывают следующую тактику уклонения.

"***В конце концов, мы всё равно состаримся и утратим свою сексуальную мощь...***"  

Конечно, да, но сексуальная мощь здесь ни при чем -- мы говорим о рабстве. Даже если это так, разве это логичная причина для того, чтобы намеренно укорачивать себе жизнь?

"***Качество жизни важнее, чем просто жить.***"  

  Именно! Вы полагаете, что качество жизни наркомана выше, чем у человека, не страдающего зависимостью? Вы действительно считаете, что качество жизни человека, употребляющего наркотики, лучше, чем качество жизни человека, не употребляющего наркотики? Жизнь, проведенная с головой в песке и в несчастье, не кажется приятной.

"***Я одинок и не планирую остепеняться в будущем, так что почему бы и нет?***"

Даже если бы это было правдой, разве это логичная причина для игры с неврологическими механизмами контроля импульсов? Можете ли вы представить себе, что кто-то может быть настолько глуп, чтобы всегда раздевается догола и готовится к сексу каждый раз, когда остаётся один, даже если он знает, что никто не придёт? **Вот чем эффективно занимаются пользователи порно!**

Постепенное разрушение контуров вознаграждения чрезмерной стимуляцией, делающее их неспособными справляться с обычными жизненными стрессами, не помогает наслаждаться жизнью с энтузиазмом и бодростью. Порно и мастурбация заменили естественный сексуальный аппетит, как шоколадка заменяет настоящую еду. Неудивительно, что многие врачи и психологи теперь связывают различные проблемы с психическим здоровьем с физиологическими причинами. Основная медицинская общественность трубит, что никогда не было научно доказано, что порно является прямой причиной проблем, о которых сообщают люди, признающие себя таковыми, но признание своей сексуальной неспособности на публике -- это нечто, вызывающее стыд, так зачем же кому-то делать это, если он не обеспокоен по-настоящему или не нашел причину и не устранил её из своей жизни?

EasyPeasy поможет вам избавиться от порнографии и стать счастливым бывшим пользователем. Никакого порно, мастурбации с помощью порно или излишних оргазмов. Единственными стимулами будут прикосновения, взгляд и запах вашего партнера. Как цельнозерновой хлеб после разыгравшегося аппетита -- вам больше не захочется кукурузного сиропа с высоким содержанием фруктозы из интернет-порно. Доказательство настолько ошеломляющее, что не требует обоснования; когда я бью молотком по пальцу, и он болит, мне это не нужно это доказывать. Стресс от интернет-порно оказывает влияние на другие аспекты жизни пользователя, предрасполагая многих к наркотикам, таким как сигареты и алкоголь, чтобы справиться с ситуацией, а в некоторых случаях кто-то даже задумывается о самоубийстве.

Пользователи также страдают иллюзией, что вредное воздействие порнографии преувеличено. Но всё обстоит как раз наоборот: нет никаких сомнений в том, что интернет-порно является основной причиной сексуальной дисфункции и многих других проблем. Сколько разводов вызвано порнографией? Точно узнать невозможно, но, судя по поиску в интернет-сообществах, это число растет в геометрической прогрессии.

В сериале *"Друзья"* есть эпизод, где парни, получавшие непрерывное бесплатное порно по телевизору, начали удивляться, от чего же разносчица пиццы не захотела посмотреть их "большую спальню". Когда вы зависимы, вы неизбежно проецируете порнофантазии на реальных женщин. Представьте себе, что может сделать неосторожный или даже случайный просмотр порно в темных уголках Интернета с человеком, который уже находится на переломном этапе своей жизни. Борьба мыслями, вызванными порнографией, сильно подорвет его психическое здоровье.

Вот еще один мысленный эксперимент: допустим, кто-то приходит к вам и говорит, что не обязательно хочет оргазма, но очень хочет заняться проникновенной любовью. Они хотят делать это столько и так долго, насколь только возможно без оргазма -- но если он случится, то это прекрасно. Я заверяю вас в получении нового феноменального сексуального опыта, намного лучше любого другого, если конечно вы когда-нибудь получите такое предложение. Попробуйте.

Под воздействием промывания мозгов мы склонны мыслить, как человек, который, падая со 100-этажного здания и пролетая мимо пятидесятого этажа, говорит: "Пока что всё хорошо!". Мы думаем, что раз уж нам до сих пор всё сходило с рук, то ещё один сеанс порно не ухудшит ситуацию. Посмотрите на это с другой стороны: "привычка" -- это непрерывная цепочка на всю жизнь, где каждый сеанс создает потребность в следующем. Когда вы начинаете привычку, вы поджигаете фитиль. Проблема в том, что вы не знаете, насколько длинный фитиль. Каждый раз, когда вы поддаетесь порносеансу, вы на шаг ближе к взрыву бомбы. **КАК ВЫ УЗНАЕТЕ, ЧТО ЭТО НЕ НА СЛЕДУЮЩИЙ РАЗ?**

## Зловещие чёрные тени

Пользователям очень трудно поверить, что порно действительно вызывает те нестабильные состояния, как когда вы выходите на улицу поздно вечером после напряженного дня на работе и чувствуете себя небезопасно и неуверенно. Непотребители не страдают от этого, ведь это заслуга порно.

Ещё одна большая радость от отказа от порнографии -- это свобода от зловещих чёрных теней на задворках нашего сознания. Все пользователи знают, что они глупцы, и совершают глупость, закрывая глаза на дурное влияние порнографии. Большую часть жизни это происходит автоматически, но чёрные тени всегда таятся в нашем подсознании чуть ниже поверхности. Некоторые из чудесных преимуществ отказа от порнографии являются осознанными, например, прекращение пустой траты времени и абсолютной глупости занятия любовью с двухмерным изображением.

В предыдущих главах речь шла о значительных преимуществах того, что вы не являетесь пользователем, но в интересах справедливости необходимо дать сбалансированное мнение. Поэтому в следующей главе я перечислил все преимущества быть пользователем порнографии.

# Преимущества использования порно
