# Метод силы воли

В обществе принято считать, что бросить порнографию очень сложно. Книги и форумы, советующие, как остановиться, обычно начинаются с того, что рассказывают, насколько это трудно. Правда же заключается в том, что это до смешного легко. Понятно, что можно поставить под сомнение это утверждение, но сначала просто подумайте об этом. Если ваша цель -- пробежать милю за четыре минуты, это дико сложно, и вам придется потратить годы на тяжелые тренировки, и даже тогда, возможно, вы будете физически неспособны.

Однако все, что вам нужно сделать, чтобы перестать смотреть порно, -- это больше не смотреть его и/или не мастурбировать. Никто не заставляет вас мастурбировать (кроме вас самих), и в отличие от еды или воды, это не нужно для выживания. Так что если вы хотите прекратить это делать, почему же это должно быть трудно? На самом деле, это не трудно. Это пользователи делают это трудным для себя, используя силу воли или любой метод, который заставляет пользователя чувствовать, что он идет на какую-то жертву. Давайте рассмотрим этот подход.

Мы не решаем стать пользователями, мы просто экспериментируем с порножурналами или веб-сайтами, и поскольку они все, за исключением нашего желанного клипа, ужасны (именно так, ужасны), мы убеждены, что сможем остановиться, как только захотим. Сначала мы смотрим те первые несколько клипов, когда захотим и по особым случаям. Прежде чем мы осознаем это, мы не только регулярно посещаем эти сайты и мастурбируем, "когда хотим" -- но мы мастурбируем на них ежедневно. Порно стало частью нашей жизни, обеспечивая нам необходимость подключения к Интернету, куда бы мы ни пошли. Мы считаем, что имеем право на любовь, секс, оргазм и снимающие стресс свойства порно. Нам не приходит в голову, что один и тот же клип и актеры не обеспечивают нам такой же степени возбуждения, и мы начинаем бороться с красной чертой, пытаясь избежать "плохого порно". На самом деле, мастурбация и интернет-порно не улучшают нашу сексуальную жизнь и не снимают стресс, просто пользователи считают, что без этого они не могут наслаждаться жизнью или справляться со стрессом.

Обычно требуется много времени, чтобы понять, что мы попали на крючок, потому что мы страдаем от иллюзии, что пользователи смотрят порно, потому что им это нравится, а не потому, что им это ***необходимо***. Когда мы не получаем "удовольствия" от порно, чего не бывает, если не добавляется новизна, шок или эскалация, у нас возникает иллюзия, что мы можем остановиться в любой момент. Это ловушка уверенности. *"Мне не нравится порно, поэтому я могу остановиться, когда захочу"*. Только, похоже, вы никогда не "захотите" остановиться.

Обычно мы осознаем, что проблема существует, только когда пытаемся остановиться. Первые попытки обычно бывают ранними -- их провоцирует знакомство с партнером, когда после первых свиданий мы замечаем, что он "недостаточно хорош". Другая распространенная причина -- невозможность не замечать последствия для здоровья, проявляющиеся в повседневной жизни.

Независимо от причины, пользователь всегда ждёт стрессовой ситуации, будь то крах здоровья или неудача в сексе. Как только они прекращают использовать порно, маленький монстр начинает испытывать голод. Тогда пользователю хочется чего-то, что поднимет его дофамин, например, сигарет, алкоголя или его любимого -- интернет-порно, гарем которого находится всего в одном клике от него. Порно тайник больше не находится в подвале, он виртуальный и доступен из любого места. Если его партнер рядом или они с друзьями, у них больше нет доступа к своему виртуальному гарему, что расстраивает его ещё сильнее.

Если пользователь сталкивался с научными материалами или интернет-сообществами, он начинает вести перетягивание каната в своем сознании, сопротивляясь соблазнам и чувствуя себя обделенным. Их способ обычного снятия стресса теперь недоступен, и они получают тройной удар. Вероятным результатом после этой пытки будет компромисс: *"Я сокращу"* или *"Я выбрал неподходящее время"*, или, возможно, *"Я подожду, пока стресс не исчезнет из моей жизни"*. Однако, как только стресс проходит, уже нет причин прекращать, и пользователь не собирается бросать, пока снова не наступит сложное время в жизни.

Конечно, никогда не бывает подходящего момента, потому что жизнь большинства людей становится более напряженной. Мы выходим из-под опеки родителей, вступаем в мир, обустраиваем свою жизнь, ипотеки, рождение детей и более ответственная и сложная работа. Независимо ни от чего, жизнь пользователя не может стать менее стрессовой, потому что порно на самом деле вызывает стресс. Чем быстрее пользователь переходит на стадию обострения, тем больше он страдает и тем больше растет иллюзия зависимости.

На самом деле, это иллюзия, что жизнь становится более напряженной, а порнография -- или аналогичный костыль -- создает эту иллюзию. Более подробно об этом будет сказано позже, но после первых неудач пользователь обычно полагается на то, что однажды он проснется и просто не захочет мастурбировать или использовать порно. Эта надежда обычно разжигается историями, услышанными от других бывших пользователей: *"Я не был серьезным, пока у меня не обвял во время секса, и я больше не хотел использовать порно и перестал мастурбировать".*

Не обманывайте себя, проанализируйте эти слухи, и вы обнаружите, что все не так просто, как кажется. Обычно пользователь уже готовился к тому, чтобы бросить, и просто использовал этот инцидент как трамплин. Чаще всего люди, которые прекращают "просто так", переживают шок: возможно, их застукал партнер, или они сами заметили, что обращаются к порнографии, не соответствующей их обычной сексуальной ориентации, или реальная сексуальная дисфункция их сильно напугала. "*Просто я такой человек*". Перестаньте обманывать себя. Этого не произойдет, если вы сами этого не сделаете.

Давайте рассмотрим более подробно, почему метод силы воли настолько неэффективен. Большую часть своей жизни мы придерживаемся методы "*я перестану завтра*". В редкие моменты что-то провоцирует попытку остановиться. Это может быть беспокойство о здоровье, мужественности или самоанализ и осознание того, что мы не получаем от этого удовольствия. Какова бы ни была причина, мы начинаем взвешивать все плюсы и минусы порнографии. Секс бывает чувственный (прикосновение, запах, голос) и детородный (оргазм и эякуляция); понимание разницы -- это один из главных ключей к открытию нашего сознания, и без этого важного различия будет путаница, которая приведет к неудаче. При рациональной оценке мы обнаруживаем истину, которую знали всю жизнь. Одно и тоже повторяется тысячи раз "***ПЕРЕСТАНЬТЕ СМОТРЕТЬ ЕГО!***"

Если бы вы сели и распределили по пунктам преимущества прекращения и сравнили их с преимуществами порнографии, то общее количество очков за прекращение значительно перевесило бы все "недостатки". Если вспомнить про пари Паскаля, то, бросив порно, вы почти ничего не теряете, с высокими шансами на выигрыш и высокими шансами на то, что не потеряете. Хотя пользователь знает, что ему будет лучше, если он станет непользователем, убежденность в том, что он чем-то жертвует, останавливает его. И хотя это иллюзия, она сильна. Они не знают почему, но у пользователя есть убеждение, что в хорошие и плохие времена жизни сеансы как-то помогают. Ещё перед тем как попытаться бросить порно, промывание мозгов обществом, усиленное промыванием мозгов от собственной зависимости, затем сочетается с ещё более сильным промыванием мозгов о том, как трудно "отказаться".

Пользователи слышат истории тех, кто прекратил использовать порно на многие месяцы, но всё ещё отчаянно жаждет этого, или о недовольных бросающих, которые, прекратив, проводят остаток своей жизни, сокрушаясь о том, что они с удовольствием провели бы ещё сеанс. Есть истории о том, как пользователи прекращали употребление в течение многих месяцев или лет, жили счастливой жизнью, но стоило им только "заглянуть" в порно, и они снова оказывались на крючке. Пользователи, вероятно, знают нескольких человек на поздних стадиях заболевания, которые заметно разрушили себя и явно не получают удовольствия от жизни, но всё равно продолжают употреблять порно. Кроме того, они, вероятно, сами пережили один или несколько подобных случаев.

Поэтому вместо того, чтобы начать с чувства: "*Вот здорово! Вы это слышали? Мне больше не нужно смотреть порно!*", они начинают с чувства обреченности и уныния -- как будто пытаются взобраться на Эверест -- и ошибочно полагают, что как только маленький монстр вцепится в вас, вы останетесь на крючке на всю жизнь. Многие пользователи начинают попытки с извинений перед подругами или женами: "*Слушай, я пытаюсь отказаться от порно. Возможно, следующие пару недель я буду раздражительным, так что постарайтесь потерпеть*". Большинство попыток обречены ещё до начала.

Предположим, что пользователь прожил несколько дней без сеанса. К нему возвращается возбуждение, он начинают восстанавливаться. Он не открывают свои любимые сайты и, следовательно, возбуждается от обычных стимулов, на которые раньше не обращал внимания. Причины, по которым он решил остановиться, быстро улетучиваются. Как если бы они увидели ужасную дорожную аварию, будучи за рулем. Этот инцидент замедлит вас на некоторое время, но всё равно, в следующий раз, когда будете опаздывать на важную встречу, вы будете гнать сильнее обычного.

По другую сторону войны находится маленький монстр, который до сих пор не получил своего. Физической боли нет -- если бы у вас было такое же чувство из-за простуды, вы бы не бросили работу и не впали в депрессию, а просто посмеялись бы над этим. Все, что знает пользователь, -- это то, что он хочет посетить свой гарем. Маленький монстр знает это и запускает большого монстра промывания мозгов, заставляя того же человека, который несколькими часами или днями ранее перечислял все причины прекратить, теперь отчаянно искать любой предлог, чтобы начать снова. Они начинают говорить такие вещи, как:

-   "*Жизнь слишком коротка, бомба уже могла взорваться, завтра я могу попасть под автобус. Я слишком поздно спохватился. В наше время говорят, что всё вызывает зависимость.*"

-   "*Я выбрал неподходящее время.*"

-   "*Мне следует подождать до Нового Года, после праздников/экзаменов, брошу после этого стрессового события в моей жизни.*"

-   "*Я не могу сконцентрироваться, становлюсь раздражительным и вспыльчивым, я даже не могу нормально выполнять свою работу.*"

-   "*Моя семья и друзья не будут меня любить. Давайте посмотрим правде в глаза, ради всех я должна начать все сначала. У меня подтвержденная сексуальная зависимость, и я никак не смогу снова стать счастливой без оргазма.*"

-   "*Никто не может выжить без секса.*" (Мозги промыты "благонамеренными" людьми).

-   "*Я знал, что это произойдет, мой мозг "сенсибилизирован" DeltaFosB из-за изменений, вызванных скачками дофамина из-за моего прошлого чрезмерного употребления порно. Сенсибилизация никогда не может быть исправлена.*"

На этом этапе пользователь обычно сдается. Запускается браузер, а шизофрения усиливается. С одной стороны, есть огромное облегчение от прекращения желания, когда маленький монстр наконец-то получает свою дозу; с другой стороны, оргазм ужасен, а пользователь не может понять, зачем он это делает. Вот почему пользователь думает, что ему не хватает силы воли. На самом деле это не отсутствие силы воли, всё, что им нужно сделать, это изменить своё мышление и в соответствии с полученными сведениями принять вполне рациональное решение.

"*Какой смысл быть здоровым или богатым, если ты несчастен?*"

Абсолютно никакого! Гораздо лучше иметь короткую приятную жизнь, чем долгую несчастную. К счастью, это неправда для тех, кто не употребляет наркотики, так как такая жизнь гораздо приятнее. Страдания, которые испытывает пользователь, вызваны не абстинентным синдромом -- хотя вначале он его вызывает -- на самом деле это борьба в сознании, вызванная сомнениями и неопределенностью. Поскольку вначале пользователь чувствует, что идет на жертву, он начинает чувствовать себя обделенным, что является серьёзной формой стресса.

В один из таких стрессовых моментов, желая вернуться в старое состояние, мозг предлагает "глянуть только одним глазком", сразу после того как пользователь бросил. Но поскольку он остановился, он не может этого сделать, и это приводит к ещё большей депрессии и снова запускает пусковой механизм. Ещё один фактор, делающий отказ от порно таким сложным, -- это ожидание того, что должно произойти. Если ваша цель -- сдать экзамен по вождению, то как только вы сдадите экзамен, вы будете уверены, что достигли своей цели. При методе силы воли внутреннее повествование звучит так: "Если я смогу достаточно долго не смотреть порно, желание посмотреть его в конце концов пройдет". Вы можете увидеть это на практике на интернет-форумах, где зависимые люди рассказывают о своих периодах и количестве дней воздержания.

Как уже было сказано выше, агония, которую испытывает пользователь, является психической и вызвана неопределенностью. И хотя она и не вызывает физической боли, она всё равно оказывает сильное воздействие. Теперь несчастный и неуверенный в себе пользователь далек от забвения, теперь он полон сомнений и страхов.

-   "*Как долго продлится тяга?*"

-   "*Буду ли я когда-нибудь снова счастлива?*"

-   "*Захочу ли я когда-нибудь вставать по утрам?*"

-   "*Как я буду справляться со стрессом в будущем?*"

Пользователь ждет улучшения ситуации, а пока он хандрит, "гарем" становится всё более желанным. На самом деле, что-то *действительно* происходит, пользователь этого не осознаёт, но если он проживёт несколько недель, не открывая порно, тяга к маленькому монстру исчезает. Однако, как уже говорилось ранее, синдром отмены дофамина и опиоидов настолько слаб, что пользователь даже не осознаёт его. В это время многие потребители чувствуют, что "завязали", и, чтобы доказать это, делают "глоток", который снова отправляет их вниз по водной горке. Получив вброс дофамина в организм, в глубине сознания раздается голос: "Ты хочешь ещё". На самом деле они действительно уже бросили, но снова попались на крючок.

В детстве вы смотрели мультфильмы, и, согласно данным нейронауки, у вас сформировались нейронные пути (DeltaFosB) для них. Представьте, что вы хотите отучить ребенка от просмотра мультиков. Вы узнали бы, существуют ли ещё такие пути у вас. Вы опросили бы взрослых, почему они больше не смотрят любимые детские мультфильмы. И во-первых, есть развлечения получше, а во-вторых, мультфильмы больше не обладают той магией. При использовании метода силы воли вы просто запрещаете ребенку смотреть мультики, а при использовании EasyPeasy, ребёнок реально понимает, что в мультиках ничего нет, ему становится не интересно и он перестаёт их смотреть сам. Какой подход лучше?

Обычно пользователь не приступает к очередному сеансу сразу после предыдущего: *"Я не хочу снова попасться на крючок!"*, пользователь ждёт необходимый на свой взгляд период в несколько часов, дней или даже недель. Затем бывший пользователь может сказать: *"Ну всё, я не зависим, значит, я могу спокойно провести ещё один сеанс"*. Они уже попали в ту же ловушку, что и в первый раз, и встали на скользкий путь.

Те, кто добился успеха, используя метод силы воли, обычно считают его долгим и трудным, потому что основная проблема заключается в промывании мозгов. Спустя долгое время после того, как физическая зависимость угасла, пользователь всё ещё хандрит и чувствует себя несчастным. В конце концов, после длительной пытки его посещает озарение, что он бросил и никогда больше не будет использовать порно, он перестаёт хандрить и признаёт, что жизнь продолжается и без порно. Процент неудач значительно выше, чем процент успеха, потому что те, кто добился успеха, проходят через всю свою жизнь в уязвимом состоянии, думая, что порно действительно дает им стимул, в какой-то степени оставаясь с промытыми мозгами. Это объясняет, почему многие пользователи, надолго прекратившие употреблять порно, впоследствии начинают снова.

Многие бывшие потребители время от времени проводят сеансы в качестве "особого лакомства" или чтобы убедить себя в том, насколько силен их самоконтроль. Это именно так -- но как только сессия заканчивается, дофамин начинает уходить, и маленький голосок в глубине сознания начинает подталкивать их к новой сессии. Если они соглашаются и используют снова, то им всё ещё кажется, что всё под контролем, никаких потрясений, эскалации или стремления к новизне, поэтому они говорят: "Замечательно! Пока мне это не так сильно нравится, я не попадусь на крючок. После Рождества / этого праздника / этой травмы я остановлюсь". Они даже не подозревают, что таким образом водные горки в их мозгу смазываются ещё сильнее.

Слишком поздно, они уже на крючке! Ловушка, из которой им удалось вырваться, снова схватила свою жертву.

Как было сказано ранее, удовольствия здесь нет. И никогда не было! Если бы мы смотрели из-за удовольствия, никто бы не оставался на сайтах дольше, чем требуется для завершения дела. В любом случае, лучший способ самоудовлетворения -- это воспоминания. Мы верим, что получаем удовольствие от порно только потому, что не можем допустить, что мы настолько глупы, что попали в зависимость, которая даже не приносит удовольствия. Большинство пользователей не имеют никакого представления о сверхнормальных стимулах, новизне или стремлении к шоку, и даже прочитав об этом, они не верят, что их употребление мотивировано эволюционной схемой вознаграждения. Именно поэтому большая часть порнографии является подсознательной -- если бы вы знали о неврологических изменениях в мозге и признали бы, что эта зависимость стоит вам больших денег в будущем, даже иллюзия удовольствия исчезла бы.

Когда мы пытаемся отгородиться от плохого, мы чувствуем себя глупо. Если бы нам пришлось открыться этому, это было бы невыносимо! Если вы понаблюдаете за пользователем в действии, вы увидите, что он счастлив только тогда, когда не знает, что употребляет. Как только это становится ему известно, они начинают испытывать дискомфорт и извиняться. Порно питает маленького монстра, поэтому, когда вы вычистите его из своего тела вместе с промывкой мозгов (большим монстром), у вас не будет ни потребности, ни желания смотреть порно!
