# Не стоит уменьшать

Многие пользователи прибегают к уменьшению просмотра порно в качестве ступеньки к прекращению употребления или в качестве попытки контролировать маленького монстра. Многие рекомендуют сокращение или "порнодиету" как средство для поднятия настроения. Использование сокращения как ступеньки к прекращению употребления порно ***смертельно опасно***. Именно эти попытки завязать с порнографией держат нас в ловушке до конца жизни. Как правило, порнодиета следует за неудачными попытками остановиться. После нескольких часов или дней воздержания пользователь говорит что-то вроде:

"*Я не могу смириться с мыслью о том, что буду ложиться спать, не посетив свой онлайн-гарем, поэтому с этого момента я буду использовать порно только раз в четыре дня или очищать свою коллекцию "плохого порно". Если я смогу следовать этой порнодиете, то смогу либо удержаться на текущем уровне, либо сократить ещё больше.*"

Теперь происходят ужасные вещи:

1.  Они застряли в худшем из всех миров: они по-прежнему зависимы от интернет-порнографии и поддерживают жизнь монстра не только в своем теле, но и в своем сознании.

2.  На самом деле проживают свою жизнь в ожидании следующего сеанса.

3.  До начала сокращения, когда бы они ни захотели посетить свой гарем, они запускали браузер и хотя бы частично снимали абстинентный синдром. Теперь же, в дополнение к обычным жизненным стрессам, они заставляют себя страдать от абстинентного синдрома большую часть своей жизни, что делает их ещё более несчастными и раздражительными.

4.  Потакая себе, они не получали удовольствия от большинства сеансов и не осознавали, что используют сверхнормальный стимул. Это происходило автоматически, единственное посещение гарема, которое доставляло удовольствие, было после периода воздержания. 
Теперь, когда они ждут посещения гарема, они "наслаждаются" каждым часом без гарема. Чем дольше они ждут, тем более "приятным" становится каждый сеанс, потому что "приятным" в сеансе является не сам сеанс, а прекращение беспокойства, вызванного тягой -- будь то легкая физическая жажда или умственная хандра. Чем дольше страдания, тем более "приятным" становится каждый сеанс.

Основная трудность в прекращении употребления заключается не в неврологической зависимости, которая протекает легко. Пользователи прекращают употребление без особых трудностей в различных случаях -- смерть близкого человека, семейные или рабочие дела и т.д. Они могут, скажем, десять дней не использовать порно, и это их не беспокоит. Но если бы они провели те же десять дней, когда у них мог быть доступ к порно и они хотели, они бы рвали на себе волосы.

Многие пользователи получив шанс посмотреть порно во время рабочего дня и спокойно воздержатся, или посетят Victoria's Secret, бассейны и так далее без излишних неудобств. Многие воздержатся, если им придется временно спать на диване, чтобы освободить место для посетителя, или если они сами находятся в гостях. Даже в Go-Go барах или на нудистских пляжах не было срывов. Пользователи почти рады, когда кто-то или что-то говорит, что им нельзя смотреть порно. На самом деле, пользователи, которые хотят бросить, получают тайное удовольствие от длительного отсутствия посещений гарема, это дает им надежду на то, что, возможно, однажды они больше не захотят использовать порно.

Настоящая проблема при прекращении -- это промывание мозгов, иллюзия самоценности, что интернет-порно -- это своего рода поддержка или награда, и без него жизнь никогда не будет прежней. Далеко не всегда отказ от интернет-порно приводит к тому, что вы чувствуете себя неуверенным и несчастным, убеждая себя в том, что самое ценное на этой земле -- это новый ролик, который вы пропустили, что вы никак не сможете стать счастливым, не увидев его.

Нет ничего более жалкого, чем пользователь, который пытается сократить просмотр порно, страдая от заблуждения, что чем меньше он смотрит порно, тем меньше ему захочется посетить свой онлайновый гарем. Верно и обратное - чем меньше они смотрят порно, тем дольше они страдают от абстинентного синдрома и тем больше "наслаждаются" облегчением от его снятия. Скоро они заметят, что их любимый жанр не приносит им былого удовольствия. Но это их не остановит: если бы порносайты были посвящены только одной звезде или одному жанру, ни один пользователь не зашел бы туда больше одного раза.

Трудно поверить? Какой самый худший момент самоконтроля, который вы испытываете? Ждать четыре дня, а потом испытать кульминацию. Тогда какой самый драгоценный момент для большинства пользователей, сидящих на четырехдневной порнодиете? Правильно, тот самый кульминационный момент после четырехдневного ожидания! Вы действительно верите, что мастурбируете, чтобы насладиться оргазмом? Вот вам более рациональное объяснение: вам просто нужно снять абстинентный синдром, питая иллюзию, что вы имеете на это полное право, ведь вы же воздерживались.

Устранение "промывания мозгов" необходимо для того, чтобы избавиться от иллюзий относительно порно до того, как вы погасите последний сеанс. Если, прежде чем закрыть окно, вы не избавились от иллюзии, что вам нравится порно, вы никак не сможете доказать это после, не попавшись на крючок снова. Нависая над закладками и сохраненными фотографиями, спросите себя, что в этом действии такого великолепного. Возможно, вы считаете, что определенный клип хорош. Если это так, то зачем смотреть другие клипы или темы? Потому что у вас это вошло в привычку? Зачем кому-то привычка засорять свой мозг и тратить себя впустую? Через месяц ничего не меняется, так почему же порноклип должен быть новый?

Вы можете проверить это сами. Найдите горячий клип из прошлого месяца, чтобы доказать, что он уже другой. Затем установите напоминание и посмотрите тот же клип после месяца без порно. Он будет (почти) ощущаться так же, как и в прошлом месяце. И всё же тот же самый ролик будет отличаться после события, где вам отказал или устроил испытание потенциальный партнер. Причина в том, что зависимый никогда не сможет быть полностью счастлив, если маленький монстр остается неудовлетворенным.

Где же здесь удовлетворение? Они просто несчастны, если не могут снять симптомы абстиненции. Разница между тем, чтобы смотреть порно и не смотреть -- это разница между счастьем и несчастьем. Пользователи, которые первым делом утром заходят на сайт ради порно, несчастны независимо от того, смотрят они его или нет.

Сокращение не только не работает, но и является худшей формой пытки. Это не работает, потому что изначально пользователь надеется, что, все меньше и меньше погружаясь в привычку, он уменьшит желание смотреть порно. Но это не привычка, это зависимость. Природа любой зависимости заключается в том, чтобы хотеть все больше и больше, а не меньше и меньше. Поэтому для того, чтобы сократить просмотр порно, пользователь должен проявлять силу воли и дисциплину до конца своей жизни. Таким образом, сокращение употребления означает силу воли и дисциплину навсегда. Остановиться гораздо легче и менее болезненно; есть буквально десятки тысяч случаев, когда сокращение употребления не помогло.

Проблема остановки не в дофаминовой зависимости, с которой легко справиться. Дело в ошибочном убеждении, что порно доставляет удовольствие. Это заблуждение изначально было вызвано промывкой мозгов, полученной ещё до начала употребления, а затем усиленной реальной зависимостью. Всё, что делает сокращение порно, -- это ещё больше укрепляет заблуждение, причём так, что порно полностью доминирует в их жизни и заставляет их неосознанно считать, что порно и их зависимость -- это самое ценное, что есть в жизни.

В тех немногих случаях, когда успех был достигнут благодаря относительно короткому периоду снижения использования порно, за которым последовал "жёсткий отказ". Эти пользователи прекратили употреблять порно, вопреки сокращению, а не благодаря ему. Это только продлевало агонию, неудачные попытки оставляли пользователей нервными и ещё более убежденными в том, что они подсели на порно на всю жизнь. Этого обычно достаточно, чтобы они, в поисках "удовольствия" и "поддержки", вернулись к своему онлайн-гарему, по крайней мере, ещё на какое-то время до следующей попытки бросить.

Тем не менее, сокращение помогает проиллюстрировать бесполезность порно, наглядно демонстрируя, что визиты в гарем не приносят удовольствия после периодов воздержания. Приходится снова какое-то время биться головой о кирпичную стену (страдать от абстинентного синдрома), чтобы сделать это снова приятным. Таким образом, ваш выбор таков:

1.  Урезáть использование порно всю жизнь и терпеть пытку самовнушением, которую вы всё равно не вытерпите.

2.  Всё чаще мучить себя на протяжении всей жизни, что бессмысленно.

3.  Быть добрым по отношению к себе и полностью прекратить использование порнографии.

Другой аспект, сокращения просмотра порнографии, заключается в том, что не существует такого понятия, как случайное или нерегулярное посещение гарема, это всегда предопределено. Интернет-порно -- это цепная реакция, которая будет продолжаться всю вашу оставшуюся жизнь, если вы не приложите усилий, чтобы её прервать.

**Помните: Сокращение просмотра порно неизбежно утащит вас вниз.**
