# Только одним глазком

"Только одним глазком" -- это миф, который вы должны выбросить из головы:

-   *Только одним глазком* заставляет нас начинать с самого начала.

-   *Всего лишь одним глазком*, чтобы поддержать себя в трудную минуту или по особому случаю, уничтожает большинство наших попыток остановиться.

-   Именно *только одним глазком* возвращает нас в ловушку, после того как нам удалось избавиться от зависимости. Иногда это "просто" попытка подтвердить себе, что порно больше не нужно, но это одно посещение гарема подтверждает обратное.

Последствия порно ужасны, они убеждают пользователя, что он никогда больше не попадется на крючок, но он уже на крючке. Пользователь чувствует, что то, что делает его таким несчастным и виноватым, не должно было полталкивать его заняться этим снова, но все же он раз за разом делает это.

Именно мысль об "одном последнем разочке" часто мешает пользователям остановиться -- после долгой поездки на конференцию, тяжелого рабочего дня, ссоры с детьми или инцидента, когда ваш партнер отказал вам в сексе. Вбейте себе в голову, что не существует такого понятия, как "просто один раз". Это цепная реакция, которая будет продолжаться всю жизнь, если её не прервать. Миф о единственном, особом разочке заставляет пользователей хандрить после прекращения использования порно. Выработайте в себе привычку никогда не раздумывать о "просто одном разе", это фантазия. Всякий раз, когда вы думаете о порно, представляйте себе грязную жизнь, проведенную за экраном ради привилегии уничтожить себя психически и физически -- жизнь в рабстве и безнадежности. Это не преступление, если ваша эрекция ненадежна, но это преступление, когда вы могли бы быть счастливее в долгосрочной перспективе, но вместо этого решили пожертвовать всем ради краткосрочного "удовольствия".

Это нормально, что мы не всегда можем придумать "чем бы заняться" вместо простоя и скуки; нереально никогда не испытывать пустоты. Мы можем спланировать большую часть своей жизни, но иногда неизвестность просто случается. Хорошие и плохие времена тоже случаются, независимо от порнографии. Но вбейте себе в голову, порно -- это не то. Ты останешься либо на всю жизнь в страданиях, либо вообще без страданий. Вы бы не стали принимать цианид только потому, что вам понравился вкус миндаля, так что перестаньте наказывать себя случайными "это просто один разочек" сессиями. Спросите пользователя, у которого проблемы в жизни: "*Если бы у тебя была возможность вернуться в то время, до того как ты подсел, выбрал бы ты стать зависимым?*" Ответ неизбежно будет один: "*Ты, наверное, издеваешься!*". И всё же у каждого пользователя есть этот выбор каждый день своей жизни, так почему же он не совершает его? Ответ на этот вопрос -- страх. Страх, что они не смогут остановиться или что без этого жизнь не будет прежней.

Перестаньте обманывать себя! Вы можете это сделать, любой может. Это до смешного просто, но для того, чтобы сделать это, необходимо четко уяснить для себя определённые фундаментальные принципы.

1.  Не от чего отказываться, наоборот вас ждут только чудесные положительные результаты.

2.  Никогда не раздумывайте о "просто одном единственном разе" или посмотреть "только одним глазком". Так не бывает! Так вы получаете только жизнь в грязи и рабстве.

3.  В вас нет ничего особенного, любой пользователь может легко остановиться.

Многие пользователи считают, что они являются заядлыми наркоманами или зависимыми личностями. Обычно это происходит в результате чтения чрезмерного количества шокирующей информации по неврологии. Такого не бывает, никто не рождается с потребностью мастурбировать на порноклипы, пока не подсел на них. Вас цепляет наркотик, а не природа вашего характера или личности. Природа вызывающих зависимость сверхнормальных стимулов заставляет вас поверить в это. Однако очень важно избавиться от этого убеждения, потому что если вы сами верите, в то, что вы зависимы, вы и будете зависимы даже тогда, когда, маленький монстр в вашем теле давно уже мертв. Очень важно устранить это заблуждение.
