# Случайные пользователи

Заядлые пользователи обычно завидуют случайным пользователям. Мы все встречали таких персонажей: "*О, я могу всю неделю обходиться без сеанса, меня это не беспокоит*". Мы хотели бы быть такими же. Возможно, в это трудно поверить, но ни один пользователь не получает удовольствия от того, что он пользователь. Никогда не забывайте:  


|   *Ни один пользователь никогда не решал стать пользователем, случайным или любым другим, **поэтому,** *

|       *Все пользователи чувствуют себя глупо, **поэтому,** *

|         *Все пользователи вынуждены лгать себе и другим в тщетной попытке оправдать свою глупость.*


Любители гольфа хвастаются тем, как часто они играют и хотят играть, так почему же пользователи хвастаются тем, как мало они мастурбируют? Если это истинный критерий, тогда, несомненно -- не мастурбировать вовсе, не так ли?

Если бы кто-то сказал вам: "*Я могу всю неделю обходиться без моркови, и меня это нисколько не беспокоит", вы бы подумали, что разговариваете с сумасшедшим. Если бы мне нравилась морковь, с чего бы я хотелось прожить без неё целую неделю? Если бы она мне не нравилась, зачем бы я делал такое заявление? Поэтому, когда пользователь делает комментарий о том, что он провёл неделю без сеанса, он пытается убедить себя -- и вас -- в том, что у него нет проблем. Но не было бы необходимости делать заявление, если бы у них не было проблемы. В переводе этот комментарий звучит так: "*Мне удалось выжить целую неделю без порно*". Он, как и каждый пользователь, надеется, что после этого он сможет выжить всю оставшуюся жизнь. Если ему удалось выжить только неделю, то можете ли вы представить, насколько ценной будет последующая сессия, когда вы чувствовали себя обделенным целую неделю?

Именно поэтому случайные потребители оказываются в большей зависимости, чем тяжелые. Иллюзия удовольствия не только сильнее, но у них меньше стимулов бросить, потому что они тратят на это меньше времени и поэтому меньше подвержены рискам для здоровья. Иногда они могут испытывать сексуальную дисфункцию, но не знают, чем она вызвана, и поэтому винят в этом другие факторы. Помните, что единственное удовольствие, которое получают потребители, -- это дофаминовый цикл, связанный с поиском и поиском, и облегчение абстинентного синдрома, как уже было объяснено. Это удовольствие является иллюзией -- представьте маленького порномонстра в виде почти незаметного зуда, о котором мы большую часть времени не подозреваем.

Если у вас есть постоянный зуд, естественная тенденция -- чесаться. Поскольку цепи вознаграждения становятся всё более невосприимчивыми к дофамину и опиоидам, естественной тенденцией становится доводить до крайностей, обострять, переборщать, поиск новизны, поиск шока и т.д. Существует четыре основных фактора, которые мешают пользователям увидеть цепочки зависимого возникновения.

**Время.**
Большинство не может себе этого позволить.

**Здоровье.**
Чтобы снять зуд, нам приходится потреблять весь доступный бесплатный материал, а потом ещё и ещё. Способность справляться с подобным объеданием у каждого человека в разное время и в разных жизненных ситуациях разная. Это действует как автоматическое ограничение.

**Дисциплина.**
Дисциплина навязывается обществом, работой, друзьями и родственниками пользователя, а может быть, и самим пользователем в результате естественного перетягивания
каната, происходящего в сознании каждого пользователя.

**Фантазия.**
Отсутствие фантазии снижает шок, новизну и другие ценности ролика на субъективной основе.

Легко думать о постоянных пользователях как о слабых, неспособных понять, почему другие могут ограничить их "потребление". Однако тяжелые пользователи должны помнить, что большинство случайных пользователей просто неспособны к постоянному просмотру, который требует очень яркого воображения и выносливости. Некоторые из этих пользователей, которым завидуют тяжелые пользователи, физически не способны на большее, или потому что им не позволяет работа, общество или собственная ненависть к тому, что они попадут на крючок.

Будет полезно дать несколько определений.

**Непользователь**

Тот, кто никогда не попадал в ловушку, но не должен этим гордиться. Они являются непользователями только по счастливой случайности или по милости свыше. Все пользователи были убеждены, что никогда не попадутся на крючок, а некоторые непользователи продолжают пробовать время от времени.

**Случайный пользователь**

Существует две основные классификации:

1.  Пользователь, попавший в ловушку, но не осознающий этого -- не завидуйте таким пользователям. Они просто пробуют нектар в устье кувшинки и, скорее всего, скоро станут тяжелыми потребителями. Помните, что как все алкоголики начинали с нечастого выпивания, так и все пользователи начинают как случайные.

2.  Пользователь, который ранее был постоянным пользователем и думает, что не сможет остановиться. Такие пользователи -- самые печальные из всех, и они делятся на различные категории, каждая из которых требует отдельного комментария.

**Пользователь "смотрю только раз в день"**

Если им действительно нравится их право на оргазм, зачем тогда использовать интернет-порно всего лишь раз в день? Если они могут использовать или не использовать его, зачем вообще беспокоиться? Помните, что "привычка" -- это, по сути, биться головой о стену, только лишь для того чтобы потом перестать и расслабиться. Тот, кто использует порно один раз в день, снимает абстинентный синдром менее чем на час каждый день. Хотя они не осознают, что весь остальной день они бьются головой об эту стену и делают это на протяжении большей части своей жизни. Они использует порно один раз в день, потому что не рискуют попасться или испортить свое неврологическое здоровье. Не сложно убедить тяжелого пользователя, что он не получает от этого удовольствия, но гораздо труднее убедить случайного пользователя. Любой, кто прошел через попытку сократить употребление, знает, что это самая страшная пытка, которая почти гарантированно сохранит зависимость на всю оставшуюся жизнь.

**Отвергнутый пользователь**

Они требуют права на оргазм каждый день, но сексуальный партнер не всегда рад выполнить их просьбу. Вначале они используют интернет-порно, чтобы заполнить эту пустоту, но после того, как они вступают на захватывающую "водную горку", они оказываются в ловушке цикла новизны, шока, сверхнормальных образов и т.д. На самом деле, они рады отказу партнера, поскольку это дает им хоть какое-то оправдание. Если интернет-порно дает вам так много, зачем вообще заводить партнера? Вместо этого избавьте их от себя. Отвергнутый пользователь даже не получает удовольствия от сеансов, ведь ему приходится держать в голове своего партнера. И иногда они обращаются к своему партнеру в реальной жизни, чтобы он дал им повод отправиться в темные долины Интернета.

**Пользователь на порнодиете**

Также известен как, "*Я могу остановиться, когда захочу. Я бросал уже тысячи раз!*"

Если они считают, что диета помогает им настроиться на то, чтобы подбирать партнеров, то почему они вообще сидят на диете -- раз в четыре дня? Никто не может предсказать будущее, и что, если случайная встреча произойдет через час после запланированного сеанса? Кроме того, если периодическая "чистка труб" полезна для снятия напряжения, почему бы не заниматься ею каждый день? Доказано, что мастурбация не нужна для поддержания здоровья половых органов, а интернет-порно -- вообще не нужно. Даже если это так, ни один "гуру" пикапа, прочитавший о неврологическом ущербе, никогда не посоветует смотреть суперстимулирующее порно. Правда в том, что пользователь порнодиеты все равно остается на крючке. Хотя они избавились от физической зависимости, они все еще остаются с главной проблемой - промыванием мозгов. Каждый раз они надеются, что остановятся навсегда, но вскоре снова попадают в ту же ловушку.

Большинство пользователей завидуют этим ограничителям и регуляторам и думают о том, как "повезло" диетчику, что он может контролировать свое употребление. Однако они упускают из виду тот факт, что диетчик не контролирует свое употребление, он контроллирует, когда он употребляет, но он хотел бы вообще этого не делать. Они проходят через трудности прекращения, затем начинают чувствовать себя обделенными и снова попадают в ловушку, жалея, что не сделали этого. Они получают худшее из двух миров. Если задуматься, то это верно и для жизни пользователей, когда им разрешают сеанс -- они воспринимают это как право или жалеют, что не сделали этого. Только когда лишают, порно становится ценным. Синдром "запретного плода" -- одна из ужасных дилемм для пользователей. Они никогда не смогут победить, потому что они хандрят из-за мифа, иллюзии. Есть только один способ победить -- перестать хандрить, прекратив использовать порно!

**Пользователь "Я смотрю только статичное/игровое/домашнее порно"**

Да, вначале все это пробуют, но разве не удивительно, что средняя шоковость и насыщенность роликов быстро возрастают, и не успеваем мы оглянуться, как чувствуем себя обделенными (срабатывает толерантность)? В статичном порно нет новизны, поэтому мы катимся вниз по водной горке к обиде и чувству вины. Худшее вещь, которую вы можете сделать, это использовать фотографии партнера (с одобрения, конечно) для мастурбации. Почему? Потому что в процессе вы перестраиваете свой мозг. Со стремления, поиска и разнообразия, вызванных приливом дофамина вы перестраиваете его на статичность и застои. Но система вознаграждения не зря настроена на предвкушение нового. С химической точки зрения, водные горки порнографии в мозгу -- это накопление DeltaFosB, поэтому вы будете испытывать трудности, когда будете с партнёром в реальном времени.

Еще одна ловушка в этой категории -- "любительское" и "домашнее" порно. Большинство из них -- подделки, и вы это знаете, к тому же вы не остановитесь на первом попавшемся, вы будете продолжать искать и искать. Помните, что мозг ищет не только оргазм, но и новизну охоты, которая придает водной горке острые ощущения. Дело не в содержании порно -- будь то любительское или профессиональное -- дело в приливе дофамина в мозг, вызывающем накопление толерантности и сытости. Порно разрушает нормальную работу мозга, мастурбация сбивает с толку мышечно-мозговую реакцию; оргазм наводняет мозг опиоидами и облегчает прохождение по этому сценарию в следующий раз.

**Пользователь "Я остановился, но время от времени заглядываю"**

В некотором смысле, подглядывающие пользователи -- наиболее жалкие из всех. Либо они идут по жизни, считая себя обделенными, либо, что чаще, случайное подглядывание превращается в два и больше, потом скольжение по скользкой дорожке вниз, и рано или поздно они возвращаются к тяжелой жизни. Они снова попадают в ту самую ловушку, в которую попали в первый раз.

Есть еще две категории случайных пользователей. Первая -- это те, кто мастурбирует на изображения или клипы последних секс-видео знаменитостей, попавших в новости, или на то, что они "унесли с собой" после "случайного" просмотра в школе или на работе. Эти люди на самом деле просто не являются пользователями, но они чувствуют, что им не хватает времени. Они хотят быть частью действия, и большинство из нас начинают именно так. В следующий раз обратите внимание, что через некоторое время знаменитость, о которой вы мечтаете, перестает вас привлекать. Чем более "недостижимой" является цель вашей фантазии, тем сильнее разочаровывает отказ от оргазма.

Вторая категория в последнее время привлекает все большее внимание, о ней лучше всего расскажет
случай, описанный в Интернете.

Одна опытная женщина много лет читала порнорассказы в Интернете и никогда не использовала больше или меньше, чем один раз за ночь. Кстати, она была очень волевой женщиной. Большинство пользователей удивились бы, почему она вообще захотела остановиться, и с удовольствием указали бы на отсутствие риска PIED или PE в её случае (это неправда). Она даже не использовала статичные изображения, а истории были намного мягче, чем любой материал, который они сами используют ежедневно.

Полагая, что случайные пользователи более счастливы и контролируют ситуацию, они совершают ошибку. Возможно, они и контролируют ситуацию, но счастливыми их точно не назовешь. В случае с этой женщиной она не была удовлетворена ни своим партнером, ни реальным сексом, и, реагируя на ежедневные стрессы и нагрузки, была очень раздражительной. Её близкие не могли понять, что её беспокоит. Даже если она убеждала себя, что не боится использования рационализации, она все равно оказывалась неспособной наслаждаться реальными отношениями, которые неизменно сопровождаются взлетами и падениями. Центр вознаграждения её мозга был не в состоянии довольствоваться нормальными стимулы для расслабления, присутствующие в жизни, в результате ежедневного дофаминового наводнения. Последующее снижение уровня чувствительности рецепторов в мозге привело к тому, что в большинстве случаев она становилась меланхоличной. Как и большинство других, она испытывала сильный страх перед темной стороной порнографии и обращением с женщинами -- до своего первого раза. В конце концов, она стала жертвой общественного промывания мозгов и попробовала свой первый сайт. В отличие от большинства тех, кто капитулирует и становится постоянным пользователем, увидев нецензурные ролики с насилием, она устояла.

Все, чем вы наслаждаетесь в порно, -- это прекращение тяги, которая началась до него, будь то почти неощутимая физическая тяга или душевная пытка от того, что вам не дают почесать зуд. Интернет-порно само по себе является ядом, вот почему вы страдаете от иллюзии наслаждения им только после периодов воздержания. Подобно голоду или жажде, чем дольше вы терпите, тем большее удовольствие получаете, когда наконец наступает облегчение. Ошибочно полагая, что порно -- это всего лишь привычка, они думают: *"Если я смогу сдерживать его до определенного уровня или только в особых случаях, мой мозг и тело примут новые правила игры. Тогда я смогу продолжать употребление на этом уровне или сократить его еще больше, если захочу"*.

Уясните для себя, что "привычки" не существует. Порно -- это наркотическая зависимость, естественной тенденцией которой является облегчение абстинентного синдрома, а не его преодоление. Чтобы удержаться на том уровне, на котором вы сейчас находитесь, вам потребуется огромная дисциплина и сила воли до конца жизни. По мере того как центр вознаграждения вашего мозга становится толерантным к дофамину и опиоидам, он хочет всё больше и больше, а не всё меньше и меньше.

По мере того, как порно начинает постепенно разрушать вашу нервную систему, смелость, уверенность в себе и контроль над импульсами, вы становитесь все более неспособны сопротивляться сокращению интервала между каждым сеансом. Вот почему на первых порах мы можем принимать или не принимать это. Если мы почувствуем признаки того, что с психикой или физикой что-то не в порядке, мы просто прекращаем занятия. Не завидуйте этой женщине -- когда смотришь только один раз в двадцать четыре часа, это кажется самой ценной вещью на земле, превращая порно в "запретный плод". В течение многих лет эта бедная женщина находилась в центре перетягивания каната.

Хотя она не могла прекратить употребление, она боялась перейти к просмотру потоковых клипов. В течение двадцати трех часов и десяти минут каждого из этих дней ей приходилось бороться с искушением и отсутствием чувств к своему парню. Ей потребовалась огромная сила воли, чтобы делать то, что она делала, в итоге она дошла до слез. Такие случаи редки, но посмотрите на это логически: есть ли в порно подлинная поддержка или удовольствие, или нет? Если есть, зачем кто-то хочет подождать час, день или даже неделю? Почему вы должны быть лишены поддержки или удовольствия в это время? Если нет подлинной поддержки или удовольствия, зачем вообще посещать свой онлайн-гарем?

Вот еще один случай, в котором человек один-раз-в-четыре-дня, описывает свою жизнь следующим образом:

> "*Мне сорок лет, я страдал от PIED (эректильная дисфункция, вызванная порнографией) с реальными женщинами и даже при использовании порно, что происходило чаще. У меня уже давно не было полной эрекции. До того, как я сел на порнодиету раз-в-четыре-дня, я крепко спал всю ночь после сеанса. Теперь я просыпаюсь каждый час ночи и думаю только об этом. Даже когда я сплю, мне снятся мои любимые клипы. В дни после запланированного сеанса я чувствую себя очень подавленным, самоограничение забирает всю мою энергию. Моя супруга оставляет меня в одиночестве, потому что я очень раздражителен, и если же у неё нет возможности уйти, то она не хочет видеть меня в доме. Я выхожу на пробежку, но мой разум одержим этим..*
>
> *В назначенный день я начинаю планировать еще ночью, очень раздражаясь, если что-то происходит не по моим планам. Я ухожу от разговоров и уступаю (только чтобы потом пожалеть) на работе и дома. Я не спорщик, но я не хочу, чтобы тема или разговор удерживали меня. Я помню случаи, когда я устраивал глупые ссоры со своей супругой. Я жду десяти часов ночи, и когда они наступают, у меня неконтролируемо дрожат руки. Я не сразу приступаю к делу -- ведь там есть новые видео, которые были добавлены -- и начинаю "класть в корзину", открывая множество вкладок. Мой разум говорит мне, что, поскольку я морил себя голодом в течение четырех дней, я заслуживаю "особенного" клипа, который должен стоить потраченного на поиск времени. В конце концов я останавливаюсь на одном или двух, но хочу, чтобы это длилось долго, чтобы я мог "пережить" следующие четыре дня, поэтому мне требуется больше времени, чтобы закончить дело.*"  

В дополнение к другим своим проблемам этот бедняга даже не подозревает, что угощает себя ядом. Сначала он страдает от "синдрома запретного плода", а затем заставляет свой мозг вымывать дофамин. Сравнительно недавно его дофаминовые рецепторы были не так сильно разрушены, но он смазывает водные горки порнографии, стремится к новизне, и ищет острых ощущений, разнообразия, шока и тревоги, чтобы пережить следующие четыре дня. Вы, вероятно, представляете себе этого человека как жалкого имбецила, но это не так. Будучи бывшим спортсменом и сержантом морской пехоты, он не собирался становиться порнозависимым. Однако после возвращения с войны он прошел обучение по программе реабилитации ветеранов в качестве IT-техника.

Когда он поступил на гражданскую службу, он был хорошо оплачиваемым ИТ-специалистом в банке, и ему выдали ноутбук, чтобы он мог брать его домой. Это был год, когда известные светские львицы "сливали" свои порнографические видео в Интернет, и об этом много говорили. Затем он подсел на порнографию, и всю оставшуюся жизнь платил за нее большую цену, разрушая себя физически и психически. Если бы он был животным, общество давно избавило бы его от страданий, но мы всё ещё позволяем психически и физически здоровым подросткам попадать в сети порно. Вы можете подумать, что этот случай и заметки преувеличены, но этот случай, хотя и экстремальный, далеко не уникален. Существуют десятки тысяч подобных историй. Можете ли вы быть уверены, что никто из его друзей и знакомых не завидовал ему за то, что он использует только раз в четыре дня? Если вы думаете, что с вами такого не может случиться, **перестаньте обманывать себя**.

**ЭТО УЖЕ ПРОИСХОДИТ.**

Как и другие наркоманы, потребители порнографии -- отъявленные лжецы, даже по отношению к самим себе. Им приходится быть такими. Большинство случайных пользователей предаются использованию порно гораздо чаще и по гораздо большему количеству поводов, чем они признаются. Во многих разговорах с так называемыми "пользователями два раза в неделю" они признаются, что делали это более трех-четырех раз за неделю. Почитайте на reddit, NoFap и rebooting-forum истории случайных пользователей, и вы поймете, что они либо считают дни, либо ждут провала. Вам не нужно завидовать случайным пользователям, и вам не нужно употреблять, жизнь без этого бесконечно слаще. Рассмотрим эту запись:

"*Все началось с простой задачи -- не трогать свои причиндалы в течение дня, и не помышлять об этом. Я больше не думаю о мастурбации, она не приходит мне в голову. Это возможно, я обещаю вам. Богатства, которые ждут тех, кто способен -- они невероятны.*"

Подростков обычно труднее вылечить, но не потому, что им труднее остановиться, а потому, что они не верят, что попали в ловушку, или находятся на начальной стадии ловушки, обычно страдая от заблуждения, что они автоматически остановятся до наступления неприятных последствий.

Родители, дети которых ненавидят порно, не должны испытывать ложное чувство безопасности. Всем детям не нравится темная сторона порно, прежде чем они попадают на крючок. Когда-то она не нравилась и вам тоже. Не ведитесь на пугающие кампании, ловушка та же, что и всегда. Дети знают, что интернет-порно -- это сверхнормальный стимул, но они также знают, что одним "посещением" или "подглядыванием" дело не ограничится. На определенном этапе они могут попасть под влияние партнера, одноклассника или коллеги по работе.

Пожалуйста, не успокаивайтесь в этом вопросе. Неспособность общества предотвратить пристрастие подростков к интернет-порно и другим наркотикам -- пожалуй, самая тревожная часть всей этой истории. Мозг подростка гораздо более пластичен, и необходимо обучать и защищать их. Если вы не знаете, с чего начать, хорошим источником информации является книга YourBrainOnPorn, которая поможет вам ознакомиться с нейробиологией. Даже если вы подозреваете, что ваш подросток уже находится на крючке, книга дает основополагающее понимание того, как помочь человеку спастись. В остальном, рекомендую книгу EasyPeasy!
