# Пользователь YouTube / Twitch / Instagram

Этого пользователя следует отнести к группе случайных пользователей, но его проявления настолько коварны, что заслуживают отдельной главы. Это приводит к нарушению самоконтроля, что почти привело к расколбасу одного пользователя форума NoFap:

> *"Прошло три недели после одной из моих неудачных попыток завязать. Попытка была вызвана беспокойством моей жены по поводу моих ненадежных стояков и отсутствия интереса. Я сказал ей, что дело не в ней, а в давлении на работе. Она сказала: "Я знаю, что ты уже справлялся с давлением на работе, но как бы ты чувствовал себя на моем месте, если бы тебе пришлось наблюдать, как кто-то, кого ты любишь, систематически разрушает себя?". Этот аргумент очень сильно меня тронул, поэтому я попытался остановиться. Она знает, что я не изменяю, но это в некотором смысле даже хуже. Попытка закончилась через три недели, кульминацией стал горячий спор со старым другом. Только спустя годы я понял, что мой коварный ум намеренно спровоцировал этот спор. В то время я чувствовал себя оправданно расстроенным, но не думаю, что это было совпадение, поскольку я никогда не спорил с этим другом раньше и не спорил с тех пор. Это явно была работа маленького монстра.*
>
> *Несмотря ни на что, у меня было оправдание. Я отчаянно нуждался в разрядке, и не имело значения, каким образом. Моя жена была не в настроении, поэтому у меня было чувство, что я имею "право", и я убедил себя, что все будет хорошо, если я "ограничу" себя, избегая порносайтов и оставаясь по ту сторону "красной черты", просматривая только видео на YouTube. Но моя жена в конце концов "пришла в себя", когда наступила ночь, и захотела заняться любовью, но я был уставшим и без своей "мужской силы", поэтому сказал, что у меня головная боль. Мне было невыносимо думать о том, какое разочарование это вызвало у моей жены. Затем я постепенно вернулся к прежним занятиям, YouTube стал моим новым гаремом. Помню, что в то время я был весьма доволен, думая, что это, по крайней мере, сокращает мое потребление. В конце концов, жена обвинила меня в том, что я продолжаю игнорировать ее в постели. Я не понимал этого, но она вспомнила случаи, когда я провоцировал ссоры и уходил из дома. В других случаях я тратил два часа на покупку какой-нибудь незначительной вещи и симулировал растяжение связок. Я придумывал слабые оправдания, чтобы отмазаться от ухаживаний за ней, так как когда у меня есть надежный онлайн-гарем, это ещё сложнее."*

Хуже всего то, что пользователь YouTube поддерживает в своем сознании заблуждение о том, что его обделяют. Одновременно это приводит к серьезным потерям самоуважения; честный в иных отношениях человек может начать обманывать любимого человека. Возможно, это уже произошло или всё ещё происходит с вами в той или иной форме.

Проблемы, возникающие с просмотром таких сайтов, как Twitch, Instagram, TikTok, Twitter (и другие социальные сети), в первую очередь обусловлены дофамином. Движимые стремлением к новизне, пользователи обманывают себя, заставляя поверить, что находятся на безопасном сайте. Помните -- кайф заключается в охоте и поиске, а не в убийстве, и маленькому монстру все равно, откуда он получает свою дозу. Для пользователя "мягкий" контент, получаемый в различных онлайн-каналах, дает ему мимолетное облегчение от абстинентного синдрома, заставляя его оставаться на крючке и ждать следующего сеанса.

Модель на картинке/видео действительно красива, и если бы она была на у вас здесь прямо сейчас, она, несомненно, доставила бы вам удовольствие, но эта картинка не может... Она просто не настоящая. Ваш мозг обманут, как бык, налетевший на красный плащ, и после этого не понимающий, почему так получилось. Можно подумать, что тогда можно просто смотреть на эти образы, не мастурбируя. Но помните, что ваш мозг подсел на безграничную новизну, и маленькому монстру все равно, откуда он получает удовольствие. Это одна и та же ловушка.

Возможно, вы смотрели сериал "Коломбо". Тема каждого эпизода похожа. Злодей, обычно богатый и уважаемый бизнесмен, совершил, по его убеждению, идеальное убийство, и его самоуверенность в том, что его преступление останется незамеченным, получает дополнительную уверенность, когда узнает, что делом занимается довольно потрепанный и невыразительно выглядящий детектив Коломбо.

У Коломбо есть обескураживающая практика закрывать дверь после окончания допроса, заверив подозреваемого, что он чист. Но не успевает удовлетворенный взгляд исчезнуть с лица убийцы, как Коломбо появляется снова, говоря: "*Только один маленький момент, сэр, который, я уверен, вы сможете объяснить...*". Подозреваемый запинается, и с этого момента он понимает, что Коломбо в конце концов выведет его на чистую воду. Независимо от того, каким чудовищным было преступление, с этого момента большинство людей начинало сочувствовать убийце.

Эти цикличные запои похожи: напряжение от того, что пользователь не разрешает себе пересечь красную черту, запрещает себе получить порно-лечение, которое он "по праву заслужили", затем следует удивление, от отсутствия ожидаемого удовольствие после завершения дела. Страх переступить черту, потерять контроль и вернуться туда, откуда начал, боязнь, что ваш партнер захочет хорошего секса. "Безопасные" видео на YouTube больше не удовлетворяют вас из-за десенсибилизации, отсутствия новизны и уверенности в том, что рано или поздно вы посетите свой любимый онлайн-гарем. Окончательное унижение и стыд наступают тогда, когда эта возможность становится фактом, после чего следует немедленное возвращение к просмотру порно-роликов.

**О, И В ЧЁМ ЖЕ РАДОСТЬ БЫТЬ ПМОером?!**
