# Социальная привычка?

Здоровье ума и тела -- вот основные причины, по которым мы *должны* хотеть прекратить -- но так было всегда. Нам не нужны научные исследования и знания в области неврологии, чтобы сказать, что порно вызывает привыкание и  потенциально разрушает нашу жизнь. Наши тела -- самые сложные объекты на планете, и любой пользователь с первого сеанса знает, что стимул может превысить норму и стать ядовитым.

Единственная причина, по которой мы когда-либо увлекаемся порнографией, -- это совпадение цикла ПМО с нашим эволюционным программированием. Порно в Интернете очень доступно, бесплатно и транслируется двадцать четыре часа в сутки. Когда-то порно считалось безобидным, но это было тогда, когда изображения были статичными, а для просмотра видео нужно было идти в местный магазин за кассетой VHS.

Сегодня принято считать -- даже самими пользователями -- что порно является сверхнормативным стимулом и формирует зависимость. В былые времена сильный мужчина не признавался, что он мастурбирует: "дрочить" было уничижительным термином. В любом пабе, клубе или баре большинство мужчин с гордостью говорили, что хотят взять женщину домой и заняться настоящим сексом. Сегодня положение полностью изменилось в отношении интернет-зависимого порномана. Современный мужчина начинает чувствовать, что женщина ему не нужна. Объединившись в сети, он обсуждает опыт, разрабатывает стратегии и изучает варианты. Современный сильный мужчина не хочет зависеть от наркотиков. Благодаря социальной революции все пользователи всерьез задумываются о том, чтобы отказаться от порнографии и мастурбации в Интернете. Сегодняшние пользователи считают порно бесполезным и вредным занятием.

Самая значительная тенденция, замеченная на форумах, -- это растущий акцент на антисоциальных аспектах порнографии. Времена, когда мужчина хвастался тем, что у него каждый день как бы есть секс и оргазм, постепенно сменяются осознанием рабства перед порномонстром.

Единственная причина, по которой люди продолжают смотреть порно, даже после удовлетворения первичного любопытства, заключается в том, что они не смогли остановиться или слишком напуганы, чтобы попробовать остановиться. Существует широкий спектр интереса к этой теме, некоторые воздерживаются от порно, мастурбации и оргазма -- с партнерами или без них. Практики, разделяющие тантрическую и детородную части секса, такие как удержание спермы и Karezza, обсуждаются и принимаются массово. Многие вышеупомянутые неудачи на самом деле являются движением вперёд и обучением на своих провалах, которые в некоторой степени приносит пользу. Начав путь без ПМО, вы найдете то, что лучше всего подходит для вашей жизни; рекомендуется разработать свой собственный план оргазмов после понимания и практики концепции разделения секса на тантрический и детородный. Каким бы ни был ваш путь, вы увидите пользу в ограничении количества раз, когда вы оргазмируя омываете свой мозг химическими веществами, и никогда больше не будете рассматривать порно, секс и оргазм как удовольствие или костыль для вашего эмоционального "я".

Различные популярные интернет-сообщества, основанные непользователями, посвящены отказу не только от порно, но и от мастурбации. Эти сайты в конечном счете полезны для тех, кто бросает, но большинство заметок указывает им на необходимость попробовать силу воли. Следствием одержимости стриками (количеством подряд идущих дней) воздержания и другими мерами является жалость к себе и отсутствие энтузиазма и восторга. Большая часть промывания мозгов остается свежей и нетронутой. В конце концов, кто-то срывается, и происходит эффект домино: другие пользователи узнают, что они не единственные. Однако их усилия не пропали даром, они продвигаются вперед, хотя и с большим количеством самоистязаний, поскольку они закрывают свои браузеры, но не желание и потребности. EasyPeasy работает в обратном направлении, сначала отключая иллюзию потребности и желания, а затем браузер. Каждый день всё больше и больше пользователей покидают тонущий корабль, а те, кто остался на нем, начинают бояться, что они будут последними.

**ДАВАЙ, ЭТО БУДЕШЬ НЕ ТЫ!**
