# Выбор времени

Помимо очевидного факта, что порно не приносит вам пользы и что сейчас самое время остановиться, важно правильно выбрать для этого время. Общество относится к интернет-порно легкомысленно, считая его слегка неприятной привычкой, которая не вредит вашему здоровью. Это неправда. Это наркомания, болезнь и разрушитель отношений. Самое страшное, что происходит в жизни большинства пользователей, -- это подсаживание на эту ужасную зависимость. Если они остаются на крючке, происходят ужасные вещи. Поэтому важно выбрать время и дать себе право на правильное излечение.

В первую очередь, определите время или случаи, когда порнография кажется вам важной. Если вы деловой человек, использующий порно для иллюзии снятия стресса, выберите относительно спокойный период или отпуск. Если вы используете порно в основном во время скучных или расслабляющих периодов, то сделайте наоборот. Независимо от этого, отнеситесь к попытке серьезно и сделайте её самой важной вещью в вашей жизни.

Загляните вперед на три недели и постарайтесь предугадать любое событие, которое может привести к неудаче. Такие события, как поездка на конференцию, отъезд партнера из города и т.д., не должны отпугивать вас, если вы заранее предвидите их и не почувствуете, будто вас чего-то лишают. Не пытайтесь в ближайшее время сокращать использование порно, так как это лишь создаст иллюзию того, что сокращение порно доставляет удовольствие. На самом деле, может помочь, если вы заставите себя смотреть и проводить как можно больше порносеансов. Во время последней сессии и последнего раза помните о разочаровании из-за насыщения, несбывшихся ожиданий, любой телесной боли, эффекте отмены, раздражительности и меланхолии. Думайте о том, как прекрасно будет, когда вы позволите себе перестать это делать.

**ЧТО БЫ ВЫ НИ ДЕЛАЛИ, НЕ ПОПАДАЙТЕ В ЛОВУШКУ, КОГДА ВЫ ГОВОРИТЕ: "НЕ СЕЙЧАС, ПОТОМ" И ВЫБРОСЬТЕ ЭТО ИЗ ГОЛОВЫ. СОСТАВЬТЕ СВОЙ ПЛАН СЕЙЧАС И С НЕТЕРПЕНИЕМ ОЖИДАЙТЕ ЕГО ИСПОЛНЕНИЯ.**

Помните, что *вы ни от чего не отказываетесь*. Напротив, вы собираетесь получить чудесные положительные результаты.

В течение многих лет медики считали порно безвредным, не зная разницы между безобидным статичным порно прошлых лет и новейшим потоковым бесконечным легкодоступным виртуальным порно. Проблема заключается в том, что хотя каждый пользователь потребляет интернет-порно исключительно для того, чтобы снять вызванную им дофаминовую тягу, его цепляет не зависимость от химического вещества, а самопромывание мозгов, вызванное зависимостью. Умный человек может попасться на уловку, но только глупец продолжит верить в иллюзию, когда поймет, в чём заключается обман. К счастью, большинство пользователей не являются дураками, они только думают или прикидываются, что являются ими. У каждого отдельного пользователя своя собственная система промывки мозгов. Именно поэтому существует такое разнообразие типов наркоманов, что ещё больше увеличивает уровень сложности этой загадки.

Хотя польза от оригинальной книги заключалась в отказе от никотина (одного из самых быстрых и вызывающих привыкание наркотиков, известных человеку), было приятно удивительно осознать, что философия, изложенная в оригинальной книге, по-прежнему актуальна и в её адаптации. Проблема, которую мы с Карром решаем, заключается в том, как донести накопленные знания и понимание до каждого конкретного пользователя. Я точно знаю, что каждый пользователь может не только легко остановиться, но и получить удовольствие от процесса, однако если пользователь не поймёт и не осознает это, всё будет не только бессмыслено, но и чрезвычайно разочаровывающе. В своей оригинальной книге Аллен Карр объясняет свой противоречивый совет:

>"Многие люди говорили мне: 'Вы говорите: "Продолжайте курить, пока не дочитаете книгу". Это, как правило, заставляет курильщика затягивать чтение книги или просто не дочитывать ее" и всё. Поэтому вам следует изменить инструкцию". Это звучит логично, но я знаю, что если бы инструкция гласила: "Немедленно прекратите", некоторые курильщики даже не стали бы читать книгу. В самом начале меня консультировал один курильщик. Он сказал: "Мне очень неприятно обращаться к вам за помощью, я знаю, что у меня сильная воля. Во всех других сферах моей жизни я контролирую себя. Почему все остальные курильщики бросают курить, используя свою силу воли, а мне приходится обращаться к вам?" Он продолжал: "Но я думаю, что смог бы сделать это сам, если бы мне можно было курить, пока я бросаю.'\"*

Согласно общественному мнению, бросить курить невероятно трудно, так что же нужно курильщику, когда что-то трудно? Наш маленький друг, наш костыль. Бросить курить -- это двойной удар: мало того, что нужно выполнить сложную задачу, что достаточно трудно, так ещё и костыль, на который мы обычно полагаемся в таких случаях, недоступен. Возможно, настоящая прелесть этого метода заключается в том, что вам не нужно "отказываться" во время прохождения процесса. Вместо этого мы изначально избавляемся от всех страхов и сомнений, так что по завершении последнего сеанса вы уже наслаждаетесь свободой.

Поэтому в этой книге будут даны те же самые советы. Сколько бы ни говорилось о том, что это будет легко и приятно, найдется подавляющее большинство тех, кто не сможет принять их из-за собственного промывания мозгов о том, как трудно бросить порно.

Тайминг -- единственная глава, которая заставляет меня серьезно усомниться в первоначальном совете Аллена. Прежде всего, если триггеры включают в себя острый стресс, то выбирайте выходной или отпуск, чтобы сделать попытку, и наоборот, если вы используете порно как средство борьбы со скукой. Есть и другой способ: выбирать то время, которое вы считаете наиболее сложным временем. Будь то стресс, социальные обязательства, концентрация или скука, но как только вы сами докажете, что справляетесь и наслаждаетесь жизнью в самых тяжелых ситуациях, любая другая жизнь автоматически станет приятной. Но если бы вам советовался этот второй трудный метод, стали бы вы пытаться?

Вот вам аналогия. Мы с сестрой собираемся плавать вместе. Мы приходим в бассейн в одно и то же время, но редко плаваем вместе. Причина в том, что она заходит в воду сантиметр за сантиметром, а поплывёт она только через полчаса. Это медленная пытка. Я заранее знаю, что если я хочу плавать, то на каком-то этапе, какой бы холодной ни была вода, мне придется отважиться погрузиться с головой. Поэтому я научился делать это несложным (но трудным способом): сразу нырять в воду. Но теперь представьте, что было бы, если я стал бы настаивать на том, что если она не нырнет сразу, то не будет плавать вовсе. Если бы я делал так, она бы вообще не стала пытаться зайти в воду. Вы поняли?

Судя по отзывам, многие пользователи использовали первоначальный совет (медленного вхождения в воду) по выбору времени, чтобы отсрочить то, что, по их мнению, станет "злым днем". Моя следующая мысль была использовать технику, аналогичную главе "Преимущества порно", я напишу здесь что-то вроде: "*Выбор времени очень важен, и в следующей главе вам посоветуют лучшее время для совершения попытки*", а на следующей странице просто огромная надпись *"СЕЙЧАС!"*. На самом деле это лучший совет, но последуете ли вы ему? Возможно, самый тонкий аспект этой ловушки заключается в том, что когда в нашей жизни есть настоящий стресс, это неподходящее время, чтобы остановиться, но в моменты отсутствия стресса у нас нет желания прекратить свои мучения, ведь всё более-менее хорошо. Поэтому задайте себе следующие вопросы:

1.  Когда вы впервые подсели на порно, действительно ли вы определились, что будете зависеть от него всю оставшуюся жизнь, не имея возможности остановиться? ***Конечно нет!***

2.  Собираетесь ли вы прожить всю оставшуюся жизнь, не имея возможности остановиться? ***Конечно нет!***

Так когда вы остановитесь? Завтра? В следующем году? Через год? Разве не об этом вы спрашивали себя с тех пор, как впервые поняли, что подсели? Вы надеетесь, что однажды утром вы проснетесь и просто не захотите больше смотреть порно? Перестаньте обманывать себя, при любой зависимости вы становитесь всё более и более зависимым, а не менее. Или вы будете ждать, пока не почувствуете, что встать с постели вам труднее, чем помастурбировать? Это было бы уже немного бессмысленно.

Настоящая ловушка -- это убеждение, что сейчас не то самое время, что завтра всегда будет легче. Мы считаем, что живем в стрессовой ситуации, но на самом деле это не так. Большинство реальных стрессов отстутствуют в нашей жизни. Выходя из дома, вы не живете в страхе, что на вас нападут дикие животные, большинство людей не задумываются о том, где и как они будут питаться в следующий раз, будет ли у них сегодня крыша над головой. Подумайте о жизни дикого животного: каждый раз, когда кролик выходит из своей норы, он сталкивается со Вьетнамом на протяжении всей своей жизни. Но кролик справляется с этим, у него есть адреналин и другие гормоны, как и у нас. Правда в том, что самые стрессовые периоды в жизни любого существа -- это раннее детство и юность. Но за три миллиарда лет естественного отбора мы научились справляться со стрессом, и многие люди, у которых было тяжелое детство, живут нормальной жизнью.

Это избитое выражение: "Если у вас нет здоровья, у вас нет ничего", но это абсолютная правда. Когда вы чувствуете себя физически и психически сильным, вы можете наслаждаться взлётами и справляться с падениями. Многие путают ответственность со стрессом; ответственность становится стрессом только тогда, когда мы не чувствуем себя достаточно сильными, чтобы справиться с ней. Большинство людей разрушает не стресс, работа или старость, а лживые костыли, иллюзия, что они опираются на что-то реальное.

Посмотрите на это с другой стороны -- вы уже решили, что не собираетесь оставаться в этой ловушке до конца жизни. Поэтому в какой-то момент -- независимо от того, легко это или трудно -- вам придется пройти через процесс освобождения. Порно -- это не привычка или удовольствие, это наркомания и болезнь. Мы установили, что завтра не станет легче, будет становиться всё хуже и хуже. Самое время избавиться от него **сейчас** -- или настолько скоро, насколько это возможно. Только подумайте, как быстро пролетает неделя вашей жизни. Это всё, что нужно. Подумайте о том, как приятно будет наслаждаться остатком жизни без постоянно увеличивающихся теней, нависающих над вами. Если вы будете следовать всем инструкциям, вам даже не придется ждать пять дней или три недели. Вам не только будет просто бросить порно, но и вы **сделаете это с радостью**!
