# Не упускаю ли я всё веселье?

**Нет!** Как только маленький порномонстр будет мертв, когда ваше тело перестанет жаждать дофамина, а водные слайды порнографии в вашем мозгу начнут быстро исчезать из-за отсутствия "смазывания" путей, все остатки промывания мозгов исчезнут. Вы не только окажетесь физически и психически лучше подготовленными к стрессам и напряжениям жизни, но и будете в полной мере наслаждаться хорошими временами.

Есть только одна опасность -- влияние тех, кто все еще использует секс как костыль и удовольствие. *"Чужая трава всегда зеленее"* -- обычное явление во многих сферах нашей жизни и легко объяснимое. Почему же в случае с порнографией -- недостатки которой столь огромны по сравнению с иллюзорными "преимуществами" -- бывшие пользователи склонны завидовать тем, кому секс и порнография нужны как костыль?

Вполне понятно, что мы попали в ловушку, когда нам с детства промывали мозги. Почему же тогда, осознав, что порно -- это игра для дураков, и сумев избавиться от этой привычки, мы снова попадаем в ту же ловушку? Это влияние общественной промывки мозгов, в результате которой порно смешивается с сексом, который представляется как норма. У бывшего пользователя возникает острая ломка! Неуверенное чувство пустоты от того, что они одиноки (что не является преступлением), вызывает чувство тревоги и заставляет их вновь катиться по водной горке. Это действительно любопытная аномалия, особенно если принять во внимание следующее наблюдение: не только все непользователи в мире счастливы, но и все пользователи в мире, даже с их искаженным, зависимым, промытым мозгом, страдающим от иллюзии наслаждения или расслабления, хотели бы, чтобы они никогда не попались на крючок с самого начала. Так почему же некоторые бывшие пользователи завидуют?

1.  'Только один разочек'. Помните, его не бывает. Перестаньте видеть единичный случай и посмотрите на это шире, с точки зрения пользователя порно. Возможно, вы завидуете им, но они не одобряют своего образа жизни и завидуют вам. Если бы вы только могли как-то со стороны понаблюдать за другими пользователями, это могло бы стать самым мощным толчком, который помог бы вам выбраться из этого состояния. Представите, как быстро они открывают множество вкладок и окон браузера? Быстро переходят к важным разделам, им быстро надоедают клипы, они перебирают жанры, вызывающие новизну, шок, тревогу и т.д. Особенно обратите внимание на то, что их действия выглядят автоматическими и компульсивными. Помните -- они не получают от этого удовольствия, но гораздо важнее, что они не могут получать удовольствие без этого. На следующее утро, проснувшись с ослабленной волей, утраченной энергией и обескровленными глазами, они будут вынуждены продолжать душить себя при первом же появлении стресса и напряжения. Им грозит целая жизнь грязи, ужасного психического здоровья и подорванной уверенности в себе -- целая жизнь разрушения самих себя с черными тенями на задворках сознания. Для достижения какой цели? Иллюзии, что вы получаете, что "заслужили", и это чёртово "удовольствие"? Сколько ещё "наслаждения" вы сможете вытерпеть?

2.  Вторая причина, по которой некоторые бывшие потребители испытывают страдания, заключается в том, что пользователь порнографии делает что-то -- например, доставляет себе удовольствие -- а непользователь нет, поэтому они чувствуют себя обделенными. Уясните для себя, что лишен не тот, кто не смотрит порнографию, а бедный зависимый, который лишает себя:

    -   Здоровья

    -   Энергии

    -   Уверенности

    -   Душевного спокойствия

    -   Мужества

    -   Умиротворённости

    -   Свободы

    -   Самоуважения

    Перестаньте завидовать пользователям порнографии и начните видеть в них жалких, ничтожных существ, которыми они на самом деле являются. Я знаю, потому когда-то я был одним из наиболее жалких. Но именно вы читаете эту книгу, а не те, кто не может признаться себе в этом и продолжает обманывать себя.

Вы не завидуете героиновому наркоману, и, как любая другая наркомания, ваша ничем не лучше. С каждым годом она будет ухудшаться в геометрической прогрессии -- и если вы уже сегодня не в восторге от порно и не получаете настоящего удовольствия, то завтра всё будет ещё хуже. Не завидуйте пользователям, пожалейте их. Поверьте мне: ***Они нуждаются в вашей жалости!***
