# Могу ли я решить проблему по частям?

Этот миф в основном распространяют пользователи, пытающиеся применять метод силы воли, которые занимаются умственной гимнастикой и начинают заниматься чем-то, что напоминает происходящее в повести "Странная история доктора Джекила и мистера Хайда": "*Порно -- это для моего альтер-эго, а романтика в реальной жизни -- для моей здоровой личности, которая хочет отношений*". Ничто не может быть дальше от истины: водные горки порнографии, DeltaFosB и неврологические изменения захлестнут романтику реальной жизни, сделав её менее желанной. И Мистер Хайд определенно откажется исполнять инструкции доктора Джекила.

Если вы используете интернет-порно, вы готовите себя к роли вуайериста. (Вуайерист -- это человек, который получает удовольствие от того, что смотрит на других людей во время секса. Он не участвует в сексе, а только смотрит.) Или требуете возможности перейти к чему-то более возбуждающему при малейшем снижении уровня дофамина. Или постоянный поиск нужной сцены для достижения максимального эффекта. Кроме того, вы можете мастурбировать в сгорбленной позе или смотреть в смартфон в постели по ночам, в итоге вы будете желать этих сигналов и обстоятельств больше, чем стимулов в реальной жизни. Секс противоречит почти всем аспектам онлайн-гарема, и у него нет шансов в сравнении. Воспоминания, созданные в молодости, сильны и долговечны, поэтому разрушение этих порнографических водных горок и перепрограммирование или создание новых занимает больше времени. Однако это не значит, что это сложно.

Каждый раз, когда вы катаетесь на "порнографической водной горке", вы смазываете её, сохраняя нервы свежими и готовыми к выстрелу. Когда вы паркуетесь рядом с фастфудом, и запах жаровни или фритюрницы влетает в ваши ноздри, продажа уже совершена, вы точно купите этот фастфуд. Точно так же водные горки порнографии в вашем мозгу готовы к тому, чтобы вы втянулись в них, и открыты двадцать четыре часа в сутки. Каждый сигнал или триггер зажигает вашу цепь вознаграждения обещанием секса -- только вот это не секс. Тем не менее, нервные клетки связывают эти ассоциации с сексуальным возбуждением, проращивая новые отростки для укрепления связей. Чем больше вы используете порно, тем сильнее становятся нервные связи. В итоге вы, возможно, станете вуайеристом, нуждающимся в просмотре постоянно обновляющегося и нового материала, нуждающимся в порно, чтобы уснуть, или в поиске идеальной концовки, чтобы получить удовольствие.

Как и к любому другому веществу или поведенческому наркотику, организм вырабатывает толерантность, и наркотик перестает полностью снимать абстинентный синдром. Как только порнопользователь завершает сеанс, он почти сразу хочет ещё один, и быстро, постоянный голод остается неудовлетворенным. Естественная тенденция -- это эскалация, чтобы получить новый дофаминовый всплеск. Однако большинство пользователей не могут этого сделать по одной или нескольким из следующих причин.

**Деньги:** Они не могут позволить себе подписку на платные порносайты.

**Здоровье:** Организм не может выдержать слишком много, либо всплесков дофамина, либо оргазмов. Кроме того, оргазм в действительности запускает химические реакции, чтобы сократить прилив дофамина и снижает тестостерон. Так и должно быть, так устроено тело.

Как только маленький монстр покидает ваше тело, ужасное чувство неуверенности заканчивается. Ваша уверенность возвращается, вместе с чудесным чувством самоуважения, обретением уверенности в том, что вы можете взять свою жизнь под контроль и использовать эту уверенность как трамплин для решения других проблем. Это одно из многих преимуществ избавления от любой зависимости.

Заблуждение компартментализации (ещё в психологии иногда называется "раздельное мышление") -- это одна из многих уловок, которыми маленький монстр играет с вашим сознанием. Эти уловки затрудняют процесс остановки потребления, и из-за невозможности удовлетворить постоянный голод, но чтобы как-то заполнить пустоту, многие потребители обращаются к курению, сильному алкоголю или даже к более сильным наркотикам.

Люди -- оценочные животные, как по отношению к себе, так и по отношению к окружающим. Просмотр порно с партнером не приносит удовлетворения, так как вы оба оцениваете игру друг друга в сравнении с происходящим в ролике. Но хотите ли вы видеть Брэда Питта в своей спальне, даже если он очень хорош и на всех постерах? Ни один человек не может сравниться с гаремом, где каждый "опыт" разыгран, по прописанному сценарию, срежиссирован профессионалами и немедленно доступен двадцать четыре часа в сутки.
