# Избегайте ложных стимулов

Многие пользователи метода силы воли пытаются повысить свою мотивацию путем создания ложных стимулов. Таких примеров много, типичный из них -- награждать себя подарками после того, как не смотрел порно в течение месяца. Такой подход кажется логичным и разумным, но на самом деле не работает, поскольку любой уважающий себя пользователь скорее продолжит смотреть порно каждый день, чем вознаградит себя подарком (на самом деле в его голове порно ценнее любых подарков). Это порождает сомнения в разумности пользователя, потому что ему не только придется воздерживаться в течение тридцати дней, но и он ещё не уверен, что получит удовольствие от этих дней без порно и от подарка. У него отняли единственное удовольствие/костыль! Всё это лишь увеличивает размер жертвы, которую, по мнению пользователя, он приносит, и теперь порно становится ещё более ценным в его сознании.

Другие примеры ложных стимулов:

-   Я остановлюсь, чтобы это заставило меня заняться социальной жизнью и более реальным сексом.

-   Я остановлюсь, чтобы какая-то магическая энергия помогла мне прыгнуть выше конкурентов и получить партнера, которого я добиваюсь.

-   Я остановлюсь, чтобы взять на себя обязательство не тратить свою энергию и энтузиазм на порно, чтобы взрастить в себе голод.

Они верны и могут быть эффективными, и в итоге вы можете получить то, что хотите, но задумайтесь об этом на секунду. Если вы действительно получите то, чего хотели, то после того, как новизна пройдет, вы будете чувствовать себя обделенным; а если не получите, то будете чувствовать себя несчастным. В любом случае, рано или поздно вы снова попадете в ту же самую ловушку.

Остановки из-за ложного стимула только усиливает сомнения, потому что если вы не получите то, что послужило стимулом (и даже если получите), вы начнете сомневаться, "*Действительно ли если я не буду смотреть порно моя жизнь станет лучше? А если я брошу, но не получу желаемое, правильно ли я тогда поступлю?*". Подобные мысли усиливают чувство лишения и, следовательно, вызывают страх.

Другим типичным примером являются договоры в Интернете или на форумах. Их преимущество заключается в том, что на определенный период они устраняют искушение и сомнения. Однако, как правило, они терпят неудачу по следующим причинам:

1.  Этот стимул является ложным. Серьёзно, вы хотите остановиться только потому, что так поступают другие люди? Всё, что это даёт, -- это создание дополнительного давления и усиление ощущения жертвования. Хорошо, если все пользователи искренне хотят остановиться в один конкретный момент -- но вы не можете заставить их остановиться, если все втайне всё ещё хотят порно. Пока они не готовы к этому, пакт создает дополнительное давление, что только усиливает их желание смотреть. Это превращает их в тайных зрителей, ещё больше усиливая ощущение зависимости.

2.  Зависимость друг от друга при использовании метода силы воли порождает чувство, что они проходят период покаяния, в течение которого они ждут, когда желание исчезнет. И если они сдаются, возникает чувство неудачи. При использовании метода силы воли по крайней мере один из участников обязательно сдастся, предоставив другим участникам оправдание, которого они так долго ждали. Это не их вина, они бы выдержали, но "Фред" их подвел. Правда заключается в том, что большинство из них уже нарушили договор до этого.

3.  Разделение заслуг -- обратная сторона такой взаимозависимости. Прекращение порнографии -- это замечательное достижение, и если вы делаете это в одиночку, то одобрение, которое вы получаете от своих друзей и интернет-приятелей, может стать огромным стимулом в первые несколько дней. Однако, когда все делают это одновременно, заслугу приходится делить, и, соответственно, стимул уменьшается.

4.  Другой классический пример -- пообещать гуру/учителю. Остановка даст вам счастье, потому что вы больше не участвуете во внутреннем перетягивании каната с самим собой, ваш мозг начинает перепрограммироваться и восстанавливает контроль над импульсами. Однако вы должны помнить, что это не сделает вас богом секса и не принесет выигрыш в лотерею. Никому, кроме вас, нет ни малейшего дела до того, что вы перестали использовать порнографию. Вы не слабый человек, если употребляете порно три раза в день и у вас есть PIED, и не сильный человек, если вы не смотрите порно и у вас всё нормально.

Перестаньте обманывать себя. Если предложение работать десять месяцев в год за двенадцатимесячную зарплату, или риск снизить способности вашего мозга справляться с ежедневным стрессом и нагрузками, или поставить себя под угрозу надежной эрекции, или пожизненные психические и физические пытки и рабство не остановили их, то вышеперечисленные фальшивые стимулы не внесут никаких изменений и лишь заставят чувствовать себя ещё хуже и вам начнёт касаться, что вы приносите ещё большую жертву. Вместо этого сосредоточьтесь на другом:

\"Что я получаю от этого? Почему мне нужно смотреть порно?\"

Продолжайте смотреть на другую сторону перетягивания каната и спросите себя, что порно даёт вам. *АБСОЛЮТНО НИЧЕГО*. Зачем мне это нужно? *НЕ НУЖНО! ВЫ ТОЛЬКО НАКАЗЫВАЕТЕ СЕБЯ*. Это пари Паскаля: вам почти нечего терять (угасающее возбуждение), шансы на большой выигрыш (полное и надежное возбуждение, душевное благополучие и счастье) и никаких шансов проиграть по-крупному.

Почему бы тогда не заявить о своем решении бросить порно друзьям и родственникам? Ну хотя бы потому что, это сделает вас гордым бывшим наркоманом или бывшим пользователем, а не восторженным и счастливым непользователем. Это может немного напугать вашего партнера, поскольку он может воспринять это как попытку заняться сексом в духе нью-эйдж. Они также могут испугаться, что вы превратитесь в секс-машину. Это трудно объяснить, если только они не настроены открыто.

Любая попытка вовлечь других людей, чтобы они помогли вам бросить порно, дает больше власти маленькому монстру. Пытаться избавиться от мыслей о порно и полностью игнорировать их -- с, что пытаться не думать об этом. Лучше оставайтесь внимательными, как только вы заметите мысли, сигналы (например, когда вы одни дома) или случайные мысли, просто скажите себе: "Отлично, я больше не раб порно. Я свободен и буду рад познать радость от обычного секса!" Это поможет снизить активность мысли и остановит её от перехода в состояние тяги и страстного желания. В этом может помочь практика mindfulness медитации дистанцирования от мыслей и их обезличивании (когда вы видите, что вы не являетесь вашими мыслями и создаёте дистанцию между собой и потоком мыслей).
