# Легкий способ остановиться

В этой главе содержатся инструкции о том, как легко прекратить использовать порнографию. Если вы будете следовать инструкциям, вы обнаружите, что прекратить использовать порнографию -- это относительно легко и даже приятно! Если вы будете следовать приведенным ниже инструкциям, то прекратить использовать порнографию будет до смешного просто. Всё, что вам нужно сделать, это две вещи:

1.  Примите решение, что вы больше никогда не будете смотреть порно.

2.  Не хандрите по этому поводу. Радуйтесь.

Вы, наверное, спрашиваете: "*Зачем нужна остальная часть книги? Почему вы не могли сказать это с самого начала?*". Ответ заключается в том, что вы бы в конце концов захандрили и, соответственно, изменили свое решение. Вероятно, вы уже делали это много раз.

Как уже было сказано, порно -- это тонкая, зловещая ловушка. Главная проблема остановки -- это не дофаминовая зависимость. Она, конечно, является проблемой, но не главной, главное -- это промывание мозгов. Поэтому сначала необходимо разрушить все мифы и заблуждения. Поймите своего врага, узнайте его тактику, и вы легко его победите. Проведя большую часть своей жизни в черной депрессии, пытаясь бросить, я, наконец, вырвавшись из нее, сразу же вышел в ноль без единого плохого момента. Это было приятно даже в период абстиненции, и с тех пор у меня не было ни малейшего чувства боли. Напротив, это было одно из самых замечательных событий в моей жизни.

Моя последняя попытка была иной. Как и все пользователи в наше время, я серьезно задумался над проблемой. До этого момента, после неудачи, я утешал себя мыслью, что в следующий раз будет легче. Мне и в голову не приходило, что мне придется идти по этому пути всю оставшуюся жизнь. Эта мысль наполнила меня ужасом, и я начал очень глубоко задумываться над этим вопросом.

Вместо того чтобы подсознательно открыть браузер, я проанализировал свои чувства и подтвердил то, что уже знал. Я не получал удовольствия от порнографии и считал её грязной и отвратительной. Я начал присматриваться к непользователям, живущим в других частях света, или к пожилым людям, которые никогда не знакомились с порносайтами. До этого момента я всегда считал непользователей невнятными, необщительными и жеманными людьми. Однако, понаблюдав за их поведением, я увидел, что они выглядят более сильными и более расслабленными. Они были способны справляться со стрессами и напряжением жизни и, казалось, получали больше удовольствия от общения, чем пользователи порнографии. У них определенно было больше искры и изюминки, чем у пользователей.

Я начал общаться с бывшими пользователями. До этого момента я всегда считал, что они были вынуждены бросить по состоянию здоровья или по религиозным причинам и втайне мечтали о посещении гарема. Некоторые, правда, говорили: *"У тебя бывают странные ощущения, но они так редки, что не стоит беспокоиться"*. Большинство же говорили: *"Соскучился? Вы, наверное, шутите! В жизни никогда не чувствовал себя лучше!"*. Для них неудачи были подспорьем для развития -- они не осуждали себя и безоговорочно принимали свои ошибки. Как тренер, который примет ошибку по-настоящему золотого игрока. Разговоры с бывшими пользователями разрушили ещё один миф, который всегда был у меня в голове, -- о том, что во мне есть врожденная слабость, пока меня не осенило: Все проходят через этот собственный кошмар.

По сути, я сказал себе: *"Множество людей сейчас прекращают это делать и живут вполне счастливой жизнью, мне не нужно было этого делать до того, как я начал, и я помню, как мне пришлось потрудиться, чтобы привыкнуть к этой грязи. Так почему я должен продолжать делать это сейчас?"*. В любом случае, я не получал удовольствия от порно, ненавидел весь этот грязный ритуал и не хотел провести остаток жизни в рабстве у этой отвратительной зависимости. Тогда я сказал себе следующее:

*"Хочешь ты этого или нет, но только что ты завершил свой последний сеанс."*

С того момента я понял, что больше никогда не буду использовать порно. Я не ожидал, что это будет легко, как раз наоборот. Я полностью верил, что подписался на месяцы черной депрессии и проведу остаток жизни с периодическими приступами. Но вместо этого, с самого начала это было абсолютное блаженство.

Мне потребовалось много времени, чтобы понять, почему это было так легко и почему я не испытывал этих ужасающих болей отмены. Причина в том, что их не существует, а в том что их вызывают сомнения и неопределённость. Проблема в неопределённости! Прекрасная правда заключается в том, что ***прекратить использовать порнографию очень просто***. Только нерешительность и хандра делают это трудным. Даже будучи зависимыми, пользователи могут обходиться без порно в определенные периоды времени. Только когда вы хотите, но не можете получить его, вы страдаете.

Поэтому ключ к тому, чтобы сделать это легко, -- это сделать остановку определенной и окончательной. Не надеяться, а знать, что вы остановились, приняв решение. Никогда не сомневайтесь и не задавайте вопросов, наоборот -- всегда радуйтесь! Если вы утвердитесь в определённости и радости с самого начала, это будет легко. Но как вы можете быть уверены с самого начала? Для этого и нужна остальная часть книги. Есть некоторые важные моменты, которые необходимо прояснить в своем сознании до того, как вы начнете:

1.  Поймите, вы можете это сделать. В вас нет ничего особенного, и единственный человек, который может заставить вас смотреть порно, -- это вы сами. Та звезда, которая никогда в своих самых смелых мечтах и не думала, что её будут использовать для уничтожения собственной мужественности, она здесь не причём. Только вы сами.

2.  Отказываться абсолютно не от чего. Наоборот, можно получить огромные положительные результаты. Вы не только станете здоровее и богаче, но и будете больше радоваться хорошим временам и меньше страдать в плохие.

3.  Не существует такого понятия, как только глянуть одним глазком или однократное посещение. Порнография -- это наркотическая зависимость и цепная реакция, и если вы будете раздумывать о разовом посещении, вы только бессмысленно накажете себя.

4.  Рассматривайте порно не как привычку, которая может причинить вам вред с позиции 'это природа мужчин', 'boys will be boys', а как наркотическую зависимость. Признайте тот факт, что, нравится вам это или нет, **у вас есть болезнь**. Она не исчезнет, если вы закроете на это глаза. Помните, что, как и все смертельные болезни, она не только останется на всю жизнь, но и ухудшится в геометрической прогрессии. И проще всего вылечиться от неё -- сейчас.

5.  Отделите болезнь -- неврологическую зависимость -- от мышления, быть или не быть пользователем. Все пользователи, если бы им дали возможность вернуться в то время, когда они ещё не были зависимы, сразу же ухватились бы за эту возможность. У вас есть такая возможность сегодня! И даже не думайте об этом как о "отказе".

Приняв окончательное решение о том, что у вас был последний визит, вы уже станете непользователем. Пользователь -- это один из тех несчастных, которые идут по жизни, уничтожая себя порнографией. Непользователь -- это тот, кто этого не делает. Приняв это окончательное решение, вы уже достигли своей цели. Радуйтесь этому факту, не сидите и не ждите, пока химическая зависимость пройдет. Немедленно выходите и наслаждайтесь жизнью. Жизнь прекрасна, даже если вы химически зависимы, а когда вы избавитесь от зависимости, каждый день жизнь будет становиться намного лучше.

Ключ к тому, чтобы легко бросить порно, -- это уверенность в том, что вам удастся полностью воздержаться порно в период абстиненции, который длится не более трех недель. Если у вас правильный настрой, это будет до смешного легко.

К этому моменту, если вы открыли свой разум и сердце, как просили в начале, вы уже решили, что собираетесь освободиться. Теперь вы должны испытывать нетерпение, словно собака, натягивающая поводок, вы не можете дождаться момента, когда разрушите водные порно-горки DeltaFosB. Если у вас возникает чувство обреченности и уныния, это может быть по одной из следующих причин:

1.  Что-то не срослось в вашем сознании. Перечитайте вышеприведенные пять пунктов и спросите себя, понимаете ли вы их истинность. Если вы сомневаетесь в каком-либо пункте, перечитайте соответствующие разделы книги.

2.  Вы боитесь самой неудачи. Не волнуйтесь, просто читайте дальше, и у вас все получится. Весь бизнес интернет-порно -- это мошенничество гигантского масштаба. Умные люди попадаются на уловки, но только дурак, узнав в чём заключается обман, продолжает обманываться.

3.  Вы со всем согласны, но всё равно несчастны. Не надо так! Откройте глаза, прямо сейчас происходит нечто совершенно удивительное. "Это лучший момент в жизни, понял? А ты где-то витаешь". Вы собираетесь освободиться из тюрьмы, важно начать с правильного настроя: *"Это замечательно, что я не пользователь!"*

Всё, что нужно сделать сейчас, -- это поддерживать такой образ мыслей в течение периода выхода из химической зависимости, и в следующих нескольких главах рассматриваются конкретные моменты, которые позволят вам это сделать. После периода абстиненции вам не нужно будет продолжать думать таким образом, вы будете так думать автоматически. Единственной загадкой в вашей жизни будет, почему вы не видели этого раньше. Однако, есть два важных предупреждения.

-   Отложите свой план последнего сеанса, пока не дочитаете книгу.

-   Много раз упоминался период выхода из зависимости до трех недель, что может вызвать недоразумения. Во-первых, вы можете подсознательно решить, что вам придется страдать в течение трех недель. Это не так. Во-вторых, избегайте ловушки мысли *"Я должен воздерживаться три недели, а потом все будет хорошо"*. Ничего волшебного после трех недель не произойдет, вы не почувствуете себя не употребляющим, как не чувствуют себя пользователи. Если вы хандрите по поводу прекращения употребления в течение трех недель, то, скорее всего, вы всё ещё будете хандрить по этому поводу после трех недель. Подводя итог, можно сказать, что если вы прямо сейчас начнете говорить: *"Я больше никогда не буду употреблять, разве это не замечательно?"*, то через три недели все искушения исчезнут. Однако если вы скажете себе: *"Если только я смогу выжить эти три недели без порно..."*, то по истечении трех недель вы будете умирать от желания посетить гарем.

Подумайте об этом так: ваш мозг хочет сохранить статус-кво, поэтому, если вы убеждены, что теряете что-то хорошее, когда бросаете порно, вы, очевидно, будете чувствовать себя ужасно. Невозможно заставить себя чувствовать себя определенным образом, если ваш мозг в это не верит. Вот почему важно пройти через трудности избавления от иллюзии, что порнография дает вам хоть что-то. Так вы поймёте, что ничем не жертвуете.

Сексуальная дисфункция во многом связана с вашим мозгом и восприятием. Интернет-порно перестраивает схему вознаграждения в вашем мозгу и заставляет ваш разум сомневаться. Это сомнение в себе, несомненно, приведет к сексуальной дисфункции. Иметь желание в верхней части тела, но не испытывать возбуждения в нижней -- худшее, что может случиться с вашим мышлением. Либидо, идущее рука об руку с романтикой, -- это эликсир молодости, который можно пить до самой смерти. Вы сохраните высокие шансы, если бросите, но это не единственная и не главная выгода. Главное -- это ваша свобода от рабства!
