# Период выхода из зависимости

В течение трех недель после последнего сеанса вы можете испытывать абстинентный синдром. Он состоят из двух совершенно отдельных, но разных факторов:

1.  Ощущение от отмены дофамина. Пустое, неуверенное чувство, похожее на голод, идентифицируемое как тяга или чувство "мне нужно что-то".

2.  Психологические триггеры определенных внешних стимулов, таких как рекламные ролики, просмотр интернет-страниц, телефонные разговоры и т.д.

Неспособность понять и различить эти два разных фактора делает достижение успеха с помощью метода силы воли крайне затруднительным и является причиной того, что многие, кому это удается, снова попадают в ловушку. Хотя дофамин не причиняет физической боли, не стоит недооценивать его силу. Мы говорим о боли в животе, если в течение дня обходимся без еды; в желудке может урчать, но на самом деле физической боли нет. Тем не менее, голод -- это мощная сила, и мы можем стать очень раздражительными, когда лишены пищи. Это похоже на то, как когда наш организм жаждет дофаминового всплеска, с той лишь разницей, что нашему телу нужна пища, а не яд. При правильном подходе к делу абстинентный синдром легко преодолевается и очень быстро проходит.

После воздержания в течение нескольких дней по методу силы воли тяга к дофаминовым вспышкам вскоре исчезает. А вот второй фактор -- промывание мозгов -- вызывает трудности. Пользователь привык снимать абстинентный синдром в определенное время и в определенных случаях, что вызывает ассоциацию идей ("Я возбудился, поэтому я должен посмотреть порно" или "Я лежу в постели с ноутбуком и должен провести сеанс, чтобы почувствовать себя счастливым"). Эффект лучше всего проиллюстрировать на примере: у вас есть машина, и поворотники находятся слева от руля, но в вашей следующей машине он находится справа. Вы знаете, что они слева, но в течение нескольких недель вы включаете стеклоочистители, когда хотите повернуть.

С остановками дело обстоит примерно так же: в первые дни спусковой механизм будет срабатывать в определенное время. Вы будете думать, что хотите сессию, поэтому противодействие промыванию мозгов необходимо с самого начала и оно приведет к тому, что эти сигналы и триггеры быстро исчезнут. При методе силы воли, поскольку пользователь считает, что приносит себя в жертву, он корит себя за это и ждет, пока позывы уйдут, что противоположно устранению этих пусковых механизмов, а на самом деле приводит к их усилению. Аналогично, мышлению "я уже эксперт", бросающий пользователь начинает задаваться вопросом, когда он уже станет крутым непользователем, и даже требует, чтобы у него не было таких мыслей, прокладывая путь к ненависти к себе и неудаче.

Частым спусковым крючком является одиночество, особенно на светских мероприятиях с друзьями. Бывший пользователь, использующий другие способы бросить, уже несчастен из-за того, что чувствует себя лишенным привычного костыля или удовольствия. Их друзья находятся со своими партнерами и ведут себя интимно. Пользователь либо одинок, либо не "получает ничего" от своего партнера, и теперь уже не получает удовольствия от того, что должно быть приятным общением с друзьями. Имеющиеся в их мозгу водные горки приводят их к порнографии, что гораздо проще, чем пытаться завоевать партнера.

Поскольку право на секс ассоциируется у них с благополучием, теперь им нанесен тройной удар, и промывание мозгов фактически усиливается. Если они решительны и могут продержаться достаточно долго, они в конце концов смиряются со своей участью и начинают жить дальше. Однако часть промывания мозгов всё ещё остается, второй наиболее жалкий аспект: пользователь бросил, но иногда даже спустя несколько лет ещё жаждет "последнего визита в гарем". Они тоскуют по иллюзии, которая существует только в их сознании, и без нужды мучают себя.

Даже под EasyPeasy реагирование на триггеры является наиболее распространенной неудачей. Бывший пользователь склонен рассматривать интернет-порно как своего рода плацебо или сахарную таблетку, думая: "Я знаю, что порно ничего не делает для меня, но если я буду думать, что оно делает... то в некоторых случаях это будет полезно". Сахарная таблетка, хотя и не оказывает реальной физической помощи, может быть мощным психологическим средством для облегчения истинных симптомов и поэтому полезна. Однако интернет-порно и привычная мастурбация -- это не сахарные таблетки. Почему? Порно создает симптомы, которые оно снимает, и перестает снимать их полностью.

Возможно, вам будет легче понять эффект, когда речь идет о человеке не употребляющем, или об успешном бывшем потребителе, который бросил в течение нескольких лет. Возьмем случай, когда пользователь теряет своего партнера. В такие моменты довольно часто, из лучших побуждений, им говорят: "Посети гарем один раз, это поможет успокоиться". Если они последуют этому позыву, он не окажет успокаивающего эффекта, поскольку нет дофаминовой зависимости и, следовательно, нет абстинентного синдрома. В лучшем случае это лишь даст им кратковременный психологический толчок.

Но ведь и после окончания сеанса изначальная трагедия остается. Более того, она усилится, потому что человек теперь страдает от абстинентного синдрома и вынужден делать выбор: терпеть его или искать облегчения, повторяя катание на водной горке, чтобы начать цепь страданий заново. Всё, что давало порно, -- это мимолетный психологический подъем, такой же, какой можно было получить от книги или хорошего фильма, или даже от плохого. Многие не употребляющие и бывшие употребляющие вновь стали зависимыми в результате таких случаев. Уясните для себя: вам не нужен прилив дофамина, и вы только ещё больше измучаете себя, продолжая рассматривать его как возможность, как некую опору или стимул. Нет необходимости быть несчастным.

Оргазм не делает отношения хорошими, чаще всего он их разрушает. Помните также, что не совсем верно, что те, кто демонстрирует публичные ласки, получают удовольствие по любому поводу; близостью лучше всего наслаждаться наедине, где партнеры могут ответить без смущения. Не обязательно быть дофаминовым наркоманом, который жаждет оргазма. Если это происходит как естественный результат ряда событий, это прекрасно, но наслаждайтесь событиями и жизнью без него.

Отказавшись от концепции порно как удовольствия самого по себе, многие пользователи думают: "*Если бы только было чистое порно в Интернете*". Существует чистое мягкое порно, и все, кто пробует его, вскоре убеждаются, что это пустая трата времени. Уясните для себя, что единственная причина, по которой вы используете порно, -- это получение дофаминового удовольствия. Как только вы избавитесь от дофаминовой тяги к порно, у вас отпадет необходимость посещать свой онлайновый гарем.

Независимо от того, вызвана ли эта боль реальными симптомами дофаминовой абстиненции или спусковыми механизмами, примите её. Физической боли не существует, и при правильном настрое это не будет проблемой. Не беспокойтесь об абстиненции -- само это чувство не так уж плохо. Проблема в ассоциации с желанием и последующим отказом самому себе. Вместо того чтобы хандрить по этому поводу, признайте: *"Я знаю, что это такое, это ломка после порно. Это то, от чего пользователи страдают всю свою жизнь и остаются зависимыми. Те, кто не используют, не испытывают таких мук, это ещё одно из многих зол лживой зависимости. Разве не чудесно, что я вычищаю эту напасть из своего мозга!"*.

Другими словами, в течение следующих трех недель у вас будет небольшая травма внутри вашего тела, но в течение этих недель и до конца вашей жизни с вами будет происходить нечто чудесное. Вы избавитесь от ужасной болезни, причем бонусы значительно перевесят легкую, временную травму, и будете наслаждаться абстинентным синдромом. Он станет моментами удовольствия, как захватывающая игра по уничтожению порнографического ленточного червя, живущего в вашем желудке. Вы должны морить его голодом в течение трех недель, пока он пытается обманом затащить вас в постель, чтобы сохранить свою жизнь.

Иногда он будет пытаться сделать вас несчастным. Временами вы будете застигнуты врасплох. Вы получите URL-адрес порнографического сайта или наткнетесь на что-то пикантное в Интернете и забудете, что вы прекратили, что вызовет легкое чувство лишения при воспоминании. Будьте готовы к таким уловкам заранее, и каким бы ни был соблазн, вбейте себе в голову, что он существует только из-за монстра внутри вашего тела, и каждый раз, когда вы сопротивляетесь соблазну, вы наносите ещё один сокрушительный удар в этой битве.

Что бы вы ни делали, не пытайтесь забыть о порно. Это одна из тех вещей, которые вызывают у ПМОеров, использующих метод силы воли, многочасовую депрессию. Они пытаются прожить каждый день, надеясь, что в конце концов они просто забудут об этом. Это как попытки заснуть накануне важного дня -- чем больше вы беспокоитесь, тем труднее это сделать. В любом случае, вы не сможете забыть об этом, в течение первых нескольких дней "маленький монстр" будет постоянно напоминать вам об этом, и вы не сможете избежать этого. Пока поблизости есть ноутбуки, смартфоны и журналы, вам постоянно будут напоминать об этом.

Дело в том, что вам не нужно забывать, поскольку ничего плохого не происходит. На самом деле происходит нечто чудесное и удивительное, и даже если вы думаете об этом тысячу раз в день, **смакуйте каждый момент, напоминайте себе, как это чудесно -- снова быть свободным. Напоминайте себе об огромной радости от того, что вам больше не нужно мучить себя**. Как уже говорилось ранее, вы обнаружите, что приступы ломки стали моментами радости, и удивитесь, как быстро вы забудете о порнографии.

Что бы вы ни делали, *не сомневайтесь в своем решении*. Как только вы начнете сомневаться, вы начнете хандрить, и всё станет хуже. Вместо этого используйте моменты хандры и превратите их в стимул к развитию. Если всё дело в депрессии, напомните себе, что её *вызвало* порно. Если друг переслал вам URL-адрес, с гордостью скажите: *"Я рад сообщить, что я больше в этом не нуждаюсь"*. Это причинит им боль, но когда они увидят, что это вас не беспокоит, и они будут на полпути к тому, чтобы присоединиться к вам.

**Помните: у вас есть невероятно веские причины для того, чтобы прекратить использовать порно**. Напомните себе об издержках и спросите себя, действительно ли вы хотите рискнуть нарушением работы вашего тела, разума и тем простым фактом, что вы будете жить под проклятием слабости всю оставшуюся жизнь. Помните об усилиях маленького монстра, направленных на минимизацию опасности, и, прежде всего, помните, что это ощущение лишь временное, и каждый момент приближает вас к цели.

Некоторые пользователи опасаются, что им придется потратить всю оставшуюся жизнь на преодоление "автоматических триггеров". Другими словами, они считают, что им придется всю жизнь, используя психологию, обманывать себя, что им не нужно порно. Это не так; помните, что оптимист видит бутылку наполовину полной, а пессимист -- наполовину пустой. В случае с порнографией бутылка пуста, а пользователь видит её полной. В использовании интернет-порно нет никаких преимуществ. Пользователю промыли мозги, чтобы он думал, что преимущества есть. Как только вы начнете говорить себе, что порнография вам не интересна или не нужна, через некоторое время вам даже не нужно будет говорить себе об этом, вы сами увидите прекрасную правду. Это последнее, что вам нужно сделать; но убедитесь, что это не последнее, что вы сделаете в своей жизни.
