# Гляну одним глазком

Это -- гибель для многих, использующих метод силы воли. Они выдерживают три-четыре дня, а затем, чтобы передохнуть, устраивают себе пикник. Они не осознают, какой разрушительный эффект это оказывает на их моральный дух.

Для большинства пользователей, при их самом первом посещении порносайта, гарем был не так хорош, как секс с реальным человеком. Чистых клипов мало, и они дают им повод думать: "*Ладно, это было не так уж приятно. Я теряю желание и не так уж люблю шокирующие вещи*". На самом деле всё происходит наоборот. Проясните в своем сознании, что наслаждение оргазмом не было причиной, по которой вы использовали порно. Если бы вы были там только ради оргазма, вы бы всегда смотрели один ролик. Единственной причиной, по которой вам нужна была порнография, было кормление этого маленького монстра. Только подумайте, после четырехдневного голодания, как ценен был для него этот единственный ролик. Ваш сознательный разум не знает об этом, но воздействие при просмотре этого единственного ролика, которое получило ваше тело, передается в ваше подсознание, и вся ваша тщательная подготовка будет сведена на нет. В глубине вашего сознания будет звучать голос, говорящий, что, несмотря на всю логику, сеансы драгоценны, и вы хотите ещё один.

Это заглядывание всего на один разочек имеет два разрушительных эффекта:

1.  Оно поддерживает жизнь маленького монстра в вашем теле.

2.  И, что хуже того, оно поддерживает жизнь большого монстра в вашем сознании. Если у вас будет "последний разочек", потом вам будет легче сделать ещё один разочек, опять же последний.

Порно -- это мышеловка без сыра, там только яд. Используя силу воли, вы пытаетесь убедить себя не хватать сыр. EasyPeasy позволяет вам увидеть, что там не сыр, а яд. Вам не нужно избегать его, вы просто больше не захотите в это ввязываться.

Прежде всего, помните:

*'Только один раз посмотреть' -- вот именно так люди и попадают в зависимость.*
