# Станет ли мне сложнее?

Существует бесконечное количество комбинаций факторов, определяющих, насколько легко каждый конкретный пользователь бросит. Начнем с того, что у каждого из нас свой характер, карьера, личные обстоятельства, время, метаболизм и т.д. Определенные профессии могут усложнить это, но если промывание мозгов будет устранено, это не будет сложно. Возьмем несколько следующих примеров.

Иногда это бывает трудно для представителей медицинской профессии. Мы думаем, что врачам должно быть легче, потому что они лучше осведомлены о последствиях, но хотя это дает более веские основания для прекращения употребления, это не облегчает задачу. Причины следующие:

1.  Постоянное осознание риска для здоровья порождает страх -- одно из условий, при котором мы испытываем потребность в снятии абстинентного синдрома.

2.  Работа врача является чрезвычайно напряженной, и они обычно не могут снять дополнительный стресс, связанный с абстинентным синдромом, во время работы.

3.  Они испытывают дополнительный стресс от чувства вины, считая, что должны подавать пример остальному населению. Это оказывает на них дополнительное давление и усиливает чувство лишения.

После тяжелого рабочего дня, когда их стресс на мгновение снимается порнографией, эта сессия неверно ассоциируется с пережитым облегчением. Из-за этой неправильной ассоциации порнография получает внутренее признание за всю ситуацию, внезапно становясь драгоценным, когда пользователь бросает и переживает абстинентный синдром. Это одна из форм случайного пользователя, и она применима к любой ситуации, когда пользователь вынужден воздерживаться в течение длительного времени. При методе силы воли пользователь несчастен, потому что его лишают удовольствия и он не наслаждается усталостью и сном, которые наступают после использования. Их чувство потери значительно усиливается. Однако если сначала устранить "промывание мозгов" и хандру по порнографии, то перерывом и сном можно наслаждаться даже тогда, когда организм жаждет аминных трансмиттеров -- серотонина, норэпинефрина и дофамина.

Еще одна сложная ситуация -- скука, особенно в сочетании с периодами стресса. Типичный пример -- студенты и родители-одиночки, для которых работа является однообразной и в то же время приносит много стресса. При попытке остановиться с помощью метода силы воли одинокий человек может долгое время размышлять о своей "утрате", что, в свою очередь, усиливает ощущение депрессии. Опять же, это можно легко преодолеть, если вы правильно настроены. Не переживайте, если вам постоянно напоминают, что вы перестали использовать порнографию. Используйте такие моменты, чтобы радоваться, что вы избавились от злобного монстра.

Если вы настроены позитивно, эти ощущения превратятся в моменты радости. Помните, что любой пользователь, независимо от возраста, пола, интеллекта или профессии, может легко и с удовольствием остановиться, **если вы будете следовать всем инструкциям.**

## Основные причины неудач

Существует две основные причины неудач. Первая -- влияние внешних раздражителей -- рекламного ролика, новостной статьи в Интернете, просмотра интернет-страниц и т.д. Они обнаруживают себя в моменте слабости или даже начинают ревновать при виде интимности других людей в социуме. Эта тема уже подробно обсуждалась. Используйте этот момент, чтобы напомнить себе, что не бывает "одиночного раза" или "глянуть одним глазком". Радуйтесь тому, что вы разорвали цепь психического рабства. Помните, что пользователь завидует вам, и вы должны пожалеть его, он в этом нуждается.

Другая причина -- "плохой день". Прежде чем начать, четко уясните для себя, что независимо от того, являетесь вы пользователем или нет, у вас будут и хорошие и плохие дни. Дождь идет и для Папы римского, и для убийцы. Жизнь относительна, и у вас не может быть взлетов без падений. Проблема метода силы воли заключается в том, что как только у пользователя наступает плохой день, он начинает скучать по визитам в "гарем", что ещё больше усугубляет проблему. Непользователь лучше приспособлен к стрессам и нагрузкам, причем не только физическим, но и умственным. Если у вас плохой день в период абстиненции, просто примите его как должное; напомните себе, что плохие дни существовали, и когда вы были зависимы, иначе вы бы не решили завязать. Вместо того чтобы корить себя за это, признайте это: *"Ладно, сегодня мне не очень хорошо, но порно здесь никак не поможет. Завтра будет лучше, и, по крайней мере, теперь у меня есть замечательный бонус: я избавился от этой ужасной зависимости".*

Когда вы являетесь пользователем порно, вам приходится не пускать в свой ум мыслей о вреде порно. По мнению пользователей, у них никогда не бывает тумана в голове, они "просто немного подавлены". Когда у вас неизбежные жизненные неприятности и вы ловите себя на мысли, что вам хочется порно, вы веселы и счастливы? Конечно, нет. Как только вы прекращаете употреблять порно, вы начинаете обвинять во всем, что идет не так, тот факт, что вы прекратили.

Если работа напрягает вас, вы думаете: "Я бы устроил сеанс". Это так, но вы забываете о важном: порно не решит вашу проблему, и, хандря по иллюзорным костылям, вы просто наказываете себя. Вы создаете себе невыносимую ситуацию: вы несчастны, так как не запрещаете себе
мастурбировать на порно, но если вы это сделаете, вы будете ещё более несчастны. Вы знаете, что приняли правильное решение, прекратив употреблять порно, так зачем же наказывать себя, сомневаясь в своем решении?*

Помните, что позитивный настрой жизненно необходим. Всегда.
