# Заменители

Примерами заменителей могут быть ограничение себя просмотром порножурналов, статичных изображений в Интернете, порнодиетами и т.д. **НЕ ИСПОЛЬЗУЙТЕ НИЧЕГО ИЗ ЭТОГО**. Они делают всё труднее, а не легче. Если у вас возникнет желание и вы воспользуетесь заменителем, то это только продлит само желание, делая всё ещё более трудным. На самом деле что вы говорите, это что вам нужно порно, чтобы заполнить пустоту. Это все равно, что уступить угонщику авто или поддаться детской истерике, -- это не отменит мучений и только продлит пытку. В любом случае, заменители не избавят от мучительных ощущений. Ваша тяга связана с определенными нейротрансмиттерами в мозге, и всё, что они сделают, это заставят вас думать о порно, потому что так вы их настроили в прошлом. Запомните следующие моменты:

1.  Порно нечем заменить.

2.  Вам не нужно порно. Это не пища, а яд. Когда наступит ломка, напомните себе, что именно пользователи страдают от ломки, а не те, кто не употребляет. Воспринимайте ломки такими, какие они есть, -- это ещё одно зло от наркотика. Воспринимайте их как смерть монстра.

3.  Интернет-порно создает пустоту, а не заполняет ее. Чем быстрее вы приучите свой мозг к тому, что у вас нет потребности смотреть порно, тем быстрее вы освободитесь. В частности, избегайте всего, что напоминает порно, например, мужских журналов, фильмов, романтических романов и рекламы. Это не значит, что вы замкнуты в себе, говорить о романтике и сексе это нормально, но не о порно. Всегда можно найти способ найти, когда и где проводить линию. Это правда, что небольшая часть пользователей, которые пытаются бросить, употребляя лишь мягкое порно или порнодиеты, добиваются успеха (с их собственной точки зрения), и приписывают свой успех такому ограничению. Однако они бросают не благодаря, а вопреки такому ограничению. Жаль, что многие до сих пор рекомендуют эти меры.

Это неудивительно, потому что если вы не до конца понимаете, что такое порноловушка, диета или мягкая замена звучит очень логично. Она основана том, что когда вы пытаетесь бросить порно, вы убеждены, что у вас есть два мощных врага, которых нужно победить:

-   Избавление от привычки.

-   Переживание ужасных физических болей при абстиненции.

Можно думать, что если у вас есть два сильных врага, которых нужно победить, разумно сражаться с ними не одновременно, а по очереди. Теория гласит, что когда вы впервые перестаете пользоваться порнографией, вы сокращаете порцию до одного раза в неделю или используете безопасное порно. Затем, когда привычка будет отменена, постепенно сокращайте порцию, таким образом, борясь с каждым врагом по отдельности.

Это звучит логично, но основано на неверной информации. Порно -- это не привычка, а дофаминовая зависимость, а реальная физическая боль от отмены почти незаметна. То, чего вы пытаетесь достичь, бросив порно, -- это как можно быстрее убить монстров в вашем теле и мозге. А всё, что делают методы замещения, -- это продлевают жизнь маленького монстра, а это, в свою очередь, усиливает промывание мозгов (большого монстра). EasyPeasy позволяет бросить немедленно, убивая промывание мозгов ещё до последнего сеанса. Маленький монстр скоро умрет, и даже пока он умирает, он не будет серьезной проблемой.

Только подумайте, как можно вылечить зависимость от наркотика, рекомендуя тот же самый наркотик? В Интернете можно найти множество историй о тех, кто бросил употреблять жёсткое порно, но подсел на "безопасные" альтернативы, поддавшись на оправдания своего маленького монстра. Не обманывайтесь тем, что безопасное порно не так ужасно, как тот очень интенсивный ролик. Все заменители имеют точно такой же эффект, как и любое порно. Некоторые даже начинают в буквальном смысле переедать, и хотя пустое чувство желания сессии почти неотличимо от голода по еде, одно не удовлетворит другое. На самом деле, если что-то и может заставить вас захотеть порно, так это набивание себя едой. Как уже объяснялось ранее, порнодиеты и безопасное порно лишь поставят вас в середину перетягивания каната, причем сопротивление искушению будет настолько раздражающим, что вы сможете почувствовать облегчение только посетив свой любимый онлайн-гарем.

Главное зло заменителей -- это продление настоящей проблемы промывания мозгов. После того как вы выздоровели от гриппа, вы ищете ему замену, чем бы ещё заболеть? Конечно, нет. Говоря, что вам нужен заменитель порнографии, вы на самом деле говорите, что чем-то жертвуете. Депрессия, связанная с методом силы воли, вызвана тем, что пользователь считает, что приносит себя в жертву. При таком подходе, всё, что вы делаете, это замените одну зависимость другой. Нет никакого удовлетворения в том, чтобы без конца запихивать в себя еду, сигареты или алкоголь. Вы просто растолстеете, станете несчастным и через короткое время вернетесь к изначальной зависимости.

Случайным пользователям трудно отбросить убеждение, что их лишают маленькой награды, например, тем, у кого нет возможности выходить в Интернет в течение определенного периода времени во время путешествия, семейного мероприятия и т.д. Некоторые говорят: "*Я бы не знал, как расслабиться, если бы не порно*". Это доказывает, что часто перерыв делается не потому, что пользователь нуждается или даже хочет этого, а потому, что он зависим -- а именно таковым он является -- отчаянно нуждается в том, чтобы почесать зуд.

Помните, что порносеансы никогда не были настоящим вознаграждением. Они были равносильны ношению тесной обуви, только лишь для того, чтобы испытать удовольствие от снятия. Так что если вы чувствуете, что вам необходимо иметь небольшое вознаграждение такого рода, так и сделайте; во время работы носите обувь или нижнее белье на размер меньше, и не позволяйте себе снимать их, а затем испытайте прекрасный момент расслабления и удовлетворения, когда они будут сняты. Возможно, вам кажется, что это довольно глупо. Вы абсолютно правы, так и есть. Представить ношение тесной обуви, находясь в порноловушке, может быть трудно, но поверьте, именно так пользователи и поступают. Также трудно представить, что скоро вам не понадобится эта маленькая "награда" и что вы будете смотреть на друзей, которые ещё находятся в ловушке, с искренней жалостью и удивляться, как они ещё не поняли смысл происходящего с ними.

Однако если вы будете продолжать обманывать себя, что посещение онлайн-гарема было настоящей наградой и что вам нужна замена, вы будете чувствовать себя обделенным и несчастным. Есть вероятность, что вы снова попадете в отвратительную ловушку. Если вам нужен настоящий перерыв, как это делают домохозяйки, учителя, врачи и другие работники, то вскоре вы будете наслаждаться этим перерывом ещё больше, потому что вам не придется возвращать себя в зависимость. Помните, что вам не нужен заменитель. Ощущения ломки -- это тяга к дофамину, и очень скоро они пройдут. Пусть это станет вашей опорой на ближайшие несколько дней, и наслаждайтесь избавлением своего тела и разума от рабства и зависимости.
