# Должен ли я избегать искушений

До сих пор советы были прямыми и просили вас относиться к ним как к инструкциям, а не как к предложениям. Для этого есть разумные, практические причины, и эти причины подтверждены тысячами примеров. Что касается вопроса о том, стоит ли пытаться избежать искушения, здесь индивидуально. Каждый пользователь должен решить самостоятельно. Однако можно сделать два полезных предложения, которые помогут вам в этом процессе. Именно страх перед будущими приступами абстиненции удерживает нас от употребления порнографии до конца жизни, и этот страх состоит из двух различных фаз.

**Первая фаза -- "*Как я смогу выжить без порнографии?*"**

Этот страх -- паническое чувство, возникающее у пользователя, когда он одинок или имеет асексуального, неинтересного или недоступного партнера. Этот страх вызван не абстинентным синдромом, а психологическим страхом зависимости, неспособности прожить без секса и оргазма. Он достигает пика, когда вы уже на грани выхода из зависимости, когда ваши страхи абстиненции достигают своего минимума. Это страх перед неизвестным, подобный страху, который испытывают люди, когда учатся нырять в воду.

Высота тумбочки для прыжков в воду -- один фут, но кажется, что высота шесть футов. Глубина бассейна -- шесть футов, но кажется, что глубина -- один фут. Действительно требуется мужество, чтобы прыгнуть в воду, если думать, что разобьёшь себе голову. Прыжок -- самое трудное, но если вы найдете в себе мужество сделать это -- остальное будет легко! Это объясняет, почему многие волевые пользователи никогда не пытаются остановиться, или могут продержаться всего несколько дней, когда всё же пытаются. Более того, некоторые пользователи, сидящие на порнодиете, решив остановиться, впадают в запой и переходят к более жёстким клипам быстрее, чем если бы они не решали остановиться. Решение вызывает панику, что является стрессом и провоцирует желание отправиться в гарем. Но теперь вы не можете туда пойти, что приводит к мыслям о лишениях, усугубляя стресс.

Триггер быстро срабатывает, когда перегорает предохранитель и вы запускаете браузер. Не волнуйтесь, паника -- это всего лишь психологическое состояние. Это страх, что вы зависимы. Прекрасная правда заключается в том, что это не так, даже если вы всё ещё зависимы. Не паникуйте и смело прыгайте.

**Вторая фаза -- долгосрочный страх**

Вторая фаза -- долгосрочная, связанная со страхом, что определенные ситуации в будущем не будут приятными или вы не сможете справиться с трудностями без порнографии. Не волнуйтесь, если вы смогли прыгнуть, скоро вы убедитесь, что всё вы можете. Само избегание искушения делится на две категории.

1.  "*Я сяду на порно-диету 'один раз в четыре дня'. Я буду чувствовать себя увереннее, зная, что могу зайти на порносайт, если станет совсем плохо. Если у меня не получится, ничего страшного, я просто добавлю дополнительные дни к следующему циклу.*"

    Процент неудач у тех, кто так поступает, **гораздо выше**, чем у тех, кто бросает насовсем. В основном это связано с тем, что если у вас плохой день в период абстиненции, то с вышеупомянутыми отговорками вам легко зайти в браузер и посетить гарем. Если вы нарушаете свои собственные правила, то вам приходится столкнуться с чувством унижения и подверженности искушениям. Как бы там ни было, если бы вы отложили это на потом, то, скорее всего, чувство вины уже прошло бы. Однако основная причина высокого процента неудач в этих случаях заключается в том, что пользователь не чувствовал полной решимости остановиться с самого начала. Помните, что для достижения успеха необходимы следующие два условия:

    -   Определенность.

    -   "*Разве это не чудесно, что мне больше не нужно порно?*"

    В любом случае, с какой стати вам нужен сеанс? Если вам всё ещё нужно посетить свой гарем, сначала перечитайте книгу. Вы что-то не поняли. Потратьте время, чтобы убить большого монстра, промывающего вам мозги, это самое важное.

2.  "*Следует ли мне избегать стрессовых или социальных ситуаций в период абстиненции?*"

    В случае стрессовых ситуаций -- да. Нет смысла оказывать на себя излишнее давление. А в случае с общественными мероприятиями, такими как встречи друзей или собрания с родственниками, совет обратный. Идите и получайте удовольствие прямо сейчас! Вам не нужен секс или порно, даже если вы зависимы от порно. Так что выходите на улицу и радуйтесь тому, что вам это не нужно, это быстро докажет вам прекрасную истину, что жизнь намного лучше без давления зависимости. Только подумайте, насколько вам станет лучше, когда маленький монстр покинет вас вместе с мыслями, что вам чего-то недостаёт.
