# Момент откровения

Обычно в течение трех недель после выхода из зависимости бывшие пользователи переживают момент откровения. Кажется, что небо стало светлее, и это момент, когда промывание мозгов полностью заканчивается. Вместо того чтобы говорить себе, что тебе не нужно смотреть порно, ты вдруг понимаешь, что последняя ниточка оборвалась, и ты можешь наслаждаться своей жизнью, никогда больше не нуждаясь в этом. С этого момента вы начинаете смотреть на пользователей как на объект жалости.

Те, кто бросает с помощью метода силы воли, обычно не переживают этот момент, потому что, хотя они и рады, что бросили, они продолжают жить, считая, что чем-то жертвуют. Чем сильнее была ваша зависимость, тем чудеснее этот момент, и он длится всю жизнь. Хотя в жизни есть много радостей, невозможно повторить то чувство, которое вы испытываете. Радость от того, что вам больше не нужно смотреть порно, совсем другая. Если вы чувствуете себя подавленным и нуждаетесь в поддержке, напомните себе о том, как прекрасно не быть подсаженным на эту ужасную зависимость. Многие называют это одним из величайших событий в своей жизни. В большинстве случаев момент откровения наступает не через три недели, а через несколько дней.

В моем случае это произошло до того, как я закончил свой последний визит в гарем. Я уверен, что многие из читателей здесь, ещё не дойдя до конца глав, сказали бы что-то вроде: "Не нужно больше ни слова. Я вижу все это так ясно, что знаю, что мне больше никогда не понадобится порно". Судя по полученным отзывам, такое случается часто. В идеале, если вы следуете всем инструкциям и полностью поняли психологию зависимости, это должно произойти с вами немедленно.

Хотя утверждается, что для того, чтобы ощутимая физическая ломка прошла, требуется около пяти дней, а для полного освобождения -- около трех недель, такие рекомендации могут вызвать две проблемы. Первая заключается в том, что в сознание людей внедряется мысль о том, что им придется страдать от пяти дней до трех недель. Вторая заключается в том, что бывший потребитель склонен думать: "*Если я могу продержаться пять дней или три недели, то в конце этого периода я могу рассчитывать на ощутимый прилив сил. *".

Однако у них может быть пять приятных дней или три приятные недели, после чего наступают катастрофические дни, которые бывают у всех, и которые не имеют ничего общего с зависимостью, а вызваны другими факторами в нашей жизни. Тогда наш бывший пользователь, ожидающий момента откровения, вместо этого испытывает депрессию. Это может разрушить их уверенность в себе. Точно так же, если бы не было никаких указаний, бывший пользователь мог бы провести остаток жизни, ожидая, что ничего не произойдет. Именно это происходит с подавляющим большинством тех, кто бросает, используя метод силы воли.

Люди часто спрашивают о значении пяти дней и трех недель. Являются ли они просто периодами, взятыми с потолка? Нет, хотя это и не конкретные периоды, они отражают накопленный за годы опыт многих людей. Примерно через пять дней после прекращения употребления порно бывший пользователь перестает считать зависимость основным занятием своего ума. Большинство бывших пользователей испытывают откровение примерно в этот период, обычно в стрессовых или социальных ситуациях, с которыми когда-то они не могли справиться или которые не доставляли им удовольствия без посещения гарема. Вы вдруг понимаете, что не только получаете удовольствие от жизни и со всем справляетесь, но и мысль о порнографии никогда не посещает вас. С этого момента всё обычно идет как по маслу. Именно тогда вы понимаете, что свободны.

По моему опыту и опыту многих других людей, пытавшихся прекратить просмотр порно с помощью метода силы воли, большинство серьезных попыток прекратить просмотр порно терпят неудачу в течение трёх недель. Часто происходит так: через какое-то время вы чувствуете, что у вас пропала тяга к просмотру порно. Но вам нужно доказать это самому себе, поэтому вы заходите в браузер посетить свой гарем. Это странное желание -- доказывать, что ты поборол порно. Но в процессе, благодаря свежему приливу дофамина, вы смазываете водную горку DeltaFosB, чего ваше тело жаждало последние три недели. Как только вы завершаете дело, дофамин начинает покидать ваше тело. Вновь появляется тоненький голосок: "*Ты не бросил, ты хочешь ещё*".

Вы не возвращаетесь туда сразу, потому что не хотите снова попасться на крючок, позволяя пройти безопасному периоду. При следующем искушении вы можете сказать себе: "*Ну, я же не подсел снова, значит, нет ничего страшного в том, чтобы попробовать один раз*". Вы уже на пути по скользкой дорожке. Ключ к решению проблемы не в том, чтобы ждать момента откровения, а в том, чтобы осознать, что как только вы закрыли порносайт в последний раз, все закончилось. Вы перекрыли доступ кислорода к своему маленькому монстру. Никакая сила на Земле не сможет помешать вам стать свободным, если вы не будете хандрить или ждать откровения. Идите и наслаждайтесь жизнью; справляйтесь с ней с самого начала. Этот момент скоро случится.
