# Последний визит

Определившись, вы готовы в последний раз навестить свой гарем. Перед этим проверьте наличие двух предметов первой необходимости.

1.  Чувствуете ли вы уверенность в успехе?

2.  Есть ли у вас чувство обреченности и уныния или наоборот вы вывоодушевлены тем, что вы вот-вот свершите что-то чудесное?

Если у вас есть сомнения, перечитайте книгу сначала. Помните, что вы никогда не решали попасть в порноловушку, но эта ловушка создана для того, чтобы поработить вас на всю жизнь. Чтобы выбраться из нее, вам нужно принять положительное решение о том, что вы собираетесь остановиться и сделать последний визит.

Помните, что единственная причина, по которой вы до сих пор читали эту книгу, заключается в том, что вы очень хотите стать свободными. Поэтому примите это положительное решение прямо сейчас, дав торжественную клятву, что когда вы закроете приватное окно браузера, независимо от того, легко это или сложно, вы больше никогда не посетите свой гарем. Возможно, вы переживаете, что уже несколько раз давали эту клятву в прошлом и все равно нарушили обещание, или что вам придется пережить ужасную травму. Не бойтесь, самое худшее, что может случиться, -- вы потерпите неудачу, поэтому вам ***абсолютно нечего*** терять, но можно очень много приобрести.

Однако перестаньте даже думать о неудаче -- прекрасная правда заключается в том, что бросить порно не только до смешного легко, но и можно получить удовольствие от этого процесса. На этот раз вы будете действовать по методу EasyPeasy! Всё, что вам нужно сделать, -- это следовать простым инструкциям, которые вам будут даны.

1.  Дайте торжественную клятву прямо сейчас и сделайте это искренне.

2.  Просматривайте фотографии и клипы на известном сайте осознанно, увидьте отчаянные попытки администраторов и разработчиков сайта, актеров и любителей усилить шок, новизну и сверхнормальность своих роликов. И спросите себя, в чём же здесь удовольствие?

3.  Когда вы наконец закроете браузер, сделайте это не с чувством "*Я больше никогда не должен посещать онлайн гарем*" или "*Мне не позволено посещать больше*", а с чувством свободы, например, "*Разве это не здорово? Я свободен! Я больше не раб порно! Мне больше никогда в жизни не придется посещать эти грязные сайты*".

4.  Имейте в виду, что в течение нескольких дней в вашем желудке будет жить маленький порно-саботажник. Только, вы уже будете осознавать это чувство желания сеанса. Маленького порномонстра называют легкой физической тягой к дофамину. Строго говоря, это неверно, и важно понять, почему. Поскольку для того, чтобы этот маленький монстр умер, требуется до трех недель, бывшие пользователи считают, что маленький монстр будет продолжать испытывать желание после последнего посещения онлайн-гарема, и поэтому они должны использовать силу воли, чтобы противостоять искушению в этот период. Это не так, тело не жаждет дофамина, вызываемого порнографией; жаждет только мозг.

Если в течение следующих нескольких дней у вас возникнет ощущение, что вы хотите чуть-чуть глянуть порно, у вашего мозга есть простой выбор. Он может либо интерпретировать это чувство как то, чем оно является на самом деле -- пустым, неуверенным ощущением, возникшим после первого посещения порносайта и закрепляющимся с каждым последующим, и сказать себе: **"УРААА! Я - НЕПОЛЬЗОВАТЕЛЬ!"**

Или же вы можете снова начать увлекаться порнографией и страдать от этого всю оставшуюся жизнь. Но вы только задумайтесь на минуту, не будет ли это невероятной глупостью? Сказать: "*Я больше никогда не хочу смотреть порно*", а затем провести всю оставшуюся жизнь говорить: "*Эх, хотел бы я сейчас заглянуть на сайт...*"? Именно так поступают те, кто использует метод силы воли, и неудивительно, что они чувствуют себя такими несчастными. Проводя остаток жизни в отчаянной хандре из-за того, чего, как они же сами отчаянно надеются, у них никогда не будет. Неудивительно, что лишь немногие добиваются успеха, а те, кто добивается, никогда не чувствуют себя полностью свободными.

> *'Представьте, вы спокойно сидите, вдруг звонит телефон, вы позволяете телефону звонить, и игнорируете его сигнал, не реагируете на этот стимул. Хотя вы и знаете что он звонит, вы больше не обращаете внимания и не подчиняетесь ему. Также четко зафиксируйте в своем сознании тот факт, что внешний сигнал сам по себе не имеет над вами никакой власти, не способен сдвинуть вас с места. В прошлом вы подчинялись ему, реагировали на него по привычке. При желании вы можете сформировать новую привычку -- не реагировать компульсивно на внешние раздражители. Четко закрепите это понимание в своем сознании, так как оно может быть весьма полезным для преодоления силы внешних раздражителей, мешающих вам.*
>
> *Заметьте также, что ваша способность осознанно выбирать свою реакцию состоит не только и не столько в том, что надо обязательно что-то сделать: приложить усилия, или сопротивляться, или бороться, но и в том, чтобы мочь ничего не делать -- вы расслаблятесь и выбираете ничего не делать. Вы просто расслабляетесь, игнорируете сигнал и позволяете его призыву остаться без ответа. Телефонный звонок -- это аналогия с любым другим внешним раздражителем, которому вы привыкли отдавать управление собой, а теперь намеренно выбираете изменить эту привычку.*'
>
> ---  Максвелл Мольц, Новая психокибернетика, гл. 12. 

Именно сомнения и ожидание чего-то особенного мешают бросить, поэтому  ***никогда не сомневайтесь в своем решении***, потому что вы знаете, что оно правильное. Если вы начнете сомневаться, вы поставите себя в проигрышное положение -- вы испытываете уныние то того, вы жаждете посещения, но не можете его получить. Независимо от того, какую методику вы используете, чего вы хотите добиться, бросив порно? Никогда больше не смотреть порно? Неверно! Многие бывшие потребители так и поступают, но всю оставшуюся жизнь чувствуют себя обделенными.

В чём разница между героиновым наркоманом и вами? У вас нет ни потребности, ни желания, у вас нет дикой тяги вколоть в себя шприц и вам не нужно проявлять силу воли, чтобы не делать этого. Даже если в метре от вас лежит отборный героин готовый к употреблению, вам всё равно. Даже если ничто не мешает это сделать, вам не хочется, вы понимаете, насколько это опасно, вам это не интересно. Вы даже не рассматриваете такую возможность.

В чем разница между пользователями и непользователями? У непользователей нет ни потребности, ни желания смотреть порно, у них нет тяги и им не нужно проявлять силу воли, чтобы не смотреть его. Именно этого вы пытаетесь достичь, и это полностью в ваших силах. Вам не нужно ждать, чтобы перестать испытывать тягу к порно или стать непользователем, это произойдет в тот момент, когда вы закроете последнее окно порносайта, перекрыв поступление дофамина. **ВЫ УЖЕ СЧАСТЛИВЫЙ НЕПОЛЬЗОВАТЕЛЬ!**

Вы останетесь счастливым непользователем, если:

1.  Вы никогда не сомневаетесь в своем решении.

2.  Вы не ждете, когда станете непользователем. В этом случае вы просто будете ждать, пока ничего не произойдет, и создадите себе фобию.

3.  Вы не пытаетесь не думать о порнографии и не ждете "момента откровения", создавая фобию.

4.  Вы не используете заменители.

5.  Вы видите всех других пользователей такими, какие они есть на самом деле, вы жалеете их, а не завидуете им.

Независимо от того, хорошие это дни или плохие, не меняйте свою жизнь только потому, что вы бросили. Если вы это сделаете, то принесете настоящую жертву, когда в этом нет необходимости. Помните, вы не отказались от жизни. Вы ни от чего не отказались. Напротив, вы излечились от ужасной болезни и вырвались из коварной тюрьмы. Пройдут дни, и ваше здоровье -- как физическое, так и психическое -- улучшится, взлёты покажутся вам более высокими, а падения -- менее низкими, относительно того, когда вы были пользователем. Всякий раз, когда вы будете думать о порно в течение следующих нескольких дней или до конца своей жизни, думайте:

***"УРААА! Я - НЕПОЛЬЗОВАТЕЛЬ!"***

## Последнее предупреждение

Ни один пользователь, если бы ему дали возможность вернуться в прошлое, до того как он попал в зависимость, с теми знаниями, которые у него есть сейчас, не стал бы и начинать. Десятки тысяч людей, успешно покончивших с привычкой, в течение многих лет ведут вполне счастливую жизнь, но потом снова попадают в ловушку. Я верю, что эта книга поможет вам сравнительно легко остановиться. Но имейте в виду, что пользователи, которые легко прекращают, так же легко начинают снова. **Не попадайтесь в эту ловушку.**

Независимо от того, как долго вы не употребляли порно и насколько уверены в том, что никогда больше не попадете на крючок, возьмите за правило на всю жизнь не смотреть порно ни по какой причине. Не поддавайтесь различного рода намекам и подтекстам в средствах массовой информации, помните, как они продвигают свой имидж "откровенности", вводя порно в мейнстрим, не зная, что порно и компульсивная мастурбация убивает отношения и чувство личного благополучия у колоссального количества мужчин и всё большего числа женщин.

Помните, что первый просмотр или визит ничего вам не даст. У вас не будет абстинентного синдрома, который можно было бы снять, и вы будете чувствовать себя ужасно. Всё, что он сделает, это запустит удовольствие от прилива дофамина в ваш разум и мозг, и маленький голосок в глубине вашего сознания будет говорить вам, что вы хотите ещё раз. Тогда у вас есть выбор: быть несчастным какое-то время или пройти через всю эту грязную цепочку событий снова.
