# Обратная связь

Война ведется не с пользователями, а против ловушки порноиндустрии, и она ведется по той простой причине, что мне нравится ее вести. Каждый раз, когда я слышу о освобождении пользователя из порно-рабства, я испытываю огромное удовольствие. Но это удовольствие не обошлось без значительных разочарований, вызванных в основном двумя категориями пользователей порно. Несмотря на предупреждение в предыдущей главе, я постоянно удивляюсь количеству тех, кто легко останавливается, но потом подсаживается и обнаруживает, что теперь уже не может бросить.

Это всё равно что найти человека, который по горло в болоте и вот-вот пойдет ко дну. Вы помогаете вытащить его, он благодарен, но через полгода вы снова находите его в болоте. Пользователи, которые легко останавливаются и начинают снова, представляют собой особую проблему, однако, когда вы освободитесь, пожалуйста, не повторяйте этой ошибки. Они считают, что такие люди начинают снова, потому что они всё ещё подсажены и им не хватает дофамина. На самом деле, им так легко остановиться, что они теряют страх перед порно. Они думают: "*Я могу позволить себе провести разовый сеанс, и даже если я снова подсяду, мне будет легко остановиться*".

Боюсь, что так не получится, потому что можно прекратить зависимость, но невозможно контролировать зависимость. Единственное, что необходимо для прекращения порнозависимости, -- это не использовать ее.

Люди обычно возвращаются к порнографии, потому что не понимают, что значит слово "легко" в EasyPeasy (easy - легко).

Представьте себе человека, сидящего на холодном бетонном полу промерзшей комнаты. На стене напротив него есть окно, шторы слегка приоткрыты, а за окном ясный весенний день -- деревья мягко покачиваются, щебечут птицы. А дверь не заперта.

Нужна ли сила воли, чтобы выбраться из этой морозной комнаты? Нет! Сбежать труднее, чем остаться? Конечно, нет! (Это даже немного приятнее, потому что вы согреетесь пока будете двигаться). Зачем кому-то в здравом уме помещать себя в такую ситуацию, причиняя себе месяцы или годы разочарования, если только он не был обманут?

EasyPeasy раздвигает шторы и показывает, что дверь не заперта, чтобы пользователь мог ясно видеть улицу и устранить **заблуждения** о том, насколько ужасным может быть внешний мир и насколько комфортно пользователю в комнате.

Другая категория пользователей, вызывающих недоумение, -- это те, кто слишком напуган, чтобы предпринять попытку остановиться, или же, когда они пытаются, считают, что это слишком трудно и возвращаются к зависимости. Основные трудности, которые возникают, заключаются в следующем:

**Страх перед неудачей.**

:   В неудаче нет ничего позорного, но не пытаться -- это просто глупость. Посмотрите на это с другой стороны: вы ни от чего не прячетесь. Самое худшее, что может случиться, это то, что вы потерпите неудачу, и в этом случае вам будет не хуже, чем сейчас. Просто подумайте, как прекрасно было бы добиться успеха. Но если вы не предпримете попытку, вы уже гарантировали себе провал.

**Страх быть несчастным и испытать боль.**

:   Не беспокойтесь об этом, просто подумайте: что ужасного может случиться с вами, если вы больше никогда не будете смотреть порно? Абсолютно ничего. Ужасные вещи *произойдут*, если вы продолжите использовать порно; перечитайте заметки о пари Паскаля. В любом случае, паника вызвана дофамином и скоро пройдет. Самое большое достижение -- избавиться от этого страха. Вы действительно верите, что пользователи согласны на вялые стояки, ненадежную сексуальную активность или иллюзорное удовольствие от порно? Если вас охватывает панический страх, вам поможет глубокое дыхание. Если вы находитесь с другими людьми, и они вас напрягают, убегите от них и уйдите в гараж, в пустой офис, ещё куда-нибудь.

    Если вам хочется плакать, не стыдитесь. Плач -- это природный способ снятия напряжения. Никто никогда не плакал, после этого не почувствовав себя лучше. Одна из ужасных вещей, которую мы делаем с молодыми людьми, -- это приучаем их не плакать. Вы можете видеть, как они пытаются сдержать слезы, но как при этом скрежещут их челюсти. Мы учим себя не показывать эмоции, но мы не должны держать их в себе. Кричать, орать или устроить истерику. Пните что-нибудь. Воспринимайте свою борьбу как боксерский поединок, который вы не можете проиграть. Никто не может остановить время, с каждым мгновением маленький монстр внутри вас умирает. Наслаждайтесь своей неизбежной победой.

**Несоблюдение инструкций.**

:   Это невероятно, но некоторые пользователи говорят, что метод не сработал для них. Затем они описывают, как проигнорировали не просто одну инструкцию, но практически все. Для наглядности в конце этой главы приведен контрольный список.

**Непонимание инструкций.**

:   Основными проблемами оказываются следующие:

    "*Я не могу перестать думать о порно.*"

    :   Конечно, не можете, а если попытаетесь, то создадите фобию и станете несчастным. Это как попытка заснуть в ночь перед важным днём: чем больше вы пытаетесь, тем труднее это сделать. Неважно, думаете ли вы о порно девяносто процентов своей жизни, важно то, что именно вы думаете. Если вы думаете: "*О боже, я обожаю смотреть порно*" или "*Когда же наконец я стану свободен?*", вы будете несчастны. Если же, каждый раз вспоминая о порно, вы думаете: " *Ура! Я свободен!*", вы будете счастливы.

    "*Когда умрет маленький порномонстр?*"

    :   Прилив дофамина очень быстро покидает организм, но невозможно сказать, когда ваше тело перестанет страдать от легкого физического ощущения отмены чрезмерного дофамина. Это пустое, неуверенное чувство идентично обычному голоду, депрессии или стрессу. Всё, что делает порно, -- усиливает это чувство. Именно поэтому пользователи, которые бросают, используя метод силы воли, никогда не уверены, действительно ли они бросили, даже после того, как их организм перестал испытывать дофаминовую ломку. Если они испытывают обычный голод или стресс, их мозг говорит им, что это веская причина, чтобы потребовать положенную порно-сессию. Суть в том, что не нужно ждать, пока тяга уйдет, поскольку она настолько незначительна, что мы даже не знаем, что она есть, а знаем её только как лёгкое ощущение позыва. Когда вы выходите от стоматолога, ждете ли вы, пока ваша челюсть перестанет болеть? Конечно, нет, вы продолжаете жить дальше. Даже если челюсть ещё болит, вы всё равно радуетесь.

        Не ждите, пока абстиненция пройдет, потому что вы создадите сомнения, постоянно задавая себе вопрос: "Как долго это будет продолжаться? Свободен ли я вообще, если я не чувствую никакой разницы?". Страх -- это реальная боль, поэтому ожидание улучшения жизни после прекращения использования порно порождает сомнения. Если вы  не боитесь, всё случится незаметно, а экспоненциальные улучшения в вашей неврологии происходят медленно, поэтому если вы ждёте,  изменений, вам будет казаться, что ничего не происходит, и это будет порождать сомнения.

    *"'Момент откровения' ещё не наступил."*

    :   Если вы будете ждать его, то просто вызовете ещё один страх. Однажды я продержался три недели на методе силы воли. Я разговаривал со старым другом и он спросил, как я справляюсь.
        "*Я продержался три недели*", ответил я. Он поинтересовался, "*Что значит 'продержался' три недели?*"
        Я уточнил, "*Я прожил три недели без порно.*"
        Он сказал, "*И что ты собираешься делать? Продержаться всю оставшуюся жизнь? Чего ты ждешь, ты уже сделал это. Ты уже непользователь.*"

        Я подумал, "*Он абсолютно прав, чего же я жду?*" К сожалению, из-за непонимания устройства ловушки, я вскоре снова попал в неё, но идею я уловил. Вы становитесь непользователем, в тот момент закрываете порносайт. Важно быть счастливым непользователем с этого момента.

    "*Мне всё ещё хочется порно.*"

    :   Тогда вы поступаете очень глупо. Как вы можете утверждать, что хотите быть непользователем, и при этом говорить, что вам хочется порно? Это противоречие. Если вы говорите, что хотите порно, вы говорите, что хотите быть пользователем. Непользователи не хотят посещать отвратительные сайты. Вы уже знаете, кем хотите быть, так что перестаньте себя наказывать.

    "*Я отказался от жизни.*"

    :   Почему? Всё, что вам нужно сделать, это перестать убивать себя и начать заряжаться энергией. Вам ни в коем случае не нужно прекращать жить. Всё очень просто: в течение следующих нескольких дней у вас будет небольшая травма. Ваше тело испытает почти незаметное обострение, когда вы перестанете ожидать всплеска дофамина. Имейте в виду: вам не хуже, чем было. Это то, от чего вы страдали всю свою жизнь, каждый раз, когда спали, в церкви, супермаркете или библиотеке. Это не беспокоило вас, пока вы были пользователем, и если вы не остановитесь, вы будете страдать от этого недомогания всю жизнь.

        Порно и оргазм не создают приятные моменты, они лишают вас их. Даже если ваше тело ещё жаждет дофамина, еда и общественные мероприятия прекрасны. Жизнь прекрасна -- посещайте общественные мероприятия, даже если там будут голые танцовщицы. Помните, что не вы лишены жизни, а пользователи. Каждый из них хотел бы оказаться на вашем месте, если бы только знал. Наслаждайтесь тем, что вы королева бала и центр внимания. Прекращение просмотра порнографии -- это прекрасный повод для разговора, вы получаете то, чего они не могут получить. Ваши друзья и сверстники будут удивлены, увидев, что вы, ранее застенчивый и усталый, теперь счастливы и веселы. Вы будете наслаждаться жизнью с самого начала; не нужно завидовать пикаперам на вечеринках, они будут завидовать вам -- ах, если бы они только знали.

    "*Я несчастен и раздражителен.*"

    :   Это неспособность следовать инструкции. Выясните, какой именно. Некоторые люди всё понимают и верят всему вышенаписанному, но все равно начинают с чувства обреченности и уныния, как будто происходит что-то ужасное. Вы делаете не только то, что вы хотите, но и то, чего хотят все пользователи на планете. При любом способе прекращения употребления бывший пользователь пытается достичь определенного настроя, поэтому каждая мысль, связанная с порно, сопровождается словами "*УРААА! Я СВОБОДЕН!*" Если это ваша цель, зачем ждать? Начните с этого настроя и никогда не теряйте его. Альтернативы нет..

    "*У меня была хорошая неделя / месяц / полгода, но я снова в ловушке.*"

    :   Помните, что страх -- это муки сами по себе. Поддавшись мукам, вы порождаете ещё больший страх, подпитывая ослабленного маленького монстра, который добивается успеха в запугивании непользователя. Человек думает, что он попался на крючок на всю жизнь. В действительности их заблуждения не изменились, но они приправили свой мыслительный процесс дофамином. Это по определению ошибка, с возможностью научиться на ней, но это неспособность следовать инструкциям. Поймите, какая это из перечисленных ниже, и радуйтесь.

## Чек-лист

Если вы будете следовать этим инструкциям, вы не сможете потерпеть неудачу:

1.  Дайте торжественную клятву, что вы никогда, никогда не будете заходить в интернет, чтобы посетить свой гарем *ИЛИ* довольствоваться статичными картинками *ИЛИ* примиритесь с рисованной эротикой *ИЛИ* со всем, что содержит сверхнормальные стимулы, и придерживайтесь своей клятвы.

2.  Проясните в своем сознании: Здесь абсолютно не от чего отказываться. И я не имею в виду, что вам станет лучше, если вы не будете заниматься ПМО (вы и без меня сами это знали), также я не имею в виду, то удовольствие или поддержку, которое вы якобы получали, занимаясь ПМО, поскольку если бы их не было, вы бы этого не делали, вы же не идиот. Основная мысль заключается в том, что ***в ПМО нет никакого подлинного удовольствия или поддержки***. Это просто иллюзия, как биться головой об стену, чтобы получить облегчение, когда вы сделаете перерыв.

3.  Не существует такого понятия, как доблестный любитель ПМО. Вы просто один из сотен миллионов людей, попавших в эту изощренную ловушку. Как и миллионы других бывших ПМОеров, которые когда-то думали, что не смогут выбраться, вы выбрались.

4.  Если бы в любой момент вашей жизни вы взвесили все "за" и "против" ПМО, то подавляющим выводом всегда было бы: "*Прекрати это делать. Ты дурак!*" И ничто и никогда этого не изменит. Так было всегда и так будет всегда. Приняв правильное решение, не мучайте себя сомнениями. Пари Паскаля идеально подходит к прекращению ПМО: здесь нет возможности проиграть, высокие шансы на выигрыш и высокие шансы избежать потерь.

5.  Не пытайтесь не думать о порнографии и не беспокойтесь о том, что вы можете постоянно думать о ней. Всякий раз, когда вы думаете об этом, сегодня, завтра или всю оставшуюся жизнь, думайте: "УРА! Я НЕ ПМОЕР"**

6.  **Не используйте** никаких заменителей. **Не бросайте себе вызов**, держа ноутбук рядом с собой во время отхода ко сну. **Не избегайте** спектаклей, фильмов или журналов. **Не меняйте** свой образ жизни только потому, что вы бросили. Если вы будете следовать вышеперечисленным инструкциям, то вскоре вы испытаете 'момент откровения', но:

7.  Не ждите, что 'момент откровения' вообще наступит. Просто продолжайте жить, наслаждаясь взлётами и справляясь с падениями. Вы увидите, что этот момент наступит очень быстро.
