# Помогите людям на тонущем корабле

Пользователи порнографии сегодня в панике, ощущая изменения в восприятии интернет-порно мужчинами и женщинами. Всё чаще изучается аддиктивная природа интернет-порно, которое теперь справедливо считается отличным от старой порнографии. Легкость и доступность вызывают тревогу даже в сердцах сторонников порнографии. Они также чувствуют, что их крестовый поход за свободу слова и мысли пытаются захватить различные элементы. Дикий Запад неконтролируемого Интернета делает практически невозможным введение возрастных ограничений на сверхнормативные стимулы. К сожалению, в ближайшее время этому не будет положен конец, но сотни тысяч пользователей останавливаются, причем большинство зависимых знают об исследованиях, показывающих сходство между порнографией и наркоманией. Каждый раз, когда пользователь, становясь непользователем, покидает тонущий корабль, оставшиеся на нем чувствуют себя всё более несчастными.

Каждый пользователь инстинктивно знает, что нелепо заниматься самосаботажем и проводить время перед двухмерными пикселями, сверхнапрягая свой мозг и в процессе развивая нейронные пути, которые гарантируют плохую сексуальную жизнь. Если вы всё ещё не считаете это глупостью, попробуйте заговорить с порножурналом, который продаётся в центре вашего города, и задумайтесь, в чём дело? Только в одном. Вы не сможете получить удовольствие, тепла и близости с картинкой. Если вы можете не покупать алкоголь и сигареты, когда вы ходите за продуктами, вы определенно можете перестать посещать свой онлайн-гарем. Пользователи не могут найти рациональных причин для просмотра порно, но они не чувствуют себя так уж глупо, поскольку другие люди такие.

Пользователи откровенно лгут о своей привычке, причем не только исследователям и окружающим, но и самим себе. Им приходится это делать -- промывание мозгов необходимо для того, чтобы сохранить хоть какое-то самоуважение. Они чувствуют необходимость оправдывать свою "привычку" не только перед *собой*, но и перед другими. Они постоянно рекламируют иллюзорные преимущества порно с помощью более изысканных средств.

Если пользователь прекращает употребление, используя метод силы воли, он все равно чувствует себя обделенным, и начинает жаловаться. Это лишь подтверждает другим пользователям, что они поступают правильно, продолжая употреблять. Если бывшему потребителю удается избавиться от привычки, он благодарен за то, что ему больше не нужно заниматься самосаботажем и тратить энергию, и ему не нужно оправдывать себя. Помните, что именно страх заставляет пользователя прятать голову в песок, сомневаясь в своем поведении только тогда, когда он бросил. Помогите пользователю, устранив эти страхи. Расскажите им, как здорово не жить в тюрьме, как прекрасно просыпаться утром в хорошей физической форме и здоровым, а не с недостатком энергии и ненавистью к себе, как замечательно освободиться от рабства, наслаждаться жизнью и избавиться от этих черных теней. А ещё лучше -- пусть они прочитают эту книгу.

Очень важно не принижать женатого пользователя или в отношениях, указывая ему на то, что он намеренно разрушает свои отношения или что это в некотором роде измена или нечистоплотность. Существует распространенное заблуждение, что бывший пользователь чаще упрекает всех в этом аспекте. Это представление имеет под собой некоторую основу, но в основном оно связано с волевым методом прекращения использования порно. Потому что бывший потребитель, хотя и избавился от привычки, все ещё сохраняет часть "промывания мозгов" и считает, что принес себя в жертву. Они чувствуют себя уязвлёнными, и их естественным защитным механизмом является нападение на других пользователей порнографии.

Это может поднять самолюбие бывшего пользователя, но ничем не поможет ему. Всё, чего можно добиться от пользователя упрёками, -- это припиреть его спиной к стене, заставляя чувствовать себя ещё более несчастным и, соответственно, ещё сильнее испытывать иллюзию потребности в порно. Хотя изменение отношения медицинской общественности к интернет-порно является основной причиной того, почему многие пользователи бросают, это не облегчает им задачу. На самом же деле, это значительно усложняет задачу. Большинство пользователей в настоящее время считают, что они прекращают употреблять порно по состоянию здоровья. Это не совсем так.

Хотя огромная опасность для здоровья, очевидно, является главной причиной отказа от порнографии, пользователи годами саботируют свою мужественность, но и это не имеет ни малейшего значения. Основная причина, по которой пользователи прекращают употреблять порно, заключается в том, что общество начинает видеть в порно то, чем оно является: наркотическую зависимость. Отношение общества постепенно меняется: многие партнеры теперь будут задавать вам вопросы, если вы сидите с ноутбуком до полуночи.

Полный запрет на порно в некоторых странах или недоступность интернета -- классические примеры дилеммы путешествующего пользователя. Как правило, они считают, что это поможет сократить потребление. В результате вместо одного или двух дней, от которых они обычно не были бы в восторге, они воздерживаются целую неделю. Однако во время этого вынужденного периода воздержания они не только испытывают душевное страдание в ожидании вознаграждения, но и их тело тоже жаждет. О, каким ценным кажется им посещение онлайн-гарема, когда они в конце концов получают возможность.

Насильственное воздержание не сокращает потребление, потому что пользователь только ещё больше потакает себе, когда ему наконец удаётся побыть одному. Всё, что это даёт, -- это закрепляет в сознании пользователя, насколько ценно порно в Интернете и насколько он зависим от него. Самым коварным аспектом этого принудительного воздержания является его влияние на подростков. Мы позволяем этим злоумышленникам "свободы выражения" (производителям порнографии) нацеливаться на несчастных подростков, чтобы подсадить их на порнографию. Затем, в самый стрессовый период жизни подростков, когда, по их заблуждениям и неосведомлённости, они больше всего нуждаются в порно, мы шантажом заставляем их отказаться от порно из-за вреда, который они причиняют себе.

Многие не в силах бросить сами, их принуждают не смотреть, не по своей вине они страдают от комплекса вины до конца жизни. Но многие успешно и с удовольствием всё же смотрят порнографию, думая: *\"Ладно. Я это только на время, а после того, как всё закончится, я всё равно вылечусь.\"* Затем наступают боль и страх перед выбором профессии и другие взрослые трудности, за которыми следует самый большой "кайф" их жизни -- поиск работы. Боль и страх позади, теперь они чувствуют себя в безопасности, и снова срабатывает старый спусковой механизм. Часть промывки мозгов всё ещё присутствует, и прежде чем запах нового рабочего ноутбука улетучивается, пользователь оказывается на пороге своего любимого онлайн-гарема. Ликование от этого события блокирует неприятные предчувствия в их сознании, они не намерены снова попасться на крючок, но один взгляд не повредит\... Слишком поздно! Они уже снова на крючке.

Старое страстное стремление к маленькому чудовищу начнется снова, и даже если они не подсядут сразу же, после-кáйфовая депрессия, вероятно, настигнет их. Странно, что, хотя героиновые наркоманы являются преступниками по закону, реакция общества -- помощь этим людям. Давайте примем такое же отношение к бедным пользователям порнографии. Они делают это не потому, что хотят, а потому, что считают, что им это нужно. В отличие от героинового наркомана, они обычно страдают многие годы от психических и физических мучений. Мы всегда говорим, что быстрая смерть лучше медленной, так что не завидуйте бедным пользователям порно. ***Они заслуживают вашей жалости.***
