# Советы непользователям

## Пусть ваши друзья, использующие порнографию, прочитают эту книгу

Для начала изучите содержание этой книги и постарайтесь поставить себя на место пользователя. Не заставляйте их читать эту книгу, говоря им, что они губят свое здоровье или играют с огнем. Они и без вас это знают. Пользователи продолжают смотреть порно не потому, что им это нравится или потому, что они этого хотят, но они убеждают себя и других людей только для того, чтобы сохранить самоуважение. Они делают это, потому что зависимы от порно, потому что думают, что оно расслабляет их, придает им смелости или уверенности (удовольствие или поддержка), и потому что чувствуют, что жизнь никогда не будет приятной без "секса" - по крайней мере, в их варианте "секса". Если вы попытаетесь заставить пользователя остановиться, он будет чувствовать себя как загнанный в ловушку зверь и ещё больше захочет оставить себе свой гарем. Это может превратить их в тайных пользователей, и порно станет ещё более ценным в их сознании.

Вместо этого сосредоточьтесь на другой стороне медали. Дайте им пообщаться с бывшими пользователями (блоги, форумы, YBOP, NoFap и т.д., но остерегайтесь пропаганды метода силы воли). Дайте им послушать/почитать пользователя, который думал, что попался на крючок на всю жизнь, и насколько лучше жизнь без порно. Как только вы убедите их в том, что они могут остановиться, их разум начнет открываться этой возможности. Затем начните объяснять заблуждение, вызванное синдромом отмены. Мало того, что "допаминовые приливы" не дают им бодрости, они разрушают их уверенность в себе и делают их раздражительными и усталыми.

Теперь они должны быть готовы сами прочитать эту книгу, ожидая прочесть страницы историй о ненадежном либидо, вялом стояке, PIED, PE и т.д. Объясните, что этот подход совершенно иной, и упоминания о болезнях составляют ничтожно малую часть материала.

Короче говоря, не дайте этому труду умереть в забытье. Расскажите своим друзьям, но не ведите себя странно. Если вы попытаетесь задавить их в разговоре или устроить дебаты, вы только добьетесь их отрешённости и ещё больше усилите их страхи.

## Следует ли мне рассказать об этом своей второй половинке?

Должен ли я рассказать жене, подруге или партнеру о своей привычке? (Цель -- таким образом помочь вам бросить порно). Здесь действуют несколько факторов.

Если вам не удается бросить порно с помощью метода силы воли, а вы уже рассказали об этом своему партнеру, расскажите ему о своем новом подходе и позвольте ему самостоятельно ознакомиться с книгой. Они смогут помочь и мотивировать вас в период выхода из зависимости и станут опорой, когда маленький монстр попытается поставить вам подножку.

Если вы только недавно узнали о существовании порноловушки и не пытались бросить в прошлом, сначала воспользуйтесь EasyPeasy самостоятельно. Как объяснялось ранее, это должен быть приятный опыт.

Если вы наслаждаетесь освобождением, вы решительны и не находите его трудным, нет особых причин сообщать об этом партнеру. Если вы раньше не говорили о своей проблеме, то не стоит и сейчас, пусть она канет в небытие. Однако будьте готовы, если ваш партнер удивится, что вы выглядите, работаете и чувствуете себя лучше!

## Мой партнер бросает порнографию

Порнография -- это извращенный разрушитель отношений, и хотя бросить порнографию можно мгновенно, на исцеление требуется время. Многие пользователи, в силу иррациональных убеждений, порожденных их зависимостью, вымещают свой гнев на партнерах и близких. Такое поведение проявляется в газлайтинге, лжи и манипулятивном поведении. Это характерно не для всех пользователей, но такое всё чаще встречается на поздних стадиях зависимости. Хотя эти формы поведения могли проявиться из-за причины лежащей в их основе порнозависимости, важно просветить себя относительно этих форм поведения и, если они будут выявлены, обратиться к психотерапевту, специализирующемуся на сексуальных зависимостях.

Если ваш партнер находится в периоде абстиненции, считайте, что он страдает, независимо от того, так это или нет. Не пытайтесь преуменьшить его страдания, говоря ему, что остановиться легко, что он может сказать себе это сам. Вместо этого продолжайте говорить, как вы гордитесь им, насколько лучше он выглядят, насколько приятнее быть с ним и насколько легче с ним в целом. Особенно важно продолжать это делать, потому что, когда пользователь делает попытку остановиться, эйфория от этой попытки и похвала, которую он получает от близких, могут помочь ему в этом. Однако они склонны быстро забывать, поэтому продолжайте хвалить их.

Если они не говорят о порнографии, вы можете подумать, что они забыли и не хотят, чтобы вы им напоминали. Обычно при использовании метода силы воли происходит совершенно обратное, так как бывший пользователь, как правило, одержим только этим. Поэтому не бойтесь поднимать эту тему и продолжайте хвалить их (они сами скажут вам, если не хотят, чтобы им напоминали).

Сделайте все возможное, чтобы избавить их от давления в период абстиненции, думайте о том, как сделать их жизнь интересной и приятной. Это также может быть трудным периодом для тех, кто не использовал порно и никогда не сталкивался с этой зависимостью. Если один из членов группы раздражителен, это может привести к общему несчастью. Поэтому предвидите это, если бывший пользователь чувствует раздражение, он может выместить его на вас, но не мстите ему, в это время он больше всего нуждается в вашей похвале и сочувствии. Если вы сами чувствуете раздражение, что вполне понятно, постарайтесь не показывать этого.

Один из приемов, на которые идут наркоманы, пытаясь бросить наркотики с помощью метода силы воли, -- закатывание истерик в надежде, что их партнер или друзья скажут: *"Мне невыносимо видеть, как ты так страдаешь. Ради всего святого, просто прими свой яд"*. Таким образом, пользователю не нужно терять лицо, поскольку "сдается" не сам, а получает указание извне. Если бывший пользователь (даже неосознанно) прибегает к этой уловке, ни в коем случае не поощряйте его к рецидиву. Вместо этого скажите: *"Если это то, что порно делает с тобой, слава богу, ты скоро освободишься. Как замечательно, что у тебя хватило мужества бросить это"*.

Помните, что в процессе выздоровления участвуют две стороны. Когда ваш партнер отказывается от порнографии, важно предоставить ему поддержку, принципы ухода и границы. Этот процесс не произойдёт моментально, он требует доверия, общения и ответственности. В этом процессе помогут ведение дневника, развитие собственных увлечений и, самое главное, терапия.

## Соскальзывание (рецидив)

Этот раздел должен послужить предупреждением для тех, кто покидает ловушку. Лично я никогда не рецидивировал, но для иллюстрации я буду использовать опыт интервью с членами сообщества и инструменты когнитивно-поведенческой терапии.

Во-первых, называть это рецидивом непродуктивно. Едиснтвенное, что произошло, это, что вы сорвались и накормили маленького монстра, который, в свою очередь, запустил работу большого монстра промывания мозгов. Пользователи, которые сорвались (что в целом является возможностью научиться на своей ошибке), обычно порождают целый ряд иррациональных убеждений:

  - "*Я никогда не буду свободным"*" -- **Чрезмерная драматизация**
  - "*Я должен/должна заниматься спортом, учиться и быть плодотворной каждый день своей жизни*"
  - "*Сегодня я занимался ПМО, так что какой смысл читать все книги и форумы... Моей целью было просто не заниматься М (мастурбацией), но вот он я -- неудачник -- у меня рецидив.*" -- **Низкая устойчивость к неудачам**
  - "*Мои друзья / читатели форума / другие люди обходятся без ПМО в течение (n) дней, но я не могу, поэтому я безнадежный случай. Вчера я чувствовал себя хорошо, так как усердно учился и плодотворно работал, но сегодня я этого не делал... Я иду по наклонной.*" - **Сравнивание себя с другими**
  - "У меня не должно быть сексуальных мыслей" -- Эти люди сами, или их родители, или общество установили **,как правильно думать** о сексе. Спросите себя, помогает ли вам самобичевание в достижении ваших целей, и если да, то получаете ли вы удовольствие от такого путешествия?

Факторы, которые приводят к промыванию мозгов каждого отдельного пользователя, могут казаться бесконечными. Вы знаете себя лучше, чем кто-либо другой, но очевидно, что вы не можете следовать инструкциям. Вы почему-то всё ещё видите ценность в порнографии, но как?

Что часто упускается из виду, так это то, что требуется время, чтобы обратить промывание мозгов вспять. Это не делает всё труднее, но почти в каждой отрасли используется секс, а активное противодействие промыванию мозгов -- процесс сознательный (по крайней мере, по началу), может потребоваться время, чтобы полностью закрепить понимания, полученные в этой книге. Поэтому рекомендуется многократное прочтение (после первого прочтения вы можете перечитывать только те главы, с которыми у вас возникли трудности), это не займёт много времени.

Удивительно, но довольно часто религиозные пользователи, выходящие из ловушки, хотят, чтобы им, в качестве искупления, было немного больно. Им кажется, что бросить легко, а потом они чувствуют себя виноватыми за то, что бросить было настолько легко, но они не сделали этого раньше. Но зачем заниматься самосаботажем и усложнять себе жизнь? Маленький монстр очень коварен и в этом отношении.

Дистанцируйтесь от маленького монстра -- вам его когда-то давно вживила порноиндустрия. Представьте себе хулигана, закатывающего истерику на школьном дворе. Что вы ему скажете? Если вы уступите, вы только усилите его позицию. Те, кто сдаются, в конечном итоге кормят хулигана и тем самым усиливают его промывание мозгов, но их представление о ловушке не изменилось. Возьмите себя в руки, выясните, где вы ошиблись, и наслаждайтесь свободой!

Вы -- не ваши позывы. Медитация осознанности -- это практика отслеживать и отмечать мысли, с ней можно узнать фундаментальные вещи о природе ума. Настоятельно рекомендуется заниматься медитацией в целом, и она также полностью совместима с религиозной практикой. Вы не можете бороться ни с собой, ни с маленьким чудовищем. Вы должны безоговорочно полюбить себя и процесс.

Но исключите неудачу из своего сознания. Вот фрагмент из книги Гуллиако "*Медитации порнозависимого*" (ссылка в разделе "Источники" в конце книги):

> Поскольку просмотр порно дает вам ноль преимуществ, это то, что только вредит вам, и крайне нелепо хотеть делать что-то подобное, я сравниваю это с питьем отбеливателя. Вот так:
>
> **Трудный путь отказа от употребления отбеливателя.**
>
> Привет! Мы - NoBleach, и мы проводим челленджи по перезагрузке, в которых участники ("Bleachstronauts") воздерживаются от употребления отбеливателя в течение определенного периода времени. Если ваша цель -- обычное участие в испытании длиной в месяц в качестве проверки самоконтроля, или если чрезмерное употребление отбеливателя стало проблемой в вашей жизни, и вы хотите отказаться от него на более длительный срок, вы найдете здесь сообщество поддержки и множество ресурсов.
>
> - “*Иногда я позволяю себе выпить один или другой стакан отбеливателя. Я знаю, что идея "одну только капельку" -- это самообман, но всё же, разве один мерный стаканчик повредит? Это не может уничтожить весь мой прогресс, который я сделал, пока не употреблял отбеливатель.*”
> - “*У меня нет проблем с тем, чтобы перестать пить отбеливатель, но иногда я иду по улице и вижу, как кто-то пьет воду, и знаете, я представляю, что в стакане отбеливатель. Затем у меня появляется желание, и, после непродолжительных дебатов с собой, стоит ли мне это делать, я наконец сдаюсь, и на ночь выпиваю стакан отбеливателя.*”
> - “*Слушай, моя проблема в том, что иногда, когда я остаюсь один на своей кухне, я начинаю рассматривать стаканы, изредка я искушаю себя, я открываю контейнер, в котором храню отбеливатель, и нюхаю запах и... В итоге я возвращаюсь к тому, с чего начинал. Я так отчаянно хочу прекратить это, но я не уверен, смогу ли я когда-нибудь остановиться.*”
> - “*Перестать пить отбеливатель невозможно, я имею в виду, что у меня же есть рот, понимаете? Как я должен остановиться, если у меня всегда будет горло, которое напоминает мне, что я могу проглотить отбеливатель?*”
> - “*Вот блин, всё шло так хорошо, целых 19 дней без отбеливателя. Главное -- учиться на неудачах! Теперь я знаю, чего не делать: не нужно смотреть на чистящие средства в супермаркете, они напоминают об отбеливателе. Постараюсь протянуть месяц! Я обнуляю свой счетчик. Пожелайте мне удачи!*”

> Если у тебя есть тяга к отбеливателю, успокойся, чувак! Вспомни, что написано в хакбуке EasyPeasy:
>
> “*Отбеливатель" очень трудно бросить из-за страха, что нас лишают удовольствия или опоры. Страх, что некоторые приятные ситуации уже никогда не будут такими приятными, как прежде. Страх, что мы не сможем справляться со стрессовыми ситуациями. Другими словами, это последствия промывания мозгов, заставляющие нас верить, что что покупка отбеливателя и, соответственно, его употребление является обязательным. Более того, это убеждение, что в дешёвом отбеливателе есть что-то, что нам необходимо, и что когда мы перестанем его использовать, мы будем отказывать себе и создавать пустоту. Уясните это для себя: Отбеливатель не заполняет пустоту, а создает ее!*”
> 
> Тогда я говорю:
> “*Предположим, вас заставили в течение пяти минут смотреть на стакан, наполненный отбеливателем. Постарайтесь вспомнить одну из тех марок или запахов, которые вам так нравились. Может быть, это сопровождается каким-то звуком или вы помните только отдельные детали. Отбеливатель находится там, а вы не можете закрыть глаза или отвернуться, потому что этот самый отбеливатель находится в вашем сознании, это воспоминание хранится в вас.*
>
> *Чувствуете ли вы тягу? Чувствуете ли вы что-нибудь на языке или какие-либо изменения в дыхании? Каковы ваши чувства от того, что вам вспоминается? Определите их, отбеливатель очерняет вашу жизнь, он хочет запутать вас и заставить отдавать внимание тому, что пытается завладеть вами.*”
>
> Вышеизложенным я не пытаюсь отвергнуть ваши чувства, и уж тем более не хочу сказать что-то вроде "хаха я умный, а ты такой тупой", а хочу дать вам перспективу, чтобы вы поняли, насколько всё до смешного легко (и всегда будет), насколько просто преодолеть эту зависимость.
> Просмотр порно не похож на переключатель "вкл/выкл", когда вы говорите: "О, хорошо, я в ситуации X, тогда я посмотрю порно". Вымысел! Враньё! Как часто вы позволяете себе выпить стакан отбеливателя? Никогда? Почему? Потому что это ужасно, вот почему! Как вы собираетесь избавиться от своей зависимости, если вы не понимаете, что ПМО -- это ужасная вещь, которую вы делаете с собой?

## А как насчет МО (мастурбация, оргазм)?

Люди дрочат уже много веков без проблем. Для ясности: проблема заключается в порнографии.

Тем не менее, вы всё равно можете подсесть на МО по тем же причинам, что и на порно, например, из-за мышления "мне необходимо получать оргазм", психического обострения, принуждения тела к сексу и просто гедонистического стремления к удовольствию.

Вполне вероятно, что порнография и мастурбация тесно переплелись в вашем сознании. Многие пользователи обнаруживают, что в результате мастурбации, вызванной порнографическими фантазиями, у них случаются рецидивы. По мере перенастройки вашего мозга, вы обнаружите, что это "промывание мозгов" в конечном итоге исчезнет, но лучше всего на некоторое время сделать перерыв в М и О. Чтобы ускорить этот процесс, попробуйте найти реальный секс, это тоже может помочь.

Это не инструкция, тут решайте сами, но по отзывам, польза от сохранения спермы многочисленна -- повышенная концентрация внимания и энергии, устранение "тумана в голове" и повышение уверенности в себе, а также множество других преимуществ. Из личного опыта могу сказать, что разница очевидна, и всё зависит от того, как вы сублимируете эту возросшую энергию.

Размышляя (без строгих научных фактов) можно предположить, что преимущества могут быть обусловлены несколькими факторами.

- После оргазма мозг выделяет пролактин, который подавляет высвобождение дофамина и выработку тестостерона.

- Отсутствие затопления мозга сверхдозами дофамина позволяет получать большее количество дофамина просто от повседневной жизни.

- Cперма реабсорбируется в кровь через ~78 дней (~75 из которых происходит сам сперматогенез) и является одним из лучших питательных веществ, которые может получить ваш организм.

- Сублимация сексуальной энергии в продуктивные привычки приводит к повышению производительности.

Возможно, вы захотите заниматься сексом и без оргазма, что, как уже говорилось, является прекрасным сексуальным опытом (часто называемым "Karezza"). Вы можете укрепить свою способность к этому, практикуя упражнения Кегеля. Из личного опыта могу сказать, что самый простой и эффективный способ воздействия на эту мышцу -- это остановка и задержка мочи во время мочеиспускания (хотя будьте осторожны и не переусердствуйте, это может вызвать другие проблемы). Разделение тантрической и детородной сторон секса -- один из многих бонусов выхода из ловушки ПМО (и моим партнерам это тоже нравилось!).

## Отклонения от стандартных рекомендаций

Этот раздел является новым и написан с некоторой опаской; тем не менее, он должен быть упомянут.

Некоторые люди, использующие EasyPeasy, обнаруживают, что их желание смотреть порно настолько уменьшается, что они не могут заставить себя провести последний сеанс. **Это нормально**, но не стоит недооценивать силу последнего сеанса. Осознанный последний просматр и закрепление того, насколько сильно вам не нравится ПМО, может быть действительно мощным средством. Лично я нашел это действительно полезным и был счастлив вымыть руки после этого, испытывая искреннее облегчение от того, что мне больше никогда не придется этого делать. Однако, ваш путь может отличаться.

Если вы уже давно освободились от ловушки маленького монстра и только что избавились от промывания мозгов, нет необходимости кормить маленького монстра ещё раз, так как он будет просто зря изводить вас. Наслаждайтесь свободой!

## Помогите положить конец этому скандалу

Интернет-порно -- одна из опасностей свободного общества, опирающаяся на благие намерения защитников личной свободы. Несомненно, основа цивилизации, причина, по которой человеческий вид продвинулся так далеко, заключается в том, что мы способны передавать наши знания и опыт не только друг другу, но и будущим поколениям. Даже животные считают необходимым учить своё потомство избегать жизненных ловушек.

Производители порнографии делают то, что они делают, не из лучших побуждений, что так они помогают человечеству. Особенно сейчас, когда зависимость от интернет-порно широко изучена. Возможно, когда-то на начальных этапах люди искренне верили, что порно обучает людей основам интимной жизни, но власть имущие знают, что это заблуждение. Ни один порносайт не делает заявлений о своей образовательности. Единственное, что обещают, -- это шок, новизну и эскалацию их контента.

Просто потрясающее лицемерие: как общество, мы сильно обеспокоены школьными издевательствами и объективизации человеческого тела. По сравнению с интернет-порно эти проблемы -- просто незначительны. Число людей, страдающих порнозависимостью, интенсивно проводящих время с воображаемыми и иллюзорными пиксельными людьми за счет своего здоровья, мужественности, энергии и времени, ежегодно становится больше и больше. Это, безусловно, самый большой убийца отношений, и жизни сотен тысяч людей разрушаются каждый год из-за того, что они попадают на крючок. Производители интернет-порно не размещают рекламу в основных изданиях -- им это не нужно, наши биологические потребности приводят нас к порогам их хорошо укомплектованных гаремов, как наркодилеры, распространяющие бесплатные образцы. В настоящее время порносайты не только выставляют свои товары, но и поощряют посетителей размещать контент.

Как умно, что порнокомпании показывают предупреждения 18+ в качестве сдерживающего фактора для несовершеннолетних пользователей, хотя некоторые даже не утруждают себя и этим. Интернет-порно затрагивает всех в любом возрасте. "*Мы предупреждали вас об опасности, так что это ваш выбор*", -- такова их позиция. Принимают ли они какие-либо меры для проверки возраста? Нет, это оттолкнуло бы их клиентов. Конечно, если проверка возраста будет введена на законодательном уровне, они просто найдут другую страну для работы. Или они заплатят какой-нибудь "элите", чтобы та продавила в массы мнение, что запрет приведёт к подпольному производству и созданию мафии? Но тогда вопрос, почему отмена сухого закона не привела к снижению числа жертв, связанных с алкоголем? Также под вопросом неспособность правоохранительных органов контролировать рост мафии.

Мы можем решить эту проблему по-другому, просвещая молодое поколение. Если они могут обходить сигареты и алкоголь при покупке, они могут сделать то же самое с интернет-порно. Мы уже наблюдаем такие сдвиги в обществе, как мемы "No Nut November" и "Coomer", которые становятся мейнстримом. У пользователя, как и у героинового наркомана, нет выбора. Пользователи не решают стать зависимыми, их заманивают в хитрую ловушку. Если бы у них был выбор, то завтра утром единственными потребителями были бы подростки, только начинающие употребление, считающие, что они могут остановиться в любой момент, если захотят.

К чему эти фальшивые стандарты? Почему героиновых наркоманов считают преступниками, но при этом они могут зарегистрироваться как наркоманы и получать метадон и надлежащее медицинское лечение, чтобы бросить наркотик? Попробуйте зарегистрироваться как порнозависимый -- если вы обратитесь к врачу за помощью, он либо скажет вам: "Перестаньте делать это так часто, попробуйте умеренность", что, как вы уже знаете, не сработает, или выпишут лекарства от вашей "депрессии". Ещё хуже совет найти настоящих партнеров -- серьезно? Неужели они никогда не слышали о пользователях, для которых порно интереснее партнёра и которые делают это за спиной партнера? Некоторые люди просто не понимают проблемы.

Кампании устрашения не помогают пользователям остановиться, они только усложняют задачу. Они пугают пользователей, что вызывает у них ещё большее желание смотреть. Они также не препятствуют тому, чтобы подростки попадали на крючок. Подростки знают, что порно убивает их либидо, но они также знают, что одним просмотром дело не ограничится. Поскольку зависимость настолько распространена, рано или поздно подросток -- либо из-за социального давления, либо из-за любопытства -- пробует в первый раз. А бесплатном порно есть всякие ролики, и вполне вероятно, они подсядут.

Почему мы позволяем этому скандалу продолжаться? Почему правительства не проводят соответствующих кампаний? Почему нам не говорят, что интернет-порно -- это наркотик и убийственный яд, что оно не расслабляет и не придает уверенности, а разрушает нервы, и что достаточно одного раза, чтобы попасть на крючок? Почему они не могут обеспечить проверку возраста, запрашивая зарегистрированные кредитные карты, возможно, у третьей стороны? Компания MindGeek, владелец многих крупных порносайтов, пытается обманом заставить правительства использовать их собственное решение по проверке возраста -- не позволяйте им этого делать! 

В романе Уэллса "Машина времени" описывается случай в далеком будущем, когда человек падает в реку. Его спутники просто сидят, как скот, на берегу, не обращая внимания на крики товарища. Бесчеловечно и тревожно, как и всеобщее безразличие общества к кризису порнографии.

Но в обществе дует ветер перемен. Снежный ком начал скатываться с холма, и есть надежда, что эта книга поможет превратить его в лавину. Вы тоже можете помочь, распространяя эту идею.

В связи с этим просьба -- если вы видите, что кто-то борется, используя силу воли, или пытается бросить порно, любезно направьте его к этому методу. Однако настоящая задача состоит в том, чтобы изменить отношение к порнографии в целом. Пожалуйста, подумайте о том, чтобы взять за правило, если вы видите в Интернете или даже на собственном опыте сталкиваетесь с нормализацией порнографии, с *уважением* просвещать и освобождать их.

Иногда вы можете получить негативную реакцию, но иногда одной вашей точной фразы достаточно. Как и многие до вас, вы можете ожидать отзывов от благодарных людей, благодарящих вас за свободу.

## Последнее предупреждение

Теперь вы можете наслаждаться остатком жизни как счастливый непользователь. Для того чтобы убедиться в этом, вам необходимо следовать простым инструкциям.

1.  Сохраните следующую страницу в закладках и обращайтесь к ней по мере необходимости.

2.  Если вы когда-нибудь начнете завидовать другому пользователю, поймите, что это он завидует вам. Вы не обделены. А вот они -- да.

3.  Помните, что вам не нравилось быть пользователем. Вот почему вы перестали. Вам нравится быть непользователем.

4.  Помните, что не бывает единственного раза.

5.  Никогда не сомневайтесь в своем решении больше никогда не смотреть порно. Вы знаете, что оно правильное.

6.  Если у вас возникли серьёзные трудности, найдите психотерапевта, разбирающегося в интернет-порно, и обратитесь к нему. Их можно найти в Интернете.
