# Инструкции

1.  Следуйте всем инструкциям.

2.  Будьте открыты.

3.  Начните с чувства восторга.

4.  Игнорируйте все советы и влияние, которые противоречат EasyPeasy.

5.  Сопротивляйтесь любым обещаниям временного решения проблемы.

6.  Чётко и ясно поймите: порно не приносит истинного удовольствия или поддержки, прекращая вы ничем не жертвуете. Вам не от чего отказываться и нет причин чувствовать себя обделенным.

7.  Ничего ждите, бросайте прямо сейчас!

8.  Примите решение никогда больше не смотреть порно и не сомневайтесь в нем.

9.  Помните, что не бывает только одного раза.

10. Больше никогда не смотрите порно.

## Аффирмации

-   Я свободен от рабства порнографии.

-   Мне легко игнорировать мысли о порнографии.

-   Прощайте мысли, прощайте порывы. Вот и уходят мои страстные желания.

-   Я фокусирую свой подсознательный ум на преодолении порнозависимости.

-   Порно крадет мое время, энергию и жизненные силы.

-   С каждым днем победить порнографию становится всё легче во всех аспектах.

-   Я наслаждаюсь и ценю свой образ жизни без порнографии, сильный, счастливый, легкий и непринужденный.

-   Когда я оглядываюсь назад и думаю о своих успехах, это доставляет мне огромную радость и гордость за себя.

-   Каждый раз, когда я вижу других потребителей порнографии, у меня появляется больше мотивации, чтобы самому разорвать эту цепь.

-   Вся накопившаяся энергия исцеляет мое тело и разум. Затем я могу выполнять более продуктивную и сложную работу, направленную на достижение моих ценностей и целей.

-   Мой мозг возвращается в здоровое состояние, тренируется благодаря тому, что я *не* делаю того, что делал раньше.

-   Теперь вся эта сдерживаемая ранее сила воли идёт на то, чтобы справиться с легковесными стрессами и вызовами жизни.

-   Отлично, я свободен, я больше не раб!
