# Habka Fudud

Ujeedada buugaan waa inuu ku siiyo maskax cusub. Si ka duwan habka joojinta oo caadiga ah - halkaas oo aad ka bilowdo adigoo dareemayso inaad fuulayso Mount Everest oo aad ku qaadato dhowrka toddobaad oo soo socda ee damaca porn iyo dareenka wax-la'aannimada - habkaan wuxuu kugu bilaabaa dareen farxadeed, sida haddii lagaa daaweeyay cudur xun. Inta wixii ka dambeeya, intaad nolosha sii marayso, waxaad dib u eegi doontaa muddadaan adigoo la yaaban sida oo aad weligaaga porn u isticmaashay markii hore. Waxaad ka xumaan doontaa isticmaalayaasha porn halkii oo aad ka maseeri lahayd.

Haddii aadan ahayn qof oo balwad lahayn (kuwa oo lamaanayaashooda dartooda u akhrinayaan), qof oo mar hore joojiiyay isticmaalka porn (ama qof oo ku jira muddada ka-hortagga inta lagu jiro "porn-qaadashada la nidaamay"), waxaa lagma maarmaan ah in la sii waddo isticmaalka porn ilaa aad si buuxda u dhammayso akhrinta buuga. Tani waxay u muuqan kartaa inay tahay mid oo iska hor imaanaysa, iyo tilmaantaan in siigaysashada la sii wado waxay keentaa diidmada ugu badan ee akhristayaasha, laakin markaad sii akhriso, damacaaga inaad porn isticmaasha ayaa si tartiib tartiib u yaraan doona. **Tilmaantaan si halis u qaado: Isku dayga inaad goor hore joojiso faa'iido kuuma yeelayso.**

Qaar badan ma dhammeeyaan buuga waayo waxay dareemaan inay ku qasban yihiin inay wax ka tanaasulaan, qaar oo xataa si ula kac u akhrinayaan hal xariiq maalintii si ay dib ugu dhigaan 'dhacdada xun.' Sidaan u fiiri: Maxaa kaa khasaaraaya? Haddii aadan joojinin ee dhammaadka buuga, xaaladdaada sidii ay ahaan jirtay kama sii xumaanayso. Waa Pascal's Wager qeexitaan ahaan, sharad oo la qaato adigoosan haysanin wax oo kaa khasaaraya oo aad fursadaha sare u haysato ee faa'iidooyinka waaweyn.

laakin haa, haddii aadan porn daawanin dhowr maalmood ama dhowr toddobaadyo, oo laakin aadan hubin haddii aad tahay isticmaale porn, isticmaale hore, ama qof oo isticmaale ahayn, ha isticmaalin porn si aad u siigaysato. Dhab ahaantii, waaba tahay qof oo isticmaale ahayn, laakin waa inaan u ogolaano in maskaxdaada ay jirkaaga la qabsato. Dhammaadka buuga, waxaad noqon doontaa qof faraxsan oo isticmaale ahayn. EasyPeasy waa lidka hababka [kale] oo caadiga ah, halkaas uu mid ka mid ah liis garaynaya khasaaraha porn oo uu leeyahay:
  
*"Haddii aan joogi karo waqti dheer oo ku filan anigoo porn la'aan, damaca ayaa ugu dambeyntii bixi doona waxaana mar kale ku raaxaysan karaa noloshayda, anigoo xor ka ah addoonsiga porn."*

Tani waa habka macquulka oo loo sameeyo, iyadoo maalin walba kumanaan joojinayaan iyagoo habkaan isticmaalayaan. Si kastaba ha ahaatee, way adagtahay in habkaan lagu guuleysto waayo sababaha soo socda:

**Joojinta PMO ma aha dhibaatada oo dhabta ah.**
Mar walba oo aad dhammeeyso fadhigaaga porn, waad joojisay isticmaalkeeda. Waxaa laga yaabaa inaad haysato sababo oo xoog leh maalinta ugu horeysa ee porn qaadashadaada nidaamsan oo "hal mar afartii malmood" si aad u dhahdo *"Ma doonaayo inaan isticmaalo porn, ama inaan xataa siigaysto mar dambe."* Dadka oo dhan way sameeyaan, sababahooduna way ka awood badan yihiin wax kasta oo aad qiyaasi karto. Dhibaatada dhabta ah waa maalinta labaad, maalinta tobnaad, ama maalinta toban kumnaad, halkaas oo mid ka mid ah daqiiqadahaaga daciifka ah aad rabto inaad "hal mar fiiriso," oo aad ka dibna rabto fiirin kale, oo aad si lama filaan u noqato balwad mar kale.

**Ka warqabka khataraha caafimaadka wuxuu abuuraa cabsi badan, taasi oo aad u adkeyneysa joojinta.** 
U sheeg isticmaale inay ragnimadiisa baaba'inayso, waxa ugu horeeya ee uu sameyn doono waa inuu wax soo qabsado si uu u kiciyo dopamine-kiisa: sigaarka, khamriga, ama xataa kicinta browserka si uu porn u raadiyo.

**Sababaha joojinta oo dhan joojinta ayay dhab ahaantii adkeeynayaan.**
Sababtuna waa laba sababood. Sababta kowaad waa inay abuurayaan dhalanteedka in nalagu qasbaayo inaan iska dhaafno 'saaxiibkeena yar', taageerteena, ama raaxadeena (si kasta uu isticmaalaha u arko). Marka labaad, "dabool" aya noqonaysaa. Uma siigaysano sababaha ay tahay inaan joojino. Su'aasha dhabta ah waxay tahay, maxaan u rabnaa ama aan ugu baahanahay inaan isticmaalno?

Isagoo EasyPeasy ah, waxaan (bilowda) iska dhego-tirnaa sababaha oo aan u jeclaan lahayn inaan joojino, waxaana si toos ah u wajahnaa dhibaatada porn, waxaana nafteena weydiinaa su'aalaha oo soo socda:

1.  Porn maxay ii qabanaysaa?

2.  Runtii ma ku raaxaystaa?

3.  Runtii ma u baahanahay inaan noloshayda dhex maro anigoo baabi'inaya maskaxdayda iyo jirkayga?

Runta quruxda badan waa in porn ay *gabi ahaan* waxba kuu qabanaynin. Aan si cad u caddeeyo, ma aha in faa'iido darada isticmaasha ay ka miisaan badan yihiin faa'iidooyinka, laakin waa inay **gabi ahaanba** faa'iidooyin ku jirin daawashada porn.

Isticmaalayaasha intooda badan waxay u arkaan inay lagama maarmaan tahay inay caqli-geliyaan sababta oo ay porn u isticmaalaan, laakin sababaha ay la yimaadaan way khaldan yihiin wayna dhalanteed yihiin.

Kowdi, waxaan meesha ka saaraynaa aminsanaantaan oo khaldan iyo kuwaan oo dhalanteedka ah. Dhab ahaantii, waxaad mar dhow ogaan doontaa inaysan jirin wax oo aad ka tanaasusho. Intaa waxaa dheer, waxaa jira faa'iidooyin togan oo aad u fiican oo laga helaayo ahaanshaha qof oo PMO sameynin, iyagoo wanaaga iyo farxadada ay yihiin laba oo faa'iidooyinkaan ka mid ah. Markaan iska saarno dhalanteedka in nolosheena ay weligeeda noqonaynin mid oo lagu raaxaysan karo iyadoo porn la'aan ah -- anagoo garwaaqsano in nolosha aysan la'aanteed kaliya ahayn mid oo lagu raaxaysan karo oo laakin ay raaxada sidoo kale tahay mid oo si aan xad lahayn uga raaxo badan -- iyo markaan dareenka in wax nalaga qaaday ama in wax ay ka maqnaanayso nalaga ciribtiro, waxaan dib ugu noqon doonaa inaan dib u eegno kor u kaca fayoobaanta iyo farxadda -- iyo daraasiinada sabab oo kale ee joojinta porn. Garashadaan waxay kuu noqon doonaan caawimo dheeraad oo wanaagsan si ay kaaga caawiyaan inaad gaarto waxa oo aad dhab ahaantii rabto: raaxada noloshaada adigoo xor ka ah addoonsiga balwadda porn!
