# Maxay u adag tahay in la joojiyo?

Isticmaalayaasha oo dhan waxay dareemayaan inuu jinni qabsaday. Maalmaha hore ee balwadda, arrinta waxay tahay su'aal fudud oo ah: *"Waan joojin doonaa, laakin maanta ma aha."* Ugu dambeyntii waxaan gaarna heer inaan aamino inaanan haysanin awooda-rabitaanka oo ku filan oo aan ku joojino, ama inay jiraan wax oo porn ku jira oo aan u baahnahay si aan nolosha ugu raaxaysano. Balwadda porn waxay la mid tahay isku dayga in laga soo baxo god oo simbiriirixan: Markaan xagga sare u soo dhowaano, qorraxda ayaan aragnaa, laakin waxaan ka dib isaragnaa anagoo dib u sii dhacayno oo ay isla markii niyaddeena hoos u dhacayso. Ugu dambeyntii browserkeena ayan furnaa, iyo isla markii oo aan siigaysanayno, waxaan dareennaa wax oo aad u xun.

Weydii isticmaalaha, *"Haddii aad dib ugu noqon karto waqtigii ka hore intaadan la qabatimin, adigoo og aqoonta oo aad hadda leedahay, ma bilaabi lahayd inaad porn isticmaasho?"*

"MA DHICI KARTO!" ayaa jawaabta ahaan lahayd.

Weydii isticmaalaha oo la xaqiijiyay, qof oo aad u difaacaya isticmaasha porn oo aaminaynin inay dhaawac u geysato maskaxda ama inay keenayso hoos-u-dhaca daawadayayaasha dopamine: *"Ma ku dhiirigalisaa carruurtaada inay porn isticmaalaan?"*

"MA DHICI KARTO!" ayaa mar kale jawaabta ahaan lahayd.

Porn waa hal-xidhaale oo caadi ahayn. Sida hore loo sheegay, dhibaatada ma aha in la sharaxo sababta oo ay u fududahay in la joojiyo, dhibaatada waa in la sharaxo sababta ay u adag tahay in la joojiyo. Dhibaatada dhabta ah waa sharaxada sababta qof kasta uu sameyo *xataa ka dib* markuu hela aragtida oo ku saabsan dhaawaca neerfaha. Qayb oo ka mid ah sababaha ee aan u bilowno waxaa sabab u ah tobanaanka milyan oo kale oo horeyba ku jiraan, haddana dadkaan oo dhan waxay jeclaan lahaayeen inaysan markii hore bilaabin, iyagoo noo sheegaya inay la mid tahay in nolosha heer hoose lugu noolaado. Anaguna ma aamino inay iyaga ku raaxaysanaynin, waayo waxaan ku-xirnaa xoriyada ama ‘waxbarashada galmada’, waxaana aad ugu dadaalnaa inaan naftigayna la qabatimno. Waxaan markaas ku dhammeeysaneynaa nolosheenna inteeda kale anagoo u sheegayno dadka kale inaysan sameynin oo aan isku dayno inaan naftigeena balwadda iska saarno, oo aan inta badan u maleyno inaan tan ku gaar nahay.

Waxaan sidoo kale qayb weyn oo waqtigeena ku qaadanaa anagoo dareemayno rajo la'aannimo iyo darxumeysinimo. 'Ku waxbarashada' nafteena ee *kicinta xad-dhaafsan oo aan-caadiga-ahaynta* waxay naga dhigaysaa inaan doorbidno oo aan u sii damacno sawiradaan oo qaboobta ah, xataa markii kuwa diiran oo dhabta ah la heli karo. Iyadoo kor-u-kaca iyo hoos-u-dhaca dopamine ee joogtada oo PMO keento ah, waxaan nafteena ku xukumaynaa nolol go'doon ah, xanaaq, xanaajin, walbahaar, daal, iyo cillad galmo. Sida aan porn u isticmaalayno, iyadoo ka maqan qaybaha ugu fiican ee galmada iyo xiriirka, waxaan ugu dambeyntii dareemaynaa darxumeysinimo iyo dambi.

Dhab ahaantii, akhrinta halkaan iyo mareegaha kale oo ku saabsan kartida qabatinka iyo burburinta ee balwadda porn waxay naga sii badinaysaa walwasha iyo rajo la'aanta! Waa maxay nooca hiwaayaddaan oo markaad sameynayso, aad jeclaan lahayd inaadan ahayn, iyo markaanad ahayn, aad rabto? Isticmaalayaasha naftooda ay quudhsadaan mar kasta oo ay wax ka akhriyaan hypofrontality iyo dareen-yareesmada, mar kasta oo ay gadaashood ka isticmaalaan lammaanahood, iyo mar kasta oo aysan isku keeni karin inay jimicsiyaan ee fadhiga porn oo maalintii ka dib. Qof oo haddiis kale caqli iyo garasho leh ayaa maalmihiisa oo dhan ku qaata quudhsi. Laakin waxa ugu xun oo dhan, maxay isticmaalayaasha ka helayaan haddii ay u adkeystaan nolosha iyagoo leh hadhyadaan madowga oo xun ee maskaxdooda gadaashiis? **Gabi ahaan, waxba!**

Waxaa laga yaabaa inaad ka fikirayso *"Taasi waa wax oo aad u wanaagsan, waan ogahay, laakin mar haddii aad waxyaalahaan ula qabatimto, aad ayay u adag yihiin in la iska joojiyo."* Laakin maxay u adag tahay? Dadka qaarkood waxay dhahaan inuu sidaas yahay waayo calaamadaha ka-noqoshada oo xoogga badan, laakin sida mar dhow ee aad u imaan doonto inaad wax ka barato, calaamadaha ka-noqoshada dhabta ah waxay yihiin kuwa oo khafiif ah dhab ahaantii. Iyo tan waxaa caddeeynaysa markaad ka tixgeliso in dad badan oo PMO-yaal ah ay noolaayeen oo ay dhinteen iyagoo ogayn inay ahaayeen dad oo balwad leh.

Qaar waxay dhahaan inay porn lacag la'aan tahay iyo inay sidaas darteed bini'aadamka u qaataan bonanza-da (abaal-marinta) nafleyda, laakin tani waa been—[porn] waa wax oo qabatimsan waxayna u dhaqantaa sida daroogooyinka oo kale. Weydii isticmaale oo dhaaranaya inuu 'erotica' kaliya ku raaxaysta sida majaladaha Playboy haddii uu weligiisa ka gudbay khadka 'porn oo amaan ahayn'. Hadduuna si buuxda daacad u yahay, wuxuu qiran lahaayay waqtiyadii uu isku dayay inuu caqli-geliyo ka-gudubka khadkaas, halkii uu gabi ahaan waxba isticmaali lahayn.

Raaxada iyaduna shaqo kuma laha. Aniga waxaan ku raaxaystaa cunista kalluunka crayfish, laakin weligayga ma gaarin heerka inay lagama maarmaan ii noqoto inaan haysto kalluunka krayfish maalin walba. Waxyaabaha kale ee nolosha, waan ku raaxaysanaa inta oo aan sameynayno, laakin meelaha ma fadhiisanno anagoo dareemayno in wax nalaga qaatay markaanan sameynaynin.

Qaar waxay dhahaan:  

*"Waa wax-barasho!"* Habbaba sidee ay qof ahaan kugu kordhisay?

*"Waa qanacsanaanta galmada!"* Haddaba maxay kuu go'doominaysaa oo ay kuu dareensiinaysaa damac oo weligiisa dhergaynin?

*"Waa dareen sii dayn!"* Ka sii daynta culayska nolosha dhabta ah? Waayahay, sii dayn oo hal saac lee kaliya, ka hor intay dhammaan kugu soo laabtaan? Waa maxay culaysyada oo ay xalisay?

*"Waxay iga caawisaa hurdada!"* Marka maxay tahay sababta oo ay dadka kale si fiican u seexan karaan la'aanteed? Waxaa jira [habab badan](https://www.sleepfoundation.org/insomnia/treatment/meditation) oo [cilmi ahaan](https://www.sleepfoundation.org/insomnia/treatment/cognitive-behavioral-therapy-insomnia) la soo bandhigay oo lagu [hagaajin karo](https://www.amazon.com/Uvex-Blocking-Computer-SCT-Orange-S1933X/dp/B000USRG90) hurdada, iyo [in ka badan](https://www.menshealth.com.au/what-is-the-military-method-the-technique-that-promises-to-help-you-sleep-in-2-minutes). 

Dad badan ayaa aaminsan in porn ay caajisnimada yaraynaysa, laakin caajiska waa xaalad maskaxeed. Porn waxay si dhaqsasho badan kuugu baran doontaa cusayb-raadinta, taasi oo kuu horseedi doonta inay caajisnimada sii kordhisa ilaa aad ugu dambeyntii ka qaybqaadato raadinta duurjoogta ah sii aad u hesho muuqaalka oo saxda ah, adigoo noqonaysid mid oo maskaxdiis si kordhaysa u siigaysato inay raadiyso wax kasta oo kicinaya dareen-cusub, dareen qiiro xoog leh, iyo ugu dambeyntii, qiimo naxdin leh.

Qaarkood waxay dhahaan in sababta kaliya ay u sameyaan ay tahay: saaxiibadood iyo qof kasta oo ay yaqaaniin ayaa sameyaan. Haddii ay sidaas tahay, naftaada u ducee in saaxiibadaa aysan bilaabin inay madaxa iska jaraan si ay u daaweeyaan madax xanuunka! Isticmaalayaasha intooda badan oo ka fikiraya waxay ku soo gabagabeyaan inay tahay caado kaliya. Runtii tani ma aha sharraxaad, laakin iyadoo laga dhimay dhammaan sharraxaadaha caadiga iyo caqli-galiga ah, waxay u muuqataa inay tahay cudur daarka kaliya oo soo haray. Nasiib darro, waa si la mid ah caqli-darro. Maalin kasta oo nolosheenna ka mid ah waxaan iska beddelnaa caadooyin, qaarkooda oo ah kuwa oo aad u raaxo leh. Laakin maskaxda ayaa nalaga xaday si aan u aaminsanaano in PMO ay tahay caado iyo in caadooyinka ay adag yihiin in la jebiyo.

Ma adag yihiin in caadooyinka la jebiyo? Darawalada Mareykanka ayaa caadeysteen inay ku wadaan dhanka midigta ee jidka, laakin markay u safrayaan dibada waxay si dhib la'aan u jebiyaan caadada si kastaba ha ahaatee. Markaadna shaqo cusub hesho, waxaad galaysaa hawl kale oo joogto ah, oo ay sidaas darteed caadooyinkaaga isbeddelaan. Caadooyinkaas ayaa laga yaabaa in waqti ay qaataan in la laqabsado, laakin ma aha wax oo la mid ah jebinta halgan nolosha oo dhan u dheer oo leh balwadda porn. Maalin kasta oo nolsheenna ka mid ah waxaan sameynaa oo aan jibinaa caadooyinka, marka maxaan u aragnaa inay adag tahay in la jebiyo caado oo na dareensiiyo in wax nalaga qaatay markaan haysanin, dembinimo markaan haysano, caado oo si kastaba aan jeclaan lahayn inaan iska jebino, oo waxa kaliya oo nalaga rabo inaan sameyno ay tahay inaan *isticmaalka iska joojino?*

Jawaabta waxay tahay in porn ay caado ahayn, *waa balwad!* Taasi waa sababta ay u muuqato inay aad u adag tahay in 'laga tanaasulo'. Isticmaalayaasha intooda badan ma fahamsan balwadda waxayna aaminsan yihiin in porn ay ka helaan raaxo oo dhab ah ama taageero. Waxay aaminsan yihiin inay hurid oo dhab ah sameynayaan haddii ay joojiyaan.

Runta oo quruxda badan waa markaad fahamto dabeecadda runta ah ee balwadda porn iyo sababaha oo aad u isticmaasho, inaad sameynta joojin doonto. Saddex toddobaad gudahood, qarsoodiga kaliya oo jiri doona waa sababta oo aad u aragtay inay lagama maarmaan kuu tahay inaad porn isticmaasho ilaa inta aad isticmaalaysay iyo sababta oo aadan ka dhaadhicin karin isticmaalayaasha kale *sida ay u fiican tahay inaadan ka mid ahaanin PMO-yaasha!*

## Dabinka Xun

Porn waa dabin qarsoodisan oo xun oo bini'aadamka iyo dabeecadda ay weligooda isku darsameen inay hindisaan. Qaar naga mid ah ayaa xataa looga digay khataraha, laakin ma aamini karno sida oo aan ugu raaxaysanaynin. Laakin maxaa awalba [balwadda] na dhex geliya? Caadi ahaan, waa muunadaha oo lacag la'aanta ah oo ka imaadaan kuwa oo xirfadlayaasha ahayn iyo kuwa xirfadlayaasha ah oo waxyaalahooda wadaagaan. Sidaas ayaa dabinka loo dhigay. Haddii ay taasi beddelkeeda khatarta nooga digi lahayd waxa oo aan galayni inta oo aan ka hore sameynin fiirsigaas ugu horreeya, gambaleelka digniinta ayaa qaylin lahaayay.

Laakin gambaleel kuwaan ma qayliyaan. Waxaa laga yaabaa inay tahay dabeecadda oo naxdinta leh ee muuqaalaha badan oo maskaxdeena da'da yar ku xaqiijiyaan inaanan weligeena la qabatimaynin, anagoo fikirayna in maadaama aan iyaga ku raaxaysanaynin ee aan mar kasta oo aan rabno iska joojin karna. Ama waxaa laga yaabaa in walaxa porn jilicsan oo u muuqdaan inaysan dembi ahayn ay kicinin wax oo gambaleel ah, sida tolnimada fanaanka xirfadaysan uu u ciyaari karo si uu maskaxdeena u khiyaano. Anagoo bini'aadamo oo caqli badan ah, waxaan markaas fahmi lahayn sababta oo dadka waaweynta kala badhkood ay sii nidaamsan ula qabatimeen wax oo yareynaya awoodeena si aan u fulino isla galmadii oo aan daawaneyno. Xiisaha ayaa nagu soo dhowaysa albaabka balwadda, laakin kuma dhiiranno inaan ku dhufano thumbnail-ka (sawirka muuqaalka) oo aan fiirinayno, anagoo ka baqayna inaan xanuunsano ama inay noo diraan waddo ama anxshax-xumo oo khatar ah. Haddaana si shil ah u riixnay mid ka mid ah, waxaa badan inuu rabitaankeena kaliya yahay inaan bogga sida ugu dhakhshada badan ka baxno, iyadoo isla markiiba ay xiisahaynta oo sii quusta ah u sii badanaysa.

Mar hadduu hawshaan bilaabto, dabinka ayaan ku xayirannahay. Intii waxaas ka dambeeya, waxaan inta nolosheenna ka haray ku qaadanaa anagoo isku dayayno inaan fahamsanaano sababta oo aan u sameyno, anagoo carruurteena u sheegayno inaysan bilaabin, oo naftigeena isku dayayno inaan, waqtiyada oo caadiga ahayn, ka baxsano. Dabinka waxaa loogu talagalay inaan joojinta isku dayno 'dhacdo' kaliya darteed, ha ahaato waxqabadka galmada, khasaaraha xirfad ama xiriir, khasaaraha kaxaynta galmada ama xataa dareenka inaad tahay qof oo baras qabo. Isla markii oo aan joojino, waxaan qabnaa walbahaar oo ka sii badan waayo xanuunada ka-noqoshada, iyadoo habka oo aan ku tiirsanaynay si aan iskaga saarno walbahaarkaas oo mar dambe la heli karin.

Xooga go'aankeena inaan joojino ayaa markaas iscaddeeynaya inuu gariiraayo. Dhowr maalmood oo cadaabsan ka dib, waxaan nafteena ku qancinaa inaan dooranay waqti qaldan oo aan ku joojino, annagoo go'aansanayno inaan sugno waqtiyo walbahaar la'aan, kaasi oo, markuu yimaado, uu meesha ka saaraya sababta oo aan u joojinay markii hore. Dabcan, muddadaas weligeeda si buuxda uma imaan doonto, waxaanan bilaabaynaa inaan aaminsanaano in nolosheena ay u janjeerto inay walbahaarka ku sii badanayso. Waxaan mar dhow ka tagnaa ilaalinta waalidiinteena, iyo culeysyada shaqada, guri-sameynta, mortgage-ka (deynta guryaha), gadashada hoyga, iyo korinta carruurta waxay bilaabayaan inay nolosheenna ciriiriiyaan. Laakin tani waa dhalanteed. Qaybaha oo ugu walbahaarka badan ee nolosha makhluuq kasta waa, dhab ahaantii, carruurnimada hore iyo qaan-gaarnimada.

Waxaan u janjeernaa inaan isku qasno mas'uuliyadda iyo walbahaarka. Nolosha isticmaalaha -- sida daroogista oo kale -- ayaa si toos ah u noqota walbahaar badan waayo porn ma naga dejiso ama mana nafisayso walbahaarka, sida qaar ay isku dayaan inay naga dhaadhicyaan. Waa lidkeeda, iyadoo keenaysa walbahaar anagoo sii waddno isticmaasha, iyadoo habeenaha eed-badanta oo caws ku ururinayso dhabarka geela. Xataa isticmaalayaasha oo caadadooda iska saaraan --- sida ay badankooda u sameyaan hal ama dhowr jeer ee noloshooda oo dhan --- ayaa haysan karaan nolol farxad leh oo dhammaystiran ah, oo haddana ay si lama filaan ah mar kale ula qabatimaan. Anagoo ku dhex warwareegayno maze-ka porn, maskaxdeena ayaa ceeryaamtaan waxaana ku dhammeeynaa inta nolosheenna ka haray anagoo isku dayayno inaan ka baxno. Dad badan ayaa guuleystaan, oo ay kaliya ku soo dhacaan dabinka xun ee waqti dambe.

Xalinta dhibaatada balwadda porn waa hal-xiraale. Wayna adag tahay. Laakin markaad jawaabta aragto, way sahlan tahay wayna baashaalsan tahay, waxaadna la yaabi doontaa sababta oo aad taasi uga fikiri weysay! EasyPeasy waa xalka hal-xiraalahaan, isagoo kaa bixinaya maze-ka, adigoo weligaaga dib ugu dhex warwareegin. **Waxa kaliya oo ay tahay inaad sameyso waa inaad tilmaamaha raacdo ilaa xarfaheed**. Laakin, haddii aad **si khaldan u leexato adigoo cutubyada ka bood-boodaysa,** ama aad **xawliga hillaaca ugu degdegtid buuga,** adigoon si taxadar leh u sameynin dadaal ula kac ah ee akhrintaada ugu horeysa, tilmaamaha oo soo hareen waxay yihiin waxyaalo oo macno lahayn.

Qof kasta ayaa u arki karo in joojinta ay fududaysan tahay, laakin waa inaan kowdi xaqiijina xaqiiqooyinka. Maya, ma aha xaqiiqooyin oo loogu talagalay in lagaa cabsi-geliyo, waxaaba jira macluumaad oo si ka badan ugu filan oo halkaasi ka jira ujeedooyinkaas. Haddii ay taasi ku joojin lahayd, mar hore ayaad joojin lahayd. Laakin maxaan u aragnaa inay adag tahay inaan joojino? In su'aashaan loo jawaabo waxay u baahan tahay inaan ogaano sababta dhabta ah ee aan weli porn u isticmaalayno, taasi oo lagu soo koobi karo laba arrimood. Waxay kala yihiin:

-   Dabeecadda porn.

-   Maskax-xadashada bulshada.

Isticmaalayaasha porn waxay yihiin bini'aadamo oo caqli badan iyo maangal ah. Way og yihiin inay qaadanayaan khataraha mustaqbalka ah oo aada u weyn, marka waxay sidaas darteed waqti badan ku qaataan caqli-gelinta 'caadadooda'. Laakin isticmaalayaasha porn waxay qalbigooda ku ogyihiin inay nacas yihiin, iyagoo og inaysan weligooda u baahnayn inay porn isticmaalaan intaysan ka hore la qabatimin. Intooda badan waxay xasuustaan in 'fiirsigoodii' ugu horreeyay uu ahaayay isku dhafanka nacaybta iyo xiisaha cusubta ah. Kadibna waxay ku takhasusaan mareeg-helista, shaandhaynta iyo calaamadaynta, iyagoo si adag uga shaqaynaya inay qabatimaan.

Ugu xanaaq badanteed, waxaa jira dareen in dadka oo balwadda lahayn - naagaha intooda badan, nimanka waayeelka ah iyo dadka oo ku nool dalalka oo pornka xawaare-sareda laga heli karin - ay wax ka maqnayn, oo ay u arkaan xaalada inay tahay mid oo lugu qosli karo. Markaad kala furfurto arrimahaan ee cutubyada xigaan, waxaad sidoo kale u fahmi doontaa dabinka xun!
