# Badbaadinta Waqtiga

Caadi ahaan, markay isticmaalayaasha isku dayaan inay joojiyaan, sababaha ugu waaweyn ee ay bixiyaan waa: caafimaadka, diinta, iyo ceebaynta lammaane-ahaan. Qayb oo maskax-xadashada ee daroogadaan xunka ka mid ah waa addoonsinimadeeda; bini’aadamka wuxuu si xoog u dagaalamay inuu addoonsiga qaar badan ee aduunka ka saaro — laakin isticmaalaha porn wuxuu noloshiisa ku bixiyaa isagoo ku dhibaataysan addoonsi oo isaga naftigiisa isku keenay. Wuxuu ka warqabin xaqiiqada in, markii loo ogolaado inuu porn isticmaalaan, uu jeclaan lahaayay inuu ahaado qof oo isticmaale ahayn. Marka kaliya ee porn noqota mid qiimeysan waa marka aan 'isku dayayno' inaan gooyno ama aan ka foogaano, ama marka ka-foogidda nalagu khasbo.

Marar badan oo ku filan laguma soo celcelin karo in maskax-xadashada ay adkeynayso joojinta porn. Inta ka badan aan iska saarno intaanan bilaabin, inta ka badan oo fudud aad u arkayso inaad ujeedadaada gaarto. Isticmaalayaasha oo la xaqiijiyay, oo aaminaynin inay porn saameyn xun ku leedahay caafimaadkooda (tusaale: kacsi la’aanta porn keento, hypofrontality-ga, iwm.), iyo inay ku jiraan is jiid jiida maskaxeeda, waxay u janjeeran inay yihiin kuwa oo dhalinyarta ah ama kuwa doobka ah oo marmarkoo lamaane galmo iska haystaan. Sidaas darteed, jawaab-celinta gudeedka ee saameyntaan waxay ku dhex dhumaan dabeecadda dhallinyaranimadooda ama ay yihiin kuwa oo aad aan u badnayn in la fiirsan karo oo la diiwaan geliyo.

Doodda oo isticmaalaha dhalinyarka ugu fiican waa waqtiga oo daawashada lugu bixinaaya, gaar-ahaan inaad u sheegto: "*Ma aamini karo inaadan ka walwalin waqtiga oo aad ku bixinayso.*" Guud ahaan, indhahooda way iftiimaan, iyagoo dareema inay liidato haddii lagu soo weeraro sababo caafimaadka darteed ama ceebaynta bulsheeda, laakiin waqtiga darteed...

"*"Waan awoodi karaa, waa x saacadood todobaadkii, waxaana u maleynayaa inay u qalanto, waa dembigayga kaliya ee raaxays.*"

"*Weli ma aamini karo inaadan ka walwalaynin. Aan ka soo qaadno celcelis ahaan oo nus saac maalintii oo ay ku jirto daadasha jireed ee ka-noqoshada dopamine: Labadii toddobaadma mar, waxaad ku bixinaysaa ku dhawaad hal maalin shaqo oo buuxda (sideed saac) ee daawashada porn. Waxaan hubaa inaad ku heshiin lahayd in nus saac maalintii ay tahay qiyaas oo aad u taxaddarsan. Ma ka fikirtay inta waqtiga aad ku qaadan doonto inta aad nooshahay? Maxaad qabanaysaa waqtigaas gudahiis? Horumarinta xiriirada dhabta ah? Maya, jiilayda porn oo aada ugu jeceshahay naxriis kuuma hayso halka kaliya oo aad waqtiya dheer ku bixisay daawashada muuqaalaheed -- waqtiga ayaad iska dhuminaysaa! Taasi kaliyuna ma aha, laakin waxaad dhab ahaantii waqtigaas u isticmaalaysaa si aad u dumisid caafimaadkaaga jireedka, neerfahaaga, iyo kalsoonidaada si aad ugu dhibaatoodid waqti nolol ah ee addoonsi, xanuunsi, murugaysi, iyo xanaajis. Hubaal taasi waa qasab inay ku walwasho, sax?*"

Way cadaataa halkaan markay marayso - gaar ahaan isticmaalayaasha ka yar - inaysan weligood balwadda u qaadanin balwad oo waqti-nololeed ah. Marmarkoo, waxaa laga yaabaa inay xisaabiyaan waqtiga ay ku dhuminayaan toddobaad gudihiis, taasina ayaa si ku filan ah ugu digniinsan. Marmar kale, iyo kaliya markay ka fikiraan joojinta, waxay iska qiyaasaayaan waqtiga ay hal sannad ku bixiyaan - taas oo cabsi leh - laakiin halaha ay bixiyaan inta ay nool yihiin waa wax aan laga fikiri karin. Si kastaba ha ahaatee, waayo aan doodid ku jirno, isticmaalaha wuxuu si degdeg u jawaabaa, "*Waan awoodi karaa, waa halahaan oo kale kaliya toddobaad walba,*" isagoo naftiisa ku khiyaamaya xeeladaha suuq-gelinta oo caadiga ah.

Ma diidi lahayd shaqo oo la bandhigay oo bixisa mushaharka sannadlaha ee aad hadda ku jirto oo weliba hal bil oo dhan fasax kugu siinaysa sannad kasta? Isticmaale kasta garaaca wadnaha gudaheed ay ku saxiixi lahaayeen, waxayna isku mashquuli lahaayeen raadinta heshiisyada fasaxa ee meelaha qalaadkuwa ah. Ogaanshaha sida loo isticmaali lahaayay bil dhan oo shaqo la'aan ayaa noqon lahayd dhibaatada ugu weyn in la xaliyo. Wadahadal kasta oo aan la yeeshtay isticmaale oo la xaqiijiyay (fadlan xasuusnow in uusan ahayn qof adiga oo kale ah oo qorsheynaya inuu joojiyo), qofna weligiis igama qaadanin dalabkaas. Maxaa diidaya?

Badanaa, halkaan markay marayso, isticmaale la xaqiijiyay wuxuu dhehi doona, "*Fiiri, run ahaan, kama walwalsani dhinacda lacagta.*" Haddii aad ka fikirayso wax oo la mid ah, is weydii sababta aan u walwalaynin. Maxaad ayaad, dhinacyada kale ee noloshaada, u aadaa dhibaato waaweyn si aad dhowr doolaro u badbaadiso, laakiin aad hadda dooartay inaad kumanaan u kharshgareysid si aad farxadaada u disho?

Go'aan walba kale oo aad samayso noloshaada gudaheed waxay noqon doonaan natiijada ee hab gorfayn oo la miisaamayo faa'idooyinka iyo faa'iido darrooyinka si loogu imaado go'aan oo caqli-galaaya. Waxaa laga yaabaa inay noqoto go'aan oo khalad ah, laakin waxay noqonaysaa natiijada gabagabo oo caqli-gayso. Mar kasta oo isticmaale kasta uu miisaamo faa'iidooyinka iyo faa'iido darrooyinka isticmaalka porn, jawaabta waa daraasiin jeer ka badan, **"ISTICMAALKA JOOJI! DOQON BAAD TAHAY!"** Sidaas darteed, isticmaalayaasha uma isticmaalayaan waayo ay rabaan ama ay go'aansadeen, laakiin [waxay u isticmaalayaan] waayo aysan joojin karin. ***Waa inay*** porn isticmaalaan, iyo ay sidaas darteed maskaxda iska xadaan, iyagoo madaxooda ciida ku dhex duugayaan.

Isticmaalayaasha waa inay maskaxda ku hayaan in xaaladda ay si kordhisan uga sii dari doonto, iyadoo daraasado badan ay soo baxayaan iyo dad badan oo ka hadlaya saameynta xun ee porn. Maanta, waa dad aan caafimaadka ahayn oo ka hadlaya saameynta, berrituna waxay ku jiri doontaa liiska dhakhtarkaaga ee baaritaannada ogaanshaha. Maalmihii oo isticmaalaha oo 'waqtiyaha oo dareen hoose' ee noloshiisa galmada ku qarin karay walaaca shaqada gadaasheed way baxeen; lammaantaada waxay ku weydiin doontaa sababta aad habeenka ugu daahooso laptop-kaaga. Isticmaalaha miskiinka ah -- oo markii horeba murug u dareemaayay --  wuxuu hadda rabaa in dhulka la furo oo uu laqo.

Waxa oo yaabka leh waa in kasta oo ay dadka badankood dhiibi lahaayeen lacag fiican ee xubinnimaha jimicsiga ama tababaraha shaqsi-ahaaneed si ay murqo u dhistaan oo ay aad u fiican u eekaadaan, iyagoo qaar badan ka mid ah oo ka-xumaadeen oo ku jeesteen daaweynta sida kor-u-kaca testosterone, oo leh waxyeellooyin la hubin iyo khatar ah, waxaa kooxdaan ku jira dad badan oo ka faa’idaysan lahaayeen, iyadoo lacag la’aan ah, joojinta daqan oo si nidaamsan u baabi’inaya nidaamaha raxada maskaxdooda oo dabiiciga ah.

Tan waxaa sabab u ah inay weli ku fikirooyiin maskaxda oo isticmaalaha laga xaday. Idhahaaga ciida ka tirtir hal daqiiqad. Balwadda porn waa meerto, meertoguna waa mid oo noloshaada oo dhan jiraysa, iyo haddii aad meertaga jibi waaysi, waxaad ahaanaysaa isticmaale inta noloshaada ka hartay. Iska qiyaas inta waqtiga aad u malaynayso inaad ku qaadan doonto porn inta jiritaankaaga ka haray. Si iska cad, tirrada waqtiga oo khasaarayso wuu u kala duwanaan doonaa qof walba, laakiin aan ka soo qaadno inay tahay sannad iyo barr ee saacadaha shaqada. Hadda ka fikir haddii ay jiri lahayd jeeg bakhtiyaanasiib oo sannad iyo barr mushaharkaaga ah, oo roogaaga la dhigay berrito? Waxaad ku qob-ku-ciyaari lahayd adigoo farxadsa. Marka, bilow qoob-ka-ciyaarka! Waxaad ku dhowdahay bilowga helitaanka dheefahaas!

Haddii aad u malaynayso in tan ay tahay aragti oo khiyaano ah, weli naftaada lee khiyaamaysaa. Iska xisaabi inta waqtiga aad badbaadin lahayd haddi aanad weligaaga fiirsigaagii ugu horeeyay aad qaadanin bilawgiiba.

Muddo gaaban, waxaad qaadan doontaa go'aanka ah inaad isticmaasho fadhigaaga ugu dambeeya (weli ma aha, fadlan xasuuso tilmaamaha!), adigoo tihid qof isticmaale ahayn adigoo aan mar dambe dabinka ku dhicin. Waxa kaliya oo ay tahay inaad sameyso si aad u ahaato qof oo isticmaale ahayn waa inaad porn isticmaalin iyo inaad iska ilaaliso 'hal fiirin lee kaliya'. Xusuusnow haddii aad fiiriso, waxay kugu kici doontaa wax kasta oo aad ku qiyaastay faa'iidada mushaharkaaga.

Haddii aad qof ula talinayso balwaddooda porn, u sheeg inay garanaayaan qof oo diiday shaqo loo soo bandhigay oo bixinaysa mushaharkooda sannadlaha ah oo sidoo kale siinaysa lacagta bil dhan oo fasax ah. Markay ku weydiiyaan yaa doqonkaas ah, u sheeg, ***"Waa Adiga!"*** Waa edeb darro, laakiin mararka qaarkood waxaad u baahan tahay inaad farriinta u gudbiso si edeb ka yar leh.
