# Caafimaadka

Tani waa meesha ay maskax-xadashada ee isticmaalayaasha ugu weyn tahay -- gaar ahaan kuwa da'da yar iyo kuwa dob ah -- kuwaas oo isku maleynaya inay ka warqabaan khataraha caafimaadka laakiin aan ahayn. Badankooda way is khiyaamaan iyagoo naftooda u sheegayaan inay diyaar u yihiin inay aqbalaan cawaaqibka isticmaalka. Haddii uu routerkaaga internetka uu lahaayay shaqo oo qaylo-dhaanta digniinta keento markaad ku dhufato mareegaha porn, iyadoo leh: "*Ilaa hadda, sidaad rabtay ayuu ahaa, laakiin haddii aad daqiiqad kale joogtid, madaxaaga wuu qarxi doonaa.*" Ma joogi lahayd? Haddii aad jawaabtaba ka shakisan tahay, isku day inaad buur aad u dheer aad kortid, adigoo geeskiis taagan oo indhahaaga xiran oo aad ka fikirayso doorashada inaad porn joojisid ama aad soo kacdid adigoo indohaaga lagaa daboolay.

Shaki kuma jiro doorashadaada waxay noqon lahayd, laakin inaad madaxaaga ciida ku dhex duugtid adigoo rajaynayso inaad hal subax soo kici doonto adigoo mar dambe porn rabin, waxba ma fulinayso. Isticmaalayaasha naftooda uma oggolaan karaan inay ka fikiraan khataraha caafimaadka. Haddii ay sidaas sameyaan, raaxada dhalanteedka ah ee balwadda ayaa ka tagaysa. Tani waxay sharxaysaa sababta ee daawaynta naxdinta leh ay kuwa waxtar lahayn u yihiin maraxladaha ugu horreeya ee joojinta: waa kuwa isticmaalayaasha ahayn oo kaliya kuwa oo isku keenaan inay wax ka akhriyaan isbeddellada maskaxda oo burburinta ah.

Ka soo qaad wadahadalkaan oo isticmaalayaal lala yeeshtay, guud ahaan, kuwa dhalinyarada ah.

> **Aniga:** "Maxaad u rabtaa inaad joojiso?"
>
> **Isticmaalaha:** "*Waxaan ka soo akhriyay blogga fanaanka naaga-doonisaha inay fiican tahay in afar maalmood la joojiyo si aan isku tamar-kiciyo.*"
>
> **Aniga:** "Miyaadan guud ahaan ka walwalsanayn khataraha caafimaadka?"
>
> **Isticmaalaha:** "*Maya, waxaa laga yaabaa inaan berrito bas hoostiis ka dhex dhaco. Macnaha: Daqiq walba ayaan la dhiman karaa.*"
>
> **Aniga:** "Laakiin si kas ah maa bas uga hoos dhaci lahayd?"
>
> **Isticmaalaha:** "*Dabcan, maya.*"  
>
> **Aniga:** "Miyaan isku dhibaynin inaad bidixda iyo midigta iska fiiriso markaad jidka goynaysid?"
>
> **Isticmaalaha:** "*Dabcan, waan fiiriyaa.*"

Sax, dhib badan bay soo maraan si aysan hoos ugu dhicin baska, iyadoo ixtimaalka inay sidaas dhacdo aad u yar tahay. Welina isticmaalaha wuxuu dooranaa inuu isgeliyo khatar oo waxaan dhan ka sii dhabsan oo ah: in balwaddooda ay curiyaamineyso, oo uu muuqo mid oo gabi ahaanba ka warqabin. Kaasi waa awooda maskax-xadashada; pornkuna waa yeey oo dharka idaha ku jira. Yaab ma ohoo in haddii xataa aan diyaarad ka dareemno ciladda ugu yar, aan diidi lahayn inaan korno -- in kasta oo ay ixtimaalka inay diyaarada dhacdo u yar tahay -- laakin oo aan islamarkiiba qaadano khataraha porn oo nalaga dhaamaanad qaaday, oo aan noqono dad oo gabi ahaanba ka warqabin? Isticmaalaha muxuu ka helaa waxaan dhan? **Gabi ahaan, Waxba!**

Khuraafaad kale oo caan ah waa niyad-jabka ama xanaajinta. Dad badan oo da'dooda ka yar kama walwalsan caafimaadkooda waayo ay la kulmin niyad-jabka ama muruga. Laakiin niyad-jabka ama walbahaarka ma aha cudurka, waa calaamad. Dadka oo da'da ka yar guud ahaan uma dareemaan xanaajinta ama niyad-jabka oo ka abuurato waayo awooda dabiiciga ah ee jirkooda inay dopamine badan soo saarto. Markay weynaadaan ama ay noloshooda la kulanto dib-u-dhacyo oo halis ah, kheyraadkoodii oo horeyba u dhammaaday ayaa si xad-dhaaf ah lugu shaqeystay, waxayna si buuxda ula kulmi doonaan calaamado. Markii isticmaalayaasha oo da'dood ka weyn ay dareemaan walbahaarka, niyad-jabka, ama xanaajinta, waxaa sabab u ah nidaamyaha dabiiciga oo amni-ahaan nidaamka neerfaha kaaga difaacaya daadasha dopamine oo xad-dhaafsan iyadoo daawadeyaasha dopamine yaraynayso. Isticmaalaha wuxuu sidoo kale neerfa-ahaan u kobicyaa isbeddelid kale, kuwaas oo isku meel xun lee ku haayo.

Sidaan oo kale uga fikir: haddii aad haysato baabuur fiican oo aad u ogolaato inuu daxaleeyo adigoon waxba ka qabanin, taasi waxay noqon lahayd wax oo aad u nacas badan. Baabuurka dhan wuxuu si dhakhsasho u noqon lahaayay buur daxal ah oo la dhaqaajin karin, isagoo awoodin inuu meelba ku geeyo. Sidaasba ha ahaatee, ma noqon lahayn dhamaadka aduunka maadaama ay tahay kaliya su'aal ee haddii aad lacag ku filan qabtid inaad baabuur kale iska gadatid. Laakin jirkaaga waa baabuur oo noloshaada dhan kugu dhex qaado. Dhamaanteena waxan dhehi karnaa in caafimaadkeena ay tahay hantideena ugu weyn -- weydii miliyaneer walba oo jiran. Inteena badan waxaan dib u milicsan karnaa jirro ama shil ee nolosheenna oo aan ducaysanay inaan fiicnaano. Adigoo isticmaale porn tahay, ma aha inaad kaliya u ogolaanooso daxalka inuu galo oo aanad waxba ka qabanoonin, laakin waxaad sidoo kale si nidaamsan u burburinaysaa halka baabuur oo aad u isticmaalayso inaad ku dhex marto noloshaada oo dhan.

Caqliyeeso. Me aha inaad sidaan sameyso, xasuusnoow: **gabi ahaan, waxba** kuuma qabanooso. Hal daqiiqad lee kaliya, madaxaaga ciida ka bixi ee is weydii: haddii aad si huban u ogaan lahayd inay fadhigaaga ku xigto ay kaa dhigi lahayd qof oo aan u jawaabi karin qof oo aad u jeceshahay, ma sii waddi lahayd isticmaalka? Markii lala hadlo dadka oo waxyaalahan ku dhacdo, waxaa hubaal ah inaysan filaynin inay iyagana ku dhici doonto, cudurka naftigiisana ma aha waxa ugu daran, laakin waa ogaanshaha inay iyaga naftigooda isku keenen. Isku day inaad ka fikirto sida ay dareemayaan dadka oo 'batoonka ku dhufdeen', iyaga maskax-xadashada way u dhammaatay. Waxay inta noloshooda ka haray ku qaataan iyagoo fikirayaan, “*Maxaan naftayda muddo aad u dheer ku khiyaamay inaan aamino inaan u bahanahay inaan porn ku siigaysto? Haddii aan kaliya fursad u heli lahaayay inaan dib ugu laabto!*”

Naftaada ha khiyaamin, fursadaas waad haysataa. Waa falcelin meerto ah, haddii aad ka qaybqaadato fadhiga porn oo soo socda, waxay kuu horseedi doontaa kan ku xiga iyo kan kaas ku xiga. Wayba kugu dhacaysaa. EasyPeasy wuxuu kaa balan qaaday in daaweyn oo naxtin leh ay jiri doonin, marka haddii aad horeyba go’aan gaartay inaad joojinaysid, halaha oo soo socdaan naxtin kuuma ahaanayaan. Laakin haddii aadan go’aankaas gaarin, *inta cutubkaan ka haray* waad ka boodi kartaa, iyo waa u soo laaban kartaa markaad inta buuga ka haray dhamaysid.

Mar hore ayaa mugyad oo cilmi baaris ah laga qoray buurburinta oo porn ay ku sameyso nolosheena galmada iyo caafimaadkeena maskaxeeda ah. Dhibaatada waa: ilaa ay ka gaaraan go’aanka joojinta, ma rabaan inay ogaadaan. Forum-yada iyo kooxaha la-taliyeyaasha waxay la yihiin waqti dhumis waayo ay porn indhahooda ka dabooshay. Haddii ay si kama' ah u akhriyaan, wixi kowaad ay sameyaan waa inay soo saaran mareegta porn oo aada ugu jecel yihin. Isticmaalayaasha porn waxay u janjeeraan inay faraxada, walbahaarka, iyo khataraha galmada u arkaan arrimo oo si lama filaan u dhacaan, sida tilaabsiga miinaha dhulka.

Tan madaxaaga geli: wayba kugu dhacaysaa. ***Mar walba*** oo aad mareegahaaga porn soo furtid, waxaad kicinaysa daadashada dopamine iyo shaqo-galinta opioids-ka. Simbiriiriixanta neerfaha ayaa la saliidayay iyo raacitaanka wuxuu si la habsami kuugu dhex marinaa talaabooyinka ku xigta, iyadoo maskaxdaada oo script-ga ku dhaqmayso. Hadda nidaamka neerfaha waxaa ku dhex daadsan dopamine oo maadaama ay markii boqolaad tahay, daawadayaasha dopamine-ka way xirmaan iyo shaydaanka yarka wuxuu ka faa'iidaystaa hoos-u-dhaca farxadaada markii loo barbardhigo markii ugu dambeeyay inuu sii ka badan kuugu wado khadka caska ilaa porn ama habdhaqan oo ka sii naxtinsan si uus u daadiyo dopamine ka badan. Cusaybta ka badan waxay keenaysaa dompamine ka badan, iyo markaas shaydaanka yar wuxuu kuu sheegi doonaa inaad sii wadid. Sawiradda badan ama muuqaalaha badan ee hal fadhi waxay kicinayaan kicin xad-dhaafsan oo aan caadiga ahayn, iyadoo maskaxdaada ku durayso kiiimiko ka badan, oo ay kugu waddo inaad sii isticmaashid.

Waqtigaasuna oo dhan, daawadayaashaaga dopamine ayaa macluumaad helayaan inay jawaab ahaan isxiraan ee daadashada darteed. Orgasm waxay kaliya kordhisaa saameyntaan waxayna keenaysaa calaamadaha ka-noqoshada. Adiguna waxaad u diidsantahay waayo uu shaydaankaaga yarka ayaa u damacsan hagaajinkiisa dopamine iyadoo xanuun dhab ama raaxo darro la'aan ah. Hanjabada kacsi la'aanta ayaa dad badan ka cabsiiya, iyadoo sababta u ah waxa oo ay dadka fikradaas maskaaxdooda ka xannabidaan oo ay ku daboolaan cabsida joojinta. Ma aha in cabsida joojinta ay ka weyn tahay cabsida kacsi la'aanta, laakiin waa in joojinta ay islamarkiiba ahaan doonto. Laakin maxaa dhinacda xunta loo fiirinaa? Waxaa laga yaaba inayba kacsi la'aanta dhici doonin, oo ayba mar hore iska joojiyeen intayba dhici lahayd. 

Waxaan u janjeernaa inaan porn uga fikirno sida dagaal is jii jiidad oo maskaxeed ah: hal dhinac waxaa jira cabsida, "*Waa caafimaad darro, waa wasaq, iyo waa addoonsinimo.*" Dhinaca kale waxaa jira fikradaha togaanta ah: "*Waa farxadayda, saaxibdayda, taagertayda.*" Laakin weligeeda ma noo muuqato in dhinacaan oo togaanta ah iyaduna ay tahay cabsida; ma aha inaan anaga porn ku raaxaysano, laakin waa inaan kaliya u janjeerno inaan ka darxumeysanahay la'aanteed. Balwadaha heroin-ka oo heroin loo diiday, darxumeyskaas way la kulmaan, laakin ka fikir farxadda ay dareemaan markii ugu dambeyntii loo ogolaado inay cirbad xididkooda geliyaan oo ay iska joojiyaan damacaas oo aadka u xun. Isku day inaad ka fikirto sida qof uu dhab ahaantii u aaminsanaan karo inuu farxad ka heliyaya duritaanka cirbadda ee xididikiisa. Dadka oo aan heroin-ka balwad u lahayn kuma dhibaatoodaan dareenkaas oo argagaxa ah, heroin-kuna dareenka ma nafiso, wuxuu yahay sababta.

Dadka oo isticmaalayaasha ahayn ma dareeemaan darxumeysnimada haddii oo loo ogolaadin isticmaalka porn - waa isticmaalayaasha kaliya kuwa oo dareenkaas ku dhibaatoodaan. Porn dareenka ma nafiso, waxay tahay sababta. Ka cabsiga ee cawaaqibaha xunka waxba kama caawisa isticmaalayaasha inay joojiyaan, waayo ay cawaaqib xumaha u barbardhigaan ku-dhex-socoda meel oo miino la dhigay. Haddii aad ka guuleysatay inaad dhex marto, waa isla fiican tahay, laakin haddii aad nasib darran tahay, waxaad ku tilaabsanay miinada iyo cawaaqibaha ayaad la kulmaysaa. Haddii aad khataraha ka warqabtay oo aad isku diyaariysay inaad la kulanto, maxaa ka galay dadka kale, sax? Balwadaha oo xaaladaan ku jira waxay caadi ahaan u kobciyaan xeeladahaan oo dhuumashada ah:

"***Qof waayeel ayaad noqonay, iyo xirfadaada galmada way kaa tagaysaa si kastaba ha ahaatee.***"  

Dabcan taasi way dhacaysaa, laakin xirfadaada galmada ma aha arrinta -- waxaan ka hadloonaa addoonsinimo. Xataa haddii ay sidaas noqoto, taasi sabab oo caqli-galaysa may tahay inaad si kas ah waxyaalahaas naftaada u keentid?

”***Tayada nolosha ayaa ka muhiimsan noolaanta kaliya.***"

Sax! Laakin inay tayada nolosha balwadaha porn ay ka fiican tahay tayada qof oo balwad lahayn maadba soo jeedinaysaa? Run mayba kaa tahay aaminsanaanta in tayada nolosha isticmaalayaasha ay ka fiican tahay tayada kuwa oo isticmaalayaasha ahayn? Nolol oo lugu qaatay iyadoo madaxa ciid lugu daboolaya uma muuqdo mid oo farxad leh.

"***Waxaan ahay qof oo doob ah, mana qorsheynaayo mustaqbalka inaan qof guursado, marka maxaa diidaya?***"

Xataa haddii ay sidaas run ahaan lahayd, taas sabab oo caqli galayso may u tahay in nidaamyada neerfaha maskaxdaada lugu ciyaaro? Suurtogal muu kuu yahay inaad ka fikirto qof oo doqonnimadiis ay ku filan tahay inay ka dhigto qof oo is qaawiyo mar walba uu kaligiisa joogo, isagoo ka walwalaynin haddii uu qof ku soo galaaya? **Taas waa isla waxa saxda ah oo isticmaalayaasha porn ay sameyaan!**

Wasakhaynta wareegyada abaalmarinteena ee kicn oo xad-dhaafsan, iyadoo laga dhigayo mid oo walbahaarada caadiga ee nolosha xamili karin kamaa caawinayso inaad noloshaada ku raxaysatid iyadoo xamaasad iyo xoog leh. Porn iyo siigaysashada waxay beddelin u noqdeen rabitaanka galmada oo dabiiciga ah, sida ay gabasha shukulaatada ay cuntada dhabta ah beddelin u noqotay. Si aan yaab lahayn, dhakhaatiir badan iyo culuumada cilmi-nafsiga ayaa hadda la xiriirinaya dhibaatooyin caafimaad maskaxeed oo kala duwan ee sababaha jir ahaaneed. Bulshada guudka ee caafimaadka ayaa sheegtay in porn ay weligiisa cilmi ahaan loo xaqiijinin inay tahay sababta tooska ah ee dhibaatooyinka dadka oo is-qiranayaan, laakin in qof uu fagaareda u qirano karti la'aantiisa galamada waa wax oo dareen ceebees u keenaaya. Marka maxay sidaas u sameyn lahaayeen haddii aysan si dhab ahaantii u helin wixii oo dhibaatada nolashooda u keenaayay oo ay markaas iska saarin?

EasyPeasy wuxuu kaa caawinayaa inaad porn iska saartid oo aad noqotid isticmaale hore oo faraxsan. Ma jiri doono porn, ama siigaysashada oo porn kaalmaysay, ama orgasm-yada oo loo baahnayn. Kaalmaynta kaliya waxay noqonay taabashada, aragtida, ama caraftida lamaantaada. Sida rootiga hadhuudhka oo dhan ee ka dib rabitaan-cuntada oo si fiican u kobcinsan, mar dambe uma baahnaanaysid sharoobada galleyda ee fructose-sarayda oo porn. Waa caddeyn aad u badan oo xataa loo baahnayn in la caddeeyo; markii aan dubbaha suulkayga ku dhufto way xanuunaysaa, loo ma baahno in la caddeeyo. Walbahaarka ee isticmaalka porn waxay ku daadataa dhinacya kale ee nolosha isticmaalaha, iyadoo badankooda u horseediso inay daroogooyin u jeestaan sida sigaarka ama khamriga si ay nolashooda la qabsadaan, iyo tusaaleyaasha qaarkood inay xataa isticmaalaha u horseediso inuu ka fikiro isdilid.

Isticmaalayaasha waxay ku dhibaatoodaan dhalanteed oo ah in saameynta porn oo xun ay aad u buunbuunaysan yihiin. Laakin xaalka waa lidkeeda, shaki kuma jira in porn ay tahay sababta oo cilladda galmada iyo dhibaatooyin kale oo badan. Meeqa furitaan ayaa u dhacaan porn darteed? Ma jiraan hababo oo la isku halayn karo in tirrada lugu ogaado, laakin raadinta bulshooyin oo onlineka waxay soo jeedisaa in tirrada ay si degdeg u badanayso.

Waxaa jiro qayb oo *Friends* ka mid ah oo nimankii ay helayaan porn lacag la’aan oo joogto ah ee TV-ga, iyo waxay bilaabayaan inay ka yaabaan maxay gabadha biisada keenaysa ay u weydiinaynin haddii ay 'sariirtooda weynka' soo gali karto. Markaad balwad leedahay, had iyo jeer ayaad naagaha dhabta ah ku saadaalinaysaa khayaaliyaashaada porn. Ka fikir wixii porn-ka oo si taxadar la'aanta ah ama xataa kuwa shilalka ah ee dhinacyada internetka oo mugdiga ah ay ku sameyn karaan qof oo horeyba ku jira xaalada bar jebinta noloshooda. Inay la dagaalamaan fikrahaas oo porn keenayso waxay noqonay dheecaan weyn ee caafimaadkooda maskaxeeda. 

Halkaan waa tijaabo kale oo fikrad ah: Aan dhehno qof ayaa kuu yimaaday oo ku dheheen inay orgasm rabin oo laakiin ay aad u rabaan inay galmo kula sameyaan, xataa dhexgalka. Waxayna rabaan inay kula samayaan inta dheer aad awoodi karto inaad orgasm-gareynin -- oo laakin haddii ay dhacdo inay fiican tahay. Waxaan kuu xaqiijin karaa ee waayo-aragtinimo galmo oo aad u cajiibsan oo kuwa kale dhan ka fiican! Haddii aad taas weligaaga laguu soo bandhigo, iska tijaabi!

Saameynta maskax-xadashada waxay naga dhigtaa inaan u janjeerno inaan u fikirno sida nin oo, isagoo dhismo oo boqol dabaq ah ka soo dhacay, laga soo xigay isagoo leh, "*Ilaa hadda, xaalada way fiicnayd.*" markuu dabaqa kontonaadka maraayo. Waxaan u maleynaa maadaama ilaa hadda aan ka fooganay cawaaqibaha xunka, inay hal fadhi kale oo porn inay waxba naga dhibaynin. Sida kale uga fikir: 'caadadaan' waa meerto oo soconaya iyadoo fadhi kasta abuurayso baahnaanta kan ku xiga. Markaad caadadaan bilawdo, waxaad shiday fiyuuska qarxiye. Dhibaatada waxay tahay: Ma ogtid muddada oo qarxiyeega (fiyuuska) uu qaadanaayo intuu kugu qarxin. Mar kasta oo aad isku ogolaato inaad yeelato fadhi kale oo porn, waxaad helaysaa hal tallaabo oo u sii dhow inay bambada qaraxdo. **SIDEED KU OGAAN DOONTAA HADDII AY MIDDA XIGTA TAHAY?**

## Hooska Madow oo Xun

Isticmaalayaasha waxay mid adag u arkaan inay aaminsanaadaan in porn ay sababta dhabta u tahay dareemahaas oo kalsooni darada ah markaad ku soo daahdo habeenaha bulsheeda maalin mashquulin ee guruiga ama shaqada ka dib. Dadka oo isticmaalayaasha ahayn dareenkaas kuma dhibaatoodaan, waayo porn ayaa sababta u ah.

Mid kale oo ka mid ah farxadda waaweyn ee joojinta porn waa xornimo ahaanshaha hooska madow ee xun oo maskaxdeena gadaasheeda ku jirta. Isticmaalayaasha dhan waxay ogyihiin inay nacas u yihiin inay maskaxdooda ka xiraan saameynta xun ee porn. Inta ka badan nolosheena habkaas wuxuu yahay mid oo iswaddo, laakiin hooska madow waxay had iyo jeer ku dhex dhuuntaan maskaxdeena miyir-daboolanka ah, oo dusha sare ka hooseeya. Dhowr ka mid ah faa'iidooyinka yaabka leh ee porn ayaa ah kuwa oo miyirka ah, sida joojinta khasaarinta waqtiga iyo nacasnimda weyn in galmo lala sameyo sawira oo laba-geesood ah.

Cutubyadii hore waxay ka hadleen faa'iidooyinka waaweyn oo ku jiraan ahaansha qof oo isticmaale ahayn, laakin dan ahaanta inaan cadaalad noqono, waxaan ku qasbanahay inaan si dheelltiran u warbixino. Sidaas darteed, cutubka soo socoda wuxuu liis gareenayaa faa'iidooyinka oo ku jiraan ahaanshaha isticmaale porn.

# Faa'iidooyinka ahaanshaha isticmaale porn
