# Habka Awooda-Rabitaan

Waxaa xaqiiq oo bulshada laga aqbalay ah inay aad u adagtahay in la joojiyo isticmaalka porn. Buugaagta iyo forum-yada oo tali ku siinayaan sida loo joojiyo waxay caadi ahaan ka bilaabaan inay kuu sheegaan sida ay u adagtahay in la joojiyo. Laakin runta waxay tahay inay si qosol leh u fududaysan tahay. Waa wax oo la fahmi karo inaad hadalkaas ka shakiso, laakin koowdi ka fikir lee. Hadduu hadafkaaga yahay inaad hal maayal ku orodo afar daqiiqood gudahiis, *kaasi* ayaa ah wixii oo adaga ah, waxaadna u baahnaanaysaa inaad dhex marto tababar oo aad u adkeysan, oo laga yaabo inaad weli jir ahaan awooda u lahayn inaad hadafka gaarto.

Si kastaba ha ahaatee, waxa kaliya oo aad u baahan tahay si aad isticmaalka porn u joojiso waa inaad falalka daawashada ama siigaysashada joojiso. Qof kuguma qasbo inaad siigaysato (oo aan adiga ahayn), iyo si ka duwan cuntada iyo biyaha, looguma baahno noolaanta. Marka haddii aad rabto inaad joojiso, maxaa keenaya inay ahaato wax oo adag ah? Dhab ahaantii, sidaas ma aha. Waa isticmaalayaasha kuwa oo naftooda ku adkeynayaan markay isticmaalaan habka awooda-rabitaanka ama hab walba oo isticmaalaha ku qasbaayo inuu dareemo inuu nooc hurrid sameynaayo. Bal aan tixgelinno hababkuwaan.

Ma go'aamino inaan isticmaalayaal noqono, waxaan kaliya tijaabinaynaa majaladaha ama mareegaha porn, iyo waayo ay aad u xun yihiin (haa, aad bay u xun yihiin) markii laga reebo muuqaalka aan rabno, waxaan ku qanacsanahay inaan joojin karno mar kasta oo aan rabno. Kowdi, waxaan daawanaa muuqaalahaas ugu yaryar oo horeeya mar kasta oo aan rabno iyo markii lugu jiro dhacdooyinka gaarka ah. Intaanan xataa ka garwaaqsanin, ma aha inaanan kaliya si joogto u booqanoono mareegahaas oo aan ku siigaysanoono mar kasta oo aan rabno -- laakin maalin walba ayaan ku siigaysanoonaa.  Porn waxay noqotay qayb oo nolosheena ka mid ah, iyadoo hubinaysa inaan u baahanahay isku xirka internetka meel kasta oo aan aadno. Waxaan markaas aaminsannahay inaan xaq u leenahay jacaylka, galmada, orgasmka iyo sifooyinka walaac-yareesmada ee porn. Nooma muuqato in isla muuqaalaha iyo jilayaasha aysan na siinaynin dareen isku mid oo kacsi ah, waxaana bilaabaynaa inaan la dagaalamo khadka cas si aan 'pornka xun' uga foogano. Dhab ahaantii, siigaysashada iyo porn midkoodna ma wanaajiyaan nolosheenna galmada mana yareeyaan walbahaarka, waa kaliya inay isticmaalayaasha aaminsan yihiin inay nolosha ku raaxaysan karin ama ay walbahaarka iska xakameyn karin orgasmka la'aanteed.

Waxaa caadi ah inay qaadato waqti oo aad u dheer inaan garwaaqsano inaan ula qabatimnay waayo waxaan ku dhibaatoonaa dhalanteedka in isticmaalayaasha ay porn daawadaan waayo ay jecel yihiin -- oo aysan u daawanin waayo ay u ***baahan*** yihiin. Markaan porn ku 'raaxaysanoonin', anagooba sidaas samayin karin ilaa cusaybnimo, naxtin, ama deg-deg-u-korid lugu daro, waxaan ku jirnaa dhalanteedka inaan iska joojin karno mar kasta oo aan rabno. Tani waa dabinka kalsoonida: "*Kuma raaxaysto porn, marka sidaas darteed waan iska joojin karaa markaan rabo*". Arrinta kaliya waa inaadan weligaaga u muuqanin inaad 'rabto' inaad joojiso.

Caadi ahaan, ma aha ilaa aan joojinta isku dayno oo aan garwaaqsano inay dhibaata jirta. Isku dayga ugu horeeya waxaa guud ahaan keenaya la kulanka lammaanaha oo markaas la ogaado inaysan 'kugu filnayn' ee shukaansiyaha koowaad ka dib. Sabab kale oo caadi ah waa markay dareemaan saameynta caafimaadka oo nolol maalmeedkooda ku jira.

Si kastaba sababta ha ahaatee, isticmaalaha wuxuu sugaa xaalad oo walbahaarsan, ha ahaato caafimaadka ama galmo. Isla markiiba markuu joojiyo, shaydaanka yar ayaa bilaabayo inuu soo gaajoodo. Isticmaalaha markaas wuxuu rabaa wax oo dopamine-kiisa kicinaayo, sida sigaarka, khamriga, ama tan oo uu aada ugu jeclaayay -- porn -- isagoo haremkiisa hal riixin ka joogto. Maalimahaan, kaydinta ee porn kuma jirto qolka hoose, hadda waxay tahay wax oo virtual ah oo meel walba laga heli karo. Istimaalayaasha haddii ay lammaantooda joogto ama ay saaxibadooda la joogaan, ma heli karaan haremkooda oo virtualka ah, taas oo ka dhigaysa inay aad uga sii walaacaan.

Hadduu isticmaalaha la kulmo waxyaala cilmiyaysan ama bulshooyin oo online ah, wuxuu gudaha maskaxdiisa ku dagaal is jii-jiid, isagoo duufsashaha iska caabinaya oo dareemaayo in wax laga qaaday. Habki oo uu caadi ahaan walbahaarka iskaga nafisi jiray ayaa markaas ahaanayo mid oo la heli karin, isagoo ku dhibaatoonaayo dharbaax oo saddex laabsan. Natiijada oo dhici karto ee xiligaan cadaabka ka dib waa inuu tanaasulo - "*Si tartiib ayaan iskaga jaraa*" ama "*Waxaan doortay waqti khaldan*" ama laga yaabee, "*Waxaan sugi doonaa ilaa uu walbahaarka noloshayda ka baxo.*" Sidaasba ha ahaatee, mar hadduu walbahaarka baxo, sababta oo lugu joogsan lahaayay ma jirto, iyo isticmaalahuna ma go'aansanaayo inuu mar kale joogsado ilaa uu waqti kale oo walbahaarsan yimaado.

Dabcan, weligiis waqti oo 'sax' ah ma jiro waayo ay nolosha ay dad badan walbahaarka u sii kordhayso. Waxaan ka tagnaa ilaaliska waalidkeena, anagoo galayno aduunka ee guri la gadaayo, daynta guriga la qaadanaayo, caruur la dhalaayo, iyo shaqoyaal oo aad u mas'uuli badan la haysanaayo. Sidaasba ha ahaadee -- nolosha isticmaalaha ma noqon karo mid oo walbahaar yaraysan waayo porn ayaa walbahaarka keenayso dhab ahaantii. Inta ka dhakhsasho badan uu isticmaalaha u maro maraxalada deg-deg-u-korida waa inta ka dhakhsasho badan uu walbahaarka noqonaayo iyo inta dhakhsasho badan ay dhalanteedka tiirsanaashaha noqonayso.

Dhab ahaantii, waxaa dhalanteed ah in nolosha ay noqonayso mid oo sii walbahaarsan. Porn -- ama 'taageer' kale oo la mid ah -- ayaa dhalanteedkaas abuuro. Tan hadhowtii ayaa si ka faafaahsan loo sharaxi doonaa, laakin guuldarreysiyadaan oo koowaadka ka dib, isticmaalaha wuxuu ku tiirsanaa suurtogalnimada inuu hal maalin soo kici doono isagoosan rabin siigaysashada ama inuu porn isticmaalo. Caadi ahaan, waxaa rajadaan kicio sheeykooyin oo uu isticmaalayaal hore ka soo maqlay, "*Run igama ahayn ilaa ay kacsi la'aan igu dhacday, markaas sida markiiba ma rabin inaan porn isticmaalo, siigaysashaduna waan iska dhaafay.*"

Naftaada ha khiyaamin, sheekooyinkaan iska baar markaas waxaad heli doontaa inaysan weligooda u fududaysnayn sida ay u muuqdaan. Waxaa caadi ah inuu isticmaalaha mar hore isku diyaarinayay inuu joojiyo oo uu kaliya dhacdada u isticmaalaayay dhiirgalin ahaan. Waxaa u badan, markii loo fiiriyo dadka oo sidaas oo kale isla markiiba u joojiyeen, inay wax oo naxtin ku dhacday: waxaa laga yaabaa in lamaantooda ay ku qabatay iyagoo daawanooyiin, ama dhacdo oo ay iyaga isku arkeen inay isticmaalaan porn oo hanuunita galmadooda ahayn, ama in dhacdo oo cabsiga cillada galmada leh ay iyaga nafigooda ku dhacday. "*Kaasi waxa luu yahay nooca qofka oo aan ahay. Macnaha: Waxaan u baahanahay waqti oo sidaas oo kale u saxsan.*" Ha is-khiyaamin. Joojinta weligeeda dhicin mayso ilaa aad adiga bilowdo dhicitaankeed.

Aan si ka faafaahsan uga fikirno sababta ay habka awooda-rabitaanka aad u adagtahay. Nolosheena inteeda badan, waxaan isticmaalnaa habka oo madaxa ciida la dhex gelinaya oo aan leh, "*Berrito ayaan joojinayaa.*" Waqtiyo oo caadi ahayn, waxbaa kicinaayo isku dayda joojinta. Waxaa laga yaabaa inay noqoto walwal oo caafimaadka ku saabsan, ragnimada, ama is-falanqaynta, ama xataa kaliya garwaaqsada inaan anaga run ahaantii ku raaxaysanayn. Si kastaba sababta ha ahaatee, waxaan bilaabnaa inaan isku barbardhigno faa'iidooyinka iyo faa'iido darroyiinka porn. Galmada waxay u kala qaybsan tahay tantric (taabashada, carfinta, codka) iyo faafinta (orgasmka); tani waxay ka mid tahay furaha ugu weyn ee furitaanka maskaxdeena, iyo kala-saaridaan muhiimta la'aanteed, waxaa jirayso wareer, taasi oo u horseediso guul daro. Markii si macquul loo kala qiimeeyo, waxaan ogaanaynaa wixii oo aan mar horey naqaanay nolosheena oo dhan: gunaanadka wuxuu kun jeer ka badan yahay "***DAAWASHADA JOOJI!***"

Haddii oo aad fadhiisan lahayd oo aad isku barbardhigi lahayd faa'iidooyinka iyo faa'iido darroyiinka joojinta porn, waxaad arki lahayd inay faa'iidooyinka ay aad uga badan yihiin 'faa'iido darroyiinka'. Haddii aad Pascal's Wager ku dhaqmi lahayd, waxaad arki lahayd inay waxba kaa khasaaraynin markaad joojinayso, adigoo fursad sare u leh inaad ka faa'iidaysato oo aadna guuldareysanin. In kasta oo uu isticmaalaha og yahay inay u fiicnaan doono inuu isticmaale ahayn, aaminsanaanta inuu wax hurayaayo ayaa ka waalaaya. In kasta oo uu dhalanteed yahay, aad bay u awood badan tahay. Isticmaalaha sababta ma ogo, laakin wuxuu haystaa aaminsanaanta in waqtiyaha fiican mise xun ee nolosha, ay fadhiyaha porn u muuqdaan inay wax ka caawiyaan. Xataa ka hore intuusan isku dayga bilaabin, maskax-xadashada bulshada oo weliba lugu sii xoojiyay maskax-xadashada balwadiisa ayaa markaas ku darsamaayo maskax-xadasha ugu xoog badan: sida ay porn u adagtahay in laga 'tanaasulo'. 

Isticmaalayaasha waxay maqlaan sheekooyin ee kuwa oo biloyiin joojiyeen oo weliba damacsan, ama joojinaha oo xanaaqsan oo ku qaataan inta noloshooda ka haray iyagoo ka murugaysan sida ay u jeclaan lahaayeen inay fadhi kale yeeshaan. Waxaa jira sheekooyin ee isticmaalayaal oo bilooyin ama sanadooyin joojiyeen, iyagoo ku noolaayeen nolol oo farxad leh, oo ay kaliya haysteen hal ‘fiirin’ kale ee porn oo ay haddana si lama filaan ula qabatimeen. Waxaa laga yaabaa inay isticmaalayaasha og yihiin qaar dad oo ku jiraan maraxladaha horumisan ee cudurka, iyagoo si caddeysan isku burburinayaan oo aysan noloshooduna ku raaxaysanayaan — oo ay weliba isticmaalkooda sii waddooyin. Intaa waxaa dheer inay u badan yihiin inay naftigooda ku dhibaatoodeen hal ama in ka badan oo waayo-aragnimadahaas. 

Marka intay bilaabi lahaayeen iyagoo dareemaya, “*Tan way fiican tahay! Warka ma maqashay? Uma baahni mar dambe inaan porn daawado!*” waxay taasi beddelkeeda ka bilaabaan dareeman oo darxumeysi ah — sida haddii ay isku dayyi lahaayeen inay Mount Everest koraan — waxayna si khaldan u qiyaasayaan in mar haddii uu shaydaanka yar ku qabsado, inaad inta noloshaada ka haray ula qabatimayso. Isticmaalayaasha intooda badan waxay bilaabaan isku-dayga joojinta iyagoo naagtooda u raali-gelinayaan, “*Fiiri, waxaan isku dayayaa inaan porn iska tanaasulo. Waxaa laga yaabaa inaan noqonaayo qof oo xanaaqsan toddobaadyada oo soo socdaan, marka iska adkeyso.*” Isku dayaga oo sidaan oo kale horey ayayba u dhamaadeen intaysan xataa bilaabanin.

Ka soo qaad inuu isticmaalaha dhowr maalin badbaaday isagoosan porn isticmaalin. Kacsigiisa ayaa u soo laabanooyo iyo wuxuu bilaabooyaa inuu soo kabto. Welina ma furin mareegaha porn oo uu aada ugu jecelaayay iyo, sidaas darteed, wuxuu kacsi ku yeelanooyaa kicnta caadiga ah oo uu markii hore ka dareen-yareesmaday. Sababaha uu meeshi hore ugu go'aansaday inuu joojiyo ayaa si degdeg uga baxooyo fikradahiisa, sida aragtida shil adigoo baabuur waddooso. Cabbaar bay ku gaabin doontaa, laakin gaaska ayaad cagtaada ku dhufan doontaa marka xigta ee ay kuu keento inaad balantaada ka daahdo.

Dhinaca kale oo dagaalka waxaa jira shaydaanka yar oo weliba helin hagaajintiisa dopamine.  Xasuusnow inuusan xanuun jireed jirin - haddii aad isla dareenkii ula kulmi lahayd hargabka dartiis, shaqadaada ma jooji lahayn mana u niyad jabi lahayd, waa iskaga qosli lahayd. Halkaan markay marayso, waxa kaliya uu isticmaalaha og waa inuu rabo inuu haremkiisa soo booqado. Shaydaanka yarkuna halahaan wuu og yahay, iyo wuxuu soo kicinayaa shaydaanka weyn, taasi oo u sababayso in isla qofkii oo dhowr sacadood ama dhowr maalmood ka hore joogay isagoo liis gareynayo sababaha dhan oo porn lugu joojiyo inuu hadda bilaabo inuu si quusan u raaadiyo marmarsi walba inuu dib ugu laabto. Wuxuu bilaabayaa inuu sheego waxyaalo sida:

-  “*Nolosha aad bay u gaaban tahay, bamba ayaa igu qarxi karo, bas hoostiis ayaan ku dhici karaa berrito. Waxaan joojiyay waqti oo aad u daahsan. Ayaamahaan wax walba ay kuu sheegayaan inuu balwad ku siinaayo.*”

-   “*Waqti khalad ayaan doortay.*”

-   “*Waxay ahayd inaan sugo ilaa ciidaha iyo intixaamyaashayda ka dib ay dhamaadeen, ama dhacdooyinka walbahaarsan ka dib.*”

-   “*Ma xooga-saari kari, waan xanaaqooyaa, xataa shaqadayda si fiican uma qaban kari.*”

-   “*Qoyskayga iyo saaxibadayda ima jeclaanayaan. Runta markii la isku sheego, waa inaan haddane u soo bilaabo dadka dartooda. Waxaan ahay balwad oo la xaqiijiyay iyo weligeeda ma dhici karto inaan haddane noqodo qof oo faraxsan orgasm-ka la’aanteed.*”

-   “*Qofna kuma noolaan karo galmo la'aan.*” (Tan waa maskax-xadasho oo ka timaado dad oo wax fiican ka wadaan oo laakin ka fikiraynin kala duwanaanshaha qaybaha tantric iyo faafinta ee galmada.)

-   “*Waan ogaayay inay sidaan dhacayso, maskaxdayda waxay ku ‘dareen-yeelatay’ DeltaFosB waayo isbeddelada oo kor-u-kaca dopamine-ka saamayeen, waayo isticmaalkayga porn hore oo xad-dhaasfan. Dareen-yeelasha ‘weligeeda’ maskaxda ma laga saari karo.*”

Maraxladaan markuu gaaro, waxaa caadi ah inuu isticmaalaha ka quusta [isku dayga inuu joojiyo]. Isagoo browserka kicinaayo, wareerka ayaa si kordhaayo. Hal dhinac, waxaa jira nafis oo aad u weyn oo damaca afjaraya maadaama uu shaydaanka yar ugu dambeyntii helaayo hagaajinkiisa; dhanka kale, orgasmka wuxuu u dareemayaa mid oo aad u xun, isticmaalahuna ma fahmi karo sababta uu u sameynaayo. Tan ayaa ah sababta oo uu isticmaalaha isku maleynaya inuu haysanin awooda-rabitaanka oo joojinta ku filan. Laakin, dhab ahaantii, la’aanshaha awooda-rabitaanka ma aha, waxa kaliya oo uu sameyay waa inuu maskaxdiisa beddelay oo uu go’aamin macquul ah oo macluumaad cusub ku salaysan soo qaatay inuu isku-dayga ka quusta. 

“*Maxay faa'iidada ah inaad caafimaad qabto ama aad taajir ahaato haddii aad murugaysan tahay?*”

Gabi ahaan, waxna! In la helo nolol raaxaysan oo gaab ah ayaa aad uga fiican nolol dheer oo darxumeysan. Nasiib wanaag, tani run uma aha kuwa oo isticmaalayaasha ahayn maadaama nolosha ay u tahay mid oo si xad-lahayn uga sii raaxo badan. Darxumeysiga oo isticmaalaha ku dhibaatoonaaya uma jira xanuunka ka noqoshada darteed — in kasta oo ay bilowgii kicinta u tahay — rafaada dhabta waa is jii-jiida maskaxda oo shakiga iyo hubaal la’aanta keenaayo. Maadaama uu isticmaalaha ka bilaawo dareenka inuu hurid sameynooyo, wuxuu bilaabaa inuu dareemo in wax laga qaadooyo, taasi oo ah nooc oo walbahaar ah.

Mid ka mid ah waqtiyadaan oo walbahaarka leh waa markay maskaxda u sheegayso inuu 'hal mar yar fiiriyo’, iyadoo rabto inuu dib ugu noqdo isla markii uu joojiyo. Laakin maadaama ay joojiyeen, dib uguma noqon karaan, iyo tan waxay ka dhigaysaa inay sii niyad jabaan, taasi oo haddane [balwadda] kicinayso. Arrin kale oo ka dhigaysa joojinta mid aad u adag waa sugitaanka inay wax dhacaan. Hadduu hadafkaaga yahay inaad baasto imtixaanka baabur wadista, waxaa hubaal ahaanaayo, isla markiiba oo aad imtixaankaaga baasto, haddii aad hadafkaaga gaartay. Laakin markaad habka isticmaalka awooda-rabitaanka isticmaalayso, sheekada wuxuu ahaanayaa, “*Haddii aan waqti dheer oo ku filan aan ku qaato anigoo porn isticmaalaynin, rabitaanka inaan daawado way iga tagaysaa ugu dambeyntii.**” Waxaad dhaqankaan ku arki kartaa forumyada online oo balwadaha ka hadlayaan maalmahood isku xigta ah oo ay ka foogadeen. Waxaad dhaqankaan ku arki kartaa forumyada online oo balwadaha oo ka hadlayaan maalmahood isku xigta ah oo ay ka foogadeen. 

Sida hore loo sheegay, rafaadka oo isticmaalaha la kulmaayo waa maskaxeed waxaana sabab u ah hubaal la’aanta. In kasta oo aysan jirin xanuun jireed, waxay weli qabtaa saameyn oo aad u xoog badan. Isagoo hadda darxumeysan oo kalsooni darran, isticmaalaha aad ayuu ka dheer yahay inuu hilmaamo, isagoo hadda shaki iyo cabsi ka buuxda. 

-   “*Ilaa intee ayuu damaca sii jiri doonaa?*”

-   “*Weligayga qof faraxsan ma noqon karaa haddane?*”

-   “*Weligayga ma rabi doonaa inaan subaxdii soo kaco?*”

-   “*Sideen weligayga ula qabsan karaa walbahaarka mustaqbalka?*”

Isticmaalaha wuxuu sugayaa inay arrimaha hagaagaan laakin intay weli murugaysan yihiin, 'haremka’ wuxuu noqonooyaa wax oo ka sii qiimeysan. Dhab ahaantii, wax way dhacaysaa laakin waxay ka dhacaysaa miyirka daboolan. Haddii uu isticmaalaha toddobaadyo u noolaan karo isagoosan browserka kicinin, damaca shaydaanka kar ayaa ka baaba’aya. Laakin sida hore loo sheegay, xanuunada kanoqoshada ee dopamine-ka iyo opiods-ka waxay yiihin kuwa oo aad u qarsoodisan ee xataa isticmaalaha wax kama warqabo. Markay waqtigaas gaaraan, istimaalayaasha intooda badan waxay dareemaan inay si guul leh balwadda 'iska saareen' iyo markaas hal mar ay dib u soo fiirinayaan si ay taas iskugu cadeeyaan, taasi oo dib ugu hoos celinayso simbiriiriixanta biyaha. Iyagoo jirkooda dopamine-ka siiyeen, waxaa hadda jira cod oo maskaxdooda gadashiisa ku jira oo u sheegaya, "*Mid kale ayaad rabtaa.*" Dhab ahaantii, waa run inay si guul leh iskaga saareen balwadda, laakin mar kale ayay balwadda isku keeneen.

Markaad cunug ahayd, waxaad fiirsan jirtay kaartoonnada, iyo sida ku cad cilmiga neerfaha, waxaad u yeelatay waddooyinka neerfaha (DeltafosB). Haddii aad rabi lahayd inaad cunug ka celiso daawashada, waxaad baran lahayd haddii waddooyinkaas oo neerfaha ay weli jiraan, waxaadana baaritaaan guud ka sameyn lahayd dadka waaweyn si aad u ogaato sababta ay mar dambe u jeclin kaartoonnada caruurnimadooda oo aada ugu jecleen. Koowdi ahaan, waxaa jira madaalalo oo ka fiican, iyo labaad, kaartoonnada ma haystaan dareemankii oo ay waagii hore haysan jireen. Markaad habka awooda-rabitaanka isticmaalayso, waxaad kaliya u diidaysaa inuu cunuga kaartoonka daawado, laakin markaad EasyPeasy isticmaalayso, waxaad sidoo kalehubinaysaa inaysan kaartoonnada u arkin wax oo qiimeysan. Kee ka fiican?

Waxaa caadi ah inuu isticimaalaha si degdeg u yeelanaynin fadhi kale, isagoo ka fikiraaya, “*Ma rabi inaan haddane ula qabatimo,*” wuxuuna u ogolaanayaa in 'xili amiinsan' ee saacadood, maalmood, ama xataa toddobaadyo ay dhaafdo. Ka dib, markuu cabbar ka foogaday, wuxuu markaas dhehi karaa, “*Hagaag, kuma qabatimin, marka fadhi kale ayaan si amiinsan u haysan karaa.*” Dib ayuu isla dabinkii ku dhacay iyo horey ayuuba simbiriiriixanta ku hoos dhacayaa.

Isticmaalayaasha oo ku guuleystaan isticmaalka habka awooda rabitaanka waxay u janjeeraan inay joojinta u arkaan mid dheer oo adag ah waayo dhibaatada ugu weyn ay tahay maskax-xadashada. Muddo aad ka dheer markay balwadda dhimatay, isticmaalaha weli wuu murugayaa, isagoo darxumeysan. Ugu dambeyntii, markuu ka badbaado cadaabkaan oo muddada dheer ah, wuxuu bilaabayaa inuu garwaaqsado inuu ka quusanaynin, isagoo muruga iska dhaafaayo oo uu aqbalaayo inay nolosha sii soconayso oo ay tahay mid oo raaxaysan porn la’aanteed. Markii habka awooda-rabitaanka loo fiiriyo, waxaa jira guul darooyin oo aad uga badan guulaha waayo qaar oo ku guuleystaan ayaa noloshooda dhex marayaan iyagoo xaalad nugul ku jiraan, iyagoo lugu deeyay dhowr maskax-xadasho oo u sheegayso in porn ay dhab ahaantii horumaris u siinayso. Tani waxay sharxaysaa sababta isticmaalayaal badan oo muddo dheer u joojiyeen ay hadhowtii dib u bilaabaan mar kale.

Isticmaalayaasha hore intooda badan waxay mar mar fadhiga u haystaaan si 'abaalmarin oo qaas ah' ama si ay isku qanciyaan sida ay u xoogtahay is-xakameyntooda. Kalfadhiguna si isla saxsan ayuu sidaas u sameya - laakin isla markiiba uu fadhiga dhamaado, dopamine-ka ayaa bilaabayo inuu ka tago iyo cod yar oo gadaasha maskaxdooda ku jira ayaa bilaabaayo inuu koo kale u wado. Haddii ay go'aansadaan inay ka qaybqaataan, waxay weli u muuqaysa inay xakami karaan, iyadoo aan naxtin jirin, degdeg u korid, ama cusayb-raadinta, marka waxay dhehayaan: "*Aad bay u fiican tahay! In kasta oo aan dhab ahaantii ku raaxaysanaynin, kuma qabatimaayo. Ciida / dhaawacaan ka dib, waa joojina.*" Laakin ma ka warqabaan in simbiriiiriixanta biyaha ee maskaxda la sii saliidayay.

Aad bay u daaheen, durtaba ayay ula qabatimeen! Dabinka oo ay maamuleen inay ka baxaan ayaa dhibanahiisa mar kale qabsaday.

Sida hore loo sheegay, baashaalka waxba kuma leh isticmaalka. Weligeeduna kuma lahayn! Haddii aan porn u daawanaynay bashaalka daraadeed, qofba ma joogi lahayn mareegaha porn waqti oo ka dheer intay ka qaadanayso in camalka la dhameeyo. Si kasta ha ahaadee, hab oo ka fiican oo lugu siigaysto waxay ka timaadaa xusuusta. Sababta kaliya oo aan u maleeyno inay porn raaxaysi leedahay waa inaan aamini karin sida aan doqon u nahay inaan ula qabatimno haddii aanan ku raaxaysanaynin. Isticmaalayaasha intooda badan kama warqabaan kicinta xad-dhaafsan oo aan caadiga ahayn, cusayb-raadinta ama naxtin-raadinta, iyo xataa markii ay ka soo akhriyaan, ma aaminaan in isticmaalkooda uu siliga nidaamka abaalmarinta maskaxda ku dhiirgelinsan yahay. Taas waa sababta oo ay balwadda porn inteeda badan u tahay arrin oo miyir-daboolan: haddii aad ka warqabi lahayd isbeddelida neerfaha, oo aad u baahnaan lahayd inaad isticmaalkaaga qiil u yeesho markuu mustaqbalka lacag kaa kharashaayo, xataa dhalanteedka inuu raaxo ku siinaayo ayaa baaba'aaya.

Markaan isku dayno inaan maskaxdeena ka xannibno dhinacda porn oo xun, waxaan dareemnaa inaan doqon nahay. Haddii aan runta isku sheegi lahayn, waxay noqon lahayd wax oo loo adkeysan karin! Haddii aad fiirisid isticmaale oo falalka ku jira, waxaad arkaysaa inuu kaliya ku faraxsan yahay markuu ka warqabin inuu isticmaalooyo. Laakin mar haddii la xasuusiyo, wuxuu u janjeerayaa inuu raaxo la'aan ku dhaco oo uu noqdo kuwa oo is difaacaya. Porn waxay quudisaa shaydaanka yarka, marka mar haddii aan jirkaaga ka saarno, iyada iyo maskax-xadashada (shaydaanka weynka), uma baahnaanayso mana rabayso inaad daawato.
