# Iska Ilaali Habka Jarista

Isticmaalayaasha waxay miciin bidaan inay habka goynta u isticmaalaan sida jaranjara ee joojinta, ama sida isku-dayin in shaydaanka la xakameeyo. Dad badan waxay ku taliyaan habka goynta ama 'porn qaadashada oo nidaamsan' sida kicin-ahaan. Isticmaalka habka goynta u sida jaranjara ee joojinta waa mid oo ***dilaa ah***. Waa noocyadaan oo isku-dayga ah oo dabinka nugu haayaan inta nolosheena ka hartay. Guud ahaan, habka goynta waxay daba raacdaa dhowr isku-dayin oo guul dareysteen in la joojiyo. Dhowr saacadood ama maalmood ee ka-foogida ka dib, isticmaalaha wuxuu dhehaa wax sida: 

"*Ma la kulmi kari fikrada oo aan hurdo anigoo aan u boooqanin haremkayga, marka hadda ka dib waxaan kaliya porn u isticmaali doonaa hal mar afarkii maalmood, ama waxaan iska saaraa uruintayda porn oo 'aada u xun'. Haddii aan nidaamkaan raaci karo, balwadayda meesheeda ayaan ku hayn karaa ama waxaan hoos u sii yareen karaa.*"

Waxyaabo oo xun ayaa hadda bilaabaan inay dhacaan:

1.  Wuxuu ku xayirsan yahay kuwa ugu xun aduunka oo dhan, isagoo weli balwad u leh porn oo kaliya shaydaanka ku haynoonin jirkiisa, laakin sidoo kale maskaxdiisa.

2.  Waxay rajaynayaan noloshooda oo dhan iyagoo sugaya fadhiga soo socda. 

3.  Inta ka hor intaysan hoos u jarin, waxay kici jireen browserkooda oo ay si qayb ahaan iskaga nafisi jireen xanuunkooda ka-noqoshada mar walba oo ay rabeen. Inta waxaa dheer ee walbahaarada caadiga ee nolosha, waxay isku keenayaan inay noloshooda badanteeda ku dhibaatoodo xanuun ka-noqosho, taas oo ka dhigayso dad oo sii ka badan u darxumeysan iyo xanaaqsan.

4.  Iyagoo ku mashquulisan, kuma raaxaysanaynin inta badan fadhiyada mana garwaaqsanaynin inay isticmaalayaan kicinta xad-dhaafsan oo aan caadiga ahayn. Waxay ahayd wax oo iswaddo. Booqashada haremka kaliya oo ay ku raaxaysteen waa mid oo xiliga ka-foognaanshaha ka dib ah. Hadda oo ay sugayaan saacada dheeraadka ah ee booqashada haremka walba, mid kasta ay 'ku raaxaystaan'. Inta ka badan oo la sugo, inta ka badan ay fadhiyada ‘raaxaysi’ u muuqdaan, waayo ‘raaxada’ oo fadhiyada ku jira aysan fadhiga naftigeeda ahayn — oo laakin ay tahay dhamaadka xanaaqa oo damaca sababtay  — ha ahaato damac yar oo jireed ah, ama darxumeysi oo maskaxeed ah. Inta ka dheer ay rafaadka joogto, inta ka badan ay ‘raxaysiga’ fadhi kasta noqonayso.

Dhibaatada aasaasiga ah oo joojinta ku jira ma aha balwada neerfa-ahaan, taas oo fududaysan. Isticmaalayaasha waxay si dhibaata la’aan u joojiyaan inta lagu jira marar oo kala duwan — dhimashada qof ay jeclaayeen, arrimaha qoyska ama shaqada, iwm. Waxay joogi doonaan, aan dhehno, toban maalmood la'aanteed, mana dhibayso. Laakiin haddii ay isla tobankii maalmood ee joogi lahaayeen waqtiyo oo ay porn heli kareen, timaha ay iska jeexjeexi lahaayeen. 

Isticmaalayaasha intooda badan waxay fursadahaas helayaan maalintooda shaqada  iyo way ka foogadaan, ama waxay dhex marayaan Victoria’s Secret mise barkadaha dabaasha iyagoo dhib lahayn. Intooda badan way ka-foganayaan haddii ay ku qasban yihiin inay fadhiga ku seexdaan si ay booqdaha boos u banayaan, ama haddii ay iyaga naftigooda booqanayaan. Xataa inta la joogo baararka Go-Go ama xeebaha oo dadka qaawan, waxyaala oo mudaaharraad ah ma jirin. Isticmaalayaasha waxay u dhow yihiin inay ku faraxsan yihiin qof ama wax inay u sheegaan inay porn arki karin. Dhab ahaantii, isticmaalayaasha oo raba inay joojiyaan waxay helayaan farxad sir ah inay joogaan iyagoo waqti dheer booqanin haremka, taas oo rajo siinayso in hal maalin laga yaabo inay weligooda rabi doonin.

Dhibaatada runta ee markii la joojinaayo waa maskax-xadashada, dhalanteedka xaq-u-lahaanshaha inay porn tahay nooc oo taageer ama abaalmarin ah oo ay nolosha weligeeda isku mid ahaanaynin la'aanteed. Iyadoo ka dheer inay porn kaa demiso, waxaa kaliya oo habka goynta ay fulisa waa inay kaa tagto adigoo dareemooso kalsooni darro iyo darxumeysi, iyadoo kugu qancinayso in waxa dhulka ugu qiimeysan ay tahay muuqaalka cusubta oo aad ka seegatay, oo inay dhici karin inaad weligaaga qof faraxsan noqotid adigoosan daawanin.

Ma jiro wax oo ka murug badan isticmaalayaasha oo isku dayaya inay hoos u gooyaan, iyagoo ku dhibaatoonayaan dhalanteedka inta ka yar ay porn daawadaan, inta ka yar ay rabaanayaan inay u booqdaan haremkooda. Runta waa lidkeeda, inta ka yar ay porn daawadaan, inta ka badan ay ku dhibaatoonayaan xanuunada ka-noqoshada oo ay inta ka badan ku 'raaxaysanayaan' nafiska. Si kastaba ha ahaatee, waxay ogaan doonaan in nooca porn ay aada u jecel yihiin uusan mar dambe ku qanacsanayn. Laakin taas iyaga ma joojin doonto: haddii ay mareegaha porn ay ku heelan lahaayeen hal nooc mise hal jilaa lee kaliya, ma jiri lahayn isticmaale oo weligiisa u tagi lahaayay wax oo hal mar ka badan.

Ma adag tahay in la aamino? Waa maxay daqiiqada is-xakamenyta oo aada ugu xun oo qofka dareemi karo? Waa sugitaanka afar maalmood oo ay markaas orgasmgareyaan. Marka, waa maxay daqiiqada oo isticmaalayaasha intooda badan ugu qiimeysan intay ku jiraan porn qaadasha nidaamsan oo hal mar afarkii maalmood? Sax, waa isla orgasmkii oo suugitaanka afartaas maalmood ka dib! dhab ahaantii maa u aaminsan tahay inaad raaxada orgasmka darteed u siigaysanoosid, ama sharaxaada oo ka caqli badan: inaad u baahan tahay inaad xanuunada ka-noqoshada iska nafiso adigoo ku hoos jirtid dhalanteedka inaad xaq u leedahay?

Ka saarida maskax-xadashada waa lama huraan sii meesha looga saaro dhalanteedka oo porn ku saabsan ka hor intaadan daminin fadhiga ugu dambeeya. Ilaa aad iska saartid dhalanteedka inaad porn ku raaxaysatid intaadan dariishadaas xirin, ma jirto hab oo aad ku caddey kartid inaan porn u baahnayn adigoosan haddane ula qabatimin. Markaad ku dul heehabooso calaamaynta iyo sawirradaha la kaydiyay, is weydii: aaway sharafta oo falalkaan ku jira? Waxaa laga yaabaa inaad aaminsantahay in muuqaalaha oo gaar ah kaliya ay fiican yihiin, sida noocyada oo aad caadi-ahaan u booqatid ama kuwa oo aada ugu jeceshid. Haddii ay sidaas tahay, maxaad isku dhibaysaa inaad muuqaalaha ama noocyada kale u daawato? Inaad caadooyinka gashay darteed? Waa maxay sababta inuu qof si caadi-ahaan maskaxdiisa u kharribo oo uu naftiisa khasaariyo? Waxba oo kala duwan ma jiro hal bil ka dib, marka sababta maxay tahay inay muuqaal porn u noqoto mid oo ka duwan?

Adiga naftigaaga ayaad tani tijaabi kartid. Raadi 'muuqaalkaas shidan' oo bishii hore si aad u cadayso inay tahay mid oo ka duwan. Markaas, xasuusin sameyso inaad isla muuqaalkaas daawato bishii soo socdo adigoo porn la'aan tihid waqtiga sugitaanka. Waxay (ku dhawaad) u dareemi doontaa sidi ay ahayd bishii hore. Isla muuqaal wuxuu ka duwanaan doonaa dhacdo bulsheed ka dib halkaas oo ay lammaane oo suurtagal ah ay ku diiday ama ay ku tijaabisay, sababta oo ahaanayso in balwadaha ay weligood u ahaan karin dad oo si buuxda faraxsan haddii uu shaydaanka yar qanacsanayn.

Qanacsanaanta maxay ka qabtaa? Waa kaliya inay darxumeysan yihiin haddii ay xanuunada ka-noqoshooda ay nafisi karin. Kala duwanaanshaha daawashada porn iyo inaad daawanin waa kala duwanaanshaha farxadda iyo darxumeysiga. Taas waa sababta oo ay porn u muuqdo inay joojinta ka fiican tahay. Isticmaalayaasha oo mareegtooda koraan wixii koowaad subaxdii ee porn darteed way darxumeysan yihiin haddii ay daawadaan ama in kale.

Ma aha kaliya inay habka goynta aysan shaqaynaynin, laakin waxay sidoo kale tahay nooca cadaabka ugu xun. Ma shaqayso waayo isticmaalyaasha ay kowdi rajaynayaan in haddii ay caadada iska yareen karaan, inay yaraynayso rabitaankooda inay porn daawadaan. Caado ma aha, waa balwad. Dabeecadda balwad kasta waa rabitaanka wax oo ka sii badanayaa, ma aha rabitaanka oo ka si yaraanaya. Sidaas darteed, haddii ay rabaan inay hoos u jaraan, waa inay isticmaalyaasha Isticmaalaan awooda rabitaankood inta noloshooda ka hartay. Marka, habka goynta macnaheeda waa awooda-rabitaan iyo edbin oo weligeeda joogayso. Joojinta oo si buuxda ah aad ay uga fududaysan tahay iyo xanuunkeed way ka yar tahay; waxaa run ahaantii jiraan toban kumamaan ee tusaaleyaal oo ay habka goynta guul dareysatay. 

Dhibaatada joojinta ma aha balwada dopamineka, taas oo fudad ah in la xamilo. Waa aaminsanaanta khaldanka inay porn raaxo ku siinayso, taas oo kowdi ka timaaday maskax-xadashada oo nala siiyay inta kor aanan xataa bilaabin isticmaalka, oo haddana balwad dhab ah lugu xoojiyay. Waxa kaliya oo hoos u jarista ay sameyso waa inay dhalanteedka sii xoojiso, ilaa ay ka gaarto heerka inay noloshooda si buuxda uga taliso oo ay ka dhaadhiciso in balwadooda ay tahay waxa oo Dhulka uga qiimaysan.

Tusaalayaasha qaarkood oo ku guuleysteen waa kuwa oo lugu gaaray muddo gaaban oo lugu jira habka goynta, taas oo ka daba socoto waqti ka-foognaansho oo si buuxda ah. Isticmaalayaashaan waxay u joojiyeen in kasta oo ay hoos u gooyeen, oo aanay sababta ahayn. Waxa kaliya oo habka goynta samaysay waa inay cadaabka dheeraysay, iyadoo isku dayada oo guul dareysteen ay isticmaalayaasha uga tageen iyagoo neerfa ah, oo ay sii qancinsan yihiin inay qabatimeen inta noloshooda ka hartay. Caadi ahaan, tan ayaa iyaga ku filan inaysan haremkooda dib ugu soo laabanin raaxaysi darteed ama taageero, mise ugu yaraanta muddada oo ka horreya isku dayga ku xigta. 

Si kastaba ha ahaatee, habka goynta waxay ka caawisaa tusaalaynta waxtar la’aanta porn, iyadoo si caddeysan u tusinayso inay booqashada haremka aysan raaxaysi lahayn waqti oo ka foognanshada ka dib. Waa inaad madaxaaga ku dhufatid darbi oo bulukeeti ah (macnaha: ku dhibaatoodo xanuunaha ka-noqoshada) si aad mid fiican ka dhigto isla mariiba aad joojiso. Sidaas darteed, doorashooyinka waa:

1.  Inaad noloshaada oo dhan ku qaadato adigoo hoos u jarayso oo aad ku dhibaatoodo cadaab oo adiga isku keentay, taas oo aan adiga karti u lahayn inaad sameyso si kastaba ha ahaadee.

2.  Inaad noloshaada oo dhan isku cadaabto, taasi oo macno lahayn.

3.  Inaad naftaada u naxariisato, oo aad gabi ahaan porn iska jarto.

Dhinaca kale oo ay habka goynta tusinayso waa inaysan jirin wax oo la dhoho booqasho haremka oo marmar ah. Porn waa meerto oo jiraysa inta nooloshaada ka haray ilaa aad ka sameyso dadaal oo dhab ah inaad jebiso.

**Xasuusnow: Hoos-u-goynta hoos bay kuu jiiday.**
