# Hal Fiirin Kaliya

"Hal fiirin kaliya" waa quraafad oo ay tahay inaad maskaxdaada ka saarto:

-   Waa *hal fiirin kaliya* oo nugu keento inaan awalba bilaabno.

-   Waxay qaadataa *hal fiirin kaliya* inaan la qabsano xaalad oo adkeysan, ama inta lagu jiro dhacdooyin oo gaar ah, oo ka adkaado isku daygeena badankood inaan joojino.

-   Waa *hal fiirin kaliya*, markii ka dib aan ku guuleysano inaan balwadda jebino, oo dib dabinka nugu celiso. Marmakoo waa kaliya inay naftooda u xaqiijiyaan inaysan u baahnayn porn iyo halka booqasho haremka wuxuu isla sidaas sameyaa.

Saameynta oo isticmaalka porn ka dib waxay ahaanayaan kuwa oo aad u xun iyo waxay isticmaalayaasha ku qanciyaan inaysan mar dambe ula qabatimi doonin — laakin hore ayay ula qabatimeen. Isticmaalayaasha waxay dareemayaan in wax oo darxumeysan iyo dembiile ah ka dhigaayo aysan ahayn inay ka dhigto inay sameyaan, laakin weliba wuu ka dhigay.

Waa fikrada ee ‘hal fadhi oo gaar ah’ oo badanaa ka hortagto isticmaalayaasha inay joojiyaan, ha ahaato midda oo safartaada shirkada ka dib, maalin adkeysan ee shaqadaada, maalin oo aad la dagaasho caruurtaada, ama dhacdo oo ay lamaantaada galmo kuu diido. Maskaxdaada ku dhex ***xooji*** inaysan jirin wax oo la dhoho ‘hal fiirin kaliya’. Waa meerto oo joogayso inta noloshaada ka hartay ilaa oo la jebiyo. Quraafaada oo ku saabsan ‘fadhiga gaarka’ waxay ku haysaa isticmaalayaasha inay murugaan iyagoo joojiyeen ka dib. La caadeysto in aadan weligaagaarkin fadhiga porn oo 'wax weyn ahayn', arigtidaas waa khiyaali. Mar walba oo aad ka fikirto porn, u arag sida waqti nolol oo wasakh ee qaadashada waqiyo oo aad u dheer oo aad shaashad gadaashiisa si aad maskaxeed iyo jireed isku burburinto — nolol oo addoonsinimo iyo quusasho. Dembi ma aha haddii uu kacsigaaga yahay mid oo aan la isku halayn karin, laakiin dembi wuu yahay haddii aad muddada dheer ahaan kartay qof oo si ka badan u faraxsan, oo aad laakin dooratay inaad taasi hurrido ee ‘raaxaysi’ oo muddo gaaban darteed.

Waa caadi inaanan mar walba u heli karin ‘wax loo sameyo’ dareenka madhanka; in sidaas la loo sameyo tusaale kasta ee nolosheena dhan si macquul ah uma suurtogalsan. Waan u qorsheyn karnaa, laakin marmarkoo wuu iska dhacaa. Waqtiyo fiican way dhacaan, iyo waqtiyo xunkuna sidoo kale way dhacaan, iyadoon loo eegin isticmaalka porn ama in kale. Laakin maskaxdaada ku caddee: porn waqtiyadaas sabab uma aha. Waxaad ku xayiran tahay mid nololeed oo darxumeysan leh ama midnaba. Weligaaga kuma riyoon lahayn qaadashada *cyanide* (sun oo yicib laga sameyay) waayo kaliya ee aad jeceshahay dhadhanka yicibka, marka jooji inaad naftaada ku ciqaabto fadhiga marmarka oo 'wax weyn ahayn'. Weydii isticmaale oo dhibaataysan, “*Haddii aad haysatay fursada inaad dib ugu laabato waqtiga oo ka kore intaadan qabatimin, isticmaale maa noqon lahayd?*” Jawaabta oo lama hurraanka ah waa, “*Waad igu ciyaaraysaa!*” Laakin isticmaale kasta wuxuu leeyahay doorashadaas maalin kasta oo noloshooda, markaa maxay u dooran waayeen? Jawaabta waa cabsi. Cabsida inaysan jooji karin ama inaysan nolosha sideedi ahaan doonin porn la'aanteed.

Naftaada ha khiyaamin! Waad joojin karta, qof walba ayaa jooji karo. Waxay tahay wax oo si qosol leh u fududaysan laakin in sidaas la sameyo, waxaa jira assaasi oo gaar ah inaad maskaxdaada ku caddesyso:

1.  Wax oo laga tanaasulaayo ma jiro, oo ay kaliya jiraan faa’iidooyin waaweyn oo la heli karo.

2.  Weligaaga naftaada ha ku qancinin fadhiga porn oo ‘wax weyn ahayn’. Waxaas ma jiro. Waxaa kaliya jira waqti nololeed oo waskhnimo iyo addonsinimo ah.

3.  Wax oo adiga ku saabsan oo kaa duwan ma jira; isticmaale walba wuxuu u arki karaa mid fudud inuu joojiyo.

Isticmaalayaasha intooda badan waxay aaminsan yihiin inay yihiin balwadyaal oo la xaqiijiyay ama inay haystaan shaqsiyad oo qabatin ah. Tan waxay caadi ahaan u dhacdaa natijo ahaan ee akhrinta tiro xad-dhaafsan oo ku saabsan cilmiga neerfaha oo naxtinta leh. Laakin ma jira wax oo ‘shaqsiyad oo qabatin ah’ la dhoho, qof oo baahitaanka inay muuqaalo ku siigaystaan lugu dhalay ma jiro intaysan ula qabatimin. Waa daroogada oo ku qabato, ma aha dabeecadaada ama shaqsiyadaa. Laakin dabeecadda kictinta xad-dhaafsan oo aan caadiga ahayn ayaa kaa dhigayso inaad sidaas aaminto. Sidaas ha ahaatee, waa lama huraan in la iska saaro aaminsanaantaan waayo markaad aaminto inaad balwad u lehdid, sidaas ayaad noqonaysaa, xataa markii shaydaanka yar uu muddo dheer ka hore dhintay. Waa lama huraan inaan maskax-xadashadaan dhamaanteed iska saarno.
