# Isticmaalayaasha oo Iska Caadiga Ah

Isticmaalayaasha oo culuska ah waxay u janjeeraan inay ka maseeraan isticmaalaha oo iska caadiga ah. Dhamaanteena waan la kulannay qofkaan: "*Haa, hal toddobaad oo dhan ayaan joogi karaa porn la'aanteed, dhibna ii ma keento.*" Waxaan jeclaan lahayn inaan sidaas oo kale ahaano. Tan waxaa laga yaabaa inay tahay wax oo adag in la aamino, laakin ma jiro isticmaale oo jecla inuu isticmaale ahaado. Weligaaga ha hilmaamin: 

|   *Ma jiro isticmaale oo go'aansaday inuu mid noqdo, ha ahaadee iska caadi ama in kale, marka **sidaas darteed,** *

|       *Isticmaalayaasha oo dhan waxay dareemaan inay doqon yihiin, iyo **sidaas darteed,** *

|         *Isticmaalayaasha oo dhan waa inay been naftooda iyo dadka kale u sheegaan sida isku day ahaan oo micna lahayn inay qiil u yeelaan doqonnimadooda.* *

Dadka oo ciyaarta golfka ka xamaasadaysan waxay ka faanaan inta badan ay ciyaaraan oo ay rabaan inay ciyaaraan, marka maxay isticmaalayaasha porn uga faanayaan inta ka yar ay siigaystaan? Haddii taasi ay tahay shuruudaha runta oo laga faano, ujeedada waxay tahay inaan gabi ahaan loo joojiyo siigaysashada, sax?

Haddii uu qof kuu sheegi lahaayay, "*Hal toddobaad oo dhan ayaan joogi karaa anigoo karooto cunin, dhibna ii ma keento.*", waxaad u maleyn lahayd inaad la hadlooso qof oo waashay. Haddii aan jecla inaan karooto cuno, maxaan u rabi lahaayay inaan joogo toddobaad oo dhan la’aanteed? Haddii aanan jeclayn, maxaan hadal oo sidaas oo kale u dhehi lahaayay? Marka haddii uu isticmaale faalo ka sameyo wax oo ku saabsan jooginta toddobaad oo dhan porn la’aanteed, waxay isku dayayaan inay iska dhaadhiciyaan — oo ay adigana kaa dhaadhiciyaan — inaysan dhibaato ku qabin. Laakin uma baahnaan lahayn inay hadalkaas sheegaan haddii aysan dhibaato haysanin. Markii la tarjumo, macnaha faaladaas waa: "*Waxaan ku guuleystay inaan noolaado toddobaad oo dhan anigoo porn la'aan!*" Sida isticmaale walba, waxay rajayayaan in hadda ka dib inay la’aanteed ku noolaan karaan inta noloshooda ka hartay. Haddii ay kaliya karti u leehyihiin inay hal toddobaad ka badbaadaan, ma ka fikir kartaa sida qiimeysan uu fadhiga u dareemi lahaayay ee ka-foognaanshada ka dib, iyagoo toddobaadkaas oo dhan dareemaayeen in wax laga qaaday?

Tan waa sababta oo isticmaalayaasha oo iska caadiga ah ay uga sii qabatimsan yihiin kuwa oo culuska ah. Ma aha kaliya in dhalanteedka ee raaxo ay tahay mid oo ka weyn, laakiin sidoo kale ma haystaan dhiirigalin inay joojiyaan maadaama ay ku qaataan waqti oo ka yar oo ay sidaas darteed nugul u ahayn khataraha caafimaadka. Marmarkoo, waxaa laga yaabaa inay la kulmaan cillada galmada, laakin ma hubaan wixii oo keenay, iyo markaas waxyaale oo kale ay iskaga eedaan. Xasuuso: raaxada kaliya oo ay isticmaalayaasha helaan waa inta ay ku jiraan wareega raadinta dopamine iyagoo iska nafisayaan xanuunada ka-noqoshada, sida hore loo sharaxay. Raaxada waa dhalanteed: u arag shaydaanka yar sida cuncun oo u dhow in la dareemi karin oo aan anaga ka warqabin waqtiyada badankood.

Haddii aan haysano cuncun oo joogto ah, janjeerta dabiiciga waa inaan iska xoqno. Iyadoo wareega abaalmarinta maskaxadeena ay si kordhaysan imyuun ku noqoto dopamine iyo opiods-ka, janjeerta dabiiciga waa siigaysashada oo aan la orgasm gareenaynin, daawashada xad-dhaafsan, degdeg u-korida, raadinta-cusubta, raadinta-naxtinta, iwm. Waxaa jira afar arrimood oo “istimaalayaasha oo iska caadiga ah” ka hortagaan inaysan si xad-dhaafsan u daawanin: 

-   **Waqtiga:** Badankooda ma awoodaan. Waqti uma haayaan inay sidaas sameyaan. 

-   **Caafimaadka:** Haddii oo la rabo in la nafiso cuncunta, waa inaan daawano waxyaalaha oo dhan oo lacag la’aan ah oo la fiirsan karo iyo ka badan. Kartida in lala qabsado daawashada xad-dhaafsaan oo noocyadaas waxay u kala duwan tahay qof walba, waqtiyada, iyo xaaladaha noloshooda oo ay ku jiraan. Tan waxay u dhaqantaa sida ka-hortaggid oo iswadda.

-   **Edbinta:** Edbinta waxaa soo rogto bulshada, ama shaqada isticmaalaha, ama saaxibaha ama ehelka; oo laga yaabo xataa isticmaalaha naftigiisa sida natijada dagaalka is jii-jiida dabiiciga ah ee maskaxdooda.

-   **Maale-awaasha:** Male-awaal la'aanta waxay si shaqsi-ahaan u yaraysaa, naxtinta, cusaybta, iyo qiimaha kale ee muuqaalaha la fiirsanaayo.

Way fududahay in isticmaalayaasha "oo iska-caadiga ahayn" loo maleeyo inay daciif yhiin, oo aan fahmi karin sida ay dadka kale u xaddidi karaan qaadashadooda. Si kastaba ha ahaadee, isticmaalayaasha oo culuska ah waa inay maskaxdooda ku haayaan inay isticmaalayaasha oo iska caadiga ahayn badankooda karti u lahayn inay si xad-dhaafsan u daawadaan, taasi oo u baahan male-awaal oo aad u xoog badan iyo adkeysi. Isticmaalayaashaan qaarkood oo "hal-mar-toddobaad-walba" ah oo isticmaalayaasha culuska ka maseeraan waxay yihiin dad oo si jireed u karti lahayn inay isticmaalkooda badiyaan, ama sababta waa shaqada, bulshada, mise nacaybkooda inay ula qabatimaan.

Waa laga yaabaa inay faa'iidoo leedahay inaan qeexitaanno ku siino:

**Qof oo Isticmaale Ahayn:**

Mid oo weligiisa dhibane ku noqonin dabinka porn oo laakin ay sidoo kale tahay inuusan qof oo taxadar lahayn uu noqonin. Wuxuu kaliya u yahay qof oo isticmaale ahayn waayo nasiibka mise nicmada wanaaga darteed. Isticmaalayaasha dhamaantooda waxaa laga dhaadhiciyay inaysan weligooda ula qabatimaynin, iyo kuwa oo isticmaalayaasha ahayn qaarkood waxay weli marmarkii isku tijaabinayaan fadhi porn.

**Isticmaalaha oo Iska Caadiga Ah:**

Kuwaas oo ka jiro laba qaybood oo aasaasi ah:

1.  Isticmaalaha oo weligiisa dhibane ku noqonin dabinka oo laakin uu garwaaqsanin — ha ka maseerin isticmaalayaasha oo kuwaas oo kale. Waxay kaliya dhedheminayaan nectar-ka dhirka, iyagoo suurtogalnimo leh inay mar dhow noqdaan isticmaalayaal oo culus. Xasuusnow: sida cabbistayaasha khamriga oo ay ka bilaabeen iyagoo cabbistayaal iska caadi ah, isticmaalayaasha porn dhamaantooda waxay sidoo kale ku bilaabaaan iyagoo iska caadi yihiin.

2.  Isticmaalaha oo isticmaale culus ahaan jiray, oo sidaas darteed u maleeyo inuusan joojin karin. Isticmaalayaashaan ayaa ugu murug badan iyo waxay ku jiraan qaybya oo kala duwan, oo qayb walba oo u baahnaanayso faalayaashooda oo kala saaran:

**Isticmaalaha oo "Hal Mar Maalintii":**

Haddii ay rurun ugu raaxaystaan xaq-u-lahaanshahooda inay orgasm-gareeyaan, maxay porn u isticmaalayaan hal mar maalintii? Haddii ay si dhibaato lahayn u qaadaan karaan ama ay iska day karaan, maxay isku dhibayaan daawashada? Xasuusnow: ‘caadada’ waa — dhab ahaantii — mid oo aad madaxaaga darbi ku dhufanayso si aad uga dhigto mid oo raaxaysan markaad joojinayso. Isticmaalaha oo “hal mar maalintii” wuxuu hal saac ka yar ku qaataa inuu maalin walba xanuunaha ka-nanoqoshada iska nafiso. In kasta oo uu ka warqabin, wuxuu inta maalintiisa ka haray ku qaataa isagoo madaxiisa darbigaas ku dhufanaayo, isagoo sidaas samayaayo inta badan noloshiisa. Way fududahay in isticmaale culus laga dhaadhiciyo inuuysan ku raaxaysanaynin, laakin aad ay uga adkeysan tahay in isticmaale oo iska caadi ah isla waxaas loo sheego. Qof walba oo la kulmay hal isku dayin ee habka goynta wuu ogaanaa inay tahay cadaabka ugu xun, oo ay u dhowdahay inay kaa balanqaado inaad balwad ahaato inta noloshaada ka haray.

**Isticmaalaha oo la Diiday:**

Xaqa ay orgasmka u leeyihiin ay maalin walba dalbadaan, laakin lamaantooda galmada mar walba kuma faraxsan inay codsiga fuliyaan. Kowdi, waxay porn u isticmaalayaan inay iska buuxiyaan dareenkuwaas madhanka, laakin markay isla markiiba qaataan ‘simbiriiriixanta biyaha,’ waxay ku dhex xayirmeen wareega raadinta cusaybta, naxtinta, sawirida ee kicinta xad-dhaafsaan oo aan caadiga ahayn leh, iwm. Dhab ahaantii, wayba ku faraxsan yihiin inay lamaantooda diiday maadama ay siinayso wax oo cudur daar la mid ah inay dib ugu laabtaan haremka. Haddii ay porn wax badan ku siisa, maxaad isku dhibaysaa inaad lammaane yeelato gabi ahaanba? Xor ka dhig lamaanataada. Isticmaalayaasha maba ku raaxaysan karaan fadhiyadood markay tahay inay lamaantooda gudaha maskaxdooda ku ‘haayaan’. Heer markay gaarto, waxay raadinayaan in lamaantooda runta ay siiso cudur daar oo ay u tagi karaan luuqyada madowga ee internetka.

**Isticmaalaha oo "Porn Qaadashada Nidaamsan":**

Sidoo kale loo yaqaan: “*Waan joojin karaa markasta oo aan rabo. Kumanaan jeer ayaan sameyay!*” 

Haddii ay u maleyaan in qaybta ka-foognaanshaa ee qaadashada la nidaamay ay niyadooda ka caawiso inay helaan niyad ay lamaan ku soo qaataan, maxayba kowdi ugu jiraan qaadashada la nidaamay ee "hal mar afarkii maalmood"? Maxaa dhacaya haddii fadhiga shukaansigooda ay tahay inay dhacdo hal saac oo fadhiga porn oo la qorsheeyay ka dib? Sidoo kale: Haddii ay 'nadiifinta tuubooyinka' u fiican tahay nafisashada walbahaarka, maxaysan u nadiifin waayeen maalin walba? Mar hore ayaa la cadeeyay in siigaysashada loo baahnayn in la ilaaliyo caafimaadka xubinta taranka, iyo pornka gabi ahaanba loo ma baahno.Xataa haddii ay sidaas ahaan lahayd, ma jiri lahayn qof oo naaga-doonista oo xirfadaysan, oo ka soo akhriyay waxyaala oo ku saabsan baabi'inta neerfaha oo weligiisa kuu talinaya inaad daawadoo kicinta xad-dhaafsan ee porn. Runta waa in isticmaalayaasha oo noocaan ka mid ah ay weli qabatimsan yihiin. In kasta oo ay iska saareen balwadda jireedka ah, waxay weli la hareen dhibaatada ugu weyn: maskax-xadashada. Mar walba ay ku jiraan waqtiga ka foognaanshaha ee qaadashadooda nidaamsan, waxay rajeeynayaan inay gabi ahaan joojiyaan, laakin mar dhow dabinka ay mar kale ku dhex dhacayaan.

Isticmaalayaasha intooda badan wayba ka maseeraan dadkaan oo joojinayaan iyo bilaabayaan, iyo waxay ka fikiraan sida uu isticmaalahaan 'nasiib' u leh yahay sida uu kartiga u haysto inuu iska xakameeyo isticmaalkiis. Laakin ma ka fikiraan xaqiiqada inuusan isticmaalahaan iska xakameeynin isticmaalkiisa -- markuu porn isticmaalo, wuxuu jeclaan lahaayay inuusan ahayn. Wuxuu dhex maraa dhibaatada joojinta, markaas wuxuu dareemaa in wax laga qaaday, oo uu markaas dabinka ku dhex dhaco haddane, isagoo jeclaan lahaay inuusan ku dhicin. Wuxuu ka helaa midda ugu xun lamada dhinacba. Haddii aad ka fikirto, waxay run u tahay nolosha isticmaalayaasha markii loo ogolaado inay hal fadhi haystaan -- ama waxay dareemaan inay xaq u leeyihiin ama waxay rabi lahayaan inaysan awalba weligood isticmaalin. Waa kaliya markii laga qaado oo ay porn noqoto wax oo qiimeysan. Dhibaatada 'miraha la mamnuucay' waa mid oo ka mid ah doorashaha oo aada u adag ee isticmaalayaasha. Mana ka guuleysan karaan waayo ay u murugaysan yihiin quraafad, oo dhalanteed ah. Waxaa kaliya jira hal hab oo ay ku guuleysan karaan: ku jooji murugada ee joojinta porn!

**Isticmaalaha oo "Waxaan Kaliya Daawadaa Porn oo Khafiifka/Sawirka Ah/oo Guriga Lugu Sameeyay":**

Haa, qof walba ayaa sidaan sameya bilowga, laakin yaab ma ahoo sida ay qiimada-naxtinta ee muuqaalaha u muuqdo inay si degdeg u kordhayso, oo aan, intaanan xataa ogayan, dareenno in wax nalaga qaatay (dulqaadashada)? Cusaybta oo sawirada porn way yar tahay, marka waxaan la kulannaa cawaaqibka koob saliida oo aan markaas hoos ugu dhacnaa simbiriiriixanta biyaha ciilka iyo dembi. Waxa ugu xun oo aad samayn karto waa inaad isticmaasho sawiradda lamaantaada (dabacan, adigoo ogolaanshooda haysato) siigaysashada darteed. Maxaa? Waayo adigoo habka ku jirto, waxaad dib u habaynaysaa maskaxdaada raadinta iyo daadashada dopamine oo kala duwanaansha muuqalaha keento. Kiimiko ahaan, simbiriiriixanta biyaha oo maskaxda ku jiro waa ururinta DeltaFosB, marka sidaas darteed waxaad arkaysaa adigoo dhib haysanooso markaad dhab ahaantii lamaantaada ula seexato.

Dabin kale oo qaybtaan ku jira waa porn oo 'xirfad lahayn' oo 'guriga lugu sameyay'. Badankooda waa been waana ogtahay, iyo waxaa ka sii darran, ma joogsanaysid markii oo kan kowaad uu idhahaaga ku dhaco, adigoo lidkeeda sii waddo raadinta. Xasuusnow: orgasmka kaliya ma aha waxa oo maskaxda raadinayso, laakin waa sidoo kale cusaybta ugaarsiga oo siinayso simbiriixanta biyaha xamaasadeeda. Arrinta ma aha waxyaalaha oo pornka ku jira -- ha ahaado mid xirfad leh ama lahayn -- waa daadashadayaasha dopamine maskaxda gudahiisa oo keenayso ururinta dulqaadasho iyo qanacsi. Porn waxay baabi'isaa hawlgalka maskaxda oo caadiga ah, iyadoo siigaysashada ay wareeriso jawaabta muruq-maskaxeed; orgasmka waxay maskaxda ku dhex daadisaa opiods oo ka dhigayso mid oo ka fududaysan in waddooyinka la raaco marka xigta. 

**Isticmaalaha oo "Waan Joojiyay Laakin Waxaan Marmar Haystaa Hal Fiirin":**

Si ahaan, isticmaalayaasha oo weli marmar fiirinayaan ayaa ah kuwa oo dhamaantooda ugu murugaysan. Ama waxay noloshooda dhex maraan iyagoo aaminsan in wax laga qaadooyo, mise inta badan, halka fiirin oo marmarkii ahaayay wuxuu isku beddelaa laba, iyagoo hoos ku dhex dhacayaan simbiriiriixanta biyaha, oo ay mar dhow ama hadhowti dib u laabtaan ahaanshaha isticmaalayaal oo culus. Waxay haddane ku dhex dhaceen isla dabinkii oo ay kowdi ku dhex dhaceen.

Waxaa jira laba qayb oo kale ee isticmaalayaal oo iska caadi ah. Kan kow waa nooca oo ku siigaysanaya sawira ama muuqaala oo laga qaaday cajalada galmada ugu dambeeyay dadka caanka oo wararka laga sheegay, mise ayyow wax oo ay ‘guriga uga keeneen’ daawashadooda ‘shilka ah’ schoolka ama shaqada. Kuwaan run ahaan waxay kaliya yihin dad oo isticmaale ahayn, laakin waxay u dareemayaan inay wax ka maqan yihiin. Waxay rabaan inay ka qayb qaataan falka, anagoo badankeena sidaan ku bilownay. Marka xigta, u fiirso in muddo ka dib uu qofka caanka oo khiyaaligaaga ah uusan mar dambe isla kicin kuu keenaynin. Inta ka badan uu qofka oo bartilmaameedka khiyaaligaaga tahay mid oo ‘aan la gaari karin’, inta ka badan ay ka-noqoshada orgasmka noqoto mid oo xanaaq badan. 

Qaybta labaad ayaa dhawaanahan soo jiidanaysay dareenka, iyadoo dulmarka sheekadaan oo onlinka lugu wadaagay ay tahay sida ugu wanaagsan oo taas lugu qeexi karo: 

Naag oo xirfadaysan ayaa sanado badan akhrisan jirtay sheekooyin porn iyo weligeeda ma isticmaalin wax oo ka weyn ama ka yar hal mar habeen kasta. Intaa waxaa dheer, waxay ahayd naag oo rabitaan-xoog badanayd. Isticmaalayaasha intooda badan waxay la yaabi lahaayeen maxay awalba u rabtay inay joojiso — iyadoo si faraxsan u sheeganayso inaysan jirin khatarta kacsi la’aanta oo porn keento, ama kacsi la’aanta markii xaaladeeda loo fiiriyo (taasi ay sheeganayso oo run ahayn). Maba isticmaalaynin sawirrada porn, iyagoo sheekooyinka ahaayeen waxyaala oo aad uga “khafiifsan” wax kasta oo ay iyaga naftigooda maalin walba isticmaalaayeen.

Waxay sameyaan khaladka oo isticmaalayaasha iska caadiga ah loo qaadanaayo inay ka farax badan yihiin ama inay ka xakam badan yihhin isticmaalkooda. Waa laga yaabaa inay ka xakam badan yihiin, laakin runtii ma faraxsan. Markii naagta xaaladeeda loo fiiriyo, naagta midna kuma qanacsanayn lamaanteeda mise galmada dhabta ah, oo ay si sare u xanaaqsan markay u jawaabta walbahaarada iyo dhibaatada oo maalmeedka ah. Kii oo ay ugu dhowayd, oo ay ugu jeclayd wuu fahmi waayay wixii oo iyada dhibaayay. Xataa markii ay si caqli-gali ah iskaga dhaadhicisa inaysan isticmaalkeeda ka cabsananin, waxay is aragtay iyadoo karti u lahayn inay ku raaxaysato xiriiraha jacaylka oo si aan la beddeli karin marmar u qabaan waqtiya sare iyo hoose. Xarunta abaalmarinta maskaxdeeda karti uma lahayn inay isticmaasha cadaadis-dejinta caadiga ah oo nolosha ku jiraan si natiijo ahaan ee daadashadaha dopaminka oo maalmeedka darteed. Hoos-u-dhaca xigta ee daawadayaasheeda dopamineka oo maskaxdeeda waxay iyada ka dhigtay, duruufaha badankooda, qof oo murgaysan. Sida dadka badan, waxay ka haysatay cabsi oo aad u weyn dhinaca shariga ee porn iyo sida oo naagaha loo la dhaqmaayo [muuqaalaha gudahooda] — intaysan iyada naftigeeda bilaabin. Ugu dambeyntii, waxay dhibane ku noqotay maskax-xadashada bulshada oo ay tijaabisay mareegteeda porn ugu horeysa. Si ka duwan kuwa oo is dhiibaan oo noqdaan isticmaalayaal oo meertaysan, isla markiiba ay aragtay muuqaalaha wasakha oo rabshaysan, way diiday inay simbiriiriixanta raacdo.

Waxa kaliya oo aad weligaaga porn ugu raaxaysan jirtay waa joojinta damaca oo daawashada ka hor bilowday, ha ahaato dareenka jireed oo u dhow in aan la dareemi karin, mise cadaabka maskaxeeda oo aan lugu ogolin inaad cuncunta iska xagato. Porn naftigeeda waa sun, taasi oo ay tahay sababta oo aad kaliya ku dhibaatoodo dhalanteedka raaxada waqtiyada ka-foognaanshaha ka dib. Iyadoo gaajada iyo harrada la mid ah, inta ka badan aad ku dhibaatoodo, inta ka badan ay raaxada noqonayso markii oo ugu dambeyntii la nafiso. Iyagoo isticmaalayaasha sameynayaan khaladka aaminsanaanta inay porn kaliya tahay caado, waxay u fikiraan: “*Haddii aan [isticmaalkayga] hoos ku hayn karo heer oo gaar ah ama kaliya intaan ku jiro dhacdooyin oo gaar ah, maskaxdayga iyo jirkayga way aqbalayaan. Markaas, waan sii waddi karaa isticmaalkayga iyadoo heerkaas joogto ama waxaan hoos u sii goyn karaa haddii aan sidaas rabo.*”

Maskaxdaaga ku caddey: ‘caadadaan’ waa wax oo jirin. Porn waa balwadda daroogo, iyadoo janjeerta isticmaalaha dabiiciga ah inuu xanuunaha ka-noqoshada iska nafiso, oo uu ahayn inuu u adkeysto. Inaad isticmaalkaaga ku haayso heerka oo aad hadda joogo waxaa laga baahanahay inaad isticmaasho is-edbin oo aad u badan iyo awooda-rabitaankaaga inta noloshaada ka hartay. Maadaama ay xarunta abaalmarinta maskaxdaada noqoto mid oo u dulqaadanaysa dopamine-ka iyo opioids-ka, waxay rabaysaa wax badan iyo wax ka badan, oo aanay rabin wax yar iyo ka yar. 

Maadaama ay porn bilaabto inay si tartiib tartiib kaa baabi’iso nidaamka neerfahaaga, geesinimadaada, kalsoonidaada, xamaynta rabitaankaaga-degega, waxaad si kordhaysan u noqotaa qof oo karti u lahayn inuu hoos u gooyo muddada oo u dhexeeyo fadhi kasta. Tani waa sababta, ee maalmaha hore, aan si dhibaata la’aan iska qaadan karno ama aan iska dhaafi karo. Haddii aan helno calaamad inay oo si maskaxeed ama jireed u khaldan, waa iska joojin jirnay. Naagtaan ha ka maseerin — markaad hal mar kaliya porn daawato labaatan iyo afar saac walba ka dib, waxay u muuqdaa inay tahay waxa oo Dhulka ugu qiimeysan, taas oo porn u beddesho ‘mira oo la mamnuucay’. Sannado badan, naagtaan miskeenta waxay ka dhexayd dagaal oo is jii-jiid.

In kasta oo ay karti u lahayn inay isticmaalka joojiso, waxay ku jirtay cabsi inay akhrinta porn si degeg ugu korto muuqaalaha live-ka ah. Labaatan iyo saddex saacadood iyo toban daqiiqood ee maalin walba oo maalmahaas ka mid ah, waxay ahayd inay la dagaasho duufshada porn, iyo dareen la’aanta ay u haysay ninkeeda. Waxay qaadatay awood-rabitaan oo aad u badan in la sameyo waxay ay iyada sameysay, taas oo ugu dambeyntii ooytin ka keenay. Xaaladaha oo noocaan ah waa naadir, laakiin sida caqli galaya u fiiri: ama waxaa porn ku jira taageero ana raaxa oo dhab ah, mise sidaas ma jira. Haddii ay jirto, yaa rabo inuu hal saac sugo, ama hal maalin, ama xataa hal toddobaad oo dhan? Maxaa keenaya in taageerta ama raaxada lagaa qaado intaad sugitaanka ku jirto? Sido kale, haddii ay jirin taageero ama raaxa oo dhab ah, maxaadba isku dhibay inaad u booqato haremkaaga halkii mar?

Halkaan waa sheeko kale ee nin oo ‘hal mar afartii maalmood’ ah, oo noloshiisa u sharaxaago sida soo socota:

> "*Afartan sano ayaan jiraa, waxaan ku dhibaatooday KLPK (kacsi la’aanta oo porn keento) intaan la jiro naagaha dhabta, iyo xataa markii aan porn isticmaalaayo, taas oo waqtiyada badankood ah. Muddo ayaa laga joogaa markii aan haystay kacsi oo si buuxda ah. Inta ka hor aan bilaabin porn qaadashada nidaamsan oo hal mar afarkii maalmood, waxaan si fiican u seexan jiray habeenka gudahiisa fadhigayga porn ka dib. Hadda waxaan soo kacaa saacad walba habeenka iyo waxay tahay waxa kaliya oo aan ka fikiri karo. Xataa markaan seexdo, waxaan ku riyoodaa muuqaalaha oo aan aada uga jeclaayay. Maalmaha oo fadhigayga porn ka dib, waxaan dareema dareen-hoose, iyadoo qaadashadayda la nidaamay ay si buuxda tamarta iga qaado. Naagtayda kaligayga ay i dhaafi jirtay waayo aan aad isku cuncunaayay iyo haddii ay idhaafi karin, iima ogoli jirin inaan guriga ku jiro. Banaanka ayaan orod-ahaan u baxaa [si aan wax kale isku mashquuliyo] laakin maskaxdayga way ku waalan tahay.*
>
> *Maalinta la qorsheeyay, waxaan bilaabayaa qorshaynta goor hore ee habeenka, anigoo aad u isku cuncuno haddii ay wax ka dhacaan qorshayaashayda. Waxaan ka bixi jiray sheekaysi walba oo aan markaas fadhigayga porn haysan jiray (aan kaliya hadhowti ka shalaayn jiray) anigoo shaqo ama guriga joogo. Aniga qof oo dood badan ma ihi, laakin ma rabi inuu mawduuca ama sheekaysiga hoos i xayiro. Waxaan xasuustaa marar oo aan dagaala nacas badan la bilaabi jiray naagtayda [si ay kaligayga iiga tagto]. Waxaan sugaa ilaa afar saac habeenimo iyo markay timaato, gacmahayga waxay si aan la xakami karin ay u gariirayaan. Hore kama bilaabo camalka — maadaama ay jiraan muuqaalal cusub oo lugu soo daray — waan iska ‘dukaameystaa’ agaarka mareegaha internetka. Maskaxdayga wuxuu ii sheegaa inaan u mudanahay muuqaal ‘gaar’ ah oo tahay inay ahaato mid oo u qalanto waqtiga oo aan ku qaatay raaditaanka maadaama aan afar maalmood isku gaajaysiiyay. Ugu dambeyntii, waxaan ku qancaa hal ama laba, laakin waxaan rabaa inay joogto si aan ku badbaadi karo afarta maalmood oo ku xigga, marka sidaas darteed waxaan qaataa waqti ka dheer inaan camalka ku dhamaystiro.*"  

Dhibaatooyinkiisa kale ka sokow, niinkaan oo miskiinka warba uma haayo inuu naftiisa sun isku siinooyo. Kowdi, wuxuu ka dhibaatoonooyaa ‘cillada miraha la mamnuucay’ oo uu markaas maskaxdiisa ku qasbaa inay dopamine daadiso. Barbardhig ahaan, daawadayaashiisa dopamine isla si hoos uma dhicin, laakiin wuxuu saliidayay simbiriiriixanta biyaha porn, isagoo raadinooyo edge-ka, cusaybta, kala duwanaanshaha, naxtinta, iyo walwasha si uu u badbaado afarta maalmood oo ku xigaan. Waxaa laga yaabaa inaad ninkaan uga fikirto qof doqon oo murugaysan, laakin sidaas ma aha. 
Maadaama uu ahaan jiray ciyaartooye oo markaas noqday qof oo saajinka ciidanka badeedka ahaan jiray, ma doonaynin inuu waxba ula qabatimo. Laakin markuu dagaalaha ka soo laabtay, waxaa loo tababaray inuu farsamayaqaanka macluumaadka tignoolajiyada ka noqdo barnaamij oo dhaqancelinta mujaahidaha. 

Markuu galay shaqada madaniga, wuxuu ahaayay farsamayaqaan macluumaadka tignoolajiyada oo xirfadaysan oo lacag fiican la siinaayay oo bangi ka shaqaya, iyo waxaa la soo siiyay laptop uu guriga gaysto. Taasi waxay ahayd isla sanadkii oo socialites-ka ay muuqaalahooda porn ‘faafiyeen’ iyo waxaa jiray wadahadal badan oo ku saabsan. Markaas wuu la qabatimay, isagoo ku qaadanaya inta noloshiisa ka haray isagoo is halligaaya jireed iyo maskaxeed-ahaan. Ninka haddii uu xaywaan ahaan lahaayay, bulshada mar hore ay isaga darxumeysigiisa ka bixi lahayd, laakin weliba waxaan u ogolaana inay dhalinyarta ula qabatimaan. Waxaa laga yaabaa inaad u maleyso inay sheekadaan iyo qoraalkaan yihiin waxyaala oo la soo buunbuuniyay, laakin sheekadaan — in kasta uu xad-dhaafsan yahay—aad ayuu ka fogsan yahay inuu sheeko gaar ahaado. Waxaa jira tobanaan oo kumamaan sheekooyin oo la mid ah. Ma hubtaa inaysan saaxiibkuwiisa iyo kuwa oo yaqaaneen midkoodna ka maseerin inuu markoo ahaayay nin oo ‘hal mar afartii maalmood’? Haddii aad u maleeyso inay sidaan kugu dhici karin, **naftaada ha khiyaamin.**

**WAYBA KUGU DHACAYSAA.**

Sida balwadaha kale, isticmaalayaasha porn waa beenoolo oo la og, xataa iyaga naftooda u been sheegaan. Way ku qasban yihiin inay sidaas ahaadaan. Isticmaalayaasha oo iska caadiga ah intooda badan waxay isticmaalaan waqtiyo iyo dhacdooyin oo aad uga badan inta ay qiran doonaan. Wadahadalada intooda badan oo lala yeeshto kuwaan oo isticmaalayaasha ‘laba mar halkii toddobaad’ la dhoho waxay qiranayaan inay isticmaaleen saddex iyo afar mar toddobaadkaas. Reddit-ka iyo NoFap-ka akhriso iyo sheekooyinka forum-yada oo dib-u-kicinta ee isticmaalayaasha oo iska caadiga ah. Waxa aad arki doontaa inay maalmo tirinayaan ama ay sugayaan inay guuldarraystaan. Uma baahnid inaad ka maseerto isticmaalayaasha oo iska caadiga ah, mana u baahnid inaad isticmaasho, nolosha waxay si aan xad lahayn u macdahay porn la’aanteed. Tusaale ahaan, qoraalkaan ka soo qaada:

“*Waxay ka bilaabatay caqabad oo fududaysan inaan hal maalin kaliya xubnaha tarankayga taabanin oo aan karti u lahayn. Siigaysashada mar dambe kama fikiri; fikrada madaxayga ma soo gala. Taasi way suurtogal tahay, waa kaa balan qaadaa. Hodantinimada oo sugto kuwa oo karti u leh — aad bay u caajiibsan yihiin.*”

Dhalinyarada guud ahaan way ka adkeysan yihiin in la daawayo, waayo aysan kaliya ahayn inay joojinta u arkaan inay adagtahay, laakin waayo ay sidoo kale aaminaynin inay ula qabatimeen ama inay ky ku jiraan maraxaalada dabinka oo horeeya, iyagoo guud ahaan ka dhibaatoodaan dhalanteedka inay si iswadda u joojinayaan intay maraxaalada labaad bilaabanin.

Waalidiinta caruurta oo porn nacaybaan—ma aha inay haystaan dareen amaan oo been ah. Caruurta dhan way nacaybaan pornka intaysan ula qabatimin. Hal mar, adiguna waad samaysay. Hana ku kadsoomin ololayaasha cabsida, dabinka waxay la mid tahay sida ay weligeeda ahayd. Caruurta way og yihiin inay porn tahay kicin xad-dhaafsan oo aan caadi ahayn, laakin waxay sidoo kale og yihiin inay hal ‘booqasho’ ama ‘fiirn’ ahayn wax oo ku filan. Heer markay gaaraan, waxaa laga yaabaa inay saameyn ka helaan lamaane, saaxibka fasalka, mise saaxibka shaqada. 

Fadlan arrintaan ha ku noqonin qof oo is cajabiyay. Guul darada bulshada inay ka hortagto inay dhalinyarada porn ula qabatimin waa dhinaca oo balwadaan ugu xun. Maskaxda dhalinyarada waxay yihiin kuwa oo si weyn ah uga jilcan, iyo way lagama maarmaan tahay in la baro oo la ilaaliyo. Haddiii aadan hubin meeshi oo aad ka bilaabi lahayd, kheyraada fiican waxaa ka mid ah buuga [YourBrainOnPorn.com](https://www.yourbrainonporn.com/so/) si aad u barato cilmi-neerfaha balwadaan. Xataa haddii aad ka shakisan tahay in dhalinyarkaaga laga yaabo inuu mar hore mu qabatimay, buugga wuxuu siinayaa fahamka aasaasiga ah oo ku saabsan caawinaadka inuu qof ka baxsado. Haddii kale, buugaan soo tali!
