# Isticmaalaha YouTube-ka / Twitch-ka / Instagram-Ka

Isticmaalahaan waxay ahayd in lala kooxeeyo isticmaalayaasha oo iska caadiga ah, laakin saameynta [ahaanshaha isticmaale oo kuwaan la mid ah] sida ay u qarsoodisan yihiin, waxay u qalmaan cutub kale oo gooni ah. Waxay u horseedisaa burburinta is-xakameynta, iyadoo u dhow inay furitaan u keento midkaan oo forumka NoFap isticmaalo:

> *"“Waxaan saddex toddobaad ku jiray isku-dayin oo ka mid ah isku dayinkaygii joojinta oo guul dareysteen, isku dayinka waxaa kiciyey walwalwasha naagtayda oo kacisigayga oo la isku helayn karin iyo xiiso la’aantayda ku saabsan. Waxaan u sheegay inay iyada sababta u ahayn, oo ay kaliya ahayd walbahaarka shaqada. Waxay dhehday: ‘Waan ogahay inaad mar hore iska xamili kartay walbahaarada shaqada, laakin sidee u dareemi lahayd haddii aad aniga ahaan lahayd oo ay ahayd inaad fiirsato qof aad jeceshahay isagoo si nidaamsan isku burburinooyo?’ Dooddaas waxay ahayd mid oo aan iska celin karin, iyo sidaas darteed: isku dayinka inaan joojiyo. Way ogtahay inaanan khiyaamaynin, laakin tan waxay aad taas uga sii daran tahay si ahaan. Isku daygii wuu dhamaaday saddex toddobaad ka dib, isagoo ku dhamaaday dood kulul oo aan saaxiib hore la yeeshay. Ma fahmin ilaa sanado ka dib inuu maskaxdayga dhagragaysan kas u kiciyay doodda, waqtigaas waxaan dareemay xanaaq oo qiil leh laakin ma aaminsani inay shil ahaayay maadaama aan weligayga saaxiibkaan gaarka ah ula dagaalamin, iyo sida markaas ka dib lama doodin. Waxay si caddeysan u ahayd shaqada shaydaanka yar.*
>
> *Si kastaba ha ahaatee, cudur daarkayga waa haystay. Waxaan si quus ah u baahnaayay sii dayntayda, dhibna ma leh sida aan ku helo. Naagtayda niyad uma lahayn galmada marka waxaan haystay dareeman ‘xaq-u-lahaansho,’ markaas waxaan iska dhaadhiciyay inay dhib lahayn haddii aan isku ‘xaddidido’ ka-foognaanshaha mareegaha porn oo aan ka jiro dhinacaan ‘khadka caska’ anigoo kaliya ka firsanaayo muuqaalaha YouTube. Laakin naagtayda waxay ugu dambeyntii ‘agagarka timaaday’ isagoo habeenka sii socday iyo waxay rabtay inay galmo sameyso, laakin waan daalay oo ‘xoogayga’ iga maqnaayay marka waxaan soo alifay inuu madax-xanuun i-haayo. Waan u adkeysan waayay inaan ka fikiro niyad-jabta tan ay naagtayda u keeni lahayd. Markaas waxaan si tartiib tartiib dib ugu laabtay dhaqankayga hore, iyadoo YouTube-ka noqotay harem-ka cusubta oo loo socdo. Waxaan xasuustaa anigoo waqtigaasi faraxsan, anigoo u maleeynaya inay ugu yaraan isticmaalkayga goynayso. Ugu dambeyntii, waxay igu eeday inaan iyada sariirta iskaga indha tirooyo. Ma garwaaqasnin, laakin waxay sharaxday mararka oo aan dooddad sababay oo aan guriga banaanka uga baxay. Waxay sharaxday anigoo marar kale laba saacadood qaadanaya inaan ‘gato wax oo yar’ iyo been abuurashada murgacshada. Waxaan sameyay cudur daarar oo daciif ah si aan uga baxo inaanan iyada kicio, marka markaan haysto harem oo aan isku halayn karo, aad bay u sii adkaanaysaa."*

Waxa oo isticmaalaha Youtube-ka ugu darran waa inay ahaanshaha xoojiso dhalanteedka oo maskaxdiisa ku jira in wax laga qaadaaya. Isla mar ahaanta, waxay keentaa dhuminta is-ixtiraamka oo aad u weyn; qof oo haddiise kale daacad ah ayaa laga yaabaa inuu isku qasbo inuu khiyaano qof uu jecel yahay. Waxaa u badan tahay inay sidaan kugu dhacday, ama ay weli si ahaan kugu dhacooso.

Dhibaatada oo lala kulmo mareegaha sida Twitch, Instagram, TikTok, Twitter (iyo warbaahinta bulshada intooda badan) waxaa waddo kaabitaanka. Iyadoo wadda damaca dopamine-ka cusayb-raadinta, isticmaalayaasha waxay isku khiyaamaan inay aaminaan inay mareeg  aamin ku jiraan. Xasuusnow: xamaasada waxay ku jirtaa ugaarsiga, ma aha dilka, iyo shaydaanka yar ma daneeyo meeshii uu hagaajintiisa ka keeno. Isticmaalaha, waxaalaha porn oo 'jilicsan' oolaga helay quudintooda online-ka oo kala duwan waxaa siinaysaa ka nasasho degdeg ah xanuunaha ka-noqoshada, iyagoo ku haanayaa qabatinka oo suugayaan fadhigooda xigta.

Jilada oo sawirka/muuqaalka ku jirta way runtii wa qurux badan tahay, iyo haddii aad hadda agtaada ku haaysan lahayd naagta, way runtii ku siin kartay raaxo, laakin sawirkaas [aad firsanayso] sidaas ma sameyn karo... Run maba aha. Maskaxaaga waxaa loo khiyaamaa sida dibida oo ku ordaya daaha casaanka, iyo ka dib ma fahmaya sababta uu u sameyay. Mid ayaa laga yaabaa inuu u maleeyo inaad markaas kaliya sawiradaas iska fiiri kartoo, adigoon ku siigaysanin. Laakin xasuusnow in maskaxaada ay la qabatimsan tahay cusaybta oo aan xadka lahayn, iyo shaydaanka yar ma daneeyo meeshii uu hagaajintiisa ka keeno. Waa isla dabin.

Waxaa laga yaabaa inaad daawatay taxanaha Tv-ga *Columbo*, mawduuca qayb kasta waa isku mid. Xumaanta qaybta, caadi ahaan, nin ganacsade oo hanti leh oo la ixtiraamo, ayaa dembi galey oo uu iska dhaadhiciyay inay ahayd dilka ugu qumman, iyo kalsoonidiisa in dembiisa la heli karin ayaa degdeg u koraa markuu arko in Baaraha Columbo, oo aadka u liidata iyo iska caadiga u muuqda, laga dhigay mas'uuliyada kiiska.

Colombo wuxuu qabaa dhaqankoo oo xanaajin badan markuu irida xiro warayska ka kib, isagoo hubiyay inuu tuhmanaha caddeyay. Laakiin wax yar ka hor marka oo qanacsanaanta ka baaba’a wajiga gacan-ku-dhiiglaha, Columbo ayaa dib u soo laabto, isagoo leh “*Hal arrin yar kaliya, mudane, oo aan hubay inaad sharaxi karto…*” Tuhmanaha wuu gariiraa, iyo wixii oo xiligaan ka dambeeyo wuu og yahay inuu Columbo isaga si tariib tartiib u daalin doono. Si kasta oo dembiga u fool-run yahay, wixii xilligaas ka dambeeyay, naxariista [daawadayaasha] waxay la jirtay gacan-ku-dhiiglaha.

Isticmaalka porn qaybtaas ay la mid tahay: xiisada in loo ogolaanin inay ka gudbaan khadka caska si ay u helaan hagaajinta porn oo ‘xaqa u lahaayeen, oo ay ka yaabaan meeshii ay raaxada ka jirtay markay camalka dhameeyaan ka dib. Cabsida inay ka gudbaan khadka caska, iyo inay xakameynta ka dhumto oo ay sariirta ku soo laabtaan, oo uu kaliya noqdo inuu cabsigaaga ku daba gasho inay lamaantaada galmo rabto. Muuqaalaha YouTube-ka oo ‘amaanka’ ah mar dambe kuma qancinaayan waayo dareen-yareesmada, cusayb la’aanta, iyo ogaanshaha la hubo inaad mar dhow ama hadhowti u booqi doonto haremkaaga. Bahdhilka iyo ceebta ugu dambeyaan oo markaas ahaanayso markay hubintaas ay xaqiiq noqoto, taas oo daba socoto dib u laabashado degdega ah daawashada meertaysan.

**Alla, Farxadda Ahaanshaha Isticmaale Porn!**
