# Caado Bulsheed?

Caafimaadka maskaxda iyo jirka waa inay sababaha ugu weyn ahaadaan oo aan rabno inaan joojino — in kasta oo ay weligooda ahaayeen. Runtii uma baahna cilmi-baaris cilmiyeed iyo cilmiga-neerfaha inay noo sheegaan inay porn qabatimsan tahay oo ay suurtogal-ahaan nolosheena u burburin karta. Jirkeena waa waxyaabaha oo meeraha ugu casrisan, iyo isticmaale walba wuu og yahay inta laga bilaaba fadhiga ugu horreynta inay kicinta xad-dhaafi karta oo ay markaas noqoto mid oo sun ah. 

Sababta kaliya oo aan porn weligeena ku lug lahaano waa is dulsaarka meertada ee barnaamijyada evolution-keena. Porn waxaa si sare loo heli karaa, iyadoo lacag la'aan ah oo toos loo daawan kara labaatan iyo afar saac. Waxaa jiray mar oo porn loo tixgeliyey mid oo waxyeello lahayn, laakin taasi waxay ahayd markii ay sawirra ahaayeen oo ay muuqaalaha u baahnaayeen inaad u safarto dukaan si aad u hesho cajalka VHS.

Maanta, waxaa guud ahaan loo tixgeliyaa — xataa ay ku jiraan isticmaalayaasha naftigooda — in porn ay tahay kicin xad-dhaafsan iyo qabatimsan. Waagii hore, ninka xooga leh ma qiri jirin inuu siigaysto, iyadoo ahaan jirtay eray oo bahdilid ah. Gudaha baar iyo kalab kasta, nimanka intooda badan waxay si ka faansan u rabi lahaayeen inay naag guriga gaystaan oo ay la sameyaan galmo dhab ah. Maanta, booska waxaa si buuxda loogu rogay balwadaha porn. Ninka oo maanta wuxuu ‘garwaaqsadaa’ inuu bilaabooyo inuu dareemo inuusan naagba u baahnayn. Iyagoo online iskugu dhegan, wuxuu ka wadahadlaa waayo-aragtinamadaha, wuxuu qorsheeyaa xeelahadaa iyo wuxuu baaraa fursadaha. Ninka oo maanta ma rabo inuu daroogooyin ku tiirsada. Kacaanka bulsheeda, isticmaalayaasha dhamaantooda waxay fikrad dhab ah siinayaan inay Porn joojiyaan iyo siigaysashada. Isticmaalayaasha maanta waxay porn u tixgeliyaan inay tahay hawlqabad oo waxtarta iyo waxyeellada lahayn.

Isbeddelida ugu muhiimsan oo forumyada laga arkay waa diirad saarida oo kordhayso ee dhinacyada lid-ku-aha-bulshada ee porn, maalmaha oo nin ka faani jiray inuu maalin kasta galmo sameyay ama orgasmgareeayay waxaa beddelay garwaaqsashada addoonsinimada shaydaanka yar ee porn. 

Sababta kaliya ay dadka u sii wadaan isticmaalka waxbarashadda ka dib waa inay ku guul dareysteen ama ay ka cabsan yihiin inay joojiyaan. Waxaa jira xiiso oo kala duwanaansho ballaaran oo mawduuca ku jira, iyagoo isticmaalayaasha qaarkooda ka foogadeen porn, siigaysashada, iyo orgasmka — ha la jiraan laamaanaha mise yee la jirin. Dhaqamadaha oo kala saaraan qaybaha galmada oo tantric-ga iyo faafinta sida xajinta shahwada iyo Karezza ayaa laga wadahadlaa itI waxaa si tirrada ka batay loo qaataa. Guul darada intooda badan oo hore loo sheegay waxay runtii yihiin horumaris, oo ay sidaas darteed xoogaa faa’iidayaan dadka oo ku dhaqmayaan. Mar haddii aad bilowdo wadada PMO-la’aanta, waxaad arkaysaa habboonta oo ugu fiican oo ku khusayso noloshaada; waa la dhiirigaliyaa inaad sameyso qorsheeyntaada ku saabsan orgasmkaee ka dib fahamka iyo ku dhaqanka kala saarida galmada. Si kasta wadadaada ha ahaatee, waxaad qiimo ku arkaysaa inaad xaddido mararka oo aad maskaxdaada kiimiko ku daadiso orgasmka, oo aad weligaaga porn, galmada, iyo orgasmka u arkin sida taageero naftaada oo qiiro leh.

Bulshooyinka online oo caanka ah ee kala duwan oo dadka isticmaalayaasha ahayn abuureen kaliya kuma ku heegansan joojinta porn laakin sidoo kale siigaysashada. Mareegahaan waxay ugu dambeyntii u faa’iido badan yihin kuwa oo doonaya inay baxsadaan, laakin badankooda waxay talinayaaan inay habka awooda-rabitaanka tijaabiyaan. Cawaaqib xumada ee ku-waalinta xariijinamada ka-foognaansha porn iyo tallaabooyinka kale waa isu-naxriista yo farxad la’aanshaha. Maskax-xadashada inteeda badan way soo haraysaa iyadoo nool oo fiicaan. Ugu dambeyntii, qofka niyadiisa wuu jabaa iyo waxaa dhacda saameynta domino, iyagoo isticmaalayaal kale ogaadaan inaysan kaligooda ahayn ee quusashada. Si kastaba ha ahaadee, dadaalkooda ma aha mid oo waxtar lahayn, khaladaadkooda ayay wax ka barbaranayaan [intay ku guda jiraan], in kasta oo ay jirta is-cadaabid maadaama ay browserkooda demiyaan oo laakin ay iska saaraynin dareemanka rabitaanka iyo u-baahnaanta. EasyPeasy si rogasho ayuu u shaqeeyaa, iyadoo kowdi ka saarayso dareemanka rabitaanka iyo u-baahnaanta intaysan ka hore browserka kaa deminin. Maalin walba, isticmaalayaal badan iyo ka badan ayaa ka tagaan markabka quusaaya iyo kuwa oo ku hareen waxay ka sii argagaxsan yihiin inay noqdaan kuwa ugu dambeya.

**HA U OGOLAANIN INAY ADIGA NOQOTO!**
