# Waqtiga Joojinta

Markii laga reebo arrinta cadda ee inay wax fiican kuu sameynaynin oo ay hadda tahay waqtiga saxada ah in la joojiyo, waqtiga joojinta way muhiim tahay. Bulshada waxay porn ula dhaqantaa sida caado oo xoogaa kharaahiysan oo caafimaadkaaga ka dhaawacaynin. Tan run ma aha. Waa balwada darooga, waa cudur iyo buburinaha xiriiraha oo bulshada ku jira. Waxa oo nolosha ugu xun isticmaalayaasha intooda badsn waa inay ula qabatimaan balwadaan oo aadka u xun. Waqtiga joojinta, sidaas darteed, way muhiim tahay si aad islu siiso xaqa oo aad ku hesho daaweyn oo habboonsan.

Kowdi ahaan, aqoonso waqtiyada ama dhacdkuwa oo ay porn kula muuqdo inay muhiim tahay. Haddii aad tahay qof ganacsade oo porn u isticmaalo dhalanteedka nafiska walbahaarka — waqti caajisan mise ciida dooro. Haddii aad tahay qof oo badanaa porn u isticmaalo intaad ku jirto xiliyo caajisnimo mise raaxaysi, lidkeeda ayaa khuseeya. Si kastaba ha ahaadee, isku-dayinka si dhab u qaado iyo ka dhig wixii oo noloshaada ugu muhiimsan.

Horay u fiirso saddex toddobaad mustaqbalka iyo isku day inaad odoroso dhacd walba oo laga yaabo inuu guuldarreysi u horseedi karo. Dhacdkuwa sida safarta shirkada, lamaantaada oo magaalada ka maqan, iwm., ka maa celin karaan inaad joojiso, ilaa iyo intaad mar hore odoraysay inay dhacaan si aad u dareemin in wax lagaa qaadaayo. Ha isku dayin inaad 'hoos u jarto' inta mudadaas lagu jiro maadaama ay kaliya abuuraysa dhalanteedka inay diidmada raaxaysi leedahay.Dhab ahaantii, waxay kaliya kaa 'caawinaysaa' inaad isku qasabto inaad daawato oo aad haysato inta fadhiyada porn oo suurtogal ah.Intaad haysanooso fadhiga porn ugu dambeysa iyo waqtiga ugu dambeya, ka digtownow dhergida oo niyad jabta keenayso, filashooyinka aan la fulin, xanuun walba oo jireed ah, saameynta ka-noqoshada, xanaajinta iyo murugta. Ka fikir sida aad wanaag u ahaanayso markaad isku ogolid inaad sameynta joojisid. 

**WAX KASTA OO AAD SAMEYSO, HA KU DHICIN DABINKA DHEHITAANKA, “HADDA MA AHA, HADHOWTII” OO AAD MASKAXDAADA KA BIXISID. XISAABI JADAWALKAAGA IYO XAMAASAD LEHOW SI AAD ULA SOCOTO.**

Xasuusnow: *waxba oo aad tanaasulayso ma jiro*. Lidkeeda, waxaad u dhowdahay inaad hesho faa’iid oo aad u cajiibsan. 

Sanado badan, xirfada caafimaadka waxay porn u aragtay mid oo dhib lahayn iyadoon ogayn kala duwanaanshaha porn khafiifka oo la soo dhaafay iyo waayo-argatinimada daawashada tooska oo virtual reality-ga oo ugu dambeeya. Dhibaatada waa: in kasta oo uu isticmaale walba porn qaato inuu iska nafiso damaca dopamine oo ay porn naftigeeda sababtay, ma aha balwada kiimikaha oo isticmaalaha qabsaday, laakin waa maskax-iska-xadashada oo natiijo ahaan balwada ka timaado. Qof oo caqliyeesan wuu ku dhici karaa khiyaanada, laakin waa kan doqonka kaliya oo weli ku sii dhacaya isagoo horeyba garwaaqsaday. Nasiib wanaag, isticmaalayaasha intooda badan doqon ma yihiin, oo laakin ay kaliya u maleeyaan inay yihiin. Isticmaale kasta wuxuu shaqsi ahaan u qabaa maskax-xadasho oo gaar ah. Taas waa sababta oo ay u muuqdo inay jiraan noocya balwadaha oo kala duwan, oo ay kaliya sii kordhisyo qarsoodiyaha.

Inta ay faa’iida buuga asalka ahayd in la joojiyo qaadashada nicotine (daroog oo ka mid ah kuwa ugu daqsiyaha badan oo ugu qabatinsan oo ku jira aqoonsiga bini’aadamka), waxay ahayd mid yaab leh in la garwaaqsado in falsafada buuga asalka ay weli u fiican tahay markii loo habeeyo balwada porn. Aqoonta iyo caqabada oo uruuraya oo aniga iyo Allen Carr aan la kulanno waa sida aqoontaas loo gaarsiin lahaayay isticmaale gaar oo kasta. Xaqiiqda inaan ogo inuu isticmaale kasta uusan kaliya joojinta u arki karo inay fududaysan tahay, oo ay laakin sidoo kale ku raaxaysan karo, ma aha inuu kaliya macno lahayn, laakin waxay sidoo kale si xad-dhaafsan u xanaaq badan tahay ilaa aan isticmaalaha laga dhaadhici karo. Buugiisa asalka, Allen Carr wuxuu sharaxayaa taladiisa oo murunka badan:

>*Dad badan ayaa ii sheegeen: “Waxaad dhehdaa, ‘Si wad sigaar cabitaankaaga ilaa aad buuga ka dhamayso.’ Tan waxay u janjeertaa inay sigaar cabbida ka dhigto inuu waqiyo aad u dheer ku qaato inuu buuga akhirsto ama inuuba dhamaysanin akhirnta. Waa inaad sidaas darteed tilmaamtaas bedesho.” Taas waxay u muuqdaa mid oo caqli-galaysa, laakin waan ogahay haddii tilmaamada ahaan lahayd: “Isla markiiba jooji”, sigaar cabidda qaarkood maba bilaabi lahayn inay buuga akhriyaan. Mar waxaa jiray sigaar cabbid oo ila tashtay maalmihii hore. Wuxuu dhehey, “Ciil ay iga haysaa inaan caawin kaa raadsada. Waan ogahay inaan rabitaan-xoog badanahay. Dhicayada kale oo dhan oo noloshayda, aniga aan xakameyaa. Waa maxay sababta sigaar cabiddaan dhan oo kale ay joojiyeen iyagoo isticmaalayaan awooda-rabitaankood, oo laakin ay tahay inaan adiga kuu imaado? Isagoo hadalkiisa sii wata wuxuu yiri, “Waxaan u maleeyaa inaan kaligayga sameyn kari, haddii oo lii ogolaan lahaayay inaan sigaar cabbo isla markiiba oo aan sameynaayay.”*

Aaminsanaanta bulshada waxay tilmaantaa in joojinta sigaar cabitaanka ay aad u adkeysantahay, marka waa muxuu sigaar cabbida rabaa markuu wax adag ku noqdo? Saaxibkeena yar, taageerteena. Ka-baxsashada sigaar-cabitaanka waxay u muuqdaa inay tahay dharbaaxo oo labanlaamsan: ma aha inay kaliya jirta hawl adkeysan oo la fulino — taas oo si ku filan u adkeysan — laakin sidoo kale taageerta oo aan caadi ahaan ku tiirsanaynay dhacdkuwaas ma la heli karo. Quruxda habkaan dhabta ah waa inaadan u baahnayn inaad wax ‘tanaasusho’ intaad habka dhex marayso. Taasi beddelkeeda, waxaan kowdi iska saarnaa cabsida iyo shakiga dhamaantooda, markaas isla markiiba oo aad dhammayso fadhigaaga ugu dambeeya, horey ayaad xoriyada ugu raaxaysanaysaa. 

Sidaas darteed, hackbuugaan wuxuu ilaalinaa inuu isla talo raaco. Si kasta oo loo sheego inay noqonayso mid oo fududaysan iyo raaxaysan in la joojiyo, waxaa jirayso aqlabiyad aad u badan oo karti u lahayn inay taasi aqbalaan, waayo maskax-xadashada oo shaqsi-ahaaneed ee sida ay u adag tahay joojinta.

*Waqtiga Joojinta* waa cutubka kaliya oo ii sababo inaan si dhab ah su’aal ka keeno talada asalka Allen Carr. Gaar ahaan markuu yiraahdo, tusaale ahaan, in haddii kiciyeyaasha rabitaanka porn ay ku jiraan walbahaarada xafiiska, inaad waqtiga ciida doorato si aad joojinta isku daydo, iyo lidkeeda in kale. Tan ma aha habka ugu fudud, oo ay lidkeeda tahay inaad doorto waqti oo aad u tixgeliso midda ugu *adag*. Ha ahaatee waqti walbahaarsan, waajibaadka bulshada, diirad saarid ama caajisnimo, mar haddii aad caddeyso inaad nolosha la qabsan karto oo aad ku raaxaysan karto adigoo ku jirto xaaladaha ugu xun, xaalad kasta oo kale way raaxaysi badan yihiin. Laakin haddii ay talada sidaas ahaan lahayd, ma sameyn lahayd isku dayga?

Halkaan waa isbarbardhig: aniga iyo walaashayda waxaan damacsanahay inaan isla dabaalano. Isku mar ayaan imaanaa barkadda dabaasha, laakin way dhif tahay inay noqoto inaan isla dabaalana. Sababta oo ah inay hal suul biyaga gelinayso oo ay nus saac ka dib runtii u dabaalanayso. Taas waa cadaab oo tartiibsan. Ka hore ayaan ogahay markay heer gaarto, si kasta oo ay biyaha u qaboob tahay, inay noqonayso inaan geesi noqdo. Marka waxaan u bartay inaan habka fududa u sameyo: inaan si toos ah ugu dhex boodo. Hadda ka soo qaad inaan ku jiro booska inaan ku adkeysiiyo haddii iyada ay si toos ugu boodaynin, inaysan dabaalan karin. Haddii ay sidaas ahaan lahayd, gabi ahaanba ma dabaalan lahayn. Dhibaatada ma arkaysaa?

Jawaab celinta laga keenay, isticmaalyaal oo badan ayaa talada waqtiga asalka u isticmaaleen si ay dib u dhigaan wixii ay u maleeyaan 'maalinta sharka ah'. Fikradahayga ku xigta waxay ahaayeen inaan isticmaalo xeelad oo cutubka "faa'iidk porn" la mid ah, wax oo la mid -- "*Waqtiga joojinta aad bay u muhiimsan tahay iyo, cutuba xigta, waxaa luguu talinaa waqtiga ugu fiican inaad isku dayga joointa sameyso.*" oo ay cutubta xigta kaliya ku jira qoraalka weyn *"HADDA!"*. Taas waa, dhab ahaantii, talada ugu fiican, laakin ma qaadan lahayd? Dhinaca dabinka uga qarsoodisan waa markaan nolosheen ku qabno walbahaar oo dhab ah, ma aha waqtiga saxda in la joojiyo, laakin waqtiyada oo aan walbahaarka qabin, rabitaanka inaan cadaabka iska joojino ma qabno. Is weydii su’aalaha oo soo socdaan:

1. Markaad porn isticmaashay markii kugu horreyay, runtii ma go’aansatay inaad sii wadayso inaad ku tiirsato inta noloshaada ka hartay oo aan weligaaga karti u lahaanaynin inaad joojiso? ***Dabcan, ma go’aansanin!***

2. Ma sii wadaysaa inta noloshaada ka hartay adigoo karti u lahayn inaad joojiso? ***Dabcan, ma sii wadaysid!***

Marka gormay joojinay? Berrito? Sanadka ku xigga? Sannadka oo kaas ka xiga? Sidaas ma ahaynoo wixii oo aad is weydiinaysay sida markii oo aad kowdi garwaaqsatay inaad qabatimtay? Inaad hal subax soo kici doonto adigoon rabin inaad weligaaga daawato mar dambe maad rajaynaysaa? Naftaada ka khiyaamin, balwad kasta waxaad sii tartiib tartiib qabatimay, oo aanay yaraanin. Ma sugaysaa ilaa aad dhab ahaantii bilawdo inaad dareemto inay sariirta ka soo kicida ay ka adag badan tahay siigaysashada? Taasi waxay ahaan lahayd wax oo xoogaa macno lahayn. 

Dabinka oo runta waa aaminsanaanta inay hadda waqtiga saxda ahayn -- oo ay weligeeda berrito ahaanayso mid oo ka fududaysan. Waxaan aaminsanahay inaan nolol walbahaarsan haysano, laakin aan dhab ahaantii haysanin. Walbahaaraha dhabta intooda badan nolosheena ayaa laga saaray. Markaad guriga ka baxayso kuma noosho cabsida inay xaywaanaha duurjoogta ku soo weeraraan, isticmayaasha intooda badan kama fikiraan meeshi ay cuntadooda xigta ka imaanayso, mise haddii uu saqaf madaxooda ka sareenaya habeenkaan. Ka fikir noloshada xaywaanaha duurjoogta ah: Mar kasta oo bakayle ka soo baxo godkiisa, wuxuu wajahayaa Vietnam inta noloshiisa oo dhan si uu u noolaado. Laakin bakaylaha wax ayuu xaladaas ka qabtaa, wuxuu qabaa adreneline iyo hormoonada, oo anaguna haysano. Runta waa: mudada ugu walbagaarsan nolosha makhluuqa carurrnimada hore iyo dhalinyarada. Saddex biliyan sanadood oo xulsahada dabiiciga waxay nugu qalabnaysay inaan walbahaaraha la qabsano, iyo dad badan oo ku soo koreen caruurnimo oo adag ah waxay horseediyaan nolol oo caadi ah.

Waa cliche in la dheho, “*Haddii aad caafimaadkaaga haysanin, waxba ma haysato*” laakin gabi ahaan way run tahay. Markaad xoog dareento jir-ahaan iyo maskax-ahaan, dareemaha sare aad ku raaxaysan kartaa iyo kuwa hoose waad iska xamili kartaa. Dad badan waxay isku qasaan mas’uuliyada iyo walbahaarka; mas’uuliyada waxay kaliya walbahaarsan noqotaa markaan dareemaynin inaan xoog ku filan leehnahay inaan xamilno. Waxa oo inta ugu badan burburiyo ma aha walbahaarka, shaqada mise waayeelnimada, oo laakin ay tahay taageeraha dhalanteedka, oo beenta sheegaya oo ay u jeestaan.

Sidaan u fiiri — hore ayaad u go’aansatay inaadan dabinka ku jiraynin inta noloshaada ka haray. Sidaas darteed, markay heer gaarto — ha ahaatee inaad u aragto fudud ama adag — waxay noqonaysaa inaad dhex marto habka xoriyad ka noqoshada. Porn caado iyo raaxo ma aha, waa balwad iyo cudur. Waxaan dejinay in, si ka fogsan inay fududaato berrito, ay si khordheysan uga sii dari doonto. Waqtiga oo la iska takhluso waa **hadda** — ama inta hadda u dhow oo aad maamuli karto. Ka fikir sida dhaqsaha badan toddobaad kasta oo nolosheena ka mid ah uu na dhaafo. Waa halahaas kaliya waxay qaadanayso. Ka fikir sida ay u fiicnaan doonto inaad ku raaxaysato inta noloshaada ka haray isagoon hadhkii oo weligiisa-khordhaya oo kaa sareeya. Ilaa inta aad raacdo tilmaamaha dhamaantood, xataa uma baahnaanayso inaad shan maalmood ama saddex toddobaad sugto. Ma aha inaadan kaliya u arki doonto inay fududahay in la joojiyo, **Waad ku raaxaysan doontaa!**

