# Uma xiisi doonaa baashaalka?

**Maya!** Mar haddii uu shaydaanka yar dhinto, oo uu jirkaaga joojiyo damaca dopamine, oo ay simbiriiriixanta biyaha porn si daqsasho u bilowdo inay baaba’do ee la’aanshaha ‘saliidaynta’ darteed, maskax-xadasho oo dhan oo soo hartay way baaba’aysaa. Ma aha inaad kaliya is arkayso adigoo si ka fiican u qalabaysan jir-ahaan iyo maskax-ahaan inaad xamisho walbahaarada nolosha, laakin waxaad sido kale si buuxda ugu raxaysanaysaa waqtiyada fiican. 

Waxaa kaliya jira hal khatar, taas oo ah saameynta kuwa oo weli galmada u isticmaalaan sida taageertooda iyo raaxadooda. ‘*Ninka kale cawskiis ayaa weligiisa ka cagaar badan*’ way ku caadi tahay dhinacya badan nolosheena iyo waxay tahay wax oo si fudud badan loo fahmi karo. Waa maxay inta lagu jira arrinta porn — iyadoo faa’iido darrooyin waaweyn leh markii loo barbardhigo ‘faa’iidooyinka’ oo dhalanteedka ah — uu isticmaalaha hore u janeeraa inuu ka maseera kuwa oo dalbanaya galmo iyo porn sida taageera? 

Maskax-xadashada oo dhan ee caruurnimada, waa mid oo la fahmi karo inaan dabinka ku dhacnay. Waa maxay sababta markaas — ka dib markaan garwaaqsanay sida ay porn u doqonnimo tahay, oo aan markaas maamulnay inaan iska saarno —oo aan si toos ah dib ugu laabano isla dabinkii? Waa saameynta maskax-xadashada bulshada oo porn ku khaldayso galmada, taas oo loo soo bandhigo sida wax oo caadi ah. Isticmaalaha hore wuxuu qabaa xanuun ka noqosho! Dareemanka maranka oo kalsooni la’aanta ahaanshaha qof doob ah (taas oo dembi ahayn si kasta ha ahaadee) wuxuu keenaa dareeman walaaca, oo ay markaas iyaga u waddo inay simbiriiriixanta biyaha raacaan. Tan waa runtii wax oo yaab leh oo caadi ahayn, gaar ahaan haddii u fiirsashadaan la tixgeliyo: ma aha kaliya in kuwa oo isticmaalayaasha ahayn ay ku faraxsan yihiin inay sidaas ahaadaan, laakin kuwa oo isticmaalayaasha ah oo dhan xataa iyagoo leh maskaxdooda leexleexsan, qabatimsan, oo laga xaday, oo ka dhibaatoonooya dhalanteedka baashaalka iyo raaxaysi, waxay jeclaan lahaayeen inaysan kowdi weligooda ula qabatimin. Marka, maxaa keenaya inay isticmaalayaashii hore qaarkood inay ka maseeraan?

1.  ‘Hal fiirin kaliya.’ Xasuusnow, taas wax oo jirin. Jooji inaad aragto munaasabadda go'doonsan oo bilaw inaad ka eegto aragtida isticmaalaha porn. Waxaa laga yaabaa inaad ka maseyreyso, laakiin iyaga ma aqbalaan naftooda, wayna kaa maseraan. Haddii kaliya aad si kiliinig ah u fiirsan kartay isticmaale kale, maadaama ay noqon karaan kobcinta ugu awooda badan dhammaan si ay kaaga caawiyaan inaad ka baxdo. U fiirso sida ugu dhaqsaha badan ee ay u furaan tabs badan iyo browserkuwa? Iyagoo si degdeg ah hore u socdaan qaybaha muhiimkuwa, oo si dhaqsaha uga caajisaan muuqaalaha oo dhex marayaan noocyada dhan oo soo saaraan cusaybta, naxtinta, walaaca, iwm. Gaar ahaan u fiirso in falalkuwa u muuqdaan ay yihiin kuwa oo iswaddo. Xasuusnow — kuma raaxaystaan, waa inaysan naftooda ku raxaysan karin la’aanteed. Subaxda xigta, iyagoo ku soo kacaan rabitaan daciifsan, tamar khasaartay oo idha cadeynayaan, waa inay sii waddan inay is ceejiyaan mar walba oo ay walbahaar iyo cadaadis soo muuqadaan. Waxay la kulmayaan nolol oo wasakh, caafimaad maskaxeed darro iyo kalsooni darro — nolol oo iyagoo is burburinayaan oo uu hadh madow ku jira maskaxdooda gadaasheed. Si loo gaaro ujeedadee? Dhalanteedka inaad helooso wixii oo aad u ‘mudan’ tahay iyo raaxaysi oo habaarsan?

2.  Sababta labaad oo ay isticmaalayaashii hore u qaabaan xanuun ka-noqosho waa inuu isticmaalaha porn wax sameynaya - sida is-raaxaynta - oo isticmaalaha hore uu sameynaynin, oo uu markaas dareemo in wax laga qaaday. Maskaxdaada ku caddey, ma aha qofka oo isticmaale ahayn oo wax laga qaadaya, laakin waa balwadaha porn oo miskeenka ah oo laga qaadaya:

    -   Caafimaadka

    -   Tamarta

    -   Kalsoonida

    -   Nabada Maskaxda

    -   Geesinimada

    -   Xasilloonida

    -   Xoriyada

    -   Is-ixtiraamka

Ka bax caadada inaad ka maseerto isticmaalayaasha porn iyo ka bilow inaad u aragto makhluuqa darxumeysan, iyo murugaysan ay runtii u yihiin. Waan ogahay, waxaan mar ahaayay mid ka mid ah kuwa ugu darran. Taas waa sababta oo aad buugaan u akhrinayso, oo ay kuwa kale ahayn oo runta isku sheegi karin oo sii waddaan inay naftooda khiyaamaan. 

Kama maseeri lahayn balwadaha heroin-ka, iyo sida balwadaha daroogiinkuwa oo dhan, balwadaada waxba kama fiicnaanayso. Sanad kasta wuxuu si khordhaayo uga sii darraa — haddii aanan ku raaxaysanaynin ahaanshaha isticmaale maanta, waxaad sii ka yar ugu raaxaysanay berrito. Ha ka maseerin isticmaalayaasha oo kale, ka naxariiso. I aamin: ***Naxariistaada way u baahan yihiin!***
