# Ka Fogow Dhiirigalinta Beenta Ah

Isticmaalayaal badan oo ku jiraan habka awooda-rabitaanka waxay isku dayaan inay dhiirigalintooda ku badiyaan dhismada dhiirigalin oo been ah. Waxaa jira tusaalooyin badan oo sidaan oo kale, mid ka mid ah kuwa caadiga oo ah inay naftooda ku abaalmariyaan hadiyado ka dib markii aysan hal bil porn daawanin. Tan waxay u muuqdaa mid oo caqli-galaya oo hab maacquul ah laakin dhab ahaantii been ay tahay, waayo uu isticmaale walba por is-ixtiraamo wuxuu doorbidi lahaayay inuu sii wato daawashadiisa porn maalin walba intuusan isku abaalgudi lahaayay hadyad oo uu is siiyay. Tan shaki bay maskaxda isticmaalaha ku abuurtaa, waayo ma aha inay kaliya tahay inuu isticmaalaha ka-foogada *sodon maalmood*, laakin sidoo kale maba hubo xataa haddii uu sodonkaas maalmood porn la’aanteed ku *raaxaysanaaya*. Raaxadiisa iyo taageertiisa uu kaliya haystay ayaa laga qaaday! Waxa kaliya oo tan sameynaysa waa inay kordhiso cabbirka huridda oo isticmaalaha dareemo uu sameenaaya, oo ay hadda porn noqotay wax oo ka sii qiimeysan gudaha maskaxdiisa.

Tusaalooyin kale waxaa ka mid ah:

-   Waxaan u joojinayaa si ay igu qasabto inaan yeeshto nolol bulsheed, oo aan sameyo galmo ka badan.

-   Waxaan u joojinayaa si ay nooc tamar sixirsan iga caawisa inaan ka hormaro tartamaaysha oo aan helo lamaanta aan rabo. 

-   Waxaan u joojinayaa si aan naftayda diirad saaro inaan tamarayda iyo xamaasadayda porn ku khasaarinin si aan naftayda dhiirigalinya ku koriyo.

Kuwaan run bay yihiin, waxna way taraan, iyo waxaa lagaa yaabaa inaad hesho wixii oo aad rabtay — laakin hal daqiiqad ka fikir. Haddii aad hesho wixii oo aad rabtay, mar haddii ay cusaybta baxdo, waxaad dareemaysaa in wax lagaa qaaday; iyo haddii aad helin, waxaad dareemaysaa darxumeysi. Si kastaba ha noqoto, mar dhow ama hadhowti ayaad dabinka ku dhex dhici doontaa.

In joojinta lala xiriiro dhiiriegalin oo been ah waxay kaliya kordhinay shakiga, waayo haddii aadan ku guuleysanin dhiirigalintaada (iyo xataa haddii aad hesho) waxaad bilaabaysaa inaad ka fikirto fikrad oo shakisan sida: “*Miyay joojinta dhab ahaantii noloshayda ka dhigaysaa mid oo ka fiican? Haddii aan joojiyo oo aan helin wixii oo aan rabay, habka si saxsan ma u isticmaalay?*” Fikradaha sidaan oo kale waxay kordhiyaan dareemanka hurrida oo ay sidaas darteed abuuraan xanuunaha ka-noqoshada. 

Tusaale kale oo caadi ah waa axdi galida online-ka ama forum-yada. Kuwaan waxay qabaan faa’iidooyinka ee iska saarida duufsashada muddooyinka gaarka ah. Laakin, waxay guud ahaan u guul dareystaan sababaha oo soo socda: 

1.  Dhiiriegalinta waa been. Maxaad u dooni lahayd inaad joojiso waayo kaliya ay dadka kale sidaas samaynayaan? Waxa kaliya oo ay sameenayso waa abuurinta cadaadis dheeraad oo ay khordhiso dareenka hurrida. Way iska fiican tahay haddii ay isticmaalayaal badan si daacad u doonaayan inay isla waqti gaar ay joojiyaan — laakin kuma qasbi kartid inay joojiyaan, in kasta oo ay dhamaantooda si qarsoodisan u rabaan. Ilaa ay diyaar u yihiin inay sidaas sameyaan, axdi wuxuu abuuraa cadaadis oo dheerad ah, oo kaliya khordhinaya damacood inay daawadaan. Kaas wuxuu iyaga ka dhigaayaa daawadayaal oo qarsoodisan, oo uu sii kordhinaysa dareenka ku tiirsanaanta.

2.  In la isku tiirsado midba midika kale isagoo la isticmaalaya habka awooda-rabitaanka wuxuu abuuraa dareemanka in la dhex marooyo muddo oo cadaabsan, inta lagu jiro taas oo ay sugaan damaca inay ka baa’bada. Haddii ay ka quustaan, waxaa jiraysa dareen guuldarreysi. Markii la isticmaalaya habka awooda-rabitaanka waa qasab inay jiraysa hal ka qaybgale oo ka quusanaaya, taas oo siinaysa ka qaybgaleyaasha kale cudur daarka ay sugaayeen. Ma aha khaladkooda, way u adkeysan lahaayeen laakin ‘Cali’ baa niyad jebiyay. Runta waa in badankooda ay mar hore khiyaameen.

3.  In amaanta la isla wadaaga waxay tahay dhibaato oo lid ku ah dhibaatada ku tiirsanaanta. Waxaa jiraya dareen guuleysi oo cajiibsan oo ku jira joojinta porn, iyo markaad kaligaaga sameynaysa, amaanta oo aad saaxibadaada ka hesho iyo kuwa online waxay noqon kartaa dhiirigalin oo aad u weyn intaad ku jirto dhowr maalmaha ugu horreya. Laakin markii ay dadka oo dhan isla waqtigii sameynayaan, amaanta waa in la isla wadaaga iyo sidaas darteed dhiirigelinta hoos bay u dhacay.

4.  Tusaale kale waa balantii inay joojinta sheekh kaa dhigayso. Joojinta waxay ku siisaa farxad waayo aad mar dambe ku jirin dagaalka is jii jiida, iyadoo maskaxdaada ay bilaabto dib u habaynta oo ay dib u hesho xakameynta rabitaan-degdega. Si kastaba ha ahaatee, was inaad maskaxdaada ku haysa inay tan ka dhigaynin qof oo galmada ku xirfadaysan ama guulayste bakhtiyaa nasiib. Qof oo adiga ahayn ma jiro oo kaa daneeyo haddii aad porn joojiso. Ma tihid qof daciifsan haddii aad porn isticmaalaysa saddex mar halkii maalmood oo aad qabto kacsi la’aanta oo porn keento, iyo sidoo kale aad ahayn qof xoog badan haddii aad tahay balwad oo calaamadahaas ka dhibaatoonin.

Khiyaanada naftaada iska jooji. Haddii ay shaqada la soo bandhigay ee shaqada toban bilood oo aad ka helaysa mushaharka sannadlaha laba iyo toban billood, ama khataraha hoos u goynta kartida maskaxdaada inay la qabsato walbahaarada iyo cadaadiska maalmeeda, ama ka soo horjeeda inaad haysato kacsi oo la isku halayn karo, mise waqti nololeeda cadaabka iyo addoonsiga maskaxeeda iyo jireedka ay iyaga ka celin waysay isticmaalka porn, dhowr dhiirigalinta nacaska ah oo hore la sheegay waxba kama caawinayaan inay joojiyaan, oo ay kaliya ku guuleysanayaan inay huridda ka dhigan mid oo si ka darran u muuqda. Taas beddelkeeda, dhinaca kale xoog saar:

\"Maxaan ka helayaa? Maxaa u baahanahay inaan porn daawado?\"

Sii fiiri dhinaca kale dagaalka is jii jiida iyo is weydii maxay porn kuu sameynaysaa. *GABI AHAAN, WAXBA!* Waa maxay sababta oo aan u baahanahay inaan sameyo? *UMA BAAHNID! NAFTAADA KALIYA AYAAD CADAABAYSAA!* Waa Wagerka Pascal: waxay u dhowdahay inaad waxba haysanin oo kaa khasaaraya (markii laga  reebo kacsiga oo la isku halayn karin), oo aad hesho fursado faa’iidooyin waaweyn (sida: kacsiga la isku halayn karo, wanaaga maskaxeed iyo farxad), oo aad fursado haysanin inay wax weyn kaa khasaarto.

Marka maxaa diidaaya inaad joojintaada u dhawaaqdo saaxibadaada iyo qoyskaaga? Hagaag, waxay kaa dhigaysaa balwad hore ama isticmaale hore oo kalsooni badan, oo laakin uu kaa dhigaynin qof faraxsan oo isticmaale ahayn. Waxaa laga yaabaa inay lamaantaada ka cabsiisa maadaama oo laga yaabo inay kan u aragto qorshe inaad galmo ka badan la sameyso. Waxaa sidoo kale laga yaabaa inay ka cabsato inaad noqonooso mashiin galmeed. Waa wax adag in loo sharaxo mooye ay maskax furan yihiin. 

Isku dayin kasta inaad dad kale keento inay ku caawiyaan inaad joojiso waxay awood badan siinaysaa shaydaanka yar. Inaad maskaxdaada ka riixdo oo aad iska dhega tirto waxay wadataa saameynta oo aad isku daydo *inaadan* ka fikirin. Ka digtownow taas beddelkeed, isla markii oo aad aragto fikrada, ama kicinta (side: markaad gurgigaaga kaligaaga joogto), ama fikrada iyadoo maskaxdaada maqan tahay, isku sheeg: “*Wacan, mar dambe mi igi addoonka porn. Waxaan ahay xor iyo faraxsan inaan ogaado qaybaha kala duwan ee galmada.*”  Tan waxay ogsijiinka ka goynaysaa fikrada oo ay ka joojiso inay noqoto rabitaan iyo damac. Dhinacaan markii loo fiiriyo, inaad meditationka dignaanta ku dhaqanto waxay kaa caawin kartaa shaqsi-ka-saarida fikradaha. 
