# Habka Fudud oo lugu Joojiyo

Cutubkaan wuxuu ka kooban yahay tilmaamo oo ku saabsan habka fudud oo lugu joojiyo isticmaalka porn. Ilaa intaad raacdo tilmaamaha, waxaad ogaan doontaa in joojinta ay u dhaxayso mid fudud ilaa mid oo lagu raaxaysto! Ilaa intaad raacdo tilmaamaha hoose, waxay si qosol leh u fududahay in la joojiyo isticmaalka porn. 

Waxa kaliya oo ay tahay inaad sameyso waa:

1.  Go'aaminka gaar inaadan weligaaga porn daawanaynin mar dambe.

2.  Ha ka murugoonin. Ka faraxsanow!

Waxaa laga yaaba inaad dhehooso, “*Maxaa loogu baahan yahay buugga intiisa kale? Maxaadan kowdiba sidaas sheegi waysay?*” Hagaag, jawaabta waa inaad ugu dambeyntii ka murugoon lahayd oo aad sidaas darteed go’aantaada beddeli lahayd. Waxay u badan tahay inaad sidaas sameysay marar badan ka hore.

Sida hore loo sheegay, porn waa dabin xun oo qarsoodisan. Dhibaatada ugu weyn ee joojinta ma aha balwada dopamine — taas oo hubaal dhibaato ah, oo laakin ay ahayn tan ugu weyn —waa maskax-xadashada. Sidaas darteed, waa lagama maarmaan in kowdi la burburiyo quraafadooyinka iyo dhalanteedkuwa oo dhan. Cadowgaaga faham, xeeladahooda ogow, markaas waxaad si fudud uga adkaan doontaa. Anigoo qaybo badan oo noloshayda ah ku qaatay niyad-jab madow anigoo isku dayaya inaan joojiyo, markii aan isla markiiba ka baxsaday, toos ayaan eber ka dhigay isticmaalkayga, anigoon haysnin hal daqiiqad oo xun. Waxay ahayd mid raaxaysan xataa markaan xiliga ka-noqoshada dhex maraayay iyo, tan iyo markaas, weligayga ma haysanin xanuun ka noqoshada ugu yar. Taas lidkeeda, waxay ahayd mid ka mid ah waxyaalaha ugu fiican oo nolshayda gudaheeda ku dhacay.

Isku dayinkayga ugu dambeeya waxay ahayd mid ka duwan. Sida isticmaalayaasha dhan oo maalmahaan, waxaan dhibaatada fikrad halis Ku siiyay maskaxdayda. Ilaa iyo markaas, anigoo guul dareystay ka dib, caado bay ahayd inaan isku qalbi qabooyiyo fikrada inay noqonayso mid oo ka fududaysan marka xigta. Weligayga kama fikirin inay ahaanayso inaan sidaan ku socdo inta noloshayda ka haray. Fikradaas waxay iga buuxisay cabsi iyo waxaan bilaabay inaan aad uga fikiro mawduuca.

Halkii aan si miyir-daboolan ugu kicin lahaayay browserka, waxaan lidkeeda falanqeeyay dareemankayga oo aan xaqiijiyay wixii oo aan mar hore ogaayay: Porn kuma raaxaysanin iyo waxaan u arkaa wax wasakh oo laga yaqyaqsoodo. Waxaan bilaabay inaan fiiriyo dadka oo isticmalayaasha ahayn oo qaybaha aduunka kale ku noolaan, ama dadka waayeelka oo weligooda baranin mareegaha porn. Ilaa iyo markaas, waxaan had iyo jeer dadka isticmalayaasha ahayn u tixgelin jiray inay yihiin dad daciifsan, aan lala hadali karin, ama xanaaqsan. Laakin markaan baari jiray sida ay u muuqdaan, waxay u muuqdeen — haddii ayba wax u muuqdaan — sida dad oo ka xoog badan oo ka raaxaysan. Waxay u muuqdeen inay la qabsan kareen walbahaarada iyo cadaadiska nolosha oo ay u muuqdeen inay si ka badan uga raaxaystaan kulan bulshada ee isticmaalayaasha porn. Waxay si hubal u haystaan soo jiidasho iyo xamaasad oo ka badan.

Waxaan bilaabay inaan la hadlo isticmaalayaashii hore. Ilaa iyo markaas, waxaan had iyo jeer iyaga u tixgeliyay sida dad oo lagu qasbay inay ka tanaasulaan sababo caafimaad ama diin-ahaan darteed oo ay had iyo jeer si qarsoodisan u damacaayeen boqashada haremka. Dhowrkood runtii waxay dheheen, “*Waad haysanaysaa xanuun ka-noqosho marmarkoo, laakin aad bay u yar yihiin iyo aad bay u fog yihiin oo ay u qalamaynin in la isku dhibo.*” Laakin badankood lidkeeda waxay dheheen, “*Aniga maa u porn xiisaaya? Waad igu ciyaaroosa! Noloshayda weligeeda kama ficnaanin!*” Xataa guul darooyinka ayaa horumaris u ahaayay iyaga — naftooda ma cambaaraynin oo ay lidkeeda shuruud la’aan aqbaleen. Waxay yihiin sida macalin oo ogolaya ciyaartooye dahab ah inuu khaldo. Inaan la hadlo isticmaalyaashii hore waxay burburisay quraafad oo aan had iyo jeer ku haayay maskaxdayda: in daciifnimo ay dabeecad-ahaan igu jirtay, ilaa ay ii cadaatay in istimaalayaasha dhamaantooda ay dhex maraan qarowgaan gaarka ah. 

Asal ahaan, waxaan is dhehey, “*Dad badan ayaa hadda joogsanaya oo ku nool nolol farxad leh, mana u baahnayn inaan sameyo ka hore intaanan bilaabin iyo waxaan xasuusan karaa anigoo aad u dadaalooyo inaan waskhdaan la qabsado. Marka, maxaan hadda ugu baahanahay?*” Sidaasba ha ahaatee, porn kuma raaxaysanin, anigoo nacaybaayo caadada wasakhda oo dhan oo aan rabin inaan ku qaato inta noloshayda ka haray addonsiga balwadaan oo laga yaqyaqsoodo. Waxaan markaas is dhehey:

“*Jeclow ama ha jeclaanin, waxaad dhamaysay fadhidaaga ugu dambeeya.”* 

Sidi markaas ayaan ogaayay inaan weligayga mar dambe fadhi kale haaysanaynin. Ma filaynin inay ahaanayso mid fudud, oo ay kaliya ahaanayso lidkeeda. Waxaan si buuxda u aaminsanaayay inaan naftayda u saxiixay bilooyin oo niyad-jebid madow oo aan ku qaadanaya inta noloshayda ka hare anigoo haysanaya xanuun ka-noqosho. Taas beddelkeeda, waxay gabi ahaan ahayd mid oo aad u farxad badan tan iyo bilowgii. 

Waxay qaadatay waqti dheer inaan fahmo sababta oo ay ahayd mid oo aad u fududaysan oo aan ku dhibaatoonin xanunaahaas ka-noqoshada oo cabsiga leh. Sababta waa inayba xanuunaas jirin, waa shakiga iyo hubin la’aanta oo abuuraysa xanunahaas. Runta oo quruxda badan waa **inay fududahay in la joojiyo isticmaalka porn.** Waa go’aan la’aanta iyo murugaysiga kaliya oo ka dhigaya mid adag. Xataa markii ay qabatimsan yihiin, isticmaalyaasha waxay waqtiyada gaarka ah joogi karaan xiliyo dheer iyagoo la’aanteed. Waa kaliya markaad rabto, oo aadan haysan karin, oo aad ku dhibaatoonaysa.

Sidaas darteed, waxa muhiimka oo lugu fududayo waa inaad joojinta ka dhigto mid hubaal oo dambeyo. Ma aha adigoo rajaynaysa, laakin adigoo *og* inaad iska saartay, markaad go’aanta gaartay. Weligaaga ka ha shakinin, su’aalna ha ka soo qaadin, dhab ahaantii, lidkeeda kaliya — adigoo ka faraxsan! Haddii aad hubaal noqon kartid bilowga, way fududaan doontaa. Laakin sidee hubaal u noqon kartaa bilowgiiba? Taasi waa sababta ay buuga intiisa kale ay lagama maarmaan tahay. Waxaa jira arrimo gaar muhiim ah oo lagama maarmaan yihiin in maskaxdaada lugu caddeyo intaadan bilaabin:

1.  Garwaaqso inaad [xoriyada] gaari karto. Ma jiro wax oo adiga ku saabsan oo kaa duwan [oo ka hortagaya inaad joojiyso], iyo qofka kaliya oo kugu qasbi karo inaad daawato waa adiga. Xataa jilaadaas [oo aad daawanayso kuguma qasbi karta], weligeeduna riyadeeda ugu waalan kama fikirin in iyada la isticmaalaya in ragnimada lugu yareeyo.

2.  Gabi ahaan waxba ma jira oo la tanaasulaaya. Taas beddelkeeda, waxaa jira faa’iidooyin togan oo waaweyn oo la heli karo. Ma aha inaad kaliya ahaanayso caafimaad ika badan iyo taajirsan, laakin waxaad sidoo kale si ka badan ugu raaxaysanay waqtiyada wanaaga oo aad ka darxumeysi yaraanay waqtiyada xun. 

3.  Ma jiro wax oo la dhoho hal fiirin mise hal booqasho. Porn waa balwad daroogo iyo meerto, inaad halkaas booqasho darteed u cabaado waxaad kaliya si aan loo baahnayn naftaada u cadaabaysaa.

4.  Porn ha u arkin sida caado oo ‘caadi u ah inay wiilasha sameyaan’ oo laga yaabo inay dhaawacdo, laakin waa inaad u aragto sida balwada daroogada. Runta isku sheeg: ha jeclaato ama ha jeclaanin, **cudurka ayaad qabtaa.** Mana kaa tagaayso waayo aad madaxaaga ciida ku dhex duugto. Xasuusnow: sida cudur walba oo dadka curiyaamiyo, ma aha inuu kaliya nolosha dhan joogaaya, laakin wuxuu sii kordhaya uga darraa. Waqtiga ugu fududaysan in la daaweeyo waa hadda.

5.  Kala saar cudurka — balwada neerfa-ahaan — ee fikirka maskaxda ee ahaanshaha isticmaale ama in kale. Isticmaalayaasha oo dhan, haddii ay haysan lahaayeen fursada inay dib ugu laabtaan waqtiga ka hore intay la qabatimin, way ku boodi lahaayeen fursadaas. Maanta ayaad fursadaas haysataa! Haba uga fikirin sida ‘tanaasul’.

Markaad go'aankii ugu dambeeyay gaarto inaad haysatay booqashadii ugu dambaysay, waxaad horeyba u ahaanaysaa qof oo isticmaale ahayn. Isticmaalaha waa mid ka mid ah masaakiintaas oo xun oo noloshooda dhex marayaan iyagoo naftooda porn ku burburinayaan. Qofka oo isticmaale ahayn waa kan oo sidaas sameynin. Mar haddii aad go’aankaas ugu dambeeya gaarto, ujeedadaada ayaad horey u gaartay. Ka faraxsanow xaqiiqdaas, meelaha ha fadhiisanin adigoo murugaysan oo sugayso in balwada kiimikaha ay baxdo. Banaanka u bax iyo isla markiiba noloshaada ku raaxayso. Nolosha way cajiibsan tahay xataa markaad ula qabatimsan tahay iyo maalin walba aad bay uga fiicnaan doontaa markaadan ahayn. 

Waxa oo lagama maarmaanka ah oo joojinta lugu fududayo waa inaad hubaal ka noqoto inaad ku guuleysanayso inaad si buuxda uga foogado ee xiliga ka-noqoshada, ugu badnaan saddex toddobaadyo. Haddii aad ku jirto maskaxda saxda ah, waxaad tan u arki doontaa mid oo si qosol leh u fududaysan. 

maraxladaan markay marayso, haddii aad bilowgii maskaxdaada u furtay sida loo codsiyay, horeyba ayaad u go’aansatay inaad ka baxsanayso. Waa inaad hadda haysato dareeman xamaasadaysan, sida eey oo xariga jiidaaya, oo aad ka sugi karin inaad burburiso simbiriiriixanaha biyaha porn ee DeltaFosB. Haddii aad haysanooso dareeman oo darxumeysan, waxay ahaanaysa mid ka kid ah sababaha oo soo socda:

1.  Wax baa jira oo maskaxdaada galin. Dib u akhriso arrimaha shanta oo sareeya iyo is weydii haddii aad aaminsantahay inay run yihiin. Haddii aad waxba ka shakiso, dib u akhriso qaybaha ku habboon ee buuuga. 

2.  Waxaad ka baqaysaa guul darada. Ha ka walwalin, sii wad akhrinta iyo waad guuleysanaysaa. Ganacsiga dhan ee porn waa khiyaamo kalsooni oo baaxad weyn. Dad oo caqli badan way ku dhex dhacaan khiyaamadaha kalsoonida, laakin waa doqonka kaliya, isagoo khiyaamada fahmay, oo sii waddo inuu naftiisa khiyaamo.

3.  Wax walba waad ku raacsan tahay laakin weli waad darxumeysan tahay. Ha ahaanin! Indhahaaga fur, wax oo aad u fiican ayaa dhacooyo. Waxaad u dhowdahay inaad ka baxsato xabsiga, waa muhiim in laga bilawdo maskax oo saxsan: “*Aad bay u fiican tahay inaan mar dambe isticmaale ahayn!*”

Waxa kaliya oo loo baahan in la sameyo waa in laguugu haayo maskaxdaas saxda adigoo ku jirto xiliga ka-noqoshada, iyo dhowr cutubyada ku xigaan waxay la kulmaan arimaha gaarka ah si ay awood kugu siiyaan inaad sidaas sameyso. Xiliga ka-noqoshada ka dib uma baahnaanaysid inaad sidaas uga fikirto, waxaad si iswaddo uga fikiraysaa. Qarsoodiga kaliya ee noloshaada waxay noqon doontaa sababta oo aad mar hore u arkin. Sidaasba ha ahaatee, [waxaa jira] laba digniin oo muhiim ah:

-   Dib u dhig qorshahaaga inaad sameyso boqashadaada ugu dambeeysa ilaa aad buuga ka dhamayso.

-  Xili ka-noqosho oo saddex toddobaad ayaa marar badan la sheegay, taas oo keeni karta ismaandhaaf. Kowdi, waxaa laga yaabaa inaad si miyir-daboolaan u dareento inay tahay inaad saddeex tddobaad u dhibaatoodo. Sidaas ma aha. Labaad, waa inaad ka foogado dabinka ee: *"Dhinac ama si kale, waa inaan saddex toddobaad ka foogada, markaas waan fiicnaanaa."* Ma jiraan wax gaar ma dhici doona saddex toddobaad ka dib, mana u dareemi doontid sida qof oo isticmaale ahayn si lama filaan, maadaama ay [dadka oo isticmaalayaasha ahayn] dhab ahaantii si ka duwan uga dareemin isticmaalayaasha. Haddii aad joojinta ka murugooto intaad ku jirto saddexda toddobaad, waxay u badanaysaa inaad weliba ka murugoon doontid saddexda toddabaad ka dib. Markii la soo koobo, haddii aad hadaba ka bilaabi karto adigoo dheheyso, *"Weligayga ma isticmaali doono mar dambe, waa fiican sow ma aha?"*, duufsashada dhan way baxaysaa. Halkii oo aad dhehdo, *"Haddii aan kaliya badbaadi karo saddexdaan toddobaad porn la'aanteed."*, waxaad u dhimanaysaa hal booqashada haremka markay saddexda toddobaad ay dhamaadaan.

Maskaxdaada waxay rabtaa inay illaaliso status quo, marka haddii aad ku jirto aaminsanaanta inaad wax fiican ka khasaarooso markaad joojinooso, waxaad si cad ula kulmi doontaa dareeman xun. Waa wax oo suurtogal ahayn in la isku qasbo inaad dareeman gaar aad dareento haddii maskaxdaada ay aaminsanayn. Tan waa sababta oo ay muhiim u tahay in la dhex maro dhibaatada ka saarida dhalanteedka inay porn waxba ku siinayso. Taasi waa sida oo aad ku ogaanayso inaadba waxba huridaynin.

Cillada galmada waxay wax badan ku leedahay maskaxdaada iyo qaabka maskaxdaada. Porn waxay dib u habeysaa wareega abaalmarinta maskaxdaada iyo waxay maskaxdaada siisaa maskax 'shakisan'. Is-shakiga waxay si hubaal u sababaysaa cillad galmo. Inaad damaca dhan qaybta jirkaaga sare ku haysato, oo laakin aad ku dhibaatoodo kacsi la'aanta qaybta hoose waa waxa ugu xun oo qaabka maskaxdaada ku dhici karo. Libido oo si fican ugu haboon jaceylka waa macaanta dhalinyarada oo aad haysan karto ilaa aad ka dhimato. Waxaad ku haay kartaa ixtimaalka heer sare markaad joojiso, laakin taasi ma aha faa'iidooyinka kaliya mise kan ugu weyn. [Kan ugu weyn] waa xornimadaada addoonsiga!
