# Xiliga Ka Noqoshada

Ilaa saddex toddobaad oo fadhigaaga ugu dambeeya ka dib, waxaa laga yaaba inaad la kulanto xanuunaha ka noqoshada. Kuwaan waxay ka kooban yihiin laba arrimood oo kala saaran oo laakiin kala duwan:

1.  Xanuunaha ka noqoshada dopamine. Waa dareen maran oo kalsooni darran oo gaajada la mid ah, iyadoo loo garto sida damac mise dareen ‘wax-oo-ay-tahay-inaan-sameyo’.

2.  Kicinta nafsiyeed ee kicin dibada gaar sida xayaysiinta, daalacashada onlineka, wadahadalada telefoonka, iwm. 

Guul darada in la fahmo oo la kala saaro labadaan arrimo oo kala duwan waxay adag ka dhigtaa in la guuleysto markii oo la isticmaalaya habka awooda-rabitaan, oo ay tahay sababta oo dadka oo isticmaalaan ay ku dhamaadaan iyagoo haddane dabinka ku dhex dhaceen. In kasta oo xanuunaha ka noqoshada dopamine ay keenaynin xanuun jireed, ha dhayalsan xoogooda. Waxaan ka hadalnaa ‘xanuunaha gaajada’ haddii hal maalin cunto la’aan la soconaaya; waxaa laga yaabaa inay caloosha ka guuxayso, laakin xanuun jireed ma jirayso. Sidaasba ha ahatee, gaajada waa ciidan oo aad u xoog badan iyo waxaan u badanahay inaan aad u xanaaqno markii oo cuntada na loo diido. Waxay la mid tahay markuu jirkeena damacaya daadashada dopamine degdeg, oo ay kal duwanaanshaha ahaanayso inuu jirkeena cuntada u baahan yahay, oo uusan sun u baahnayn. Isagoo qaab maskax saxsan la haysto, xanuunaha ka noqoshada waxaa si fudu looga adkaan karaa oo ay si dhaqso ah u baaba’aan.

Ka dib markaad ka foogado dhowr maalmood adigoo isticmaalaysa habka awooda-rabitaanka, damaca daadashada dopamine degdegsan way baaba’aan mar dhow. Waa arrinta labaad — maskax-xadashada — oo adagta keenayso. Isticmaalaha wuxuu u bartay caadada inuu xanuunihiis ka noqoshada iska nafiso waqtiyada iyo dhacdooyinka gaarkood, taas oo keenaysa isku xiriika fikradaha *(“Kacsi ayaan yeeshtay, marka waa inaan porn daawado.” mise “Sariirtayda ayaan fuulaa anigoo laptop-kayga wato, marka waa inaan fadhi porn haysto si aan farxad u dareemo.”)* Saameyntaan waxaa si fiicaan u muujinaysa tusaale: waxaad haysataa baabuur oo kabaalka calaamadaha leexshada ku yeelo bidixda, laakin baabuur cusub aad gadataa oo isla calaamadaas ku qabo midigta. Waad ogtahay inuu dhinaca midigta ku yeelo, laakin dhowr toddobaad waxaad marmarkoo [si shil ah] ku dhufataa kobaalka masaxaadaha muraayada hore oo bidixda ku yeela markaad rabto inaad leexshada calaamayso. 

Joojinta sidaas ay la mid tahay: intaad ku jirto maalmaha hore, farsamaynta kicinta [inaad porn daawato] ayaa hawlgeli doonaan waqtiyada gaarka ah. Waxaad ka fikiri doontaa rabitaanka inaad fadhi porn yeelato, marka sidaas darteed in bilowgiiba maskax-xadashada laga hortaggo waa muhiim iyo waxay sababaysaa inay kicinkuwaas si dhaqso u baaba’aan. Inta lagu jira habka awooda-rabitaan, waayo uu isticmaalaha aaminsan yahay inuu hurid sameynooyo, wuu ka murugooyaa iyo wuxuu sugooyaa inay damaca baxaan, taas oo lid ku ah ka saarida farsamayntaan kicinta oo ay dhab ahaantii ku dhamaato iyadoo kicinta kordhisay. Sidoo kale, inta lagu jiro fikradaha in sheekh la noqon doono joojinta, isticmaalaha wuxuu ka fikiraa markuu noqon doono iyo xataa wuxuu dalbanaa inuuba ahayn inuu fikradahaas haysto, taas oo abuurayso wadadda is-nacaybta iyo guul darada.

Kicin oo guud ah waa waqtiyada oo aad kali tihid, gaar ahaan markaad saaxibadaada la jirto dhacdooyin bulsheed. Isticmaalahii hore oo habab kale isticmaalaya si uus u joojiyo wuxuu mar horeba darxumeysi noqday waayo dareenka in laga qaaday taageertiisa ama raaxadiisa oo caadiga ah. Saaxibadiisa waxay la jiraan lamaantooda iyo mid kasta aad bay lamaantooda u dhow yihiin. Isticmaalahuna waa doob ama ‘waxba kama helooyo’ lamaantiisa, oo uu hadda mar dambe ku raxaysanoonin wax oo ahayd inay ahaado dhacdo bulsheed oo wanaagsan. Simbiriiriixanada biyaha maskaxdiisa waxay isaga u horseedisa porn, taas oo ka fududaysan inuu isku dayo inuu lamaantiisa cajabiyo.

Waayo uu isku xiriiro xaq-u-lahaanshaha galmada ee fayoobidiisa, wuxuu hadda ka dhibaatoonooyaa dharbax oo saddex jibaraan iyo maskax-xadashada waxay dhab ahaantii kordhay. Haddii uu go’aansan tahay oo uu u adkeysan karo, wuxuu ugu damneyntii aqabali doonaa nasiibkiisa iyo noloshiisa ayuu la soconaa. Sidaasba ha ahaatee, qayb oo maskax-xadashada ka mid ah ayaa soo haraaya, oo dhinaca labaad ugu murugaysan ay ahaanayso inuu isticmaalaha joojiyay oo laakin dhowr sanadood ka dib uu weliba u damacooyo ‘hal fiirin ee haremka oo ugu dambeeya’ dhacdooyinka gaarka ah. Wuxuu u niyad jabaaya dhalanteed oo maskaxdiisa kaliya ku jiraan, oo uu si aan loo baahnayn naftiisa u cadaabaayo.

Xataa iyadoo EasyPeasy ah, in loo jawaaba kicinta waa guul darada ugu guudsan. Isticmaalahii hore wuxuu u janjeeraa inuu porn u tixgeliyo sida placebo ama kaniini sokor, isagoo fikiraaya, “*Waan ogahay inay porn waxba ii qabanin, laakin haddii aan iska dhaadhiciyo inay wax ii qabato, waxay dhacdooyinka gaarka wax ka taray.*” Kaniini sokor, in kasta oo ay ku siinaynin caawin jireed oo dhab ah, waxay ahaan kartaa caawinaad nafsiyeed oo xoog badan inay nafiso calaamadaha dhabta ah oo ay sidaas darteed faa’iido badan tahay. Laakin porn iyo siigaysashada caadada ah ma ahaan kaniini sokor. Maxaa? Porn waxay abuurtaa calaamadaha ay nafiso, kartina uma leh inay si buuxda u nafiso. 

Waxaa lagaa yaabaa inaad u aragto ka fududaysan in saameynta la fahmo markaad saameynta lala xiriirto qof oo isticmaale ahayn ama isticmaale oo guuleystay oo dhowr sannado joojiyay. Ka soo qaad tusaalaha isticmaale oo lamaantiisa ka khasaaray. Waa guud waqtiyadaas, isagoo niyad fiican la leh, in la dheho, “*Hal mar haremka u booqo, waxay kaa cawinaysaa inaad is-dejiso.*” Haddii dalabka la aqbalo, ma haysanaya saameynta dejineed maadaama ay balwad dopamine jirin oo ay sidaas darteed xanuunaha ka noqoshada jirin. Marka ugu fiican, waxa kaliya oo ay sameysa waa inay isaga siiyso horumarin nafsiyeed oo daqiiqad yar. 

Xataa markii uu fadhiga dhamaado ka dib, masiibada asalka weli way jirtaa. Dhab ahaantii, wayba sii kordhaysaa waayo qofka wuxuu hadda ku dhibaatoodaa xanuunaha ka noqoshada oo ay sidaas darteed tahay inuu wax doorto: u adkeyso, mise nafis raadi isagoo soo dib u celiyo inuu simbiriiriixanta biyaha raaco si uus haddane u soo bilaabo meertada darxumeysiga. Waxa kaliya oo pornka dhan siisay waa horumarin nafsiyeed oo degdegsan, isla horumarintii waxaa laga heli haray buug ama filin oo dareen wanaagsan, xataa mid xun. Dad badan oo isticmaalayaal ahayn iyo isticmaalayaashii hore waxay dib ugu qabatimaan natiijo ahaan dhacdooyinkaan oo kale. Maskaxdaada ku caddey: uma baahnid daadashada dopamine degdega iyo waxaad kaliya is-cadaabaysaa markaad sii wado inaad u tixgeliso sida nooc taageer ama horumarin. Looma baahna in darxumeysan la ahaado. 

Orgasm-yada ma abuuraan xiriir galmo oo fiican, badanaa way haleeyaan. Sidoo kale xasuusnow inaysan si buuxda u run ahayn in lamaanayaasha oo tusaan kalgacal oo dadweyn ah ay mar kasta ku raaxaysanayaan; isu dhawaanshaha waxaa si fiican lugu raaxaystaa gaarka markii lamaanayaasha ay u jawaabi karaan iyagoo ceeb jirin. Uma baahnid inaad ahaato balwad dopamine ooo orgasmka keentay. Haddii ay daadashada dopamine-ka ay dhacdo sida natiijo oo dabiici ahaan ee dhacdooyinka nolosha oo taxane ah, taasi way fiican tahay, laakin ku raaxayso dhacdada iyo nolosha la’aanteed.

Markay iska dayaan fikrada in porn ay dabeecad ahaan raxaysi leehdahay, isticmaalayaasha intooda badan waxay fikiraan, “*Haddii ay kaliya jiri lahaayeen porn oo nadiif ah.*” Way *jiraan* porn nadiif oo jilicsan, iyo qof kasta oo tijaabiyo wuxuu si dhaqso u arkaa inay waqti khasaaris tahay. Maskaxdaada ku caddey in sababta kaliya oo aad porn u isticmaalaysay ay tahay helitaanka daadashada dopamine. Mar haddii laga saara damaca dopamine ee porn, uma baahnanaysid inaad haremkaaga u soo booqato. 

Haddii ay xanuunaha ka imaadaan calaamadaha ka noqoshada dopamine oo dhab ah ama ay ka imaadaan farsamaynaha kicinta, aqbal. Xanuunka jireedka waa wax oo aan jirin iyo markaad maskax saxsan haysato, dhib ma ahaanaaya. Ha ka walwalin ka noqoshada — dareenka naftigiisa ma xuma. Waa la xiriirka rabitaanka oo markaas la dareemo in wax luguu diiday oo dhibaatada ah. Intaad ka murugoon lahayd, u qiro: “*Waan ogahay kan wuxuu yahay, waa xanuunada ka noqoshada oo porn. Kaas waa wixii oo isticmaalayaasha ka dhibaatoodaan oo ku haaya inay balwad ahaadaan. Dadka oo isticmaalayaasha ahayn kuma dhibaatoodaan xanuunahaan, waa mid ka mid ah sharriga badan ee balwadaan oo beenta sheegaaya. Aad bay u fiican tahay sida aan sharrigaan maskaxdayda ka saaraaya, sow ma aha!*” 

Markii sida kale loo dhigo, saddexda toddobaad oo xigta waxaad haysanaysaa dhaawac yar jirkaaga ku jira, laakin inta lagu jira saddexdaas toddobaad iyo inta noloshaada ka haray, wax oo aad u fiican ayaa kugu dhacaaya. Waxaad naftaada ka saaraysaa cudur oo aad u xun, iyadoo gunooyinka ka culus badan xanuunaha yar, dhaawaca yar, oo aad dhab ahaantii ku raaxaysato xanuunaha ka noqoshada. Waxay noqonayaan daqiiqad oo raaxaysan, sida ciyaar xamaasadaysan in la gaajeeyo gooryaanka porn oo calooshaada ku nool. Waa inaad saddex toddobaad iyadaa gaajeyso iyadoo isku dayaysa inay ku khiyaanta inaad sariirtaada korto oo aad [balwada] sii noolaysiisoo. 

Waqtiyada qaarkood, waxay isku dayi doontaa inay darxumeysan kaa dhigto. Waqtiyada qaarkood, way kaa yaabinaysaa mar oo adiga ka warqabin. Tusaale: Waad heli doontaa URL porn ama waxaad ka hor imaan doontaa [filimada ama sawiradda xunxun] oo online adigoo hilmaantay inaad joojisay, taas oo ku siinaysa dareen yar in wax lagaa qaaday markaad xasuusato. Horeyba ugu sii diyaar garoow khiyaamintaas, iyo si kasta oo duufsashada ha ahaato, maskaxdaada ku caddey inay kaliya meesha joogta waayo shaydaanka yar oo jirkaaga ku jira, iyo [sidoo kale ku caddey in] mar kasta oo aad caabinto jirrabadda, inaad dharbaaxad kale gashato dagaalka. 

Wax kasta oo aad sameyso, ha isku dayin inaad porn ilowdo. Tan waa mid ka mid ah arrimaha oo u keenayso PMO-yaalaha oo isticmaalayaan habka awooda-rabitaanka saacadood oo murugaysan. Waxay isku dayaan inay maalin walba dhex maraan iyagoo rajaynayaan inay ugu dambeyntii iska hilmaamayaan. Waa sida adigoo karti u lahayn inaad joojiso — inta ka badan aad ka walwasho, inta ka badan ay adkaanayso. Sidaasba ha ahaadee, karti uma lahaanaysid inaad iska ilowdo, intaad ku jirto dhowr maalmaha hore ‘shaydaanka yar’ wuxuu ku sii xasuusinaayaa kartina uma lahaanaysid inaad [fikradaha] ka foogado. Iyagoo weli jiraan laptop-yaal, teleefannada, iyo majaladaha, waxaad arki doontaa xasuusin oo joogto ah. 

Arrinta oo ah inaadan u baahnayn inaad ilowdo maadaama ay wax xunba dhacaynin. Dhab ahaantii, wax oo aad u fiican ayaa dhacooyo, iyo xataa haddii aad kumanaan mar ka fikirto maalin kasta,** ku baashaal daqiiqad walba, is-xasuusi sida ay u wanaagsan tahay inaad xorowdo ahaato haddane. Is-xasuusi farxada ee aan u baahnayn inaad is cadaabto mar dambe.** Sida hore loo sheegay, waxaad arki doontaa inay xanuunaha noqdaan waqtiyo oo raaxaysan, adigoo ka yaabto sida ay si dhaqso oo aad markaas porn ilobayso.

Wax kasta oo aad sameyso, *ha ka shakinin go’aantaada.* Mar haddii aad bilowdo inaad shakiso, waxaad bilaabaysaa inaad ka murugoonto, iyo way ka sii darraysaa. Taas beddelkeeda, daqiiqadaas murugta isticmaal iyo u beddel sida horumarin. Tusaale: Haddii ay sababta [murugtaas] tahay niyad jabta, is-xasuusi in porn ay *sababta* u ahayd. Haddii URL luguu soo diro oo saaxibkaaga ka imaaday, ka faan inaad dhehdo, “*Waan fa faraxsanahay inaan sheego inaan waxaas u baahnayn mar dambe.*” Taas wuu ka xumaan doonaa, laakin markuu arka inay [porn la’aanta] ku dhiboonin wuxuu ka jiraya kala bar inuu kugu soo biiro.

**Xasuusnow: waxaad haysataa sababo oo aad u xoog badan inaad awalba joojiso.** Is-xasuusi qiimaha iyo is weydii haddii aad rabto inaad gasho khataraha cillada jirkaaga, maskaxdaada, iyo xaqiiqda inaad sixir ka hoos noolaanaysid inta nolshaada ka haray. Ka digtoonow dadaalka shaydaanka yar inuu khataraha yareeyo iyo, ugu muhiimsan, xasuuso inay dareemanka ay kaliya daqiiqad yar yihiin oo ay daqiiqad kasta [oo aad joogto la’aanteed] waa hal daqiiqad oo ujeedadaada u dhow.

Isticmaalayaasha qaarkood waxay ka baqayaan inay noqonayso inay inta noloshooda ka haray ku bixiyaan iyagoo dib u rogayaan ‘kicinta oo iswaddaan’. Markii sida kale loo dhigo, waxay aaminsan yihiin inay ahaanayso inay noloshooda dhex maraan iyagoo naftooda ku khiyaamayaan inay porn u baahnayn, iyagoo isticmaalayaan cilmi-nafsiyeedka. Laakin sidaas ma aha; xasuuso inuu yididiidlaha u arko inay dhalada kala bar u buuxan tahay oo uu kab niyad jabsan u arko inay kala bar u maran tahay. Faa’iidooyin kuma jiraan isticmaalka porn. Tusaalaha porn, dhalada way maran tahay iyo isticmaalaha wuxuu u arkaa inay buuxan tahay. Waa isticmaalaha oo maskaxda laga xaday inuu u maleeyo inay jiraan. Mar haddii aad bilowdo inaad isku sheegto inaadan porn u baahnayn ama inaadan rabin, waqti oo aad u yar ka dib, uma baaanaanaysid inaad sheegto xataa, adigoo naftigaaga arkooso runtaas quruxda. Waxay tahay wixii ugu dambeeya oo aad u baahantahay inaad sameyso — hubi inaysan ahayn wixii ugu dambeeya oo aad sameyso.
