# Hal Fiirin Yar Kaliya

Tan waxay tahay sababtaa guul darrada dad badan oo isticmaalayaan habka awooda-rabitaanka. Waxay dhex marayaan laba ama saddex maalmood markaas waxay haaysanayaan hakaas fiirin ee inay xaaladaha xun la qabsadaan. Ma garwaaqsadaan saameynta oo aada u xun ay tan u yeelayso kalsoonidooda.

Isticmaalayaasha intooda badan, fiirsigoodii ugu horreeyay ee mareegta porn harem uma fiicnayn sida galmada lala sameyo qof run ah. Muuqaalaha nadiifka oo aada u yar yihiin oo aada u fog yihiin, taas oo ay maskaxdooda miyirka ah siinayso horumarin, iyagoo fikiraan, “*Hagaag, si buuxda sidaas uguma raaxaysanayn. Damaca wuu iga tagayaa mana jecli waxyaalaha oo naxtinta ah.*” Dhab ahaantii, arrinta waa lidkeeda. Maskaxdaada ku caddey: raaxada orgasmka ma aha sababta oo aad porn u joojisay. Haddii ay isticmaalayaasha halkaas u joogeen orgasmka kaliya, weligooda ma daawan lahayn wax oo hal muuqaal ka badan. Sababta kaliya oo aad porn u baahnayd waa inaad shaydaankaas yar quudiso. Ka fikir sida ay qiimeysan u ahayd isaga ka dib markii afar maalmood la gaajeeyay. Maskaxdaada miyirta qabta ma og, laakin hagaajinta dopamine oo jirkaaga helay waxaa la gaarsiiyaa maskaxdaada oo miyir-daboolanka, iyo diyaarinta dhawaaqa oo dhan waxay ahaanaysaa wax oo aan la go’aamin. Waxaa jiraya cod yar oo maskaxdaada gadaasheeda ku jira oo dhehaayo, in kasta oo ay caqli galaynin, in fadhiyaha ay qiimeysan yihiin oo aad mid kale rabto.

‘Fiirintaas oo yar’ waxay qabtaa laba saameyn oo burburinsan:

1.  Waxay shaydaanka yar ku haysaa inuu jirkaaga ku sii noolaado.

2.  Si ka darran, waxay shaydaanka yar ku haysaa inuu maskaxdaada ku sii noolaado. Haddii aad haysatay ‘fiirinta ugu dambeysay’, way ka fududaan doontaa inaad haysato tan ku xiga.

Porn waa dabinka jiirka oo farmaajo lahayn, oo sun kaliya. Markaad isticmaasho habka awooda rabitaanka, waa inaad iska dhaadhiciso inaadan farmaajada qabanin, laakin EasyPeasy wuxuu kuu ogolaanayaa inaad sunteeda aragto.

Ugu muhiimsan, xasuusnow:

*'Hal fiirin kaliya' waa sida ay dadka u yeeshtaan balwadda marka horeba.*