# Beddelka

Qaar tussaalayaal oo beddelka ka mid ah waa in la isku xadiido majaladaha porn, sawirada internetka, porn oo isticmaalka la nidaamay, iwm. **MIDNA HA ISTICMAALIN.** Waxay joojinta ka dhigayaan si ka adag badan, ma fududayaan. Haddii aad haysato xanuun oo aad markaas beddelka isticmaasho, waxay kaliya xanuunka si dheeraynaysaa, taas oo ka dhigaysa si ka adag. Waxa oo aad runtii dhohoosa waa inaad porn u baahantay si aad maranka iska buuxiso. Waxay la mid tahay inaad u tanaasusho afduubiye mise xanaaqa cunuga, adigoo u sii ogolaasho inay xanuunaha sii socdaan oo aad sii dheerayso cadaabka. Sidaasba ha ahaadee, beddelka ma nafisayso xanuunaha. Damacaaga waa neurotransmitters-yada gaarka ah oo maskaxdaada ku jira, iyo wixii oo kaliya uu samenaya waa inuu kugu haayo inaad porn ka fikrto. Arrimahaan xasuuso:

1.  Porn beddel uma jira. 

2.  Porn uma baahnid. Cunto ma aha, waa sun. Markay xanuunaha yimaadaan, is-xasuusi inay isticmaalayaasha yihiin kuwa oo ka dhibaatoodo xanuunaha ka noqoshada, ma aha kuwa oo isticmaalayaasha ahayn. U arag sida ay runtii u yihiin, waa sharriga kale oo daroogada ka mid ah. U arag sida dhimashada mid oo shaydaamanka ka mid ah.

3.  Porn ayaa abuurto maranka; ma buuxiso. Inta ka dhaqso badan oo aad maskaxdaada u barto inaadan u baahnayn daawashada waa inta ka dhaqso badan oo aad ka xorobayso. Gaar ahaan, ka fogow wax walba oo porn u ek, sida majaladaha nimanka, sheekadaha jacaylka, iyo xayaysiisyada. Tan ma la mid ah ahaanshaha maskax-xiran, way fiican tahay in laga hadlo jaceylka iyo galmada, laakin porn [sidaas] ma aha. Waxaa had iyo jeer jira hab oo lugu ogaan karo goor iyo meel oo lugu takooro. Run ay tahay in dadweyna yar oo ka mid ah isticmaalayaasha oo isku dayayaan inay joojiyaan iyagoo isticmaalayaan porn jilicsan ama isticmaalka porn la nidaamay oo ay [sidaas] ku guuleystaan oo ay guushooda ku xiriiriyaan habab kuwaas. Sidaasba ha ahaatee, waxay joojiyaan *in kasta oo ay* habab kuwaas isticmaalayaan, oo laakin ay habab kuwaas sababta ahayn. Way nasiib darran tahay in dad badan ay weli ku taliyaan [marashada] talaaboooyin kuwaan. 

Laakin tan waa mid oo aan yaab lahayn waayo haddii aadan si buuxda dabinka u fahmin, [porn] qaadashada oo nidaamsan ama beddlid oo jilicsan waxay u muuqdaan habab oo caqli-galayaan. Waxay ku salaysan tahay aaminsanaanta in markii oo aad isku daydo inaad porn joojiso, inaad haysanaynayso laba cadow oo xoog badan inaad ka adkaato: 

-   Jebinta caadada.

-   Ka badbaadista xanuunada ka noqoshada jireedka oo aada u xun.

Haddii aad haysato laba cadow oo xoog badan inaad ka adkaato, caqli ma galaya inaad islamarkiiba labadaba la dagaasho, waxaa caqli galaya inaad hal iyo hal u dagaasho. Marka aragtida waxay leedahay markaad kowdi joojiso isticmaalka porn, waxaad [isticmaalkaaga] hoos u jaraysaa hal mar halkii toddobaad mise waxaad isticmaashaa porn amiinsan. Markaas markay caadada jabto, waxaad sii tartiib tartiib u yareenaysaa sahayda, oo aad sidaas hal iyo hal iskaga dhiciso labada cadow. 

Tan waxay u muuqdaa wax oo caqli galaya laakin waxay ku salaysan tahay macluumaad khaldan. Porn caado ma aha, waa balwad daroogo, iyo xanuunada jireedka dhabta oo xanuunaha ka noqoshada ka yimaadaan waxay u dhowdahay in la fahmi karin. Waxa oo aad rabto inaad hesho markaad joojinayso waa inaad sida ugu dhakhshada badan labadaba disho shaydaamanka oo jirkaaga ku jiraan iyo kuwa oo maskaxda ku jiraan. Waxa kaliya oo xeeladaha beddelidka oo dhan ay sameyaan waa inay dheerayaan nolosha shaydaanka yar, oo ay tan sidaas darteed u dheerayso maskax-xadashada. EasyPeasy wuxuu fudud ka dhigaa in si degdegsan loo joojiyo, isagoo maskax-xadashada la dilaya adigoon fadhigaaga ugu dambeeya gaarin. Shaydaanka yar mar dhow ayuu dhiman doonaa, iyo xataa markuu dhimanooyo, ma ahaanaya dhibaata oo ka badan wixii uu ahaayay markaad isticmaale ahayd.

Ka fikir lee, siday ku daawayn kartaa qabatinka dargoogada adigoo isla daroogii talinooso? Waxaa jira sheekooyin badan oo ku saabsan dad oo joojiyeen isticmaalka porn culus oo laakin ay la qabatimsan yihiin beddelidkooda ‘amiinsan’ iyagoo lugu khiyaamay cudurdaaryaasha shaydaankooda yar. Ha ku kadsoomin xaqiiqda in porn-ka oo amiinka ay aad u xumayn — muuqaalkaas kowaad oo kugu horreeyay isla sidii ay ahayd. Beddelka oo dhan waxay qabaan isla saameyntii saxda oo nooc walba oo porn. Qaarkood waxay bilaabaan inay cunto cunaan [porn beddelkeed], laakin in kasta oo ay dareenka maranka ee rabitaanka porn tahay mid aan laga kala saari karin dareenka gaajada, mid midka kale ma qancin doono. Dhab ahaantii, haddii ay wax jirto oo lugu talagalay inay kordhiso rabitaankaaga porn, waa isku dal-dalka cuntada. Sida hore loo sharaxay, porn qaadasha la nidaamay iyo porn amiinsan waxay kaliya ku dhex gelinayaan dagaal is jiid jiid, iyadoo iska caabinta duufshada ay si aad u xanaajin badato ilaa aad nafis dareemayso markaad booqdo haremkaaga ugu jeclayd. 

Madaxda sharriga oo ku jira habka beddelka waa dheeraynta dhibaatada runta ah, maskax-xadashada. Beddelid maad u baahan tahay markuu hargabka kaa tago ka dib? Dabcan, uma baahnid. Markaad dhehdo inaad u baahan tahay beddelid, waxaad runtii dhehaysaa inaad hurid sameynooso. Niyad jabka oo lala xiriiriyo habka awooda rabitaanka waxaa keenayso xaqiiqda inuu isticmaalaha aaminsan yahay inuu hurid sameynooyo. Waxa kaliya oo aad sameynooso waa inaad hal dhibaato ku beddesho mid kale. Farxad kuma jira inaad naftaada ku daldasho cunto, sigaar, ama khamri. Waxaad kaliya noqon doontaa cayil badan iyo darxumeysan, iyo si dhakhsasha ayaad darooga ugu soo laabanaysaa.

Isticmaalayaasha oo iska caadiga ah waxay adag u arkaan inay iska saaraan aaminsanaanta in laga qaadaya abaalmarintooda, sida kuwa oo loo ogolaanin inau online galaan intay ku jiraan waqti oo safarsan, dhacdo qoyska, iwm. Qaar waxay dhehaan, “*Ma ogaan lahayn sida loo nasto haddii ay porn iga caawin lahayn.*” Tan arrinta lee caddeysaa — badanaa nasashada ma qaato waayo uu isticmaalaha u baahan yahay ama uu rabo, laakin sababta waa in qabatimaha — taas oo ah wixii uu runtii yahay — uu si quusan u baahan yahay inuu cuncunta iska xago. 

Xasuusow, fadhiyaha porn weligooda ma ahayn abaalmarin oo dhab ah. Waxay la mid ahaayeen in la gashto kabo ciriiri si aad u dareento raaxada iska siibida. Marka haddii aad dareento inay lagama maarmaan tahay inaad haysato abaalmarin yar, beddelkaaga taas ka dhig; adigoo shaqaynooso, xiro kabo mise kastuumo oo hal cabbir kaa yar iyo ha isku ogolaanin inaad isla siibto ilaa aad haysato waqtigaaga nasashada, markaas la kulan daqiiqada raaxada iyo qanciska oo aad u fiican markaad iska siibto. Waxaa laga yaabaa inaad u maleeyso inay taas aad u doqon tahay. Gabi ahaan ayaad saxsan tahay. Waxay adag noqon kartaa in sidaas loogu milicsado inta weli lugu jira dabinka, laakin taasi waa waxa oo isticmaalayaasha sameyaan. Waxay sidoo kale adag tahya in la milicsado inaadan mar dhow u baahnaanaynin ‘abaalmarintaas’ yar, oo aad mar dhow so naxriisan dhab ah ugu tixgeliso saaxibadaada oo weli dabinka ku jiraan oo aad ka yaabto sababta oo ay arrinta u arki karin.

Sidaasba ha ahaatee, haddii aad sii wado inaad naftaada khiyaanto ina booqda haremka ay abaalmarin dhab ahayd, ama inaad u baahan tahay beddelid, waxaad dareemi doontaa in wax lagaa qaaday ama darxumeysan. Ixtimaalka waa inaad ugu dambeyntii ku dhex dhaci doonto dabinkaas oo yaqyaqsan mar kale. Haddii aad u baahan tahay nasasho oo daacad ah sida ay haweenka guriga, maclimiinta, dhakhaatiirta, ama shaqaalayaasha kale u baahan yihiin, waxaad mar dhow si ka badan ugu raaxaysan doontaa nasashadaas waayo aad u baahnayn inaad naftaada qabatimin. Xasuuso inaadan beddelid u baahnayn. Xanuunada waxay yihiin damaca dopamine iyo mar dhow way bixi doonaan. U ogolow inay fikradaas taageertaada noqoto dhowr maalmaha oo soo socdaan iyo ku raaxayso inaad jirkaaga iyo maskaxdaada ka saarto addoonsiga iyo ku tiirsanaanta.
