# Ma Ka Foogadaa Xaaladaha Duufsan

Talada waxay si toos ahayd ilaa hadda iyo waxay ku weydisay inaad ula dhaqanto sida tilmaamid intaad soo jeedin ula dhaqmi lahayd. Waxaa u jira sababo macquul oo la taaban karo ee taladaan waxaana sababahaas taageeray kumanaan kiis oo daraasado ah. Markii la fiiriyo su’aasha haddii la isku dayo in laga foogado duufsashada ama in kale, arrinta sidaan oo kale ma aha. Isticmaale kasta was inuu naftiisa u go’aamiyo. Sidaasba ha ahaadee, laba talooyin oo caawin badan ayaan la soo jeedin karaa si ay kugu caawiso markaad habkaan marayso. Waa cabsida xanuunada ka noqoshada oo mustaqbalka oo nugu haayo inaan porn isticmaalno inta nolosheena ka haray, iyo cabsidaan waxay ka kooban tahay laba maraxlad oo kala saaran.

**Marxalada Kowaad - “*Sidee uga badbaadi karaa porn la’aanteed?*"**

Cabsidaan waa dareeka argagaxsan oo isticmaalaha haysto markuu doob yahay ama uu leeyahay lamaane oo xise u qabin galamada ama oo la heli karin. Cabsidaan xanuunada ka noqoshada ma keento laakin waxaa sababto cabsida nafsiyeeda ee ku tiirsanaanta, cabsida inaadan karti u lahayn inaad [ka] badbaado galmada ama orgasmyada la’aantood. Cabsidaas meesha ayay ugu sarreysa markaad u dhowdahay inaad joojiso, markay xanuunadaada ka noqoshada ay marayaan meeshii ugu hooseeyo. Waa ka cabsida waxyaalaha oo aan la garanayn, nooca cabsida oo ay dadk haystaan markay baranayaan quusitaanka.

Looxa quusitaanka hal cagood ayay u sareysan tahay laakin waxay u muuqda loox oo lex cagood u sareysan. Biyaha waxay lex cagood u qoto dheer tahay laakin waxay u muuqda inay hal cagood u qoto dheer tahay. Geesinimo ay qaadataa in laga boodo [looxa quusitaanka], adigoo iska dhaadhicisay inaad madaxaaga jejebinayso. Boodinta waa qaybta ugu adag badan, haddii aad hesho geesinimada inaad sameyso - inta kale way fududahay! Tani waxay sharaxdaa sababta oo isticmaalayaasha badantooda oo awooda-rabitaan badan ay weligooda isku dayeen inay joojiyaan, ama ay u badbaadi karaan dhowr maalmood kaliya markay isku dayaan. Dhab ahaantii waxaa jira qaar isticimaalayaal oo ku jiraan habka porn qaadashada la nidaamay oo, isla markii oo ay go’aamiyaan inay joojiyaan, ay dhab ahaantii si xad-dhaafsan u daawadaan iyo waxay dedeg ugu kordhaan muuqaala oo ka sii darran muuqaalaha ay fiirsan lahaayeen haddii weligooda go’aaminin inay joojiyaan. Go’aanka waxay keenaysaa argagax, taas oo walbahaarsan ah waxayna kicisaa tilmaanta inaad safar u qaadato harem-ka. Laakin hadda [adigoo joojisay], ma haysan karto [safarkaas], taas oo horseediso fikradaha in wax lagaa qaaday iyo walbahaar oo ka badan. 

Kicinta waxay si dhakhso badan u kacdaa markay fiiyuuska babto, waxaad markaas shidaa browserka. Ha ka walwalin, argagaxa waxay kaliya tahay nafsiyeed. Waa cabsida inaad weli [porn] ku tiirsantahay. Runta oo quruxda badan waa inaadan ku tiirsanayn, xataa markii oo aad weli balwad u leedahay. Ha argagaxin ee bood.

**maraxlada labaad - Cabsida oo Muddada Dheer**

maraxlada labaad way muddo-dheer tahay, iyadoo ku lug leh cabsida inay xaaladaha gaarka ah mustaqbalka aysan raaxo ahaanaynin ama inaadan karti u lahaanaynin inaad la qabsato dhaawacaha porn la’aanteed. Ha ka walwalin, haddii aad boodi kartid, waxaad arkaysaa inay arrinta lidkeeda tahay. Ka foognaansha duufsashada naftigeeda waxay u kala baxaan laba qaybabood.

1.  "*Waxaan la socan doonaa (subscribe-gareenayaa) porn qaadasha nidaamsan oo hal mar afartii maalmood. Waxaan dareemi doonaa kalsooni badan anigoo og inaan online gali karo haddii ay adag igu noqoto. Haddii aan guul darreysto way iska fiican tahay, maalmo kale lee ku darri doonaa meertadayda xigta.*” 

Heerka guul-darrada dadka oo sidaan sameynaya **aad bay uga badan tahay** kuwa oo gabi ahaanba u joojinayaan. Tani waxay inta badan sabab u tahay xaqiiqda ah in haddii aad ku jirto daqiiqad xun inta lagu jiro xilliga ka noqoshada, way fududahay inaad browserka korto oo aad haremka booqato adigoo wadato cudurdaarrada sare ku xusan. Laakin haddii aad qabto sharaf darrada inaad si cad u jebiso xeerarkaaga sida muraayadda daaqadd oo la jebiyay, waxaad u badan tahay inaad duufsashada ka adkaato. Si kastaba ha ahaatee, waxay u badan tahay inayba xanuunka ku dhaafi lahayd haddii aad dib u dhigi lahayd. Sidaasba ha ahaatee, sabata ugu weyn ee heerka sare oo guul darrada kiisyadaan Waa isticmaalaha uu si buuxsan uga go’anayn inuu awalba joojiyo. 

Xasuuso in labada oo lama huraan ah oo lagu guulaysto ay yihiin:

-   Hubaalka.

-   “*Cajiib buu yahay inaanan mar dambe porn u baahnayn, sow ma aha?*”

    
Si kastaba ha ahaatee, maxaad aduunkoo dhan uga baahan tahay fadhi porn? Haddii aad weli [dareemooso inaad] u baahan tahay inaad soo booqato haremkaaga, [waa inaad] kowdi dib u akhriso buuga. Wax ayaaba maskaxdaada weli galin. Waqtiga qaado inaad disho shaydaanka weynka masxadaada ku jira oo maskaxda xadaaya ilaa uu ka kago markuu dhinto. 

2.  “*Ma ka foogadaa dhacdooyinka walbahaarsan ama bulsheeda ah intaan ku jiro xiliga ka noqoshada?*”

    Markii loo fiiriyo xaaladaha walbahaarsan, haa. Caqli ma galaya in la isku keeno walbahaar oo loo baahnayn. Laakin markii loo fiiriyo arrinta dhacdooyinka bulsheeda, sida bars iyo kalaabyada, talada waa lidkeeda. Bax ee si toos u soo raaxayso! Galmo uma baahnid, xataa dhinaca faafinta galmada, markaad balwad u leehdihid porn. Bax ee ka farax xaqiiqda inaadan u baahnayn galmada ama galmada faafinta, waxay si dhakhsasho badan kuuga caddeynaysaa runta quruxda badan in nolosha ay aad uga fiican tahay cadaadis kuwaan la’aantood. Ka fikir sida ay aad uga fiicnaan doonto markuu shaydaanka yar kaa tago, isagoo la baxo fikradahaas. 
