# Daqiiqada Waxiiyga

Caadi ahaan saddex toddobaad gudahooda markay ka baxsadeen ka dib, isticmaalayaashii hore waxay la kulmaan *daqiiqada waxiyga*. Cirka wuxuu u muuqdaa inuu sii iftiimo wuxuuna yahay daqiiqada markuu maskax-xadashada si buuxda u dhamaado. Halkii oo aad isku sheegi jirtay inaadan u baahnayn inaad porn daawado, waxaad sii lama filaan u garwaaqsanaysaa in dunta ugu dambeysa ay jabsan tahay oo aad ku raaxaysan karto inta noloshaada ka haray adigoon weligaaga u baahnaanin mar dambe. Wuxuu sidoo kale yahay markay halkaan marayso markii oo aad caadi ahaan isticmalayaasha u fiiriso sida waxyaala oo murugaysan.

Joojinaha oo isticmaalayaan habka awooda-rabitaanka caadi ahaan ma la kulmaan daqiiqadaan waayo in kasta oo ay ka faraxasan yihiin inay ahaadaan isticmalayaal hore, waxay sii waddaan inay noloshooda dhex maraan iyagoo aaminsan yihiin inay hurid sameynayaan. Inta ka badan oo aad balwad lahayd, inta ka badan ay daqiiqadaan fiicnaanayso, waxayna joogaysaa waqti nololeed. In kasta oo ay jiraan farxado badan ee nolosha, waxay tahay wax oo macquul ahayn in dib ula kulanto dareenka dhabta ee inaad la kulantay. Farxadda inaadan mar dambe ku qasbanayn inaad porn daawato way ka duwan tahay, haddii aad haysato dareeman hoose oo aad horumarin u baahan tahay, is-xasuusi sida ay aad u fiican tahay inaadan la qabatimin balwadaas oo aada u xun. Dad badan waxay u liis gareeyaan sida mid ka mid ah dhacdooyinka ugu fiican ee noloshooda. Kiisyada badan markii oo loo fiiryo, daqiiqada waxiiga ma dhacdo saddex toddobaadyo ka dib, laakin wuxuu dhacaa dhowr maalmood ka dib. 

Kiiskayga markii la fiiriyo, wuxuu dhacay intaanan dhamaynin booqashadayda haremka ugu dambeeya. Waxaan hubaa in dadka badankooda oo halkaan joogo, xataa intaysan ka hore gaareen dhamaadka cutubyada ay wax dhehi lahaayeen sida, “*Uma baahnid inaad hal eray kale sheegto. waxaan si aad u caddeysan u arki karaa wixii oo dhan. Waan ogaan doonaa inaanan weligayga porn u baahnaan doonin mar dambe.*” Iyadoo ku saleysan jawaab celinta aan helay, tani waxay dhacdaa marar badan. Sida habboon, haddii aad raacdo tilmaamaha oo aad si buuxda cilmi-nafsiyeedka u fahamto, waa inay isla markiiba kugu dhacdo. 

In kasta oo la sheego inay qaadanayso shan maalmood in xanuunada ka noqoshada jireedka oo la fahmi karo ay badaan, oo ay qaadato saddex toddobaad in isticmaale hore uu si buuxda u xoriyad noqdo, tilmaamahaas waxay keeni karaan dhibaatooyin oo laba ah. Kan kowaad waa in soo jeedinta la gelinaya maskaxda dadka inay ahaanayso inay ku dhibaatoodaan waqti oo shan maalmood ila saddex toddobaad u dhxeeya. Tan labaad waa in isticmaalaha hore uu u janjeero inuu fikiro, “*Haddii aan shan maalmood mise saddex toddobaad badbaadi karo, waxaan fili karaa horumarin dhab ah ee dhamaadka xiligaas.*"

Sidaasba ha ahaadee, waxaa laga yaabaa inuu haysto shan maalmood ama saddex toddobaad oo wanaagsan oo ay markaas ku xigto maalmo xun oo dad kasta ku dhaco, taasi oo waxba ku lahayn balwadda oo laakin laga keenay dhinacyada kale ee nolosheena. Markaas, isticmaalahii hore oo sugooyo daqiiqada waxiiyga wuxuu taasi beddelkeeda la kulmaa niyad jab. Wuxuu jebin karaa kalsoonidiisa. Si la mid ah, haddii aysan jirin hab-raacyo, isticmaalaha hore wuxuu ku qaadan karaa inta noloshiisa ka haray isagoo sugaya inay waxba dhicin. Tan waxa oo ku dhaco dadka badankooda oo joojiyaan markay isticmaalayaan habka awooda-rabitaanka. 

Dadka waxay badanaa wax ka weydiiyaan muhiimada shanta maalmood iyo saddexda toddobaad. Ma yihiin daqiiqado kaliya oo si lama filaan ah u yimaaddaan? Maya, in kasta oo aysan ahayn taariikhyo oo hubaalsan, waxay ka tarjumayaan uruurinta jawaab-celinta sannadahii la soo dhaafay. Waa qiyaastii shan maalmood oo joojinta ka dib markii isticmaalayaashii hore ay balwadda ka joogsato sida mashquulka ugu weyn ee maskaxdooda. Isticmalayaashii hore badankooda waxay waxiiyga la kulmaan muddadaan agaarkeed, guud ahaan inta lagu jira xaalado culus iyo kuwa bulsheeda ah oo ay markoo hore karti u lahayn inay la qabsadaan ama oo raaxo lahayn ee booqsho harem la’aanteed. Waxaad si lama filaan ah u garwaaqsan doontaa inaadan kaliya ku bashaalaynin oo aad la qabsanaynin, oo laakin aad sidoo kale fikrada porn ay xataa weligaaga kuu imaanin. Markii halkaas laga bilaabo, [joojinta] waxay caadi ahaan noqonaysaa mid oo aad u fudud. Taasi waa markaad ogaato inaad xor tahay. 

Waa labadaba waayo-aragtinimadayda iyo waayo-aragtinimada dadka badan oo kale oo isku dayayaan inay joojiyaan iyagoo isticmaalayaan habka awooda rabitaanka ee in agaarka xiliga saddexda toddobaada ay tahay markay isku dayinka dhabta ah ay badankooda guul dareystaan. Waxa oo badanaa dhaco waa in qiyaastii saddex toddobaadyo [ee joojinta] ka dib aad dareento in damaca inaad porn daawato ay [si buuxda] kaa tagtay. Waxaad u baahan tahay inaad tan naftaada u caddeyso, marka waxaad kortaa browserka inaad haremkaaga u booqdo. Waxay u dareentaa wax oo caadi ahayn, taasi oo caddeynayso inaad [runtii balwadda] iska saartay. Laakin adigoo habka ku jirto, waxaad saliidaysay  simbiriiriixanta biyaha DeltaFosB waayo daadashada dopamine-ka degegsan oo cusubta ah, taasi oo ah wixii oo jirkaaga u damacaayay saddexda toddobaadyo oo la soo dhaafay. Isla markiiba oo aad camalka dhamayso, dopamine-ka wuxuu bilaabaa inuu jirkaaga ka baxo. Cod yar ayaa dib u soo baxaayo, “*[Balwadda] ma iska saarin, mid kale ayaad rabtaa.*”

Si dhakhsasho ugu ma laabatid waayo aadaan rabin inaad mar kale ula qabatinto, taasi oo u ogolaanayso inay muddo amaansan ku dhaafdo. Marka, markii oo mar xigta lugu jirrabado waxaad karti u leedahay inaad naftaada u sheegto, “*Hagaag, mar kale kuma qabatimin, marka dhib kuma jiro inaan mid kale haysto.*” Waxaadba horeyba hoos ugu socotaa simbiriiriixanta. Asaasiga xalinta dhibaatadaan ma aha sugitaanka daqiiqada waxiiyga, laakin waa in la garwaaqsado in mar haddii aad browserka xirto, way dhamaatay. Sahayda ogsijiinta ayaad ka goysay shaydaankaaga yar. Ma jiro xoog oo dhulka ku jiro oo ahaanshaha xornimada kaa celin karo, **ilaa aad ka murugoontid ama aad waxiiyga sugtid.** Bax ee nolosha ku soo raaxayso; la qabso isla bilwogiiba. Daqiiqada mar dhow bay imaan doontaa.
