# Booqashada Ugu Dambeeysa

Adigoo go’aamisay waqtiga [joojinta], waxaad hadda diyaar u tahay inaad u booqdo haremkaaga hal mar kale oo dambeeya. Ka hor intaadan sameynin, iska hubi labada oo aasaasiga ah. 

1.  Ma hubtaa inaad guulaysanayso?

2.  Dareen oo murug iyo niyad-jab maad haysataa, mise dareen farxad inaad u dhowdahay inaad hesho wax oo aad u fiican?

Haddii aad wax shaki ah ka qabto, dib u akhriso buuga. Xasuusnow inaadan weligaaga go’aaminin inaad ku dhex dhacdo dabinka porn, oo laakin dabinka loogu talagalay inuu ku addoonsado inta noloshaada ka haray. Si aad u baxsato, waxaad u baahan tahay inaad sameyso go'aanka firfircoon inaad joojinayso oo aad sameyso booqashadaada ugu dambeeysa. 

Xasuuso, sababta kaliya oo aad buugaan ilaa hadda u akhirsay waa inaad aad u jeceshahay inaad ka baxsato. Marka hadaba go’aanta firircoonka samey, adigoo sameynayso dhaarashada adaga in markaad browserka gaarka ah aad xirto, ha u aragto fudud mise adag, inaadan weligaaga haremkaaga mar dambe u booqanaynin. Waxaa laga yaabaa inaad ka walwalsan tahay inaad dhaarashadaan dhowr marar sameysay waagii hore oo aad weli guul darraysanooso, ama inay noqon doonto inaad dhex marto dhaawac oo aad u xun. Ha ka baqin, waxa oo aada ugu xun oo kugu dhici karo waa inaad guul darreysato, marka sidaas darteed waxaad ***gabi ahaan jira waxba*** oo aad ka khasaarayso iyo wax badan oo aad ka faa’iidayso.

Laakin iska day inaad xataa guul darrada ka fikirto — runta quruxda badan waa inaysan kaliya ahayn inay si qosol leh u fududahay in la joojiyo, oo laakin aad sidoo kale habka ku raaxaysan kartid. Markaan waxaad isticmaali doontaa EasyPeasy! Waxa kaliya oo u baahantahay inaad sameyso waa inaad raacdo tilmaamaha oo lugu siin doono.

1.  Hadaba dhaarashada dhabta samey ee ula jeeddo.

2.  Si miyir ah u browsegareey sawirada iyo muuqaalaha mareegta porn oo aada ugu jeclayd, adigoo u fiiriinayso isku dayga maamulaha, jiilayaasha, kuwa aan xirfad lahaynta ee mareegta oo quusta ah inay boonbooniyaan dabiiciga naxtinta, cusaybta, iyo xad-dhaafsan ee bedeecadooda, waxaana is weydiisaa meeshii ay raaxada jirta.

3.  Markaad ugu dambeyntii browserka xirto, ha sameynin adigoo leh dareenka, “*Waa inaan weligayga mar dambe harem online kale booqdo.*” mise “*La iima ogola inaan booqdo mid kale.*" oo laakin lidkeeda adigoo leh dareen xoriyad, sida, “*Way fiican tahay, sow maha? Xor ayaan ahay! Hadda ka dambeeya ma ihi addoonka porn! Ma aha inaan mar kale gudaha noloshayda booqdo mareegyaashaan oo wasakhda ah.*”

4.  La soco in, in dhowr maalmood, ay jiri doonto wax yar oo dumiye porn ee gudaha calooshaada. Waxaa laga yaabaa inaad kaliya ka warqabto dareenka rabitaanka porn. Shaydaanka yar ee porn waxaa loogu tilmaamay sida damaca yar jireedka ee dopamine. Dhab ahaantii tani way khaldan tahay, waxayna muhiim tahay in sababta la fahmo. Maadaama ay qaadato ilaa saddex toddobaad inuu shaydaankaas yar dhinto, isticmaalayaashii hore waxay aaminsan yihiin inuu shaydaanka yar sii damaci doono booqashada haremka onlineka ugu dambeeya ka dib. Sidaas ma aha, jirka ma damco dopamine oo porn kicisay; waa kaliya maskaxda oo damco.

Haddii aad haysato dareenkaas ee rabitaanka hal fiirin adigoo ku jirto dhowr maalmaha xigta, maskaxdaada waxay qabtaa doorasho fudud. Waxay midba dareenkaas u fasiri kartaa waxa uu dhab ahaantii yahay — dareen maran, oo kalsooni darran oo ka bilaabtay booqashada koowaad ee mareeg porn oo laga sii waaridayo mid kasta oo xigta, oo aad is dhehdo, “**AAHEEY! WAXAAN AHAY QOF OO ISTICMAALE AHAYN!**”

Mise, waxaad bilaabi kartaa inaad porn u damacdo oo aad dhibaatoodo inta noloshaada ka haray. Hal daqiiqad kaliya lee ka fikir, taasi ma ahaan lahaynoo wax oo aad oo doqon badan in la sameyo? In la dheho, “*Ma rabi inaan weligayga porn daawado mar kale*” oo markaas inta nolosha ka hary dhan lugu qaato isagoo la dhehaayo, “*Waxaan jeclaan lahaayay booqo.*”? Taasi waa waxa kuwa oo isticmaalayaan habka awooda-rabitaanka ay sameyaan, yaabna ma leh waxa ay u dareemeyaan dareeman oo aad u darxumeysan. Iyagoo qaadanayaan inta noloshooda ka haray iyagoo si quus ah u murugayaan wax oo ay si quus ah u rajaynayaan inaysan weligooda haysanin. Yaab ma leh inay dhowr oo aad u yar u guuleystaan oo kuwa oo guuleystaan ay weligooda xornimo si buuxda u dareemin.

> *'‘Sawirkaan oo maskaxeeda ah si cad maskaxdaada u geli, waayo wuxuu ahaan karaa wax oo aad uu caawin badan ee ka adkaanta xooga kicinta dibadda ah oo ku dhibo. Is arag adigoo si aamusan u fadhiso, adigoo u ogol inuu telefoonka yeero, adigoo iska dhega tirday calaamadiisa, oo aad ka dhaqaaqaynin amrigiisa. In kasta oo aad ka warqabtid, dhib kama lihid mana addecisid. Sidoo kale, si cad u geli maskaxdaada xaqiiqda in calaamada banaanka aysan naftigeeda xoog kugu lahayn, xoog ay kugu dhaqaaji lahayd. Waagii hore waad addeeci jirtay, waad u jawaabtay, si buuxda caado ahaan. Waad sameyn kartaa, haddii aad rabto, inaad ka qaabto caado cusub jawaab la’aanta.*
>
> *Sidoo kale u fiirso in guul darradaada inaad [calaamadaas] u jawaabto ay ka koobnayn inaad wax sameyso, ama dadaalka, ama iska caabinta ama dagaalka, oo laakin ay ka kooban tahay in wax la sameynin — in laga nasto wax sameynta. Kaliya waad nasataa, waad iska dhega tirdaa calaamada, waxaana u ogoshaa in u yeeridiisa ay ahaadaan kuwa oo aan dhegta loo dhigin. Teleefoonka oo yeeraaya wuxuu yahay barbardhiggid oo astaan u ah kicin dibad walba oo kale oo laga yaabo inaad si caado ah u siiso xakamta oo aad hadda si ula kac ah u rabto inaad caadadaas beddesho.*'
>
> ---  Maxwell Maltz, "The New Psycho Cybernetics” Cutubka 12-aad. 

Waa shakiga iyo sugitaanka kaliya oo adag ka dhigayaan in la joojiyo, **marka weligaaga ha ka shakinin go’aantaada** waayo waa ogtahay inay tahay midda saxda ah. Haddii aad bilowdo inaad ka shakiso, waxaad is gelinsysaa xaalid oo guul jirin. Darxumeysan adigoo booqasho u damacdo, oo laakin karti u lahayn inaad hal haysato. Si kastaba ha ahaatee nidaamka aad isticmaalayso, maxaad rabtaa inaad ka hesho markaad porn joojinayso? Inaad weligaaga daawanin mar dambe? Maya! Isticmaalayaal badan oo hore ayaa sidaas sameyaan laakin waxay dhex maraan inta noloshooda ka haray iyagoo dareemayaan in wax laga qaaday. 

Waa maxay farqiga u dhexeeya isticmaalayaasha iyo kuwa oo aan isticmaale ahayn? Kuwa oo isticmalayaasha ahayn baahnaansho ama rabitaan oo dhan uma qabaan inay porn daawadaan, way damac la’aan yihiin mana u baahna inay awooda rabitaankooda isticmalaan si aysan u daawanin. Taasi waa waxa aad isku dayayso inaad hesho, waxayna gabi ahaanba ku jirtaa awoodaada inaad sidaas sameyso. Ma aha inaad sugto ilaa ay damaca joogato ama aad noqoto qof oo aan isticmaale ahayn, way dhamaanaysaa daqiiqada oo aad xirto browserkaas ugu dambeeya, taasi oo goynayso sahayda dopamine. **HORAAN AYAAD U TAHAY QOF AAN ISTICMAALE AHAYN OO FARAXSAN!**

Waxaad ahaanaysaa qof oo isticmaale ahayn ilaa inta:

1.  Aadan weligaaga ka shakinin go’aantaada. 

2.  Aadan sugin inaad noqoto qof oo isticmaale ahayn. Haddii aad sugto, waxaad kaliya u sugi doontaa inay waxba dhicin waxayna abuuraysaa cabsi.

3.  Aad isku dayin inaadan porn ka fikirin ama aadan sugin in ‘daqiiqada waxiiyga’ ay imaado, taasi oo abuurayso cabsi.

4.  Aadan beddelka isticmaalin.

5.  Aad u aragto isticmaalayaasha kale oo dhan sida ay runtii u yihiin oo aad u naxariisato intaad ka maseeri lahayd.

Ha ahaadaan maalmo fiican mise kuwa xun, noloshaada ha beddelin waayo aad joojisay kaliya. Haddii aad sidaas sameyso, waxaad sameyn doonta hurid dhab ah markaadan u baahnayn. Xasuusnow, ma ka tanaasulin noolaanta. Waxba kama tanaasulin. Taas lidkeeda, waxaad iska daaweysay cudur oo aad u xun waxaana ka baxsatay xabsi oo aad u qarsoodisan. Maalmaha intay dhaafaan oo ay caafimaadkaaga — labadaba jireedka iyo maskaxeeda — ay hagaagto, xaaladaha sareysan waxay u muuqan doonaan in ka sareysan iyo xaaladaha hooseeyaan waxay u muuqan doonaan in ka sareysan.

Mar kasta oo aad porn ka fikrto intaad ku jirto dhowr maalmaha xigaan mise inta noloshaada ka haray, u fikir:

***"AAHEEY! WAXAAN AHAY QOF OO ISTICMAALE AHAYN!"***

## Digniinta Ugu Dambeeysa

Ma jiro isticmaale, haddii la siin lahaayay fursada inuu dib ugu laabto waqti ka hore intuusan la qabatimin, isagoo haysto aqoonta uu hadda haysto, oo dooran lahaayay inuu bilaabo. Tobanaan kun oo qof oo si guul leh sanado badan iskaga sareen balwada ayaa haystaan nolol oo aad u farax badan, oo ay kaliya dabinka ku dhacaan mar kale. Waxaan aaminaa inay buugaan kaa caawinayso inaad u aragto inay aad u fududahay in la joojiyo. Laakin digtoonow, isticmalayaasha oo si fudud u arkaan joojinta waxay isla fudud u arkaan inay [isticmaalka] mar kale bilaabaan. **Ha ku kadsoomin dabinkaan!**

Si kasta u dheer oo aad joojisay ama aad ugu kalsoon tahay inaadan weligaaga la qabatimi doonin, xeer nololeed ka dhig inaadan porn u daawanin sabab walba. Iska caabi tixraacyada iyo soo jeedinta galmeeda oo warbaahinta ku jiraan ee xasuuso sida ay u xayaysiinayaan sawirkooda ‘maskax-furannimada’ iyagoo porn soo gelinayaan dhaqanka caadiga ah, iyagoo ka warqabin in porn iyo siigaysashada qasabka ah ay yihiin dilaayaasha xiriirada iyo [dilaayaasha] dareenka shaqsi ahaaneed ee wanaagga ee tirrada nimanka oo aad u badan iyo tirrada kordhayaan ee naagaha. 

Xasuuso in fiirintaas ama booqshadaas ugu horreeya ay waxba kuu qabanaynin. Ma haysan doonto xanuunada ka noqosha oo aad iska nafisi karto, waxayna kaa dhigi doontaa inaad haysato dareeman oo aad u xun. Waxa oo ay sameynayso waa inay geliso raaxada daadashada dopamineka degdegsan ee maskaxdaada, iyo [markaas]cod yar oo maskaxdaada gadaasheeda jiro ayaa kuu sheegi doono inaad mid kale rabto. Markaas waxaad haysan doontaa doorashada ahaanshaha darxumeysan ee muddo yar ama aad mar kale soo bilowdo meertada oo wasakhda ah.