# Jawaab Celinta

Dagaalkaan ma aha mid oo isticmaalayaasha ka dhan ah, laakin wuxuu ka dhan yahay dabinka warshadaha porn, waxaana dagaalkaan loo waddaa sababta kaliya oo ah inaan ku raaxaysto inaan waddo. Mar kasta oo aan maqlo isticmaale oo ka baxsaday xabsiga waxaan helaa dareen oo aad u farxad badan. Laakin farxadaan ma jirin iyadoo xanaajin oo aad u badan la’aanteed, tan oo inta badan laga keenay laba qaybood oo isticmaalayaal. In kasta oo laga digay digniinta cutubka hore, waxaan si joogto uga yaabaa tirrada kuwa oo fudud u arkaan inay joojiyaan, oo laakin hadhowtii la qabatimaan oo ay arkaan inaysan guuleysan karin marka xigta. 

Waxay la mid tahay in la helo qof oo ku jira dhiiqo oo gaarayso ilaa qoortiisa oo u dhow inuu hoos galo. Waxaad ka caawisaa inay soo baxo wuuna kaa mahadsan yahay oo laakin markaas, lix bilood ka dib, wuxuu ku sii toos dib uga quustaa dhiiqada. Isticmaalayaasha oo u arkaan inay fududahay in la joojiyo oo mar kale bilaabaan waxay keenaan dhibaato oo gaar ah, sidaasba ha ahaadee, markaad xor ka noqoto, **FADLAN, FADLAN, FADLAN HA SAMEYNIN QALADKA LA MID AH!** Waxay u maleeyaan in dad kuwaas oo kale ay mar kale u bilaabaan waayo ay weli la qabatimsan yihiin oo ay u xiiseen dopamine-ka. Dhab ahaantii, waxay joojinta sii aad u fudud u arkaan ee cabsidooda porn wayba ka dhumtaa. Waxay u fikiraan, “*Fadhi kale waan haysan karaa, iyo xataa haddii aan mar kale la qabatimo, waxaan u arki doonaa inay fududahay in la joojiyo.*” 

Waxaan ka baqaayaa inay sidaasba u shaqaynin, waayo way fududahay in porn la joojiyo oo laakin ay macquulba ahayn in balwadda la xakamo. Halkii arrin oo assaasiga ah ee joojinta porn waa in la isticmaalin.

Dadka waxay caadi ahaan porn ugu laabtaan waayo si khalad ay u fahmaan qaybta “fudud” ee Habka Fudud ku jira. 

Ka fikir qof oo fadhiyo dhulka shamiindada qabowga ee qol oo aad u qabojisan. Darbiga oo iyaga dhincaca lidkooda jira waxaa jira daaqad oo tuusaysa banaanka maalin gu’ ah oo kaamilsan — geedaha oo si tartiib u lulaaya, shimbiraha yeeraaya — taasi oo ag yeesho irid furan.

Awooda rabitaan may qaadanaysaa in laga baxo qolkaas oo qabowga badan? Maya! Baxsashada ma ka adag tahay joogida? Dabcan, maya! Dhab ahaantii, kistoo wayba ka fududahay maadaama uu jirka dhaqaaqaayo. Waa maxay sababta qof kasta oo maskaxdiisa qumman uu naftiisa gelinaya xaalad oo noocaas ah, taasi oo naftiisa u horseedisa bilood ama sannado oo xanaajin badan haddii aan la khiyaamin?

EasyPeasy wuxuu gees u riixaa daahyada si uu isticmaalaha si cad banaanka u arki karo iyo si uu ka saaro **dhalanteedyada** ee sida uu banaanka ay aad u xun tahay iyo sida u raaxaysan isticmaalaha uu qolka ku yahay. Qaybta kale ee isticmaalayaasha xanaajinta badan waa kuwa oo aad uga baqayaan inay sameyaan isku dayga inay joojiyaan, ama markay sameyaan, waxay u arkaan wax oo aad u dhib badan.

Dhibaatooyinka ugu weyn waxay u muuqdaan inay yihiin kuwa oo soo socda.

**Cabsida guul darada.**

:   Ceeb kuma jira guul darada, laakin inaadba isku dayin si cad ayay u nacas badan tahay. Sidaan oo kale u fiiri: waxaad ka dhuumanaysaa wax oo waxba ahayn. Waxa ugu xun oo kugu dhici karo waa inaad guul dareysato, oo ay markaas xaladaada ka xumayn sida ay hadda tahay. Ka fikir sida ay aad u fiicnaan lahyad inaad guulaysato. Haddii aadan isku dayga sameynin, waxaan horeyba isla dhamaanad qaaday guul darrada. 

**Cabsida xanuunka iyo ahaanshaha darxumeysiga.**

:   Ha ka walwalin, ka fikir kaliya: maxaa jira oo xun oo kugu dhici karo haddii aadan weligaaga porn daawanin mar dambe? Gabi ahaan, waxba. Waxyaalaha xun waxay dhacayaan **haddii aad** sameyso; dib u akhriso qoraalada oo ku saabsan Wager Pascal. Si kastaba ah ahaadee, argagaxa waxaa keena dopamine wayna bixi doontaa mar dhow. Faa’iidada ugu weyn waa inaad iska saarto cabsidaas. Runrun maad u aaminsantahay inay isticmaalayaasha diyaar u yihiin kacsi-galmada daciifka, waxqabadka galmada aan la isku halayn karin, ama raaxada dhalanteedka ay porn ka helaan? Haddii aad is aragto adigoo argagaxayso, neefsasho qoto dheer ayaa ku caawinayso. Haddii aad dad kale la jirto oo ay hoos kuu jiidayaan, ka baxso iyaga iyo gal garaashka, xafiis maran, ama meel kale.

    Haddii aad dareento inaad oohin doonto, ha ka ceeboonin. Oohinta waa dabiicga habkiisa ee nafisashada cadaadiska. Ma jiro qof oo si fiican u ooyay isagoosan in ka fiican u dareemin ka dib. Mid ka mid ah waxyaalaha xun aan ku sameyno nimankeena dhalinyarada waa inaan barno inaysan ooynin. Waxaad arki kartaa iyagoo isku dayayaan inay ilinta isku celiyaan, laakin u fiirso sida uu daankooda u gariiraaya. Waxaan is-barnaa inaanan muujinin shucuurta, laakiin looguma talagalin inaan shucuurteena ku ilaalino gudaha. Qayli, cawaad, ama dagaal. Wax haraanti. U arag dhibaatadaada sida ciyaarta feerka oo aadan ka guul dareysan karin. Qofna ma joojin karo waqtiga, daqiiqad walba oo ku dhaafdo shaydaankaasi oo yar oo kugu jira ayaa dhimanooyo. Ku raaxayso guushaada oo lama huraanka ah.

**Aan tilmaamaha la raacin.**

:   Si yaab leh, isticmaalayaasha qaarkood waxay dhehaan inuu habkaan iyaga u shaqaynin. Waxay markaas sifayaan sida aysan iska dhega tirin hal tilmaamo kaliya, oo laakin ayba kuligooda iska dhega tireen. Si loo caddeeyo, [tilmaamahaan] waxaa lagu soo koobay sida liis hubin ee dhamaadka cutubkaan.

**Si khaldan loo fahama tilmaamaha.**

:   Dhibaatooyinka ugu weyn waxay u muuqdaan inay kuwaan yihiin:

    "*Ma joojin kari ka fikirka porn.*"

    :   Dabcan ma joojin kartid iyo haddii aad isku daydo, cabsi ayaad abuuri doontaa, taasi oo darxumeysan kaa dhigayso. Waxay la mid tahay isku dayga inaad hurdo hesho habeenkii: inta ka badan aad isku daydo, inta ka badan ay adkaanayso. Dhib ma laha haddii aad ka porn fikirto boqolkiiba 99 ee noloshaada, waa wixii oo aad ka fikirayso wixii oo muhiim ah. Haddii aad ka fikirayso, “*Alla, waan jecelahay inaan porn fiiriyo*” mise “*Goormay xor ka noqonayaa?*” waxaad ahaanaysaa qof oo darxumeysan. Haddii aad taasi beddelkeeda ka fikirayso, “*AAHEEY! XOR AYAAN AHAY!*” waad farxi doonta.

    "*Goormuu shaydaanka yar dhimanaa?*"

    :   Daadashada dopamine si dhakhso badan ayay jirkaaga ka baxaysaa, laakin macquul ma aha in la sheego markay jirkaaga joogsata inay ka dhibaatooda dareeman yar oo jireedka ee ka noqoshada dopamine. Dareenkaas maran oo kalsooni darran wuxuu la mid yahay gaajada, niyad-jabka, ama walbahaarka oo caadiga ah. Waxa kaliya oo porn ay sameyso waa inay heerkooda kordhiso. Tan waa sababta oo ay isticmaalayaasha oo joojiyaan iyagoo isticmaalayaan habka awooda rabitaanka ay weligooda hubin haddii ay balwada iska saareen, in kasta oo uu jirkooda jogsaday inuu ka dhibaatoodo ka noqoshada dopamine. Haddii ay ka dhibaatoodaan gaajo ama walbahaar oo caadi ay, maskaxdooda waxay weliba iyaga u sheegaysaa inay tan ay tahay sabab oo macquul ah oo ay sheegadaan fadhigooda porn ee ‘xaqqa u lahaayeen’. Arrinta waa inaadan u baahnayn inaad sugto inuu damaca kaa tago maadaama uu aad u yar yahay inaanan xataa ogayn inay jirto, oo aan kaliya ugu ognahay sida dareenka rabitaan. Markaad dhakhtarka ilkaha ka tagto, ma sugtaa inuu xanuunka daankaaga joogsado? Dabcan ma sugtid, nolosha ayaad la socotaa. In kasta uu daankaaga weli ku xanuunaaya, waad ka faraxsan tahay [xaqiiqda in lagaa daaweeyay].

    :   Ha sugin inay xanuunada ka noqoshada kaa tagaan waayo cabsi ayaad abuuri doontaa adigoo si joogto is weydiiso, “*Ilaa intee ay tan qaadanaysaa? Miyaan xorba ahay haddii aanan si ka duwan u dareemin?*” Cabsida waa xanuunka dhabta ah, sidaas darteed sugintaanka inay nolosha fiicnaato joojinta ka dib waxay abuuraysaa shaki. Xanuunada ka noqoshada waa waxyaala oo la dareemi karin ilaa aad ka cabsato, iyo soo kabashada aada u weyn ee neerfaha tartiib tartiib bay yihiin, marka haddii aad sugto inaad si ka duwan u dareento, wuxuu u dareemaa inay waxba dhacaynin, taasi oo shaki abuuraysa. 

    *"Daqiiqada waxiiyga ma imaanin weli."*

    :   Haddii aad sugto, waxaad kaliya abuuraysaa cabsi kale. Waxaan markoo saddex toddobaad u joojiyay anigoo ku jira habka awooda rabitaanka. Anigoo la wadahadlaya saaxibkayga hore, wuxuu i weydiiyay sidee ahaayay. "*Waxaan badbaaday saddex toddobaad,*" ayaan ugu jawaabay. Wuxuu i weydiiyay, “*Maxaad ka wadaa inaad saddex toddobaad badbaaday?*” Waxaan u cadeeyay, “*Waxaan joogay saddex toddobaad porn la’aanteed.**” Wuxuu dhahay, “*Maxaad sameyn doontaa? Inta noloshaada ka haray maad badbaadi doontaa? Maxaad sugaysaa, waaba samesay. Waxaad tahay qof oo isticmaale ahayn.*”

        Waxaan fikiray, “*Gabi ahaan wuu saxsan yahay, maxaan u sugayaa?*” Nasiib darrase, dib aan ugu laabtay, laakin arrinta waa xasuustay. Waxaad noqotaa qof oo isticmaale ahayn markaad browserkaaga xirto. Arrinta oo muhiimka ah waa inaad bliowgiiba ahaato qof isticmaale ahayn oo faraxsan. 

    "*Weli porn ayaan rabaa.*"

    :   Marka waxaad iska dhigaysaa qof oo aad u doqon badan. Sidee u sheegan kartaa inaad rabto inaad ahaato qof oo isticmaale ahayn oo aad markaas dhedo inaad porn rabto? Taasi waa khilaaf. Haddii aad dhahdo inaad porn rabto, waxaad dhohaysaa inaad rabto inaad isticmaale ahaato. Dadka oo isticmaalayaasha ahayn ma rabaan booqdaan mareegaha porn oo yaqyaqsada badan. Waaba ogtahay wixii oo aad rabto, marka iska day inaad naftaada cadaabto.

    "*Noolaanta ayaan ka quustay.*"

    :   Maxaa? Waxa kaliya oo aad u baahantahay inaad sameyso waa joojinta inaad naftaada disho oo aad taasi beddelkeeda tamar geliso. Ma aha inaadan ugu yaraantii nolaantaada joojiso. Sidaan ayay u fududahay: Dhowr maalmaha oo xigaan waxaad haysan doontaa dhaawac yar oo noloshaada ku jira. Jirkaaga wuxuu ka dhibaatoon doonaa sii xumaanshaha oo u dhow in la fahmi karln ee xanuunada ka noqoshada oo ka imaadaan dalbashada iyo sheegitaanka daadasho dopamine. Haddaba, tan maskaxda ku haay: xaaladdaada sidii ay ahaan jirtay kama sii xumaanayso. Tani waa wixii oo aad ka dhibaatoonaysay noloshaada oo dhan, mar kasta oo aad hurdaysay, aad masaajidka ku jirtay, aad dukaanka ku jiray, ama maktabadda. Uma ekayn inay ku dhibayso markaad isticmaale ahayd iyo haddii aadan joojinin, waxaad sii soconaysaa adigoo ka dhibaatoonooso dhibkaan inta noloshaada ka haray.

        Porn iyo orgasmyada dhacdooyinka [fiican] ma sameyaan, way kaa qaadaan. Xataa markuu jirkaaga weli dopamine u damcooyo, cuntada iyo dhacdooyinka bulsheeda aad bay fiican yihiin. Nolosha ayaa aad u fiican — aad xafladaha bulsheeda, xataa haddii ay jiraan qob-ka-ciyaara oo qaawan. Xasuuso: adiga ma aha qofka oo wax laga qaaday, waa isticmaalayaasha. Mid kasta oo iyaga ka mid ah waxay jeclaan lahaayeen inay booskaaga ku jiraan, haddii ay kaliya wax ogaan lahaayeen. Ku raaxayso ahaanshaha prima donna-da iyo dhexda dareenka. Joojinta porn waxay tahay arrin fiican ee wadahadlka, adigoo haysan karto raaxo qarsoodisan oo aysan haysan karin. Saaxiibadaada waxay ka yaabi doonaan inay ku arkaan adigoo, waagii hore ahaan jirtay qof xishoodsan oo daalan, aad hadda tahay qof oo faraxsan. Waxaad bilowgiiba nolosha ku raaxaysan doontaa; uma baahnid inaad ka maseerto fanaaniinta naaga-doonistaha oo xafladaha joogaan, adiga bay kaa maseeri doonaan — haddii ay kaliya wax ogaan lahaayeen.

    "*Waan darxumeysanahay waana xanaajinsanahay.*"

    :   Tan waa guul darro in tilmaamaha la raaco. Soo ogow midda ay tahay. Dadka qaarkooda way fahmaan wayna aaminaan wax walba oo la qoray, laakin waxay weli ka bilaabaan dareen oo niyad jab oo murugaysan, sida haddii ay wax aad u xun ay dhacooso. Ma sameynoosid kaliya waxa oo aad jeceshahay inaad sameyso, laakin waxaad sidoo kale sameynaysaa waxa oo isticmaale walba oo dhulkaan degan uu sidoo kale u jecelaan lahaayay inuu sameyo. Sida hab kasta ee joojinta, isticmaalihii hore wuxuu isku dayayaa inuu helo qaab maskaxeed oo gaar ah, marka fikrad walba oo porn ku xiran waxaa lugu xoojiiyaa, “*AAHEEY! XOR AYAAN AHAY!*” Haddii ay taasi ujeedadaada tahay, maxaad u sugaysaa? Ka bilow qaab maskaxdaas weligaaguna yee kaa dhumin. Ma jiro wax beddel ah.

    "*Waxaan haystay hal toddobaad / hal bil / lix bilood oo fiican laakin dib ayaan dabinka ugu jiraa*"

    :   Xasuusnow: cabsida waa xanuunka naftigeeda. Inaad xanuun dartiisa ku tanaasusho wuxuu abuuraa cabsi oo ka badan, taasi uu quudinayso shaydaankii yare oo la daciifay oo ay guulaysato inay ka nixiso qofka oo isticmaalaha ahayn inuu u maleeyo inuu la qabatimay inta noloshiisa ka haray. Dhab ahaantii, aragtinimadiisa maskax-xadashada ayaan is beddelin, laakin wuxuu habka fikradahiisa siiyay dopamine. Tani waa, qeexitaan ahaan, wax ka barashada khaladaadka laakin waxay [sidoo kale] tahay guul darada in tilmaamaha la raaco. Hoos ka faham midkee [aad ku guul dareysatay inaad raacdo] ee ka farax.

## Liiska Hubinta

Haddii aad tilmaamahaan raacdo, ma guul dareysan kartid:

1.  Dhaarashada dhabta samey inaadan weligaaga online galaynin inaad haremkaaga online booqato *AMA* aadan ku qanacdo sawirada qaawan *AMA* aadan la qabsato sawirada kacsiga *AMA* waxyaala oo dhan oo ay ku jiraan kicin xad-dhaafsan oo aan caadiga ahayn, ee ku dheg [inaad] dhaarashadaada [raacdo].

2.  Tan maskaxdaada ku caddeey: Gabi ahaan waxba ma jira oo laga tanaasulo. Markii taasi la dheho, macnaha midna ma aha inaad ka fiicnaan doonto ahaanshaha qof oo PMO sameynin (halahaan oo dhan ayaaba tan ogayd); ama in kasta oo aysan jirin sabab macquul oo aad PMO ku sameyso, aad weliba raaxo ama taageero ka hesho maadaama aadan sameyn lahayn haddii kale. Waxaa oo [runtii] laga wado waa ***inaysan ku jirinba raaxo ama taageero sameynta PMO.** Waa dhalanteed kaliya, sida inaad madaxaaga darbi ku dhufato si aad ugu raaxaysato markaad joogsato.

3.  Ma jiro wax oo la dhoho isticmaale porn oo la xaqiijiyay. Waxaad kaliya ka mid tahay boqolaada oo malaayinkuwa oo ku kadsoomeen dabinka qarsoodisan. Sida malaayinka kale oo PMO-yaalihii hore oo markoo u malayeen inaysan ka baxsan karin, waad ka baxsatay.

4.  Haddii, adigoo ku jirto waqti kasta oo noloshaada, aad barbardhigi lahayd faa’iidooyinka iyo faa’iiido darrooyinka PMO-ga, gunaanada waxay had iyo jeer ahaan lahayd, “*Jooji sameynta. Doqon baad tahay.*” Waxana oo taasi beddeli kara ma jiro. Weligeeda sidaas ay ahayd, weligeeduna sidaas ayay ahaanaysaa. Adigoo sameysay wixii oo aad ogtahay inay tahay go’aanta saxda, haba is-cadaabin ee shakiga. Wagerka Pascal wuxuu si kaamil ayuu ugu khusayaa PMO, adigoo fursad u haysanin inaad khasaarto, oo aad qabto fursado sareysan inaad faa’iidaysato iyo fursado sareysan inaad khasaaraha ka foogado.

5.  Ha isku dayin inaadan porn ka fikirin, ama aad ka walwasho inaad si joogto uga fikirayso. Mar kasta oo aad ka fikirto, ha ahaato maanta, berrito, ama inta noloshaada ka haray, waa inaad fikirto, **“AHEEY! WAXAN AHAY QOF OO PMO SAMEYNIN.”**

6.  **Ha isticmaalin** nooc oo beddel ah. **Ha kula tartamin naftaada** inaad laptop-kaaga ag dhigato markaad hurdayso. **Ha ka fooganin** riwaayadaha, filimada, ama majaladaha. **Ha beddelin** qaab nololeedkaaga sinaba waayo aad joojisay kaliya. Haddii aad raacdo tilmaamaha kore, waxaad mar dhowti la kulmi doontaa ‘daqiiqada waxiiyga’, laakin:

7.  Ha sugin inuu ‘daqiiqada waxiiyga’ imaado. Nolaashaada la soco, adigoo ku raaxaysanooso xaaladaha sareysan oo aad la qabsato kuwa oo hooseeya. Waxaad arki doontaa inuu si dhakhsasho badan daqiiqada u imaan doono.
