# Caawi Dadka oo Saaran Markabka Quusaya

Isticmaalayaasha porn waxay maalmahaan argagaxsan yihiin, iyagoo dareemayaan sida nimanka iyo naagaha ay porn u arkaan. Dabiiciga qabatimsan ee porn-ka internetka ayaa si isa soo taraysa loo darsooyaa marar badan, iyadoo hadda si saxsan loo tixgeliyo inay porn-ka caadiga ah (sawirada) ka duwan tahay. Dadaal la'aannimada [oo helitaanka ku jira]  iyo helitaanka [fududa] waxay xataa kor ugu qaadaan digniinshaha qalbiga isticmaalayaasha porn. Waxay sidoo kale u dareemaan in ololahooda xoriyatul-qawlka iyo fikrada ay arrimo kala duwan ka afduubeen. Internet-ka oo la ilaalinin ayaa ka dhigaya wax oo u dhow inuu suurtogal aheyn in la dhaqan geliyo xayiraadaha da'da ee kicinaha xad-dhafsan. Way nasiib daran tahay in tani ay mar dhow dhamaan doonin, laakin boqolaal kun oo isticmaalayaal ah ayaa joojinayaan, iyagoo balwadaha badankooda ay ka warqabaan daraasadaha oo muujinayaan isku-mid ahaanta porn iyo balwada daroogada. Mar kasta uu isticmaale ka tago markabka quusaaya, kuwa oo markabka ku soo haraan waxay dareemaan darxumeysi oo ka sii badan.

Isticmaale walba wuu og yahay inuu doqon yahay in la is-burburiyo oo waqti lugu qaato sawirada laba-geesooda hortooda, isagoo si xad-dhaafsan u kicinaya maskaxdiisa oo uu, isagoo habka ku jira, horumariyo waddooyin neerfo oo ka damaanad qaadayaan waxqabad galmeed oo liita ah. Haddii aadan weli u malaynin in taasi ay doqon tahay, isku day inaad la hadasho majalad porn adigoo taagan bartamaha magaaladaada ee is weydii maxay ku kala duwan yihiin. Hal kaliya. Ma heli karto raaxada diirimaadka iyo xiriir qoto-dheernimada adigoo sidaas sameynaysid. Haddii aad joojin karto gadashada khamriga iyo sigaarka mar kasta oo aad dukaamaysato, waxaad hubaal ka joojin kartaa inaad booqdo hareemkaaga online. Isticmaalayaashu ma heli karaan sababo macquul ah oo loogu talagalay daawashada porn, laakiin ma dareemaan inay doqon yihiin maadaama ay dadka kale sidaas sameyaan. 

Isticmaalayaasha waxay si cad uga been sheegaan caadooyinkooda, ma aha kaliya cilmi-baarayaasha iyo dadka ku xeeran, laakiin sidoo kale naftooda. Waa inay sidaas sameyaan - maskax-xadashada waa lama huraan haddii ay rabaan inay ilaaliyaan dhowr is-ixtiraamaankooda. Ma aha inay kaliya dareemayaan baahida loo qabo inay naftooda 'caadadooda' qiil ugu yeelaan, laakiin waxay sidoo kale [dareemaan baahida inay qiil ugu yeelaan] dadka oo isticmaalayaasha ahayn. Waxay weligooda xayeysiiyaan faa’iidooyinka dhalanteedsan ee porn iyagoo isticmaalayaan habab oo ka sii qarsoodisan. 

Haddii uu isticmaale joojiyo isagoo isticmaalaya habka awood rabitaan, wuxuu weli dareemaa in wax laga qaaday wuxuuna u janjeeraa inuu noqdo baroore. Waxa kaliya ee tani ay sameyso waa in loo xaqiijiyo isticmaalayaasha kale sida ay ugu saxsan yihiin inay sii wadaan isticmaalkooda. Haddii uu isticmaalihii hore guuleysto inuu balwada iska saaro, wuu mahadsan yahay inuusan mar dambe u baahnayn inuu is-burburiyo ama uu tamartiisa khasaariyo, baahidna uma haysto inuu naftiisa qiil u yeelo. Xasuusnow: waa cabsida oo madaxa isticmaalaha ciida gudaheeda ku haayo, isagoo kaliya su’aal dhaqankiisa ka keenaayo markuu joojiyo. Ka caawi isticmaalaha adigoo meesha ka saaraysa cabsidaas. U sheeg sida ay u wanaagsan tahay in nolosha aan la dhex marin adigoo xabsi ku dhex nool, sida ay u qurux badan tahay in subaxdii la soo kaco adigoo dareemayso inaad jirdhisan tahay oo aad caafimaad qabto intaad tamar la’aan ahaan lahayd oo aad is-nacaybi lahayd, sida ay u fiican tahay inaad xor ka ahaato addoonsinimada, [iyo] inaad kartida haysato inaad noloshaada oo dhan ku raaxaysato aad ka takhaluso hadh kuwaas oo madow. Ama weliba sii ka fiican, ka dhig inay buugaan akhriyaan. 

Waa lama huraan in aan la dhayalsanin isticmaale oo xaas leh adigoo u tilmaamaya inuu is ula kac u burburinaayo xiriirkiisa ama inay si uun khiyaano tahay ama nijaas. Waxaa jira fikrad khaldan oo caadi ah oo ah in isticmaallihii hore uu dhinacaan ugu xun yahay. Fikirkaan wuxuu leeyahay xoogaa run ah, laakiin guud ahaan waxaa sabab u ah habka awooda rabitaanka ee joojinta. Maadaama isticmaalihii hore — in kasta oo uu balwada iska saaray — wuxuu weli haystaa qayb oo maskax-xadashada ka mid ah wuxuuna weli aaminsanyahay inuu hurid sameyay. Wuxuu weli dareemaa nugul iyo habkiisa difaaca dabiiciga ah waa inuu weeraro isticmaalaha porn. 

Waxaa laga yaabaa inay tan kor u qaado ego-ga isticmaalihii hore, laakin waxba kama caawiyo isticmaalaha. Waxa oo dhan ay tan sameyso waa inay dhabarkiisa derbiga saarto, taas oo ka dhigaysa inuu dareemo murugo badan iyo, cawaaqib ahaan, in baahidiisa porn ay ka sii weynaato. In kasta oo isbeddelka dabeecadda Aasaaska Caafimaadka ee porn ku aaddan ay tahay sababta ugu weyn ee isticmaalayaasha ay badankooda u joojinayaan, ma ka dhigayso wax oo ka fududaysan in la sameyo. Dhab ahaantii, waxayba ka dhigtaa oo aad uga adag badan. Isticmaalayaasha intooda badan maalmahan waxay aaminsan yihiin inay inta badan u joojinayaan sababo caafimaad dartood. Tani gabi ahaan run uma aha. 

In kasta oo khatarta caafimaad ee weyn ay tahay sababta ugu weyn ee joojinta, isticmaalayaasha waxay sanado badan baabi'inaayeen ragnimadooda, weligeeduna ma samaynin xataa farqiga ugu yar. Sababta ugu weyn ee ay isticmaalayaasha u joojinayaan waa inay bulshada bilaabaysa inay porn u aragto waxa ay dhab ahaantii tahay: balwada daroogada. Hab-dhaqanka bulshooyinka si tartiib tartiib ah ayay isku beddelayaan: lammaanayaal badan waxay hadda su’aal ka keenaan haddii aad laptop-kaaga saaran tahay habeen barkii.  

Porn-ka oo si buuxda u maamnuucsan ee wadamada qaarkooda ama internet la'aanta waxay yihiin tussaleyaal caadi ee doorshada laba daran ee isticmaalihii oo safaraynaya. Guud ahaan wuxuu qaataa hab-dhaqanka inuu ka caawin doono inuu [mamnuuca wadanka] isticmaakiisa yareynaysa. Natiijada waa meeshi uu hal mise laba mar halkii maalin [uu isticmaali lahaayay], midna uusan jeclaan lahayn, wuxuu [hadda] ka foogadaa hal toddobaad oo dhan. Sidaasba ha ahaatee, intuu ku jiro waqtigaan oo ka-foognaanshaha oo qasabka ah, ma aha inuu kaliya si maskaxeed u dareemaya in wax laga qaaday isagoo abaalmarintiisa sugaaya, laakin jirkiisa ayaa sidoo kale u damacaayo. Alla, sida ay booqadaas haremka onlineka u qiimeysan tahay markii ugu dambeyntii loo ogolaado inuu kaligiisa ahaado. 

Ka-foognaanshaha qasabka ah, dhab ahaantii, hoos uma gooyo qasdashada porn waayo isticmaalaha wuxuu kaliya si ka badan is gelinayaa markii ugu dambeyntii loo ogolaado. Waxaa oo dhan ay tani sameyso waa inay geliso maskaxda isticmaalaha sida ay porn u qiimaysan tahay iyo sida uu ugu tiirsan yahay. Dhinaca ka-foognaanshahaan oo qasabka ee ugu khiyaano badan waa saameynta uu dhalinyarada ku leeyahay. Waxaan u ogolaanaa in afduubayaasha 'xoriyatul qawlka', soo saarayaasha porn, ay u beegsadaan dhalinyarada oo nasiib-darrada ah si ay marka horeba balwad ka dhigaan. Markaas, intay ku jiraan waxa oo u badato inay tahay xiliga noloshooda ugu walbahaarsan, markay, maskaxdooda dhalantaysan, ay porn ugu baahan yihiin, waxaan ku hanjabinaa inay tanaasulaan waayo waxyaalaha oo ay naftooda isku keenayaan. 

Qaar badan ma awoodaan inay sidaas sameyaan oo ay ku qasban yihiin, iyagoo aan khalad lahayn, inay ka dhibaatoodaan aaminsanaanta inay dembiile yihiin inta noloshooda ka haray. Qaar badan [oo kale] way ku guuleystaan [inay joojiyaan] wayna ku faraxsan yohiin inay sidaas sameyaan, iyagoo fikirayaan, “*Hagaag. Tan ayaan hadda si ku meel gaar u sameyn doonaa iyo ka dib markay dhammaato, si kastaba waan bogsan doonaa.*” Kadibna waxaa yimaada xanuunka iyo cabsida shaqo raadinta iyo halganka kale ee qaangaarka, oo ay ku xigto xaalada oo noloshooda 'ugu sareysan' - helitaanka shaqada. Xanuunka iyo cabsida way dhammaadaan, waxayna [isticmaalayaasha hore] dareemayaan ammaan, markaa farsamadii hore ee kicinta ayaa dib ugu soo noqotaa shaqada. Qayb oo maskax-xadashada ka mid ah ayaa weli joogta, iyo ka hor intaysan caraftii laptop-ka shaqada cusubta ay meesha ka bixin, isticmaalaha wuxuu taagan yahay albaabka haremkiisa onlineka oo ugu jecelaayay. Faraxada dhacdada waxay maskaxdiisa ka daboolaa dareemanka oo xun, ma doonaayo inuu mar kale la qabatimo, laakin hal fiirin xanuun uma keeni lahayn...Aad iyo aad ayuu u daahay! Horey ayuuba la qabatimay mar kale. 

Damaca hore ee shaydaanka yar ayaa dib u bilaabanaaya, iyo xataa haddii uusan isla markiiba ula qabatimin, niyad-jabka oo horumarinta ka dib ayaa qabanaaya. Cajiib bay tahay ee in kasta oo ay balwadaha heroin-ka ay dambiileyaal sharci ahaan, jawaabta bulshada waa inay dad kuwaas caawiyaan. Aan u qaadano dabeecad isku mid ah isticmaalaha porn oo miskiinka ah. Ma sameynaya waayo uu rabo, oo laakin uu u maleeyo inay tahay inuu sidaas sameyan. Si ka duwan balwadaha heroin-ka, waxay caadi ahaan ka dhibaatoodaan sanado badan ee cadaab jireed iyo maskaxeed. Waxaan had iyo jeer dhahnaa inay geerida degdega ay ka fiican tahay mid oo tartiib ah, marka ha ka maseerin isticmaalaha porn oo miskeenka ah. ***Way u mudan yihiin naxariistaada.***