# Talooyin Ku oo Socota Akhristayaasha oo Porn Isticmaalin

## Caawi saaxiibadaada oo porn isticmaalaan inay buugaan akhriyaan

Kowdi, baro waxyaalaha oo buugaan ku jira ee isku day inaad is geliso booska isticmaalaha. Ha ku qasbin [isticmaalayaasha] inay buugaan akhriyaan adigoo u sheegaysa inay caafimaadkooda burburinayaan ama inay dab ku ciyaarayaan. Waxay sii adiga kaa fiican u og yihiin. Isticmaalayaasha ma sii wataan daawashada porn waayo ay ku raaxaystaan ama ay rabaan, waxay kaliya tan u sheegaan naftooda iyo dadka kale si ay u ilaaliyaan is-ixtiraamkooda. Waxay u sameyan waayo way ku tiirsan yihiin maadaama ay u maleeyaan inay raaxo, geesinimo, iyo kalsooni siiyso (raaxo ama taageero) iyo maadaama ay u dareemaan inay nolosha raaxaysan ahaan karin ‘galmada’ la’aanteed — ugu yaraantii nooca ay u galmada u maleeyaan. Haddii aad ku qasabto inuu isticmaale joojiyo, wuxuu u dareemi doonaa sida xaywaan wuxuuna haremkiisa si ka badan u rabi doonaa. Waxaa laga yaabaa inay isaga ka dhigto qof oo isticmaale qarsoodi ah pornkuna waxay sii ka qiimeysan ula noqonaysaa maskaxdooda. 

Taasi beddelkeeda, xooga saar dhinaca kale ee arrinta. Ka dhig inuu galo shirkadda isticmaalayaashii hore (blog-yada, forum-yada, YourBrainOnPorn, NoFap, iwm. ee laakin ka digtownoow ee doodidooda habka awooda rabitaanka). Ka dhig in [isticmaalyaashii hore] ay u sheegaan isticmaalaha sida ay iyaguna sidoo kale u malayeen inay ula qabatimeen inta noloshooda ka haray iyo sida ay nolosha aad uga fiican tahay markii la yahay qof oo isticmaale ahayn. Mar haddii aad ka dhigto inuu aamino inuu joojin karo, maskaxdiisa ayaa bilaabanaya inuu furmo. Markaas waxaad ka bilowdaa inaad u sharaxdo dhalanteedka oo laga abuuray xanuunada ka noqoshada. Ma aha kaliya in ‘daadshadaha dopamineka’ aysan isaga horumarin siinaynin, laakin waxay sidoo kale u burburinayaan kalsoonidiisa oo ay ka dhigayaan qof xanaaqsan oo daalan. 

Hadda waa inuu diyaar u noqdo inuu buugaan akhriyo naftigiisa, isagoo filayaa inuu akhrin doono boggag badan oo ku saabsan sheekooyin ee kacsi galmada oo aan la isku halayn karin, kacsi la’aanta oo porn keento, kacsi la’aanta, iwm. U sharax in habkaan uu gabi ahaanba ka duwan yahay iyo in tixraacyada xanuunada ay yihiin qayb oo aad ugu yar ee nuxurka.

Markii la gaabiyo, ha u ogolaanin inuu [buugaan] mugdiga ku dhinto. U sheeg saaxibadaada hana ka argagaxin. Haddii aad isku daydo inaad ‘guuleysato’ wadahadalka ama dooda, waxaad kaliya ku guuleysan doontaa inaad fogayso oo aad sii kordhiso cabsidiisa. 

## Ma u sheegaa lamaanahayga?

Ma u sheegaa xaaskayga, saaxiibaday, ama lamaanahayga balwaddayda? Ujeedada oo ah inay kugu caawiso joojinta. Waxaa jira arrimo badan oo halkaan ku lug leh. 

Haddii aad horeyba u guul darreysanaysay inaad joojiso, adigoo isticmaalayso habka awooda rabitaanka oo aad horeyba u sheegtay lamaanahaaga, u sheeg habkaaga cusubta ee u ogol inay naftooda bartaan ee akhrinta buugga. Waxay awoodi doonaan inay ku caawiyaan oo ku dhiirigaliyaan intaad ku jirta xiliga ka noqoshada waxayna yihiin dhufays markuu shaydaanka yar isku dayo inuu ku qaso. 

Haddii aad hadda iyo kow noqotay qof oo ka warqabsan jiritaanka dabinka porn oo aadan waqti hore isku dayin inaad joojiso, waa inaad kowdi EasyPeasy isticmaasho. Sida hore loo sharaxay, waa in tan ay noqonto waayo-aragtinimo oo raaxaysan. Sidaasba ha ahaatee, haddii aad u aragto wax adag, codso caawinaadooda. Noqo qof furfuran oo nugul markaad lamaanahaaga ula jirto waxayna xoojinaysaa xiriirkaaga. 

Ilaa iyo intaad ku raaxaysanaysa baxsashada oo aadan u arkaynin wax adag ee go’aan la’aanta darteed, ma jirto sabab oo aad lamaanahaaga ku ogaysiiyso. Haddii ayba [balwada] dhib ahayn waqti hore, ha dhimato. Si kastaba ha ahaatee, u diyaar garow in lammaanahaaga laga yaabo ay la yaabto sababta oo aad u eegayso, dareemayso, oo aad si fiican wax u qabanayso! 

## Lamaanahayga ayaa porn joojinooyo

Porn waa burburinaha qalloocan ee xiriiraha iyo in kasta oo joojinta porn la sameyn karo isla markiiba, boogsiinta waqti ay qaadanaysaa. Isticmaalayaal badan, oo ay ugu wacan tahay aaminsanaanaha caqli-galiga ahayn oo ka yimaadeen balwaddooda, waxay xanaaqooda saa lamaanahooda ama ay jecel yihiin. Dabeecadahaan waxaa lagu muujiyaa xad-gudub shucuureed, been-abuurta, iyo dabeecado wax-is-daba-mar ah. Tani ma aha isticmaalayaasha dhamaantooda, laakiin waxay ku sii badanaysaa marxaladaha dambe ee cudurka. In kasta oo dabeecadahaan laga yaabo in laga muujiyay balwada porn, waxaa muhiim ah inaad naftaada barto dabeecadahaan ee haddii aad naftaada ku garwaaqsato, aad tixgeliso inaad la kulanto daaweeya oo ku xirfadayasan balwadaha galmeeda. 

Haddii uu lamaanahaaga ku jira xiliga ka noqoshada, u qaado inuu ku dhiban yahay ee haddii uu yahay ama in kale. Ha isku dayin inaad yareeso adigoo u sheegayso inay fududahay in la joojiyo oo uu isaga kaligiisa joojin karo. Taasi beddelkeeda, sii wad inaad u sheegto sida aad ugu hanweyntahay, sida ka fiican uu u eg yahay, sida ka macaan ay tahay inaad la joogto iyo sida ka fudud uu yahay in lala joogto guud ahaan. Waxaa gaar ahaan muhiim ah inaad tani sii sameyso, waay markuu isticmaale isku dayga sameyo inuu joojiyo, faraxada isku dayga iyo amaanta uu dadkiisa ka helo ayaa caawin karo inuu sii socdo. Sidaasba ha ahaatee, wuxuu u janjeera inuu si dhakhso badan u hilmaamo, marka waa inaad amaanta soo socod siiyso. 

Maadaama uusan porn ka hadlaynin, waxaa laga yaabaa inaad u maleyso inuu hilmaamay oo uu rabin inaad xasuusisid. Caadi ahaan, lidkeeda ayaa arrinta ah ee habka awooda rabitaanka, maadaama uu isticmaalihii hore u waxba oo kale ku waalanin. Marka ha ka cabsanin inaad mawduuca mar kale keentid ee sii wadd inaad amaan siiysid (isaga ayaa kuu sheegaya haddii uusan rabin in la xasuusiyo). 

Ku dadaal si aad u nafiso culaysyada [nolosha] intuu ku jiro xiliga ka noqoshada, adigoo ka fikirayso habab oo aad noloshiisa ka dhigto mid xiiso badan oo raaxaysan. Tani waxay sidoo kale u noqon kartaa xili oo imtixaansan dadka oo istimaalayaasha ahayn oo weligooda balwada lahayn. Haddii xubin oo kooxda ka mid ah uu xanaaqsan yahay, wuxuu gabi ahaan keeni karaa darxumeysi. Markaa ka filo tan haddii uu isticmaalihii hore dareemaayo xanaaq, waxaa laga yaabaa inuu kugu keeno, laakin ha aargoosanin, waa waqtigaan waqtigii oo uu ugu badnaan u baahan yahay amaantaada iyo naxariistaada. Haddii aad adiga naftigaaga xanaaqsan tahay, taasi oo la fahmi karo, isku day inaadan tusinin.

Mid ka mid ah khiyaanada oo balwada ciyaaraya markuu isku dayaayo inuu joojiyo isagoo isticmaalaya habka awooda rabitaanka waa inuu dagaal galo, isagoo rajeenaya in lamaantiisa ama saaxibadiisa ay dhahaan, “*Uma adkeysan kari inaan ku arko adigoo sidaan oo kale u dhibaataysan. Ilaahi dartiisa, iska qaado suntaada.*” Sidaas darteed, ma ahaan doonto inuu isticmaalaha ceeb galo, maadaama uu ka ‘quusanin’, waa loo tilmaamay [inuu sameyo]. Haddii isticmaallihii hore uu sameyo qorshahan, ha dhiirigalinin inuu inay soo noqodaan (relapse). Taasi beddelkeeda, waa inaad dhahdo, “*Haddii tan ay tahay waxa oo porn kugu sameyso, Ilaahi mahdi inaad mar dhow xor ka noqonayso. Aad bay u fiican tahay inaad haysatay geesinimada inaad iska saarto!*”

Xusuusnow: waxaa jira laba kooxood oo boogsiinayaan inta lagu jira safarka soo kabashada. Markuu lamaanahaaga porn joojinaayo, waxaa muhiim ah inaad haysato xiriiryaasha taageerada, caadooyinka is-daryeelka, iyo xuduudaha. Habkaani ma dhaco hal habeen gudahiis, una baahan kalsooni, isgaarsiin, iyo isla xisaabtan. Jornaalista, horumarinta rabitaankaaga, iyo ugu muhiimsan, daawaynta, habkaan ayay caawiyaan. 

## Soo Noqoshada (Relapse) 

Jiritaanka qaybtaan waa inay digniin u noqota kuwa oo dabinka ka baxayaan. Shaqsi ahaan, weligayga [porn] uma soo noqonin, laakin waxaan isticmaali doonaa waayo-aragtinimaha oo waraysiyada xubnaha bulshada ka imaadeen iyo qalabka daaweynta dabeecadda garashada si aan u muujiyo. 

Marka hore, in 'soo noqoshada' lugu waco waa mid oo ujeedada ka soo horjeeda. Waxa kaliya oo dhan oo dhacay waa inaad simbiriiriixday oo aad shaydaanka yar quudisay, taasi oo sidaas darteed shaydaanka weyn kicisay. Isticmaalayaasha oo simbiriiriixaan (taasi oo ah qeexitaan ahaan: wax ka barashada khaladaadka) waxay caadi ahaan abuuraan tiro dhan ee aaminsanaan oo macquul ahayn:

  - “Weligaya xor ma noqon dooni” - **Buunbuuninta**
  - “Waa inaan jimicsado, wax barto, oo aan noqdo qof oo wax soo saar leh maalin kasta ee noloshayda.”
  - “Maanta PMO ayaan sameyay, marka maxaa faa’iidada akhrinta bugaagta iyo forumyada oo dhan. . . Ujeedadayda waxay ahayd inaanba siigaysashada sameynin, laakin waa kan — waxaan ahay qof oo guul dareystay — oo porn u soo noqonooyo.” **Dulqaadashada Niyad-Jabka Hoose**
  - “Saaxibadayda / akhristayaasha forumyada / dadka kale waxay joogayaan PMO la’aan ee (x) maalmood, laakin aniga ma sameyn kari marka xaaladayda waa mid oo rajo lahayn. Waxaan dareemay wanaag shalay maadaama aan si fiican wax u bartay, wax soo saarna waa lahaayay, laakin maanta ma sameynin. . .hoos ayaan u dhacooyaa.” — **Qiimeynta Nafta iyo Dadka Kale**
  - “Waa inaanan haysado fikradaha galmeed” - Naftooda, waalidiintooda, ama bulshadooda guud ahaan ayaa ku dhejiyeen **aaminsananta adkeysan** oo la xiriira galmada. Is weydii haddii is-calanqaadida ay kaa caawinayso inaad ujeedooyinkaaga gaarto, iyo haddii aad gaarooso, ma ku raaxaysanaysaa safarka?

Dhinacyada oo ka dambeeyaan maskax-xasashada isticmaale walba waxay u muuqdaan inay xadba lahayn. Adigaa is og si dadka kale oo dhan ka fiican, laakin [soo noqoshada] waxay si cad u tahay guul darada in tilmaamaha la raaco. Waxaad aragtay qiimo oo porn ku jira, laakin sidee?

Waxa oo inta badan la ilduufay waa inay waqti qaadanayso in dib loo rogo maskax-xadashada. Tan ma ka dhigayso wax oo ka adag badan [in la joojiyo], laakin ku dhawaad ​​warshad kasta waxay isticmaashaa galmo, iyo in maskax-xadashada laga hortaga waa hab oo miyir ah (ugu yaraan bilowga), marka waxaa laga yaabaa in waqti ay qaadan doonto in si buuxda loo xoojiyo casharada oo [maskaxda] ku jiraan. Sidaas darteed, akhrin badan [ee buugaan] ayaa lagula talinayaa (waxaad u boodi kartaa cutubyada oo adag kugu ah) mana aha inay waqti badan kugu qaadato.

Waayo-aragtinimada oo si yaab leh ugu caadi ah isticmaalayaasha oo diinta ah oo dabinka ka baxayaaan waa inay rabaan inay wax yar xanuunto, sida kafaargudid. Waxay joojinta fudud u arkaan, markaas waxay dareeman inay dembile yihiin inay sidaan u dareemaan. Laakin maxaad isku burburinaysaa oo adag ka dhigaysaa? Shaydaankii yar aad buu u qalloocan yahay arrintaan.

Naftaada ha la xiriirin shaydaanka yar - waa wax oo waqti hore warshadaha porn ku dareen. Ka fikir xoogsheegaha oo dagaal ku haysanaya garoonka ciyaaraha iskoolka. Maxaad u sheegtaa xoogsheegaha? Haddii aad tanaasusho, waad xoojinaysaa. Qaar oo joojiyaan waxay ugu dambeeyaan inay quudiyaan xoogsheegaha (macnaha: shaydaankii yar) oo ay markaas maskax-xadashadooda kordhiyaan, laakin fikradooda dabinka ma is-beddelin. Kor isku qaad, soo ogow meeshi oo aad khalad gashay ee xornimada ku raaxayso! 

Adiga damacaaga ma tihid. Digtoonaanta baaraandegidda waa dhaqanka u-fiirsashada fikradaha, waxaana jira cashara oo aasaasiga ah oo ku jiraan dabiiciga maskaxda oo la heli karo. Aad ayaa lagugu talinayaa inaad baaraandegid (meditation) sameyso guud ahaan, waxayna si buuxda ula soconaysaa dhaqanka diinta. Naftaada ma dagaali kartid, mana la dagaali kartid shaydaanka yar. 

Laakin guul darada maskaxdaada ka saar. Halkaan waa qayb oo ka mid ah “*Meditations of a Porn Addict*” ee Gulliaco (linkiga wuxuu ku jiraa qaybta kheyraadka ee dhamaadka buuga): 

>  Maadaama ay daawadshada porn waxba ku siinin, oo ay kaliya wax ku yeesha, oo ay si buuxda u qosol badan tahay in la rabo in wax oo sidaas oo kale la sameyo, waxaan u barbardhigaa cabitaanka warankiilada (biliijka). Waa kan: 
>
> **Safarka adag in aan biliijka la cabbin.**
>
> Halow! Waxaan nahay NoBleach waxaana marti gelinaa caqbadaha oo ka qaybgalayaasha (“Bleechstronauts”) ay muddo ka foogadaan cabitaanka biliijka. Haddii ujeedadaada ay tahay ka qaybqaadasho caadi ah ee caqabad bilood ah sida imtixaanka is-xakamaynta, ama haddii cabitaanka xad-dhaafsan ee biliijka ay dhibaato ku noqotay noloshaada oo aad rabto inaad muddo ka dheer joojiso, waxaad heli doontaa bulsho ku taageerta iyo kheyraado badan. 
>
> - “*Marmarkoo waxaan isku ogolaa inaan cabo hal koob biliij ama mid kale. Waan ogahay in ‘hal dhibac’ ay been tahay, laakin uma maleeynaayo in hal koob uu wax yeeli doono. Hal koob ma baabi’in karo saacadaha oo dhan oo aan joogay anigoosan cabaynin.*” 
> - “*Dhib kuma haysti joojinta cabitaanka biliijka, laakin mararka qaarkood waxaan arkaa qof oo biya koob ka cabaaya, waxaana ka fikiraa in koobka uu biliij ku jira. Markaas damac ayaan haystaa iyo, ka dib markaan isla doodo haddii aan cabaayo ama in kale, waxaan ugu dambeyntii ka tanaasulaa iyo koob ayaan cabaa.*”
> - “*Fiiri, dhibaatadayda waa in marmarkoo, markaan kaligayga jikada ku jira, waxaan bilaabaa inaan koobabka arko, naftayda ayaan tijaabiyaa mararka qaarkood anigoo furaaya weerka oo aan biliijka ku haayo, marmarkoo waan urinayaa ee. . .Hagaag, waxaan dib ugu laabtaa meeshi oo aan ka bilaabay. Waan quusanahay inaan waxaan joojiyo, laakin ma ogi haddii aan weligayga awoodi doono inaan joojiyo.*”
> - “*Joojinta cabitaanka biliijka waa wax oo suurtogal ahayn, yacni, had iyo jeer ayaan af qabaa, ma og tahay? Sidee u joojin karaa haddaan qabo dhuun oo iga xasuusinaysa inaan biliijka cabi karo?*” 
> - “*Nin yahow, si fiican ayay u soconaysay, 19 maalmood oo dhan anigoosan sameynin. Arrinta muhiimta ah waa in guul darrada laga barto! Hadda waan ogahay waxa oo aan iska ilaalinaayo inaan sameyo: fiiritaanka alaabta nadiifinta oo dukaanka weyn ku jiraan! Waxaan isku dayi doonaa inaan hal bil gaaro! Waxaan dib u habeyn doonaa tirintayda. Ii rajee nasiib!*”

> Haddii aad damac haysato, is deji nin yahow! Xasuuso wuxuu hackbuuga sheegaayo: 
>
> “*Way adagtahay in biliijka la iska joojiyo waayo cabsida in nalaga qaadayo raaxadeena ama taageerteena. Cabsida laga qabo in xaaladaha wanaagsaan oo gaarka ah aysan  dib isu ahaan doonin. Cabsida in lagaaga tagayo adigoosan la qabsan karin xaaladaha walbaarsan. Si kale haddii loo dhigo, waa saameynta maskax-xadashada oo nagu khiyaanaysa inaan aamino in gadashada - oo cabitaanka la socodo - ay tahay wax oo looga baahan bini’aadamaha dhamaantood. Xataa inta ka sii dheer, waa aaminsanaanta inay jiraan wax oo dabeecadda biliijka ku jira oo aan u baahanahay, iyo in, markii joojino isticmaalka, aan nafteena diidi doonno oo aan maran abuurayno. Tan maskaxdaada ku caddey: Biliijka maranka ma buuxiyo, mid ayuu abuuraa!*”
> 
> Aniguna waxaan dhahaa:
> “*Ka soo qaad inaad ku qasban tahay inaad fiirsato koob biliij shan daqiiqood. Isku day inaad xasuusato mid ka mid ah astaanta mise carafta oo aada uga jeclayd. Waxaa laga yaabaa in [xasuustaas] ay ia socoto nooc dhawaaq, ama aad kaliya xasuusato dhowr faafaahin. Biliijka way jirtaa mana xiri kartid indhahaaga ama aad madaxaaga ka jeediso maadaama ay biliijkaan maskaxdaada ku jirta, xasuusintiisa wuu kugu duuban yahay.*
>
> *Wax oo damac ah maad dareentaa? Wax maad carabkaaga ku dareemaysaa, mise isbeddelida neefsashadaada? Maxay dareemankaaga yihiin ee waxyaalaha oo aad xasuusanayso? Dareemankuwaas soo ogow, biliijka wuxuu rabaa inuu waxaas daboolow, oo uu wareer ka dhigo, oo uu kaa dhigo inaad kaliya u fiirsato waxyaalaha oo rabaan inay ku qabtaan.*”
>
> Marka loo fiiriyo [isbarbardhigga] oo kor ku xusan, iskuma dayo inaan iska tuuro dareenkaaga ama aan dhaho wax oo la mid ah, "haha waan caqli badanahay, waad doqon tahay", oo laakin aan kaliya ku siiyo aragti si aad u garwaaqsato sida ay u fududahay (oo ay weligeeda fududaanayso) inaad ka adkaato balwaddaan.
> Daawashada porn maaha beddelid oo daar/dami ah meesha oo aad dhahdo, “*Hagaag, waxaan ku jiraa xaalad, markaas ayaan porn daawanayaa.*” Khiyaali! Been badanaa! Meeqa jeer ayaad naftaada u ogolaataa inaad biliij cabto? Marna? Maxaa? Maadaama uu yahay wax oo aad u xun, taasi waa sababta! Sidee uga baxaysaa balwadaada haddii aadan garwaaqsanin in PMO ay wax oo aad u xun inaad naftaada ku sameyo?

## Ka Waran MO (siigaysashada iyo biya-baxa)?

Dadka waxay u siigaysanayeen muddo dheer iyadoosan jirin wax oo dhibaato ah. Si loo caddeeyo, ayaa porn dhibaatada ah. 

Iyadoo taasi la dhahay, ogow inaad weli MO ula qabatimi kartaa sababaha oo porn la mid ah, sida maskaxda ‘baahida in orgasm la haysto’,  degdeg u korida oo maskaxeed ah, ku qasabka inuu jirka galmo sameyo, iyo raaxo-raadinta. 

Waxay si xad-dhaafsan u badan tahay in porn iyo siigaysashada ay maskaxdaada gudahiisa isku xiran yihiin. Isticmaalayaasha intooda badan waxay arkaan inay [porn] ugu soo noqdaan ee natiijo ahaan ay ku siigaysteen khiyaaliyaal oo porn keeneen. Iyadoo maskaxdaada dib u habeeynayso, waxaad arkaysaa in maskax-xadashadaan ay ugu dambeyntii baaba'ayaan, waxaa ugu fiican inaad MO muddo ka nasato. Waa inaad sidoo kale raadiso galmo dhab ah si aad habka u dedejiso. 

Kan tilmaama ma aha, laakin iska qiimey: faa'iidooyinka oo laga sheegay xajinta shahwada way badan yihiin — xoogi saarada iyo tamarta oo korodhisan, ka saarida 'ceeryaamada maskaxda', iyo kalsooni kordhisan, oo la socoto faa’iido kale oo badan. Waayo-aragnimadayda shaqsi ahaaneed, waxaa jira farqi cad, wuxuu ku tiirsan yahay sida oo tamartaan kordhisan aad geliso. 

Waxaan qiyaasayaa, angioo lahayn aqoonta sayniska, in faa'iidooyinka loo aqoonsan karo dhowr arrimood oo kala duwan. 

- Orgasmka ka dib, maskaxda waxay soo daysaa prolactin, taasi oo xayirto soo daynta dopamine.

- In maskaxda loo diido daadashada dopamine waxay u ogolaanaysaa wax qaadasha oo badan adigoo kaliya nolosha ku nool. 

- Shahwada waxaa dib u loo soo celiya dhiigga ~78 maalmood ka dib, waxayna tahay mid ka mid ah nafaqooyinka ugu wanaagsan ee uu jirkaaga heli karo.

- In tamarta galmeeda la geliyo caadooyinka oo wax soo saar leh waxay la imaadaa lakabka dheeraadka oo wax soo saarid leh.

Waxaa laga yaabaa inaad sidoo kale u rabto inaay galmo sameyso iyadoo orgasm la'aan, taasi oo ah, sida hore loo sheegay, waayo-aragtinimo galmeed oo aad u fiican (oo badanaa lugu tixraacyo Karezza). Waxaad xoojin kartaa awoodaada inaad sidaan sameyso adigoo ku celcelinaysa jimicsiga kegal. Waayo-aragnimadayda shaqsi ahaaneed, habka ugu fudud oo uguna waxtarka badan oo lagu beegsanaayo muruqaan waa adigoo joojinaysa oo bilaabaysa socodka kaadidaada intaad kaadinayso (laakin ka digtoonow inaad si xad-dhaafsan u sameynin, taasi oo keeni karta dhibaatooyin kale iyada u gaar ah). Kala qaybinta dhinacaha tantric-ga iyo midda faafinta de galmada waxay tahay mid ka mid ah gunnada badan re ka baxsashada dabinka PMO (lamaanayaashayduna way jeclaayeen sidoo kale). 

##  Ka leexashada talooyinka caadiga ah

Qaybtaan way cusub tahay, waxayna si kistoo ka walwalsan u qoran tahay; laakin weliba, waa in la sheego. 

Dadka qaarkood oo EasyPeasy isticmaalayaan waxay arkaan in damacooda porn ay noqdo mid oo aad u yareysan, inay xataa isku keeni karin inay haystaan fadhiga oo ugu dambeeya. **Tani way fiicantahay** laakin ha ka dhayalasanin xooga inaad mid haysato. In si miyir leh u browse-gareeyso oo aad [maskaxdaada] ku xoojiso sida oo aad PMO u jeclayn waxay ahaan kartaa wax oo aad u xoog badan. Shakhsi ahaan, waxaan u arkay inay waxtar leedahay waana ka faraxsanahaayay inaan gacmahayga ka dhaqo, anigoo si daacad u nafisan inay weligeeda ahaanayso inaanan sameenaynin mar dambe. Sidaasba ha ahaatee, waxaa laga yaabaa in xaaladaada ay kala duwanaan karto. 

Haddii aad horeyba muddo uga xorowday dabinka oo aad maskax-xadashada iska saartay,  looma baahna in shaydaanka yar la quudiyo maadaama u kaliya ku dhibi lahaayay. Taasi beddelkeed xorninada ku raaxayso! 

## Caawi afjarida fadeexadaan

Porn waa mid ka mid ah khataraha bulshada xorta ah, iyadoo ka faa’iidaysanayso dadaalka daacadda ah ee u doodayaasha xorriyadda shaqsi ahaaneed. Hubaal, saldhigga ilbaxnimada - sababta uu bini’aadamka ilaa hadda u horumaray - waa inaan awood u leenahay inaan gudbino aqoonteena iyo waayo-aragtinimadeena, oo anaga kaliya u gudbinin, oo laakin sidoo kale jiilasha mustaqbalka ah. Xataa xoolaha ayaa u arkaan inay lagama maarmaan tahay inay faracooda ka ilaaliyaan dhibaatooyinka nolosha. 

Laakin soo saarayaasha porn si daacad uma sameynayaan, iyagoo aaminsan inay bini’aadamka caawinayaan, gaar ahaan hadda iyadoo balwada porn si weyn loo bartay. Waxaa laga yaabaa in maraxladaha koowaad ay dadka si daacad u aaminsanaayeen in porn ay dadka barto soo dhowaanshaha, laakin maamuulka [maanta] way og yihiin in taasi ay khalad tahay. Ma jiro mareeg porn oo wax daacad ka sheeganaayo waxbarashada. Waxa kaliya oo la sheeganaayo waa tayada naxtinta, cusaybta, iyo degdeg u korida nuxurkooda. 

Munaafaqnimada ba'an aad ayay u yaab badan tahay: bulsho ahaan, waxaan haddiisa kale ka xanaaqnaa cagajugleynta iskoolka iyo hoos-u-dhigida jirka bini’aadamka. Markii loo barbardhigo porn, dhibaatooyin kuwaas waxay la mid yihiin finan xun oo waxba ahayn. Tirada oo dadka la qabatimeen waxay gaaraan meel oo ka sareysan sannad kasta, iyagoo [balwadaha] waqti ku qaataan dad oo khiyaali ah iyagoo huridayaan caafimaadkooda, ragnimadooda, iyo waqtigooda. Ilaa hadda waxay tahay dilaaga xiriirka ugu weyn, iyo boqolaal oo kumanaan nolol ayaa burburaan sannad kasta maadaama ay ula qabatimaan. Soo saarayaasha porn kuma xayeysiiyaan daabacadaha caadiga ah — uma baahna inay sidaas sameyaan, damaca nafleydeena ayaa nugu horseedinaysa agaarka haremkooda oo ay si fiican u buuxiyeen, iyagoo bixinayaan muunado lacag la’aan sida ka ganacsada daroogada. Maalmahaan, mareegaha waxyaalahooda ma buuxiyaan inta ay booqadayaasha ku dhiirigalinayaan inay waxyaalaha dhejiyaan.

Sidee xariif ah in shirkadaha porn ay muujiyaan digniinaha *18+* sida ka hortag ahaan ee isticmaalayaasha oo aan qaan-gaarin, in kasta oo ay qaarkooda xataa isku dhibin inay sidaas sameyaan. Porn waxay saamaysaa qof kasta ee da 'kasta. "*Waan kaaga dignay khatarta, markaa waa doorashadaada,*" ayaa ah dabeecadooda. Ma qaataan wax oo tallaabo ah si ay da’daada u xaqiijiyaan? Maya, taasi waxay niyad jebinaysaa macaamiishooda. Dabcan, haddii xaqiijinta da'da la sharciyeeyo, waxay raadinayaan waddan kale oo ay ka shaqeeyaan. Mise, amay laaluush siin doonaan nooc oo 'maamuul' ah si ay wax uga qoraan sida mamnuucidda u keentay qaybinta [porn oo] sharci-darrada ah iyo abuurista Maafiayada? Shayga si ku habboon loo hilmaamo waa su'aasha ee sababta burinta mamnuucida [khamriga] aysan u keenin dhimista dhaawacyada oo khamriga lugu xiri karo, iyo [dhimista] guul darada dhaqangelinta sharciga inay xakamaan kordhista Maafiyada? 

Taas si ka duwan ayaan wax uga qaban karnaa anagoo barayna jiilka oo soo korayaan. Haddii ay iska ilaalin karaan sigaarka iyo khamriga markay wax iibsanayaan, waxay sidaas oo kale u sameyn karaan porn. Waxaan horeyba u arkoonaa isbedelid bulsheed sida ‘No Nut November’ iyo ‘Coomer’ oo caadi noqonayaan. Isticmaalaha [porn] ma haysto doorashada oo ka badan markii loo fiiriyo balwadda heroin-ka. Isticmaalayaasha ma go'aansadaan inay la qabatimaan, waxay ku soo jiitaan dabin qarsoodisan. Haddii ay go’aanta haysan lahaayeen, isticmaalayaasha kaliya oo berrito subaxdeed jiri lahaayeen waa dhalinyarada oo hadda iyo kow bilaabayaan, iyagoo aaminsan inay joojin karaan mar kasta haddii ay rabaan. 

Maxaa loo haysanayaa heerarka oo nacasnimada ah? Maxay balwadaha heroin-ka oo loo arko inay dembiile yihiin, ay weli isdiiwaangelin karaan inay balwad leeyihiin oo ay heli karaan methadone iyo daaweynta caafimaadka si caawinaad ahaan inay balwada iska saaraan? Isku day inaad isdiiwaangeliso sida balwad porn lee — haddii aad dhakhtarkaaga u tagto si aad caawinaad u hesho, wuxuu kuu sheegaa: “*Jooji inaad aad u badan u sameyso, isku day dhexdhexaadinta,*” taasi oo aad ogtahay inay shaqaynaynin, ama wuxuu kuu qoraa daaweyn si uu wax kaaga qabto ‘niyad-jabkaaga’. Waxaa ka sii daran talada inaad baxdo oo aad lamaanayaal oo dhab ah soo raadsato — dhab ahaantii? Maxaa, weligooda may ka maqlin isticmaalayaasha oo u arkaan in porn ay ka fiican tahay oo lamaanahooda gadaashooda ka sameyaan? Dadka qaarkooda maba fahmayaan.

Ololayaasha oo cabsida leh ma ka caawiyaan isticmaalayaasha inay joojiyaan, adag bay ka dhigaan. Waxa kaliya oo ay sameyaan waa inay isticmaalyaasha ka nixiyaan, taasi oo iyaga ka dhigaysa inay sii ka badan u rabaan inay daawadaan. Mana ka hortagaan inay dhalinyarada la qabatimin. Dhalinyarada way og yihiin in porn ay tamartooda galmada disho, laakin waxay sidoo kale og yihiin in hal fiirin ay sidaas sameyn doonin. Maadaama ay balwada aad u baahsan tahay, mar dhow ama hadhowtii dhalinyarka — midba cadaadiska bulshada ama xiisaha — wuxuu tijaabin doonaa hal booqasho. Maadaama ay porn qabto muuqaala xun oo lacag la’aan ah, waxay u badataa inuu dhalinyarka la qabatimi doono. 

Maxaan u ogolnaa inay fadeexadaan sii socoto? Maxaysan dawladaha ula soo baxaynin ololal oo habboon ah? Maxaan noola soo sheegi waay in porn daroogo oo dilaa ah ay tahay, oo ay kaa caawinin nasashada oo ay kalsooni ku siinaynin, oo laakin ay neerfahaaga burburiso, oo ay qaadanayso hal fiirin in lala qabatimo? Maxay u fulin waayeen xaqiijinta da'da iyagoo codsanayaan kaararka deynta oo diiwaangashan, laga yaabee ay xataa la jiraan qolo saddexaad? MindGeek, milkiilaha mareegaha badan ee porn oo waaweyn, ayaa isku dayaya inay dawladaha khiyaameeyaan si ay u isticmaalaan xalkooda xaqiijinta da'da — ha u ogolaanin inay sidaas sameyaan! Buuga *The Time Machine* ee H.G. Wells ayaa qeexaayaa xaalad ee uu nin webi ku dhex dhacay. Saaxibadiisuna waxay fadhiyaan agaarka geeska webiga iyagoo la mid ah lo’ oo waxba ka ogayn qaaylada [ninka] oo quusta ah. Way naxariis la’aan tahay wayna argagax badan tahay, iyadoo aad ula mid ah dareen la’aanta guud ahaan oo bulshada ee dhibaatada porn. 

Laakin waxaa jirta dabayl isbeddeleed oo bulshada ku jira. Kubadda barafka ayaa bilaabay inay hoos u soo rogto buurta waxaana la rajaynayaa in buugaani uu ka caawin doono inuu u beddelo baraf oo aad u weyn. Adiguna waxaad caawin kartaa markaad faariinta faafinayso. 

Sidaan: Haddii aad aragto qof oo ku dhibaataysan isagoo isticmaalaya awooda rabitaan, ama oo isku dayaya inuu porn joojiyo, si naxariis leh ugu tilmaan jihada habkaan. Sidaasba ha ahaadee, hawsha dhabta ah waa in la beddelo sheekada oo porn ku xeeran guud ahaan. Fadlan ka fiirso inaad caado ka dhigato in haddii aad onlineka ku aragto ama xataa la kulanto porn oo la caadiyaynaya, aad isku daydo inaad *si xushmad leh* wax u barto oo aad xorayso.

Marmar, waxaa laga yaabaa inaad hesho falcelin taban, laakin mararka qaarkood, faallo ayaa ah waxa loo baahan yahay oo dhan. Sida dadka badan oo hortaada sameyeen, waxaad filan kartaa inaad hesho fariimo oo ka imaanaya dad mahadsan oo kaaga mahadcelinaya xorriyaddooda. 

## Digniinta ugu Dambeeysa 

Waxaad hadda ku raaxysan kartaa, inta noloshaada ka haray, adigoo ah qof faraxsan oo isticmaale ahayn. Si aad u hubiso inaad sameyso, waxaad u baahan tahay inaad raacdo tilmaamahaan oo fudud.

1.  Ku hayso bogga soo socda bookmarks-kaaga ee tixraac inta aad u baahan tahay.

2.  Haddii aad weligaaga bilowdo inaad ka maseerto isticmaale kale, ogow inay iyaga adiga kaa maseeri doonaan. Adiga ma aha qofka oo wax laga qaadaaya. Waa iyaga.

3.  Xasuusnow inaadan jeclayn ahaanshaha isticmaale. Taas waa sababta oo aad u joojisay. Waxaad jeceshahay ahaanshaha qof oo isticmaale ahayn.

4.  Xasuusnow inaysan jirin wax oo la dhoho hal fiirin kaliya.

5.  Weligaaga ha ka shakinin go’aantaada inaadan weligaaga porn daawanaynin mar dambe. Waad ogtahay inay tahay midda saxda ah.

6.  Haddii ay jiraan wax dhibaato ah, raadso ee la xiriir daaweeyaha oo aqoonta u leh balwadda porn. Liisaskaas waxaad ka heli kartaa online.
