# Tilmaamaha

1.  Tilmaamaha oo dhan raac.

2.  Maskax furan hayso.

3.  Ka bilow dareen farxadeed.

4.  Iska dhega tir talooyinka iyo saameynta dhan oo EasyPeasy khilaafayaan.

5.  Iska caabbi ballan kasta oo xalin ku meel gaar ah. 

6.  Maskaxdaada ku caddey: porn kuma siisa raaxo ama taageero oo dhab ah, hurridna ma sameynoosid. Ma jira wax oo la tanaasulaaya, mana jira sabab oo aad u dareento in wax lagaa qaaday.

7.  Ha sugin inaad joojiso, hadaba samey!

8.  Go'aanso inaadan mar dambe daawanin iyo weligaaga su'aal ha ka keenin.

9.  Xasuusnow inaysan jirin wax oo la dhoho hal fiirin kaliya.

10. Weligaaga porn ha daawanin mar dambe.

## Is-Xaqiijinta

-   Xor ayaan ka ahay addoonsiga porn.

-   Way fududahay inaan iska dhega tiro fikradahayga porn.

-   Nabad gelyo fikradayda, nabad gelyo damacayadayda. Alla, damacayadayda way baxeen! 

-   Waxaan maskaxdayga oo miyir-daboolanka xoogi saaraa inay balwada porn ka adkaada.

-   Porn waxay iga xaddaa waqtigayga, tamartayda, iyo ragnimadayda.

-   In porn laga adkaado waxay si baaxad leh ugu fudud noqotaa maalin walba iyo dhinac walba.

-   Waan ku raaxaystaa iyo waan qiimeeyaa qaab nololeedkayga oo xooga, faraxsan, oo khafiif iyo fudud ah oo porn ka xor ah.

-   Haddii aan dib u fiiriyo oo aan ka fikiro horumarkayga, wuxuu i siinayaa faraxd weyn iyo kalsooni ee naftayda. 

-   Mar kasta oo aan arko isticmaalayaal porn oo kale, way i dhiirigalisaa inaan is arko anigoo meertadaas jebiyo.

-   Tamartaas oo dhan oo la soo ururiyey waxay bogsiinaysaa jirkayga iyo maskaxdayda. Markaas, waxaan samayn karaa shaqo wax soo saar badan oo adag oo ai aan u gaaro qiyamkayga iyo ujeedadayda.

-   Maskaxdayda waxay ku soo noqonaysaa qaabka saxda ah, anigoo u jimicinaya oo **aan** sameynoonin wixii oo an awal sameynaayay.

-   Hadda tamartaas oo dhan oo la soo ururiyey waxaa loo isticmaalooyaa in la xamilo walbahaarada yaryarta iyo cadaadiska nolosha. 

-   Wacan, xor baan ahay iyo mar dambe addoon ma ihi!
